### ISSUE TITLE
gobuilder zip shouldnt have the dist/ folder

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1006]
currently the gobuilder zip looks like this:

![](https://camo.githubusercontent.com/d5cc0e516564e8b22fef07124401dbaec2f352b9/68747470733a2f2f7777772e657665726e6f74652e636f6d2f73686172642f733139382f73682f66316261303663332d353531632d343336652d623337342d3865303330353864663666302f32363430316436663164383530343165393136373930333839326566623537322f646565702f302f697066732d332e706e67)

need https://github.com/Luzifer/gobuilder/issues/13

**Comment by whyrusleeping** [comment]
i think this has been solved
