### ISSUE TITLE
Pinning fail bug

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1008]
Found a bug. 

- I pinned a hash: 

```
# i pinned a hash
> ipfs pin add -r <hash>

# pinning failed (context deadline exceeded)

# it ran it again
> ipfs pin add -r <hash>
pinned <hash> recursively
# succeeded immediately

# ran refs just to check
> ipfs refs -r <hash>
<hash1>
<hash2>
<hash3>
<hash4>
<hash5>

# then it got stuck, in the usual "i dont have a ref yet, am fetching it" kind of way
# and proceeded to download more.
```
**THE POINT though, is that `ipfs pin add -r <hash>` _succeeded_ without all the refs being local**

---

Suggested fix: when adding a recursive pin _must_ check all the refs are there locally. May not need to check the refs themselves, but at least check the object is stored in the repo.

**Comment by hosh** [comment]
I ran into that, but thought that was normal

**Comment by whyrusleeping** [comment]
makes sense, ill fix it
