### ISSUE TITLE
API_ORIGIN doesn't work

### ISSUE THREAD

**Issue by NodeGuy** [ipfs/go-ipfs#1017]
I set the `API_ORIGIN` environment variable to `*` to allow API access from the browser.  I see the following line in the debug log:

`16:54:43.529  INFO commands/h: Allowing API requests from origin: * handler.go:44`

but the HTTP response doesn't include the `Access-Control-Allow-Origin` header as expected.

**Comment by jbenet** [comment]
Interesting. may be worth git blame-ing the gateway files.

cc @mappum @cryptix

**Comment by NodeGuy** [comment]
I'll fix this.
