### ISSUE TITLE
Config file needs documentation

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/go-ipfs#1018]
When upgrading, I've noticed that any new settings don't get automatically added to the config. This is a bit of a problem when I want to play with the latest features without doing an ipfs init. Can we get some documentation on the config file?

**Comment by jbenet** [comment]
Oooof that sucks, not sure how that started to happen. Yeah we should do that.

**Comment by rht** [comment]
Linking the issue node #1375

**Comment by yangwao** [comment]
is documentation somewhere?

**Comment by RichardLitt** [comment]
Not that I know of.
