### ISSUE TITLE
No API to know if server is shutting down

### ISSUE THREAD

**Issue by torarnv** [ipfs/go-ipfs#1023]
Results in https://github.com/ipfs/webui/issues/28

**Comment by whyrusleeping** [comment]
Well, we do have a way of knowing if the server is shutting down, the master context will signal everyone who has registered to know. The issue here is that braintree/manners doesnt respect contexts.

**Comment by Stebalien** [comment]
Go-ipfs will now _immediately_ stop listening on the API when shutting down. I'd say that's a pretty decent signal.
