### ISSUE TITLE
strange issues after closing laptop for an extended period of time

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1025]
I had a daemon running on my laptop last night, and closed my laptop before going to bed. When I woke up in the morning, the daemon was acting strangely, and doing simple things would hang (especially when I didnt expect them to), such as: `ipfs dht findprovs -v <some hash>` would print out nothing, not even than its making requests from nodes.

**Comment by jbenet** [comment]
interesting. being able to repro will help us fix things

**Comment by Stebalien** [comment]
Hypothesis: You were spamming out reprovide records and your `ipfs dht findprovs -v` command was stuck at the back of the queue.

**Comment by Stebalien** [comment]
(too old to debug)
