### ISSUE TITLE
Remove all CtxCloser, ContextGroup in favor of goprocess

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1030]
the codeabse is littered with the previous iterations. at this point goprocess appears to be robust (the only large problems in a long time have been in goprocess/limited)

**Comment by rht** [comment]
@jbenet What is the built-in (idiomatic) way for a goprocess.Process to return its parent or children Process? For the latter this can be done in ContextGroup with ```p.Children()```.
From the test file https://github.com/jbenet/goprocess/blob/ea63e9540cd19cb39e0e4c4442b9c27664287bb8/goprocess_test.go it looks like there needs to be a tree struct?

**Comment by jbenet** [comment]
> What is the built-in (idiomatic) way for a goprocess.Process to return its parent or children Process?

I haven't needed something like this yet.  (`net/context.Context` doesn't either) What's the use case?

**Comment by rht** [comment]
e.g. https://github.com/ipfs/go-ipfs/blob/7fbfecf6fab5920317de2e999e96d3fd145bcecf/routing/dht/providers.go#L58

**Comment by jbenet** [comment]
don't need it.

the construction:
```go
pm.Children().Add(1)
go func {
  pm.Children().Done()
}()
```

becomes simply
```go
proc.Go(func {})
```

**Comment by rht** [comment]
Ok what about SetTeardown https://github.com/ipfs/go-ipfs/blob/master/core/core.go#L137? And WithContextAndTeardown https://github.com/ipfs/go-ipfs/blob/master/routing/dht/dht.go#L74 (this is unneeded with SetTeardown interface is available, however)?

**Comment by jbenet** [comment]
there's `WithTeardown` but no `SetTeardown` yet. could make it.
