### ISSUE TITLE
Make all jenkins tests work on travis

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1033]
We need to make all the jenkins tests (https://build.protocol-dev.com/) run on travis.

This should be possible now. the doubtful ones are those that require docker.

ipfs/infrastructure#9

**Comment by diasdavid** [comment]
Just missing the docker tests //cc @whyrusleeping

**Comment by whyrusleeping** [comment]
Closing. We're actually moving back to jenkins.

![image](https://cloud.githubusercontent.com/assets/1243164/23643554/66253b46-02b7-11e7-8ebd-7be5c3065526.png)

**Comment by lgierth** [comment]
:D
