### ISSUE TITLE
ipfs stats bw accuracy or purpose

### ISSUE THREAD

**Issue by rubiojr** [ipfs/go-ipfs#1040]
I was streaming a large file and I realized that `ipfs stats bw -poll` output doesn't match what raw iface stats (via `bwm-ng`) and the other peer is getting.

Here's what `bwm-ng` is reporting (eth0 is the interesting interface):

![screen shot 2015-04-08 at 2 12 06 pm](https://cloud.githubusercontent.com/assets/10998/7045002/a6e1cefe-ddf9-11e4-8a80-9a3879fb67d7.png)

Here's what `ipfs stats bw` is reporting:

![screen shot 2015-04-08 at 2 12 15 pm](https://cloud.githubusercontent.com/assets/10998/7045004/afaabd7a-ddf9-11e4-8520-ab205b2c4446.png)

The person I'm streaming the file to is reporting ~450 KiB too.

Should `ipfs stats bw` account for that?

**Comment by jbenet** [comment]
There's significant TCP + IP framing, though 1MB may be too much... We unfortunately don't control that so our current accounting doesn't cover it. We could try to estimate it but wouldn't be right... maybe we should just be polling the way some of these other tools do it, so we get full stats from the kernel.

cc @whyrusleeping

**Comment by whyrusleeping** [comment]
@rubiojr Yeah, I couldnt figure out what the discrepancy was being caused by. We are listing all bytes going over our peers `net.Conn`s...  But one thing to note is that `ipfs stats bw` outputs in bytes per second, where most network tools output in bits per second. 56KB/s * 8 = 448. which looks about right for what youre reporting.

**Comment by rubiojr** [comment]
@whyrusleeping @jbenet  so what I was trying to say is that the person downloading from me was getting ~450 Kilobytes/s (3.6 Megabits/s) while `ipfs stats bw` was reporting 56 KB (448 Kb/s as you said). Right? It seems to me that the numbers don't add up (or it's just measuring protocol data transfer and not the bulk file transfer).

The interface reports 5.3 Mb/s but the peer was downloading using wget from an external ipfs gateway while I was streaming the file from my laptop realtime so I guess the overhead seen in the interface could be explained (I don't know enough about ipfs to say unfortunately).

Maybe I was measuring it wrong but it should be easy to double check.

**Comment by jbenet** [comment]
i think our bw reporting is definitely off -- given ip + tcp framing. (i believe we do catch the streaming + encryption (HMAC) overheads, but still). What you suggest though implies to me there's more missing.

I think we should explore the kernel based monitoring i mentioned above for _totals_. We could rename what we currently call _total_ into _protocol total_, or something.

**Comment by cryptix** [comment]
> I think we should explore the kernel based monitoring i mentioned above for totals. We could rename what we currently call total into protocol total, or something.

Do OS/Kernel APIs allow for filtering by process?
Otherwise you just bundle an iftop like tool without much gain..

**Comment by rubiojr** [comment]
Perhaps using pcap like [nethogs](http://nethogs.sourceforge.net/)?. That will require root though (or maybe [CAP_NET_RAW+CAP_NET_ADMIN](http://seclists.org/tcpdump/2011/q1/58). Or just use something like `nethogs` :)

**Comment by Kubuxu** [comment]
I used nethogs and it is off by factor of 8 and more.
![](https://cloud.githubusercontent.com/assets/2259282/12808730/73742040-cb19-11e5-8b87-613c47da0a71.png)

I am sure that `nethogs` shows KiloBytes per second.

**Comment by Stebalien** [comment]
At the time this issue was filed, the bandwidth stats collection system miscalculated bandwidth by a factor of 5(?). We still have overhead but *that* issue has since been fixed.
