### ISSUE TITLE
deamon: slice bounds out of range

### ISSUE THREAD

**Issue by tstorch** [ipfs/go-ipfs#1043]
On Linux I tried to terminate the daemon with Ctrl-C. [This](http://pastebin.com/XHfhQn7q) ist what I got.

Since I have not clue about this project I can't give any further initial information. Just Thought I would leave this here.

**Comment by whyrusleeping** [comment]
thats strange, this is the second time ive seen this in less than a day. must have been introduced recently. Thanks for reporting!

**Comment by torarnv** [comment]
I've been seeing this on and off while working on the shutdown stuff as well (before my changes :smile:)

**Comment by jbenet** [comment]
Did you have it mounted? 



—

**Comment by tstorch** [comment]
Can't say it for sure, but I'm pretty sure it was.

**Comment by jbenet** [comment]
wonder if leveldb is closing before the query finishes

**Comment by whyrusleeping** [comment]
@jbenet that would be my guess... any way to tell? like, leveldb.IsClosed()?

It would be super cool if it didnt panic and just returned an `ErrClosed` instead

**Comment by whyrusleeping** [comment]
just encountered this myself.

**Comment by whyrusleeping** [comment]
pretty sure this has been fixed, reopen as needed
