### ISSUE TITLE
put `docker run`... command in the README

### ISSUE THREAD

**Issue by mlovci** [ipfs/go-ipfs#1052]
so you don't have to go to the Dockerfile on hub.docker.com to know how to start it.

`docker run -p 8080:8080 -p 4001:4001 -p 5001:5001 go-ipfs:latest`

**Comment by jbenet** [comment]
@mlovci :+1: -- mind making a PR?

**Comment by mlovci** [comment]
no problem, wait a tic

**Comment by mlovci** [comment]
@jbenet  ... Just making sure I'm not crazy. Docker can't interact with the host's files unless they're mounted inside the container, right?

Thus, I'm going to suggest that the command be:

`docker run -p 8080:8080 -p 4001:4001 -p 5001:5001 -v /somewhere/you/care/about:/export jbenet/go-ipfs:latest` 

and instruct users to put files they care about in `/somewhere/you/care/about`

**Comment by jbenet** [comment]
@mlovci yeah, though ipfs doesn't need anything mounted. The one thing users may do is mount a location to put the repo in, setting the IPFS_PATH to that.

**Comment by mlovci** [comment]
hold on... explicate... yo no entendo.

`docker exec <ipfs_container> add <a file>`
certainly needs the directory where `<a file>` exists mounted inside the container, right?

What does IPFS_PATH refer to? `~/.go-ipfs` in the container?

**Comment by jbenet** [comment]
> `docker exec <ipfs_container> add <a file>`
> certainly needs the directory where `<a file>` exists mounted inside the container, right? 

ahh, certainly true. was thinking about it as just exposing the API or Gateway. (if you run ipfs as a daemon, you can expose the api, and use that. we haven't made the cli be smart enough to use it nicely it's super hacky to do this atm, cause have to trick the cli outside the container to talk to a node inside the container. easier then with a mounted repo.)

> What does `IPFS_PATH` refer to? `~/.go-ipfs` in the container?

Right. `IPFS_PATH` defaults to `~/.go-ipfs`

> sorry if these are dumb questions.

not at all, we haven't doc-ed enough.

**Comment by mlovci** [comment]
This is staying open until at least Monday. I'm having problems making this work on my macbook and I can't VPN to my ubuntu workstation where it works.

**Comment by jbenet** [comment]
@mlovci 
- if you're running osx in the macbook, it's because docker is inside the boot2docker vm?
- if you're running linux / container, maybe its not resolving ~/ to root? there was an issue about that i think

**Comment by mlovci** [comment]
if you're running osx in the macbook, it's because docker is inside the boot2docker vm?

Correct, `boot2docker ssh -L 5001:localhost:5001 -L 4001:localhost:4001 -L 8080:localhost:8080 -fN` fixes docker issues. I'll add this to the instructions, unless there's a better way?

**Comment by mlovci** [comment]
#1067

**Comment by mlovci** [comment]
#1067 #1068
