### ISSUE TITLE
 [minor] "~/.go-ipfs/daemon.lock" already locked

### ISSUE THREAD

**Issue by okket** [ipfs/go-ipfs#1053]
Currently, when stopping a running command like ```ipfs ping``` with ```Ctrl-C``` the client tries to open the repository on close, resulting in the confusing, bogus message:

```shell
ERROR   cmd/ipfs: file "~/.go-ipfs/daemon.lock" already locked <autogenerated>:24
Received interrupt signal, shutting down...
```
This does not cause any issues other than giving ```ipfs``` a bad UX rep ;)

**Comment by whyrusleeping** [comment]
fixed!

**Comment by jbenet** [comment]
thanks @okket -- these sorts of things are really important. our UX should be _great_.
