### ISSUE TITLE
`ipfs cat <hash>` needs a good error message

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1060]
```
> ipfs cat Qmaa4Rw81a3a1VEx4LxB7HADUAXvZFhCoRdBzsMZyZmqHD
Error: Lock Create of foo/daemon.lock (abs: /Users/jbenet/.go-ipfs) failed: open .go-ipfs/daemon.lock: no such file or directory
```

unhelpful error message. should be:

```
> ipfs cat Qmaa4Rw81a3a1VEx4LxB7HADUAXvZFhCoRdBzsMZyZmqHD
Error: no repository found at /Users/jbenet/.go-ipfs
Did you run `ipfs init` ?
```
This error message used to be correct, i believe. in any case, it's an error that tons of people are bound to hit. Maybe this is a case where we _should_ have error message tests. 

cc @whyrusleeping @chriscool

**Comment by chriscool** [comment]
Ok, yeah you are right that it is perhaps better to check the error message then.

**Comment by whyrusleeping** [comment]
Yeah, every bit of the UX should be tested

**Comment by whyrusleeping** [comment]
this has been resolved
