### ISSUE TITLE
Addition of --local flag to [ cat, ls, refs, ... ]

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1075]
It would be nice if we had a `--local` flag that could make `ipfs [ cat, ls, refs, ... ]` return only local objects. This would be good for online tests, and so on.

**Comment by whyrusleeping** [comment]
:+1: I too want this.

**Comment by ForrestWeston** [comment]
@jbenet @whyrusleeping Should the `--local` flag be available on all commands, or is there a specific subset?

**Comment by whyrusleeping** [comment]
hmmmm... we could set it up so that the local flag gets parsed before the `Run` command even starts running, by swapping out the constructNode function with one that builds an 'offline' node. Although i'm not sure what implications that might have. Goin 3 for 3 on this one? That help wanted label seems to be paying off

**Comment by jbenet** [comment]
> hmmmm... we could set it up so that the local flag gets parsed before the Run command even starts running, by swapping out the constructNode function with one that builds an 'offline' node. Although i'm not sure what implications that might have. 

wait, why? why not just a global flag (on the `ipfs` root command)?

we still want this to run on the deamon if it's there.

**Comment by jbenet** [comment]
> Should the `--local` flag be available on all commands, or is there a specific subset?

so far, i think there should be a subset. because it cannot apply to all commands, like, what would these mean?

```
ipfs id --local
ipfs swarm peers --local
ipfs version --local
```

**Comment by whyrusleeping** [comment]
> wait, why? why not just a global flag (on the ipfs root command)? (though i dont think it's needed here)

there is actually already a global `--local` flag that doesnt do anything, thats the one i'm referring to. I'm just saying we could parse it out and handle it before the `Run` function on the command gets invoked.

>we still want this to run on the deamon if it's there.

Yeah, thats still possible.

**Comment by jbenet** [comment]
> there is actually already a global --local flag that doesnt do anything, thats the one i'm referring to. I'm just saying we could parse it out and handle it before the Run function on the command gets invoked.

sure but _why_. why do you propose to do this?

why is the global flag there, if not for this? why not just use it as usual?

**Comment by Stebalien** [comment]
This has been implemented as `--offline`.
