### ISSUE TITLE
Can't pass options to "ipfs mount"

### ISSUE THREAD

**Issue by zorun** [ipfs/go-ipfs#1077]
Passing options to `ipfs mount` does not work:

    $ ipfs mount -n /tmp/ipns -f /tmp/ipfs
    Error: Expected 0 arguments, got 2
    Use 'ipfs mount --help' for information about this command

This is despite the command advertising support for the options:

    $ ipfs mount --help
    
        ipfs mount - Mounts IPFS to the filesystem (read-only)
    
    OPTIONS:
    
        -f string - The path where IPFS should be mounted
        -n string - The path where IPNS should be mounted

**Comment by jbenet** [comment]
@zorun did you try:

```
ipfs mount -n=/tmp/ipns -f=/tmp/ipfs
```

note the equals. these are required for now. https://github.com/ipfs/go-ipfs/issues/1078

**Comment by zorun** [comment]
Ah, right, thanks!
