### ISSUE TITLE
commands flag: stop requiring `=`

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1078]
Currently our commands lib requires `=` between flag names and values:

```
ipfs cmd -f=value
ipfs cmd --flag=value
```

This was a bad idea. It should be possible to:

```
ipfs cmd -f value
ipfs cmd --flag value
```

**Comment by whyrusleeping** [comment]
relevant function for anyone who wants to hack on this: https://github.com/ipfs/go-ipfs/blob/master/commands/cli/parse.go#L105

**Comment by AtnNn** [comment]
I am working on a fix in https://github.com/AtnNn/go-ipfs/commit/0dcf1ac603d669fd33df9bbedafc84dcde07f378
