### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by cryptix** [ipfs/go-ipfs#1084]
[/ipfs/QmbHsSrezmhSpxJ1pJj1UsW39AxeXNAXQ9jQwZnUYw8ewR](http://gateway.ipfs.io/ipfs/QmbHsSrezmhSpxJ1pJj1UsW39AxeXNAXQ9jQwZnUYw8ewR) [gist mirror](https://gist.github.com/cryptix/48e350e23663233cc81c)

**Comment by jbenet** [comment]
hmmm odd

**Comment by jbenet** [comment]
@whyrusleeping thoughts?

**Comment by whyrusleeping** [comment]
has been fixed since
