### ISSUE TITLE
IPFS daemon doesn't unmount when killed

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/go-ipfs#1092]
Run `ipfs daemon --mount`, let it initialize and then kill it. Note how the mounted directories aren't unmounted. 

Hopefully this is getting fixed in https://github.com/ipfs/go-ipfs/pull/1037

**Comment by torarnv** [comment]
Yes, the revert of f74e71f in #1037 should fix this, I'm seeing the directories unmounted cleanly here.

**Comment by dylanPowers** [comment]
:+1:

**Comment by jbenet** [comment]
i think this should be fixed now?

**Comment by jbenet** [comment]
@dylanPowers could you try to repro with new master?

**Comment by dylanPowers** [comment]
Verified resolved
