### ISSUE TITLE
DNS "server misbehaving"

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/go-ipfs#1094]
I've found when doing a large quantity of ipns requests, a request that should resolve can sometimes not resolve with the error:
"Path Resolve error: lookup dylankpowers.com on 127.0.1.1:53: server misbehaving"

So the real question: What would cause the server to misbehave?

**Comment by whyrusleeping** [comment]
significant financial incentive?

**Comment by jbenet** [comment]
http://golang.org/src/net/dnsclient.go?h=server+misbehaving#L77

**Comment by whyrusleeping** [comment]
"none of the error codes make sense"

**Comment by dylanPowers** [comment]
I used dig to play around and I've pinned this down to a bug in the nameservers of my domain registrar (Hover). dig for instance gives SERVFAIL as the error. This may be a good FYI for future reference since TXT records aren't incredibly common and other DNS providers may have glitches.
