### ISSUE TITLE
sharness: t0060-daemon bug

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1105]
in https://github.com/ipfs/go-ipfs/blob/96a22c5bb1713b0ecf6502ee2bd01f383b4956ec/test/sharness/t0060-daemon.sh#L18 the daemon is initialized with 
```
ipfs daemon --init >actual_daemon 2>daemon_err &
```
which -- unlike the other daemon initializations -- does not set the addresses for the gateway nor api. This means that it will clash with any other running daemon at the same ports. (this used to be fine, but since we added port randomization we've been running tests concurrently)

This problem is made worse because in https://github.com/ipfs/go-ipfs/blob/96a22c5bb1713b0ecf6502ee2bd01f383b4956ec/test/sharness/t0060-daemon.sh#L24

```

pollEndpoint -ep=/version -v -tout=1s -tries=60 2>poll_apierr > poll_apiout
```
does not set the `-host` variable, as in other calls to `pollEndpoint`:
```
pollEndpoint -ep=/version -host=$ADDR_API -v -tout=1s -tries=60
```
so the second fails silently if there is another daemon running. and instead a failure may come in https://github.com/ipfs/go-ipfs/blob/96a22c5bb1713b0ecf6502ee2bd01f383b4956ec/test/sharness/t0060-daemon.sh#L29-L34 if the repo has not been constructed yet. 

in any case, this is not good. it works if it is _the only_ daemon, but many tests run with other daemons in the background.

I think this needs
- [ ] a way to seed `daemon --init` with a config (or partial config)
- [ ] change https://github.com/ipfs/go-ipfs/blob/96a22c5bb1713b0ecf6502ee2bd01f383b4956ec/test/sharness/t0060-daemon.sh#L18 to use a config which provides addrs
- [ ] change https://github.com/ipfs/go-ipfs/blob/96a22c5bb1713b0ecf6502ee2bd01f383b4956ec/test/sharness/t0060-daemon.sh#L24 to use the chosen api or gateway addr
- [ ] change https://github.com/ipfs/go-ipfs/blob/96a22c5bb1713b0ecf6502ee2bd01f383b4956ec/test/sharness/t0060-daemon.sh#L96 to use a config which provides addrs
- [ ] change https://github.com/ipfs/go-ipfs/blob/96a22c5bb1713b0ecf6502ee2bd01f383b4956ec/test/sharness/t0060-daemon.sh#L97 to use the chosen api or gateway addr

**Comment by whyrusleeping** [comment]
this has been fixed
