### ISSUE TITLE
sharness: graceful shutdown

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1106]
currently our sharness tests kill the daemon like this

```sh
	for i in 1 2 3 4 5 6 7 8 9 10
	do
		kill $1
		sleep 1
		! kill -0 $1 2>/dev/null && return
	done
```

but this will not let the daemon do graceful shutdown (and unmounting), unless it exits within 1 second. The second kill signal will cause ipfs to skip graceful shutdown and terminate immediately.

This should only force a shutdown after the 10 sec have elapsed.

**Comment by jbenet** [comment]
I'm on this

**Comment by whyrusleeping** [comment]
I think we do this now
