### ISSUE TITLE
init: lower default key bits to 2048 for now

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1107]
until we actually have a proper focus on securing the whole thing, i think we should lower the default rsa key size to 2048. It's always a pain for new users to get hung on 4096 rsa key gen, when we have not even made sure we're using the keys correctly yet.

**Comment by david415** [comment]
oh? because they run out of entropy for key generation?

**Comment by whyrusleeping** [comment]
"closed as wontfix: @jbenet's laptop is too slow"

But this is probably okay, generation takes around four seconds for me, i guess that feels "hung"...

**Comment by jbenet** [comment]
> "closed as wontfix: @jbenet's laptop is too slow"

embedded devices need keys too :) 

4s is way too long. imagine if gmail took 4s to load!

**Comment by jbenet** [comment]
this already got done in #1111
