### ISSUE TITLE
Windows Error `fsync: The handle is invalid`

### ISSUE THREAD

**Issue by gatesvp** [ipfs/go-ipfs#1108]
Only started when I moved to `flatfs` today (2015-04-21).

Log file from `ipfs daemon debug` is below.

https://gist.github.com/gatesvp/ed830da1e2429016b851

I'm not really clear on what "leads in" to the error. We basically seem to do useful work for a bit and then die.

**Comment by jbenet** [comment]
@whyrusleeping and I didn't test flatfs on windows. maybe this is a pathing issue?

**Comment by whyrusleeping** [comment]
i should probably set up a windows box to run tests on

**Comment by gatesvp** [comment]
I can help on Thursday, though the simplest method is probably to fire up a
Windows VM on Azure.
Looks to be ~$0.02 / hour :)

http://azure.microsoft.com/en-us/pricing/details/virtual-machines/

**Comment by tv42** [comment]
Work in progress: https://github.com/jbenet/go-datastore/pull/18 to be vendored back in when ready.

**Comment by jbenet** [comment]
@gatesvp would you pls test current master works? reopen if not.

**Comment by gatesvp** [comment]
Tested just now, works as expected :)

**Comment by jbenet** [comment]
Great! Thanks!



—
