### ISSUE TITLE
Dht get returns a zero length ID

### ISSUE THREAD

**Issue by travisperson** [ipfs/go-ipfs#1116]
Should this be returning the peer id for the node the value was retrieved from?

```
~ $ curl -XPOST 'http://127.0.0.1:5001/api/v0/dht/put?arg=fff&arg=ddd'
{
  "Extra": "",
  "ID": "QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
  "Responses": null,
  "Type": 5
}{
  "Extra": "",
  "ID": "QmZ9AXzdbR1TpK7YFVGuAPx8pMef2RFX5z17vGf8x76mnd",
  "Responses": null,
  "Type": 5
}{
  "Extra": "",
  "ID": "QmSJ5B27yQe9bDLmwqF4FxJpBBcpxMnK9uJwX8qbQUyycN",
  "Responses": null,
  "Type": 5
}
```

```
~ $ curl -XGET 'http://127.0.0.1:5001/api/v0/dht/get?arg=fff'
{
  "Extra": "ddd",
  "ID": "",
  "Responses": null,
  "Type": 5
}
```

**Comment by whyrusleeping** [comment]
Hrm, i guess i could throw the node the value came from in there.

**Comment by whyrusleeping** [comment]
Try adding this on line 136 of routing/dht/routing.go
```
	notif.PublishQueryEvent(ctx, &notif.QueryEvent{
			Type:      notif.Value,
			ID:        result.peer,
                        Extra: result.value,
		})
```

**Comment by travisperson** [comment]
Didn't see anything different
```
notif.PublishQueryEvent(ctx, &notif.QueryEvent{
		Type: notif.Value,
		ID: result.peer.ID,
		Extra: string(result.value),
})
```

After adding that code (line 136), I ran the same above commands and no output for the `ID`. Also try a new key/value pair just to be sure.

Not a huge deal, can be backlogged and maybe I'll see if I can get it to work later.

**Comment by whyrusleeping** [comment]
oh, the ID needs to be added to the object on line 112

**Comment by jbenet** [comment]
it's probably worth carefully designing this API. 

Would it be useful for me to make an `ipfs/api` repo to house what the api should be in all these commands? we could even have a test suite in it for testing implementation conformance.

**Comment by jbenet** [comment]
we could even rapid-protoype future apis there

**Comment by travisperson** [comment]
+1

I think that is a great idea.

**Comment by jbenet** [comment]
Ok cool. will do it over at https://github.com/ipfs/api -- feel free to add issues there. 

@dylanPowers may need to add this o/ to our repos listing

**Comment by travisperson** [comment]
Do you want to file issues against that repo for issues with go-ipfs?

I found another thing that we should look at under pin.

**Comment by jbenet** [comment]
@travisperson i think that repo should say what the API **SHOULD** be (and have tests for it). bugs/errors/deviations in go-ipfs should be filed here.

**Comment by jbenet** [comment]
@travisperson so maybe if its an api change, suggest it generally over there, and we can apply changes here. (i.e. describe it in terms of commands and url paths and not go files/funcs)

**Comment by jbenet** [comment]
@travisperson (making this up as we go-- want to be inclusive to non-go-folk)

**Comment by whyrusleeping** [comment]
closing, this is fixed as far as i can tell
