### ISSUE TITLE
Dockerfile updates

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1129]
@Luzifer found some bugs changing user in the dockerfile. it prompted me to comment:

> i wonder if there's some funkiness with shell expansion. i think the dockerfile should 
> (a) not run ipfs as root (unless needed by fuse/privileged/whatever), and 
> (b) it should set an explicit `IPFS_PATH` env var to both signal to user where it will put repo AND put it someplace user-independent. 
> Maybe a good location is `/repo` or `/ipfs_repo` (or `/ipfs/repo` if UFS/AUFS/OFS make it work with fuse.)

**Comment by Luzifer** [comment]
Targeting in #1128

**Comment by whyrusleeping** [comment]
I think this has been fixed
