### ISSUE TITLE
ipfs init is not reporting failures

### ISSUE THREAD

**Issue by Luzifer** [ipfs/go-ipfs#1130]
Given the `$IPFS_PATH` is not writable for `ipfs init` the command does show the output we're used to as if it worked fine. Instead it should show an fatal error because `ipfs init` is in fact not able to write into that directory and it is empty afterwards which causes strange errors:

```
# echo $IPFS_PATH
/data/ipfs

# ls -lhR /data
/data:
total 4.0K
drwxr-xr-x 2 root root 4.0K Apr 23 20:58 ipfs

/data/ipfs:
total 0

# ipfs version
ipfs version 0.3.2

# ipfs init
initializing ipfs node at /data/ipfs
generating 2048-bit RSA keypair...done
peer identity: QmfJZTJVaDcfDfxs6LpwEqiAtqxGa2rkCpTTqMPgoZwdMm

# ipfs daemon
Initializing daemon...
Error: no ipfs repo found. please run: ipfs init
```

**Comment by whyrusleeping** [comment]
Good catch, should be a moderately easy fix in `cmd/ipfs/init.go` or maybe somewhere in `repo/fsrepo`.

**Comment by jbenet** [comment]
woahhh interesting. we should add a test case for this to sharness tests.
