### ISSUE TITLE
shell redirect append in ipns fuse failed.

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1135]
Yesterday, I was doing:

```
> echo "aaa" >foo
> echo "bbb" >>foo
```
and the append would fail.

im trying to repro now, and this just happened:

```
> echo "foo" >foo    # should delete everything in that file.
> echo "foo" >>foo
> echo "foo" >>foo
> echo "foo" >>foo
> echo "foo" >>foo
> cat foo
foo
pofkopdsafkdsadsafdsafdsafdsafoo
foo
foo
foo
foo
```

odd things:
- the file used to contain: 
    ```
    pofkopdsafkdsadsafdsafdsafdsaf
    ```
    (maybe also the first `foo` but not sure)

- the file should have been truncated by the first echo. didnt happen.
- append worked this time :confused: 

cc @whyrusleeping 
cc @tv42 -- we could probably use some fuse help

**Comment by tv42** [comment]
You need to implement Setattr, to change file sizes -- including truncation.

**Comment by whyrusleeping** [comment]
I'll get to this next sprint.

**Comment by whyrusleeping** [comment]
I think this is fixed
