### ISSUE TITLE
Errors while running for a long time

### ISSUE THREAD

**Issue by viraptor** [ipfs/go-ipfs#1143]
Hi, this is going to be a very under-defined report, but when I run ipfs daemon v0.3.2 for a long time, I get this error sometimes:

    14:14:27.049 ERROR p2p/host/b: protocol mux failed: %sEOF basic_host.go:98

**Comment by whyrusleeping** [comment]
Yeah, that should probably be demoted to a `Warning` or something, I beleive that it happens when someone connects to you, and their connection drops unexpectedly, or in the middle of a message.
