### ISSUE TITLE
nicer looking index page

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1153]
this is not so hot:

![](https://www.evernote.com/shard/s198/sh/d3330945-35ed-4b18-ac9b-0d7a9e74828b/03ee32a72c1a59f360798568802f7e0d/deep/0/-ipfs-QmR9yzggUjRQRWBuDgwwjrTWH1Vhd37U8PxNNLYoCN5xYv.png)

would be nice to have humanized sizes. and nice listings. and maybe have links to ipfs.

**Comment by whyrusleeping** [comment]
should be as simple as deciding what we want: https://github.com/ipfs/go-ipfs/blob/master/core/corehttp/gateway_handler.go#L491

**Comment by krl** [comment]
Something like this?

http://gateway.ipfs.io/ipfs/QmbYKLhGDqD1euYtTqWqLJsXcTxzeZ6UrWGTyt2tCtENHr/filelist.html

**Comment by krl** [comment]
using MIT licensed https://github.com/teambox/Free-file-icons

**Comment by whyrusleeping** [comment]
krl thats a lot nicer :)

**Comment by jbenet** [comment]
Very nice! Would be nice to include an ipfs logo or something. like "served by IPFS".

also-- this is perhaps a separate PR -- we should do something cool with the index page. index pages haven't changed much in decades-- what could we do? previews? allow switching between "list, thumbnail, gallery" view? (insta-media-galleries)

**Comment by jbenet** [comment]
- would be nice to make the path components clickable, like at the top of http://ipfs.io/blog/0-hello-worlds/

**Comment by jbenet** [comment]
Idea: make the index page optionally take an argument, as a "viewer" which is JS that is loaded and runs on the page.

this could potentially be super dangerous, but it's an interesting idea.

**Comment by krl** [comment]
+1 more branding
+1 gallery mode

@jbenet: would be nice to spec out what a viewer would be, and how it could potentially support non-unixfs structures as well.

**Comment by whyrusleeping** [comment]
would it be `ipfs.io/ipfs/viewer#path` or `ipfs.io/ipfs/path#viewer` ?

**Comment by jbenet** [comment]
the problem with using the `#<path>` notation is that it breaks anchors :(

**Comment by krl** [comment]
http://gateway.ipfs.io/ipfs/QmTxNTmUDXBPvyjg4bAo5Qizs6ag1sXtZkfhNxv7yE7AzC/filelist.html

here's a more branded version. @jbenet, @cryptix - how do we best get this into go-ipfs?

**Comment by cryptix** [comment]
@krl that looks awesome! We currently hardcode the html template for the index [here](https://github.com/ipfs/go-ipfs/blob/master/core/corehttp/gateway_handler.go#L446).

**Comment by jbenet** [comment]
@krl looks very good. can we put that thing in a repo somewhere, and have the go templating in a pkg there? (i'd like to use it in other tools, and i'd like to give feedback on it)

**Comment by cryptix** [comment]
> can we put that thing in a repo somewhere, and have the go templating in a pkg there?

Do our unixfs objects implement `os.File`? Otherwise I'm not sure how much reuse you will get out of this.

**Comment by jbenet** [comment]
@cryptix not that-- the templating from names, icons, sizes -> nice output.

**Comment by krl** [comment]
@jbenet https://github.com/krl/ipfs-file-list

**Comment by jbenet** [comment]
@krl thanks
