### ISSUE TITLE
Internal organization for this repository (internal, core, shell, http, cmd, test)

### ISSUE THREAD

**Issue by wking** [ipfs/go-ipfs#1158]
On Mon, Apr 27, 2015 at 11:17:18PM -0700, Jeromy Johnson [wrote][0]:
> In my perfect awesome world where I wrote all the code and spent
> lots of time making the interfaces perfect, We would have the
> importer, with all its knobs and switches on the low end (probably),
> and `coreunix.Add` being all nice and user friendly on top, and then
> the `commands.Add` would just call into `coreunix.Add`.
>
> I guess the further refinement of that idea is that *all* commands
> are just UX wrappers over the `core*` methods, and the `core*`
> methods handle a bunch of logic in order to make calls to the low
> level `importer` style, raw methods.
>
> \<musings ignore=true random=true>
> maybe we should rename core -> mantle, and call the lowest level
> type API commands the core...
> \</musings>

So after a fairly brief chat on IRC with @jbenet, my understanding was
that we wanted something like:

* `internal/…` Really low-level stuff where we reserve the right to
  break interfaces as often as we like.
* `core/…` The official, low-level API that gives consumers all the
  knobs they need, which we try hard to keep stable.
* `shell/…` The official, high-level API that gives consumers easy
  access to common operations (e.g. [create a file node from a reader
  without wrapping with metadata][1]).  We work *really* hard to keep
  this stable.

Then on top of the `core/…` and `shell/…` Go APIs, we'd build:

* `http/…` The REST API
* `cmd/…` The command-line API
* `test/…` Integration tests, etc.

To avoid cyclic imports (see part of my commit message in ccb3f399
(util/testutil/addcat/addcat: Factor out add/cat/verify helper,
2015-04-26), I'd jump through whatever hoops had to be jumped through
to ensure imports never cut further down in that stack.  For example,
you could import all of `core` and `shell` from `cmd/…` or `test/…`, but you
couldn't import any of `shell/…` from `core/…`.

Spun off from ipfs/pm#6.

[0]: https://github.com/ipfs/pm/issues/6#issuecomment-96939273
[1]: https://github.com/ipfs/go-ipfs/pull/1136#issuecomment-96854906

**Comment by jbenet** [comment]
all SGTM.

only one comment:

- we currently have some `internal/` packages, but i'm strongly against them and want to get rid of them. they can cause really, really bad situations. (fun story: https://github.com/jbenet/go-fd-mutex -- this isn't quite `internal/`, but there are similar cases).

**Comment by wking** [comment]
On Tue, Apr 28, 2015 at 04:53:28PM -0700, Juan Batiz-Benet wrote:
> - we currently have some `internal/` packages, but i'm strongly
>   against them and want to get rid of them.

I expect we'll have stuff that's so low-level that we can't imagine
folks using it directly that we don't want to commit to stabilizing.
It takes some work to deprecate nicely (see #1159), and if that
applies to *all* of our package-public interfaces I think it would be
too big a drag.  But maybe we don't want anything that low-level ;).
Anyhow, I'm fine moving stuff into “we commit to trying to keep this
stable, and will work hard to help you migrate smoothly when we do
break backwards compatibility” locations as we see fit, and just
letting the internal stuff about which we don't make those guarantees
wither away.

**Comment by wking** [comment]
I recommend closing this issue now that 6fd877de (doc: Add some docs
explaining the sub-package layout, 2015-05-02, #1185) has landed.
Unless there are other places we want to document this layout?

**Comment by jbenet** [comment]
this is good enough for now
