### ISSUE TITLE
Need maximum message size on msgio reader (or at least the secio reader)

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1175]
In todays episode of "whyrusleeping finds the transport bugs", we have the problem thats been causing all our out of memory panics. If i connect to an ipfs peer, handshake, and then send a msgio header saying my message will be 19 trillion bytes, [we will attempt to malloc a buffer of 19 trillion bytes.](https://github.com/ipfs/go-ipfs/blob/master/p2p/crypto/secio/rw.go#L128). This causes the panics we see, as evidenced by this line in the stack traces:

```
 runtime.mallocgc(0xb1b99a33, 0xa8a320, 0xc200000001, 0xc208fa9c20)
```
that first argument isnt a pointer, its the size of the allocation.

I suggest either a sane max size (8MB might be okay) or we move towards doing streaming reads, using a limitreader to specify how many bytes are available to the consumer.

**Comment by whyrusleeping** [comment]
CC @jbenet

**Comment by jbenet** [comment]
limitedreader or maxsize sound good. a max message size well below the limit will help-- (but remember the problems that emerge from having a max size)

**Comment by jbenet** [comment]
also, wow.

**Comment by jbenet** [comment]
:clap:

**Comment by whyrusleeping** [comment]
we have this now, closing
