### ISSUE TITLE
net panics if given unsecured connection

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1177]
If you try to dial through the swarm without having your private key set (attemping to take advantage of the [if statement here](https://github.com/ipfs/go-ipfs/blob/master/p2p/net/conn/dial.go#L63) and trigger an unsecured connection). The swarm will [panic here](https://github.com/ipfs/go-ipfs/blob/master/p2p/net/swarm/swarm_conn.go#L41) because the underlying conn is actually a multiaddr-net-conn instead of a `conn.Conn`. I'm not super certain why the code in swarm_conn is okay, it feels wrong to me.

**Comment by jbenet** [comment]
interesting. singleConn should be wrapping: https://github.com/ipfs/go-ipfs/blob/master/p2p/net/conn/conn.go#L40-L53
