### ISSUE TITLE
secio handshake hangs if transport has little or no buffering

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1178]
In our secio handshake, both sides [write at the same time](https://github.com/ipfs/go-ipfs/blob/master/p2p/crypto/secio/protocol.go#L112)

This works fine for most scenarios, the network buffer size is probably larger than the size of the kernels write buffer (or the socket buffer on the other side). But when the messages become larger, or the network buffer size becomes smaller (as is the case in my testing), the handshake will hang.

**Comment by jbenet** [comment]
ohh interesting. that's annoying. makes sense. bufio might help?

**Comment by jbenet** [comment]
as we discussed, we should go with the goroutine approach (bufio won't work well)

**Comment by whyrusleeping** [comment]
needs to be verified, but i think this might be fixed

**Comment by Stebalien** [comment]
This is not fixed.

**Comment by Stebalien** [comment]
This has now been fixed.
