### ISSUE TITLE
Commit Data Structure

### ISSUE THREAD

**Issue by SilentCicero** [ipfs/go-ipfs#1188]
A commit system like Github has would be amazing. Command line would be something like: "ipfs commit myfile.md HASH_OF_REPO". Whereby I can overwrite or over-link one file with another in a specific repository.

**Comment by diasdavid** [comment]
100% agreed! Join the discussion on:
- https://github.com/ipfs/notes/issues/23
- https://github.com/ipfs/notes/issues/45
