### ISSUE TITLE
pinning taking up lots of CPU on benchmarks

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1192]
I was looking over the benchmarks for the dagmodifier since someone mentioned writing a large file into /ipns was slow, and i noticed that we are spending a lot of time right here: https://github.com/ipfs/go-ipfs/blob/master/pin/indirect.go#L46

We really shouldnt be marshaling keys to base58 for this...

@tv42 in your pinning stuff you were working on, you dont do any b58 marshaling, right?

**Comment by tv42** [comment]
@whyrusleeping I consider needing base58 outside of UI a design failure.

**Comment by whyrusleeping** [comment]
@tv42 good.

**Comment by whyrusleeping** [comment]
this is much better
