### ISSUE TITLE
randomize ports in sharness

### ISSUE THREAD

**Issue by cryptix** [ipfs/go-ipfs#1197]
at least `t0060-daemon.sh` uses the default and clashes with services also running on `:8080`.

**Comment by jbenet** [comment]
Ohhh and the swarm is currently defaulting to the same port every time. I bet that's the remaining problem!

**Comment by jbenet** [comment]
i think i did this in https://github.com/ipfs/go-ipfs/pull/1220

**Comment by jbenet** [comment]
No, this is still a problem.

https://github.com/ipfs/go-ipfs/blob/37b32a658775dd94d7ebb8d71720e62924c316d6/test/sharness/t0060-daemon.sh#L18-L19

**Comment by whyrusleeping** [comment]
TODO: make t0060 use randomized ports.

**Comment by whyrusleeping** [comment]
this has been completed
