### ISSUE TITLE
logs that dont get printed still render

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1217]
So this really isnt an issue with our code, but with the logger library:
https://github.com/whyrusleeping/go-logging/blob/master/logger.go#L266

**Comment by jbenet** [comment]
if you git blame that, i touched it last, so i may have introduced this problem unwittingly

**Comment by whyrusleeping** [comment]
it should be an easy fix, probably.

**Comment by jbenet** [comment]
Closed in #1359
