### ISSUE TITLE
Improve Add performance

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1223]
the `ipfs add` operation is quite slow, we need to improve this.

**Comment by whyrusleeping** [comment]
merged #1242, it helped

**Comment by whyrusleeping** [comment]
#1274 will help as well

**Comment by whyrusleeping** [comment]
after #1242, 100GB is estimated to take ~2hrs

**Comment by rht** [comment]
@whyrusleeping `ipfs get` flushes every 32 KB if this is a lot?

**Comment by whyrusleeping** [comment]
no, thats fine. `ipfs get` is mostly bottlenecked on bitswap cramming things into the blockstore, not writing a single file to disk clientside

**Comment by diasdavid** [comment]
Let's merge this discussion on https://github.com/ipfs/go-ipfs/issues/1216
