### ISSUE TITLE
Bitswap tests halt?

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1228]
I've seen these a few times on travis-- and it takes a long time locally too -- something seems to be wrong. maybe this is the "halting" we're seeing.

- https://travis-ci.org/ipfs/go-ipfs/jobs/62211476

All of them failed this way:
- https://travis-ci.org/ipfs/go-ipfs/builds/62211484
- https://travis-ci.org/ipfs/go-ipfs/builds/62211474

Update: sorry i re-rolled the builds so it went away.

**Comment by jbenet** [comment]
-  https://travis-ci.org/ipfs/go-ipfs/jobs/62211476

**Comment by jbenet** [comment]
cc @whyrusleeping

**Comment by whyrusleeping** [comment]
yeah... the bitswap TestLargeSwarm test takes a really long time. I had to turn it down on my local branch.

**Comment by jbenet** [comment]
Seems like it's gotten worse? 



—

**Comment by jbenet** [comment]
We should have nice benchmark graphs generated with every changeset, ah yes, that'd be nice



—

**Comment by whyrusleeping** [comment]
Its better on my branch now, lots of eventlogs causing excess memory consumption leading to lots of time spent in GC

**Comment by whyrusleeping** [comment]
bitswap tests are better now
