### ISSUE TITLE
ipfs bitswap stat fails in an ugly way when offline

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1236]
`ipfs bitswap stat` should print out a message like "this command must be run in online mode" when run without a daemon, instead we get an ugly casting error.

**Comment by jbenet** [comment]
Is there a test for this?

**Comment by Ape** [comment]
@jbenet See #1278.

**Comment by jbenet** [comment]
it should have a test case, that verifies `ipfs bitswap stat` and friends do not fail in an ugly way when offline.

**Comment by RichardLitt** [comment]
Should I open an issue for that test case?
