### ISSUE TITLE
network performance is spotty

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1241]
I put some timers around stream writes and did some testing, the results arent good. Writes will randomly take up to 3 seconds (rare occasion), and in the 800ms -> 1200ms range more frequently. The tests I ran were over wifi LAN, and 'ipfs ping' the peer in question reported an average latency of 2.3ms.

**Comment by whyrusleeping** [comment]
@jbenet part of this issue i think is that msgio writes the length and the message separately, triggering two separate syscalls. This is made worse by the fact that #1065 hasnt yet merged.

**Comment by whyrusleeping** [comment]
i think i found the root cause. tcp over wifi is the worst. just dont do it.

**Comment by whyrusleeping** [comment]
preliminary tests show that QUIC deals with packet loss much better than tcp (http://www.connectify.me/blog/taking-google-quic-for-a-test-drive/ <- from 2013). So i'm hoping that we will see some good perf improvements when we finally get that.

**Comment by jbenet** [comment]
@whyrusleeping yeah and because we use _one_ tcp connection, we get the worst of all possible worlds because _one_ drop will back up everything (this is called head-of-line blocking). QUIC fixes this.

We may want to write libutp bindings sooner.

**Comment by whyrusleeping** [comment]
oh yeah, i forgot about that too... super shitty. i was debating asking the QUIC team what another dev could do to help the cause and hacking on that.

**Comment by jbenet** [comment]
i saw an extraction, we could try to make bindings for it

**Comment by whyrusleeping** [comment]
closing issue, we have utp, and performance appears to have improved even over tcp

**Comment by jbenet** [comment]
We should add utp to the bootstrap addrs (when we allow multiple addrs per
bootstrap node)
