### ISSUE TITLE
Avoid dialing known _local_ addresses when not in that network

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1246]
See #1226 

Change `p2p/net` to avoid dialing known local area network addresses when not in that local network. 

For example, it does not make sense to dial a 192.168.0.0/16 address when not within that subnet. This alone will cut out most -- if not all -- of the sysadmin netscan warnings. Most VPSes are in different networks.

We need to:
- [ ] identify a list of all subnets that we should do this with.
- [ ] implement the changes

**Comment by whyrusleeping** [comment]
my thoughts for a simple, "quick and easy" solution are to provide a config setting to allow users to specify which ranges to avoid dialing.

**Comment by jbenet** [comment]
- [ ] implement https://github.com/ipfs/go-ipfs/issues/1246 
- [ ] implement https://github.com/ipfs/go-ipfs/issues/1247

**Comment by Stebalien** [comment]
Moving to libp2p: https://github.com/libp2p/go-libp2p/issues/436
