### ISSUE TITLE
Config option to disable dialing specific subnets entirely

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1247]
See #1226 

Having a config option to disable dialing local subnets entirely. maybe even allowing configurable address filters.

We need to:
- [x] come up with a config format for the filters
- [x] add a config option for the subnet filters
- [x] add subnet filter support to `p2p/net`

This will make it possible to both (a) prevent dialing local subnets entirely, and (b) prevent dialing _everything BUT_ local subnets (i.e. don't connect to WAN).

One open question about these filters is:
- whether to filter _all_ traffic (dials + listens), just dials, or make it configurable by subnet.

**Comment by jbenet** [comment]
### possible config format:
```js
{ // ...
 "Swarm": {
  "TrafficFilters": [
    { "0.0.0.0/0": "deny"},
    { "10.10.10.0/28": "allow"},
  ]
}}
```

meanig that no config is as if:
```
{ "Swarm": {
  "TrafficFilters": [
    { "0.0.0.0/0": "allow"},
  ]
}}
```

People more experienced with traffic forming tools should comment here and tell me all the desires. we can probably implement something pretty expressive without too much more effort.

**Comment by timgws** [comment]
What about if we had something like Apache's htaccess[1](https://httpd.apache.org/docs/2.2/howto/access.html) format?

      DefaultOrder deny,allow
      Deny from 10.0.0.0/8
      Allow from all

It's expressive and short. For example, a machine only wanting connections to machines on the same LAN network could do:

      DefaultOrder deny,allow
      Deny from all
      Allow from 10.0.0.0/8

**Comment by jbenet** [comment]
Ah yeah that's promising! maybe we can discuss `iptables` or `nft` formats too, and pick whatever is best for us. anyone experienced with those want to throw out some relevant examples?

**Comment by timgws** [comment]
IP tables would be similar, but it's a little "unfriendly". If you want world domination, you want something that with a limited amount networking knowledge, know __exactly__ what you are doing within seconds of staring at the file.

With `iptables` you can block an IP like this:

     iptables -I INPUT -s 1.2.3.4 -j DROP

`-I` inserts this rule into a chain (in this case, INPUT). `-s` specifies the source address (this can also be a netblock, such as 192.168.0.0/23). `-j` specifies a chain to jump to (here it's `DROP`).

Would we maybe want to have configuration for each interface as a possibility? Maybe this is something best left to the operating system to work out?

**Comment by whyrusleeping** [comment]
I'm wondering if this should be implemented in the peerstore, since thats where we handle addresses. Maybe when we ask if for addresses to dial, it can filter them by our blocklist, but when we ask it for addresses to send to other peers, it can give us all of them. (doing it this way also makes the changes to the construction process a little simpler)

**Comment by timgws** [comment]
That sounds like the right place to do it.

The only question is what about the `swarm connect` command? Do we have an option to force a connection to a given IP address given by the user, even if the IP address has been denied with a block list?

**Comment by whyrusleeping** [comment]
@timgws yeah, that seems like the right thing to do, have a `-f` option to ignore the blacklist

**Comment by whyrusleeping** [comment]
@jbenet i'm now wondering if these should be specified in some sort of multiaddr format like: `/filter/ip4/192.168.0.0/16` or something

**Comment by jbenet** [comment]
@whyrusleeping oh interesting! that might work very well. 

we should probably note that it's a `cidr` subnet address, with a prefix too:
```sh
/filter/cidr/ip4/192.168.0.0/16

# which means

/filter
+-- /cidr/
    +-- /ip4/192.168.0.0
     /16
```

though this o/ gets clunky, because the address `/cidr/<ip-addr>/<length>` now has a sub-multiaddr. maybe it makes sense to flip it:

```sh
/filter/cidr/16/ip4/192.168.0.0/

# which means

/filter
+-- /cidr/16
    +-- /ip4/192.168.0.0
```
but that gets farther away from the `<ip>/<length>` cidr convention.

(formats are hard.)

**Comment by whyrusleeping** [comment]
yeah, that could work. do we wanna make a decision on what the proper 'filter format' should be for multiaddr before i start hacking?

**Comment by jbenet** [comment]
1. instead of `"filter"` which is generic and liable to clash, i'd go for something like `/ip-subnet`
2. i'm thinking that this part is not needed, if this address is in a field like:

    ```
    Filters: [
      "/ipcidr/16/ip4/192.168.0.0"
      "/ipcidr/16/ip4/192.168.0.0"
    ]
    ```

3. i'm not super comfortable with switching the order, but not sure what else to do there. **shrug**


---

let's go with either:
```sh
/ipcidr/16/ip4/192.168.0.0
/ip4/192.168.0.0/ipcidr/16
```

**Comment by whyrusleeping** [comment]
i like the latter

**Comment by jbenet** [comment]
> i like the latter

let's do it

**Comment by whyrusleeping** [comment]
alright, should i call the package multiaddr-filter? multiaddr-ipmask?

**Comment by jbenet** [comment]
both sgtm
