### ISSUE TITLE
dht test failure

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1253]
On my spree of "travis broke, file an issue", i've got yet another random failure, this one from the dht.

https://travis-ci.org/ipfs/go-ipfs/jobs/63253981

**Comment by chriscool** [comment]
I don't know if the above is fixed now, but I often get a failure for the same test:

```
$ go test github.com/ipfs/go-ipfs/routing/dht
--- FAIL: TestConnectCollision (5.14s)
        dht_test.go:798: Timeout received!
time="10:28:33:000" level=error msg="TestBogusPrivateKey.Sign -- this better be a test!" module=boguskey 
FAIL
FAIL    github.com/ipfs/go-ipfs/routing/dht     11.984s
```

**Comment by chriscool** [comment]
Maybe issue #1639 (panic in DHT tests) is also related.

**Comment by whyrusleeping** [comment]
Ah, the above is fixed. but i've seen that timeout one a few times. I think its just machines being overloaded, but i'll see about raising the timeout.

**Comment by whyrusleeping** [comment]
@chriscool mind filing a bug for the failure you found? I'll close this one.

**Comment by chriscool** [comment]
Ok I filed #1873 (dht_test timeout)
