### ISSUE TITLE
[Feature request] Allow parameters to ipfs init

### ISSUE THREAD

**Issue by peerchemist** [ipfs/go-ipfs#1296]
Default behavior is to init IPFS root in ~/.ipfs , allow parameter where this can be changed.

Examples:

`ipfs init ipfs-test`

`ipfs init /var/lib/ipfs`

**Comment by whyrusleeping** [comment]
this is currently changeable through the environment variable `IPFS_PATH`. This also appears to be an undocumented feature which we should probably address

**Comment by diasdavid** [comment]
@RichardLitt we should add the env vars to the CLI API spec as it will have to be part of a language implementation

**Comment by jbenet** [comment]
Indeed.

This is documented in ipfs main help now. Should likely also be documented
in ipfs daemon and ipfs init.

**Comment by Dignifiedquire** [comment]
Env vars are really problematic, as they will not work in the same way on Windows and on any other api transport like http. So I suggest that all config that can be done via an env variable also needs to be available as a regular flag.

**Comment by jbenet** [comment]
ok we could use a `--repo-path` plag (or `--repo` if we dont think we'll
need to use it in other commands)

**Comment by Ape** [comment]
@Dignifiedquire Is there any scenario where it would be useful to set IPFS_PATH on the HTTP API?

**Comment by Dignifiedquire** [comment]
@Ape I would say so, e.g. if it's used from another application that's running locally and it wants to start a daemon that has another home directory specific to the application.

**Comment by RichardLitt** [comment]
#2526 was closed due to lack of activity. If anyone is interested on picking this issue up, that might be a good place to start.
