### ISSUE TITLE
Installation script for linux_x86 doesn't work

### ISSUE THREAD

**Issue by PayasR** [ipfs/go-ipfs#1298]
the structure of ipfs-master-linux-x86.zip is :
.zip 
-ipfs (the executable)
-dist ( a folder that has install.sh and README. )

And the installer has lines:
bin=ipfs
binpath=/usr/local/bin
if [ -d "$binpath" ]; then
  mv "$bin" "$binpath/$bin"
  echo "installed $binpath/$bin"

so it is trying to relocate ipfs <executable> which is actually in the parent folder. 
Output:
mv: cannot stat ‘ipfs’: No such file or directory
installed /usr/local/bin/ipfs

even after relocating the executable to the same folder.
Output:
 mv: cannot create regular file ‘/usr/local/bin/ipfs’: Permission denied

Solution:
1. move the executable to the same folder.
2. use 'sudo mv ...'

**Comment by whyrusleeping** [comment]
1 appears to be a bug, for 2, you should use `sudo ./install.sh`

**Comment by PayasR** [comment]
2. So we need to mention that somewhere .. or at least it should print 'sudo' required instead of silently failing.

**Comment by whyrusleeping** [comment]
@PayasR  not saying i dont agree, but i havent run an install script that didnt error out on `/usr/local/bin: permission denied`

**Comment by jbenet** [comment]
IIRC this may be fixed with the latest gobuilder api. the `dist/` directory is a side effect of the older gobuilder not letting us rename the paths and me not knowing a good way to fix it.

cc @Luzifer thoughts?

**Comment by Kubuxu** [comment]
I think it is not longer relevant.
