### ISSUE TITLE
look at running merkledag tests without rebroadcast delay

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1306]
The merkledag tests seem a little suspicious to me, every so often they complete in  0.2 seconds, and other times they complete in 10.2 seconds. This makes me think that something is failing, and then getting kicked back into play by bitswaps timers.

I'm going to take a look at this, i just filed an issue as a reminder for myself.

**Comment by jbenet** [comment]
why do merkledag tests depend on bitswap?

**Comment by whyrusleeping** [comment]
@jbenet because the DAGService is in the merkledag package, and it uses bitswap

**Comment by jbenet** [comment]
Yeah, but the merkledag tests shouldn't be testing (only with) bitswap. they should use a simplified blockstore. (it's good to test with bitswap too, but that's an integration test and should be separate).

**Comment by jbenet** [comment]
Everything needs to be tested in isolation AND in combination, if we want to remain sane.

**Comment by whyrusleeping** [comment]
well, i think those tests are actually pointing out a bug in bitswap, so this is a good thing. (i think)

**Comment by whyrusleeping** [comment]
this is fixed, i think
