### ISSUE TITLE
need a global timeout flag

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1325]
It would be awesome if i could pass `--timeout=5s` to any command i run and have the commands context expire when the timeout is up.

**Comment by jbenet** [comment]
+1

**Comment by jbenet** [comment]
should support `--timeout=0` for no timeout.

**Comment by jbenet** [comment]
the way to implement is: cli passes it as an option to the API. the api (in the cmdslib) sets the timeout of the cmd's context based on this timeout.

**Comment by whyrusleeping** [comment]
we have this
