### ISSUE TITLE
Rename 'ipfs object' to 'ipfs dag'

### ISSUE THREAD

**Issue by wking** [ipfs/go-ipfs#1328]
@jbenet [mentioned this][1] in passing, and I thought I'd open a separate issue for it.  Personally, I like ‘object’ better, since this command is about manipulating individual nodes and edges in the Merkle DAG.  But I'm not clear on the motivation behind the rename, so maybe I'm missing something.  For this issue:

* Why do we want the rename?  Equivalently, how will we motivate this to users?
* How is the transition going to work?  Will we support both forms through some deprecation period?

[1]: https://github.com/ipfs/go-ipfs/pull/1320#issuecomment-108231171

**Comment by jbenet** [comment]
on the motivation, some quotes from people i asked:
- "object is too generic, it's unclear" 
- "`ipfs dag` is more clear-- you're manipulating the dag directly"
- "object is too much typing"
- "`ipfs dag` sounds cooler"'
- "`ipfs dag` makes more sense cause unixfs is also a set of objects, so `ipfs object` feels like like a parent of unixfs."

i agree with some of these but not all

---

on the transition, yeah probably support both forms and drop it before beta release.

---

btw, a similar thing will be to make `ipfs files` a thing, and have `unixfs`-specific `cat, ls, get` there. (still will want `ipfs ls, ipfs cat, ipfs get` in porcelain, but that may have to do with StackStream and so on, to be general enough to be global. not sure yet).

**Comment by diasdavid** [comment]
Let's merge this thread into the main one https://github.com/ipfs/go-ipfs/issues/575
