### ISSUE TITLE
object new returns different hash than blank template

### ISSUE THREAD

**Issue by travisperson** [ipfs/go-ipfs#1332]
While playing around I was trying to create a blank dag via `ipfs object put` and found out that you can't due to #883 (Which I think we should revert unless there is a valid bug as go it self doesn't care about extra fields).

I noticed that hash in the issue differed from that of the new `ipfs object new` command. I ran stat on each hash and found the follow.

```
~/s/g/i/go-ipfs (master) $ cat << EOF  | ipfs object put
> {
>   "Links": [],
>   "Data": ""
> }
> EOF
added QmPRmYXoB2SaqFXkCeoX7ebPZG2ZuFoHCB9zHjaxCPFL3u
~/s/g/i/go-ipfs (master) $ 
ipfs object stat QmPRmYXoB2SaqFXkCeoX7ebPZG2ZuFoHCB9zHjaxCPFL3u
NumLinks: 0
BlockSize: 2
LinksSize: 2
DataSize: 0
CumulativeSize: 2
~/s/g/i/go-ipfs (master) $ ipfs object new
QmdfTbBqBPQ7VNxZEYEj14VmRuZBkqFbiwReogJgS1zR1n
~/s/g/i/go-ipfs (master) $ 
ipfs object stat QmdfTbBqBPQ7VNxZEYEj14VmRuZBkqFbiwReogJgS1zR1n
NumLinks: 0
BlockSize: 0
LinksSize: 0
DataSize: 0
CumulativeSize: 0
~/s/g/i/go-ipfs (master) $ 
ipfs object get QmPRmYXoB2SaqFXkCeoX7ebPZG2ZuFoHCB9zHjaxCPFL3u
{
  "Links": [],
  "Data": ""
}
~/s/g/i/go-ipfs (master) $ 
ipfs object get QmdfTbBqBPQ7VNxZEYEj14VmRuZBkqFbiwReogJgS1zR1n
{
  "Links": [],
  "Data": ""
}
```

I did a bit of digging and it turns out `QmPRmYXoB2SaqFXkCeoX7ebPZG2ZuFoHCB9zHjaxCPFL3u` when encoded has byte data of `[10 0]`, hence the `BlockSize` of 2, `LinksSize` is `BlockSize - DataSize`, so we get 2 there as well even though there are zero links.

The `ipfs object new` `QmdfTbBqBPQ7VNxZEYEj14VmRuZBkqFbiwReogJgS1zR1n` has byte data of `[]`

/cc @whyrusleeping

**Comment by jbenet** [comment]
- Why is #883 wrong? we _should_ be validating input.
- yeah i think you're right about the sizes stuff, not sure.

**Comment by travisperson** [comment]
It doesn't really validate though, it checks for empty values. The question is, are empty values okay.

**Comment by jbenet** [comment]
@travisperson oh i see, you're right.

So, what i think should happen is this:
- empty nodes are fine, and default no links or no data to empty.
- actually validate-- if _unexpected keys_ are there, there should be an error. for example, the tests in https://github.com/ipfs/go-ipfs/commit/b688e72de05cef362e310c90f9968a0614830adf#diff-0cbbd6451dadc6f9670ea767d0e3360dR85 should remain.

this is one of those cases where if the user input something, and receives an OK response, then the user expects the input to have been consumed, not to have part of it partially dropped. if the user made a mistake, the user should be alerted to this. losing data unexpectedly is the key thing we we must not do.

**Comment by jbenet** [comment]
so instead of reverting #883 we should just remove https://github.com/ipfs/go-ipfs/commit/b688e72de05cef362e310c90f9968a0614830adf#diff-94bc6ab66c2700453221e08f66413d94R412

**Comment by travisperson** [comment]
Ah yes, the tests can definitely stay. Really just meant what you described above by removing that check.

As far as checking for unwanted fields, the only way I know how to do that is to decode the data into a `map[string]interface{}`, delete (or move) the known fields we want and then check for extras.

Is there a better way?

**Comment by jbenet** [comment]
> As far as checking for unwanted fields, the only way I know how to do that is to decode the data into a `map[string]interface{}`, delete (or move) the known fields we want and then check for extras.

that's all there is.

**Comment by whyrusleeping** [comment]
this has been fixed by ensuring that the difference between a nil array and a zero length array in go->protobuf is normalized
