### ISSUE TITLE
clear progress bar on exit

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1345]
progress bar sometimes lingers after exit:

```
> ipfs cat QmWmupGwtrGwbu8WL3prFkw4ChAeiYQqHfwRTvBnGhuh6S >/dev/null
75.28 MB / 90.41 MB [=========================================================>-----------] 83.27 % 1s
>
```
would be ideal to (a) stop the progress bar, (b) clear the line before (c) exiting.

**Comment by rht** [comment]
> progress bar sometimes lingers after exit
This could mean either the progress bar keeps adding up even after exit or it hangs there after exit.

> (b) clear the line before
The line is to be cleared (with '\b') after exit? But the elapsed time is useful info.
curl/wget retains the progress stat.

**Comment by jbenet** [comment]
> But the elapsed time is useful info.

Agreed. Maybe we can make it update one last time with all the correct information. that may be the easiest way.

**Comment by jbenet** [comment]
this keeps bugging me + confusing people

![](http://gateway.ipfs.io/ipfs/QmZjMzrgbiBYs6K97iUsEmiW22kXM62wPnaRtvcSBYMy4Q/cap.png)

**Comment by jbenet** [comment]
@ipfsbot pin -r QmZjMzrgbiBYs6K97iUsEmiW22kXM62wPnaRtvcSBYMy4Q

I wish o/ worked

**Comment by rht** [comment]
I am confused with the issue with progressbar staying after exit (check curl/wget, they retain the progressbar). There could be extra line saying "data transport/transfer done!" to avoid misunderstanding with the total estimated size.

**Comment by rht** [comment]
i c, like `ipfs add`'s behavior.

**Comment by jbenet** [comment]
> I am confused with the issue with progressbar staying after exit (check curl/wget, they retain the progressbar). There could be extra line saying "data transport/transfer done!" to avoid misunderstanding with the total estimated size.

yeah if the progress bar stays, it should be drawn to 100% before exiting. the problem now is that  (as the picture shows) the bars disappeared midway because the program exited before the bar was redrawn.

i think i'm a bit happier with the bar disappearing, though i'd also be ok with it staying (at 100%). it's not critical output to keep in general, because non-ttys shouldn't see it either. progress bar is mostly for users waiting on the process + "not knowing what it's doing".

thanks for fixing!! :+1:
