### ISSUE TITLE
Daemon doesn't cleanly shutdown

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/go-ipfs#1349]
After hitting ctrl-c, I get:

```
^C
Received interrupt signal, shutting down...
Publishing!
```

What's it publishing? 
I now have to hit ctrl-c again to stop it.

**Comment by wking** [comment]
On Tue, Jun 09, 2015 at 03:14:19PM -0700, Dylan Powers wrote:
> What's it publishing? 

I'd guess it's cautiously flushing the FUSE-mounted IPNS tree in case
there are local changes dirying it up.  But I also see this when there
haven't been recent IPNS/FUSE changes, and even when the FUSE mounts
are write-only or not mounted at all, so I don't really know.
