### ISSUE TITLE
.. links in http proxy borked unless url ends with a slash

### ISSUE THREAD

**Issue by JasonWoof** [ipfs/go-ipfs#1365]
To reproduce:

http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye

click b

click c

Now you should be at http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/b/c

click ".."

This takes you to

http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/

but should take you to http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/b or maybe http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/b/

Explanation: the ".." link goes to "./..". The browsers interpret this differently depending on whether the URL ends with a slash or not. When navigating deeper into the file tree (eg from b -> c) the links do not end with /, and after doing that, the "./.." doesn't go to the right place.

To be clear, the ".." link works fine for this url:

http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/b/c/

But not this one:

http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/b/c

(the only difference being whether there's a "/" at the end or not).

This is particularly problematic, because the http proxy is generating urls like the latter.

**Comment by wking** [comment]
On Fri, Jun 12, 2015 at 09:12:34AM -0700, Jason Woofenden wrote:
> To be clear, the ".." link works fine for this url:
> 
> http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/b/c/
> 
> But not this one:
> 
> http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/b/c
> 
> (the only difference being whether there's a "/" at the end or not).
> 
> This is particularly problematic, because the http proxy is
> generating urls like the latter.

Where's the code generating those URLs?  But this is a good argument
for having an option to suffix directory listings with slashes like
‘ls -p’ [1] in IPFS listing commands.  Related discussion in [2] and
following comments.

[1]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/ls.html#tag_20_73_04
[2]: https://github.com/ipfs/go-ipfs/pull/1348#issuecomment-111340373

**Comment by whyrusleeping** [comment]
https://github.com/ipfs/go-ipfs/blob/master/core/corehttp/gateway_handler.go#L456

**Comment by JasonWoof** [comment]
hmm... if you don't want to meddle with how the template is used, you could replace this line:

    <li><a href="./..">..</a></li>

with:

    <li><a href="{{ .path }}./..">..</a></li>

Bit of a hack, but it works.

**Comment by JasonWoof** [comment]
P.S. this works, because it transforms  ``b/c -> b/c./..``  and ``b/c/ -> b/c/./..`` both of which (in my chromium) resolve to ``b/``

**Comment by jbenet** [comment]
` b/c./..` works?

**Comment by JasonWoof** [comment]
yep! ``b/c./..`` resolves to ``b/``

That's the hack :) if there's no ``/`` at the end of the path, then the first ``.`` becomes (as far as the browser is concerned) part of the previous path segment (``c`` in this case)

**Comment by JasonWoof** [comment]
mouse over the links in the bottom/right quadrant to see how your browser resolves them: http://jsfiddle.net/ruuboj4x/

Source code is it the top/left

**Comment by jbenet** [comment]
Ah, right that makes sense nvm. 

My one worry is that it becomes root-specific -- i.e. the index changes based on the path you accessed it on. What other solutions can we try here?

**Comment by whyrusleeping** [comment]
wouldnt `<li><a href="./../">..</a></li>` work?

**Comment by jbenet** [comment]
@whyrusleeping i dont think so:

```
foo/bar/ + ./../ = foo/bar/./../ = foo/bar
foo/bar + ./../ = foo/bar./../ = foo/
```

**Comment by JasonWoof** [comment]
@whyrusleeping the browser adds that slash automatically anyway, so ``href="./../"`` behaves exactly like ``href="./.."``

@jbenet both your examples are wrong...

If your browser is at ``/foo/bar/``  and you click ``href="./../"`` you'll go to ``/foo``

If your browser is at ``/foo/bar`` and you click ``href="./../"`` you'll go to ``/``

To break down the latter... the browser first resolves the ``./`` part, to ``/foo`` because it thinks ``bar`` is a filename, thus the current directory is ``/foo``. Then it goes up one because of the ``../``, resulting in ``/``

These are the reasons why the current code is broken (why I filed this bug report)

My suggested (hacky) fix is to concatenate the current path with ``"./.."`` which makes the browser resolve the paths differently than if you just put ``./..`` or ``./../`` in the ``href=``. To be explicit:

If you click ``href="/foo/bar/./..`` you'll go to ``/foo/``

if you click ``href="/foo/bar./.."`` you'll go to ``/foo/``

In this case (catting the path/string together) the browser resolves the second one differently. It sees ``bar.`` as a single path segment (a directory name ending with ``.``) and then removes it when it processes the ``..`` at the end.

**Comment by JasonWoof** [comment]
Seems to me there are several options for improving this:

1.    the ``{{ .path }}./..`` hack above

2.    issue redirects when the HTTP proxy gets a request for a directory, and there's no slash at the end. Apache does this.

3.    make the template code more complex, so it generates ``../`` or ``./`` based on whether the url ends with a slash or not

4.    add some javascript that adjusts the link (to ``../`` or ``./``) based on whether the URL ends with a slash or not

**Comment by jbenet** [comment]
I think
>  (3.) make the template code more complex, so it generates ../ or ./ based on whether the url ends with a slash or not

is the safest thing

**Comment by JasonWoof** [comment]
option 2 (http redirect) is safe too.

option 3 (smarter template) has the advantage of making it easier to squish another bug: the ``..`` link should be removed completely when at a top-level directory (ie we should never provide a link to ``/ipfs/`` or ``/ipns/``

option 2 is slightly slower the first time you go to a directory without a slash at the end (browser redirect)

option 3 generates the same page at ``/foo/bar`` and ``/foo/bar/``, which is fetched/cached separately. You will hit both of these if you go up and down the tree. I think this extra bandwidth, latency and caching is why apache goes for option 2.

**Comment by jbenet** [comment]
:-1: on redirect. let's go with option (3.) here.
