### ISSUE TITLE
Read-only API

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1383]
Many use cases (eg. #1322) would love an exposed read-only API, in particular through the gateway.

We can do this a few different ways:
1. mount the readonly API on the normal Gateway endpoint (my preference) (easy)
2. create another, isolated endpoint for a readonly API. (medium)
3. implement auth on the API for writable commands, and open that up. (hard)

Regardless, when exposing these, we should expose:
- mainly read-only things that serve IPFS content `{cat, ls, refs, block {get, stat}, object {get, stat, links}}`
- _maybe_ expose internal node service state (e.g. {stats, bitswap, dht, id})
- _do not_ expose internal node variables (e.g. pins, keys, etc).

### Short term goals

if we go with (1.) above, let's:

- [ ] setup gateway to expose pieces of the API 
- [ ] expose `{cat, ls, refs, block {get, stat}, object {get, stat, links}}` via gateway

**Comment by harlantwood** [comment]
+1 for (1)

**Comment by Kubuxu** [comment]
This is already resolved, isn't it?

**Comment by harlantwood** [comment]
Yup, should be closed I believe.
