### ISSUE TITLE
Fix Daemon Exit 

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1384]
- today, when `ipfs daemon` receives SIGTERM, it first attempts to exit gracefully. it often doesn't quickly enough. we should fix this.
- when the user sends a _second_ SIGTERM, go-ipfs shuts down asap (ungracefully). this is mostly a hidden trick that most people don't _know_ (but likely find quickly enough).
- this -- however -- is annoying for process controllers, because they just send SIGTERM once

I think that:
- we should improve ipfs graceful exit.
- we should also make ipfs respect the first SIGTERM. it could run its own timer, and if it hasn't exited gracefully fast enough (10s?), triggers the ungraceful exit.

**Comment by whyrusleeping** [comment]
Going to close this issue. If specific goroutines are causing daemon exit to hang, lets open issues for those specifically ('actionable' being the keyword here)

**Comment by Kubuxu** [comment]
Also most daemon controllers now a days will kill target multiple times if it doesn't close.
