### ISSUE TITLE
memory leak from http gateway

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1387]
If a client requests a file from the http gateway, and only part of the file is available on the network, the request will hang and never finish, and never release block data from memory.

This is because the context used in an http request does not have a timeout, it waits for the handler func to exit, which wont happen because the `Read` call its making is hung.

**Comment by cryptix** [comment]
This might be a good chance to revisit the [close notifier](http://godoc.org/net/http#CloseNotifier) and use it to cancle the request context. I [started](https://github.com/ipfs/go-ipfs/compare/wip/ctxCloseNotifier#diff-4df02c629d914567df45314a464367b9R106) some work on it but it is a fairly easy introduction if somebody else wants to take a stab.

**Comment by lgierth** [comment]
We've wired context with gateway, resolver, and dagreader.
