### ISSUE TITLE
IPFS add -r returns a "no such file or directory" error. 

### ISSUE THREAD

**Issue by sroerick** [ipfs/go-ipfs#1409]
Using FreeBSD

While adding files, "ipfs add -r" discovered a lockfile that it was unable to parse.

The lockfile contained a pipe to localhost. details can be found in irc logs beginning here: https://botbot.me/freenode/ipfs/2015-06-21/?msg=42494305&page=3

**Comment by jbenet** [comment]
@whyrusleeping we should get metadata in place to fix these problems once and for all.

not sure what we should do with pipes and so on. what do other systems do for {pipes, fifos, etc}?

**Comment by whyrusleeping** [comment]
it appears that git just ignores pipes

**Comment by wking** [comment]
On Sun, Jun 21, 2015 at 06:37:25AM -0700, sroerick wrote:
> While adding files, "ipfs add -r" discovered a lockfile that it was
> unable to parse.
> 
> The lockfile contained a pipe to localhost.

Work on a fix (actually looking at the file's mode ;) in #1413.

**Comment by jbenet** [comment]
#1642

**Comment by whyrusleeping** [comment]
we now have better handling of these types of issues.
