### ISSUE TITLE
mark and sweep GC

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1416]
pinning right now is very fragile, and this is entirely due to the fact that we store indirect pins as they come in, and then only at the end (once we know the hash) can we set the indirect pin. If the pin operation fails, we gets lots of garbage indirect pins that are currently impossible to clean up. The proposed solution is to implement a mark and sweep garbage collection which would only add a pin to the root of a recursively pinned object, and on GC, check the entire tree against the remove list. (or whatever, google mark and sweep if you want a real explanation)

**Comment by wking** [comment]
On Mon, Jun 22, 2015 at 01:35:20PM -0700, Jeromy Johnson wrote:
> (or whatever, google mark and sweep if you want a real explanation)

I'm not a garbage-collection expert, but Googling mark-and-sweep got
me to this tri-color marking explanation [1], which looks about as
easy to implement and is non-blocking.

[1]: https://en.wikipedia.org/wiki/Tracing_garbage_collection#Tri-color_marking

**Comment by jbenet** [comment]
@wking great, that's so nice and simple.

**Comment by jbenet** [comment]
in our case, we could "blacken" down from the pinning root, and then gc all objects left.
