### ISSUE TITLE
Simple way for local ipfs cli to connect to remote ipfs daemon

### ISSUE THREAD

**Issue by ehd** [ipfs/go-ipfs#1421]
Paraphrasing @jbenet:

Being able to connect to remote ipfs daemons

- via a flag: `ipfs --api-addr=/ip4/... <cmd>`
- via an environment variable: `IPFS_API_ADDR=/ip4/... ipfs <cmd>`

would be ideal.

**Comment by whyrusleeping** [comment]
i've wanted this for probably 8 months now

**Comment by NodeGuy** [comment]
Is there a non-simple way to do it today?

**Comment by almereyda** [comment]
I am using IPFS in a local area network as a general data dump. This functionality would allow for easier archiving of connected nodes' data.

Is there a known workaround to use the CLI to recursively add directories to a remote daemon?

**Comment by whyrusleeping** [comment]
You can now write the remote multiaddr into the `$IPFS_PATH/api` file.

**Comment by Kubuxu** [comment]
Here is a script that automates it: https://gist.github.com/Kubuxu/0cafd6dc71114349875827c2c379fa1f
