### ISSUE TITLE
systemd support

### ISSUE THREAD

**Issue by slang800** [ipfs/go-ipfs#1430]
`systemctl <command> ipfs` doesn't work, which makes this a pain to manage as a daemon

**Comment by jbenet** [comment]
@slang800 you probably want a systemd script, kind of like these initd scripts:
- http://gateway.ipfs.io/ipfs/QmbYCwVeA23vz6mzAiVQhJNa2JSiRH4ebef1v2e5EkDEZS/ipfs.conf
- https://github.com/dylanPowers/ipfs-linux-service/blob/master/init.d/ipfs

**Comment by sroracle** [comment]
Here's a rudimentary systemd service file that I use:

```
[Unit]
Description=IPFS daemon
After=network.target
RequiresMountsFor=%h

[Service]
User=%u
ExecStart=/usr/bin/ipfs daemon

[Install]
WantedBy=multiuser.target
```

Place this file in `/etc/systemd/user` and start with `systemctl --user start ipfs`. This assumes the user already ran `ipfs init`.

**Comment by jbenet** [comment]
@sroracle 

it would be amazing to have an "example" in http://ipfs.io/docs/examples (https://github.com/ipfs/examples) that goes over systemd, initd, and other services.

(also, nice NERV avatar :) )

**Comment by jbenet** [comment]
@sroracle 

also, maybe: 

> Place this in ~/.config/systemd/user/ipfs.service (create the directories as necessary) and start with systemctl --user start ipfs. This assumes the user already ran ipfs init.

this could be a `sh` script

**Comment by sneak** [comment]
The examples are somewhat poor; this one is better:

```
[Unit]
description=ipfs p2p daemon
After=network.target
Requires=network.target

[Service]
Type=simple
User=ipfs
RestartSec=1
Restart=always
PermissionsStartOnly=true
Nice=18
StateDirectory=/var/lib/ipfs
Environment=IPFS_PATH=/var/lib/ipfs
Environment=HOME=/var/lib/ipfs
LimitNOFILE=8192
Environment=IPFS_FD_MAX=8192
EnvironmentFile=-/etc/sysconfig/ipfs
StandardOutput=journal
WorkingDirectory=/var/lib/ipfs
ExecStartPre=-adduser --system --group --home /var/lib/ipfs ipfs
ExecStartPre=-mkdir /var/lib/ipfs
ExecStartPre=-/bin/chown ipfs:ipfs /var/lib/ipfs
ExecStartPre=-/bin/chmod ug+rwx /var/lib/ipfs
ExecStartPre=-chpst -u ipfs /usr/local/bin/ipfs init --profile=badgerds
ExecStartPre=-chpst -u ipfs /usr/local/bin/ipfs config profile apply server
ExecStartPre=-chpst -u ipfs /usr/local/bin/ipfs config profile apply local-discovery
ExecStartPre=-chpst -u ipfs /usr/local/bin/ipfs config Datastore.StorageMax "4000GB"
ExecStart=/usr/local/bin/ipfs daemon --enable-namesys-pubsub --enable-pubsub-experiment

[Install]
WantedBy=multi-user.target
```

**Comment by Stebalien** [comment]
I have an initial PR (https://github.com/ipfs/go-ipfs/pull/5514) to add systemd and socket activation support. I'd like to *avoid* making the example service file too opinionated unless we provide both a system and a user service file along with instructions.

**Comment by feilongfl** [comment]
a sample for `archlinux`, base on @sneak version

```
[Unit]
description=ipfs p2p daemon
After=network.target
Requires=network.target

[Service]
Type=simple
User=ipfs
RestartSec=1
Restart=always
PermissionsStartOnly=true
Nice=18
StateDirectory=/home/ipfs
Environment=IPFS_PATH=/home/ipfs
Environment=HOME=/home/ipfs
LimitNOFILE=8192
Environment=IPFS_FD_MAX=8192
EnvironmentFile=-/etc/sysconfig/ipfs
StandardOutput=journal
WorkingDirectory=/home/ipfs
ExecStartPre=-groupadd ipfs
ExecStartPre=-useradd -r -g ipfs -d /home/ipfs ipfs
ExecStartPre=-mkdir /home/ipfs
ExecStartPre=-/bin/chown ipfs:ipfs /home/ipfs
ExecStartPre=-/bin/chmod ug+rwx /home/ipfs
ExecStartPre=-chpst -u ipfs /usr/bin/ipfs init --profile=badgerds
ExecStartPre=-chpst -u ipfs /usr/bin/ipfs config profile apply server
ExecStartPre=-chpst -u ipfs /usr/bin/ipfs config profile apply local-discovery
ExecStartPre=-chpst -u ipfs /usr/bin/ipfs config Datastore.StorageMax "2GB"
ExecStart=/usr/bin/ipfs daemon --enable-namesys-pubsub --enable-pubsub-experiment --enable-gc

[Install]
WantedBy=multi-user.target

```

**Comment by Ericson2314** [comment]
@Stebalien's #5514 mentioned above he closed, but his #6675 is now merged!

**Comment by RubenKelevra** [comment]
@Ericson2314 is there a reason why you warm up this old and closed ticket? :)

**Comment by Ericson2314** [comment]
I posted here because I landed here while looking for systemd support, the information was out of date, and the situation has *improved* since. I figured I would by leaving a comment for future searchers, I would save them some trouble.

I usually figure this is good practice (especially when it's good news). And since the issue had been updated with new information before (by an employee of Protocol Labs, no less), I figured it was deemed good practice here to.

**Comment by caryyu** [comment]
Ubuntu 20.04.2 LTS

/home/ubuntu/.config/systemd/user/ipfs.service

```ini
[Unit]
Description=IPFS Daemon
After=network.target

[Service]
Environment=IPFS_PATH=/home/ubuntu/.ipfs
ExecStart=/usr/local/bin/ipfs daemon --init --migrate
StandardOutput=journal
Restart=on-failure
KillSignal=SIGINT

[Install]
WantedBy=multi-user.target
```

systemctl --user daemon-reload
systemctl --user start ipfs

**Comment by RubenKelevra** [comment]
Hey @caryyu,

you can find the systemd service files for go-ipfs [in misc/systemd](https://github.com/ipfs/go-ipfs/tree/master/misc/systemd).

I recommend the hardened version if you don't need FUSE.

**Comment by alexs0x01** [comment]
> Ubuntu 20.04.2 LTS
> 
> # System-Scoped
> /etc/systemd/system/ipfs.service
> 
> ```ini
> [Unit]
> Description=IPFS Daemon
> After=network.target
> 
> [Service]
> User=ubuntu
> Group=ubuntu
> Environment=IPFS_PATH=/home/ubuntu/.ipfs
> ExecStart=/usr/local/bin/ipfs daemon --init --migrate
> StandardOutput=journal
> Restart=on-failure
> KillSignal=SIGINT
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> sudo systemctl daemon-reload sudo systemctl start ipfs sudo systemctl enable ipfs - for auto-start by reboot
> 
> # User-Scoped
> /home/ubuntu/.config/systemd/user/ipfs.service
> 
> ```ini
> [Unit]
> Description=IPFS Daemon
> After=network.target
> 
> [Service]
> User=ubuntu
> Group=ubuntu
> Environment=IPFS_PATH=/home/ubuntu/.ipfs
> ExecStart=/usr/local/bin/ipfs daemon --init --migrate
> StandardOutput=journal
> Restart=on-failure
> KillSignal=SIGINT
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> systemctl --user daemon-reload systemctl --user start ipfs

The IPFS documentation recommends that the daemon be ran under user-scope. The system-scope example could put your system at risk of being compromised.
