### ISSUE TITLE
mDNS is broadcasting all of the IP's that a peer is dialed to

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#1434]
Want to confirm that this is the intended behaviour:
https://github.com/ipfs/go-ipfs/blob/master/p2p/discovery/mdns.go#L71-L79

As @jbenet pointed out, this causes privacy + service enumeration issues.

**Comment by jbenet** [comment]
@diasdavid ohh

> so in mDNS e not only announce ourselves, but the IP’s of the peers we are also connected

thought you meant "broadcast the IPs of _all_ of our peers". 

so, this is intened for now, yes. It _is_ a privacy concern (not one as bad as revealing _all_ the addresses of _all_ the peers we know). And it should be disableable somehow, but i think that mDNS _in general_ is a privacy concern, and that is already disableable (via config). I'm not sure if anyone who would want to run mDNS would care about revealing all the interfaces. it will typically be laptops connected to a LAN, and those typically dont have more _interesting_ interfaces. 

Also, this information (revealing own IPs) is what's done when connecting to another peer directly, even without mDNS. (yep, a privacy concern). so if/when we add a setting to silence that behavior (trading off ease of use for privacy), we can then add a setting to change it here too.

**Comment by diasdavid** [comment]
right! Had read that wrong. I really thought it was "announcing the IPs of all of peers". Thanks @jbenet :)
