### ISSUE TITLE
mDNS doesn't work on Mac OS X

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#1435]
It is something related with the mDNS library being used, since it works fine on Linux and other libraries (for example [multicast-dns](https://www.npmjs.com/package/multicast-dns)) work fine.

For ref: https://github.com/hashicorp/mdns/issues/41

**Comment by jbenet** [comment]
mDNS works for me on OS X (my nodes are able to connect to each other without talking to a bootstrap server) Do you have a script to repro that doesn't work on OSX but works on Linux?



—

**Comment by diasdavid** [comment]
Interesting, it didn't work on my Mac nor on @whyrusleeping's Mac.

Example here: https://github.com/hashicorp/mdns/pull/40/files

To try it from Node

```javascript
mdns = require("multicast-dns")()

var serviceTag = '_foobar._tcp' // or 'discovery.ipfs.io.local for the IPFS service'

mdns.on('response', function(resp) {
  console.log('got a response: ', resp)
})

mdns.query({
  questions:[{
    name: serviceTag,
    type: 'A' // 'PTR' if looking for discovery.ipfs.io.local
  }]
})
```

**Comment by jbenet** [comment]
We verified it works on OSX. closing.
