### ISSUE TITLE
listen address output twice

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1442]
started up a new node and saw this oddity:

```
[whyrusleeping@why2 ~]$ ipfs daemon 2> ipfs.log
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/45.55.196.28/tcp/4001
Swarm listening on /ip4/45.55.196.28/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
```

the `/ip4/45.55.196.28/tcp/4001` is listed twice. Not sure why

**Comment by sujaypat** [comment]
Would it make sense to make addrs in [printSwarmAddrs](https://github.com/ipfs/go-ipfs/blob/master/cmd/ipfs/daemon.go#L498) a map to handle duplicates? Also, what's the purpose of sorting addrs?
