### ISSUE TITLE
ipfs add --name (like -w but with a filename)

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1445]
when adding files (our streams of data) it is nice to be able to set a filename. for example:

```
> head -c 1048576 /dev/random | ipfs add --name "1MB"
added QmZbe1fuZmqaHUP8cjoNZE88T4UPM6oG55eS8QqY9opmHz/1MB 1MB
```

Which is equivalent to:

```
> head -c 1048576 /dev/random >1MB
> ipfs add -w 1MB
added QmZbe1fuZmqaHUP8cjoNZE88T4UPM6oG55eS8QqY9opmHz/1MB 1MB
```

If we can re-appropriate `-n`, it would be nice. `-n` is not the best shorthand for `--only-hash`

**Comment by jbenet** [comment]
@whyrusleeping can we rebind `-n`? maybe   `--only-hash, -y` and `--name, -n` ?

**Comment by whyrusleeping** [comment]
:+1:

**Comment by Stebalien** [comment]
There's now a `--stdin-name` flag.
