### ISSUE TITLE
ipfs-add: Disable progress bar

### ISSUE THREAD

**Issue by kyrias** [ipfs/go-ipfs#1452]
I run `ipfs add` through fabric in my deploy scripts for my website, but due to the progress bar I've had to disable printing anything while running `ipfs add`. This is suboptimal though, since then it's impossible to know what's happening right now, if anything at all.

**Comment by whyrusleeping** [comment]
@kyrias run `ipfs add -q`

**Comment by kyrias** [comment]
Closer, but I'd want the filenames to be listed as well. But I guess that that's better for now, thanks.

**Comment by jbenet** [comment]
@kyrias would you prefer:

- a cli option to disable the progress bar for this run
- a config var to disable the progress bar globally

?

**Comment by kyrias** [comment]
A CLI flag would be most useful to me, but I could work with both. :smile:

**Comment by darkstar** [comment]
Why not just disable the progress bar when stdout is not a TTY?

**Comment by jbenet** [comment]
Yeah we should do that too



—

**Comment by jbenet** [comment]
still needs to happen.
- [ ] disable the progress bar when stdout is not a TTY
- [ ] maybe add `--no-progressbar` flag.

**Comment by whyrusleeping** [comment]
you can now do `--progress=false` to omit the progress bar but retain filenames
