### ISSUE TITLE
raise bitswap worker limits

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1457]
I think better limits are:
- [ ] provides workers at ~200
- [ ] task workers at `len(partners) * 4`

Yes, these are big. goroutines are cheap if we only use them when we need to. we should not pre-allocate the goroutines but allocate them as needed instead (only bounding their creation with ratelimiter or something).

---

A better approach would rework how sending operates to use only 1 stream (and thus 1 goroutine) per bitswap peer, sending blocks sequentially. reasoning is that if one block is not making fwd progress, sending more will not help. Since there's no need to wait for an ack, many blocks can be "in flight" at once, so bandwidth can be saturated just fine with _one_ stream.

**Comment by whyrusleeping** [comment]
the bitswap code has been reworked to reuse a single stream per peer.
