### ISSUE TITLE
move gateway index page to 

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1459]
move gateway assets:
- [ ] https://github.com/ipfs/go-ipfs/blob/master/core/corehttp/gateway_indexPage.go
- [ ] https://github.com/ipfs/go-ipfs/tree/master/assets/gw-assets

to https://github.com/ipfs/dir-index-html so we can work on it there.

**Comment by jbenet** [comment]
@rht could you take care of this?

**Comment by rht** [comment]
I need more context. Those are go-specific template files, then why are they moved to a new repo?

**Comment by jbenet** [comment]
@rht i dont mean the go files necessarily, i mean the html. i want to be able to work on the html parts on that repo, and then just include it (with gx or with git?) here

**Comment by rht** [comment]
Can be closed.

**Comment by rht** [comment]
(here goes)
