### ISSUE TITLE
ipns_test.TestMultiWrite on OSX

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#147]
`ipns_test.TestMultiWrite` on OSX fails. see:

- https://gist.github.com/jbenet/562393fec9911302b3ab
- https://botbot.me/freenode/ipfs/2014-10-08/?msg=23135540&page=2 (read up)
- https://github.com/bazillion/fuse/issues/44

**Comment by jbenet** [comment]
Does this exist still? does it fail?

**Comment by diasdavid** [comment]
Is this still reproducible? Closing (old issue), reopen as needed.
