### ISSUE TITLE
Spikes in the number of goroutines

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#1470]

**Comment by lgierth** [comment]
One clue I've been seeing is that the daemon takes minutes to terminate, during these goroutine spikes.

**Comment by jbenet** [comment]
Interesting. we ought to get a goroutine dump during one of these

**Comment by whyrusleeping** [comment]
the other day i was really wanting for goprocess to have named children, so you could somehow see which child routines were taking a long time to complete.

**Comment by whyrusleeping** [comment]
idea: goprocess could catch `SIGQUIT` print out the process tree (names included) and *then* print out the full program stack dump. and then `os.Exit(1)` or something

**Comment by jbenet** [comment]
> print out the process tree (names included)

i think this would be a very useful thing to have. particularly if we have a way of outputing dot syntax and we can generate a dag vis that shows what we're wiring up and why its wrong.

**Comment by lgierth** [comment]
fixxxed <3<3<3
