### ISSUE TITLE
test_kill_repeat_10_sec $IPFS_PID takes a long time

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1476]
when running sharness tests manually (with -v) i notice that the final 'kill the daemon' test case takes an unnecessarily long time. It would be great if someone could investigate this further.

**Comment by jbenet** [comment]
Yep. 

i think it's the slow shutdown of the daemon in general

**Comment by whyrusleeping** [comment]
ah, i see, it sends a single kill and then waits ten seconds. hrm...

**Comment by whyrusleeping** [comment]
I beleive ive fixed this
