### ISSUE TITLE
/api/v0/refs return invalid streamed JSON

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/go-ipfs#1477]
For instance, `http://127.0.0.1:5001/api/v0/refs?arg=QmS2HL9v5YeKgQkkWMvs1EMnFtUowTEdFfSSeMT4pos1e6` will return

```
{
  "Ref": "QmSQtihzZT8jyThuXqtSLnouDov9nxypqZh74MHQoMHLeF\n",
  "Err": ""
}{
  "Ref": "QmNh5CNBdFkVsALDqzU6AvbFAJd8LpjBV7voojQq95nKDA\n",
  "Err": ""
}{
  "Ref": "QmWpjY3EJgAQ95HVcjuQDtqyhofWoQDxxwEhmu2BnwXqDj\n",
  "Err": ""
}{
  "Ref": "QmVpzYsqP1P6t3PXJoX3VGzYUxNfiPRr9ChWaq5sV7K5Vc\n",
  "Err": ""
}
```

To be valid JSON, this list need to be wrapped inside [] and comma separated.
```
[
	{
	  "Ref": "QmSQtihzZT8jyThuXqtSLnouDov9nxypqZh74MHQoMHLeF\n",
	  "Err": ""
	},
	{
	  "Ref": "QmNh5CNBdFkVsALDqzU6AvbFAJd8LpjBV7voojQq95nKDA\n",
	  "Err": ""
	},
	{
	  "Ref": "QmWpjY3EJgAQ95HVcjuQDtqyhofWoQDxxwEhmu2BnwXqDj\n",
	  "Err": ""
	},
	{
	  "Ref": "QmVpzYsqP1P6t3PXJoX3VGzYUxNfiPRr9ChWaq5sV7K5Vc\n",
	  "Err": ""
	}
]
```

Also note the `\n` in the end of each hash.

**Comment by whyrusleeping** [comment]
@MichaelMure its a stream of objects, so it doesnt need to be surrounded by brackets, but we do need the newlines to help delimit

**Comment by MichaelMure** [comment]
Ok, so JSON streaming is actually a thing (https://en.wikipedia.org/wiki/JSON_Streaming), I didn't know.

To comply with the wikipedia description, I would say that:

- a new line is needed between each JSON object
- `\n` at the end of each hash need to be removed

What determine that a particular command is streamed or not ?

**Comment by jbenet** [comment]
> - a new line is needed between each JSON object

I do prefer ndjson (newline-delimited), but "Concatenated JSON" is a thing (as wikipedia points out). so we can do either as long as we agree.

we'd also need to make sure the json stringifier does not pretty-print. no unescaped newlines. (this is why concatenated json is perhaps safer.

> - \n at the end of each hash need to be removed

yeah i dont know why that's there.

**Comment by MichaelMure** [comment]
I guess this one can be closed.
