### ISSUE TITLE
Identify should not have to announce available protocols with the addition of `multistream-select` `ls`

### ISSUE THREAD

**Issue by daviddias** [ipfs/go-ipfs#1484]
@whyrusleeping @jbenet Do still need this: https://github.com/ipfs/go-ipfs/blob/master/p2p/protocol/identify/pb/identify.proto#L26

**Comment by jbenet** [comment]
as you mention, with multistream ls, we could get rid of it. (in that case, comment it out in the protobuf and mark as deprecated so we dont reuse that tag). 

---

OTOH, if we keep it around it may help listing with `ipfs id` and the Home page in the webui:

![](http://gateway.ipfs.io/ipfs/QmdK5isFSDY96GQd4YcBtYFKu39RpgzfoSkBrbGcdgLwcd/cap.png)

**Comment by Kubuxu** [comment]
Not relevant anymore.
