### ISSUE TITLE
Use domain names instead of IPs for bootstrap

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#1485]
The default config's bootstrap nodes should be specified as domain names such as `bootstrap1.ipfs.io`, `bootstrap2.ipfs.io` and so on.
- [ ] create domains bootstrap1 through bootstrap9
- [ ] change default config

**Comment by jbenet** [comment]
@lgierth SGTM. and this is fine because we have the peerIDs hardcoded. we incur no impersonation risk from DNS. (we DO incur DNS silencing risk. maybe we should keep one or two hardcoded IPs?).

**Comment by whyrusleeping** [comment]
can multiaddr even handle dns?

**Comment by jbenet** [comment]
not yet, but we can add it.

**Comment by sivachandran** [comment]
@jbenet/@whyrusleeping can you tell what is required to support dns in bootstrap?

**Comment by Kubuxu** [comment]
I would be for keeping at least one bootstrap node in the list as plain IP just in case something goes wild (like DNS failure).

**Comment by lgierth** [comment]
@sivachandran mainly we need DNS support in multiaddr: jbenet/go-multiaddr#7

Once that is available, we'll probably have to make a few amendments to go-ipfs to also support multiaddrs starting in /dns instead of just /ip4 and /ip6.

**Comment by lgierth** [comment]
And yes we should still keep at least a few IP addresses in there -- there was a DNS outage just a few weeks ago and having IPs in there saved the network.

**Comment by whyrusleeping** [comment]
also using dns gets tricky, the record must only point to a single address otherwise the keys won't match

**Comment by Kubuxu** [comment]
What about something like dnslink but for multiaddr? You would specify whole multiaddr in DNS record.

**Comment by lgierth** [comment]
@Kubuxu yes, dnsaddr \o/ I've had this laying around in my notes for a few weeks:

```
# dnsaddr

dnsaddr is to multiaddr, what /ipns/domain.tld is to /ipfs

TXT bootstrap.ipfs.io dnsaddr=/ip6/1:2:3::4/tcp/4737/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3
TXT bootstrap.ipfs.io dnsaddr=/ip6/5:6:7::8/udp/4737/utp/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z

$ dnsaddr bootstrap.ipfs.io /ip6/tcp/ipfs /ip6/udp/utp/ipfs
/ip6/1:2:3::4/tcp/4737/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3
/ip6/5:6:7::8/udp/4737/utp/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z
```

**Comment by lgierth** [comment]
I've made a tool called `madns` as part of [go-multiaddr-dns](https://github.com/multiformats/go-multiaddr-net) which resolves /dnsaddr multiaddrs.

The next step is integrating this into ipfs and libp2p.

**Comment by whyrusleeping** [comment]
This is madness!

**Comment by bertrandfalguiere** [comment]
I think bootstrap via DNS is now implemented and not experimental.

I think this issue can be closed?
