### ISSUE TITLE
Possible FD leak

### ISSUE THREAD

**Issue by Luzifer** [ipfs/go-ipfs#1489]
As a user of `v0.3.5` from homebrew I'm seeing an increase of errors after the daemon is running for some time (several days):

```
Failed to write to log, can't read log file directory: open /Users/luzifer/.ipfs/logs: too many open files
```

The error is repeating several hundred times and does only solve when restarting the daemon.

**Comment by jbenet** [comment]
Interesting. Could you try latest? (Logs no longer written out). Also what's the ulimit?



—

**Comment by Luzifer** [comment]
Okay now things are starting to get strange:

```
[00:30] luzifer ~> ulimit
unlimited
```

Starting daemon from fresh master (8668f40) and keep watching whether it comes up again.

**Comment by jbenet** [comment]
@Luzifer `brew`, right? so, macs have a bunch of ways to set FDs: http://superuser.com/a/303058

**Comment by Luzifer** [comment]
Yep but manually started from my shell it should have my limit, not the one from `launchd`… (Still found no way to get the stdout of processes in `launchd` like in Ubuntus `upstart`)

**Comment by jbenet** [comment]
@Luzifer i think you can ask launchd to log out to a file.

```xml
<key>StandardOutputPath</key>
<string>/var/log/nginx.log</string>
```


http://superuser.com/questions/726906/osx-mavericks-how-can-i-make-a-webserver-launch-at-boot-and-listen-to-port-80-w

**Comment by whyrusleeping** [comment]
@Luzifer has this been resolved?

**Comment by NeoTeo** [comment]
Possibly related, my ipfs daemon window is flooded with similar messages:
ERRO[09:09:10:000] too many open files, retrying in %dms200      module=flatfs

**Comment by tkawachi** [comment]
Same here

```
ERRO[00:46:12:000] too many open files, retrying in %dms0        module=flatfs
ERRO[00:46:12:000] too many open files, retrying in %dms100      module=flatfs
ERRO[00:46:12:000] too many open files, retrying in %dms0        module=flatfs
ERRO[00:46:12:000] too many open files, retrying in %dms100      module=flatfs
ERRO[00:46:12:000] too many open files, retrying in %dms200      module=flatfs
ERRO[00:46:12:000] too many open files, retrying in %dms200      module=flatfs
```

```
$ ipfs version
ipfs version 0.3.8-dev
```

**Comment by longears** [comment]
Same error messages here. (`ipfs version 0.3.10-dev` prebuilt binary from website, OSX Yosemite 10.10.5)
I was able to resolve it:
```
ulimit -a        # see that the default number of file descriptors is 256
ulimit -n 2048   # increase
ulimit -a        # verify the increase worked
ipfs daemon
```
Note that `ulimit` only affects the current shell.
Is this something ipfs can set by itself when it launches?  If not, maybe the OSX version should ship with a shell script that sets the fd limit and then launches ipfs?

**Comment by whyrusleeping** [comment]
yeah, we don't want ipfs to start mucking with system settings. shipping a script might be a good idea

**Comment by jbenet** [comment]
in most cases, i think increasing the ulimit on its own is probably ok. systems still have hard caps, and the perms could be removed from the user given to ipfs if people actually care about this. (and we could have a config to turn it off).

lots of osx users will never start ipfs from a terminal. it would be nice if ipfs always worked, the way bittorrent clients always work (im sure bittorrent clients muck with their ulimits too).

**Comment by jbenet** [comment]
if we go with "the script route" then we should switch _all_ uses of go-ipfs to always start with that script, to avoid the complexity of users sometimes using it and sometimes not with bugreports now having to figure out if they were using the script or not. (this would make it so "running ipfs" effectively becomes "running the ipfs luncher script", which is ok but then is beside the point and the previous suggestion (just have go-ipfs set the ulimit) is likely less complex in the long run

**Comment by whyrusleeping** [comment]
ipfs now by default raises the default file descriptor limit to 1024 if it is lower than 1024 on startup
