### ISSUE TITLE
random API failures

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1490]
I'm not really sure what causes it, but i will occasionally get random failures through the API such as:

```
whyrusleeping@idril ~/c/ipfs-bot (master)> gx publish
ERROR: Post http://localhost:5001/api/v0/object/patch?arg=QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn&arg=add-link&arg=ipfs-bot&arg=QmVTiPRV9LBpfyQzKTX2dPpJ8h4E4gz791Dax5A82UC6pG&enc=json&stream-channels=true: EOF
```

This happens with pinbot as well, so its likely something to do with ipfs-shell. But ipfs shell just wraps the command libs http code.

**Comment by jbenet** [comment]
I see them on ipfs cli too. They're recent. Not sure what's up.



—

**Comment by whyrusleeping** [comment]
thats troubling... we should bump up the error logging in the commands lib

**Comment by whyrusleeping** [comment]
Fixed in api refactor
