### ISSUE TITLE
ci testutil needs to detect circle CI

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1493]
we have tests that change their behaviour when they detect a CI environment, we should probably let this code know about circleCI. 

https://github.com/ipfs/go-ipfs/tree/master/util/testutil/ci

**Comment by whyrusleeping** [comment]
closed by #1499, the generic `CI` variable wasnt being looked for.

**Comment by jbenet** [comment]
:+1:
