### ISSUE TITLE
api _sometimes_ screws up

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1509]
see asciinema 
https://asciinema.org/a/azdydoafop175o9l1mzg2fs0w

**Comment by whyrusleeping** [comment]
that didnt really look like a sometimes to me... what did you do to that poor daemon?

**Comment by jbenet** [comment]
i think this was the failures we've been seeing. 

@whyrusleeping, 

@zignig reports that the API failures are still there. or rather, there when he uses `http` package directly. it's not great that our API now fails with the standard library's http client. we should discuss whether to ship this, or try to fix it. (we could ask people to use ipfs-shell for now...)

@wking you recently mentioned a good idea re: side-stepping multipart and doing independent http requests. how do you see this working for add?

**Comment by whyrusleeping** [comment]
@jbenet go's http library is broken, I can get it to fail against any http server by making requests quickly enough and not closing response bodies.

**Comment by jbenet** [comment]
> go's http library is broken, I can get it to fail against any http server by making requests quickly enough and not closing response bodies.

Can you get it to fail if you DO close response bodies?

**Comment by jbenet** [comment]
> The client must close the response body when finished with it

The http lib is clear on this. I don't think it's an error. to reuse the pool you need to close responses. why is that unacceptable?

**Comment by whyrusleeping** [comment]
@jbenet the pool reuse has a race condition.

**Comment by whyrusleeping** [comment]
I *think* this can be closed? cc @jbenet

**Comment by jbenet** [comment]
looks ok to me
