### ISSUE TITLE
Try to connect to the API instead of looking for a repo lock to determine daemon status 

### ISSUE THREAD

**Issue by wking** [ipfs/go-ipfs#1514]
With an IPFS daemon running in a local container (so not out of my host `~/.ipfs`), I can't run other IPFS commands from the host:

    $ ipfs swarm peers
    Error: This command must be run in online mode. Try running 'ipfs daemon' first.
    Use 'ipfs swarm peers --help' for information about this command

We shouldn't be checking the repo lock to determine if the daemon is up (it might even be on a completely separate host from the client), we should just try to connect to the configured `Addresses.API`.

**Comment by jbenet** [comment]
@wking two things
-  the repo spec (which is a bit out date in other respects (pinning in 0.4.0)) calls for an `api` file  -- https://github.com/ipfs/specs/tree/master/repo/fs-repo#api -- which is to have the URL of the api.
- i dont think trying to access the API at the well known location is correct. could be a _different_ daemon -- which would conflict with the default value of `$IPFS_PATH`. so the below would return different things if other daemons started up behind the scenes, which is not right. we should respect `$IPFS_PATH`. 
- that said, we _should_ make it easy to connect to APIs. maybe with: `ipfs --api=<addr> <cmd>` and maybe even `IPFS_API=<addr> ipfs <cmd>`.
- for docker, there's `docker exec`, not sure if there's something like it for `runC`, suspect not.

```sh
# suppose another daemon exists in the background
> hash=$(echo "hello" | ipfs add -q | tail -n1)
> kill all containers
> ipfs cat $hash
blockstore: not found
```

**Comment by whyrusleeping** [comment]
@jbenet you PR'ed something recently like a `--api` flag, right? does that address this issue?

**Comment by jbenet** [comment]
Yep, #1598
