### ISSUE TITLE
ipfs repo gc does not fully reverse ipfs add

### ISSUE THREAD

**Issue by rht** [ipfs/go-ipfs#1515]
```
. lib/test-lib.sh
random 100000 41 >gc &&
du -sb "$IPFS_PATH/blocks" | awk "{print \$1}" >expected &&
hash=`ipfs add -q gc` &&
ipfs pin rm -r $hash &&
ipfs repo gc &&
du -sb "$IPFS_PATH/blocks" | awk "{print \$1}" >actual &&
test_cmp expected actual
```

will fail with 4kB or 16 kB of residue.

**Comment by jbenet** [comment]
Hmm seems like a bug to me. thoughts @whyrusleeping ?

**Comment by whyrusleeping** [comment]
odd. this is a really good test to have. we should run it against dev0.4.0 and see how well the mark and sweep GC fares.

**Comment by rht** [comment]
Now this is down to ~O(6 bytes) of residue.

**Comment by jbenet** [comment]
nice! that should be fine then.

also, do we know what improved?

**Comment by rht** [comment]
Hmm...Need tests to see more changes.

The 6 bytes could be due to the irreversible hash key size errs? https://github.com/ipfs/go-ipfs/issues/1554

**Comment by jbenet** [comment]
maybe but not sure
