### ISSUE TITLE
Add /ipns/local (or equivalent) for quick access to the local namespace

### ISSUE THREAD

**Issue by rschulman** [ipfs/go-ipfs#1517]
It would be convenient to have a shortcut path to the local ipns namespace to avoid the extra steps of looking up the local ID then putting that into the path. It would make sense since the local namespace will likely be the most often used, I would think.

Thoughts, @jbenet ?

**Comment by jbenet** [comment]
@rschulman we already use `/ipns/local` in the mounted filesystem, so yeah we could probably do this.

wonder about the implications of handling this correctly, etc. it's got similar security holes as using `localhost` in various places.

**Comment by whyrusleeping** [comment]
I've wanted an 'ipfs hosts' file, or an 'alias set' for a while now. Would be a good thing to figure out.

**Comment by Kubuxu** [comment]
This was implemented a long time ago.
