### ISSUE TITLE
webui broken by get fix

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1528]
the get fix broke the webui

![](http://gateway.ipfs.io/ipfs/Qmagvgj5df3Mj2N2F7nU6c3JNc9mYtZ3TUhRS3zXxfHnY2/cap.png)

---

https://botbot.me/freenode/ipfs/2015-07-28/?msg=45757898&page=3

```
<slothbag> I just rolled back to the commit before http get fix and it works
```

**Comment by jbenet** [comment]
@whyrusleeping very important to fix this before cutting 0.3.6

**Comment by whyrusleeping** [comment]
why is the webui making requests to an updates check endpoint that doesnt exist?

**Comment by whyrusleeping** [comment]
@jbenet i'm having trouble figuring out whats causing the webui to 'fail' aside from the numerous bad calls its making:

- a few calls to `ipfs update check` which was removed in november
- a call to `getLocation` with a null value for multiaddrs (should that be checked? why is it null)
  - the value came from a call to `ipfs id` which i dont see failing in any way
- a call to `ipfs config Gateway.Enabled'
  - digging into this led me to discover we have a typo of the key 'Writeable' in our default config

I'm going to assume that the ipfs id call is returning null multiaddrs somehow, but i've no idea how or what call its actually making (to what peer). Anyone know more javascripts than myself want to lend a hand?

**Comment by whyrusleeping** [comment]
also, the webfonts its looking for dont appear to exist

**Comment by whyrusleeping** [comment]
alright, this looks like changing things to always use chunked encoding has broken the node-ipfs-api, @krl could you help me look at this?

**Comment by jbenet** [comment]
> a few calls to `ipfs update check` which was removed in november

yeah we should add it back :)

> a call to `ipfs config Gateway.Enabled'

we ended up never adding `Gateway.Enabled`.

> a call to `getLocation` with a null value for multiaddrs (should that be checked? why is it null)

not sure. @krl?

>  also, the webfonts its looking for dont appear to exist

i think this was fixed in a new webui version, as of yet unreleased. 

> alright, this looks like changing things to always use chunked encoding has broken the node-ipfs-api,

yep. i think that's it. i guess this is why the `flushCopy` was there :smile:
