### ISSUE TITLE
Connection Request ("STUN" over DHT)

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#153]
In a similar vein to #57, I would like to have a message or a service that implements 'connection requests', for example, peer X is behind a NAT and peer Y wants to connect to him. Peer Z has an open connection to X, so peer Y sends a request to Y through Z containing his public IP address and requesting X to connect directly to him.

**Comment by Stebalien** [comment]
Closing for spring cleaning. Anyone interested in discussing message routing should file an issue here: https://github.com/libp2p/notes/issues.

Note: The current plan (until we get message routing) is to open a relayed connection, signal over that, and then migrate to a direct connection.
