### ISSUE TITLE
ipfs add -r -w <dir> borked

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1533]
See: http://gateway.ipfs.io/ipfs/QmVoUkEGYLk4yFT8pUt7Lyz6VStE2GzzZp4EkF39CsEo6M/go1.4.2.src -- click AUTHORS. it _wrapped_ every single file in a dir. not what we want. we want the last dir to be wrapped itself.

**Comment by whyrusleeping** [comment]
thats quite the bug, lol

**Comment by jbenet** [comment]
closed in #1536
