### ISSUE TITLE
repo.lock prevents daemon restart

### ISSUE THREAD

**Issue by Luzifer** [ipfs/go-ipfs#1537]
```
Running ipfs version 0.3.5...
Found ipfs repository. Not initializing.
Error: ipfs daemon is running. please stop it to run this command
Use 'ipfs daemon --help' for information about this command
```

**How?** The old container running IPFS was killed by whatever reason, the `repo.lock` was left behind, the new container is unable to start because of that file.

**Tempfix?** Remove `repo.lock`, start new container.

**Proposed fix?** See age of repo.lock, renew it periodically, if it's stale ignore it and override it.

**Comment by jbenet** [comment]
@Luzifer do you see this often?

**Comment by Luzifer** [comment]
Yep. I do.

Further analysis:

```
root@docker01 ~ # docker logs ipfs
Running ipfs version 0.3.6...
Found ipfs repository. Not initializing.
Error: ipfs daemon is running. please stop it to run this command
Use 'ipfs daemon --help' for information about this command
root@docker01 ~ #
```

```
2015/08/02 08:33:00 Container ipfs has a new image version.
2015/08/02 08:33:00 Image: e5d8f88c14f7cccf21890df6aaf451d31b618ee359b6808a4ee754f2b040cba5 Current: 2db69e4b4024e1ff8fb6b7229a29406c42ea515aa9d0c1026381e2f2c7e980fa
2015/08/02 08:33:00 Stopping deprecated container 05d84e44ee53f7d918c4f02c8d0d681626846d3e962f275a3d3ac06ba7e1f5c0
2015/08/02 08:33:40 Removing deprecated container 05d84e44ee53f7d918c4f02c8d0d681626846d3e962f275a3d3ac06ba7e1f5c0
2015/08/02 08:33:41 Creating container ipfs
2015/08/02 08:33:41 Starting container ipfs
2015/08/02 08:34:00 Removing stopped container 45d8ec3910581cdb5cdf7a1f962ea28e5cb39151c0ba30872eb4da8ffe83cc1a
```

If you take a look at the timestamps:
- 08:33:00: Update is detected, stop command is executed
- 08:33:40: The killed container is removed
- 08:33:41: A new container is created
- 08:34:00: The new container is already crashed and gets removed (and recreated and again and again…)

Currently my dockermanager is waiting 20s from `stop` to `kill` ([fsouza/go-dockerclient#Client.StopContainer](https://godoc.org/github.com/fsouza/go-dockerclient#Client.StopContainer)) and obviously the container is not able to exit properly within 20s…

**Comment by jbenet** [comment]
@Luzifer that's really annoying. suggested fix here? is this a timestamping-on-the-file problem? (the file lock we're using is what bradfitz wrote for camlistore).

cc @whyrusleeping

**Comment by Luzifer** [comment]
One fix could be to ensure the daemon quits within `N` seconds and ensure the container is not killed before `stop`+`N`.

Another fix could be to see whether the daemon who wrote the lock is still active (for example the solution I initially suggested: Write a timestamp to that file as mtime or content every `M` seconds and if it was not written within `M*2` ignore the lock and start nevertheless)

**Comment by Luzifer** [comment]
Hmm maybe same issue as in #1476? Lets see if it continues…

**Comment by whyrusleeping** [comment]
@Luzifer I beleive this happens when the daemon is killed in an incorrect way (i.e. `SIGKILL` and friends) and the lockfile doesnt get released. This also *may* be a bug in our file locking code.

**Comment by Luzifer** [comment]
```bash
# docker logs ipfs
Running ipfs version 0.3.8-dev...
Found ipfs repository. Not initializing.
Error: ipfs daemon is running. please stop it to run this command
Use 'ipfs daemon --help' for information about this command
```

In 0.3.8-dev still present.

**Comment by Stebalien** [comment]
@whyrusleeping  when the daemon dies, the lock file should be released (may be not deleted but released). Most operating systems guarantee this. The file locking code may be buggy but I've looked it over and it looks reasonably correct.
@Luzifer Is the daemon actually dead? Have you tried running fuser on the lock file (assuming Linux)?

**Comment by Luzifer** [comment]
@Stebalien Yep. The Container is definitely dead.

I have a dir mounted into the container, the container gets replaced (stop + 20s + kill) and then the lock is still present and the new container doesn't start…

**Comment by Stebalien** [comment]
What does `flock  -n /path/to/repo.lock echo "not locked" || echo "really locked"` output? And `fuser /path/to/repo.lock`?

**Comment by Luzifer** [comment]
```
root@docker01 ~ # flock -n /data/ipfs/repo.lock echo "not locked" || echo "really locked"
not locked
root@docker01 ~ # fuser /data/ipfs/repo.lock
Cannot stat file /proc/15144/fd/3: Stale file handle
Cannot stat file /proc/15145/fd/3: Stale file handle
Cannot stat file /proc/15146/fd/3: Stale file handle
Cannot stat file /proc/23182/fd/5: Stale file handle
Cannot stat file /proc/23186/fd/1: Stale file handle
Cannot stat file /proc/23186/fd/2: Stale file handle
root@docker01 ~ # docker logs ipfs
Running ipfs version 0.3.8-dev...
Found ipfs repository. Not initializing.
Initializing daemon...
Error: can't Lock file "/data/ipfs/repo.lock": has non-zero size
root@docker01 ~ #
```

**Comment by Stebalien** [comment]
You appear to be using the fallback locking mechanism. What CPU architecture (and OS) are you running ipfs on?

**Comment by Luzifer** [comment]
```
root@docker01 ~ # uname -a
Linux docker01 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@docker01 ~ # docker -v
Docker version 1.7.0, build 0baf609
root@docker01 ~ # docker info
Containers: 29
Images: 332
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 390
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 31.29 GiB
Name: docker01
ID: QE6C:ZNQX:BADL:4BTY:7AK5:274U:7B7N:EUS7:FGYI:TE5Q:JPXI:FBK6
WARNING: No swap limit support
root@docker01 ~ # mount | grep "on / "
/dev/md2 on / type ext4 (rw)
```

**Comment by Luzifer** [comment]
But maybe it's indeed the reason in #1703 - The stop signals are going to the shell script and maybe ipfs is not able to clean up properly…

**Comment by Stebalien** [comment]
IPFS shouldn't have to clean up; it's just using the wrong lock. Basically, there are two types of locks:

1. fcntl (flock) locks. These locks are closed by the kernel when the process closes the file (automatically happens on exit). Even if the process crashes, the kernel should still free these.

2. PID locks. IPFS writes the daemon's PID to the lock file. To check if the lock is held, IPFS checks if a process with that PID is running. This is inherently flawed because (1) PIDs can be reused so the lock can appear to be held when it is not and (2) it doesn't account for PID namespaces. In your case, ipfs probably gets the same PID in every container. This means that, when you try to take the lock, IPFS thinks you already have the lock because a process with the PID written in the lock file is currently running (your process). This could be fixed but it shouldn't be necessary because you *should* be using the first type of lock (flock).

**Comment by Luzifer** [comment]
Hmm in that case: Don't know why this is the case… I'm just using the [official container](https://hub.docker.com/r/jbenet/go-ipfs/)… :disappointed:

**Comment by Stebalien** [comment]
Found it. You're running a 64bit kernel but the docker image uses the 32bit ipfs build. https://github.com/camlistore/lock doesn't support 32bit linux (https://github.com/camlistore/lock/issues/7).

**Comment by Luzifer** [comment]
Yeah… That arch thing is a huge mystery to me… Whenever I'm trying to run containers with `amd64` binaries the containers just crashes because they are not able to run them even when the machines are running on amd64 themselves…

**Comment by whyrusleeping** [comment]
@Stebalien good catch. We should do one or both of:

1) print a warning message when on an unsupported arch
2) patch camlistore/lock to support the platform

**Comment by Luzifer** [comment]
@whyrusleeping We're using the 386 binary in our official Docker container.

**Comment by Stebalien** [comment]
I've created a pull request on camlistore/lock to fix 32bit linux but I don't know how active the project is.

**Comment by jbenet** [comment]
thanks @Stebalien

**Comment by Stebalien** [comment]
All platforms now use locks that are guaranteed to be released on exit and the next release (baking as an RC1) auto-recovers the leveldb datastore after a crash.

**Comment by cboddy** [comment]
@Stebalien great! Just to check: is that update in the 4.18 release?

**Comment by Stebalien** [comment]
Yes.
