### ISSUE TITLE
{dht, kad}.proto question

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#1541]
Is it possible for a peer to have peers it can't connect in its k-bucket? AFAIU, k-buckets are filled and orded by 'last seen', and therefore a peer that we were never able to connected is not considered for the k-bucket, which means that the hypothesis of having peer replying to a kad-router query with a peer list of peers it can't connect, will never happen. Right? If so, why do we need this value https://github.com/ipfs/go-ipfs/blob/master/routing/dht/pb/dht.proto#L38

**Comment by whyrusleeping** [comment]
yeah, any peer in our routing table will be a peer that we are connected to. we only put a peer in the routing table when we receive a message from them (or upon connection i beleive) and when they disconnect, they are removed from the routing table. as far as i can tell, you are right, that should never happen

**Comment by Stebalien** [comment]
This looks answered. If not, please reopen.
