### ISSUE TITLE
List the files uploaded through API and CLI on the WebUI as well

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#1555]
This will save a lot of confusion for the electron-app users.

**Comment by jbenet** [comment]
this is related to the "local storage" problem. and the "listing roots" problem.

cc @whyrusleeping

**Comment by whyrusleeping** [comment]
i just want a log file in `$IPFS_PATH` that lists every 'block create' operation. such as adds, block puts, object puts, and object patches along with the time it happened.

**Comment by whyrusleeping** [comment]
closing as a duplicate of: https://github.com/ipfs/go-ipfs/issues/1353
