### ISSUE TITLE
go-ipfsd and go-ipfs-cli as separate projects

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#1556]
We've been having some conversations about this and wanted to make sure it was written down/discussed

It starts to make more and more sense to separate go-ipfs into two separate repos: `go-ipfsd` and `go-ipfs-cli`.

The major benefit is being able to use the go-ipfs-cli with more than one IPFS peer that doesn't have to be necessarily installed with `go-ipfsd`, this IPFS node can be remote, installed in the future through the Node.js implementation or it could be installed through the electron app. It should favor and look for a node installed locally on the default ports, though the HTTP API and if no Node is found, then spawn a new ephemeral node instance to do the IPFS operation. If the operation is an `add`, there should be at least a repo locally, otherwise tell the user that the data added won't be able to be used if there is never a ipfsd running using that repo created by the ephemeral node.

Separating things reduces friction on contributions and makes our APIs stronger due to the need of executing more tests, but also adds complexity when it comes to installation. Something I believe can be easily solved with the current endeavour of making distributions for each OS, including nice installers. (Example. node.js `brew`, `pkg`, `apt-get`, `msi`, etc installers, do install both Node.js and npm in favor of user experience)

**Comment by whyrusleeping** [comment]
I think we can achieve the benefits you bring up without making separate binaries. For now, i'm going to close this and say we should keep a single binary.
