### ISSUE TITLE
Add --empty option for init

### ISSUE THREAD

**Issue by leni536** [ipfs/go-ipfs#1559]
Suggestion:

Add --empty (or similar) option for init. Right now init adds and pins the help files to the local storage (I think it's reasonable). It could be useful to create empty repos right away instead of writing a script that unpins then garbage collects all these help files.

**Comment by whyrusleeping** [comment]
Seems like a good idea to me.

**Comment by jbenet** [comment]
:+1: let's name it `--empty-repo`.

**Comment by jbenet** [comment]
thanks to @prusnak -- merged
