### ISSUE TITLE
peer ID missing in swarm peers output

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1560]
mars has been running for 11 days now, and I logged in this morning and ran `ipfs swarm peers` and it took a while before returning, and when it did, one of the peers had a missing ID.

output: https://gist.github.com/whyrusleeping/2319d244e93219b4100a

**Comment by MichaelMure** [comment]
For what it's worth, reproduced through the API:
```
{
  "Strings": [
    "/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",

...
    "/ip4/104.236.76.40/tcp/1443/ipfs/",
...
    /ipfs/QmWZtrDVgxWpDbdQRNRsak5nxrr5RC7R6BipcgpmAmgSoM",
    "/ip6/2607:f810:c20:1d:ca60:ff:fec8:76df/tcp/4001/ipfs/QmNoDNpuYFWnVFN4hHuGojHcewF4bamd7c7BTp3g41uei2"
  ]
}
```

**Comment by MichaelMure** [comment]
I hammered the API to gather more data.

Apparently it's not related to a particular peer, and a call with an erroneous peer entry was preceded 0.5s before by a call with the peer just fine.

**Comment by MichaelMure** [comment]
And for some stats, it happened 2 times with two different peer over 2280 API call (96 peers connected currently).

**Comment by whyrusleeping** [comment]
I havent seen this lately, i'm going to assume the issue has been resolved
