### ISSUE TITLE
Setting "deep" config options doesn't work

### ISSUE THREAD

**Issue by ehd** [ipfs/go-ipfs#1561]
I consulted the new CORS documentation in `ipfs daemon --help` and found this

```
You can setup CORS headers the same way:

ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials '["true"]'
```

However, when I tried it I got an error at first.

Using `ipfs config show` I saw that `API.HTTPHeaders` is set to `null`, so I set it to an empty object like this:

```
ipfs config --json API.HTTPHeaders '{}'
```

Afterwards I was also able set properties within the `API.HTTPHeaders` object.

I would have expected the `ipfs config --json` command to automatically create objects along a valid property path.

**Comment by jbenet** [comment]
> I would have expected the ipfs config --json command to automatically create objects along a valid property path.

@ehd yeah, it should. interesting... can you repro with a test case? we should add it to test suite if so

**Comment by ehd** [comment]
@jbenet Yeah, gladly. Should I add it in [this test](https://github.com/ipfs/go-ipfs/blob/d1366cde1b1ae8d5a6557546c26eef134bacb4bc/test/sharness/t0021-config.sh)?

I also found [this test in user-config](https://github.com/ipfs/go-ipfs/blob/d1366cde1b1ae8d5a6557546c26eef134bacb4bc/test/sharness/t0070-user-config.sh#L14) which sets a deep property successfully. Lo and behold, maybe a difference between `null` and not defined in the code that checks deep property access?

One more question: Where do I put the ipfs binary in order to run the tests? From the README I couldn't find out how to build ipfs in a way that makes it work within the test harness command from `.travis.yml`.

**Comment by jbenet** [comment]
@ehd yeah that test works.

> Where do I put the ipfs binary in order to run the tests? From the README I couldn't find out how to build ipfs in a way that makes it work within the test harness command from .travis.yml.

just run `make`. it should build its own version and place it in `test/bin/ipfs`

**Comment by ehd** [comment]
@jbenet https://github.com/ehd/go-ipfs/commit/c6d1413594b3aa73cc45fb28751f6ac41882195d adds test cases for:

- config set a path with a parent that is not defined: Passes
- config set a path with a parent that is null (like setting a property inside API.HTTPHeaders & Gateway.HTTPHeaders): Fails

**Comment by jbenet** [comment]
thanks @ehd!

**Comment by jbenet** [comment]
@rht, @whyrusleeping, @heems can one of you pick this up this week?

**Comment by rht** [comment]
Waiting for merge on @ehd's commit before this is rebased and merged: https://github.com/ipfs/go-ipfs/pull/1570

**Comment by ehd** [comment]
thanks! should i open a PR or something to get the above commit merged?

**Comment by rht** [comment]
@ehd uh huh

**Comment by ehd** [comment]
@rht I opened a PR pulling my commit into your fork so master doesn't get a failing test merged in. Please let me know if you want me to do something else instead.

**Comment by ehd** [comment]
high 🙏🏻 five. Thank you.
