### ISSUE TITLE
IPNS pointer was not unixfs node

### ISSUE THREAD

**Issue by krl** [ipfs/go-ipfs#1566]
ERRO[20:33:15:000] IPNS pointer was not unixfs node              module=ipnsfs
ERRO[20:33:15:000] error from node construction: unexpected EOF  module=cmd/ipfs
Error: unexpected EOF

@whyrusleeping Could this error be moved into to ipfs mount command instead of blocking the daemon completely?

**Comment by whyrusleeping** [comment]
yeah probably. Got a repro?

**Comment by krl** [comment]
ipfs name publish /ipfs/QmZFmR9oSwy42skdwT4mTWEiRY2Cky6N2vcVb5x5ZhrWmS

ipfs daemon

**Comment by whyrusleeping** [comment]
I think that this will change once the mfs PR lands. I will verify over there to make sure.

**Comment by krl** [comment]
@whyrusleeping sweet thx for the quick fix!

**Comment by krl** [comment]
There seems to have been a regression on this issue

**Comment by whyrusleeping** [comment]
@krl thanks for the heads up. Ill take a look.

**Comment by whyrusleeping** [comment]
@krl what the heck? my changes are gone.

**Comment by krl** [comment]
Thx, works again!
