### ISSUE TITLE
graphmd does not show "grouping" blocks

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/go-ipfs#1574]
When a file is big enough, child blocks are organized in a subtree. `graphmd` does not show this subtree, and instead show all the blocks as direct child of the file block.

At least in my machine, @whyrusleeping seems to not have the problem. I have go-ipfs from august 5.

**Comment by MichaelMure** [comment]
This is what I get for a 102Mo file. The WebUI list only 3 direct child for this file (ie, a subtree).

![random](https://cloud.githubusercontent.com/assets/294669/9285798/0b99bf32-42ea-11e5-99eb-efcc5f43cc60.png)

**Comment by jbenet** [comment]
can you post the hash in a copy-pastable way? would like to inspect

**Comment by MichaelMure** [comment]
Hrmmmm, trying to reproduce again, I totally may have mixed up hashes. The graph I posted is actually for a 39Mo file which does not have a subtree. Subtree does show correctly for a 102Mo file. 
Sorry !
