### ISSUE TITLE
gateway api doesn't resolve ipns entries

### ISSUE THREAD

**Issue by krl** [ipfs/go-ipfs#1586]
@rht

```bash
krl@bataille:~$ curl "http://gateway.ipfs.io/api/v0/object/get?arg=%2Fipns%2FQmPY8N2qYSV6qBtpPZ6Kfuj9H35gLmytEySbGj2zFyCPQs&stream-channels=true"
{
  "Message": "could not resolve name.",
  "Code": 0
}

krl@bataille:~$ curl "http:/localhost:5001/api/v0/object/get?arg=%2Fipns%2FQmPY8N2qYSV6qBtpPZ6Kfuj9H35gLmytEySbGj2zFyCPQs&stream-channels=true"
{
  "Links": [
    {
      "Name": "log",
      "Hash": "QmVzy8nvhYdxPE9EDvaSgnsErQ4CvNjyvGtDbQNyMf73Lt",
      "Size": 1219
    }
  ],
  "Data": "{\"type\":\"starlog-feed\",\"name\":\"frong\"}"
}
```

**Comment by rht** [comment]
can't reproduce. likely due to caching

**Comment by krl** [comment]
@rht, @lgierth - i made this test script to show what i want to work:

http://gateway.ipfs.io/ipfs/QmZmgC5Cw1scmQwUZp9X7QZBPFyPrXt1Uz1hXYSTeV1tL1/

it works fine on localhost, but fails on gateway. Probably something to do with the Referer. Thoughts?

**Comment by lgierth** [comment]
This is probably the line: https://github.com/ipfs/go-ipfs/blob/4cef86298e8bbb4c0b8e10ac77ad71999e7964aa/commands/http/handler.go#L106-L111

**Comment by rht** [comment]
Most likely.

Because it works if directly from the gateway http://gateway.ipfs.io/api/v0/cat?arg=/ipfs/QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V

The script doesn't tell if the err is 403 or 404, however.

**Comment by lgierth** [comment]
And the related tokens/CORS discussion: https://github.com/ipfs/go-ipfs/issues/1532

**Comment by lgierth** [comment]
> The script doesn't tell if the err is 403 or 404, however.

It does in the network console, it's all 403 with a "403 - Forbidden" body

**Comment by jbenet** [comment]
@lgierth does the gateway have the CORS headers setup?

- do we want to allow `"*"`? (i'd say lets wait until we know we have to)
- let's allow `"gateway.ipfs.io"` and `"ipfs.io"` for now?

**Comment by krl** [comment]
Setting the gateway CORS to its own domain should be enough, other gateways will choose their own CORS.

Assuming most people would not need to send cookies with their gateways, we could just warn them that it's not an opaque thing no?

**Comment by krl** [comment]
@lgierth any progress/ETA on this?

**Comment by lgierth** [comment]
on it right now

**Comment by jbenet** [comment]
```
16:13 <•jbenet> https://github.com/ipfs/go-ipfs/blob/master/commands/http/handler.go#L94 <--- api handler. not 100% certain it's getting the right values for the _readable gateway_
16:14 <•jbenet> it may just be pulling the same cors as API, which is bad, we want it to pull the CORS of the "gateway".
16:15 <•jbenet> (its confusing to call these "gateway" and "api" still, because both now have "gateway" and "api" parts to them
16:16  ⇐ voxelot quit  ↔ danslo nipped out  
16:18 <•jbenet> maybe we can call them "internal http server" and the "external http server" 
```

so at the very least, it _looks like_ 
- the "API" part of the "external" server needs to adopt different CORS set than regular "internal" API, else problems will emerge
- the "API" part of the "external" server should be currently pulling the same CORS as `API.HTTPHeaders` (but i'm not sure if im reading code correctly) 

maybe:
- rename the "8080" server to "External Gateway" or "External API" or  "External Server"
- rename the "5001" server to "Internal Gateway" or "Internal API" or "Internal Server" 
- (i dont like the word "Server". anything similar?)
- if we rename, will need to migrate config values + docs.

**Comment by krl** [comment]
All good!
