### ISSUE TITLE
Add abruptly dies when daemon running

### ISSUE THREAD

**Issue by davidar** [ipfs/go-ipfs#1591]
When the daemon is running, `ipfs add -r` on a directory like [this](http://ipfs.davidar.io/ipfs/QmdKjhpvnWYbqps2hFJJNSBSwDv4NKQyPnxkAFWmAuHiuD/) (on the order of 1000 1MB files) will just abruptly stop partway through, no errors or anything. The daemon doesn't die, and it doesn't appear to be consuming significant amounts of memory (so I don't think it's #1222).

After stopping the daemon, add runs without issue in offline mode.

I didn't see any errors in the log (sorry, forgot to make a copy, but should be relatively easy to reproduce). The only thing I noticed was a lot of noise about blocks being published to the network, so perhaps the problem is related to that somehow?

IRC logs in case I've missed anything: [1](https://botbot.me/freenode/ipfs/2015-08-18/?msg=47477895&page=1) [2](https://botbot.me/freenode/ipfs/2015-08-18/?msg=47490339&page=2)

CC: @jbenet @whyrusleeping

**Comment by rht** [comment]
Discovered the bug independently when tried adding go-ipfs's Godeps directory.

**Comment by rht** [comment]
To reproduce:
1. run `ipfs daemon`
2. go to go-ipfs repo, run `ipfs add -r Godeps`

Notice it will always stop at
`added QmcgpsyWgH8Y8ajJz1Cu72KnS5uo2Aa2LpzU7kinSupNKC Godeps/_workspace/src/github.com/jbenet/go-multihash/multihash/LICENSE`

**Comment by davidar** [comment]
Oops, this seems to be a dupe of #1072
