### ISSUE TITLE
WSASend error on Windows makes WebUI stop working

### ISSUE THREAD

**Issue by slothbag** [ipfs/go-ipfs#1606]
I get this error on windows after only a few minutes..

error while writing stream WSASend tcp4 127.0.0.1:5001: An established connection was aborted by the software in your host machine.  module=commands/http

After this the webui no longer works and I have to restart the daemon

**Comment by slothbag** [comment]
Just click around the webui a few times and the error should appear.  I have been keeping in sync with ipfs master branch every week and this problem has only just started happening recently.. i.e. a week or two.

**Comment by jbenet** [comment]
cc @gatesvp

**Comment by slothbag** [comment]
Update: Looks like clicking on the "Logs" tab in the WebUI triggers the bug.

**Comment by whyrusleeping** [comment]
@slothbag it appears that the logs tab is just broken in general. cc @diasdavid @krl

**Comment by slothbag** [comment]
Seems to be working now.
