### ISSUE TITLE
MFS API Feedback

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1607]
If you have any feedback, comments, questions, or concerns about the mfs api. This is the place for it.

**Comment by Kubuxu** [comment]
It would be awesome to have flags for `ipfs files stat` to display only hash of directory. Currently I use `head -1` for this purpose.

**Comment by MasterJames** [comment]
Where do I find the IPFS MFS API?

**Comment by Kubuxu** [comment]
It is `ipfs files` subcommands.

**Comment by MasterJames** [comment]
Okay so mfs is only mutable through ipns.
I was looking for a mutable solution within ipfs that ideally works on the file system. What might you suggest? The data store or objects? Sorry it's a nub question but I have hunted around without much success ipns is workable but it would be nice to build a mutable file system on top of ipfs.
It's just I thought the mfs would be mutable but I guess not. ?

**Comment by slang800** [comment]
It would be nice if we got rid of all the `ipfs files` subcommands and just mounted the MFS via FUSE so we can use the standard GNU fs utilities.

**Comment by Powersource** [comment]
What does MFS stand for? I couldn't find anything reasonable.

**Comment by Powersource** [comment]
I'm guessing it stands for Mutable file system. Is there anything longer than snippets written about it?

**Comment by zignig** [comment]
It would be nice if patch append-data and set-data were available from the files interface. Setting meta data on files in MFS would be useful.

**Comment by MasterJames** [comment]
Yes mutable file system it has commands like
`ipfs mfs ls`

**Comment by djdv** [comment]
Going forward, feedback for the `ipfs files` command should be individual issues in this repo (ipfs/go-ipfs).
Concerns about the MFS api itself should go in [ipfs/go-mfs](https://github.com/ipfs/go-mfs).
And general questions should see https://docs.ipfs.io/#community
