### ISSUE TITLE
ipfs object put does not accept xml as input encoding

### ISSUE THREAD

**Issue by martingms** [ipfs/go-ipfs#1612]
`$ ipfs object put --inputenc=xml <some_xml_file` returns

    Error: unknown object encoding

The error comes from the default case of the `switch` statement at core/commands/object.go:664

**Comment by whyrusleeping** [comment]
Looks like we havent written a decoder for xml yet. If you'd like to get your hands a little dirty, it shouldnt be too much work to code that up. If not, we can get to it
