### ISSUE TITLE
Failures in mock_notif_test.go reappeared

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1614]
The notifications test started failing again, and its hanging on this line: https://github.com/ipfs/go-ipfs/blob/master/p2p/net/mock/mock_notif_test.go#L136

**Comment by whyrusleeping** [comment]
@jbenet can you take a look at this? I'm not super familiar with this test, or what the line i linked is for

**Comment by whyrusleeping** [comment]
[These calls](https://github.com/ipfs/go-ipfs/blob/master/p2p/net/mock/mock_notif_test.go#L124-L130) appear to be required due to the IDService's `IdentifyConn` being called.

**Comment by whyrusleeping** [comment]
@jbenet I might not understand the net code well enough, but what happens if the `IdentifyConn` call fails? theres no error returned, and as far as i can tell, the offending connection does not get closed.

**Comment by whyrusleeping** [comment]
looks like the issue is that `IdentifyConn` is hanging on write (line 90, `protocol.WriteHeader`)

**Comment by jbenet** [comment]
> what happens if the `IdentifyConn` call fails? theres no error returned, and as far as i can tell, the offending connection does not get closed.

You're right. ideally, Identify should run _before_ everything else, but it makes it very expensive to do so (many-RTT hit as a handshake...). We could close the conn if Identify fails and hope the other side retries?

**Comment by whyrusleeping** [comment]
I beleive this has also been resolved
