### ISSUE TITLE
Error: pin: context deadline exceeded

### ISSUE THREAD

**Issue by davidar** [ipfs/go-ipfs#1630]
Pinning seems to time out on large (10GB) directories:

```sh
# load into cache
$ ipfs refs -r QmYaFMPTgDkwp3vun6o3zfVv6gFwDWVSJWwZQHieXj1Ys6
<snip>
# make sure it's definitely cached
$ ipfs get QmYaFMPTgDkwp3vun6o3zfVv6gFwDWVSJWwZQHieXj1Ys6

$ ipfs pin add -r QmYaFMPTgDkwp3vun6o3zfVv6gFwDWVSJWwZQHieXj1Ys6
Error: pin: context deadline exceeded
```

Affects: ipfs/archives#2

Edit: Actually, it would also be nice if you didn't have to do the caching step separately (i.e. make pin act like get, but without actually creating files in the current directory).

**Comment by whyrusleeping** [comment]
@davidar thats interesting. how long did the `pin` call take?

**Comment by davidar** [comment]
@whyrusleeping A minute or two before error, I guess (refs -r also takes a while just to list blocks from the cache). I can time it exactly later today if that would help.

**Comment by rht** [comment]
> Actually, it would also be nice if you didn't have to do the caching step separately (i.e. make pin act like get, but without actually creating files in the current directory).

Related #875

**Comment by whyrusleeping** [comment]
I've got to be honest, i cant tell where that timeout in pin is coming from... @rht can you see  where?

**Comment by davidar** [comment]
@rht not exactly, what I mean is download to the block store and pin it simultaneously (without timing out). A progress bar too would be nice

**Comment by rht** [comment]
@whyrusleeping  In corerepo.Pin, it comes from core.Resolve(ctx,...), which either 1. n.Resolver(ctx,...) (which timeout happens only in path.Resolver.ResolveLinks), or 2. blockservice.GetBlock (which timeout happens somewhere in bitswap).

**Comment by rht** [comment]
@davidar I ref-ed the issue because this is another view of not wanting to "duplicate" files (you only want the cache).

**Comment by rht** [comment]
Actually, since `ipfs refs -r` uses core.Resolve and it works just fine, the err is constrained to come from the 2nd one (n.Pinning.Pin). @davidar sorry no need to run the test.

**Comment by whyrusleeping** [comment]
@rht it has to be the one in `ResolveLinks`, i'm fairly certain that bitswap wont ever timeout a request.

**Comment by rht** [comment]
`ipfs refs` uses https://github.com/ipfs/go-ipfs/blob/master/core/commands/refs.go#L192-L201 which uses `ResolveLinks`, which is identical to the first part of pin https://github.com/ipfs/go-ipfs/blob/master/core/corerepo/pinning.go#L28-L35

**Comment by rht** [comment]
Wish this could return an interator https://github.com/rht/go-ipfs/commit/6d55bc90747d869dd62fa85d1f6b819e755d6119

**Comment by jbenet** [comment]
@rht can use channels as iterators

i like iterators in python. probably the best support i've seen in a language for them. (without going c++ operator overloading crazy).

**Comment by whyrusleeping** [comment]
This has since been improved, ipfs pin add is much better about timeouts and resource consumption
