### ISSUE TITLE
panics in api command calls get ignored over API

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1635]
when a panic happens inside the handler for an api call, it is silently ignored. nothing is printed or logged by the daemon.

**Comment by jbenet** [comment]
Not so good. They should get logged as errors. 




It is typical in http servers to catch exceptions/errors which are fatal to the request but not to the whole service. Ideally we should be able to distinguish them-- as some panics may merit crashing the process.



—

**Comment by whyrusleeping** [comment]
@jbenet agreed. I'll fix that up
