### ISSUE TITLE
logs no longer show filename/number

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1652]
@rht do you think you could put filename:linenumber back into the logger format? Its really useful to have

**Comment by rht** [comment]
The pin error line number could have been known. Here is the state: https://github.com/Sirupsen/logrus/issues/63

**Comment by whyrusleeping** [comment]
Ah, this must be why I used go-logging in the first place.

**Comment by whyrusleeping** [comment]
this has been resolved
