### ISSUE TITLE
massive amounts of weird open network file descriptors during ipfs add

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1654]
The add issue we've been seeing is a [double hidden](https://github.com/ipfs/go-ipfs/pull/1653/commits) 'too many open file descriptors' error. I have no idea whats causing the open file descriptors, they arent the files we're adding.

http://gateway.ipfs.io/ipfs/QmTK3eArBLsxuLTgadUbFWxuShFdKa2BwwwFMLQXbVRQoU

**Comment by whyrusleeping** [comment]
Its dialing my router... http://gateway.ipfs.io/ipfs/QmPqYwYEyzuJdvegPHZmbPqyHJUbjcrUUhsEpuFLvcXxJN

Not sure why i'm dialing my router a fuckload on port 5555

**Comment by rht** [comment]
After https://github.com/ipfs/go-ipfs/blob/master/commands/http/client.go#L124, add `httpRes.Close = true` seems to fix the random add locally.

**Comment by whyrusleeping** [comment]
this is because of #1656

**Comment by jbenet** [comment]
great work @whyrusleeping

**Comment by rht** [comment]
if #1584 is solved as well?
