### ISSUE TITLE
external port mappings should be cached for some time

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1656]
currently we call out to ExternalAddrs on the nat manager way too often, we need to find a way to cache this intelligently.

@jbenet this might also explain why some nodes still have sooooo many addresses that they advertise.

**Comment by jbenet** [comment]
- easy: time based caching. (maybe every 30 or 60s? packets to the nat are not very expensive)
- harder: figure out how to ask the nat to tell us if it changes. seems hard.

**Comment by whyrusleeping** [comment]
I think time based caching will be a good quick short term solution. This is a fairly major issue, since it crashes our most used command.

**Comment by jbenet** [comment]
Indeed

**Comment by whyrusleeping** [comment]
issue has been addressed, but the symptoms still occur for other reasons. closing.
