### ISSUE TITLE
Gobuilder building is broken 

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1660]
We need to fix this. i want to pull prebuilt binaries with new things, like `--api` and cannot.

**Comment by whyrusleeping** [comment]
link to problems? anything else wrong?

**Comment by jbenet** [comment]
it's the vendoring with godeps we discussed with @Luzifer and @cryptix. Didn't see an issue filed to fix it. Anyway, super annoying.

**Comment by Luzifer** [comment]
https://github.com/Luzifer/gobuilder/issues/62

**Comment by jbenet** [comment]
@Luzifer any update on godeps being fixed?

Also, is gobuilder on `1.5.1`? -- https://gobuilder.me/github.com/ipfs/go-ipfs/cmd/ipfs/log/436733ccb7429cf9 seems broken

or there's something wrong with @whyrusleeping's check o/

**Comment by Luzifer** [comment]
@jbenet sadly no timeline yet because of too high work load… :disappointed: 

GoBuilder is currently building on `go version go1.5.1 linux/amd64` (inherited from `golang:latest`)

**Comment by diasdavid** [comment]
Seems that is working pretty well to me https://gobuilder.me/github.com/ipfs/go-ipfs :)

**Comment by jbenet** [comment]
@diasdavid I don't think it is -- unless it's changed in last week. We
still need to trigger them manually I believe?

(If so pls reopen, mobile)

**Comment by Luzifer** [comment]
@jbenet You triggered all those builds manually?

![image](https://cloud.githubusercontent.com/assets/20142/12291141/cce3c6de-b9e5-11e5-831b-00f41d24a006.png)

Also the build is running fine without errors for ages now…

**Comment by jbenet** [comment]
oh hmm. since when? i still had to run dev0.4.0 builds recently

**Comment by Luzifer** [comment]
Hm okay looks like a misunderstanding…

What will be built automatically:
- `master` (the commit being the `HEAD` of `master`)

What gets tagged automatically:
- All tags attached to the commit just built
- All branches attached to the commit just built

So if you push the commit `123456` which happens to have the tag `v1.2.3` and which is the `HEAD` of `master` GoBuilder gets a ping from GitHub containing that commit hash. GoBuilder fetches that commit and collects all references (`v1.2.3` and `master`). After the build GoBuilder tags the result with all found references.

If you push to the branch `dev0.4.0` the commits most likely are not part of `master` and will not be built automatically. Thats the reason why you need to trigger them yourself. Maybe it might be useful to remove the restriction to build only the `master` ref or any ref manually passed but that would cause the user to have a hard time to find the latest build he can trust. Might be a feature for the next builder generation to have a regex to sort out whether to use a reference or not…

Hope this removes some of the confusion. :)

**Comment by jbenet** [comment]
Ah ok makes sense.

I'd probably just do similar to docker, and enable tags/branches in gobuilder to automatically build too, even if they should be configured manually in the yml file. (the pushes/merges into a branch should still trigger webhooks)

**Comment by Luzifer** [comment]
Added this as a feature request to GoBuilder: https://github.com/Luzifer/gobuilder/issues/68
