### ISSUE TITLE
wrap permanence

### ISSUE THREAD

**Issue by reit-c** [ipfs/go-ipfs#1663]
I've been thinking a bit about the add -w wrapper functionality, which helpfully permits users to add single files to IPFS and give them a proper filename (for browsers/applications to know what type of file it is and so on), which is great, but it unfortunately damages the long-term permanence factor of IPFS. The problem being, one of the stated goals of IPFS was content-addressed objects with links that don't break, but I fear a common use case may end up being something like https://github.com/ipfs/ipfs.js where the file is addressed as \<hash\>/\<filename\> and since the hash is dependent on the filename these links have the capacity to be broken permanently. Even if an identical file becomes available elsewhere under other circumstances it is unlikely the file names will match, nor could the swarms be joined.

However, since single files are not directories and do not have children, in the event that a hash is resolved to a single file and not a directory it should be possible to take the remainder of the path as the file name. That is, both Qm12345678990, Qm12345678990/something.png, and Qm12345678990/somethingelse.png could all refer to the same file, ensuring that even in the event the file names of wrapped objects change the network itself would still continue to recognize them as the same files.

**Comment by jbenet** [comment]
Hey @reit-c, thanks for bringing up the concern, but i think there's a misunderstanding in your model.

Both the file and the wrapping directory have their own hash. the directory _links_ to the file via it's hash. e.g.:

```
> echo foo >bar
> ipfs add -w bar
added QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6 bar
added QmZb5Gox3Xpsv1hrdeMsnmL5wdMFLmG6Ph54kSmWhBihyn
> ipfs ls QmZb5Gox3Xpsv1hrdeMsnmL5wdMFLmG6Ph54kSmWhBihyn
QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6 12 bar
> ipfs cat QmZb5Gox3Xpsv1hrdeMsnmL5wdMFLmG6Ph54kSmWhBihyn/bar
foo
> ipfs cat QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6
foo
```

a _recursive_ pin pins both:
```
> ipfs pin add -r QmZb5Gox3Xpsv1hrdeMsnmL5wdMFLmG6Ph54kSmWhBihyn
# pins QmZb5Gox3Xpsv1hrdeMsnmL5wdMFLmG6Ph54kSmWhBihyn recursively
# pins QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6 indirectly
```

I think this addresses your concern. If this continues not to be clear, reopen.

> since single files are not directories and do not have children,

incorrect. big files are chunked and do have children.

**Comment by reit-c** [comment]
>Both the file and the wrapping directory have their own hash. the directory links to the file via it's hash
Ah, no I fully understand that, I'm suggesting doing away with the directory, in this use case it isn't actually necessary. That is, the network doesn't need knowledge of the file name at all, that information can be carried by the link itself. I'm not 100% on how chunked files work, but there should be a level in there where a file node (with child chunks) and a directory node (with a listing of linked directories/files) can be internally distinguished (I know that using the API to perform an ls will return a tag of type 1 or 2 for each linked node, so that information should be in there somewhere).

On a pathing level my understanding is if I access a file such as QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6 the system knows to return that as a file directly, it somehow knows it isn't a directory. In that case, QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6/\<something\> should have no meaning, which provides a void where meaning could be assigned to 'pretend' that it's a directory node with a child of QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6 and a file name of \<something\> and transparently return it as such.
