### ISSUE TITLE
RE:  wrap permanence #1663

### ISSUE THREAD

**Issue by reit-c** [ipfs/go-ipfs#1664]
(from https://github.com/ipfs/go-ipfs/issues/1663 - opening new issue because third parties lack appropriate permissions to reopen issues closed by project maintainers)

>Both the file and the wrapping directory have their own hash. the directory links to the file via it's hash

Ah, no I fully understand that, I'm suggesting doing away with the directory, in this use case it isn't actually necessary. That is, the network doesn't need knowledge of the file name at all, that information can be carried by the link itself. I'm not 100% on how chunked files work, but there should be a level in there where a file node (with child chunks) and a directory node (with a listing of linked directories/files) can be internally distinguished (I know that using the API to perform an ls will return a tag of type 1 or 2 for each linked node, so that information should be in there somewhere).

On a pathing level my understanding is if I access a file such as QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6 the system knows to return that as a file directly, it somehow knows it isn't a directory. In that case, QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6/\<something\> should have no meaning, which provides a void where meaning could be assigned to 'pretend' that it's a directory node with a child of QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6 that has a file name of \<something\> and transparently return it as such. This would allow for swarm crossover even where the name of the file changes, as the file name information is already carried by the external channel (the path/URL) and there is no purpose in duplicating it.

I do realize that this is an edge case, and that it certainly feels like a hack, but in the event that IPFS ends up being used as suggested in https://github.com/ipfs/ipfs.js with single files being wrapped in a directory and addressed as /ipfs/\<hash\>/\<filename\> on a regular basis, the network may end up littered with dead and unrecoverable links in a completely avoidable manner.

**Comment by jbenet** [comment]
> that information can be carried by the link itself.

the point is that "the link" is embedded in another object, hence the directory. please dont open new issues. just comment in the old one. you can comment, even if it's closed, no?

**Comment by jbenet** [comment]
actually, this doesnt belong in go-ipfs. put it in ipfs/faq if you want to keep discussing this, or ask in IRC.

**Comment by jbenet** [comment]
the premise of your suggestion:

>  the network may end up littered with dead and unrecoverable links in a completely avoidable manner.

is incorrect. recursive pinning! pins the directory as well and keeps it with the file.

**Comment by reit-c** [comment]
>the premise of your suggestion ... is incorrect. recursive pinning! pins the directory as well and keeps it with the file.

That's not what I'm referring to. Lets say there's a popular image x.jpg, and has been added to IPFS by someone directly to give \<hash1\>. Someone has a local copy which they've renamed to y.jpg, and decides to use the wrap function on it, resulting in \<hash2\>/y.jpg. This user posts this link on some forum somewhere and forgets about it. After a while, this user goes offline/reinits their node and \<hash2\> dies.

Much later, someone else stumbles across that thread and tries to open the link. Despite x.jpg being a popular file on the network, and \<hash1\> being well seeded, the link is permanently dead.

**Comment by jbenet** [comment]
Yes, that's fine and as designed. this is a small edge case. and in practice, files will be nested in deep directory hierarchies and data will be nested in deep data structure hierarchies, once you go 6 links deep even with a small fanout (4) you have thousands of objects to keep. This is all fine-- and intended. git works this way too. Stuff is seldom lost from git.
