### ISSUE TITLE
running 'du' in a subdirectory of the mounted /ipfs/ gives error.

### ISSUE THREAD

**Issue by rodri** [ipfs/go-ipfs#1666]
Using ipfs compiled a week ago with Go 1.3.3

to reproduce, e.g.:

...:~$ cd /ipfs/QmNhFJjGcMPqpuYfxL62VVB9528NXqDNMFXiqN5bgFYiZ1/
...:/ipfs/QmNhFJjGcMPqpuYfxL62VVB9528NXqDNMFXiqN5bgFYiZ1$ du
Aborted
...:/ipfs/QmNhFJjGcMPqpuYfxL62VVB9528NXqDNMFXiqN5bgFYiZ1$

**Comment by rodri** [comment]
well, I really ran 'ls -l' before 'du', if that matters.

**Comment by whyrusleeping** [comment]
thanks for filing! i'll take a look.

**Comment by Stebalien** [comment]
This only happens in the top level directory. There's an old fedora bug report: https://bugzilla.redhat.com/show_bug.cgi?id=890223

**Comment by Stebalien** [comment]
@rodri I can no longer reproduce. @whyrusleeping recently fixed a bunch of fuse bugs so I'm guessing this is now fixed.

Please reopen if it's still an issue for you.
