### ISSUE TITLE
WEBUI: Failed to load resource: Bad Request : api/v0/update/check?stream-channels=true

### ISSUE THREAD

**Issue by sauloal** [ipfs/go-ipfs#1669]
Failed to load resource: the server responded with a status of 400 (Bad Request) http://XXX:5001/api/v0/update/check?stream-channels=true Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by davidar** [comment]
I'm also seeing lots of 40x errors on a somewhat recent build (within the past couple of weeks). As a result the webui is broken.

**Comment by whyrusleeping** [comment]
`http://XXX:5001/api/v0/update/check?stream-channels=true` is expected, we've disabled the update command for now. It shouldnt cause any issues for the webui though.

@davidar the webui is broken for you? what build of ipfs?

**Comment by davidar** [comment]
@whyrusleeping 0.3.8-dev (master as of last Friday)

**Comment by diasdavid** [comment]
Is this still current? If so, let's open it on the https://github.com/ipfs/webui repo please
