### ISSUE TITLE
WEBUI: 404 on viewing object DAG

### ISSUE THREAD

**Issue by sauloal** [ipfs/go-ipfs#1671]
in the 'files' tab, when asking to view the file I can access it but when asking for DAG I get 404.

e.g.: http://XXX:5001/ipfs/HASH/#/objects/HASH2

**Comment by whyrusleeping** [comment]
are you sure the hash you give the DAG viewer exists? I just tried on latest master, and got a url like: `http://localhost:5001/ipfs/QmS2HL9v5YeKgQkkWMvs1EMnFtUowTEdFfSSeMT4pos1e6/#/objects/object/\ipfs\<hash>`

and it worked fine

**Comment by sauloal** [comment]
I'm using the UI, so, I didn't do it by hand

**Comment by whyrusleeping** [comment]
Yeah, i'm using the UI as well, but you pasted a hash in the box, right?

**Comment by sauloal** [comment]
no. i've clicked in the link in we ui itself

**Comment by whyrusleeping** [comment]
okay, so you click the 'DAG' tab on the left side, and it brings up a text box and a 'Go' button. Did you not paste a hash in that text box and click go?

**Comment by sauloal** [comment]
no. i uploaded a file, listed my files. clicked in DAG of one of my files

**Comment by whyrusleeping** [comment]
Ah! okay, i was able to repro that. Thanks

**Comment by jbenet** [comment]
I think this should be filed in https://github.com/ipfs/webui no?

**Comment by sauloal** [comment]
@jbenet . I agree but I was directed here in the IRC chat...

**Comment by diasdavid** [comment]
Is this still current? If so, let's open it on the https://github.com/ipfs/webui repo please
