### ISSUE TITLE
WEBUI: 404 error doesn't link back to webui

### ISSUE THREAD

**Issue by 5paceManSpiff** [ipfs/go-ipfs#1673]
I'm not quite sure if this is intentional or not, but when I enter a hash in the search bar of the webui that doesn't exist, the link to that let's you "Go to console home" sends you to `http://localhost:5001` rather than `http://localhost:5001/webui` resulting in another 404 error.

**Comment by jbenet** [comment]
Thanks, sounds like a bug. @5paceManSpiff mind putting this over in https://github.com/ipfs/webui ? thanks

**Comment by 5paceManSpiff** [comment]
Not at all.  Here is the new issue.

https://github.com/ipfs/webui/issues/79
