### ISSUE TITLE
IPv6 error on daemon startup

### ISSUE THREAD

**Issue by jasonkgreen** [ipfs/go-ipfs#1675]
0.3.8-dev on Raspberry pi B+
ipfs daemon gives:

Initializing daemon...
ERRO[22:54:27:000] error from node construction: 1: listen tcp6 [::]:4001: socket: address family not supported by protocol
  module=cmd/ipfs
Error: 1: listen tcp6 [::]:4001: socket: address family not supported by protocol

workaround:  delete ipv6  line from swarm section of config file

**Comment by jbenet** [comment]
ideally this would not happen. ipfs init could check the OS stack and avoid adding the `ip6` addr in that case.

**Comment by lidel** [comment]
Not listening on ipv6 anymore, dynamically enabling it  is tracked in https://github.com/ipfs/go-ipfs/issues/5905
