### ISSUE TITLE
IPFS on a remote node.

### ISSUE THREAD

**Issue by solarisfire** [ipfs/go-ipfs#1677]
I run windows, kind of have no choice...

So I envisioned being able to have an IPFS node elsewhere on my network, on a nice Ubuntu box, that would have 24hr uptime.

But trying to access the webui remotely just throws an absolute ton of errors...

Looks like even though it's accessing the webui over the network, it's still trying to access a gateway at 127.0.0.1:8080 even though that obviously doesn't exist...

**Comment by jbenet** [comment]
This should be no problem, i do it all the time. Did this work for you in the end?
