### ISSUE TITLE
[question] IPNS publishing to non-default names

### ISSUE THREAD

**Issue by sunny-g** [ipfs/go-ipfs#1684]
Has this feature been built out yet? I'm currently getting the error `Error: keychains not yet implemented` when trying to (locally) publish a document to name other than my own, but that error tells me that this command may only work to publish messages to other names whose keypairs are installed on the machine's Keychain.

I'm trying to build a service that allows users to publish JSON-LD Identity Credentials and modifications to those credentials to their IPNS name from the browser using the `node-ipfs-api` package. I don't know the internals of how modifying an IPNS entry works but I would naively think that the `ipfs name publish` command would only need to be changed to verify the signature of the new document before publishing. 

**Edited for a little more context.**

**Comment by lgierth** [comment]
Yes, being able to use multiple keypairs is a TODO: https://github.com/ipfs/specs/tree/master/keystore

**Comment by sunny-g** [comment]
Thanks @lgierth for chiming in! It seems then that `ipfs` will only be extended to publish docs signed by locally-saved keypairs, correct? 

That kind of makes my idea DOA if I can't sign and send them out to be published from the browser :(

**Comment by lgierth** [comment]
It'd bring us close to being able to publish to arbitrary IPNS namespaces that you own a key for, though.

@whyrusleeping and @diasdavid might be able to tell you more.

**Comment by sunny-g** [comment]
@lgierth true, though I assumed that that functionality would be less useful if your IPNS namespace could map to more than just one IPFS hash. Is there a roadmap or spec proposal for that particular feature?

**Comment by whyrusleeping** [comment]
@sunny-g your ipns namespace can map to a directory containing multiple hashes as children. We also are going to have a 'keystore' which will allow you to own, generate and securely share keypairs and have ipns entries for each.

**Comment by sunny-g** [comment]
@whyrusleeping I forgot that you could map a directory, sorry about that!

However, I think I'm misunderstanding your point of the 'keystore', or at least its relevance to my use case: I don't want users to share their keypairs with the server, only their signed docs/directories (and if they can't be obtained in another way, their public keys) to be pushed to the network by the server.

**Comment by Kubuxu** [comment]
We support keystore for a while.
