### ISSUE TITLE
`ipfs pin add -r` times out, but `ipfs refs -r` does not

### ISSUE THREAD

**Issue by willglynn** [ipfs/go-ipfs#1687]
$ dig txt ipfs.io +short
    "dnslink=/ipfs/QmZfSNpHVzTNi9gezLcgq64Wbj1xhwi9wk4AxYyxMZgtCG"
    $ time ipfs pin add -r /ipfs/QmZfSNpHVzTNi9gezLcgq64Wbj1xhwi9wk4AxYyxMZgtCG
    Error: pin: context deadline exceeded

    real	1m0.031s
    user	0m0.011s
    sys	0m0.014s

    $ ipfs swarm peers | wc -l
          89
    $ ipfs refs -r /ipfs/QmZfSNpHVzTNi9gezLcgq64Wbj1xhwi9wk4AxYyxMZgtCG
    QmTkQCrspeQDEiFBvphH3ULHYNWr3aXpymGiyjMrrUimtZ
    QmNxKkkzXGJ2TpEDeeR6B7j95gx59pLWBk3spKzs1zKyYT
    QmUyX3YLX1Exur9kMAGmRfD77WfAnhFR4ov7n2b8hHzwF6
    QmZ4DpoqBxuhpTP2UkchfCM71MxAS6Vas16fcTipKjd7cU
    QmYJSgxfXYqwjFn17qqpiZYanSdijj3hY7hhAmS3515Ucd
    QmYJQ6A68kuRu8gRFD96HTcQf6TTjX2uDwEUjJCMChumQ8
    QmNqJXwbBJY8qk3CcST8DRPSb2yEJivnxjy4rfNpv8Kve4
    QmNeaEhZuGUDpA35EqHghpufZpEz3btZQCkauEduDgWRdX
    QmZCCM1kCpuH4xJwxdMx5C2gqb9VjtJBfntA4z5EEp49B1
    <sits forever>

I'm not exactly sure why `ipfs pin add -r` fails (and I wish it would describe exactly what it's doing when the deadline hits), but I'm opening this issue because I think `ipfs refs -r` should have the same behavior. I'd rather them both give up after a reasonable period of time, or both hang forever, or both have a `--timeout` parameter defaulting to the same value.

**Comment by rht** [comment]
Already in #1630

**Comment by whyrusleeping** [comment]
All commands respect a `--timeout` flag, example: `ipfs refs -r <hash> --timeout=10m`
