### ISSUE TITLE
ipfs ls on Mac OS X 10.9.5 returns nothing

### ISSUE THREAD

**Issue by jpolterock** [ipfs/go-ipfs#1690]
Both the precompiled binary and the binary compiled from source on Mac OS X 10.9.5 return no output for an 'ipfs ls' on any object. Where 'ipfs cat <hash> > new file' works. So, the file exists, but 'ipfs ls' returns nothing.

**Comment by whyrusleeping** [comment]
`ipfs ls` on files wont print anything because it only lists directories. (its not quite like standard unix ls in that manner). Perhaps we should print an error message or something.

**Comment by jpolterock** [comment]
I guess I'm struggling with how to discover what files are in my /ipfs. I
can see I have a [gif] file in there but I thought the ls of that files
hash would show me the blocks.

If I happen to lose all the information I get from the initial ipfs init,
how do I boostrap myself again to find the readme, quick-start, etc.

I'm struggling with how to do discovery at the lowest level presented with
the options 'ls' and 'cat' and each of these requiring a <hash> reference
that I don't have anymore.

Thanks,
Josh

**Comment by whyrusleeping** [comment]
@jpolterock having an 'add log' that shows all the things youve added is on our todo list. Its a highly requested feature, it just really needs to be implemented. In the meantime, you can use 'ipfs refs local' to print out all the hashes that are on your computer, this isnt *super* helpful as it includes indirect blocks and sub-chunks.

**Comment by jpolterock** [comment]
I can precede each of those refs with an 'ipfs ls' and at least find what
I'm looking for.

Thanks.

Have a great weekend!

**Comment by jbenet** [comment]
sounds like this is resolved (as the issue about the add log is different)
