### ISSUE TITLE
Ipfs add -r . not finishing on windows 7

### ISSUE THREAD

**Issue by bussiere** [ipfs/go-ipfs#1691]
When i make ipfs add -r . on a small directory it does the first files but after it blocks and does not seem to continue anymore 

Here is a screen : http://gateway.ipfs.io/ipfs/QmWY6eCPpmXFAGG2fpSNeXUB8R2yx5nJp1eVEwPgR3m8YS

Regards

**Comment by whyrusleeping** [comment]
On linux and OSX, we can kill the program and dump all the stack traces by sending it a `SIGQUIT`, which can be done by pressing ctrl+\   I don't know if that works on windows too.

If it does, it would be great to take a look at the stack dumps of the hung add

**Comment by jbenet** [comment]
@bussiere do you have master? @whyrusleeping and @rht fixed some things recently. (not sure if @rht's PR is merged yet)

**Comment by bussiere** [comment]
Yeah i ve installed it from go get from a week ago max.

Sadly i will be without windows computer for one week. I will give you more
feedback when i come back.

Regards and thanks for ipfs

**Comment by rht** [comment]
@bussiere update?

**Comment by whyrusleeping** [comment]
I have recently been able to run this command on a windows server 2012 machine. Marking as closed unless someone can repro the failure on latest master
