### ISSUE TITLE
Gateway problem

### ISSUE THREAD

**Issue by bussiere** [ipfs/go-ipfs#1693]
I am 90% sure that there is a problem with gateway.ipfs.io

http://gateway.ipfs.io/ipfs/QmVAebMg1mQRyJ8KiW6bUN3rYyn8oPgELiWmZuPPsByjY9
Doesn't work

It works on my local gateway,
http://gateway.ipfs.io/ipfs/QmNYYQHKtvXRag1zZ1JHA6noRbkZbH2fP36YmNn9U6tAdP

And my ipfs daemon is On, and i'am sure it must have been uploaded in the network , i've waited enough time ...

Strange

**Comment by BrendanBenshoof** [comment]
It looks like they just took a while to load.
I threw your images into http://cachewarmer.blamestross.com, so they should load faster now (for now).

If there was an issue, it appears to have resolved itself (which is annoying from the point of view of fixing it). 

It might just be that your local gateway has limited bandwidth or connectivity into the network (how soon after starting the node did you try and ad this?)

**Comment by bussiere** [comment]
I have one of the fastest connection for personnal use here (fiber)
http://www.speedtest.net/my-result/4660627367

And my daemon is still up .... 
That's strange ...

**Comment by jbenet** [comment]
i think this is a resolution problem. we're working on fixing this stuff.

@bussiere to troubleshoot, are you behind NAT?

**Comment by bussiere** [comment]
Yes i'am behind a NAT

**Comment by jbenet** [comment]
@bussiere can you show me your `ipfs id` ?? want to see the local addrs.

**Comment by bussiere** [comment]
ipfs id
{
    "ID": "Qmf5ZET7LNr84wDHnZpfVdhVqBcPvTKX8CtbdmqiZAqe8K",
    "PublicKey":
"CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC2Ia4e0flENp92So9+JnKzIoGj1gWbYXF7LOB2KiScp1PMA18z3HDjxnIo+I1VnX6vIWUUwz7uDxtKCtJrSVAYHKGJUQKaGqQNmuC2qZGg1KM3CCPunj3IGMqrCGfzQ9Rvn0ljFVeNwZjc0bPCQ8SkiSeVCznGvVBYy4VpW0vCgUckTRpyy37fZP2PrkeiUoZntoBknWKJZusn7Kpuh0DwhNWUhbaYC7KgFbUjO6eJMTSt7g6AUh3Tm/UaCV8IjkJpMV91uK8BQUVDR4Zoc+bLu7LXH8uSOBoe2Z0kIsH/5OJgz/r0wB6/i/nhykCDdvDxrWsQE1S/B6sT6TX0+WK5AgMBAAE=",
    "Addresses": [
        "/ip4/
127.0.0.1/tcp/4001/ipfs/Qmf5ZET7LNr84wDHnZpfVdhVqBcPvTKX8CtbdmqiZAqe8K",
        "/ip4/
192.168.0.17/tcp/4001/ipfs/Qmf5ZET7LNr84wDHnZpfVdhVqBcPvTKX8CtbdmqiZAqe8K",
        "/ip4/
172.17.42.1/tcp/4001/ipfs/Qmf5ZET7LNr84wDHnZpfVdhVqBcPvTKX8CtbdmqiZAqe8K",

"/ip6/::1/tcp/4001/ipfs/Qmf5ZET7LNr84wDHnZpfVdhVqBcPvTKX8CtbdmqiZAqe8K",
        "/ip4/
89.158.102.15/tcp/4001/ipfs/Qmf5ZET7LNr84wDHnZpfVdhVqBcPvTKX8CtbdmqiZAqe8K",
        "/ip4/
89.158.102.15/tcp/48159/ipfs/Qmf5ZET7LNr84wDHnZpfVdhVqBcPvTKX8CtbdmqiZAqe8K"
    ],
    "AgentVersion": "go-ipfs/0.3.8-dev",
    "ProtocolVersion": "ipfs/0.1.0"


- Были бы кости, а мясо нарастет

**Comment by jbenet** [comment]
hmmm, looks like it did bust through the nat (the `89...` addrs), but may be a symmetric nat, anything interesting about your network? 

(our nat holepunching isnt perfect yet, long way to go)

**Comment by bussiere** [comment]
Nope it's a classical french "box" for personnal usage.
It seems weird because i'ave already uploaded other albums and images to
ipfs and everything was fine. Just this time it didn't worked as planned
....

- Были бы кости, а мясо нарастет

**Comment by jbenet** [comment]
@bussiere hmm. try rebooting ipfs?

**Comment by whyrusleeping** [comment]
I'm pretty sure this has been resolved since.
