### ISSUE TITLE
Two ports opened

### ISSUE THREAD

**Issue by akaihola** [ipfs/go-ipfs#1700]
I have a laptop and a Raspberry Pi 2 behind a NAT router, with ipfs 0.3.8-dev installed on both. When I run the daemon on the laptop, it opens two ports on the public net, for example:

    laptop$ ipfs id
    {
        ...
        "Addresses": [
            "/ip4/127.0.0.1/tcp/4001/ipfs/Qm...",
            "/ip4/192.168.1.100/tcp/4001/ipfs/Qm...",
            "/ip4/172.17.42.1/tcp/4001/ipfs/Qm...",
            "/ip6/::1/tcp/4001/ipfs/Qm...",
            "/ip4/89.27.5.135/tcp/1137/ipfs/Qm...",
            "/ip4/89.27.5.135/tcp/16440/ipfs/Qm..."
        ],
        "AgentVersion": "go-ipfs/0.3.8-dev",
        "ProtocolVersion": "ipfs/0.1.0"
    }

(The 172.* IP seems to be there because I have Docker installed.)

I'm able to telnet from the outside to port 16440, so ipfs apparently has succeeded in setting that up with the router using uPnP. However, port 1137 is inaccessible.

When I `ipfs swarm connect` the laptop to ipfs on my cloud server, it registers the laptop with the 1137 address, not the 16440 address:

    cloud-server$ ipfs swarm peers
    ...
    /ip4/XX.XX.XX.XX/tcp/1137/ipfs/Qm...
    ...

The lower port number changes when I restart. I've seen e.g. 1026, 1092 and 1137. The same happens on the Raspberry Pi.

**Comment by whyrusleeping** [comment]
is it always 1137? or does it change?

**Comment by akaihola** [comment]
It changes. Although when I now restarted three times, the port is still always 1137. But yesterday it definitely was 1092 when I initially ran ipfs.

**Comment by whyrusleeping** [comment]
okay, thats fairly normal. Thats just the port that the remote side sees your dial originating from. As far as i know, raspberry pi's dont support `SO_REUSEPORT` so the remote wont see the 'correct' port.
