### ISSUE TITLE
'ipfs get [hash]' completes before file is fully downloaded

### ISSUE THREAD

**Issue by sroerick** [ipfs/go-ipfs#1712]
I have run into an issue where 'ipfs get' believes the file is complete long before it actually is.

I am not sure what causes this problem, but ran into it perhaps a dozen or so times while pinning a long list of files. 

I ran into this issue on multiple computers, and it should be reproducible, though it does appear to happen at random. 

Presently, to accurately 'get' hashes, I am running ipfs get on two different computers to ensure the file size is correct.

**Comment by jbenet** [comment]
odd-- and bad. we should try and get to repro this, so we can test for it.

**Comment by whyrusleeping** [comment]
@sroerick a quicker way to 'validate' a file from get would be to add it bad with 'ipfs add' and make sure it hashes the same

**Comment by sroerick** [comment]
@whyrusleeping I will do this in the future. 

@jbenet if it helps, I was working with the AlexandriaP2P library, trying to pin all content from the library. 
This is my list of pins: https://github.com/sroerick/infrastructure/blob/master/seeding/refs-to-seed
Many containers have many files within them, and some of the files are very large. I would assume the problem lies somewhere in there. 

Some of them also didn't have very many seeds, though I have a gateway seeding now. I don't know if some kind of dht error could cause this behavior, but should be at least one webseed running fulltime now. hopefully more soon.

**Comment by jbenet** [comment]
ah interesting. hmmm can you maybe repro with a script like this:

```sh
#!/bin/sh

hash=$1
if [ "$hash" = "" ]; then
  echo "usage: $0 <ipfs-path>"
  echo "test ipfs get"
  exit 0
fi

for i in {1..100}; do
  sleep 1

  ipfs repo gc  # clear old hashes
  ipfs get -o expected "$hash"
  diff expected actual

  if [ $? -ne 0 ]; then
    echo "get failed!!"
    break
  fi
done
```

**Comment by whyrusleeping** [comment]
A few bugs in `ipfs get` have since been fixed, if this is still a problem please open a new issue
