### ISSUE TITLE
cannot restart daemon on Windows after the daemon is stopped

### ISSUE THREAD

**Issue by Mithgol** [ipfs/go-ipfs#1713]
Steps that might reproduce the problem:

1. Download https://gobuilder.me/get/github.com/ipfs/go-ipfs/cmd/ipfs/ipfs_master_windows-amd64.zip to `U:\IPFS`.

1. Set `IPFS_PATH=U:\IPFS\.ipfs` in environment.

1. Run `ipfs init`.

1. Run some `ipfs cat` as `ipfs init` recommends. Also run some `ipfs add` to test what quick start says.

1. Finally run `start "" ipfs daemon` to start the daemon in another console window. The daemon seems to start correctly.

1. Ctrl+C in that window (as ipfs/faq#39 recommends) to stop the daemon. The window is closed.

1. Try `ipfs daemon` again (or try `ipfs id`) and get the following error:

![(screenshot)](https://cloud.githubusercontent.com/assets/1088720/9897020/38e4d186-5c4c-11e5-83bb-bfc2684b929a.gif)

It should be expected for the machine to refuse connections when the daemon is down, and it should not prevent the daemon from restarting.

**Comment by jbenet** [comment]
dupe of #1661 ?

**Comment by Mithgol** [comment]
Dupe of #1661 and #1681, closed as dupe.
