### ISSUE TITLE
high memory usage for ipfs daemon

### ISSUE THREAD

**Issue by eminence** [ipfs/go-ipfs#1719]
duplicate of #1584  ?

After adding a fairly small directory (7700 files, about 300MB total), ipfs memory usage shot up dramatically.  After letting things settle for about 20 minutes, there has been no change.  Here is a snapshot from `top`:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  553 achin     20   0 19.264g 7.979g  13668 S   2.3 25.4  67:56.68 ipfs
```

I've captured all of the debugging data from `http://localhost:5001/debug/pprof/` and saved it here:

[QmXD4RzFuHBtteB43dmgZeaNFeFC1rGECukRYGXWSZRtKo](http://ipfs.io/ipfs/QmXD4RzFuHBtteB43dmgZeaNFeFC1rGECukRYGXWSZRtKo)

**Comment by cryptix** [comment]
Hey, thanks for looking into this! I'm not sure if it is a duplicate or not, just a small FYI:

The pprof data dumps are nearly useless without the binary they came from,, Can you add binary next time? (BTW ziping go binaries usually leads to 40-60% size reduction:)

**Comment by lgierth** [comment]
Closing in favor of #1924
