### ISSUE TITLE
HTTP API - incorrect Content-Type - streaming output from a channel not always JSON

### ISSUE THREAD

**Issue by WeMeetAgain** [ipfs/go-ipfs#1721]
Code says:

> `// streaming output from a channel will always be json objects`

https://github.com/ipfs/go-ipfs/blob/master/commands/http/handler.go#L231

This isn't the case when `encoding=text` is specified,
response returns `Content-Type: application/json` where it should return `Content-Type: text/plain`

proof:
```bash
$ mkdir testdir
$ echo "hello test" > testdir/test.txt
$ ipfs add -r testdir
added QmRmPLc1FsPAn8F8F9DQDEYADNX5ER2sgqiokEvqnYknVW testdir/test.txt
added QmTcJAn3JP8ZMAKS6WS75q8sbTyojWKbxcUHgLYGWur4Ym testdir
$ curl -i "http://localhost:5001/api/v0/refs?arg=QmTcJAn3JP8ZMAKS6WS75q8sbTyojWKbxcUHgLYGWur4Ym&stream-channels=true&encoding=text"
HTTP/1.1 200 OK
Content-Type: application/json
Transfer-Encoding: chunked
X-Chunked-Output: 1

QmRmPLc1FsPAn8F8F9DQDEYADNX5ER2sgqiokEvqnYknVW
```

**Comment by jbenet** [comment]
you're right. not sure what's up. it should be in the commands lib i think

**Comment by whyrusleeping** [comment]
if you set encoding to text, its gonna send you text, the fact that it sets `Content-Type` to json is a bug.
