### ISSUE TITLE
requesting a big file block the terminal/http request

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/go-ipfs#1725]
Requesting a big file or group of files through the command line or the API is currently blocking. Pinning something big mean having a terminal running somewhere.

My personal use case is for a software build on top of IPFS that can request file or group of files that can be any size. Currently there is no other way than to have multiple HTTP request running indefinitely.

It would be nice, both for the API and the command line to be able to request something (pin? get?) and to have IPFS memorize this request and return.

**Comment by lgierth** [comment]
Yes, totally with you! We're discussing an overhaul of the pinning interface here: https://github.com/ipfs/go-ipfs/issues/1711
