### ISSUE TITLE
Req: Android support

### ISSUE THREAD

**Issue by aunk** [ipfs/go-ipfs#1729]
I'dlike to use ipfs, but my current os is android. Am i screwed?

**Comment by fazo96** [comment]
It depends on what you need to do, you can still read ipfs and ipns links using http://gateway.ipfs.io/ipfs/<hash>

There is a js implementation in development which will allow ipfs to be used pretty much anywhere, but it's not working yet.

**Comment by Mithgol** [comment]
There are probably some hardhips ahead because an initial port of IPFS to Android is expected to eat your mobile traffic and your battery's electrical energy like crazy.

Such port would also need to be improved eventually and told to slow down its file exchange when the device is not charging or not on Wi-Fi.

**Comment by lgierth** [comment]
@mschneider anything you could share regarding your android port a few months ago?

**Comment by pims** [comment]
@aunk could this be helpful https://github.com/ipfs/java-ipfs-api ?

**Comment by jbenet** [comment]
@Mithgol it will be ok with a DHT client instead. the DHT is the biggest constant-traffic thing.

**Comment by aunk** [comment]
@pims yea that'll help. Are therre compilers for android,on android?.l

**Comment by Mithgol** [comment]
So, is Android supported now or is it a wontfix?

**Comment by lgierth** [comment]
> So, is Android supported now or is it a wontfix?

There is nothing actionable in this feature request. We're definitely interested in concrete ideas and contributions regarding Android.

**Comment by RichardLitt** [comment]
What's wrong with keeping it open as a discussion issue with a label of 'help wanted'?

**Comment by mschneider** [comment]
I got it to work on Android 4 (rooted) with go 1.4 compiled as a binary and launched with fork from java

**Comment by lgierth** [comment]
> What's wrong with keeping it open as a discussion issue with a label of 'help wanted'?

Let's have that discussion in the notes repo as long as there's nothing actionable (code to review). We can still open issues here for concrete go-ipfs bugs/problems/enhancements. Let's fight issue tracker bloat! :fist: 

> I got it to work on Android 4 (rooted) with go 1.4 compiled as a binary and launched with fork from java

@mschneider Cool! The advantages of static compilation :)

**Comment by RichardLitt** [comment]
Sounds good.

**Comment by kevinmartinmauro** [comment]
@mschneider  are you open to sharing your code? might it an include an explanation of why root is needed?

**Comment by Kubuxu** [comment]
@kevinmartinmauro see: https://github.com/ligi/IPFSDroid I think they got go-ipfs running on Androind

**Comment by mschneider** [comment]
i cross-compiled back then on mac os x with go 1.4 for android. apart from setting up the cross-compiler i just ran `go build`. no magic.

android cross-compilation was experimental before 1.5 and was completely reworked with that release. by now it should just be a few ENV variables and `go build` and should work out of the box

**Comment by lgierth** [comment]
There is even an app nowadays: https://github.com/ligi/IPFSDroid (is uses xgo: https://github.com/karalabe/xgo)

**Comment by AlhaadiDev** [comment]
i has the same issue, anyone can  help me. Show me how it done. [this on euse kotlin](https://github.com/ligi/IPFSDroid ). Can anyone show me how it done using java and tell me step by step to implement IPFS in android.
