### ISSUE TITLE
cross platform paths need to get fixed

### ISSUE THREAD

**Issue by SCBuergel** [ipfs/go-ipfs#1730]
When adding a folder to IPFS in Windows via 

    ipfs add -r ameisng

the sub-folders are added with a backslash instead of a forward slash. This breaks e.g. websites published via IPFS as /index.html and /css/main.css are not loaded since they are in \index.html and \css\main.css.

Example:
I got the following hash of the main directory (containing an index.html) by running the command above:
https://gateway.ipfs.io/ipfs/Qmd4kv52hAjK1SoqGGwg1hmGkxrt5xZP9oQmvi9YwwN7rr
This does not load the index.html but just lists all files in the directory due to the backslash issue.

Solution:
Always use forward-slashes when adding sub-directories to IPFS.

**Comment by jbenet** [comment]
yeah this is an annoying problem. we need to fix this. it shouldn't be hard to do-- someone need to make sure we use `filepath` in all the right places.
