### ISSUE TITLE
UDT Transition path

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1738]
Once we get UDT into go-ipfs, we need to have a plan for how to transition the network to use it. My thoughts are as follows:

1. Change default config to include a UDT listener address, and provide instructions in release notes for users with prexisting configs to add it manually.
2. Update all bootstrap nodes to have both TCP and UDT listeners.
3. Somehow make go-ipfs prefer UDT addresses when given the choice between UDT and TCP.
4. update default config so that bootstrap node addrs are all UDT (or maybe just some of them)
5. update *some* of the bootstrap nodes to have only UDT listener addresses (2-3 nodes, definitely less than half)
6. change default config to *only* have a UDT listener (note: nodes will always have the ability to dial tcp)

These steps should be spaced a few days or so apart each, to give the network time to adapt to each change and to observe any issues along the way. Any bugs that get found and fixed related to the UDT transition process should increase the time between the relevant steps (allowing more time for users to update to the fixed code)

**Comment by zignig** [comment]
:+1: :100:

**Comment by whyrusleeping** [comment]
@zignig me too... but none such libraries exist with any sort of reasonable performance.

**Comment by jbenet** [comment]
above sgtm for the most part.

> - update default config so that bootstrap node addrs are all UDT (or maybe just some of them)
> - update some of the bootstrap nodes to have only UDT listener addresses (2-3 nodes, definitely less than half)
> - change default config to only have a UDT listener (note: nodes will always have the ability to dial tcp)

tons of networks block _ALL_ udp traffic. See https://www.google.com/search?q=udp+blocked
- nodes should continue to expose a TCP listener by default.
- all bootstrap nodes should continue to support tcp.

The benefits you're looking for can be achieved by getting "Somehow make go-ipfs prefer UDT addresses" right.
