### ISSUE TITLE
command: `ipfs repo stat`

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1744]
we need an `ipfs repo stat` command that can display stats like:

- Number of objects in local repo
- Total storage taken up (`du $IPFS_PATH`) 
- local path to repo ??

https://github.com/ipfs/node-ipfsd-ctl/issues/18

**Comment by dignifiedquire** [comment]
@jbenet @whyrusleeping the PR from @diasdavid was merged, can we close this?

**Comment by diasdavid** [comment]
sure :) (https://github.com/ipfs/js-ipfsd-ctl/issues/18 is unblocked ;))
