### ISSUE TITLE
ipfs update discussion

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1746]
The ipfs update command needs two primary bits of information:

1. How to check if a new version is available
2. How to download that new version

@jbenet How do we want to do this?

**Comment by jbenet** [comment]
Version check could be checking a list we maintain at a well known url (like the denylists stuff). (Basically rely on dns and HTTP for mutability until IPNS is perfect.)




Or, we could actually use lots of DNS TXT records for this. (Sigh, wish DNS was inverted and path based... tempted to implement a resolver that maps a/b/c/d to d.c.b.a ...)



—

**Comment by BrendanBenshoof** [comment]
Lazy p2p solution: include a signed certificate of "version info". When I encounter a peer that has an updated version, the certificate can "Inform me if I am out of date" and point to a ipfs hash of the new release.

You "push" an update by installing it on your servers and it spreads to your peers.

It does not really change anything in the security model. 

This is how GameOver Zeus dealt with updates.

**Comment by BrendanBenshoof** [comment]
```
Sigh, wish DNS was inverted and path based... tempted to implement a resolver that maps a/b/c/d to d.c.b.a ...
```

Why not ship a mini-DNS server with the ipfs daemon? You can use it to redirect DNS requests for websites with ipns txt records, and let it have whatever behavior you want for such cases.

**Comment by jbenet** [comment]
@BrendanBenshoof DNS resolution already works within Go, though i think it delegates to the OS resolver. moved reversing discussion over to: https://github.com/jbenet/random-ideas/issues/36

**Comment by whyrusleeping** [comment]
ipfs-update works, is shipped. closing
