### ISSUE TITLE
Smarter bitswap

### ISSUE THREAD

**Issue by ion1** [ipfs/go-ipfs#1750]
The current bitswap implementation is naive and results in download bandwidth being spent mostly on duplicate blocks.

I ran a benchmark by downloading a large file and plotting the bandwidth used by the ipfs daemon.

![graph](https://ipfs.io/ipfs/QmPVgoo3UCuZxmGu77qpHwGfYxNGK6XvUByuo9uwng28ar/ipfs.png)

The green graph shows the total download rate accurately but the boundary between light green (productive bandwidth) and dark green (bandwidth spent on duplicate blocks) is just an estimate based on the ratio between blocks received and dup blocks received.

The blue line shows the actual growth of the file that is being downloaded.

Also noteworthy:
- The 30 minutes of block downloading after the file has already been fetched and the wantlist is empty.
- The sawtooth pattern in the wantlist length which also affects the bandwidth usage. The wantlist behavior corresponds to the daemon exhausting the first top-level 45-megabyte link (consisting of a bunch of 250-kilobyte chunks) before proceeding to the next one.

[The scripts used to generate the graph](https://github.com/ion1/ipfs-benchmark). [The raw data](https://ipfs.io/ipfs/QmPVgoo3UCuZxmGu77qpHwGfYxNGK6XvUByuo9uwng28ar). [The file that was downloaded](https://ipfs.io/ipfs/QmTrRng9EWBWCLmpHVgKx3NDzHG8J8Y76Vuo21eYqKbyid).

**Comment by ion1** [comment]
Even with the naive bitswap implementation, couldn’t the daemon reject others sending it blocks not in its wantlist?

**Comment by jbenet** [comment]
it does, but still spend bandwidth receiving them before rejection. (need to hash it to know what it is). we could add a header with what object it is, for fast cancels, or a "confirm step" (but this is a bit less naive). bittorrent's wants are immediate, but bitswaps are more long term. we may want the confirm step there... or have it in a 0-rtt mode where the user can always cancel before receiving a large block).

**Comment by jbenet** [comment]
btw @ion1 this graph is fantastic, just the sort of stuff we need. I wonder if we could get a "scaffolding" setup so that the scripts run + the graph is produced by some buildbot somewhere (maybe travis or one of our machines) so that we can get the graphs on demand as we push new changes to bitswap

**Comment by jbenet** [comment]
(from there we can add more graphs). basically, this + bssim

**Comment by whyrusleeping** [comment]
we could send the hash of the coming block as a header to the message, this may help, but we still might be receving a decent amount of the data before we can close it out.

On the other side, we're already sending cancel messages to the nodes we're connected to, upon receiving a cancel, the nodes can check if they are sending us that block and halt the write. This might be more effective in places where upload bandwidth is congested compared to download (quite common ive heard).

A combination of both would probably help quite a bit, I would say that implementing the second one might be a bit easier to do first, it just requires keeping a map of cancel funcs for the contexts of each send, and writing a more finely grained context writer that allows us to cancel partway through the write.

**Comment by jbenet** [comment]
yeah let's implement the second, and see how it goes. i suspect you're right and that might cover 90% of the cases, because cancels should be written through anyway

**Comment by ion1** [comment]
Here’s another benchmark: downloading a single large directory full of small files (namely [the RFC archive](https://ipfs.io/ipfs/QmYrmnuar6wM7SkUTtdyfv1b4Dsq6HAnHkdhLYF2F1dwZ2)) instead of a single large file this time.

![graph](https://ipfs.io/ipfs/QmfEuq2GyZkjGTr8ohLRjLG1QR39fHzaBR2fUTgKrXVf1m/ipfs.png)

Noteworthy:
* Instead of the sawtooth pattern in the previous graph, the wantlist jumps to almost 8000 blocks in the beginning and steadily goes to zero.
* `ipfs get` only manages to write most of the data to the disk at the very end (the blue line).
* It took 6½ hours to download 500 MB of data vs. the previous graph where it took 3 hours to download 537 MB of data under more or less identical conditions. The difference seems to be in the structure of the data.

**Comment by jbenet** [comment]
- great, great graph
- that is awfully slow
- the dups are abusrd
- let's fix this

**Comment by whyrusleeping** [comment]
I'll take on implementing the changes discussed in the next sprint

**Comment by ion1** [comment]
Some ideas about wantlist management follow. They may or may not be good, and there’s a high likelihood you have already planned something better. In case some of this turns out to be useful, here goes:

* When downloading something, an almost-empty wantlist is pessimal (the first graph above, periodically), but so is a too large wantlist (the second graph above). There is a sweet spot somewhere. Perhaps we could estimate the optimal number of bytes to be queued for download based on the latency and peak dowload rate we are seeing.
  * Say, we are seeing a latency of 1 s and a bandwidth of 2 MB/s at a certain point. If we want to have 15 seconds worth of data in the wantlist, we could do the calculation as (15 s + *latency*) · *bandwidth* = 32 MB.
  * The latency component might be negligible as long as the network resides on a single planet.

Imagine we could estimate for every block a weight *w* corresponding to how likely the user is to request it soon. We could keep drawing blocks starting from the highest *w* to populate the wantlist until we reach the threshold computed above.

To facilitate this, we could add a `<object>.metadata` in addition to `<object>.data` on disk. The metadata for a given object would hold a set of links to the estimated “next” object based on its parent.

![IPFS “next” links](https://ipfs.io/ipfs/Qmaw7ZDNvHw3a17xSaxHNjPNjVuqiyrPXHfuyP2TnDofrK)

* When storing the object `A` with links to `B`…`F`:
  * Add into `B`’s “next” set the tuple `(added-by: A, type: direct, link: C)`. I drew the link to `C` as an edge with the `added-by` field as a label.
  * Add into `C`’s “next” set the tuple `(added-by: A, type: direct, link: D)`.
  * …
  * Add into `F`’s “next” set the tuple `(added-by: A, type: next-of, link: A)`. The “next” object from `F` is not `A` but whatever is “next” from `A`. I drew a bar above.the edge label to signify a `next-of` link.
    * Turns out we don’t have to store the `type` field. The type of the link is `next-of` if and only if `added-by` = `link`.
* When garbage-collecting the object `A`, remove all tuples with `added-by: A` from the metadata of its children.

The set of the possible “next” objects from a given object is:

* Its first child if it has one.
* Otherwise, the “next” set in its metadata with any `next-of` links recursively replaced with the `direct` link at the end of the chain if one exists (O(*ancestors*)).

Now that we have an estimate of the “next” object(s) for many objects, given an object that the user requested explicitly, we could follow its “next” links and assign the objects a decreasing weight with the assumption that the user might want the following chunk soon. Conceptually:

![IPFS “next” weights](https://ipfs.io/ipfs/QmPacdgag2qHScRQSUg3UWe5mQvrdn8C1hgRrgAYsGgFPq)
An algorithm for computing the weights and populating the wantlist might work as follows:

* Add all the objects the user is explicitly requesting to a priority queue with weight *w*=1.
* While the number of queued bytes is less than the threshold estimated above:
  * Take and mark the unmarked object with the highest *w*. Let *w*<sub>next</sub> = *c*·*w* (with a small constant *c*, e.g. 0.5). Add the “next” object to the queue with weight *w*<sub>next</sub>.
    * If there were multiple “next” objects, divide *w*<sub>next</sub> among them equally.
    * If the object was already in the queue with weight *w*<sub>old</sub>, set its weight to max(*w*<sub>old</sub>, *w*<sub>next</sub>).
    * If the “next” object was already on disk, apply the same logic to *its* “next” object with *c*·*w*<sub>next</sub>.
* We might want to have a weight threshold below which we refrain from adding “next” objects.
* Given a full queue, we might want to cancel objects with the lowest weight to free room for objects being added with higher weights.
* Do we want to communicate the weights to peers and take advantage of them when choosing what to upload? In this case, the wantlist being very long would no longer hurt since probability of receiving a block with a low weight is low.

**Comment by rht** [comment]
What would be the quick first aid for this bandwidth issue?
But it appears https://github.com/ipfs/go-ipfs/blob/master/exchange/bitswap/bitswap.go#L310 does remove duplicate block receives?

**Comment by cryptix** [comment]
@rht: the Code you linked to just stops the processing.

I had instances where a node during large requests was killed, restarted and was still hammered with duplicate blocks. I manually 'unwanted' the blocks in these cases because it just wouldn't stop.. 

Maybe we could introduce a check there, if received more than 50 dup blocks in the last 30 secs un-want again?

**Comment by rht** [comment]
`ipfs bitswap unwant` does exactly that, of what you referred as "stops the processing" (https://github.com/ipfs/go-ipfs/blob/master/core/commands/bitswap.go#L65).

How to check for the 50 dup blocks when each blocks that are being downloaded are removed from the wantlist right away?

Running the `ipfs bitswap unwant $key` works because you know which are the dup blocks.

**Comment by rht** [comment]
ic, so "stops the processing" is unraveled as "send message to wantmanager, which then removes the key from the wantlist".

Currently the dup block checking only checks whether the keys are in wl or not, but is not aware of the keys that are being canceled.

**Comment by rht** [comment]
ok, I'm trying to figure out how the machinery works.

So the wantmanager updates the wantlist entries at a period of 10 seconds. Within this, dup blocks will accumulate, beyond this, dup blocks are to be canceled.

**Comment by aaronshaf** [comment]
Is this still an issue?

**Comment by whyrusleeping** [comment]
It has improved since  this issue was created, but its still not great. I would enjoy seeing the graph that @ion1 produced regenerated using 0.4.5

**Comment by Kubuxu** [comment]
Here: https://ipfs.io/ipfs/QmQENM1DHba8PN2W1AAdiJ65aVhGvjp53z831FBQyJNLh5/ipfs.png

**Comment by aaronshaf** [comment]
Looks a heckuva lot better? Few duplicates?

**Comment by eingenito** [comment]
Duplicate blocks have been greatly reduced in releases 0.4.18 and up.
