### ISSUE TITLE
Daemon causes connection loss.

### ISSUE THREAD

**Issue by doei** [ipfs/go-ipfs#1761]
As discussed on #ipfs I can't run the ipfs daemon for more than a few minutes without getting kicked off. The issue looks similar to [this one](https://github.com/ipfs/go-ipfs/issues/1226), however having had this problem for a few days already, my ISP did not contact me for any port scanning problem.

@whyrusleeping advised me to filter a few IPs (from [this list](https://github.com/ipfs/go-ipfs/issues/1226#issuecomment-120498051)), which seemed to delay the connection loss for a bit, but didn't fully solve the issue...

Hope it helps, tell me if you want some more logs and/or info for whatever...

**Comment by lgierth** [comment]
Maybe this is generally an issue with the number of open connections? You could `ipfs swarm peers | wc -l >> peercount.log` until the connection drops?

**Comment by jbenet** [comment]
@doei what's your ISP? they may be throttling anything that looks like p2p.

**Comment by doei** [comment]
@lgierth tried it a couple more times with this in mind, got disconnected after around 125 peers each time.
@jbenet I doubt that cause bittorrent works fine.
I also tried deactivating the router's ipv6 firewall, but it didn't seem to change anything...

**Comment by cryptix** [comment]
@doei I had weird issues with my ISP for _month_ where daemon startup crashed and rebooted their supplied modem. BT and other P2P also worked fine, too.

**Comment by doei** [comment]
@cryptix so how did that stop?

**Comment by cryptix** [comment]
@doei hour(s) of calls and two holiday-days to get a support "techie" from them to run speedtest.net at my home.. I had to demonstrate them the crash twice until they changed _something_. I still think that it was the ISPs crappy carrier-grade NAT but... Just saying that you shouldn't factor out the ISP too soon.

**Comment by doei** [comment]
@cryptix so they didn't tell you what they changed exactly? I'm not factoring out anything, but filtering p2p traffic alone can't be the reason. Anyway thanks for the answers, i'll post here if anything ever changes.

**Comment by jbenet** [comment]
@doei that's painful, either way. After `0.3.8` lands this week, you'll get a udp based transport (UDT likely), so that might help.

**Comment by cryptix** [comment]
@doei you should come over to irc so we can discuss more - maybe it's worth a try to give you a patch that inserts sleep intervals between bootstrapping nodes.

**Comment by doei** [comment]
@cryptix i'm around :) just checked-in IRC

**Comment by Plumebit** [comment]
Did anybody find a solution to this problem?  I'm having the same exact issue with my connection for whatever reason.

**Comment by whyrusleeping** [comment]
This has been resolved since 0.4.0
