### ISSUE TITLE
docker usage prevents restart, repo.lock error

### ISSUE THREAD

**Issue by sroerick** [ipfs/go-ipfs#1762]
I've run into an issue where usage of the docker image seems to produce a file in ipfs_data called 'repo.lock'. If the daemon needs to restart, it returns the following error:

>  Error: can't Lock file "/data/ipfs/repo.lock": has non-zero size
 
Removing the file seems to allow restarts again. 

But the file is generated every time I boot the docker image. 

file contents are simply: 

> {"OwnerPID":1}

**Comment by jbenet** [comment]
@Luzifer you ran into this too, no?

**Comment by sroerick** [comment]
so my duct tape and bubble gum solution for this is to run a cron job that deletes repo.lock. 

Allows container to restart. 

seems pretty sketchy, but it's what I'm rolling with for now.

**Comment by jbenet** [comment]
Ugh that sucks. we need to get to the bottom of this, is this the flock library we use failing?

**Comment by whyrusleeping** [comment]
This has been resolved. (updates to the flock lib)
