### ISSUE TITLE
Daemon crashes

### ISSUE THREAD

**Issue by mattseh** [ipfs/go-ipfs#1766]
Hello,

I am trying out IPFS, and used the prebuilt linux 64 bit ARM image on a raspberry pi 2 (1gb ram version). I had it running in a screen session.

Checking on it around 24 hours later, I have this in my shell (I hope this helps, IPFS is a great idea):

github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-stream-muxer/yamux.(*conn).Serve(0x131d3c80, 0x12cfa1a0)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-stream-muxer/yamux/yamux.go:66 +0x1c
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream.(*Swarm).addConn
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/conn.go:173 +0x130

goroutine 7483428 [select]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux.(*Session).AcceptStream(0x13231080, 0x12461fb8, 0x0, 0x0)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux/session.go:154 +0x11c
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-stream-muxer/yamux.(*conn).AcceptStream(0x13231080, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-stream-muxer/yamux/yamux.go:58 +0x38
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-stream-muxer/yamux.(*conn).Serve(0x13231080, 0x1356b640)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-stream-muxer/yamux/yamux.go:66 +0x1c
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream.(*Swarm).addConn
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/conn.go:173 +0x130

goroutine 7498372 [select]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux.(*Session).keepalive(0x131e90e0)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux/session.go:246 +0xe0
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux.newSession
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux/session.go:96 +0x400

goroutine 7820070 [select]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux.(*Session).AcceptStream(0x123fea20, 0x154f5fb8, 0x0, 0x0)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux/session.go:154 +0x11c
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-stream-muxer/yamux.(*conn).AcceptStream(0x123fea20, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-stream-muxer/yamux/yamux.go:58 +0x38
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-stream-muxer/yamux.(*conn).Serve(0x123fea20, 0x14d21db0)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-stream-muxer/yamux/yamux.go:66 +0x1c
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream.(*Swarm).addConn
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/conn.go:173 +0x130

goroutine 6622023 [select]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux.(*Session).send(0x127e84e0)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux/session.go:290 +0x460
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux.newSession
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux/session.go:94 +0x3d4

goroutine 5600386 [select]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux.(*Session).send(0x13084240)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux/session.go:290 +0x460
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux.newSession
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux/session.go:94 +0x3d4

goroutine 7545237 [select]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux.(*Session).keepalive(0x12d145a0)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux/session.go:246 +0xe0
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux.newSession
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux/session.go:96 +0x400

goroutine 7557316 [select, 24 minutes]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux.(*Stream).Read(0x156f0700, 0x14ad9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux/stream.go:123 +0x378
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-stream-muxer/yamux.(*stream).Read(0x156f0700, 0x14ad9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-stream-muxer/yamux/yamux.go:20 +0x48
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream.(*Stream).Read(0x14b0ea80, 0x14ad9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/stream.go:73 +0x6c
github.com/ipfs/go-ipfs/p2p/net/swarm.(*Stream).Read(0x14b0ea80, 0x14ad9000, 0x1000, 0x1000, 0x14c05fb0, 0x0, 0x0)
        /go/src/github.com/ipfs/go-ipfs/p2p/net/swarm/swarm_stream.go:30 +0x50
github.com/ipfs/go-ipfs/metrics/stream.(*meteredStream).Read(0x12f68140, 0x14ad9000, 0x1000, 0x1000, 0x1, 0x0, 0x0)
        /go/src/github.com/ipfs/go-ipfs/metrics/stream/metered.go:37 +0x64
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-context/io.(*ctxReader).Read.func1(0x12b73c40, 0x14ad9000, 0x1000, 0x1000, 0x12eb2f40)
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-context/io/ctxio.go:108 +0x54
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-context/io.(*ctxReader).Read
        /go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-context/io/ctxio.go:111 +0xd0

**Comment by whyrusleeping** [comment]
@mattseh hrm, the top of the stack dump is chopped off. If you could run your daemon with stderr redirected like: `ipfs daemon 2> errors.output` and then give us that file when it crashes, that would help a lot!

**Comment by mattseh** [comment]
Cool, running with error recording now, will check back on it in a few days.

**Comment by mattseh** [comment]
Unfortunately, it happened again, see gist: https://gist.github.com/mattseh/9763b00187180d6c393a

**Comment by mattseh** [comment]
This may be useful:

pi@raspberrypi ~/ipfs $ ./ipfs swarm peers | wc -l
188

**Comment by whyrusleeping** [comment]
ah, yeah. on a raspberry pi, this is the issue: https://github.com/ipfs/go-ipfs/issues/1767

**Comment by whyrusleeping** [comment]
> and used the prebuilt linux 64 bit ARM image on a raspberry pi 2 

Although I didnt think that the raspberry pi was 64 bit. Are you sure?

**Comment by mattseh** [comment]
My mistake, I used this, https://gobuilder.me/get/github.com/ipfs/go-ipfs/cmd/ipfs/ipfs_master_linux-arm.zip , which is 32 bit

**Comment by whyrusleeping** [comment]
This has been resolved
