### ISSUE TITLE
IPFS daemon crashes

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1767]
originally posted by @p4bl0-

Hi there,

I've been running and IPFS daemon on my server for a few days now, and I noted regular crashes (one or two times a day).

It always starts with "panic: runtime error: slice bounds out of range".

At first I was running the master (0.3.8-dev) i386 version from Gobuilder downloaded last week, and the same behavior continues with the same version but from monday (2015-09-28).

The crash logs are very, very large (1.3Mo and 1.2Mo for today's (2015-09-29) crashes), and github doesn't want me to attach them to the issue, but I could create a gist here: https://gist.github.com/p4bl0-/16fb68dc8262bbe3b2c0 (no other public pastebin I found accepted files this size!).

Sorry to not be able to help further, I don't know how to read Go traces.

**Comment by whyrusleeping** [comment]
@p4bl0- are you sure youre running 0.3.8? I'm fairly certain that the issue i'm seeing in that stack trace has been fixed for a little while (before 0.3.7)

**Comment by p4bl0-** [comment]
Yes, I'm positive.

$ ipfs version
ipfs version 0.3.8-dev

**Comment by whyrusleeping** [comment]
this PR will fix the issue: https://github.com/jbenet/go-msgio/pull/8

**Comment by whyrusleeping** [comment]
this has been resolved!
