### ISSUE TITLE
IPFS wont compile on Windows due to go-log symlink

### ISSUE THREAD

**Issue by slothbag** [ipfs/go-ipfs#1794]
When building a fresh source tree and trying to compile on windows I get "missing go-log" error.  I believe this is due to the use of a symlink which windows does not support.  After I renamed the go-log folder to replace the symlink file it compiles normally.

**Comment by jbenet** [comment]
@slothbag i believe this was fixed last night? no? cc @whyrusleeping

**Comment by slothbag** [comment]
Sorry, yeah could have been.. i was meant to log this issue last week but forgot.

Actually I did a clean compile using go 1.5 this afternoon and it all went well so it must be fixed. I'll close it now.

**Comment by jbenet** [comment]
no worries! thanks
