### ISSUE TITLE
did cat lose the progress bar?

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1795]
I'm not seeing it

```
> ipfs cat QmXipyrjt2Vzjg2vV7uhgCi8GNEFhrEdXrirtDcYhqGGEc >r3

```
cc @rht

**Comment by jbenet** [comment]
QmXipyrjt2Vzjg2vV7uhgCi8GNEFhrEdXrirtDcYhqGGEc is ~200MB of randomness.

**Comment by rht** [comment]
The err happens only when daemon is on
`Error: read tcp 127.0.0.1:53124->127.0.0.1:5001: read: connection reset by peer`.
When offline, sometimes it shows progressbar when it is slow enough.

**Comment by jbenet** [comment]
isn't that error different? the cat actually completes

**Comment by jbenet** [comment]
And, are you getting cat progressbar at all on daemon now? it used to be there-- do we need to bisect this?

**Comment by rht** [comment]
No, the cat err when daemon that it doesn't complete. Bisecting.

**Comment by rht** [comment]
Found a bug: coreunix.Add should have ctx as arg.

**Comment by rht** [comment]
At least for the `connection reset by peer` err:

```
a7e50f1fbc5a58963a1b1e462575249de61540f1 is the first bad commit
commit a7e50f1fbc5a58963a1b1e462575249de61540f1
Author: Jeromy <jeromyj@gmail.com>
Date:   Fri Jul 24 17:41:59 2015 -0700

    implement http trailers for errors after headers are sent
    
    refactor http handler and copyChunks to get this all to work correctly
    License: MIT
    Signed-off-by: Jeromy <jeromyj@gmail.com>
```

**Comment by rht** [comment]
https://github.com/ipfs/go-ipfs/commit/a7e50f1fbc5a58963a1b1e462575249de61540f1

**Comment by whyrusleeping** [comment]
yeah, the connection reset by beer is a result of us not properly handling trailers, and will be fixed by #1621 when we make go1.5 a requirement.

**Comment by rht** [comment]
What would be the fix in the mean time? Offline cat?

**Comment by rht** [comment]
Can be closed?

**Comment by whyrusleeping** [comment]
it doesnt look like cat has a progress bar still... thats odd

**Comment by rht** [comment]
Bisecting, this is the latest good commit, https://github.com/ipfs/go-ipfs/commit/814f437fb48b26b4e4cede8a1bd102fe66b4edef. The first bad commit is still the same as the pointed out in https://github.com/ipfs/go-ipfs/issues/1795#issuecomment-145361972

**Comment by rht** [comment]
One likely cause: https://github.com/ipfs/go-ipfs/commit/a7e50f1fbc5a58963a1b1e462575249de61540f1#diff-ceb40d01c16a02936d808eb855ea499bR293 wraps outside of the progressbar reader.
Would it be clean to use channel (as the one in `ipfs add`)?

**Comment by jbenet** [comment]
fwiw, im not seeing the progressbar on add either. what happened?

cc @whyrusleeping

**Comment by jbenet** [comment]
and we should _test_ that progress bar works so that this doesnt happen again

**Comment by diasdavid** [comment]
Following @whyrusleeping's comment https://github.com/ipfs/go-ipfs/issues/736#issuecomment-168354462, we now have a progressbar, sometimes it takes time to appear when the dir is too large. Closing this one in favor of keeping progressbar enhancements discussion on #736
