### ISSUE TITLE
curl on gateway dies on big file. (timeouts?)

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1798]
```
> curl https://ipfs.io/ipfs/<300MB-file> >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 93  175M   93  163M    0     0   694k      0  0:04:18  0:04:00  0:00:18 1041k
curl: (18) transfer closed with 11912094 bytes remaining to read
```

is this a timeout hitting? maybe the request is timing out-- we shouldn't time out a request if it's started going. we should timeout resolves, but not the whole request. not if it's making forward progress.

**Comment by whyrusleeping** [comment]
I think this has been resolved. Please open a new issue if you see this again
