### ISSUE TITLE
pin add and rm should default to recursive

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1801]
currently `ipfs pin add` and `ipfs pin rm` and `ipfs pin ls` all default to showing direct pins. Direct pins are rarely used, and recursive pins are added by default when you add files.

We should make the `-r` or `--recursive` flag default to true, and have a `--direct` flag to manipulate the rarely used direct pins.

**Comment by ForrestWeston** [comment]
I can take a hack at this one.

**Comment by whyrusleeping** [comment]
cool, should be fairly low impact as far as the codebase is concerned. (high impact for users! We will need to make sure to announce this change properly)

**Comment by jbenet** [comment]
Yep, am convinced.

I think we should just flip the `--recursive` default to true, and have
people say `--recursive=false` instead of having to add a `--direct` flag
and having to make sure  edge cases like `--recursive --direct` are
erroring appropriately.

>

**Comment by ForrestWeston** [comment]
Making some headway, however: 
```ipfs pin add --recursive=false```
errors with:
```Error: Option 'recursive' takes no arguments, but was passed 'false'```
same goes for ```-r``` option.

**Comment by jbenet** [comment]
Looks like the library needs to accept optional values for bools.



—

**Comment by ForrestWeston** [comment]
Ok, I can put that in the same PR, working on it now.

**Comment by ForrestWeston** [comment]
This has been merged, closing...

**Comment by jbenet** [comment]
:+1: thanks @ForrestWeston
