### ISSUE TITLE
Daemon Crash: Unexpected Fault

### ISSUE THREAD

**Issue by stephen304** [ipfs/go-ipfs#1803]
Log is here: https://gist.github.com/Stephen304/0f393e85e9af3401a53b

I installed via the [go-ipfs-git](https://aur.archlinux.org/packages/go-ipfs-git/) arch package from the AUR.
This issue seems very very consistent as it always crashes after 1 minute.

```
ipfs daemon  0.24s user 0.06s system 0% cpu 1:00.19 total
ipfs daemon  0.33s user 0.15s system 0% cpu 1:00.31 total
ipfs daemon  0.17s user 0.06s system 0% cpu 1:00.19 total
ipfs daemon  0.18s user 0.07s system 0% cpu 1:00.31 total
ipfs daemon  0.18s user 0.07s system 0% cpu 1:00.16 total
ipfs daemon  0.17s user 0.07s system 0% cpu 1:00.16 total
```

Edit: I also tried uninstalling the package, ensuring it wasn't installed with which, and installing via go get. That also produced the exact same behavior.

**Comment by jbenet** [comment]
looks like a data race

**Comment by whyrusleeping** [comment]
@Stephen304 could we get some system information? 64 or 32 bit, x86* or arm? Which version of go do you have installed?

**Comment by Stephen304** [comment]
HP Chromebook 14 (x86), arch linux 64-bit go version devel +510f1db Mon Jul 20 16:31:37 2015 +0000 linux/amd64

**Comment by Stephen304** [comment]
So this is interesting: The prebuilt binary works fine, but the prebuilt is the same version as the one from go get. The binaries are different though:

    stephen@Jupiter ~ (git)-[master] % ipfs version
    ipfs version 0.3.8-dev
    stephen@Jupiter ~ (git)-[master] % cd Downloads/ipfs
    stephen@Jupiter ~/Downloads/ipfs (git)-[master] % ./ipfs version
    ipfs version 0.3.8-dev
    stephen@Jupiter ~/Downloads/ipfs (git)-[master] % md5sum /bin/ipfs
    0e604b4d497977362cba51e4378e17a2  /bin/ipfs
    stephen@Jupiter ~/Downloads/ipfs (git)-[master] % md5sum ipfs
    8abaa28f38ef78ad130a3836da3fbbcb  ipfs

**Comment by jbenet** [comment]
@whyrusleeping this was likley introduced recently? wonder if it's still in master.

**Comment by whyrusleeping** [comment]
This was a go bug (the ipfs daemon in question was built with a development version)
