### ISSUE TITLE
Move from logrus to go-logging for logs

### ISSUE THREAD

**Issue by noffle** [ipfs/go-ipfs#1808]
After chatting with @whyrusleeping, we agree that [go-logging](https://github.com/whyrusleeping/go-logging) would be a better, more readable logging lib for go-ipfs. All of the logging is already neatly contained in [vendor/](https://github.com/ipfs/go-ipfs/tree/master/vendor/QmXJkcEXB6C9h6Ytb6rrUTFU56Ro62zxgrbxTT3dgjQGA8/go-log).

- [ ] Rebase [op/go-logging](https://github.com/op/go-logging) onto @whyrusleeping's [fork](https://github.com/whyrusleeping/go-logging).
- [ ] Plug the resulting repo into [vendor/](https://github.com/ipfs/go-ipfs/tree/master/vendor/QmXJkcEXB6C9h6Ytb6rrUTFU56Ro62zxgrbxTT3dgjQGA8/go-log).
- [ ]  Update API calls throughout. (Though both libs expose a Logger type ([go-logging](https://godoc.org/github.com/op/go-logging#Logger), [logrus](https://godoc.org/github.com/Sirupsen/logrus#Logger)), they aren't 100% compatible, which will mean some amount of fudging.)

**Comment by whyrusleeping** [comment]
> Rebase op/go-logging onto @whyrusleeping's fork.

I'd go with rebasing my fork onto their latest master. All we changed was adding the functions with the explicit format strings (`Errorf` vs `Error`)

**Comment by rht** [comment]
Can be closed as of https://github.com/ipfs/go-ipfs/commit/248e74845dddee61eab7d0eb115e377d6adfbb62.
