### ISSUE TITLE
relased version 0.3.5_linux_amd64 shows 0.3.4 version

### ISSUE THREAD

**Issue by ChristianKniep** [ipfs/go-ipfs#1810]
While downloading the 0.3.5 version, it shows something else as version string.
Wrong file uploaded?

```
[root@f1d0aa3022dc tmp]# unzip ipfs_v0.3.5_linux-amd64.zip
Archive:  ipfs_v0.3.5_linux-amd64.zip
   creating: ipfs/
  inflating: ipfs/ipfs
   creating: ipfs/dist/
  inflating: ipfs/dist/install.sh
  inflating: ipfs/dist/README.md
  inflating: ipfs/dist/LICENSE
[root@f1d0aa3022dc tmp]# ./ipfs/
dist/ ipfs
[root@f1d0aa3022dc tmp]# ./ipfs/ipfs version
ipfs version 0.3.4
```

**Comment by ChristianKniep** [comment]
same goes for the `386` file.

**Comment by whyrusleeping** [comment]
@ChristianKniep yeah, we messed up on the tagging for that version.

**Comment by whyrusleeping** [comment]
We're currently on version 0.3.7, is there any particular reason you need version 0.3.5?

**Comment by ChristianKniep** [comment]
`0.3.5` is the last stable version to me. I opened an issue for that #1807 and put it in the README of my docker image: https://github.com/qnib/docker-ipfs

**Comment by jbenet** [comment]
@ChristianKniep sucks. that sounds like CORS headers missing. replied in #1807.

@whyrusleeping where did we mess up? i see:

- tag `v0.3.6` -> d50def3f5cb42a724de6f96c333b11281975add1 
- tag `v0.3.5` -> 952dc9c60fdff27902749222fdc30164e7eea1ee

**Comment by jbenet** [comment]
Oh, i see, we apparently failed to _actually_ bump the version till fa23022 -- we could re tag it. i don't recall what happend.

**Comment by diasdavid** [comment]
@ChristianKniep would updating your Docker image to use 0.3.10 and above work for you?

**Comment by ChristianKniep** [comment]
Hey @diasdavid,

I updated the version but and it shows the correct version string. :)
Even though I am not able to bootstrap it with only one peer. But that's a ticket for another day.

Thanks and keep up the good work!

Happy 2016
Christian
