### ISSUE TITLE
Can't add hidden files

### ISSUE THREAD

**Issue by mappum** [ipfs/go-ipfs#1812]
Currently, hidden files (anything prefixed with `.`) can't be added to IPFS. This makes it hard to work with some things, for example git repos (which have a `.gitignore`) and npm modules (`.npmignore`). The default behavior of excluding hidden files makes sense, but it should work when explicitly adding them.

```
$ touch .foo     
$ ipfs add .foo
ERRO[20:38:40:000] .foo is a hidden file                         module=commands/http
```

**Comment by zignig** [comment]
ipfs add --hidden .foo

**Comment by mappum** [comment]
Ah, didn't notice that when I quickly visually parsed the helptext:

```
OPTIONS:

    -r,     --recursive           bool   - Add directory paths recursively
    -q,     --quiet               bool   - Write minimal output
    -p,     --progress            bool   - Stream progress data
    -t,     --trickle             bool   - Use trickle-dag format for dag generation
    -n,     --only-hash           bool   - Only chunk and hash - do not write to disk
    -w,     --wrap-with-directory bool   - Wrap files with a directory object
    --hidden                      bool   - Include files that are hidden
    -s,     --chunker             string - chunking algorithm to use
```

Maybe it should be given the `-H` flag too (`-h` is taken by the help option).

**Comment by whyrusleeping** [comment]
using `-H` could work. that might be a good idea

**Comment by jbenet** [comment]
+1 for -H
