### ISSUE TITLE
IPFS daemon info logs

### ISSUE THREAD

**Issue by croqaz** [ipfs/go-ipfs#1816]
Hi all,

I am using the `ipfs daemon` with the `--debug` option, but the output is so huge, that is completely useless.

An `ipfs daemon --verbose` option that will show relevant output for a regular user would be very useful.
So when you add, name publish, etc, you see the command in the log and if it was a success, or a failure in some way.

This would be an improvement.

**Comment by jbenet** [comment]
Try less logging:

```
IPFS_LOGGING=info ipfs daemon
```

> An ipfs daemon --verbose option that will show relevant output for a
regular user would be very useful.
So when you add, name publish, etc, you see the command in the log and if
it was a success, or a failure in some way.

Have you seen the eventlog output? try

```sh
ipfs log tail
# or
curl http://localhost:5001/logs
```

Maybe we should have an option that outputs nginx-like formatted logs from
the eventlog.

i do not want to have _yet another_ set of logs, we already have two. what
we need is to filter these down to meaningful signal for users.

this is not an easy task. but we could start by commenting out all current
logs and readd the ones we need

**Comment by whyrusleeping** [comment]
you can modify the log levels while the daemon is running with `ipfs log level`, it allows you to tweak per subsystem to suit your needs.

**Comment by croqaz** [comment]
It's ok. Thank you !

I didn't see the option when I was typing ipfs and ipfs | grep log.
