### ISSUE TITLE
gateway: file upload functionality?

### ISSUE THREAD

**Issue by prusnak** [ipfs/go-ipfs#1819]
Would it make sense to enable adding a file to node via HTTP POST/PUT request to gateway? This would enable IPFS to be used in lots of web applications that just need GET/PUT functionality. This option should not probably be default and could be enabled via a command line switch (similarly how unrestricted-api is enabled).

**Comment by jbenet** [comment]
Yes, this used to be in and was removed to refactor. (Refactor didn't happen-- bad @cryptix). We should add it back in.




Should be a config option 



—

**Comment by whyrusleeping** [comment]
yeah, we used to have it. But it was quite complicated... now that we have patch code, we can rewrite it using that to reenable the functionality

**Comment by cryptix** [comment]
sorry... :disappointed:

**Comment by prusnak** [comment]
Seems to be implemented in #1543

**Comment by jbenet** [comment]
@prusnak seems in need of rebase and fixes. i dont have time for it atm. maybe @ebuchman ? or someone else?

**Comment by rht** [comment]
There is one https://github.com/ipfs/go-ipfs/pull/1845 but it depends on the add refactor to be merged.

**Comment by ebuchman** [comment]
I can take a look again this weekend. Does #1845 allow one to upload a directory?

**Comment by rht** [comment]
@ebuchman yes it does, see https://github.com/rht/go-ipfs/commit/545c07a1f75877350045ff81eded34a8f637d928#diff-19ceb36d78bde310c54cc44a95bec44cR269. Sorry for reinventing your PR.

**Comment by rht** [comment]
Currently the added node is pinned by default.

**Comment by davidar** [comment]
@jbenet will this enable https://botbot.me/freenode/ipfs/msg/50741140/ ?

**Comment by prusnak** [comment]
As this was implemented in merge from #1845 I am closing this issue.

There is a multipart issue tracked here: #2205
