### ISSUE TITLE
t0060-daemon fails if nc is not installed  

### ISSUE THREAD

**Issue by ForrestWeston** [ipfs/go-ipfs#1821]
Running the sharness tests fails on my computer (Arch-Linux) because I do not have NetCat installed. Not a big deal to install and they run/pass after the installation (openbsd-netcat), but I thought someone should know.
```
lib/sharness/sharness.sh: line 314: nc: command not found
> cat swarmnc

not ok 13 - transport should be encrypted
#	
#	  nc -w 5 localhost 4001 >swarmnc &&
#	  grep -q "AES-256,AES-128" swarmnc &&
#	  test_must_fail grep -q "/ipfs/identify" swarmnc ||
#		test_fsh cat swarmnc
#	
```

**Comment by jbenet** [comment]
indeed, we probably should use a simple go version or something

**Comment by chriscool** [comment]
Not sure if we can close this one as PR #1868 (t0060: fail if no nc) is merged.

**Comment by jbenet** [comment]
yep, you're right.
