### ISSUE TITLE
`ipfs files write <path> <data>` -> passing <data> errors

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#1828]
Being unable to write to a file using the <data> argument (piping a stream works perfectly though as also tests show https://github.com/ipfs/go-ipfs/blob/dev0.4.0/test/sharness/t0250-files-api.sh#L244-L336).

Also wondering why `-e` is the alias to `--create` and not `-c` and ` -n, --count ` could be used for a write, probably leftovers from the read call?

For ref: help menu
```
» ipfs files write --help                                          ◉ ◼◼◼◼◻◻◻◻◻◻

    ipfs files write <path> <data> - Write to a mutable file in a given filesystem

ARGUMENTS:

    <path> - path to write to
    <data> - data to write

OPTIONS:

    -o, --offset   int  - offset to write to
    -e, --create   bool - create the file if it does not exist
    -t, --truncate bool - truncate the file before writing
    -n, --count    int  - maximum number of bytes to read

DESCRIPTION:

    Write data to a file in a given filesystem. This command allows you to specify
    a beginning offset to write to. The entire length of the input will be written.

    If the '--create' option is specified, the file will be created if it does not
    exist. Nonexistant intermediate directories will not be created.

    Example:

        echo "hello world" | ipfs files write --create /myfs/a/b/file
        echo "hello world" | ipfs files write --truncate /myfs/a/b/file

```

**Comment by whyrusleeping** [comment]
`-e` is used because `-c` is taken already by the root command to specify the location of the config file.

> Being unable to write to a file using the argument 

What do you mean by this?

**Comment by diasdavid** [comment]
this:

```
» ipfs files write /folder1/a2 bananas                             ◉ ◼◼◼◻◻◻◻◻◻◻
Error: lstat bananas: no such file or directory

Use 'ipfs files write --help' for information about this command
```

**Comment by deltab** [comment]
Do you have a file called `bananas` in the current directory, for the command to read from?

**Comment by diasdavid** [comment]
@deltab with a file it does work, but is that what is expect with the second argument only? 
for ref from help menu: `<data> - data to write`

**Comment by whyrusleeping** [comment]
yeah, it expects a filename. Should probably make that more clear...

**Comment by deltab** [comment]
Yeah, an unclear description: the argument is the name of a file to read data from, to be written "to a file in a given filesystem", meaning... I'm not sure what exactly.

**Comment by diasdavid** [comment]
@whyrusleeping what about writing from a client that is not sharing the host with the IPFS node?

**Comment by whyrusleeping** [comment]
the file is read clientside and sent over the same way that the streamed stdin is

**Comment by diasdavid** [comment]
doh, got it! :D thanks @whyrusleeping

**Comment by jbenet** [comment]
@whyrusleeping  -- making sure -- `write` reads from stdin if the file arg is not there, right?

**Comment by whyrusleeping** [comment]
Yes, the input it takes is in the form of a `cmds.FileArg` which either takes the cli arg as the name of a file and opens it, or grabs stdin.
