### ISSUE TITLE
ipns resolve local name very slow

### ISSUE THREAD

**Issue by krl** [ipfs/go-ipfs#1831]
```
$ time ipfs name resolve
/ipfs/QmXQ5czKP2mhQrF2RtfiVv9sQ97MpWiyhSTTXgefgQdmHU
real	1m0.097s
```

@whyrusleeping 
This should probably read from the local known value of the ipns key, no?

It was pretty much instant before.

**Comment by whyrusleeping** [comment]
yeah, this behaviour was changed to query the network for records and select the best one. I agree that resolving the local name should be quick, but i'm not sure on the UX for this.

**Comment by jbenet** [comment]
wow, is it really taking 1min to go through the whole dht? exhausting the queriable set should exit this quicker.

maybe the queries are taking a long time as setting up new connections is very slow.

we should really get more data + viz on this. i think being able to animate queries and explore them will give us a much better way to solve the problem.

i'm reminded yet again that packet switching replaced line switching.

**Comment by whyrusleeping** [comment]
@jbenet its mostly dialing stuff that takes lots of time. I was going to work on some little tools for requesting records, giving the ability to specify how many to wait for and other such tweaks.

**Comment by krl** [comment]
If a quickfix would be possible, that would be great. the --local arg as
you suggested would work. I'm blocked on this re starlog at the
moment.

**Comment by whyrusleeping** [comment]
@krl i will try and get to that ASAP.

**Comment by whyrusleeping** [comment]
@krl https://github.com/ipfs/go-ipfs/pull/1834

**Comment by jbenet** [comment]
#1834 is merged.
