### ISSUE TITLE
ipfs id <self> fails

### ISSUE THREAD

**Issue by richardschneider** [ipfs/go-ipfs#1836]
Supplying the local peer id to `ipfs id` fails with `Error: routing: not found`.

     D:\ipfs>ipfs id
     {
        "ID": "Qmf5A6usmhEnrRWVTvLgGbVXsMXRvj8Ja9MTv6bT77oTSY",
        "PublicKey":  ...
        "Addresses": ...
        "AgentVersion": "go-ipfs/0.3.8-dev",
        "ProtocolVersion": "ipfs/0.1.0"
     }
    D:\ipfs>ipfs id Qmf5A6usmhEnrRWVTvLgGbVXsMXRvj8Ja9MTv6bT77oTSY
    Error: routing: not found

**Note** running on a windows machine

**Comment by jbenet** [comment]
this is because go-ipfs currently assumes a peerid means an online query.

- [ ] check if given peerid is own, if so, local should be fine.
- [ ] maybe offline routing should be able to resolve local records? cc @whyrusleeping

**Comment by whyrusleeping** [comment]
offline routing can resolve local records, but i think that findpeer is written in a way that it wont return information about the asker. which is kinda weird.
