### ISSUE TITLE
webui randomly stops working because API requests return 403

### ISSUE THREAD

**Issue by bcg-didi** [ipfs/go-ipfs#1839]
In my `http://localhost:5001/webui`, sometimes the Ajax API requests stop working, returning *403 Forbidden*.

When trying the cURL (copied from browser dev console) in terminal, it also returned 403.
Interesting find: when removing the "Referer" header from the request, the 403 went away.
Related IRC snippet:
\<rand_me> deltab: does that explain it for you?
\<deltab> no, but it indicates where to look
\<deltab> https://github.com/ipfs/go-ipfs/blob/d4938c9b0cd57c52c71ec83998a8288c3247826c/commands/http/handler.go#L350 

If I restart the ipfs daemon, the issue sometimes persists and sometimes goes away. No pattern found so far.

Info about how to enable debug log in ipfs config is welcome. Maybe that would help.

**Comment by lgierth** [comment]
That's CORS rejecting the request, try setting `API.HTTPHeaders`.

**Comment by mappum** [comment]
> Info about how to enable debug log in ipfs config is welcome. Maybe that would help.

You can get the daemon to output debug info to console with `ipfs daemon --debug`.

**Comment by bcg-didi** [comment]
> That's CORS rejecting the request

Yes, sounds like CORS. However I wonder:
* how comes it sometimes works (always using same URLs)?
* shouldn't the dev tools console tell if it's CORS? It didn't

> try setting API.HTTPHeaders.

Can you please tell me how exactly to do this? I'm new to ipfs.

**Comment by jbenet** [comment]
Not sure, but this may be part of a bug we're about to ship a fix for.

**Comment by chpio** [comment]
same problem here with the docker `:release` and `:master` tags.

**Comment by whyrusleeping** [comment]
This is generally a CORS problem, see `ipfs daemon --help` for more info there.
