### ISSUE TITLE
self-hosting the go-ipfs releases

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1841]
(meant to post this last week, apparently i didnt)

# self-hosting the go-ipfs releases

(this will be a model for other releases)

We've been meaning to self-host the ipfs binaries and the install/update process. This issue will track the different pieces that need to come into place.

## Current state

- go-ipfs binaries built with [gobuilder.me](https://gobuilder.me)
- go-ipfs binaries are hosted by gobuilder
- go-ipfs binaries not built reproducibly yet
- no developer-signed builds yet
- `ipfs-update` does not work yet
- [`install-ipfs.sh`](https://github.com/ipfs/install-ipfs) works (shell install from gobuilder)
- [releases.ipfs.io](https://github.com/ipfs/distributions) has been developed but not finished yet

## Desired state

- [ ] go-ipfs binaries built reproducibly (by gobuilder, devs, whoever...)
- [ ] go-ipfs binaries signed by multiple developers
- [ ] go-ipfs binaries hosted on ipfs
- [ ] `ipfs-update` should work
- [ ] auto-update should work (req signed, opt out)
- [ ] all releases ref published at an IPNS name
- [ ] all releases ref published at a DNS name (`releases.ipfs.io`)
- [ ] [releases.ipfs.io](https://github.com/ipfs/distributions) index deployed
- [ ] net-wall implemented to warn network operators of updates.

## complicating factors:

- signing binaries requires a secure key setup.
- signed binaries requires 100% reproducible builds for all the archs.
- dist.ipfs.io requires some design work

## Batches of work

-  [ ] **Phase 1: `ipfs-update` (by `0.3.9`)** https://github.com/ipfs/go-ipfs/issues/1842
  - [x] design `ipfs-update` https://github.com/ipfs/go-ipfs/issues/1841
  - [ ] implement `ipfs-update`
  - [ ] design net-wall
  - [ ] implement net-wall
  - [ ] `ipfs version` can show git commit

- [ ] **Phase 2: releases.ipfs.io -- still build from gobuilder**
  - [ ] finish designing `releases.ipfs.io` frontend
  - [ ] host binaries on ipfs
  - [ ] publish `releases.ipfs.io`
  - [ ] releases DNS + IPNS refs
  - [ ] update `install-ipfs.sh` to use bins from ipfs
  - [ ] update `ipfs-update` to use bins from ipfs

- [ ] **Phase 3: signed releases -- gobuilder still builds master**
  - [ ] achieve reproducible builds on all archs (build machines? vms?)
  - [ ] setup key infrastructure (see tuf)
  - [ ] get hardware key devices for @whyrusleeping, @jbenet, and others.
  - [ ] setup build signing release protocol
  - [ ] achieve signed builds

- [ ] **Phase 4: verify signed releases**
  - [ ] update `ipfs-update` to require signed releases
  - [ ] update `install-ipfs.sh` to require signed releases
  - [ ] update releases.ipfs.io to show signatures
  - [ ] implement auto-update

**Comment by jbenet** [comment]
See also https://github.com/ipfs/go-ipfs/issues/1842

**Comment by whyrusleeping** [comment]
https://dist.ipfs.io is live!
