### ISSUE TITLE
`ipfs-update` design + implementation

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1842]
(meant to post this last week, apparently i didnt)

# `ipfs-update` design + implementation

`ipfs-update` is a subtool that updates an ipfs distribution.

Requirements:
- [x] it should be callable with `ipfs update`
- [x] it should be callable directly with `ipfs-update`
- [x] it should be capable of operating without the daemon on (`ipget`?)
- [x] it should be capable to operating with a broken ipfs default repo, and broken `ipfs` binary.
- [x] it should prefer to download using ipfs
- [x] it should fall-back to download with HTTPS (dist.ipfs.io)
- [ ] it should fall-back to download with HTTP (if-and-only-if! signed releases)
- [ ] it should fall-back to a manually-given tarball (`ipfs-update install <ipfs-0.3.8.tar.gz`)

Phases:
- [ ] Phase 1: scaffolding, installs from gobuilder
- [ ] Phase 2: installs from `dist.ipfs.io`
- [ ] Phase 4: verifies signatures on releases

## Commands

```
> ipfs-update --help

  ipfs update - update the ipfs distribution

SUBCOMMANDS

  ipfs update check             - checks for new updates
  ipfs update install <release> - install a specific release
  ipfs update latest            - install latest release
  ipfs update version           - returns current installed version
  ipfs update versions          - lists all known versions

DESCRIPTION

  The `ipfs update` command is used to update an ipfs distribution
  directly via ipfs. It is a standalone tool meant to be included
  with the distribution. Though it can be distributed, and run
  completely independently.

> ipfs update check
Current version: go-ipfs/0.3.9
Latest version: go-ipfs/0.4.0
To update, run: ipfs update latest

> ipfs update latest
Current version: go-ipfs/0.3.9
Latest version: go-ipfs/0.4.0
Downloading /ipfs/QmYJzq3Ggx9bDjRPrG41oFhiVwCqqZwxAtdAsXg2X6rAD6/ipfs-0.4.0-darwin
[=====================================================>          ] 82% of 20 MB # or whatever
Shutting down ipfs daemon...ok        # if one is detected
Verifying ipfs-0.4.0-darwin...ok      # runs some test commands
Installing ipfs-0.4.0-darwin...ok     # moves into place
Old version available at /Users/jbenet/.ipfs/old-bin/go-ipfs/0.3.9
Current version: go-ipfs/0.4.0
```

**Comment by jbenet** [comment]
this is important for 0.3.9 release

**Comment by whyrusleeping** [comment]
@jbenet we will need some sort of endpoint for the tool to query to discover what versions are available, and where to download them.

**Comment by whyrusleeping** [comment]
We will need something like:
```
> curl https://ipfs.io/dist/go-ipfs/versions
{
    "latest":"0.3.9",
    "0.3.9":"/ipfs/Qmasdasd",
    "0.3.8":"/ipfs/Qmeeeeee",
    "0.3.7":"/ipfs/Qmaljkawd",
}
```
And each of those hashes would resolve to a directory with a child directory for each architecture.

**Comment by JJJollyjim** [comment]
How will this work when ipfs has been installed through the system package manager?

**Comment by whyrusleeping** [comment]
@JJJollyjim thats a good question. there should probably be some code to check for an installation method... Although, we should probably do it similar to how chrome does. You only install with your package manager, but updates happen through the app itself.

**Comment by jbenet** [comment]
> We will need something like:

we already have it. in https://github.com/ipfs/distributions/pull/10/files#diff-d2772e81a298311bb7bd125ec42d37deR43 we add a json file to the distributions repo with all the info per version.

**Comment by JJJollyjim** [comment]
@whyrusleeping where do you get that? From [the chromium website](https://www.chromium.org/administrators/turning-off-auto-updates):

> **Q:** Does Chrome on Linux auto-update too?
> **A:** Google Chrome on Linux does not auto-update itself; it relies on your package manager to update it.

In fact, my Chrome install (Arch Linux) is a couple of versions old because I haven't updated from the AUR recently. Windows install:

![capture](https://cloud.githubusercontent.com/assets/691552/10563254/6b5583fc-75df-11e5-9715-12836920cfb4.JPG)

Arch install:

![screenshot_2015-10-18_21-31-14](https://cloud.githubusercontent.com/assets/691552/10563263/9ff9d55e-75df-11e5-87a0-541520aff03f.png)

Assuming you're planning to get `go-ipfs` into repos, I don't think that packagers would be keen on having the software downloading and installing updates as binaries from a 3rd-party. As a user, I trust the maintainers of my distro to not push malicious code to my system in updates and to have secure building/package-signing processes, though I cannot say the same for the developers of each individual package.

Just my thoughts, love what you're doing with IPFS!

**Comment by whyrusleeping** [comment]
@JJJollyjim ah, yeah. youre right. I got confused with steam.

**Comment by whyrusleeping** [comment]
> we already have it

@jbenet can i curl dist.ipfs.io/versions or something for that then?

**Comment by jbenet** [comment]
@whyrusleeping you'll be able to:

```
> curl dist.ipfs.io/go-ipfs/versions
v0.2.2
v0.2.3
v0.3.2
v0.3.3
v0.3.4
v0.3.5
v0.3.6
v0.3.7
v0.3.8
```

this is done but i cant push an example because the network am in is blocking all non-http traffic and i need to setup some cjdns style tunnel to look like HTTP/TLS.

**Comment by whyrusleeping** [comment]
`git push https://github.com/ipfs/whatever master`

**Comment by jbenet** [comment]
an example will be at: https://ipfs.io/ipfs/QmZiSAYkU7gZtqYeZWL21yuwgFtRnJu1JjDzR6Qd2qdDBr once i'm back at a real network.

**Comment by jbenet** [comment]
@whyrusleeping it's pushed to git: https://github.com/ipfs/distributions and make. ipfs just needs to look more like http/tls.

**Comment by whyrusleeping** [comment]
@jbenet could i get a json object or something back from the versions endpoint? having just a list works... but its not as nice

**Comment by jbenet** [comment]
@whyrusleeping deal with the versions list or PR https://github.com/ipfs/distributions -- i dont have time this week for dev.

**Comment by whyrusleeping** [comment]
ipfs update is a thing and has shipped!
