### ISSUE TITLE
findprovs returns invalid JSON when using the API

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/go-ipfs#1851]
The CLI command findprovs works perfectly fine. Example output: 
```
> $ ipfs dht findprovs QmXFmCEhamPHvpbzQ3HMFABrpAXgE7D9jzp6QtvyC8Xp55                                                                ⬡ 4.0.0 
QmNnCaT1sa8zAwpnqDARwhXWZgXQ452EVWvRJg9WkwVnUN
QmWuZGboBP9fpoFvFZ1H9mEKcor5Uz8vk76eib9ssvCpvW
QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd
```

However, when using the API and making the following request:
```
curl localhost:5001/api/v0/dht/findprovs?arg=QmXFmCEhamPHvpbzQ3HMFABrpAXgE7D9jzp6QtvyC8Xp55
```
Returns the following invalid JSON https://gist.github.com/VictorBjelkholm/1c459d6710c4e3a762f6

First, all the objects needs to be wrapper in an array. Secondly, between the objects, there has to be a comma.

A third, possibly unrelated issue, is that the response always seems to end with:
```
{
  "Extra": "routing: not found",
  "ID": "",
  "Responses": null,
  "Type": 3
}
```

**Comment by VictorBjelkholm** [comment]
Closing this since seems to be a bug in the node-library
https://github.com/ipfs/node-ipfs-api/issues/76

**Comment by jbenet** [comment]
try using curl on the API directly, if still not sure if it's in go-ipfs or node-ipfs-api
