### ISSUE TITLE
go-ipfs binary is too large

### ISSUE THREAD

**Issue by CaioAlonso** [ipfs/go-ipfs#1855]
Seeing as we are gearing up towards self-hosting releases and autoupdating them, I think it would be interesting to reduce the ```ipfs``` binary size.

Go is not compatible by default with upx, but https://github.com/pwaller/goupx fixes that. Maybe we could use it?

A preliminary test with the code in master gives me a 75% reduction in binary size:
```
$ du -h ipfs
24M     ipfs
$ goupx ipfs
(...)
$ du -h ipfs
6.1M    ipfs
```

And using the ```--strip-binary``` option, even more:
```
$ du -h ipfs
24M     ipfs
$ goupx --strip-binary ipfs
(...)
$ du -h ipfs
4.5M    ipfs
```

**Comment by whyrusleeping** [comment]
what is being removed? Go's binaries are large because they are statically compiled. I assume that all of that space is code, and I was also under the assumption that the compiler removed unused code.

I'm skeptical that you can get such a reduction in size without any adverse side effects.

**Comment by jbenet** [comment]
I suspect there's a ton from debugging symbols.



—

**Comment by whyrusleeping** [comment]
well if we remove those, then all the panics will be illegible and useless for debugging anything. (if that is in fact whats taking up all the space)

**Comment by CaioAlonso** [comment]
@whyrusleeping there's some discussion about this here: https://github.com/golang/go/issues/6853

**Comment by lgierth** [comment]
Wow, that's some weird copyright header! https://github.com/pwaller/goupx/blob/master/hemfix/hemfix.go

All rights reserved, based on code found somewhere, *and* GPL! :)

**Comment by Kubuxu** [comment]
I close it as https://github.com/ipfs/go-ipfs/issues/2097 is more developed.
