### ISSUE TITLE
on Windows 386, "the NTVDM CPU has encountered an unhandled exception."

### ISSUE THREAD

**Issue by fiatjaf** [ipfs/go-ipfs#1860]
Using the Windows 386 binary on https://gobuilder.me/github.com/ipfs/go-ipfs in a computer with Windows 7 I got this. Tried running in compatibility mode, but the problem is the same. What could be wrong here?

**Comment by whyrusleeping** [comment]
@fiatjaf could you try building it yourself?

**Comment by whyrusleeping** [comment]
this appears to be a bad instruction, aka, the compiler wrote bad bytecode.

**Comment by fiatjaf** [comment]
@whyrusleeping on Windows? I could, but I don't even know how to start. Does the Go compiler run on Windows? Do you have instructions somewhere?

**Comment by whyrusleeping** [comment]
@fiatjaf sure! let me write you something up...

There are prebuilt binaries for go here: https://golang.org/dl/ (hopefully *that* doesnt crash for you too)

Once you install that through the installer, you will need need to set the environment variable `GOPATH`
if you have something like git-bash installed, you can just open a terminal and do `export GOPATH=somewhere`. thats where go will store packages it downloads.

With that variable set, run `go get github.com/ipfs/go-ipfs/cmd/ipfs`. That should download the source, and build and install the ipfs binary. If that succeeds, the ipfs binary should be located at `$GOPATH/bin/ipfs`

let me know if anything else needs to be cleared up

**Comment by fiatjaf** [comment]
@whyrusleeping, tried to compile it, got some errors (after a long time, probably downloading? the internet is slow here):

```bash
pc@pc-PC MINGW32 ~
$ mkdir go
pc@pc-PC MINGW32 ~
$ export GOPATH=~/go
pc@pc-PC MINGW32 ~
$ go get github.com/ipfs/go-ipfs/cmd/ipfs
# github.com/ipfs/go-ipfs/Godeps/_workspace/src/bazil.org/fuse
go\src\github.com\ipfs\go-ipfs\Godeps\_workspace\src\bazil.org\fuse\error_std.go                                                                                                                                  
               :27: undefined: errNoXattr
go\src\github.com\ipfs\go-ipfs\Godeps\_workspace\src\bazil.org\fuse\fuse.go:1092                                                                                                                                 
                : undefined: attr
go\src\github.com\ipfs\go-ipfs\Godeps\_workspace\src\bazil.org\fuse\fuse_kernel.                                                                                                                                  
               go:152: undefined: syscall.O_ACCMODE
go\src\github.com\ipfs\go-ipfs\Godeps\_workspace\src\bazil.org\fuse\fuse_kernel.                                                                                                                                  
               go:378: undefined: attr
```

Windows is bizarre.

**Comment by whyrusleeping** [comment]
Ah, right. For windows we need to specify not to build in fuse support:
```
$ go install -tags=nofuse github.com/ipfs/go-ipfs/cmd/ipfs
```

**Comment by fiatjaf** [comment]
Ok, I've tried compiling in a 64bit Windows 8 and a x86 Windows 7 and both worked. I don't know if something has changed in the codebase in the meantime, so I'll have to try again the binary from gobuilder.me (the delay in the tests happens because these computers aren't mine and I don't use them often).

**Comment by whyrusleeping** [comment]
@fiatjaf thanks for the feedback! I'm going to venture a guess that gobuilders binaries are bad then...

**Comment by jbenet** [comment]
@whyrusleeping why would gobuilder's binaries be bad? 

fwiw, gobuilder has been accused a few times before, and always been something else.

**Comment by whyrusleeping** [comment]
@jbenet this is the library linking issue we talked about, someone else had a very similar issue on a weird distro of linux too.

**Comment by fiatjaf** [comment]
Finally tried it again with the binary from gobuilder.me and it has worked.
