### ISSUE TITLE
Running multiple ipfs

### ISSUE THREAD

**Issue by ottuzzi** [ipfs/go-ipfs#1872]
Hi,

how can I run multiple ipfs daemon on a single machine? It would be useful to change:
* ipfs init to specify where to create .ipfs directory
* ipfs daemon to specify from which directory to read config file
* ipfs any other command to specify from which directory to read config file

I cannot see in any help if these features are already available.

What do you think?
Thank in advance
Bye
Piero

**Comment by lgierth** [comment]
You can use the `IPFS_PATH` env variable with any command.

**Comment by whyrusleeping** [comment]
you can also specify the command line flag `-c` with the same effect.

**Comment by jbenet** [comment]
you can also use the `--api` flag to target a remote daemon
