### ISSUE TITLE
Timing tests

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#188]
Need to move away from timing tests, to something sync/mock based like: https://www.youtube.com/watch?v=ndmB0bj7eyw

**Comment by whyrusleeping** [comment]
I think we can probably close this now, our tests are much better in regards to relying on timers

**Comment by briantigerchow** [comment]
https://build.protocol-dev.com/job/gotest/696/console

failure at bd1d8767eb0810de66ee5b226b937d7c81a29e13

ok  	github.com/jbenet/go-ipfs/p2p/net/mock	0.898s
--- FAIL: TestDialBackoff (1.61 seconds)
	dial_test.go:103: new silent peer: <peer.ID QmUDmJ> /ip6/::1/tcp/54504
	dial_test.go:235: s2 should not happen immediately
	dial_test.go:252: s2 took too long
	dial_test.go:260: s3 should not happen yet
	dial_test.go:276: s3 took too long

**Comment by whyrusleeping** [comment]
hrm...  thats a new one. Agreed on the reopen

**Comment by jbenet** [comment]
That's  my fault. it's a timing test :( -- it's hard to do real network tests without using time. i'll try to rework it / make it more generous. maybe should add some signals inside the swarm functions itself.

**Comment by cryptix** [comment]
[Found](https://build.protocol-dev.com/job/race/17421/consoleText) another timing related one for the list: `TestStBackpressureStreamWrite` from `p2p/test/backpressure`.

**Comment by jbenet** [comment]
- [ ] TestBootstrap-- it so annoying.

**Comment by cryptix** [comment]
- [ ] [TestSimultOpenFewStress](https://github.com/jbenet/go-ipfs/blob/88dea5771d32cd3864a904731d4aaa55435be965/p2p/net/swarm/simul_test.go#L59) - maybe have a global or return a chan from `SubtestSwarm` to know when to advance?

**Comment by jbenet** [comment]
Saw this one again:

```
--- FAIL: TestBootstrap (0.56s)
	dht_test.go:303: connecting 30 dhts in a ring
	dht_test.go:79: dial attempt failed: misdial to <peer.ID NsEZww> through /ip4/127.0.0.1/tcp/51254 (got <peer.ID VnbQqa>)
TestBogusPrivateKey.Sign -- this better be a test!
FAIL
FAIL	github.com/ipfs/go-ipfs/routing/dht	2.356s
```

**Comment by whyrusleeping** [comment]
`TestBootstrap` still fails occasionally... would love to get that one fixed up.

**Comment by lgierth** [comment]
Another TestBootstrap failure: http://ci.i.ipfs.io:8111/viewLog.html?buildId=1000&buildTypeId=GoIpfs_CiTests&tab=buildLog

**Comment by Kubuxu** [comment]
Please reopen or create new issue if there are any more test failures.
