### ISSUE TITLE
Add `ipfs object cache` command

### ISSUE THREAD

**Issue by rht** [ipfs/go-ipfs#1891]
For downloading hashes into datastore without writing output to local dir.

https://github.com/rht/go-ipfs/commit/cc79cb36ed84a54f23376633feb425f948ededb9 but with a better way to ensure the blocks have been downloaded (instead of https://github.com/rht/go-ipfs/commit/cc79cb36ed84a54f23376633feb425f948ededb9#diff-94bc6ab66c2700453221e08f66413d94R262).

**Comment by whyrusleeping** [comment]
so `ipfs object get -o /dev/null <hash>` ?

**Comment by rht** [comment]
Yes for that particular commit.
But surely there is a way to receive notifications from `GetBlocks` channel.

This is to be used for partial mirror/backup of a hash, e.g. https://github.com/ipfs/archives/issues/29.

**Comment by whyrusleeping** [comment]
what is the expected behaviour you want from the command? like, a specific usecase or two. I'm defintely not against this, I just want to make sure we place it correctly.

**Comment by rht** [comment]
One specific use case is to distribute the links of a hash into multiple `IpfsNode`s:
1. $mirrorServer1 ipfs refs $hash | get_1st_1/N_of_links | ipfs object cache
...
N. $mirrorServerN ipfs refs $hash | get_Nth_1/N_of_links | ipfs object cache

Another use case is to simply mirror a hash without having to output to local dirs.

**Comment by whyrusleeping** [comment]
`ipfs refs -r <hash>` will do what you want. it fetches refs locally (caching them).

**Comment by whyrusleeping** [comment]
We could add an option to refs to print no output for this purpose.

**Comment by rht** [comment]
I thought `ipfs refs -r` is just to get object links.
Though it does fetch the entire object through `core.Resolve`.

To read the links of an object, its data needs to be fetched as well?
How to fetch the links of an object without fetching its data?

**Comment by whyrusleeping** [comment]
runnings `ipfs refs -r` on a hash will fetch the entire heirarchy.

**Comment by rht** [comment]
> How to fetch the links of an object without fetching its data?

This is needed for manual "ipfs-cluster".

And isn't `ipfs object links` basically `ipfs refs` but without `-r` option?

**Comment by whyrusleeping** [comment]
`ipfs object links` prints out the links stored in an individual merkledag object, as does `ipfs refs` without the `-r`. With the `-r` all links are traversed in order to find *all* refs under a given object.

**Comment by rht** [comment]
Then shouldn't either of `ipfs refs` or `ipfs object links` be squashed? Or put in doc, "This is an alias to 'ipfs refs'".

**Comment by jbenet** [comment]
They're logically independent tools that happen to coincide in output in one case. They're not aliases 



—

**Comment by rht** [comment]
Here are sanity checks,
1. doc
`ipfs refs`:
```
DESCRIPTION:

    Retrieves the object named by <ipfs-path> and displays the link
    hashes it contains, with the following format:
    
      <link base58 hash>
    
    Note: list all refs recursively with -r.
```

`ipfs object links`:
```
DESCRIPTION:

    'ipfs object links' is a plumbing command for retreiving the links from
    a DAG node. It outputs to stdout, and <key> is a base58 encoded
    multihash.
```
(found a typo retreiving -> retrieving)

2. code https://github.com/ipfs/go-ipfs/blob/master/core/commands/refs.go#L261 and https://github.com/ipfs/go-ipfs/blob/master/core/commands/object.go#L761
3. test `ipfs refs` is used in t0080-repo.sh, while `ipfs object links` is used in t0081-repo-pinning.sh. They are both used for pin check, and are interchangeable.

They are essentially the same tool, except that `ipfs refs` have more features.

**Comment by jbenet** [comment]
> They are essentially the same tool, except that ipfs refs has more features.

Not the same tool. please understand the scoping, one is meant to operate on a raw objects, the other on whole fs/graph.  They're logically independent tools that happen to _coincide_ in idea and in output in one case. They're not aliases though.

another example:

```sh
# on master
rm Makefile
git checkout Makefile
git status
rm Makefile
git checkout-index <filename>
git status
```

**Comment by rht** [comment]
Though `git checkout` does cover all of `git checkout-index` functionalities (but I'm not sure why they are implemented separatedly, if @chriscool can shed some light here).

**Comment by chriscool** [comment]
`git checkout-index` was created at the very beginning as checkout-cache.c: https://github.com/git/git/commit/33db5f4d9027a10e477ccf054b2c1ab94f74c85a

while `git checkout` was created a few month later as git-checkout-script in shell:
https://github.com/git/git/commit/303e5f4c325d008c68e5e70e901ab68b289ade2e

as can be seen in the commit message at first `git checkout` did not accept filenames, that was added later.
