### ISSUE TITLE
ipfs daemon: error log is not show code line

### ISSUE THREAD

**Issue by ldnvnbl** [ipfs/go-ipfs#1893]
I think error log shows code line is good for developer, especially for some new developer who want to contribute to the project.

I use this log format in my project:

```
[prefix] [timestamp] [log level] [code info] [log info]
```
example:

```
2015/10/24 12:54:02.503853 [INFO] github.com/ipfs/go-ipfs/xxxx.go:23:  Swarm listening on /ip4/127.0.0.1/tcp/4001
```
log level can be: DEBUG, INFO, WARN, ERROR, PANIC, FATAL

I think this issue is nice for developer!

The issue https://github.com/ipfs/go-ipfs/issues/1808 say that will move from logrus to go-logging for logs, go-logging is very nice, but it just log shortfunc. if go-logging can log code line, that will be very nice.

**Comment by whyrusleeping** [comment]
Yep. youre preaching to the choir. I want this too, and i'm probably going to push it out this week.

**Comment by whyrusleeping** [comment]
this has been fixed
