### ISSUE TITLE
[meta] workflow and labels discussion

### ISSUE THREAD

**Issue by chriscool** [ipfs/go-ipfs#1894]
As discussed in PR #1847 there are the following labels:

- `in progress`, not yet ready
- `RFCR`, ready for code review,
- `RFM`, ready for merge,
- `need_tests`, a special case of `in progress`

Let's discuss here if this is enough and how we should use them.

**Comment by chriscool** [comment]
My opinion is that the `RFCR` and `RFM` tags and maybe others like them (for example `RFC`) should be put by the author of the PR and should describe what is needed to move the PR forward from his/her point of view.

For example:
- a `RFC` would mean "it is a very experimental feature that might not be worth it, do you agree this feature is worth it and should be done like this", while
- a `RFCR` would mean "I think this is a good uncontroversial or already discussed feature, do you think my code is bug free and maintainable", and
- a `RFM` would mean "every comments have been taken into account, or the changes are obviously good, it should be merged now"

Other labels like `needs_tests` or maybe `need_doc` could be added by reviewers, but except in simple cases like tests or doc missing, reviewers might often want to explain what is needed in more details than a label.

Reviewers could also add a `LGTM` or `+1` label or comment if they think that the PR should be merged but they should not merge it themself.

**Comment by whyrusleeping** [comment]
@chriscool i like this and agree.

**Comment by jbenet** [comment]
Sgtm. 




Though I wouldn't want a serious process to be a MUST in that it can be really annoying if we force people to always apply labels. We can start by having them and using them to see if it's very useful. In the end, a label change doesn't notify people and a comment with the same words (as we are already doing) is usually easy enough of a signal.



—

**Comment by whyrusleeping** [comment]
I like using the labels because it makes it really easy to see from the pr page what needs attention.

**Comment by jbenet** [comment]
Agreed but it can be a hassle to maintain



—

**Comment by rht** [comment]
`need_tests` -> `need tests`?

`LGTM` label -> but whose `LGTM`? Should this be differentiated to `jbenet LGTM`, `whyrusleeping LGTM`?
It is simpler to check the labels than to scroll through the reviews looking for a LGTM.

I think the m-of-n review labels should be used only for huge/feat PR.

**Comment by rht** [comment]
> I think the m-of-n review labels should be used only for huge/feat PR.

Depending on how huge/critical the change is, could even notify the most recent authors in the lines being changed with `git blame`.

**Comment by whyrusleeping** [comment]
Yeah, i dont think a `LGTM` label is needed, that one would be difficult. A comment saying "LGTM" should suffice in that case.

**Comment by whyrusleeping** [comment]
resolved
