### ISSUE TITLE
ipfs swarm connect is returning before making sure the connection was indeed dialed

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#1895]
It can be tested with node-ipfs-api 

https://github.com/ipfs/node-ipfs-api/commit/a4655dd13ea67171a22f68da110d9d8ef2011197

**Comment by whyrusleeping** [comment]
this is troublesome

**Comment by whyrusleeping** [comment]
closing

**Comment by diasdavid** [comment]
thank you :)

**Comment by whyrusleeping** [comment]
@diasdavid see #1900, its not what your issue was, but it helps.
