### ISSUE TITLE
daemon stops responding after running for a while

### ISSUE THREAD

**Issue by mungojelly** [ipfs/go-ipfs#1896]
I noticed that my daemon routinely stops providing or receiving data after running it for a little while!

$ cat /etc/fedora-release 
Fedora release 21 (Twenty One)

$ ipfs version
ipfs version 0.3.8

ipfs cat <hash> or cat /ipfs/<hash> hang indefinitely

my ipns hash stops being available through https://ipfs.io/ipns/QmSy5XjpgqhD4t436czqP1sgcGSxx7n4p7JC8hVEDsnDs7

"ipfs dht findprovs QmSy5XjpgqhD4t436czqP1sgcGSxx7n4p7JC8hVEDsnDs7" takes a long time and then says "error: routing: not found"

ipfs swarm peers still shows plenty of peers: http://ipfsbin.xyz/#QmY1JoCSm46AfJ2BskMvoEZsBJA4oZCoSA2zFFxRvy1Gtt

ipfs log tail: http://ipfsbin.xyz/#QmX4iVYPMWtMVXLMC4EmG3g8GQt1Kb2hR7hbWewa88i4CK

**Comment by whyrusleeping** [comment]
I'm pretty sure one of the 10 open PR's i have fixes this. In the future, could you run your daemon with stderr redirected to a logfile (`ipfs daemon 2> logfile`) and then when your daemon becomes unresponsive, use ctrl+\ to send a sigquit to the daemon, causing it to print out all stack dumps before exiting. Then provide that logfile for me on the issue report.
