### ISSUE TITLE
Daemon doesn't handle windows WM_CLOSE

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/go-ipfs#1897]
I want to embed a daemon instance in a Qt GUI and I've some trouble to properly terminate the daemon process.

As stated in the QProcess terminate() function:

> On Windows, terminate() posts a WM_CLOSE message to all toplevel windows of the process and then to the main thread of the process itself. On Unix and OS X the SIGTERM signal is sent.

What happen is that the daemon doesn't handle this signal and keep running, to be lately abrubtly killed and leaving the repo with a repo.lock file.

I'm not sure about the status of signals on windows and what should be done here. Any idea ?

**Comment by whyrusleeping** [comment]
good catch, i think we should be using `os.Interrupt` instead of `os.SIGINT` in our interupt handler

**Comment by MichaelMure** [comment]
I tried the pull request branch and it doesn't work for me. The daemon keep running as before.

I also tried to use the windows API from the C++ side without more success:
```
GenerateConsoleCtrlEvent(CTRL_C_EVENT, daemon_process_->processId());
GenerateConsoleCtrlEvent(CTRL_BREAK_EVENT, daemon_process_->processId());
```

(insert rant about unreadable api docs here)

**Comment by djdv** [comment]
This can be closed when the builds switch to Go 1.14.
See: https://github.com/ipfs/go-ipfs/pull/6808 (includes a patch for <= 1.13 if needed)

**Comment by Stebalien** [comment]
I'm planning on building the next version with go 1.14 anyways. Thanks for tracking this!

**Comment by MichaelMure** [comment]
> I'm planning on building the next version with go 1.14 anyways. Thanks for tracking this!

Just a reminder: https://github.com/libp2p/go-libp2p-kad-dht/issues/453#issuecomment-591958668

**Comment by Stebalien** [comment]
The query logic has been rewritten from scratch (in a testing branch for now) so we'll have to re-test that once that stabilizes.
