### ISSUE TITLE
dependency: mdns

### ISSUE THREAD

**Issue by cryptix** [ipfs/go-ipfs#1901]
Hi,

ages ago (ipfs/go-ipfs#1156) I forked `hashicorp/mdns` to get it to update one of their dependencies (hashicorp/mdns#37). Upstream never came through and there are new PRs of interest piling up (cryptix/mdns#1).

@gaboose started https://github.com/Gaboose/mdns 

> Forked from hashicorp/mdns with a selection of PRs merged, because they were starting to pile up and stagnate.
> I'll add each author of a PR that's merged as a collaborator to this repo. See where that takes us.

I never had deeper inside into mdns (just wanted to consolidated our `x/net/context` dependency, really) and don't want to maintain it, so maybe we should switch? Maybe we can substitute my collaborator access for @ipfs/go-ipfs-team ?

**Comment by Gaboose** [comment]
Oh, you noticed that. I wasn't sure if adding a collaborator gives a
notification.

I didn't mean to load responsibility on any of you. Just wanted to try a
"push access for all" kind of thing.

Sure, I can switch you for the ipfs team.

**Comment by cryptix** [comment]
> I didn't mean to load responsibility on any of you. Just wanted to try a "push access for all" kind of thing.

Oh don't get me wrong. Thanks for making the fork, I hope it will flourish! I just wanted to get more relevant people involved. :)

**Comment by jbenet** [comment]
i'm down to use @Gaboose's work if it has feature parity and improvements.

@Gaboose may be worth talking to hashicorp about taking over maintenance of the main fork. not sure.

**Comment by whyrusleeping** [comment]
I think we're still technically using @cryptix's library. Lets re-evaluate.

**Comment by cryptix** [comment]
Oh wow.. I hoped you updated since this was a thing.

**Comment by Gaboose** [comment]
Regarding the cryptix's request in first post. I think i can't add access for a team of an organisation which I'm not a part of.

**Comment by lgierth** [comment]
This is using whyrusleeping/mdns now, which is an up-to-date fork of hashicorp/mdns.
