### ISSUE TITLE
Using ipfs pin rm from API does the right thing but returns a message like: { Pinned: [ 'Qma4hjFTnCasJ8PVp3mZbZK5g2vGDT4LByLJ7m8ciyRFZP' ] }

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#1903]
Noticed that `ipfs pin rm` returned:

```
{ Pinned: [ 'Qma4hjFTnCasJ8PVp3mZbZK5g2vGDT4LByLJ7m8ciyRFZP' ] }
```

and then when checking for the list of pins, the hash was not there, which means that the behaviour is correct, it is just the word "Pinned" that should say Unpinned"

ipfs cli shows a correct message however.

**Comment by jbenet** [comment]
agree.

**Comment by whyrusleeping** [comment]
this has since been changed to `Pins`, which is more agnostic to the action performed
