### ISSUE TITLE
ipfs service example doesn't build: undefined: "github.com/ipfs/go-ipfs/repo/fsrepo".At

### ISSUE THREAD

**Issue by jchown** [ipfs/go-ipfs#1904]
I'm trying to build the example "[Roll your own IPFS](https://ipfs.io/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/example#/ipfs/QmThrNbvLj7afQZhxH72m5Nn1qiVn3eMKWFYV49Zp2mv9B/api/service/readme.md)" in https://ipfs.io/docs/examples/ but I get 

> undefined: "github.com/ipfs/go-ipfs/repo/fsrepo".At
> undefined: core.NewNodeBuilder

I'm sorry, I'm a complete IPFS and Go noob...

**Comment by whyrusleeping** [comment]
yeah, the examples are from github.com/ipfs/examples, the one youre looking at is api/service.

Its fixed there, we need to update the webpage with the examples repo again.

@jbenet whats the procedure for doing this?

**Comment by jbenet** [comment]
- update examples in https://github.com/ipfs/website/ 
- use the makefile in https://github.com/ipfs/website/

I just did it.

**Comment by jchown** [comment]
Thanks guys!
