### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ottuzzi** [ipfs/go-ipfs#1906]
Hi,

is there any public roadmap for ipfs/go-ipfs?
I tried to look for it but I cannot find it.

Thanks
bye
Piero

**Comment by rht** [comment]
Yes, 0.4.0, for example
![deliver](https://ipfs.io/ipfs/QmVURr9WEp5kioLDYADP1gB45n53nzNxfKpmDvqYfeWmK1)
See https://github.com/ipfs/go-ipfs/milestones.

**Comment by ottuzzi** [comment]
Hi,

thanks for your answer... I was looking more for a possible timeframe: is there any expected release date for 0.3.9 or 0.4.0?

Thanks in advance
Bye
Piero

**Comment by whyrusleeping** [comment]
my current estimates:

## 0.3.9
later this week (friday probably), shipping a fix to windows builds, and a few other bugfixes for things that slipped through testing on 0.3.8

## 0.3.10
was going to be 0.3.9, but we wanted to ship bugfixes sooner. This should be able to happen by nov 20(ish) if things go well. This update is planned to contain 'ipfs update' and utp.

## 0.4.0
I will be pushing to get this in before the new year. Ideally, second week of december, but more likely we will push up against the last week of the year.

**Comment by rht** [comment]
@whyrusleeping what are ways to move this to the nearer future (at the same time, without being rushed)?

**Comment by cryptix** [comment]
@Ottuzi you might also want to check out the project management repo (ipfs/pm) for progress reports.

**Comment by whyrusleeping** [comment]
@rht getting faster code review through. 

0.3.9 actually can be shipped now, the bugfixes i want are in. I can writeup the changelog in the morning and do that. 

0.3.10 needs a good design on utp, if you want to help me work out how the interfaces should look for the transport stuff and where things should go, that would be awesome. I want to have a video call with @jbenet and discuss it so we can get it done quickly (would *love* to merge utp by monday). The other thing that 0.3.10 needs it ipfs-update, most of the independent tool is written, if you want to look over that and give me feedback that would be great. The other part of ipfs-update is having it able to be called from the ipfs cli, (`ipfs update` calls to `ipfs-update` similar to git). Any help figuring out the way to wire this nicely into ipfs/commands-lib would also be appreciated.

After that, we have 0.4.0, which in my opinion, can just merge after 0.3.10 lands and i rebase (and test). But we should probably write down concretely exactly what our expectations for 0.4.0 are.

I would love to get to having more consistent, reliable releases. Anything we can do towards that end i'm on board for.

**Comment by whyrusleeping** [comment]
For further reference, take a look at the captains log: https://github.com/ipfs/go-ipfs/issues/2247
