### ISSUE TITLE
Feature request: no automatic pinning on ipfs-add

### ISSUE THREAD

**Issue by eminence** [ipfs/go-ipfs#1908]
Add a `--no-pin` option to `ipfs add` to prevent the file(s) from being automatically pinned.

This is useful when you want to add some content temporarily to IPFS, and it's too burdensome to remember to manually unpin the content later.

This is one solution to some of the use-cases in https://github.com/ipfs/notes/issues/49

**Comment by rht** [comment]
For reference, @ebuchman had wanted this as well, but for gateway.

**Comment by rht** [comment]
Can be closed.

**Comment by rht** [comment]
(here goes)
