### ISSUE TITLE
Multipart upload not working as advertised

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/go-ipfs#1915]
According to @whyrusleeping when uploading files via the http api using `add -r` the request should not need to nest the multipart parts into each other, but can be simply submitted as a list. But if I try to attempt sending such a request I get the error `File argument 'path' is required` back.

Here is the wireshark dump of the request that's being sent: https://gist.github.com/Dignifiedquire/bc72721f5b96c7017188

Tested versions: `0.3.7`, `0.3.9-dev`.

**Comment by rht** [comment]
Currently it is created only when the content type is "multipart/form-data": https://github.com/ipfs/go-ipfs/blob/master/commands/http/parse.go#L99.

**Comment by Dignifiedquire** [comment]
Closing for now as it does work, just not very intuitive.

**Comment by rht** [comment]
This could be added right away since https://github.com/ipfs/go-ipfs/blob/master/commands/files/multipartfile.go#L68 also checks the case for 'multipart/mixed'.

**Comment by rht** [comment]
Actually, the lib itself, `r.MultipartReader`, doesn't handle `multipart/mixed`.
