### ISSUE TITLE
dht get is hanging on 0.3.9

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#1923]
In the CLI

```bash
 ✘ ⮀ ⭠ tests-update± ⮀ ~/Documents/code/ipfs/js-ipfs-api ⮀
» ipfs dht put key 'b'                                                     ◉ ◼◼◼◼◼◻◻◻◻◻
storing value at <peer.ID dWox4M>
storing value at <peer.ID PXVJms>
storing value at <peer.ID bPaEBH>
storing value at <peer.ID WPNZbN>
storing value at <peer.ID eZzw2y>
storing value at <peer.ID PuH4wv>
storing value at <peer.ID SoLju6>
storing value at <peer.ID SAe6zd>
storing value at <peer.ID SXpdF5>
storing value at <peer.ID QLUokU>
 ⭠ tests-update± ⮀ ~/Documents/code/ipfs/js-ipfs-api ⮀
» ipfs dht get 'key'                                                       ◉ ◼◼◼◼◼◻◻◻◻◻
# never returns
```

In js-ipfs-api

```JavaScript
      apiClients['a'].dht.put('scope', 'interplanetary', function (err, res) {
        console.log(err, res)
        // err -> null
        // res -> 
// [ { Extra: '',
//    ID: 'QmRS475pVJMm82wTKaRqDUnF4uMhCgLJNxi2Wqb2tCqRpn',
//    Responses: null,
//    Type: 5 },
//  { Extra: '',
//    ID: 'QmVY3TjkAonbxj2xabvouLA9awy6mTxoMPNcfN78xEB9fp',
//    Responses: null,
//    Type: 5 },
//  { Extra: '',
//    ID: 'QmVY3TjkAonbxj2xabvouLA9awy6mTxoMPNcfN78xEB9fp',
//    Responses: null,
//    Type: 0 },
//  { Extra: '',
//    ID: 'QmRS475pVJMm82wTKaRqDUnF4uMhCgLJNxi2Wqb2tCqRpn',
//    Responses: null,
//    Type: 0 },
//  { Extra: '',
//    ID: 'QmRS475pVJMm82wTKaRqDUnF4uMhCgLJNxi2Wqb2tCqRpn',
//    Responses: [],
//    Type: 1 },
//  { Extra: '',
//    ID: 'QmVY3TjkAonbxj2xabvouLA9awy6mTxoMPNcfN78xEB9fp',
//    Responses: [],
//    Type: 1 } ]
        if (err) {
          throw err
        }

        apiClients['a'].dht.get('scope', function (err, value) {
          console.log(err, value)
          // err -> 
// { Extra: '',
//  ID: 'QmVY3TjkAonbxj2xabvouLA9awy6mTxoMPNcfN78xEB9fp',
//  Responses: null,
//  Type: 0 }
          // value -> undefined
          if (err) {
            throw err
          }
          assert.equal(value, 'interplanetary')
          done()
        })
      })
```

**Comment by diasdavid** [comment]
Ah, correction, CLI finally returned with: `error: record key does not have selectorfunc`

**Comment by jbenet** [comment]
yeah i think this is the same error i was seeing in https://github.com/ipfs/js-ipfs-api/issues/96

**Comment by whyrusleeping** [comment]
@diasdavid the dht doesnt support arbitrary keys being put to it. (thats the error youre seeing). The time its taking i'm not so sure about

**Comment by diasdavid** [comment]
"dht doesnt support arbitrary keys", is that a recent change? It was working on 0.3.7. What kind of keys does it support then?

**Comment by diasdavid** [comment]
dht get on a valid hash (of a previous added file) returns an error too:

```
» ipfs dht get QmW92LT5rgN9Gnsf2JXwowZTcQfmhoMphTHMjXt1c55rfb              ◉ ◼◼◼◼◼◼◼◼◼◻
error: record key does not have selectorfunc
```

**Comment by whyrusleeping** [comment]
supported keys on the dht right now are `/ipns/<hash>` and `/pk/<hash>`.

the first is for the ipns record of the peer whose ID is the hash, and the second is for public keys.

**Comment by diasdavid** [comment]
Still had no luck
https://github.com/ipfs/js-ipfs-api/commit/3f161720d8e98cd6c956bb4c833a243dcbf750bc
https://github.com/ipfs/js-ipfs-api/commit/a0b61acfedefb5d8196ce2d56074d212e0c03dc6

**Comment by diasdavid** [comment]
for context: https://botbot.me/freenode/ipfs/2015-11-02/?msg=53251377&page=2

`selectorFunc` error is indeed a bug

**Comment by diasdavid** [comment]
@jbenet pointed out that we need to document this properly
https://botbot.me/freenode/ipfs/2015-11-02/?msg=53253155&page=2

**Comment by RichardLitt** [comment]
@diasdavid I'm not sure what I would do about usage considerations. I agree with jbenet that it might be easy for docs to grow stale, and overhead of maintaining them might be too high. What works for most issues is a GitHub issue you can point to that stays open until this actual issue is closed by later implementations, which you can point to if anyone asks. Another thing that might be done is to just add a note next to relevant code, or in the documentation tied to the code, so that it is not locked in a repo.

The real question is: who will need to see these considerations? How can we explain it to them? Before, or after they're familiar with this area of the code? Can we have better training materials to make them see that this isn't the best option or use, and why there are DOS security concerns? How do we make that clear?

**Comment by whyrusleeping** [comment]
This has since been resolved
