### ISSUE TITLE
Check Key Pair Generation

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#1929]
### Key-pair generation

It is critical that we check cryptographic operations to ensure the right amount of entropy is being sourced.
See: [Issue #911](https://github.com/ipfs/go-ipfs/issues/911)

This was previously a markdown file in a `dev` folder: see https://github.com/ipfs/go-ipfs/pull/1930.

**Comment by jbenet** [comment]
we determined a long time ago this is fine.
