### ISSUE TITLE
Tag versions on DockerHub

### ISSUE THREAD

**Issue by jonnor** [ipfs/go-ipfs#1944]
Hi, hoping this is right place to report issues about https://hub.docker.com/r/jbenet/go-ipfs/

Currently there is only one (Docker) tag in the repo, `latest`. Can you also add tags for version, like '0.3.9'?
I'm considering deploying IPFS in production, and want to refer to a particular version of go-ipfs.

CC @jbenet

**Comment by lgierth** [comment]
We should rename the image to ipfs/go-ipfs and see if the new automatic tagging will be good enough.

**Comment by jbenet** [comment]
SGTM. lmk what i should do. happy to hand over the image to another maintainer too

**Comment by lidel** [comment]
@lgierth I just tested `ipfs/go-ipfs:v0.3.11` and it says..

```
> docker run -d --name ipfs-node (...) ipfs/go-ipfs:v0.3.11                                                                                                                                         
95e0c02a78645f1eb320ecbea65c030178b3f51449ed1c03e3350b29fc74e719

> docker logs -f ipfs-node
Running ipfs version 0.4.0-dev...
Found ipfs repository. Not initializing.
Initializing daemon...
Error: Repo has incorrect version: 2
Program version is: 3
Please run the ipfs migration tool before continuing.
See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md
Sorry for the inconvenience. In the future, these will run automatically.
```

Seems that the tag wrong, and 0.4.x binary is shipped.. :trolleybus:

**Comment by lgierth** [comment]
thanks @lidel for checking this out -- oh man. Looking into it.

**Comment by lgierth** [comment]
So I built that tag using this curl command, and from Docker Hub's documentation I was pretty sure it'd do the right thing...

```sh
$ curl -H "Content-Type: application/json" --data '{"source_type": "Tag", "source_name": "v0.3.11"}' -X POST https://registry.hub.docker.com/u/ipfs/go-ipfs/trigger/[snip]/
```

**Comment by lgierth** [comment]
Yeah okay I've removed the v0.3.11 tag -- back then the Dockerfile would always build from master, unless you'd pass in another ref via the `VERSION` env variable.

Closing this whole issue since we have tags now, at least for >= v0.4.

**Comment by lgierth** [comment]
Okay one more open question. @whyrusleeping in v0.4.0-rc1, the image is built using go1.4.2 -- I recall bugs, is it worth keeping that build up? The Dockerfile on master builds using go1.5.3.

**Comment by whyrusleeping** [comment]
ooooh, yeah. we need to use at least 1.5.2

**Comment by lgierth** [comment]
Okay then I'm gonna remove that one too.
