### ISSUE TITLE
Issue Reporting Guide

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#1946]
@whyrusleeping raised a good point about possibly adding an issue reporting guide for go-ipfs:

> Maybe we should also add an 'issue reporting' guide, and mention `ipfs diag sys` and that providing a shell script or set of commands to repro the issue is recommended.

What are some basic points you would like to see covered in issues, particularly of different types, for this repository? If someone submits an error, how would you like it to look? I'm not sure that this is written anywhere. I'm not suggesting a must-conform-to-guide, but a document that we can add either here or in ipfs/community that helps people who may not know how to file an appropriate issue for their system. 

Speaking of which, @whyrusleeping, `ipfs diag sys` threw an error for me (`Error: Unknown Command "sys"`).

**Comment by lgierth** [comment]
:5001/debug/pprofs might be useful too

**Comment by rht** [comment]
Guides to be derived from: http://www.chiark.greenend.org.uk/~sgtatham/bugs.html (ref-ed in git), https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue.

What about enabling anon bug report https://gitreports.com/?

**Comment by jbenet** [comment]
definitely ok with anon bug reports, but it's also trivial to create an account and having conversations over issues is very nice/useful.

**Comment by michaelavila** [comment]
Closing as I see much of this information in the issue template when creating a new issue: https://github.com/ipfs/go-ipfs/issues/new

Please re-open if I've misunderstood.
