### ISSUE TITLE
gateway index: filenames aren't escaped in links

### ISSUE THREAD

**Issue by cryptix** [ipfs/go-ipfs#1947]
Thanks to @MarkDerosier for spotting and reporting this in ipfs/website#77.

See Qme8HUxpr6QMcDzd3U1SzgUqtnoFQDdxZUZC69VMpi4LaL for example.

The constructed links contain the unescaped filenames and so clicking them send requests to the gateway with `?token=...` as a query parameter.

**Comment by jbenet** [comment]
:+1:

**Comment by adrian-bl** [comment]
I think this could be closed as a duplicate of https://github.com/ipfs/go-ipfs/issues/2061

My PR fixes this issue and i'm able to browse trough the whole directory tree on my local machine.

**Comment by lgierth** [comment]
duplicate of #2061, which has been resolved in ipfs/dir-index-html#9
