### ISSUE TITLE
[gateway] Content-Encoding: gzip

### ISSUE THREAD

**Issue by davidar** [ipfs/go-ipfs#1948]
AFAICT the gateway doesn't perform any compression, which is especially problematic for loading large JS files. Could we either perform compression within the gateway, or at least recognise compressed files and supply the appropriate header in the response (like S3 does)?

**Comment by davidar** [comment]
Perhaps I should have submitted this to infrastructure, as I'm mostly interested in the public gateway (cc @lgierth)

**Comment by lgierth** [comment]
Oh aehm yes! Don't know how I missed this low-hanging fruit! I'll do it right away so you won't have to open another issue

**Comment by lgierth** [comment]
Nginx should compress now, at least it does for me :)

**Comment by lgierth** [comment]
ipfs/infrastructure#e80ea375010882b674cd0a49c896d25ab162c482
