### ISSUE TITLE
OSX sharness tests hanging frequently

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1960]
I'm seeing sharness tests hang on osx with some degree of frequency.

Example: https://travis-ci.org/ipfs/go-ipfs/jobs/90398677

**Comment by chriscool** [comment]
Is it always after the same tests?

**Comment by whyrusleeping** [comment]
Its almost always after the one in the linked CI run, but occasionally i see a very similar issue in other tests. (always on OSX)

**Comment by chriscool** [comment]
If the Travis OS X machines sometimes hang after some operations performed by those tests it maybe because:
- the Travis OS X are not properly configured/maintained for those operations, or
- those operations are buggy
Maybe we could try those tests repeatedly on other Mac OS X machines?

**Comment by jbenet** [comment]
did something change? didnt used to see this hanging on OSX a few weeks ago
