### ISSUE TITLE
Remove chunk channels as input to DagBuilderHelper

### ISSUE THREAD

**Issue by rht** [ipfs/go-ipfs#1969]
If channels are used in order to speed up the loading process of next chunks (for small files case), it appears to have a reverse effect as shown in https://github.com/ipfs/go-ipfs/pull/1964#issuecomment-156788359 (`ipfs add` of lots of 'small' 1KB files).

**Comment by rht** [comment]
(in SSD, but I remembered the `NextFile()` preload wasn't implemented in `SerialFile` (for lots of small files) either)

**Comment by whyrusleeping** [comment]
This has been resolved
