### ISSUE TITLE
ipfs get: hash on wantlist is not canceled on repo/daemon when the ipfs client abruptly exits

### ISSUE THREAD

**Issue by rht** [ipfs/go-ipfs#1976]
Any gateway / RO api could have its storage and bandwidth blown without any cost on the sender.

- `ipfs get hash`
- `ipfs bitswap stat` contains the hash
- C-c `ipfs get`
- `ipfs bitswap stat` still contains the hash

**Comment by jbenet** [comment]
Yeah bitswap wantlists in go should incorporate contexts



—
