### ISSUE TITLE
ndjson problems

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/go-ipfs#1978]
Currently 

```
/api/v0/dht/findprovs?arg=<hash>&stream-channels=true
```

returns something that looks like ndjson but is not: https://gist.github.com/Dignifiedquire/93d2b01c638f08a77f68. According to the [spec](http://ndjson.org/) every line has to be a valid json object.

Ref https://github.com/ipfs/js-ipfs-api/issues/76

**Comment by jbenet** [comment]
this stuff is _**very important**_ we need serious API tests here.

**Comment by Dignifiedquire** [comment]
F****. I'm so sorry, this is a bug in the request library I'm using and not in go ipfs. The headers are set to chunked output and it's not detecting them properly. So sorry about this :blush:

**Comment by whyrusleeping** [comment]
> *very important*

https://www.youtube.com/watch?v=Hzx8KHjQD6c

**Comment by jbenet** [comment]
@Dignifiedquire so _it does_ return proper ndjson output?

**Comment by Dignifiedquire** [comment]
@jbenet It returns proper chunked output, for why it's causing issues see: https://github.com/ipfs/js-ipfs-api/issues/76#issuecomment-158216527
