### ISSUE TITLE
each CLI command makes two api requests

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1990]
every cli command that gets run makes two API requests, one to /version to check compatibility, and another for the actual command. It seems to me like the version check could be embedded in headers and done alongside the command itself.

**Comment by rht** [comment]
iirc there was a rtt bug where it is twice than it should be, could this be the cause?

**Comment by rht** [comment]
#1303

**Comment by whyrusleeping** [comment]
no, this is just because the commands client makes a version request to check versions, and then make the actual request if the version check passes. it happens inside this call here: https://github.com/ipfs/go-ipfs/blob/master/cmd/ipfs/main.go#L406
