### ISSUE TITLE
log/tail is slow and sometimes hangs completely

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/go-ipfs#1996]
Doing tests with js-ipfs-api I ran into an issue that often `log/tail` takes > 10s to respond and sometimes does not respond even after > 1min. After testing the same behaviour occurs on the cli. A restart of the daemon solves it but only for the first `log/tail` call.

cc @whyrusleeping @diasdavid

**Comment by jbenet** [comment]
cc @whyrusleeping  -- is this pre-or-post the log changes we recently did?

**Comment by jbenet** [comment]
"recently" (2-3 weeks ago)

**Comment by Dignifiedquire** [comment]
This was experienced on the `0.3.9` binary.

**Comment by whyrusleeping** [comment]
This has been resolved.
