### ISSUE TITLE
Bookkeep pins for each app

### ISSUE THREAD

**Issue by Gaboose** [ipfs/go-ipfs#2015]
I was told the standard way to write an app (like [ipfspics](http://ipfs.pics), [coopcache](http://coopcache.org/)) on ipfs includes running its own separate daemon. But if several daemons pin the same thing, memory usage unnecessarily duplicates (right?). OTOH if an app uses the 5001 port API instead, there's **no guarantee that the things the app pinned will stay pinned**: other apps or the user can manually unpin them, unaware of implications to apps that may rely on those blocks.

A potential solution is to identify apps when they connect to the API, then **make the effects of API calls like "pin add" and "pin rm" independent between apps** as well as the manual "ipfs pin add" and "ipfs pin rm" commands. I.e. the block would be stored as long as at least one app pins it. As a bonus, uninstalling ipfs apps would become cleaner - they'd be able to free all their pins.

**Comment by jbenet** [comment]
@Gaboose can you move this to this repo: https://github.com/ipfs/notes/ -- this needs a more open ended discussion than this repo is for, as we need to come up with a good solid design.

but yes, we are thinking about this already and plan to do something with capabilities to support multiple apps in one node

**Comment by Gaboose** [comment]
Ok. I'll close this issue then.
