### ISSUE TITLE
Generic K/V block datastore for FUSE abstraction of cloud object storage

### ISSUE THREAD

**Issue by kyledrake** [ipfs/go-ipfs#2017]
This is a proposal to create a special version of the block datastore that uses FUSE as an abstraction layer that is optimized for use with K/V object stores and "slow filesystems".

A few more object storage databases have emerged recently, such as [OVH Public Cloud](https://www.ovh.com/us/cloud/storage/object-storage.xml) and the upcoming [Backblaze B2](https://www.backblaze.com/b2/cloud-storage-providers.html). These alternatives provide significant cost savings over S3, and don't charge based on the number of HTTP requests. But integrating code directly into go-ipfs for all of these options is probably not feasible.

One idea I was pondering was providing a special version of the block datastore that uses FUSE as an abstraction layer, but is optimized for use with K/V object stores.

The main difference is that K/V datastores don't require directory partitioning, and as I understand it, doing things like creating/deleting directories adds a performance hit for no benefit. Metadata lookups are also probably not needed. And of course, only pinned content would probably need to go into the K/V store, non-pinned content should be cached locally. There's probably some other things but this is what I can think of ATM.

**Comment by jbenet** [comment]
why fuse? i dont think we need fuse, this is what https://github.com/jbenet/go-datastore/ is for (and why i've fought so hard to keep the repo generic on top of it). 

it's not perfectly there-- cant put the entire repo on it, but dev0.4.0 gets it closer (all blocks, inc pinset). after that it's removing all uses of leveldb and putting it into blocks too.
