### ISSUE TITLE
Linux Syslog Integration

### ISSUE THREAD

**Issue by mercurytw** [ipfs/go-ipfs#2024]
As a linux server administrator, I would like to have the option of redirecting stdout, stderr, and logging to the linux syslog (for which there is a go library), so that I can easily view log output at the same aggregation point as the other daemons I manage and monitor.

**Comment by jbenet** [comment]
@mercurytw why not do this with a script wrapping `ipfs`? could be part of the init scripts

**Comment by cryptix** [comment]
I, for one, welcome our new systemd overlords.

**Comment by mercurytw** [comment]
I think it's much cleaner if it was done in the program. The lack of actual daemonization of ipfs's daemon comand means that a (Sys V) init script needs to do a lot of work as it is to get ipfs more properly daemonic, so to speak. 

I'm all about systemd too, but not all machines have it.

Also, an init script can't handle ipfs's log without making something to read it periodically, which would be really sloppy.

**Comment by jbenet** [comment]
i understand, but we also have a ton of platforms to support and i dont want to have to start accepting patches just to dump go-ipfs stdout into some random osx or windows special purpose files/devices. this is what platform-specific scripts are for, and does not belong in the _core_ of ipfs.

**Comment by mercurytw** [comment]
That's a fair point. It'd be nice to at least be able to specify an alternate log file location in the config file, at the very least though.
(and maybe consider naming the command "server" or "node" instead of "daemon...")

**Comment by mercurytw** [comment]
closed as won't fix. no hard feelings.

**Comment by whyrusleeping** [comment]
@mercurytw are there any (non-platform specific) options we could implement that would make wrapping ipfs in a script easier for you?

**Comment by jbenet** [comment]
@mercurytw what file do you want to redirect to? i can write the script for you

**Comment by mercurytw** [comment]
@jbenet Thanks, but I've already got something in place. Plus writing the script is the fun part :)

I'll get back to whyrusleeping in a moment.
