### ISSUE TITLE
IPFS Not accepting multiple messages at one time with Stream Read/Write

### ISSUE THREAD

**Issue by Crypt-iQ** [ipfs/go-ipfs#2031]
I followed the example from IPFS website entitled "roll your own IPFS".
It uses the net.Stream interface to read and write messages.  I have two computers, both running one host and one client.  Each host is paired with the other's client.  However, there is a problem.  When multiple messages are written to one client at roughly same time, it will overload and concatenate messages, or drop them all together.  

go func() {
      for {
          buf := make([]byte, 2000)
          con.Read(buf)

          readqueue[readqueueindex] = buf
          readqueueindex++

      }
  }()

If two messages arrive at roughly the same time, the "buf" will be read once, (after con.Read is called, there is nothing to read the next message) and the second message will not be read, giving unpredictable results.  How do I fix this?  I think I should have one continuous Read function, rather than an intermittent one.  readqueue is just an array to put the messages into.

Thanks.

**Comment by jbenet** [comment]
@Crypt-iQ did you fix it somehow?

**Comment by Empire-Holdings** [comment]
Yeah, I realized I should just do something like this:

buf := make([ ]byte, 100000)

go func() {
      con.Read(buf)
}

Here I just read into one large array, and handle readqueue elsewhere

**Comment by Crypt-iQ** [comment]
Yeah I realized I should just do something like this

buf := make([ ]byte, 100000)

go func() {
      con.Read(buf)
}()

Here I just made one big buffer to read into, instead of many small ones that are reset and interrupt the read process
