### ISSUE TITLE
Build of dev0.4.0 branch gobuilder

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#2033]
> I'm opening this issue so it doesn't get lost.

I really need to get builds from the dev0.4.0 release (till tomorrow tops), if possible. @Luzifer we've created a tag, but it doesn't seem gobuilder cared (https://github.com/ipfs/go-ipfs/releases/tag/v0.4.0-dev) , what am I missing? Thank you

**Comment by jbenet** [comment]
@diasdavid what did you do to fix it?

**Comment by diasdavid** [comment]
@jbenet pinged @Luzifer, he got me back on IRC and started it :)

**Comment by jbenet** [comment]
for posterity, @Luzifer what do we need to do?

**Comment by Luzifer** [comment]
It's quite simple:

1. Push the commit with the tag as latest commit on `master` and ping / let GitHub ping the hook of GoBuilder to start a build (it will tag everything (tags/branches) connected to the commit)
2. OR if it was pushed not being the latest commit on `master`, go to gobuilder.me and put `github.com/ipfs/go-ipfs/cmd/ipfs@v0.4.0-dev` (with the right tag) into the new build field…

**Comment by jbenet** [comment]
thanks!
