### ISSUE TITLE
config JSON parsing on Windows with " instead of '

### ISSUE THREAD

**Issue by SCBuergel** [ipfs/go-ipfs#2034]
As 'ipfs daemon --help' suggests, the cors domain can be set via

```
>ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
```

which in Windows yields

```
Error: failed to unmarshal json. invalid character '\'' looking for beginning of value
```

The correct version should be

```
>ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin "[\"*\"]"
```

I just tested this version is and it seems Ubuntu-compatible. One might change that to the default suggestion in 'ipfs daemon --help' (and wherever else this is used).

**Comment by jbenet** [comment]
i wouldn't be opposed to this
