### ISSUE TITLE
Change example origin to be less dangerous 

### ISSUE THREAD

**Issue by travisperson** [ipfs/go-ipfs#2035]
The example in the daemon probably should not use the wildcard, and instead use an actual hostname.

 https://github.com/ipfs/go-ipfs/blob/76dedd8447be1de4a8da2776b812ec8b3dbd3be9/cmd/ipfs/daemon.go#L94

Other discussion: https://github.com/ipfs/js-ipfs-api/issues/156

**Comment by jbenet** [comment]
@travisperson agreed! wildcard is bad.
