### ISSUE TITLE
weird add 'race' condition

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2038]
What should happen if a user runs: 
```
ipfs add -r . > add_output
```

what currently happens is that an empty file named add_output is included in the added files.
I'm not quite sure if thats the *right* thing to do...

**Comment by rht** [comment]
It is more of a unix gotcha, since `git add . > out` does it as well.

**Comment by jbenet** [comment]
yeah i dont think we can avoid it easily... -- cp does it too:

```
> ls
1  2  3  4  5
> cp -r -v . ../b >out
> ls
1  2  3  4  5  out
> ls ../b
1  2  3  4  5  out
```

**Comment by jbenet** [comment]
(i think #wontfix)

**Comment by rht** [comment]
I wonder if this can possibly be fixed with [monadic shell](http://okmij.org/ftp/Computation/monadic-shell.html). Or actually more likely with an immutable fs (if the globbing is done on a specific hash).

Can be closed?

**Comment by Kubuxu** [comment]
To explain why it is happening, when command like `ipfs add -r . > add_output` is executed following happens:
1. file `add_output` is opened with Write flag which means that it will be created and empty file is on filesystem
2. `ipfs add -r  .` is spawned with stdout redirected over buffered pipe to `add_output`.

This means that at he moment of execution of `ipfs add` there is empty `add_output` file is in the filesystem. If not buffered pipe was used (or a lot of files added) it might be possible that the file in IPFS will contain some data.
