### ISSUE TITLE
using t.Fatal in a goroutine

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2043]
Apparently (it makes sense thinking about it) you can't use `t.Fatal` in a goroutine.

A cursory search reveals at least a few occurences of this bug: https://gist.github.com/whyrusleeping/6ff875746eccfc2611ab

Lots of them in our dependencies unfortunately, but a few in our code:
exchange/bitswap/bitswap_test.go-173
fuse/readonly/ipfs_test.go-160
merkledag/merkledag_test.go-198-
test/supernode_client/main.go-145-
test/supernode_client/main.go-183

**Comment by chriscool** [comment]
@whyrusleeping is there something else that should be used instead?

**Comment by whyrusleeping** [comment]
the errors need to be somehow propogated back to the main goroutine (the one executing the Test* function) and `t.Fatal` needs to be called there.

**Comment by chriscool** [comment]
Ok, thanks!

**Comment by jbenet** [comment]
Here are some examples of what i do:

example:

```go
func TestSimpleAsync(t *testing.T) {

	// use a channel to hand off the error
	errs := make(chan error, 1)
	go func() {
		err := somethingAsync()
		errs <- err
	}()

	// wait for it
	err := <-errs
	if err != nil {
		t.Fatal(err)
	}
}
```

```go
func TestNAsync(t *testing.T) {

	// we're going to have N children
	N := 10

	// use a channel to hand off the error
	errs := make(chan error, N)
	for i := 0; i < N; i++ {
		go func() {
			err := somethingAsync()
			errs <- err
		}()
	}

	// wait for all N to finish
	for i := 0; i < N; i++ {
		err := <-errs
		if err != nil {
			t.Fatal(err)
		}
	}
}
```

```go
func TestManyAsync(t *testing.T) {

	var wg sync.WaitGroup
	errs := make(chan error, 10)

	for shouldKeepGoing() {

		wg.Add(1)
		go func() {
			defer wg.Done()

			err := somethingAsync()
			if err != nil {
				errs <- err
			}
		}()
	}

	// close errs once all children finish.
	// wg allows us to do this without knowing
	// how many children a priori.
	go func() {
		wg.Wait()
		close(errs)
	}()

	for err := range errs {
		if err != nil {
			t.Fatal(err)
		}
	}
}
```

**Comment by whyrusleeping** [comment]
We should verify that all occurences of this have been resolved, then close the issue

**Comment by Stebalien** [comment]
Closing because, realistically, nobody's going to audit every one of our repos for this.
