### ISSUE TITLE
`ipfs mount` failure in travis-ci

### ISSUE THREAD

**Issue by thelinuxkid** [ipfs/go-ipfs#2044]
When fuse is enabled in travis, the sharness test for `ipfs mount` fails with `failed to find any peer in table`

**Comment by thelinuxkid** [comment]
I created a retry with a timeout 991ab47e04e64ff1fb24aa700b8a2da07888b8f9. It seems better than just ignoring the error. However, I am still getting errors in travis (not on my laptop though). I think at this point the best thing is to create a timeout before the mount test is run. If that doesn't get rid of the error in travis then it must be network related. ​I am now getting a different error on my laptop. It's related to `ipfs cat` but I haven't been able to ​dig into it too much.

**Comment by thelinuxkid** [comment]
from @whyrusleeping: So instead of a timeout thing there, I'm thinking we can just ignore the specific error you are seeing. Its a result of the node not being connected to any other peers, and in the case of initializing a new keyspace for ourselves, its not a big deal.

**Comment by thelinuxkid** [comment]
I will make the change. I am always wary of just ignoring errors, so, I will at least put a warning in the log. Normally, if you wait a few seconds before mounting, the error doesn't trigger. However, that is not a guarantee. But, I am thinking since sharness are integration tests it makes sense to put a timeout there instead of ignoring the error in the code. I am afraid there could be a situation where the error is triggered at that point for a different reason and we are just ignoring it. It's reasonable to have integration tests wait a few seconds for a service to be up, or fail.

**Comment by whyrusleeping** [comment]
So, the code returning the error only runs once on the first time a node is spawned, to initialize the ipns entry of the node to the empty directory. I think that the right thing to do might be to not publish the ipns entry in that intializer, instead, just 'publish' it locally.

**Comment by thelinuxkid** [comment]
Yeah. Ignoring the `failed to find any peer in table` just creates name resolving errors down the line. I will try that 'publish' locally approach.

**Comment by jbenet** [comment]
we may want to re-evaluate these error conditions. i think in general it may be good to `log.Error` that (or maybe `log.Warning`, really) and not "fail things specially" here

**Comment by jbenet** [comment]
(prob different PR altogether)

**Comment by thelinuxkid** [comment]
I created an offline router (e37208095e1f36a82e3b2c4554b74345ebba8931) for the `mount` command which seemed to solve the problem. The sharness tests are passing both locally and on travis-ci. Thank you @whyrusleeping for the help on that. This is a better solution than ignoring, so, no logging changes were necessary @jbenet.

I am having a separate problem with the go tests, however, so I won't create the PR until that is fixed. I will create a separate issue for that too.
