### ISSUE TITLE
no addresses on peer being sent

### ISSUE THREAD

**Issue by MarkDerosier** [ipfs/go-ipfs#2052]
default via 10.1.10.1 dev eth1 
10.1.10.0/24 dev eth1  proto kernel  scope link  src 10.1.10.242 

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fc:aa:14:43:44:4d brd ff:ff:ff:ff:ff:ff
    inet 10.1.10.242/24 brd 10.1.10.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 2601:449:c200:2b00:feaa:14ff:fe43:444d/64 scope global mngtmpaddr dynamic 
       valid_lft 325637sec preferred_lft 325637sec
    inet6 fe80::feaa:14ff:fe43:444d/64 scope link 
       valid_lft forever preferred_lft forever

{"diskinfo":{"free_space":4.95853084672e+11,"fstype":"btrfs","total_space":5.12010223616e+11,"used_space":1.6157138944e+10},"environment":{"GOPATH":"","IPFS_PATH":""},"ipfs_commit":"","ipfs_version":"0.3.11-dev","memory":{"swap":{"free":0,"sin":0,"sout":0,"total":0,"used":0,"used_percent":0},"virt":{"active":1.75622144e+09,"available":3.3166839808e+10,"buffers":1.16736e+06,"cached":2.492563456e+09,"free":3.0710554624e+10,"inactive":8.6761472e+08,"shared":0,"total":3.3734787072e+10,"used":3.024232448e+09,"used_percent":1.6835655810953625,"wired":0}},"net":{"interface_addresses":["/ip4/127.0.0.1","/ip4/10.1.10.242","/ip6/::1","/ip6/2601:449:c200:2b00:feaa:14ff:fe43:444d","/ip6/fe80::feaa:14ff:fe43:444d"]},"runtime":{"arch":"amd64","compiler":"gc","gomaxprocs":3,"numcpu":8,"numgoroutines":675,"os":"linux","version":"go1.5.1"}}

eventually the daemon will error with 

```
   18:23:00.646 ERROR        dht: no addresses on peer being sent!
```

**Comment by Mithgol** [comment]
I have encountered the same problem on Windows 64bit with the IPFS executable unpacked from https://gobuilder.me/get/github.com/ipfs/go-ipfs/cmd/ipfs/ipfs_release_windows-amd64.zip

Here's a screenshot:

![(screenshot)](https://cloud.githubusercontent.com/assets/1088720/12007266/cbcff7f8-ac0d-11e5-8eed-f6c33d76ae00.png)

**Comment by Stebalien** [comment]
(closing due to age)
