### ISSUE TITLE
ipfs add crashes due to weird filename

### ISSUE THREAD

**Issue by fazo96** [ipfs/go-ipfs#2073]
Looks like `ipfs add` crashes when adding a folder with a filename that contains `'`. Tried on `go-ipfs 0.3.10` on `Ubuntu 15.10` using the executable from gobuilder

**Comment by fazo96** [comment]
Oops, I think the problem is something else:

```
09:09:07.244 ERROR commands/h: multipart: unexpected line in Next(): "5e5dc034b0e0373a4aa6e015470c5a67e05d9afdd3b6dd2d290d6d238ff1--\r\n" client.go:271
```

It happens sometimes, even without the `'` in the filename.

**Comment by djdv** [comment]
That filename seems to be adding for me on FreeBSD, filenames with `<` or `>` are invalid on Windows so I couldn't try there.
https://ipfs.io/ipfs/QmQTigV2Zi39bddKSYbewFBTx1qGk52onzSerdb4iwZv4q
Could the issue be related to something else?
Those seem to be substitutes for Unicode control characters
http://www.fileformat.info/info/unicode/char/0080/index.htm
http://www.fileformat.info/info/unicode/char/0089/index.htm
I don't know where those would be coming from but they should probably be stripped out of filenames before being added. If they themselves are in the filename and not just the substitute for them, it may be what's causing the issue, I don't know how to create a filename with those specific characters to test but they may need to be escaped or quoted.

**Comment by eingenito** [comment]
Closing as stale. Please reopen if appropriate.
