### ISSUE TITLE
Move ipfs-specific logic out of commands lib

### ISSUE THREAD

**Issue by rht** [ipfs/go-ipfs#2075]
`ipfs`-specific code should be localized https://github.com/ipfs/go-ipfs/pull/2037#discussion_r46788119

**Comment by whyrusleeping** [comment]
@lgierth this is related to the core-ipfs-api work and gateway extraction you were doing

**Comment by lgierth** [comment]
clarified the title of this issue and added it to the core-api milestone

**Comment by lgierth** [comment]
The commands lib is now extracted and I think this can be closed (cc @keks)
