### ISSUE TITLE
task frozen, bitswap wantlist at 0

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#2077]
- On 0.3.10. 
- Have an `ipfs refs -r` task, which is now frozen without finishing (stuck somewhere)
- bitswap stat shows wantlist of 0 keys! :( 

```
> ipfs bitswap stat
bitswap status
	provides buffer: 0 / 256
	blocks received: 10717
	dup blocks received: 6588
	dup data received: 1.3GB
	wantlist [0 keys]
```

- this is a big bug.

**Comment by jbenet** [comment]
- i killed the refs process and issued it again (without restarting daemon), wantlist jumped to 150 keys, then whittled down back to 0. refs still hung.

**Comment by whyrusleeping** [comment]
this has since been resolved (was a bitswap bug)
