### ISSUE TITLE
name publish doesn't instantly update the cache entry in the local node

### ISSUE THREAD

**Issue by fazo96** [ipfs/go-ipfs#2078]
When `ipfs name publish` finishes, it doesn't instantly update the cache of the local node.

This is a problem in [my app](https://github.com/fazo96/ipfs-boards): the user updates his profile, but it takes a while (around 20 seconds) until he sees his changes.

**Comment by jbenet** [comment]
i've noticed this before, it's silly.

**Comment by harlantwood** [comment]
Both IPNS publishing and resolving seemed surprisingly slow in our ad hoc testing (on 0.3.9).  For [our nascent app](https://github.com/core-network/agent), we are moving to tracking the IPFS "head" at the application level instead.

We would much rather use IPNS, and plan to move to our when performance improves.

**Comment by fazo96** [comment]
@harlantwood it's already improved _hugely_ in 0.3.10 and 0.4.0 in my experience, this is just an issue when you are resolving the address associated with the node that is performing the resolution, which should be an instant resolution but for some reason it's not

**Comment by whyrusleeping** [comment]
has this been resolved?
