### ISSUE TITLE
mdns service string does not conform to convention.

### ISSUE THREAD

**Issue by NeoTeo** [ipfs/go-ipfs#2086]
An IPFS node currently advertises itself as an mdns service using the string "discovery.ipfs.io" (in p2p/discovery/mdns.go) which, when listed, shows up on the network as 
     ipfs.local.          discovery

This is different from the standard convention of a service type followed by a transport layer, separated by underscores. Eg. the Airplay and 1Password services show up as 
    _tcp.local.          _airplay
    _tcp.local.          _1password4

In the case of Apple's Foundation frameworks the libs expect this format to be able to search for a particular service and I think the unconventional format is causing it to not be found when searching for the transport layer "ipfs".

Any chance we can use the standard convention (as described in the usage example at https://github.com/cryptix/mdns) in IPFS as well?

**Comment by whyrusleeping** [comment]
sure, think you could file a PR?

**Comment by NeoTeo** [comment]
Yeah, I'll give it a go.

**Comment by jbenet** [comment]
@NeoTeo is this part of an RFC? or this apple enforcing a standard themselves?

i agree we want to make it easier, but not sure if we should be advertising in both.

(though yes, `ipfs.local. discovery` seems wrong)

mdns is more complicated than it needed to be >.<

**Comment by NeoTeo** [comment]
Yeah, RFC 6763 which follows conventions from RFC 2782. Agreed on mdns.

**Comment by whyrusleeping** [comment]
@NeoTeo this has been resolved, right?

**Comment by NeoTeo** [comment]
Yes :)
