### ISSUE TITLE
binaries much bigger?

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#2097]
- https://ipfs.io/ipfs/QmeEVmRTDX2c9zjPtjHJG6GidrFL7NjqEqP1Q4am6sLfif/go-ipfs

why are the binaries much bigger now? they used to be ~5MB, now ~20MB. is this go1.5?

**Comment by lgierth** [comment]
More like, used to be ~50, now >200MB

**Comment by djdv** [comment]
It may have been mentioned before but `strip` and `upx` reduce Go binaries significantly, this is not a proper solution to this problem though. On my system an ipfs binary at 24MB is reduced to 17MB with `strip -s` and further reduced to 4.1MB with `upx -9`. Seems like the binary size issue keep getting pushed back upstream.
https://github.com/golang/go/issues/6853

**Comment by lgierth** [comment]
We wanna keep as much debugging info as possible in there, though. Nothing's really stable or bugfree yet :)

**Comment by djdv** [comment]
Oh of course, to clarify shipping stripped binaries wouldn't be ideal but if people are concerned about size it's an option for them to consider locally.

**Comment by Kubuxu** [comment]
I think we should be fine with compressing the binaries using upx.

**Comment by whyrusleeping** [comment]
with go1.7 binaries have started to shrink, go1.8 will bring even more size reduction here. I think we can mark this closed.
