### ISSUE TITLE
gobuilder is using go1.5.1 instead of go1.5.2, which has a multipart bug

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#2104]
https://gobuilder.me/github.com/ipfs/go-ipfs/cmd/ipfs?branch=v0.3.10
> Last built 1 week ago using go version go1.5.1 linux/amd64 and 489 seconds of time

IIRC, go1.5.1 had a issue in the http module that was causing ipfs api to throw sometimes in a very specific scenario when a multipart message was constructed. go1.5.2 fixed this, @whyrusleeping can confirm.

@Luzifer do you have a plan to update gobuilder to user go1.5.2, so that people using that prebuilt binary don't have this bug.

**Comment by Luzifer** [comment]
@diasdavid the image was updated as soon as the `golang` docker images was updated but the build machine was using a wrong image. I just ensured it got the latest one:

``` bash
# docker run --rm -ti --entrypoint go registry.luzifer.io/gobuilder-image version
go version go1.5.2 linux/amd64
```

**Comment by diasdavid** [comment]
sweet! :D thank you for checking it @Luzifer Just one more thing, could you start new builds with go1.5.2? I'm clicking the restart button but it is not answering to me

**Comment by Luzifer** [comment]
The next commit will automatically get started using the new image… Already built commits are blocked because some people are trying to overload the builders… I got so many duplicate triggers for already built commits… :/

**Comment by Kubuxu** [comment]
Are we using gobuilder any longer?

**Comment by lgierth** [comment]
Nope because it go get's.
