### ISSUE TITLE
Custom datastore path

### ISSUE THREAD

**Issue by travisperson** [ipfs/go-ipfs#2117]
It appears when creating a new repo that there is a `Path` under `Datastore`. I'm taking a wild guess that this is where IPFS should be looking to open the Datastore.

Currently `dev0.4.0` does not use this value.

https://github.com/ipfs/go-ipfs/blob/dev0.4.0/repo/fsrepo/defaultds.go#L24

Thinking something like this:

``` diff
diff --git a/repo/fsrepo/defaultds.go b/repo/fsrepo/defaultds.go
index 4bca310..7f398ae 100644
--- a/repo/fsrepo/defaultds.go
+++ b/repo/fsrepo/defaultds.go
@@ -21,7 +21,13 @@ const (
 )

 func openDefaultDatastore(r *FSRepo) (repo.Datastore, error) {
-       leveldbPath := path.Join(r.path, leveldbDirectory)
+       dsPath := r.config.Datastore.Path
+
+       if len(dsPath) == 0 {
+               dsPath = r.path
+       }
+
+       leveldbPath := path.Join(dsPath, leveldbDirectory)

        // save leveldb reference so it can be neatly closed afterward
        leveldbDS, err := levelds.NewDatastore(leveldbPath, &levelds.Options{
@@ -40,7 +46,7 @@ func openDefaultDatastore(r *FSRepo) (repo.Datastore, error) {
        // reach a uniform 256-way split, we need approximately 4 bytes of
        // prefix.
        syncfs := !r.config.Datastore.NoSync
-       blocksDS, err := flatfs.New(path.Join(r.path, flatfsDirectory), 4, syncfs)
+       blocksDS, err := flatfs.New(path.Join(dsPath, flatfsDirectory), 4, syncfs)
        if err != nil {
                return nil, fmt.Errorf("unable to open flatfs datastore: %v", err)
        }
```

**Comment by travisperson** [comment]
This would also require a few changes to how testing initialization is done as the `r.path` is hardcoded in other areas

**Comment by whyrusleeping** [comment]
:+1:

**Comment by whyrusleeping** [comment]
@travisperson think you could throw together a PR for this?

**Comment by travisperson** [comment]
When I originally opened this issue I started working on a fix, which worked but really didn't do what I was thinking it would. Along the way I figured out a bit more about how things are working and I have a new proposed solution, but I want to get some feedback on this.

`Datastore.Path` should be the root of datastore. With a default value of `Datastore.path = ""` the value used will be `<REPO_ROOT>/datastore`. Setting `Datastore.Path`will change  the root of leveldb, and must be an absolute path to a writable path.

This will only ever have an effect on the location of the datastore. I propose along with this that a new configuration section set add for blocks. This will allow a user to change the location of where blocks are stored on disk, which I believe to probably be the most useful now that blocks are stored outside of the datastore using flatfs.

**Comment by whyrusleeping** [comment]
hrm... i'm not so sure how i feel about having the flatfs blockstore and leveldb treated separately. They are logically the same to the code... in general though, i agree

**Comment by whyrusleeping** [comment]
It might honestly make more sense to have `blocks` be inside of `datastore` and more leveldb down into something like `datastore/leveldb`. @jbenet thoughts here? The current layout is... disorganized

**Comment by travisperson** [comment]
yep, totally down with that as well.

**Comment by Kubuxu** [comment]
Currently possible via DatastoreSpecs.
