### ISSUE TITLE
travis sharness tests often fail with timeout

### ISSUE THREAD

**Issue by thelinuxkid** [ipfs/go-ipfs#2119]
As seen here: https://travis-ci.org/thelinuxkid/go-ipfs/jobs/98444177.

I am looking into this.

**Comment by lgierth** [comment]
Also have a look at #2002 where we're coordinating the fixing of build issues

**Comment by Stebalien** [comment]
I'm not seeing timeouts anymore so I'll close this as fixed, for now.
