### ISSUE TITLE
Windows: cli colour codes

### ISSUE THREAD

**Issue by djdv** [ipfs/go-ipfs#2124]
[Minor]
Coloured log output doesn't work with these codes in the standard Windows terminal, makes for some ugly output.
![screenshot](https://ipfs.io/ipfs/QmQyMCGcQuxRR98MycNza8ptEWCzzhJQU24od76Q9PVnxG)

**Comment by Stebalien** [comment]
@djdv this should be fixed by #5007 (merged to master). Can you check?

**Comment by djdv** [comment]
@Stebalien 
Looks good here!
