### ISSUE TITLE
IPNS Path Resolve error: could not resolve name at gateway

### ISSUE THREAD

**Issue by jbshirk** [ipfs/go-ipfs#2131]
From command prompt I see that I added an object, pinned it, published it, and the name resolves:
    localhost:ipfs joe$ ipfs add tw5.htm
    added QmVmTrmgWHz7RsaG9hQRwWyF4iESW1GS38rKs69EgMuTrD tw5.htm
    localhost:ipfs joe$ ipfs pin add QmVmTrmgWHz7RsaG9hQRwWyF4iESW1GS38rKs69EgMuTrD
    pinned QmVmTrmgWHz7RsaG9hQRwWyF4iESW1GS38rKs69EgMuTrD recursively
    localhost:ipfs joe$ ipfs name publish QmVmTrmgWHz7RsaG9hQRwWyF4iESW1GS38rKs69EgMuTrD
    Published to Qme67efGcE9iX6r8Wk6CrHUsmWckLbnMHQ19g5YK15doUY: QmVmTrmgWHz7RsaG9hQRwWyF4iESW1GS38rKs69EgMuTrD
    localhost:ipfs joe$ ipfs object stat QmVmTrmgWHz7RsaG9hQRwWyF4iESW1GS38rKs69EgMuTrD
    NumLinks: 13
    BlockSize: 633
    LinksSize: 574
    DataSize: 59
    CumulativeSize: 3306059

    localhost:ipfs joe$ ipfs name resolve Qme67efGcE9iX6r8Wk6CrHUsmWckLbnMHQ19g5YK15doUY
/ipfs/QmVmTrmgWHz7RsaG9hQRwWyF4iESW1GS38rKs69EgMuTrD

in the browser the name resolves and the object loads on localhost 
http://127.0.0.1:8080/ipns/Qme67efGcE9iX6r8Wk6CrHUsmWckLbnMHQ19g5YK15doUY

at the gateway the object loads:
https://gateway.ipfs.io/ipfs/QmVmTrmgWHz7RsaG9hQRwWyF4iESW1GS38rKs69EgMuTrD

but the name does not resolve:

https://gateway.ipfs.io/ipns/Qme67efGcE9iX6r8Wk6CrHUsmWckLbnMHQ19g5YK15doUY/
    Path Resolve error: could not resolve name.

https://gateway.ipfs.io/ipns/Qme67efGcE9iX6r8Wk6CrHUsmWckLbnMHQ19g5YK15doUY/tw5.htm
    Path Resolve error: could not resolve name.

Am I doing something wrong?

**Comment by Kubuxu** [comment]
Link you gave is working now.

**Comment by jbshirk** [comment]
@Kubuxu ok, good. Thanks. I guess it's just slow propagation.
