### ISSUE TITLE
dev0.4.0 returns a HTTP 500 on ipfs files stat when we are connected to 0 peers

### ISSUE THREAD

**Issue by daviddias** [ipfs/go-ipfs#2132]
@whyrusleeping, this happens because bitswap throws when we are connected to 0 peers

**Comment by lgierth** [comment]
Yeah we need to generally use proper response codes in the files api, e.g. for file-not-found and the like ;)

**Comment by Stebalien** [comment]
We've now accepted the fact that the commands lib API is not really HTTP.
