### ISSUE TITLE
add signoff checking to commit hook

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2140]
we should make sure you cant commit without the proper signoff, and maybe even add the setup script for the signing hook to the go-ipfs repo itself. New contributors have trouble with this often enough that we should help them out

**Comment by Kubuxu** [comment]
Setup script would work. Adding commit hook that blocks committing if there is no signoff is fruitless.

If someone knows about it then he will have hook adding signoff installed if not then he won't have the second hook either way.

Also someone might be committing WIP then blocking commit would be only annoying, current solution of hook adding signoff works.

Hmm, looks like the file is gone: https://github.com/ipfs/go-ipfs/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh
It was there recently.

**Comment by noffle** [comment]
Typo in my commit msg, but [I fixed the contribute.md link](https://github.com/ipfs/go-ipfs/commit/38a600b3c83d72ca5cebef07890b197a3d9b3a06).

**Comment by RichardLitt** [comment]
Thanks @noffle. 

We could add a section to the contribute about adding the commit sign off, with a simple command to install the hook, and then point to the more detailed thing in the main community contribute as needed?
