### ISSUE TITLE
Docker out of memory crash (32 bit binary used)

### ISSUE THREAD

**Issue by klauspost** [ipfs/go-ipfs#2149]
It seems like the Docker image uses a [32 bit ipfs binary](https://github.com/ipfs/go-ipfs/blob/master/Dockerfile#L18).

This causes out-of-memory crashes when I import many files at once, for instance: [crash.txt](https://github.com/ipfs/go-ipfs/files/76231/crash.txt).

Is there any reason for not using a 64 bit binary?

**Comment by klauspost** [comment]
@Luzifer - do you remember why you chose the 32 bit executable?

**Comment by Luzifer** [comment]
Because the 64bit binary didn't work in the docker container on all of my test systems… (Until today I'm putting 32bit binaries into containers because of the 64bit binaries are failing to start)

Just tried again:

```bash
# docker run --rm -ti -v ~/tmp/ipfs:/data/ipfs ipfs64
/usr/local/bin/start_ipfs: line 11: /usr/local/bin/ipfs: No such file or directory
Running ...
/usr/local/bin/start_ipfs: line 16: /usr/local/bin/ipfs: No such file or directory
/usr/local/bin/start_ipfs: line 17: /usr/local/bin/ipfs: No such file or directory
/usr/local/bin/start_ipfs: line 18: /usr/local/bin/ipfs: No such file or directory
/usr/local/bin/start_ipfs: line 21: /usr/local/bin/ipfs: No such file or directory
```

Change used for this test:

```diff
diff --git a/Dockerfile b/Dockerfile
index 88a8bf4..4106339 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -15,10 +15,10 @@ ADD bin/container_shacheck /usr/local/bin/shacheck
 RUN adduser -D -h /data -u 1000 ipfs \
  && mkdir -p /data/ipfs && chown ipfs:ipfs /data/ipfs \
  && apk add --update bash curl wget ca-certificates zip \
- && wget https://gobuilder.me/get/github.com/ipfs/go-ipfs/cmd/ipfs/ipfs_${VERSION}_linux-386.zip \
- && /bin/bash /usr/local/bin/shacheck ${VERSION} ipfs_${VERSION}_linux-386.zip \
- && unzip ipfs_${VERSION}_linux-386.zip \
- && rm ipfs_${VERSION}_linux-386.zip \
+ && wget https://gobuilder.me/get/github.com/ipfs/go-ipfs/cmd/ipfs/ipfs_${VERSION}_linux-amd64.zip \
+ && /bin/bash /usr/local/bin/shacheck ${VERSION} ipfs_${VERSION}_linux-amd64.zip \
+ && unzip ipfs_${VERSION}_linux-amd64.zip \
+ && rm ipfs_${VERSION}_linux-amd64.zip \
  && mv ipfs/ipfs /usr/local/bin/ipfs \
  && chmod 755 /usr/local/bin/start_ipfs \
  && apk del wget zip curl
```

**Comment by Kubuxu** [comment]
It looks like ipfs might be missing some lib. Can you run 'ldd /usr/bin/ipfs' in the container?

**Comment by klauspost** [comment]
I seems like all gobuilder builds are failing: https://gobuilder.me/github.com/ipfs/go-ipfs leaving only empty files. My guess is that even the 32 bit build is broken ATM.

**Comment by Kubuxu** [comment]
Or that. I've heard hoofbeets and thought of zebras instead of horses.

**Comment by Luzifer** [comment]
@klauspost You should look at https://gobuilder.me/github.com/ipfs/go-ipfs/cmd/ipfs - There you will find the binaries used for the container.

LDD:

```
> docker run --rm -ti --entrypoint=/bin/bash ipfs64
bash-4.3$ ldd /usr/local/bin/ipfs
	/lib64/ld-linux-x86-64.so.2 (0x562e4880b000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x562e4880b000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x562e4880b000)
bash-4.3$ /usr/local/bin/ipfs
bash: /usr/local/bin/ipfs: No such file or directory
bash-4.3$
```

**Comment by whyrusleeping** [comment]
I think this has since been resolved. If not, its very likely not a problem anymore.
