### ISSUE TITLE
cannot write back by relay.

### ISSUE THREAD

**Issue by utamaro** [ipfs/go-ipfs#2150]
While I'm trying to use relay by peer B , i.e. A->B->C,
Peer A can write data to Peer C, but C cannot write back to A.
"Stream Closed" error occured just after con.Write() at C.
Only the C to B connection seems to be closed while Accept().
(B to C connection seems to be alive)

server.go
https://gist.github.com/utamaro/bd4048cc20cd4c1c6393
client.go
https://gist.github.com/utamaro/b7f053ba0b1df35dad7d

workaround: not to use Listen/Accept but to use SetStreamHandler as relay_test.go
https://gist.github.com/utamaro/2587bc5ae98f0b314116

**Comment by whyrusleeping** [comment]
The relay isnt currently functional. We will be working on that in the next few months. If you like, open up a tracking issue on https://github.com/libp2p/go-libp2p and we can use that to keep everyone updated.
