### ISSUE TITLE
Removing a pin of a hash that does not exist should fail immediately

### ISSUE THREAD

**Issue by travisperson** [ipfs/go-ipfs#2155]
Performing a `ipfs pin rm` is a local command and should not require any connection to any network (I would believe). This also means that it should always fail immediately if the hash does not exist in the datastore.

Currently it will not, and in fact appears to hang indefinitely.

**Comment by whyrusleeping** [comment]
hahaha, it tries to fetch it from the network... good catch

**Comment by noffle** [comment]
Thanks for catching this @travisperson! Key resolution happens separately from dag node resolution now for unpinning, which should be able to fast-fail in most cases now.
