### ISSUE TITLE
bitswap: context deadline exceeded

### ISSUE THREAD

**Issue by peteygao** [ipfs/go-ipfs#2158]
Just got IPFS up and running, added a few .mkv files (`ipfs add -r .`), and used the localhost gateway to stream the file to VLC (`http://localhost:8080/ipfs/<hash>/`).

Every once in a while, the `ipfs daemon` would spit out that error. It won't crash or anything, but the VLC playback will pause for 30~60 seconds before resuming playback (I'm assuming the block had to be re-requested by VLC and re-served by the daemon?).

The IPFS Daemon is running on a Raspberry Pi 2 and version info:
```
pi@MediaDisk ~ $ ipfs version
ipfs version 0.3.10
```

**EDIT**: Nevermind, doesn't seem to have anything to do with me streaming anything from the local gateway. The errors continues even after I've stopped the video playback, it was simply that the playback stuttering helped to surface the problem.

**Comment by lgierth** [comment]
How big are the files, I'm guessing something upwards of 500MB each? They get split up into tons of 256KB blocks, Bitswap might be timing out while announcing that it provides them.

**Comment by lgierth** [comment]
And agreed, it probably doesn't have anything to do with the gateway and VLC.

**Comment by peteygao** [comment]
@lgierth No, ~175MB each. What's the timeout for Bitswap announcements?

**Comment by rht** [comment]
It is 15s and hardcoded, ref: https://github.com/ipfs/go-ipfs/blob/94bdce63a7d51e7ffee09fdbb6a5fa4d47ae1c6f/exchange/bitswap/bitswap.go#L38

**Comment by whyrusleeping** [comment]
I think this has since been resolved
