### ISSUE TITLE
"ipfs config edit" runs in daemon's tty

### ISSUE THREAD

**Issue by ScoreUnder** [ipfs/go-ipfs#2175]
When running `ipfs daemon` and `ipfs config edit`, the editor will open in the tty where `ipfs daemon` was launched. Ideally I'd expect it to run in the tty which invoked the edit command.

If you're running in debug mode (or if the daemon is feeling chatty), the editor is very difficult to use because the debug log messages are printed over the top of the editor, obscuring its contents and masking the cursor's real position.

**Comment by ScoreUnder** [comment]
Bonus: It uses `$EDITOR` as defined in `ipfs daemon`'s environment, meaning it can't be worked around with (for example) `EDITOR=gedit ipfs config edit`.

**Comment by Kubuxu** [comment]
Resolved in https://github.com/ipfs/go-ipfs/pull/2718
