### ISSUE TITLE
Encoding option for ipfs object get/put

### ISSUE THREAD

**Issue by jgraef** [ipfs/go-ipfs#2177]
Both `ipfs object get` and `ipfs object put` have an option to specify the encoding. `ipfs get` has `--encoding` and `ipfs put` has `--inputenc`.

I propose to use `--encoding` for both to make it more uniform.

**Comment by whyrusleeping** [comment]
`--inputenc` specifies the encoding of the data that the command takes as input. `--encoding` specifies the format of the output of the command. They won't necessarily always be the same

**Comment by jbenet** [comment]
maybe `--enc-in` and `--enc-out` (or `--codec-in` and `--codec-out` ?)
>
>
if we were to change, we can keep the current names as aliases for the new
ones (forever, or maybe with a deprecation warning)
