### ISSUE TITLE
windows 0.4.0: wrong estimation of total folder size (big folder on network drive) 

### ISSUE THREAD

**Issue by SCBuergel** [ipfs/go-ipfs#2179]
I am using the latest 0.4.0 buid right now for `ipfs add folder -r -p` on a big folder with many files from a network drive. The estimation of the folder size gives +Inf and correspondingly negative remaining times:
![negativetimes](https://cloud.githubusercontent.com/assets/11379673/12215646/81237c66-b6c6-11e5-9ed2-8a4b0efa882c.png)

The folder is big but in fact a bit smaller than +Inf.

**Comment by whyrusleeping** [comment]
hrm... it shouldnt show inf. But if the folder is sufficiently large it will take a while before it can determine the real size and update.

**Comment by Dignifiedquire** [comment]
Had the same issue on OS X when adding stackoverflow archives (180gb) it showed -Inf until it was finished

**Comment by Kubuxu** [comment]
Same thing on Linux while adding 21GB of cdn-js.

**Comment by SCBuergel** [comment]
Still the same on 0.4.2 Win x64 for adding some 10 files of 17MB each.
![image](https://cloud.githubusercontent.com/assets/11379673/18249170/eb03fb42-737c-11e6-8bd4-45b10665fa0b.png)

**Comment by Kubuxu** [comment]
@SCBuergel can you show output of `ipfs version --all` (or `ipfs version` if `--all` doesn't work).

**Comment by SCBuergel** [comment]
@Kubuxu I am on 0.4.2 for Win x64 [I am the 90%^^]:
![image](https://cloud.githubusercontent.com/assets/11379673/18348174/20d3035e-75ca-11e6-8e49-57464c8518fe.png)

**Comment by Kubuxu** [comment]
Can you try updating to [0.4.3-rc3](https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.4.3-rc3). I think we have fixed this bug but I am not 100% sure.

**Comment by lordcirth** [comment]
This was last reported a year ago in 0.4.2, and I cannot reproduce this now on 0.4.22. I think this can be closed.
