### ISSUE TITLE
Is ipfs daemon meant as system-wide or per-user?

### ISSUE THREAD

**Issue by Ape** [ipfs/go-ipfs#2183]
By default ```ipfs``` command will use a user local ipfs data path (```~/.ipfs```) and user local daemon instance.

But other aspects would suggest that ipfs daemon is meant to be system-wide. For example mounting ```/ipfs``` and ```/ipns``` will require root access and the paths will be global to the host. Also, only one daemon instance can use ports 4001, 5001, and 8080. This is not necessarily a problem, because users can change the ports.

Is the ipfs daemon meant to be one-per-host or one-per-user?

**Comment by jbenet** [comment]
the mountpoints can be relocated. 

truly, it should be able to be both-- in that some installations will want it to be a systemwide service, and some a per-user thing.

**Comment by Ape** [comment]
Is there any way for authentication on gateway or API service? Can every user on localhost just connect to these? Even to other user's instances?

**Comment by Kubuxu** [comment]
There might be in future with Token API.

**Comment by zignig** [comment]
Agreed , Token API for mfs and api , and conversion to http2 would an awesome addition.

**Comment by Dumptel** [comment]
Just a note that systemwide ipfs daemon does not require to be run as root.

From fuse(8) man page on Debian it follows that:
* The user must be in fuse group.
* The user must have write permissions to the mointpoint directory.
* The mountpoint is not sticky directory which isn’t owned by the user.
* No other users can access the mounted filesystem (this is configurable).

(I think there was some change in requirements in some Debian update (like permissions for /dev/fuse or fuse-group-owner of the mountpoint), but I’m not sure.)

To access the mounted filesystem from other users (except root), `user_allow_other` must be enabled in `/etc/fuse.conf` and `Mounts.FuseAllowOther` — in ipfs config.

Also, to access the daemon and its datastore from other users, I copy `~ipfs/.ipfs/api` file to these users’ `~/.ipfs` dirs (or you can use `--api` command line argument).

**Comment by yuvipanda** [comment]
I'm going to try to make a debian package for IPFS, and am thinking of doing the following:

1. Make an ipfs user and group
2. Run the daemon as the ipfs user/group
3. Add the ipfs user to the fuse group, and make sure the /ipns and /ipfs folders are owned by the ipfs user/group
4. Set the ipfs home to somewhere not in $HOME - /var/lib/ipfs perhaps? This will be owned by ipfs group / user, so you can access this if your user is in the ipfs group.

This should work somewhat well... Thoughts?

**Comment by yuvipanda** [comment]
Another option would be to make two packages - ipfs and ipfs-fuse, and the latter mounts the file paths. Not sure if that pattern is something you want to encourage.

**Comment by whyrusleeping** [comment]
We're planning on having a separate binary for the fuse mounting code in the future.

If there are any more questions along this topic, please direct them over to the faq: https://github.com/ipfs/faq/issues

**Comment by keith24** [comment]
This is how I relocated the ipfs mountpoints so ipfs can run as a service system-wide.  

The [docs for ipfs init](https://ipfs.io/docs/commands/#ipfs-init) say: 

>   ipfs uses a repository in the local file system. By default, the repo is
>   located at ~/.ipfs. To change the repo location, set the $IPFS_PATH
>   environment variable:
> 
>       export IPFS_PATH=/path/to/ipfsrepo

So it worked fine for me to put it in /etc:

```sh
sudo mkdir /etc/ipfs
export IPFS_PATH=/etc/ipfs
# run ipfs init or move the .ipfs folder if you already did
if [ -d ~/.ipfs ]; then sudo mv ~/.ipfs/* /etc/ipfs; else sudo ipfs init; fi
# Set permissions (I'm using ipfs-daemon system user and ipfs group, which I'm in)
sudo chown -R ipfs-daemon:ipfs /etc/ipfs
```

I also put this in my systemd service:

```systemd
[Service]
Environment=IPFS_PATH=/etc/ipfs
User=ipfs-daemon
Group=ipfs
ExecStart=/usr/local/bin/ipfs daemon
```

**Comment by nichtich** [comment]
@yuvipanda any progress on this? I'm asking because of https://discuss.ipfs.io/t/would-it-be-nice-if-linux-distros-came-with-go-ipfs-preinstalled/85/17 and the chance of widespread adoption before 2020 (next chance to get into an Ubuntu LTS release).

**Comment by OpenOS-Project-Creator-Founder** [comment]
> I'm going to try to make a debian package for IPFS, and am thinking of doing the following:
> 1. Make an ipfs user and group
> 2. Run the daemon as the ipfs user/group
> 3. Add the ipfs user to the fuse group, and make sure the /ipns and /ipfs folders are owned by the ipfs user/group
> 4. Set the ipfs home to somewhere not in $HOME - /var/lib/ipfs perhaps? This will be owned by ipfs group / user, so you can access this if your user is in the ipfs group.
> 
> This should work somewhat well... Thoughts?
> 



Why not have the entire Linux Kernel & Linux Distro ad IPFS?

https://github.com/cpg1111/ipos
