### ISSUE TITLE
add flag to 'ipfs add' to choose blake2 as hash function

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#2185]
@whyrusleeping just thought that when we add blake2 support, prior versions wont be able to use those hashes. if we can throw in support in 0.4.0 it would help. Feature creep i know but breakingness :S
- https://blake2.net/
- https://github.com/codahale/blake2

![](https://blake2.net/sandy.png)

(dat speed!)

**Comment by rht** [comment]
I'd vote for blake2b/s, but keep in mind that https://github.com/ipfs/archives/issues/35#issuecomment-165654806.

For effective optimization, it'd be better to make a breakdown of the bottlenecks https://github.com/ipfs/go-ipfs/issues/1616#issuecomment-155416422 (this benchmark is old, but just to serve a point).

**Comment by jbenet** [comment]
@rht makes sense. i'd opt for 2b/s as well.

**Comment by rht** [comment]
Here is a heuristic benchmark:

`ipfs add -q -r Godeps` on https://github.com/ipfs/go-ipfs/tree/e8c753d2e52b9f6e47d7f13c6b6fcffd0888c548 with various hash functions:
- sha2-256: 90ms (total time spent on `addAllAndPin`: 363ms)
- sha3-512: 144ms
- sha2-512: 100ms
- blake2b-512: 86ms
- blake2b-256: 63ms
- sha3-256: 85ms

**Comment by whyrusleeping** [comment]
We should probably add support for this before ipfs 0.5.0

**Comment by jbenet** [comment]
would be nice

**Comment by aead** [comment]
Just for reference: 
The "offical" golang [x/crypto](https://godoc.org/golang.org/x/crypto) sub-repo now contains both - [BLAKE2b](https://godoc.org/golang.org/x/crypto/blake2b) and [BLAKE2s](https://godoc.org/golang.org/x/crypto/blake2s)

**Comment by whyrusleeping** [comment]
With the latest bitswap fixes, we can change the hash function up and have it work just fine. Lets actually get around to prioritizing this as an experimental feature

**Comment by whyrusleeping** [comment]
@Kubuxu do you think you could take on getting the blake2 multihash stuff implemented?

**Comment by Kubuxu** [comment]
For 0.4.5?

**Comment by whyrusleeping** [comment]
@Kubuxu hmm... I'd like to be able to have it in 0.4.5. But thats a decent hunk of work. If you think we can do it quickly enough then lets go for it, otherwise, its on 0.4.6

**Comment by Kubuxu** [comment]
I will use this issue to add things I need you to take a look at for blake2 support: 

First one: https://github.com/multiformats/multicodec/pull/25

**Comment by whyrusleeping** [comment]
The code for blake2 is now merged into master and will be in the 0.4.6 release. Its not yet available as an easily specifiable parameter to `ipfs add`, but that can be added soon.

**Comment by whyrusleeping** [comment]
Moving the implementation of a `--hash-fn=blake2b-256` flag for add into the 0.4.7 milestone

**Comment by whyrusleeping** [comment]
Alright, having two releases in the wild that can understand this hash function is sufficient for deploying the change to master.

Lets go ahead and do this for 0.4.8 :) (it should be very simple)

**Comment by kevina** [comment]
@Kubuxu this is assigned to you.  Do you want me to take it.  Should be easy after https://github.com/ipfs/go-ipfs/pull/3743 is merged.

**Comment by Kubuxu** [comment]
It requires dependency propagation of go-multihash. So if you ware up to it, go for it.

**Comment by kevina** [comment]
@whyrusleeping the `go-multihash` dep is used nearly every where so it will be a difficult dependency to update and there are several outstanding P.R. for additional hashes.  Do you still want to target this for  Ipfs 0.4.8 or bump it?

**Comment by whyrusleeping** [comment]
@kevina we can probably bump this one to 0.4.9

I'm working right now on bubbling a dependency update, but it shouldnt be needed for blake2. I beleive that code is already merged into master here

**Comment by whyrusleeping** [comment]
The dep is for sure in master now. Lets get this into 0.4.10 :)

**Comment by kevina** [comment]
This sounds like an easy one for me to do, shall I?

**Comment by kevina** [comment]
With https://github.com/ipfs/go-ipfs/pull/3919 merged this is now possible.

**Comment by JayBrown** [comment]
Late question: is there a list of all the hashes supported by IPFS you can use with `ipfs add --hash <hash>`?

For example, an older one is here – https://multiformats.io/multihash/ – but for example blake2s-128 doesn't seem to be supported anymore.

**Comment by JayBrown** [comment]
Is that in a new version? My go-ipfs v0.4.17 doesn't have `ipfs cid` (yet).

**Comment by Stebalien** [comment]
@Jay we just released 0.4.18.

**Comment by dozykeys** [comment]
Good day @Stebalien 

When i try to upload to ipfs, everything is successful, but whenever i try to use blake2b for the hashAlg,it fails with error, no hasher found for blake2b-208. I observed that just sha256 and sha512 are available.

IPFS Version : 0.63.5
Below is the full error

[nodemon] restarting due to changes...
[nodemon] starting node dozie2.js
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/12D3KooWRnb6NYEcUaeciXQhCaERJnqcnbPGuQ9BZhQgjqqM64Lx
Swarm listening on /ip4/192.168.8.96/tcp/4002/p2p/12D3KooWRnb6NYEcUaeciXQhCaERJnqcnbPGuQ9BZhQgjqqM64Lx
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/12D3KooWRnb6NYEcUaeciXQhCaERJnqcnbPGuQ9BZhQgjqqM64Lx
file:///Users/macbook/Documents/node_apps/RC3-NFT/node_modules/ipfs-core-utils/src/multihashes.js:10
const LOAD_HASHER = (codeOrName) => Promise.reject(new Error(No hasher found for "${codeOrName}"))

**Comment by Jorropo** [comment]
@dozykeys you are showing a js-ipfs stack trace not a Kubo one.
You should open a new issue on js-ipfs's repo but
It's probable js-ipfs "just" don't support blake2.

**Comment by dozykeys** [comment]
okay thank @Jorropo  but can i also use kubo on nodejs?

**Comment by Stebalien** [comment]
No. Kubo is written in go.

**Comment by dozykeys** [comment]
@Stebalien thanks.
