### ISSUE TITLE
API should use whole name options, not flags

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2189]
According to feedback given in https://github.com/ipfs/api/pull/17, the API uses flags such as `r` and `w` instead of `recursive` and `wrap-with-directory`. I do not understand the logic behind this. I suggest that we move the API to either accept aliases, or to use the full names. It is awkward, documenting and using the API the way it currently exists. 

cc @diasdavid @whyrusleeping

**Comment by whyrusleeping** [comment]
`-r` and `-w` arent going away, you'll never get me to type `--wrap-with-directory`. That said, we should document both the long and short options.

**Comment by RichardLitt** [comment]
They shouldn't go away for the CLI. However, they should for the HTTP API. 

We should do more than document: we should implement the long options.

**Comment by jbenet** [comment]
i think the api should accept aliases (and i think it does? if not the cmds lib then uses one as the main one, and we _could_ switch it to the longer one)

**Comment by whyrusleeping** [comment]
the api accepts aliases

**Comment by RichardLitt** [comment]
@whyrusleeping Can we use this as a tracking issue, then, for adding aliases, or should I open up a separate issue for that?
