### ISSUE TITLE
`add` sends Transfer-Encoding header twice

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2190]
#### What

Transfer-chunked should only be sent once. 

#### Example

```sh
$ curl -F "file=test" -i http://localhost:5001/api/v0/add
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Access-Control-Allow-Headers: X-Stream-Ouptut, X-Chunked-Output
Access-Control-Expose-Headers: X-Stream-Ouptut, X-Chunked-Output
Content-Type: application/json
Trailer: X-Stream-Error
Transfer-Encoding: chunked
X-Chunked-Output: 1
Date: Tue, 12 Jan 2016 15:55:41 GMT
Transfer-Encoding: chunked
```

Made apparent during https://github.com/ipfs/api/pull/17

**Comment by Dignifiedquire** [comment]
Also why is there a `Continue` in there Oo

**Comment by lgierth** [comment]
curl sends `Expect: continue` for form/file uploads, so that the server can reject the request before any data has been sent. Useful in case of buffering proxies in between -- you don't want to upload a couple MB on a small DSL line just to be told "nope" afterwards.

**Comment by RichardLitt** [comment]
That is good to know! Thanks!

**Comment by lgierth** [comment]
The duplicated transfer-encoding is still obviously wrong :)

**Comment by Kubuxu** [comment]
Resolved in: https://github.com/ipfs/go-ipfs/pull/2465
