### ISSUE TITLE
Run migration automatically at least for container

### ISSUE THREAD

**Issue by Luzifer** [ipfs/go-ipfs#2192]
I'm using IPFS from the Docker container on a server with data directory persisted using a volume mount. Sadly the container stopped working today. The reason is quite obvious:

```
root@docker01 /data/ipfs # docker logs ipfs
Running ipfs version 0.4.0-dev...
Found ipfs repository. Not initializing.
Initializing daemon...
Error: Repo has incorrect version: 2
Program version is: 3
Please run the ipfs migration tool before continuing.
See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md
Sorry for the inconvenience. In the future, these will run automatically.
root@docker01 /data/ipfs #
```

As this step requires manual interaction it breaks all automation steps (possibly) taken. Therefore the container (and maybe IPFS in general) should do this migration automatically when it detects an outdated repository.

**Comment by whyrusleeping** [comment]
Is it possible to have your container pull from the release branch instead of master?

**Comment by Luzifer** [comment]
I'm using `jbenet/go-ipfs:latest`… And that [repo](https://hub.docker.com/r/jbenet/go-ipfs/) contains latest master… Aside: IMHO this would only postpone the issue until `v0.4.0` is released. Then the migration still would be required but not done automatically…

**Comment by jbenet** [comment]
@Luzifer thanks!
- `jbenet/go-ipfs:latest` now pulls from `release`, my sincere apologies :S
- added `jbenet/go-ipfs:release` and `jbenet/go-ipfs:master` too.
- @whyrusleeping i think we _can_ run the migration automatically, you?. or introduce a temporary flag for `ipfs daemon` that does (`--auto-migrate` or something).

**Comment by lgierth** [comment]
I'd wanna get an ipfs/go-ipfs image with automatic tag builds going, and maybe I can get to it before v0.4.0. Can someone else make the migration change though? :)

**Comment by Luzifer** [comment]
@lgierth Automatic tag building should be easy as of the changes made by DockerHub 1-2 months ago: You can specify to use a tag name as a image tag… Should be ~2m of clicking in the DockerHub interface…

**Comment by Patagonicus** [comment]
I just played around a bit and it looks like

* The migration tool is very fast
* The migration tool does not do anything if the repo is at the correct or a higher version

This means that simply running the tool on every container start should not be a problem. However I'm unsure on how to add the tool to the image as it is part of a different repository. The options I see are:

* Simply clone master off of GitHub. This makes the build non-reproducible and makes it harder to test changes to the migration tool.
* Set `ENV` variables in `Dockerfile` that specify the repo URL and commit. This mitigates some of the issues, but still poses the problem that the container needs to be able to clone from the repo (so you can't add changes from a local repo). Then we'd need to decide if we want to specify the commit via its hash (reproducible builds) or branch (we can update the migration tool in the image without needing a new commit). I tend towards using a hash.
* Merge the migration repo into go-ipfs/use subtree/…

If someone can help me decide what to do changing the Dockerfile and the scripts running in the container should be easy enough. :smile:

**Comment by lgierth** [comment]
Since v0.4.3-rc1 you can enable automatic migrations: `ipfs daemon --migrate=true`
