### ISSUE TITLE
attempting to run 'ipfs publish' on the readonly api returns confusing error

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2200]
i accidentaly made a call to 'ipfs publish' against the ipfs.io gateways, and it took me a while to figure out that the gateway was returning me an error, and not my own local code:

```
This command can't be called directly. Try one of its subcommands.
```

We should probably return something like "no such command" or "command not available on this api" or something

**Comment by magik6k** [comment]
Seems to be fixed:

```
$ ipfs name publish /ipfs/QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv --api=/dns4/ipfs.io/tcp/80
Error: Command not found.
```
