### ISSUE TITLE
wrong docker release version

### ISSUE THREAD

**Issue by chpio** [ipfs/go-ipfs#2216]
hi,

how to reprodice:
1. pull and run `jbenet/go-ipfs:release`
2. `docker exec ipfs_ipfs_1 ipfs version`

results in: `ipfs version 0.4.0-dev`

expected result: `ipfs version 0.3.11` because 0.3.11 is the last *release*

**Comment by jbenet** [comment]
@chpio you're right. This was fixed for master here https://github.com/ipfs/go-ipfs/pull/2213 -- but we need to cherry-pick the commit and at it to the release branch. If you know what i mean, could you try filing a PR? if not someone else may be able to soon.

**Comment by jbenet** [comment]
Ok i pushed it here: https://github.com/ipfs/go-ipfs/commit/2081538543488946d0e000b20459ace2352732be

rebuilding now: https://hub.docker.com/r/jbenet/go-ipfs/builds/

**Comment by jbenet** [comment]
cc @Luzifer it should work shortly as well. thanks for adding this. 

cc @whyrusleeping beware when merging master into release. this should merge cleanly but just in case you see something odd.

**Comment by chpio** [comment]
@jbenet Thank you!

```sh
# ipfs version
ipfs version 0.3.11
```

works now! closing this

**Comment by chpio** [comment]
yeaaahh! my files are accessible via the gateway again :)

**Comment by jbenet** [comment]
I'm sorry about that delay.

**Comment by chpio** [comment]
> I'm sorry about that delay.

which delay? my only problem was the incompatibility of v0.3 & v0.4

**Comment by jbenet** [comment]
> my files are accessible via the gateway again :)

that they didnt work for a while
