### ISSUE TITLE
CHANGELOG.md should be updated for v0.3.11 and v0.4.0

### ISSUE THREAD

**Issue by chriscool** [ipfs/go-ipfs#2222]
In PR #2208 we realized that the changelog has not been updated for v0.3.11 and v0.4.0 yet.

PR #2208 also contains one commit that adds information in the changelog for v0.4.0, so it might be better to merge PR #2208 before working on this.

cc @whyrusleeping @jbenet

**Comment by jbenet** [comment]
@whyrusleeping shipped that release-- he will be able to make this changelog better

**Comment by whyrusleeping** [comment]
uhm.... I'm pretty sure I wrote a changelog for 0.3.11... >.>

**Comment by chriscool** [comment]
@whyrusleeping did you find it back somewhere?

**Comment by whyrusleeping** [comment]
nope. Apparently it either disappeared, or i never wrote it. I'll put it together today
