### ISSUE TITLE
Q flag for `ipfs add` is broken

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2224]
#### What

Attempted to use `-q` with `ipfs add`. Hangs and doesn't end process. 

```sh
12:51 ~/src/ipfs-api (feature/add-add) * 🐕  ipfs add test 
added QmeomffUNfmQy76CQGy9NdmqEnnHU9soCexBnGU3ezPHVH test
12:51 ~/src/ipfs-api (feature/add-add) * 🐕  ipfs add -q test 
    
^C
^CReceived another interrupt before graceful shutdown, terminating...
12:51 ~/src/ipfs-api (feature/add-add) * 🐕  
```

**Comment by rht** [comment]
Can't reproduce this in https://github.com/ipfs/go-ipfs/commit/89a6f01be017b4da63492a1a1f76d4607e49c931. Is it specific to the file?

**Comment by RichardLitt** [comment]
The file is just `hello world`. I'm going off of `ipfs version 0.4.0-dev`.

**Comment by rht** [comment]
Still can't reproduce it. Is the hash in ipfs.io?

**Comment by RichardLitt** [comment]
QmePw8gVcBMb8x6kAep6aMBAX23hCSk6iZW3i9VKkiFhu1

**Comment by rht** [comment]
The content is indeed `Hello world`, and I still can't reproduce the bug in current master.

Do the other flags works?

**Comment by RichardLitt** [comment]
huh. Now I can't reproduce. Thanks, @rht
