### ISSUE TITLE
[meta] Two Factor

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2227]
I'm going to start enforcing that people with direct write access to go-ipfs have two factor auth enabled. The following people have write access currently, but have two factor disabled:

- [x] @jbenet 
- [x] @diasdavid 
- [x] @noffle 
- [x] @lgierth 
- [x] @mildred 
- [x] @RichardLitt 
- [ ] @ipfsbot 
- [x] @tv42

**Comment by lgierth** [comment]
let's do it -- get your yubikeys ready!

**Comment by noffle** [comment]
Enabled!

**Comment by jbenet** [comment]
And my Axe

**Comment by jbenet** [comment]
You guys ought to add 2-FA, but if you do not want to, let us know and we'll remove write access to go-ipfs for the time being.

**Comment by Dignifiedquire** [comment]
any reason this is limited to go-ipfs? I suggest enforcing this for write access for all repos on ipfs

**Comment by mildred** [comment]
I won't do it. I won't give any mobile telephone number to GitHub and won't depend anything too complicated or risking locking me out. My cookies are killed every day and I want to be able to log in fast. Please remove my commit access.

**Comment by Kubuxu** [comment]
@mildred buy yourself a [Yubikey](https://www.yubico.com/products/yubikey-hardware/yubikey4/]. Model 4 Nano is awesome.

**Comment by mildred** [comment]
I don't really trust those devices to keep my keys for me. I want to be able to keep a backup them somewhere safe at home, and these devices are write only, designed to prevent copying of the keys.

I thought a lot about it this morning and found I could use TOTP. There is a command line program that provides this functionality, and I can store the password, protected by a GPG, and backup it to my liking.

**Comment by RichardLitt** [comment]
![bow](https://24.media.tumblr.com/tumblr_m1ub5u22aJ1r2xijoo1_250.png)

**Comment by whyrusleeping** [comment]
@lgierth cmon man! you have a yubikey now!

**Comment by lgierth** [comment]
Got it set up now! The setup instructions with Android app and all that where a bit discouraging (no Play Store on my phone) but with the SMS path is was simple, yay.

**Comment by tv42** [comment]
I'm not at all convinced all these secondary routes are much safer than my password was, and this changes nothing about SSH access, but hey, this seems like a popular thing..

**Comment by RichardLitt** [comment]
Who is in charge of ipfsbot?
