### ISSUE TITLE
goroutines building up in yamux.Read

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2237]
Not really sure yet whats going on here, but on latest master i'm seeing lots of goroutines building up waiting on a read. It looks like its caused by a 'dead' connection, where NewStream is called a bunch, and `Write` gets called on that stream, spinning off a goroutine to sit and wait for a read to happen for the handshake.

**Comment by rht** [comment]
This `NewStream` could be the cause to the peerhost-zombies in #2240.

**Comment by Kubuxu** [comment]
Was this fixed?

**Comment by whyrusleeping** [comment]
I beleive this was fixed in the recent yamux changes
