### ISSUE TITLE
Config to force hash verification for local retrieval

### ISSUE THREAD

**Issue by sivachandran** [ipfs/go-ipfs#2259]
As per the IRC discussion https://botbot.me/freenode/ipfs/msg/58755967, content hashes are verified only when the content is retrieved from network. The hashes are not verified when retrieved from local storage. But verifying hashes for local retrieval helps us to detect disk corruption.  So please provide a config to enable hash verification even for local retrieval.

**Comment by rht** [comment]
+1

**Comment by rht** [comment]
e.g. `git-fsck`

**Comment by whyrusleeping** [comment]
If the option proposed here is added, it should add a check here: https://github.com/ipfs/go-ipfs/blob/master/blocks/blockstore/blockstore.go#L93

to rehash the block (call `NewBlock(data)` instead of `NewBlockWithMultihash`) and validate the key matches
