### ISSUE TITLE
LinkSize > 0 even when NumLinks === 0

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#2260]
```
» ipfs object stat QmeGYYkoAwJWooGSoW9Lx1rEmkDfqpTXgGR4hCs7yDV6Wx
NumLinks: 0
BlockSize: 126
LinksSize: 2
DataSize: 124
CumulativeSize: 126
```

Is there any reason I'm missing on why it is `2`?

**Comment by rht** [comment]
See https://github.com/ipfs/go-ipfs/blob/06cb9b5813a2fb15d57267bc72268ffbe32ea796/merkledag/node.go#L239 for how the `LinksSize` is determined.

The protobuf marshal additionally adds offset with https://github.com/ipfs/go-ipfs/blob/06cb9b5813a2fb15d57267bc72268ffbe32ea796/merkledag/pb/merkledag.pb.go#L556.

**Comment by diasdavid** [comment]
oh, I see. Thank you @rht :)

**Comment by rht** [comment]
(I'd consider it a bug. `LinksSize` can already be determined accurately through the sum of of the size of the links. The framing should have been put into `DataSize`)

**Comment by whyrusleeping** [comment]
yeah, that doesnt seem right to me. the comment is vague, i'm not sure what is meant to 'include framing'. with zero links, linksize should be zero

**Comment by whyrusleeping** [comment]
This should be resolved now. The links field is normalized to be null if no links are present. The two bytes was caused by a non-null but zero length links array in the protobuf

**Comment by rht** [comment]
As of https://github.com/ipfs/go-ipfs/commit/7276fd84b0c819ecc21d032eaad2281d58dfb37c,

```
$ ipfs object stat QmZPL7kCwRvZHVaKQDYd5RrdiAAUomu6EYPtexUSaAAWyJ                    
NumLinks: 0
BlockSize: 12979
LinksSize: 3
DataSize: 12976
CumulativeSize: 12979
```

**Comment by diasdavid** [comment]
So, just to be sure, do we put an empty array on the protobuf taking those couple of bytes?
