### ISSUE TITLE
DAGService 'recursive' methods

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#2262]
@whyrusleeping I've a memory of you mentioning that the 'recursive' versions of Add and Remove on the DAGService are deprecated and not used anymore, could you confirm?

https://github.com/ipfs/go-ipfs/blob/master/merkledag/merkledag.go#L71-L89
https://github.com/ipfs/go-ipfs/blob/master/merkledag/merkledag.go#L110-L130

**Comment by rht** [comment]
Not @whyrusleeping, I think this should be deprecated, but `DAG.AddRecursive` is still used in the gateway's [delete handler](https://github.com/ipfs/go-ipfs/blob/f631db7e694630024b1f15bd7754b301d20ec452/core/corehttp/gateway_handler.go#L463), where in this case there should be a pin lock before doing the adding ([bug]).

`DAG.RemoveRecursive` is not used, but there has been feature requests of manual removal of a specific unpinned dag without having to gc the entire cached blocks (there is a question of whether this should be allowed, or not, much like in the runtime of gc-ed langs).

**Comment by rht** [comment]
A reason the dag-scale (/ recursive node) should not be put into the merkledag spec is that because it has to inter-op with other dag-scale operation (e.g. pinning, gc).

**Comment by whyrusleeping** [comment]
confirmed. AddRecursive should be removed wherever possible. We shouldnt rely on the 'node' pointer in the links for anything other than caching. it should not be used to build a tree

**Comment by whyrusleeping** [comment]
these methods have been removed
