### ISSUE TITLE
MerkleDAG Batch

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#2263]
> this might be obvious, but since I didn't have any docs, thought of asking :)

Batch func purpose is to be able to defer writes to disk, it is a perf thing only, right?

https://github.com/ipfs/go-ipfs/blob/master/merkledag/merkledag.go#L260-L296

**Comment by whyrusleeping** [comment]
this is a perf thing, yes. Writing a bunch of things to disk all at the same time saves syscalls.

**Comment by diasdavid** [comment]
Sounds good :+1:
