### ISSUE TITLE
BlockSize === 0 when creating an empty object

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#2271]
When a new empty object is created, it's data size makes sense to be 0, however, its block size should be > 0, since the block size is the size of the serialized version of the object, which packs some protobuf encoding.

```
» ipfs object new | ipfs object stat
NumLinks: 0
BlockSize: 0
LinksSize: 0
DataSize: 0
CumulativeSize: 0
```

Could someone confirm this? I'm getting some inconsistency between go and js interop, in the JS impl, we get block size equals 2 bytes for an empty obj

**Comment by whyrusleeping** [comment]
an empty object should probably serialize to zero bytes. Are you sure you are setting the links and data to null in your javascript implementation?

**Comment by diasdavid** [comment]
@whyrusleeping I was creating an empty array for links and a 0 byte buffer for data. All good now with https://github.com/vijayee/js-ipfs-merkle-dag/pull/15
