### ISSUE TITLE
go get on OS X not building

### ISSUE THREAD

**Issue by andreiamatuni** [ipfs/go-ipfs#2273]
$: go get -u github.com/ipfs/go-ipfs/cmd/ipfs

package github.com/ipfs/go-ipfs/cmd/ipfs
	imports github.com/ipfs/go-ipfs/vendor/QmQg1J6vikuXF9oDvm4wpdeAUvvkVEKW1EYDw9HhTMnP2b/go-log: must be imported as QmQg1J6vikuXF9oDvm4wpdeAUvvkVEKW1EYDw9HhTMnP2b/go-log

**Comment by whyrusleeping** [comment]
are you using go1.6 beta?

**Comment by andreiamatuni** [comment]
yeah

**Comment by whyrusleeping** [comment]
yeah, go1.6 changed the default to have the vendor experiment on by default. Between that and some other issues, we don't support building with go1.6 yet.

**Comment by whyrusleeping** [comment]
go get is no longer supported as part of the ipfs build process, see the readme for details.
