### ISSUE TITLE
Sharness tests x0045 and xt0130

### ISSUE THREAD

**Issue by chriscool** [ipfs/go-ipfs#2274]
The following tests are not run and I wonder if they are worth keeping:

- https://github.com/ipfs/go-ipfs/blob/master/test/sharness/x0045-add-cat-iptb.sh
- https://github.com/ipfs/go-ipfs/blob/master/test/sharness/xt0130-multinode.sh

cc @whyrusleeping @jbenet

**Comment by whyrusleeping** [comment]
the xt0130 test is already in as t0130, it can be removed. I think x0045 can also be removed since we do the same stuff in other tests

**Comment by chriscool** [comment]
Ok I will do that. Thanks!

**Comment by Kubuxu** [comment]
Already resolved.
