### ISSUE TITLE
Error Messages: What does Code mean? 

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2293]
When using the CLI API, I am frequently getting error messages.

Example:

```
{
  "Message": "This command can't be called directly. Try one of its subcommands.",
  "Code": 1
}
```

What does Code mean? 
Why are some messages only text (ex: `Argument 'root' is required`, while some messages formatted like the above?

**Comment by whyrusleeping** [comment]
i'm not really sure how all this works to be honest, but i think that the code signifies that the exit status of the cli should be 1

**Comment by RichardLitt** [comment]
Who would know?

**Comment by RichardLitt** [comment]
@Kubuxu Do you know? 

I feel this might be a duplicate issue - I remember talking about it somewhere other than here.

**Comment by whyrusleeping** [comment]
Code 1 signifies that the CLI should return an exit code of 1 (and similarly 0 for code 0)

**Comment by RichardLitt** [comment]
I know what this means now.
