### ISSUE TITLE
Should format exist in leaves?

### ISSUE THREAD

**Issue by briantigerchow** [ipfs/go-ipfs#230]
ipfs block put problem

@jbenet

**Comment by diasdavid** [comment]
Let's bring this discussion to the IPLD thread https://github.com/ipfs/specs/pull/37.

**Comment by whyrusleeping** [comment]
This should be resolved by CIDv1

Ref #3059

**Comment by whyrusleeping** [comment]
progress https://github.com/ipfs/go-ipfs/pull/3307

**Comment by whyrusleeping** [comment]
We now have the ability to create files that have no formatting in the leaves via `ipfs add --raw-leaves`. This option may be made the default at some point in the future.
