### ISSUE TITLE
IPFS API `ipfs commands --flags` response does not show flags

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2301]
#### ipfs commands --flags

Works in the CLI:

```
$ ipfs commands --flags
ipfs
ipfs add
ipfs add --chunker / ipfs add -s
ipfs add --hidden / ipfs add -H
ipfs add --only-hash / ipfs add -n
ipfs add --pin
ipfs add --progress / ipfs add -p
ipfs add --quiet / ipfs add -q
ipfs add --recursive / ipfs add -r
ipfs add --trickle / ipfs add -t
ipfs add --wrap-with-directory / ipfs add -w
```

Does nothing in the HTTP API: 

```
curl -i "http://localhost:5001/api/v0/commands?flags"
HTTP/1.1 200 OK
Content-Type: application/json
Trailer: X-Stream-Error
Transfer-Encoding: chunked
Date: Thu, 04 Feb 2016 23:33:57 GMT
Transfer-Encoding: chunked

{
  "Name": "ipfs",
  "Subcommands": [
    {
      "Name": "name",
      "Subcommands": [
        {
          "Name": "publish",
          "Subcommands": [],
          "Options": [
            {},
            {},
            {}
          ],
          "ShowOptions": true
        },
        {
          "Name": "resolve",
          "Subcommands": [],
          "Options": [
            {},
            {}
          ],
          "ShowOptions": true
        }
      ],
      "Options": null,
      "ShowOptions": true
    },
```

It does turn `ShowOptions` to true, which is good. But where are the options?

From https://github.com/ipfs/http-api-spec/pull/34

**Comment by RichardLitt** [comment]
Reopening as I'm not sure this is closed - while it does now show flags, 

     curl -i http://localhost:5001/api/v0/commands?flags=true

and 

     curl -i http://localhost:5001/api/v0/commands

Are no different in their response. Shouldn't they be?

**Comment by Kubuxu** [comment]
`flags=true` is more of formatting option for text based output. It don't really make sense for JSON based API to remove those fields.

**Comment by RichardLitt** [comment]
Aight. In that case, the API is fine, and I am happy. thanks. 

Could this be used to help with autogenerating snyposes, @Kubuxu?

**Comment by Kubuxu** [comment]
Possibly, we would have to think about it and you would have to show me what exact style of synopses you want.
