### ISSUE TITLE
Include commit hash or tag in version string

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2304]
This could be done in way similar to Semver, string after `+` is additional version information that is not used for version comparison. 

To get hash or tag from git cjdns uses:

```
git describe --always --dirty --tags
```

This would allow precise identification of gateway, and APIs during development periods.
(I wouldn't have to ask Larsg if given patch was deployed or not)

**Comment by lgierth** [comment]
> (I wouldn't have to ask Larsg if given patch was deployed or not)

Oh we have the commit in `/version` and `/api/v0/version` now :)

e.g. https://ipfs.io/api/v0/version

Otherwise :+1: agreed, the current 7-char string from `git describe --abbrev` is less than optimal. The format you propose (e.g.`v0.4.0-rc1-25-gce0d62d`) is pretty widely used I think.

**Comment by Kubuxu** [comment]
I didn't notice, thanks for pointing it out. :D

**Comment by RichardLitt** [comment]
I think this is a good idea.

**Comment by hutenosa** [comment]
Isn't the same as `ipfs version --commit` ? Or commit tag should be returned anyway whether `--commit` flag is given or not?

**Comment by lgierth** [comment]
@hutenosa no it isn't, `ipfs version --commit` prints only the abbreviated commit hash as I said above, e.g. `gce0d62d`.

**Comment by Kubuxu** [comment]
We could make it SemVer (not enforcing API compatibility, even though 0.x.x. means do what you want with versions, rules but equality and ordering) compliant by making it `0.4.0-rc1+c25+gce0d62d`, release candidate 1 of version 0.4.0, non comparative data, 25 commits since last tag (rc1) current  commit `ce0d62d`.  Some project also embed truncated hash in version string.

**Comment by hutenosa** [comment]
I'd suggest to use dot as field separator in build part of SemVer string. With the following command `git describe` output can be transformed into SemVer-compatible string:

```
> git describe --always --tags --match 'v*' --dirty |\
sed -E 's/^v(.*)/\1/' | sed -E 's/-([0-9]+)-g([0-9a-z]{7}$)/+c\1.\2/' |\
sed -E 's/-([0-9]+)-g([0-9a-z]{7})-dirty$/+c\1.\2.dirty/' | sed -E 's/-dirty$/+dirty/'
```

```
"v0.4.0-rc2" >> "0.4.0-rc2"
"v0.4.0-rc2-dirty" >> "0.4.0-rc2+dirty"
"v0.4.0-rc2-56-gd9b766d" >> "0.4.0-rc2+c56.d9b766d"
"v0.4.0-rc2-56-gd9b766d-dirty" >> "0.4.0-rc2+c56.d9b766d.dirty"
```

**Comment by hutenosa** [comment]
I'm wondering how git tag version can be forwarded through Dockerfile. I see @lgierth did a smart hack by putting only `HEAD` and `refs/` into the image, ignoring the rest. Unfortunately `git describe` wouldn't consider it as a full-featured repository. Here are the possible workarounds:

0. Remove `.git/` from `.gitignore`. This would bloat the image size but `git describe` would work perfectly.
0. Add build argument. That requires building docker image with custom invocation, something like `docker build --build-arg version=0.4.0 Dockerfile`. If the argument is missing, consider `0.0.0` by default. 

Lars, what do you think?

**Comment by lgierth** [comment]
@hutenosa you forgot option 3, figure out what git-describe needs :)

**Comment by hutenosa** [comment]
I guess `git describe` needs the DAG of commit objects since it traverses the graph and searches for the closest path from the HEAD. It'd be an overkill to reimplement such logic inside docker RUN command ;)

**Comment by lgierth** [comment]
Mmmh yeah -- not sure. I really don't like bloating the automated images over at Docker Hub with the git repo.

**Comment by Kubuxu** [comment]
Resolved long time ago.
