### ISSUE TITLE
`log level` subsystem argument should be enumerated in docs

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2305]
The `ipfs log level` subcommand requires a `subsystem` argument. For example, `dht`. An invalid subsystem throws an error; however, the possible subsystems are not enumerated in the manual, and so it is impossible to know easily what is valid or what is not. 

For the `level` argument, the manual helpfully says: "one of: debug, info, warning, error, fatal, panic". I think this ought to be the case for `subsystem` too.

**Comment by whyrusleeping** [comment]
we have `ipfs log ls` now
