### ISSUE TITLE
Problem running make install

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2313]
https://ipfs.io/ipns/bin.ipfs.ovh/#QmSni6tPbqmW5DH8cLGzs6y8ry8sjeJy1rXj2b2CMv4CF4.txt

Installation fails during build.

**Comment by lgierth** [comment]
I think something went wrong with gx rewrites there

**Comment by Kubuxu** [comment]
Yes, killing build while gx is working is not a good idea.
`rm -rf $GOPATH/go/gx` fixes it.
Reporting to gx.
