### ISSUE TITLE
multistream into stream-muxer

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#2317]
@whyrusleeping just want to confirm, does yamux/spdy get multistreamed into on the current implementation? Is go-ipfs ready to support both yamux and spdy at the same time? Let's go together through some of these network details before shipping 0.4.0 and make sure we don't miss any

**Comment by whyrusleeping** [comment]
yes indeed, yamux and spdy are both supported in 0.4.0

**Comment by diasdavid** [comment]
sweet! Didn't know that spdy was already built in by default in the codebase.

What about other protocols, for example, if I want to send a bitswap message, does it expect for a stream to be opened and multistreamed into bitswap?

**Comment by whyrusleeping** [comment]
yes, you need to multistream into bitswap or the dht or any other protocol

**Comment by diasdavid** [comment]
❤️
