### ISSUE TITLE
fix appveyor tests

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2326]
The appveyor tests are currently not quite working. It would be awesome to get these turning green again.

@chriscool if you could help out with this, that would be really helpful. thanks!

**Comment by chriscool** [comment]
Ok, do you know at which point if any the appveyor tests were green?

**Comment by chriscool** [comment]
Ok it looks like they have never been green.

**Comment by dignifiedquire** [comment]
they were never green, I was happy I got to the point were tests would be actually executed

**Comment by chriscool** [comment]
@dignifiedquire Yeah, it is great you got to that point! Thanks!

**Comment by Stebalien** [comment]
(not using appveyor)
