### ISSUE TITLE
Swarm.AddrFilters doesn't work for IPv6

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2329]
I am using: `/ip6/fc00::/ipcidr/8` and it still connects with cjdns, when running `/ip4/0.0.0.0/ipcidr/0` I get only cjdns connections.

**Comment by lgierth** [comment]
Yep I can confirm this is an issue, looking into it

**Comment by whyrusleeping** [comment]
@lgierth is this fixed?

**Comment by Kubuxu** [comment]
This is fixed in new libp2p. https://github.com/ipfs/go-libp2p/pull/36

**Comment by whyrusleeping** [comment]
Cool
