### ISSUE TITLE
what is different in 0.4.0?

### ISSUE THREAD

**Issue by dominictarr** [ipfs/go-ipfs#2336]
I have seen the blog post about [how to migrate to 0.4](https://ipfs.io/ipfs/QmQUuZSSYJRn8sXBDsUfyoWbkD9BS4W7UNXFsAdtRVTwSy/9-v04x-migration/) but I am curious what has actually changed?

**Comment by diasdavid** [comment]
@dominictarr we will be writing a blog post soon, here https://github.com/ipfs/blog/issues/28 you can find the highlights, but probably the most impactful thing is the files API, which lets you use IPFS like a UnixFS directly, creating read and write streams to it, check https://github.com/ipfs/ipfs-blob-store for an example (note it only works with 0.4.0)
