### ISSUE TITLE
Travis can't fetch deps using gx

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2339]
https://travis-ci.org/ipfs/go-ipfs/jobs/109191119

It seems random as other builds fail earlier, other succeed.

**Comment by whyrusleeping** [comment]
thanks for reporting, it looks like the gateways are flaking out (probably just one host, cant tell yet). I added a delayed retry to gx's fetching mechanism so it looks like everythings happy now...

**Comment by Kubuxu** [comment]
Unfortunately it didn't help: https://travis-ci.org/ipfs/go-ipfs/jobs/109224776

**Comment by Kubuxu** [comment]
And here it just hanged: https://travis-ci.org/ipfs/go-ipfs/jobs/109237716

**Comment by whyrusleeping** [comment]
I'm thinking this one is resolved now... i'll close it in a couple days if its better
