### ISSUE TITLE
odd failure in t0060

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2347]
https://travis-ci.org/ipfs/go-ipfs/jobs/109512700

**Comment by chriscool** [comment]
@whyrusleeping there is no failure in the Travis run you link above.
It ends with:

```
*** aggregate ***
lib/test-aggregate-results.sh
fixed   0
success 1379
failed  0
broken  26
total   1415
```

**Comment by whyrusleeping** [comment]
I definitely posted a failed set of tests... unless it got rerun or something, or my comment got changed...

**Comment by whyrusleeping** [comment]
https://travis-ci.org/ipfs/go-ipfs/jobs/110288218

Heres a failure.

**Comment by whyrusleeping** [comment]
This has been resolved
