### ISSUE TITLE
weird behaviour when adding nested dirs

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#2348]
I noticed a weird behaviour when adding nested dirs with go-ipfs, it seems that `ipfs add -r` freaks out if a dir is empty and exits prematurely

```bash
» ipfs version
ipfs version 0.4.0-dev
```

```bash
» ipfs add -r dir-big
added QmW7BDxEbGqxxSYVtn3peNPQgdDXbWkoQ6J1EFYAEuQV3Q dir-big/1.2MiB.txt
added QmaFgyFJUP4fxFySJCddg2Pj6rpwSywopWk87VEVv52RSj dir-big
```

```bash
» tree dir-big
dir-big
└── 1.2MiB.txt

0 directories, 1 file
```

```bash
» ipfs add -r dir-nested
added QmQmZQxSKQppbsWfVzBvg59Cn3DKtsNVQ94bjAxg2h3Lb8 dir-nested/200Bytes.txt
added QmQmZQxSKQppbsWfVzBvg59Cn3DKtsNVQ94bjAxg2h3Lb8 dir-nested/level-1/200Bytes.txt
```

```bash
» tree dir-nested
dir-nested
├── 200Bytes.txt
├── dir-another
└── level-1
    ├── 200Bytes.txt
    └── level-2

3 directories, 2 files
```

**Comment by whyrusleeping** [comment]
@diasdavid can you write a small test script to reproduce? i.e. `mkdir -p a/b/c && ipfs add -r a`

**Comment by diasdavid** [comment]
While I was preparing the script for you, I saw it failing again several times, but now, after I tar'ed it and added to IPFS, and finished the script that would download from ipfs, untar and ipfs add -r, it started working!! Then I went back to the original dir-nested where I was seeing the error and it doesn't happen anymore and I seem unable to make it fail again 😧
