### ISSUE TITLE
daemon crashes during pin of a certain key.

### ISSUE THREAD

**Issue by codeburd** [ipfs/go-ipfs#2349]
I've a certain key that, when I attempt to pin it, causes a crash. Of both the IPFS process given the 'ipfs pin add' command, and of the daemon itsself. I know it isn't adding a key in general that does it, because I can add others. I can even add those which the dubious one refers to. But add the Cursed Key and... crash.

The cursed key is unusual in one respect: It's huge. Cumulative size is over eight gig. Crash occurs within less than a minute of giving the ipfs pin add command. I've only been able to produce it on one node, because I only have two running and the other one is where I added a big directory to get the cursed key in the first place. It's running in a VM I rent, but memory and disk space are plentiful. Both the crashing node and the one that should be sourcing the data are running 0.4.0-dev.

I can give you plenty of error output. Here's stderr from the daemon: http://birds-are-nice.me/wall_of_error
The pin add process gives only one line:

> ipfs pin add QmYJhxy447ySmhh1i2tmJ5kM4FvURiwKoDK64dGxvcAiyX 
> Error: Post http://127.0.0.1:5001/api/v0/pin/add?arg=QmYJhxy447ySmhh1i2tmJ5kM4FvURiwKoDK64dGxvcAiyX&encoding=json&stream-channels=true: EOF

That gives you the offending key as well. It's a large collection of music files, all public domain in the UK. I put them together a long time ago as a resource for a school, due to the number of students downloading chart music from dodgy sites to use as background in presentations. Thus the huge size.

So, that gives two possible explanations:
1. My node has some issue that causes it to crash when pinning large objects.
2. There's a general issue which causes a crash when pinning certain things, and that key or one of those it refers to is able to trigger it. Possibly through sheer quantity of data, it's basically an accidental fuzzer.

**Comment by codeburd** [comment]
Possible insight!

Error: mkdir /home/user/.ipfs/blocks/12207b4b/: too many links
ls .ipfs/blocks/ -1|wc -l
31998

I'm using a VM with some shared-space virtual filesystem, and I'm guessing it has a maximum of 32000 subfolders per folder (including . and ..). This might explain some of the erratic behaviour, but I don't know if it's related to the issue already described above. Still, it's certainly an issue that will need addressing - even on filesystems that let you place millions of folders, it's got a good chance of messing up some search/backup/AV software somewhere.

**Comment by Kubuxu** [comment]
As we introduced better sharding this should be resolved.
