### ISSUE TITLE
`ipfs tar add` does not work for large files

### ISSUE THREAD

**Issue by pietsch** [ipfs/go-ipfs#2350]
When I try to do `ipfs tar add` with a 20 GB file, this is what happens after a few seconds:

> ipfs tar add oai_dc-dump-2016-02-05.tar
> Error: Post http://127.0.0.1:5001/api/v0/tar/add?encoding=json&stream-channels=true: EOF

I tried this with both the stable and the current master version (as of yesterday) on AMD64 Linux with 4 GB RAM:

> ipfs-stable version
> ipfs version 0.3.10
> 
> ipfs-dev version
> ipfs version 0.4.0-dev

Workaround: Unpacking the TAR file and doing `ipfs add --recursive` on the resulting directory seems to work.

**Comment by hutenosa** [comment]
In current implementation IPFS loads the entire tar file into the memory. If you don't have enough RAM, it obviously fails.  Also, `ipfs tar` uses its own serialization machinery, incompatible with `unixfs`. In other words, adding via `ipfs tar add` and adding recursively unpacked data is not the same. For instance, you cannot do `ipfs ls` on tar's root key. So if you want to add tars as folders, you've left with a single choice: unpack and add recursively.

**Comment by lordcirth** [comment]
I cannot reproduce this issue on 0.4.22:

```
lordcirth@nezha:/SSD_Data/ISOs$ ls -lh big.tar
-rw-r--r-- 1 lordcirth kvm 36G Nov  2 13:56 big.tar

lordcirth@nezha:/SSD_Data/ISOs$ time ipfs tar add big.tar
QmSYazufVBA9PCNA8zVdiQL4TJHpXcNRTXFC6mTmuvQjj2

real    34m24.144s
user    11m14.707s
sys     1m7.147s
```

While it was very slow to add, I have 32GB of RAM and I could add a 36GB tar file.

**Comment by Stebalien** [comment]
@lordcirth thanks for triaging!
