### ISSUE TITLE
Randomised swarm port

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2355]
In cases where there are mutliple daemons running one default swarm port is just bad.

It means that in a network only one instance of IPFS will be 0conf rest will have to change port. I think we should randomise swarm ports while initalising config, at least from some range.

**Comment by whyrusleeping** [comment]
you can use port zero and it will randomly select one on daemon start

**Comment by whyrusleeping** [comment]
@Kubuxu can we close this?
