### ISSUE TITLE
gateways hanging for gx in CI

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2375]
https://travis-ci.org/ipfs/go-ipfs/jobs/110288219

@lgierth to me, this implies that the gateways are hanging. They all have the packages cached, this shouldnt be an issue...

**Comment by noffle** [comment]
I've been experiencing lengthy gateway hangs as well in my `go get` experiments, but can't repro on localhost with `multireq`+`go-ipfs`.

**Comment by whyrusleeping** [comment]
yeah, everything i try locally works quickly... but the gateways (on OSX in particular) seem to timeout and die

**Comment by noffle** [comment]
I see ~50% success rate, 50% hang rate. Possibly just one of the `multireq` hosts is hanging? </speculating>

**Comment by whyrusleeping** [comment]
potentially, i'll take a look at them...

**Comment by Kubuxu** [comment]
How about setting up local IPFS node and adding `.ipfs` to Travis cache? This would greatly improve setup time. Or other solution would be adding `go/src/gx` into Travis cache.

**Comment by whyrusleeping** [comment]
this has been mostly fixed

**Comment by RichardLitt** [comment]
@whyrusleeping That's not useful. What hasn't been fixed?

**Comment by whyrusleeping** [comment]
its like good and okay now for the most part. the new hang issues are gateway related and not gx related
