### ISSUE TITLE
`ipfs files rm` recursive flag doesn't affect output

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2378]
Using the recursive flag doesn't seem to change anything. I can remove a directory from the files API without needing to call it, and setting it as false doesn't mean I can't remove a directory.

#### Commands I ran
```
10:41 ~/src/http-api-spec (feature/files) * 🐕  ipfs files cp /ipfs/QmT78zSuBmuS4z925WZfrqQ1qHaJ56DQaTfyMUF7F8ff5o /test
10:41 ~/src/http-api-spec (feature/files) * 🐕  ipfs files rm /test
10:41 ~/src/http-api-spec (feature/files) * 🐕  ipfs files ls /
here
10:41 ~/src/http-api-spec (feature/files) * 🐕  ipfs files cp /ipfs/QmT78zSuBmuS4z925WZfrqQ1qHaJ56DQaTfyMUF7F8ff5o /test
10:41 ~/src/http-api-spec (feature/files) * 🐕  ipfs files rm /test --recursive=false
10:41 ~/src/http-api-spec (feature/files) * 🐕  ipfs files ls /
here
```

**Comment by diasdavid** [comment]
You are adding and removing a file called `test`, and `ipfs files ls /` is showing you one called 'here', which I'm guessing it is another file you add copied earlier

**Comment by RichardLitt** [comment]
Sorry, I should have clarified. `test` is a directory. That it is not there when I `ls /` shows that it has been removed, regardless of the recursive flag.

**Comment by whyrusleeping** [comment]
```
➜  ~ ipfs files mkdir /test
➜  ~ ipfs files ls /
cat
test
➜  ~ ipfs files rm /test
Error: /test is a directory, use -r to remove directories
```

I failed to repro

**Comment by RichardLitt** [comment]
@whyrusleeping Thanks. Me too. Will try like this.
