### ISSUE TITLE
What does "X-Stream-Error" in a 200 Ok Response from the API?

### ISSUE THREAD

**Issue by daviddias** [ipfs/go-ipfs#2386]
Example shown by the http-api-spec https://github.com/ipfs/http-api-spec/blob/master/apiary.apib#L2939

**Comment by whyrusleeping** [comment]
the `X-Stream-Error` is a trailer we use to signify that a streaming output command has errored. 

For example, during an `ipfs cat`, we get the first few blocks and want to start streaming back data, so we respond `200 OK` and start sending data. But halfway through fetching the information, we error out for some reason. How do you convey that to the user? Our solution was to use http trailers.

**Comment by anderspitman** [comment]
@whyrusleeping how has your experience using trailers been in general? They seem to be used very little, and maybe not well supported, and yet the use case is important.

**Comment by Stebalien** [comment]
I can't speak to why's experience but my experience has been: HTTP isn't a good choice for streaming APIs. The protocol itself technically works but:

* Up till the fetch API, browsers didn't allow scripts to read streaming responses.
* Go's HTTP server (and probably others) expect to receive the entire request body before the response is written.
* As you noted, the only way to send late errors is to use trailing headers.

On the other hand, trailers are older and likely better supported than websockets.

**Comment by anderspitman** [comment]
Oh I'd be the last to disagree with you about HTTP streaming. However, I'm replacing a complicated backend, and having completely stateless endpoints would be a nice win over WebSockets. We don't need upload streaming. I've been playing with [XHR streaming](https://hpbn.co/xmlhttprequest/#streaming-data-with-xhr). Preliminary tests have it working pretty well. The big downsides are that it's text only (not a problem for us) and the entire response gets buffered in responseText, even though you can peek at it as it comes in. Our responses are fairly small so again shouldn't be an issue.

However, error handling for streaming definitely seems like a missing piece. I'm honestly surprised there aren't more resources out there. People have been streaming HTTP for a long time.

That's interesting about go's HTTP server. Node has excellent support for HTTP streaming.

**Comment by Stebalien** [comment]
The issue is specifically bidirectional streaming: https://github.com/golang/go/issues/15527
