### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2393]
Sometimes I wish to be using local IPFS resources but I don't want IPFS to communicate with internet. Reasons for that are metered bandwidth, very weak connection etc..

Idea would be a flag which can be passed daemon for example `ipfs daemon --offline`.

**Comment by noffle** [comment]
You can do this today with an empty bootstrap list, though I agree this is tedious for one-off use. An `--offline` daemon flag sounds reasonable to me.

**Comment by whyrusleeping** [comment]
I've wanted this for a while too. Lets put it on the TODO list

**Comment by yangwao** [comment]
:+1:

**Comment by whyrusleeping** [comment]
`ipfs daemon --offline` could construct an 'offline' node (the same way we do when running a command without the daemon) but still run the http api. This should happen soon!

**Comment by whyrusleeping** [comment]
@pfista I think of the two you posted in IRC, this would be the better one to work on.
