### ISSUE TITLE
api file doesnt get cleaned up

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2395]
the `api` file in the repo lingers around, we should clean this up when the daemon shuts down.

**Comment by whyrusleeping** [comment]
caused a test failure here: http://ci.i.ipfs.io:8111/viewLog.html?buildId=108&buildTypeId=GoIpfs_CiTests&tab=buildLog#_focus=5301

**Comment by Stebalien** [comment]
Fixed.
