### ISSUE TITLE
makefile should check installed version of go

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2397]
@chriscool could you put this together? You already did it nicely for gx versions, and reusing that code would be great.

**Comment by chriscool** [comment]
Ok, I will take a look soon.

**Comment by chriscool** [comment]
By the way should we just test that go version is >= 1.5 or are there other things to test, like go version < 1.6?

**Comment by lgierth** [comment]
> go version is >= 1.5

>= 1.5.2

> go version < 1.6

not sure anyone has tested with 1.6 yet

**Comment by Stebalien** [comment]
I'm running IPFS with go 1.6 and haven't noticed any issues.

**Comment by whyrusleeping** [comment]
yeah, we fixed the couple issues that 1.6 brought up, so it should work. but i won't recommend it as an official supported version until we get CI running it.

For now, just saying greater than 1.5.2 should be good

**Comment by chriscool** [comment]
Ok, thanks all!
