### ISSUE TITLE
Make -h an alias for --help

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/go-ipfs#2408]
At the moment `-h` and `--help` do different things, which is confusing me all the time as `-h` does print some help but not all of it.

cc @RichardLitt

**Comment by RichardLitt** [comment]
This is actually pretty standard for man pages: long help and short help. Not sure about fixing this. I always use --help.

**Comment by noffle** [comment]
I think the `-h` vs `--help` for short vs long help is reasonably established nomenclature. However, the difference between our short help and long help on some commands seems unreasonable (read: you'd almost never want the short help):

```
stephen // ~ $ ipfs dht -h
USAGE:

    ipfs dht - Issue commands directly through the DHT.

Use 'ipfs dht --help' for more information about this command.
```

```
stephen // ~ $ ipfs dht --help

    ipfs dht - Issue commands directly through the DHT.

SUBCOMMANDS:

    ipfs dht findpeer <peerID>... - Run a 'FindPeer' query through the DHT.
    ipfs dht get <key>...         - Run a 'GetValue' query through the DHT.
    ipfs dht put <key> <value>    - Run a 'PutValue' query through the DHT.
    ipfs dht query <peerID>...    - Find the closest peers to a given key by querying through the DHT.
    ipfs dht findprovs <key>...   - Run a 'FindProviders' query through the DHT.

    Use 'ipfs dht <subcmd> --help' for more information about each command.
```

"Long" help is still very short. I think making the differentiation between short and long might make more sense once "long help" is longer. (Bonus: try `curl --help` for a good time.)

I think this ties into https://github.com/ipfs/go-ipfs/issues/2402 and wanting default output to include subcommands.

**Comment by dignifiedquire** [comment]
> I think the -h vs --help for short vs long help is reasonably established nomenclature

Where? `curl -h` is the same as `curl --help`, same for `git -h` and `git --help` and pretty much every single cli application I use.

**Comment by whyrusleeping** [comment]
@dignifiedquire not sure what youre talking about, try `git push -h` and `git push --help`

**Comment by dignifiedquire** [comment]
@whyrusleeping okay for subcommands it is different, but still git lists all options on `-h` which a lot of the `ipfs <cmd> -h` do not do, and has actually the full man pages which are real text based docs `--help`. At the current state of ipfs help I would say what we have under `--help` is about the amount of details of `-h`that we need and the text for `--help` does not exist currently for most commands.

**Comment by noffle** [comment]
@dignifiedquire Agreed! Subcommand discoverability and short-help where ever possible! I think this notion is captured by #2402.
