### ISSUE TITLE
Test case for resolving IPNS hash

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2411]
While writing the docs for `ipfs resolve`, [here](https://github.com/ipfs/http-api-spec/pull/51), I wondered if we could set up a test case where an IPNS path nests an IPNS path pointing to an IPFS path. According to the code [here](https://github.com/ipfs/go-ipfs/blob/master/core/commands/resolve.go#L82-L98), this shouldn't resolve without the `recursive` flag. Maybe I misunderstand, but I think that would be cool. 

Can someone help me figure out how to set this up?

cc @diasdavid

**Comment by Stebalien** [comment]
We now test recursive resolution.
