### ISSUE TITLE
ipfs commands is a weird command

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2420]
`ipfs commands` run from the cli doesnt make an http request. Making an http request manually to the proper endpoint still works though, with the exception of the `-f` flag not actually doing anything useful, all that passing `-f` does is making the output contain `"ShowOptions":true` instead of `false`.

cc @RichardLitt

**Comment by RichardLitt** [comment]
Related to https://github.com/ipfs/go-ipfs/issues/2301

**Comment by dignifiedquire** [comment]
Also it's pretty useless on the http api as it documents everything according to the cli and not the http api

**Comment by noffle** [comment]
What is the motivation behind `ipfs commands`? Is this for other unix tools to consume, or is it intended for humans?

**Comment by RichardLitt** [comment]
@noffle We use it to build the website, IIRC.

**Comment by RichardLitt** [comment]
Specifically, [here](https://github.com/ipfs/website/blob/master/src/ipfs.io/docs/commands/Makefile).

**Comment by noffle** [comment]
Ah ha! So that we can get https://ipfs.io/docs/commands/ -- got it.

**Comment by keorn** [comment]
Could be used for auto generating API wrappers.

**Comment by RichardLitt** [comment]
I think we've justified `ipfs commands`. I used it today. Can we close this now?
