### ISSUE TITLE
t0300 hung on travis

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2425]
random failure here. not sure what is actually holding things up.

https://s3.amazonaws.com/archive.travis-ci.org/jobs/112937044/log.txt

**Comment by whyrusleeping** [comment]
another one here: https://s3.amazonaws.com/archive.travis-ci.org/jobs/112940506/log.txt

cc @chriscool

**Comment by chriscool** [comment]
The `docker_build()` function that fails does something like `docker build --rm -f "$TEST_TESTS_DIR/Dockerfile" "$APP_ROOT_DIR"`. Maybe fetching the Docker image hangs or something.

**Comment by whyrusleeping** [comment]
is the fetch happening through the official docker registries? does this seem like a problem with their infrastructure? or travis?

**Comment by chriscool** [comment]
I don't know. On the command line "docker build" is very verbose, but it looks like it is not so verbose on Travis. I will see if I can make it more verbose, so it will be hopefully easier to see what goes wrong.

**Comment by mnp** [comment]
I was having trouble with the Dockerfile as it stands.  First, the comments were breaking the multi-line RUN command.  Second, the "apk" get's were running way too slowly.  So I made a quick test dockerfile, https://gist.github.com/mnp/620641be76df385075c2 which uses the official golang docker image (based on debian, not alpine) and cuts out the comments.  This works okay.

Let me know if we want a real issue and PR, and I'll clean up the gist for production.

**Comment by lgierth** [comment]
Doesn't travis have something like a docker image cache? I vaguely remember something like that. Otherwise we can certainly optimize it a little more to avoid apk running every time.

@mnp I'm *very* surprised that the comments made problems -- could you file another issue here for that, with output and docker version?

**Comment by Kubuxu** [comment]
Docker has cache but only for sudoless builds.

**Comment by chriscool** [comment]
@whyrusleeping PR #2451 should help debug this.

**Comment by mnp** [comment]
@lgierth cannot reproduce either issue :-(   Pls ignore my gist and my remark.

The questionable platform was OSX go1.6 darwin/amd64 and docker 1.10.2, but it was behind a corp firewall at the time, and docker-machine is notoriously picky about switching network interfaces.  I tried today on same box, same network, fresh pull, and it ran clean.

Also runs clean for me on current ubuntu.

**Comment by whyrusleeping** [comment]
havent seen this in a long while, closing
