### ISSUE TITLE
ipfs swarm connect /<peer_id>/ fails with "failure: dial backoff" and requires a restart

### ISSUE THREAD

**Issue by peteygao** [ipfs/go-ipfs#2428]
I'm attempting to connect from a local home machine that's been running ipfs daemon that's been up for weeks (no exaggeration) to an ipfs daemon that I just booted up on a Digital Ocean droplet.

I wait a while until `ipfs swarm peers | wc -l` shows a sizeable peer list (73 peers at the time of attempt), and I was still getting `failure: dial backoff`.

Next I restarted my local home ipfs daemon (again, lots of uptime), and then right afterwards I attempted connecting and this time it connected to the Digital Ocean peer without a problem.

On my local ipfs node (behind 2 layers of routers), I was connected to only 7 peers prior to restart, and after restarting ipfs daemon, 3 peers.

If you guys need any other information about my setup, let me know.

**Comment by whyrusleeping** [comment]
This is likely a combination of NAT traversal issues and address selection problems. One node is trying to dial the other at bad addresses (127.0.0.1, 192.168.* and friends) until it trips the exponential backoff. Once that gets high enough with failures you will see the issue you describe. 

I think a good interim solution here will be to add commands that clear the dial backoff for a given peer, and allow the removal of addresses in our local address book to avoid dialing bad address. Those are both very manual things, but will help debug the issue more in-depth.

**Comment by whyrusleeping** [comment]
This should no longer happen. manual connects will clear the dial backoff. If this continues to occur, please open a new issue and reference this one.

**Comment by jbenet** [comment]
Good solution (clear on manual)

**Comment by Sulejman** [comment]
Still getting same problem.

**Comment by Stebalien** [comment]
@Sulejman please open a new issue, including information like which version of go-ipfs you're using and how to reproduce the issue.
