### ISSUE TITLE
ipfs should adjust its open file descriptor limit if its too low (OSX)

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2431]
On daemon startup, we should check the open file descriptor limit and raise it ourselves if its below 1024.

**Comment by dignifiedquire** [comment]
Wouldn't that require sudo privileges?

**Comment by whyrusleeping** [comment]
no, you can run `ulimit -n 1024` as a normal user on most systems

**Comment by mattseh** [comment]
Please do this, I was caught by this today. It shouldn't be a manual step IMO.

**Comment by whyrusleeping** [comment]
we do this now!
