### ISSUE TITLE
Add command to remove lock files

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2457]
We should have a command - `ipfs repo repair` or `ipfs repo fsck` - which removes lockfiles. See bug issue [here](https://github.com/ipfs/support/issues/12).

**Comment by whyrusleeping** [comment]
`ipfs repo fsck` has been planned. We should do that soon.

**Comment by TheNain38** [comment]
I think that when starting IPFS should try to remove stale lock file, by searching if the a proccessus with the owner's PID exists, if it doesn't, then it should remove the `repo.lock` file and start normally

**Comment by sscheper** [comment]
For the record, it's February 11, 2019 and I just experienced this issue. 

Removing BOTH of these files solved it:

1. `~/.ipfs/repo.lock`
2. `~/.ipfs/datastore/LOCK`

**Comment by Stebalien** [comment]
You should _never_ need to do this at this point. If you do, something is wrong.

**Comment by Kubuxu** [comment]
@sscheper which version of go-ipfs are you using?

**Comment by mrusme** [comment]
Ran into `Error: resource temporarily unavailable` inside a self-built Docker container that currently runs `0.5.1`. Added `rm -rf /data/ipfs/repo.lock /data/ipfs/datastore/LOCK` to the very first line of the startup script, so that it always removes the locks that might still exist on the persistent storage from a previously running container. The daemon now starts again. However, if I dial into that container and try to perform an `ipfs add -Q -r ./site` (while the daemon is running within that container) it still shows `Error: resource temporarily unavailable`. Not exactly sure what's going on there, maybe someone here can provide further insights?

**Comment by Stebalien** [comment]
I really wouldn't do that. It no longer matters if the lockfile exists unless a go-ipfs daemon has the lockfile open and _locked_. That would mean that the daemon is running.

Your second issue may be that ipfs is running but your IPFS node can't find and/or connect to it. I don't know what your exact setup is so I'm not sure why. If you'd like more help on this, please ask on https://discuss.ipfs.io.

**Comment by koxon** [comment]
While running kubo IPFS on containers and network storage. I see that when a container is killed or fails, the lock files remains and prevent a new daemon from starting.

**Comment by xueshuai0922** [comment]
> While running kubo IPFS on containers and network storage. I see that when a container is killed or fails, the lock files remains and prevent a new daemon from starting.在容器和网络存储上运行 kubo IPFS 时。我看到当容器被杀死或失败时，锁定文件会保留并阻止新的守护程序启动。

yes ,i meet a same problem,should kill lock first?

**Comment by koxon** [comment]
How to remove the lock file when using Docker? I try to override the entrypoint in the dockerfile to perform the `rm` as root but I have no luck so far. Anyone managed to make this work when using Docker?

**Comment by koxon** [comment]
I've built my own entrypoint.sh and Dockerfile to deal with the lock files.

Dockerfile:
`
FROM ipfs/kubo:latest

COPY 001-config_efs.sh /container-init.d/001-config_efs.sh

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
`

entrypoint.sh:
`
#!/bin/sh

trap stop SIGTERM SIGINT SIGQUIT SIGHUP ERR

start(){
    echo "Fixing ownership and deleting lock files"
    chown -fR ipfs /data/ipfs/ || true
    rm -rf /data/ipfs/repo.lock /data/ipfs/datastore/LOCK /data/ipfs/blocks/.temp

    echo "Starting IPFS daemon"
    tini -- gosu ipfs /usr/local/bin/start_ipfs daemon --migrate=true --agent-version-suffix=docker
}

stop(){
   echo "Shutting down IPFS"
   tini -- gosu ipfs /usr/local/bin/ipfs shutdown

   exit
}

start
`

001-config_efs.sh:
`
#!/bin/sh
set -ex

# We make sure those files are cleanedup at container startup
# If the container is killed, those files may remain
# They would block ipfs process startup
rm -rf /data/ipfs/repo.lock /data/ipfs/datastore/LOCK /data/ipfs/blocks/.temp
`

I remove the locks files in the entrypoint.sh as `root` and in the 001-config_efs.sh config file that is executed by ipfs at startup as the user `ipfs`.

It looks like with those changes, the cluster has recovered and the repo.lock file has been removed. 

The entrypoint also attempt to shut down ipfs gracefully if it receives a SIGTERM. This is useful if you're running your task on AWS Fargate SPOT where your task can be shutdown by AWS with a 2min warning.
