### ISSUE TITLE
ipfs ls failing, but only over http api

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-ipfs#2462]
Running the follows returns fine with no errors:
ipfs ls QmNNFsQsZu7SZBRGeDHWjcEuFeSc8TEcRLi8qyUP6HYAtv

But trying using the java http api returns a 500 error. (The call works fine for other hashes).

**Comment by dignifiedquire** [comment]
What's the result when using curl?

**Comment by ianopolous** [comment]
Using curl gives: {"Message":"proto: unixfs_pb.Data: wiretype end group for non-group","Code":0}

**Comment by RichardLitt** [comment]
I wasn't able to replicate this. 

```
$ curl -i "http://localhost:5001/api/v0/ls?arg=QmNNFsQsZu7SZBRGeDHWjcEuFeSc8TEcRLi8qyUP6HYAtv"
HTTP/1.1 200 OK
Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output
Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output
Content-Type: application/json
Server: go-ipfs/0.4.0-dev
Trailer: X-Stream-Error
Transfer-Encoding: chunked
Date: Mon, 14 Mar 2016 00:44:33 GMT
Transfer-Encoding: chunked

{"Objects":[{"Hash":"QmNNFsQsZu7SZBRGeDHWjcEuFeSc8TEcRLi8qyUP6HYAtv","Links":[]}]}
```

**Comment by ianopolous** [comment]
Funnily enough using your command, I get the same result. To get the error I have to run:
curl http://127.0.0.1:5001/api/v0/file/ls?arg=QmNNFsQsZu7SZBRGeDHWjcEuFeSc8TEcRLi8qyUP6HYAtv

**Comment by RichardLitt** [comment]
`ipfs file ls` is a different command from `ipfs ls`. Which do you mean to use?

**Comment by ianopolous** [comment]
My bad. I didn't even realise I was using the file version. Sorry.

**Comment by RichardLitt** [comment]
No worries! Glad we got this sorted. :)
