### ISSUE TITLE
panic from utp

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2464]
@dignifiedquire reported this panic which appears to be solely the fault of our utp library (not influenced by any ipfs code that i can tell)

https://gist.githubusercontent.com/dignifiedquire/33c5e9b5af4305491e37/raw/7c0c8731916bf8b21f723a8c1a32c2e1276bb993/fail.log

**Comment by whyrusleeping** [comment]
reported fixed: https://github.com/anacrolix/utp/issues/7

Need to update utp dep now

**Comment by dignifiedquire** [comment]
cool :)

**Comment by whyrusleeping** [comment]
fixed in latest update of utp
