### ISSUE TITLE
`ipfs object get` with protobuf encoding never errors in HTTP API

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2468]
`ipfs object get --encoding=protobuf` works using the normal CLI:

```
$ ipfs object get QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ --enc=protobuf
1
" ? :?^?E???p??\?|?.??t|d??U??cat.jpg?
$  ipfs object get kitten --enc=protobuf
Error: invalid ipfs ref path
```

However, when put through the HTTP API, it will not return an error if the key is invalid or missing.

```
13:07 ~/src/http-api-spec (feature/object) 🐕 curl -i -X POST "http://localhost:5001/api/v0/object/get?arg=&encoding=protobuf"
HTTP/1.1 200 OK
Server: go-ipfs/0.4.0-dev
Date: Tue, 15 Mar 2016 17:07:58 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

13:07 ~/src/http-api-spec (feature/object) 🐕  curl -i -X POST "http://localhost:5001/api/v0/object/get?arg=kitten&encoding=protobuf"
HTTP/1.1 200 OK
Server: go-ipfs/0.4.0-dev
Date: Tue, 15 Mar 2016 17:08:01 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

13:08 ~/src/http-api-spec (feature/object) 🐕  curl -i -X POST "http://localhost:5001/api/v0/object/get?arg=mW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ&encoding=protobuf"
HTTP/1.1 200 OK
Server: go-ipfs/0.4.0-dev
Date: Tue, 15 Mar 2016 17:08:15 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

This should be solved before merging https://github.com/ipfs/http-api-spec/pull/32.

**Comment by RichardLitt** [comment]
Blocking https://github.com/ipfs/http-api-spec/pull/67.

**Comment by Stebalien** [comment]
Would it be acceptable to return a JSON error?

**Comment by RichardLitt** [comment]
Sure. But that needs to be returned.

**Comment by RichardLitt** [comment]
It should at least return a status code of `500`.

**Comment by Stebalien** [comment]
We really shouldn't ever be returning 500 (500 means the application had some internal error it couldn't handle). Cases:

* Bad Multihash: 400 (it's a malformed request).
* IPFS object couldn't be found (but may exist somewhere): 504.
* IPFS path is impossible (e.g., `/ipfs/$hash/a/b` where `a/b` doesn't resolve relative to the object named by `$hash`): 410 (gone).
* IPNS path doesn't currently resolve (but we found the IPNS record and the associated IPFS object(s)): 404 (not found).

**Comment by RichardLitt** [comment]
@Stebalien Fascinating! 

@whyrusleeping What do you think about this? Might be a wider-reaching issue.

**Comment by whyrusleeping** [comment]
@Stebalien how much of this has been addressed by your latest PR?

**Comment by Stebalien** [comment]
My PR only returns a 500 error (with json content) when `object get --encoding=protobuf` fails. Nothing more.

**Comment by Stebalien** [comment]
So, this now *does* return a 500 error. It should probably return something else but that will require some changes to the API (we can revisit semantic errors later, right after we move away from the HTTP API to an RPC based API) . I'd call this specific issue fixed.

**Comment by Stebalien** [comment]
Ok, so I *think* this is fixed. However, the error producing the 500 is actually a panic in the daemon so I'm going to wait for *that* issue to be fixed before declaring *this* fixed.

* Blocked on #4360
