### ISSUE TITLE
`ipfs object links --encoding=protobuf` has no marshaller

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2470]
```
$ ipfs object links QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ --enc=protobuf
Error: No marshaller found for encoding type 'protobuf'
```

Should it? Why not? 

Discovered while documenting https://github.com/ipfs/http-api-spec/pull/32.

**Comment by RichardLitt** [comment]
Blocking https://github.com/ipfs/http-api-spec/pull/67.

**Comment by Stebalien** [comment]
@RichardLitt is this still a problem? IMO, `object links` *shouldn't* support `--enc=protobuf`. It should support `--enc=cbor` if anything but it's not a protonode (and I'd rather not define a custom protobuf for *every* response from the API.

**Comment by RichardLitt** [comment]
If it is still a problem, it isn't my itch anymore. Closing this.
