### ISSUE TITLE
Repository linking to files.

### ISSUE THREAD

**Issue by palkeo** [ipfs/go-ipfs#2476]
Hi,

I suppose that a very common use case for IPFS would be to share huge files/directories.
At the moment, if you want to do that IPFS will copy all your data to its own repository.

Would it be possible to optionally have IPFS link to the actual data on disk instead of copying it ? For the tree representing the directory it would have the leaf nodes link to a filename:offset:length, and only store the intermediate nodes (which would represent a very small overhead because the actual data are leaf nodes).
Alternatively, we could also have an implementation of a repository that would store metadata (and intermediate blocks) in « .ipfs » files in your filesystem along with the files you share.

That would cause issues if you move or modify the files you added because the repository will point to invalid data. But it would be very useful for sharing huge directories that you can't afford to copy to IPFS which is a huge wast of space.

For people who just want to share quickly some static files they have in their filesystem, it would be faster and would not copy everything.

What do you think ?

**Comment by whyrusleeping** [comment]
see #875

**Comment by palkeo** [comment]
Cool, thanks !
