### ISSUE TITLE
ipfs init nukes everything in the directory

### ISSUE THREAD

**Issue by noffle** [ipfs/go-ipfs#2478]
Unexpected behaviour: `ipfs init --force` will destroy everything in `$IPFS_PATH`, not just the files IPFS created. I learned this the hard way by setting `IPFS_PATH=/tmp` and then having my whole `/tmp` dir nuked when I init'd again.

**Comment by noffle** [comment]
A good analogy of why this is disasterous is imagining if `git init --force` wiped everything in the current directory.

**Comment by whyrusleeping** [comment]
ipfs init -f has been removed

**Comment by lbeziaud** [comment]
The `-f` option is still used by [bench_cli_ipfs_add](https://github.com/ipfs/go-ipfs/blob/master/test/bench/bench_cli_ipfs_add/main.go#L67). @whyrusleeping

**Comment by Stebalien** [comment]
See https://github.com/ipfs/go-ipfs/pull/4081
