### ISSUE TITLE
Automatic updates of jbenet/go-ipfs on dockerhub

### ISSUE THREAD

**Issue by chpio** [ipfs/go-ipfs#2482]
it seams (?!) [ipfs/go-ipfs](https://hub.docker.com/r/ipfs/go-ipfs) is _the_ docker repo. so it would be nice if jbenet/go-ipfs would go away (i was using it until now and was wondering why it's never updating)

**Comment by lgierth** [comment]
Oh man that's my bad, sorry -- when I created the ipfs/go-ipfs automated image I wanted to make the old jbenet/go-ipfs image update too. Taking care of it today.

We won't be deleting jbenet/go-ipfs for a good while because many people are using it still (like you).

**Comment by jbenet** [comment]
Wonder if we can symlink it

**Comment by lgierth** [comment]
We had this working for a while in meantime, but then it looks like the linking to jbenet/go-ipfs from ipfs/go-ipfs broke some time after 7-Jul (5d1b28e233b37a8567bf444e9c3dd21aae5c14b7) -- Docker Hub doesn't have the linking feature anymore, instead it has webhooks and triggers now.

@jbenet do we still want to support the old jbenet/go-ipfs image?

**Comment by jbenet** [comment]
I think a lot of people are depending on it. I've seen over 200K pulls in
the last couple mo.
