### ISSUE TITLE
IPFS get hangs unless peers are connected

### ISSUE THREAD

**Issue by jwsher** [ipfs/go-ipfs#2485]
On computer A  behind a NAT firewall I run the following command:

` ./ipfs add very-small-file
`
Then on computer B, which is a VPS server on another network, I run the command:

`./ipfs get <multihash from very-small-file>
`

The ipfs get hangs for an indefinite amount of time.  If I directly connect from computer A to computer B using the following command on computer A:

`ipfs connect <Computer B IPFS address>
`
 it works.  If I grab the file off of ipfs.io using the URL https://ipfs.io/ipfs/<multihash&gt; it works and then my hung ipfs on the VPS server is able to get the file soon after and successfully completes the transfer.

Is this a bug or is it expected behavior?  IMHO, having to know the IPFS server address that a file resides on would make the system more difficult to use than otherwise.

**Comment by whyrusleeping** [comment]
What sort of NAT is it? If it supports upnp or nat-pmp, they should be able to connect just fine. Otherwise, theres no way to dial into your 'computer A'. And you just have to hope that computer A decides to connect to computer B as part of its dht maintenance.

This connectivity is something we're working on improving, but its very difficult stuff.

**Comment by jwsher** [comment]
This is my ISP's NAT which I have no control over and which doesn't support uPnP.  I ended up using OpenVpn to a VPS using this guide:

https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-14-04

I then set up port forwarding with UFW (Uncomplicated FIrewall) to my server on the VPN network with the VPS:

https://gist.github.com/kimus/9315140

Believe it or not, this works fine.

**Comment by whyrusleeping** [comment]
@jwsher whoa, thanks for those tips. I hadnt actually figured out how to get things working from behind a vpn yet

**Comment by whyrusleeping** [comment]
Just to recap, `ipfs get` will hang if it cannot find or connect to the peers with the data youre looking for. If both peers involved are confirmed to be online, this is generally an issue with NAT traversal.

I'm gonna close this issue out, if there are any other questions or problems along this line, please open another issue
