### ISSUE TITLE
`pin add` doesn't return

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#2488]
Following scenario:

1. `ipfs add -r` something locally
2. have Pinbot pin it, or pin it on the gateways by hand
3. the `pin add` command won't return indefinitely
4. restart IPFS on the gateways
5. `pin add` returns immediately because apparantly pinning already finished before restarting IPFS

Will fetch a goroutine dump when this happens the next time.

**Comment by davidak** [comment]
i can open this from the public gateway:

https://ipfs.io/ipfs/QmSHYqKyiKQYUoUdik5DSpDxKjwNrq5QH8eqFJRFEQpR6P

but can't pin it or open with my local gateway. i have 135 peers, so it should be possible to reach a node that has this files.

here is the output of `curl localhost:5001/debug/pprof/goroutine\?debug=2` while pinning is still running:

http://ipfsbin.xyz/#QmTQrDAhR5FkfDJiNxksiM5D2HHseauNhMKo7QE6fk8D3k

**Comment by whyrusleeping** [comment]
@lgierth @davidak is this still an issue?

**Comment by davidak** [comment]
No, it seams to be solved! 👍 

(have you changed anything?)

I'm still not able to pin [this Video](https://pod.geraspora.de/posts/4458195). But i think no body is hosting it.

```
ipfs get QmNbQh8hVUVkVnt9Ggi5rVjxVdFhjGHfNrA8tk16sWtAw6
Saving file(s) to QmNbQh8hVUVkVnt9Ggi5rVjxVdFhjGHfNrA8tk16sWtAw6
5.00 MB
```
i stopped after 17h48m18s (also tried multiple times in the past)

**Comment by lgierth** [comment]
Yes this is definitely resolved with the yamux and utp fixes.
