### ISSUE TITLE
Getting "no addresses on peer being sent!" error

### ISSUE THREAD

**Issue by mitar** [ipfs/go-ipfs#2495]
Just installed the go binary 0.3.11 on my Mac OS X, running daemon like explained in the "getting started" guide, and I see errors in the console:

```
19:38:33.376 ERROR        dht: no addresses on peer being sent!
					[local:<peer.ID XKKFFa>]
					[sending:<peer.ID >]
					[remote:<peer.ID SoLnSG>] handlers.go:73
```

Not sure what is this. Is it because I ran `ipfs diag net`?

It seems I am connected well:

```
ipfs swarm peers | wc -l
100
```

**Comment by firemound** [comment]
Hey @mitar, I am getting this same issue, not sure what it's complaining about. Did you ever figure out the issue? I'm running v0.4.2 on Ubuntu 16.04.1.

**Comment by Kubuxu** [comment]
It probably shouldn't be an error. 
@firemound do you encounter any other problems apart from that log?

**Comment by firemound** [comment]
@Kubuxu no, I'm not experiencing any obvious service problems. It is not clear why that error is being logged.

**Comment by whyrusleeping** [comment]
This is not technically an error, but its something we need to fix so that we don't encounter the issue. The problem is that we might have information for a peer, but all the addresses we have for them have expired, leading to us  'knowing' about a peer, but sending an empty response because we don't know any addresses.

**Comment by whyrusleeping** [comment]
TODO: decide what to do in libp2p when we no longer have any valid addresses for a peer. We should probably clear any other info we have about them from the peerstore to save memory.

**Comment by maxlath** [comment]
if it's not a critical issue, could it get something like a yellow `WARN` instead of a red `ERROR` label? It does look scary for newbies :)

**Comment by jbenet** [comment]
It's not an error, and expected behavior. this should be lowered to Debug.
