### ISSUE TITLE
DHT issues right now

### ISSUE THREAD

**Issue by slothbag** [ipfs/go-ipfs#2507]
There appears to be some sort of problems with the DHT part of IPFS. I add some content to one node and another external node cannot get the content. I had to manually issue a ipfs swarm connect command, once connected the remote node could get the content.

I have tried with two peers on a LAN, two peers on port forwarded internet addresses.. same problem.  

Either a problem exists with the DHT peer finding or my nodes are running out of "empty slots" for a new peer to connect.

**Comment by slothbag** [comment]
I'm getting this error after a long wait..

```
Error: pin: Failed to get block for QmSyjzwFdMEjCbXCtiHYdwUPPsgCYPB41HKG6Atr3hVsZj: open /root/.ipfs/blocks/122044ef/122044ef3820bde050bcf76022da308974f224c284dbbbbf7508d5226110ffa0eb52.data: too many open files
```

**Comment by lamarpavel** [comment]
I recently had the same issue but blamed it on my university network. I was trying to get things working with a few friends at university - two of us added different text files to IPFS and one of the others could get one of those text files but not the other, while no one else could get either. We also got the same Error as you.

Back at home I tried the same thing in my LAN with two laptops and it worked perfectly.

Some time later I tried again with a friend at uni and we manually added each other via `swarm connect` and then we could see each others files. This was all on IPFS 0.3.11.

**Comment by whyrusleeping** [comment]
I've also noticed issues with discovery and NAT traversal lately. I've been trying to find time to narrow down the issue. I wrote up some debugging tips here: https://github.com/ipfs/go-ipfs/issues/2401#issuecomment-201021451

If anyone wants to help out and try to reproduce the issue, maybe write up different scenarios things work in vs things not working, that would be amazingly helpful.

**Comment by whyrusleeping** [comment]
Tracking these issues in #2509

**Comment by slothbag** [comment]
Will track other issue. thanks.
