### ISSUE TITLE
ipfs need to allow sharing of filles already on filesystem without moving them into own storage

### ISSUE THREAD

**Issue by iav** [ipfs/go-ipfs#2508]
ipfs need to allow sharing of filles already on filesystem without moving them into own storage.
Like older filesharing system, like eMule or DirectConnect.

Use-case: a big three with files located on server. Files accessible via http server and possible kind of other services, like ftp etc. What means - that file collection want to be accessible via ipfs, but should still be placed on filesystem as it placed on ipfs opening moment, and fileset will be updated on time going.

It means should be a way to add into storage a set of filesystem trees like _--no-relocation_ option.
With them I write _ipfs  add --no-relocation /var/ftp_ every file placed inside _/var/ftp_ folder will be accessed by ipfs hashes.
Maybe, some kind of a way to exclude needed - like _ipfs  add --no-relocation /var/ftp --x=".ssh/*" --x=".htaccess" --x="*/*passwd"_

**Comment by whyrusleeping** [comment]
take a look at #875

**Comment by iav** [comment]
Sure. Sorry.

**Comment by RichardLitt** [comment]
@iav No worries! There are a ton of issues, it's easy to get lost. :)
