### ISSUE TITLE
IPFS_BOOTSTRAP / env-override of config?

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#251]
As noted in #250, it would be nice to be able to pass in bootstrap addresses as part of an envvar or a cli param. This would make it easier to programmatically create nodes.

What might make sense is to design a seamless way for env vars to override configuration variables, that way we dont have to create multiple ways of changing them.

Maybe a `IPFS_CONFIG(_Key)+` ->`config(.Key)+` approach. (e.g.`IPFS_Config_Bootstrap`)... hmm i dont like this.

**Comment by diasdavid** [comment]
We can keep it simple by using env vars and giving the option to extend the default config with `--config=` option

**Comment by hannahhoward** [comment]
@gmasgras can you comment on whether this is still relevant based on the Docker-izing work you are doing? Should it remain open?

**Comment by gmasgras** [comment]
Here is a PR that addresses this issue: https://github.com/ipfs/go-ipfs/pull/6325

**Comment by lidel** [comment]
As clarified in https://github.com/ipfs/go-ipfs/pull/8326#issuecomment-912726852:
>  If we ever add config override via env variable, it should be supported in go-ipfs natively ([`go-ipfs/docs/environment-variables.md`](https://github.com/ipfs/go-ipfs/blob/master/docs/environment-variables.md)), and work as "ad-hoc" ephemeral override that does not mutate the config file.
