### ISSUE TITLE
'make install' fails with 'dial tcp 127.0.0.1:5001: getsockopt: connection refused'

### ISSUE THREAD

**Issue by chriscool** [ipfs/go-ipfs#2510]
I get this error now:

```
> make install
gx --verbose install --global
installing package: go-ipfs-0.4.0
[1 / 6] fetched dep: gogo-protobuf
[2 / 6] fetched dep: go-log
  - QmNefBbWHR9JEiP3KDVqZsBLQVRmH3GBG2D2Ke24SsFqfW not found locally, fetching into /home/utilisateur/gocode/src/gx/ipfs/QmNefBbWHR9JEiP3KDVqZsBLQVRmH3GBG2D2Ke24SsFqfW
  - fetching QmNefBbWHR9JEiP3KDVqZsBLQVRmH3GBG2D2Ke24SsFqfW via ipfs api
[3 / 6] fetched dep: go-net
[4 / 6] fetched dep: goprocess
[5 / 6] fetched dep: randbo
ERROR: [6 / 6 ] parallel fetch: failed to fetch package: QmNefBbWHR9JEiP3KDVqZsBLQVRmH3GBG2D2Ke24SsFqfW:Post http://127.0.0.1:5001/api/v0/get?arg=QmNefBbWHR9JEiP3KDVqZsBLQVRmH3GBG2D2Ke24SsFqfW&encoding=json&stream-channels=true&: dial tcp 127.0.0.1:5001: getsockopt: connection refused
ERROR: install deps: failed to fetch dependencies
make: *** [deps] Erreur 1
```

**Comment by Stebalien** [comment]
Assuming you're building from git, what commit are you trying to build (`git rev-parse HEAD`)? `gx` should be using `v04x.ipfs.io`, not `localhost:5001`.

The underlying issue is that, at some time in the past, you ran an IPFS daemon which created `~/.ipfs/api` (indicating that there is an IPFS API running at `localhost:5001`) but the IPFS daemon didn't delete this file when it exited. See #2395.

**Comment by chriscool** [comment]
```
commit 45e1f757d2c8477a1814e25f6221481320d8cb78
Merge: 18da0a4 e2ea348
Author: Jeromy Johnson <whyrusleeping@users.noreply.github.com>
Date:   Sun Mar 27 17:44:01 2016 -0700

    Merge pull request #2502 from MichaelMure/fix_fuse_test
    
    correct import in fuse tests
```

but I also tried v0.4.0-rc3 and I get the same error.

**Comment by whyrusleeping** [comment]
thats bizarre... @chriscool could you try deleting ~/.ipfs/api and try again?

**Comment by chriscool** [comment]
Yeah, it works better after deleting ~/.ipfs/api.
It blocked twice, but after killing and restarted it completed.
Thanks!

**Comment by whyrusleeping** [comment]
i'm gonna go ahead and blame the gateways for that...

**Comment by lgierth** [comment]
> Yeah, it works better after deleting ~/.ipfs/api.

This is being left behind by double-ctrl-c'ing I think. We should maybe decouple non-daemon tools from IPFS_PATH.
