### ISSUE TITLE
swarm 0

### ISSUE THREAD

**Issue by who-am-1** [ipfs/go-ipfs#2518]
"AgentVersion": "go-ipfs/0.3.11"
I do ipfs init, ipfs daemon
I can open readme, locally added files, but I can't open links on browser from quick-start.
ipfs swarm peers is empty
I have openwrt router

**Comment by atommixz** [comment]
looks like upnp work's properly https://ipfs.pics/QmZmQ5vjaRPwv6eSVXEZ8jrkX5iazV3t7V87Woe78Gr4hC
192.168.1.200 it's my pc with empty swarm

**Comment by whyrusleeping** [comment]
are you behind a vpn?

**Comment by atommixz** [comment]
no, I behind openwrt router, he connected to provider with ipoe and dhcp

**Comment by whyrusleeping** [comment]
could you try running:
```bash
ipfs swarm connect /ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
ipfs swarm connect /ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z
ipfs swarm connect /ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM
```

And let me know if any of them error?

**Comment by atommixz** [comment]
```
ipfs swarm connect /ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
Error: connect QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ failure: dial backoff

$ ipfs swarm connect /ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z
Error: connect QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z failure: dial attempt failed: failed to dial <peer.ID SoLnSG>

$ ipfs swarm connect /ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM
Error: connect QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM failure: dial backoff


```

**Comment by whyrusleeping** [comment]
interesting... could you restart your daemon and try things again?

**Comment by atommixz** [comment]
```
$ ipfs swarm connect /ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
Error: connect QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ failure: dial attempt failed: failed to dial <peer.ID aCpDMG>
$ ipfs swarm connect /ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z
Error: connect QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z failure: dial attempt failed: failed to dial <peer.ID SoLnSG>
$ ipfs swarm connect /ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM
Error: connect QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM failure: dial attempt failed: failed to dial <peer.ID SoLPpp>
```

**Comment by atommixz** [comment]
i can try update openwrt 15.05 to 15.05.1

**Comment by whyrusleeping** [comment]
wow. those are some super helpful error messages...

Its not going to be an issue with openwrt

**Comment by atommixz** [comment]
or install ipfs from git

**Comment by whyrusleeping** [comment]
alright, one more thing to try, a bit more involved debugging:

kill your ipfs daemon, and then in the terminal youre running it from, set `IPFS_LOGGING` to `debug`, and run the daemon with `ipfs daemon 2> ipfs.log`.

then try the connections again, if they fail, kill the daemon and send me that logfile in a pastebin

**Comment by atommixz** [comment]
http://ix.io/vqO

**Comment by whyrusleeping** [comment]
thats bizarre. zero indication of why the dial fails...

Could you try using an ipfs binary from http://dist.ipfs.io ?

**Comment by atommixz** [comment]
I used go-ipfs_v0.3.11_linux-amd64.tar.gz
http://ix.io/vrf/

**Comment by atommixz** [comment]
also I can't open webui with FF and chromium, just infinite loading blank page
git version (same with v0.3.11) ix.io/vrW

**Comment by atommixz** [comment]
I try connect to ipv6 peers (I get it from ipfs on vps), also I try connect to ipv6 in fc00::/8 - I have 4 peers from ipfs on vps
ipfs version 0.4.0-dev http://ix.io/vsF
still empty ipfs swarm peers

**Comment by atommixz** [comment]
tomorrow I'll try direct connect (without router), if it will be useless, then my pc is broken. Maybe iommu and eth card

**Comment by atommixz** [comment]
So, I do direct-connect internet to my pc, just do 'sudo dhcpcd -n <interface> and I got internet. I try to use binary from http://dist.ipfs.io, but all the same. I try to use peers as u say, over ipfs swarm connect. It's not work for my pc. Also I try disable iommu in BIOS and use iommu=soft, it's just not work for me. 

I can telnet from vps to my pc on 4001 port, and looks like it works http://ix.io/vx5 . I have no rules in iptables on pc, service is disabled.

I have no any idea. Another software just works fine with openwrt and upnp.
What else can I do?

**Comment by atommixz** [comment]
good news everyone! I can connect on my PC to some peers from my vps (not all), over openwrt router and upnp, also i can connect to my VPS over cjdns. After I connect to 1 peer, I get many peers. No idea why I can connect to one, but I can not connect to another. 
What do you think about it?
U can close this issue.

**Comment by atommixz** [comment]
The question is, why my ipfs on desktop can not connect to peers of the bootstrap list

**Comment by atommixz** [comment]
peer list on my PC http://ix.io/vxn

**Comment by atommixz** [comment]
I still not connect with anyone if i'm not connected to my vps ipfs (but i can't use it, cause it eat my small vps memory)

**Comment by fiatjaf** [comment]
I have this same problem. I can't understand what is happening. I do see any logging output.

**Comment by atommixz** [comment]
**fiatjaf**, problem is #2879 
You can use cjdns network and add this lines into .ipfs/config to work around this:
```
    "/ip6/fcfe:eab4:e49c:940f:8b29:35a4:8ea8:b01a/tcp/34843/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm",
    "/ip6/fce3:c53b:c3c5:2f54:8bb0:b6d9:898e:f140/tcp/52587/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z",
    "/ip6/fcdf:a296:afe3:7118:4135:cc0b:ff92:4585/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3",
    "/ip6/fcd8:a4e5:3af7:557e:72e5:f9d1:a599:e329/tcp/42694/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
    "/ip6/fc3d:9a4e:3c96:2fd2:1afa:18fe:8dd2:b602/tcp/41029/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx",
```

**Comment by fiatjaf** [comment]
Thank you very much, @atommixz. So now when you solve NAT traversal you should start thinking about double NAT traversals? Cool.

After I do that will IPFS be able to reach the other peers without having to use cjdns? Also (only if you answered yes to the previous question) I don't have any cjdns people to connect to, can you peer with me?

**Comment by atommixz** [comment]
I'm not developer, I just spoke with the developer about this. Mr. Kubuxu told me the solution with the help of cjdns. They will solve the problem sooner or later.

Yes, cjdns just helps connect to another peers from ipv4/ipv6. I have 117 peers now.
```
$ ipfs swarm peers | wc -l
117
```
Very many public peers for cjdns is here https://pad.meshwith.me/p/public, I recommend you adding more then one peer for better connectivity.

**Comment by fiatjaf** [comment]
Thanks again, @atommixz. Now I am able to connect to cjdns and ping these addresses you pasted, and I have added them to the IPFS bootstrap list, but IPFS still can't connect. `ipfs swarm peers` gives me nothing, even after daemon restarts and letting the daemon running for many hours. Do you have any more tips for me?

**Comment by atommixz** [comment]
This works for me. Try check that UPNP works on your router. And add this peers in the top of the bootstap list

**Comment by tari** [comment]
I'm seeing what looks like a similar issue to @fiatjaf, on a system that is not behind a NAT. The daemon reports listening on TCP port 4001, which I have opened in my firewall. There are periodic bootstrap errors in the log:

```
{"error":"failed to bootstrap. dial attempt failed: misdial to \u003cpeer.ID SoLSaf\u003e through /ip4/128.199.219.111/tcp/4001 (got \u003cpeer.ID \u003e)","event":"bootstrapError","peerID":"QmcAwcBoHFMgevUpn4UHpTcSJmTs4Cx2Q9jnDTQVG2nRyQ","system":"core","time":"2016-08-05T09:14:37.907135299Z"}
```

`ipfs swarm connect` fails in the same way as described earlier in this thread. IPFS version is 0.3.11 on NixOS.

**Comment by whyrusleeping** [comment]
@tari ipfs version 0.3.11 and earlier no longer have official bootstrap nodes on the network. I would recommend updating to a newer version of ipfs

**Comment by tari** [comment]
Ah, so it is. I suspected the problem might be a protocol mismatch, but it would be nice if the documentation mentioned something to the effect of "using a sufficiently old version might not work". I only found mention of the dropped 0.3 support on the blog after I knew to look for it.

Nix hasn't yet packaged 0.4.x, but that's not your fault. Thanks!

**Comment by jbenet** [comment]
@tari good point. want to PR docs somewhere to make it easier to figure this out?

**Comment by saiganesh10** [comment]
@atommixz I am using ipfs version 0.4.10. There is no response from swarm peers. Can you explain the solution with cjdns for the same?

**Comment by who-am-1** [comment]
I changed the provider and can not reproduce it anymore

**Comment by Stebalien** [comment]
This issue is old enough that it's probably not worth keeping open (either fixed or we'll have to start debugging from scratch).
