### ISSUE TITLE
Literal hash scheme ?

### ISSUE THREAD

**Issue by palkeo** [ipfs/go-ipfs#2522]
Hi !

For some data structures that can be stored in IPFS, you will point to other structures and sometimes they can be very small.

Say, you have a filesystem where you point to a hash of the content of the file, but the file can be so small that the hash will be smaller than its content, and you still have to retrieve the block with the content… That's a waste of time and space.

Given that IPFS has support for multihashes, what about having a specific format of multihash where you would store the base64-encoded content (or something like that) directly into the hash, if it fits ?

That could simplify a lot some data structure, allowing to "inline" pointers without any added complexity, and can be done transparently :)

**Comment by lgierth** [comment]
Yes, we want this and are tracking the discussion in jbenet/multihash#13
