### ISSUE TITLE
FAQ?

### ISSUE THREAD

**Issue by KrishnaPG** [ipfs/go-ipfs#2524]
Couldn't find any FAQ section on the IPFS.io website- anyone know the location where FAQ are documented for IPFS?

For example,
- Does IPFS support ACLs or all the files put on IPFS are accessible by all without restriction? What is the recommended way to achieve secure / privacy in the later case?
- Where can we find more info on the Gateway? We would like to support the existing [gateway.ipfs.io](gateway.ipfs.io) with our gateway instance as backup (say, to take off some load from yours) - how to achieve it?
- Also, would it be possible to have on-premise Gateway that only caters few restricted set of machines inside private network (and not expose everything outside)? Like a private p2P
- Is it possible to have the owner of the content control where (and how many) copies are stored across the network? And perhaps expire the content after some set time or manually?
- What is the recommended way to handle frequently updated content? E.g. website pages (links from external sites may get invalidated upon updation)

Thanks for any pointers to answers to these above.

**Comment by Kubuxu** [comment]
hee is FAQ section https://github.com/ipfs/faq/issues/

**Comment by RichardLitt** [comment]
Thanks for pointing this out @KrishnaPG - we need to work on that. The FAQ is indeed at ipfs/faq. I would suggest reopening these questions there, because they aren't go-ipfs specific.
