### ISSUE TITLE
iptb dependency

### ISSUE THREAD

**Issue by chriscool** [ipfs/go-ipfs#2525]
It looks like iptb code is both in https://github.com/ipfs/go-ipfs/tree/master/test/dependencies/iptb and in https://github.com/ipfs/go-ipfs/tree/master/Godeps/_workspace/src/github.com/whyrusleeping/iptb/util

I wonder if it would be possible to have everything in one place.

**Comment by chriscool** [comment]
By the way once all my recent iptb PRs are merged I'd like to upgrade the iptb dependency to the latest version, and it would help if I could do it simply in one place.

cc @whyrusleeping

**Comment by whyrusleeping** [comment]
The 'main' code is in test/dependencies, the 'lib' is in Godeps. I agree its not ideal... We could probably move the lib back to test/dependencies and rewrite the paths in the 'main' code to point there instead.

**Comment by whyrusleeping** [comment]
iptb is now vendored with gx
