### ISSUE TITLE
ipfs name resolve --local errors with 'multihash too short'

### ISSUE THREAD

**Issue by area** [ipfs/go-ipfs#2527]
I'm trying to use the feature documented https://github.com/ipfs/go-ipfs/pull/1834

`ipfs name resolve <id>` resolves (eventually) as normal, but `ipfs name resolve --local <id>` gives `Error: multihash too short. must be > 3 bytes`. Do I need some further setup to be able to use `--local`?

**Comment by whyrusleeping** [comment]
huh. That does look like a bug... thanks for reporting!
