### ISSUE TITLE
ipns resolve locally

### ISSUE THREAD

**Issue by cpacia** [ipfs/go-ipfs#2535]
Question, does the IPNS query resolve locally if you query for your own peer ID? Specially I care about on the gateway, but it could be in the api as well. Or does it always do a DHT crawl? 

If it does a DHT crawl can it be made to just resolve it locally to save some time?

**Comment by whyrusleeping** [comment]
It by default will always crawl the dht, unless the value is cached (given the caching rules and TTL set on the record). But there is a `--local` flag you can pass to `ipfs name resolve` to have it only use information you have locally.

**Comment by cpacia** [comment]
What are the caching rules? For example, when does it stop pulling from cache and make another dht crawl? 

Also, the use case I'm thinking of is in openbazaar the UI can query: /ipns/<peerid>/ to view a store, but it would make it easier from an implementation standpoint if viewing your own store used the same api call: /ipns/<ownpeerid>

But that looks like it hits the dht every time. I was able to patch gateway_handler with like 10 lines of code to check if the peerid in an ipns query is your own id, if so it resolves it locally and changes it to an ipfs request. That makes viewing my own store much faster. I don't know if you want a PR for that or not.

**Comment by VictorBjelkholm** [comment]
> check if the peerid in an ipns query is your own id, if so it resolves it locally

This really feels like that should be the default behaviour for the gateway and other calls. Currently, resolving your own Peer ID via IPNS takes too long and it's probably the first thing people try when it comes to IPNS. Publish/resolve from your own ID.

**Comment by Stebalien** [comment]
I agree. For one's *own* peer ID, we could short-circuit (as this key absolutely should not be shared). However, we can't generalize that to keys in the keystore as others may be publishing on the same key.

**Comment by whyrusleeping** [comment]
I don't think short circuiting makes sense. You don't want the command to lie to you. If I run `ipfs name resolve foo`, i'd expect it to fail if that record was no longer accessible on the DHT. caching and short circuiting here could lead to some annoying "works on my machine" type issues
