### ISSUE TITLE
ipsf cat - Strange output 

### ISSUE THREAD

**Issue by EliasGabrielsson** [ipfs/go-ipfs#2546]
Input:
```
ipfs cat QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V
```

Expected output same as:
```
ipfs cat QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/security-notes
```

Got this output:
```
Error: no link named "QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V" under QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG
```

Is it me how misunderstand the documentation or is it bug?

**Comment by noffle** [comment]
You're close!

`QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/security-notes` is equivalent to `QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V`, which means you get see the security notes with either

```
$ ipfs cat QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/security-notes
```
or
```
$ ipfs cat QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V
```

The `/` delimeter here refers to a link by name, so `QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V` would only work of the object `QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG` had a link named `QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V` (which it doesn't; it has a link named `security-notes`.

**Comment by EliasGabrielsson** [comment]
Ok, is IPLD the right place to get all information how it works:
https://github.com/ipfs/specs/tree/master/ipld?

**Comment by noffle** [comment]
IPLD isn't deployed yet -- we're using a unixfs-like pathing system (using protobufs underneath). The [whitepaper](https://github.com/ipfs/papers/raw/master/ipfs-cap2pfs/ipfs-p2p-file-system.pdf) is one place you might read about this.
