### ISSUE TITLE
Memory leak while adding files

### ISSUE THREAD

**Issue by neko259** [ipfs/go-ipfs#2547]
I added 14403 image files (exactly half of them are small thumbnails about 8K size, other vary from 100K to 10M. The overall size is 4.7G. While performing add, ipfs process took RAM and the most was 6G (that is at the completion point). After completion the memory was not freed completely, 2G were still taken by the process. When trying to break the process, the memory was not freed at all and frozen at the break point.

I tried to do ls on this uploaded directory but failed, ipfs ls process starts to eat memory again.

**Comment by SCBuergel** [comment]
Which version of ipfs (check with `ipfs version`) are you running and on which platform? I had that issue [previously](https://github.com/ipfs/go-ipfs/issues/2173) but it should be resolved in the latest version.

**Comment by neko259** [comment]
I tried on 0.3.11 and 0.4-dev from dist on the moment of about a week 
ago. If something changed from that point, I can try again.

**Comment by Kubuxu** [comment]
There was release of `0.4.0` few days ago so it might have changed.

**Comment by neko259** [comment]
Seems working indeed.
