### ISSUE TITLE
outdated helptext for ipfs log level

### ISSUE THREAD

**Issue by fzzr-** [ipfs/go-ipfs#2551]
ipfs version 0.4.0

```bash
# ipfs log level all info
Changed log level of '*' to 'info'
# ipfs log level all fatal
Error: logger: invalid log level
# ipfs log level all panic
Error: logger: invalid log level
```

But help says:
```bash
ipfs log level --help 

    ipfs log level <subsystem> <level> - Change the logging level.

ARGUMENTS:

    <subsystem> - The subsystem logging identifier. Use 'all' for all subsystems.
    <level>     - The log level, with 'debug' the most verbose and 'panic' the least verbose.
    			One of: debug, info, warning, error, fatal, panic.
```

**Comment by fzzr-** [comment]
And one question: How can I check if daemon is alive?

**Comment by whyrusleeping** [comment]
It looks like that help text is out of date, there arent fatal and panic levels anymore. 

As for best way of checking daemon liveness, i normally run `ipfs id` and make sure that the addresses field isnt null. Having addresses there means your node is online.

**Comment by fzzr-** [comment]
@whyrusleeping Thank you. I now do it that way.

**Comment by fzzr-** [comment]
https://github.com/ipfs/go-ipfs/blob/2b6da0c024f28abeb16947fb452787196a6b56a2/core/commands/log.go#L45-L47
