### ISSUE TITLE
`ipfs get` stalling at 1024KB (Windows)

### ISSUE THREAD

**Issue by SCBuergel** [ipfs/go-ipfs#2552]
I am trying to `ipfs get QmaYFLojf84ZqmMR9SMZuwc4X4vL4oKoutjeScHxmeocHM`. It starts downloading but then stalls (I have to kill it via Ctrl+c):

```
Saving file(s) to QmaYFLojf84ZqmMR9SMZuwc4X4vL4oKoutjeScHxmeocHM
1024.00 KB
```

The complete size of the object is however bigger than that:

```
>ipfs object stat QmaYFLojf84ZqmMR9SMZuwc4X4vL4oKoutjeScHxmeocHM
NumLinks: 19
BlockSize: 921
LinksSize: 838
DataSize: 83
CumulativeSize: 4798097
```

Accessing it via gateway works: https://gateway.ipfs.io/ipfs/QmaYFLojf84ZqmMR9SMZuwc4X4vL4oKoutjeScHxmeocHM

I am running the latest ipfs release (0.4.0) installed from binary download on windows 7 within a very restricted network so my deamon is running read-only. Still I think the behavior should be different.

**Comment by whyrusleeping** [comment]
There is a lot that we havent tested on windows, I'm not sure why this would happen but I'm working on getting an azure box so we can run windows CI and test these things

**Comment by djdv** [comment]
I'm closing this due to age. The listed hash doesn't seem to be available anymore so I can't test it specifically, but `get` in general should be working on Windows right now.
