### ISSUE TITLE
uTP on IPv4

### ISSUE THREAD

**Issue by cpacia** [ipfs/go-ipfs#2553]
Don't know if this is a problem with my machine, but I can't seem to get it to listen on external uTP IPv4.  /ip4/73.89.130.237/udp/4001/utp is never listed in the swarm addrs.

Config:
"Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/utp",
      "/ip6/::/udp/4001/utp"
 ]

Addrs:
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/utp
Swarm listening on /ip4/192.168.0.11/tcp/4001
Swarm listening on /ip4/192.168.0.11/udp/4001/utp
Swarm listening on /ip4/73.89.130.237/tcp/4001
Swarm listening on /ip6/2601:18d:8302:3e0:200:ff:fe00:a42f/tcp/4001
Swarm listening on /ip6/2601:18d:8302:3e0:200:ff:fe00:a42f/udp/4001/utp
Swarm listening on /ip6/2601:18d:8302:3e0:70cf:c542:7c6a:4e8a/tcp/4001
Swarm listening on /ip6/2601:18d:8302:3e0:70cf:c542:7c6a:4e8a/udp/4001/utp
Swarm listening on /ip6/2601:18d:8302:3e0:9c39:c7c3:55c9:eadd/tcp/4001
Swarm listening on /ip6/2601:18d:8302:3e0:9c39:c7c3:55c9:eadd/udp/4001/utp
Swarm listening on /ip6/2601:18d:8302:3e0:a4b8:fb9b:415:4952/tcp/4001
Swarm listening on /ip6/2601:18d:8302:3e0:a4b8:fb9b:415:4952/udp/4001/utp
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/::1/udp/4001/utp

**Comment by whyrusleeping** [comment]
interesting... good catch. This might be part of an underlying NAT issue.

**Comment by ckmakcesar** [comment]
encountering the similar problems building a private network using .ipfs/swarm.key



tried with the same swarm config; but not even seeing IPv6 UTP: 
```
Initializing daemon...
Adjusting current ulimit to 2048...
Successfully raised file descriptor limit to 2048.
Swarm is limited to private network of peers with the swarm key
Swarm key fingerprint: 1aa873ae11510bb1cf6f911d1cc807ce
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.7.238/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit/ipfs/QmPhEmiE1sLDkLZvqwEbtvSj7R4kfisyAefMfcLrQ1sdDN
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.7.238/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
```



also tried with the following, without TCP; not sure if it is due to my network settings: 

Config:
"Swarm": [
"/ip4/0.0.0.0/udp/4001/utp",
"/ip6/::/udp/4001/utp"
]

```
Initializing daemon...
Adjusting current ulimit to 2048...
Successfully raised file descriptor limit to 2048.
10:29:40.857 ERROR   cmd/ipfs: error from node construction: failed to listen on any addresses: [no transport for address: /ip4/0.0.0.0/udp/4001/utp no transport for address: /ip6/::/udp/4001/utp] daemon.go:320
Error: failed to listen on any addresses: [no transport for address: /ip4/0.0.0.0/udp/4001/utp no transport for address: /ip6/::/udp/4001/utp]
```

**Comment by lgierth** [comment]
We don't currently support /utp anymore, you'll have to remove it from your config.

**Comment by tianser** [comment]
@lgierth any protocal based udp will be not supported anymore later?

**Comment by Stebalien** [comment]
We're actively working on adding support for QUIC: https://github.com/libp2p/go-libp2p-quic-transport

**Comment by tianser** [comment]
@Stebalien get it,  Good job
