### ISSUE TITLE
corenet wrong import

### ISSUE THREAD

**Issue by cpacia** [ipfs/go-ipfs#2558]
I believe the peer import in core/corenet/net/ should be from go-libp2p-peer. The repo it's pointing to currently doesn't exist.

**Comment by whyrusleeping** [comment]
yeah, I just changed that in go-libp2p yesterday. That change hasnt yet been propogated up into go-ipfs, i think @lgierth was planning on doing that today.

**Comment by cpacia** [comment]
Ah ok cool. Yeah I was going to say. It looks like there's a log of places where it's using the wrong peer.

**Comment by whyrusleeping** [comment]
this has been resolved, we use the right imports across the board now

**Comment by W-B-S** [comment]
in this example 
https://ipfs.io/docs/examples/example-viewer/example#../api/service/readme.md
I am still puzzled by this problem.


import (
    "fmt"

    core "github.com/ipfs/go-ipfs/core"
    corenet "github.com/ipfs/go-ipfs/core/corenet"
    fsrepo "github.com/ipfs/go-ipfs/repo/fsrepo"

    "code.google.com/p/go.net/context"
)
