### ISSUE TITLE
High CPU usage after sleep, os x

### ISSUE THREAD

**Issue by EliasGabrielsson** [ipfs/go-ipfs#2566]
* `ipfs daemon`, running 5 hours.
* Computer sleep ~ 10h
* Wakeup - High usage for the ipfs service, `ipfs; 220 % cpu; threads: 86; idle wake ups: 356`

```
ipfs diag sys:
{"diskinfo":{"free_space":2.9200621568e+10,"fstype":"17","total_space":2.8938477568e+10},
"environment":{"GOPATH":"/Users/elias/go","IPFS_PATH":""},
"ipfs_commit":"a957b4b",
"ipfs_version":"0.4.1-dev",
"memory":{"swap":0,"virt":0},
"net":{"interface_addresses":["/ip6/::1","/ip4/127.0.0.1","/ip6/fe80::1","/ip6/fe80::9227:e4ff:fef2:c5ad","/ip4/192.168.10.11"]},
"runtime":{"arch":"amd64","compiler":"gc","gomaxprocs":3,"numcpu":4,"numgoroutines":485,"os":"darwin","version":"go1.6"}}
```

**Comment by Faleidel** [comment]
I get the same problem some times.

**Comment by whyrusleeping** [comment]
If this happens again, could I get the following information:
- a copy of the ipfs binary you are running
- the entire output of `curl localhost:5001/debug/pprof/profile` (redirect it out to a file)
  - Note: this will hang for 30 seconds as it collects a cpu profile.

**Comment by EliasGabrielsson** [comment]
@whyrusleeping Sounds like a plan.
I will try to reproduce the bug tonight.

**Comment by EliasGabrielsson** [comment]
@whyrusleeping Error is reproduced.
binary, profiledump and log is zipped and uploaded to:
https://drive.google.com/open?id=0BzWfO7CwZ2RoRzlVdXBPSGotSTQ

**Comment by whyrusleeping** [comment]
@EliasGabrielsson Thanks! looking at it now.

If anyone feels like doing any investigation on their own, I wrote a short guide to debugging perf in go-ipfs here: https://github.com/ipfs/go-ipfs/issues/2594#issuecomment-212506980

**Comment by whyrusleeping** [comment]
@EliasGabrielsson after a cursory look over that information, It looks like you ran out of file descriptors. The cpu profile appears to by lying to me though, its telling me its spending most of its time in usleep, which is definitely incorrect. Could you try running `ulimit -n 4096` in your terminal before running `ipfs daemon` and see if the problem persists?

I also noticed from the system diagnostics info you provided that youre running ipfs from a git commit sha of `9890d28` which I can't seem to locate on my system. Are you running any patches on top of master?

**Comment by mythmon** [comment]
I think I'm having a similar problem. I get a very high amount of CPU usage sometimes. It might be related to putting my laptop to sleep.

Here is a copy of my `ipfs` binary, as well as the output of `curl localhost:5001/debug/pprof/profile`: https://ipfs.io/ipfs/QmW9CWvLse1puV4R8tXxMYVqUxhyyyFnHzXrq8KRDCv5JV/ipfs-debug.tar.gz

`ulimit` and `ulimit -f` both report "unlimited".

**Comment by whyrusleeping** [comment]
@mythmon `ulimit -n` is the important one. I'll take a look at your output too

**Comment by mythmon** [comment]
Ah. `ulimit -n` isn't mentioned in `man ulimit`. For me `ulimit -n` is 1024. I'll bump that up.

**Comment by mythmon** [comment]
I still run into this issue with `ulimit -n 4096` (well, technically setting that through Systemd, but it has the same effect).

**Comment by EliasGabrielsson** [comment]
@whyrusleeping 
a) New error report with `uname -n 4096`: http://ipfs.io/ipfs/QmVonCyUvnr4tfwKWs3YsBGmSfNUDJWnzYKkkxBoETPbJU
b) I where checking my commit log and could not find any patches on top of master. Anyway this new report is checked out from master and compiled directly.

**Comment by whyrusleeping** [comment]
@anacrolix you should take a look at this one. The latest profile from @EliasGabrielsson shows a large amount of activity and memory allocation from utp

**Comment by whyrusleeping** [comment]
it looks to me like this send call is failing: https://github.com/anacrolix/utp/blob/master/utp.go#L871

and then returning back up to `Write`, and `Write` appears to not check errors that `write` returns, so it loops infinitely creating a printing errors. Thats just a guess though, i'd have to repro locally to know for sure

**Comment by EliasGabrielsson** [comment]
I use to get error msg like these: `22:26:50.360 ERROR       mdns: mdns lookup error: failed to bind to any unicast udp port mdns.go:130` as well.

**Comment by anacrolix** [comment]
I'll take a look.

**Comment by anacrolix** [comment]
The ipfs-debug profile is very useful. Errors in the net.PacketConn that utp.Socket wraps are not propagated correctly. I'm adding tests for this. Presumably this occurs during wakeup after long sleeps, the connection is abandoned by the kernel, rather than the close being initiated by utp.Socket as I expected.

Regards file descriptor counts, if you're using utp with a single Socket, you should only ever see a single file descriptor in use (by utp). Be sure to use utp.Socket.Dial if this is a goal for you.

I'll address the other profile after I fix this first one.

**Comment by anacrolix** [comment]
It looks like the other profile provided is the same error. I've just pushed this fix on top of a huge cleanup on uTP, hopefully it's more approachable for others now. Thanks.

**Comment by whyrusleeping** [comment]
@EliasGabrielsson @mythmon if you guys could try out latest master, i've pushed the utp lib changes up into go-ipfs

**Comment by EliasGabrielsson** [comment]
@whyrusleeping sure thing. I will start a daemon and have my computer sleep at night and we see whats happening. I allmost reproduced the bug everytime so if its work I think we are green. Let's see the result in ~12h.

**Comment by anacrolix** [comment]
Damn, 4 hours to go.

**Comment by EliasGabrielsson** [comment]
@whyrusleeping @anacrolix 
Initial testing looks good.
* Running  `ipfs daemon`
* Computer sleep ~ 8h
* Working ~1.5h - **No problem**, use to "trigger" within 30 min ish
* Computer sleep ~ 1. 5h
* Working ~0.5h - **No problem**

### Summary
I think this is fixed. I have the daemon running and come back in a few days for final results.

**Comment by whyrusleeping** [comment]
thats really great to hear! Thanks @EliasGabrielsson for testing and @anacrolix for fixing :)

**Comment by EliasGabrielsson** [comment]
Solved.
