### ISSUE TITLE
`ipfs repo version` command

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#2571]
It would be really useful to have this work:

```
> cat ~/.ipfs/version
3
> ipfs repo version
ipfs repo version fs-repo@3
> ipfs repo version -q
fs-repo@3
```
because that way tools and applications can easily check the version of repos without making nasty assumptions.

---

may also be relevant to include this in the `ipfs repo stat` output:

```
> ipfs repo stat
NumObjects 	 288
RepoSize 	 6
RepoPath 	 /Users/jbenet/.ipfs
Version 	 fs-repo@3
```

**Comment by whyrusleeping** [comment]
`ipfs version --repo` accomplishes this. Although we could add an alias to this under the repo subcommand as you propose.

**Comment by RichardLitt** [comment]
Agreed adding it to `stat` would be good, and an alias.
