### ISSUE TITLE
large files question

### ISSUE THREAD

**Issue by icf20** [ipfs/go-ipfs#2575]
I have a question about the block part, if i take a 100MB video and add it into IPFS, then a person take that video and cut the file in half and add the file again, will duplicate the 50% of the blocks or will share the blocks ?

**Comment by Kubuxu** [comment]
Depends on encoding of video, there is good chance that some data might be deduped if underlaying binary format will be the same (no reencoding/recopression).

It also depends on chunker but there is room for improvment.

In future please place general questions about IPFS on https://github.com/ipfs/faq/issues

**Comment by icf20** [comment]
there are so many places where to post issues that is impossible to guess where, ipfs have 50 repos https://github.com/ipfs maybe you should pin one repo on top and name it "start here if you dont know what you want "
