### ISSUE TITLE
IPFS "disconnecting"

### ISSUE THREAD

**Issue by Zaijo** [ipfs/go-ipfs#2578]
From time to time, my list of peers turns empty. When I look into `ipfs daemon` log it says:

```
09:09:42.140 ERROR ipns-repub: Republisher failed to republish: failed to find any peer in table repub.go:72
```

This error occurs then roughly every 4 hours in my ipfs daemon. No peers appear in my `ipfs swarm peers`

Starting cause may be one of:
- moving to other network
- waking up from hibernation
  I don't know why it happens.

`ipfs version 0.4.0` On Mac 10.11.3

**Comment by whyrusleeping** [comment]
This could be caused by a few different issues. I know we've had trouble with resuming (switching networks and waking from sleep as you mention) lately, Try out the latest master (if youre comfortable building from source) or at least give 0.4.1 a try, it doesnt have some of the fixes i'm thinking of, but it should do better than 0.4.0 in that regard

**Comment by Stebalien** [comment]
@Zaijo are you still seeing this? I haven't seen an issue like this for a while.

**Comment by Zaijo** [comment]
It was more than a year ago. Thanks for asking. Honestly, I don't run IPFS on my machine these days. But I'm willing to give it a try if it would be of some help. Which version should I try? I'm running the same machine. It would be a nice experiment.

**Comment by Stebalien** [comment]
The latest release 0.4.13 would be fine. However, if you're willing to build from source, the latest master is probably the best choice; there are always shiny new fixes (no bugs, we have a rule against introducing new bugs).

Releases: https://dist.ipfs.io/#go-ipfs

**Comment by Zaijo** [comment]
Well. This particular issue seems to be fixed. Thanks.

**Comment by Stebalien** [comment]
Awesome. Thanks for testing! One down, 656 to go.
