### ISSUE TITLE
webui issue

### ISSUE THREAD

**Issue by leochan007** [ipfs/go-ipfs#2609]
when access via 5001/webui got this output:
 ERROR core/serve: Path Resolve error: no link named "webui-zh.json" under QmcnV8mXz9B4kuNEUymZ2mhqDLy2e76iMMk8SnmPDnxp6H gateway_handler.go:510

**Comment by RichardLitt** [comment]
@dignifiedquire, actually, is this the webui at fault here?

**Comment by dignifiedquire** [comment]
sounds like the package doesn't server/contain `webui-zh.json`

**Comment by TheNain38** [comment]
@dignifiedquire Same for french (e.g. "webui-fr.json")

**Comment by dignifiedquire** [comment]
You can see the list of supported locales here: https://github.com/ipfs/webui/tree/master/dist/locale if it's not in there it will fail (it will try for every locale and if it does not find it use the default english one)

**Comment by whyrusleeping** [comment]
any further discussion on this should go into the webui repo: https://github.com/ipfs/webui

**Comment by RichardLitt** [comment]
@dignifiedquire Want to open a new issue there?
