### ISSUE TITLE
Files API File Creation return value?

### ISSUE THREAD

**Issue by matthewrobertbell** [ipfs/go-ipfs#2610]
In my opinion, it'd be very useful for the file creation API call to return the multihash of the file that's been created. Why is this not the case?

Cheers

**Comment by whyrusleeping** [comment]
which api call are you talking about?

**Comment by mattseh** [comment]
"ipfs files write --create" equivalent, accessed over the HTTP interface.

**Comment by whyrusleeping** [comment]
A multihash isnt returned from that call because one isnt generated immediately on that write. You can call `ipfs files stat` on the path afterwards to get the hash, or use `ipfs add <file>` to get the hash, then `ipfs files cp <hash> <files api path>` to put it into place.

**Comment by Stebalien** [comment]
Closing in favor of #6326 (which calls for a flag instead of doing this by default).
