### ISSUE TITLE
`ipfs config id <arg>` accepts invalid parameter

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2616]
```
13:06 ~/src/http-api-spec (master) * 🐕  ipfs config id kitten
13:06 ~/src/http-api-spec (master) * 🐕  ipfs config show | grep kitten
  "id": "kitten"
```

I don't think this should be the case. It used to show an error: `"Message": "routing: not found"`. What changed?

**Comment by whyrusleeping** [comment]
`ipfs config` would never return a routing not found. although `ipfs id` might.

**Comment by RichardLitt** [comment]
A-ha! Was a bug in my HTTP request - `config` snuck in where it shouldn't've. Thanks.
