### ISSUE TITLE
`ipfs name resolve <arg>` example doesn't resolve

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2617]
```    
> ipfs name resolve --help
....
Resolve the value of your identity:
    
      > ipfs name resolve
      QmatmE9msSfkKxoffpHwNLNKgwZG8eT9Bud6YoPab52vpy
    
    Resolve the value of another name:
    
      > ipfs name resolve QmbCMUZw6JFeZ7Wp9jkzbye3Fzp2GGcPgC3nmeUjfVF87n
      QmatmE9msSfkKxoffpHwNLNKgwZG8eT9Bud6YoPab52vpy
```

The first hash is different, when run, which is expected - it is my key. The second, though, doesn't resolve. Can we use a persistent hash that will always resolve in the help docs?

**Comment by thomas-gardner** [comment]
Here are a couple candidates (ordered by preference):

	$ ipfs name resolve ipfs.git.sexy
	/ipfs/QmVyS3iAy7mvDA2HqQWm2aqZDcGDH3bCRLFkEutfBWNBqN

	$ ipfs name resolve ipfs.io
	/ipfs/QmaBvfZooxWkrv7D3r8LS9moNjzD2o525XMZze69hhoxf5

**Comment by RichardLitt** [comment]
Should we be using a non-hash in the example? I feel like that should be a second example, here.

**Comment by whyrusleeping** [comment]
you can use mars: QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
