### ISSUE TITLE
vm running issue

### ISSUE THREAD

**Issue by leochan007** [ipfs/go-ipfs#2623]
when i run ipfs daemon in a vm (linux)  i  add port forward 4001 5001 8080

i can only access webui's webpage but there was no content(node info etc.) showed.

**Comment by leochan007** [comment]
if i access ipfs webui via vm ipaddr it won't show anything.but if i access ipfs webui via 127.0.0.1 from host with port forward . it would be ok.

**Comment by whyrusleeping** [comment]
You will have to change the listener address for the API in your ipfs config to not listen on just `127.0.0.1`, and then set up CORS headers as shown in `ipfs daemon --help`.

Let us know if you have any other issues or that doesn't work for you.
