### ISSUE TITLE
'ipfs swarm peers' should print more info

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2629]
I think it would be pretty helpful to have ipfs swarm peers have a verbose option that allows it to print out latency to each peer and also potentially 'last contact' with each peer.

**Comment by csasarak** [comment]
I am interested in getting involved with this project, if you think this is a good place for a new person to get involved I could help.

**Comment by Kubuxu** [comment]
It should be quite easy to do. I would encourage you to try.

A lot of issues are tagged with difficulty.

**Comment by csasarak** [comment]
Sounds good, I'll have a go.

**Comment by Kubuxu** [comment]
Resolved by #2713
