### ISSUE TITLE
Check for gx and gxgo versions automatically

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2635]
I just tried to update `go-ipfs`. 

```
17:10 ~/src/go-ipfs (master) 🐕  make build && make install
fatal: gx version '0.3.0' should be at least '0.6'
=> Upgrade or install gx using your package manager or run `make gx_upgrade`
make: *** [gx_check] Error 1
17:10 ~/src/go-ipfs (master) 🐕  make gx_upgrade
go get -u github.com/whyrusleeping/gx
17:10 ~/src/go-ipfs (master) 🐕  make build && make install
fatal: gx-go version '0.2.0' should be at least '1.1'
=> Upgrade or install gx-go using your package manager or run `make gxgo_upgrade`
make: *** [gx_check] Error 1
17:11 ~/src/go-ipfs (master) 🐕  make gxgo_upgrade
go get -u github.com/whyrusleeping/gx-go
17:11 ~/src/go-ipfs (master) 🐕  make build && make install
gx --verbose install --global
installing package: go-ipfs-0.4.0
```

`gx_upgrade` and `gxgo_upgrade` should have happened automatically, I think.

**Comment by chriscool** [comment]
What if the user doesn't want to upgrade because some other stuff depends on old versions?

**Comment by chriscool** [comment]
Before we came up with the current solution there was an automatic upgrade and some people complained about that.

What we could do though is ask "Do you want to upgrade [y/N]?:", but this must be done carefully because `make build` could be run non interactively...

**Comment by RichardLitt** [comment]
That's a fair point. It just confused me why this came up, it's something I would expect to work.

**Comment by chriscool** [comment]
Downloading our own versions of the tools might be a bit wasteful when many programs are doing that.
If iptb needs gx and gx-go too, will it have to also download its own version, and what about fs-repo-migrations, ipif-update, and so on?

**Comment by RichardLitt** [comment]
I also think that the copy should be changed. I've just tried to update IPFS on a second machine, and I got the comments above. However, I don't know how to install gx, or how to install gx-go. `go get gx` doesn't work, and I'm not sure how to find out where `gx` is without googling. 

Should we point the user to the install docs?

**Comment by chriscool** [comment]
The current error message contains the following:

=> Upgrade or install gx using your package manager or run `make gx_upgrade`
=> Upgrade or install gx-go using your package manager or run `make gxgo_upgrade`

@RichardLitt did you try `make gx_upgrade` and `make gxgo_upgrade`?

Maybe it would be more straightforward if we suggested using make first.

**Comment by RichardLitt** [comment]
I tried both of those; I had issues with a conflict in gxgo_upgrade which meant i had to go manually run `git reset --hard` to make it work.

**Comment by whyrusleeping** [comment]
this should be resolved now. the build process grabs its own specific versions of gx and gx-go
