### ISSUE TITLE
Go 1.6 support

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2640]
Arch uses Go in version 1.6 it would be nice to be able to compile on it.

**Comment by dignifiedquire** [comment]
What issues are you seeing? I've been compiling and running with 1.6 for weeks now (not on arch though)

**Comment by Kubuxu** [comment]
It is just locked by Makefile, isn't it?

**Comment by whyrusleeping** [comment]
@Kubuxu we had some issues in the past, but they have since been resolved
