### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2641]
Version: `ipfs version 0.4.1-dev-daaa69e`
This could be fixed but I am unable to upgrade as for #2640

https://gist.github.com/Kubuxu/25ea85b995c3f39d4f277bd3c426ef1a

I have NTP enabled.

**Comment by Kubuxu** [comment]
I've upgraded to newest version, will report back if crashes still happen.

**Comment by whyrusleeping** [comment]
Thats bizarre... i've never seen that sort of panic before. What system are you running on?

**Comment by Kubuxu** [comment]
Arch Linux
```
Linux n1.kubuxu.ovh 4.5.3-1-ck #1 SMP PREEMPT Sun May 8 23:53:20 CEST 2016 x86_64 GNU/Linux
```

**Comment by Kubuxu** [comment]
Still happens on the newest version from git.

**Comment by whyrusleeping** [comment]
@Kubuxu could you set `GOTRACEBACK` to `crash` and try to repro?

**Comment by whyrusleeping** [comment]
I'm thinking it might be an issue with the bfs scheduler youre using... but i'm not too certain. (its the only difference in our machines)

**Comment by Kubuxu** [comment]
It is possible as `ck` patchset is not that popular among people.

**Comment by Kubuxu** [comment]
Seems like upgrade to newest version fixed it. I will reopen it if it shows up again.
