### ISSUE TITLE
processing power

### ISSUE THREAD

**Issue by Mithgol** [ipfs/go-ipfs#2642]
I've noticed that the Windows build of IPFS version 0.4.1 (or also the previous 0.4.0) that runs on my computer as `ipfs daemon` eventually takes 25% of its full processing power (one of four i7-3770 cores). After shutdown and restart of the daemon everything's fine for an hour (or a half) but then it gradually returns to those 25%. That never happened before May 2016.

Either something's wrong with 0.4.x (I haven't tried downgrading to 0.3.x because of the changes in protocols that would separate me from the new network) or the sheer number of nodes in the network has recently grown enough to put that strain on an individual node.

**Comment by falsechicken** [comment]
I have noticed a leap in performance requirements too. After not using IPFS for a while (0.3.x) I decided to give 0.4 a shot last night. Got the latest release build and initialized a new repo. When trying to use the node to view pictures on ipfs.pics it seemed to trash my CPU and never load the image (About 7 minutes of waiting). Now this was tested on my low power atom (hyperthreaded) netbook so its definitely on the slow side but I do know that 0.3.x worked aright. Ill try again with my desktop at some point.

**Comment by whyrusleeping** [comment]
Most of the CPU consumption i've noticed since 0.4.0 has been from utp. A patch for utp to help address those issues was merged after 0.4.1, if you guys want to try out latest master and see if the cpu usage is better that would be very helpful

**Comment by falsechicken** [comment]
Roger that. I'll try it out if I get some time in a few hours.

**Comment by falsechicken** [comment]
Latest master seems to work fine for me.

**Comment by whyrusleeping** [comment]
@falsechicken awesome to hear. It must have been the utp issue.

**Comment by Mithgol** [comment]
Are there any pre-built `ipfs.exe` of the latest master for Windows? (Because I'm not sure if I'm ready to build one for myself. And because [https://ipfs.io/ipns/dist.ipfs.io#go-ipfs](https://ipfs.io/ipns/dist.ipfs.io#go-ipfs) seems to provide only versioned distributions, not master.)

**Comment by falsechicken** [comment]
@Mithgol If not I can build you some periodically. Not an ideal solution for anyone but I am willing to cross build you one sometimes. My email is on my Github profile.

**Comment by Mithgol** [comment]
Thanks.

I've thought a bit more about it and decided to wait until 0.4.2 (or 0.5.0, if the next version is a new minor). It would probably be more stable than a master build.

**Comment by Mithgol** [comment]
This issue is fixed in version 0.4.2 (as far as I can tell).
