### ISSUE TITLE
ipfs daemon Crash Out of Memory Error

### ISSUE THREAD

**Issue by cchrysostom** [ipfs/go-ipfs#2645]
This morning a node running 0.4.1 crashed with the following log output. I need help diagnosing what happened. It may also be useful to you.

https://gist.github.com/cchrysostom/311d372a3d843947ad560bbbc4cef788

Thanks.

**Comment by whyrusleeping** [comment]
looks like a plain and simple out of memory issue. Are you running the binary from the dists.ipfs.io page? also what OS and how much RAM does your machine have?

**Comment by cchrysostom** [comment]
It is a Digital Ocean droplet. Memory looks like:

MemTotal:        1017872 kB

**Comment by gsf** [comment]
I've been hitting the memory ceiling on my VPS too. Hopefully helped by work on issues like #2847.

**Comment by whyrusleeping** [comment]
Yeah, #2847 should help significantly towards this. Its likely going to merge today

**Comment by cchrysostom** [comment]
Great, thank you. I'll keep my eyes open for the merge. Our solution was to move ipfs to a system with a lot more memory.

**Comment by whyrusleeping** [comment]
@cchrysostom give it another try. I merged in the PR that helps out memory usage

**Comment by whyrusleeping** [comment]
Since then we have pushed a few other PRs improving memory usage. Its not perfect yet, but i think its good enough that we can close this one out.
