### ISSUE TITLE
ipfs config edit `ENV variable $EDITOR not set` when set

### ISSUE THREAD

**Issue by scriptjs** [ipfs/go-ipfs#2649]
ipfs config edit cannot find $EDITOR on OSX

```
$ ipfs config edit
Error: ENV variable $EDITOR not set
$ echo $EDITOR
vi
```

**Comment by lgierth** [comment]
Ugh how annoying -- could you try `export EDITOR=$EDITOR` before running ipfs config edit?

**Comment by scriptjs** [comment]
@lgierth Hi there. Result is same

**Comment by patientplatypus** [comment]
This issue should not be closed! We are having the same issue. MUCH SADNESS

**Comment by Kubuxu** [comment]
@patientplatypus this is regression that was introduced, please report a new issue.

**Comment by kneekey23** [comment]
Did anyone solve this or a workaround?

**Comment by postables** [comment]
if you add `export EDITOR=$(which vim)` into your bashrc file or other similar profile file then you won't have to do it every time. the ENV VAR will be available everytime you start a shell.

**Comment by kneekey23** [comment]
yup just did that, worked. THANK YOU!

**Comment by kneekey23** [comment]
yup just did that, worked. THANK YOU!

**Comment by kneekey23** [comment]
yup just did that, worked. THANK YOU!

**Comment by Kubuxu** [comment]
Can someone of you report it in a separate issue, please?

**Comment by meteorplus** [comment]
better export EDITOR=$(which nano)

not a big fan of vim :p

**Comment by Stebalien** [comment]
You don't have `vim` installed. You'll need to either install `vim` or set a different editor.

**Comment by meteorplus** [comment]
@Stebalien everyone hates VIM

**Comment by whyrusleeping** [comment]
Yeah, vim sucks. Use neovim.
