### ISSUE TITLE
Move `ipfs repo stat` to `ipfs stats repo`

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2680]
I think that `ipfs repo stat` would be more appropriate under the `ipfs stats` header.

**Comment by whyrusleeping** [comment]
i think the case could be made to have it be both place, as an alias for the same command

**Comment by RichardLitt** [comment]
Agreed. Are there other aliases I could look at in the code, to see how to implement a PR myself?

**Comment by RichardLitt** [comment]
Same goes for:

```
ipfs bitswap stat
ipfs block stat
ipfs files stat
ipfs object stat
```
