### ISSUE TITLE
killing CLI commands prints ugly error message

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2686]
Killing a cli command cancels the context which throws us an error for that clientside:

```
10:16:56.988 ERROR commands/h: net/http: request canceled client.go:247
```

We should avoid doing that, the user cancelled it, they know its being cancelled

**Comment by Kubuxu** [comment]
I can't reproduce it. Which command you've used.

**Comment by whyrusleeping** [comment]
try: `ipfs ping QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ` or `ipfs stats bw --poll`

**Comment by Stebalien** [comment]
Now it just prints "Error: canceled".
