### ISSUE TITLE
Set LongDescription to ShortDescription if no LongDescription

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2691]
This came up here: https://github.com/ipfs/go-ipfs/pull/2681#discussion_r63260096. Right now, if there is no long description, we just copy the short one. This is redundant. We should set it so that if there is no extra information for long description, just copy the short one and use that.

**Comment by Kubuxu** [comment]
I will take it.

**Comment by RichardLitt** [comment]
Thanks, @Kubuxu!
