### ISSUE TITLE
Documentaion for logging?

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#2692]
Is the IPFS_LOGGING and IPFS_LOGGING_FMT variables documented anywhere?  It took me a while to discover how they work.  It doesn't help that the code for this is in a external module.

**Comment by kevina** [comment]
So as best as I can tell, `IPFS_LOGGING` is one of: `debug`, `info`, `notice`, `warning`, `error`, `critical`.  `IPFS_LOGGING_FMT` is one of: `color`, `no color`.

Is there anything I am missing.  It is possible to control the logging of the individual subsystems via the `IPFS_LOGGING` variable like you can with `ipfs log level <subsystem> <level>`.

I think this documentation of these environmental variables should go under the help for `ipfs log`.  The documentation should also make clear that `ipfs log tail` is a different type of log and is not controlled via `ipfs log level`.  It should also make it clear what `ipfs log level` does control.

**Comment by Stebalien** [comment]
Documented in #6268.
