### ISSUE TITLE
Repeated connection attempts to localhost instead of local network?

### ISSUE THREAD

**Issue by interfect** [ipfs/go-ipfs#2700]
My IPFS 0.4.0 on Ubuntu 16.04 keeps trying to connect to one particular peer on 127.0.0.1:

```
19:29:06.814 WARNI       core: trying peer info: {<peer.ID ZhmndN> [/ip4/127.0.0.1/tcp/4001]} core.go:200
```

That's not going to work; that peer _is_ on my local network, but it ought to be dialing it as `/ip4/10.1.0.2/tcp/4001/ipfs/QmZhmndNASacWAvP3ktoBxq2zWiD5nSuowwzYvsmK1dkrG`. And really, it oughtn't to be dialing it at all, because it has an incoming connection from it on the peers list.

Does IPFS just keep dialing peers it already has connections to?

**Comment by whyrusleeping** [comment]
This should be resolved now
