### ISSUE TITLE
t0022-init-default fails if a daemon is running

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2703]

**Comment by whyrusleeping** [comment]
https://circleci.com/gh/ipfs/go-ipfs/3889

**Comment by whyrusleeping** [comment]
https://travis-ci.org/ipfs/go-ipfs/jobs/141925539

**Comment by whyrusleeping** [comment]
can someone verify if this is still a problem?

**Comment by Stebalien** [comment]
It doesn't appear to be.
