### ISSUE TITLE
0.4.1 Crashing Regularly

### ISSUE THREAD

**Issue by wkennington** [ipfs/go-ipfs#2708]
-- Logs begin at Thu 2016-03-24 05:59:28 PDT, end at Mon 2016-05-16 16:03:11 PDT. --
May 11 19:50:22 page ipfs[1225]: Initializing daemon...
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/10.2.0.32/tcp/4001
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/10.2.0.32/udp/4001/utp
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/10.2.1.32/tcp/4001
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/10.2.1.32/udp/4001/utp
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/10.2.2.32/tcp/4001
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/10.2.2.32/udp/4001/utp
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/10.2.5.32/tcp/4001
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/10.2.5.32/udp/4001/utp
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/127.0.0.1/tcp/4001
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/127.0.0.1/udp/4001/utp
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/192.168.17.9/tcp/4001
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/192.168.17.9/udp/4001/utp
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/65.19.134.243/tcp/4001
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip4/65.19.134.243/udp/4001/utp
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip6/2001:470:1:572::4/tcp/4001
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip6/2001:470:1:572::4/udp/4001/utp
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip6/::1/tcp/4001
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip6/::1/udp/4001/utp
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip6/fda4:941a:81b5:1000::32/tcp/4001
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip6/fda4:941a:81b5:1000::32/udp/4001/utp
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip6/fda4:941a:81b5:1001::32/tcp/4001
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip6/fda4:941a:81b5:1001::32/udp/4001/utp
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip6/fda4:941a:81b5:1002::32/tcp/4001
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip6/fda4:941a:81b5:1002::32/udp/4001/utp
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip6/fda4:941a:81b5:1005::32/tcp/4001
May 11 19:50:32 page ipfs[1225]: Swarm listening on /ip6/fda4:941a:81b5:1005::32/udp/4001/utp
May 11 19:50:32 page ipfs[1225]: API server listening on /ip4/127.0.0.1/tcp/5001
May 11 19:50:32 page ipfs[1225]: Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8001
May 11 19:50:32 page ipfs[1225]: Daemon is ready
May 12 03:18:48 page ipfs[1225]: 03:18:48.250 ERROR        dht: no addresses on peer being sent!
May 12 03:18:48 page ipfs[1225]:                                         [local:<peer.ID amrdGn>]
May 12 03:18:48 page ipfs[1225]:                                         [sending:<peer.ID Sa79r6>]
May 12 03:18:48 page ipfs[1225]:                                         [remote:<peer.ID Z86ow1>] handlers.go:73
May 12 06:11:16 page ipfs[1225]: 06:11:16.036 ERROR        dht: no addresses on peer being sent!
May 12 06:11:16 page ipfs[1225]:                                         [local:<peer.ID amrdGn>]
May 12 06:11:16 page ipfs[1225]:                                         [sending:<peer.ID bZ3eMn>]
May 12 06:11:16 page ipfs[1225]:                                         [remote:<peer.ID SoLju6>] handlers.go:73
May 14 17:42:12 page ipfs[1225]: 17:42:12.697 ERROR        dht: no addresses on peer being sent!
May 14 17:42:12 page ipfs[1225]:                                         [local:<peer.ID amrdGn>]
May 14 17:42:12 page ipfs[1225]:                                         [sending:<peer.ID deUCdN>]
May 14 17:42:12 page ipfs[1225]:                                         [remote:<peer.ID Z86ow1>] handlers.go:73
May 14 17:44:29 page ipfs[1225]: 17:44:29.079 ERROR        dht: no addresses on peer being sent!
May 14 17:44:29 page ipfs[1225]:                                         [local:<peer.ID amrdGn>]
May 14 17:44:29 page ipfs[1225]:                                         [sending:<peer.ID deUCdN>]
May 14 17:44:29 page ipfs[1225]:                                         [remote:<peer.ID Z86ow1>] handlers.go:73
May 14 17:51:30 page ipfs[1225]: 17:51:30.371 ERROR        dht: no addresses on peer being sent!
May 14 17:51:30 page ipfs[1225]:                                         [local:<peer.ID amrdGn>]
May 14 17:51:30 page ipfs[1225]:                                         [sending:<peer.ID deUCdN>]
May 14 17:51:30 page ipfs[1225]:                                         [remote:<peer.ID Z86ow1>] handlers.go:73
May 16 15:24:09 page ipfs[1225]: panic: runtime error: invalid memory address or nil pointer dereference
May 16 15:24:09 page ipfs[1225]: [signal 0xb code=0x1 addr=0x48 pc=0x5f9ec2]
May 16 15:24:09 page ipfs[1225]: goroutine 1075072567 [running]:
May 16 15:24:09 page ipfs[1225]: panic(0xe02c20, 0xc82000e0a0)
May 16 15:24:09 page ipfs[1225]:         /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.6.2/share/go/src/runtime/panic.go:481 +0x3e6
May 16 15:24:09 page ipfs[1225]: gx/ipfs/QmZwZjMVGss5rqYsJVGy18gNbkTJffFyq2x1uJ4e4p3ZAt/go-libp2p-peer.(*AddrManager).AddAddrs(0xc820224048, 0xc8ae8974a0, 0x22, 0xc8bfb1e200, 0x8, 0x8, 0x8bb2c97000)
May 16 15:24:09 page ipfs[1225]:         /tmp/nix-build-go1.6-go-ipfs-v0.4.1.drv-0/go/src/gx/ipfs/QmZwZjMVGss5rqYsJVGy18gNbkTJffFyq2x1uJ4e4p3ZAt/go-libp2p-peer/addr_manager.go:107 +0x352
May 16 15:24:09 page ipfs[1225]: github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).handleAddProvider(0xc82071e8c0, 0x7f6134820e28, 0xc8202eec40, 0xc8e2dd88a0, 0x22, 0xc888f65340, 0x0, 0x0, 0x0)
May 16 15:24:09 page ipfs[1225]:         /tmp/nix-build-go1.6-go-ipfs-v0.4.1.drv-0/go/src/github.com/ipfs/go-ipfs/routing/dht/handlers.go:279 +0xc6a
May 16 15:24:09 page ipfs[1225]: github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).(github.com/ipfs/go-ipfs/routing/dht.handleAddProvider)-fm(0x7f6134820e28, 0xc8202eec40, 0xc8e2dd88a0, 0x22, 0xc888f65340, 0xc888f65340, 0x0, 0x0)
May 16 15:24:09 page ipfs[1225]:         /tmp/nix-build-go1.6-go-ipfs-v0.4.1.drv-0/go/src/github.com/ipfs/go-ipfs/routing/dht/handlers.go:33 +0x6a
May 16 15:24:09 page ipfs[1225]: github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).handleNewMessage(0xc82071e8c0, 0x7f613084bf78, 0xc8b2964f80)
May 16 15:24:09 page ipfs[1225]:         /tmp/nix-build-go1.6-go-ipfs-v0.4.1.drv-0/go/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:48 +0xa5a
May 16 15:24:09 page ipfs[1225]: created by github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).handleNewStream
May 16 15:24:09 page ipfs[1225]:         /tmp/nix-build-go1.6-go-ipfs-v0.4.1.drv-0/go/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:17 +0x49
May 16 15:24:09 page systemd[1]: ipfs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 16 15:24:09 page systemd[1]: ipfs.service: Unit entered failed state.
May 16 15:24:09 page systemd[1]: ipfs.service: Failed with result 'exit-code'.

**Comment by whyrusleeping** [comment]
@wkennington is this the 0.4.1 release? or are you building a later master build?

**Comment by whyrusleeping** [comment]
@wkennington found the issue, thanks for reporting!

**Comment by wkennington** [comment]
I'll reopen if this is still broken
