### ISSUE TITLE
Migrating away from Godeps

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2722]
Many packages in Godeps are our own (ipfs, whyrusleeping) so we should easily be able to push the to gx, others are external but we also can push them to gx.

Question is: do we want to do that, if yes what should be the time frame as it will be quite a bit of work. There are, as for today, 54 packages in Godeps.

**Comment by Kubuxu** [comment]
Dependencies still inside Godpes:
* [ ] bazil.org/fuse
* [ ] bitbucket.org/ww/goautoneg
* [ ] github.com/bren2010/proquint
* [ ] github.com/briantigerchow/pubsub
* [ ] github.com/camlistore/lock
* [ ] github.com/cenkalti/backoff
* [ ] github.com/cheggaaa/pb
* [ ] github.com/codahale/hdrhistogram
* [ ] github.com/codahale/metrics
* [ ] github.com/cryptix/mdns
* [ ] github.com/docker/spdystream
* [ ] github.com/dustin/go-humanize
* [ ] github.com/dustin/randbo
* [ ] github.com/facebookgo/atomicfile
* [ ] github.com/gogo/protobuf/io
* [ ] github.com/gogo/protobuf/proto
* [ ] github.com/hashicorp/golang-lru
* [ ] github.com/ipfs/go-datastore
* [ ] github.com/jbenet/go-base58
* [ ] github.com/jbenet/go-context/frac
* [ ] github.com/jbenet/go-context/io
* [ ] github.com/jbenet/go-detect-race
* [ ] github.com/jbenet/go-fuse-version
* [ ] github.com/jbenet/go-is-domain
* [ ] github.com/jbenet/go-msgio
* [ ] github.com/jbenet/go-multiaddr
* [ ] github.com/jbenet/go-multiaddr-net
* [ ] github.com/jbenet/go-multihash
* [ ] github.com/jbenet/go-os-rename
* [ ] github.com/jbenet/go-peerstream
* [ ] github.com/jbenet/go-random
* [ ] github.com/jbenet/go-random-files
* [ ] github.com/matttproud/golang_protobuf_extensions/pbutil
* [ ] github.com/mitchellh/go-homedir
* [ ] github.com/mtchavez/jenkins
* [ ] github.com/olekukonko/ts
* [ ] github.com/rs/cors
* [ ] github.com/satori/go.uuid
* [ ] github.com/steakknife/hamming
* [ ] github.com/syndtr/goleveldb/leveldb
* [ ] github.com/syndtr/gosnappy/snappy
* [ ] github.com/texttheater/golang-levenshtein/levenshtein
* [ ] github.com/whyrusleeping/chunker
* [ ] github.com/whyrusleeping/go-logging
* [ ] github.com/whyrusleeping/go-metrics
* [ ] github.com/whyrusleeping/go-sysinfo
* [ ] github.com/whyrusleeping/multiaddr-filter
* [ ] golang.org/x/crypto/blowfish
* [ ] golang.org/x/crypto/sha3
* [ ] golang.org/x/net/context
* [ ] golang.org/x/net/internal/iana
* [ ] golang.org/x/net/ipv4
* [ ] golang.org/x/net/ipv6
* [ ] gopkg.in/fsnotify.v1

**Comment by kevina** [comment]
Note: Migrating `github.com/ipfs/go-datastore` will cause me some grief with pull request #2634.

**Comment by Kubuxu** [comment]
`github.com/ipfs/go-datastore` has quite a lot of godeps and deps on its own so it will take a while.

**Comment by kalmi** [comment]
`gx install` is now broken on Windows when ipfs's source's root is somewhat deeply nested. For example this is too deep: C:\Projects\Go\src\github.com\ipfs\go-ipfs

https://github.com/whyrusleeping/gx/issues/80

**Comment by zramsay** [comment]
Happy to pick this up (Godeps yuck). Started with PR ^
