### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2725]
https://gist.github.com/Kubuxu/0003dd409debaa21d98384a27e190867

While playing with `object patch set-link`, but I don't think it is connected.

I am running newest master.

**Comment by Kubuxu** [comment]
Same crash: https://gist.github.com/Kubuxu/9e76975347c0da1fc4333d5e98f0dbdc

**Comment by Kubuxu** [comment]
Looks like the error is triggered by deferred call to `timer.Stop()` in the `waitForSendErr` function of yamux.

**Comment by Kubuxu** [comment]
I am building package with debugging symbols this time.

**Comment by whyrusleeping** [comment]
Hrm... the yamux fixes i made got modified and merged upstream. I'll work on pulling those in

**Comment by Kubuxu** [comment]
It might have been either random crash or go incompatibility with ck patchset, I haven't seen this crash in a while.
