### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2740]
Might be connected with: https://github.com/golang/go/issues/15436

**Comment by RichardLitt** [comment]
Can you describe what you were doing that caused it to crash? This is really hard to replicate.

**Comment by Kubuxu** [comment]
Nothing, I was adding package to gx and it just died. That why I called it random.


I forgot to include the crash log: https://gist.github.com/Kubuxu/d8c2948cc84e338c4530328bdfe5343a

**Comment by Kubuxu** [comment]
And again: http://hastebin.com/eluyuwahif

**Comment by Kubuxu** [comment]
I think it was connected with -ck patchset.
