### ISSUE TITLE
Meta: Label tracking issues

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2742]
The issue https://github.com/ipfs/go-ipfs/issues/2738, "js-ipfs compatability blockers", is a planning issue. It has a few things that need to be done, and can be used as a reference for the topic it opens. To quote: 

> currently js-ipfs and go-ipfs cant quite communicate properly. This will be a log of existing issues that need to be resolved/worked around.

While all issues are, to some extent, like this, I think that issues like this  - and other issues, like the IPNS discussion issues - should be labelled as 'Tracking' issues, to make it clear that they are issues to be described to and which will depend on many other issues to close. What do you think?

**Comment by Kubuxu** [comment]
@whyrusleeping let's just do it?

**Comment by whyrusleeping** [comment]
yeap, this SGTM, go ahead and do it
