### ISSUE TITLE
TestBootstrap fails occasionally 

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2745]
http://ci.ipfs.team:8111/viewLog.html?buildId=2045&buildTypeId=GoIpfs_CiTests&tab=buildLog#_focus=4136&state=4136

More here: https://github.com/ipfs/go-ipfs/issues/188

**Comment by whyrusleeping** [comment]
i hate this one. Its the 'misdial' issue, it affects a few different tests.

**Comment by whyrusleeping** [comment]
https://circleci.com/gh/ipfs/go-ipfs/4055

**Comment by Kubuxu** [comment]
My sanity tests caught it: https://travis-ci.org/ipfs/go-ipfs/jobs/136932615#L3812

**Comment by Kubuxu** [comment]
I am able to replicate failure in less than a minute:
```
cd routing dht
while time go test -run TestBootstrap; do; done
```
Looks like failure about one in five.

**Comment by whyrusleeping** [comment]
https://travis-ci.org/ipfs/go-ipfs/jobs/137017648 heres another one

**Comment by Kubuxu** [comment]
It think I figured out what is happening, the SO_REUSE_PORT flag on a socket makes it possible for socket `127.0.0.1:0` to randomise to the same address. I am running now tests on my server with ` IPFS_REUSEPORT=false` env variable. If I am sure that it is the solution (no failure for few hours) I will work on a solution.

**Comment by Kubuxu** [comment]
I found it pretty interesting that it is a problem but it makes sense, it is birthday paradox with calendar not of 365 days but 2^16. As it turns out for 10% failure rate binding 140 addresses is enough: https://www.wolframalpha.com/input/?i=y%3D+1+-+(((2%5E16)+nPr+n+)%2F(2%5E16)%5En)++from+0+to+200

I still will wait few hours to confirm that issues is gone.
