### ISSUE TITLE
ipfs init fails with no stdin

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2748]
`echo "" | ipfs init` reproduces the issue. This is a problem if i want to run `ipfs init` in a docker container. (although passing `-t` is a workaround)

**Comment by whyrusleeping** [comment]
This appears to be a problem with most commands actually

**Comment by lgierth** [comment]
Likely introduced in #2581, we fixed a similar thing in #1263.

**Comment by Kubuxu** [comment]
I can look into fixing it tomorrow.

**Comment by Kubuxu** [comment]
Resolved in #2749

**Comment by lgierth** [comment]
Well this hasn't exactly been resolved... we just reverted the commit.

**Comment by dignifiedquire** [comment]
This is a real problem for us, ipfsd-ctl the module to control a go daemon from node.js is not able to work with 0.4.2 because of this bug.

**Comment by lgierth** [comment]
hey @sivachandran, would be great to get this fixed for  0.4.3!
