### ISSUE TITLE
Lost readme link?

### ISSUE THREAD

**Issue by MasterJames** [ipfs/go-ipfs#2767]
After I use ipfs init and it displays the link to the readme etc.
How do you find that number again later?
it doesn't seem to be in the config show? Try my peer id (whihc is what I thought it was but isn't) says...
`Error: merkledag: not found`
of course.
I hunted around in .ipfs but didn't discover anything obvious there.
on Windows 8.1 with Go version.

**Comment by MasterJames** [comment]
I guess you have to store it yourself but it's a hash of the data so it's the same for everybody which has an advantage of data duplication I suppose. 
/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG
Or is mine different/unique each time?

**Comment by RichardLitt** [comment]
It's not unique.

```
to get started, enter:

	ipfs cat /ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme
```

You can also access this from the gateway, here: https://ipfs.io/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/
