### ISSUE TITLE
init --force flag does nothing

### ISSUE THREAD

**Issue by MasterJames** [ipfs/go-ipfs#2768]
After the first run of ipfs init the second run says no dice as expected, but running it with either of the force flags does nothing.
`Error: Unrecognized option 'force'`

[Running on Windows 8.1 current go-ipfs version]

**Comment by lgierth** [comment]
`--force` has been removed in 0.4.2 -- I think we need to update the command reference on the website, using `ipfs commands` as input. @MasterJames wanna give it a try in https://github.com/ipfs/website?

**Comment by NatoBoram** [comment]
Is there any plans to add similar functionality?

What's the alternative if we need to generate a new identity?

**Comment by Stebalien** [comment]
Not at the moment. Please file a feature request, this seems reasonable.
