### ISSUE TITLE
create issue template 

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2770]
Lets make an issue template for go-ipfs issues and move towards having issues filed here being solely bugs and directly actionable things. All others should be directed to ipfs/support or ipfs/faq

**Comment by Kubuxu** [comment]
Or ipfs/notes for ideas.

**Comment by chriscool** [comment]
So where should issue go? :-)

Ok, as it is actionable, it could probably stay here. But to be really actionable, we should probably state what we want in the issue template.
 
I suggest we ask for the commit version (from `ipfs version --commit`) and a way to reproduce the problem. Maybe we could ask for the repo version (from `ipfs version --repo`) too?
What else?

**Comment by whyrusleeping** [comment]
I think also asking for operating system and platform would be good info to have as well. There are a lot of issues where it would have saved a lot of time to know that the user was on windows the whole time.

**Comment by chriscool** [comment]
Yeah sure!

**Comment by whyrusleeping** [comment]
relevant info: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by whyrusleeping** [comment]
we now have an issue template!
