### ISSUE TITLE
Slow ipfs connection due to tcp/utp incongruence

### ISSUE THREAD

**Issue by C0DEHERO** [ipfs/go-ipfs#2771]
So, I tried accessing an mp3 file I added in ipfs over the gateway, but it didn't work. After @whyrusleeping accessed the file, the gateway followed suit, so I suppose the gateway retrieved the file from whyrusleeping's node because it couldn't connect to mine.

Now, whyrusleeping informed me that it took long to connect to my node, and that other nodes were apparently trying to connect to me via utp even though I don't have utp enabled.

ipfs version 0.4.2

OS: ArchLinux on newest updates. Stock kernel x86_64 Linux 4.5.4-1-ARCH. If it matters, the only changes I did to the setup network wise (except for the usual wifi stuff) was install and enable unbound.

output of `ipfs config Addresses`:

{
  "API": "/ip4/127.0.0.1/tcp/5001",
  "Gateway": "/ip4/127.0.0.1/tcp/8080",
  "Swarm": [
    "/ip4/0.0.0.0/tcp/4001",
    "/ip6/::/tcp/4001"
  ]
}

**Comment by whyrusleeping** [comment]
an ipfs dht findpeer shows a large number of utp addresses for your peer. I Think that the cause of this is our assumption that if you dial someone on a given transport, that you have a listener for that transport. I'll work this into libp2p soon and report back when its fixed.
