### ISSUE TITLE
Separate sharness tests for reported bugs and regressions

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2774]
Some of tests fit currently named types but some of the would be too specific or too weird to fit in already named kind. What do you thing about creating two more kinds of tests:

* `t0500-issues-and-regressions-offline.sh`
* `t0501-issues-and-regressions-online.sh`

Where tests would be created by per issues/bug basis and would specify for which issues exactly where they created.

**Comment by whyrusleeping** [comment]
I like this idea, we should do this.

**Comment by Kubuxu** [comment]
I am adding them with https://github.com/ipfs/go-ipfs/pull/2773

**Comment by chriscool** [comment]
Yeah, but if overtime we create many tests for bugs, the t0500 and t0501test scripts could become very big and messy.

We should at least reserve some test numbers for more test scripts of both kind. For example t05XX for offline issues and regressions, and t06XX for online issues and regressions.

**Comment by Kubuxu** [comment]
Seems like a smart idea. Let's move them over before there is much of a mess.

**Comment by Kubuxu** [comment]
Done in #2773, moved them around in https://github.com/ipfs/go-ipfs/pull/2790
