### ISSUE TITLE
Mans: Keep text within 78-char ruler

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2783]
I think we should keep the text for the descriptions wrapped in under the 78-char ruler. Here is an example where that doesn't happen, on my terminal: 

![screen shot 2016-06-01 at 4 48 34 pm](https://cloud.githubusercontent.com/assets/910753/15716032/b43fe166-2818-11e6-86d6-bea090f92557.png)

Even if this is a ridiculous cultural remnant of [IBM's punchcard days](https://programmers.stackexchange.com/questions/148677/why-is-80-characters-the-standard-limit-for-code-width), it may still be worth doing to conform to the industry standard.

I've gone through and manually PRed the descriptions to be wrapped (See #2782, #2780, #2779), but there are still the cases of the options and some of the examples. Should we manually wrap options? And Synopses? If so, how?

**Comment by whyrusleeping** [comment]
We should have a test that we can manually run to verify all our helptext fits within this limit. I think its a good idea to try and keep the 78 (but really 80) character limit

**Comment by whyrusleeping** [comment]
We've got a test for this now. Next up is trying to make it pass.

To run the test:
```
cd test/sharness
make deps
./t0010-basic-commands.sh
```

**Comment by whyrusleeping** [comment]
I'm assuming that since the test is merged to master, and things are passing, that this has been resolved

**Comment by Kubuxu** [comment]
Tests are not passing, they are marked as failed.

**Comment by whyrusleeping** [comment]
If any contributor is looking for something easy to get started with this, one would be great

**Comment by devedge** [comment]
I'm interested in taking this, are there any specific style guidelines I should adhere to when wrapping the text?

**Comment by magik6k** [comment]
Done in https://github.com/ipfs/go-ipfs/pull/4121
