### ISSUE TITLE
fix recursive --only-hash adding

### ISSUE THREAD

**Issue by noffle** [ipfs/go-ipfs#2784]
Fixing this in https://github.com/ipfs/go-ipfs/pull/2531 created another issue, https://github.com/ipfs/go-ipfs/pull/2690. The second regression is more serious, so [we've disabled recursive hash-only on `ipfs add`](https://github.com/ipfs/go-ipfs/pull/2690#issuecomment-223041891) for now. This bug tracks properly re-adding this functionality.

**Comment by whyrusleeping** [comment]
I believe this was resolved in my mfs caching PR
