### ISSUE TITLE
Warn user when auto-updating

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#279]
My vps's ipfs totally auto-updated on its own and didn't tell me. I'm +1 to auto-updating, -1 to robot armageddon. 

The event was definitely logged, but i'm using default logging level (`ERROR`). I think we should either 
1. log one message as `CRITICAL` (not an error, but is definitely critical to know).
2. have a class of messages that are end-user advisory (not program logs). or "notifications".

I propose to implement (1) for now and consider the merits of (2) separately.

**Comment by whyrusleeping** [comment]
since we no longer autoupdate, i'm closing this
