### ISSUE TITLE
Switch from camlistore/lock to go4.org/lock

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#2791]
Upstream moved to go4 and go4.org/lock finally works correctly on 32bit linux (no more stale locks!). This is the correct fix for #1537. I'd submit a PR myself but IPFS's dependency management is a bit convoluted...

**Comment by whyrusleeping** [comment]
@Stebalien thanks for reporting. This one is particularly convoluted since we arent just adding a new dependency or updating one that already in gx, we're removing one from godeps and replacing it with one in gx. I'll handle it and document the process here for later reference

**Comment by Stebalien** [comment]
No problem. I was just explaining why I didn't fix this myself.
