### ISSUE TITLE
Update utp dep and run extended t0130

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2802]

**Comment by whyrusleeping** [comment]
in t0130, we have the extended tests disabled for utp as they currently don't pass reliably. A lot of work has been put into utp by @anacrolix lately and i'm hoping the issues have been resolved.

**Comment by Kubuxu** [comment]
The `upt` dep has be modified by @whyrusleeping not to import missinggo.

This leads me to an idea/proposal to create Github org that would keep our forked dependencies (that don't use gx) in one place. Is it a good idea?

**Comment by whyrusleeping** [comment]
@Kubuxu I don't know if this will happen often enough to make it worthwhile.

**Comment by Kubuxu** [comment]
In my option one time is enough. I created org, `gxed` where at least I will be keeping deps I update/introduce.

**Comment by Kubuxu** [comment]
Also looks like utp is using missinggo quite a lot:
```
grep -R missinggo
package.json:      "name": "missinggo",
conn.go:	"github.com/anacrolix/missinggo"
conn.go:	gotFin    missinggo.Flag
conn.go:	closed    missinggo.Flag
conn.go:	destroyed missinggo.Flag
conn.go:		started:     missinggo.MonotonicNow(),
conn.go:	ret := missinggo.JitterDuration(3*l, l)
deadlines.go:	"github.com/anacrolix/missinggo"
deadlines.go:	passed missinggo.Flag
send.go:	"github.com/anacrolix/missinggo"
send.go:	started     missinggo.MonotonicTime
send.go:		latency = missinggo.MonotonicSince(s.started)
send.go:	if missinggo.MonotonicSince(s.started) >= writeTimeout {
socket.go:	"github.com/anacrolix/missinggo"
socket.go:	"github.com/anacrolix/missinggo/inproc"
socket.go:	"github.com/anacrolix/missinggo/pproffd"
socket.go:	backlogNotEmpty missinggo.Event
socket.go:	closed    missinggo.Event
socket.go:	destroyed missinggo.Event
socket.go:	// Pop a pseudo-random syn to make room. TODO: Use missinggo/orderedmap,
socket.go:	c.sendPendingSendSendStateTimer = missinggo.StoppedFuncTimer(c.sendPendingSendStateTimerCallback)
socket.go:	missinggo.AddCondToFlags(
socket.go:		missinggo.WaitEvents(&mu, &s.closed, &s.backlogNotEmpty, &s.destroyed)
```

**Comment by Kubuxu** [comment]
Just for tracking: I got stuck on https://github.com/jbenet/go-multiaddr-net/pull/17#issuecomment-224064595 as utp changed exposed address and I don't know how to tackle it down without modifying the registry significantly.

**Comment by whyrusleeping** [comment]
This has been completed
