### ISSUE TITLE
`ifps bootstrap rm --all` fails when pipe to stdin is left open

### ISSUE THREAD

**Issue by longboardcat** [ipfs/go-ipfs#2805]
We're running ipfs through a framework that leaves the file-handle open for a little while the process starts and never sends any data on it. We’re attempting to run `ipfs bootstrap rm --all` using `Open3.popen2e` (see [build_execution](https://github.com/square/build_execution) for more context). When we run it this way, `--all` is interpreted as a multiaddr/peerID format.  This seems like it might have something to do with the `isTerminal` function in `commands/cli/parse.go`. I'm not sure what's going on, and I'm not familiar with go.

You can reproduce the problem by running `cat | ipfs bootstrap rm --all` with at least one address in the bootstrap list and then hitting `Ctrl-D` to send EOF.

```bash 
cat | ipfs bootstrap rm --all
Error: invalid ipfs address
```

cc @mappum for `isTerminal`
cc @mtauraso

**Comment by Kubuxu** [comment]
Yeah, we are having problems with the `isTerminal` over here too: https://github.com/ipfs/go-ipfs/issues/2748

I think we shouldn't using heuristic for stdin but require either no argument or `-` argument.

**Comment by whyrusleeping** [comment]
@Kubuxu I think youre right. Or we can be a little better about checking our input, instead of assuming "not a terminal" means input, we can check to make sure its a file or a pipe (though i'm not sure what all options there are here)

**Comment by mtauraso** [comment]
IMO if there's any sort of auto-detect (be it pty/pipe/file/etc detection) that changes behavior, there ought be an override on the command-line for odd circumstances where you don't want that. This decouples the optimization of the naive case from the specific case and allows you to get the "just works" amazingness, while preserving specificity for those who want it.

**Comment by whyrusleeping** [comment]
This should be resolved now
