### ISSUE TITLE
ipfs get $hashofblock gives confusing error message

### ISSUE THREAD

**Issue by jonnor** [ipfs/go-ipfs#2807]
When the hash referred is a block, one cannot use `ipfs get` (as it expects a file object) - but instead have to use `ipfs block get`. This is fine, but the error message when attempting is not very helpful in understanding this:
```
$ ipfs get QmSnWHYwDUE1gdcUb6ZYgU2khZ5FkxuWsTvXbw3zGsKc3x
Error: Failed to decode Protocol Buffers: incorrectly formatted merkledag node: Unmarshal failed. proto: illegal wireType 6

$ ipfs block get QmSnWHYwDUE1gdcUb6ZYgU2khZ5FkxuWsTvXbw3zGsKc3x
�ripld-image-versionhtilesize�axayetiles�axayflevel0��fformatcpngdsize�axayddata�
......
````
Expected would be something like "Requested hash $hash refers to a block, not an object. Use ipfs block get instead". Possibly with the detailed error message above following it.

Ping @Kubuxu

**Comment by Kubuxu** [comment]
All files are blocks, in this case the block just doesn't contain unixfs format.

It should be more of: "Requested hash isn't recognised unix file encoding format" or something similar.
If someone has good error message, it should be quite easy to implement.

**Comment by whyrusleeping** [comment]
It looks like the block you requested is not a merkledag object. We should fix the error messages, and increase documentation around the layers of data involved here. raw blocks, merkledag protobufs, and then unixfs protobufs

**Comment by jonnor** [comment]
It is the kind of "block" one gets with `ipfs.block.put` using HTTP API. I guess that is a "raw block"?
Some guidance around this when making use of the API would indeed have been helpful, it is quite possible I should not have been using the block method/endpoint in the first place...
Was uploading a Buffer representing a PNG in one case, and a CBOR serialized JSON in another case.

**Comment by whyrusleeping** [comment]
@jonnor would the following look good to you?
```
➜  go-ipfs git:(master) ✗ ipfs object get QmUJPTFZnR2CPGAzmfdYPghgrFtYFB6pf1BqMvqfiPDam8
Error: QmUJPTFZnR2CPGAzmfdYPghgrFtYFB6pf1BqMvqfiPDam8 was not a valid merkledag node
```

**Comment by jonnor** [comment]
Not a `merkledag node` does not explain to me that it is a block, or help me understand that I should be using `block`...

**Comment by whyrusleeping** [comment]
@jonnor well, everything is technically a block. The cause of the error is that its not a merkledag node. You can do a `block get` on a perfectly valid merkledag

**Comment by RichardLitt** [comment]
If everything is a block, then why isn't `ipfs block` named `ipfs merkledagNode`?

**Comment by Kubuxu** [comment]
@RichardLitt because `ipfs block` deals with raw blobs stored in IPFS. `ipfs object` deals with DAG nodes and `ipfs get` interprets DAG nodes as files.

**Comment by RichardLitt** [comment]
```
ipfs block - Manipulate raw IPFS blocks.
```

Should this be 'raw IPFS MerkleDag blocks`, maybe?

**Comment by Kubuxu** [comment]
No `ipfs object` manipulates MerkleDags. `ipfs block` is for binary data not interpreted by IPFS in any way.

**Comment by Kubuxu** [comment]
All files are objects, all objects are blocks.

**Comment by whyrusleeping** [comment]
@jonnor how about "The block referred to by <HASH> was not a valid merkledag node" ?
