### ISSUE TITLE
Separate networks

### ISSUE THREAD

**Issue by cpacia** [ipfs/go-ipfs#2815]
Is there an easy way to create a network separate from the main IFPS network. Obviously, you can just change the bootstrap list, but if someone adds a peer from the other network than the two just merge together. 

I'm asking because there are a couple tweaks I'm making in OpenBazaar that I don't think you guys would want in the code base. One has to do with changing the ttl on certain types of data. Regular ipfs provider entries stay at 24 hours but providers related to our messaging system I'm increasing to 7 days because 24 isn't long enough for the purpose. 

If our networks merge and we get nodes that are purging those providers after 24 hours then the messaging system wont work very well. 

I know bitcoin uses a magic number in the packets to deal with this. That's seems like the best solution to me as it would be pretty easy to change the constant to create a new network (like a testnet for example). 

I'm also wondering, if without changing the packet structure, I can just change the protocol string from "/ipfs/dht" to "/openbazaar/dht".

I've tested this by changing both /ipfs/dht/ and /ipfs/bitswap/ but I still get connections on my node even with running with these protocol strings (same bootstrap peers).  

I haven't taken a deep look into the libp2p but would it still open connections in that case but just not be able to send messages? If so, if someone adds a peer from a different network will the two networks be prevented from merging? Or will the routing table be filled up with peers from the other network?

**Comment by whyrusleeping** [comment]
We currently dont have a way to create a completely separate network, i have some work towards this in progress, but its not ready yet. 

Changing the protocol string would work pretty well for you. Your nodes still might connect to the main network, but no DHT messages would be propogated between the networks.

**Comment by whyrusleeping** [comment]
That said, there might be some weird things that happen in that case because we assume everyone connecting has the same protocols. This is an assumption i'm working on fixing quite soon since the js-ipfs implementation won't have a dht for a while

**Comment by whyrusleeping** [comment]
@cpacia i'm assuming we've resolved this. closing
