### ISSUE TITLE
Test auto-updating works.

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#282]
We should test auto-updating works with one of the sharness tests.  Maybe:

1. Query the current version (once #281 is fixed)
2. `git checkout` a build known to be older. 
3. build it
4. test various expected outputs of `ipfs update` command
5. test whether it auto-updates
6. test `ipfs version` moves to latest.

**Comment by whyrusleeping** [comment]
closing, no auto updates here.
