### ISSUE TITLE
ipfs ls gets stuck

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2820]
ipfs object get works but ls gets stuck:
```
ipfs object get QmcmPko2PHCLnLqZTZXjPf4FLKyYjKDpb9VDbH6cVWTsU7
{"Links":[{"Name":".githash","Hash":"QmdG39xEJFK2YmYFxBYip1wCfvhSjVEXqCYnERJY2JY7rC","Size":49},{"Name":"ajax","Hash":"Qmdswc3USf1YoXWbUHUMDAcvwDjkwuPcq5ja4kiFAy5rZx","Size":20796815067}],"Data":"\u0008\u0001"}
```

Goroutine trace: https://gist.github.com/Kubuxu/ab56191ccb9aa725d5230f22bcd86f1a

It is probably due to fact that one file got lost and is no longer available: `fs:/ipfs/QmcmPko2PHCLnLqZTZXjPf4FLKyYjKDpb9VDbH6cVWTsU7/.githash`

**Comment by Kubuxu** [comment]
This can be resolved if we drop `Type` from `ls` result.

**Comment by whyrusleeping** [comment]
yeah... `ipfs ls` has the unixfs info encoded in it. We made `ipfs files ls` to be the 'correct' tool for this purpose. I wonder if we should look at deprecating that feature of `ipfs ls`.

In any case, you can add `--timeout=10s` to the command to make it not take longer than ten seconds

**Comment by Kubuxu** [comment]
The only thing that blocks the node is adding a slash over here: https://github.com/ipfs/go-ipfs/blob/master/core/commands/ls.go#L119

Of course it can be useful from the API but please take a look at #2824
