### ISSUE TITLE
Windows: makefile doesn't understand path quirk

### ISSUE THREAD

**Issue by djdv** [ipfs/go-ipfs#2833]
Previously I have used `make` from the msys2 project inside of a native Windows command line shell to build IPFS, pull https://github.com/ipfs/go-ipfs/pull/2808 seems to have broken my ability to build this way. This is more than likely do to the way msys and cygwin convert Windows paths i.e. C:\tmp -> /c/tmp.

![make break](https://cloud.githubusercontent.com/assets/13862850/15955819/4fa977b2-2eb2-11e6-948b-7338b8190b5c.png)

Within an msys2 shell I can build again just fine after setting up Go paths, or installing a second copy of Go inside of the msys environment.

![make break 2](https://cloud.githubusercontent.com/assets/13862850/15955823/53757d1e-2eb2-11e6-876b-64285eea235b.png)

I'm not sure how many people this effects but I don't think it's too uncommon for people to use the native shell and natively installed version of Go if they can.

**Comment by lgierth** [comment]
cc @kalabe got a good idea how to fix building on windows? If it's too tricky I think we should revert #2808 and instead reconsider how we're organizing our build.

**Comment by djdv** [comment]
@lgierth  I think @karalabe is the intended name, kalabe is someone else. Pinging for above.

**Comment by Kubuxu** [comment]
It was reverted, should we close it?

**Comment by djdv** [comment]
I would say yes, but a separate issue should probably be opened for multiple GOPATH paths if that's still desired.
