### ISSUE TITLE
Daemon needs restart to publish content

### ISSUE THREAD

**Issue by ligi** [ipfs/go-ipfs#2834]
This will be a suboptimal bugreport, but I think this needs investigation and should not get lost.

Scenario:
- I was adding a file locally
- @Kubuxu was pinning the file with the bot on IRC
- I was trying to wget the file from the ipfs.io gw and it was "awaiting response..." for ages
- after some debugging on irc ( read on from here: https://botbot.me/freenode/ipfs/2016-06-10/?msg=67646335&page=2 ) we found out that restarting the daemon gives some progress - means every time I restarted the daemon I saw some progress with wget - but then it stopped again - with constant restarting I was able to completely download the file ( and after this no more restarting of the daemon was needed ) - but this should not be the solution for end-users

perhaps this is the reason: @Kubuxu Looks like you are NATed two times.
11:33 @Kubuxu IPFS should be able to punch through either way, weird.

If it is a problem with my network I am happy to do tests and/or invite Berlin based IPFS devs ( @haadcode , @lgierth ) to figure out what is the problem.

**Comment by whyrusleeping** [comment]
@ligi could you provide some more information about what version of ipfs you were running? and on what system.

**Comment by ligi** [comment]
sure: {"Version":"0.4.2","Commit":"1654bbf","Repo":"3"}
on Ubuntu 16.04

**Comment by Stebalien** [comment]
Closing due to age.
