### ISSUE TITLE
Packaging issues with gx

### ISSUE THREAD

**Issue by zimbatm** [ipfs/go-ipfs#2842]
Hi,

ipfs is awesome and I want to package the latest version for nix. Usually it's fairly easy to package go programs but ipfs has made it pretty hard. `gx` depends on `ipfs` and `ipfs` depends on `gx`. I would also like to add a `fetchipfs` method to nixpkgs but again it would require to have `ipfs` working.

I suspect this issue is going to be affecting anyone who wants to produce reproducible builds. Is there any way to have ipfs only depend on `godep` maybe?
Alternatively, I could use pre-compiled `gx` binaries during bootstrap if they are made available for all the platforms.

**Comment by lgierth** [comment]
gx is actually supposed to use https://ipfs.io/api if there's no local IPFS daemon. Does that not work for you?

> Alternatively, I could use pre-compiled gx binaries during bootstrap if they are made available for all the platforms.

gx and gx-go binaries are available at https://dist.ipfs.io -- I guess we can add binaries for nix?

**Comment by Kubuxu** [comment]
The gx and gx-go doesn't depend on IFPS. They can build and download deps without IFPS at all, they will use global gateways for that task.

gx can't just publish new packages without local IPFS instance

**Comment by zimbatm** [comment]
> gx is actually supposed to use https://ipfs.io/api if there's no local IPFS daemon. Does that not work for you?

Actually I didn't get there, I was stuck at trying to compile gx for nix by listing all of the sources.

> gx can't just publish new packages without local IPFS instance.

Nice. I will try to bootstrap the whole system with the binaries above.

It might make sense to pin the gx dependencies using another tool like godep, govendor, ... for reproducability reasons.

**Comment by zimbatm** [comment]
I think I got confused. I managed to package gx, I just had to fix one of the imports: https://github.com/zimbatm/nixpkgs/commit/e1a487fa8f17f6ddd880899c0fe25ca97816926e#diff-fa2e05fb2a868ddbf9fea7a064c6f49cR19

**Comment by zimbatm** [comment]
Right now it's not straigh-forward to find back the original repo from the package.json file. It would be nice if the git hash and repo where also stored along-side as a fallback?

**Comment by Kubuxu** [comment]
You can go to IPFS hash of given package and look at its `package.json` and `gx.dvcsimport` field for the git source. It should be possible with command but I just discovered that it is broken.

**Comment by whyrusleeping** [comment]
@zimbatm I agree, we need a way to easily determine what git ref was used for any given gx publish. Do you have any ideas on a good place to store that info? 
My initial thoughts were to change the format of the .gx/lastpubver file to include extra metadata such as this

**Comment by Kubuxu** [comment]
We could have just other file in there: `.gx/githash`. First line would be full hash at which it was published, next word `dirty` if the publish was not done on a committed changes.

**Comment by zimbatm** [comment]
I need a bit more information:

1. Is it fair to assume that all the dependencies are stored in git?
2. Do you only export repo roots with gx?

If both answers are yes, personally it would be much more useful if go-ipfs's package would already contain the resolved information. A new key like that:

```json
{
 "gxDependencies": [
    {
      "hash": "QmYtB7Qge8cJpXc4irsEp8zRqfnZMBeB7aTrMEkPk67DRv",
      "name": "go-log",
      "version": "1.1.1",
      "source": {
        "url": "git+https://github.com/...",
        "rev": "<git sha1 here>"
      }
    }
}
```

Then it would be easy for me to clone the repos in a GOROOT structure and setup a symlink to `$GOROOT/src/ipfs/QmYtB7Qge8cJpXc4irsEp8zRqfnZMBeB7aTrMEkPk67DRv`.

Or alternatively augment the Godeps/Godeps.json with the gx information. That would provide a nice way to transition without breaking backward-compatibility.

**Comment by Kubuxu** [comment]
Problem is that quite frequently our deps are modified and published to gx only.

Setting symlink to `$GOPATH/src/ipfs/Qm...AAA` won't work as path files undergo post processing after the import.

If you have gx and gx-go, which should be quite easy to do (you need to just package gx and gx-go which are normal go programs), then you should have no issue to build go-ipfs.

**Comment by Kubuxu** [comment]
Please tell me if you have any more questions, otherwise please close it.

**Comment by zimbatm** [comment]
Alright thanks, I think I can get to build a gx fetcher for nix
