### ISSUE TITLE
Statistics for deprecated protocols

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2843]
As we modify the go-ipfs protocols we mostly keep backward compatibility but that means that we will be keeping really outdated and who knows, vulnerable code around.

My idea is to tag and count statistics for older protocol variants, then I we see that the older variant isn't used at all (for example on the solarnet nodes) we can safely remove it from the codebase.

Example of change that introduces backward compatible protocol improvement but leaves some code lying around is: https://github.com/ipfs/go-ipfs/pull/2817

**Comment by whyrusleeping** [comment]
@Kubuxu Anything actionable here? Unsure if we want to keep this open or what

**Comment by Kubuxu** [comment]
This is something we will have to do sooner or later. You can close it, or leave open as a reminder.

Hmm, let's keep things actionable. CLOSED
