### ISSUE TITLE
set --manage-fdlimit to true, and have the default value for fds be 1024

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2845]
The current default of behaviour of ipfs is to not touch the fd limit (even if it is unsufficient). The reasoning for this is that we want to respect user defined limits on the program. I think though, that it is reasonable to raise the limit in the case that it is lower than 1024. Ipfs does not run well when it is given fewer than 1024 file descriptors to work with.

To this end, the option to `ipfs daemon`, `--manage-fdlimit` should now default to true, and we should set the file descriptor to 1024 in the default case (while still respecting the environment variable for that if set).

**Comment by Kubuxu** [comment]
Resolved in: https://github.com/ipfs/go-ipfs/pull/2884
