### ISSUE TITLE
Commit  breaks 'make build' on Cygwin

### ISSUE THREAD

**Issue by jefft0** [ipfs/go-ipfs#2851]
I'm building on Cygwin. I get the following error after the recent change to Makefile in commit https://github.com/ipfs/go-ipfs/commit/ff75bc0318579fa743a35d316c61d2f8c4ab92ce#diff-a723d88d463c5bcca77d3d10a2b337bd 

    go-ipfs must be built from within your $GOPATH directory.
    expected 'C:/work/go/src/github.com/ipfs/go-ipfs' but got '/cygdrive/c/work/go/src/github.com/ipfs/go-ipfs'

When I revert the changes to Makefile and bin/check_go_path, then `make build` works again.

**Comment by lgierth** [comment]
Hey thanks for reporting this and sorry we broke it :) Closing in favor of #2833
