### ISSUE TITLE
Daemon crashes on EC2 instance after a few days

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-ipfs#2864]
I have an IPFS daemon running on an EC2 instance, (https://demo.peergos.net) and it keeps crashing. This is some of the latest goroutine dump upon crash:
[ipfs,dump.txt](https://github.com/ipfs/go-ipfs/files/321196/ipfs.dump.txt)

It is built from source from master. It has been happening since 0.4.0. The current git hash of the version that caused this dump is 79e9bd842cfcb85d...

**Comment by whyrusleeping** [comment]
@ianopolous how is it crashing? the stack trace you provided doesnt indicate a panic or OOM issue.

**Comment by ianopolous** [comment]
All I know is it terminates, and that was the last part of the goroutine dump. I've started it again to capture the entire output, but it will take a few days to repeat at least. I would be surprised if it was an OOM issue, but we'll see.

**Comment by ianopolous** [comment]
Turns out it was an OOM error. The machine has about 800 MiB of RAM free and is under extremely low usage (was uploading a 2MiB file). Do you want the full goroutine dump?

**Comment by ianopolous** [comment]
@whyrusleeping It has crashed again, but this time not an OOM, 
runtime/cgo: runtime/cgo: pthread_create failed: Resource temporarily unavailable
pthread_create failed: Resource temporarily unavailable
SIGABRT: abort

**Comment by ianopolous** [comment]
It just crashed again, still under almost no load, this time another OOM.

**Comment by Kubuxu** [comment]
We are working on it: https://github.com/ipfs/go-ipfs/issues/2848 https://github.com/ipfs/go-ipfs/issues/2848

**Comment by ianopolous** [comment]
This is still happening, though it took a week this time. This is on the master branch, at commit: 4fa85cc4d4 from July 1st. 
[ipfs.oom.log.txt](https://github.com/ipfs/go-ipfs/files/365420/ipfs.oom.log.txt)

**Comment by jbenet** [comment]
Try rc3?

**Comment by ianopolous** [comment]
I'm not in a position where I can upgrade it at the moment as we're half way through rewriting our front end. I'm happy to close it for now, as I don't notice it, after putting it in upstart. We've also moved from EC2 to Linode.
