### ISSUE TITLE
Should .Default(false) be used on all boolean options?

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#2865]
@RichardLitt has been adding `.Default(false)` to a lot of Boolean options.  To me this seams really unnecessary and adds noise to the help text.  I can find very little president for this in the help text for most (unix) command line options.

The only discussion I can find on this is in the comments for pull requests #2582 where @whyrusleeping and @jbenet commented on it.  However,  @jbenet final comment seamed more about if Boolean options should always default to false and less on if "Default: false" should be displayed for each and every Boolean option that defaults to false.

This issue is a request to formally document the policy and the reason behind it.

**Comment by kevina** [comment]
For the record I should add that I think "Default: true" should be displayed for the few Boolean options that default to true, but "Default" false" is unnecessary and redundant.

**Comment by whyrusleeping** [comment]
@kevina I agree. I think adding the `Default(false)` is just noise and have voiced this a few times.

**Comment by RichardLitt** [comment]
Yeah, I took @jbenet's comment to mean I should just put it in. I'm happy to remove it if is clearer, it is some noise and we can assume that they will be false. Adding Default: true if valid is something that should be done, for sure.

**Comment by kevina** [comment]
@whyrusleeping I don't think this issue was ever resolved or properly discussed.  I am reopening.  I also changed the title to be more direct.

**Comment by RichardLitt** [comment]
AFAIK, this has been discussed a lot off-GitHub. The resolution we came to is that, no, `.Default(false)` is an understood quality of booleans, and it doesn't mean to be made explicit. If you see this in the code, you can remove it, and there's no expectation going forward to include it.

**Comment by whyrusleeping** [comment]
Cool, i think we're in agreement here that `Default(false)` is not necessary.
