### ISSUE TITLE
'ipfs pin add --help' hangs

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#2866]
```
$ ipfs version --commit
ipfs version 0.4.2-2a3bba3
```

`ipfs pin add --help` hangs waiting for input
`ipfs pin add --help < /dev/null` is okay
`ipfs pin add --help q` is okay.

**Comment by kevina** [comment]
`git revert -m1  e5e2f2c19c2b688a64b89b79a40f900048394336`

Fixes it for me.  Thus I am left to conclude something in pull request #2822 broke this.

**Comment by Kubuxu** [comment]
Sorry, didn't notice this issue and created https://github.com/ipfs/go-ipfs/issues/2868

I will close this in favour of https://github.com/ipfs/go-ipfs/issues/2868
