### ISSUE TITLE
Required String arugments with stdin handling enabled block --help

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2868]
Introduced in: https://github.com/ipfs/go-ipfs/pull/2822

As the string arguments from stdin are resolved before the command is run it halts execution of the command and waits for the input.

The simplest and the most sane solution would be to remove stdin from String arguments.
All Unix based system all include `xargs` command that does exactly that and current behaviour of `ipfs` command rises more confusion than it is useful.

My proposition would be to remove `EnableStdin` from non file type arguments and also log it/crash as an error in command creation routines.

**Comment by whyrusleeping** [comment]
@Kubuxu which commands does this affect?

**Comment by Kubuxu** [comment]
Many of them, there are about 30 StringArgs with Stdin handling enabled.

**Comment by whyrusleeping** [comment]
hrm... I like being able to pipe arguments directly to the commands. Maybe theres a way to defer the processing of the arguments until later?

**Comment by Kubuxu** [comment]
Not without introducing terminal vs pipe inconsistency again: https://github.com/ipfs/go-ipfs/pull/2877

I didn't know that you could directly pipe into commands for quite some time.
Using `xargs` is just natural.

**Comment by whyrusleeping** [comment]
@Kubuxu is this resolved? If so, can you PR in a test that just runs `ipfs block get --help` and makes sure it returns?

**Comment by Kubuxu** [comment]
https://github.com/ipfs/go-ipfs/issues/2913
