### ISSUE TITLE
mount on case insensitive filesystems

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#288]
Some  filesystems (like osx's default hfs) [are case insensitive...](http://a0.1nsk.ru/3/a32b30b66d.png) this breaks our b58 string keys when mounting with fuse. Possible solutions
- use different encoding (argh)
- use a different mount point to map between encodings `/ipfs/b32/...`

**Comment by mitar** [comment]
hfs is case insensitive, but case preserving. You can still store files with different case, you just cannot have two files which have name different only in case.

**Comment by Stebalien** [comment]
CIDs fix this as we can use any base we want. Also, we're switching to base32 by default so this will become even less of an issue.
