### ISSUE TITLE
Trouble pulling up new resources

### ISSUE THREAD

**Issue by jcalfee** [ipfs/go-ipfs#2882]
I'm using the latest IPFS release on my localhost and on the server... 0.4.2

I noticed that if we add a new IPFS resource, it does not get listed (or found) in our production IPFS server.  If, however, I pull up the hash at `https://gateway.ipfs.io/ipfs/xxxxx` it will cause our IPFS server to find the resource right away.  Also, bouncing our server will allow the recourse to be found.

The `ipfs swarm peers` returns a long list of peers.

**Comment by jcalfee** [comment]
The resource remains stuck in the `ipfs bitswap wantlist`

**Comment by whyrusleeping** [comment]
@jcalfee could I get a stack dump from the server in question? `curl localhost:5001/debug/pprof/goroutine\?debug=2`

**Comment by jcalfee** [comment]
[ipfs.stack.txt](https://github.com/ipfs/go-ipfs/files/326175/ipfs.stack.txt)

**Comment by whyrusleeping** [comment]
Looks like the yamux/utp hang we fixed recently (in master) If you want to try running latest master it will likely fix the problem. The next official release (v0.4.3) will be around the second week of July and will include those fixes.

**Comment by jcalfee** [comment]
thank you
