### ISSUE TITLE
Filing an Issue

### ISSUE THREAD

**Issue by em-ly** [ipfs/go-ipfs#2894]
Version/Platform/Processor information (from `ipfs version --all`): Mac
Type (bug, feature, meta, test failure, question): Is this thing on?
Area (api, commands, daemon, fuse, etc): Meta
Priority (from P0: functioning, to P4: operations on fire): P∞

Description:
\o/

**Comment by whyrusleeping** [comment]
Looks good to me.

**Comment by em-ly** [comment]
@therealplato - we just implemented a new issue filling format - check it out!

**Comment by RichardLitt** [comment]
@em-ly Did you run `ipfs version --all`?
