### ISSUE TITLE
make install: import cycle not allowed

### ISSUE THREAD

**Issue by jcalfee** [ipfs/go-ipfs#2899]
Description:
```
go get -d github.com/ipfs/go-ipfs
import cycle not allowed
package github.com/ipfs/go-ipfs
	imports runtime
	imports runtime/internal/atomic
	imports unsafe
	imports runtime
```
Same happens during `make install`:
```
import cycle not allowed
package github.com/ipfs/go-ipfs/cmd/ipfs
	imports expvar
	imports net/http
	imports crypto/tls
	imports crypto/x509
	imports net
	imports runtime/cgo
	imports runtime/cgo
make[1]: *** [install] Error 1
make[1]: Leaving directory `/home/jcalfee/opt/go/src/github.com/ipfs/go-ipfs/cmd/ipfs'
make: *** [install] Error 2
```

**Comment by Kubuxu** [comment]
It looks like Golang issues, which version of Golang are you using, and try making a sample project using for example `expvar` package.

**Comment by jcalfee** [comment]
go version go1.6.2 linux/amd64

**Comment by jcalfee** [comment]
Not sure how to make a sample project.

**Comment by jcalfee** [comment]
I'm not developing in Go yet!  I'm trying to build master because I'm told your two weeks away from having a bug fix that I need.

**Comment by whyrusleeping** [comment]
@jcalfee can you compile a simple go program, such as:
```go
package main

import "fmt"

func main() {
  fmt.Println("Hello World!")
}
```

**Comment by jcalfee** [comment]
NO, Same error!  Thank you, I'll go figure this out..

**Comment by saplmm** [comment]
请问：这个问题怎么解决的？我的也是出现了这个问题，一直没有解决 @jcalfee
