### ISSUE TITLE
CI of subprojects

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2900]
Following projects have CI broken or not at all
- [ ] https://github.com/ipfs/go-libp2p-secio - https://github.com/ipfs/go-libp2p-secio/pull/4
- [ ] https://github.com/ipfs/go-libp2p-crypto - https://github.com/ipfs/go-libp2p-crypto/pull/4
- [ ] https://github.com/ipfs/go-libp2p-peerstore - https://github.com/ipfs/go-libp2p-peerstore/pull/4
- [ ] https://github.com/ipfs/go-libp2p-loggables - https://github.com/ipfs/go-libp2p-loggables/pull/4

**Comment by facastagnini** [comment]
Ticket breakdown:
- ipfs/go-libp2p-secio/issues/2
- ipfs/go-libp2p-crypto/issues/3
- ipfs/go-libp2p-peerstore/issues/3
- ipfs/go-libp2p-loggables/issues/3

**Comment by Kubuxu** [comment]
@facastagnini I just started PRin them. :smile:

**Comment by facastagnini** [comment]
hahaha, I know

**Comment by facastagnini** [comment]
Guys, this ticket can be closed
