### ISSUE TITLE
t0080 has bad gc test

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2906]
Type: test failure
Area: repo sharness tests
Priority: P1

Description:
in t0080-repo.sh, there is a test (currently test_expect_failure) that checks the size of a repo before and after a gc. This is occasionally faulty because the daemon is running during this and will sometimes write random bits of data to the datastore, thus changing the observed size. We should either run this test with the daemon offline, or find a better way to measure

**Comment by Kubuxu** [comment]
As we have `--offline` flag now it should be easy.
