### ISSUE TITLE
Inconsistent usage of IPFS and ipfs

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2910]
We generally agreed on fact that capitalised IPFS should be used in reference to project and ipfs in reference to CLI or implementation.

Unfortunately now we are inconsistent across codebase. One of great examples is help text of `ipfs tar`:

```
 ipfs tar -h
USAGE
  ipfs tar - Utility functions for tar files in IPFS.

SUBCOMMANDS
  ipfs tar add <file> - Import a tar file into ipfs.
  ipfs tar cat <path> - Export a tar file from IPFS.

Use 'ipfs tar --help' for more information about this command.
```

**Comment by RichardLitt** [comment]
Opened PR.
