### ISSUE TITLE
`ipfs block rm`

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#2914]
Currently, the only way of deleting blocks in go-ipfs is through `repo gc`. In js-ipfs land, since the Block Service exposes an interface to delete, we also have exposed that on the block API. It is very convenient for testing and a quick way to delete a specific block.

Can we expose this feature in go-ipfs too?

**Comment by Kubuxu** [comment]
Is should be really easy as we also have `Delete` call in blockstore. Problem with deleting block is that it might be component of different file or directory and as user would probably expect the removal of all blocks connected to file or directory it is even bigger issues.

**Comment by diasdavid** [comment]
@Kubuxu that would be something for the files api. The block API is really well scoped as the put and get only also return or add a single block

**Comment by Kubuxu** [comment]
Ahh, right. So yeah, `ipfs block rm` should be possible and quite easy to do.

**Comment by kevina** [comment]
How should removing pinned blocks be handled?  Disallow?  Allow and ignore pin?  (This could then cause many problems with ipfs commands, for example the garbage collector will abort) Allow and attempt to do something about the pin?  (Not so easy unless the pin a a direct pin.)

**Comment by whyrusleeping** [comment]
Yeah, we need to make sure we don't remove blocks that are pinned.

**Comment by diasdavid** [comment]
Good point. If a block is pinned, it should error saying that it is pinned

**Comment by kevina** [comment]
I agree at least by default.  However, for performance reasons, we might want to add an option to disable this detection if the user knows what they are doing.

I am not 100% sure I understand the pining code but it seams that to detect indirect pins all recursive pins need to be walked, thus making pin detection expensive.  It looks like there might be some caching going on in the datastore under the prefix 'local/pins/indirect/keys/' but it doesn't seam like this is used  by [`pin.IsPinnedWithType()`](https://github.com/ipfs/go-ipfs/blob/master/pin/pin.go#L203).

**Comment by whyrusleeping** [comment]
Yeah, pin detection is expensive. We can optimize with various caching structures though in the future.

**Comment by kevina** [comment]
I know the issues involved so I take responsibility for this one.

**Comment by RichardLitt** [comment]
Participating.

**Comment by diasdavid** [comment]
Any update on this one?  :)

**Comment by kevina** [comment]
@diasdavid please see #2962

**Comment by whyrusleeping** [comment]
we have this now :)

**Comment by diasdavid** [comment]
woot!
