### ISSUE TITLE
`ipfs dht findpeer $peerId` has incorrect error message for longer peerid

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2916]
Version/Platform/Processor information (from `ipfs version --all`):
```
go-ipfs version: 0.4.2-f182675
Repo version: 3
System version: amd64/darwin
Golang version: go1.5.3
```
Type (bug, feature, meta, test failure, question): doc
Area (api, commands, daemon, fuse, etc): commands
Priority (from P0: functioning, to P4: operations on fire): P0

Description:

```sh
$ ipfs dht findpeer /ip4/198.100.147.192/tcp/4001/ipfs/QmQTw94j68Dgakgtfd45bG3TZG6CAfc427UVRH4mugg4q4
Error: multihash too short. must be > 3 bytes
```

The Multihash isn't too short. It is too long.

**Comment by whyrusleeping** [comment]
This needs to be addressed in go-multihash
