### ISSUE TITLE
Getting a lot of ECONNRESET when calling `files mkdir` exhaustively

### ISSUE THREAD

**Issue by daviddias** [ipfs/go-ipfs#2918]
Version/Platform/Processor information (from `ipfs version --all`):

```
go-ipfs version: 0.4.2-255c6f3
Repo version: 3
System version: amd64/darwin
Golang version: go1.6
```

Type: bug
Area: API
Priority: P2

Description:

Getting several ECONNRESET errors when calling the `files mkdir` several times. It works fine in the beginning though.

Example error:

```
{ [Error: Client request error: read ECONNRESET]
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  trace:
   [ { method: 'GET',
       url: 'http://127.0.0.1:5001/api/v0/files/mkdir?p=true&flush=true&arg=%2Fnpm-registry%2Fnode-spec%2F-&stream-channels=true' } ],
  isBoom: true,
  isServer: true,
  data: null,
  output:
   { statusCode: 502,
     payload:
      { statusCode: 502,
        error: 'Bad Gateway',
        message: 'read ECONNRESET' },
     headers: {} },
  reformat: [Function] }
```

How to reproduce:

``` sh
> ipfs daemon &
# ...
> git clone git@github.com:diasdavid/npm-on-ipfs.git -b ipfs-npm
> cd npm-on-ipfs
> npm install
> npm link
> ipnpm registry clone
```

**Comment by whyrusleeping** [comment]
@diasdavid does the daemon print out any errors when this happens?

**Comment by diasdavid** [comment]
@whyrusleeping not even one

**Comment by diasdavid** [comment]
We've found a bug where ipfs-blob-store would try to write an undefined buffer if the buffer was empty (happened when npm had a reference to a tarball it no longer possesses)

Fixed here - https://github.com/ipfs/ipfs-blob-store/pull/18

Now everything seems to work as expected, still getting the 502, but things are stored.

**Comment by whyrusleeping** [comment]
@diasdavid would you consider this bug resolved?

**Comment by diasdavid** [comment]
Can't tell, need to update registry-mirror to the latest js-ipfs-api and test it exhaustively again.

**Comment by magik6k** [comment]
It appears to be fixed, feel free to re-open if it still happens
