### ISSUE TITLE
Tracker/proxy versus DHT

### ISSUE THREAD

**Issue by cminnoy** [ipfs/go-ipfs#2920]
Hi,

I would like to refer to the following comparission (for bittorrent) between DHT and Trackers:
https://www.ietf.org/proceedings/76/slides/ppsp-4.pdf

Would it be usefull for IPFS also to implement a concept of a Tracker?
For example in a LAN, you don't want to have a DHT running around, nor each individual
PC talking direct to the internet.
A Tracker will be faster. I can imagine that corporations will be refusing IPFS on their
network when they can not control/monitor the communication/bandwidth.
A Tracker or Proxy could be helpfull at the edge of the LAN to the WAN.

Cheers,

Chris

**Comment by whyrusleeping** [comment]
ipfs has support for plugable routing mechanisms. It doesnt necessarily need to use the DHT if something else is available. This isnt currently implemented, but can be easily in the future.

If you want to have further discussion towards this, could you please move your issue over to ipfs/notes ? we try to keep issues in this repo down to things directly related to the go implementation of the protocol.
