### ISSUE TITLE
Daemon startup hangs in Bitswap.GetBlock()

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#2931]
Version/Platform/Processor information (from `ipfs version --all`):

```
go-ipfs version: 0.4.2-fe7b01f
Repo version: 3
System version: amd64/linux
Golang version: go1.5.2
```

Type (bug, feature, meta, test failure, question): `bug`
Area (api, commands, daemon, fuse, etc): `daemon`
Priority (from P0: functioning, to P4: operations on fire): P2

Description:

Daemon starts up with a functional swarm, then hangs in `core.setupNode() -> core.IpfsNode.loadFilesRoot() -> bitswap.Bitswap.GetBlock()`. This means there's no API or Gateway. Goroutine dump from SIGQUIT: https://ipfs.io/ipfs/QmcLeh6SCD9zqDZZcuAeKFRRc5DygDNBM7LxR7LJesXWyy

**Comment by whyrusleeping** [comment]
@lgierth was this one of the storage nodes? This looks to me like someone put stuff in mfs and then ran a gc

**Comment by Kubuxu** [comment]
Before we had best effort pin.

**Comment by lgierth** [comment]
Yes this is from @diasdavid's registry-mirror node on biham, from around 18-Feb-2016. Do we have to start over?

**Comment by whyrusleeping** [comment]
@lgierth yeah, this one unfortunately requires a start-over. Its since been fixed though.
