### ISSUE TITLE
Increase 512 kbyte limit for `ipfs object put`

### ISSUE THREAD

**Issue by kpcyrd** [ipfs/go-ipfs#2938]
For a mirroring project, I'm trying to add very large folders to ipfs (> 10k links).

I've used `ipfs object patch add-link` for this, but switched to `ipfs object put` for performance reasons.

Current go-ipfs has a hardcoded limit for `ipfs object put`, which is [512 kbytes][1].

The folder I'm trying to add to ipfs is too large for this limit.

[1]: https://github.com/ipfs/go-ipfs/blob/ddc8d0c60c7e4e46f63afc3d754f4c973ae084a8/core/commands/object/object.go#L24

**Comment by Kubuxu** [comment]
@kpcyrd it is more of an issue of `ipfs object patch add-link` disregardig soft limits we set in go-ipfs. Bigger directories are planned and worked on: https://github.com/ipfs/notes/issues/76

**Comment by kpcyrd** [comment]
//cc: @whyrusleeping
