### ISSUE TITLE
Periodic Heavy CPU usage

### ISSUE THREAD

**Issue by japzone1** [ipfs/go-ipfs#2945]
Version/Platform/Processor information (from `ipfs version --all`): 
version 0.4.2 
(--all command is unrecognized)
Windows 10 x64
Intel i7 4720HQ

Type (bug, feature, meta, test failure, question): bug
Area (api, commands, daemon, fuse, etc): daemon
Priority (from P0: functioning, to P4: operations on fire): P2

Description:
Whenever IPFS starts downloading a file my CPU usage shoots up like crazy. It'll eventually level off but then it shoots up again. Each time making my PC barely usable. This makes streaming any kind of media impractical as my PC looses the resources it needs to even play the media. Any tips on how I can help you debug this would be appreciated.

**Comment by whyrusleeping** [comment]
@japzone1 Thanks for reporting, heres some info you can give me that will help debug the issue:

- *during* the heavy CPU usage, collect the information specified in this guide: https://github.com/ipfs/go-ipfs/blob/master/docs/debug-guide.md
- roughly how big is the content youre downloading?
- How frequently do the CPU spikes happen? every hour? every day?
- What are your internet speeds like normally?

**Comment by japzone1** [comment]
- [ipfs-dumps.zip](https://github.com/ipfs/go-ipfs/files/349090/ipfs-dumps.zip)

- It happened with a 26mb video, and happened several times during a 1GB+ video

- First CPU spike is when it first starts retrieving a file, subsequent spikes happen if the file is large (like the 1GB+ video I tried downloading)

-My internet connection is 50mbps up/down

**Comment by whyrusleeping** [comment]
@japzone1 could I also get a copy of the binary youre running?

**Comment by japzone1** [comment]
[Here you go](https://mega.nz/#!bZw0jKpb!BsTMeZvjk2zEGbZdRRD1q3VvUXVZ1MoKAkE-piWMX_0)

**Comment by whyrusleeping** [comment]
Cool, All the major issues i see here should be resolved in latest master. If you want to try building from source and giving that a shot, it would be great feedback for us. Otherwise, just wait a couple weeks for the 0.4.3 release and try it then

**Comment by japzone1** [comment]
Cool. Not sure if I've got time to build from source, but I'll definitely give the update a try when it's ready.

**Comment by whyrusleeping** [comment]
@japzone1 there are release candidate builds of 0.4.3 up on dist.ipfs.io, want to give that a shot and let me know how it goes?

**Comment by japzone1** [comment]
@whyrusleeping There's still some pretty high CPU usage, but I'm not sure if that's normal or not. At the very least, my system no longer locks up when I'm trying to stream a video making it usable compared to before. Though that's me running IPFS on an i7.  Not sure how well it would be working if I was using an i3 or less.

**Comment by jbenet** [comment]
@japzone1 and this is with 0.4.3-rc3, right?
https://dist.ipfs.io/go-ipfs/v0.4.3-rc3  (the download link in dist.ipfs.io
is the release, and doesn't show next release's RCs next to it yet)

**Comment by japzone1** [comment]
Yes. I noticed the download button was still for .2 and managed to hunt
down .3-rc3.

**Comment by whyrusleeping** [comment]
I think the underlying problem described here has since been resolved. If this happens again to anyone, please open a new issue.
