### ISSUE TITLE
Build: multiple GOPATH components 

### ISSUE THREAD

**Issue by djdv** [ipfs/go-ipfs#2947]
Version/Platform/Processor information (from `ipfs version --all`):
N/A
Type (bug, feature, meta, test failure, question):
Bug
Area (api, commands, daemon, fuse, etc):
Build system
Priority (from P0: functioning, to P4: operations on fire):
P1

Description:
A patch was merged https://github.com/ipfs/go-ipfs/pull/2808 that resolved this issue but was reverted https://github.com/ipfs/go-ipfs/pull/2862 there was no original issue ticket filed, I am filling this one so that the revert issue (https://github.com/ipfs/go-ipfs/issues/2833) may be closed without dropping awareness of the issue.

Original text by @karalabe from https://github.com/ipfs/go-ipfs/pull/2808 below:

Go's `GOPATH` environment variable can contain multiple paths, separated by a colon `:` similar to the `PATH` env var. In such cases Go uses the first path element to install any packages, however the remaining paths are still used to find dependencies. Because of this it's quite a common setup to have multiple paths listed in GOPATH (e.g. one for development and another for appengine, which has its special installer).

The current Makefile however erroneously assumes that `GOPATH` contains a single path element, and tries to locate go-ipfs within by appending a string to `GOPATH`, which is obviously cause an invalid path, and hence fail the `path_check` rule in the Makefile, even though the required condition is met.

**Comment by Kubuxu** [comment]
I think the problem is that in Windows the path separator would be `;`.

So we would need if we run `Windows && !Cygwin` then change the path separator to `;`.
