### ISSUE TITLE
curlftpfs and ipfs

### ISSUE THREAD

**Issue by scriptzteam** [ipfs/go-ipfs#2965]
Hello,

just tried this and got error:

I mounted remote ftp via curlftpfs into dir /mnt then i did this ->

ipfs add /mnt/somedironremoteftp/ -r

and got this error:
Error: Post http://127.0.0.1:5001/api/v0/add?encoding=json&progress=true&r=true&stream-channels=true: readdirent: input/output error

Also on daemon this error -> 19:04:59.391 ERROR commands/h: err: multipart: NextPart: unexpected EOF handler.go:287

Any fix on this?

**Comment by whyrusleeping** [comment]
ipfs is encountering some error while walking through the directory. It feels like this is coming from the mountpoint, its likely that curlftpfs is bugging out. If you can reproduce this issue on something like sshfs i'll take another look.

**Comment by whyrusleeping** [comment]
Issue has been inactive for over a year, going to close this for now, please reopen as needed
