### ISSUE TITLE
After applying #2830, build on OpenBSD still fails

### ISSUE THREAD

**Issue by pranomostro** [ipfs/go-ipfs#2967]
Hello,

I have followed the instructions in described in  #2830, but
unfortunately I get another error message.

I am also using OpenBSD (5.9), with go version go1.5.3 openbsd/386.

Here is the error message: if I run `go build -tags=nofuse` directly in the cmd/ipfs:

```
# gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/poll
../../../gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/poll/poll_bsd.go:24: cannot use uint64(fd) (type uint64) as type uint32 in field value
```

I am trying to build ipfs 0.4.2, using gx version 0.8.0.

Is this rather a gx issue? If yes, I will open an issue there (I got gx running on my system, though).

Thanks in advance.

**Comment by whyrusleeping** [comment]
@pranomostro this is an issue with the go-reuseport dependency. We need to do better handling here for the 386 architecture on bsd

**Comment by pranomostro** [comment]
Thank you.

You're doing great work here.

**Comment by Stebalien** [comment]
This has been fixed.
