### ISSUE TITLE
too many open files during heavy fetching

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2970]
running a gx install against the local daemon fails (at 6912f47a446e61f6a4168fc859b0d9ade501a2ca) with 'too many open files' errors.

This is fairly recent, i didnt have the issue with a daemon running on 2df8dc5

**Comment by Kubuxu** [comment]
Can't replicated using used repo and `ls -1 /proc/$IPFSPID/fd | wc -l`.

**Comment by Kubuxu** [comment]
Can't replicated using used repo and `ls -1 /proc/$IPFSPID/fd | wc -l`.

**Comment by Kubuxu** [comment]
@whyrusleeping I think it is resolved with the backing out we do. Can you confirm?

**Comment by whyrusleeping** [comment]
@Kubuxu I recently saw an issue with pinning a massive object that resulted in printing a bunch of these too many open file descriptor issues. I'm not sure if we want to keep this open or not for that

**Comment by Kubuxu** [comment]
I see error logs about backlog quite regularly but everything works after it. If that is the case it might be worth just downgrading those logs to warning.

**Comment by whyrusleeping** [comment]
@Kubuxu I think we can probably drop those error messages down to warnings, except in the case where were having a large enough delay.

**Comment by whyrusleeping** [comment]
I don't see this anymore.
