### ISSUE TITLE
Send a message for `--version`

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipfs#2976]
Type (bug, feature, meta, test failure, question): Feature
Area (api, commands, daemon, fuse, etc): CLI
Priority (from P0: functioning, to P4: operations on fire): P0

Description:

> I type `ipfs --version` a lot, and it tells me nothing just `Error: Unrecognized option 'version'`. Would be nice to be able to have `--version` also return something, just like `ipfs --help` does.

From my issue in https://github.com/ipfs/ipfs/issues/158.

**Comment by whyrusleeping** [comment]
This has already been done apparently
