### ISSUE TITLE
t0040 test failure (appears random)

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2978]
Version/Platform/Processor information (from `ipfs version --all`):
Travis CI

Type (bug, feature, meta, test failure, question): 
Area (api, commands, daemon, fuse, etc): add
Priority (from P0: functioning, to P4: operations on fire): P1

Description:

Odd failure having something to do with pipes

https://travis-ci.org/ipfs/go-ipfs/jobs/145829692

**Comment by lgierth** [comment]
One more: https://travis-ci.org/ipfs/go-ipfs/jobs/146666577

Seems like it's killing the daemon and then adding stuff? That sounds sketchy.

**Comment by Stebalien** [comment]
For the record, that pipe error is unrelated (and fixed in 39197ff8d3d2a9f8197d486592b1fc7518008a5d).

This looks fixed (we no longer attempt to add files after killing the daemon...).
