### ISSUE TITLE
Issue template suggests `ipfs version --all` which is unavailable

### ISSUE THREAD

**Issue by yuvallanger** [ipfs/go-ipfs#2982]
# Version/Platform/Processor information (from `ipfs version --all`):

ipfs 0.4.2

# Type (bug, feature, meta, test failure, question):

meta

# Area (api, commands, daemon, fuse, etc):

commands

# Priority (from P0: functioning, to P4: operations on fire):

P?

# Description:

The template suggests:

```
    Version/Platform/Processor information (from `ipfs version --all`):
```

But `--all` is an unrecognized option of the subcommand:

```
$ ipfs version --all
Error: Unrecognized option 'all'
```

**Comment by Kubuxu** [comment]
It will be available on days (0.4.3-rc1).

**Comment by lgierth** [comment]
Let's keep this open though while there's no final 0.4.3 release -- it's still an issue and everybody opening an issue might run into it :)

**Comment by lgierth** [comment]
0.4.3-rc1 is now available on https://dist.ipfs.io so `ipfs version --all` now works.
