### ISSUE TITLE
`ipfs add -s` help?

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#2985]
Version/Platform/Processor information (from `ipfs version --all`): 0.4.2-1a8fc59
Type (bug, feature, meta, test failure, question): documentation bug
Area (api, commands, daemon, fuse, etc): commands
Priority (from P0: functioning, to P4: operations on fire): 

Description:

I believe the `ipfs add` help used to give examples of how to use the `-s, --chunker` option, i.e. what values to feed in. that seems completely gone in 0.4.2 and now people cannot use that option because nothing tells them how to.

This may be fixed in 0.4.3?

cc @RichardLitt @whyrusleeping

**Comment by RichardLitt** [comment]
I can't find any examples of `--chunker` in git for `ipfs add`.

@whyrusleeping Any idea where I can find what values work for `chunker`? I can't seem to track it down.

**Comment by hmeine** [comment]
The solution is linked to from the FAQ: https://github.com/ipfs/faq/issues/214

I was missing the option in the python api ( https://github.com/ipfs/py-ipfs-api/ ), but then I am not sure whether this is available from the rest API at all, or whether it is somehow done in the frontend? (This would also have implications on how easy it would be to implement custom, domain-specific chunkers.)

**Comment by Stebalien** [comment]
(documented)
