### ISSUE TITLE
Nil pointer dereference in dht/routing

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#2987]
Version/Platform/Processor information (from `ipfs version --all`):

Basically 0.4.3-rc1

```
$ ssh root@`dig +short venus.i.ipfs.io` docker exec -i ipfs ipfs version --all
20:27:19.237  INFO   cmd/ipfs: IPFS_PATH /data/ipfs main.go:297
go-ipfs version: 0.4.3-dev-566c08e
Repo version: 4
System version: amd64/linux
Golang version: go1.6.3
```

Type (bug, feature, meta, test failure, question): bug
Area (api, commands, daemon, fuse, etc): dht
Priority (from P0: functioning, to P4: operations on fire): 2

Description:

Only got this short dump:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x0]

goroutine 8775155 [running]:
panic(0xe7ac20, 0xc82000e0a0)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).findProvidersAsyncRoutine(0xc8201ae630, 0x7f62cf5e2c88, 0xc82460ff80, 0xc823ba8960, 0x22, 0x3, 0xc829934b40)
	/go/src/github.com/ipfs/go-ipfs/routing/dht/routing.go:385 +0x88b
created by github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).FindProvidersAsync
	/go/src/github.com/ipfs/go-ipfs/routing/dht/routing.go:306 +0x1d6
```

**Comment by Kubuxu** [comment]
This error shouldn't happen, there is if condition right before that checking if the variable isn't null.

Me and @whyrusleeping came up with explanation that it would have to be either Go or System level race condition, where caches didn't get flushed and re-fetched from RAM.

**Comment by whyrusleeping** [comment]
That said, please let us know immediately if this happens again. I just cant see a cause for this, and the race detector doesnt show anything here.
