### ISSUE TITLE
Integrate ipfs to ios,the app crashed after enter background exceed 7 minutes.

### ISSUE THREAD

**Issue by zyzhangyang** [ipfs/go-ipfs#2994]
Version/Platform/Processor information (from `ipfs version --all`):ipfs version --all

Type (bug, feature, meta, test failure, question):bug
Area (api, commands, daemon, fuse, etc):etc
Priority (from P0: functioning, to P4: operations on fire):P2

Description:
I have used gomobile bind to integrate ipfs to ios app.When the app enter background exceed 7 minutes or more,the app will crash.I need help to figure out what happend,and how to fix it.

The stacktrace is as below:

```
* thread #7: tid = 0x24f23b, 0x000000010007bd24 TestIpfs`notok + 4, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)

  * frame #0: 0x000000010007bd24 TestIpfs`notok + 4

    frame #1: 0x000000010007be80 TestIpfs`runtime.madvise + 32

    frame #2: 0x00000001000286e4 TestIpfs`runtime.sysUnused + 52

    frame #3: 0x00000001000378bc TestIpfs`runtime.scavengelist + 332

    frame #4: 0x0000000100037974 TestIpfs`runtime.(*mheap).scavenge + 132

    frame #5: 0x00000001000505e4 TestIpfs`runtime.sysmon + 868

    frame #6: 0x00000001000482b8 TestIpfs`runtime.mstart1 + 280

    frame #7: 0x0000000100048188 TestIpfs`runtime.mstart + 120

    frame #8: 0x000000010078c23c TestIpfs`crosscall1 + 48

    frame #9: 0x000000010078bb14 TestIpfs`threadentry + 84

    frame #10: 0x00000001976bbdc8 libsystem_pthread.dylib`_pthread_body + 164

    frame #11: 0x00000001976bbd24 libsystem_pthread.dylib`_pthread_start + 160

    frame #12: 0x00000001976b8ef8 libsystem_pthread.dylib`thread_start + 4`
```

**Comment by whyrusleeping** [comment]
I really don't know whats going on here. That looks like a stack dump from ios, I don't see anything actually ipfs related in it either. The closest thing i see is what looks like the golang garbage collector running. I would try filing this as a bug in the go-mobile project

**Comment by xuruijing** [comment]
@zyzhangyang         Is Integrate ipfs to ios complete？

**Comment by Stebalien** [comment]
Closing due to age.
