### ISSUE TITLE
error : context deadline exceeded

### ISSUE THREAD

**Issue by aronayne** [ipfs/go-ipfs#2998]
Version/Platform/Processor information (from `ipfs version --all`):
version 0.4.2

Type (bug, feature, meta, test failure, question):
Area (api, commands, daemon, fuse, etc):
Priority (from P0: functioning, to P4: operations on fire):

Description:

I installed version go-ipfs_v0.4.2_darwin-amd64.tar.gz on mac.

Starting ipfs daemon returns :

```
> ipfs daemon
Initializing daemon...
Swarm listening on /ip4/10.24.56.9/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.7/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
```

I can access the readme : `ipfs cat /ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme`
and quick start guide : 
`ipfs cat /ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/quick-start`

When I try to access links returned by quick-start :

Browse:

webui:
http://localhost:5001/webui

video: http://localhost:8080/ipfs/QmVc6zuAneKJzicnJpfrqCH9gSy6bz54JhcypfJYhGUFQu/play#/ipfs/QmTKZgRNwDNZwHtJSjCp6r5FYefzpULfy37JvMt9DwvXse

images:
http://localhost:8080/ipfs/QmZpc3HvfjEXvLWGQPWbHk3AjD5j8NEN4gmFN8Jmrd5g83/cs

markdown renderer app: http://localhost:8080/ipfs/QmX7M9CiYXjVeFnkfVGf3y5ixTZ2ACeSGyL1vBJY1HvQPp/mdown

they are not responsive.

After approx 10 mins errors are reported on console :

Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
15:05:52.919 ERROR core/serve: Path Resolve error: Failed to get block for QmZpc3HvfjEXvLWGQPWbHk3AjD5j8NEN4gmFN8Jmrd5g83: context deadline exceeded gateway_handler.go:510
15:06:18.581 ERROR core/serve: Path Resolve error: Failed to get block for QmU3o9bvfenhTKhxUakbYrLDnZU7HezAVxPM6Ehjw9Xjqy: context deadline exceeded gateway_handler.go:510
15:07:06.504 ERROR core/serve: Path Resolve error: Failed to get block for QmVc6zuAneKJzicnJpfrqCH9gSy6bz54JhcypfJYhGUFQu: context deadline exceeded gateway_handler.go:510
15:09:15.659 ERROR core/serve: Path Resolve error: Failed to get block for QmU3o9bvfenhTKhxUakbYrLDnZU7HezAVxPM6Ehjw9Xjqy: context deadline exceeded gateway_handler.go:510

On browser error is :
Path Resolve error: Failed to get block for QmZpc3HvfjEXvLWGQPWbHk3AjD5j8NEN4gmFN8Jmrd5g83: context deadline exceeded

I've installed ipfs as per guide : https://ipfs.io/docs/getting-started/

Do these errors point to a specific issue ?

Following guide at https://github.com/ipfs/go-ipfs ipfs appears to be setup correctly locally as can successfully test : 
echo "hello world" > hello
ipfs add hello
ipfs cat

**Comment by Kubuxu** [comment]
Can you try updating to `0.4.3-rc1` from https://dist.ipfs.io ?

**Comment by adrian-git-hub-user** [comment]
I've updated : 

ipfs version
ipfs version 0.4.3-dev

But same issue.

**Comment by adrian-git-hub-user** [comment]
This may have occured due to incorrect hash value 'QmZpc3HvfjEXvLWGQPWbHk3AjD5j8NEN4gmFN8Jmrd5g83' when I used hash returned by echo "hello world" > hello
ipfs add hello

to access it succeeds. So http://localhost:8080/ipfs/<HASH_VALUE> returns "hello world"

**Comment by whyrusleeping** [comment]
I think this is resolved now. Please reopen as needed
