### ISSUE TITLE
How can i shutdown ipfs daemon gracefully?

### ISSUE THREAD

**Issue by haiheipijuan** [ipfs/go-ipfs#3000]
Version/Platform/Processor information (from `ipfs version --all`):
go-ipfs version: 0.4.3-dev-745c093
Repo version: 4
System version: amd64/darwin
Golang version: go1.6

Type (bug, feature, meta, test failure, question):question
Area (api, commands, daemon, fuse, etc):commands，daemon
Priority (from P0: functioning, to P4: operations on fire):

Description:
Now I want to write a command-line command to shutdown  ipfs daemon gracefully. Can you give me some advice?

**Comment by JesseWeinstein** [comment]
From `ipfs daemon --help`:

>   To shutdown the daemon, send a SIGINT signal to it (e.g. by pressing 'Ctrl-C')
>  or send a SIGTERM signal to it (e.g. with 'kill'). It may take a while for the
>  daemon to shutdown gracefully, but it can be killed forcibly by sending a
>  second signal.

**Comment by haiheipijuan** [comment]
I know this. I mean, I wanted to write a sub-commands such as (ipfs daemon shutdown), then I should send an interrupt signal to whom?

**Comment by whyrusleeping** [comment]
an `ipfs daemon shutdown` command would need to cancel the 'master' context used by the command invocation for the daemon. You would have to make some changes in cmd/ipfs/main.go and cmd/ipfs/daemon.go.

**Comment by haiheipijuan** [comment]
OK，thank you！I will try.

**Comment by a2468834** [comment]
[Update] At version 0.9.1, it's `ipfs shutdown` now.
(1) Open another terminal
(2) Enter `ipfs shutdown`.
(3) The original ipfs deamon active terminal will stop running.
