### ISSUE TITLE
ipfs refs ignores options ( --format, --edges, --unique)

### ISSUE THREAD

**Issue by JesseWeinstein** [ipfs/go-ipfs#3001]
ipfs version 0.4.2

Type: bug
Area: commands
Priority: P0

Description: The `ipfs refs` command appears to ignore the documented options `--format`, and `--edges` (and maybe `--unique`, I'm less sure how to test that).

**Comment by RichardLitt** [comment]
Are there tests for these? Might be helpful to write some, if not.

**Comment by Kubuxu** [comment]
Just replicated that, working on it.

**Comment by Kubuxu** [comment]
Only `--edges` was ignored.

**Comment by JesseWeinstein** [comment]
I've confirmed that `--format` works (I must have tried it with `local`, or something else). I'm not sure of a good example hash to use to test `--unique`.
