### ISSUE TITLE
Many commands are erroneously printing "Reading from stdin" info message

### ISSUE THREAD

**Issue by thomas-gardner** [ipfs/go-ipfs#3002]
Version/Platform/Processor information (from `ipfs version --all`):
```
commit: d742fb1...

$ ipfs version --all
go-ipfs version: 0.4.3-dev-
Repo version: 4
System version: amd64/linux
Golang version: go1.6.3
```
Type (bug, feature, meta, test failure, question): `bug`
Area (api, commands, daemon, fuse, etc): `commands/files|cli`
Priority (from P0: functioning, to P4: operations on fire): `P0`

Description: As in the title,
```
go-ipfs|master $ ipfs ls --help 2>&1 |head -n1
ipfs: Reading from /dev/stdin; send Ctrl-d to stop.
```
This is not the intended behaviour.

I think it should be possible to move this message into ReaderFile.Read() so that it isn't printed too early---an example of early printing is  `ipfs dht put foo`.

**Comment by lgierth** [comment]
Another simple way to reproduce this:

```sh
> ipfs add --help
ipfs: Reading from /dev/stdin; send Ctrl-d to stop.
USAGE
  ipfs add <path>... - Add a file to ipfs.
[...]
```

**Comment by whyrusleeping** [comment]
This should be addressed by: https://github.com/ipfs/go-ipfs/pull/3033

Mind testing and verifying?
