### ISSUE TITLE
How to configure ipfs to allow remote connections ?

### ISSUE THREAD

**Issue by adrian-git-hub-user** [ipfs/go-ipfs#3003]
Version/Platform/Processor information (from `ipfs version --all`): 0.4.2

Type (bug, feature, meta, test failure, question): bug / feature
Area (api, commands, daemon, fuse, etc): daemon
Priority (from P0: functioning, to P4: operations on fire): P0

Description:

Can access the various rest URI's from localhost but not from machine name or IP address. Is there an ipfs configuration option to enable remote access over LAN? So can connect using http://(IP_ADDRESS_OF_MACHINE>:8080/ipfs/<HASH> instead of http://localhost:8080/ipfs/<HASH>

---------------------------------------------------
This is for you! Please read, and then delete this text before posting it.
The go-ipfs issues are only for bug reports and directly actionable features.
Check https://github.com/ipfs/community/blob/master/contributing.md#reporting-issues if that doesn't fit.
Check https://github.com/ipfs/go-ipfs/blob/master/docs/github-issue-guide.md if you are not sure how to fill this issue.

**Comment by lgierth** [comment]
Yes, there's the `Addresses.Gateway` setting in the config file, usually at `~/.ipfs/config` -- just set it to `/ip4/0.0.0.0/tcp/8080`.

Please open an issue in https://github.com/ipfs/support if this doesn't work for you.

**Comment by adrian-git-hub-user** [comment]
Yes, that worked. thanks.

My update to ~/.ipfs/config is in bold : 

  "Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ],
    "API": "/ip4/127.0.0.1/tcp/5001",
    "**Gateway": "/ip4/0.0.0.0/tcp/8080"**
  },
