### ISSUE TITLE
Does ipfs use a blockchain ?

### ISSUE THREAD

**Issue by adrian-git-hub-user** [ipfs/go-ipfs#3004]
Version/Platform/Processor information (from `ipfs version --all`): 0.4.2

Type (bug, feature, meta, test failure, question): question
Area (api, commands, daemon, fuse, etc):
Priority (from P0: functioning, to P4: operations on fire): P1

Description:

From reading the ipfs whitepaper : https://github.com/ipfs/papers/raw/master/ipfs-cap2pfs/ipfs-p2p-file-system.pdf ipfs does not appear to make use of the blockchain. 

Blockchain is referenced in the doc here : 

 This forms a generalized Merkle
DAG, a data structure upon which one can build versioned
file systems, blockchains, and even a Permanent Web. 

and here : 

A raw data field and a common link structure are the
necessary components for constructing arbitrary data structures
on top of IPFS. While it is easy to see how the Git
object model fits on top of this DAG, consider these other
potential data structures: (a) key-value stores (b) traditional
relational databases (c) Linked Data triple stores (d)
linked document publishing systems (e) linked communications
platforms (f) cryptocurrency blockchains. 

My understanding before I investigated myself is that somehow utilised a blockchain and formed the assumption that ipfs stored data in blocks, that perhaps were pre-mined. But it seems this assumption is incorrect ? If ipfs does not currently utilise a blockchain are there plans for ipfs to incorporate a blockchain ?

---------------------------------------------------
This is for you! Please read, and then delete this text before posting it.
The go-ipfs issues are only for bug reports and directly actionable features.
Check https://github.com/ipfs/community/blob/master/contributing.md#reporting-issues if that doesn't fit.
Check https://github.com/ipfs/go-ipfs/blob/master/docs/github-issue-guide.md if you are not sure how to fill this issue.

**Comment by RichardLitt** [comment]
Hi @adrian-git-hub-user, thanks for your question! It's a good one. IPFS currently doesn't use a blockchain, but rather MerkleDAGs, which is another kind of graph structure. I would read up a bit more about it. 

If you would like to discuss this further, I would open an issue in [ipfs/faq](https://github.com/ipfs/faq/issues), as this is less about go-ipfs and more about IPFS in general (of which there are several implementations, including js-ipfs). This repository is not the best place to ask this question. Also, in ipfs/faq you can find some issues which may help you answer your own question, like [this one](https://github.com/ipfs/faq/issues/82). 

Can you open another issue, there, not only to get a more detailed answer, but also to help others who may have the same question? Thanks!

**Comment by adrian-git-hub-user** [comment]
Thanks @RichardLitt , question posted here : https://github.com/ipfs/faq/issues/152
