### ISSUE TITLE
bug: executable flags aren't stored in the dag

### ISSUE THREAD

**Issue by knupfer** [ipfs/go-ipfs#3005]
Version/Platform/Processor information (from `ipfs version --all`):

go-ipfs version: 0.4.3-dev-b5fbc01
Repo version: 4
System version: amd64/linux
Golang version: go1.6.2

Type (bug, feature, meta, test failure, question): bug
Area (api, commands, daemon, fuse, etc): file
Priority (from P0: functioning, to P4: operations on fire): P2

Description:

Using `ipfs add foo.sh` results in a non-executable file. This is bad for example for distributing source code with an executable `configure` or for sharing `/bin` between machines via ipfs.

**Comment by hsanjuan** [comment]
Closing in favour of https://github.com/ipfs/go-ipfs/issues/6920.
