### ISSUE TITLE
-enc doesn't seem to work

### ISSUE THREAD

**Issue by JesseWeinstein** [ipfs/go-ipfs#3012]
Version/Platform/Processor: 0.4.2/Debian jessie/x86_64
Type: bug
Area: commands
Priority: P0
Description: When I try to use the short form of `--encoding`, `-enc`, it doesn't seem to be recognized.
```
 ipfs object get QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG -enc json
Error: Unrecognized option 'e'
```

**Comment by Kubuxu** [comment]
You have to use `--enc`.

**Comment by JesseWeinstein** [comment]
OK, then this is a smaller and easier ticket, merely fixing the documentation. I'll have a PR made ASAP.

**Comment by Kubuxu** [comment]
but I can't get `--encoding` to work on `ipfs add`.
