### ISSUE TITLE
Crash with 'Could not resolve name' during fuse mount on OS X

### ISSUE THREAD

**Issue by dokterbob** [ipfs/go-ipfs#3013]
Version/Platform/Processor information (from `ipfs version --all`):
- ipfs version 0.4.2-41c5e11 (repo version 3)
- OS X 10.11.6
- osxfuse 2.8.3 (FuseVersion: 27)

Type (bug, feature, meta, test failure, question): bug
Area (api, commands, daemon, fuse, etc): fuse
Priority (from P0: functioning, to P4: operations on fire): P4

Description:

```
$ ipfs daemon --mount
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/<private>/tcp/4001
Swarm listening on /ip4/<private>/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
12:38:27.074 ERROR  fuse/ipns: looking up /ipns/<unresolvable_hash>: Could not resolve name. ipns_unix.go:98
12:38:27.074 ERROR       node: error mounting: Could not resolve name. mount_unix.go:101
Error: Could not resolve name.
```

Before (until about an hour ago) this worked fine. I have no idea how IPFS ended up trying to resolve this hash upon mounting. Starting the daemon without `--mount` works just fine. Let me know if I can help with further feedback.

**Comment by whyrusleeping** [comment]
@dokterbob thanks for reporting this!

Unfortunately, the fuse part of the codebase hasnt been prioritized for quite some time. It definitely needs some work. If you want to help dig into the code and try and help fix things, that would be very helpful. Otherwise, just keep reporting new issues as you encounter them so that we have a good idea of what to work on

**Comment by karlek** [comment]
I had a similar problem. This comment helped me:
https://github.com/ipfs/go-ipfs/issues/2383#issuecomment-187867923

**Comment by dokterbob** [comment]
@karlek Thanks! This helped. :)
