### ISSUE TITLE
Fuse mounts yield 'Device not configured' after some time

### ISSUE THREAD

**Issue by dokterbob** [ipfs/go-ipfs#3014]
Version/Platform/Processor information (from `ipfs version --all`):
- ipfs version 0.4.2-41c5e11 (repo version 3)
- OS X 10.11.6
- osxfuse 2.8.3 (FuseVersion: 27)

Type (bug, feature, meta, test failure, question): bug
Area (api, commands, daemon, fuse, etc): fuse
Priority (from P0: functioning, to P4: operations on fire): P3

Description:
After starting the daemon with IPFS mounted, requesting a bunch of files from `/ipfs/` results in `Device not configured`. As in:

```
$ stat /ipfs/<hash>
stat: /ipfs/<hash>: stat: Device not configured
```

This error has occurred repeatedly after running an early prototype of an ipfs crawler, using Apache's Tika to index files. The thing is in a very early stage but has been published on GH for purpose of replicating this issue. https://github.com/dokterbob/ipfs-crawler

Sadly enough, while attempting to replicate this issue reliably (without the crawler) I ran into #3013.

**Comment by whyrusleeping** [comment]
We've recently updated the fuse package we import. Mind trying this out again with the latest master?

**Comment by aschmahmann** [comment]
Closing this since there's a lot of work to be done on the fuse implementation. Will be tracking in a meta issue.
