### ISSUE TITLE
no buildable Go source file

### ISSUE THREAD

**Issue by jbshirk** [ipfs/go-ipfs#3016]
0.4.2/Darwin/amd64 (from `ipfs version --all`):

Type (question):
Area (install):
Priority (P1):

Description:
following the compile from source directions at https://github.com/ipfs/go-ipfs

```
# go get -d github.com/ipfs/go-ipfs
can't load package: package github.com/ipfs/go-ipfs: no buildable Go source files in /Users/joe/go/src/github.com/ipfs/go-ipfs
```

I did do the hello.go test on the go getting started and it worked. I don't understand what this error means.

**Comment by lgierth** [comment]
The `go get` method of installing go programs is too limited for go-ipfs, that's why we're using the Gx package manager together with a Makefile -- check out the installation guide: https://github.com/ipfs/go-ipfs#install

**Comment by jbshirk** [comment]
Thank you but as I mentioned, I was following exactly that same page; I saw that mention of Gx but I don't understand what it means or what I am supposed to do... the instruction pages does not say. I also don't understand why the instructions are obsolete (since following them doesn't work and the instructions _say_ they don't work).

**Comment by lgierth** [comment]
Oh sorry, I misread your initial comment! It's definitely not needed anymore since the dependencies are all covered by `make install` -- I just tried it with a completely fresh gopath. Would you like to open a pull request which removes this part from the docs?

cc @Kubuxu @RichardLitt

The "build from source" instructions should be as simple as `git clone && make install`. (The `go get` line is even broken as it should be `ipfs/go-ipfs/cmd/ipfs` there.)

**Comment by jbshirk** [comment]
```
$ git clone && make install
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

**Comment by lgierth** [comment]
Sorry I was paraphrasing for @richardlitt and @kubuxu -- it's the same procedure as described in the guide, except that you can omit the `go get ...` step.

**Comment by jbshirk** [comment]
```
$ cd $GOPATH/src/github.com/ipfs/go-ipfs
$ make install
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```
Following these directions (as modified per above) isn't working for me. I don't know whether it helps, but I add that I recently upgraded from Mavericks to El Capitan, using my time machine backup to preserve everything I had installed before. Maybe that means that developer tools need updating; I don't know. What I do know is that go version go1.6.3 darwin/amd64 is working just fine.

**Comment by jbshirk** [comment]
this info may help:

```
$ xcrun git --version
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
$ git --version
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

**Comment by whyrusleeping** [comment]
@jbshirk it looks like your OSX developer tools are all messed up.

**Comment by jbshirk** [comment]
Oh my, you are right. No idea why but it's gone... I'll fix that. Thanks!

**Comment by jbshirk** [comment]
I'm confused. I've reinstalled latest xcode developer tools. 
continuing from where I left off:

`$ cd $GOPATH/src/github.com/ipfs/go-ipfs`

Then install go-ipfs and its dependencies, including gx and gx-go:

`$ make install`
```
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

$ sudo make install
Password:
*****
You have not agreed to the Xcode license agreements. You must agree to both license agreements below in order to use Xcode.

Hit the Enter key to view the license agreements at '/Applications/Xcode.app/Contents/Resources/English.lproj/License.rtf'
...
By typing 'agree' you are agreeing to the terms of the software license agreements. Type 'print' to print them or anything else to cancel, [agree, print, cancel] agree

You can view the license agreements in Xcode's About Box, or at /Applications/Xcode.app/Contents/Resources/English.lproj/License.rtf

cat install.sh >install 
chmod a+x install

$ make install
make: `install' is up to date.

$ ipfs daemon
Initializing daemon...
Error: Repo has incorrect version: 4
Program version is: 3
Please run the ipfs migration tool before continuing.
See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md
Sorry for the inconvenience. In the future, these will run automatically.

$ ipfs version
ipfs version 0.4.2
```

The whole point of this exercise is that I had inadvertently converted my data to 4, not knowing that there is no binary available yet for the latest version. Following these directions appears to get me right back exactly where I was before: ipfs version 3. What am I missing?

**Comment by thomas-gardner** [comment]
> cat install.sh >install 
> chmod a+x install

Did you type these commands in? Where did you find these instructions?

The Makefile should probably work once the `install` script is removed:

	```
	$ rm install
	$ make install
	```

If that fails you can try this:

	```
	$ gx --verbose install --global
	$ go install ./cmd/ipfs
	```

**Comment by jbshirk** [comment]
@thomas-gardner : no, I did not type the ````cat```` and ````chmod```` commands. Those pooped out of my first make install after installing xcode developer tools to the default location. This, unexpectedly required me to agree to the license as su, and after doing this, those happened. Henceforth I'll put the command in 'code' and the output in italic, to differentiate the two.

After rm install, I tried it again, but the same thing happened:

`$ make install`
_cat install.sh >install 
chmod a+x install_

So this recreates the same install file. I examined their contents and they are ipfs scripts. There must be some path problem.

README.md says that running install.sh will mv ipfs binary to /usr/local/bin/ipfs but this didn't happen. What is there is what I installed in May, which must be the 0.4.2 that reports back from ````ipfs version````

I am not finding any ipfs binary output in my filesystem from doing this today.

**Comment by Kubuxu** [comment]
Can you post the `ls` of `$GOPATH/src/github.com/ipfs/go-ipfs`.

**Comment by jbshirk** [comment]
`$ $GOPATH/src/github.com/ipfs/go-ipfs`
_-bash: /Users/joe/go//src/github.com/ipfs/go-ipfs: is a directory_
`$ ls $GOPATH/src/github.com/ipfs/go-ipfs`
_LICENSE		README.md	build-log	install		install.sh_

**Comment by Kubuxu** [comment]
Ahh, you have to either `go get -d github.com/ipfs/go-ipfs` or `cd $GOPATH/src/github.com/ipfs/go-ipfs && git clone https://github.com/ipfs/go-ipfs.git`.

The `https://dist.ipfs.io` released contain only prebuilt binary.

**Comment by jbshirk** [comment]
Thank you. That is a step forward. However, the result of make install still is unexpected:

`$ cd $GOPATH/src/github.com/ipfs/go-ipfs && git clone https://github.com/ipfs/go-ipfs.git`
_Cloning into 'go-ipfs'... 
remote: Counting objects: 55676, done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 55676 (delta 18), reused 0 (delta 0), pack-reused 55623
Receiving objects: 100% (55676/55676), 23.38 MiB | 5.78 MiB/s, done.
Resolving deltas: 100% (33907/33907), done.
Checking connectivity... done.
`$ make install`
make: `install' is up to date._

**Comment by jbshirk** [comment]
I see what happened... the output of the git clone was to put a child _go-ipfs_ inside ../go-ipfs/. Fixed that and `make install` runs. 

`Install` did not copy the new binary (in ~/go/bin/ipfs) to the previous default location (/usr/local/bin/ipfs)

After copying:
`$ ipfs version`
_ipfs version 0.4.3-dev_

Success! I am up and running with my existing data converted to v.4. 

I appreciate your patience with this. I think the takeaway here is that the docs need to be made a bit clearer, perhaps some work on the "braindead" scripts. But hopefully this experience will help others who run into this situation.
