### ISSUE TITLE
bug: Automatic migration on Win64 failing

### ISSUE THREAD

**Issue by NightRa** [ipfs/go-ipfs#3019]
go-ipfs version: 0.4.3-dev- (0.4.3-rc1 binary)
Repo version: 4 (current is 3)
System version: amd64/windows

Type: bug
Area: automatic migration
Priority: P2

Description:
The automatic migration in 0.4.3-rc1 fails with the following:
```
Initializing daemon...
Found old repo version, migrations need to be run.
Run migrations automatically? [y/N] y
  => checking for migrations binary...
  => usable migrations not found on system, fetching...
fetching url: https://ipfs.io/ipfs/QmUnvqDuRyfe7HJuiMMHv77AMUFnjGyAU28LFPeTYwGmFF/fs-repo-migrations/versions
fetching url: https://ipfs.io/ipfs/QmUnvqDuRyfe7HJuiMMHv77AMUFnjGyAU28LFPeTYwGmFF/fs-repo-migrations/v1.1.0/fs-repo-migrations_v1.1.0_windows-amd64.zip
Error: no migration binary found that supports version 4 - failed to check migrations version: exec: "C:\\Users\\Ilan\\AppData\\Local\\Temp\\go-ipfs-migrate167521031\\fs-repo-migrations": file does not exist
```
The mentioned temporary folder contains only the zip file, unextracted.

**Comment by lgierth** [comment]
The auto-migration relies on dist.ipfs.io having fs-repo-migrations binaries for the platform. Would you be interested in adding windows-amd64 builds? I filed an issue for it: ipfs/distributions#72.

In the meantime, you can simply try `go get -u github.com/ipfs/fs-repo-migrations` and run `ipfs daemon` again. If the daemon doesn't pick that up, you can run `fs-repo-migrations` manually.

**Comment by lgierth** [comment]
Oooh nevermind what I'm saying about adding support for windows-amd64 -- it's supposed to already be there...

**Comment by lgierth** [comment]
The auto-migrations code needs to append `.exe` on windows.

**Comment by NightRa** [comment]
@lgierth From the source & the results I see all the things you mention done:
1. It did download "fs-repo-migrations_v1.1.0_windows-amd64.zip" into the temporary folder.
2. unpack.unpackZip does try to extract a file ending in .exe
But apparently it doesn't?

**Comment by NightRa** [comment]
Maybe it doesn't hit this conditional in unpack.go/unpackZip:
```
if fis.Name == dist+"/"+binnom+".exe"
```

**Comment by whyrusleeping** [comment]
@NightRa could you try building latest master from source and testing that it now works? I tested on a windows server 2012 box and the automatic migrations succeeded for me, but i'd like a bit more confirmation before shipping anything new

**Comment by whyrusleeping** [comment]
marking as closed, please test and reopen if there are more issues or this one hasnt been resolved

**Comment by NightRa** [comment]
@whyrusleeping It does succeed on master. Great!
