### ISSUE TITLE
Failing to install from source on RPi 3 - "unexpected end of JSON input"

### ISSUE THREAD

**Issue by claudiobizzotto** [ipfs/go-ipfs#3020]
Processor information:
Raspberry Pi 3, ARMv7 Processor rev 4 (v7l)

Go version:
go1.6.2 linux/arm

Type:
Bug

Area:
Daemon

Priority:
I've tested the installation on a Ubuntu 14.04 Docker image and everything seemed to work. This might be an ARM thing. It's hard to assign a priority here. Maybe P1?

Description:
I'm following [these steps](https://github.com/ipfs/go-ipfs#build-from-source) to install IPFS from source on a Raspberry Pi 3. When I run `make install`, the installation outputs some error messages complaining about an `unexpected end of JSON input`. Note that below I'm including more output than just the error messages. Also, two or three weeks ago I successfully installed IPFS on a RPi 1 following the same steps and everything worked fine.

``` SHELL
[...]
installation of go-log complete!
  - go-ipfs depends on go-libp2p (QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms)
installing package: go-libp2p-3.3.7
[1 / 34] fetched dep: go-libp2p-peerstore
  - Qmb1US8uyZeEpMyc56wVZy2cDFdQjNFojAUYVCoo9ieTqp not found locally, fetching into /home/pi/go/src/gx/ipfs/Qmb1US8uyZeEpMyc56wVZy2cDFdQjNFojAUYVCoo9ieTqp
  - QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB not found locally, fetching into /home/pi/go/src/gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB
  - QmcrrEpx3VMUbrbgVroH3YiYyUS5c4YAykzyPJWKspUYLa not found locally, fetching into /home/pi/go/src/gx/ipfs/QmcrrEpx3VMUbrbgVroH3YiYyUS5c4YAykzyPJWKspUYLa
ERROR: [2 / 34 ] parallel fetch: failed to fetch package: Qmb1US8uyZeEpMyc56wVZy2cDFdQjNFojAUYVCoo9ieTqp: unexpected end of JSON input
  - QmSscYPCcE1H3UQr2tnsJ2a9dK9LsHTBGgP71VW6fz67e5 not found locally, fetching into /home/pi/go/src/gx/ipfs/QmSscYPCcE1H3UQr2tnsJ2a9dK9LsHTBGgP71VW6fz67e5
ERROR: [3 / 34 ] parallel fetch: failed to fetch package: QmcrrEpx3VMUbrbgVroH3YiYyUS5c4YAykzyPJWKspUYLa: unexpected end of JSON input
ERROR: [4 / 34 ] parallel fetch: failed to fetch package: QmSscYPCcE1H3UQr2tnsJ2a9dK9LsHTBGgP71VW6fz67e5: unexpected end of JSON input
  - QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ not found locally, fetching into /home/pi/go/src/gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ
[...]
ERROR: [29 / 34 ] parallel fetch: failed to fetch package: QmT8rehPR3F6bmwL6zjUN8XpiDBFFpMP2myPdC6ApsWfJf: unexpected end of JSON input
[30 / 34] fetched dep: go-libp2p-secio
ERROR: install deps:%!(EXTRA *errors.errorString=failed to fetch dependencies) 
Makefile:52: recipe for target 'deps' failed
make: *** [deps] Error 1
```

**Comment by whyrusleeping** [comment]
i've not seen this before... This might have been an issue with the gateways. Could you retry this installation?

**Comment by claudiobizzotto** [comment]
I did it yesterday on a RPi 1 and, once more, [it worked](https://github.com/claudiobizzotto/ipfs-rpi). I've used a 64GB SD card, though, whereas my test on the RPi 3 was run on a 16GB one. So I'm starting to think the issue is related to storage and not the RPi model.

I'll try to repeat the same test (64GB SD card) on a RPi3 and see what happens.

Thanks.

**Comment by claudiobizzotto** [comment]
No luck. I've used a larger SD card (64 GB) and the installation still failed on the Pi 3.

**Comment by whyrusleeping** [comment]
@claudiobizzotto do the arm/linux binaries on https://dist.ipfs.io work for you?

**Comment by whyrusleeping** [comment]
I'll need to pick up a raspberry pi 3 to test this out.

**Comment by claudiobizzotto** [comment]
@whyrusleeping, I'm checking the 32 bit Linux binary right now. I didn't even know about dist.ipfs.io before - I'll definitely favour the binary over the build process, if it works.

**Comment by claudiobizzotto** [comment]
The ARM binaries seem to work on all RPi models. I still can't figure why the build process failed on the RPi 3, so I'll leave the issue open and let you guys decide whether you close it or not.

**Comment by eingenito** [comment]
I'm going to close this for age reasons. If it comes up again we can reopen or recreate
