### ISSUE TITLE
Automation of ipfs init return Error: EOF

### ISSUE THREAD

**Issue by fredead** [ipfs/go-ipfs#3029]
Version/Platform/Processor information (from `ipfs version --all`):
ipfs version 0.4.2

Type (bug, feature, meta, test failure, question): bug / feature
Area (api, commands, daemon, fuse, etc): commands
Priority (from P0: functioning, to P4: operations on fire): P0

Description:

When automating an install of ipfs as ipfs take config from STDIN this is return
Error: EOF 

workaround 
command: ipfs init < /dev/null

repeat easily 
echo | ipfw init

notes: 
  In this case i am using ansible but this could happen in others. It would be nice if the error was more informative. Error STDIN config EOF or some such

**Comment by whyrusleeping** [comment]
@fredead this has been addressed since 0.4.2. Could you try out ipfs v0.4.3-rc1 and let me know if that solves the problem?

**Comment by dokterbob** [comment]
Just ran into the same problem, the workaround of `< /dev/null` does it for me - and the problem *does* seem fixed in 0.4.3rc3.

**Comment by Kubuxu** [comment]
This was a bug introduced in 0.4.2 and fixed in 0.4.3-rc1.

**Comment by whyrusleeping** [comment]
close when 0.4.3 is released

**Comment by dokterbob** [comment]
Ok, let's close it then. :)

**Comment by sapk** [comment]
Bug present in docker image ipfs/go-ipfs:latest and works fine too in ipfs/go-ipfs:v0.4.3-rc3

**Comment by lgierth** [comment]
> Bug present in docker image ipfs/go-ipfs:latest and works fine too in ipfs/go-ipfs:v0.4.3-rc3

Yes, a couple of days ago I fixed our docker image versioning. That means `go-ipfs:latest` is v0.4.2.

- `go-ipfs:master` is built from the `master` branch
- `go-ipfs:latest` and `go-ipfs:release` are built from the `release` branch
