### ISSUE TITLE
Significance of key generated by 'ipfs init'

### ISSUE THREAD

**Issue by adrian-git-hub-user** [ipfs/go-ipfs#3031]
Following doc https://ipfs.io/docs/getting-started/ what is the 'peer identity' hash key , this is required to store files on ipfs ?

From 'getting started' doc 
peer identity: Qmcpo2iLBikrdf1d6QU6vXuNb6P7hwrbNPW9kLAH8eG67z
to get started, enter:
  ipfs cat /ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme
Should each of these keys contain same value ?
  
Once I 'ipfs init' and close terminal is the hash key stored on system so can re-access or is it required by user to securely store ?

**Comment by whyrusleeping** [comment]
@adrian-git-hub-user could you move this question to https://github.com/ipfs/faq/issues ?

**Comment by adrian-git-hub-user** [comment]
@whyrusleeping done : https://github.com/ipfs/faq/issues/166
