### ISSUE TITLE
ipfs daemon shutdown command

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3034]
It would be useful to have a command to be able to halt the daemon programmatically, either `ipfs daemon stop` or `ipfs daemon shutdown`. 

Related Issues: 
- https://github.com/ipfs/go-ipfs/issues/3000
- https://github.com/ipfs/go-ipfs/issues/2991

**Comment by whyrusleeping** [comment]
we have this now. `ipfs shutdown`

**Comment by aloknerurkar** [comment]
This is not an issue, but more of a query. I am sorry if this is not the right forum for it but as its specific to this command I was hoping to get some help here.

I am working on something where I programatically start the ipfs node. I was trying to understand the shutdown code.

`
        Run: func(req *cmds.Request, re cmds.ResponseEmitter, env cmds.Environment) error {
		nd, err := cmdenv.GetNode(env)
		if err != nil {
			return err
		}

		if !nd.IsDaemon {
			return cmds.Errorf(cmds.ErrClient, "daemon not running")
		}

		if err := nd.Close(); err != nil {
			log.Error("error while shutting down ipfs daemon:", err)
		}

		return nil
	},
`

The ipfs daemon is running in a separate process. How is this able to stop the same running node? Is there some way this cmdenv is able to share memory between processes?

I might have to go much deeper in code to understand this, so if anyone knows it on the top of their head I would really appreciate it!

**Comment by Stebalien** [comment]
I'd be happy to answer this question on https://discuss.ipfs.io.

**Comment by aloknerurkar** [comment]
> I'd be happy to answer this question on https://discuss.ipfs.io.

Created a topic here:
https://discuss.ipfs.io/t/sharing-memory-in-ipfs-commands/6745?u=aloknerurkar

**Comment by jcomeauictx** [comment]
As of ipfs version 0.8.0-dev, `ipfs shutdown` works, but `ipfs help` doesn't show it. People like me therefore keep trying `ipfs stop`, `ipfs quit`, `ipfs terminate`, ...

**Comment by Stebalien** [comment]
@jcomeauictx please file a new bug. It looks like this was never actually added to the help text.

**Comment by jcomeauictx** [comment]
Thanks, I'll pass for now. If I'm going to file a bug I might as well fix it and submit a pull request, and my plate is already overfull.
