### ISSUE TITLE
`ipfs log level` not working as expected (IPFS 0.4.2)

### ISSUE THREAD

**Issue by harlantwood** [ipfs/go-ipfs#3038]
Version/Platform/Processor information:
```
$ ipfs version --commit 
ipfs version 0.4.2-41c5e11
$ go version
go version go1.6.2 linux/amd64
$ uname -a
Linux 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 
```

Type (bug, feature, meta, test failure, question): bug
Area (api, commands, daemon, fuse, etc): commands
Priority (from P0: functioning, to P4: operations on fire): P0

Description:

Even when I set the log level to critical, I seem to be getting non-error, non-critical logs.  Both with `ipfs log tail`:

```
$ ipfs log level all critical
Changed log level of '*' to 'critical'
$ ipfs log tail 
{"event":"Bitswap.Rebroadcast.active","session":"2f02864e-71b6-4d71-bd22-c5753c25b1ec","system":"bitswap","time":"2016-08-04T03:10:45.697124487Z"}
{"event":"Bitswap.Rebroadcast.idle","session":"2f02864e-71b6-4d71-bd22-c5753c25b1ec","system":"bitswap","time":"2016-08-04T03:10:45.697199453Z"}
...
```

and with `curl http://localhost:5001/logs`:

```
$ ipfs log level all critical
Changed log level of '*' to 'critical'
$ curl http://localhost:5001/logs
{"event":"log API client connected","session":"6480f68c-50ef-4700-965c-406563fcc795","system":"core/server","time":"2016-08-04T03:08:49.264673232Z"}
{"event":"Bitswap.Rebroadcast.active","session":"6480f68c-50ef-4700-965c-406563fcc795","system":"bitswap","time":"2016-08-04T03:08:50.374859831Z"}
...
```

No change if I restart IPFS daemon.

**Comment by harlantwood** [comment]
BTW, `IPFS_LOGGING=<level> ipfs daemon` is working well for me, so this is not an issue for my workflow, just reporting FYI.

**Comment by whyrusleeping** [comment]
the `ipfs log level` commands only control the logs that are printed to stderr, logs output from `ipfs log tail` are event logs and are processed separately.

**Comment by harlantwood** [comment]
Got it, thanks.

**Comment by jbenet** [comment]
Maybe we should move event logs to `ipfs log events`, deprecate but keep
tail as backward compat

**Comment by whyrusleeping** [comment]
I think this can be closed. Please reopen if we still need to address something
