### ISSUE TITLE
How to set proxy in gx ?

### ISSUE THREAD

**Issue by aronayne** [ipfs/go-ipfs#3039]
Version/Platform/Processor information (from `ipfs version --all`):0.4.2

Type (bug, feature, meta, test failure, question): feature
Area (api, commands, daemon, fuse, etc): gx
Priority (from P0: functioning, to P4: operations on fire): P4

Description:

Attempting to install go-ipfs from source (running 'make install') I receive : 
QmVvJ27GcLaLSXvcB4auk3Gn3xuWK5ti5ENkZ2pCoJEYW4 not found locally, fetching into /Users/user/go/src/gx/ipfs/QmVvJ27GcLaLSXvcB4auk3Gn3xuWK5ti5ENkZ2pCoJEYW4
- QmUWER4r4qMvaCnX5zREcfyiWN7cXN9g3a7fkRqNz8qWPP not found locally, fetching into /Users/user/go/src/gx/ipfs/QmUWER4r4qMvaCnX5zREcfyiWN7cXN9g3a7fkRqNz8qWPP
- fetching QmVvJ27GcLaLSXvcB4auk3Gn3xuWK5ti5ENkZ2pCoJEYW4 via ipfs api
- fetching QmUWER4r4qMvaCnX5zREcfyiWN7cXN9g3a7fkRqNz8qWPP via ipfs api

This looks fine but I then receive multiple errors (just displaying one here) : 

ERROR: from shell.Get(): &url.Error{Op:"Post", URL:"http://v04x.ipfs.io/api/v0/get?arg=QmYvsG72GsfLgUeSojXArjnU6L4Wmwk7wuAxtNLuyXcc1T&encoding=json&stream-channels=true", Err:(*net.OpError)(0xc8201b24b0)}

This appears to be a proxy issue. How to set a proxy within gx ? Can it be set from Makefile ?

**Comment by whyrusleeping** [comment]
@adrian-git-hub-user do you use a proxy to access the internet normally?

**Comment by adrian-git-hub-user** [comment]
@whyrusleeping yes I use proxy normally. I set http_proxy & https_proxy variables.

**Comment by Kubuxu** [comment]
https://github.com/ipfs/go-ipfs/pull/4920
