### ISSUE TITLE
change RateIn/RateOut to int

### ISSUE THREAD

**Issue by davidak** [ipfs/go-ipfs#3046]
ipfs version 0.4.2

Type: meta
Area: api
Priority: P0

Description:

```
$ curl http://127.0.0.1:5001/api/v0/stats/bw
{"TotalIn":86659937,"TotalOut":53471597,"RateIn":5138.312239678545,"RateOut":5291.6313566228355}
```

i think we don't need the 12 digits behind the comma.

actually i want to use this values for monitoring and not store unnecessary information.

**Comment by Kubuxu** [comment]
You can just trim them, double floating point is IMO good format for transfer rate.
