### ISSUE TITLE
Implement CIDv1

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3059]
Once the content ID v1 specification is finalized, we need to begin the work of implementing and integrating it into go-ipfs.

This will contain roughly the following tasks:

- [ ] Implement go-multibase
- [ ] implement binary multicodec
- [ ] Implement 'go-cid' (or whatever we choose to call it)
- [ ] integrate into go-ipfs packages:
  - [ ] `blocks` package. `NewBlock` should use CID to 'hash' content, and the `Key()` method should return a CID
  - [ ] `blocks/key` should be able to understand multibase (and when to leave it off for legacy keys?)
  - [ ] `exchange/bitswap` will need to handle sending CIDs and legacy keys in wantlists
  - [ ] `path`:
    - [ ] resolver will need to understand CIDs (might not need to change anything here)
    - [ ] `ParsePath` needs to understand multibase
  - [ ] `core/corehttp`/`commands/http` will need to understand CIDs and multibase encodings
  - [ ] TODO: other integration points

Depends on: 
- [ ] #3055 

Links:

- CIDv1 proposal: https://github.com/ipfs/specs/issues/130

**Comment by jbenet** [comment]
There should be a separate package -- go-cid -- that implements all the
parsing/coding.

**Comment by lgierth** [comment]
- [ ] find a name
  - multiname
  - multid (mul-thai-dee -- maybe too smart?)
  - multiqual (qualifier -- might sound too much like equal)
  - multisym (symbol, which is a synonym of identifier)

**Comment by whyrusleeping** [comment]
multilarsgierth

**Comment by Kubuxu** [comment]
@lgierth for me it looks like it isn't really a part of multiformats suite, it is just bundle of them to be used as object identifiers in IPFS.

**Comment by jbenet** [comment]
I think it should be part of IPLD, it will be usable in other systems

**Comment by whyrusleeping** [comment]
This has been implemented
