### ISSUE TITLE
Code bug

### ISSUE THREAD

**Issue by haiheipijuan** [ipfs/go-ipfs#3063]
Version/Platform/Processor information (from `ipfs version --all`):
go-ipfs version: 0.4.3-rc2-3ba9b67
Repo version: 4
System version: amd64/darwin
Golang version: go1.6

Type (bug, feature, meta, test failure, question):bug
Area (api, commands, daemon, fuse, etc):code
Priority (from P0: functioning, to P4: operations on fire):p1

Description:
code is here: https://github.com/ipfs/go-ipfs/blob/master/blocks/blockstore/arc_cache.go#L63, shoud be "if res {", because we don't need to  to put the key into the cache does not exist.

**Comment by Kubuxu** [comment]
I disagree with your statement, we want to cache both positive and negative `Has` responses. This means: if `Has` call was successful, put it into cache, no matter if it is true or false.

**Comment by haiheipijuan** [comment]
OK, thanks.
