### ISSUE TITLE
ipfs object commands need to be re-thought for ipld

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3067]
the `ipfs object` command group assumes quite heavily that youre manipulating the current structure of protobuf merkledag nodes. We should think about how this command will work once we have ipld objects.

**Comment by jbenet** [comment]
Yep great point.

**Comment by whyrusleeping** [comment]
I'm going to keep the `ipfs object` api the same as it currently is, and use `ipfs dag` moving forward for ipld things

**Comment by whyrusleeping** [comment]
Closing this in favor of `ipfs dag` discussion.

**Comment by mib-kd743naq** [comment]
@whyrusleeping when you say *`ipfs dag` discussion* could you link what are you referring to? Would like to read through that...
