### ISSUE TITLE
How to create IPFS swarm ?

### ISSUE THREAD

**Issue by adrian-git-hub-user** [ipfs/go-ipfs#3072]
Version/Platform/Processor information: 0.4.2
Type (bug, feature, meta, test failure, question): question
Area (api, commands, daemon, fuse, etc): swarm
Priority (from P0: functioning, to P4: operations on fire): P4

Description:

I initialize Initializing daemon on node1, IP of node1 is 10.131.28.5 : 

Swarm listening on /ip4/10.131.28.5/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.1/tcp/4001
API server listening on /ip4/0.0.0.0/tcp/5001
Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080

On node2 I attempt to create a swarm connect command (https://ipfs.io/docs/commands/#ipfs-swarm-connect): 
ipfs swarm connect /ip4/10.131.28.5/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuQQQ
But this returns error : 
Error: connect QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuQQQ failure: dial attempt failed: <peer.ID SD4n7J> --> <peer.ID aCpDMG> dial attempt failed: i/o timeout

maCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuQQQ is the peer identity of node1 , is this the value I should use to connect to node1 ?

What steps have I omitted in setting up an ipfs swarm ?

**Comment by whyrusleeping** [comment]
@adrian-git-hub-user Are you sure thats the correct ip address and peer ID for your peer? The peer ID you listed just appears to be the peer ID of mars (a bootstrap node) with the final few characters changed.

If youre trying to connect to mars, try using: `ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ`

**Comment by adrian-git-hub-user** [comment]
@whyrusleeping 

ipfs swarm connect /ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ

returns : 

Error: connect QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ failure: dial attempt failed: <peer.ID ViRv54> --> <peer.ID aCpDMG> dial attempt failed: i/o timeout

From reading your comment about bootstrap node I found this https://github.com/ipfs/examples/issues/3 which details the default bootstrap nodes, but shouldn't the IP addresses of these nodes match the IP address the machine is running on. 

The command : 
ipfs swarm addrs

returns : 
QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3 (1)
	/ip4/178.62.61.185/tcp/4001
QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM (1)
	/ip4/104.236.179.241/tcp/4001
QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu (1)
	/ip4/128.199.219.111/tcp/4001
QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64 (1)
	/ip4/104.236.76.40/tcp/4001
QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd (1)
	/ip4/178.62.158.247/tcp/4001
QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx (1)
	/ip4/104.236.151.122/tcp/4001
QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z (1)
	/ip4/104.236.176.52/tcp/4001
QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm (1)
	/ip4/162.243.248.213/tcp/4001
QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ (1)
	/ip4/104.131.131.82/tcp/4001

But these nodes cannot be used unless one of the IP addresses and hash values are contained on my network? As 0 machines with one of IP addresses returned by 'ipfs swarm addrs' explains why 'ipfs swarm connect' returns 'timeout' ?

**Comment by adrian-git-hub-user** [comment]
Here are steps I followed in order to setup a swarm on IPFS

HOST1 : 
ipfs init
initializing ipfs node at /root/.ipfs
generating 2048-bit RSA keypair...done
peer identity: <PEER_IDENTITY_HASH_HOST1>

ipfs daemon
Initializing daemon...
Swarm listening on /ip4/<HOST1_IP_ADDRESS>/tcp/4001
...

HOST2 : 
Initialise daemon also on HOST2
Initializing daemon...
Swarm listening on /ip4/<HOST2_IP_ADDRESS>/tcp/4001
...

ipfs swarm connect /ip4/<HOST1_IP_ADDRESS>/tcp/4001/ipfs/<PEER_IDENTITY_HASH_HOST1>
connect <PEER_IDENTITY_HASH_HOST1> success

* Note : iptables firewall could be blocking port 4001, to open port  try on HOST1 : 'sudo iptables -I INPUT -p tcp -m tcp --dport 4001 -j ACCEPT'
* If command 'ipfs swarm connect' is successful HOST1 and HOST2 are now binded to each other

HOST1 : 
ipfs swarm peers
/ip4/<HOST2_IP_ADDRESS>/tcp/4001/ipfs/<PEER_IDENTITY_HASH_HOST2>

HOST2 : 
ipfs swarm peers
/ip4/<HOST1_IP_ADDRESS>/tcp/4001/ipfs/<PEER_IDENTITY_HASH_HOST1>

**Comment by whyrusleeping** [comment]
@adrian-git-hub-user glad you got it working!
