### ISSUE TITLE
Object links command is not giving an answer for IPNS pubkeys

### ISSUE THREAD

**Issue by pfrazee** [ipfs/go-ipfs#3080]
Version/Platform/Processor information (from `ipfs version --all`): 0.4.1/darwin/64-bit

> ~/sites/ipfs-site ipfs version --all
> Error: Unrecognized option 'all'

Type (bug, feature, meta, test failure, question): bug
Area (api, commands, daemon, fuse, etc): commands
Priority (from P0: functioning, to P4: operations on fire): P3

Description:

According to @diasdavid, I should be able to run `ipfs object links <ipns-pubkey>` and get the ipfs hash that it's currently mapped to.

To test this, I published with `ipfs name publish <hash>`, checked that it worked with `ipfs name resolve <pubkey>`, and then tried `ipfs object links <pubkey>`. The links command never responded.

The usecase for this is inside an electron app, so I need one of the [core](https://github.com/ipfs/interface-ipfs-core) commands to do the resolution. Otherwise, I'd just use name-resolve.

Thanks

**Comment by Kubuxu** [comment]
Are you using `ipfs object links /ipns/<pubkey>`?

**Comment by pfrazee** [comment]
@Kubuxu no, I just did `<pubkey>`. Adding the `/ipn/` prefix didnt solve it

**Comment by pfrazee** [comment]
Wait! I take it back. It took a while, but adding the prefix solved it

**Comment by pfrazee** [comment]
Thanks, yes that solved it. It's *very* slow, but it works

**Comment by jbenet** [comment]
yeah we need to make this much faster!
