### ISSUE TITLE
"invalid peer address" with ipv6 in swarm peer connect

### ISSUE THREAD

**Issue by dokterbob** [ipfs/go-ipfs#3082]
Version/Platform/Processor information (from `ipfs version --all`): 0.4.2
Type (bug, feature, meta, test failure, question): bug
Area (api, commands, daemon, fuse, etc): commands
Priority (from P0: functioning, to P4: operations on fire): P2

Description:
Explicitly connecting to peers works fine for ip4 addresses but with ip6 it yields the following result:

```
$ ipfs swarm peer connect /ip6/<ip6_addr>/tcp/4001/ipfs/<peer_id>
Error: invalid peer address: invalid multiaddr, must begin with /
```

The error results from [/core/commands/swarm.go#L358](https://github.com/ipfs/go-ipfs/blob/master/core/commands/swarm.go#L358), the parse error from which originates from [thirdparty/ipfsaddr/ipfsaddr.go#L57](https://github.com/ipfs/go-ipfs/blob/master/thirdparty/ipfsaddr/ipfsaddr.go#L57) which again reaches into `go-multiaddr`, which seems to be maintained [here](https://github.com/multiformats/go-multiaddr) - and which suggests this is a dependency issue. 

However, actually looking at [the code](https://github.com/multiformats/go-multiaddr/blob/f3dff105e44513821be8fbe91c89ef15eff1b4d4/codec.go#L24) it seems this is just a regular string split and something might be fishy about the command argument parser. (This is about as far as I'm willing to follow down this rabbit's hole, for now.)

**Comment by whyrusleeping** [comment]
@lgierth wanna see if you can figure this one out?

**Comment by VictorBjelkholm** [comment]
Might be related to using go-ipfs on windows, see https://discuss.ipfs.io/t/ipfs-swarm-connect-command-returns-an-error/696/7

**Comment by lgierth** [comment]
I mean, it would be useful to see the actual multiaddr that caused this error ;)

**Comment by VictorBjelkholm** [comment]
@lgierth it seems related to the environment and `/` rather than the actual IP/port in the multiaddr.

**Comment by whyrusleeping** [comment]
Ah yeah, as @Kubuxu labeled, this is a problem with arguments starting with '/' in windows. ref #4190

**Comment by Kubuxu** [comment]
Closing in favour of https://github.com/ipfs/go-ipfs/issues/4190.
