### ISSUE TITLE
add `ipfs dht provide` command

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3099]
It would be nice to have a provide command as part of the ipfs dht subcommands. I think its the only DHT rpc not currently exposed through the api

**Comment by jbenet** [comment]
@whyrusleeping the "providing" system is above the dht, it _uses_ the dht -- well it uses any `libp2p.ContentRouting` interface. in go-ipfs, this is implemented in the dht, but that's historical. 

so i'd make an `ipfs provide` command instead.
