### ISSUE TITLE
How is the distribution of data finally organised?

### ISSUE THREAD

**Issue by Kuurusch** [ipfs/go-ipfs#3108]
Hey, 
It's not really a bug-report but it's a little difficult to find the right place to place my question.
How is it at the moment exactly solved to distribute data?
So when I place some data in ipfs, how is aqtually download my data or junks from it?
I ask this question because I intend to build a little platform like youtube, based on ipfs and I'm worried what happend, when someone publish a video on this platform and there are a lot of people, who want to watch it from the first moment. Will they then take the data all from my machine or is the data from the first moment distributed and is there a way to controll, where it is distributed over ipfs in the first moment?

**Comment by Stebalien** [comment]
Files are distributed on demand. That is, when you add a file to IPFS it just adds it to your local node (and may advertise it on the network). It isn't sent to any other machine until requested. To answer your question, yes, if everyone starts downloading the file at the same time, they'll all download it from your machine.

However, you can preemptively fetch the file from a public gateway to trick the public gateway into caching it. Unfortunately, there's no nice way to do this other than to just re-download the file from the gateway.

Note: In general, questions like this go on the [FAQ](https://github.com/ipfs/faq).

**Comment by Kuurusch** [comment]
Thanks a lot Stebalien! 
Hm, so the behaviour is like I suspected. What you think out there, wouldn't it be nice to have somehow the possibility to define/join a group of nodes who holds the folder of particular data distributed?

**Comment by whyrusleeping** [comment]
@Kuurusch Take a look at https://github.com/ipfs/notes/issues/58 and https://github.com/ipfs/ipfs-cluster  That seems closer to what youre after. 

And as @Stebalien mentions, try to keep issues on this repo focused on actionable items pertaining to the go-ipfs implementation. 

We have https://github.com/ipfs/faq https://github.com/ipfs/support and https://github.com/ipfs/notes for more general discussion
