### ISSUE TITLE
ipfs daemon repeatedly crashes macOS sierra go 1.7

### ISSUE THREAD

**Issue by timup** [ipfs/go-ipfs#3122]
Version/Platform/Processor information (from `ipfs version --all`):

`ipfs version --all`
Error: unrecognized option 'all'
`ipfs version --commit`
ipfs version 0.4.2-
`ipfs version --repo`
3

macOS 10.12 sierra
go 1.7

Type (bug, feature, meta, test failure, question):

bug

Area (api, commands, daemon, fuse, etc):

daemon

Priority (from P0: functioning, to P4: operations on fire):

P3 - frequently crashes

Description:

running `ipfs daemon` on a fresh install of go, ipfs, with a newly created ipfs repo:
```
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.76.211/tcp/4001
Swarm listening on /ip4/199.255.11.2/tcp/4001
Swarm listening on /ip4/223.154.118.149/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
```
then moments later (~20s):
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x122a926068bb pc=0x16d3f0]
```
followed by this hefty trace: 
https://gist.github.com/timup/f3416c71bc58ca3207629736a638ec46

Prior to upgrading go to 1.7 `ipfs daemon` returned the error:
```
panic: sync: inconsistent mutex state
```
as referenced in #3045 .  Not sure if this is a continuing go/Sierra issue, but wanted to report the change after upgrading to go 1.7.

**Comment by whyrusleeping** [comment]
@timup just to confirm, you did rebuild ipfs after upgrading to go1.7, right? (and restart the daemon)

**Comment by timup** [comment]
@whyrusleeping after upgrading to go1.7 I removed the original ipfs binary and repo, and installed using: https://dist.ipfs.io/#go-ipfs

**Comment by whyrusleeping** [comment]
@timup Ah, yeah. Theres the problem, the binaries on dist are still built with 1.6. You'll have to build from source until the official 0.4.3 release where we will be building with go1.7

**Comment by timup** [comment]
cool cool, thanks for looking into this!
