### ISSUE TITLE
wantlist entries are never cleared from gateway nodes

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3165]
The gateways wantlists seem to just get bigger and bigger as time goes on. We need to be clearing out entries related to gateway requests when each request terminates.

**Comment by lgierth** [comment]
Can wantlist entries be tied to a context?

**Comment by Kubuxu** [comment]
I think we could, I don't know how far we are from passing the context to the bitswap.

Problem arises when there are two different requests wanting the same hash from bitswap.
Solution: reference counting in requests that were called only with context and periodic (?10min?) GC, if context is done, decrease the counter by one, if it is 0, remove the entry from wantlist.

Sounds good? I could get right to it.

**Comment by whyrusleeping** [comment]
@Kubuxu each wantlist entry does have a context associated with it already. The issue is that if multiple requests reference the same block, you end up having to store multiple contexts, and respecting each of them.

**Comment by Kubuxu** [comment]
Resolved by https://github.com/ipfs/go-ipfs/pull/3182
