### ISSUE TITLE
Basic commands use IPFS Core API

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#3172]
Most of the "business logic" buried in the `core/commands` package should use the IPFS Core API. We'll start with the basic commands `add`, `cat`, `get`, `ls`, and `refs`. The rest will follow.

Dependencies:
- [ ] #2876 Gateway uses minimal IPFS Core API
  - for the basic Core API imeplementation

**Comment by kevina** [comment]
Any rewrite of the `add` command is likely to cause me grief with the filestore code (#2634).  I would like to be involved in any rewrite efforts.  I might even be willing to just write the new code for `add` once I know the issues involved.

**Comment by lgierth** [comment]
Closing in favor of #4498
