### ISSUE TITLE
Improve bitswap testing interfaces

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3181]
Right now, its pretty annoying to write a new bitswap test. There is a lot of setup required to create a bitswap instance, this doesnt necessarily always have to be. We should rethink how a bitswap instance is created, instantiated and hooked up to a network.

**Comment by Kubuxu** [comment]
@whyrusleeping are labels correct here?

**Comment by whyrusleeping** [comment]
hush

**Comment by eingenito** [comment]
Closing due to age and many changes to bitswap to allow for easier unit testing.
