### ISSUE TITLE
Expose MFS onto the gateway

### ISSUE THREAD

**Issue by zignig** [ipfs/go-ipfs#3188]
Feature request,

Adding the /mfs/ directory onto the gateway http interface would be useful

as in http://localhost:8080/mfs/< path > , to serve the mutable files.

**Comment by whyrusleeping** [comment]
We should probably make this into a config option, so the user can enable this if they want.

It can be implemented as a read only gateway pretty easily, but it would be pretty cool to have RW access to it available. 

On a slightly different point, it would be really cool to have an ftp server to access mfs with (but that one would definitely be a separate binary)

**Comment by jbenet** [comment]
Would love to see this happen, will be easier to prototype and test this
once we extract the gateway into other repo

**Comment by zignig** [comment]
won't fix
