### ISSUE TITLE
API call to /diag/net?vis=d3 not returning anything

### ISSUE THREAD

**Issue by andreiamatuni** [ipfs/go-ipfs#3190]
go-ipfs version: 0.4.4-dev-0f0cf44
Repo version: 4
System version: amd64/darwin
Golang version: go1.7

Type: bug
Area: api
Priority: P3

Description:

The HTTP API isn't returning results for calls to /diag/net?vis=d3.

It returns the correct data for ?vis=text and ?vis=dot parameters though. Running this on the command line:

```
$: ipfs diag net --vis=d3
```

returns a correct response with the data represented in the d3 format. To test the http api, I used curl with the following commands:

```
curl -i "http://localhost:5001/api/v0/diag/net?vis=text" > curlresult-text.txt
```

```
curl -i "http://localhost:5001/api/v0/diag/net?vis=dot" > curlresult-dot.txt
```

```
curl -i "http://localhost:5001/api/v0/diag/net?vis=d3" > curlresult-d3.txt
```

All of them except the d3 version responded with appropriate data. The d3 version just had the http header and empty body.

**Comment by andreiamatuni** [comment]
I changed the query to:

```
curl -i "http://localhost:5002/api/v0/diag/net?encoding=json&stream-channels=true&vis=d3" > curlresult-d3.txt
```

and it works now. I guess I needed the "encoding=json&stream-channels=true" part for the d3 data.

**Comment by whyrusleeping** [comment]
@andreiamatuni thats really odd that it doesnt produce any output without the extra flags... I'll mark this as a bug and make sure we take a look.

**Comment by andreiamatuni** [comment]
The only reason I added the flags in the first place was because I saw that the go-ipfs-api library adds them as default as part of the shell.newRequest() function.

**Comment by Stebalien** [comment]
This command no longer exists.
