### ISSUE TITLE
bad error if $repodir/api file is bad/corrupted

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#3191]
Version/Platform/Processor information (from `ipfs version --all`):

0.4.3-rc3

Type (bug, feature, meta, test failure, question): bug
Area (api, commands, daemon, fuse, etc): commands
Priority (from P0: operations on fire, to P4: functioning): P4

Description:

bad error if $repodir/api file is bad/corrupted

``` sh
> rm ~/.ipfs/api # clear anything there
> touch ~/.ipfs/api # bad file
> ipfs daemon
Error:  is not a 'thin waist' address
```

It should be something like

```
> ipfs daemon
Error: failed to parse <path-to-repo/api file. If there is no daemon running, just delete it.
You can do this with:
    ps aux | grep ipfs  # check there is no ipfs daemon
    rm <path-to-repo>/api
```

**Comment by whyrusleeping** [comment]
Thats kinda funny actually, It reads the api file, and tries to parse its contents as a multihash. The strange part here is that it succeeds, an empty string is a valid multihash (one with no protocols).

**Comment by whyrusleeping** [comment]
We should validate the address protocols on read instead of have it fail when we go to start up an http client (as i suspect we're now doing).
