### ISSUE TITLE
TestHasIsBloomCached failures

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#3208]
https://travis-ci.org/ipfs/go-ipfs/jobs/159157692

```
--- FAIL: TestHasIsBloomCached (0.03s)
    bloom_cache_test.go:100: Bloom filter has cache miss rate of more than 5%
FAIL
FAIL    github.com/ipfs/go-ipfs/blocks/blockstore   0.053s
```

**Comment by lgierth** [comment]
Another, on OSX this time: https://travis-ci.org/ipfs/go-ipfs/jobs/159136318

**Comment by Kubuxu** [comment]
After 10000 iterations of that test I am unable to replicate this, nither I have any explenation why it failed.

**Comment by Stebalien** [comment]
Saw it again. Isn't just a test bug? Bloom filters are probabilistic (assuming this test isn't supposed to be deterministic...).

**Comment by Kubuxu** [comment]
It is test bug. I will change the test to use deterministic seed.

**Comment by Kubuxu** [comment]
Hmm, it uses deterministic seed. I have no idea how it failed. Looks like I have the same reaction as I had a year ago. https://github.com/ipfs/go-ipfs/issues/3208#issuecomment-246322227

**Comment by Stebalien** [comment]
Moved to https://github.com/ipfs/go-ipfs-blockstore/issues/6
