### ISSUE TITLE
(project-management) Deal with 10-15 Inbox Issues at the end of each sprint call

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/go-ipfs#3211]
_This is not urgent. Consider starting this habit _after_  devcon2._

There are 374 Issues in the Inbox on the [go-ipfs waffle board](https://waffle.io/ipfs/go-ipfs).  Now that we've got the sprint calls down under 30 minutes, consider using a bit of time at the end of each call to deal with 10-15 of those issues -- closing them, refining them, marking them as duplicates, etc.  At that rate you would have your inbox clear within the year, which is way better than still having 400 issues in the inbox a year from now!

**Comment by whyrusleeping** [comment]
That sounds like a good plan to me :)

**Comment by whyrusleeping** [comment]
Going to close this now. The suggestion has been taken to heart <3
