### ISSUE TITLE
crash in tests during add

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3215]
I thought this was an instance of the other issue we've been seeing, but looking more closely at it, it seems that the daemon crashes during an `ipfs add` in the test here:

https://travis-ci.org/ipfs/go-ipfs/jobs/159304039

raw: https://s3.amazonaws.com/archive.travis-ci.org/jobs/159304039/log.txt

We should add some extra code around this to check for this and print out daemon_err in the event something weird happens...

**Comment by Kubuxu** [comment]
This might be connected as failed test is the first one that uses daemon after this message was logged:
```
17:41:36.344 ERROR commands/h: unexpected EOF client.go:247

ok 65 - ipfs add bigfile succeeds

expecting success: 

    	HASH="QmU9SWAPPmNEKZB8umYMmjYvN7VyHqABNvdA6GUi4MMEz3" &&

    	echo "added $HASH bigfile" >expected &&

    	test_cmp expected actual
```
https://travis-ci.org/ipfs/go-ipfs/jobs/159304039#L3944

**Comment by whyrusleeping** [comment]
I think this has been resolved
