### ISSUE TITLE
go-ipfs claims success dialing to a multiaddr without secio, however it fails at secio

### ISSUE THREAD

**Issue by daviddias** [ipfs/go-ipfs#3218]
Version/Platform/Processor information (from `ipfs version --all`):

go-ipfs version: 0.4.4-dev-3722e90
Repo version: 4
System version: amd64/darwin
Golang version: go1.7.1

Type (bug):
Area (commands, daemon):
Priority (from P0: operations on fire, to P4: functioning): P2

Description:

`ipfs swarm connect /ip4/127.0.0.1/tcp/9090` will return 0, although it fails. This happens because it yields success after getting the TCP handshake performed.

Expected behaviour: fail because secio fails.

Ref:
- https://github.com/ipfs/js-ipfs/issues/439

**Comment by lgierth** [comment]
Ideally it'd only succeed if the connection subsequently showed up in `ipfs swarm peers`

**Comment by Stebalien** [comment]
Fixed.
