### ISSUE TITLE
running an older daemon on a newer repo prints confusing error messages

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3221]
Right now if you run an 0.4.2 daemon on a repo thats 'version 4'. It will print:

```
Error: Repo has incorrect version: 4
Program version is: 3
Please run the ipfs migration tool before continuing.
```

The help it prints is incorrect, it should instead say something like "your repo is a newer version that your ipfs binary, please update your ipfs installation or run XYZ to revert your repo"

**Comment by lgierth** [comment]
I can take care of it today

**Comment by whyrusleeping** [comment]
This was actually done in https://github.com/ipfs/go-ipfs/commit/a3bd3bc3

https://github.com/ipfs/go-ipfs/pull/2939
