### ISSUE TITLE
`pubsub ls` subcommand

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#3223]
Would be great to have:

```
# list pubsub subscriptions, only strings
> ipfs pubsub ls --string
<topic-string> <num-peers> <num-messages seen>
<topic-string> <num-peers> <num-messages seen>

# list pubsub subscriptions, only ids
> ipfs pubsub ls --id
<topic-id>
<topic-id>

# list pubsub subscriptions
> ipfs pubsub ls
<topic-id> <topic-string> <num-peers> <num-messages-seen>
<topic-id> <topic-string> <num-peers> <num-messages-seen>
```

reminder:
- `topic string` is the user-chosen topic string
- `topic-id` is the cid/hash of the TopicDescriptor object

**Comment by keks** [comment]
I've been working on pubsub for a while and would like to get it out of the experimental phase. One question I have about this is what is a topic string vs. topic id? It seems that at the moment any string qualifies for a topic id so this is not very clear.

**Comment by whyrusleeping** [comment]
@keks the topic string is a human readable name, this is what we're currently doing when we use pubsub. The next step is to start using the topic descriptor stuff that we've been planning on for a while. Once we do that, the topic id will be the hash of the topic descriptor object.

**Comment by whyrusleeping** [comment]
this has been implemented
