### ISSUE TITLE
resolve-type=false not working for ls in API

### ISSUE THREAD

**Issue by dokterbob** [ipfs/go-ipfs#3231]
#### Version information:

go-ipfs version: 0.4.3-rc4-db509ec
Repo version: 4
System version: amd64/darwin
Golang version: go1.7.1

#### Description:

In order to make link resolution for files relatively fast (to work around #3120), it should be possible to use the API equivalent of `--resolve-type=false` on the `ls` command. However, requesting a URL of the form `/api/v0/ls?arg=<really_good_hasj>&resolve-type=false` happily returns type information.

The likely perpetrator would be the command argument parsing in https://github.com/ipfs/go-ipfs/blob/master/commands/http/parse.go, where arguments are (very) generically parsed to be interpreted as shell commands. As it seems to work for other arguments, it might be related to the `-` in flag.

I have also tried with `resolve-type`, `resolvetype` and `resolve_type`.

**Comment by Kubuxu** [comment]
`resolve-type` will return type information if it is locally available, it will not try to download the blocks needed for type information.

**Comment by Stebalien** [comment]
If either `resolve-type` or `size` is true, we resolve both the type and the size in the json response (doesn't cost us anymore). This is a bit confusing but I'm not sure it's worth trying to fix it.
