### ISSUE TITLE
`file ls` command returning 0 size on requested hash

### ISSUE THREAD

**Issue by dokterbob** [ipfs/go-ipfs#3232]
#### Version information:

go-ipfs version: 0.4.3-rc4-
Repo version: 4
System version: amd64/linux
Golang version: go1.7

#### Description:

When running `ipfs file ls` (_NOT_ `ipfs files ls`), the resulting information on the requested hash (_NOT_ the objects it links to) includes a size which is always 0. For example:
`$ ipfs file ls --enc=json <hash>`

```
{
    "Arguments": {
        "<hash1>": "<hash1>"
    },
    "Objects": {
        "<hash1>": {
            "Hash": "<hash1>",
            "Size": 0,
            "Type": "Directory",
            "Links": [<items>]
        }
    }
}
```

Note "Size" being 0.

Also note that this issue might become irrelevant depending on how listing commands will eventually be sorted out as part of #3056.

**Comment by Stebalien** [comment]
Fixed (although it's still intentionally 0 for directories).
