### ISSUE TITLE
bug: Cannot build: go-ipfs must be built from within your $GOPATH directory.

### ISSUE THREAD

**Issue by ProgVal** [ipfs/go-ipfs#3234]
#### Version information:

git master

#### Type:

Bug

#### Priority:

P3

#### Description:

Every time I run `make build`, I get this: `go-ipfs must be built from within your $GOPATH directory.`

I tried the following:

```
 ipfs@particle  ~/gopath/go-ipfs   master ●  export GOPATH=$PWD
 ipfs@particle  ~/gopath/go-ipfs   master ●  make build
go-ipfs must be built from within your $GOPATH directory.
expected within '/home/ipfs/gopath/go-ipfs' but got '/home/ipfs/gopath/go-ipfs'
Makefile:49 : la recette pour la cible « path_check » a échouée
make: *** [path_check] Erreur 1
 ✘ ipfs@particle  ~/gopath/go-ipfs   master ●  export GOPATH=$HOME/gopath
 ipfs@particle  ~/gopath/go-ipfs   master ●  make build                
go-ipfs must be built from within your $GOPATH directory.
expected within '/home/ipfs/gopath' but got '/home/ipfs/gopath/go-ipfs'
Makefile:49 : la recette pour la cible « path_check » a échouée
make: *** [path_check] Erreur 1
```

I am new to building Go applications, I may have missed something about how `$GOPATH` works.

**Comment by lgierth** [comment]
> `export GOPATH=$PWD`

go-ipfs must be `$GOPATH/src/github.com/ipfs/go-ipfs`, so that it matches the imports in the code. You can move it there, or symlink it (that's what I do).

**Comment by mateon1** [comment]
The GoPath is a Go specific location, if you set GoPath, then use `go get github.com/ipfs/go-ipfs` it should download to the correct directory.

**Comment by ProgVal** [comment]
It works, thanks!
