### ISSUE TITLE
make `res.SetError` accept more input types

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3240]
It would be really great if in the commands lib,  `res.SetError` accepted an interface as its first input type (as opposed to an error, as it currently is). Inside that function we can type switch on the input and if its a string, we call `fmt.Errorf` on it, if its an error we just use it as is, and if its any other type we `fmt.Errorf("%v")` it.

This will make writing commands a good deal cleaner.

**Comment by Stebalien** [comment]
We now return errors.
