### ISSUE TITLE
docker test failure

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3241]
Updating import paths places seems to have broken part of the docker build: https://api.travis-ci.org/jobs/161208304/log.txt?deansi=true

**Comment by lgierth** [comment]
i think this affects the regular manual build too -- fix in ipfs/go-ipfs#40

**Comment by whyrusleeping** [comment]
@lgierth has this been resolved?

**Comment by lgierth** [comment]
Neither of the two links above make any sense to me :+1: I'm just gonna go assume it's resolved.
