### ISSUE TITLE
Replacing Identity PrivKey and PeerID in config throws dht and core errors

### ISSUE THREAD

**Issue by rcurrie** [ipfs/go-ipfs#3245]
#### Description:

Trying to switch a server's private key and ID doesn't seem to work. Shutting down a fresh empty server and replacing just PrivKey and PeerID and then starting the server back up causes errors when accessing data or resolving using ipns. Some functions (ID) still work. I've been assuming I can backup the keys and then if needed tilt up a fresh server and empty repo but retain the same durable ipns address by copying the backed up version into a fresh repo.
#### Steps to recreate

Start ipfs with an empty data directory
ipfs creates a new set of keys and empty repo
Verify everything's working fine (try resolving via localhost:8080/ipns/<hash>

Stop the server and replace PrivKey and PeerID in config with those from another server that is working (could another newly init'd repo)

Start server back up and the logs from the docker show:
Initializing daemon...
Swarm listening on /ip4/104.210.32.107/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.2/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
API server listening on /ip4/0.0.0.0/tcp/5001
Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
Daemon is ready
03:58:51.357 ERROR        dht: no addresses on peer being sent!
                                        [local:<peer.ID duKtoA>]
                                        [sending:<peer.ID SoLSaf>]
                                        [remote:<peer.ID SoLnSG>] handlers.go:75

Try resolving and address:
03:59:26.978 ERROR core/serve: Path Resolve error: Could not resolve name. gateway_handler.go:509

Try getting an ipfs blog by hash:
04:01:54.218 ERROR        dht: no addresses on peer being sent!
                                        [local:<peer.ID duKtoA>]
                                        [sending:<peer.ID VTsDGj>]
                                        [remote:<peer.ID SoLV4B>] handlers.go:75

**Comment by whyrusleeping** [comment]
Thats odd... i'm guessing that we assume something about our peer ID during init. This should definitely be an allowable use-case.

**Comment by rcurrie** [comment]
Tried transplanting ID and PrivateKey with ipfs version 0.4.8-dev and it seems to work just fine so closing.
