### ISSUE TITLE
OSXFUSE failure

### ISSUE THREAD

**Issue by mattseh** [ipfs/go-ipfs#3250]
#### Version information:

go-ipfs version: 0.4.3-
Repo version: 4
System version: amd64/darwin
Golang version: go1.7

#### Description:

I installed osxfuse from their website, as suggested, version 3.5.

When running ipfs mount, I get: "Error: fork/exec /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs: no such file or directory"

Based on this: https://github.com/bazil/fuse/issues/103 it looks like version 3 changed some paths, whereas IPFS is still using old V2 paths.

**Comment by whyrusleeping** [comment]
We should update our bazil/fuse dep then.

**Comment by hmeine** [comment]
Yes, with the latest official FUSE for macOS, the helpers have moved from
``/Library/Filesystems/osxfusefs.fs/Support`` into
``/Library/Filesystems/osxfuse.fs/Contents/Resources``.
Wouldn't it suffice to look in both locations (the latter one first, presumably)?

**Comment by hmeine** [comment]
What is the last known working FUSE for macOS version, then?  Symlinking the above paths does not seem to make ``ipfs mount`` work, and the comments in https://github.com/ipfs/go-ipfs/pull/3413#pullrequestreview-11455879 suggest that versions >= 3.0.0 are not supported yet?

**Comment by Kubuxu** [comment]
It is in our dependency, update for it is queued but we won't be able to test it for next release. For now 3.0.0 is no supported.

**Comment by whyrusleeping** [comment]
We have updated our fuse dep, This should be resolved. Please reopen the issue if problems still exist

**Comment by hmeine** [comment]
Thanks.  Can you clarify when that update happened, i.e. which release it will be / has been part of?
I just tried again with OSXfuse 3.6.3 and IPFS 0.4.10, but without success (`Error: mount_osxfusefs: exit status 64`).

**Comment by whyrusleeping** [comment]
@hmeine it should have been in at least 0.4.8, before closing the issue i installed osxfuse 3.6.3 on macOS high sierra and successfully mounted /ipfs and /ipns with ipfs 0.4.10 (downloaded from dist.ipfs.io)

**Comment by sl37** [comment]
Seems I am out of luck with >>>ipfs mount
My configuration has
`"AgentVersion": "go-ipfs/0.4.17/",
"ProtocolVersion": "ipfs/0.1.0"`
Installed macfuse version is 3.8.2
I am on macOS High Sierra, Version 10.13.6 (17G65).
I get the following error message in the daemon:
`00:19:35.833 ERROR       node: error mounting: mount_osxfusefs: exit status 64 mount_unix.go:93`
Is there any specific information available, which configurations work, which don't, what fixes the developers are working, and how soon a fix can be expected?
Sorry to bother with this. Unfortunately my coding skills are completely inadequate for attempting to come up with a solution myself.

**Comment by melgu** [comment]
\> ipfs mount
results in `Error: mount_osxfusefs: exit status 64`

macOS 10.15.5 (19F101)
ipfs version 0.6.0
osxfuse version 3.10.6
(Both installed via Homebrew)

**Comment by Stebalien** [comment]
Unfortunately, osxfuse has now gone closed source and the fuse library we're using has dropped support for it. We're probably not going to be able to solve your issue.

**Comment by melgu** [comment]
I fixed it myself. It couldn't mount into the root folder on macOS. Mounting into the home folder was possible. Thanks, anyways!
