### ISSUE TITLE
IPFS is available hash

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3256]
It is nice feature to check if IPFS is operational only with having access to hashes (`fs:/ipfs/X`), to check if IPFS is supported (for webpages - see https://github.com/lidel/ipfs-firefox-addon/issues/149).

Currently my best idea is to use autogenerated `index.html` of empty directory as it is always available hash in IPFS but I think it would be better to have dedicated canary content that would be included in every repo of initial IPFS installation (that would also survive GC).

Something like file with content `IPFS is active` for example. Then by requesting this hash using `web+fs:/ipfs/Qm...AAA` one can check if browser supports IPFS.

**Comment by WardCunningham** [comment]
I like this idea. I will suggest users add such a hash before launching the localhost daemon.
```
echo wiki | ipfs add
ipfs daemon
```
This will be required only of the earliest adopters.

**Comment by whyrusleeping** [comment]
We can add such a small file to the welcome docs (that way they are pre-seeded into every node on init)

**Comment by Kubuxu** [comment]
I tired adding it to `assets/` but it gave me an error:
```
bindata: Failed to stat input path '../vendor/dir-index-html-v1.0.0': lstat ../vendor/dir-index-html-v1.0.0: no such file or directory
assets.go:1: running "go-bindata": exit status 1
```

**Comment by whyrusleeping** [comment]
@lgierth any idea on that error?

**Comment by lgierth** [comment]
I have a fix for that in #2997 which is blocked

**Comment by lgierth** [comment]
Specifically ipfs/go-ipfs@ca907c69ccc503dbdcd97ae2a1625d78fab5f07b brings back the dir-index-html dependency which was deleted for the second time already because it's not `import`ed anywhere.

**Comment by whyrusleeping** [comment]
@lgierth what is it blocked on?

**Comment by lgierth** [comment]
js-ipfs-api tests making assumption about init-docs: https://github.com/ipfs/js-ipfs-api/issues/365

I figure just picking that commit over here should work.

**Comment by lgierth** [comment]
#2997 is unblocked and ready
