### ISSUE TITLE
The "delete" button in the web-interface for local data has no effect

### ISSUE THREAD

**Issue by Kuurusch** [ipfs/go-ipfs#3261]
#### Version information:

0.4.2 and 0.4.3

#### Type:

Bug

#### Priority:

P3
#### Description:

In the web-interface under "files" there you can see a list of the local files. If I click under "action" onto the "delete" button (x), it has no effect, say the file stais.

Thanks for fixing this!

**Comment by Kubuxu** [comment]
The webui is separate repo: https://github.com/ipfs/webui

It would be great if you could report it there.

**Comment by Kuurusch** [comment]
Okdoky, thanks!
