### ISSUE TITLE
Potential for race condition in bitswap

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3274]
Making this issue to track a potential race condition in bitswap. When adding a block to bitswap, the incoming block is passed through to the notifications lib and published to anyone waiting for that block. In the case that someone has called `GetBlock` on the block and then we add it locally, two different goroutines would have the same 'block'. This is only a problem in cases where we mutate the node on the adders side after the add call.

Doing a simple `ipfs cat h(X)` in one shell before `h(X)` exists, and then running `ipfs add X` does not even trigger the race detector.

**Comment by whyrusleeping** [comment]
@Stebalien I think we fixed this issue recently, right?

**Comment by magik6k** [comment]
ref https://github.com/ipfs/go-ipfs/pull/4169, looks fixed

**Comment by Stebalien** [comment]
I think this is a non-issue and unrelated. This appears to be about returning the same block object to multiple clients which should be totally fine (they're immutable (well, we copy before mutating at least).

**Comment by eingenito** [comment]
Closing as fixed.
