### ISSUE TITLE
Residual Context goroutines

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3279]
Pollux has quite a number of goroutines running.
It is due to over 7k gourutines stuck in `context.propagateCancal.func1` closure.

Sample:

```
goroutine 4065045863 [select, 8462 minutes]:
gx/ipfs/QmZy2y8t9zQH2a1b8q2ZSLKp17ATuJoCNxxyMFG5qFExpt/go-net/context.propagateCancel.func1(0x7fe83c441040, 0xc42012cf90, 0x7fe83cbc7ce0, 0xc4459e4b80)
    /go/src/gx/ipfs/QmZy2y8t9zQH2a1b8q2ZSLKp17ATuJoCNxxyMFG5qFExpt/go-net/context/context.go:244 +0x174
created by gx/ipfs/QmZy2y8t9zQH2a1b8q2ZSLKp17ATuJoCNxxyMFG5qFExpt/go-net/context.propagateCancel
    /go/src/gx/ipfs/QmZy2y8t9zQH2a1b8q2ZSLKp17ATuJoCNxxyMFG5qFExpt/go-net/context/context.go:249 +0x1de
```

Full debug info fs:/ipfs/QmT4dEtK87CbS8BLdo8zbo95K3SCQoBppdZzC3SwREheoz

**Comment by Kubuxu** [comment]
The reason behind it could be lack of shortcircuiting between gx'ed go-net context and stdlib Context.

Code in question: https://ipfs.io/ipfs/QmZy2y8t9zQH2a1b8q2ZSLKp17ATuJoCNxxyMFG5qFExpt/go-net/context/context.go

**Comment by whyrusleeping** [comment]
Yeah, i bet thats an issue from us having stdlib and older non-stdlib contexts interspersed

**Comment by whyrusleeping** [comment]
This has been resolved
