### ISSUE TITLE
Adding multiple directories does not work

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#3282]
#### Version information: go-ipfs version: 0.4.4-dev-543f611

Adding multiple directories does not work as expected. See #2811.  Fixing this would be difficult due to how commands are sent to the server.  So while #3258 fixes #2811 when adding just files, it will disallow adding of multiple directories unless `-w` is also given.

**Comment by magik6k** [comment]
Not sure what here was broken, but recent changes to add might have fixed whatever was not working, and in my testing everything seemed to work.
