### ISSUE TITLE
Building Old Version of go-ipfs is not possibe

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#3285]
I'm not sure where to put this, but this concerns me.

When I tried to push an older commit to the build-server it could not download a dependency.

Here is the IRC conversation I had with @whyrusleeping (https://botbot.me/freenode/ipfs/msg/74275647/):

> **Oct 05 19:48:56 kevina:**    whyrusleeping: the build servers are having a hard time getting old gx deps: hanging on - running post install for gogo-protobuf: /home/ubuntu/.go_workspace/src/gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV
> **Oct 05 19:49:02 kevina:**    https://circleci.com/gh/ipfs/go-ipfs/5188?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> **Oct 05 19:49:55 kevina:**    and QmQgRCmDMVcbP42bVDgWRZbZnNHRRGSKmmjuU35oKEC7D1
> **Oct 05 19:50:00 kevina:**    https://travis-ci.org/ipfs/go-ipfs/jobs/165379858
> ...
> **Oct 05 21:21:41 whyrusleeping:** not seeing any providers for QmQgRCmDMVcbP42bVDgWRZbZnNHRRGSKmmjuU35oKEC7D1
> ...
> **Oct 05 21:25:25 kevina:**    whyrusleeping: Any ideas how to fix?
> **Oct 05 21:25:38 whyrusleeping:** kevina: uhm... update to newer deps

**Comment by kevina** [comment]
Note: I have many of these deps still on my hard drive.  I will be happy to recreate the hashes and pin them somewhere if someone could walk me though what needs to be done.

**Comment by whyrusleeping** [comment]
You should be able to just cd into the directory (with the package.json), run `gx-go rewrite --undo` and then go up two directories and add the dir with the hash name

**Comment by kevina** [comment]
Okay, the `gx-go rewrite --undo` was the part I was missing before.

**Comment by kevina** [comment]
Okay, I managed either recreate or retrieve all the deps on my hard drive as of about a month ago.  The list is available in [this gist](https://gist.github.com/kevina/f3bb24a41af46c27fe30dbdb3c2db3e7).  Not all of them where lost but it was difficult for me to tell so I just pinned them all.  They are pinned on this node:
```
/ip4/198.74.53.236/tcp/4001/ipfs/QmZMPx9gzP7mQPojPyJvasxtTkk3iGaWorazoc18oRVE2n
/ip6/2600:3c02::f03c:91ff:fe6e:3d74/tcp/4001/ipfs/QmZMPx9gzP7mQPojPyJvasxtTkk3iGaWorazoc18oRVE2n
```
Could you pin these on the gateway or wherever you keep gx dependecies?

#### Notes on recreated the dep.

I has to do a little more than `gx-go rewrite --undo` as it does not rewrite the gx dependency to itself.  For example, if the package was go-libp2p, the it won't undo the `gx/ipfs/QmUuwQUJmtvC6ReYcu7xaYKEUM3pD46H18dFn3LBhVt2Di/go-libp2p/p2p/host` dependency.  Here is what I had to do for each dependency:
 1. gx-go rewrite --undo
 2. write a perl script to undo the self-dep: [fixup.pl](https://gist.github.com/kevina/f5b9a0210254d37921daf9488be955bd)
 3. run gofmt on each `.go` file
 4. rm the empty `.gx/post-install`
 5. `ipfs add -w -H` (the -H in important to get any dot files)

I'm not sure if this was enough to make all the dependencies match but it was enough so that I could pin all the dependencies I had on my hard drive.

**Comment by Kubuxu** [comment]
Thank you for recreating that, we might have lost some due to the pin bug that was in go-ipfs from 0.4.0 to 0.4.4, I will pin them on one of the storage nodes.

**Comment by whyrusleeping** [comment]
@kevina @Kubuxu can this be closed?
