### ISSUE TITLE
error message from reuseport after suspend

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3289]
Hey @Kubuxu not sure how serious this one is or not. But figured i should report it for you.

11:11:53.649 ERROR reuseport-: EpollWait returned error: interrupted system call. Continuing. linux.go:181

**Comment by Kubuxu** [comment]
This just means I have to add it to ignored somehow, matching the string is probably the only way.

**Comment by Kubuxu** [comment]
I could also try matching errno.

**Comment by whyrusleeping** [comment]
matching errno might work, thats a nicer solution IMO. but either way.

**Comment by Kubuxu** [comment]
I have pushed: https://github.com/jbenet/go-reuseport/pull/17/commits/91d76fbb663c048b7a42948c2b8f8740d7231e1b

Can you CR here? I will then propagate it.

**Comment by Kubuxu** [comment]
Pushed https://github.com/libp2p/go-tcp-transport/pull/5

**Comment by whyrusleeping** [comment]
merged libp2p/go-tcp-transport#5

**Comment by whyrusleeping** [comment]
@Kubuxu has this been resolved?

**Comment by Kubuxu** [comment]
I think yes.
