### ISSUE TITLE
Invalid peer address

### ISSUE THREAD

**Issue by viettienbk** [ipfs/go-ipfs#3296]
**ipfs version 0.4.3**
 It error when I connect to other address
`ipfs swarm connect /ip4/192.168.226.1/tcp/4001/ipfs/QmewnG2gBxmTGCUC5qoJqy7srfbdVgmeWb7owquRbMaXec
Error: invalid peer address: invalid multiaddr, must begin with /
`

**Comment by whyrusleeping** [comment]
I've had errors like this before when exec'ing ipfs from other programs, The mistake i had made when doing that was essentially passing a blank argument before the multiaddr argument. 

Are you running this on the command line?

**Comment by freeaccount255** [comment]
@whyrusleeping Yes, I'm running on the command line.
Can you resolve it?

**Comment by Kubuxu** [comment]
@viettienbk are you still having problems with it?

**Comment by whyrusleeping** [comment]
I think this was on windows. I had a similar problem with a leading slash on a cli argument in windows

**Comment by whyrusleeping** [comment]
ref #4190

**Comment by Kubuxu** [comment]
Closing in favour of https://github.com/ipfs/go-ipfs/issues/4190.
