### ISSUE TITLE
ipfs v.0.4.4 is not available in updater

### ISSUE THREAD

**Issue by Kuurusch** [ipfs/go-ipfs#3299]
#### Version information:
v0.4.4

#### Type:
Bug

#### Priority:
P0

#### Description:
Over the ipfs-updater is no v0.4.4 available!

**Comment by lgierth** [comment]
We haven't released it yet

**Comment by lgierth** [comment]
0.4.4 is now released and you can find it through ipfs-update, or https://dist.ipfs.io
