### ISSUE TITLE
Reduce memory usage

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3318]
As part of our resouce consumption reduction milestore, Lets make an effort to get the idle memory usage of an ipfs node down below 100MB. 

Things that could help here are:
- peerstore written to disk
- providers garbage collection smarter
- fewer goroutines per peer connection
- bitswap wantlists to disk

---

**READ BEFORE COMMENTING**

Please make sure to upgrade to the *latest* version of go-ipfs before chiming in. Memory usage still needs to be reduced but this gets better every release.

**Comment by chevdor** [comment]
Yes please! On a small instance, it looks like this:
![screen shot 2016-11-04 at 17 56 42](https://cloud.githubusercontent.com/assets/738724/20014644/1c408f58-a2b8-11e6-9d74-e1b6170f79a5.png)

Guess who is the big one taking all the room ? :)

**Comment by mattseh** [comment]
A nice test for this would be running IPFS on a 512MB VPS. I ran it, using Ubuntu 14.04, running the deamon in the background, and "ipfs get" an 83MB file, the daemon was OOM killed. Testing that the get completes successfully would be nice.

I also got this, which I think is already noted as a bug:

15:19:13.466 ERROR     flatfs: too many open files, retrying in 600ms flatfs.go:121

**Comment by chevdor** [comment]
@mattseh the chart I included above *is* a VPS with 512 MB running pretty much only ipfs and nginx with no swap. IPFS takes way too much, enabling swap is then sadly required.

**Comment by mattseh** [comment]
Agreed, I only tried running it on the tiny VPS to see what the simplest thing was that would kill the deamon.

**Comment by Fladirmacht** [comment]
node js ipfs can kill my 64GB ram server in 2hrs when streaming :(

**Comment by Kubuxu** [comment]
Node js implementation is separate, please report that on js-ipfs repo.

This repo is about go-ipfs implementation.

**Comment by Fladirmacht** [comment]
i try booth, go-ipfs do this the same for me - running fine till out of memory - 0.4.6 ver - is there some way how to solve it, pls?

**Comment by skorokithakis** [comment]
I'm seeing 700 MB RAM usage on my VPS instance as well, it would be great if this could be lowered.

**Comment by timthelion** [comment]
I get OOM killed even on a system with 4 gigs of free memory.

````
root@hobbs:/var/log# dmesg | egrep -i 'killed process'
[764907.341661] Out of memory in UB 2046: OOM killed process 31956 (ipfs) score 0 vm:6157228kB, rss:3875436kB, swap:0kB
[2499620.020001] Out of memory in UB 2046: OOM killed process 25440 (ipfs) score 0 vm:4503708kB, rss:3905584kB, swap:0kB
root@hobbs:/var/log# ipfs version
ipfs version 0.4.10
root@hobbs:/var/log# 
````

Is there any limitation to how much ipfs uses? How does the ipfs.io gateway stay alive? Do you just restart it every time it dies?

**Comment by Kubuxu** [comment]
Our gateways are mostly stable. As a note we are working on  connection closing which should solve most of this issue.

**Comment by pors** [comment]
I have exactly the same issue on a VPS of the same size. I have swapping on and that is what is happening. My VPS provider is complaining :)

@Kubuxu is there an ETA? I'm happy to help test an early version.

**Comment by dokterbob** [comment]
The only way I have been able to more-or-less stably run ipfs in production was inside a memory-constrained container (systemd cgroup), restarting it everytime it crashed because not having 'enough' memory. This was about half a year ago.

Perhaps this should be considered higher priority as some newer features as it does, fundamentally, affect stability and performance of IPFS in a very bad way.

**Comment by timthelion** [comment]
I agree, this and the overall performance of downloading (which is not 
great) are the only things I care about from the IPFS project. Sure, 
there are new features that would be nice, but I can implement those 
easilly myself by using IPLD, its no show stopper to be missing a new 
feature when IPLD is as powerfull as it is. But this IS a bit of a show 
stopper.

**Comment by kpcyrd** [comment]
I'd love to see some improvements as well, I'm currently running high memory instances for ipfs. :)

My memory usage is around 1G and 2G.

**Comment by pors** [comment]
Hey @dokterbob, we meet again :)

**Comment by skorokithakis** [comment]
Don't I get any love, @pors?

**Comment by pors** [comment]
@skorokithakis huh? Scary shit :)

**Comment by whyrusleeping** [comment]
Hey everyone, we identified and resolved a pretty gnarly memory leak in the dht code. The fix was merged into master here: https://github.com/ipfs/go-ipfs/pull/4251

If youre having issues with memory usage, please try out latest master (and the soon to be tagged 0.4.11-rc2) and let us know how things go.

**Comment by skorokithakis** [comment]
Can we get a build uploaded somewhere, for us plebes? Also, how confident are you that this doesn't contain any show-stopping bugs? We're really really wanting to put a less leaky version to production, but we obviously don't love crashes either :/

**Comment by whyrusleeping** [comment]
Yeah, builds will be uploaded once I cut the next release candidate.  We are quite confident there are no show-stopping bugs (otherwise we wouldnt have merged it), but to err on the safe side its best to wait for the final release of 0.4.11

**Comment by whyrusleeping** [comment]
Once dns finishes propogating, the 0.4.11-rc2 builds will be here: https://dist.ipfs.io/go-ipfs/v0.4.11-rc2

The non-dns url is: https://ipfs.io/ipfs/QmXYxv8gK4SE3n1imq1YAyMGVoUDiCPgaSynMqNQXbAEzm/go-ipfs/v0.4.11-rc2

**Comment by dokterbob** [comment]
@pors Nice to run into you again! Still would like to have a proper look at hackpad. How may I contact you? IRC or something?

@whyrusleeping Thanks for another rc. Let's see how this runs. ^^

**Comment by pors** [comment]
@dokterbob you can email me at mark at pors dot net. And we can change to Dutch :)

**Comment by kpcyrd** [comment]
Can we please keep this on topic?

**Comment by skorokithakis** [comment]
I've been running rc2 all day, and memory usage seems much better than before. It's at 16% now whereas it was at 35% before the upgrade, but, given the nature of leaks, we won't know until after a week or so.

**Comment by whyrusleeping** [comment]
@skorokithakis Thanks! Please let us know if you notice any perf regressions, fixing this properly meant putting a bit more logic in a synchronous hot path and we arent yet sure if it will be an issue in real world scenarios.

**Comment by Calmarius** [comment]
More than 4 GB RAM usage here with 0.4.11, according to top:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                     
15384 calmari+  20   0 4797260 2,487g    188 S   3,3 86,2  25:54.47 ipfs                                                                                        
   33 root      20   0       0      0      0 S   0,3  0,0   0:10.12 kswapd0                                                                                     
 1114 mysql     20   0 1246948  12356      0 S   0,3  0,4   0:09.18 mysqld                                                                                      
    1 root      20   0  119780   1304    580 S   0,0  0,0   0:01.96 systemd                                                                                     
    2 root      20   0       0      0      0 S   0,0  0,0   0:00.00 kthreadd                                                                                    
    3 root      20   0       0      0      0 S   0,0  0,0   0:00.64 ksoftirqd/0                                                                                 
    5 root       0 -20       0      0      0 S   0,0  0,0   0:00.00 kworker/0:0H                                                                                
    7 root      20   0       0      0      0 S   0,0  0,0   0:05.87 rcu_sched                                                                                   
    8 root      20   0       0      0      0 S   0,0  0,0   0:00.00 rcu_bh                                                                                      
    9 root      rt   0       0      0      0 S   0,0  0,0   0:00.01 migration/0                                                                                 
   10 root      rt   0       0      0      0 S   0,0  0,0   0:00.07 watchdog/0                                                                                  
   11 root      rt   0       0      0      0 S   0,0  0,0   0:00.07 watchdog/1                                                                                  
   12 root      rt   0       0      0      0 S   0,0  0,0   0:00.01 migration/1                                                                                 
   13 root      20   0       0      0      0 S   0,0  0,0   0:01.08 ksoftirqd/1                                                                                 
```

SSH session became unresponsive, needed to kill the daemon to get my control back.

**Comment by skorokithakis** [comment]
htop reports IPFS taking up 26% of my 4 GB RAM here, which is maybe slightly better than before. I don't think 26% is warranted, especially since IPFS takes up 1% of RAM after a restart.

**Comment by Kubuxu** [comment]
@skorokithakis ipfs network grew a lot in last few weeks. We are finally close to implementing feature we call "connection closing" which should allow you to limit number of connections and thus significantly reduce number of connected peers.

**Comment by skorokithakis** [comment]
@Kubuxu Ah, that'd be fantastic. Will that lead to a corresponding memory usage reduction? I imagine network routing will be largely unaffected with the smaller number of peers, correct?

**Comment by Kubuxu** [comment]
Our primiary connection muxer reserves memory buffer per stream (which usually would be like ~3x #peers). So yes, it will reduce memory usage.

**Comment by whyrusleeping** [comment]
Yeah, we fixed one memory issue (my previous comment) and then in the following couple weeks, the network increased from 1k nodes, to over 6.5k nodes. Since memory usage is mostly linear with the number of peers you have that is causing problems...

**Comment by dokterbob** [comment]
Wow, what caused the sudden increase in nodes?

**Comment by skorokithakis** [comment]
@Kubuxu Do you know when this will be released? My server is getting killed by the IPFS node taking up 30% of all memory.

**Comment by Stebalien** [comment]
@skorokithakis I'd try the RC: https://github.com/ipfs/go-ipfs/releases/tag/v0.4.12-rc1.

**Comment by skorokithakis** [comment]
@Stebalien Fantastic news, thank you.

**Comment by XertroV** [comment]
I've been having memory issues with 0.4.11 (being killed around 2GB of RAM) - going to update to 0.4.12-rc1 and post here if I have issues. (Also have a cron job running every 24 hours to collect up a debug package)

**Comment by skorokithakis** [comment]
Make sure you enable the connection manager as described in the pull request, it's not enabled by default.

**Comment by Kubuxu** [comment]
@skorokithakis it is since: https://github.com/ipfs/go-ipfs/commit/c0d6224f0ecf6d301da4931deb3c12838ea3dcce

**Comment by XertroV** [comment]
Sweeto - so I should be good to compile from the v0.4.12-rc1 tag?

Compiling now - few hiccups with $GOPATH but following the README and checking out v0.4.12-rc1 seems to be working now. 👍

**Comment by Kubuxu** [comment]
We also put RC versions on the dist.ipfs.io: https://dist.ipfs.io/go-ipfs/v0.4.12-rc1

**Comment by mgamsjager** [comment]
Using 0.4.13-rc1 on FreeBSD and with 900 open connections it uses about 288MB of RAM. 

This version seems to fix the lavish amount of RAM it used to occupy before.

**Comment by skorokithakis** [comment]
I hope it works, 0.4.12 uses 1 GB of RAM and that's only because I used cgroups to limit it to that.

**Comment by whyrusleeping** [comment]
> Wouldn't it be more logical to not accept any new connections after the highmark is reached instead of dropping down to the lowmark?

No, because forming new connections is very important for the proper functioning of the network.

0.4.13 shouldnt impact memory usage at all. Its simply a hotfix for a couple bugs we discovered. The next memory usage drop should come when we fix the address storage issues: https://github.com/libp2p/go-libp2p-peerstore/issues/15

**Comment by davidak** [comment]
IPFS used 8.8 GB RAM before i rebootet the system. Has connection to 1125 peers right now.

![screenshot_2017-12-18_06-23-58](https://user-images.githubusercontent.com/91113/34091304-1a6d02f0-e3bd-11e7-959f-fd48bac3276c.png)

**Comment by whyrusleeping** [comment]
@davidak update to 0.4.13, you should see a pretty significant improvement.

**Comment by joesis** [comment]
Just FYI - if you somehow built IPFS code (I know the official releases don't) with `-race` flag, the memory consumption can be 20x times larger. See https://golang.org/doc/articles/race_detector.html#Runtime_Overheads

**Comment by whyrusleeping** [comment]
https://github.com/ipfs/go-ipfs/pull/4509 reduces memory consumption during large `ipfs add` operations.

**Comment by whyrusleeping** [comment]
https://github.com/ipfs/go-ipfs/pull/4525 reduces memory consumption for gateways that are serving large files.

**Comment by klueq** [comment]
0.4.17, 300 MB on a new ipfs init. That's not going to work and the reason is not the tiny VPSes, but Android and iOS phones that usually have 1 GB of RAM with much less available at runtime.

**Comment by klueq** [comment]
As it usually happens, we write software in assumption that a typical user has a 24 CPUs, 32 GB RAM Linux station :)

**Comment by burdakovd** [comment]
Here is another datapoint. On a machine with 1.7 GB of RAM and 3G of swap, running only IPFS daemon in server mode and nginx, after 4 days we see 1.6 GB of RAM used and 550 MB of swap space used.

![image](https://user-images.githubusercontent.com/5193161/46039088-bbd30980-c104-11e8-9fdb-523865068614.png)

**Comment by klueq** [comment]
Can we have a flag to limit the number of peers and some smart logic to discard bad peers and get good ones? That seems to be the unavoidable reason for high memory footprint.

**Comment by dokterbob** [comment]
@klueq Check out the connection manager. https://github.com/ipfs/go-ipfs/blob/419bfdc20fc68d70ba0ea5dc9d0bed8db16c1c11/docs/config.md#connmgr

**Comment by klueq** [comment]
Cool. Looks like it's already there.

Another suggestion is why not to use UDP? From my limited understanding, all those 800 TCP connections with peers are idle 99% of the time, but they have real memory buffers and other overhead on both sides. Instead, we could send a UDP ping from time to time to check if the peer is online and if we need to transfer some data reliably, we send another UDP message, the peer acks it and we create a temporary TCP channel.

**Comment by Kubuxu** [comment]
There is experimental QUIC transport that uses UDP.
Should roll out wider soon-ish.
 https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#quic

**Comment by whyrusleeping** [comment]
The TCP buffers arent the dominating consumer of memory here. Plus, re-establishing a new connection is very much non-trivial.

**Comment by Stebalien** [comment]
The memory issue comes from our *internal* buffers/state. We're constantly working on improving this but it'll take time. (semi related: https://github.com/libp2p/go-libp2p/issues/438)

**Comment by rob-deutsch** [comment]
This is something I've been interested in recently (see #5530) and a reality that we have to contend with is that Go is memory hoggish, and it's getting worse (golang/go#23687).

Go is very reluctant to give any memory back to the OS unless the OS very much needs it.

The practical implications for `go-ipfs` are twofold:
1) **Multiprocessing environments:** Reported memory can include a large amount of memory that Go is hanging on to simply because it can. This is an issue when evaluating memory use in a multithreaded environment. E.g. knowing that two different processes each have resident memory of 1GB is meaningless if - for example - one process only actually has 100MB allocated and the other has 900MB allocated.

2) **Performance:** When time comes for the OS to claw back this memory, which process does it choose to rob it from? 

I think that things would be difficult enough in a world where the Go runtime holds memory that's "in use", "technically in use because caching" and "just because I can". But its even more trickier when the Go runtime only holds memory that's either "in use" or "just because I can".

**Comment by Calmarius** [comment]
I'm running IPFS 0.4.17 on my Raspberry PI (using the low power profile if I remember correctly). When it starts it has low memory usage, But that memory usage slowly climbs up as the hours pass. Within 1-2 days the OOM killer usually kills it. The number of connections are low the "ipfs swarm peers" don't fill the terminal window.

So I think something is leaking there. Or in the Go runtime.

**Comment by whyrusleeping** [comment]
@Calmarius Try 0.4.18. There has been significant work towards reducing memory usage. Likely not fully resolved, but should be noticeably better.

**Comment by dokterbob** [comment]
Maybe put a reference to 0.4.18 in the description so we won't have to tell them about it all the time.

(By the way kudo's on the good work, resource usage is indeed much more stable - although not nearly there yet!) 

Whyrusleeping <notifications@github.com> schreef op 27 november 2018 18:49:01 GMT+00:00:
>@Calmarius Try 0.4.18. There has been significant work towards reducing
>memory usage. Likely not fully resolved, but should be noticeably
>better.

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by Calmarius** [comment]
Yes! Updated to 0.4.18 and it's running without problems for 2 weeks on my rpi. Great progress indeed!

**Comment by voxsoftware** [comment]
0.4.20, using more than 3GB Ram, problem still

**Comment by lordcirth** [comment]
> 0.4.20, using more than 3GB Ram, problem still

Under what load, and after running for how long? Does it cap at 3GB for you, or continue to grow?

**Comment by voxsoftware** [comment]
I am running about 2 days, but really i still not use too much. Continue growring, now is 3.7GB Ram. Under Ubuntu 18.04 package: go-ipfs.

**Comment by whyrusleeping** [comment]
I really wonder whats causing this. mars (our first bootstrapper node, and arguably the most connected to ipfs node) peaks at just over 4GB, but every time I check, that much memory is not actually in use, its just the go runtime refusing to return the memory to the OS.

@Stebalien can we try running that memory profile dumper thing on some machines? https://gist.github.com/whyrusleeping/b0431561b23a5c1d8b2dfce5526751aa

**Comment by voxsoftware** [comment]
Just now was killed the daemon. This makes go-ipfs unusable. Have js-ipfs the same problem?

**Comment by Stebalien** [comment]
@voxsoftware try disabling the DHT by running the daemon with `ipfs daemon --routing=dhtclient`. Also, I'd consider upgrading to the latest RC (go-ipfs 0.4.21-rc3) or just wait for the release (likely tonight or tomorrow).

**Comment by voxsoftware** [comment]
I started with --routing=dhtclient. In about 1 hour, now is 850MB memory. I evaluated using ipfs on desktop app, but with this, I see really still unusable for that purpose

**Comment by skorokithakis** [comment]
Same here. I'm thinking of having systemd restart the daemon once a day, which is, unfortunately, the last thing I'm going to try before giving up on IPFS altogether...

**Comment by lordcirth** [comment]
> Same here. I'm thinking of having systemd restart the daemon once a day, which is, unfortunately, the last thing I'm going to try before giving up on IPFS altogether...

I set a memory cap in systemd. The memory pressure keeps it's usage down, and if it still goes over, it gets automatically killed and restarted. Works well enough.

**Comment by voxsoftware** [comment]
> > Same here. I'm thinking of having systemd restart the daemon once a day, which is, unfortunately, the last thing I'm going to try before giving up on IPFS altogether...
> 
> I set a memory cap in systemd. The memory pressure keeps it's usage down, and if it still goes over, it gets automatically killed and restarted. Works well enough.

Can you give an example please? An this works ok for Linux backend, but, how about using in a desktop app for example in Windows?

**Comment by lordcirth** [comment]
> > > Same here. I'm thinking of having systemd restart the daemon once a day, which is, unfortunately, the last thing I'm going to try before giving up on IPFS altogether...
> > 
> > 
> > I set a memory cap in systemd. The memory pressure keeps it's usage down, and if it still goes over, it gets automatically killed and restarted. Works well enough.
> 
> Can you give an example please? An this works ok for Linux backend, but, how about using in a desktop app for example in Windows?

Like so:
https://gist.github.com/lordcirth/378ae7c3a8d2786874d00867098cbad1

As for Windows, dunno. Haven't used it much in a long time.

**Comment by skorokithakis** [comment]
@lordcirth this is extremely helpful, thank you.

**Comment by Stebalien** [comment]
Closing as stale (most of the issues raised here have been addressed, or are recorded in more specific issues).
