### ISSUE TITLE
Stop using gx/gx-go

### ISSUE THREAD

**Issue by zimbatm** [ipfs/go-ipfs#3327]
Hi,

can I suggest returning back to a standard package management like govendor or Godeps instead of using gx-go?

I think the concept is a neat idea but it increases the complexity for contributors and packagers unnecessarily. Tools like govendor might not be the best to work with but they are mature and well supported.

As an example, I really want to update the NixOS package past January. Unfortunately gx-go doesn't play well in the purely functional package manager. I would have to build a new fetcher, but it requires interaction with the current checkout which is not available in that context. I'm sure I can get it to work with enough efforts but right now I just want to have IPFS installed and working.

In life you have to pick your battles and I think IPFS is more important than gx-go right now.

**Comment by christynelson467** [comment]
how do I ho back

**Comment by christynelson467** [comment]
is there a link to one you recommend.  currently reading bitcoins for
dummies ... I'm going to just use a labtop. I  am  running 1 miner just so
it cam be tested.  hopefully  in the end its just a learing curb for all
lol.  so I guess I  waisted a month trying to learn on my own

**Comment by lgierth** [comment]
@christynelson467 stop commenting random stuff in IPFS github issues. IPFS has nothing to do with Bitcoin. You're welcome to come back when you have questions or suggestions about IPFS.

**Comment by zimbatm** [comment]
Thanks :) Anything to add on the actual ticket?

**Comment by whyrusleeping** [comment]
@zimbatm instead of asking us to change everything up, why not propose how we could make things easier on you?

**Comment by zimbatm** [comment]
The best thing you could do for me as a packager would be to commit the dependencies into the vendor/ folder. If that happens then it doesn't matter what dependency-tracking tool you are using anymore. It would also make it easier for people to build and install go-ipfs using the traditional `go get` utility.

**Comment by whyrusleeping** [comment]
@zimbatm we have been looking into ways to make gx import paths `go get`able such that `go get github.com/ipfs/go-ipfs/cmd/ipfs` would correctly install the dependencies. Would that solve your problem?

**Comment by zimbatm** [comment]
@whyrusleeping yes that might work. What we do with the other go package is map each import with the underlying repo that it's served from and then fetch each repo individually. For example that's the dependency set for `gx`: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/gx/deps.nix

**Comment by zimbatm** [comment]
I still think the current incarnation of `gx` is not a good idea.

1. It uses the file `package.json` which is already taken by the very popular `npm` project.
2. It adds a layer of indirection that hides where the original source code comes from
3. It's harder to access the content as IPFS is not yet widely deployed (and gx is not helping with that).
4. I am not convinced IPFS is a stabler source of information than github right now. I expect old generations of code to disappear as the host publishing the information gets cycled.

I think it would be better if IPFS was added on top of an existing solution to act like a cache. For example if the Godeps.json would also contain a IPFS hash. That way it would be possible to rely on IPFS for speed and integrity checks but it's still optional.

**Comment by PerfectLaugh** [comment]
I agree with @zimbatm 
I also think this is unnecessary to put all the codes on the IPFS, since it is just a source code, unless IPFS is being widely used and having a convenient way to access the source code just as HTTP. 
It makes me harder to access the dependencies of source code. I have to google the name of a package I need to access, and it is unpleasant to see a bunch of hashes in codes, which is too large and unidentifiable as a version identifier. That is hard to me to learn and make contributions to IPFS.
I hope we can resolve this problem somehow.

**Comment by Kubuxu** [comment]
You can look into package.json file or access the hash or do `gx-go rewrite --undo`.

There is no currently an alterative to gx that would satisfy our security and repeatability requirements without bloating the repo itself (we tried Godeps in the past, it didn't work out).

**Comment by whyrusleeping** [comment]
@PerfectLaugh Its actually even easier to see the code for any gx package, just open the hash up on a gateway. ipfs.io/ipfs/<package hash>, and boom. All the code is right there.

**Comment by zimbatm** [comment]
@whyrusleeping what are the availability guarantees of ipfs? In my mind ipfs is less durable than git and I would expect old git checkouts to not be able to resolve some dependencies.

@Kubuxu what security aspects are you specifically concerned with? Are git shas strong and repeatable enough?

**Comment by whyrusleeping** [comment]
I'm going to close this issue. I am not interested in any more discussion about "moving away from gx". 
If you want to discuss how we can improve gx to make it easier on everyone, please open a new issue with suggestions.
