### ISSUE TITLE
Reduce number of threads stuck in sync of datastore

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3329]
Part of my effort for go-ipfs to run on systems with limited threads/processes.

This is done by semaphore in go-ds-flatfs, see: https://github.com/ipfs/go-ds-flatfs/pull/1
It works, needs just review.

**Comment by christynelson467** [comment]
please merge all to fix whatever needed for me. I don't know codes.  keep
saying I  need help. don't know what applies  to me

**Comment by christynelson467** [comment]
I do plan on switching to pc and laptop as well. no mobile or tablet at
all  later tonight  so please merge whatever needed on that as well. if I
need to  invest to learn proper steps and  see profit please just advise.
