### ISSUE TITLE
Improve Garbage Collection Performance

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3333]
IPFS currently has two different garbage collectors that run. The manual `ipfs repo gc`, and the provider cache cleanup routine. Currently, `ipfs repo gc` is very slow, and the providers garbage collection is very ineficient (causes mars to OOM frequently) due to what appears to be the same issue. The problem i've identified so far is that creating `ds.Key`s from the individual datastores, then parsing those back into strings for different types is quite expensive.

Lets try and figure out how to make both of these usecases faster.

**Comment by kevina** [comment]
Related issue: ipfs/go-datastore#40

**Comment by kevina** [comment]
Speeding up `Blockstore.AllKeysChan()` should help improve `ipfs repo gc`, see #3376.  I have not looked into the overhead of creating `ds.Key`s specifically yet; in particular I have not looked at the providers garbage collection code at all.

**Comment by whyrusleeping** [comment]
@kevina i've been looking at the providers GC code recently, i'll push a couple PRs towards improving that soon.

**Comment by kevina** [comment]
Related #3462

**Comment by whyrusleeping** [comment]
I think @kevina has improved the perf of both of these routines pretty decently. Well enough for me to feel okay closing this issue (for now).
