### ISSUE TITLE
Performance: ipfs add I/O (rotational disks)

### ISSUE THREAD

**Issue by donothesitate** [ipfs/go-ipfs#3337]
#### Version information:

go-ipfs version: 0.4.5-dev-634005a
Repo version: 4
System version: amd64/linux
Golang version: go1.7.1
#### Description:

Improve performance of addition/hashing of files by using file extents on filesystems applicable to.
Does slightly up to massively increase throughput on rotational disks, based on device performance and I/O load by rest of the system.

This would likely be done per directory level. Can be further improved by doing traversal first (increase of memory usage for large datasets, therefore should be a command flag).

**Comment by whyrusleeping** [comment]
@donothesitate could you please elaborate on what youre proposing here? I'm not sure exactly what youre after.

**Comment by donothesitate** [comment]
@whyrusleeping 
One can read [file extents](https://en.wikipedia.org/wiki/Extent_(file_systems)) of the underlying filesystem, and therefore effectively convert potentially random I/O into sequential with skips.
This is further amplified by not having to seek for inodes in between.

One example of this is [rmlint](https://github.com/sahib/rmlint).

**Comment by Stebalien** [comment]
This would require a pretty substantial amount of work for unclear gain. While potentially useful, I'm going to close this as something we can reconsider far in to the future.
