### ISSUE TITLE
Config Option For Enabling Filestore?

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#3344]
Right now the filestore is enabled via a special command, and once enabled for a repo it can not be disabled.

When talking to @whyrusleeping he suggested using a Config variable.  **I considered this option but rejected it because once enabled just disabling it might cause problems.**  For example, if any files in the filestore are pinned (even indirectly) than just disabling it would break the pins.

This issue is here to have a written record of the decision.

**Should there be a config option for enabling the filestore?**  And if so, what should the behavior be if the filestore is present and it is disabled in the config file?

**Comment by whyrusleeping** [comment]
I think we should have an option in the config, and if you have the filestore initialized, and then disable the option in the config, it should error out and ask you to 'fix' it somehow.

**Comment by kevina** [comment]
Thanks.  I am fine with that.  I will implement that and close this issue when it is in kevina/filestore.

**Comment by kevina** [comment]
No longer relevant.  Closing.
