### ISSUE TITLE
Regression test for DagService GetLinks optimization of RawNodes

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3362]
So it doesn't disappear one day.
https://github.com/ipfs/go-ipfs/pull/3351/commits/bfe7ad7ec30ebf0e9914ed1cf58076ffca51d119

It isn't critical but would be nice thing to have, should be nice start point for someone that just starts deving go-ipfs.

**Comment by divserge** [comment]
Hi, everyone!
Is this issue still viable? I'd be glad to pick up this one

**Comment by whyrusleeping** [comment]
I think @Kubuxu actually just wrote this today: https://github.com/ipfs/go-ipfs/pull/3583
