### ISSUE TITLE
Check all vendored code so far is appropriately licensed

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#337]
Make sure all libs vendored are appropriately licensed (MIT, BSD, APL2.0).

**Comment by rht** [comment]
Using https://www.npmjs.com/package/node-license-validator

```shell
$node-license-validator -l .
Identified licenses: [Apache, BSD, ISC, MIT, MPL]
```

**Comment by rht** [comment]
The package uses https://www.npmjs.com/package/spdx for its license algebra, but it isn't able to detect files without explicit license type, e.g. https://github.com/ipfs/go-ipfs/blob/master/Godeps/_workspace/src/github.com/kr/binarydist/License (MIT).

**Comment by jbenet** [comment]
maybe we should add a test if anything outside of the permissive licenses gets added.

**Comment by jbenet** [comment]
though would not be good to have to depend on node.js installed for running ipfs tests.

**Comment by rht** [comment]
There is an official go spdx library (one out of two, the other one being python, http://git.spdx.org/) that can be used.

In addition to the two, there are only node implementation (the one linked above) and haskell implementation.
cabal is in the process of adopting this (https://github.com/haskell/cabal/issues/2547).

**Comment by whyrusleeping** [comment]
our s3 datastore code relies on lgpl code at the moment.

**Comment by whyrusleeping** [comment]
We've gone through and removed the s3 lib, everything else is good to go
