### ISSUE TITLE
Unrewritten (for dev) go-ipfs endevour

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3370]
It is quite useful to dev go-ipfs in un-rewritten version, this also applies to libp2p that should work in this mode by default.

There will be some problems with consistency (different packages, new packages breaking compat) but it is quite possible.

There are some packages that have to be merged to master for this to work as we have patches in PRs.

**Comment by whyrusleeping** [comment]
I support working towards making ipfs build while its deps are in dvcs form, but i'm not on board with actually committing it that way

**Comment by Kubuxu** [comment]
Resolved by https://github.com/ipfs/go-ipfs/pull/6038.
