### ISSUE TITLE
add command to disable networking temporarily

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3372]
I would love to have a command for ipfs that is able to bring all of its networking down, and then bring it back up whenever you want to.

**Comment by whyrusleeping** [comment]
Could be something like `ipfs swarm down` and `ipfs swarm up`.  Would probably shut down the 'host' in the `core.IpfsNode` and set the daemons mode to 'offline' (so commands that only work online will fail with appropriate messages)

**Comment by wigy-opensource-developer** [comment]
How is this different from stopping the daemon and restarting it again? Gateway ports on localhost will be still available? BTW, is `killall -INT ipfs` the most elegant way to stop the daemon right now?

**Comment by whyrusleeping** [comment]
Yeah, the idea is that the API will still be accessible while the daemon is offline (allowing apps that are using the api to continue working as expected).

And yes, sending an interrupt is currently the best way of stopping the daemon.

**Comment by Kubuxu** [comment]
As a note, there is `ipfs daemon --offline` but it is per daemon run, it cannot be toggled.

**Comment by whyrusleeping** [comment]
ref: #4074

**Comment by magik6k** [comment]
Closing as this is basically https://github.com/ipfs/go-ipfs/issues/4074
