### ISSUE TITLE
Remove Expensive log.Debuf(...) statement in blockstore.AllKeysChan?

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#3378]
[This statement](https://github.com/ipfs/go-ipfs/blob/10915f346af4f63f38749015eb10273f447786b9/blocks/blockstore/blockstore.go#L205) is causing a major slowdown in AllKeysChan,
```
	get := func() (*cid.Cid, bool) {
		...
		log.Debug("blockstore: query got key", c)
		...
	}
```
due to the fact that the Cid is converted to a string which is very expensive due to the conversion to the Base58 representation.  This is done even if the log.Debug does not output anything.  See #3376.

The question is what to do about it?  The easiest thing would be to just remove it or comment it out with a explanation to why.

The other alternative is to only enable it when Debug mode is activated, but this is not the same as the Debug logging level.

I can't seam to find a way to check what the logging level is, if there was I could just use that.

**Comment by whyrusleeping** [comment]
@kevina I think its fair to remove that one. Its not really necessary here, and isnt a log statement i've ever found useful in debugging.
