### ISSUE TITLE
Add LEGAL file

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#338]
I'll have a file, called `LEGAL`, that serves as an entrypoint for understanding go-ipfs licensing, this will include a notice about vendored code.

**Comment by whyrusleeping** [comment]
@jbenet this doesnt appear to be done yet. Do we still need to do this?

**Comment by jbenet** [comment]
@whyrusleeping i think so, it can refer to `LICENSE` and the go style `PATENTS` (when it's added), and address dependencies. This could be moved to github.com/ipfs/community though as it should happen across repos.

**Comment by RichardLitt** [comment]
Closing in favor of https://github.com/ipfs/community/issues/139.
