### ISSUE TITLE
log parameters getting 'String'ed even when log level is disabled.

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3383]
In reference to: https://github.com/ipfs/go-ipfs/issues/3378

It seems that theres an issue in https://github.com/whyrusleeping/go-logging (the base lib for ipfs/go-log). We should fix this so that arguments don't even get considered unless their log level is enabled.

**Comment by Stebalien** [comment]
Fixed by updating go-logging.
