### ISSUE TITLE
'ls' API discussion (move to streaming)

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3385]
Currently, the outputs of both `ipfs ls` and `ipfs files ls` are arrays of directory entries. This has worked great for us, but thats mostly because we didnt have directory sharding. With sharded directories, this interface means we need to enumerate *every single* entry before we can output it. Recently in some tests, this has been OOMkilling ipfs nodes. We should switch to a streaming interface (as used by commands like `ipfs refs`) to avoid buffering this all in memory.

I'm opening this issue to discuss this since i think its a breaking change to the api, and will need support from the java scripters.

cc @jbenet @Kubuxu @diasdavid @dignifiedquire @lgierth

**Comment by diasdavid** [comment]
Moving it to become a streaming endpoint sounds good to me.

To avoid breaking changes, what about having both in the http-api with a flag option, and then change the default (stream: false to stream: true) upon previous notification of the users

**Comment by whyrusleeping** [comment]
I think thats exactly what the stream-channels option specifies currently, though I definitely might be wrong.

**Comment by diasdavid** [comment]
We are always setting that to `true` - https://github.com/ipfs/js-ipfs-api/blob/master/src/request-api.js#L115

There is a difference in go-ipfs between 'stream-channels', which is just write data to the pipe as it comes and then there is 'stream' endpoint which sends the results as ndjson.

**Comment by whyrusleeping** [comment]
@diasdavid mmm... the `stream-channels` option was meant to imply that the output would be ndjson. Is that not the case?

**Comment by diasdavid** [comment]
`stream-channels` existed before ndjson was introduced. 

See how it was enabled even before May 2015 https://github.com/ipfs/js-ipfs-api/blob/639b73a82e93d8440ed6b1617800b1566a0f9264/index.js#L26, way before ndjson was even a thing in the http-api.

I believe there is a confusion with `x-stream-output` https://github.com/ipfs/js-ipfs-api/blob/master/src/request-api.js#L52

**Comment by kevina** [comment]
I'll be happy to work on this once we decide it is wanted.

**Comment by magik6k** [comment]
Update: There is now `ipfs ls --stream`, but it's not the default

**Comment by Stebalien** [comment]
Let's close this as we'll have to revisit it when we redo the API.
