### ISSUE TITLE
gx deps fails

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/go-ipfs#3388]
I just installed `gx` and `gx deps` fails for go-ifps:

```
Justins-MacBook-Pro:go-ipfs justin$ gx deps
package QmPF5kxTYFkzhaY5LmkExood7aTTZBHWQC6cjdDQBuGrjp not found
```

I'm very new to `gx` and IPFS and it's possible I'm doing something stupid.

**Comment by JustinDrake** [comment]
(Note that IPFS is correctly installed and runs fine.)

**Comment by hsanjuan** [comment]
I think this means that you have not run `make deps` in the go-ipfs folder.

**Comment by JustinDrake** [comment]
`make deps` runs without issues, but `gx deps` still fails.

**Comment by whyrusleeping** [comment]
@JustinDrake do you have `gx-go` installed and in your path?

**Comment by JustinDrake** [comment]
Yes, that fixed it! I ran `go get -u github.com/whyrusleeping/gx-go` and it now works. This was not at all clear from the `gx` install documentation.

**Comment by whyrusleeping** [comment]
@JustinDrake Yeap, thanks for pointing this out. I'm adding some more code to gx that will error out if the subtool is missing and the `SubtoolRequired` config field is set.
