### ISSUE TITLE
pubsub.sub should set 'x-stream-output' header

### ISSUE THREAD

**Issue by haadcode** [ipfs/go-ipfs#3394]
#### Description:

Currently, when called via the HTTP API, pubsub/sub http response returns 'x-chunked-output' header. We want it to return 'x-stream-output' header in order to make it play nicely with js-ipfs-api.

**Comment by whyrusleeping** [comment]
@haadcode hrm... `x-stream-output` is sent when we are streaming back data, as in `ipfs cat`. `x-chunked-output` is used when we are sending back a series of objects, which is what pubsub sub should be returning. How is this different than `ipfs ping` for example?

**Comment by haadcode** [comment]
You're probably right about this. The problems are on the js-ipfs-api side in regards to parsing the incoming (json) data.

We can leave it as it is. Closing this issue.
