### ISSUE TITLE
List of experimental IPFS features

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3397]
**Update 23-Jul-2017** -- Since #4036 experimental features are documented in [docs/experimental-features.md](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md).

------

IPFS currently has a few different features that are in the 'experimental' phase. This might be because we arent fully confident in releasing the code as an official feature yet, or because we don't want to make a certain change to the network yet. Whatever the case, we should have a log of all of those features and their states.

Lets use this issue to track the state of these features, and maybe think about putting this info in a doc that we commit to version control.

**Comment by whyrusleeping** [comment]
## `ipfs pubsub`

### State
experimental, default-disabled.

### In Version
master, unreleased.

### How to enable
run your daemon with the `--enable-pubsub-experiment` flag. Then use the `ipfs pubsub` commands.

### Road to being a real feature
- [ ] Needs more people to use and report on how well it works
- [ ] Needs authenticated modes to be implemented
- [ ] needs performance analyses to be done

**Comment by whyrusleeping** [comment]
## Client mode DHT routing
Allows the dht to be run in a mode that doesnt serve requests to the network, saving bandwidth.

### State
experimental.

### In Version
master, unreleased.

### How to enable
run your daemon with the `--routing=dhtclient` flag.

### Road to being a real feature
- [ ] Needs more people to use and report on how well it works.
- [ ] Needs analysis of effect it has on the network as a whole.

**Comment by whyrusleeping** [comment]
## go-multiplex stream muxer
Adds support for using the go-multiplex stream muxer alongside (or instead of) yamux and spdy. This multiplexer is far simpler, and uses less memory and bandwidth than the others, but is lacking on congestion control and backpressure logic. It is available to try out and experiment with.

### State
Experimental

### In Version
master, unreleased

### How to enable
run your daemon with `--enable-mplex-experiment`

To make it the default stream muxer, set the environment variable `LIBP2P_MUX_PREFS` as follows:
```
export LIBP2P_MUX_PREFS="/mplex/6.7.0 /yamux/1.0.0 /spdy/3.1.0"
```

To check which stream muxer is being used between any two given peers, check the json output of the `ipfs swarm peers` command, you'll see something like this:
```
$ ipfs swarm peers -v --enc=json | jq .
{
  "Peers": [
    {
      "Addr": "/ip4/104.131.131.82/tcp/4001",
      "Peer": "QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
      "Latency": "46.032624ms",
      "Muxer": "*peerstream_multiplex.conn",
      "Streams": [
        {
          "Protocol": "/ipfs/bitswap/1.1.0"
        },
        {
          "Protocol": "/ipfs/kad/1.0.0"
        },
        {
          "Protocol": "/ipfs/kad/1.0.0"
        }
      ]
    },
    {
...
```

### Road to being a real feature
- [ ] Significant real world testing and performance metrics across a wide variety of workloads showing that it works well.

**Comment by whyrusleeping** [comment]
## Raw Leaves for unixfs files
Allows files to be added with no formatting in the leaf nodes of the graph.

### State
experimental.

### In Version
master, (0.4.5).

### How to enable
Use `--raw-leaves` flag when calling `ipfs add`.

### Road to being a real feature
- [ ] Needs more people to use and report on how well it works.

**Comment by whyrusleeping** [comment]
## Ipfs Filestore
Allows files to be added without duplicating the space they take up on disk.

### State
experimental.

### In Version
master, (0.4.7).

### How to enable
Modify your ipfs config:
```
ipfs config --json Experimental.FilestoreEnabled true
```

And then pass the `--nocopy` flag when running `ipfs add`

### Road to being a real feature
- [ ] Needs more people to use and report on how well it works.
- [ ] Need to address error states and failure conditions
- [ ] Need to write docs on usage, advantages, disadvantages
- [ ] Need to merge utility commands to aid in maintenance and repair of filestore

**Comment by Kubuxu** [comment]
## Private Networks 
------
Allows to limit peerset and secure the connections to limited set of nodes that share the same pre-shared key.

### State
Experimental

### In Version
master, 0.4.7

### How to enable
Generate PSK (use [ipfs-swarm-key-gen](https://github.com/Kubuxu/go-ipfs-swarm-key-gen)) and save it. To join given private network copy it to `swarm.key` file in IPFS Repo.
Then share it with others and they should do the same. If you start ipfs daemons they will be only able to connect to each other.

This means that you can use global bootstrap nodes so you have to have at least one daemon in public network that will have permanent public IP. Then use `ipfs id` on it to get its address. Then remove global bootstrap nodes and add that address to the bootstrap list.
```bash
ipfs bootstrap rm --all
ipfs bootstrap add $YOUR_NEW_BOOTSTRAP_ADDRESS
```

You can also set `LIBP2P_FORCE_PNET=1` environment variable to force the usage of private network. If there is no private network the daemon will fail to start.

### Road to being a real feature
- [ ] Needs more people to use and report on how well it works.
- [ ] More docs

**Comment by magik6k** [comment]
## `ipfs ptp` 
------
Allows to tunnel TCP connections through Libp2p sterams

### State
Experimental

### In Version
master, 0.4.10

### How to enable
PTP command needs to be enabled in config

`ipfs config --json Experimental.Libp2pStreamMounting true`

### Road to being a real feature
- [ ] Needs more people to use and report on how well it works / fits use cases
- [ ] More documentation
- [ ] Support other protocols

**Comment by lgierth** [comment]
Since #4036 experimental features are documented in docs/experimental-featuers.md

**Comment by Kubuxu** [comment]
@lgierth this should be added as a top comment (edit).

**Comment by lgierth** [comment]
right, good call

**Comment by whyrusleeping** [comment]
I'm gonna go ahead and close this

**Comment by pataquets** [comment]
I'm trying one of them without experiencing problems, so far. But when I want to provide feedback, no clear method is given.
Any feedback form? Any issue?
Also, a link to each feature's own issue would be helpful in reporting problems or giving feedback.

**Comment by magik6k** [comment]
If you have any feedback other than 'it works', you should open a new issue. ('it works' is also a valid feedback for these features, there is just no good place for it)

**Comment by DaniellMesquita** [comment]
@whyrusleeping
Is your comment updated? https://github.com/ipfs/go-ipfs/issues/3397#issuecomment-284337564

**Comment by Stebalien** [comment]
@DaniellMesquita no. The Filestore is still unstable.

Personally, I'm hesitant to stabilize it ever as deleting files from the filestore can remove blocks from independently pinned files.

Ways forward:

* Create a separate dropbox-like ipfs application that watches a directory and only serves files out of that directory. When added/removed from the watched directory, files would be added/removed from IPFS.
* Keep the filestore and the blockstore independent. That is, never count us "having" a block if we have it in the filestore when adding data via `ipfs add` or `ipfs get`.
* Improve mount support to the point where users can just keep their files in IPFS.

**Comment by Johnlez7** [comment]
**### p2p http proxy**

Hi everyone,
I try to use p2p http proxy to setup my nextcloud server at home to be visitable outside through android phone,
but I stopped by this issue:
 as the most nextcloud server will happen,
I already add the '127.0.0.1','localhost',[ipv6],to the trusted-domain list in the config.php,
and even:
'trusted_proxies' =>
  array (
    0 => '127.0.0.1',
 ),
'proxy' => '/root/myproxy.server.ext',

but it still can not work, can brothers share your ideas to handle it , thanks so much!

![install-wizard-a4](https://user-images.githubusercontent.com/74808160/129827682-e9cfe913-444d-4702-a506-8274fd48a62e.png)

**Comment by Stebalien** [comment]
@Johnlez7 please ask on discuss.ipfs.io
