### ISSUE TITLE
programatically automate "ipfs name publish <hash>"

### ISSUE THREAD

**Issue by chriswingler** [ipfs/go-ipfs#3400]
#### Description:
Hi is there any way to create a production build without copy/pasting the folder hash into a terminal command?

**Comment by hsanjuan** [comment]
would `curl 'localhost:5001/api/v0/name/publish?arg=<hash>'` work for you?

(api endpoint off the top of my head, might be slightly wrong)

**Comment by chriswingler** [comment]
Not sure.  I will look into it...  was hoping for something along the lines of `ipfs name publish <directory>`

**Comment by hsanjuan** [comment]
`ipfs add -q -r test | tail -n 1 | xargs ipfs name publish` ?

**Comment by chriswingler** [comment]
yes! thank you!
