### ISSUE TITLE
notif.go:38 reports DHT error

### ISSUE THREAD

**Issue by bitsanity** [ipfs/go-ipfs#3405]
IPFS Bug Report
P4
Mon Nov 21 11:39:30 PST 2016
ipfs version 0.4.5-dev
Linux raspberrypi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

**11:29:24.145 ERROR dht: checking dht client type: &errors.errorString{s:"EOF"} notif.go:38**

Notes:
- compiled go (1.4 then 1.7) then gx and IPFS from source on RPi3
- node seems to be functioning, test file available and updatable via gateway.ipfs.io
- CPU consumption ~ 10%
- mem consumption ~ 20% (total RAM = 1 GB)
- would be a P5 except the log entry says "ERROR"

**Comment by whyrusleeping** [comment]
@bitsanity Ah, yeah. that one isnt an error, we should drop it down (EOF is expected, other potential error messages arent)

**Comment by whyrusleeping** [comment]
This error has been demoted to a warning
