### ISSUE TITLE
There is no "shell" package

### ISSUE THREAD

**Issue by calmh** [ipfs/go-ipfs#3409]
Hi! I'm looking to get started with IPFS, at the API level, by importing the relevant packages in Go. The [godoc](https://godoc.org/github.com/ipfs/go-ipfs) sounds promising in

> IPFS is a global, versioned, peer-to-peer filesystem
>
> There are sub-packages within the ipfs package for various low-level utilities, which are in turn assembled into:
> 
> core/...:
> The low-level API that gives consumers all the knobs they need, which we try hard to keep stable.
> 
>  shell/...:
>  The high-level API that gives consumers easy access to common operations (e.g. create a file node from a reader without wrapping with metadata). We work really hard to keep this stable.

The `shell` package/directory sounds exactly like what I want! But it does not exist :(

**Comment by calmh** [comment]
I found https://github.com/ipfs/go-ipfs-api - is that the new location/replacement perhaps?

**Comment by hsanjuan** [comment]
Yes! But that package is pending a revamp so it might change heavily in the near future (also, it doesn't implement all endpoints). Depending on what you need, you might be better off talking http directly to the API until we bring the go-ipfs-api up to speed.

**Comment by calmh** [comment]
Gotcha.
