### ISSUE TITLE
What is a supernode?

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/go-ipfs#3412]
Both `go-ipfs/routing/` and `go-ipfs/routing/config/` have supernode code. What is a supernode?

In `supernode.go` there are addresses which look like bootstrap addresses. What does `SNR` mean?

```
var DefaultSNRServers = []string{
	"/ip4/104.236.176.52/tcp/4002/ipfs/QmXdb7tWTxdFEQEFgWBqkuYSrZd3mXrC7HxkD4krGNYx2U",
	"/ip4/104.236.179.241/tcp/4002/ipfs/QmVRqViDByUxjUMoPnjurjKvZhaEMFDtK35FJXHAM4Lkj6",
	"/ip4/104.236.151.122/tcp/4002/ipfs/QmSZwGx8Tn8tmcM4PtDJaMeUQNRhNFdBLVGPzRiNaRJtFH",
	"/ip4/162.243.248.213/tcp/4002/ipfs/QmbHVEEepCi7rn7VL7Exxpd2Ci9NNB6ifvqwhsrbRMgQFP",
	"/ip4/128.199.219.111/tcp/4002/ipfs/Qmb3brdCYmKG1ycwqCbo6LUwWxTuo3FisnJV2yir7oN92R",
	"/ip4/104.236.76.40/tcp/4002/ipfs/QmdRBCV8Cz2dGhoKLkD3YjPwVFECmqADQkx5ZteF2c6Fy4",
	"/ip4/178.62.158.247/tcp/4002/ipfs/QmUdiMPci7YoEUBkyFZAh2pAbjqcPr7LezyiPD2artLw3v",
	"/ip4/178.62.61.185/tcp/4002/ipfs/QmVw6fGNqBixZE4bewRLT2VXX7fAHUHs8JyidDiJ1P7RUN",
}
```

**Comment by lgierth** [comment]
SNR stands for supernode routing. It's never really been used so far, but it's an alternative routing scheme in addition to the kademlia DHT.

Btw many questions like this best fit in the [ipfs/faq](https://github.com/ipfs//go-ipfs) repo :sunflower:

**Comment by JustinDrake** [comment]
@lgierth Ok, I'll ask in ipfs/faq in the future. thanks.
