### ISSUE TITLE
Start tagging dependencies

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3426]
Lets start tagging issues and PRs with what they depend on. 

For example:

* depends on #7

or

* depends on libp2p/go-libp2p#18

NOTE: if youre actually writing these, omit the asterisk.

If we do this rigorously then we can more easily integrate into @jbenet's dependency visualizer tool

**Comment by wking** [comment]
The current dependency regex isn't smart enough to detect pre blocks, so your depends lines above show up [in the graph][1] ;).

![graph](https://cloud.githubusercontent.com/assets/209920/20845750/54e1bd5e-b87b-11e6-9230-6ddbadd39803.png)

If you want to not match the regexp, put something else in the line.  For example, backticks: `depends on #7`.

[1]: https://jbenet.github.io/depviz/#/http/github.com/ipfs/go-ipfs/3426?expanded=true

**Comment by whyrusleeping** [comment]
@wking haha, thanks for the tip
