### ISSUE TITLE
CIDv1 pin specification doesn't work

### ISSUE THREAD

**Issue by mib-kd743naq** [ipfs/go-ipfs#3431]
#### Version information:
```
go-ipfs version: 0.4.5-dev-bf9927f
Repo version: 4
System version: amd64/linux
Golang version: go1.7.1
```

#### Type:
Bug

#### Priority:
P2

#### Description:
```
$ ipfs pin add zdj7WgpD1zodrFvjBSWMXL2y9dR7z7H1TJdBhrTLZcS4LGPH9
pinned QmZixeZjnNnKrU8acnNR6mnrVmuqHutVKPSvfmDmEthV7D recursively
```
Did not expect to see a "CIDv0" at the output, likely indicates incorrect index store or somesuch...

**Comment by whyrusleeping** [comment]
Ah, yeah. I think i know whats happening here. The protobuf nodes always default to generating a cidV0. We might need some way to store cid prefix in the nodes to make sure we generate the correct output cid...

**Comment by whyrusleeping** [comment]
@mib-kd743naq can you verify that this was fixed in latest master?

**Comment by mib-kd743naq** [comment]
Works as of 0c413de
