### ISSUE TITLE
Pinning large files

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/go-ipfs#3433]
I have been trying to pin a hash referencing a lot of content (in the area of 1TB) and ipfs daemon would simply die. 

The output details are in this gist: https://gist.github.com/dignifiedquire/85b15ef84284693051ac6e4672a3a4ee

**Comment by Kubuxu** [comment]
It might be due to go-ipfs doing recursive ref on the whole file.

**Comment by whyrusleeping** [comment]
This should be resolved now. Was unbounded concurrency in the enumerate children methods
