### ISSUE TITLE
[wishlist] More efficient interface for `block put`

### ISSUE THREAD

**Issue by mib-kd743naq** [ipfs/go-ipfs#3442]
I am currently using the API with a reasonably fast curl-based HTTP client to add many externally generated blocks. This seems to be slower than I would like, especially for the cases when the block is already in the blockstore. In any case the HTTP overhead is not trivial.

I was wondering what would it take / is it possible to have `some-program-generating-null-delimited-base64-encoded-blobs-possibly-prefixed-with-expected-base58-id-so-an-error-can-be-raised | ipfs block put -f raw --batch=base64 -` or somesuch, with the obvious behavior?

Thank you in advance!

**Comment by Kubuxu** [comment]
It might be easier, and faster do to them length prefixed and not encoded.

**Comment by mib-kd743naq** [comment]
@Kubuxu actually... now that you mention it... the `generator...` program by definition has knowledge of protobuf, so might as well do this:
```
message BlockPutBatchStream {
	repeated IPFSBlock Blocks = 1;
}

message IPFSBlock {
	enum BlockType {
		ProtobufV0 = 0;   // corresponds to `block add`
		ProtobufV1 = 1;   // corresponds to `block add -f protobuf`
		Raw = 10;         // corresponds to `block add -f raw`
	}

	required BlockType Type = 1;
        required bytes Data = 2;
	optional bytes ExpectedID = 3;  // if supplied by the client verified against what `block add` would print on STDOUT, and `exit 1` on mismatch
}
```

**Comment by mib-kd743naq** [comment]
I suppose also needs a `required bytes MultiHashID = 4;` to address this proactively

**Comment by whyrusleeping** [comment]
Since most protobuf decoders (except [mine](https://github.com/whyrusleeping/go-pbs) ) don't handle reading in streams of objects nicely, how about we just sent a stream of varint length-prefixed `IPFSBlock`s? (skipping the `BlockPutBatchStream` message)

**Comment by mib-kd743naq** [comment]
Oh I didn't know streaming is problematic. In this case, yes: certainly omitting the "outer shell" and only keeping the varint length prefix makes perfect sense

**Comment by mib-kd743naq** [comment]
I still strongly believe the **inner** payload should remain in self-describing protobuf format though, to avoid faffing with CLI options.

**Comment by whyrusleeping** [comment]
Lets make it look more like:

```protobuf
message IPFSBlock {
	message CidPrefix {
		Version = 0;
		Codec = 1;  
		MhType = 2;
		MhLength = 3;
	}

	required CidPrefix Prefix = 1;
        required bytes Data = 2;
	optional bytes ExpectedID = 3;  // if supplied by the client verified against what `block add` would print on STDOUT, and `exit 1` on mismatch
}
```

**Comment by mib-kd743naq** [comment]
@whyrusleeping perfect!

What would CidPrefix look like to generate a `Qm...` style blockstore id? (i.e. `block add` with no options equivalent on current go-ipfs)

**Comment by whyrusleeping** [comment]
From: https://github.com/ipfs/go-cid/blob/master/cid.go#L248

```go
p := cid.Prefix{
  Version: msg.Version,
  Codec: msg.Codec,
  MhType: msg.MhType,
  MhLength: msg.MhLength,
}

c, err := p.Sum(data)

fmt.Println(c)
```

**Comment by mib-kd743naq** [comment]
So in actual numbers: x00 x70 x12 x20 should yield me a `Qm....` in the end?

That is lovely \o/

**Comment by whyrusleeping** [comment]
> So in actual numbers: x00 x70 x12 x20 should yield me a Qm.... in the end?

Yep!

**Comment by mib-kd743naq** [comment]
I started playing with this again. Here is [the "put-sequence"](ipfs.io/ipfs/QmSZ97nmxwoHiheZ9qSBEz9Fgqz7iDtkYbyymeR96S94vS) that produced [QmQxa8P7g4n17wsvYNxn9xN2H79n3NYXyURnFTjYeB7BPV](https://ipfs.io/ipfs/QmQxa8P7g4n17wsvYNxn9xN2H79n3NYXyURnFTjYeB7BPV) (just the string `123\n45\n`)

I had to make some adjustments, @whyrusleeping please comment if any of this looks out of place:

> Lets make it look more like:
> ...
> `optional int Version = 0;`

Tags can only start at 1, so the proposed `CidPrefix` should look like this:
```
	message CidPrefix {
		optional int Version = 1;
		optional int Codec = 2;  
		optional int MhType = 3;
		optional int MhLength = 4;
	}
```

> how about we just sent a stream of varint length-prefixed IPFSBlocks? (skipping the BlockPutBatchStream message)

I elected to prefix every "frame" with a "Length Delimited Tag 1" byte of `0x0a`, making the entire blob a proper protobuf stream: this allows on-the fly examination like so:
```
~$ curl -s https://ipfs.io/ipfs/QmSZ97nmxwoHiheZ9qSBEz9Fgqz7iDtkYbyymeR96S94vS | protoc --decode_raw
1 {
  1 {
    1: 0
    2: 112
    3: 18
    4: 32
  }
  2 {
    1 {
      1: 0
      2: "123"
    }
  }
  3: "QmXtqzZD6BmtmhgGFKYUjPpHg97ciKV4QL7Hh6fwQwzUng"
}
1 {
  1 {
    1: 0
    2: 112
    3: 18
    4: 32
  }
  2 {
    1 {
      1: 0
      2: "\n"
    }
  }
  3: "QmRnnQXyW5wNz6rvjw4fQQ8XWaLvyfkvJBztC3WGx1gmyg"
}
1 {
  1 {
    1: 0
    2: 112
    3: 18
    4: 32
  }
  2 {
    1 {
      1: 0
      2: "45"
    }
  }
  3: "QmTs5HQfHvU3zGZLnyAG3mXH9FbeNNkiCg41xkmEHxmryV"
}
1 {
  1 {
    1: 0
    2: 112
    3: 18
    4: 32
  }
  2 {
    1 {
      1: 2
      3: 1
    }
    2 {
      1 {
        2: "3D\335i\006d\005I\005k\254\332\241\2753\005(\226VR\377\036L4\272\272*\351`U\222\277"
      }
    }
  }
  3: "QmQ64t3jF15zuSb162LWzQovrHJdbC2jutLEfVvx3FzKxN"
}
1 {
  1 {
    1: 0
    2: 112
    3: 18
    4: 32
  }
  2 {
    1 {
      1: 2
      3: 3
    }
    2 {
      1 {
        2: "R\025\245\037yH\324\037\375\t\2334%\254%\326\032\336\324\327\373\335/\"}\205_\205\217X @"
      }
    }
    2 {
      1 {
        2: "\031\372\376\016Q\311e\232\036\300\033\372s\314r\225\036\272\260Y\352=J\250\353\223\343X\231\023\306["
      }
    }
  }
  3: "QmRt86Ug6PFNL3XR76eTLFqsaTqTSyj14b1mfZ1kxdRYeH"
}
1 {
  1 {
    1: 0
    2: 112
    3: 18
    4: 32
  }
  2 {
    1 {
      1: 2
      3: 4
    }
    2 {
      1 {
        2: "3D\335i\006d\005I\005k\254\332\241\2753\005(\226VR\377\036L4\272\272*\351`U\222\277"
      }
    }
    2 {
      1 {
        2: "4\243\007\356\221\211H\'\233zi\271\364D \310v\215ja\371\234\266\343\321Q0\320G8\307\356"
      }
    }
  }
  3: "QmNgJyNg8bqrijv19j6baAJ8ebafurw3GEcamoZKEKEo8P"
}
1 {
  1 {
    1: 0
    2: 112
    3: 18
    4: 32
  }
  2 {
    1 {
      1: 2
      3: 7
    }
    2 {
      1 {
        2: "\215\370\206\322l:\r\226\230\240_q\374\031\032W\225\377\213\277\267\212`\366\034\245\337\230\275\000\210M"
      }
    }
    2 {
      1 {
        2: "\005\tL\274\276=\316\304\342HJs\314\234^\346[\356\004nB\026\243\332YC\3406\335\314(\354"
      }
    }
  }
  3: "QmQxa8P7g4n17wsvYNxn9xN2H79n3NYXyURnFTjYeB7BPV"
}
```

**Comment by ribasushi** [comment]
This has since been implemented via https://github.com/ipfs/go-ipfs/issues/6870
