### ISSUE TITLE
Streaming out of and into repo hits lock

### ISSUE THREAD

**Issue by gsf** [ipfs/go-ipfs#3446]
When I `ipfs cat` content from my local repo, modify it, and `ipfs add` it back in, I get a lock error and an empty file is added. Is the repo locking on read? If so, why? 

```
# ipfs version --all 
go-ipfs version: 0.4.5-dev-66315b8 
Repo version: 4 
System version: amd64/linux 
Golang version: go1.7.1
# ipfs cat QmTudJSaoKxtbEnTddJ9vh8hbN84ZLVvD5pNpUaSbxwGoa | sed 's/2/3/' | ipfs add
Error: cannot acquire lock: Lock FcntlFlock of /root/.ipfs/repo.lock failed: resource temporarily unavailable
added QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH
```

**Comment by whyrusleeping** [comment]
@gsf You can do this with the daemon running, but without the daemon running, opening up the repo does take a lock. We do this at the repo level because lower layers (like leveldb) don't tolerate being opened concurrently.

**Comment by gsf** [comment]
Oh yeah, makes sense, leveldb doesn't like concurrent access of any kind (google/leveldb#182). Thanks for the explanation.
