### ISSUE TITLE
ipfs repo gc -- failure to remove unpinned objects

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#3453]
I noticed:
- my repo has gotten quite big.
- ipfs now consumes all my disk space and can crashes in an unrecoverable way with out of disk space fails. (leveldb cant open when out of disk apparently)
- i tried to `ipfs repo gc` and kept getting `Error: merkledag: not found`, and exiting. It looks like some bug is causing an error internally in the repo.

I get this right now:
```
> head -c 4096 /dev/urandom | ipfs add -q
Qmdt8RPd1SuM2pqq8SVZcN1PXqdJesaDgVut4DNxQ171SE
> ipfs pin rm Qmdt8RPd1SuM2pqq8SVZcN1PXqdJesaDgVut4DNxQ171SE
unpinned Qmdt8RPd1SuM2pqq8SVZcN1PXqdJesaDgVut4DNxQ171SE
> ipfs repo gc
Error: merkledag: not found
```

---

Thoughts:
- Some object in the pinset is NOT in the repo, hence this error.
  - If so, !!!!!!
- This error should be more clear as to what's going on.
- Arguably it should continue to work past this error.

**Comment by Kubuxu** [comment]
It is hard to work past this error as we might accidentally remove blocks that would be pinned behind links in missing block. We might want try to refetch the missing bock.

You can try `ipfs pin ls | cut -d' ' -f 1 | ipfs refs -r` to try fetching missing blocks from the network.

**Comment by whyrusleeping** [comment]
Huh, this is quite strange. I wonder how we managed to sync a pin to an object we hadnt successfully written to disk

**Comment by whyrusleeping** [comment]
@jbenet how big is the repo?

**Comment by lgierth** [comment]
Gonna look into this to make sure we don't have some big bad regression waiting to be released with 0.4.5

**Comment by whyrusleeping** [comment]
@lgierth Have you had time to look into this? As far as i can tell this is either a disk corruption issue, or something thats a result of a bug much earlier on than 0.4.4

In either case i'd say this shouldnt block 0.4.5

**Comment by whyrusleeping** [comment]
I think this was an issue with gc not handling new types correctly (ipld, zcash, etc). This should be resolved now.
