### ISSUE TITLE
Incorrect size calculation on recursive directory `ipfs add` (109 seems random)

### ISSUE THREAD

**Issue by mib-kd743naq** [ipfs/go-ipfs#3455]
#### Version information:
```
go-ipfs version: 0.4.5-dev-66315b8
Repo version: 4
System version: amd64/linux
Golang version: go1.7.3
```

#### Type:
`Bug`

#### Priority:
`P2`

#### Description:
```
~$ tree top
top
└── foo
    └── bar
        └── baz

~$ ls -l top/foo/bar/baz
-rw-r--r-- 1 ipfs ipfs 3 Dec  1 19:37 top/foo/bar/baz

~$ ipfs add -r top
added QmQpeUrxtQE5N2SVog1ZCxd7c7RN4fBNQu5aLwkk5RY9ER top/foo/bar/baz
added QmSMxgMY4ZpB9H7zbn3AhLNobnjjnzkfeEKwXaAJ9ibr1G top/foo/bar
added QmVzzr9ArZaQZSWTYgUpAN4fJrK46qmbYpf95CyD4fz7jd top/foo
added QmW4UsYZRtxSBtQgCkHEsFpJDMNYv8j4eFpEU97w1fEHtp top
```

Size [listed in the top object](https://ipfs.io/api/v0/object/get/QmW4UsYZRtxSBtQgCkHEsFpJDMNYv8j4eFpEU97w1fEHtp) is inexplicably 109 bytes for foo. I would expect 3. Even if we allow for directory sizes (why?) numbers still do not add up:
```
~$ du -sb top
54	top

~$ du -sb top/foo
37	top/foo

~$ du -sb top/foo/bar
20	top/foo/bar

~$ du -sb top/foo/bar/baz
3	top/foo/bar/baz
```

**Comment by whyrusleeping** [comment]
@mib-kd743naq thats the total size of that entire subtree

**Comment by whyrusleeping** [comment]
What your filesystem isnt including is filenames and other metadata. The ipfs object is essentially including the size of the inodes in the count.

**Comment by mib-kd743naq** [comment]
@whyrusleeping In my experiments I determined that the size is for information purposes only (I could even omit the tag3-size entirely and everything still works).

Is there an actual compelling case to have the "right ipfs-storage number" instead of just matching what an idealized  filesystem would look like? ( i.e. not count directory sizes at all )

**Comment by mib-kd743naq** [comment]
@whyrusleeping Actually... I am still not sure what the number represents. Could you break it down for me? e.g. why is [QmSMxgMY4ZpB9H7zbn3AhLNobnjjnzkfeEKwXaAJ9ibr1G](https://ipfs.io/api/v0/object/get/QmSMxgMY4ZpB9H7zbn3AhLNobnjjnzkfeEKwXaAJ9ibr1G) showing a size of 11 - where did go-ipfs take that from?

**Comment by whyrusleeping** [comment]
its the size of the object itself, not its contents, more specifically, in this case, its the size of the protobuf representation of that object

**Comment by mib-kd743naq** [comment]
Understood. That's kinda unfortunate because this means that an identical "file" will show up with a different size depending on whether --raw-leaves was used :/

In any case - still would like more clarity on my earlier question: https://github.com/ipfs/go-ipfs/issues/3455#issuecomment-264262829

**Comment by whyrusleeping** [comment]
> this means that an identical "file" will show up with a different size depending on whether --raw-leaves was used :/

Thats what the `FileSize` embedded in the root node of every unixfs file object is for. It tells the size of the data of a given file.

> Is there an actual compelling case to have the "right ipfs-storage number" instead of just matching what an idealized filesystem would look like? ( i.e. not count directory sizes at all )

Yes. The dag is not a filesystem. UnixFS is a filesystem abstraction built on top of the dag

**Comment by mib-kd743naq** [comment]
> Thats what the FileSize embedded in the root node of every unixfs file object is for. It tells the size of the data of a given file.

Yes I understand that. But what we **display** in the browser that is supposed to show "filesystem abstraction on top of the dag", are the sizes of the underlying DAG (i.e. abstraction leak). Additionally it seems that the actual numbers **can be** arbitrary, which makes me even more confused.

I guess I will close this ticket for the time being and construct some "questionable" directory trees, so we can talk about actual invalid examples and whether they ought to work forever or not.
