### ISSUE TITLE
Tests fail if a go-ipfs daemon is already running

### ISSUE THREAD

**Issue by mib-kd743naq** [ipfs/go-ipfs#3457]
#### Version information:
Current master: https://github.com/ipfs/go-ipfs/commit/a542dea5d

#### Type:
`Bug`

#### Priority:
`P1`

#### Description:

If an ipfs daemon is active `TEST_NO_FUSE=1 make test` [fails like this](http://ipfs.io/ipfs/QmQHa39FjkQeGEYUmau2gmT4d23pV2q9KPQqftkRcw5Bwz)
( tested only under the same user account, not sure what happens if the daemon runs under a dedicated/separate user but still occupies the usual ports )

**Comment by whyrusleeping** [comment]
Thanks for reporting, This may have been fixed. Needs to be verified

**Comment by whyrusleeping** [comment]
It appears that t0063 still fails if you have a daemon running locally while running the tests

**Comment by Kubuxu** [comment]
I think it was resolved, I will try to check it once I am home.
