### ISSUE TITLE
Pubsub returns wrong peers for a topic

### ISSUE THREAD

**Issue by haadcode** [ipfs/go-ipfs#3467]
#### Version information:

0.4.5-pre1

#### Type:

Bug

#### Description:

When I call pubsub/peers(topic), go-ipfs returns all peers that are connected to it. Expected behaviour is to return only the ones that are subscribed to the specified topic.

**Comment by haadcode** [comment]
@keks care to take a look?

**Comment by keks** [comment]
Oh dang, sorry for not responding! Was really busy with uni stuff this week. I'll take a look on Monday!

**Comment by Kubuxu** [comment]
https://github.com/ipfs/go-ipfs/pull/3484There is PR made by @whyrusleeping for this already: #3484
