### ISSUE TITLE
coreunix.Add is documented to pin objects but it doesn't

### ISSUE THREAD

**Issue by zaibon** [ipfs/go-ipfs#3470]
#### Version information:
```
go-ipfs version: 0.4.4-
Repo version: 4
System version: amd64/linux
Golang version: go1.7
```

#### Description:
The documentation of the [coreunix.Add](https://github.com/ipfs/go-ipfs/blob/master/core/coreunix/add.go#L254) method claims to pin the object to the local data store but it doens't seem to do so.

After adding a file using :
```go
// r is a reader from a file
hash, err := coreunix.AddWithContext(ctx, service.node, r)
if err != nil {
	panic("error adding file")
}
fmt.Println(hash)
```

I'm trying to make sure the object is pinned using `ipfs pin ls` but this command returns nothing
I can cat the file with `ipfs cat <hash>` but after doing `ipfs repo gc` 
trying to cat the file again fails with `Error: merkledag: not found` which proof the object was not pinned

**Comment by whyrusleeping** [comment]
Oh, `AddWithContext` should be calling `adder.PinRoot()`.

**Comment by lgierth** [comment]
So, the `coreunix.Add*()` functions used to pin before 0.4.0, but in the huge overhaul of add, importer, pinning, and with the introduction of GC, it was decided the default behaviour on the library layer should be to *not* pin. Only the CLI and (under certain circumstances) end-user apps should pin by default.

The documentation simply slipped through, so thanks for catching that :)
