### ISSUE TITLE
Support OSXFUSE 3+

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3471]
Currently it doesn't work with our fuse lib version.

**Comment by flyingzumwalt** [comment]
:+1:

**Comment by flyingzumwalt** [comment]
FYI Until you fix this, you're returning an error message that's not self-consistent. It says "Please upgrade to the latest OSXFUSE version." but then says "OSXFUSE versions >3.0.0 are not compatible with version of FUSE library in current use." Without any actual recommendation of which version you should be using.

```
mount_test.go:74: OSXFUSE version 3.5.4 not supported.
		
		OSXFUSE versions <2.7.2 are known to cause kernel panics!
		Please upgrade to the latest OSXFUSE version.
		It is recommended you install it from the OSXFUSE website:
		
			http://osxfuse.github.io/
		
		For more help, see:
		
			https://github.com/ipfs/go-ipfs/issues/177
		
		OSXFUSE versions >3.0.0 are not compatible with version of FUSE library in current use.
			This will be fixed in near future, see https://github.com/ipfs/go-ipfs/issues/3471
```

**Comment by flyingzumwalt** [comment]
Wow. Fuse doesn't even provide prebuilt downloads for version <3.x

Reason to press on this: when I download the code and run the tests, I get a bunch of test failures around fuse -- fuse isn't installed and then (after installing) fuse version isn't supported. Basic sanity check for good OSS code: someone with coding skills should be able to download your tests, run them and get 100% pass without digging through docs or GH issues.

**Comment by Kubuxu** [comment]
We know that, the message was fixed. The upgrade of fuse library we are currently are using was queued for 0.4.6
