### ISSUE TITLE
OSX Teamcity tests leave `nc` process running

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3496]
The OSX teamcity tests will occasionally all start failling because some test run failed to clean up a netcat listener (on port 5005 I think). We should figure out where/why this is happening and fix it.

**Comment by whyrusleeping** [comment]
This appears to be in `t0235`:

```
14:     go-sleep 0.5s | nc -l 5005 > nc_out &
```

I'm not 100% sure, but i don't believe processes necessarily get killed if their input process dies.

**Comment by lgierth** [comment]
Might need `-o pipefail`

**Comment by whyrusleeping** [comment]
@lgierth i don't think that would do it. The problem is that the `nc` process just isnt dying. setting pipefail would make just make it return non-zero *when* it exits *if* `go-sleep` returns a non-zero exit code.

**Comment by whyrusleeping** [comment]
cc @chriscool and @Kubuxu

**Comment by Kubuxu** [comment]
we can have test after it that always kills it.

but apart from that we should have teamcity run some sort of containers (docker, lxc, lxd, whatever), and scrap the whole container after test is done.

**Comment by whyrusleeping** [comment]
@Kubuxu Yeah, we should be. But i'm not aware of any containerization stuff that works on OSX. I read that docker supports osx 'natively' but i'm not sure whether or not that means the OS inside the container will still be osx.

**Comment by chriscool** [comment]
I would suggest killing the process explicitly like this:

```
test_expect_success "can start nc server" '
	nc -l 5005 > nc_out &
'

test_expect_success "can make http request against nc server" '
	NC_PID=$! &&
	( ipfs cat /ipfs/Qmabcdef --api /ip4/127.0.0.1/tcp/5005 || true ) &&
	go-sleep 0.5s &&
	test_kill_repeat_10_sec $NC_PID
'
```

**Comment by Kubuxu** [comment]
This might be a solution: https://paolozaino.wordpress.com/2015/08/04/how-to-run-your-applications-in-a-mac-os-x-sandbox-to-enhance-security/

**Comment by Kubuxu** [comment]
This might be also general solution for those sorts of problems:
```
trap "exit" INT TERM
trap "kill 0" EXIT
```
