### ISSUE TITLE
Mutex/Lock limit

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3506]
As discussed in: https://github.com/ipfs/go-ipfs/pull/3437
Locks are tricky, edge cases are easy to miss and even easier to introduce later.

I don't know if you agree with me but I would like to limit ourselves to at most two locks in play at any given time. As it was shown before (by deadlock in bitswap and the PR that almost introduced lock related race), it is hard to get work on two concurrent locks correctly. With three it would be even easier to miss some edge case.

The alternative to locks is actor/messenger patter, problem with it is that it is harder to reason about and is much more verbose but I think possible bugs introduced by interaction of three locks overweight cons of this pattern.

I would love to hear your comments and thoughts on this issue.
cc  @hsanjuan @jbenet @lgierth @whyrusleeping

**Comment by whyrusleeping** [comment]
Depends on the situation. I'm not going to make any blanket rules about "thou shalt not use this many locks".

**Comment by Stebalien** [comment]
(old discussion)
