### ISSUE TITLE
question: IpfsRouting interface residue (FindProviders)

### ISSUE THREAD

**Issue by Zanadar** [ipfs/go-ipfs#3510]
#### Version information:
```
go-ipfs version: 0.4.5-dev-047a702
Repo version: 4
System version: amd64/darwin
Golang version: go1.7.3
```

#### Description:
I was poking around writing some tests for `offline` routing and I discovered that there seems to be some residue of an interface that I can't find anywhere else in the form of the `FindProviders` method.

`IpfsRouting` does not implement this method at present, but a few tests and mocks hanging around call it ([eg](https://github.com/ipfs/go-ipfs/blob/master/routing/mock/interface.go#L28)).  Maybe this is a method that got pulled out of IPFS but certain callers never reflected that?

A [quick search](https://github.com/ipfs/go-ipfs/search?utf8=%E2%9C%93&q=FindProviders%28) reveals its fairly isolated to a mock and the tests that rely on that mock, but I could be missing something.

**Comment by Kubuxu** [comment]
It is implemented by go-libp2p-kad-dht: https://github.com/libp2p/go-libp2p-kad-dht/blob/67413010a1f5dc28edc3e353b97a66b2a4063903/routing.go#L292

**Comment by whyrusleeping** [comment]
Yeah... `FindProviders` is deprecated in favor of the `FindProvidersAsync` call. We should probably just remove it for good at this point.

**Comment by Zanadar** [comment]
Makes sense. I can put up a PR to pull it out.
