### ISSUE TITLE
Download progress bar goes over 100%

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/go-ipfs#3529]
#### Version information:

go-ipfs version: 0.4.5-dev-548490f
Repo version: 4
System version: amd64/darwin
Golang version: go1.7.3

#### Priority: P5

The download progress bar goes over 100%. See below for an example.

```
ipfs get Qmcd7Sebd46vxDWjbUERK8w82zp8sgWTtHT5c93kzr2v3M
Saving file(s) to Qmcd7Sebd46vxDWjbUERK8w82zp8sgWTtHT5c93kzr2v3M
 2.50 KB / 734 B [====================================================================================================] 348.77% 0s
```

**Comment by whyrusleeping** [comment]
I think this might be a result of differences between dag size and filesize... not 100% sure though, will investigate more.

**Comment by whyrusleeping** [comment]
I beleive the issue here is that we pipe everything through a tar stream, and we're tracking the progress of the tar over the actual size of the files.

**Comment by whyrusleeping** [comment]
This has been fixed
