### ISSUE TITLE
Archiving git branches

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3531]
I think @lgierth mentioned this some time ago.
It might be worth archiving old branches (ones without open PR, not active for past month or so) to other repo so 1. size of the repo fetch is reduced 2. branch namespace frees up a bit

Archiving them to separate repo/remote would be probably the best solution but other would be to move them to branch sub-name (like `archive/`).

**Comment by Kubuxu** [comment]
It becomes a bit more relevant now as all branches are visible in Jenkins. 
Would you agree to create a `go-ipfs-archive` repo and move old unused branches to it?

**Comment by Kubuxu** [comment]
cc @lgierth @whyrusleeping

**Comment by lgierth** [comment]
Yes SGTM :+1: something like, older than a month, and not bound to an open PR.

**Comment by lgierth** [comment]
Ah yeah you suggested the exact same :P

> ones without open PR, not active for past month or so

**Comment by whyrusleeping** [comment]
@Kubuxu we're doing this now, right? Can we close this issue?

**Comment by Kubuxu** [comment]
https://github.com/ipfs/go-ipfs-archived
