### ISSUE TITLE
Keys from keystore are not republished to DHT

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3537]
Needs to be added to `node.IpnsRepub.AddName`.

We need to probably also store the last published entry to keep it through node resets.

**Comment by wigy-opensource-developer** [comment]
Thanks, Kuba. I just added a comment to #3472 about this missing part.

**Comment by whyrusleeping** [comment]
Lets definitely try and get this done in 0.4.8, Don't want the keystore feature to remain semi-gimped for long

**Comment by whyrusleeping** [comment]
more discussion in https://github.com/ipfs/go-ipfs/issues/3808

**Comment by whyrusleeping** [comment]
@Kubuxu this is done now, right?
