### ISSUE TITLE
Constantly crashes within 5 minutes after start "runtime/cgo: pthread_create failed: Resource temporarily unavailable"

### ISSUE THREAD

**Issue by Inversion-des** [ipfs/go-ipfs#3542]
#### Version information:
go-ipfs version: 0.4.4-
Repo version: 4
System version: amd64/linux
Golang version: go1.7

#### Description:
Crashes without any activity.
There is 5GB RAM free, so should not be OOM.
Output ends with "Daemon is ready".

$> ipfs repo stat
>NumObjects       20
RepoSize         798799
RepoPath         /home/test/.ipfs
Version          fs-repo@4

Changes in config:
- "StorageMax": "300MB"
- "Gateway": "/ip4/0.0.0.0/tcp/8090"

Logs from 2 crashes:
[ipfs_erros_1.zip](https://github.com/ipfs/go-ipfs/files/674581/ipfs_erros_1.zip)
[ipfs_erros_2.zip](https://github.com/ipfs/go-ipfs/files/674582/ipfs_erros_2.zip)

**Comment by Kubuxu** [comment]
It is probably due to low process limit, either try updating to one of pre releases of 0.4.5 or increase the process limit with `ulimit -u 1024`.

**Comment by Inversion-des** [comment]
$ ulimit
>unlimited

Is it ok? Or should I try to change it to 1024?
It's on Debian.

**Comment by Kubuxu** [comment]
Check `ulimit -u`.

**Comment by Inversion-des** [comment]
same here
$ ulimit -u
>unlimited

**Comment by eingenito** [comment]
I'm going to close this issue due to age. Please reopen if you are still experiencing this with recent builds.
