### ISSUE TITLE
`ipns resolve` doesn't resolve subdomains correctly

### ISSUE THREAD

**Issue by the-kenny** [ipfs/go-ipfs#3546]
#### Version information:

```
go-ipfs version: 0.4.4-
Repo version: 4
System version: amd64/linux
Golang version: go1.7.4
```

#### Description:

I set up a ipns record on my DNS provider. The domain is `tarn-vedra.de`. It resolves to `/ipfs/QmUuWNu8rmeLmWXNcagbxCM1utw5qcAJoQtypCQoRjD7jP/index.html`

I also run a blog on a subdomain. The domain is `blog.tarn-vedra.de`. There, the following record is set:

```
blog.tarn-vedra.de.     10799   IN      TXT     "dnslink=/ipfs/QmdW3xv6W2d26N6Zh8HwEWYAY9WRwDbMC43uZNQFfJbMYL"
```

Now I *thought* `ipfs resolve /ipns/blog.tarn-vedra.de` would resolve the record set for the subdomain. The actual result is the entry for `tarn-vedra.de`

Is this intended behavior?

**Comment by whyrusleeping** [comment]
This is odd, @lgierth any ideas?

**Comment by ivan386** [comment]
@the-kenny add new txt record:
`_dnslink.blog.tarn-vedra.de.     10799   IN      TXT     "dnslink=/ipfs/QmdW3xv6W2d26N6Zh8HwEWYAY9WRwDbMC43uZNQFfJbMYL"`

**Comment by the-kenny** [comment]
@ivan386 That works, thanks :) Can you explain why this is necessary and why my other configuration didn't work?

**Comment by ivan386** [comment]
@the-kenny 
I am guessing wildcard dns record points to tarn-vedra.de.

IPFS client resolves 2 dns txt recods `blog.tarn-vedra.de.` and `_dnslink.blog.tarn-vedra.de.`

The second entry has a higher priority.  Because of wildcard record `_dnslink.blog.tarn-vedra.de.` was point to `tarn-vedra.de.`

**Comment by Kubuxu** [comment]
They have the same priority as far as go-ipfs is concerned, having two different records under those two domains `blog...` and `_dnslink.blog` might cause unexpected results.

**Comment by whyrusleeping** [comment]
I beleive the `_dnslink` option has the higher priority. If both are set we use the dnslink one

**Comment by Kubuxu** [comment]
That is true, it was changed at request. This also explains why dnslink seems slow in some cases, I think.

@the-kenny is it god to close?

**Comment by Kubuxu** [comment]
Closing, if you find some other issue with it, please open a new issue.
