### ISSUE TITLE
support input cbor in dag put command

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-ipfs#3551]
#### Version information:
go-ipfs version: 0.4.5-dev-4cb236c
Repo version: 4
System version: amd64/linux
Golang version: go1.7.1

#### Type:
Enhancement

#### Priority:
P4 (for me)

#### Description:
Support input cbor format in dag put command

e.g. 
```bash
echo -e "\xA1\x64\x64\x61\x74\x61\x60" | ipfs dag put --input-enc=cbor
```
returns "Error: unrecognized input encoding: cbor"

**Comment by whyrusleeping** [comment]
Note that as a temporary workaround, you can use block put:

```
echo -e "\xA1\x64\x64\x61\x74\x61\x60" | ipfs block put --format=cbor
```

**Comment by ianopolous** [comment]
Excellent! Thank you, @whyrusleeping. That drops this a priority level or two. :-)

**Comment by ianopolous** [comment]
Is there any reason not to use the block.{put / get} commands permanently? They fit our use case perfectly.   The only reason we couldn't use them previously is we didn't want to mess around with protobuf. (We don't need any of the ipld selector stuff)

**Comment by mib-kd743naq** [comment]
@ianopolous don't see why not - `block put` should be entirely content/encoding agnostic.

**Comment by ianopolous** [comment]
@mib-kd743naq surely it must be a valid encoding so ipfs can parse the embedded merkle links?

**Comment by mib-kd743naq** [comment]
@ianopolous Nope. Each block is "put" independently. It is up to you to provide a complete dag. Only higher order commands ( like `ipfs object` etc ) try to parse stuff.

Consider:
```
~$ echo garbage | ipfs block put -f cbor
zdpuAnnzx1Ue3fGV77nycvwuT71cvguGNZ5R4SK3Yse3GbvAj
```

Which results in a working https://ipfs.io/api/v0/block/get/zdpuAnnzx1Ue3fGV77nycvwuT71cvguGNZ5R4SK3Yse3GbvAj
But a silently failing https://ipfs.io/api/v0/object/get/zdpuAnnzx1Ue3fGV77nycvwuT71cvguGNZ5R4SK3Yse3GbvAj
and https://ipfs.io/ipfs/zdpuAnnzx1Ue3fGV77nycvwuT71cvguGNZ5R4SK3Yse3GbvAj

**Comment by ianopolous** [comment]
What I meant was if I put two blocks, and block A has a valid cbor merkle link to the other and i recursively pin block A, then I expect IPFS to also pin the other block. If that doesn't work, unfortunately that's a deal breaker.

**Comment by mib-kd743naq** [comment]
@ianopolous a `put` **does not** imply a `pin`. You have to do an `ipfs pin X` explicitly after all your `ipfs put`s took place.

This is what I meant by an earlier
> `block put` should be entirely content/encoding agnostic.

**Comment by ianopolous** [comment]
Let me be clear. If I execute the following commands, and A is valid cbor in ipld canonical encoding, containing a merkle link to B, then I expect ipfs to pin B as well (based on my reading of all the docs/code):
```bash
cidB = ipfs block put B
cidA = ipfs block put A
ipfs pin -r cidA
```

**Comment by mib-kd743naq** [comment]
> If... A is valid cbor in ipld canonical encoding, containing a merkle link to B, then I expect ipfs to pin B as well 

@ianopolous that is correct. The ticket was about `put` specifically, so I answered in that context. Sorry for the confusion.

**Comment by ianopolous** [comment]
@mib-kd743naq Phew! I was starting to get worried about my world view there. :-)

**Comment by whyrusleeping** [comment]
This is now done :)

```
echo "CBORSTUFF" | ipfs dag put --input-enc=raw
```

**Comment by whyrusleeping** [comment]
@ianopolous wanna verify and close this out?

**Comment by ianopolous** [comment]
@whyrusleeping This gives the expected result, but why call the encoding raw, rather than cbor?
```bash
printf "\xA1\x64\x64\x61\x74\x61\x60" | ipfs dag put --input-enc=raw | ipfs dag get
=> {"data":""}
```

**Comment by whyrusleeping** [comment]
@ianopolous because that flag is signalling an encoding, not a serialization format.

**Comment by whyrusleeping** [comment]
Gonna go ahead and close this now :)
