### ISSUE TITLE
(!) go-ipfs silently malfunctions in case of datastore corruption

### ISSUE THREAD

**Issue by mib-kd743naq** [ipfs/go-ipfs#3559]
#### Version information:
`any`

#### Type:
`Bug`

#### Priority:
`P0`

#### Description:
```
~$ echo -n 123 | ipfs add --raw-leaves
added zb2rhhqpmFZaUQuktAbCi9YoJwAqgqFq4biAfxBjy7hDKqpUA zb2rhhqpmFZaUQuktAbCi9YoJwAqgqFq4biAfxBjy7hDKqpUA
```
```
~$ ipfs cat zb2rhhqpmFZaUQuktAbCi9YoJwAqgqFq4biAfxBjy7hDKqpUA
123
```
```
~$ echo -n aww > .ipfs/blocks/AFKRE/AFKREIFGMWSFSICCF6OUC7SIM7X5YT5YUBFB6P77D6QH5GMOQ337PIT24M.data
```
```
~$ ipfs cat zb2rhhqpmFZaUQuktAbCi9YoJwAqgqFq4biAfxBjy7hDKqpUA
aww
```

It might be the case that checks are disabled by default for performance reasons ( which would be reasonable ). But having at least a non-default option to force-verify every from-disk read would be essential...

I am also not sure nor know how to test if stuff coming from bitswap is rigorously verified before it is written to disk ( bitflips past the network interface are not unheard of )

**Comment by lgierth** [comment]
The `Datastore.HashOnRead` option should cover this.

**Comment by mib-kd743naq** [comment]
Duh... I actually **looked** through the options and missed it :/
Option works as expected
Sorry for the noise
