### ISSUE TITLE
How to cleanup `ipfs dht findpeer QmBlah` for my own node?

### ISSUE THREAD

**Issue by wigy-opensource-developer** [ipfs/go-ipfs#3561]
go-ipfs version: 0.4.5-dev-
Repo version: 4
System version: amd64/linux
Golang version: go1.7.3

#### Type:
Bug

#### Priority:
P2

#### Description:
I am using a laptop that moves between networks, so its public facing IPv4 address changes. Also, at least in Hungary, most of the ISPs ask extra money for static public IPv4 addresses, so even an always-on desktop is in a LAN that gets routed through different public IPv4 every day or week.

My IPFS node therefore gathered quite some addresses if you ask `ipfs dht findpeer QmBlah` or `ipfs id QmBlah` on another node (If you ask it on the same node, the first returns nothing after a loooong wait, the second returns the same data that `ipfs id` would, which excludes public IP addresses).

Is there a way to remove obsolete multiaddresses for a node from the DHT?

**Comment by Kubuxu** [comment]
They will expire on their own. How many addresses you see there?

**Comment by wigy-opensource-developer** [comment]
I see around 8-9 public IPv4 addresses. They seem to be causing delays in contents pinned only on this node. Also, I have the feeling that IPNS records that were published from this laptop are resolved slowly on other nodes.

**Comment by Kubuxu** [comment]
When all the nodes that have those peer infos will restart, we probably should have timeout on those.

**Comment by wigy-opensource-developer** [comment]
So without any incentive system internal to IPFS for storing DHT records indefinitely, I see that reproviding content / republishing names / resharing peer infos every day makes complete sense (https://github.com/libp2p/go-libp2p-kad-dht/blob/master/records.go#L22).

I am still digging up the DHT code to find out where the stale addresses are reshared by the peers and will try to come up with a PR.

**Comment by Kubuxu** [comment]
The peer info is a bit different form what I know, not sure though.

**Comment by whyrusleeping** [comment]
The address factory work that @lgierth was doing should help with this.

**Comment by lgierth** [comment]
The work that'll actually fix this is properly signed peer routing records. Right now anyone can publish addresses for any peer. Instead, only the actual node should be able to publish addresses for itself, and it should attach a TTL.

I think that depends on IPRS?

The address factory work (`Addresses.Announce` and `Addresses.NoAnnounce` in go-ipfs config) won't solve the issue that all kinds of addresses for your node are floating across the network.

**Comment by Stebalien** [comment]
This should actually be fixed now.

1. We now _push_ new addresses when they change.
2. DHT nodes (once they upgrade to the next release) will _replace_ their known addresses for a peer when receiving a new set instead of adding them.
3. DHT queries only return information about directly connected peers (except for content routing but that information will expire pretty quickly).

All together, this should mostly fix this issue (although signed peer routing records are still something we need).
