### ISSUE TITLE
IPFS disconnects internet

### ISSUE THREAD

**Issue by emuNAND** [ipfs/go-ipfs#3564]
#### Version information:
0.4.4
#### Type:
Bug
#### Priority:
P1
#### Description:
running the IPFS daemon causes the connection from the computer running the daemon to the router to slow to a halt. no error is shown except for not finding the hash table because of the lack of internet. both my wireless card and my usb adapter have this problem. i am unable to connect an Ethernet cable because of how far the computer is from the router. also, if it's any help, i am running Ubuntu Gnome 16.10
i will edit this later with more details since i am away from my computer right now.

**Comment by Kubuxu** [comment]
Covered by: https://github.com/ipfs/go-ipfs/issues/3320 https://github.com/ipfs/go-ipfs/issues/3216 https://github.com/ipfs/go-ipfs/issues/2234

If you think that those issues cover it, please close this one.

**Comment by emuNAND** [comment]
thanks Kubuxu, #2234 fixed my problem.
