### ISSUE TITLE
No ( apparent ) way to list the hash of existing keys

### ISSUE THREAD

**Issue by mib-kd743naq** [ipfs/go-ipfs#3568]
#### Version information:
```
go-ipfs version: 0.4.5-dev-d83a911
Repo version: 4
System version: amd64/linux
Golang version: go1.7.4
```

#### Type:
`Bug/Missing Feature`

#### Priority:
`P1`

#### Description:
I can get my `self` IPNS id via the command `ipfs id`. But there seems to be no way to list the hash for some secondary key aside from publishing something to the keyslot with `ipfs name publish -k <key>`

Before this is released as stable `ipfs key list` should gain a way to list the corresponding hashes ( either by default or with an option )

**Comment by whyrusleeping** [comment]
Yeah, i mentioned this as well in my 0.4.5 review: https://github.com/ipfs/go-ipfs/issues/3534#issuecomment-269076321

**Comment by kevina** [comment]
I'll look into it.  I am unfamiliar with that part of the code but this seams a simple enough task.  If I can't figure out what to do I will unassigne myself.
