### ISSUE TITLE
How to launch ipfs daemon in background (Windows cmd)

### ISSUE THREAD

**Issue by slrslr** [ipfs/go-ipfs#3572]
Hello,

i downloaded Windows version of the IPFS from https://ipfs.io/docs/install/
and i am having .bat script that is launching multiple applications on my computer start.

I used this commands in that .bat script:

start "" /MIN /B "C:\Windows\system32\ipfs.exe" daemon
start "" /MIN "C:\Windows\system32\ipfs.exe" daemon
start "" "C:\Windows\system32\ipfs.exe" daemon

It launch the daemon, but i still see the command line window and i do not want to see it, i want it to run on background (hiddenly). Which command to use or how to do it in Windows? Thank you

**Comment by kpcyrd** [comment]
This might help:
https://superuser.com/questions/198525/how-can-i-execute-a-windows-command-line-in-background

The cleanest way in windows is probably having a desktop client that has a regular installer and sets itself to auto-start, while also having go-ipfs as a subprocess. (I think some other open source projects do something like this).

**Comment by slrslr** [comment]
I thought there is only one ipfs for Windows. btw, none of the "START" kind of commands mentioned on yours linked page worked for me to launch ipfs daemon the way that it is not terminated when the command line window is closed.

But in my case I still have to keep open one cmd window because of other app that is running inside it, so i made it the way that i launch ipfs first at background and then this other app like this:
start /B "" "C:\Windows\system32\ipfs.exe" daemon > ipfsoutput.txt & start c:\path\to\other\exe

I still will be looking for the way to run daemon better way on windows without cmd window being open.

**Comment by chosenken** [comment]
Ok, I found a way to start IPFS in the backgroup without a command window staying up.  The downside is you don't see any logs, and you have to kill the program via the Task Manager.  If you have [Git for Windows installed](https://git-scm.com/download/win), then you just need to create a bash file to execute IPFS.  The contents would be:

```bash
#!/bin/bash
/c/Windows/System32/ipfs daemon &
```

Save this as something like `ipfs_daemon.sh`, then place it in `C:\Users\<Name>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`.  This folder will auto-start whatever is inside it.  Now on login/startup, it will start the daemon in the background.

**Comment by Kubuxu** [comment]
Closing as it it is not actionable from go-ipfs side. If you have more questions about that use http://ipfs.trydiscourse.com/.

**Comment by nicolasayotte** [comment]
You make a batchfile here : $APPDATA/Microsoft/Windows/Start Menu/Programs/start-scripts.cmd
```batch
pwsh %userprofile%\bin\Start-IpfsDaemon.ps1
```

And then you place in your $HOME/bin/Start-IpfsDaemon.ps1

```powershell
$options = @{
  FilePath               = 'ipfs'
  ArgumentList           = @('daemon')
  WindowStyle            = 'Hidden'
  RedirectStandardOutput = "$env:TEMP/ipfs.log" 
  RedirectStandardError  = "$env:TEMP/ipfs.err" 
}
Start-Process @options
```
