### ISSUE TITLE
unclean shutdown prevents restart

### ISSUE THREAD

**Issue by kpcyrd** [ipfs/go-ipfs#3574]
#### Version information:
```
go-ipfs version: 0.4.4-8b35f9b
Repo version: 4
System version: amd64/linux
Golang version: go1.7.3
```

#### Description:

I'm running ipfs inside docker containers on a Container Linux/CoreOS cluster. After a while I noticed all my containers are dead and failed to restart due to a locking issue.

On irc I got the hint to run `ipfs repo fsck` (I submitted a patch in #3573 to make this easier), which fixed the issue. I sort of have to rely on ipfs to be able to restart after unclean shutdowns, therefore I'm filing this bug. :)

ipfs should be able to detect the the repo isn't locked anymore, even though the lockfiles still exist.

**Comment by kevina** [comment]
@whyrusleeping what do you think?  Should we put the process pid into the `repo.lock` file and just remove it if no ipfs process is running with that pid.

**Comment by Kubuxu** [comment]
@kevina repo.lock already does that using native Linux API http://man7.org/linux/man-pages/man2/flock.2.html

**Comment by kevina** [comment]
@Kubuxu sorry your right, I also killed ipfs with SIGKILL and was able to restart it even though repo.lock already exists.  I'm not sure what problem @kpcyrd is seeing.

**Comment by kpcyrd** [comment]
This only happend in a docker container that died (probably) because of OOM. I'm not sure I missed something when filing this issue and I couldn't reproduce it since, so I'm closing this issue.
