### ISSUE TITLE
Add + Support an  `offset` flag for `ipfs cat`

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#3578]
What the title suggests :)

**Comment by mib-kd743naq** [comment]
Surely `ipfs cat ... | tail -c +2000` is enough for this...?

**Comment by diasdavid** [comment]
We need to have support for it coming from the http-api too.

**Comment by lgierth** [comment]
Would Range headers satisfy this need on the http api? We get these for free with go's net/http. They're already used e.g. for skipping in a video/audio file through the gateway.

**Comment by whyrusleeping** [comment]
@diasdavid how would we handle calling `ipfs cat` on multiple hashes? like `ipfs cat QmdrSmgViWKCjRntzsoiFhzQ1Wsce2ig5nZErS7SvXr9Ng QmWJ7ot9xrhkSHwCqm9XAhnXe944nXYQQ3tCSmXfnxUWNj` ?

**Comment by diasdavid** [comment]
Good question. What about simply treating the concatenation of both files as a single file for the offset?

**Comment by magik6k** [comment]
Done in #4538
