### ISSUE TITLE
Add `make source` for options on building on less common systems

### ISSUE THREAD

**Issue by rht** [ipfs/go-ipfs#3579]
#### Description:

> Note: This process may break if gx or any of its dependencies break as go get will always select the latest code for every dependency, often resulting in mismatched APIs.

To peg the version, it should be sufficient with a redirect gopkg.in/whyrusleeping/gx-go.v1. This is an additional POF, but still better than the current method for "building on less common systems", which is without the version peg.

**Comment by whyrusleeping** [comment]
This has been added `make install_unsupported`
