### ISSUE TITLE
`ipfs pin` hangs, has no option for timeout

### ISSUE THREAD

**Issue by sneak** [ipfs/go-ipfs#3594]
#### Version information:

ipfs@ipfs:~ $ ipfs version --all
go-ipfs version: 0.4.5-dev-56058c1
Repo version: 4
System version: arm/linux
Golang version: go1.7.4

#### Description:

I have a machine running the ipfs daemon 24/7 that grabs a text file from my ipns namespace, and iterates over the lines, doing an `ipfs pin add $ENTRY` via cron, to automatically mirror whatever I toss into that file.

I logged in and found a zillion `ipfs pin` processes sitting there hanging, some days old.

Is it possible to add a timeout for things like `ipfs pin` (and other things that tend to hang for extremely long periods/indefinitely, like `ipfs name resolve`)?  This would make scripting a lot easier, I could just add a --timeout=60s or something.

**Comment by sneak** [comment]
This may be related/dupe of #3533.

**Comment by whyrusleeping** [comment]
I think the reason for the hang has been fixed in a recent PR, but for the timeout, you can pass `--timeout` to any ipfs command (i know, this is pretty much undocumented).
