### ISSUE TITLE
Gateway and readonly repo

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#3596]
The gateway tries to fetch, store, and serve any hash that is requested. It would be useful to be able to refine this behavior, e.g. for repos in readonly environments. The naming is the best I could come up with adhoc.

- [x] `Gateway.Fetch ||= true` config option: whether a hash that has been requested should be fetched from the network if it isn't stored locally yet. If set to false, the gateway will immediately respond with a client error (4xx) if the requested stuff isn't stored locally.
- [ ] `Datastore.Readonly ||= false` config option: whether stuff that has been fetched (as in the above) should be stored locally, or discarded after sending it with the response.

**Comment by Stebalien** [comment]
The first part has been implemented. The second part has significant performance implications and probably won't be (one should just use GC for that).
