### ISSUE TITLE
ERROR: dht: checking dht client type: &errors.errorString{s:"EOF"} notif.go:38

### ISSUE THREAD

**Issue by sere4tegdd** [ipfs/go-ipfs#3599]
I get that error after starting `ipfs daemon`

**Comment by Kubuxu** [comment]
@whyrusleeping was this fixed already? I am 90% sure that I wasn't fixing it.

**Comment by FrankPetrilli** [comment]
Just wanted to throw this in; with a brand new master revision, I got this error after the daemon was running for a few hours:

`21:30:28.981 ERROR        dht: checking dht client type: &errors.errorString{s:"EOF"} notif.go:38`

**Comment by whyrusleeping** [comment]
Yeah, this hasnt been fixed yet... Let me go do that.

**Comment by whyrusleeping** [comment]
This should now be resolved.
