### ISSUE TITLE
Unable to mount new installation - installation instructions may need updating/revising

### ISSUE THREAD

**Issue by mitra42** [ipfs/go-ipfs#3601]
#### Version information:
go-ipfs version: 0.4.4-
Repo version: 4
System version: amd64/darwin
Golang version: go1.7

#### Type: 
Bug

#### Priority:
P3

#### Description:
Installed IPFS
Installed go
Installed Fuse from https://osxfuse.github.io/
The installation instructions don't work well (Mac OSX 10.11.6)
ipfs mount complains about not being able to check the version
Even after installing fuse-version with go get github.com/jbenet/go-fuse-version/fuse-version
ipfs mount still reports the error
ipfs config DontCheckOSXFUSE true
however reports
mitraplasma:~ mitra$ ipfs config DontCheckOSXFUSE true
Error: failed to set config value: Wrong config type, expected bool (maybe use --json?)
Trying TRUE or True didn't work any better

After that ipfs mount gets
Error: config key invalid: DontCheckOSXFUSE %!s(bool=true)

So unable to mount ipfs

Happy to run any tests to check this.

**Comment by 20zinnm** [comment]
I second this. Just tried mounting, does not work on Mac--Fuse version check fails every time.

**Comment by Stebalien** [comment]
Well, this is a bit old. See: https://github.com/ipfs/ipfs/issues/343#issuecomment-409100391

To answer the question: the suggested command should have been `ipfs config --json DontCheckOSXFUSE`
