### ISSUE TITLE
More granular address announcements

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#3613]
Sometimes a go-ipfs listener can not directly bind to its external address. This is e.g. the case with NAT, where it binds to an IP address in the local network, while other nodes dial it using the local router's public IP address. We jump through all kinds of hoops to work around that, and one of these is "observed addresses", where other nodes tell us which addresses they've seen us using.

Another example are HTTP-based transports like /ws, which will in many cases be behind an SSL-terminating reverse proxy. Bound address: /ws, external address: /wss. There is a way to discover that we're behind a reverse proxy (by passing a special HTTP header), but that would only work after the first request has come in. Until then, the node would be unaware of its /wss address.

We could just as well have an ExternalAddresses config option though (or ideally both). This might also be useful for announcing /dns addresses. The default bootstrappers will eventually be bootstrap.libp2p.io or so, and they'd be able to announce it.

**Comment by mateon1** [comment]
Related: ipfs/faq#185 (using SOCKS with IPFS)

**Comment by lgierth** [comment]
@diasdavid @Kubuxu @whyrusleeping what do you think of this?

What I was thinking of is something like a `Addresses.Announce` array option. @diasdavid also brought up the inverse use case, excluding certain addresses from announcement (`Addresses.NoAnnounce`).

If `Addresses.Announce` is empty, we'll infer the addresses to announce as usual. If `Addresses.NoAnnounce` is non-empty, we'll exclude any matching address from the set of to-be-announced addresses.

`Addresses.NoAnnounce` should allow for filtering based on `/ipcidr`. It would probably be useful to allow for `/ipcidr` in `Addresses.Swarm` too.

### Examples

Websocket listener behind an HTTPS reverse proxy:

```json
{
  "Addresses": {
    "Swarm": [
      "/ip6/::/tcp/80/ws"
    ],
    "Announce": [
      "/dns6/example.net/tcp/4001/wss"
    ]
  }
}
```

Normal TCP listener, but don't announce our 172.16.0.0/12 addresses.

```json
{
  "Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001"
    ],
    "NoAnnounce": [
      "/ip4/172.16.0.0/ipcidr/12"
    ]
  }
}
```

**Comment by lgierth** [comment]
The bootstrap nodes would announce their IP, and their dnsaddr.

```json
{
  "Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001"
    ],
    "Announce": [
      "/ip4/1.2.3.4/tcp/4001",
      "/dnsaddr/libp2p.io"
    ]
  }
}
```

**Comment by whyrusleeping** [comment]
This all looks good to me. :+1:

**Comment by diasdavid** [comment]
Thanks @lgierth, this pretty much covers my concerns.

While we are at it, can we piggy back a old proposed change of putting libp2p things under libp2p key?

```
libp2p: {
  addresses: {
    swarm:
    announce:
    noAnnounce:
  }
  discovery
  ...
}
```

**Comment by whyrusleeping** [comment]
@diasdavid We *can* do that, but it doesnt need to be coupled to the change @lgierth is proposing. This change doesnt require a migration, renaming those keys does.

That said, we have needed a config file migration to update defaults for a good while

**Comment by lgierth** [comment]
> That said, we have needed a config file migration to update defaults for a good while

Yeah I can take care of it when patching the new bootstrap addrs into the config.

**Comment by lgierth** [comment]
I have a hunch this is gonna get ugly unless I refactor things a bit. Listened-on addresses and their announcement is currently pretty strongly coupled. Maybe it's worth introducing a broker-like object which would control the logic around our node's addresses.

**Comment by lgierth** [comment]
> I have a hunch this is gonna get ugly unless I refactor things a bit

No, actually it's gonna be just fine. See libp2p/go-libp2p#196 for the few changes that are needed on go-libp2p's part.
