### ISSUE TITLE
pin add needs a progress bar

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3624]
It currently just prints nothing until its done, this can lead people (myself included) into thinking that its frozen.

**Comment by Voker57** [comment]
Problem is, it's most likely doing FetchGraph, and it's impossible to tell when it stops until it's done. "cycle" progress bar which changes state each fetched node?

**Comment by whyrusleeping** [comment]
Yeah, thats most of the reason why we don't have a progress bar for this yet. We could do something cool with passing the progress updater down inside a context, and then in the FetchGraph code updating our 'nodes to fetch' and 'nodes fetched' counts as we explore the graph.

**Comment by kevina** [comment]
I think we need a general framework for somehow showing progress on operations that take a long time.  I think the garbage collector falls in the same category.  Just some sort of way to indicate progress to the user...

**Comment by whyrusleeping** [comment]
As @Voker57  said, I think an output of "Fetched/Processed %d nodes" would be sufficient.

Right now i track pin progress by watching `ipfs bitswap stat` to see the number of received blocks.

As i mentioned in my previous comment, the easiest way to do this would probably be to pass a "Progress Counter" object through the context, and in `FetchGraph` check if our context has one of these, and update it with information as we fetch things.

**Comment by kevina** [comment]
Okay, I will look into it and see what I can do.
