### ISSUE TITLE
Block.put returns Multihash instead of Cid

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-ipfs#3627]
#### Version information: go-ipfs version: 0.4.5-pre2-416f025
Repo version: 5
System version: amd64/linux
Golang version: go1.7.1

#### Description:
The http api for block.put seems to still return multi-hashes rather than cids (in the JSON object that is returned). 

E.g.
{"Key":"QmVBCpx91Yb5hGCqkQbWeqQ83B8r9mbN9EMr3c6y22ePKE","Size":12}

**Comment by whyrusleeping** [comment]
@ianopolous what paramters are you passing to block put for format? By default it creates an old style node (protobuf, cidv0).

**Comment by mib-kd743naq** [comment]
@ianopolous specifically:

```
~$ echo -ne "\x4b\x67\x27\x64\x61\x79\x20\x49\x50\x46\x53\x21" > /dev/shm/hello_cbor

~$ curl -X POST 'localhost:5001/api/v0/block/put?format=cbor&mhtype=sha2-512&mhlen=48' -F 'data=@/dev/shm/hello_cbor'
{"Key":"zM59kiJaF1YinUK4HFUJYTVbh4AiSeUs369wZ62UzYWLaWi2rqY5JcvRXAHD5riM9M2ueLu","Size":12}
```

**Comment by ianopolous** [comment]
Sorry, I'm an idiot. Of course it needs the format=cbor.
