### ISSUE TITLE
blockstore query also queries leveldb

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3628]
The way the namespace datastore works is that it queries both underlying datastores and filters out the correct entries it needs. This is both really inefficient, and since leveldb cant seem to be queried concurrently, causing me a headache elsewhere. We should fix this abstraction and pass a direct reference to flatfs to the blockstore (or have the namespace datastore be mount datastore aware)

**Comment by whyrusleeping** [comment]
@kevina do you think you could take a look at this? I think the idiomatic go way to do this would be to make the namespace datastore understand mount datastores and be able to optimize for that case.

**Comment by kevina** [comment]
@whyrusleeping, sure I am a little confused on to what you are after though.

**Comment by kevina** [comment]
Okay I think I understand I'll look into this soon, likely tomorrow.

**Comment by whyrusleeping** [comment]
My thought is that when a namespace datastore is created, it should be able to check if its child is a mount datastore, and if thats the case, and its namespace matches one of the mounts, we can skip all the middle layering and just use the mounted datastore directly (skipping the key appending and trimming stuff).

**Comment by kevina** [comment]
We talked this out over IRC and it seams that this is not the issue @whyrusleeping was seeing.  Both datastores are _not_ being queried.
