### ISSUE TITLE
Flatfs initialization bombs on windows

### ISSUE THREAD

**Issue by cpacia** [ipfs/go-ipfs#3632]
The ultimate cause is something causes a ._check_writeable file to be written to the blocks directory. 

Then when this line of code checks that the directory is empty it returns an error: 

https://github.com/ipfs/go-ds-flatfs/blob/9553971a40e28fd9d1022c66c1dc0b9dc5e03451/flatfs.go#L63

A simple `os.Remove()` fixes it, though I'm not familiar enough with either windows or what IPFS is doing on init to know why that file gets written there.

**Comment by whyrusleeping** [comment]
Thats... weird. I wonder why that file gets created. 

Will need to research this some, and this should get fixed before we ship 0.4.5 (since this is caused by very recent flatfs changes)
cc @kevina

**Comment by kevina** [comment]
[This code](https://github.com/ipfs/go-ipfs/blob/master/thirdparty/dir/dir.go#L18) likely creates it:
```go
func Writable(path string) error {
	// Construct the path if missing
	if err := os.MkdirAll(path, os.ModePerm); err != nil {
		return err
	}
	// Check the directory is writeable
	if f, err := os.Create(filepath.Join(path, "._check_writeable")); err == nil {
		os.Remove(f.Name())
	} else {
		return errors.New("'" + path + "' is not writeable")
	}
	return nil
}
```
Now what to do about it?

**Comment by kevina** [comment]
Okay so [this code](https://github.com/ipfs/go-ipfs/blob/f09bd5c3f18cae2f557066e2c1fd2f2718c64329/repo/fsrepo/defaultds.go#L71) calls Writable:
```go
func initDefaultDatastore(repoPath string, conf *config.Config) error {
	// The actual datastore contents are initialized lazily when Opened.
	// During Init, we merely check that the directory is writeable.
	leveldbPath := path.Join(repoPath, leveldbDirectory)
	if err := dir.Writable(leveldbPath); err != nil {
		return fmt.Errorf("datastore: %s", err)
	}

	flatfsPath := path.Join(repoPath, flatfsDirectory)
	if err := dir.Writable(flatfsPath); err != nil {
		return fmt.Errorf("datastore: %s", err)
	}
	return nil
}
```
We should probably not do that anymore.  Flatfs has a seperate Create function, we should probably use it.  @whyrusleeping agree?

**Comment by whyrusleeping** [comment]
@kevina We should probably make sure that that writeable method doesnt leave a file lingering in it (make sure we remove it afterwards)

**Comment by kevina** [comment]
@whyrusleeping  Writable should already be cleaning up.  Unless os.Create can fail but still write the file.

**Comment by kevina** [comment]
@whyrusleeping Let me know if you want me to do anything on this or if you want to handle it.  I'm afraid I won't be much help in debugging the windows specific problem.

**Comment by whyrusleeping** [comment]
Looks like the issue is that `path` was used instead of `filepath` for concatenation and encoding of keys.

**Comment by whyrusleeping** [comment]
As well as windows having a problem with removing a file thats open. So in the `Writeable` function we have to close `f` before calling remove on it.

**Comment by kevina** [comment]
Okay, I will create a p.r. first thing tomorrow, unless you beat me to it. :)  I won't be able to test it on windows though. :(

**Comment by whyrusleeping** [comment]
I've got one PR up, pushing the second in a little bit
