### ISSUE TITLE
In Windows seems to fail to release lock on ls error

### ISSUE THREAD

**Issue by tkharris** [ipfs/go-ipfs#3633]
#### Version information:
go-ipfs version: 0.4.4-      
Repo version: 4              
System version: amd64/windows
Golang version: go1.7        

#### Description

In Windows seems to fail to release lock on ls error.

> thomas.harris@ThoHarris9-NB10 /cygdrive/c/ipfs-data
> $ ipfs ls QmVRvcjXFuhxYLpHfQF6pHo6Wc8TAsAEzK9fGTbtd9fBEm
> 
> thomas.harris@ThoHarris9-NB10 /cygdrive/c/ipfs-data
> $ ipfs ls QmVRvcjXFuhxYLpHfQF6pHo6Wc8TAsAEzK9fGTbtd9fBEm
> 
> thomas.harris@ThoHarris9-NB10 /cygdrive/c/ipfs-data
> $ ipfs ls bogus
> Error: invalid ipfs ref path
> 
> thomas.harris@ThoHarris9-NB10 /cygdrive/c/ipfs-data
> $ ipfs ls QmVRvcjXFuhxYLpHfQF6pHo6Wc8TAsAEzK9fGTbtd9fBEm
> Error: cannot acquire lock: file "C:\\Users\\Thomas.Harris\\.ipfs\\repo.lock" already locked

**Comment by whyrusleeping** [comment]
@tkharris Thanks for reporting. We are going to try and get windows CI and testing set up in the next several weeks, these sorts of issues should get worked out soon.

**Comment by whyrusleeping** [comment]
Got a windows VM running, managed to reproduce the issue.

**Comment by whyrusleeping** [comment]
Hrm... We might need to update our locking dependency. Its been a solid year since I updated it. (June 21st, 2016)

**Comment by whyrusleeping** [comment]
Hrm... there havent been any updates to that locking lib since our last update. It also supports windows via a fallback locking mechanism. I wonder if theres a better way to do locking on windows?

**Comment by Stebalien** [comment]
Locking files is actually pretty easy on windows, they have mandatory file locks. Actually, it looks like there may be a stale PR you may be able to revive:

https://github.com/camlistore/lock/pull/2 (note, that's on the old repo). Unfortunately, the code in that PR looks a bit more complicated than it really should be...
