### ISSUE TITLE
ipfs get fails with bad message when using wrong version client

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3634]
was running a daemon using ipfs 0.4.5-dev, and tried to ipfs get with 0.4.5-pre2. On most commands this errors with an 'api mismatch' error, but ipfs get errors with an 'unexpected EOF' ugly message.

**Comment by chenminjian** [comment]
The issue should be closed, because the bug has been fixed. Test using ipfs daemon 0.4.18-dev and ipfs client 0.4.17.
