### ISSUE TITLE
IPFS does not respect IPFS_PATH on Windows

### ISSUE THREAD

**Issue by cakenggt** [ipfs/go-ipfs#3641]
#### Version information:
go-ipfs version: 0.4.4-
Repo version: 4
System version: amd64/windows
Golang version: go1.7

#### Description:
I have tried changing my account's environment variable for `IPFS_PATH` and my system variable for it, but neither actually changes where the `init` creates a repo, or where the `daemon` starts up from.

I shut down my command line in between changes to refresh the system variables and it still doesn't work.

**Comment by rht** [comment]
On `Linux majorana 4.4.41 #1-NixOS SMP Mon Jan 9 07:08:10 UTC 2017 x86_64 GNU/Linux`, `ipfs version 0.4.5-dev`, `go version go1.7.4 linux/amd64`, setting `IPFS_PATH` it works just fine.

- Do other env vars function well? e.g. if you could test `IPFS_LOGGING=debug`
- Does the problem persist if you use the latest pre-release? https://github.com/ipfs/go-ipfs/releases/tag/v0.4.5-pre2

**Comment by mateon1** [comment]
This does not happen on my Windows 10 x64 machine.
Can you type `echo %IPFS_PATH%` in the same shell that you are launching the IPFS daemon from?

Note: I had small issues with environment variables when setting them for my user account only. Try setting the IPFS_PATH environment variable system-wide and try again.

**Comment by djdv** [comment]
Also working on my machine.
![untitled](https://cloud.githubusercontent.com/assets/13862850/22404198/0053b4fc-e5fa-11e6-840c-348c4975f4ad.png)

**Comment by Kubuxu** [comment]
Seems like it isn't possible to reproduce. Please reopen with steps to reproduce if it is still an issue.
