### ISSUE TITLE
ipfs add ignore, .ipfsignore

### ISSUE THREAD

**Issue by crackcomm** [ipfs/go-ipfs#3643]
I would love to be able to run `ipfs add -w -r .` but ignoring `node_modules` or `target` directory, or any other directory.
Something like `.ipfsignore` may be an overkill but something like this is what I am looking for.

**Comment by whyrusleeping** [comment]
Yeah, i'd like to have this too. I implemented it semi-manually for `gx` https://github.com/whyrusleeping/gx/blob/master/gxutil/publish.go

**Comment by AlbertoElias** [comment]
Is there a way to ignore files yet?

**Comment by Stebalien** [comment]
This feature was, unfortunately, blocked on one PR that was blocked on another (large) PR. Path forward:

* Fix: https://github.com/ipfs/go-ipfs-cmdkit/issues/5
* Revive: https://github.com/ipfs/go-ipfs/pull/4013

Unfortunately, I'm not sure anyone will have time to work on this at the moment unless @crackcomm has some free time and feels like reviving their PRs.

**Comment by kjzz** [comment]
Hey @whyrusleeping , Has this issue been finished?If not,i am willing to di this.

**Comment by marcusnewton1** [comment]
+1 good idea

**Comment by dholms** [comment]
Any movement on this? It'd be very useful for us (specifically an `--ignore` or `--exclude` flag).
Happy to contribute as well, but want to check the status first since it seems like PRs addressing this (https://github.com/ipfs/go-ipfs/pull/4013) never got unblocked

**Comment by Stebalien** [comment]
@dholms no progress but not blocked, as far as I know. The next step is https://github.com/ipfs/go-ipfs-cmdkit/issues/5. There are two PRs (see the bottom of that issue) trying to fix that but they're kind of hacky. If you'd like to rebase/clean them up, I can take a look at them.

Note: we have quite a few high-priority issues in flight at the moment so reviews may take a while.

**Comment by bmann** [comment]
@Stebalien we're not using golang in-house at the moment, we can see if we can bounty it.

**Comment by hsanjuan** [comment]
Heads up this issue has been picked up by @corntoole. Any feedback and review help on issues linked above from interested parties is more than welcome!

**Comment by Stebalien** [comment]
Ignore file support has now been merged. You can pass:

* `--ignore=file` to skip a file/directory.
* `--ignore-rules-path=.someignorefile` to apply all ignore rules specified by the file.

In the future, we should consider shorter flags (maybe a `-g` flag to ignore files specified by `.gitignore`, etc.) but this is a good, mvp.
