### ISSUE TITLE
Gx-go rewritten imports make it difficult to maintain long-lived branches

### ISSUE THREAD

**Issue by wigy-opensource-developer** [ipfs/go-ipfs#3648]
#### Description:

The source code for go-ipfs is committed _after_ a `gx-go rewrite` was run on it. This effectively makes each go module depend on the exact implementation of other modules, not on their public interface, which is a CS101 anti-pattern.

Let's assume that [go-cid](https://github.com/ipfs/go-cid) got a new commit that makes it 2x faster than before. Getting that into go-ipfs would change 11 dependencies of all 8500 existing currently (`gx deps --tree --highlight go-cid | wc -l`) by changing `packages.json` files all around the projects. Merging those changes might only conflict with other changes involving dependency updates.

In the current source code though we might get merge conflicts for each and every go file using go-cid (85 files only in go-ipfs counted by `grep -rl QmcTcsTvfaeEBRFo1TkFgT8sRmgi1n1LTZpecfVP8fzpGD | wc -l`) **in addition** to having those conflicts in the `packages.json` files. As far as I can tell, this could be avoided by using `gx-go rewrite --undo` before committing the sources to git.

Examples using gx the "right" way:
- https://github.com/multiformats/go-multibase
- https://github.com/libp2p/go-libp2p-kad-dht
- https://github.com/libp2p/go-libp2p

There is no right time to make such a big change in a project, because it is always costly. The only sure thing is that the later it is made the more expensive it gets. How about spending it right after the 0.4.5 release, now that @Kubuxu made it hopefully easier to adapt the build system to this change?

**Comment by lgierth** [comment]
> As far as I can tell, this could be avoided by using gx-go rewrite --undo before committing the sources to git.

Not going to happen, and you're not the first to propose it :)

> which is a CS101 anti-pattern

That might be so, but what we gain is reproducibility. Without the rewritten imports, there would be no way to rebuild e.g. 0.4.5 from source, once there has only been one commit in one of the dependencies.

Before gx, builds would break any time some dependency made some silly change.

We want software and builds that we can trust -- an immutable tree of code is a big step in that direction.

> Examples using gx the "right" way:

These are libraries and they're never used on their own, i.e. they're never the root of the code tree.

- Libraries: classic unrewritten imports for compatibility with any non-gx application
- Applications: rewritten imports for reproducibility

**Comment by wigy-opensource-developer** [comment]
> That might be so, but what we gain is reproducibility. Without the rewritten imports, there would be no way to rebuild e.g. 0.4.5 from source, once there has only been one commit in one of the dependencies.

The reproducibility is built-in to the packages.json. There is no need to copy-paste that 85 more times into actual go files. I did not suggest at all to build go-ipfs using github.com imports. That would be foolish indeed. I understand the purpose of using gx and what problems it solves that is usually overseen by the golang community.

Immutability is not improved at all by copying a piece of information several times into the source code - making it more difficult to work with. Configuration management (branching, merging) is as important piece to the success of this software as which algorithms it uses for encryption. It needs a thriving developer community.

**Comment by wigy-opensource-developer** [comment]
> These are libraries and they're never used on their own, i.e. they're never the root of the code tree.

When I modify a library, I run tests on them. That is the time when they are the root of the code tree. But it is not a big deal, because I do a

- go get -u github.com/this/library
- go-gx rewrite
- gx install
- go test

And then I do a `go-gx rewrite --undo` before the commit. And **this** procedure is exactly what I am suggesting for go-ipfs, too.

**Comment by Kubuxu** [comment]
We are not doing that for exactly one reason: So it is clear that `go get github.com/ipfs/go-ipfs` will not work and is not supported. Otherwise users will use the `go get ...` and then any dependency in our dep-tree can compromise while binary.

**Comment by wigy-opensource-developer** [comment]
OK. What is then the expected workflow to merge master into a long-lived branch that has also some changes to dependencies?

**Comment by Kubuxu** [comment]
Unrewrite master, commit, switch to your branch, unrewrite it, commit. Merge, resolve package.json conflict if there is any.

**Comment by wigy-opensource-developer** [comment]
Exactly where I was heading to. Thanks for confirming. I will not love it though :tongue:

**Comment by Kubuxu** [comment]
Resolve them.

**Comment by wigy-opensource-developer** [comment]
> Or do it manually and resolve conflicts, at first it seems hard but it isn't really.

I opened this issue exactly because of the suckery that was involved in manually resolving conflicts. Especially that gofmt sorts imports by hash if they are not prepended by a module alias, so most of the cases conflicts are not even detected by git, but go build. I always wondered why clever people make their lives harder with using so bad tooling.

**Comment by whyrusleeping** [comment]
> Unrewrite master, commit, switch to your branch, unrewrite it, commit. Rebase or merge, resolve package.json conflict if there is any, rewrite, squash.

Eh... this is what currently works but its a hack. I need to work on better tooling that makes this easier (i *do* accept pull requests to gx by the way ;) )

> I always wondered why clever people make their lives harder with using so bad tooling.

Things are so many times better with gx than without. Dependency management in go is hell. Having to do a couple 'gx-go rewrite' calls when you want to update a old branch is a comparatively low price to pay.
