### ISSUE TITLE
go-ipfs does not compile in docker container

### ISSUE THREAD

**Issue by magwas** [ipfs/go-ipfs#3654]
#### Description:

I want to build go-ipfs in a docker container. It fails.

Dockerfile: http://paste.ubuntu.com/23940726/
Build output: http://paste.ubuntu.com/23940719/

Reproduction:
1. create the Dockerfile
2. docker build .

**Comment by magwas** [comment]
sorry, it was not go, but go-ipfs

**Comment by lgierth** [comment]
That's weird -- it's network errors regarding v04x.ipfs.io. Does the box this runs on have IPv4 connectivity? v04x.ipfs.io is definitely up and will continue to be available.

**Comment by magwas** [comment]
As you can see from the logs, there are multiple wgets going through in order.
Moreover, when I have tried to use wget for one of the failing urls, it did work.

**Comment by lgierth** [comment]
@whyrusleeping is there a way to get more info out of these gx fetch errors_

**Comment by whyrusleeping** [comment]
@lgierth a newer version of gx has more useful error messages. I havent updated the version used by go-ipfs to that yet unfortunately

**Comment by magwas** [comment]
if I can help in anything to pin down the problem, just tell me

**Comment by Kubuxu** [comment]
Does it fail if you try rebuilding it?

**Comment by magwas** [comment]
Yes, still does. Build output: http://paste.ubuntu.com/23965834/

**Comment by whyrusleeping** [comment]
The errors in the last paste look like youre not able to resolve dns queries for some reason. Its showing udp packet timeouts

**Comment by magwas** [comment]
Howevert there are wgets before that with no trouble with dns resolving...

**Comment by Kubuxu** [comment]
It was a bug in Go 1.7 which is the Go version that gx 0.10.0 was compiled with. Current master will use g 0.11.0 which will not have this problem.

**Comment by Kubuxu** [comment]
It was a bug in Go 1.7 which is the Go version that gx 0.10.0 was compiled with. Current master will use g 0.11.0 which will not have this problem.
