### ISSUE TITLE
go-ipfs rc1/2 from dist.ipfs.io fails to install migrations

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipfs#3661]
#### Version information:
go-ipfs version: 0.4.5-rc1-
Repo version: 5
System version: arm/linux
Golang version: go1.7.4

#### Type:
Bug

#### Description:

```
ipfs@tuvok:/opt/go-ipfs $ ./ipfs daemon
Initializing daemon...
Found outdated fs-repo, migrations need to be run.
Run migrations now? [y/N] y
  => Looking for suitable fs-repo-migrations binary.
  => None found, downloading.
  => Failed to download fs-repo-migrations.
The migrations of fs-repo failed:
  failed to download latest fs-repo-migrations: failed to run ldd: exit status 1
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations
Error: failed to download latest fs-repo-migrations: failed to run ldd: exit status 1
```
ldd complains:

```
ipfs@tuvok:/opt/go-ipfs $ ldd ipfs 
	not a dynamic executable
```

IPFS was downloaded from dist.ipfs.io. It seems it is statically built.
https://github.com/ipfs/go-ipfs/blob/master/repo/fsrepo/migrations/migrations.go#L256 fails to run when it tries to guess if we are using `musl` (I'm not sure we provide musl builds for repo migrations anyway).

**Comment by Kubuxu** [comment]
We should provide them as docker containers that run our Dockerfiles run with musl.

**Comment by lgierth** [comment]
Will take care of it tonight -- will change the ldd check to `ldd --version`, which prints libc information. For the case that ldd is unavailable or broken, we'll disregard the respective error and assume glibc. We shouldn't have this whole code path fail just because the musl check fails.
