### ISSUE TITLE
Sharness failure from killing iptb nodes

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#3677]
#### Description:

https://travis-ci.org/ipfs/go-ipfs/jobs/200779018

```
expecting success: 
		iptb stop
	
ipfs kill err:  error killing daemon /Users/travis/gopath/src/github.com/ipfs/go-ipfs/test/sharness/trash directory.t0130-multinode.sh/.iptb/1: os: process already finished
not ok 27 - shut down nodes
```

**Comment by whyrusleeping** [comment]
I'm assuming this is an issue with the new makefiles, @Kubuxu take a look

**Comment by Kubuxu** [comment]
I don't think it is me. I can't see any way I could have caused it, but it is good to know.

**Comment by Kubuxu** [comment]
We should add error log read when iptb fails.

**Comment by whyrusleeping** [comment]
It looks like a daemon is dying for some reason during the iptb tests.

**Comment by Kubuxu** [comment]
I have updated IPTB in process, maybe something got broken from version to version.

**Comment by whyrusleeping** [comment]
Found the issue. iptb kill was using `wait`to wait on the daemons to be killed, but wait only works on child process. The daemons spawned by iptb are set to not be children of iptb so they can run after the `iptb start` command finishes. The wait call was erroring and we werent checking the error. I switched it to use a kill(0) loop. Will update in ipfs soon.

**Comment by Kubuxu** [comment]
Fixed.
