### ISSUE TITLE
Not clear how to fully replicate a node

### ISSUE THREAD

**Issue by mib-kd743naq** [ipfs/go-ipfs#3696]
#### Version information:
`N/A`

#### Type:
`Documentation/HOWTO Enhancement`

#### Priority:
`P4`

#### Description:
I am provisioning a new go-ipfs-based node, and would like to fully replicate pinned content from another node I control. It is not clear what is the current most efficient and error-resilient way of doing that.

In essence I am trying to figure out what is the best practice for doing the moral equivalent of `git clone`, if one has full control over both the source and destination node.

**Comment by whyrusleeping** [comment]
@mib-kd743naq Hrm... I think the most direct way would be to get a list of pins from the source node, and pin those on the new node. If you care about temporarily cached content, then you could get the output of `ipfs refs local` and fetch each of those blocks on the new node.

**Comment by whyrusleeping** [comment]
@mib-kd743naq i made this, hopefully it helps: http://ipfs.git.sexy/sketches/replicate_node.html

Any feedback and/or additional clarifications you think i should make or discuss would be great.

**Comment by Kubuxu** [comment]
`for ref in `cat all_the_refs`; ....` won't work if the list is too long

better way would be: `< all_the_refs xargs -L 1 ipfs block get > /dev/null`

**Comment by gh338** [comment]
Is there a difference between "ipfs refs local" and "ipfs pin ls --type all" ?
On my replication setup these two show very different amounts of objects.
Cheers

**Comment by Stebalien** [comment]
@gh338 please ask questions on the forums: https://discuss.ipfs.io.

**Comment by hsanjuan** [comment]
Let's move this documentation request and discussion to https://github.com/ipfs/docs/issues/442
