### ISSUE TITLE
reducing top-level mess

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#370]
the project top level looks a bit messy. potential reorg:

- [ ] blocks/
- [ ] blocks/blockservice/
- [x] blocks/blockstore/
- [ ] cmd/
- [ ] lib/commands/
- [ ] lib/util/
- [ ] lib/diagnostics/
- [ ] lib/crypto/
- [ ] core/
- [ ] core/daemon/
- [ ] core/peer/
- [ ] exchange/
- [ ] fs/fuse/
- [ ] fs/unixfs/
- [ ] fs/importer/
- [ ] merkledag/
- [ ] merkledag/path/
- [ ] merkledag/pin/
- [ ] namesys/
- [ ] net/
- [ ] routing/
- [ ] test/
- [ ] tool/config/
- [ ] tool/tour/
- [ ] tool/updates/
- [ ] tool/server/http/
- [ ] tool/daemon/

**Comment by whyrusleeping** [comment]
closing, this will be better later when we break things out into submodules
