### ISSUE TITLE
Very weird panic during linux CI run

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3710]
Scroll to the bottom of this travis CI log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/202531197/log.txt

**Comment by Kubuxu** [comment]
I've seen it once before, it seems that during exiting due to wrong CLI args some other goroutine in background tries to attach process and it panics.

**Comment by whyrusleeping** [comment]
Ah, looks like we need to move the http gateway creation stuff to start after *everything* else has begun

**Comment by whyrusleeping** [comment]
Should be as simple as moving the gateway setup stuff here https://github.com/ipfs/go-ipfs/blob/master/cmd/ipfs/daemon.go#L379 down to right before the "Daemon is ready" message. This shouldnt mess with any of the printed output AFAIK.
