### ISSUE TITLE
Empty 200 status response when using certain type of txt file

### ISSUE THREAD

**Issue by jonmyates** [ipfs/go-ipfs#3724]
#### Version information:
https://ipfs.infura.io:5001/api/v0/add

#### Description:
When trying to add a file named readme.txt with the following content:

```
FxCop Installation Instructions
1. Download the Microsoft Windows SDK for Windows 7 and .NET Framework 4 version 7.1.
2. Run %ProgramFiles%\Microsoft SDKs\Windows\v7.1\Bin\FXCop\FxCopSetup.exe to install FxCop.
```

a 200 HTTP status is returned but is empty.

http://i.imgur.com/lu5PgFB.png
http://i.imgur.com/E1BqqSe.png

**Comment by Kubuxu** [comment]
It is probably due to origin protection but I am not sure why it returns 200. Can you try the same with local node?

**Comment by jonmyates** [comment]
Sure,

Returns a 403 - Forbidden.

**Comment by Kubuxu** [comment]
So it on whoever hosts ipfs.infura.io, sorry, can't help with that.

**Comment by whyrusleeping** [comment]
cc @hermanjunge

**Comment by hermanjunge** [comment]
Thanks for the heads-on @whyrusleeping 

Hi @jonmyates 

Here is the file uploaded into INFURA. It can be seen both in INFURA, as in the IPFS gateway

https://ipfs.infura.io/ipfs/QmXmnwtefGNgeeSMMySjSrm3hTXYDtaqGszqRvii4NQeg9

https://ipfs.io/ipfs/QmXmnwtefGNgeeSMMySjSrm3hTXYDtaqGszqRvii4NQeg9

Used

```
curl -F file=@readme.txt https://ipfs.infura.io:5001/api/v0/add
{"Name":"readme.txt","Hash":"QmXmnwtefGNgeeSMMySjSrm3hTXYDtaqGszqRvii4NQeg9"}
```

*NOTE* You can tell us on any INFURA issue [here in our repo](https://github.com/infura/infura/issues)
