### ISSUE TITLE
pubsub does not always find other peers

### ISSUE THREAD

**Issue by mitar** [ipfs/go-ipfs#3745]
#### Version information:
```
go-ipfs version: 0.4.5-
Repo version: 5
System version: amd64/linux
Golang version: go1.7.4
```
```
go-ipfs version: 0.4.5-
Repo version: 5
System version: amd64/darwin
Golang version: go1.7.4
```

#### Description:

I am using pubsub feature and testing it between two nodes (one on public IP, another not, the first running Linux, the second Mac OS X) and I am noticing that not always peers discover each other and as a consequence messages do not get broadcasted. It is like each node would be on its own.

**Comment by whyrusleeping** [comment]
@mitar Could you try the `--discover` option on `ipfs pubsub sub` ?

**Comment by mitar** [comment]
I am running with that option all the time, using JS API:

```
this.ipfs.pubsub.sub(this.getTransactionsTopic(), {discover: true}, callback)
```

Is there any blacklisting/penalty or something? Because I tried to find a reproduction and was stoping and starting daemons often and subscribing and stopping subscriptions often, and more and more I was doing that, more and more peers didn't find each other?

**Comment by whyrusleeping** [comment]
@mitar hrm... theres no such penalty. 

If the nodes get connected they should start pubsubbing to eachother. The next time you see this issue, can you try verifying whether or not the nodes in question have a connection between them? (shows up in `ipfs swarm peers`)

**Comment by mitar** [comment]
I mean, I can pretty easy reproduce this. So I can check. :-)

**Comment by mitar** [comment]
Yes, there is no connection between them. They do not appear in each others' `ipfs swarm address`.

So I tested this now on two machines both on public IPs (A and B). One machine (A) has a firewall preventing inbound connections though.

So trying to call `ipfs swarm connect A` from B, it cannot connect (because of the firewall). But after I did `ipfs swarm connect B` from A, it connected and then also pubsub peers appeared.

**Comment by mitar** [comment]
If there is anything else I can do to help debug this, please tell. But it is pretty regular to me that it happens.

**Comment by whyrusleeping** [comment]
@mitar You should allow A's firewall to accept connections from ipfs

**Comment by mitar** [comment]
I thought IPFS magically get through this NATs and firewalls. :-) It works sometimes.

**Comment by mitar** [comment]
If I have 4 nodes which are not behind a firewall, and I add another node which it is to the same publication, will that one has easier time joining?

**Comment by whyrusleeping** [comment]
> I thought IPFS magically get through this NATs and firewalls

Heh, sometimes. 

> If I have 4 nodes which are not behind a firewall, and I add another node which it is to the same publication

Yes, if those nodes are not partitioned, then connecting to *any* of them will get you in the pubsub swarm

**Comment by mitar** [comment]
And they should not be partitioned because they have public IPs?

So this is the problem only because the current broadcast domain for my topic is small. When there will be more peers in it with more public IPs, it should be easier for everyone to join?

OK, then this should probably be closed because it is an edge case.

**Comment by whyrusleeping** [comment]
@mitar cool. Let me know if you have any other issues :)
