### ISSUE TITLE
Pin (add / rm) over http breaks backwards compatibility in 0.4.6

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-ipfs#3753]
#### Version information:
0.4.6

#### Description:
The json response from pin add/rm is not backwards compatible from 0.4.5 to 0.4.6
In 0.4.5 I get a response like:
{"Pins":["QmVv4Wz46JaZJeH5PMV4LGbRiiMKEmszPYY3g6fjGnVXBS"]}

and in 0.4.6 I get:
{"Pins":[{"/":"QmVv4Wz46JaZJeH5PMV4LGbRiiMKEmszPYY3g6fjGnVXBS"}]}

Which is a schema change and thus breaks our existing parser.

**Comment by lgierth** [comment]
Ugh yeah that needs to change back

**Comment by Kubuxu** [comment]
@whyrusleeping I think it is due to CID changes.

**Comment by whyrusleeping** [comment]
@Kubuxu Yeah, we just need to change the type in the pin output struct to be a string instead of a cid

**Comment by whyrusleeping** [comment]
this has been resolved
