### ISSUE TITLE
Improve fuse error reason in case of mount failure

### ISSUE THREAD

**Issue by Powersource** [ipfs/go-ipfs#3772]
#### Version information:
```
% ipfs version --all
go-ipfs version: 0.4.6-
Repo version: 5
System version: amd64/linux
Golang version: go1.8
```
```
% fusermount --version
fusermount version: 2.9.7
```
```
% uname -a
Linux pc 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux
```

#### Type:  
Bug

#### Description:
When I try to `ipfs mount` fuse complains and mounting fails.
```
% IPFS_FUSE_DEBUG=true ipfs daemon
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.1/tcp/4001
Swarm listening on /ip4/172.18.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.123/tcp/4001
Swarm listening on /ip4/89.160.37.16/tcp/14466
Swarm listening on /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
22:49:47.133 ERROR       node: error mounting: fusermount: exit status 1 mount_unix.go:97
22:49:47.133 ERROR       node: error mounting: fusermount: exit status 1 mount_unix.go:101
```
The [relevant file](https://github.com/ipfs/go-ipfs/blob/master/fuse/node/mount_unix.go#L96-L102).
```
% mkdir fs ns           
% ipfs mount -f fs -n ns
Error: fuse failed to access mountpoint fs
% ls
fs  ns
```
`sshfs` uses the same fuse version and mounting, reading and unmounting works normally there.
```
% sshfs --version
SSHFS version 2.8
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```

**Comment by whyrusleeping** [comment]
We should try and get more information out of fuse here. calling the fusermount binary is failing for some reason and we have no idea why

**Comment by Kubuxu** [comment]
Few things: do mount points exist, does your user own them?

**Comment by Powersource** [comment]
@Kubuxu 
```
% ls -l
total 8
drwxr-xr-x 2 me me 4096 Mar  9 22:49 fs
drwxr-xr-x 2 me me 4096 Mar  9 22:49 ns
% whoami
me
% ipfs mount -f fs -n ns
Error: fuse failed to access mountpoint fs
```

**Comment by Powersource** [comment]
I don't know exactly why, but suddenly it works. I tried updating and restarting my computer yesterday but that didn't help. What's likely to have made a difference is that today I updated to linux 4.10 (and restarted).

**Comment by Powersource** [comment]
Aaaaand it's broken again, amazing.

**Comment by Powersource** [comment]
Installed the latest git version and it works now. If it stays working for a few days I'll close again.

**Comment by whyrusleeping** [comment]
@Powersource Lets keep this issue open even if it keeps working for you.

The main problem i see here is that *when* it fails, we have no indication as to why. In whatever case, we need to address that

**Comment by Kubuxu** [comment]
I am very glad that the update resolved issues. It was long overdue.

**Comment by alfiedotwtf** [comment]
I'm getting the exact same error as @TroyWilson1, but only inside a Docker container. On the host, it works fine

**Comment by whyrusleeping** [comment]
@alfiedotwtf inside docker you might have to mess with some priviliges. The node will need to be started with certain flags I think

**Comment by whyrusleeping** [comment]
this might help: https://stackoverflow.com/questions/48402218/fuse-inside-docker

**Comment by gar71** [comment]
Hi.  I am having the same issue with a non descriptive ipfs mount  .   Error: exit status 1
IPFS daemon says 
15:00:24.559 ERROR       node: error mounting: exit status 1 mount_unix.go:89
15:00:24.559 ERROR       node: error mounting: exit status 1 mount_unix.go:93

I can't find any log files to help decipher this error message.  
Running on Mac OS X 10.13.6
ipfs 0.4.17
MACOSX FUSER 3.8.2

**Comment by aschmahmann** [comment]
Closing this since there's a lot of work to be done on the fuse implementation. Will be tracking in a meta issue.
