### ISSUE TITLE
ipfs daemon --init does not work

### ISSUE THREAD

**Issue by mitar** [ipfs/go-ipfs#3773]
#### Version information:

```
go-ipfs version: 0.4.6-
Repo version: 5
System version: amd64/linux
Golang version: go1.8
```

#### Description:

I am passing `--init`, but it does not do what is saying it will do, which is, initialize the repo:

```
$ export IPFS_PATH=/ipfs
$ /usr/local/bin/ipfs daemon --init
Initializing daemon...
Error: no IPFS repo found in /ipfs.
please run: 'ipfs init'
```

**Comment by whyrusleeping** [comment]
@mitar Thats odd... it works for me.
I was going to ask if it could be a permissions issue, but that prints out permission denied for me.

Does the /ifps folder contain anything?

**Comment by mitar** [comment]
It does not. You can do full reproduction using a Docker image:

```
$ docker run -d --name test-sgx tozd/sgx
$ docker exec -t -i test-sgx bash
$ wget -O - https://dist.ipfs.io/go-ipfs/v0.4.6/go-ipfs_v0.4.6_linux-amd64.tar.gz | tar zx --strip=1 -C /usr/local/bin go-ipfs/ipfs
$ mkdir /ipfs
$ export IPFS_PATH=/ipfs
$ ipfs daemon --init
Initializing daemon...
Error: no IPFS repo found in /ipfs.
please run: 'ipfs init'
```

**Comment by whyrusleeping** [comment]
@mitar ah, ipfs init assumes that the directory youre giving it does not already exist.

**Comment by mitar** [comment]
Oh, but for `ipfs init` there is no such assumption. It just checks that the directory is empty. So [this works](https://github.com/luckychain/lucky/blob/master/etc/service/ipfs/run):

```
mkdir -p /ipfs
export IPFS_PATH=/ipfs
ipfs init --empty-repo || true
ipfs daemon --migrate --enable-gc --enable-pubsub-experiment
```

But this does not:

```
mkdir -p /ipfs
export IPFS_PATH=/ipfs
ipfs daemon --init --migrate --enable-gc --enable-pubsub-experiment
```

It is not really possible inside Docker for a directory to not exist, because in practice I am mounting external volume to `/ipfs`. So it exists because Docker puts a volume there.

BTW, having `--init-empty` would be great for `daemon`.

**Comment by whyrusleeping** [comment]
Ah interesting. Thats a weird discrepancy. Lets make sure the `--init` flag on the daemon has the same exact behaviour as `ipfs init`

**Comment by kevina** [comment]
I will look into this today.

**Comment by kevina** [comment]
#3805 should fix it.
