### ISSUE TITLE
bug: cannot run ipfs daemon on Windows 10 Linux subsystem

### ISSUE THREAD

**Issue by gediminaspetrikas** [ipfs/go-ipfs#3779]
#### Version information:
```
go-ipfs version: 0.4.6-
Repo version: 5
System version: amd64/linux
Golang version: go1.8
```

#### Type:
Cannot run `ipfs daemon` on Windows 10 Linux subsystem.
Works as expected in Windows 10.

#### Priority:
P3
#### Description:
Cannot run `ipfs daemon` on Windows 10 Linux subsystem.
To reproduce:

- `ipfs init`
- `ipfs daemon`
```
Initializing daemon...
16:30:55.710 ERROR   cmd/ipfs: error from node construction: route ip+net: netlinkrib: invalid argument daemon.go:344
Error: route ip+net: netlinkrib: invalid argument
```

Works as expected with plain Windows 10.
```
go-ipfs version: 0.4.6-
Repo version: 5
System version: amd64/windows
Golang version: go1.8
```

Area: "daemon + init"

**Comment by Kubuxu** [comment]
It is bug in Window's Linux subsystem implementation not sure if we can help with anything here.

**Comment by gediminaspetrikas** [comment]
Well, that is sad to hear. @Kubuxu, can this bug prevent me from using JS implementation of IPFS as well on the Linux subsystem?

**Comment by Kubuxu** [comment]
Not sure, it is completely separate, so this exact bug shouldn't.

**Comment by gediminaspetrikas** [comment]
Alright, thanks!

**Comment by whyrusleeping** [comment]
@gediminaspetrikas Could you try using the linux binary in the windows subsystem?

**Comment by whyrusleeping** [comment]
And if you are already running the linux bin, could you try out setting `IPFS_REUSEPORT` to false and running the daemon?

**Comment by gediminaspetrikas** [comment]
@whyrusleeping 
```
GED » IPFS_REUSEPORT=false ipfs daemon
Initializing daemon...
18:35:18.751 ERROR   cmd/ipfs: error from node construction: route ip+net: netlinkrib: invalid argument daemon.go:344
Error: route ip+net: netlinkrib: invalid argument
```
didn't help unfortunately. Ran in linux subsystem

**Comment by Kubuxu** [comment]
I think it is code discovering interfaces. You might get somewhere by hanging the `0.0.0.0` and `::` swarm addresses in config to your interface addresses.

**Comment by Kubuxu** [comment]
@gediminaspetrikas have you tried doing above  ^^

**Comment by djdv** [comment]
This appears to have been resolved.
![Untitled](https://user-images.githubusercontent.com/13862850/57713864-4db26700-7641-11e9-9734-f26fb38b961d.png)
