### ISSUE TITLE
FreeBSD: Specify that "make install" will not work in the text of README - must use "gmake install"

### ISSUE THREAD

**Issue by janicez** [ipfs/go-ipfs#3781]
#### Version information:
None  
System: FreeBSD 11-Stable  

#### Type:
Build system bug

#### Priority:
P2 - slows down FreeBSDers

#### Description:
Simple text fix, which is why I have set this at a fairly high priority - because it can be done so easily (just add two lines after the "make install" stuff explaining that on non-GNU/Linux systems, you need to use "gmake" rather than "make")

**Comment by djdv** [comment]
I don't have the time now to experiment with it but I was curious if it was worth using the `GNUmakefile` name if it relies on GNU make, gmake and bmake should recognize these and act appropriately. Maybe eventually create a separate `BSDmakefile` that is bmake/pmake compliant.

https://wiki.freebsd.org/build  (section 1.2 subsection 7)
https://www.gnu.org/software/make/manual/make.html#Makefile-Names

**Comment by zramsay** [comment]
closed in #3959
