### ISSUE TITLE
panic, build system: ERROR: install-path hook failed: exit status 1 

### ISSUE THREAD

**Issue by janicez** [ipfs/go-ipfs#3784]
#### Version information:
None  
FreeBSD 11-Stable

#### Type:
Build system panic in gx install --global

#### Priority:
P0 on freebsd, P5 on unaffected platforms

#### Description:
```
hadron@schoenefeld:~/go/src/github.com/ipfs/go-ipfs$ gmake install
bin/check_go_version 1.7
gx install --global
ERROR: install-path hook failed: exit status 1 
gmake: *** [mk/gx.mk:4: gx-deps] Error 1
```

**Comment by Kubuxu** [comment]
It looks like gx-go isn't installed, IDK why this would happen.

`gmake install_unsupported` should still work.

**Comment by whyrusleeping** [comment]
Could be that GOPATH isnt set

**Comment by Kubuxu** [comment]
Ghhr, looks like I have missed it when I've done the refactor. I must have lost it in my initial feature list as latter I was comparing everything with it.

I will fix it tomorrow.

**Comment by janicez** [comment]
Guys, it's gotten even worse

```
ERROR: strconv.ParseInt: parsing "t": invalid syntax 
```

**Comment by whyrusleeping** [comment]
@janicez what is the output of `./bin/gx-go hook install-path` ?

**Comment by janicez** [comment]
Never mind. I got it installed.

**Comment by callumgare** [comment]
https://xkcd.com/979/ Sigh...

**Comment by whyrusleeping** [comment]
@callumgare having the same problem? if so, what errors are you getting?
