### ISSUE TITLE
Fix ugly output when killing a command

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3785]
Killing an ipfs command with ctrl+c prints this ugly error message:
```
00:01:48.015 ERROR commands/h: net/http: request canceled client.go:247
Error: net/http: request canceled
```

I know that the request was canceled. I canceled it..

**Comment by Stebalien** [comment]
This is now *slightly* better. The client just prints out `Error: context canceled` (no line numbers, etc.).
