### ISSUE TITLE
Is there something like a keychain?

### ISSUE THREAD

**Issue by nezzard** [ipfs/go-ipfs#3793]
Hi, i have 2 questions, i want to implement something like a comment system for users outside ipfs network
1. How i can give access for users, to add data? 
2. Can i generate for them repo?

I looking for a something like a ZeroID in a zeronet

**Comment by wigy-opensource-developer** [comment]
If each user runs its own node, there is no need to authenticate/authorize them. You only need those concepts if your users cannot run their own nodes and they need a "proxy". Some pieces are missing from IPFS to implement that set of features I have dubbed "[light client](https://github.com/Fermat-ORG/iop-content-address-network/issues/1)".

Do you have something like those in mind? If yes, feel free to [follow the progress](https://github.com/orgs/DeCentral-Budapest/projects/1) or give further input here!

**Comment by nezzard** [comment]
No, user have not node, they are just visitors wich dont know about ipfs.
I need something like login system. user create account with login and password, and than i need to give access for users.
Like in zeronet, when you register, they generated for me bitcoin adress, with a piblic and privete keys wich i thnk store in network ( but i cant understand how it's work)
So i need to make something like zeroID, but have no idea how

**Comment by whyrusleeping** [comment]
@nezzard you can generate an arbitrary number of keys through the `ipfs key` subcommand. Though I'm not sure exactly what youre trying to accomplish here.

When you 'register' with zeronet, who are you registering with?

**Comment by wigy-opensource-developer** [comment]
@nezzard In ZeroNet the default is also to run your own node on your own desktop/laptop. ZeroNet also supports "proxies" where any user can create a new identity with their browsers. In that case the proxy generates the private key for you and asks you to save it somewhere if you want to get back to the same identity (see it in action: https://bit.surf:43110/zeroproxies.bit )

In IPFS there is also a way to create lots of identites with `ipfs key gen` as Jeromy mentioned. It is not possible to do so from the browser, like it is not possible to upload anything. That costs bandwidth and storage space for the node maintainer, so it needs a incentive model that is not yet here.

ZeroNet proxies will not survive long-term either without any financial incentives. They are just good for showing what content can be reached on ZeroNet. Privacy-aware end-users will just install their own ZeroNet node.

The "light client" proposal tries to add a feature similar to ZeroNet proxy to IPFS, but tries to leave the incentive system open to the node operator.

**Comment by nezzard** [comment]
@wigy-opensource-developer 
So as i see i have only two ways?
1. Make some registration without gen a new key, and store data to json or db like a orbit db
2. Gen key with node js or something else, and do some stuff like in a first question

Which way is more correctly?

I planing ipfs base site, but without nodes to other visitors, just like usual site wordpress or other cms

**Comment by Kubuxu** [comment]
Closing as non-actionable regarding go-ipfs. Please move the discussion to discuss.ipfs.io.
