### ISSUE TITLE
CORS headers not sent

### ISSUE THREAD

**Issue by substack** [ipfs/go-ipfs#3797]
#### Version information:

```
 $ ipfs version --all
go-ipfs version: 0.4.5-dev-
Repo version: 4
System version: amd64/linux
Golang version: go1.7
```

#### Description:

I set the http configuration for CORS as the help page for `ipfs daemon` recommends:

```
$ ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin
[
  "localhost:9966"
]
```

but after restarting the daemon the headers aren't present:

```
curl -I 'http://localhost:5001/api/v0/ls?arg=QmS3snR6YuGSk48U8JRBmqSVRsiFihRsFBfZtq7Rr9SbW2'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
Content-Type: application/json
Server: go-ipfs/0.4.5-dev
Trailer: X-Stream-Error
Vary: Origin
Date: Sat, 18 Mar 2017 09:45:38 GMT

```

**Comment by whyrusleeping** [comment]
Hrm... thats pretty annoying. Let me look into this.

**Comment by whyrusleeping** [comment]
odd that the `Vary: Origin` header is there...

**Comment by whyrusleeping** [comment]
For some unknown reason we skip adding these headers here: https://github.com/ipfs/go-ipfs/blob/master/commands/http/handler.go#L85

My understanding of http security semantics isnt where it should be. I'll need to figure out why we do this...

**Comment by substack** [comment]
I get the same headers set on 0.4.7:

```
$ ipfs --version
ipfs version 0.4.7
```

```
$ curl -I 'http://localhost:5001/api/v0/ls?arg=QmS3snR6YuGSk48U8JRBmqSVRsiFihRsFBfZtq7Rr9SbW2'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
Content-Type: application/json
Server: go-ipfs/0.4.7
Trailer: X-Stream-Error
Vary: Origin
Date: Sat, 18 Mar 2017 22:07:59 GMT

```

**Comment by whyrusleeping** [comment]
To get the header to be returned, i also had to set the allowed methods:
```
whyrusleeping@rumil ~/g/s/g/i/go-ipfs> ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["HEAD","GET"]'
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["http://localhost:9966"]'
whyrusleeping@rumil ~/g/s/g/i/go-ipfs> ipfs daemon
Initializing daemon...
Swarm not listening, running in offline mode.
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
```
whyrusleeping@rumil ~/g/s/g/i/go-ipfs> curl -I -H "Origin: http://localhost:9966" http://localhost:5001/api/v0/id
HTTP/1.1 200 OK
Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
Access-Control-Allow-Origin: http://localhost:9966
Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
Content-Type: application/json
Server: go-ipfs/0.4.8-dev
Trailer: X-Stream-Error
Vary: Origin
Date: Sat, 18 Mar 2017 22:33:01 GMT
```

**Comment by Kubuxu** [comment]
If you compare it with gateway the `Access-Control-Allow-Methods: GET` header is missing.

**Comment by Kubuxu** [comment]
If you compare it with gateway the `Access-Control-Allow-Methods: GET` header is missing.

**Comment by substack** [comment]
Everything is working for me now. I think the 0.4.7 upgrade fixed the issue in the browser and the issue with curl was related to other configuration settings. Thanks.
