### ISSUE TITLE
ERROR    bitswap: Error writing block to datastore: sync /ipfs/blocks: invalid argument bitswap.go:303

### ISSUE THREAD

**Issue by starrychloe** [ipfs/go-ipfs#3799]
```
20:35:43.128 ERROR    bitswap: Error writing block to datastore: sync /ipfs/blocks: invalid argument bitswap.go:303
20:35:43.922 ERROR  providers: error adding new providers: sync /ipfs/datastore: invalid argument providers.go:258
20:35:45.664 ERROR  providers: error adding new providers: sync /ipfs/datastore: invalid argument providers.go:258
```
and it just repeats...

#### Version information:
```
[vagrant@localhost go-ipfs]$ ./ipfs version --all
go-ipfs version: 0.4.6-
Repo version: 5
System version: amd64/linux
Golang version: go1.8
```

#### Type:
Error during running. Must be a bug somewhere.

#### Priority:
P4

#### Description:
IPFS daemon leaves errors in the console as it runs. I don't know what causes it, but clicking on big, old IPFS links seems to cause it. I can view `/ipfs/datastore/` and `/ipfs/blocks` fine. I can access the cat pic http://127.0.0.1:8080/ipfs/QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ/cat.jpg fine. These links seem to cause the error to print:
http://127.0.0.1:8080/ipfs/QmcYKHpcBJNL9uaxxTZJGuk9QYBfS3cDuYKoELPhfdmRqn
http://127.0.0.1:8080/ipfs/QmbzpQmRULESivRvpP9SZL2vsu1dGkmczwVKCWzD2oXdMP
http://127.0.0.1:8080/ipfs/QmRcsML93Bwi8V9DiGhX4Zs9ypDgHSCWCpAMxd7cpHcS1f

**Comment by whyrusleeping** [comment]
Invalid argument is a new one. 

After a small amount of research i see that some filesystems (particularly on virtualbox for some reason?) do not support calling fsync on directories. This *might* be a lead here.

What filesystem are you using?

**Comment by starrychloe** [comment]
I'm using vboxsf. 

```
[vagrant@localhost ~]$ mount | grep ipfs
ipfs on /media/sf_ipfs type vboxsf (rw,nodev,relatime)
ipfs on /ipfs type vboxsf (rw,nodev,relatime)
```
The host (Windows 8.1) is using NTFS.

**Comment by Kubuxu** [comment]
You should be able to work it around by switching `NoSync` in config to `true`.

**Comment by whyrusleeping** [comment]
@Kubuxu `NoSync` still does a minimal amount of sync calls IIRC. Maybe youre right though?

**Comment by Kubuxu** [comment]
not sure, but it might help

**Comment by whyrusleeping** [comment]
@starrychloe any update here? does this still happen?

**Comment by starrychloe** [comment]
Yes, it seems to help. No invalid argument errors in the console.

```
[vagrant@localhost go-ipfs]$ grep NoSync /ipfs/config
    "NoSync": true,
```

**Comment by whyrusleeping** [comment]
@eginez Does the issue persist if you init with `ipfs init --profile=badgerds` ?

**Comment by eginez** [comment]
Alright I think I got to the bottom of it. I think there is a bug while parsing the config file around these lines: https://github.com/ipfs/go-ipfs/blob/master/repo/fsrepo/fsrepo.go#L398.

The `NoSync` config is being ignored. Presumably in favor of `sync`  inside the `Spec` map. Setting `sync` to `false` fixes the fs syncing issues and the pi seems to be happy.

We should either warn/fail on the presence of `NoSync` and let the user know the setting has move or override `sync` with `NoSync` preserve backwards compat.
