### ISSUE TITLE
identical content, different hash

### ISSUE THREAD

**Issue by udatny** [ipfs/go-ipfs#3800]
#### Version information:
go-ipfs_v0.4.6_windows-amd64 prepackaged

#### Type:
Bug

#### Priority: 
P2

#### Description:
I am working on an offline hashing solution for ipfs in java. for beeing able to do so i took the protobuffer definitions from the repo.

https://github.com/ipfs/go-ipfs/blob/master/merkledag/pb/merkledag.proto

from this file i generate the protocol definitions. 

when i am serializing a PBNode in this way, the resulting hash differs from the one generated by the go ipfs implementation (using ipfs add). 
the difference is, that the java / google generated protobuffer builder sticks to the order defined in the .proto file (the numbers behind the fields). 

```
// An IPFS MerkleDAG Node
message PBNode {

  // refs to other objects
  repeated PBLink Links = 2;

  // opaque user data
  optional bytes Data = 1;
}

```
Here it gets a bit confusing. there is a field sequence in the sense of a series of fields in the definition, and there is an order defined by the sequence numbers behind the fields. 

in my understanding, the .proto definition says, that the order is Data, followed by Links. 

see the Go hint about the trailing numbers here: https://developers.google.com/protocol-buffers/docs/javatutorial#defining-your-protocol-format

That is what is also reflected in the generated java code: it serializes the protobuffer according to the numbers and not the field definition sequence order. 

so i get a PBNode serializing as [Data,Links] instead of [Links,Data] and i can fix this by manually reassembling the resulting ByteString - which leads to the corresponding hash as when i add it by ipfs. 

so now my issue: in my opinion, the .proto definition is wrong. The java world may suffer from this issue. It took me some deeper analysis to figure my issue. 

nevertheless the issue lead me also to the point where i found out that a content may live under two different hashes. see yourself: 

identical content, different hash. the difference here is the underlaying protobuffer structure, not visible in the output. 

```
$ ./ipfs.exe object get QmbKmWzcgv8pLgqc4o8X97qk2mUiHYJn1LW4T7YiYNfDpJ
{"Links":[{"Name":"some Link Name","Hash":"QmT78zSuBmuS4z925WZfrqQ1qHaJ56DQaTfyMUF7F8ff5o","Size":20}],"Data":"\u0008\u0001"}
```

```
$ ./ipfs.exe object get QmZEc66sE3yLLXWQUG8SWSZbePP4Kk8DoXiFLqWqcm1k1j
{"Links":[{"Name":"some Link Name","Hash":"QmT78zSuBmuS4z925WZfrqQ1qHaJ56DQaTfyMUF7F8ff5o","Size":20}],"Data":"\u0008\u0001"}
```

**Comment by udatny** [comment]
i checked the reading aspect. the binary representation in ipfs is different - and therefore the different hash, but i can read it back in any order with protobuffers. so no issues with reading.

**Comment by Kubuxu** [comment]
Yeah, there shouldn't be any problems with reading. Just the output format will be different.

**Comment by whyrusleeping** [comment]
This problem feels like our version of ethereums sha3 choice...

**Comment by whyrusleeping** [comment]
"Cant change it now, everything would break"

**Comment by lgierth** [comment]
We can "change" it with unixfs v2 based on IPLD instead of merkledag/protobuf.

**Comment by whyrusleeping** [comment]
@lgierth yeah, I think thats the best plan moving forward we have here

**Comment by Stebalien** [comment]
Closing as "won't fix". We're hoping to ship UnixFSv2 soon so this should become a thing of the past.
