### ISSUE TITLE
Odd bitswap test failure in travis CI

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3814]
```
--- FAIL: TestLargeFile (3.80s)
	bitswap_test.go:166: Give the blocks to the first instance
	bitswap_test.go:177: not enough peers connected to instance
20:26:30.330 ERROR    bitswap: nil cid in GetBlock bitswap.go:178
FAIL
FAIL	github.com/ipfs/go-ipfs/exchange/bitswap	81.701s
```

Really not sure where this could come from. Needs investigating. 

Was on tests for commit 0325888

**Comment by whyrusleeping** [comment]
Got this again on a different PR:
```
02:21:24.976 ERROR    bitswap: nil cid in GetBlock bitswap.go:178
--- FAIL: TestWantlistCleanup (0.45s)
	bitswap_test.go:489: should only have keys[0] in wantlist
FAIL
FAIL	github.com/ipfs/go-ipfs/exchange/bitswap	172.694s
```

This time on bc4d951

**Comment by whyrusleeping** [comment]
I think the error message saying `nil cid` is just TestEmptyKey.

There appear to be two separate test failures here. (both on travis CI)

I'll set up a script to run these with the race detector on for a while

**Comment by whyrusleeping** [comment]
@Kubuxu the first one seems like it could be related to the iptb issues we're seeing

**Comment by whyrusleeping** [comment]
Though it is also timing related and could have just been that the machine was so overloaded that it took over 500ms to form the right connections

**Comment by Stebalien** [comment]
Related to #4108?

**Comment by Stebalien** [comment]
I think this is just a timing issue (same as #4108). As that's fixed, I'll close this for now.
