### ISSUE TITLE
Weird `make install` failure on travis CI

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3817]
travis CI is the gift that keeps on giving. 

https://ipfs.io/ipfs/QmWz5BzBf2oJ7XXk5YeQQLoh5MYz6QDmH3n8KfWezMFdeM

This one looks a bit weird. It seems like the download tool fails to fetch things for some reason (thoughts @lgierth ?) And then the makefile continues trying to install things afterwards (@Kubuxu from the recent makefile refactor?)

I would normally chock this one up to travis being weird. But our scripts should try and fail a little more gracefully than this

**Comment by Kubuxu** [comment]
I have fixed `dist_get` failing without failing with https://github.com/ipfs/go-ipfs/pull/3818. No idea why the un-tag.gz failed.

**Comment by Kubuxu** [comment]
It might have been gateway or connection problem. Closing.
