### ISSUE TITLE
network transfer between two nodes very slow

### ISSUE THREAD

**Issue by satra** [ipfs/go-ipfs#3825]
#### Version information:
server: 
go-ipfs version: 0.4.6-
Repo version: 5
System version: amd64/linux
Golang version: go1.8

client:
go-ipfs version: 0.4.6-
Repo version: 5
System version: amd64/darwin
Golang version: go1.8

#### Description:

on the client:
```
ipfs bootstrap rm --all
ipfs bootstrap add /ip4/18.13.53.53/tcp/4001/ipfs/QmSgC4gsjk3hd49Yosov2CadExkRts9dAdoEEyG2TN3jHu
ipfs ping QmSgC4gsjk3hd49Yosov2CadExkRts9dAdoEEyG2TN3jHu
ipfs get -o ants /ipfs/QmNng3MdmWZCxkBbwrxbDEoXXQ5gqvcCSuPisdAxvcRCh2
```
and this transfer is very slow. 

the server sits on a large bandwidth connection and if i simply use rsync to download the ipfs directory it's much much faster.

is there a way to determine what the client and the server are spending their time on?

@whyrusleeping - it almost seems like the `ls` issue we were seeing. that it won't start retrieving anything till it does an `ls` and then takes forever to download the 1.5G of data.

**Comment by whyrusleeping** [comment]
@satra Hrm... This is a bit of a known problem. The dht overhead here is pretty annoying (something i'm planning on improving with: https://github.com/ipfs/go-ipfs/issues/3786).

What is the normal transfer speed between the two machines in question?

What is the latency between the two machines?

What is the actual bandwidth utilization of each machine vs how fast the transfer appears to be going?

**Comment by satra** [comment]
@whyrusleeping - sorry about the delay. had a chance to upgrade to 0.4.9 and test out latencies and bandwidth.

ping latency: 

```
64 bytes from 18.13.53.53: icmp_seq=0 ttl=55 time=6.908 ms
64 bytes from 18.13.53.53: icmp_seq=1 ttl=55 time=7.288 ms
64 bytes from 18.13.53.53: icmp_seq=2 ttl=55 time=7.355 ms
64 bytes from 18.13.53.53: icmp_seq=3 ttl=55 time=7.412 ms
```

an scp command:

```
$ scp satra@oms.mit.edu:/path/to/file .
sub-BANDA001_task-rest_run-01_bold.nii.gz                 12%   60MB   3.7MB/s   01:57 ETA
```

ipfs command translates to about 20MB/minute 

```
ipfs get -o testfs /ipfs/QmWvQ8fz9XMJoxQHV5BHKmVqYoVNWkckUxQ8LNSgEkdBgD/bin
Saving file(s) to testfs
 41.97 MB / 2.47 GB [>----------------------------------------------------]   1.66% 1h57m3s
```

**Comment by satra** [comment]
@whyrusleeping and @Kubuxu - any ideas on how to improve throughput?

**Comment by satra** [comment]
@magik6k - will check it out and report back the numbers.

**Comment by Kubuxu** [comment]
You may also want to start the daemon with `ipfs daemon --routing=none` for receiving the files. We are thinking of better providing strategies so they don't reduce speed of the download but this might be workaround for now.

**Comment by satra** [comment]
@Kubuxu - ok this is much faster. i'll keep playing with and see if things are better.

**Comment by Kamelia2000** [comment]
Hello Do you think  IPIPFS is  good to make a chat soluton like IM messenger like Telegram and very much fast ?

**Comment by Stebalien** [comment]
@Kamelia2000 please ask support questions on https://discuss.ipfs.io

(also, in general, please keep issue comments on-topic)
