### ISSUE TITLE
Let "ipfs repo stat" include StorageMax as set in the configuration (in bytes)

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipfs#3836]
#### Description:

I'm not sure this is a good idea but maybe I'm wrong or there's a better approach.

The underlying problem is to know how many more bytes an ipfs node can store.

`ipfs repo stat` provides RepoSize and `ipfs config show` provides `StorageMax`, so it's just matter of doing the math.If StorageMax came included in `repo stat`, then it would:

  * Save 1 api call
  * Save parsing of the configuration
  * Save converting human-readable configuration values to bytes (extra dependency)

But as I say, I'm not sure the `repo stat` information is the place for a GC-related configuration option.

**Comment by kevina** [comment]
@hsanjuan any progress on this?

**Comment by hsanjuan** [comment]
@kevina I'm not working on this. I was waiting to hear if this sounded reasonable?

**Comment by kevina** [comment]
@whyrusleeping thought it was reasonable when we talked.  I am going to try and implement something this week.

**Comment by kevina** [comment]
@whyrusleeping I think the best way to handle this is just add a `StorageMax` field to the `Stat` field in `core/corerepo/stat.go` and have RepoStat populate the field.  This will be useful, but @hsanjuan is right in that this is a property of the configuration and not strictly the repo though.

Should we also calculate the free space?  If so should that also go in the Stat field of have that be done in the marshaler?

**Comment by whyrusleeping** [comment]
@kevina first bit SGTM

RE free space: You mean total free space on the disk?  Or free space below the 'storage max' ?

**Comment by kevina** [comment]
@whyrusleeping I mean StorageMax-RepoSize which is theoretically the amount of space left even though right now I believe on the GC uses  StorageMax and there wouldn't not be an error until free space on the disk.

**Comment by kevina** [comment]
See #3915.  I _just_ added the StorageMax field for now.
