### ISSUE TITLE
Let 'ipfs dht findprovs' return more than 20 peers

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/go-ipfs#3839]
#### Version information:
```
go-ipfs version: 0.4.8-rc1-
Repo version: 5
System version: amd64/darwin
Golang version: go1.8
```

#### Type:
Enhancement

#### Priority:
P5

#### Description:
Currently when running `ipfs dht findprovs` it'll continue until a timeout or finding 20 peers. It would be helpful if we could configure the command not return just because it found 20 peers. In addition, would be helpful to be able to configure the amount of time it'll search as well.

Relevant line: https://github.com/ipfs/go-ipfs/blob/cbf8a0cdb4af60c5106fc41d03902272ac72be6e/core/commands/dht.go#L162

**Comment by Kubuxu** [comment]
There is global ipfs option, `timeout` that causes the command to timeout after some time.

Example: `ipfs --timeout=1s dht findprovs /ipfs/QmVZxZgdnZ8h2L7V5bhLsE4CvAmAaGyLjBhFJHYigPE9X1`

**Comment by lgierth** [comment]
Needs to be documented -- it's not in `ipfs --help`

**Comment by faddat** [comment]
is this what one would use to identify the peers serving a given file?

**Comment by Kubuxu** [comment]
Yes `findprovs` can be used for that.

**Comment by Kubuxu** [comment]
It should be very easy to do, just making https://github.com/ipfs/go-ipfs/blob/master/core/commands/dht.go#L162 a CLI parameter and adding some tests for it.
