### ISSUE TITLE
/api/v0/add fails to report created objects for added files

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipfs#3842]
#### Version information:  

go-ipfs version: 0.4.8-rc1-
Repo version: 5
System version: amd64/linux
Golang version: go1.8

#### Description:

```sh
$ mkdir afolder
$ cd afolder
$ echo "wahaha1" > myfile1
$ echo "wahaha2" > myfile2
$ curl -X POST -F "file=@myfile1;filename=a/d/e/myfile" -F "file=@myfile2;filename=myfile2" "http://localhost:5001/api/v0/add"
{"Name":"a/d/e/myfile","Hash":"QmPhQt36SfHfW6m5Cd1hECKppPehL5fhgEv9jmkr94kPZe"}
{"Name":"myfile2","Hash":"QmeWD26mRZZnJNCtzkkvpXt1s3JLYYXjzWZYCiZj98wmsj"}
{"Name":"a/d/e","Hash":"QmaA2J8jUY6ij5jiGwC3sgbnRhTDkD2iJXe55okvKjssRD"}
{"Name":"a/d","Hash":"QmTAEd6aAPiHdXfyqUW7kQ8HTTNmW5JXdXgnLBqAdupmDd"}
{"Name":"a","Hash":"QmSRLFiVsttMHwTyPRMXyTFmht6xSZJ6BT9KdBdcEp9TwQ"}
$ ipfs pin ls QmeWD26mRZZnJNCtzkkvpXt1s3JLYYXjzWZYCiZj98wmsj
QmeWD26mRZZnJNCtzkkvpXt1s3JLYYXjzWZYCiZj98wmsj indirect through QmfNiRzgSER1p6aFPCocuUNhfxsnVS2siUeQxmnqrQsFM6
$ # WAT? WHO IS QmfNiRzgSER1p6aFPCocuUNhfxsnVS2siUeQxmnqrQsFM6?
$ ipfs pin ls QmfNiRzgSER1p6aFPCocuUNhfxsnVS2siUeQxmnqrQsFM6
QmfNiRzgSER1p6aFPCocuUNhfxsnVS2siUeQxmnqrQsFM6 recursive
$ ipfs ls QmfNiRzgSER1p6aFPCocuUNhfxsnVS2siUeQxmnqrQsFM6
QmSRLFiVsttMHwTyPRMXyTFmht6xSZJ6BT9KdBdcEp9TwQ 162 a/
QmeWD26mRZZnJNCtzkkvpXt1s3JLYYXjzWZYCiZj98wmsj 16  myfile2
```

So QmfNiRzgSER1p6aFPCocuUNhfxsnVS2siUeQxmnqrQsFM6 is created, and pinned recursively but the user is not informed and it is somehow unexpected because why does it wrap "a/" and "myfile2"?. Also, QmeWD26mRZZnJNCtzkkvpXt1s3JLYYXjzWZYCiZj98wmsj is not recursively pinned, which is probably what the user wanted when adding.

Yes, I'm testing the http api in exotic ways :)

**Comment by hsanjuan** [comment]
This is reproducable with the cli, doing `ipfs add -r folder1 folder2` is very confusing

**Comment by Kubuxu** [comment]
Connected with: https://github.com/ipfs/go-ipfs/issues/2811

**Comment by hsanjuan** [comment]
hmm maybe close this @Kubuxu . I should have searched for dups before.

**Comment by Kubuxu** [comment]
I will close this, but if you could try to improve the title of #2811 .

**Comment by hsanjuan** [comment]
@Kubuxu I don't dare because @kevina is describing the same problem from a different perspective (i think)

@kevina mind improving that title for us?
