### ISSUE TITLE
Can I manually add address?

### ISSUE THREAD

**Issue by baimurzin** [ipfs/go-ipfs#3844]
Is it possible to add manually peers before starting **ipfs daemon**
And how I can get value from second machine to add it on first machine?

And for example I have run a daemon in local network on several devices, and then I give access to global network would files accessible to others people. If yes, how can I prevent it?

**Comment by hsanjuan** [comment]
> Is it possible to add manually peers before starting ipfs daemon

Use the `Bootstrap` list to add peers before starting in the configuration.

> And how I can get value from second machine to add it on first machine?

Use `ipfs id` to find the second machine's peer addresses.

> And for example I have run a daemon in local network on several devices, and then I give access to global 
network would files accessible to others people. If yes, how can I prevent it?

Files are accessible to other people as soon as a node bootstrap to one of the default nodes or finds a node which is connected to the outside.

>  If yes, how can I prevent it?

Enable private networks. See https://github.com/ipfs/go-ipfs/issues/3397#issuecomment-284341649

**Comment by baimurzin** [comment]
@hsanjuan Thanks, it useful enough!
