### ISSUE TITLE
Possibility to restrict file access for users in network

### ISSUE THREAD

**Issue by baimurzin** [ipfs/go-ipfs#3849]
Now is it possible to set permission on any file for some users in network?
For example, I have a file with secret information and want to share it with some users. Is it possible to restrict from others and share somewhen you want.
May there is such opportunity using blockchain/ethereum?

**Comment by whyrusleeping** [comment]
@baimurzin Could you ask this question on our discourse forum? http://ipfs.trydiscourse.com/

We're trying to keep issues on this repo as actionable issues on the go-ipfs implementation
