### ISSUE TITLE
Hardcoded /home/whyrusleeping path on crash.

### ISSUE THREAD

**Issue by nannal** [ipfs/go-ipfs#3852]
#### Version information:
go-ipfs version: 0.4.8-
Repo version: 5
System version: amd64/darwin
Golang version: go1.8

#### Description:

Tor wasn't running & I tried to torify IPFS (due to ISP issues with DHT) saw some interesting output with hardcoded /home/whyrusleeping/ (why rus lee ping?) paths

torify ipfs daemon &
[1] 80545
Mac:IIS dabbott$ which: no getcap in (/Users/dabbott/.rvm/gems/ruby-2.4.0/bin:/Users/dabbott/.rvm/gems/ruby-2.4.0@global/bin:/Users/dabbott/.rvm/rubies/ruby-2.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/dabbott/.rvm/bin:/Users/dabbott/.rvm/bin:/usr/sbin:/sbin)
fatal error: runtime: bsdthread_register error (unset DYLD_INSERT_LIBRARIES)

runtime stack:
runtime.throw(0x19d450f, 0x3f)
	/home/**whyrusleeping**/go/src/runtime/panic.go:596 +0x95 fp=0x7fff5fbff770 sp=0x7fff5fbff750
runtime.goenvs()
	/home/**whyrusleeping**/go/src/runtime/os_darwin.go:106 +0x85 fp=0x7fff5fbff7a0 sp=0x7fff5fbff770
runtime.schedinit()
	/home/**whyrusleeping**/go/src/runtime/proc.go:486 +0xa1 fp=0x7fff5fbff7e0 sp=0x7fff5fbff7a0
runtime.rt0_go(0x7fff5fbff818, 0x2, 0x7fff5fbff818, 0x0, 0x0, 0x2, 0x7fff5fbff9b8, 0x7fff5fbff9bd, 0x0, 0x7fff5fbff9c4, ...)
	/home/**whyrusleeping**/go/src/runtime/asm_amd64.s:158 +0x183 fp=0x7fff5fbff7e8 sp=0x7fff5fbff7e0

[1]+  Exit 2                  torify ipfs daemon

**Comment by nannal** [comment]
Actually torify ipfs daemon doesn't seem to work on osx but does appear to work fine on linux 

 "which: no getcap in (/Users/dabbott/.rvm/gems..." is a torify related error.

**Comment by whyrusleeping** [comment]
Huh, interesting. I should change the build box's go installation to use something in /usr/bin.

**Comment by Kubuxu** [comment]
This is only a build path so it doesn't make much difference. We should just build as `ipfs` user or something.

**Comment by whyrusleeping** [comment]
Yeah, building as my user is sloppy. Will fix next time

**Comment by Kubuxu** [comment]
Closing it as non-actionable right now, it also isn't much of an issues. It is just where the daemon was built. It is up to one building it to keep it out of there.
