### ISSUE TITLE
Add ability to add new functionality via plugins

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3853]
With go1.8 we can now load plugins at runtime: https://golang.org/pkg/plugin/

I think we can do some really cool things with this. The main examples that stand out in my mind are:

- Add support for new ipld types
  - i've been struggling to decide how i want to ship the blockchain and git integrations, this solves the problem nicely
- Add support for new libp2p transports
  - I don't necessarily want to ship ipfs with support for utp, udt, webrtc, and friends by default. But if users want to try these out easily, using a plugin really makes sense to me here

**Comment by Kubuxu** [comment]
As a note it will work only on LInux right now.

**Comment by whyrusleeping** [comment]
I think we can close this now, we have plugins (At least where they are supported by go). @Kubuxu ?

**Comment by Kubuxu** [comment]
Yes. What we can do is open issue for plugin types we want to support.
