### ISSUE TITLE
go-ipld-node has been renamed go-ipld-format

### ISSUE THREAD

**Issue by timthelion** [ipfs/go-ipfs#3858]
The repo go-ipld-node no longer exists https://github.com/ipfs/go-ipfs/blob/master/package.json#L259

It seems to have been renamed to go-ipld-format https://github.com/ipfs/go-ipld-format/blob/master/format.go

I came across this while reading the source code.

**Comment by Kubuxu** [comment]
Actionable here:
 - update gx package
 - update and rename imports

**Comment by tomatopeel** [comment]
Is this still an issue? A grep for ipld-node in go-ipfs doesn't turn aything up.

**Comment by Stebalien** [comment]
Nothing that I can see other than https://github.com/ipfs/go-ipld-format/pull/15

**Comment by whyrusleeping** [comment]
I think this can be closed now
