### ISSUE TITLE
Version mismatch between Docker image and pre-built client

### ISSUE THREAD

**Issue by bjornl** [ipfs/go-ipfs#3865]
#### Version information:

go-ipfs version: 0.4.8-dev-c21c85f
Repo version: 5
System version: amd64/linux
Golang version: go1.7.4

#### Type:
Bug

#### Severity:
Very Low

#### Description:

Official Docker image[1] uses version string "0.4.8-dev" while the pre-built binary uses version string "0.4.8" so the pre-built binary can not be used to interact with IPFS Docker container.

ipfs --api /ip4/10.32.0.48/tcp/5001 cat QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme 
api version mismatch (/go-ipfs/0.4.8-dev/ != /go-ipfs/0.4.8/)

[1] https://hub.docker.com/r/ipfs/go-ipfs/

**Comment by Kubuxu** [comment]
Pushed 0.4.8 tag into release branch. When docker hub rebuilds it should be solved.
