### ISSUE TITLE
Is it possible to see which IPs are hosting a particular IPFS address? 

### ISSUE THREAD

**Issue by LRonHubs** [ipfs/go-ipfs#3871]
Sorry if this is a duplicate post. Is there a function to see which IP addresses are hosting a particular file?

**Comment by Kubuxu** [comment]
The go-ipfs issues tracker is meant for directly actionable items related to go-ipfs.

Checkout ipfs/faq for answer and if you don't find it there as it on https://discuss.ipfs.io .
