### ISSUE TITLE
ipfs dns command acting odd

### ISSUE THREAD

**Issue by tjgillies** [ipfs/go-ipfs#3872]
#### Version information:
go-ipfs version: 0.4.8-
Repo version: 5
System version: amd64/linux
Golang version: go1.8

#### Type:
Bug

#### Severity:
medium
#### Description:
```
[tyler@tyler-pc ~]$ ipfs dns -r tyler.cat
Error: not a valid domain name
```

Resolves fine when I have an /ipfs/ record. Complains when I have an /ipns/ record. Everything else works fine

**Comment by Kubuxu** [comment]
Should be resolved by: https://github.com/ipfs/go-ipfs/pull/3873
