### ISSUE TITLE
bug: Bitswap not recording 'Bytes sent'

### ISSUE THREAD

**Issue by dgrisham** [ipfs/go-ipfs#3875]
#### Version information:

go-ipfs version: 0.4.9-dev-9dc5883a
Repo version: 5
System version: amd64/linux
Golang version: go1.8.1

This bug was also observed in version 0.4.8-dev.

#### Description:

When sending blocks to another user, the number of bytes sent to that user is not recorded in the corresponding Bitswap ledger (the receiving peer *does* record the number of bytes they receive, however).

**Steps to reproduce**:

1. (Optional) Initialize 2 peers to be connected to only each other.
    - On both peers: `ipfs init`, `ipfs bootstrap rm all`, `ipfs bootstrap add <other_peer_multiaddr>`
    - Run `ipfs daemon`, then `ipfs swarm peers` to ensure connections are established.
2. Add file to IPFS on one of the peers, then get the file on the other peer.
    a. Peer 1: `head -c 1000 /dev/urandom | base64 > /tmp/file && ipfs add -q /tmp/file`
    b. Peer 2: `ipfs get <file_hash>`
3. Check Bitswap ledgers with `ipfs bitswap ledger <peer_id>`

After I run those steps, the result on the *sending* peer is:

```
Ledger for <peer.ID XLhkey>
Debt ratio:     0.000000
Exchanges:      0
Bytes sent:     0
Bytes received: 0
```

And on the *receiving* peer:

```
Ledger for <peer.ID PipTao>
Debt ratio:     0.000000
Exchanges:      1
Bytes sent:     0
Bytes received: 1365
```

If I then swap the roles and have the second peer upload a file that the first peer downloads, the first ledger changes to:

```
Ledger for <peer.ID XLhkey>
Debt ratio:     0.000000
Exchanges:      1
Bytes sent:     0
Bytes received: 1365
```

and the second ledger is unchanged from the one above.

I'm going to look into this myself, but I thought I'd post it here in case anyone has an immediate idea as to why this is happening. 

Thanks!

**Comment by dgrisham** [comment]
It looks like the function `MessageSent`, which updates the ledger just like `MessageReceived` when a message is received, wasn't actually called anywhere. I was able to fix it by adding a call to `MessageSent` where it seemed to make the most sense and have verified that the update works as expected, I'm about to submit a pull request with the change. Let me know if there are any other checks or changes I can make to this update, or if I completely missed the reason for this issue and my change was unnecessary.

**Comment by whyrusleeping** [comment]
@dgrisham make sure to add a test or two for this in exchange/bitswap/bitswap_test.go :)

**Comment by dgrisham** [comment]
@whyrusleeping Gotcha, will do :)
