### ISSUE TITLE
ipfs config not working

### ISSUE THREAD

**Issue by kenshyx** [ipfs/go-ipfs#3881]
#### Version information:
``` 
go-ipfs version: 0.4.8-
Repo version: 5
System version: amd64/linux
Golang version: go1.8
```

#### Description:
I've noticed a weird behaviour of `ipfs config`. If the node running this command does not have "golang" installed it throws an error`Error: api not running` [test](https://travis-ci.org/AkashaProject/ipfs-connector/builds/226425114#L3127). After I installed golang everything worked as expected [test](https://travis-ci.org/AkashaProject/ipfs-connector#L3081).

**Comment by whyrusleeping** [comment]
the 'api not running' error comes from the node being improperly shut down and the `$IPFS_PATH/api` file still existing.

I spun up a fresh ubuntu docker image (without go installed), copied an ipfs binary into it, and everything seems to work properly:
```
oot@067dab1fc270:/# ./ipfs config Addresses
{
  "API": "/ip4/127.0.0.1/tcp/5001",
  "Gateway": "/ip4/127.0.0.1/tcp/8080",
  "Swarm": [
    "/ip4/0.0.0.0/tcp/4001",
    "/ip6/::/tcp/4001"
  ]
}
root@067dab1fc270:/# which go
```

**Comment by MichaelMure** [comment]
Shouldn't go-ipfs cleanup the api file and try again in this case ?

**Comment by whyrusleeping** [comment]
@MichaelMure Thats a difficult one... I often manually write the api file to point to a remote server (so i don't have to pass a --api flag). Having that file get deleted if my internet goes down would be pretty annoying.

I guess a workaround here would be to have two files, `api` and another one whose existence denotes manual human intervention. The `api` file should get cleaned up as you suggest in error cases, and the human created file should return the 'api not running' error.

**Comment by MichaelMure** [comment]
I agree, it sounds like two different use case to me. Otherwise, each apps that embed go-ipfs have to cleanup the api file in case of a crash or if the daemon got killed with the app.

**Comment by Kubuxu** [comment]
IPFS daemon cleans it up. In most cases. In some cases (when it is killed forcibly or crashes) it doesn't.

**Comment by kenshyx** [comment]
Thanks for clarifying :)
