### ISSUE TITLE
IPFS needs an acd_cli option

### ISSUE THREAD

**Issue by SchroSct** [ipfs/go-ipfs#3883]
#### Description: IPFS should have an option to use acd_cli as a backend for storage for the repo.
This would allow for nodes to act as less efficient but longer term 'unlimited' storage repo.

**Comment by whyrusleeping** [comment]
This means creating a datastore implementation that can use the acd_cli to store blocks. To start with that, someone would need acd API documentation, and then would need to implement this interface: https://github.com/ipfs/go-datastore/blob/master/datastore.go

**Comment by SchroSct** [comment]
https://github.com/yadayada/acd_cli/tree/master/acdcli/api
does this help at all?
I like the idea of having the amazon api directly in with go-ipfs, but maybe it's easier for the time being to simply have go-ipfs make calls to the acd_cli that may work better than the 'acd_cli mount' which seems to create issues with uploads and deletions.

**Comment by SchroSct** [comment]
Amazon has proven to be as terrible as suspected.  Changed their terms making this an extra bad idea.
