### ISSUE TITLE
ipfs cat /ipfs/<hash>: unrecognised node type

### ISSUE THREAD

**Issue by dojobel** [ipfs/go-ipfs#3886]
#### Version information:
go-ipfs version: 0.4.8-
Repo version: 5
System version: amd64/linux
Golang version: go1.8

#### Type:
Bug

#### Severity:
Medium
#### Description:
I've added a file and folder to the IPFS repository and am getting this error when browsing to them using gateway.ipfs.io:

ipfs cat /ipfs/<HASH>: unrecognized node type

The two "root" hashes (don't know the term you guys use for the top-level) are:
QmcxzUBGcTSc1zrm5n1yihWiRW3wB5mQs9B832WyGxta1k
QmdMfkseBWgYnXktFGQZMoQzqUxTMD9dWoHjZ8ptWs9uys

Interestingly, browsing to the only file sitting underneath the first hash works fine:
QmZ7RUvVGfKVa14uARQCpfgbGQUkchsjWka7coiNN44idf

And browsing to several other files below the second hash work fine also:
Qmb6TYpcHUwKXpebS4JnNFTnGmL3UsbEYxYwg9EXHAuA7u
QmTMhki9DDH4mcaC8QjqGFsnfsexLWcjH5iWUoRs4cUhjR

Seems to just be directory listings that it's bombing out for.

It also might be worth mentioning I've enabled sharding just before this started occurring (for another issue I have logged), unsure if that's related or not

**Comment by whyrusleeping** [comment]
It would appear that the gateways cant handle listing sharded directories. I'll fix this

**Comment by dojobel** [comment]
@whyrusleeping just tested this but I'm still getting the same result.. Do I need to re-add the files or do anything from my end? Is there a delay for the merge to take place on the gateways?

**Comment by Kubuxu** [comment]
Yeah, global gateways have to be deployed for the change to be observed on `ipfs.io`.
