### ISSUE TITLE
Ipfs daemon doesnt shutdown quickly after ctrl+c

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3903]
Something is preventing it from closing quickly. I think its probably waiting on something network related, it shouldnt be. 

To reproduce:
- start a daemon
- do a few things to get connections started up
- kill the daemon with a single ctrl+c
- notice how long it takes to actually exit

**Comment by erkinalp** [comment]
It is intended. It should first serve already-made requests.

**Comment by whyrusleeping** [comment]
No, it's waiting more than just serving live requests.

**Comment by Kubuxu** [comment]
I am removing it from the milestone, please let me know if we want to investigate it in near future.

**Comment by Stebalien** [comment]
I haven't seen this issue in a while.
