### ISSUE TITLE
need option to fetch and not provide immediately

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3904]
i want to be able to run `ipfs pin add` but not have my node automatically send out provider messages. Purely a perf/resource consumption thing

**Comment by whyrusleeping** [comment]
This should actually be fairly possible after provider modes are shipped.

**Comment by schomatis** [comment]
@whyrusleeping Is this issue still relevant to work on it?

**Comment by whyrusleeping** [comment]
@schomatis Yes, definitely. @magik6k has started work towards this, you should coordinate with him on how to move forward.

**Comment by michaelavila** [comment]
This is now possible in a number of ways, so I'm closing this issue.

1. `ipfs add --offline`
2. Use the new strategic provider system with a strategy of "none" (`Provider.Strategy`)
