### ISSUE TITLE
ipfs resolve doesn't work with sharded dirs

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3910]
#### Description:

Run `ipfs resolve /ipfs/Qm...AAA/file` where `Qm...AAA` is sharded.

**Comment by whyrusleeping** [comment]
Solution is likely to add a unixfs contextual resolver to the resolve command (though maybe we want that as an option?)
see:  https://github.com/ipfs/go-ipfs/blob/master/core/commands/ls.go#L93

**Comment by whyrusleeping** [comment]
@Stebalien has this been resolved?

**Comment by Stebalien** [comment]
@whyrusleeping no. I only fixed pinning. Test case:

```go
ipfs resolve /ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/index.html
```

However, this is a deeper issue. We need to switch to using the unixfs resolver for *all* `/ipfs` paths and then add a `/ipld` prefix for resolving IPLD paths (https://github.com/ipfs/notes/issues/248).

**Comment by Stebalien** [comment]
Fixed in the CoreAPI refactor.
