### ISSUE TITLE
Turkish Wikipedia: Error: no link named "wiki"

### ISSUE THREAD

**Issue by Zaijo** [ipfs/go-ipfs#3911]
#### Version information:
go-ipfs version: 0.4.8-
Repo version: 5
System version: amd64/darwin
Golang version: go1.8

#### Type:
Bug

#### Severity: 
High

#### Description:
ipfs get /ipns/QmVH1VzGBydSfmNG7rmdDjAeBZ71UVeEahVbNpFQtwZK8W/wiki/Anasayfa.html
Error: no link named "wiki" under QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX

**Comment by Kubuxu** [comment]
Update to 0.4.9-rc2, it was bug in handling of directory sharding in gateway code.

**Comment by Zaijo** [comment]
I'm running ipfs version 0.4.13 but the same error appears. Wowever, I can "ipfs cat" the very same Anasayfa.html file and I get the result to console.

**Comment by Stebalien** [comment]
Yeah, this isn't fixed. It's the same as #4431. #4444 tries to fix this but we're currently considering our options.

**Comment by aschmahmann** [comment]
Closing in favor of #8072
