### ISSUE TITLE
Add flag to ipfs add to select hash function to use

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3917]
I see this as step 1 towards enabling blake2b support. This flag could even default to blake2b-256

**Comment by kevina** [comment]
@whyrusleeping With the way you had me write the flag to select the CID version this should be easy to do.  Do you want me to take this one it will probably only take me a few hours, including tests.

**Comment by kevina** [comment]
Okay this seams really straightforward and easy to do I will go ahead and knock this one off.

**Comment by whyrusleeping** [comment]
@kevina Yeah! go ahead :)

**Comment by kevina** [comment]
@whyrusleeping 

Setting the default to `blake2b-256` would be an incompatible change so its best that it defaults to "sha2-256" for now.

Also CidV0 technically supports different hashes, but in practice this will cause decoding problems so this will only work with CidV1.  The only question is should `--hash=sha2-256` function also set the Cid version to 1.  All other values will only work CidV1 so its best to just (unconditionally) set it.
