### ISSUE TITLE
command Add is unsuccessful when File is a ReaderFile

### ISSUE THREAD

**Issue by briantigerchow** [ipfs/go-ipfs#392]
Seems to be  `*MultiFileReader.Read`

```
Post http://127.0.0.1:5001/api/v0/add: Couldn't call NextFile(), this isn't a directory
```

@mappum

**Comment by jbenet** [comment]
update?

**Comment by mappum** [comment]
Which file is a ReadFile? This should never happen since the `Files` field in `Request` should always be a directory.

**Comment by jbenet** [comment]
Update? @briantigerchow @mappum

**Comment by jbenet** [comment]
is this fixed? let's verify

**Comment by whyrusleeping** [comment]
closing, issue resolved a while ago
