### ISSUE TITLE
Remove gx references to be usable as library

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [ipfs/go-ipfs#3920]
I am trying to use go-ipfs in a personal project. Sadly, several `go` files have explicit references to "gx".
Since I am using Bazel to build my project, this mechanic is not working.
It would be great if go-ipfs would handle like a stock go project without the need for a specific build system/package manager.

**Comment by Kubuxu** [comment]
It was discussed multiple times already:
https://github.com/ipfs/go-ipfs/issues/3327
https://github.com/ipfs/go-ipfs/issues/3648

**Comment by abergmeier-dsfishlabs** [comment]
> It was discussed multiple times already:
#3327
#3648

I do understand the problems with go's module system and the incentive to create/use gx.
On the other hand I would perhaps suggest you looking at Bazel. There you can reference third-party revisions AND have use standard go methods.

**Comment by whyrusleeping** [comment]
@abergmeier-dsfishlabs with bazel you should be able to run `gx-go uw` on the go-ipfs source to change paths back to normal github paths.

**Comment by wigy-opensource-developer** [comment]
@abergmeier-dsfishlabs After running through the Bazel tutorial, I still do not see how you can chose a given commit in a git repository for your build. If you want to get reproducible builds, you need to find a way to do that. gx is one way to achieve that reproducibility and you can integrate it into your build system as an external dependency: https://bazel.build/versions/master/docs/external.html#non-bazel-projects

**Comment by abergmeier-dsfishlabs** [comment]
> After running through the Bazel tutorial, I still do not see how you can chose a given commit in a git repository for your build.

In your `WORKSPACE` file you would write:

    git_repository(
        name = "com_ipfs_go-ipfs",
        commit = "a4ffefd2ad6207758669d07e30acd52f74dc4f09",
        remote = "https://github.com/ipfs/go-ipfs.git",
    )

I will probably fork, remove gx, add Bazel and merge every release into my fork.

**Comment by whyrusleeping** [comment]
Closing

**Comment by anacrolix** [comment]
See now #5850 and #5848.
