### ISSUE TITLE
add `--first-valid` option to ipns name resolution

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3930]
Some usecases for ipns just care about getting *any* valid record. Our time to first record for ipns lookups is quite fast, i think we should expose this for users who don't care as much about perfect consistency

**Comment by whyrusleeping** [comment]
maybe make it into a `--resolve-mode=first-valid`

**Comment by whyrusleeping** [comment]
This might require the changes to getValue that @mildred was working on

**Comment by lgierth** [comment]
Or just make the DHT quorum configurable instead

**Comment by whyrusleeping** [comment]
@vyzo @magik6k  @Kubuxu, could one of you take a hack a this? It could be incredibly useful for some users of ipns

**Comment by vyzo** [comment]
I can take a hack, but it will be a few days as I am on the roard till thursday evening.

**Comment by vyzo** [comment]
Are we in a rush here? 
I would rather have #4047 merged first, because it would create a bad conflict in the rebase.

**Comment by whyrusleeping** [comment]
no rush, can definitely get that PR merged first

**Comment by magik6k** [comment]
We now have `ipfs name resolve --stream`, connected with `| head -n1` this does exactly what is requested here.
