### ISSUE TITLE
bug: Errors trying to pin Turkish Wikipedia

### ISSUE THREAD

**Issue by Bk7Z26JEYcp** [ipfs/go-ipfs#3932]
#### Version information:
go-ipfs version: 0.4.9-
Repo version: 5
System version: amd64/linux
Golang version: go1.8.1

#### Description:
I have installed go-ipfs on a vultr.com VPS with 512 MB of ram using an ipfs.io blog post [1] as a guide.
Following instructions at another ipfs.io blog post [2], I have tried pinning the Turkish Wikipedia
 to my ipfs node, this results in many errors and an eventual crash of the ipfs daemon. A full error log is at pastebin [3], an excerpt is here:

$ ipfs pin add QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX
15:54:29.716 ERROR    bitswap: couldnt open sender again after SendMsg(<peer.ID QZDKpK>) failed: dial backoff wantmanager.go:233
15:54:38.158 ERROR    bitswap: couldnt open sender again after SendMsg(<peer.ID QKmLFd>) failed: dial attempt failed: <peer.ID cEWfCa> --> <peer.ID QKmLFd> dial attempt failed: i/o timeout wantmanager.go:233

[1] [https://ipfs.io/blog/22-run-ipfs-on-a-vps](https://ipfs.io/blog/22-run-ipfs-on-a-vps)
[2] [https://ipfs.io/blog/24-uncensorable-wikipedia](https://ipfs.io/blog/24-uncensorable-wikipedia)
[3] [https://pastebin.com/MegVJCuz](https://pastebin.com/MegVJCuz)

**Comment by whyrusleeping** [comment]
We've been noticing that since the wikipedia dump is made up of a very large number of small files, its putting a lot of stress on the DHT when syncing it all at once. I'm working on some fixes that should help avoid this in the future, but for now, the workaround we're recommending is to disable the DHT for the duration of the sync. To do that, start the ipfs daemon with `--routing=none`, and then before running the pin command, connect your node manually to another peer that has the entire backup:
```
ipfs daemon --routing=none
# now, in another shell
ipfs swarm connect /ip4/188.40.116.66/tcp/4001/ipfs/QmepgFW7BHEtU4pZJdxaNiv75mKLLRQnPi1KaaXmQN4V1a
ipfs pin add QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX
```

**Comment by whyrusleeping** [comment]
You can also run the pin with a `--progress` option to track that:
```
ipfs pin add --progress QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX
```

**Comment by Bk7Z26JEYcp** [comment]
Thank you for your help!
I tried your instructions and succeeded on the third attempt. The error messages for the first two attempts:

Attempt 1:
$ ipfs pin add --progress QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX
Fetched/Processed 188073 nodes22:30:10.088 ERROR    bitswap: couldnt open sender again after SendMsg(<peer.ID X7oD3P>) failed: dial attempt failed: context deadline exceeded wantmanager.go:233
Fetched/Processed 701189 nodes01:04:20.011 ERROR commands/h: unexpected EOF client.go:247

Error: unexpected EOF
[1]+  Killed                  ipfs daemon --routing=none

Attempt 2:
$ ipfs pin add --progress QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX
Fetched/Processed 695855 nodes09:32:07.144 ERROR commands/h: unexpected EOF client.go:247

Error: unexpected EOF
[1]+  Killed                  ipfs daemon --routing=none

**Comment by whyrusleeping** [comment]
Glad to hear you got it synced! 512mb of ram is quite low for ipfs today,
primarily due to TCP connections and our stream muxer being really memory
hungry.

**Comment by whyrusleeping** [comment]
Going to close this one out, please do open a new issue if you (or anyone else) runs into similar problems.
