### ISSUE TITLE
Bootstrapping problems

### ISSUE THREAD

**Issue by dsvi** [ipfs/go-ipfs#3933]
#### Version information:
go-ipfs version: 0.4.9-
Repo version: 5
System version: amd64/linux
Golang version: go1.8.1

#### Type:
Bug

#### Severity:
High
#### Description:

Bootstrapping doesn't seem to work for me on couple machines. I can ping the ip addresses from the built in bootstrap list, but ipfs do not connect to them. `ipfs swarm peers` is empty.

**Comment by mateon1** [comment]
If possible, could you include as much related info as possible?
What commands are you using? What do they output? What routers do the broken nodes have? What ISPs are they on? Is outgoing port 4001 blocked?

**Comment by dsvi** [comment]
Sorry, should have done that at the beginning.
Generally i have got ipfs and set up my node by
`ipfs init`
`ipfs daemon`
Both nodes behind NAT but they are able to redirect ports for themselves through upnp. I've checked this. Ping to the nodes from the config bootstrap list goes through fine. But ipfs is still unable to bootstrap 
`ipfs swarm peers`
returns empty.

**Comment by Jacodelange** [comment]
@dsvi Were you able to find a solution?

**Comment by whyrusleeping** [comment]
I'm pretty sure this was an issue in the reuseport code. It has been updated in 0.4.10, and another related fix was merged for 0.4.11. Please reopen if this is still broken on latest master or 0.4.11 (once its released).

**Comment by dsvi** [comment]
Unfortunately the issue is still here, in 0.4.11

**Comment by dsvi** [comment]
Don't know how to reopen it. Not sure i have the access rights

**Comment by Kubuxu** [comment]
@whyrusleeping any idea?

**Comment by whyrusleeping** [comment]
It sounds like a firewall issue.

@dsvi Can you try netcatting to one of the bootstrap nodes, for example:
```
nc 104.236.179.241 4001
```

And see if you get a multistream tag back?

**Comment by dsvi** [comment]
It's not a firewall issue, since some nodes actually work, member? (See my workaround.) It's just the nodes from bootstrap list (and some others) that don't.
the netcat gives me: 
`/multistream/1.0.0`

**Comment by dsvi** [comment]
actually the situation had changed a bit. now on 
`ipfs swarm connect /ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3`
i get:
`Error: connect QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3 failure: dial attempt failed: <peer.ID Yp54FE> --> <peer.ID SoLMeW> dial attempt failed: dial tcp6 [2a03:b0c0:1:d0::e7:1]:4001: connect: network is unreachable`
note the ip4 in the request, but yet it tries to connect through tcp6. maybe this will give some hint, on whats going on.

**Comment by Stebalien** [comment]
`ipfs swarm connect /ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3` won't force your machine to dial `127.62.61.185`. Instead, it will just add it to your address book and then dial all known addresses for that peer. The gateways advertise IPv6 addresses but your don't have IPv6 support so that dial is failing.

However, I that's not the problem. I'm guessing that this is just the *last* error; there's a different error for the IPv4 address that we're not seeing because IPFS tries all addresses (and returns the last error).

Please try raising the log level of swarm by running `ipfs log level swarm2 info` and then run `ipfs log tail` while dialing. This should print out any relevant errors (and yes, we should return these errors somehow; probably by printing status messages to stderr).

**Comment by djdv** [comment]
https://github.com/ipfs/go-ipfs/pull/4453 is giving me connection issues, anything prior to dfe7ef4fcfaf340846ee16031550601b3ff625d6 will connect but anything later than this leaves me with an empty peer table, unable to connect to anyone, even local network connections.

The error I am getting when trying to dial out is
```
> ipfs swarm connect /ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3
Error: connect QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3 failure: dial attempt failed: <peer.ID WABRCq> --> <peer.ID SoLMeW> dial attempt failed: dial tcp4 0.0.0.0:4737->178.62.61.185:4001: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
```

To me this implies that something somewhere is trying to bind to the same socket twice.

**Comment by Stebalien** [comment]
@djdv this is *definitely* a bug (or maybe a build issue) but not the same as this one. I've reported a new one (#4512).

**Comment by Stebalien** [comment]
(closing this as it's old enough to no longer be particularly useful)

**Comment by icemagno** [comment]
2023 and I came here because SAME issue
