### ISSUE TITLE
Command to check block size without retrieving it?

### ISSUE THREAD

**Issue by ethernomad** [ipfs/go-ipfs#3946]
`ipfs block stat` has to retrieve the block before it can determine the size. This could lead to a DoS attack.

Is it possible to query the size of a block before downloading it?

**Comment by mattseh** [comment]
If it is linked to from a parent block then `ipfs object links`:

>➜  ~ mkdir x
>➜  ~ echo "hello" > x/hello.txt
>➜  ~ ipfs add -r x
added QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN x/hello.txt
added QmU5PLEGqjetW4RAmXgHpEFL7nVCL3vFnEyrCKUfRk4MSq x
>➜  ~ ipfs object links QmU5PLEGqjetW4RAmXgHpEFL7nVCL3vFnEyrCKUfRk4MSq
QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN 14 hello.txt

**Comment by ethernomad** [comment]
But this is not authoritative - an attacker could lie.

**Comment by mattseh** [comment]
I think this is a fundamental limitation, you cannot be sure of the size of some data without being able to measure it yourself.

**Comment by whyrusleeping** [comment]
@ethernomad its worth noting that an individual block may be no larger than 2MB. So fetching a single block to check its size is unlikely to cause a DoS

**Comment by whyrusleeping** [comment]
I think this issue is resolved. Please reopen if there are further clarifications needed
