### ISSUE TITLE
Split & concat via IPFS?

### ISSUE THREAD

**Issue by JayBrown** [ipfs/go-ipfs#3947]
Based on ideas from [**this discussion comment**](https://discuss.ipfs.io/t/private-personal-use-of-ipfs/350/13?u=jaybrown) regarding enhanced security.

You can always do it manually outside of `ipfs`, of course, but maybe there's some need to add a **split** option to `ipfs add`, i.e. to split a file at a random point before adding it to the IPFS? E.g.:

```
ipfs add --split=2 /path/to/testfile
added QmHash1 segment 1 of testfile
added QmHash2 segment 2 of testfile
```

Alternative options could be `--split=25m` for 25 MB, with g for GB and so on.

In turn ipfs would then need a **concat** option, e.g.:

```
ipfs get concat QmHash1 QmHash2 -o /newpath/to/testfile
```

or as a new command

```
ipfs concat QmHash1 QmHash2 -o /newpath/to/testfile
```

As stated above, the original idea behind it is to increase security, i.e. to obfuscate the original file. It would be useless, though, if there's a public record on when and by which node an object (hash) was originally added to the IPFS.

**Comment by Kubuxu** [comment]
You can already do it using external tooling. I don't really see a reason to add it to IPFS directly.

Also it doesn't add that much security, it is more of a obscurity than security.
