### ISSUE TITLE
DAG in Web UI breaks on object from "ipfs dag put"

### ISSUE THREAD

**Issue by mattseh** [ipfs/go-ipfs#3960]
#### Version information:

go-ipfs version: 0.4.9-
Repo version: 5
System version: amd64/darwin
Golang version: go1.8.1

Using Chrome Version 59.0.3071.86 (Official Build) (64-bit) on OS X

#### Description:

I make a DAG:

    ➜  ~ echo '{"hello": "world"}' | ipfs dag put
    zdpuAtX7ZibcWdSKQwiDCkPjWwRvtcKCPku9H7LhgA4qJW4Wk

I then go to the Web UI (port 5001 on localhost), click on the DAG menu option, then input the above multihash. Nothing appears to happen, and I get these errors in the Chrome console: https://gist.github.com/anonymous/967208b3c0ce2cbed8da294276338f04

A multihash from `ipfs add` does not have this error.

**Comment by Kubuxu** [comment]
Please report it to webui repo at https://github.com/ipfs/webui
