### ISSUE TITLE
Daemon appears to conflict with Google Chrome / Great Suspender plugin

### ISSUE THREAD

**Issue by h3298** [ipfs/go-ipfs#3961]
#### Description: 
90 suspended tabs were lost when launching daemon while browser was running
(this has never occurred before under any other circumstance)
a security warning also appeared in extensions list which has never been seen before

possibly a low memory issue was involved ; too busy to attempt replication at the moment due to loss of research project

idea: Can IPFS possibly be implemented in browser through an extension instead of the current method?

**Comment by Kubuxu** [comment]
Were you using the IPFS Addon?

**Comment by h3298** [comment]
No, I was not aware there is one.  This should be promoted on the IPFS main web site.  I'll post a link here to the web store for the convenience of others.
https://chrome.google.com/webstore/search/ipfs

Today I learned the developer's account was compromised and an unauthorized version of the extension was pushed to the Chrome webstore.  It was merely by chance that I installed IPFS at the same time.  The issue is resolved.

**Comment by Kubuxu** [comment]
We are creating https://github.com/ipfs/ipfs-companion/ which soon should work also on Chrome.

Good that it was not issue on our side. Have fun discovering IPFS.

**Comment by lgierth** [comment]
Hold on, @h3298 what are you saying about account compromise? Please reach out to security@ipfs.io asap.

**Comment by lgierth** [comment]
Ah okay, that's about a different extension unrelated to IPFS.

For context: https://github.com/deanoemcke/thegreatsuspender/issues/512#issuecomment-306356434
