### ISSUE TITLE
I can't find any speed comparison with http [down|up]load

### ISSUE THREAD

**Issue by baimurzin** [ipfs/go-ipfs#3973]
Hello!
It seems that it's work speed high enough(ipfs add/get)
But can someone provide any real actual speed comparison between traditional http file upload and download and using ipfs? 
It will be very useful!

**Comment by whyrusleeping** [comment]
Hey! Lets keep this sort of discussion in discourse on your thread there: https://discuss.ipfs.io/t/i-cant-find-any-speed-comparison-with-http-down-up-load/615
