### ISSUE TITLE
The contributing document links to a non-existent "developer certificate of origin" doc

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#3976]
Specifically, the `./docs/developer-certificate-of-origin` link in [contribute.md](https://github.com/ipfs/go-ipfs/blob/master/contribute.md#commit-messages) is dead (and doesn't appear anywhere in the git commit history as far as I can tell).

**Comment by magik6k** [comment]
It was added in https://github.com/ipfs/go-ipfs/commit/be334f3c3455accef812d8f992ac6c56a388347f, and the file didn't exist then too.

**Comment by lgierth** [comment]
Yeah let's remove that

**Comment by Stebalien** [comment]
We'll probably want to replace it with some language stating that the author:

1. Actually *can* license the content under the MIT license (they own it or it's already MIT licensed and properly attributed).
2. Mumble patent rights? This is why people use the Apache 2.0 license...

**Comment by lgierth** [comment]
No, the current policy is that we require contributions to go-ipfs be MIT-licensed using the signoff in the comment message.

**Comment by lgierth** [comment]
> No, the current policy is that we require contributions to go-ipfs be MIT-licensed using the signoff in the comment message.

Although of course that needs improvement. Just saying that we should remove the DCO mention regardless.

**Comment by Stebalien** [comment]
#3976

**Comment by Kubuxu** [comment]
I think it was supposed to link to copy of DCoO as it is in Linux: https://developercertificate.org/

**Comment by Stebalien** [comment]
@Kubuxu Looks about right. I've updated the PR.
