### ISSUE TITLE
IPFS doesn't accept multibase IPNS addresses

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#3977]
#### Version information:

go-ipfs version: 0.4.9-8ec0814a
Repo version: 5
System version: amd64/linux
Golang version: go1.8.3

#### Type:

Enhancement?

#### Severity:

Low

#### Description:

IPFS doesn't accept multibase IPNS addresses. For example, try fetching wikipedia with a multibase prefix:

```sh
ipfs cat /ipns/zQmdJiuMWp2FxyaerfLrtdLF6Nr1EWpL7dPAxA9oKSPYYgV/wiki/index.html
```

**Comment by whyrusleeping** [comment]
hrm... Should we add a cid multicodec for ipns?

**Comment by Stebalien** [comment]
Lately, I've been thinking of generalizing CIDv0: https://github.com/ipld/cid/issues/12

But yes, the alternative is to just say `Qm...` in `/ipns/Qm...` is not a CID, `SomethingElse` in `/ipns/SomethingElse` is.

**Comment by kevina** [comment]
Note: There is some debate is CidV0 hashes should even be allowed a multibase prefix so I'm not sure the correct thing to do here.

**Comment by Stebalien** [comment]
@kevina at the moment, IPNS addresses *aren't* CIDs. They're just raw multihashes (that point to special protocol buffers, not IPLD nodes).

**Comment by reardenlife** [comment]
@whyrusleeping
> "hrm... Should we add a cid multicodec for ipns?"

Was it ever implemented -- the CIDv1 for IPNS?

**Comment by lidel** [comment]
Done. IPNS support for multibase names being CIDv1 with libp2p-key codec   was implemented to make  https://github.com/ipfs/go-ipfs/pull/7441 possible a while ago :cat2:
