### ISSUE TITLE
endian.go:36 ("array bound is not constant") & endian.go:37 ("array index out of bounds")

### ISSUE THREAD

**Issue by Geremia** [ipfs/go-ipfs#3984]
0.4.9 and master branches
go version go1.8.1 gccgo (GCC) 7.1.0 linux/amd64

Bug

High

#### Severity:
Cannot build

#### Description:
I get this error at the end of the `make install` process:
```
go install -ldflags="-X "github.com/ipfs/go-ipfs/repo/config".CurrentCommit=7ea34c6c"  ./cmd/ipfs
# gx/ipfs/QmeFPvhFJGXGiXAc9zunNxZjCaWgYQpcsdwip2NWLcccyw/GoEndian
../../../gx/ipfs/QmeFPvhFJGXGiXAc9zunNxZjCaWgYQpcsdwip2NWLcccyw/GoEndian/endian.go:36:11: error: array bound is not constant
  bs := (*[INT_SIZE]byte)(unsafe.Pointer(&i))
           ^
../../../gx/ipfs/QmeFPvhFJGXGiXAc9zunNxZjCaWgYQpcsdwip2NWLcccyw/GoEndian/endian.go:37:8: error: array index out of bounds
  if bs[0] == 0 {
        ^

make: *** [cmd/ipfs/Rules.mk:26: cmd/ipfs-install] Error 2
```

**Comment by whyrusleeping** [comment]
key problem here: gccgo. Those are interesting errors...

**Comment by Kubuxu** [comment]
The problem is in https://github.com/gxed/eventfd/blob/master/eventfd.go which is used by our polling code. We need native encoding order to communicate with the Linux facilities but Go doesn't expose it anywhere.

**Comment by Geremia** [comment]
My machine is little endian (at least that's what C programs think it is…).

**Comment by Kubuxu** [comment]
It is problem with GoEndian not being able to compile under gccgo.

**Comment by Geremia** [comment]
@Kubuxu Yes
