### ISSUE TITLE
IPFS Daemon will not start after process abruptly stops

### ISSUE THREAD

**Issue by dondreytaylor** [ipfs/go-ipfs#3986]
#### Version information:
go-ipfs version: 0.4.9-
Repo version: 5
System version: 386/linux
Golang version: go1.8.1

#### Type:
Bug 

#### Severity:
High

#### Description:
It appears that my IPFS daemon will not start anymore after running for a few days and abruptly stopping without warning . Any time I attempt to start the IPFS daemon it hangs at **Successfully raised file descriptor limit to 2048.**

I noticed a repo.lock gets created when this happens, which I delete before attempting to start the daemon again. I can't seem to figure out why this happened all of sudden. My machine has quite a lot of disk space left. If anyone has experienced this issue, would definitely appreciate the help. Screenshot of the point where the IPFS daemon hangs is below. 

![screen shot 2017-06-16 at 4 22 45 pm](https://user-images.githubusercontent.com/3202583/27243708-2872cfee-52b1-11e7-89b5-462e6aec5cab.png)

**Comment by Kubuxu** [comment]
Can you try reproducing it with setting `IPFS_LOGGING=debug` environment variable?
It might give us some more insight.

**Comment by dondreytaylor** [comment]
Okay I'll try it now

**Comment by dondreytaylor** [comment]
After running it with `IPFS_LOGGING=debug` it seems to still hang. 

![screen shot 2017-06-16 at 4 47 20 pm](https://user-images.githubusercontent.com/3202583/27244277-d4ce90b4-52b3-11e7-9683-d9034cc3a2d8.png)

Also tried it with the debug flag too. When it gets to the end it drops my ssh connection into the machine.

![screen shot 2017-06-16 at 4 48 45 pm](https://user-images.githubusercontent.com/3202583/27244314-fd5b70ba-52b3-11e7-9da4-b694c7ad0533.png)

**Comment by Kubuxu** [comment]
It might be a problem with router and establishing UPnP mapping. Can you try restarting your router?

**Comment by Kubuxu** [comment]
(for the IPFS_LOGGING to take place you would have to export it `export IPFS_LOGGING` but it achieved similar result as IPFS_DEBUG).

**Comment by dondreytaylor** [comment]
Ah okay, forgot the export. Okay I'm going to restart my router now.

**Comment by dondreytaylor** [comment]
Wow, you were right on the money with that one. As soon as I restarted my router the IPFS daemon started up perfectly. Thanks.

![screen shot 2017-06-16 at 5 31 14 pm](https://user-images.githubusercontent.com/3202583/27245455-9fdfbefe-52b9-11e7-9968-bc7fa9278236.png)

**Comment by Kubuxu** [comment]
Another case of https://github.com/ipfs/go-ipfs/issues/3320 this time bad implementation of UPnP caused the problem.

**Comment by dondreytaylor** [comment]
Oh wow, totally missed this. I kept searching "daemon stopped" which is probably why I missed. I see, so the implementation of UPnP seems to cause problems at times.

**Comment by dondreytaylor** [comment]
Sure I'll get my router information now and comment it here.

**Comment by Kubuxu** [comment]
I have never met this problem before, so this is something completely new (it would be hard to find), it is also a bit other case of #3320 as the router wasn't dying, it just had problem with UPnP and possibly new connections.

**Comment by dondreytaylor** [comment]
Yeah, this one would have been difficult to replicate in a test environment for sure lol 

The router that I'm using is: 

**Brand:** D-Link 
**Model:** DIR-868L
**Hardware Version:** A1
**Firmware Version:** 6.0.9.1.86.1.7

**Comment by Kubuxu** [comment]
If the problem repeats I would try giving it a firmware update (if there is one). Have fun with IPFS.

**Comment by dondreytaylor** [comment]
Okay, I definitely will. Thanks @Kubuxu for all your help!
