### ISSUE TITLE
add a `--server` flag to ipfs init

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3987]
It would be good to have flag that sets a bunch of defaults best suited for running ipfs in a server environment. Including turning off mdns, blocking dialing to certain private ip ranges, and (when we have it) setting the announced addresses to the detected public ip of the machine.

**Comment by whyrusleeping** [comment]
issue about ip ranges not to dial: https://github.com/ipfs/go-ipfs/issues/1226#issuecomment-120494604

**Comment by lemmi** [comment]
An alternative (or addition) could be a `--profile=...` flag. So there could be a server profile and --server is the shortcut. Maybe profiles could be json files that are merged or override options in the config. These files could be built-in, or sit in a folder and also be user-editable.
