### ISSUE TITLE
mfs support for raw-nodes is incomplete

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3989]
many commands in the `ipfs files` namespace don't fully support raw-nodes. Simple reproduction:
```
echo "foo" | ipfs add --raw-leaves
ipfs files cp /ipfs/THATHASH /foo
# that bit breaks, but also somewhat succeeds
ipfs files stat --hash /foo
```

**Comment by kevina** [comment]
This sounds like an easy one for me to take on.

**Comment by whyrusleeping** [comment]
@kevina great!

**Comment by Kubuxu** [comment]
It is partially: https://github.com/ipfs/go-ipfs/issues/3921

**Comment by whyrusleeping** [comment]
@Kubuxu yeah, the dagmodifier is a good chunk of it

**Comment by kevina** [comment]
working on this now
