### ISSUE TITLE
Multiple races when starting daemon

### ISSUE THREAD

**Issue by magik6k** [ipfs/go-ipfs#3992]
#### Version information:
Current master

#### Severity:
Medium/Low

#### Description:
When compiling with go race detector (`GOFLAGS='-gcflags "-N -l" -race' make build `), when daemon is starting, there are multiple races reported:

https://gist.github.com/magik6k/0d5474ca940dc257abfc448c7e4e9abf

I haven't looked at them in detail, it's just what i have noticed when debugging different issue.

**Comment by whyrusleeping** [comment]
In general, It would be great to be able to run the ipfs daemon with race detection enabled. It currently fails because we open too many goroutines (too many connections + too many goroutines per connection in bitswap mostly). I remember @Kubuxu was working on addressing some of this

**Comment by Stebalien** [comment]
As far as I can tell, the only thing left is the mDNS race: https://github.com/libp2p/go-libp2p/issues/257
