### ISSUE TITLE
Return the size of each file on `ipfs add`

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#4008]
@whyrusleeping would you be ok with adding one more value on the response of an `ipfs add`? The respective file size.

This would enable us to greatly reduce the bundle size of `ipfs-api/add`, which is what most users need.

**Comment by whyrusleeping** [comment]
@diasdavid would you want something returned for directories and symlinks?

**Comment by diasdavid** [comment]
@whyrusleeping I feel it is useful to have the 'size' for those. Essentially I just grab the cumulative size https://github.com/ipld/js-ipld-dag-pb/blob/master/src/dag.proto.js#L13

**Comment by whyrusleeping** [comment]
@diasdavid alright, and you just want a `"size":12345` field added to the response object? Do you want it to be a number or a string?

**Comment by diasdavid** [comment]
Let's do a string because you [know](http://www.w3devcampus.com/wp-content/uploads/logoAndOther/logo_JavaScript.png)

**Comment by lgierth** [comment]
:+1: on including that, both the `ls` and `object/stat` commands return numbers though. Might be worth it to be consistent?

**Comment by Kubuxu** [comment]
It might be worth migrating away from returning numbers in JSON, to prevent stuff like https://github.com/ipfs/go-ipfs/issues/4008#issuecomment-311483203

**Comment by lgierth** [comment]
Which issue do you mean? 4008 is this one here

**Comment by Kubuxu** [comment]
Sorry https://github.com/ipfs/go-ipfs/issues/3354

**Comment by whyrusleeping** [comment]
@lgierth I think we should try to migrate numbers in our api to be strings. It would be a breaking change, but i think its pretty important. This is probably worth opening its own issue over

**Comment by imkmf** [comment]
Hey all! Can this be closed with #4082 being merged?
