### ISSUE TITLE
Change DAGService/BlockService's Remove methods to take CIDs

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4010]
Currently, they take nodes/blocks but use CIDs internally. Taking a CID is more generally useful. Currently, to remove a node by CID, one has to first retrieve it :(.

* [ ] Blocked on https://github.com/ipfs/go-ipld-format/pull/8

**Comment by whyrusleeping** [comment]
This can probably happen as part of the other cleanup work youre proposing

**Comment by Stebalien** [comment]
Yes, that's my plan. I'll close this for now.
