### ISSUE TITLE
yamux connection write timeout should probably be increased

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4011]
I'm on pretty crappy internet right now, and delays of ten seconds seem pretty common, its causing my connections to drop pretty frequently because we set the timeout here to be ten seconds: https://github.com/ipfs/go-ipfs/blob/master/core/core.go#L271

We should probably bump this up to 30 seconds or so

**Comment by Stebalien** [comment]
The real issue was that this 10 second timeout applied to buffered writes. We now:

1. Only apply it to the current write.
2. Limit messages to 64KiB each.

If we stall for >= 10 seconds, our connection is slower than 52kbps (dialup). I consider this fixed (enough).
