### ISSUE TITLE
Extract the bloom filter (blocks/bloom) into a separate repo

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4016]
I will end up needing it in go-floodsub. Alternatively, I can use an existing bloom filter implementation but I'd rather not start using two different bloom filter implementations...

**Comment by lgierth** [comment]
Well go for it :)

**Comment by Kubuxu** [comment]
We are already using different bloom implementation bblom in https://github.com/gxed/bbloom for caching of Has requests to the blockstore but it uses a bit different construction.

The blocks/bloom is much simpler but slower.

**Comment by Stebalien** [comment]
@Kubuxu is there any reason to use the one in blocks/bloom over bbloom?

**Comment by Kubuxu** [comment]
Significant performance difference and completely different thread safety.

The bbloom is much faster, thread safe (I have also atomic version of it if it ever becomes bottleneck in the blockstore Has lookup pipeline, I was one that path).

Block/boom as far as I understand is part of network protocol right now and serializes to protobuf.

**Comment by Kubuxu** [comment]
The main difference is: bbloom is fast, more complex and free to change, block/bloom is sower, simpler and stable.

**Comment by whyrusleeping** [comment]
wait, do we actually use the blocks/bloom code anywhere right now?

**Comment by Stebalien** [comment]
We use it in `blocks/set` but I can't find any users of that code...

**Comment by Stebalien** [comment]
Would you like a PR to delete those two packages (I'm not a fan of keeping dead code around, there's always git history if we want it back).

**Comment by Stebalien** [comment]
*\*poof\**
