### ISSUE TITLE
Get DAG's JSON from gateway?

### ISSUE THREAD

**Issue by mattseh** [ipfs/go-ipfs#4024]
#### Version information: 

go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/darwin
Golang version: go1.8.3

#### Description:

Traversal of objects created with `dag put` is possible when they lead to a file, for example `/ipfs/cid/image.jpeg` but when viewing `/ipfs/cid` I get `unrecognized node type`.

It would be useful to be able to get the raw JSON (or in other formats) directly from the gateway, rather than the API, so that javascript running within a webpage hosted on IPFS can traverse DAGs.

A further enhancement would be displaying a DAG so that links are clickable by humans, just as folder listings currently work.

**Comment by Kubuxu** [comment]
It is possible: https://ipfs.io/api/v0/dag/get?arg=zdpuAtTavf6ZSeBHi3cs9omZFyrdSLCseDtJEuejYp1fBYD17

**Comment by mattseh** [comment]
This is loadable from javascript inside an IPFS webpage, thanks!
