### ISSUE TITLE
Cache commonly accesses blocks to faster storage devices

### ISSUE THREAD

**Issue by travisperson** [ipfs/go-ipfs#403]
I brought this up in IRC a while ago, and I thought I made an issue for it but I can't find it anymore, feel free to close this if it's open someplace.

----

Much like processors have different levels of cache before memory and disks I think it would be great to allow IPFS to cache commonly accesses blocks or files. My idea behind this has two different approches. 

The first being, just having IPFS do an in memory store of blocks it's read off the disk. If I have a server with 64 gigs of ram and all I'm running off it is IPFS, it should be smart and try to store data in memory. I'm not sure what improvements this would have over the kernel itself doing this for you.

The second would be telling IPFS about different drives and giving them tiers. Three basic tiers or even just two would probably be fine. This would allow server owners to maybe use a SSD for files they want to be accessed quicker, and then just regular old platter disks for everything else.

One thing that would also allow is for a hosting service to provide faster file access for people who want to pay a little bit more. Some files could be backed by a larger stripped raid of drives.

**Comment by whyrusleeping** [comment]
closing, cool idea, but don't need to keep an issue open (closed issues still are searchable)
