### ISSUE TITLE
make install error in mac

### ISSUE THREAD

**Issue by shangmacun** [ipfs/go-ipfs#4043]
go install -ldflags="-X "github.com/ipfs/go-ipfs/repo/config".CurrentCommit=0b481a3"  ./cmd/ipfs
# gx/ipfs/QmVSase1JP7cq9QkPT46oNwdp9pT6kBkG3oqS14y3QcZjG/go-datastore/syncmount
../../../gx/ipfs/QmVSase1JP7cq9QkPT46oNwdp9pT6kBkG3oqS14y3QcZjG/go-datastore/syncmount/mount.go:31: undefined: sort.Slice

**Comment by whyrusleeping** [comment]
@shangmacun please update your go compiler to 1.8 or higher

**Comment by Quantomicus** [comment]
That said, the readme should be updated to reflect the fact that 1.8 is now required.
