### ISSUE TITLE
Error message when shutting down ipfs daemon

### ISSUE THREAD

**Issue by JayBrown** [ipfs/go-ipfs#4055]
#### Version information:
```
go-ipfs version: 0.4.10-4679f80
Repo version: 5
System version: amd64/darwin
Golang version: go1.8.3
```

#### Type:
error message without any noticeable error

#### Severity:
very low

#### Description:
I ran `ipfs shutdown` on the daemon, which had been started with `--writable`, and received the following error message (in the second terminal, not in the daemon's terminal).

```
Error: Post http://127.0.0.1:5001/api/v0/shutdown?encoding=json&stream-channels=true: EOF
```

Daemon shutdown worked nonetheless.

**Comment by whyrusleeping** [comment]
This same issue is causing random test failures in CI. Lets figure it out asap

**Comment by sherodtaylor** [comment]
Still getting this issue.

**Comment by schomatis** [comment]
@whyrusleeping Is this still an ongoing problem? I'm having trouble reproducing the error.

**Comment by Stebalien** [comment]
I haven't seen it for a while but I don't know of anything we might have done to fix it (maybe updating the commands lib?).

**Comment by Kubuxu** [comment]
@schomatis it was rare, usually daemon takes a sweet time to shut down and this happens only if it shuts down too fast. You can try running `ipfs daemon --offline` so it shuts down faster.

**Comment by Stebalien** [comment]
It's still happening.

**Comment by schomatis** [comment]
I'll take a look using @Kubuxu's advice.

**Comment by schomatis** [comment]
I can't reproduce it. I've tried with combinations of the `--offline` and `--writable` flags, with a heavy `add` load to the daemon and without. @Stebalien in what conditions did you see it happening again?

**Comment by Stebalien** [comment]
I just saw it on a random test on Jenkins. Unfortunately, I can't recall which test.

**Comment by Kubuxu** [comment]
It happens quite frequently on Jenkins.
