### ISSUE TITLE
TestFetchGraph failing randomly

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4062]
very occasionally we get a failure in TestFetchGraph: https://ci.ipfs.team/blue/organizations/jenkins/go-ipfs/detail/PR-4047/57/pipeline/

```
--- FAIL: TestFetchGraph (0.01s)
	merkledag_test.go:248: merkledag: not found
FAIL
```

This is likely a bug in FetchGraph or EnumerateChildren, definitely needs looking into.

**Comment by Kubuxu** [comment]
Repeated in https://travis-ci.org/ipfs/go-ipfs/jobs/262757884

**Comment by Stebalien** [comment]
This appears to be happening more often...

**Comment by Stebalien** [comment]
So, this is definitely a bug, not just a racy test. `FetchGraph` succeeds and then enumerating the graph fails. Possible locations:

1. `offline_ds.GetLinks` or `GetLinksDirect`. The test case uses this, `FetchGraph` uses `GetLinksDirect`. This seems unlikely
2. `EnumerateChildrenAsync` or `EnumerateChildren`. I'm betting it's `EnumerateChildrenAsync` (it's probably miscounting and not waiting for some subgraph to be enumerated.

**Comment by Stebalien** [comment]
So much for it being `EnumerateChildrenAsync`'s fault. I've tried replacing `EnumerateChildrenAsync` (in `FetchGraph` with `EnumerateChildren` and it still fails occasionally.

They could both be buggy...

**Comment by Stebalien** [comment]
Not `GetLinks` versus `GetLinksDirect` (not that surprising).

Also, I'm pretty sure the bug is *not* in `EnumerateChildren` as it's a simple recursive function.

**Comment by Stebalien** [comment]
So... bitswap is notifying bitswap sessions about blocks *before* adding them to the blockstore. We *really* need to clean up this logic.

(actually, bitswap notifies the session about the block *twice*, once before adding it to the blockstore and once after because bitswap is special).

**Comment by Stebalien** [comment]
As a matter of fact, we had a race condition where we could end up returning a block to the user while bitswap was closing and never record the block in the blockstore.

**Comment by Stebalien** [comment]
As a matter of fact, we had a race condition where we could end up returning a block to the user while bitswap was closing and never record the block in the blockstore.
