### ISSUE TITLE
Is ipfs diag net not longer supported?

### ISSUE THREAD

**Issue by alphaCTzo7G** [ipfs/go-ipfs#4064]
#### Description:

I noticed that ipfs diag net is supposed to recursively show the network on its usage, but it doesn't show up on my system, no manual, no help. So I am guessing its been removed?

**Comment by whyrusleeping** [comment]
Correct, it was a debug command used to get a view of the network as we were developing it. It was a DoS vector as it caused a recursive query to be sent through the entire system, and we decided that the danger it posed to the network was greater than the benefit it provided for debugging.

**Comment by Kubuxu** [comment]
I also responded here: https://github.com/ipfs/examples/issues/82

Let's track updating docs here.

**Comment by alphaCTzo7G** [comment]
Ok.. thanks for the info.. will track docs in the other thread.. and do PRs..
