### ISSUE TITLE
Pubsub is not working in windows

### ISSUE THREAD

**Issue by mariosk** [ipfs/go-ipfs#4068]
#### Version information:
$ ipfs version --all
go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/windows
Golang version: go1.8.3

#### Description: Steps to reproduce the issue in windows only (open 3 different terminals):
1. ipfs daemon --enable-pubsub-experiment
2. ipfs pubsub sub mariosk
3. ipfs pubsub pub mariosk test

Terminal number 2 should dump message "test". No message is shown, until I shutdown the daemon through Ctrl-C.

**Comment by Kubuxu** [comment]
It might be just a problem with flushing the stdout. Could you try listening using js-ipfs-api or manually using HTTP?

**Comment by mariosk** [comment]
Just used manually HTTP and I still get nothing:

**Comment by diasdavid** [comment]
Could this have been solved with https://github.com/ipfs/go-ipfs-api/pull/63#issuecomment-345971096 ?

**Comment by wehriam** [comment]
Any updates on this issue?

**Comment by djdv** [comment]
@wehriam 
I've heard reports of this from a few users for a while now but have never been able to reproduce it on any of my machines or VMs under any combination (for example even non-local non-windows published messages show up for me on a Windows host, and vice-versa).

This will require some investigation.

This is an old screenshot of mine but I'm sure pubsub was working for me prior to this revision as well.
![win-pubsub](https://user-images.githubusercontent.com/13862850/39607953-10c2bc3a-4f0c-11e8-9139-de95371d449d.png)

Here is one from my current build
![win-pubsub 2018](https://user-images.githubusercontent.com/13862850/39608039-b393918c-4f0c-11e8-8337-77e73ec8d75a.png)

**Comment by wehriam** [comment]
Let me know if there’s any way I can assist.

**Comment by djdv** [comment]
I suppose what we need, is to find some common ground between machines that are experiencing this problem. Without a reproducible test case, this is hard to diagnose.
So far I've had success on Windows 7 and Windows 10, both on real hardware and virtual (VMware). Under different consoles (Win32, mintty, and ConEmu) as well as under different shells (cmd.exe, Powershell, MSYS bash).

@mariosk, @wehriam 
Can you tell me a little more about the environments you're having trouble with? Any details that may be particular to your setups, or special tools that are used that may be related (like a different console program, shell, etc.).
