### ISSUE TITLE
ipfs shutdown errors out on Windows

### ISSUE THREAD

**Issue by kenshyx** [ipfs/go-ipfs#4078]
#### Version information: 
```
go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/windows
Golang version: go1.8.3
```
#### Description:
On my windows machine when I'm calling `shutdown` command I always get this Error: `"Command failed: "go-ipfs\ipfs.exe" shutdown\nError: Post http://127.0.0.1:5001/api/v0/shutdown?encoding=json&stream-channels=true: read tcp 127.0.0.1:51873->127.0.0.1:5001: wsarecv: An existing connection was forcibly closed by the remote host.\n"`. 
On linux is working as expected.

**Comment by Kubuxu** [comment]
On linux it also sometimes doesn't work. What we probably have to do is shutdown with some delay, at least after the API socket is closed.

**Comment by richardschneider** [comment]
I'm get an ECONNRESET when calling `/api/v0/shutdown` the HTTP route.  It should return 200, then do the shutdown logic.

**Comment by Stebalien** [comment]
Duplicate: https://github.com/ipfs/go-ipfs/issues/4055
