### ISSUE TITLE
Partial Read / Seeking without downloading the complete file

### ISSUE THREAD

**Issue by NateWickstrom** [ipfs/go-ipfs#4085]
#### Description:

I'm working on a media player app (on Android) that uses IPFS to play remote music and video files.  It has the go-ipfs daemon running in the background and interacts with it via the http interface (http://127.0.0.1:5001/api/v0).  However, the **/get** command downloads the entire file before the stream is accessible, which isn't ideal since that can take 10s of seconds even for small files;  The **/cat** command only returns streams that start from the beginning of files, i.e. you can't seek the stream, but it can be opened quicker (in a few seconds) - i assume this is because, unlike **get**, the entire file isn't downloaded before it can be opened; And the **/files/read** command only works on local files, so this is a non-starter.

First of all, my assumptions are correct, right?  With go-ipfs you can't open a file from the middle, until it's completely downloaded.  I spent a few hours digging around the specs, code and open issues and couldn't find any specific mention of the feature being supported (yet?) so figured opening an issue was the next step.  I can post some example code, if needed...

Second, if this feature _is_ missing, what are some thoughts on its feasibility and implementation?

**Comment by whyrusleeping** [comment]
Hey @NateWickstrom! Sorry for the long delay in responding. Accessing files through the gateway (127.0.0.1:8080/ipfs/<hash>) allows you to stream and seek, it supports the range headers required for streaming via http.

Currently, you cant seek with cat, but this is something we're planning on adding fairly soon.

As for `files/read`, files arent necessarily local, just referenced by the files api. You can do `ipfs files cp /ipfs/<hash> /foo` and it will put your file into the files tree without downloading it entirely. (this is super useful for interacting with very large directories of things).

**Comment by negamaxi** [comment]
@whyrusleeping any updates on cat seeking?

**Comment by whyrusleeping** [comment]
@negamaxi we just merged a `--offset` flag for `ipfs cat`. Does that work for what you need?
