### ISSUE TITLE
Can't switch planets on webui's "Connections" page

### ISSUE THREAD

**Issue by elitak** [ipfs/go-ipfs#4087]
#### Version information:
go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/linux
Golang version: go1.8.3
#### Description:
The visualization is nice, but I can only select Earth on the Connections page of the webui. I would like also to be able to see my connections to Luna, Mars, various objects in the asteroid belt, artificial satellites, etc.

**Comment by Kubuxu** [comment]
Please report this issue at webui's tracker: https://github.com/ipfs/webui/

**Comment by TheAlgo** [comment]
are u mad?
