### ISSUE TITLE
Add pinning support for object.put

### ISSUE THREAD

**Issue by mitar** [ipfs/go-ipfs#4092]
#### Version information:

```
go-ipfs version: 0.4.6-
Repo version: 5
System version: amd64/darwin
Golang version: go1.8
```

#### Description:

Followup from https://github.com/ipfs/js-ipfs-api/issues/532

When calling object.put, it would be great if I could specify an option that the object should also be pinned. Currently it seems I have to do two calls. But I think it is pretty common that you want objects you created to be pinned on your instance of IPFS.

**Comment by magik6k** [comment]
You should be able to use `ipfs dag put` (which has --pin option) as a workaround for now.
