### ISSUE TITLE
Add a WebSockets listener to the default config

### ISSUE THREAD

**Issue by daviddias** [ipfs/go-ipfs#4093]
It reduces one config step to new users.

**Comment by Kubuxu** [comment]
It won't work by default either way because it is not `wss` it is `ws`.

**Comment by diasdavid** [comment]
@Kubuxu "It won't work" if the user is dialing from a webpage that was loaded behind https. It will work in:

- localhost
- IP
- any http page

It will reduce one config step.

**Comment by whyrusleeping** [comment]
Maybe we can just add an init profile with websockets enabled by default.

**Comment by lgierth** [comment]
A /ws listener by default would help integrating with in-browser local discovery through FlyWeb -- the details around https need to be figured out though (whether it's needed, etc.)

**Comment by alvin-reyes** [comment]
Did we have any updates on this? Any follow thru if this was implemented? Thanks.

**Comment by Stebalien** [comment]
Once we fix https://github.com/libp2p/go-ws-transport/issues/21, I think we should be good to go.

**Comment by magik6k** [comment]
PR in go-ipfs-config - https://github.com/ipfs/go-ipfs-config/pull/24

Closing this issue as there is also https://github.com/ipfs/go-ipfs/issues/5251 which tracks this too
