### ISSUE TITLE
"file already closed" error during add in Go 1.9

### ISSUE THREAD

**Issue by djdv** [ipfs/go-ipfs#4097]
#### Version information:
go-ipfs version: 0.4.11-dev-181dd0061
Repo version: 5
System version: amd64/windows
Golang version: devel +835dfef939 Wed Jul 26 13:29:59 2017 +0000

#### Type:
Bug | Upstream bug?

#### Severity:
Medium-High
#### Description:
The contents of this directory don't seem to add properly on Windows, the same file gives an "already closed" error every attempt. Each file in the set can be added without issue on its own, but not every file at once.
`/ipfs/zdj7WhLoxPJPKibsr9q7uSeGZdkqVfV4b8xguCZa8vbH6Rcpa`
The hash was generated from the same data on FreeBSD. On Windows that hash can be retrieved with `ipfs get` without issue.
For reference I've tried this with Go versions ~~1.8~~ (Edit: just kidding, I accidentally tested 1.9 twice) up to the listed master above. I'm not sure what the cause is or where in the code path it's triggering this.
![already closed add issue](https://user-images.githubusercontent.com/13862850/28687499-96e4188e-72dc-11e7-9432-828c21114e29.png)

**Comment by djdv** [comment]
Update: I made a mistake during my second round of testing. This problem does NOT happen in go 1.8.3, the earliest I encountered this was in Go 1.9beta1, it remains an issue in the listed master above(835dfef939). When I tested again yesterday I must have mixed up my environment and built go-ipfs with the Go tip build twice instead of with 1.8.3, oops.

This could be an upstream issue, but I'm not sure. It should be noted that Go 1.9 is in the RC stage right now.

Here's the original screenshot from June ‎25th, 2017 showcasing the go1.9beta1 build, it's the same result.
![1 9 issue](https://user-images.githubusercontent.com/13862850/28719212-125e599e-7377-11e7-98c0-ee364b078ac9.png)

**Comment by Kubuxu** [comment]
It is new thing in Go 1.9 it will require fixing: https://github.com/golang/go/commit/e3d7ec006f25385972c89f771d5d577adce3f024

**Comment by magik6k** [comment]
Managed to reproduce on Linux:
* `go get golang.org/x/build/version/go1.9rc2`
* `go1.9rc2 download`
* Patch `mk/golang.mk` with:
```diff
diff --git a/mk/golang.mk b/mk/golang.mk
index 75490f176..ed7128707 100644
--- a/mk/golang.mk
+++ b/mk/golang.mk
@@ -19,7 +19,7 @@ go-tags=$(if $(GOTAGS), -tags="$(call join-with,$(space),$(GOTAGS))")
 go-flags-with-tags=$(GOFLAGS)$(go-tags)
 
 define go-build
-go build -i $(go-flags-with-tags) -o "$@" "$(call go-pkg-name,$<)"
+go1.9rc2 build -a -i $(go-flags-with-tags) -o "$@" "$(call go-pkg-name,$<)"
 endef
 
 test_go_short: GOTFLAGS += -test.short
```
* `make build install`
* run daemon, then add -r in go-ipfs root
