### ISSUE TITLE
Disable mdns for most sharness tests

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4098]
We should disable mdns for sharness tests by default and re-enable it only when necessary. Otherwise, our test nodes may end up talking to non test nodes.

**Comment by Stebalien** [comment]
cc @vyzo

**Comment by lgierth** [comment]
Can possibly also disable the port mapping and gateway discovery stuff, to save a bit more time on startup.

Makes for a good `init` profile :)

**Comment by Kubuxu** [comment]
There is already `test` init profile https://github.com/ipfs/go-ipfs/blob/master/repo/config/profile.go#L31

**Comment by magik6k** [comment]
it isn't - https://github.com/ipfs/go-ipfs/blob/master/test/sharness/lib/test-lib.sh#L144, easy fix though. IPTB tweaks config by itself

**Comment by Stebalien** [comment]
IPTB already seems to manage configs so mixing in yet another config management system may not be the best idea.

**Comment by Stebalien** [comment]
Scratch that, this may work.

**Comment by Stebalien** [comment]
So, I've filed an issue for changing IPTB to use profiles but left that for another time: https://github.com/whyrusleeping/iptb/issues/35

The fix for this bug is here: https://github.com/ipfs/go-ipfs/pull/4103
