### ISSUE TITLE
ipfs peers swarm shouldn't print connections.

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4104]
#### Type:

Enhancement (and kind of a bug)

#### Severity:

Very Low

#### Description:

`ipfs swarm peers` currently prints out each connection instead of each peer. It really should be printing  peer IDs (with the connections optionally listed below). That is, I'd expect:

```
/ipfs/QmId
    /ip4/192.168.1.32/tcp/1234
    /ipfs/QmIdOther/p2p-route
...
```

**Comment by whyrusleeping** [comment]
Note: this will break the api, some discussion around that will be necessary.

**Comment by vyzo** [comment]
Some tests will break or become harder to write as well.

**Comment by Kubuxu** [comment]
I very frequently do: `ipfs swarm peers | grep $peerID` and pass it to `ipfs swarm connect` somewhere else.

**Comment by Stebalien** [comment]
> Thinking about it, it will break with Circuit Relay.

No, that should still work (you'll just connect through the relay).

So... do we have any way to rename commands while retaining backwards compatibility (i.e., undocumented compatibility aliases). Given the discussion here, this should really be called `ipfs swarm conns`.

Alternatively, we could just document this in the command's help text.

**Comment by vyzo** [comment]
We should definitely keep a command with the old behaviour around, it will make our life easier for tests.
Plus it's useful, I agree with @kubuxu for the connect use case.

**Comment by Stebalien** [comment]
Replacement (so I can update the actual issue title/body without making this whole conversation make no sense): #4196
