### ISSUE TITLE
Outdated Example

### ISSUE THREAD

**Issue by wjh** [ipfs/go-ipfs#4107]
I'm really sorry if this is on the wrong issue tracker, but it *is* in relation to go-ipfs.

Anyway, I was following the example [here](https://ipfs.io/ipfs/QmNZiPk974vDsPmQii3YbrMKfi12KTSNM7XMiYyiea4VYZ/example#/ipfs/QmP8WUPq2braGQ8iZjJ6w9di6mzgoTWyRLayrMRjjDoyGr/api/service/readme.md), and it seems to be out of date.

I get errors when trying to use corenet, as it no longer exists - I checked the code here, which obviously confirmed this.

I'm well aware that IPFS is not yet stable, but I was wondering if someone could point me towards a way to fix this code? 

Thanks.

**Comment by magik6k** [comment]
This api was replaced by https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#ipfs-p2p. In it's current form it may not cover all use cases, If you have any feedback on it, comment on https://github.com/ipfs/go-ipfs/issues/3994

**Comment by wjh** [comment]
Ahhh I see, thank you.
