### ISSUE TITLE
add cmd and coreunix.Add() produce different hashes

### ISSUE THREAD

**Issue by cpacia** [ipfs/go-ipfs#4118]
Looks like coreunix.add only uses v0 and I need it to use v1. 

My attempts don't seem to be working right. 

I've added:
```
// AddWithContext does the same as Add, but with a custom context.
func AddWithContext(ctx context.Context, n *core.IpfsNode, r io.Reader) (string, error) {
	defer n.Blockstore.PinLock().Unlock()

	prefix, err := dag.PrefixForCidVersion(1)
	if err != nil {
		return "", err
	}
	prefix.MhType = mh.SHA2_256
	prefix.MhLength = -1

	fileAdder, err := NewAdder(n.Context(), n.Pinning, n.Blockstore, n.DAG)
	if err != nil {
		return "", err
	}
	fileAdder.Prefix = &prefix
	fileAdder.RawLeaves = true

	node, err := fileAdder.add(r)
	if err != nil {
		return "", err
	}

	return node.Cid().String(), nil
}
```
But it's returning a different cid then what is returned by the add command with --cid-version 1.

Any idea what the difference is?

**Comment by cpacia** [comment]
Update. When I read out the bytes it looks like the `add --cid-version 1` appends a carriage return (0x0A) to the data where coreunix.Add() does not thus resulting in a different hash. Not sure where this is happening.

**Comment by kevina** [comment]
@cpacia that's odd, if that is really the case I am surprised it has gone unnoticed.  What does `ipfs version --all` show you, also can you give an example of some sample data you added and how you knew the '0x0A' was added.

**Comment by cpacia** [comment]
I think the issue is when a file is read from disk `0x0A` is appended, but if the same bytes are passed directly from memory to coreunix.add() then it's missing the `0x0A` and calculates a different hash.

**Comment by kevina** [comment]
@cpacia something like that will be difficult to go unnoticed, can you please produce steps to reproduce the problem and the output of `ipfs version --all`

**Comment by cpacia** [comment]
im on 0.4.10
steps to repeat should be create a file ... `hello.txt` with value of `hello`.
`ipfs add hello.txt`
> QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN

then 
```
br := bytes.NewReader([]byte("hello"))
fmt.Println(coreunix.Add(nd, br))
```
> QmWfVY9y3xjsixTgbd9AorQxH7VtMpzfx2HaWtsoUYecaX

I'm going to change the title because this is not an issue with CIDv1 (although it would be nice if coreunix handled that).

**Comment by kevina** [comment]
@cpacia this could be os specific could you please provide the full output of `ipfs version --all`.

**Comment by kevina** [comment]
@cpacia many text editors will automatically add a newline to the file so will something like `echo hello.txt`.  You can check this by using something like `hexdump -C hello.txt`

**Comment by kevina** [comment]
For example:
```
$ echo hello > hello.txt
$ hexdump -C hello.txt
00000000  68 65 6c 6c 6f 0a                                 |hello.|
00000006
$ ipfs add hello.txt
added QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN hello.txt
```
To avoid the newline you can use `echo -n`:
```
$ echo -n hello > hello.txt
$ hexdump -C hello.txt
00000000  68 65 6c 6c 6f                                    |hello|
00000005
$ ipfs add hello.txt
added QmWfVY9y3xjsixTgbd9AorQxH7VtMpzfx2HaWtsoUYecaX hello.txt
```

**Comment by cpacia** [comment]
```
go-ipfs version: 0.4.10-4679f80
Repo version: 5
System version: amd64/linux
Golang version: go1.8.1
```
So this isn't per se an editor issue. I ran into it because I created a file using `os.Create()`, wrote some bytes to the file, then called `ipfs add`, then send the byte I still had in memory to another machine when called `coreunix.add()` and it produced two different hashes. 

If this is the expected behavior then I suppose I need discard the bytes from memory and read them from disk before sending to the remote machine.

**Comment by lgierth** [comment]
Definitely not the expected behaviour -- I think kevina is just trying to rule out options as to where that carriage-return might be coming from.

I think it's worth having a look at the `coreunix.Adder` in both cases. Just insert some fmt.printf in `coreunix.AddWithContext` and somewhere in the `add` command.

**Comment by kevina** [comment]
I can not reproduce this.  When I add a 5 byte file using the command `ipfs add hello.txt` containing just the string `hello`  (with no newline) I get the expected hash of `QmWfVY9y3xjsixTgbd9AorQxH7VtMpzfx2HaWtsoUYecaX`.

@cpacia please double check that the file you added with `ipfs add` is exactly 5 bytes and does not already contain the newline.  Also can I see the full output of `hexdump -C hello.txt` and `ipfs add hello.txt`.

**Comment by cpacia** [comment]
Can't seem to replicate now that I switch back to working with cidv0. :/

Maybe the issue was just related to my original question about adding cidv1 through coreunix.. which is where I'm getting two different hash (though not sure right now if it's its the carriage return doing it or not).

**Comment by kevina** [comment]
@cpacia that code looks right.  What is the exact contents of the file you added and what is the hash of the code above and the has when used from the command line.

**Comment by cpacia** [comment]
Well I think I got it working. Looks like this is another one of those that I spend all night trying to debug then it just starts working lol. 

I'm honestly not sure what the issue was. I think there might have been some issues with how I was adding files when using cidv1 and my attempts to debug it sent me barking up the wrong tree. 

Going to close. Thanks for helping.
