### ISSUE TITLE
`ipfs swarm connect` with alternate address

### ISSUE THREAD

**Issue by briantigerchow** [ipfs/go-ipfs#412]
ipfs swarm connect works as intended the first time it is executed with valid args:

```
go-ipfs (master) λ. ipfs swarm connect /ip4/104.236.176.52/tcp/4001/QmaQujMiKngVVV6nRQsGRU1HVKriU7aGzUzL695zG6nqeW
connect QmaQujMiKngVVV6nRQsGRU1HVKriU7aGzUzL695zG6nqeW success
```
woohoo!

Now, let's connect via udp over a port that we're pretty sure isn't exposed.

```
go-ipfs (master) λ. ipfs swarm connect /ip4/104.236.176.52/udp/4312312/QmaQujMiKngVVV6nRQsGRU1HVKriU7aGzUzL695zG6nqeW
connect QmaQujMiKngVVV6nRQsGRU1HVKriU7aGzUzL695zG6nqeW success
```
What's the desired behavior in this case?

a) command merely ensures that a connection exists between local node and the peer
- [ ] b) command ensures that there's a connection over the specified protocol tcp/udp

**Comment by jbenet** [comment]
No longer panics, but the errors are unfriendly:

```
> ipfs swarm connect /ip4/1.2.3.4
Error: invalid peer address: protocol requires address, none given: ip4

> ipfs swarm connect /ip4/1.2.3.4/
Error: multihash too short. must be > 3 bytes
```

**Comment by jbenet** [comment]
Also to correct my statement above: 
> that's not even a valid multiaddr (udp port) . it doesnt error out on parsing?

Sorry, `/udp/<port>` is totally a valid multiaddr. i mistook udp for utp. `/utp/<port>` is wrong, it would be: `/udp/<port>/utp`
