### ISSUE TITLE
Invalid JSON Output Produced When Adding A Fie with wrap-with-directory Enabled

### ISSUE THREAD

**Issue by saden1** [ipfs/go-ipfs#4120]
#### Version information:
go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/linux
Golang version: go1.8.3

#### Type:
Bug

#### Severity:
High - The main functionality of the application does not work, API breakage, repo format breakage, etc.

#### Description:
Calling `/api/v0/add?wrap-with-directory=true` with a payload produces:
```json
{"Name":"testfile.txt","Hash":"QmTmGS2h4NTDrPWbo7n9TAMKv4USohQZkyijEqLUcLPX8t"}
{"Name":"","Hash":"QmcUNQJLEiSEiR355GSHQ18USvkVWS1H51tkn2MkRwPF5Y"}
```

This output can not be parsed by [older generation](https://tools.ietf.org/html/rfc7159#section-2) JSON parsers (Jackson). Would it be possible to add a comma after each object and produce [RFC4627](https://tools.ietf.org/html/rfc4627) compatible output?

**Comment by Kubuxu** [comment]
It is NDJSON format (http://ndjson.org/). It is supposed to be split on `\n`/ Please read NDJSON spec for reasons for that and more details.l

**Comment by saden1** [comment]
Ah. I wasn't aware of DNJSON. From the looks of it the format isn't widely adopted. It would be nice to be able to use existing tools to parse the JSON format produced by IPFS.

**Comment by magik6k** [comment]
Changing this now would mean breaking pretty much all http API compatibility.

With some languages (including Java streams library) you should be able to just do `input.split("\n").map(line -> JSON.parse(line))` to get a valid array of results.

**Comment by Kubuxu** [comment]
The point of NDJSON is to support streaming responses, you can treat each line like an event, their order is also not determined so you should check if the message you got in this line is one you are looking for.

**Comment by saden1** [comment]
@Kubuxu, 

Is the response sent back incrementally or all once? How do I know when the stream ends and to stop reading?

**Comment by Kubuxu** [comment]
It is sent incrementally, the HTTP stream will be closed or the multipart response of it will be finished (there is method for it in HTTP) when the response will be sent in full.

Simplest example of such command is `ipfs ping` or `ipfs dht findpeer`
Try it out for yourself `ipfs --enc json dht findpeer QmZatNPNW8DnpMRgSuUJjmzc6nETJi21c2quikh4jbmPKk`

**Comment by whyrusleeping** [comment]
closing, feel free to reopen if there are further questions
