### ISSUE TITLE
How can i let my wordpress work on ipfs?

### ISSUE THREAD

**Issue by vritxii** [ipfs/go-ipfs#4130]
#### Description:
After i added a website source code to ipfs , it doesn't work anyway, how can it work like this website --- https://gateway.ipfs.io/ipfs/QmeYYwD4y4DgVVdAzhT7wW5vrvmbKPQj8wcV2pAzjbj886/

**Comment by Voker57** [comment]
IPFS can't run your php, all it does is distribute static files.

**Comment by lgierth** [comment]
@vritxii You can try one of the Wordpress plugins that export your site as static HTML, then add the resulting directory to IPFS.

If you're up for a bit of hacking, it would be awesome to write a Wordpress plugin that provides "publish to IPFS" functionality right within Wordpress.

**Comment by jlubbers08** [comment]
So I wrote a plugin that does exactly that. The site generates in the background and then is updated with every page save. It also makes the IPFS version of the site like a time machine.

https://www.jefflubbers.com/ipfs-wordpress/

**Comment by lgierth** [comment]
@jlubbers08 oh this looks fantastic! Thank you!

**Comment by lgierth** [comment]
@jlubbers08 actually, would you like to post that to https://discuss.ipfs.io? I'm sure there's gonna be quite a few people interested in this wordpress plugin.

**Comment by jdbohrman** [comment]
Would docer containers help this at all? @jlubbers08

**Comment by jlubbers08** [comment]
@jdbohrman  I'm not sure I quite follow. I mean I run a few nodes of IPFS in Docker containers one for production and the others for testing and playing around with, but what problem would docker containers fix in your mind? 

Just a community note too I've mode the code to be opensource and am working on getting it up to WordPress standards if anyone wants to help the repo is `https://github.com/jlubbers08/IPFS-Bridge`
