### ISSUE TITLE
Concurrency-related crashes from Prometheus client

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#4132]
#### Description:

Since I deployed v0.4.11-pre to the gateways, I see regular crashes (~1/h) out of the Prometheus client lib (client_golang). Note that these crashes might have occured earlier too, just less frequently since the gateways way running on a lot less potent machines until yesterday.

These are supposedly fixed in client_golang's master, but updating it is non-trivial since it has seen structural refactorings and is now multiple packages that all need to be gxed.

```
fatal error: concurrent map iteration and map write

goroutine 140025520 [running]:
runtime.throw(0x561c52fef158, 0x26)
  /usr/lib/go/src/runtime/panic.go:596 +0x97 fp=0xc43e745e20 sp=0xc43e745e00
runtime.mapiternext(0xc43e745f58)
  /usr/lib/go/src/runtime/hashmap.go:737 +0x7f0 fp=0xc43e745ed0 sp=0xc43e745e20
runtime.mapiterinit(0x561c536bb180, 0xc431686840, 0xc43e745f58)
  /usr/lib/go/src/runtime/hashmap.go:727 +0x2b5 fp=0xc43e745f28 sp=0xc43e745ed0
gx/ipfs/QmX3QZ5jHEPidwUrymXV1iSCSUhdGxj15sm2gP4jKMef7B/client_golang/prometheus.computeApproximateRequestSize(0xc44a077a00, 0xc4256773e0, 0x13)
  /go/src/gx/ipfs/QmX3QZ5jHEPidwUrymXV1iSCSUhdGxj15sm2gP4jKMef7B/client_golang/prometheus/http.go:303 +0x8d fp=0xc43e745fc8 sp=0xc43e745f28
runtime.goexit()
  /usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc43e745fd0 sp=0xc43e745fc8
created by gx/ipfs/QmX3QZ5jHEPidwUrymXV1iSCSUhdGxj15sm2gP4jKMef7B/client_golang/prometheus.InstrumentHandlerFuncWithOpts.func1
  /go/src/gx/ipfs/QmX3QZ5jHEPidwUrymXV1iSCSUhdGxj15sm2gP4jKMef7B/client_golang/prometheus/http.go:275 +0x14f
```

**Comment by lgierth** [comment]
Possibly useful info: https://github.com/prometheus/client_golang/issues/189 && https://github.com/prometheus/client_golang/pull/311

**Comment by Stebalien** [comment]
@lgierth I've updated prometheus. Can you check to see if this has been fixed?
