### ISSUE TITLE
ipfs name resolve CLI cannot resolve DNS TXT /ipns dnslink

### ISSUE THREAD

**Issue by pors** [ipfs/go-ipfs#4167]
#### Version information:
go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/darwin
Golang version: go1.8.3

#### Type:
Bug

#### Severity:
Medium 

#### Description:
I created a DNS TXT record as follows:

```
decentralized.blog.	900	IN	TXT	"dnslink=/ipns/QmRf4ERGvYpVo6HRa2VueZT8pWi8YvyLS3rW6ad2y83tdN"
```

It does work when trying to access it through the default gateway: https://ipfs.io/ipns/decentralized.blog

But this command can not resolve:

```
$ ipfs name resolve decentralized.blog
Error: Could not resolve name (recursion limit exceeded).
```

**Comment by Kubuxu** [comment]
You can use `ipfs name resolve -r` it will work then. Gateway uses it buy default.

@lgierth what do you think about changing this behavior? Having `--recursive` true by default so it is consistent with the gateway.

**Comment by pors** [comment]
Ah cool, thanks @Kubuxu

**Comment by whyrusleeping** [comment]
Yeah, lets go with recursive being the default here. Its really what people expect.
