### ISSUE TITLE
Configurable DNS Resolver

### ISSUE THREAD

**Issue by cpacia** [ipfs/go-ipfs#4170]
From my reading of namesys.go it looks like it will attempt a DNS resolution for every IPNS query. This was likely a source of IP leaks for me when running over Tor. 

I patched my code to allow a custom DNS Resolver to be passed into `NewNameSystem` to get around this. It might be worth considering doing the same here upstream.

**Comment by whyrusleeping** [comment]
@cpacia do you mind submitting a PR with those changes?

**Comment by cpacia** [comment]
Sure though I'm not sure if you would want it done the same way. Take a look at the diff https://github.com/OpenBazaar/go-ipfs/commit/3e6340cbef64ff39bec0299fb05ae49c6dff7e7f

**Comment by whyrusleeping** [comment]
That changeset looks pretty reasonable to me, I might look at wiring it through differently though. cc  @Kubuxu @magik6k

**Comment by magik6k** [comment]
It could be made configurable via config with some API to allow plugging custom resolvers, though that might encourage adding too many custom resolves.

Another idea is to make something that would be somewhere between BuildCfg and Node, so we could avoid passing things like that (DNSResolver) through function arguments. Should be an easy refactor.

**Comment by cpacia** [comment]
duplicate of #5945 which is more up to date
