### ISSUE TITLE
Don't decode URI encode slashes

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4178]
#### Version information:

> go-ipfs version: 0.4.11-dev-48476b292
Repo version: 5
System version: amd64/linux
Golang version: go1.8.3

#### Type:

Bug

#### Severity:

Low

#### Description:

We're currently decoding `%2F` to `/` in our paths *before* splitting path segments in our gateway. This means that we're accepting, e.g.:

```
http://127.0.0.1:8080/ipfs%2FQmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv%2Freadme
```

This can cause surprising behavior and allow buggy code that shouldn't work to work. Also, funky URI escape decoding has been known to cause security problems in the past (although I think we're safe in this particular case).

**Comment by lgierth** [comment]
Good catch

**Comment by reinerRubin** [comment]
Do the handlers even need processed paths? I have looked through 
>"core/corehttp/gateway_handler.go"
and have not found the cases when "s/URL.Path/URL.EscapedPath()/" can break anything.

**Comment by Stebalien** [comment]
Thinking about this a bit, I'm not sure if we _want_ to fix this. Yeah, it's a bit funky but we allow url-escaping everything _else_ in these paths. Thoughts?

**Comment by reinerRubin** [comment]
I have also thought about this. But everything else is not interpreted as a path segment. On the other hand the fix seems to be awkward and if there are not any real benefits or security risks it is not worth it.

**Comment by Stebalien** [comment]
I'd say it's not worth it. I'll leave this open for a few days to see if anyone wants to chime in.

**Comment by the-superpirate** [comment]
Folks, I'm stuck with it. Is there any way to workaroud it?
I have a filename in directory named "blabla%2Fblabla" and it cannot be opened through gateway because %2F is decoded to slash beforehand.

**Comment by Jorropo** [comment]
@the-superpirate `blabla%252Fblabla` ?
