### ISSUE TITLE
Wrong --local/-L flag documentation

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#4182]
#### Description:

`ipfs --help` defines `--local` as "Run the command locally, instead of using the daemon". This is completely inaccurate. The flag is used in only two places:

- `ipfs add --local` uses an Offline Exchange for adding files, skipping the immediate publication of provider records.
- `ipfs name resolve --local` uses an Offline Routing Resolver, avoiding IPNS queries to the DHT.

The flag should be removed from the root command, and instead added to these two commands.

There's a backward compatiblity angle to consider, where tools could possibly be calling `ipfs --local add <file>` instead of the better `ipfs add --local <file>`.

**Comment by Stebalien** [comment]
This command should also be extended to work elsewhere (e.g., `ipfs block stat`). Making this option "just work" everywhere is a pretty decent motivation for https://github.com/ipfs/go-ipfs/issues/4009.

**Comment by Stebalien** [comment]
Fixed. This is now `--offline` everywhere and behaves as expected.
