### ISSUE TITLE
ipfs cat by peerId Error: merkledag: not found

### ISSUE THREAD

**Issue by shroomist** [ipfs/go-ipfs#4187]
#### Version information:
go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/darwin
Golang version: go1.8.3

#### Type:
High

#### Description:

Osx first launch `ipfs init` returns that config is already created
`#grep PeerID ~/.ipfs/config "PeerID": "QmW8DKrYwdatoKxnYt3jK9SKMfurAfQ9m8XGVhhaczF61z", #ipfs cat /ipfs/QmW8DKrYwdatoKxnYt3jK9SKMfurAfQ9m8XGVhhaczF61z Error: merkledag: not found`

**Comment by Kubuxu** [comment]
You can't cat your PeerID, it is identifier of peer, not identifier of file.

**Comment by Stebalien** [comment]
For now... https://github.com/ipld/cid/issues/12 (well, it will never be a file but we should dogfood IPLD more).
