### ISSUE TITLE
No media mime type error

### ISSUE THREAD

**Issue by OstlerDev** [ipfs/go-ipfs#4198]
#### Version information:
go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/linux
Golang version: go1.8.3

#### Type: 
Bug

#### Severity: 
High

#### Description: 
After adding a file to IPFS and attempting to load it from the public gateway, the file starts to download but will only download up to 1mb before hanging indefinitely. The IPFS daemon server that I uploaded the content to outputs the error below constantly when I attempt to load the file from the public gateway. I have tested this with several files that have similar encoding, and they all seem to have the issue.

Link to affected hash: https://gateway.ipfs.io/ipfs/QmfJC7BgkKRL7y7gd9L9fG7V5SziEzo1ch1jtngrNv3n4E/

Link for original file: http://www.dvdloc8.com/clip.php?movieid=8419&clipid=2

Error in Terminal: 
```
02:27:40.909 ERROR commands/h: err: mime: no media type handler.go:285
02:27:41.913 ERROR commands/h: err: mime: no media type handler.go:285
02:27:42.917 ERROR commands/h: err: mime: no media type handler.go:285
02:27:43.922 ERROR commands/h: err: mime: no media type handler.go:285
02:27:44.925 ERROR commands/h: err: mime: no media type handler.go:285 
02:27:45.928 ERROR commands/h: err: mime: no media type handler.go:285
02:27:46.931 ERROR commands/h: err: mime: no media type handler.go:285
02:27:47.937 ERROR commands/h: err: mime: no media type handler.go:285
```

**Comment by OstlerDev** [comment]
The file seems accessible now, not sure what might have changed, but the initial error message might still be valid. I will see if there is a more reproducible way to cause this issue.

**Comment by Stebalien** [comment]
I'm not sure how this issue got so lost (well, >900 open issues probably had something to do with it) but, at this point, we've refactored the commands library (the likely culprit) twice so I'm going to close this as:

* A bug.
* A *likely* fixed bug that we won't be able to reproduce.
