### ISSUE TITLE
with go1.9, GOPATH check in makefile no longer required.

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4200]
we should probably move to requiring go1.9 and drop that check

**Comment by djdv** [comment]
At current we rely on `1.11.4` and `make` will build without GOPATH set. (it mimicks what Go would do)
https://github.com/ipfs/go-ipfs/blob/307d06b4651d93eb2cdd8f7bfd9f169bfcc9bd74/mk/golang.mk#L17-L18
