### ISSUE TITLE
add: Trickle overrides chunker

### ISSUE THREAD

**Issue by djdv** [ipfs/go-ipfs#4201]
#### Version information:
go-ipfs version: 0.4.11-dev-cbd13b611
Repo version: 6
System version: amd64/windows
Golang version: devel +812b34efae Mon Sep 4 00:07:33 2017 +0000

#### Type:
Bug?

#### Severity:
Low-Medium
#### Description:
I don't know if this is expected behaviour or not, maybe some kind of warning stating argument priority should be displayed if it is.

```
>ipfs add --pin=false -t hello.txt
QmVMJV7nBAKMvxfuTZEGpB8fg9oxAvhGzA3wWprKscJbzH hello.txt

>ipfs add --pin=false -s rabin hello.txt
QmcTkUnEKwnnodaCRSVFpFEJTMJNcFfU64cD6s3BxfbWvf hello.txt

>ipfs add --pin=false -s rabin -t hello.txt
QmVMJV7nBAKMvxfuTZEGpB8fg9oxAvhGzA3wWprKscJbzH hello.txt
```
P.S. this is my entry for the "best issue title" contest

**Comment by whyrusleeping** [comment]
> P.S. this is my entry for the "best issue title" contest

You've got some pretty heavy competition for that, good luck though.

This definitely looks like a bug.

**Comment by kevina** [comment]
Everything is working as intended.  The problem is your test file is too small.  For example if you tried added a small file with and without `-s rabin` (and without `-t`) you would get the same result:
```
echo 'Hello!' > hello.txt
$ ipfs add --pin=false hello.txt
added QmenmPhbFCbn2BGkGbNCjxFp5qdXnuhWL9Lqt6GjFq1NUK hello.txt
$ ipfs add --pin=false -s rabin hello.txt
added QmenmPhbFCbn2BGkGbNCjxFp5qdXnuhWL9Lqt6GjFq1NUK hello.txt
```
When a larger file is added I get different hashes when `-s rabin` is added with `-t`.
```
$ test/bin/random 1048576 > 1mbfile
$ ipfs add --pin=false -t 1mbfile 
added QmNaPVwnb1M28iVh54iL4HGheheewJCm9yrFix2ptJG19T 1mbfile
$ ipfs add --pin=false -t -s rabin 1mbfile 
added QmejfLpJTuCtMeFbaUH72Tj5DcRvauFFev43thyHjfpJnx 1mbfile
```

**Comment by djdv** [comment]
Thanks @kevina 
I probably should have thought of testing various sizes when chunking is involved. Oops! This popped out at me while testing something else.
