### ISSUE TITLE
http connection dies unexpectedly during add

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4203]
on latest master (cbd13b6115c1f8285b7a10443b56ebe290da0afd) i started a new ipfs daemon in offline mode and attempted to add all of ipfs dists. About 80% of the way in, both the client and the daemon got the same error:

daemon:
```
16:39:41.537 ERROR commands/h: err: read tcp4 127.0.0.1:5001->127.0.0.1:38034: use of closed network connection handler.go:285
```
client:
```
16:39:41.530 ERROR commands/h: read tcp 127.0.0.1:38034->127.0.0.1:5001: use of closed network connection client.go:247
```

This smells like a go bug or a kernel bug to me.

**Comment by whyrusleeping** [comment]
```
Error: read releases/ipfs-pack/v0.3.0/ipfs-pack_v0.3.0_darwin-amd64.tar.gz: input/output error
17:50:56.430  INFO   cmd/ipfs: Shutting down node... main.go:240
17:50:56.430 DEBUG       core: core is shutting down... core.go:504
17:50:56.430 DEBUG blockservi: blockservice is shutting down... blockservice.go:251
Command exited with non-zero status 1
7.01user 1.24system 0:08.86elapsed 93%CPU (0avgtext+0avgdata 244640maxresident)k
3697792inputs+14072outputs (5major+55452minor)pagefaults 0swaps
why@manwe ~/c/distributions> cat releases/ipfs-pack/v0.3.0/ipfs-pack_v0.3.0_darwin-amd64.tar.gz | shasum
cat: releases/ipfs-pack/v0.3.0/ipfs-pack_v0.3.0_darwin-amd64.tar.gz: Input/output error
3dd84601064b72bebe0321b2463716683e835c6c  -
```

Not actually http related it seems. Looks like we're just hiding errors. Plus my filesystem appears to be corrupted?

**Comment by whyrusleeping** [comment]
I'm pretty sure we've seen this before. Adding the file directly (with daemon running)  shows the error, its only when a large number of things are being added at once that the error is hidden.

@kevina I seem to remember you talking about this at some point.

**Comment by kevina** [comment]
@whyrusleeping do you mean #3855?

**Comment by whyrusleeping** [comment]
@kevina ah yes, exactly. Thanks!

**Comment by whyrusleeping** [comment]
closing as duplicate of #3855
