### ISSUE TITLE
sha3 hash functions unrecognised

### ISSUE THREAD

**Issue by alanshaw** [ipfs/go-ipfs#4207]
#### Version information:

go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/darwin
Golang version: go1.8.3

#### Description:

```sh
$ ipfs add ../test2.md --hash=sha3-224
Error: unrecognized hash function: sha3-224
$ ipfs add ../test2.md --hash=sha3
added zB7NbDcdPF25nBUAkzEtQx5wNeXzUvUdGGVieW7N85NwcpUDg2MBe7pActQU92PfGJWfZDq95Bsgz4GxTP13p8gzdbN5v test2.md
$ ipfs add ../test2.md --hash=sha3-256
Error: unrecognized hash function: sha3-256
$ ipfs add ../test2.md --hash=sha3-384
Error: unrecognized hash function: sha3-384
$ ipfs add ../test2.md --hash=sha3-512
Error: unrecognized hash function: sha3-512
```

**Comment by whyrusleeping** [comment]
Yeah, the full list of supported hashes is here: https://github.com/multiformats/go-multihash/blob/master/multihash.go#L87

We should probably start an effort to expand that list.

**Comment by whyrusleeping** [comment]
Oh wait, the hashes youre trying *are* in that list. And it even looks like they are here too: https://github.com/multiformats/go-multihash/blob/master/sum.go#L23

I wonder whats going on here

**Comment by kevina** [comment]
I'll look into this one.  Hopefully tonight, if not then tomorrow.

**Comment by kevina** [comment]
This works on master.

It looks like support for those where added on Apr 24, 2017 (https://github.com/multiformats/go-multihash/commits/master/multihash.go) and the dependency updated in cccc6a94a32d2b2f56b9234efb3e9e1a9fd0f390 around July-11.
