### ISSUE TITLE
shake hash functions unrecognised

### ISSUE THREAD

**Issue by alanshaw** [ipfs/go-ipfs#4208]
#### Version information:

go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/darwin
Golang version: go1.8.3

#### Description:

```sh
$ ipfs add ../test2.md --hash=shake-128
Error: unrecognized hash function: shake-128
$ ipfs add ../test2.md --hash=shake-256
Error: unrecognized hash function: shake-256
```

**Comment by whyrusleeping** [comment]
see my response to #4207

**Comment by kevina** [comment]
This works on master.  Again see #4207.
