### ISSUE TITLE
bitswap share function

### ISSUE THREAD

**Issue by briantigerchow** [ipfs/go-ipfs#421]
**context**
This issue is about modeling the bitswap function P(SEND) as a function of the debt ratio and total bandwidth between a pair of peers.

-- 

@jbenet I had started toying around with generalized logistic functions. Perhaps you'll find this a useful starting point:

![screenshot 2014-12-08 15 49 02](https://cloud.githubusercontent.com/assets/734339/5349957/ecbcb292-7ef2-11e4-9d32-a97732d84058.png)
https://www.dropbox.com/s/gnix3y3ho54ad1m/bitswap.nb?dl=0

**Comment by whyrusleeping** [comment]
closing, can be looked at later when we get to bitswap actually using a function for making block decisions
