### ISSUE TITLE
Support Unix Sockets

### ISSUE THREAD

**Issue by cbluth** [ipfs/go-ipfs#4218]
#### Version information:
```root@23b28683cdc7:/# ipfs version --all
go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/linux
Golang version: go1.8.3
root@23b28683cdc7:/#
```

#### Type:
Feature

#### Severity:
Low/Medium

#### Description:
Please consider supporting the option to bind the ipfs/http-gateway and/or the API to a unix socket instead of (or in addition to) a TCP socket.

**Comment by magik6k** [comment]
There is some discussion on unix sockets in https://github.com/ipfs/notes/issues/129. This is probably also blocked by https://github.com/ipfs/go-ipfs/pull/3856

**Comment by whyrusleeping** [comment]
cc @keks this is something we want to be able to do with the ipfs cmds lib

**Comment by keks** [comment]
Yes! That would be rad.

I think the best way would be to make a wire format that works directly on top of a reliable transport, so it doesn't matter whether we use unix domain sockets or e.g. websockets (which have been requested in the past).
I'm working on getting cmds1.0 out as soon as I can. Afterwards I'll tackle this one.

**Comment by kyledrake** [comment]
Not to add more work to everyone's plates, but unix socket support for go-ipfs would be great, and I would definitely use it in production.

**Comment by teran-mckinney** [comment]
Nice work!
