### ISSUE TITLE
need batch interface for `ipfs dag put`

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4234]
Playing around with the git ipld plugin and i'm thinking that it would be a lot faster if we were able to do batch puts of dag objects via the http api. This will also probably help out the go-ipld-eth plugin when ingesting lots of data.

**Comment by hermanjunge** [comment]
Yeah. Today, one of my workarounds today is doing 

```
find . -name "eth-state-trie-rlp-*" -exec sh -c "cat {} | ipfs dag put --input-enc raw --format eth-state-trie; echo" \;
```

**Comment by Kubuxu** [comment]
I know that @magik6k hit this too. Spawning so many processes was degrading perf. @magik6k did using plain HTTP was any better?

I also think this was discussed somewhere previously.

**Comment by Kubuxu** [comment]
The thing that was discussed previously was `block put` not `dag put`.

**Comment by Kubuxu** [comment]
I think with most of the use cases the batch operations will use the same `input-enc` and `format` so length prefixed  (8 bytes length prefix with fixed endianness) bytestream should suffice. It would be also quite easy to implement in client libraries (no need for encoding sub-lib).

What do you think?

**Comment by magik6k** [comment]
Sending batches can be done using `req.Files()`, as is done in `ipfs add`.
