### ISSUE TITLE
ipfs init --profile=badgerds, mmap value log error

### ISSUE THREAD

**Issue by leerspace** [ipfs/go-ipfs#4242]
#### Description: Initializing an ipfs repository using the badgerds profile doesn't work in 0.4.11-rc1 and results in a non-working repository. Given the error message about not having enough free space I moved the repository onto a 1TB drive but it still fails.

FWIW this worked in ipfs version 0.4.11-dev-c14a995.

Here's the output from `ipfs init --debug --profile=badgerds` on Windows:
```
ipfs init --debug --profile=badgerds
[0;37m15:43:06.504  INFO [0;34m  cmd/ipfs: [0mIPFS_PATH C:\Users\John\.ipfs [0;37mmain.go:301[0m
[0;37m15:43:06.504 [36mDEBUG [0;34m  cmd/ipfs: [0mcalling pre-command hooks... [0;37mmain.go:295[0m
[0;37m15:43:06.505 [36mDEBUG [0;34m      lock: [0mChecking lock [0;37mlock.go:32[0m
[0;37m15:43:06.505 [36mDEBUG [0;34m      lock: [0mFile doesn't exist: C:\Users\John\.ipfs/repo.lock [0;37mlock.go:34[0m
[0;37m15:43:06.506  INFO [0;34m  cmd/ipfs: [0mchecking if daemon is running... [0;37minit.go:66[0m
[0;37m15:43:06.506 [36mDEBUG [0;34m  cmd/ipfs: [0mexecuting command locally [0;37mmain.go:342[0m
initializing IPFS node at C:\Users\John\.ipfs
generating 2048-bit RSA keypair...done
peer identity: QmcSimR7CDQqGCAsYBokGxpt1YcExA5dtiJm6tK52sEs6p
Error: Unable to open value log: Unable to mmap value log file: Not enough storage is available to process this command.
```

**Comment by leerspace** [comment]
PR https://github.com/ipfs/go-ipfs/pull/4007

**Comment by whyrusleeping** [comment]
Hey @manishrjain, any idea here?

**Comment by manishrjain** [comment]
Ah.. yeah this is a known issue. We set the initial mmap size when writing a log file to uint32 max (4GB). And in Windows, this seems to cause issues. We'll fix it urgently.

https://github.com/dgraph-io/badger/issues/212

**Comment by leerspace** [comment]
From looking at the linked issue it sounds like this is suspected to be a Windows issue and I can confirm that I am getting this error on Windows 10. I also see the OP in the linked issue saying "this should not prevent Badger from working on a Windows machine with enough RAM", but the machine I'm getting this error on has 16 GB of RAM which seems like it should be more than enough.

**Comment by manishrjain** [comment]
We figured out what the issue was. Just pushed a fix, if you can try it out and confirm it.

https://github.com/dgraph-io/badger/issues/212

**Comment by leerspace** [comment]
@whyrusleeping does the badger dependency for IPFS need to be updated or something like that in order for new IPFS builds from master to get the fix? I just tried building and retesting and saw the error again.

**Comment by lgierth** [comment]
@leerspace yes, all dependencies are immutable, so the change needs to be bubbled up

**Comment by magik6k** [comment]
This was fixed with https://github.com/ipfs/go-ipfs/pull/4291

**Comment by Mikaela** [comment]
I am seeing this on Arch Linux ARM on Raspberry Pi B+:

```
nitializing IPFS node at /home/mikaela/.ipfs                                  
generating 2048-bit RSA keypair...done
peer identity: QmdEXRTSA9XJkyccbtmBBsDZYXvGNvx8EJ5ZpnqZcLwTs4                  
badger 2019/04/23 14:31:37 INFO: All 0 tables opened in 0s                     
Error: Mmap value log file. Path=/home/mikaela/.ipfs/badgerds/000000.vlog. Error=cannot allocate memory
┌┌(mikaela@tezagm)┌(174/pts/3)┌(02:31:04/23/19)┌-                              
└┌(%:~)┌- ipfs --version
ipfs version 0.4.19
```

I think in my case it's just out of memory as that isn't a very powerful device.

**Comment by manishrjain** [comment]
You can set value log to be served off disk instead of mmaping it.

**Comment by nampdn** [comment]
> You can set value log to be served off disk instead of mmaping it.

@manishrjain Could you please help me where to change this parameter in the `config` file? I'm facing the same issue

**Comment by Stebalien** [comment]
@nampdn You can't yet change this through the config. Could you file a [feature request](https://github.com/ipfs/go-ipfs/issues/new?labels%5B%5D=feature&template=feature.md)?

**Comment by jsimnz** [comment]
I just received this error this error as well
```
generating 2048-bit RSA keypair...done
peer identity: QmUT6JjNRuzuxGQRtHAax5LJdYbCEGabonJjfbFSQDT83p
Error: Mmap value log file. Path=/home/jsimnz/.ipfs/badgerds/000000.vlog. Error=exec format error
```

My machine has 32GB of memory, and only 10GB is used. Windows 10 using the Ubuntu subsystem. 

Thoughts?

**Comment by Stebalien** [comment]
That's a bug in the WSL: https://github.com/microsoft/WSL/issues/3451. We should probably make mmapping configurable (https://github.com/ipfs/go-ipfs/issues/6449) but WSL really needs to fix this.
