### ISSUE TITLE
Removing block does not clear the DHT table

### ISSUE THREAD

**Issue by redmouth** [ipfs/go-ipfs#4249]
After a block is unpinned and removed, local DHT still keep the block's key.  As designed?

**Comment by Stebalien** [comment]
I assume you mean that we don't cancel provider records (i.e., "I provide block X")? Yes, this is by design. Publishing provider records already creates a lot of spam (we're working on reducing this) so we just let them expire (at least for the moment).

**Comment by michaelavila** [comment]
Closing as question was adequately answered with nothing to fix or follow up on.
