### ISSUE TITLE
Interoperability between go-ipfs@0.4.11 and js-ipfs@0.26

### ISSUE THREAD

**Issue by daviddias** [ipfs/go-ipfs#4250]
@Stebalien reported during the last all hands that he has seen file transfer errors between latest go-ipfs and latest js-ipfs.

I've been unable to reproduce these locally. The only failing tests I see are due to a repo version update:

```
    repo
got file
      1) read repo: go -> js
Swarm listening on /ip4/127.0.0.1/tcp/4110/ws/ipfs/QmNnMBwPz4JBSXRnu8j4Q49y22pX93ihG7rYAmajjBkwsp
Swarm listening on /ip4/127.0.0.1/tcp/4009/ipfs/QmNnMBwPz4JBSXRnu8j4Q49y22pX93ihG7rYAmajjBkwsp
API is listening on: /ip4/127.0.0.1/tcp/5008
Gateway (readonly) is listening on: /ip4/127.0.0.1/tcp/9096
got file
      2) read repo: js -> go


  41 passing (47s)
  4 pending
  2 failing

  1) interop repo read repo: go -> js:
     Uncaught Error: version mismatch: expected v5, found v6
      at get (node_modules/ipfs-repo/src/version.js:57:27)
      at store.get (node_modules/ipfs-repo/src/version.js:31:9)
      at node_modules/graceful-fs/graceful-fs.js:78:16
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:504:3)

  2) interop repo read repo: js -> go:
     Error: Error: ipfs repo needs migration.

      at Object.done (node_modules/ipfsd-ctl/src/exec.js:23:27)
      at Stream.listeners.done.once (node_modules/ipfsd-ctl/src/exec.js:45:18)
      at Stream.f (node_modules/once/once.js:25:25)
      at Socket.reemit (node_modules/duplexer/index.js:70:25)
      at Pipe._handle.close [as _onclose] (net.js:545:12)
```

@Stebalien were there any other errors? If yes, how to reproduce them? What is your testing environment?

**Comment by diasdavid** [comment]
Also, run tests on js-ipfs-api just to double check and all good there.

**Comment by Stebalien** [comment]
The go daemon would randomly die (no errors, it looks like it just shut down) but I think it was an issue with running the tests repeatedly (while the repo tests repeatedly failed). I'm guessing daemons or random files were getting left around from previous test runs.

**Comment by diasdavid** [comment]
@Stebalien can you reproduce it? You will be able to `pgrep ipfs` and see how many daemons were left behind if any.

**Comment by Stebalien** [comment]
Well, it doesn't look like anything is getting left behind but I still get the failure occasionally:

Stdout:

```
> ipfs@0.26.0 test:interop /home/steb/projects/go/src/github.com/ipfs/js-ipfs
> npm run test:interop:node


> ipfs@0.26.0 test:interop:node /home/steb/projects/go/src/github.com/ipfs/js-ipfs
> mocha -t 60000 test/interop/node.js



  interop
    basic
Swarm listening on /ip4/127.0.0.1/tcp/4110/ws/ipfs/QmUFZ1tPjP24G65GVZSyfuAHdy65iXpJVnUX3dB7q5ffvj
Swarm listening on /ip4/127.0.0.1/tcp/4009/ipfs/QmUFZ1tPjP24G65GVZSyfuAHdy65iXpJVnUX3dB7q5ffvj
API is listening on: /ip4/127.0.0.1/tcp/5008
Gateway (readonly) is listening on: /ip4/127.0.0.1/tcp/9096
Swarm listening on /ip4/127.0.0.1/tcp/4111/ws/ipfs/QmUFZ1tPjP24G65GVZSyfuAHdy65iXpJVnUX3dB7q5ffvj
Swarm listening on /ip4/127.0.0.1/tcp/4010/ipfs/QmUFZ1tPjP24G65GVZSyfuAHdy65iXpJVnUX3dB7q5ffvj
API is listening on: /ip4/127.0.0.1/tcp/5009
Gateway (readonly) is listening on: /ip4/127.0.0.1/tcp/9097
      ✓ connect go <-> js (224ms)
      ✓ connect js <-> js (93ms)
      cat file
        ✓ go -> js: 1.02 kB (453ms)
        ✓ js -> go: 1.02 kB (274ms)
        ✓ js -> js: 1.02 kB (719ms)
        ✓ go -> js: 63.5 kB (419ms)
        ✓ js -> go: 63.5 kB (243ms)
        ✓ js -> js: 63.5 kB (677ms)
        ✓ go -> js: 65.5 kB (426ms)
        ✓ js -> go: 65.5 kB (291ms)
        ✓ js -> js: 65.5 kB (689ms)
        ✓ go -> js: 524 kB (918ms)
        ✓ js -> go: 524 kB (679ms)
        ✓ js -> js: 524 kB (1418ms)
        ✓ go -> js: 786 kB (901ms)
        ✓ js -> go: 786 kB (777ms)
        ✓ js -> js: 786 kB (1598ms)
        ✓ go -> js: 1.05 MB (909ms)
        ✓ js -> go: 1.05 MB (825ms)
        ✓ js -> js: 1.05 MB (1784ms)
        ✓ go -> js: 1.05 MB (971ms)
        ✓ js -> go: 1.05 MB (917ms)
        ✓ js -> js: 1.05 MB (1810ms)
        ✓ go -> js: 4.19 MB (1196ms)
        ✓ js -> go: 4.19 MB (1692ms)
        ✓ js -> js: 4.19 MB (4198ms)
        ✓ go -> js: 8.39 MB (1541ms)
        1) js -> go: 8.39 MB
        ✓ js -> js: 8.39 MB (7546ms)
      get directory
        2) go -> js: depth: 5, num: 5
        3) js -> go: depth: 5, num: 5
        ✓ js -> js: depth: 5, num: 5 (880ms)
        4) go -> js: depth: 5, num: 10
        5) js -> go: depth: 5, num: 10
        ✓ js -> js: depth: 5, num: 10 (992ms)
        6) go -> js: depth: 5, num: 50
        7) js -> go: depth: 5, num: 50
        ✓ js -> js: depth: 5, num: 50 (2100ms)
        8) go -> js: depth: 5, num: 100
        9) js -> go: depth: 5, num: 100
        ✓ js -> js: depth: 5, num: 100 (3312ms)
    kad-dht
      a JS node in the land of Go
        - make connections
        - one hop
        - two hops
        - three hops


  32 passing (1m)
  4 pending
  9 failing

  1) interop basic cat file js -> go: 8.39 MB:
     Uncaught AssertionError: expected [Error: connect ECONNREFUSED 127.0.0.1:43773] to not exist
      at waterfall (test/interop/exchange-files.js:147:28)
      at node_modules/async/internal/once.js:12:16
      at next (node_modules/async/waterfall.js:21:29)
      at node_modules/async/internal/onlyOnce.js:12:16
      at f (node_modules/once/once.js:25:25)
      at ClientRequest.req.on (node_modules/ipfs-api/src/utils/request-api.js:159:5)
      at Socket.socketErrorListener (_http_client.js:401:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)

  2) interop basic get directory go -> js: depth: 5, num: 5:
     Error: connect ECONNREFUSED 127.0.0.1:43773
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  3) interop basic get directory js -> go: depth: 5, num: 5:
     Error: connect ECONNREFUSED 127.0.0.1:43773
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  4) interop basic get directory go -> js: depth: 5, num: 10:
     Error: connect ECONNREFUSED 127.0.0.1:43773
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  5) interop basic get directory js -> go: depth: 5, num: 10:
     Error: connect ECONNREFUSED 127.0.0.1:43773
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  6) interop basic get directory go -> js: depth: 5, num: 50:
     Error: connect ECONNREFUSED 127.0.0.1:43773
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  7) interop basic get directory js -> go: depth: 5, num: 50:
     Error: connect ECONNREFUSED 127.0.0.1:43773
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  8) interop basic get directory go -> js: depth: 5, num: 100:
     Error: connect ECONNREFUSED 127.0.0.1:43773
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  9) interop basic get directory js -> go: depth: 5, num: 100:
     Error: connect ECONNREFUSED 127.0.0.1:43773
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)



npm ERR! code ELIFECYCLE
npm ERR! errno 9
npm ERR! ipfs@0.26.0 test:interop:node: `mocha -t 60000 test/interop/node.js`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the ipfs@0.26.0 test:interop:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/steb/.cache/npm/_logs/2017-09-19T21_05_59_338Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 9
npm ERR! ipfs@0.26.0 test:interop: `npm run test:interop:node`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the ipfs@0.26.0 test:interop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/steb/.cache/npm/_logs/2017-09-19T21_05_59_353Z-debug.log
```

Log 1:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test:interop:node' ]
2 info using npm@5.3.0
3 info using node@v8.5.0
4 verbose run-script [ 'pretest:interop:node',
4 verbose run-script   'test:interop:node',
4 verbose run-script   'posttest:interop:node' ]
5 info lifecycle ipfs@0.26.0~pretest:interop:node: ipfs@0.26.0
6 info lifecycle ipfs@0.26.0~test:interop:node: ipfs@0.26.0
7 verbose lifecycle ipfs@0.26.0~test:interop:node: unsafe-perm in lifecycle true
8 verbose lifecycle ipfs@0.26.0~test:interop:node: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/steb/projects/go/src/github.com/ipfs/js-ipfs/node_modules/.bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/steb/projects/go/src/github.com/ipfs/js-ipfs/node_modules/.bin:/home/steb/.config/spacemacs/bin:/home/steb/projects/go/bin:/home/steb/.local/bin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle ipfs@0.26.0~test:interop:node: CWD: /home/steb/projects/go/src/github.com/ipfs/js-ipfs
10 silly lifecycle ipfs@0.26.0~test:interop:node: Args: [ '-c', 'mocha -t 60000 test/interop/node.js' ]
11 silly lifecycle ipfs@0.26.0~test:interop:node: Returned: code: 9  signal: null
12 info lifecycle ipfs@0.26.0~test:interop:node: Failed to exec test:interop:node script
13 verbose stack Error: ipfs@0.26.0 test:interop:node: `mocha -t 60000 test/interop/node.js`
13 verbose stack Exit status 9
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid ipfs@0.26.0
15 verbose cwd /home/steb/projects/go/src/github.com/ipfs/js-ipfs
16 verbose Linux 4.13.2-1-hardened
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "test:interop:node"
18 verbose node v8.5.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 9
22 error ipfs@0.26.0 test:interop:node: `mocha -t 60000 test/interop/node.js`
22 error Exit status 9
23 error Failed at the ipfs@0.26.0 test:interop:node script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 9, true ]
```

Log 2:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test:interop' ]
2 info using npm@5.3.0
3 info using node@v8.5.0
4 verbose run-script [ 'pretest:interop', 'test:interop', 'posttest:interop' ]
5 info lifecycle ipfs@0.26.0~pretest:interop: ipfs@0.26.0
6 info lifecycle ipfs@0.26.0~test:interop: ipfs@0.26.0
7 verbose lifecycle ipfs@0.26.0~test:interop: unsafe-perm in lifecycle true
8 verbose lifecycle ipfs@0.26.0~test:interop: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/steb/projects/go/src/github.com/ipfs/js-ipfs/node_modules/.bin:/home/steb/.config/spacemacs/bin:/home/steb/projects/go/bin:/home/steb/.local/bin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle ipfs@0.26.0~test:interop: CWD: /home/steb/projects/go/src/github.com/ipfs/js-ipfs
10 silly lifecycle ipfs@0.26.0~test:interop: Args: [ '-c', 'npm run test:interop:node' ]
11 silly lifecycle ipfs@0.26.0~test:interop: Returned: code: 9  signal: null
12 info lifecycle ipfs@0.26.0~test:interop: Failed to exec test:interop script
13 verbose stack Error: ipfs@0.26.0 test:interop: `npm run test:interop:node`
13 verbose stack Exit status 9
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid ipfs@0.26.0
15 verbose cwd /home/steb/projects/go/src/github.com/ipfs/js-ipfs
16 verbose Linux 4.13.2-1-hardened
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "test:interop"
18 verbose node v8.5.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 9
22 error ipfs@0.26.0 test:interop: `npm run test:interop:node`
22 error Exit status 9
23 error Failed at the ipfs@0.26.0 test:interop script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 9, true ]
```

**Comment by Stebalien** [comment]
Note: I commented out the repo tests here.

**Comment by Stebalien** [comment]
Another failure
<details>
  <summary>stdout</summary>
<pre>
> ipfs@0.26.0 test:interop /home/steb/projects/go/src/github.com/ipfs/js-ipfs
> npm run test:interop:node


> ipfs@0.26.0 test:interop:node /home/steb/projects/go/src/github.com/ipfs/js-ipfs
> mocha -t 60000 test/interop/node.js



  interop
    basic
Swarm listening on /ip4/127.0.0.1/tcp/4110/ws/ipfs/QmeDXyCA3PqzbXa4MbZRmyFxnSTukVux4QpqZ4EKVft3Eu
Swarm listening on /ip4/127.0.0.1/tcp/4009/ipfs/QmeDXyCA3PqzbXa4MbZRmyFxnSTukVux4QpqZ4EKVft3Eu
Swarm listening on /ip4/127.0.0.1/tcp/4111/ws/ipfs/QmeDXyCA3PqzbXa4MbZRmyFxnSTukVux4QpqZ4EKVft3Eu
Swarm listening on /ip4/127.0.0.1/tcp/4010/ipfs/QmeDXyCA3PqzbXa4MbZRmyFxnSTukVux4QpqZ4EKVft3Eu
API is listening on: /ip4/127.0.0.1/tcp/5008
Gateway (readonly) is listening on: /ip4/127.0.0.1/tcp/9096
API is listening on: /ip4/127.0.0.1/tcp/5009
Gateway (readonly) is listening on: /ip4/127.0.0.1/tcp/9097
      ✓ connect go <-> js (217ms)
      ✓ connect js <-> js (108ms)
      cat file
        ✓ go -> js: 1.02 kB (454ms)
        ✓ js -> go: 1.02 kB (276ms)
        ✓ js -> js: 1.02 kB (699ms)
        ✓ go -> js: 63.5 kB (418ms)
        ✓ js -> go: 63.5 kB (242ms)
        ✓ js -> js: 63.5 kB (679ms)
        ✓ go -> js: 65.5 kB (422ms)
        ✓ js -> go: 65.5 kB (265ms)
        ✓ js -> js: 65.5 kB (666ms)
        ✓ go -> js: 524 kB (842ms)
        ✓ js -> go: 524 kB (661ms)
        ✓ js -> js: 524 kB (1374ms)
        ✓ go -> js: 786 kB (859ms)
        ✓ js -> go: 786 kB (754ms)
        ✓ js -> js: 786 kB (1612ms)
        ✓ go -> js: 1.05 MB (851ms)
        ✓ js -> go: 1.05 MB (948ms)
        ✓ js -> js: 1.05 MB (1893ms)
        ✓ go -> js: 1.05 MB (845ms)
        ✓ js -> go: 1.05 MB (798ms)
        ✓ js -> js: 1.05 MB (1839ms)
        ✓ go -> js: 4.19 MB (1156ms)
        ✓ js -> go: 4.19 MB (1801ms)
        ✓ js -> js: 4.19 MB (4279ms)
        ✓ go -> js: 8.39 MB (1471ms)
        ✓ js -> go: 8.39 MB (2771ms)
        ✓ js -> js: 8.39 MB (7533ms)
      get directory
        1) go -> js: depth: 5, num: 5
        2) js -> go: depth: 5, num: 5
        ✓ js -> js: depth: 5, num: 5 (884ms)
        3) go -> js: depth: 5, num: 10
        4) js -> go: depth: 5, num: 10
        ✓ js -> js: depth: 5, num: 10 (1034ms)
        5) go -> js: depth: 5, num: 50
        6) js -> go: depth: 5, num: 50
        ✓ js -> js: depth: 5, num: 50 (2043ms)
        7) go -> js: depth: 5, num: 100
        8) js -> go: depth: 5, num: 100
        ✓ js -> js: depth: 5, num: 100 (2885ms)
    kad-dht
      a JS node in the land of Go
        - make connections
        - one hop
        - two hops
        - three hops


  33 passing (1m)
  4 pending
  8 failing

  1) interop basic get directory go -> js: depth: 5, num: 5:
     Error: connect ECONNREFUSED 127.0.0.1:37053
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  2) interop basic get directory js -> go: depth: 5, num: 5:
     Error: connect ECONNREFUSED 127.0.0.1:37053
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  3) interop basic get directory go -> js: depth: 5, num: 10:
     Error: connect ECONNREFUSED 127.0.0.1:37053
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  4) interop basic get directory js -> go: depth: 5, num: 10:
     Error: connect ECONNREFUSED 127.0.0.1:37053
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  5) interop basic get directory go -> js: depth: 5, num: 50:
     Error: connect ECONNREFUSED 127.0.0.1:37053
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  6) interop basic get directory js -> go: depth: 5, num: 50:
     Error: connect ECONNREFUSED 127.0.0.1:37053
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  7) interop basic get directory go -> js: depth: 5, num: 100:
     Error: connect ECONNREFUSED 127.0.0.1:37053
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

  8) interop basic get directory js -> go: depth: 5, num: 100:
     Error: connect ECONNREFUSED 127.0.0.1:37053
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)



npm ERR! code ELIFECYCLE
npm ERR! errno 8
npm ERR! ipfs@0.26.0 test:interop:node: `mocha -t 60000 test/interop/node.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ipfs@0.26.0 test:interop:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/steb/.cache/npm/_logs/2017-09-19T21_13_58_655Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 8
npm ERR! ipfs@0.26.0 test:interop: `npm run test:interop:node`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ipfs@0.26.0 test:interop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/steb/.cache/npm/_logs/2017-09-19T21_13_58_675Z-debug.log
</pre>
</details>

One interesting thing I've noticed is that these failures tend to happen in runs.

**Comment by mitra42** [comment]
I'm seeing this error currently - the node modules are up to date. 
IPFS options are:
"repo":"/tmp/ipfs_dweb20171029","config":{"Addresses":{"Swarm":["/dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star"]}},"EXPERIMENTAL":{"pubsub":true}}

Its totally reproducable, the file is at https://dweb.me/examples/example_academic.html?verbose=true and errors show up in the console (with the verbose option set like this).

**Comment by mitra42** [comment]
Narrowing this down to just one line: 
In package.json:
"ipfs": "git+https://git@github.com/ipfs/js-ipfs.git#319c1c9830262ab5c05bf99fc525d8883d3178cb",  WORKS
"ipfs": "git+https://git@github.com/ipfs/js-ipfs.git",  FAILS
 "ipfs": "^0.26.0", FAILS
    "ipfs": "^0.25.4", FAILS for different reasons (doesnt recognize p2p-webrtc-star)

So until this is fixed maybe use that specific github commit.

**Comment by Stebalien** [comment]
@mitra42 these errors are unrelated. This is about js<->go interop, not the repo version change in js-ipfs master.
