### ISSUE TITLE
ipfs fails to build on mipsle architecture

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4257]
We're using old versions of golang.org/x/net and golang.org/x/sys that don't have mipsle support. We need to update those.

**Comment by cc14514** [comment]
why do not use vendor for deps ?

**Comment by cc14514** [comment]
liangcdeiMac:ipfs liangc$ GOOS=linux GOARCH=mips go build -o ipfs_mips .
# gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/ipv4
../../../../../gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/ipv4/icmp.go:34:2: undefined: sysICMPFilter
# gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/ipv6
../../../../../gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/ipv6/icmp.go:34:2: undefined: sysICMPv6Filter
# gx/ipfs/QmXPKMT5cT8ajqamSD1YaeEpfeaHvs9AU4MQzte4Bkr6V4/sys/unix
../../../../../gx/ipfs/QmXPKMT5cT8ajqamSD1YaeEpfeaHvs9AU4MQzte4Bkr6V4/sys/unix/flock.go:18:42: undefined: Flock_t
../../../../../gx/ipfs/QmXPKMT5cT8ajqamSD1YaeEpfeaHvs9AU4MQzte4Bkr6V4/sys/unix/sockcmsg_linux.go:14:29: undefined: Ucred
../../../../../gx/ipfs/QmXPKMT5cT8ajqamSD1YaeEpfeaHvs9AU4MQzte4Bkr6V4/sys/unix/sockcmsg_linux.go:27:54: undefined: Ucred
../../../../../gx/ipfs/QmXPKMT5cT8ajqamSD1YaeEpfeaHvs9AU4MQzte4Bkr6V4/sys/unix/sockcmsg_unix.go:42:9: undefined: Cmsghdr

**Comment by cc14514** [comment]
format

**Comment by Kubuxu** [comment]
Should be resolved by go modules: https://github.com/ipfs/go-ipfs/pull/6038
