### ISSUE TITLE
Quick question on setting up bootstrap nodes for private-networks

### ISSUE THREAD

**Issue by ssikdar1** [ipfs/go-ipfs#4262]
#### Version information:
go-ipfs version: 0.4.10-4679f80
Repo version: 5
System version: amd64/linux
Golang version: go1.7.5

#### Description:

Hey quick question:

I was wondering about a clarification on how to go about trying out the private networks experimental feature:
https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks

 These instructions here:

>>
When using this feature, you will not be able to connect to the default bootstrap nodes (Since we arent part of your private network) so you will need to set up your own bootstrap nodes.

To prevent your node from even trying to connect to the default bootstrap nodes, run:

ipfs bootstrap rm --all
>>

From here:
https://ipfs.io/ipfs/QmNZiPk974vDsPmQii3YbrMKfi12KTSNM7XMiYyiea4VYZ/example#/ipfs/QmP8WUPq2braGQ8iZjJ6w9di6mzgoTWyRLayrMRjjDoyGr/bootstrap/readme.md

I see that the rm --all removes all the bootstrap nodes in your ipfs list. And you can add new ones via : 
ipfs bootstrap add <multi peer address>. 

I'm guessing if I run a couple of more machines with ipfs with the same ~/.ipfs/swarm.key i can use get their multi peer addresses and add it to the orignal machines bootstrap list.

my question: Is this all that needs to be done to setup bootstrap nodes? 

Thanks!

**Comment by Kubuxu** [comment]
@ssikdar1 yes, any ipfs node can be a bootstrap node.

**Comment by janhuang6** [comment]
I am using the following command to add a new machine to ipfs node:

ipfs bootstrap add /ip4/35.x.x.x/tcp/4001/ipfs/QmSrBvxEoeu5yR??????????????????????????????dG

I believe for every new ip address, I need to use a new hash value "QmSrBvxEoeu5yR??????????????????????????????dG"

The question is how do I or where can I get the new hash value for my new machine (new ip)?

Thanks!

**Comment by Stebalien** [comment]
@janhuang6 we've switched to using https://discuss.ipfs.io for questions and discussions.

P.S., Please try to avoid asking new questions on open threads/issues.
