### ISSUE TITLE
ipfs dag add / hash of unhashable type

### ISSUE THREAD

**Issue by udatny** [ipfs/go-ipfs#4263]
#### Version information:
go-ipfs_v0.4.10_windows-amd64

#### Type:
Bug

#### Severity:
High

#### Description:
trying to add binary file with : 
ipfs dag put  --input-enc raw somsdfsdfsdf.png

i attached the file (the image)

returning: 
Error: cbor panic: runtime error: hash of unhashable type []interface {}
![somsdfsdfsdf](https://user-images.githubusercontent.com/6443496/30772510-380197c0-a05d-11e7-88f0-542def184a94.png)

**Comment by ivan386** [comment]
You can use
`ipfs add --raw-leaves somsdfsdfsdf.png`
or
`Ipfs block put < somsdfsdfsdf.png`

**Comment by udatny** [comment]
Hello ivan, thanks, the issue is specific to ipfs dag / cidv2 . I am able to add any file using the mentioned command, except this file, so i guess its a bug.

**Comment by udatny** [comment]
Sorry, cidv1.

**Comment by ivan386** [comment]
>  I am able to add any file using the mentioned command
@udatny 
You check this files? 

`ipfs dag put --input-enc raw somsdfsdfsdf.png` try read and save node in cbor format.

> -f,        --format string - Format that the object will be added as. Default: cbor.

**Comment by udatny** [comment]
Yes. Exactly this file and this command. Does it work for you? U can see i use sh**  microsoft and it does not work with the provided picture. A non json cannot be addedusing cbor as i understand. Therefore the raw param.

**Comment by udatny** [comment]
The attached png file.

**Comment by udatny** [comment]
Pls try to reproduce in your os with the attached pic.

**Comment by magik6k** [comment]
I'm able to reproduce this on Linux, this is a problem with our CBOR lib. `ipfs dag put --input-enc raw` is used to put raw dag-cbor, not raw data. For that you want to use the commands @ivan386 suggested above.

**Comment by udatny** [comment]
@magik6k thanks. I still dont get it. If i want to add a binary using cidv1. How do i do it? And. Why does it work with other binaries? So is it a bug? Or  my fault?

**Comment by magik6k** [comment]
If you just want to get CIDv1 you do `ipfs add --cid-version=1`, `dag put` works only due to the fact that the data sometimes happens to be valid-ish CBOR.

**Comment by udatny** [comment]
Ok. My fault.
