### ISSUE TITLE
Two quick questions on ipfs behaviours

### ISSUE THREAD

**Issue by wpfnihao** [ipfs/go-ipfs#4265]
#### Version information:
go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/linux
Golang version: go1.8.3

#### Type:
Misc.

#### Severity:
Very Low
#### Description:

During my usage of ipfs, I find two interesting behavior of ipfs:
1. `ipfs get` with a folder containing a large number of files smaller than 256KB has a constant speed, no matter the actually file size, as long as they are smaller than 256KB. However, if the files are larger than 256KB, I get the expected behavior of ipfs, say, with the total size fixed, the more the files (the smaller the file), the slower the speed. I understand that ipfs will segment large files into chunks, each with the size of 256KB. But what I don't understand is, why this will affect the networking behavior of ipfs.
2. While using `ipfs get` to copy data from one node to another, I observed 6% and 15% CPU usage on the sender and receiver both equipped Intel E5 CPU (40 cores), respectively. I think this is a very high CPU usage for just copying data.

My questions here are:
1. Could you please give me a brief explanation why `ipfs get` has the interesting behavior while copying files smaller than 256KB and why ipfs has such a high cpu usage?
2. Could you please point me the right direction so that I can also go through the codes by myself?

Thanks.

**Comment by kevina** [comment]
For (1) I am guessing that most of the time is spent finding the block, and if you have a fast enough network the time it takes to transfer the block once found is insignificant.  For (2) we are working to improve IPFS resource usage.

**Comment by bertrandfalguiere** [comment]
I guess this can be closed.
And questions can now be asked at https://discuss.ipfs.io
