### ISSUE TITLE
web ui: Files page remove pin button broken

### ISSUE THREAD

**Issue by AgentME** [ipfs/go-ipfs#4269]
#### Version information:
go-ipfs version: 0.4.11-
Repo version: 6
System version: amd64/linux
Golang version: go1.9

#### Description:

The X remove buttons on the Files page of the web ui are broken. If you click any of them, then the web UI goes to the front page (because the remove button is a link to "#" and the preventDefault() method is never called on the click event object), and this error appears in the console: "TypeError: t.preventDefault is not a function"

**Comment by Kubuxu** [comment]
Can you report it at: https://github.com/ipfs/webui
