### ISSUE TITLE
ipfs daemon -- Error: EOF

### ISSUE THREAD

**Issue by us** [ipfs/go-ipfs#4273]
#### Version information:
go-ipfs version: 0.4.11-
Repo version: 6
System version: amd64/darwin
Golang version: go1.9

#### Type:
Error: EOF

#### Description:
⋊> ~ ipfs daemon                                                                                                                                                                         21:57:18
Initializing daemon...
21:57:23.044 ERROR   cmd/ipfs: error from node construction: EOF daemon.go:335
Error: EOF

**Comment by magik6k** [comment]
That message doesn't provide much info by itself.

* Are you using custom datastore configuration?
* Is it a fresh install or have you been using this setup for a while?
* Can you reproduce this with fresh repo:
  * `IPFS_PATH=/tmp/ipfs ipfs init`
  * `IPFS_PATH=/tmp/ipfs ipfs daemon`

**Comment by us** [comment]
it's a fresh install.Yesterday I just follow the quick-start and i had a break and problem..

**Comment by Stebalien** [comment]
Can you try running the daemon with `IPFS_LOGGING=debug ipfs daemon` and posting the logs?
