### ISSUE TITLE
Intermittent name resolution problems 

### ISSUE THREAD

**Issue by Calmarius** [ipfs/go-ipfs#4287]
#### Version information:

go-ipfs version: 0.4.11-
Repo version: 6
System version: amd64/linux
Golang version: go1.9

#### Description:

DNS based ipfs resolve fails intermittently in 0.4.11:

```
--------------------
$ ipfs resolve /ipns/ipfs.io
Error: Could not resolve name.
--------------------
$ ipfs resolve /ipns/ipfs.io
Error: Could not resolve name.
--------------------
$ ipfs resolve /ipns/ipfs.io
Error: Could not resolve name.
--------------------
$ ipfs resolve /ipns/ipfs.io
Error: Could not resolve name.
--------------------
$ ipfs resolve /ipns/ipfs.io
Error: Could not resolve name.
--------------------
$ ipfs resolve /ipns/ipfs.io
/ipfs/QmPCawMTd7csXKf7QVr2B1QRDZxdPeWxtE4EpkDRYtJWty
--------------------
$ ipfs resolve /ipns/ipfs.io
Error: Could not resolve name.
--------------------
$ ipfs resolve /ipns/ipfs.io
/ipfs/QmPCawMTd7csXKf7QVr2B1QRDZxdPeWxtE4EpkDRYtJWty

```

Other domain tools work without problems. So it's not an issue of my DNS server.

The ipfs daemon is running and is connected to 2000 peers... Perhaps it's a file descriptor exhaustion issue?

**Comment by Stebalien** [comment]
That sounds like a good hypothesis. What's your FD limit (`cat /proc/$(pidof ipfs)/limits`) and how many file descriptors does IPFS have open (`echo ${#$(echo /proc/self/fd/*)[@]}`)?

**Comment by Kubuxu** [comment]
@Stebalien I always use `ls -1 /proc/$(pidof ipfs)/fd/ | wc -l`.

**Comment by Stebalien** [comment]
@Kubuxu though shalt not parse `ls` output! (I guess it's probably fine in this case).

**Comment by Stebalien** [comment]
@Calmarius mind trying this with the latest IPFS release? It should work a *lot* better now.

**Comment by Calmarius** [comment]
Much better now.

Given that the number of connections is now kept in check I can also run the daemon 24/7 now.

**Comment by Stebalien** [comment]
Good to hear. I'm closing this as fixed but please reopen if you experience this issue again.

**Comment by anasant** [comment]
I was trying to access: https://ipfs.io/ipns/QmZxWEBJBVkGDGaKdYPQUXX4KC5TCWbvuR4iYZrTML8XCR/en/where-to-vote/index.html from the article: http://la3.org/~kilburn/blog/catalan-government-bypass-ipfs/

I am getting: 
```
ipfs resolve -r /ipns/QmZxWEBJBVkGDGaKdYPQUXX4KC5TCWbvuR4iYZrTML8XCR/en/where-to-vote/index.html: Could not resolve name.
```
In my understanding, IPFS should provide historic versioning of the data and I should always be able to access the page. Is this incorrect? If not, where has the page gone?

**Comment by Stebalien** [comment]
> In my understanding, IPFS should provide historic versioning of the data and I should always be able to access the page. Is this incorrect? If not, where has the page gone?

There are two things going on here.

1. IPNS records expire every 24hours (for now). If you publish an IPNS record, you *must* repeatedly re-publish it every few hours. Otherwise, the network will forget it. In the future, we could use something like namecoin to prevent this but we don't have that at the moment.
2. Files stored in IPFS will only continue to exist in IPFS as long as IPFS nodes are storing (and serving) them. IPFS is permanent in the sense that `/ipfs/...` links never "break"; they always point to the same file. However, that doesn't mean you'll always be able to retrieve that file (we *can't* really make this guarantee).

**Comment by anasant** [comment]
Thank you for the explanation!
