### ISSUE TITLE
IPFS WebUI sends 404

### ISSUE THREAD

**Issue by DakshMiglani** [ipfs/go-ipfs#4289]
#### Version information:

```
go-ipfs version: 0.4.11-
Repo version: 6
System version: amd64/linux
Golang version: go1.9
```

#### Description: 
When I start the daemon, and I try to open `localhost:5001` the WebUI returns `404 page not found`, Don't know what's wrong?

**Comment by Calmarius** [comment]
You are supposed to go to `localhost:5001/webui`

**Comment by DakshMiglani** [comment]
Thanks!
