### ISSUE TITLE
api call to lookup dnslink name doesn't work

### ISSUE THREAD

**Issue by bonds** [ipfs/go-ipfs#4293]
#### Version information:

````
~ ❯❯❯ ipfs version --all                                                    Mon 2017-10-09 14:27:51 -0700
go-ipfs version: 0.4.11-dev-
Repo version: 5
System version: amd64/openbsd
Golang version: go1.8
````

#### Description:

Using the API to resolve ggr.com doesn't work, i.e.:

````
https://ipfs.io/api/v0/dns/ggr.com
````

returns

````
{"Message":"Could not resolve name (recursion limit exceeded).","Code":0}
````
Yet, the name resolves at the CLI fine:
````
~/Downloads ❯❯❯ ipfs --debug name resolve -r ggr.com                        Mon 2017-10-09 12:09:19 -0700
14:09:29.683  INFO   cmd/ipfs: IPFS_PATH /home/scott/.ipfs main.go:301
14:09:29.687 DEBUG   cmd/ipfs: calling pre-command hooks... main.go:295
14:09:29.687 DEBUG   cmd/ipfs: executing command via API main.go:332
/ipfs/QmWqNxbUnGZzmLeyA8jMi1VeyuHpBcYDYH9WcYZY31zijk
````
See https://github.com/ipfs/ipfs-companion/issues/288 for a previous discussion and more detail on this issue.

**Comment by Stebalien** [comment]
The issue here is that the `dns` command isn't recursive by default. You can add `?r=true` to the end to fix this.

Honestly, we should probably make these recursive by default, if possible.

**Comment by lgierth** [comment]
> Honestly, we should probably make these recursive by default, if possible.
Yes, with a limit of 10 or so
