### ISSUE TITLE
Garbage collection doesn't free up space when using badger

### ISSUE THREAD

**Issue by leerspace** [ipfs/go-ipfs#4300]
#### Version information:
go-ipfs version: 0.4.11-
Repo version: 6
System version: amd64/linux
Golang version: go1.9

#### Type:
Bug

#### Severity:
Medium/High

#### Description:
When running garbage collection on a repo using the badger datastore, local storage is not freed up after running `ipfs repo gc`.

**Comment by Stebalien** [comment]
Yeah, that's because badger has to do a separate internal GC. Currently, we don't manually trigger it on repo GC but we probably should.

**Comment by leerspace** [comment]
It looks like this might have been "fixed" by ipfs/go-datastore#68 and the "Basic GC Implementation" commit to go-ds-badger (?). Should this work already or do the changes to go-ds-badger just need to bubble up?

**Comment by magik6k** [comment]
The changes are bubbled up, just not wired up to gc logic

**Comment by magik6k** [comment]
https://github.com/ipfs/go-ipfs/pull/4578 is going to fix this, at least for big datastores (few gigs with with 100s of MBs of reclaimable space).

For full GC there is an offline tool being developed in https://github.com/dgraph-io/badger/pull/400, which will likely help with the cases where the online badger GC doesn't help

**Comment by schomatis** [comment]
#4578 has been merged and the GC logic is working, note however that the GC mechanism for `badger` is not the same as for `flatfs`, some data may not be immediately reclaimed.
