### ISSUE TITLE
respect provider strategies on initial adds

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4311]
We have provider strategies that define which content gets provided. However, they are only respected on *reprovide*, for the initial adding of the content, everything currently gets provided regardless of whether or not it should be given the strategy.

We should rework the providers system to address this issue, moving provides out of the add path should also improve the performance of add.

**Comment by michaelavila** [comment]
This work is being tracked here: #5774 and references this issue, so I'm going to close this issue.
