### ISSUE TITLE
Format flag buggy when passed to `ipfs refs`

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4319]
`ipfs refs --format=bla QmId...` prints out `bla` for every hash.

**Comment by whyrusleeping** [comment]
```
OPTIONS

  --format            string - Emit edges with given format. Available tokens: <src> <dst> <linkname>. Default: <dst>.
```

What were you expecting?

**Comment by Stebalien** [comment]
Ah. I was expecting it to mean the same thing as every other `--format`. Kind of non-nonsensical here I guess (the correct flag is `--encoding`) but just seeing my format spit back out at me kind of threw me for a loop. I tried passing in `%s` to see if it was some form of format string but checking `--help` never seemed to occur to me...
