### ISSUE TITLE
go-ipfs fails to build on i386

### ISSUE THREAD

**Issue by Voker57** [ipfs/go-ipfs#4322]
#### Version information:

5c9125e8b55bc7d9e60f8a9169473da36d28b920 

#### Description: 

```
# gx/ipfs/QmTBxwy8cerzXbZQFUwTBCSxx55jUgVzudFcpmnAHUGuPy/badger
../../../gx/ipfs/QmTBxwy8cerzXbZQFUwTBCSxx55jUgVzudFcpmnAHUGuPy/badger/kv.go:86:6: constant 1099511627776 overflows int
cmd/ipfs/Rules.mk:21: recipe for target 'cmd/ipfs/ipfs' failed
make: *** [cmd/ipfs/ipfs] Error 2
```

**Comment by magik6k** [comment]
See https://github.com/ipfs/go-ds-badger/issues/9, this will be fixed when https://github.com/ipfs/go-ds-badger/pull/10 is merged and propagated

**Comment by jfacorro** [comment]
Do you know how much time is it expected for the change in ipfs/go-ds-badger#10 to be propagated after merging?

**Comment by magik6k** [comment]
We have some compatibility problems with badger, see https://github.com/ipfs/go-ipfs/pull/4327#issuecomment-338064247 for more details.

For now if you want to build current master, as a work-around you can do the following:
* Remove badgerds logic: https://github.com/ipfs/go-ipfs/blob/master/repo/fsrepo/datastores.go#L347-L394
* Remove badgerds from datastore list at https://github.com/ipfs/go-ipfs/blob/master/repo/fsrepo/datastores.go#L65
* Remove badgerds import: https://github.com/ipfs/go-ipfs/blob/master/repo/fsrepo/datastores.go#L20
* `make build install`
