### ISSUE TITLE
dht: checking dht client type: context canceled notif.go:81

### ISSUE THREAD

**Issue by m-brian** [ipfs/go-ipfs#4334]
#### Version information:
go-ipfs version: 0.4.11-41102bd
Repo version: 6
System version: amd64/darwin
Golang version: go1.9

#### Type:
Bug

#### Severity:
Medium
#### Description:
Shortly after starting the daemon on macOS High Sierra, the terminal shows the following error. Sometimes it reappears when I close the daemon:
```
Daemon is ready
04:05:42.177 ERROR        dht: checking dht client type: context canceled notif.go:81
04:07:24.444 ERROR        dht: checking dht client type: context canceled notif.go:81
^C
Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)
04:11:44.369 ERROR        dht: checking dht client type: connection reset notif.go:81
04:11:44.371 ERROR        dht: checking dht client type: connection reset notif.go:81
```
After the error first appears, the Web UI refuses to list connected peers - it just claims there are 0 peers, even though `ipfs swarm peers` lists plenty of them.

Not sure if this is the intended behavior.

**Comment by whyrusleeping** [comment]
How are you accessing the webui? via localhost:5001/webui? are there any errors in the developer console?

**Comment by tomasi-o** [comment]
Same here, accessing it via terminal (iterm) on MacOS 10.11 and MaOS 12 (Sierra). Do I have to do some port forwarding maybe?

**Comment by davidrhodus** [comment]
Running Ubuntu( 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)

Seeing the daemon exit here with the same error:

dht: checking dht client type: connection reset

**Comment by Fohlen** [comment]
Seing this on High Sierra and ipfs version 0.4.11

**Comment by alvin-reyes** [comment]
Getting this error on 2 of my Digital Ocean instance with Ubuntu 16.04.3 LTS

IPFS Version 0.4.11

**Comment by slindner211** [comment]
I also have this problem on High Sierra and ipfs version 0.4.11

**Comment by whyrusleeping** [comment]
Seeing the error message in the issue title is *not* a bug. Please ignore it until we downgrade the error log to a warning.

The other issue mentioned the issue (on seeing no peers in the webui) should have a separate issue opened for it.
