### ISSUE TITLE
arm64 bootstrapping fails, reuseport / epollwait function not implemented

### ISSUE THREAD

**Issue by elitak** [ipfs/go-ipfs#4337]
#### Version information:

    go-ipfs version: 0.4.11-
    Repo version: 6
    System version: arm64/linux
    Golang version: go1.9.1

#### Description:
Most of my arm64 hosts spam the following to syslog:

    Oct 23 19:30:50 armhost ipfs[1058]: 19:30:50.222 ERROR reuseport-: EpollWait returned error: function not implemented. Continuing. linux.go:189
    Oct 23 19:30:50 armhost ipfs[1058]: 19:30:50.223 ERROR reuseport-: EpollWait returned error: function not implemented. Continuing. linux.go:189
    Oct 23 19:30:50 armhost ipfs[1058]: 19:30:50.223 ERROR reuseport-: EpollWait returned error: function not implemented. Continuing. linux.go:189
    Oct 23 19:30:50 armhost ipfs[1058]: 19:30:50.224 ERROR reuseport-: EpollWait returned error: function not implemented. Continuing. linux.go:189

Some manage to eventually bootstrap, but others are stuck forever not able to connect to the network. I cannot dial in or out, either. Could this have something to do with low system memory (512MB ram)?

**Comment by Stebalien** [comment]
https://github.com/jbenet/go-reuseport/issues/22

...and this is what happens when perfectly good bug reports go unnoticed. Let me fix that for you.

In the mean time, try setting `IPFS_REUSEPORT=false` in your environment (it'll turn off reuseport which should work around this issue.

**Comment by elitak** [comment]
The environment flag fixed my issue, and the daemon now immediately bootstraps. Thanks very much.

**Comment by Stebalien** [comment]
I'm assigning this a P-0 flag so we don't drop it. The fix is ready, just waiting to be merged, propagated, and tested.

**Comment by Stebalien** [comment]
@elitak this should be fixed. Could you try building the latest git release and try running *without* `IPFS_REUSEPORT=false`?

**Comment by elitak** [comment]
The issue is gone now, thanks.
