### ISSUE TITLE
Cann not get IPFS object from WAN

### ISSUE THREAD

**Issue by zhazha3374** [ipfs/go-ipfs#4338]
#### Version informa
ipfs version 0.4.11

#### Type:
Etc. 

#### Description:

I add a file to ipfs by command "ipfs add" from a LAN, and download the file by command "ipfs get" from the LAN successfully. But download the same file failed by command "ipfs get" from WAN. 
Why? Something config wasn't set up?

**Comment by magik6k** [comment]
This usually means connectivity problems, can you try to follow https://github.com/ipfs/go-ipfs/blob/886403df942550e5a7fadd6a86bab77fac8e5798/docs/file-transfer.md and report here if it worked for you?

**Comment by zhazha3374** [comment]
@magik6k  Thanks for your advice. the problem has been resolved.  the reason is that UPNP is disable.
