### ISSUE TITLE
Does exist correct manual for building go-ipfs on Windows platform ?

### ISSUE THREAD

**Issue by ghbpeter** [ipfs/go-ipfs#4341]
I tried to build go-ipfs by https://github.com/ipfs/go-ipfs/blob/master/docs/windows.md
and it finishes on step: go install -ldflags="-X "github.com/ipfs/go-ipfs/repo/config".CurrentCommit=..."
with output below. What is reason of missing packages ?

c:\Users\peter\go\src\github.com\ipfs\go-ipfs\cmd\ipfs>go install -ldflags="-X "github.com/ipfs/go-ipfs/repo/config
..\..\vendor\gx\ipfs\QmX3QZ5jHEPidwUrymXV1iSCSUhdGxj15sm2gP4jKMef7B\client_golang\prometheus\summary.go:23:2: cannot find package "github.com/beorn7/perks/quantile" in any of:
        c:\users\peter\go\src\github.com\ipfs\go-ipfs\vendor\github.com\beorn7\perks\quantile (vendor tree)
        c:\projects\go\src\github.com\beorn7\perks\quantile (from $GOROOT)
        c:\users\peter\go\src\github.com\beorn7\perks\quantile (from $GOPATH)
..\..\vendor\gx\ipfs\QmcWmYQEQCrezztaQ81nXzMx2jaAEow17wdesDAjjR769r\go-libp2p-pnet\psk_conn.go:8:2: cannot find package "github.com/davidlazar/go-crypto/salsa20" in any of:
        c:\users\peter\go\src\github.com\ipfs\go-ipfs\vendor\github.com\davidlazar\go-crypto\salsa20 (vendor tree)
        c:\projects\go\src\github.com\davidlazar\go-crypto\salsa20 (from $GOROOT)
        c:\users\peter\go\src\github.com\davidlazar\go-crypto\salsa20 (from $GOPATH)
..\..\vendor\gx\ipfs\QmUamAGkvPp1w84dfc2YMy9ic6iyBvaRoaTiaat8Crtawq\go-ds-badger\datastore.go:4:2: cannot find package "github.com/dgraph-io/badger" in any of:
        c:\users\peter\go\src\github.com\ipfs\go-ipfs\vendor\github.com\dgraph-io\badger (vendor tree)
        c:\projects\go\src\github.com\dgraph-io\badger (from $GOROOT)
        c:\users\peter\go\src\github.com\dgraph-io\badger (from $GOPATH)
..\..\vendor\gx\ipfs\QmX3QZ5jHEPidwUrymXV1iSCSUhdGxj15sm2gP4jKMef7B\client_golang\prometheus\desc.go:23:2: cannot find package "github.com/golang/protobuf/proto" in any of:
        c:\users\peter\go\src\github.com\ipfs\go-ipfs\vendor\github.com\golang\protobuf\proto (vendor tree)
        c:\projects\go\src\github.com\golang\protobuf\proto (from $GOROOT)
        c:\users\peter\go\src\github.com\golang\protobuf\proto (from $GOPATH)
..\..\vendor\gx\ipfs\QmSk46nSD78YiuNojYMS8NW6hSCjH95JajqqzzoychZgef\go-metrics-prometheus\binding.go:6:2: cannot find package "github.com/gxed/client_golang/prometheus" in any of:
        c:\users\peter\go\src\github.com\ipfs\go-ipfs\vendor\github.com\gxed\client_golang\prometheus (vendor tree)
        c:\projects\go\src\github.com\gxed\client_golang\prometheus (from $GOROOT)
        c:\users\peter\go\src\github.com\gxed\client_golang\prometheus (from $GOPATH)
....

**Comment by lgierth** [comment]
Did you follow all the steps? This looks like you skipped the "download and install dependencies" step.

**Comment by ghbpeter** [comment]
Yes I followed these steps, gx --verbose install --global installed some packages, see below output. Maybe some problem with GOPATH ? I have set it to c:\users\peter\go .

c:\Users\peter\go\src\github.com\ipfs\go-ipfs>c:\users\peter\go\bin\gx --verbose install --global
  - QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52 not found locally, fetching into vendor\gx\ipfs\QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52
[[33mget [0m] [fetch]   go-log                   QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52
[0 / 164] 0s  - QmeS8cCKawUwejVrsBtmC1toTXmwVWZGiRJqzgTURVWeF9 not found locally, fetching into vendor\gx\ipfs\QmeS8cCKawUwejVrsBtmC1toTXmwVWZGiRJqzgTURVWeF9
[[33mget [0m] [fetch]   go-ipfs-addr             QmeS8cCKawUwejVrsBtmC1toTXmwVWZGiRJqzgTURVWeF9
[0 / 164] 0s  - fetching QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52 via ipfs api
  - fetching QmeS8cCKawUwejVrsBtmC1toTXmwVWZGiRJqzgTURVWeF9 via ipfs api
  - fetch finished in 743.5769ms
  - fetch QmeS8cCKawUwejVrsBtmC1toTXmwVWZGiRJqzgTURVWeF9 complete!rsBtmC1toTXmwVWZGiRJqzgTURVWeF9 746ms[1B
[1 / 82] fetched dep: go-ipfs-addr
  - QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M not found locally, fetching into vendor\gx\ipfs\QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M
[[33mget [0m] [fetch]   go-libp2p-secio          QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M
[1 / 164] 0s  - fetching QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M via ipfs api
  - fetch finished in 811.841ms
  - fetch QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52 complete!HBEp3R73FL4NF6FnQTEGyNAXHm2GS52 814ms[3B
[2 / 82] fetched dep: go-log
  - QmaPbCnUMBohSGo3KnxEa2bHqyJVVeEEcwtqJAYxerieBo not found locally, fetching into vendor\gx\ipfs\QmaPbCnUMBohSGo3KnxEa2bHqyJVVeEEcwtqJAYxerieBo
[[33mget [0m] [fetch]   go-libp2p-crypto         QmaPbCnUMBohSGo3KnxEa2bHqyJVVeEEcwtqJAYxerieBo
[2 / 164] 0s  - fetching QmaPbCnUMBohSGo3KnxEa2bHqyJVVeEEcwtqJAYxerieBo via ipfs api
[2 / 164] 0s  - fetch finished in 489.7363ms
  - fetch QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M complete!aoMMYx8jxBGauZw75zPjnZAyfwPso7M 504ms[2B
.... etc.

**Comment by ghbpeter** [comment]
For example it looks for:
github.com/beorn7/perks/quantile
and it is not found but I see that directory exist in this place on my machine:
C:\Users\peter\go\src\github.com\ipfs\go-ipfs\vendor\gx\ipfs\QmbNinL4ErzM73BxQSNf8q2vPmAM4v3MNQM2DmDqDjt47D\perks\quantile

**Comment by ghbpeter** [comment]
I was successful with build now. It seems that I had not set GOROOT and maybe that was the reason. But I found strange behavior with GOROOT variable, see attached output.
It accepts GOROOT only if it is ended with last backslash. So I also set GOPATH again and added last backslash.

``c:\Users\peter>set GOROOT="c:\Projects\Go"

c:\Users\peter>go get -u github.com/ipfs/go-ipfs
go: cannot find GOROOT directory: "c:\Projects\Go"

c:\Users\peter>dir c:\Projects\Go
 Volume in drive C is Windows
 Volume Serial Number is D460-28CD

 Directory of c:\Projects\Go

10/25/2017  01:22 PM    <DIR>          .
10/25/2017  01:22 PM    <DIR>          ..
10/25/2017  01:22 PM    <DIR>          api
10/04/2017  06:48 PM            41,258 AUTHORS
10/25/2017  01:22 PM    <DIR>          bin
10/25/2017  01:22 PM    <DIR>          blog
10/04/2017  06:48 PM             1,576 CONTRIBUTING.md
10/04/2017  06:48 PM            55,577 CONTRIBUTORS
10/25/2017  01:22 PM    <DIR>          doc
10/04/2017  06:48 PM             5,686 favicon.ico
10/25/2017  01:22 PM    <DIR>          lib
10/04/2017  06:48 PM             1,479 LICENSE
10/25/2017  01:22 PM    <DIR>          misc
10/04/2017  06:48 PM             1,303 PATENTS
10/25/2017  01:22 PM    <DIR>          pkg
10/04/2017  06:48 PM             1,601 README.md
10/04/2017  06:48 PM                26 robots.txt
10/25/2017  01:22 PM    <DIR>          src
10/25/2017  01:22 PM    <DIR>          test
10/04/2017  06:48 PM                 7 VERSION
               9 File(s)        108,513 bytes
              11 Dir(s)  15,183,925,248 bytes free

c:\Users\peter>set GOROOT=c:\Projects\Go\

c:\Users\peter>go get -u github.com/ipfs/go-ipfs``

**Comment by Kubuxu** [comment]
Seems like the problem was solved, closing. If it is not, please comment and reopen.
