### ISSUE TITLE
bootstrap: without working /ip6, dial backoff also affects /ip4

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#4342]
#### Description:

We have a couple of IPv6 nodes in the default bootstrap config. On a machine where IPv6 is not supported, or broken, IPv6 dails fail and eventually result in the dial backoff kicking in. This dial backoff seems to also affect IPv4 dials.

- Dial backoff should be per-transport or per-address

**Comment by Stebalien** [comment]
Duplicate of: https://github.com/libp2p/go-libp2p-swarm/issues/37

**Comment by lgierth** [comment]
Ah excellent
