### ISSUE TITLE
Add 'routing' section to config

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4351]
It would be very useful to have a configuration option that would allow us to select routing options, like the `--routing` daemon flag. This way, we can set things like `dhtclient` mode routing for certain config init profiles. It would also be nice to be able to configure certain attributes of whatever routing system we choose.

**Comment by magik6k** [comment]
Implemented in https://github.com/ipfs/go-ipfs/pull/4154
