### ISSUE TITLE
Cryptic error message if ipfs daemon is running and file being added is non-readable

### ISSUE THREAD

**Issue by Voker57** [ipfs/go-ipfs#4362]
#### Version information:

go-ipfs version: 0.4.12-rc1-68a2d4d42
Repo version: 6
System version: amd64/linux
Golang version: go1.8.1

#### Type: Enhancement

Low

#### Description:

If daemon is running during ipfs add, all I get on non-readable (unix permissions) file:

```
13:03:03.204 ERROR commands/h: err: read tcp4 127.0.0.1:5001->127.0.0.1:60510: use of closed network connection handler.go:285
```

If daemon is not running, there is proper error about permissions.

**Comment by Stebalien** [comment]
See: https://github.com/ipfs/go-ipfs/issues/3855
Reported upstream at: https://github.com/golang/go/issues/21760

**Comment by Stebalien** [comment]
(but thanks for the excellent bug report)
