### ISSUE TITLE
IPNS name caching

### ISSUE THREAD

**Issue by matthiasbeyer** [ipfs/go-ipfs#4366]
#### Description:

IPNS names are, as far as I experienced so far, not cached. That means, as soon as a node which publishes a name goes offline, the IPNS hash cannot be resolved anymore.

Publishing a blog from a notebook is practically not possible because of that, for example.

It would be nice if IPNS names could be cached (implicitely by resolving them or explicitely... something like `ipfs name cache <hash>`).
The node which caches the name could automatically try to resolve the hash every `n` minutes/hours (configurable?) and automatically update its cache.

#### Implications / Problems

I'm not sure what the implications would be for a client resolving a hash and getting multiple answers, that should be discussed, of course.

**Comment by Stebalien** [comment]
> IPNS names are, as far as I experienced so far, not cached. That means, as soon as a node which publishes a name goes offline, the IPNS hash cannot be resolved anymore.

IPNS names (records) *are* cached by the network (for ~24 hours, IIRC). That is, the network will remember that some IPNS name points to some ipfs path (`/ipfs/Qm....`) for approximately<sup>&dagger;</sup> 24 hours. However, the content to which the name points isn't cached (or "pinned" as we call it).

Really, you can't really expect random nodes on the network to store arbitrary data for free, a service like that would be abused out of existence.<sup>&ddagger;</sup> However, you can pay a pinning service to pin anything you want (you can find them via google). Whenever you update your website, you'd tell them to stop pinning the previous version of your website and to start pinning the new one.

We are working on a decentralized way to do this called Filecoin, a cryptocurrency where you can pay an *arbitrary* node in the network to provably store your content. However, Filecoin is still in early development so you should look into pinning services for now.

---

<sup>&dagger;</sup>While IPNS names are cached by a system called the DHT, if you get unlucky and all the nodes in the DHT storing your IPNS record forget it or go offline, you're IPNS record will disappear from the network until you republish it. It's a best effort system.

<sup>&ddagger;</sup>Technically, such services *do* exist, for example neocities.org. However, these are centralized services that can deal with abuse by, e.g., banning accounts.
