### ISSUE TITLE
feat: `ipfs bitswap` command

### ISSUE THREAD

**Issue by mappum** [ipfs/go-ipfs#437]
We're going to need to create the `ipfs bitswap` command.

**Subcommands:**
- `ipfs bitswap wantlist [<peer>]` - Displays a peer's wantlist, or our own if no peer provided
- `ipfs bitswap ledger <peer>` - Displays ledger info for a peer (debt ratio, amount of data exchanged, etc, could have a subcommand to reset a ledger or manually set values)
- `ipfs bitswap strategy` - Displays some info about the strategy in use (could have subcommands to adjust strategy settings)
#415 depends on this

**Comment by diasdavid** [comment]
Currently, we have: 

```bash
$ ipfs bitswap --help

    ipfs bitswap - A set of commands to manipulate the bitswap agent

SUBCOMMANDS:

    ipfs bitswap stat            - show some diagnostic information on the bitswap agent
    ipfs bitswap unwant <key>... - Remove a given block from your wantlist
    ipfs bitswap wantlist        - Show blocks currently on the wantlist

    Use 'ipfs bitswap <subcmd> --help' for more information about each command.
```

Currently `ipfs bitswap <peerId>` is behind the `-p` flag (ipfs bitswap -p <peerId>)

Still missing:
- [ ] ipfs bitswap ledger <peer> - Displays ledger info for a peer (debt ratio, amount of data exchanged, etc, could have a subcommand to reset a ledger or manually set values)
- [ ] ipfs bitswap strategy - Displays some info about the strategy in use (could have subcommands to adjust strategy settings)

**Comment by whyrusleeping** [comment]
I think we can close this, once we actually have bitswap strategies we can worry about a bitswap strategy subcommand
