### ISSUE TITLE
Error: manifest has unsupported version: 2 (we support 4)

### ISSUE THREAD

**Issue by leerspace** [ipfs/go-ipfs#4375]
#### Version information:

go-ipfs version: 0.4.12-rc2-
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2

#### Description:

The IPFS daemon fails to start after updating to v0.4.12-rc2. It fails with an error message saying

```
Initializing daemon...
Error: manifest has unsupported version: 2 (we support 4)
```

This looks like it might be coming from [badger](https://github.com/dgraph-io/badger/blob/master/manifest.go).

**Comment by leerspace** [comment]
It looks like the on-disk format for badger changed with #4364 and #4327. So this is probably expected.

**Comment by magik6k** [comment]
This is expected, there is a WIP tool for that - https://github.com/ipfs/badgerds-upgrade/pull/1 - if you really want to, you may give it a try:

* Build it
* Make sure your daemon isn't running
* Make a backup of `~/.ipfs` (or wherever your repo is)
* Run the tool

**Comment by magik6k** [comment]
Once https://github.com/ipfs/badgerds-upgrade/pull/1 gets merged I'll add a better error message to badgerds.

**Comment by leerspace** [comment]
That seemed to work without issues as far as I can tell. I've only run it so far on a mostly empty repository, but I can now use v0.4.12-rc2 on it!

Is this expected to be something that automatically gets run when v0.4.12 is released (if an older badger datastore is detected)? Or will it be a manual upgrade?

**Comment by whyrusleeping** [comment]
@leerspace as badger is currently experimental, it will not be run automatically. Moving forward though, this sort of thing will likely be included as a migration between versions. Now that datastores are user-configurable we need to look into more advanced upgrade management.

**Comment by leerspace** [comment]
Thanks for the info. I won't wait hold out for 0.4.12 with the expectation that it will be an automatic badger update and will instead update my nodes manually (using magik6k's badgerds-upgrade utility).

**Comment by magik6k** [comment]
Closing with https://github.com/ipfs/go-ipfs/pull/4379
