### ISSUE TITLE
Errors when make install 

### ISSUE THREAD

**Issue by Andlinks-Yourturn** [ipfs/go-ipfs#4376]
#### Type:
0.4.11

#### Description:
I  want to install ipfs by building from the source code. But, errors occur when make install in go-ipfs folder. It seems gx fail to download  iptb QmU4QKCqf79zWCDyBGhUjPDg4SoZTbtVP4XuZ9 .
How can I fix it? Thanks.

**Comment by Stebalien** [comment]
We're trying to move support questions to [discuss.ipfs.io](https://discuss.ipfs.io). Mind posting this issue there?
