### ISSUE TITLE
bitswap: Error writing block to datastore: mkdir 

### ISSUE THREAD

**Issue by scroot** [ipfs/go-ipfs#4404]
#### Version information:
go-ipfs version: 0.4.14-dev-
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2

#### Type:
Medium 

#### Description:

11:03:45.139 ERROR    bitswap: Error writing block to datastore: mkdir /disk/192.168.1.250/p2p/blocks/W6: no such file or directory bitswap.go:317
11:03:45.517 ERROR    bitswap: Error writing block to datastore: mkdir /disk/192.168.1.250/p2p/blocks/YQ: no such file or directory bitswap.go:317
11:03:45.749 ERROR    bitswap: Error writing block to datastore: mkdir /disk/192.168.1.250/p2p/blocks/B5: no such file or directory bitswap.go:317
11:03:46.966 ERROR    bitswap: Error writing block to datastore: mkdir /disk/192.168.1.250/p2p/blocks/QW: no such file or directory bitswap.go:317

**Comment by Stebalien** [comment]
Does your repo exist (`/disk/192.168.1.250/p2p`)? Did you delete your blocks directory?

**Comment by scroot** [comment]
##Thank you!
 there are other processes to remove this directory.
