### ISSUE TITLE
Excessive calls to gettimeofday() and select() on OSX

### ISSUE THREAD

**Issue by hmage** [ipfs/go-ipfs#4409]
#### Version information:
go-ipfs version: 0.4.13-cc01b7f
Repo version: 6
System version: amd64/darwin
Golang version: go1.9.2

#### Description:

While investigating why idle ipfs is eating 8% of CPU on OSX, I ran `syscallbypid.d` from dtrace toolkit for 5 seconds:
```
   PID CMD                      SYSCALL                     COUNT
 17122 ipfs                     getpeername                     1
 17122 ipfs                     pread                           1
 17122 ipfs                     sendto                          3
 17122 ipfs                     recvfrom                        4
 17122 ipfs                     getsockname                     5
 17122 ipfs                     sysctl                         40
 17122 ipfs                     stat64                        199
 17122 ipfs                     getsockopt                    505
 17122 ipfs                     kqueue                        653
 17122 ipfs                     bind                          718
 17122 ipfs                     connect                       734
 17122 ipfs                     socket                        739
 17122 ipfs                     write                        1293
 17122 ipfs                     close                        1446
 17122 ipfs                     setsockopt                   2193
 17122 ipfs                     fcntl                        2215
 17122 ipfs                     kevent                       4325
 17122 ipfs                     read                         6286
 17122 ipfs                     select                      11919
 17122 ipfs                     gettimeofday                98128
```

As you can see, while it calls connect(), socket() and bind() only about 700 times, and uses kqueue() for scheduling, it still somehow manages to use select() seventeen times more than that and 140x more calls to gettimeofday().

I don't know the source code, but I suspect that logging function calls gettimeofday() no matter what effective output log level is set, therefore all debug log calls that aren't printed still eat up CPU time.

Another suspect is that some third party library probably has their own event loop, and on top of that instead of querying gettimeofday() once at beginning of the cycle the code likely queries it many many times within the loop, even though time barely progresses at all, and such precision there isn't likely necessary.

If it's easily possible, I'd love if ipfs wasn't doing unnecessary syscalls.

**Comment by Stebalien** [comment]
There's probably nothing we can do about `select`, that's almost certainly go. As for `gettimeofday`, yes, we can probably reduce the number of calls. That could be:

* logging (as you say)
* timeouts (we set deadlines all over the place)
* bandwidth metrics

Actually, given the number of calls, I'm guessing bandwidth metrics. Try disabling them with `ipfs config --bool Swarm.DisableBandwidthMetrics true`.

**Comment by hmage** [comment]
Do I need to restart ipfs daemon?

Without restarting it made no effect.

After restart I'll need to wait until the same number of peers builds up before it happens. Will write right back with results.

**Comment by Stebalien** [comment]
> Do I need to restart ipfs daemon?

yes.

> After restart I'll need to wait until the same number of peers builds up before it happens. Will write right back with results.

You can actually get your node to connect to a bunch of peers by repeatedly calling `ipfs dht findprovs` on random IPFS hashes.

> As for timeouts, usually they are done via select() or kevent(). Could be the cause of so many select calls.

Probably. However, that's all done by go's runtime. We have very little control over that. One thing we *can* do is buffer better to reduce the number of IO related syscalls: https://github.com/ipfs/go-ipfs/issues/4280. That's something I plan on doing soon.

**Comment by hmage** [comment]
It did help somewhat, but not entirely:

```
   PID CMD                      SYSCALL                     COUNT
 88466 ipfs                     getpid                          1
 88466 ipfs                     accept                          2
 88466 ipfs                     getpeername                     3
 88466 ipfs                     sendto                          3
 88466 ipfs                     pread                           5
 88466 ipfs                     recvfrom                        6
 88466 ipfs                     getsockname                     8
 88466 ipfs                     sysctl                         10
 88466 ipfs                     getsockopt                     23
 88466 ipfs                     kqueue                         31
 88466 ipfs                     connect                        33
 88466 ipfs                     bind                           35
 88466 ipfs                     socket                         37
 88466 ipfs                     close                          56
 88466 ipfs                     setsockopt                    112
 88466 ipfs                     fcntl                         117
 88466 ipfs                     write                        1179
 88466 ipfs                     select                       3456
 88466 ipfs                     kevent                       4326
 88466 ipfs                     read                         5873
 88466 ipfs                     stat64                       6391
 88466 ipfs                     gettimeofday                53812
```

Number of `select` and `gettimeofday` calls has been reduced dramatically.

But, I can't attribute this to change of setting -- it could have been just because of restart and different peer activity. Number of peers is roughly the same.

**Comment by whyrusleeping** [comment]
I wonder if we're calling `time.After` and excessive amount somewhere again. This has come up in the past... It looks like youre running the 0.4.13 release (and not any commits since) so we can rule out the recent changes in libp2p.

I'm gonna go ahead and call this one a bug

**Comment by Kubuxu** [comment]
Looking at Golang's runtime, on darvin on x86 and x64 it should run `walltime()` functions that uses gettimeofday as fallback but if something is wrong and it instead would use `time_now()` functions it would call `gettimeofday()` every time.


Could you try building and profiling this program:

```
package main

import (
	"fmt"
	"time"
)

func main() {
	n := 1000000
	var t uint64
	for i := 0; i < n; i++ {
		t += uint64(time.Now().Unix())
	}
	fmt.Printf("total from %d runs: %d", n, t)
}
```

**Comment by hmage** [comment]
```
hmage@whmd:~$ mkdir -p temp/timenow
hmage@whmd:~$ cd temp/timenow
hmage@whmd:~/temp/timenow$ cat << EOF > timenow.go
<...skip...>
EOF
hmage@whmd:~/temp/timenow$ go build
hmage@whmd:~/temp/timenow$ sudo dtruss -b 1024M -c ./timenow
Password:
<...skip...>
write(0x1, "total from 1000000 runs: 1511363254959970\0", 0x29)		 = 41 0
select(0x0, 0x0, 0x0, 0x0, 0xC420039F18)		 = -1 Err#4

CALL                                        COUNT
bsdthread_register                              1
close                                           1
exit                                            1
open                                            1
read                                            1
write                                           1
stat64                                          2
sysctl                                          2
bsdthread_create                                4
mmap                                            8
sigaltstack                                    10
__pthread_sigmask                              14
sigaction                                      50
select                                       1574
gettimeofday                               929470

hmage@whmd:~/temp/timenow$ go version
go version go1.9.2 darwin/amd64
hmage@whmd:~/temp/timenow$ uname -a
Darwin whmd 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
```

**Comment by hmage** [comment]
Number of calls will be lower than actual because dtrace uses buffer size and if it overflows faster than it can print them out, it will skip syscalls and let the program continue running.

**Comment by Kubuxu** [comment]
Looking at the runtime once more, on darvin Golang does not cache/use alternative method time in any way.

In case of Linux, no syscalls are called to get time and the syscall calls look like this:
```
      1 arch_prctl
      1 execve
      1 exit_group
      1 gettid
      1 munmap
      1 readlinkat
      1 sched_getaffinity
      1 write
      2 sigaltstack
      3 clone
      3 futex
      8 mmap
      8 rt_sigprocmask
    114 rt_sigaction
```

I am not sure if darvin provides alternative method for getting time and even if it does it would have to be adopted by Golang runtime.

**Comment by hmage** [comment]
That's because on Linux, unlike Darwin and *BSD, has a vDSO optimization for `gettimeofday`. It is not a real syscall, it's code provided by kernel that programs run in userspace -- https://lwn.net/Articles/446528/

If you disable that on Linux, you'll get similar picture.

This might be the reason why this excessive usage of gettimeofday was never noticed until now in Go, since Go is very linux-centric.

**Comment by hmage** [comment]
Either way, one way to mitigate this is to reduce amount of calls to `time.Now()` within the event loop by calling it once and caching the result until you go back to sleep through golang's equivalent of select().

**Comment by Stebalien** [comment]
> event loop

We don't have any control over this, it's built into go. From our perspective, we just have a bunch of lightweight threads.

> slow time on osx

Are you running High Sierra? Looks like a bug: https://github.com/golang/go/issues/22037

That should be fixed in go 1.10.

Note: we should still work on improving this.

**Comment by Stebalien** [comment]
Also note: FreeBSD now has VDSO timeofday support (although go may not use it yet). Apple puts frustratingly little effort into modernizing darwin.

**Comment by Kubuxu** [comment]
It seems to be resolved in 1.10: https://github.com/golang/go/issues/22601

**Comment by Kubuxu** [comment]
@hmage mind giving a dev version using Go 1.10 a try?

**Comment by Stebalien** [comment]
> Apple puts frustratingly little effort into modernizing darwin.

(actually, while generally true, it appears that Apple *does* provide a syscall-less way to get the time).

**Comment by hmage** [comment]
> @hmage mind giving a dev version Go 1.10 a try?

Couldn't find any snapshot that's explicitly versioned as 1.10, so I went ahead and built current master branch of go, after that I'm having issues building ipfs with current go head:
```
fatal: Invalid 'go version' output: go version devel +88599f184d Wed Nov 22 20:27:00 2017 +0000 darwin/amd64
```

When doing `make build`.

Therefore, I can't check it on go 1.10 yet.

**Comment by whyrusleeping** [comment]
@hmage instead of running make build, try:
```
go build ./cmd/ipfs
```

And if it complains about gx dependencies, do:
```
go get github.com/whyrusleeping/gx
go get github.com/whyrusleeping/gx-go
gx install
go build ./cmd/ipfs
```

**Comment by whyrusleeping** [comment]
We need to fix our scripts to handle dev versions of go better.

**Comment by hmage** [comment]
Using head of go shows definitely an improvement for `gettimeofday`:
```
hmage@iiHMD:~$ sudo syscallbypid.d
Tracing... Hit Ctrl-C to end.
^C
   PID CMD                      SYSCALL                     COUNT
 75115 ipfs                     mmap                            5
 75115 ipfs                     pread                           5
 75115 ipfs                     sysctl                         22
 75115 ipfs                     getsockopt                     25
 75115 ipfs                     bind                           30
 75115 ipfs                     connect                        30
 75115 ipfs                     kqueue                         30
 75115 ipfs                     socket                         30
 75115 ipfs                     fcntl                          90
 75115 ipfs                     setsockopt                     90
 75115 ipfs                     stat64                        110
 75115 ipfs                     close                         258
 75115 ipfs                     write                         516
 75115 ipfs                     kevent                       1899
 75115 ipfs                     read                         3097
 75115 ipfs                     select                       3432
hmage@iiHMD:~$ ipfs swarm peers | wc -l
     617
hmage@iiHMD:~$ ipfs version --all
go-ipfs version: 0.4.13-cc01b7f1
Repo version: 6
System version: amd64/darwin
Golang version: devel +571ee0436f Thu Nov 23 00:34:48 2017 +0000
```

Number of peers isn't completely up to previous runs, and activity could be less than reported before, but `gettimeofday` is gone.

`select` could be down because of disabled bandwidth metrics, or lower number of actively talking peers.

**Comment by whyrusleeping** [comment]
@hmage also try setting `IPFS_REUSEPORT` to "false" before running the daemon. Its very likely our tcp reuseport code is the culprit of those selects

**Comment by Kubuxu** [comment]
If `IPFS_REUSEPORT=false` solves it, I think we can open issue about migrating go-reuseport to Go 1.10 Socket Control API and close this one.

**Comment by hmage** [comment]
Seems like `IPFS_REUSEPORT=false` has no effect:

```
   PID CMD                      SYSCALL                     COUNT
  1141 ipfs                     getpeername                     1
  1141 ipfs                     getsockopt                      1
  1141 ipfs                     accept                          2
  1141 ipfs                     pread                           3
  1141 ipfs                     sendto                          3
  1141 ipfs                     bind                            4
  1141 ipfs                     recvfrom                        4
  1141 ipfs                     getsockname                     6
  1141 ipfs                     sysctl                          8
  1141 ipfs                     connect                        10
  1141 ipfs                     close                          13
  1141 ipfs                     socket                         14
  1141 ipfs                     setsockopt                     25
  1141 ipfs                     fcntl                          45
  1141 ipfs                     write                         776
  1141 ipfs                     kevent                       2608
  1141 ipfs                     select                       3928
  1141 ipfs                     read                         3957
  1141 ipfs                     stat64                      11412
```

Number of `select` calls remains relatively same for a 5-second period with same number of peers as in previous reports after disabling bandwidth metrics.

PS: On another note, number of `stat64` calls is strange -- dtruss shows that it's trying to `stat64` files that don't actually exist in very large number, example path `/Users/hmage/.ipfs/blocks/4S/CIQLAPOJ6PTRWAEM2TIRZNURTRYX5JBLO2HDJJXV4ACMLTHHDABI4SA.data` -- could it be that some peer is requesting blocks that aren't marked as available in leveldb but ipfs would still stat the block's location just in case?

**Comment by Kubuxu** [comment]
We don't keep track of blocks in level DB.
To reduce it you can enable Bloom filter hash cache with `Datastore.BloomFilterSize`, its size depends on how many blocks you are storing but few 100k should be safe starting value.

**Comment by Stebalien** [comment]
So, we've replaced the metrics library. The only thing left is to wait for go 1.10.

**Comment by Kubuxu** [comment]
It seems that number of select and read calls is close to the same which would hint that it is normal behaviour of fd event loop. Nothing we can do there apart from reducing number of peers/DHT queries we get.

**Comment by hmage** [comment]
@Kubuxu yeah, last profile is much better than in the first post.

**Comment by hmage** [comment]
1.10 is out.

**Comment by Kubuxu** [comment]
@hmage do you think we can close this issue? Next release is very near (today or in few days) and it should be built using 1.10?

**Comment by hmage** [comment]
Well, since I tested on unreleased 1.10 and this was fixed there, I'm all for it.
