### ISSUE TITLE
sharness tests flaky: API file doesn't show up

### ISSUE THREAD

**Issue by keks** [ipfs/go-ipfs#4417]
Recently (probably after my cmds PR got merged) the sharness tests have become quite flaky. I have searched some test logs and very often the issue was that the test fails because the api file does not show up in time. Often times simply rebuilding helps, but "rebuild til tests pass" is terrible advice.

Here's a list of tests failing under similar conditions:

search for `not ok 12 - api file shows up`:
- https://ci.ipfs.team/job/go-ipfs/job/PR-4047/100/consoleText
- https://ci.ipfs.team/job/go-ipfs/job/cleanup%2Fdead-cmds-code/1/consoleText

search for `not ok 27 - api file shows up`:
- https://ci.ipfs.team/job/go-ipfs/job/fix%2Fflaky-sharness-api-file/2/consoleText

search for `not ok 18 - api file shows up`:
- https://circleci.com/api/v1.1/project/github/ipfs/go-ipfs/8365/output/19/1?file=true

(feel free to extend)

I'll try to research it, maybe the best way forward for now is to increase the timeout.

**Comment by keks** [comment]
Relate but out of scope: [flaky go test](https://ci.ipfs.team/blue/organizations/jenkins/go-ipfs/detail/fix%2Fflaky-sharness-api-file/3/pipeline/)

**Comment by keks** [comment]
I ran it a few times with a timeout of 1s instead of 100ms and it didn't show up. I'll try 200ms tomorrow.

**Comment by magik6k** [comment]
This may be related to slower Jenkins worker (travis/circle/old jenkins have/had quite powerful workers).

Note that the timeout is 2s (20 * 100ms) - https://github.com/ipfs/go-ipfs/blob/master/test/sharness/lib/test-lib.sh#L215, increasing the time parameter will slow down the sharness tests quite considerable

Linked https://github.com/ipfs/go-ipfs/pull/4411#issuecomment-346141045

**Comment by Stebalien** [comment]
Increasing these timeouts really shouldn't slow down the tests in the non-failure case. `test_wait_for_file` won't wait the full timeout unless the file doesn't show up.

**Comment by keks** [comment]
@Stebalien the test loops over a 100ms wait and then checks whether the file is there for 20 times. That means that if I increase the 100ms to 1s, it will always wait multiples of 1s instead of 100ms. Instead I should increase the number of iterations.

**Comment by Stebalien** [comment]
> @Stebalien the test loops over a 100ms wait and then checks whether the file is there for 20 times. That means that if I increase the 100ms to 1s, it will always wait multiples of 1s instead of 100ms. Instead I should increase the number of iterations.

Ah. I assumed that was a delay. I'd just make it a delay rather than the number of iterations. That's what we care about (shortest timeout, longest timeout).

**Comment by michaelavila** [comment]
Closing as I've looked through a handful of the latest sharness test runs and I see no indication that we are still experiencing this issue. Reopen if you can find a recent instance.
