### ISSUE TITLE
Use GOOS to build on all platforms

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4427]
`make test_short` (and CI builds) should try building on other operating systems to make sure that ipfs at least builds. That is, we should run, e.g., `GOOS=windows go build` in `cmd/ipfs`.

**Comment by whyrusleeping** [comment]
we used to do this: https://github.com/ipfs/go-ipfs/pull/2611/files

**Comment by Stebalien** [comment]
Removed in #3504. @Kubuxu?

**Comment by Kubuxu** [comment]
Looks like it: https://github.com/ipfs/go-ipfs/pull/3504/files#diff-b67911656ef5d18c4ae36cb6741b7965L148

It was not being used by CI as we never run this target AFAIK.
