### ISSUE TITLE
Document cmdkit's global options

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#4432]
#### Description:

The global options declared by cmdkit should be documented on the root command, and on all other commands.

See https://github.com/ipfs/go-ipfs-cmdkit/blob/f3631e8ddde711a7aefed041806902d907a1f9ae/option.go#L22-L30

People keep asking about e.g. `--timeout` :)

**Comment by keks** [comment]
Good point. I'd like to defer this until I got to moving the definitions to go-ipfs-cmds (already happened in my working branch) so avoid the possibilty of forgetting to update the docs.

Also at the moment the global options are defined [here](https://github.com/ipfs/go-ipfs-cmds/blob/master/command.go#L287-L291) and implicitly applied [here](https://github.com/ipfs/go-ipfs-cmds/blob/master/command.go#L160) so no wonder nobody knows what's going on. In my working branch `globalOptions` is gone and the options are instead options of the root command.

**Comment by keks** [comment]
Whoops, must have "slipped on the mouse"...

**Comment by lgierth** [comment]
Code-wise it doesn't *have* to be on the root command, I just meant `ipfs --help` and `ipfs foo --help`.

> Whoops, must have "slipped on the mouse"...

Mausrutscher eh?

**Comment by kevina** [comment]
I just marked this as P1.  I don't have the global options memorized and have to keep digging in the source code to figure them out, of which where they are defined is non-obvious.

**Comment by michaelavila** [comment]
I think this is also important. I was recently supporting someone in the community that was running into issues and we solved them using the `--offline` flag which is global and not documented in a way that's easy to learn about.

**Comment by michaelavila** [comment]
Closing as I see these flags listed when I run `ipfs --help`
