### ISSUE TITLE
This is not go-gettable.

### ISSUE THREAD

**Issue by docmerlin** [ipfs/go-ipfs#4448]
This dependency is NOT go-gettable.

https://github.com/ipfs/go-ipfs/blob/bc7124226c1ddf8ce814121ef9e1162340e2d9e3/namesys/dns.go#L10

**Comment by whyrusleeping** [comment]
A lot of our dependencies arent go-gettable, check the build/install instructions in the readme: https://github.com/ipfs/go-ipfs#build-from-source
