### ISSUE TITLE
gx 0.4.13 release?

### ISSUE THREAD

**Issue by b5** [ipfs/go-ipfs#4478]
#### Version information:
0.4.13
#### Type:
Docs
#### Severity:
Low
#### Description:
can't find a gx release of 0.4.13, is one out there? kthxbye

**Comment by lgierth** [comment]
Oops, yeah, that should be part of the release checklist: https://github.com/ipfs/go-ipfs/blob/master/docs/releases.md

**Comment by b5** [comment]
although I'm def not the right person to be doing gx releases, rewinding to commit `cc01b7f188622e7148ce041b9d09252c85041d9f` & running `gx publish` gave me `/ipfs/QmViBzgruNUoLNBnXcx8YWbDNwV8MNGEGKkLo6JGetygdw`. 
currently have this hash pinned to a qri gateway PR-able branch [here](https://github.com/qri-io/go-ipfs/tree/gx-0.4.13), but I totally understand if releases need to be in-house 🙂

**Comment by Stebalien** [comment]
@b5 I get the same hash.
