### ISSUE TITLE
Error starting a private network

### ISSUE THREAD

**Issue by jyang** [ipfs/go-ipfs#4490]
#### Description:

https://discuss.ipfs.io/t/error-when-set-ipfs-private-network/1393

**Comment by leerspace** [comment]
If you can provide specific steps to reproduce I'd be happy to see if I also get the issue. Given that [the instructions](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks) have worked for [others](https://discuss.ipfs.io/t/ipfs-based-manufacturing-execution-system/1648/6), it would be helpful to know what exact steps were taken to get this error.

**Comment by Kubuxu** [comment]
I think it might be an issue with line ends. I think multicodec parser only accepts `/n` and not `/r/n`. It can be fixed either in `go-multicodec` or by changing go-libp2p-pnet not to use it.

**Comment by psprings** [comment]
@leerspace I am seeing what I presume to be the same issue as @jyang with the following:

**IPFS version**: 0.4.13
**Docker version**: Version 18.02.0-ce-rc2-win51 (15631)
**OS**: Edition - Windows 10 Pro / Version - 1709 / OS Build - 16299.248

```bash
$ docker run --rm -it --entrypoint /bin/sh ipfs/go-ipfs
/ # ipfs init
initializing IPFS node at /data/ipfs
generating 2048-bit RSA keypair...done
peer identity: QmcV7eFBQWC8EHgRaW8VtbvM2c9AcEBShJn48mit95gvTz
to get started, enter:

        ipfs cat /ipfs/QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv/readme

/ # echo 'e0e7b1394fb6e928eecf2f8db77eaa99d3657684dc939519f285cb902bd93e22' > /data/ipfs/swarm.key
/ # ipfs bootstrap rm --all
/dnsaddr/bootstrap.libp2p.io/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN
/dnsaddr/bootstrap.libp2p.io/ipfs/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa
/dnsaddr/bootstrap.libp2p.io/ipfs/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb
/dnsaddr/bootstrap.libp2p.io/ipfs/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt
/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM
/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64
/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu
/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd
/ip6/2400:6180:0:d0::151:6001/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu
/ip6/2604:a880:1:20::203:d001/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM
/ip6/2604:a880:800:10::4a:5001/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64
/ip6/2a03:b0c0:0:1010::23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd
/ # ipfs daemon
Initializing daemon...
22:25:55.302 ERROR   cmd/ipfs: error from node construction: psk header error: multicodec did not match daemon.go:320
Error: psk header error: multicodec did not match
```

This happens whether I:
* Volume mount to `/data/ipfs/swarm.key`
* COPY to `/data/ipfs/swarm.key` via a `Dockerfile`
* `echo` contents to file (as shown above)

For contrast:
```bash
$ docker run --rm -it --entrypoint /bin/sh ipfs/go-ipfs
/ # ipfs init
initializing IPFS node at /data/ipfs
generating 2048-bit RSA keypair...done
peer identity: QmPQHY7paJBQG7CDNB67aF63ZuacNViBAdSE7bXw3vBM42
to get started, enter:

        ipfs cat /ipfs/QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv/readme

/ # ipfs daemon
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.3/tcp/4001
Swarm listening on /p2p-circuit/ipfs/QmPQHY7paJBQG7CDNB67aF63ZuacNViBAdSE7bXw3vBM42
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/172.17.0.3/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
```

**Comment by RegEM** [comment]
I briefly had the same problem. On my windows machine, I changed file saving line type to unix. Using Textpad as editor. 

On to the next issue: 'Republisher failed to republish: failed to find any peer in table core'

**Comment by ssdubey** [comment]
I had the similar issue in Ubuntu machine. I reinforced `\n` between the three lines of the swarm.key file by bringing them in same line and pressing `enter`. It worked fine after that.

**Comment by Kubuxu** [comment]
As a stopgap measure, consider using `dos2unix` utility to make sure that `swarm.key` is in Unix format:
```bash
dos2unix swarm.key
```

**Comment by Stebalien** [comment]
This is fixed in the latest go-ipfs master.
