### ISSUE TITLE
Application panics because both x/net/trace and go-net/trace are imported

### ISSUE THREAD

**Issue by joesis** [ipfs/go-ipfs#4491]
#### Version information:
go-ipfs version: 0.4.14-dev-cca71b6db
Repo version: 6
System version: amd64/darwin
Golang version: go1.9.1

#### Description:

`go-ipfs` indirectly uses a variation of `golang.org/x/net/trace` serving from IPFS. When `golang.org/x/net/trace` is used in a project which also uses `go-ipfs`, the binary simply panics. Package conflict is a general issue of Go. In some cases, it does nothing more than increased binary size, but it's tricky in this case and there seems no easy workaround.

```
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x6148b40, 0x525de24, 0xf, 0x5c73dc0, 0x54f3660)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2274 +0x8e2
net/http.(*ServeMux).HandleFunc(0x6148b40, 0x525de24, 0xf, 0x54f3660)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2306 +0x63
net/http.HandleFunc(0x525de24, 0xf, 0x54f3660)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2318 +0x69
gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/trace.init.0()
	/Users/joesis/go/src/gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/trace/trace.go:110 +0x50
gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/trace.init()
	<autogenerated>:1 +0x6e7
gx/ipfs/Qme3aYm74r4gyMjtZTXpopHkBA6qjU21LXJy4GF56pLkW8/badger.init()
	<autogenerated>:1 +0xcd
gx/ipfs/QmPhe5Agy6FW8nyFXdphtAVPrmmPFN18pCrtpnRzMWa4Vi/go-ds-badger.init()
	<autogenerated>:1 +0xaa
github.com/ipfs/go-ipfs/repo/fsrepo.init()
	<autogenerated>:1 +0xd7
```

**Comment by Stebalien** [comment]
We use GX to manage dependencies to work around both this problem and the problem of avoiding breaking changes. Basically, it allows us to put all of our deps in ipfs and then reference them by hash. Unfortunately, this means you *can't* "do both" (use non-gxified packages with a gxified package).

We leave most of our libraries in the normal "ungxified" state however, go-ipfs is really meant to be an application, not a library, so we leave it in the "gxified" state (where all import paths are rewritten to point to `gx/ipfs/QmId...` locations).

If you'd still like to use go-ipfs itself in your application: before building your project, call `gx-go uw && go get ./...` in the go-ipfs package. This will replace all the `gx` paths with the upstream repo paths and fetch the required dependencies.

However, a better solution would be to find what you need and help us extract it. Do you really need *all* of go-ipfs?

**Comment by joesis** [comment]
Thanks, @Stebalien! It worked. For now, full-featured IPFS node in the main process is exactly what we want, though fine-grained tuning may come later.

I'm probably among very few ppl running into this, as there's no existing issue about it, but if there are more ppl, it would be good to have the instructions in README to save time on both ends.

Thanks again
