### ISSUE TITLE
Switch to mr-tron's base58 library

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4500]
Our current one is obscenely inefficient. In our current library, a *single* encode/decode round trip does 238 mallocs (versus 6 in mr-tron's library) and takes ~6x~ *8-10x (small optimizations go a long way in inner loops)* longer.

repo: [mr-tron/base58](https://github.com/mr-tron/base58)

~Waiting on mr-tron/base58#7 (custom alphabet support).~

---

Any objections? I plan to switch both the multibase library and the multihash library.

**Comment by dignifiedquire** [comment]
yes please, checked the library looks pretty good to me

**Comment by Stebalien** [comment]
Done.
