### ISSUE TITLE
Possibility to set the path of IPFS via the command line and not only from environment variable %IPFS_PATH%

### ISSUE THREAD

**Issue by gdeverlant** [ipfs/go-ipfs#4504]
#### Description:

Hi,

my request is really simple: is there a way to initialize the daemon or normal init for ipfs by specifying the root path for external HD?

**Comment by Stebalien** [comment]
Currently, no. We could add a command line flag but is there any reason not to just use the environment variable? You can set it temporarily if you want.

**Comment by leerspace** [comment]
You could also create a symbolic link from the default IPFS path and point it to an external HD somewhere. That's what I currently do on 2 linux nodes and 1 Windows node and it works well.

**Comment by gdeverlant** [comment]
Actually I'm trying to implement ipfs with my non-linear video editor. It runs on Windows and Mac and there are not Admin privileges because it is a captive runtime with no installation. I'm able to launch Native Processes and there's no possibility for Environment variable setup.

**Comment by kpcyrd** [comment]
```
IPFS_PATH=/mnt/somewhere/ ipfs daemon
```

You do not need admin privileges or any kind of changes to the system to set environment variables when starting a program. Check the documentation of the function you use to start the process, those usually accept an argument for an environment to use.

**Comment by gdeverlant** [comment]
I'm running on Windows and MacOS and there is no possibility for me to add anything in front of the ipfs executable like you mentioned IPFS_PATH=/mnt/somewhere/ ipfs daemon.

I'm using an API which allows me to launch an executable like this : https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/desktop/NativeProcess.html#includeExamplesSummary

```
var processArgs:Vector.<String> = new Vector.<String>();
processArgs[0] = "--init";
processArgs[1] = "--rootPath";
processArgs[2] = "--G:\ipfs";
```

That's why I think this option will be useful.

**Comment by gdeverlant** [comment]
I could find a workaround by launching cmd.exe and then setting the path set IPFS_PATH=G:\ipfs and then
launching the ipfs init + ipfs daemon which works.
