### ISSUE TITLE
Disable pedantic codeclimate checks

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4513]
Codeclimate got a bit more opinionated recently: https://codeclimate.com/github/ipfs/go-ipfs/pull/4471

We should disable the cognitive complexity checks, as well as the 'similar blocks of code' checks, as they tend to be pretty useless.

**Comment by vyzo** [comment]
amen for that -- "no, your function has more than 4 returns" is just pointless.

**Comment by michaelavila** [comment]
Closing as I see that `method-complexity` and `similar-code` checks are disabled in config here: https://github.com/ipfs/go-ipfs/blob/master/.codeclimate.yml
