### ISSUE TITLE
File is not deleted/removed, it jumps to Main page/home page

### ISSUE THREAD

**Issue by slrslr** [ipfs/go-ipfs#4522]
#### Version information:
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/windows
Golang version: go1.9.2

#### Type:
Bug

#### Severity:
High

#### Description:
When i add new file via: http://localhost:5001/ipfs/StringHere/#/files
It shows a message that the file was added, but the file list was not updated. When i reload page (Ctrl+F5), then i see the file. Then i click X button next to the file to delete/remove it.
It instantly redirect me to the page: http://localhost:5001/ipfs/StringHere/#/
When i go to Files: http://localhost:5001/ipfs/StringHere/#/files
The file is still there (not removed even i hit remove X button), even after Ctrl+F5 and after i stop ipfs daemon and start it again (ipfs daemon --init), the file is still there.
I am using up to date Firefox 57.0.2 (64-bit)

**Comment by Stebalien** [comment]
The webui in the current release is, unfortunately, quite buggy. The next go-ipfs release will include a newer, less-buggy webui release which shouldn't exhibit this bug. We'll revisit this bug after the release (which shouldn't be too far off).

**Comment by leerspace** [comment]
Related issue: ipfs-shipyard/ipfs-webui/issues/607

**Comment by leerspace** [comment]
I think this should be addressed now (if not fixed). I'm not sure the webui in v0.4.15 even shows pins anywhere now.
