### ISSUE TITLE
Building for iOS with gomobile fails with: undefined: syscall.O_DSYNC

### ISSUE THREAD

**Issue by wehriam** [ipfs/go-ipfs#4524]
#### Version information:

N/A

#### Type:

Bug

#### Severity:

Low

#### Description:

Building for iOS with gomobile fails with an `undefined: syscall.O_DSYNC` error associated with [Badger](https://github.com/dgraph-io/badger), see [lines 23-25](https://github.com/dgraph-io/badger/blob/master/y/file_dsync.go#L23-L25).

Compiling with Go 1.10 beta throws the same error.

```
saucer:ipfs-ios wehriam$ gomobile build -target=ios github.com/ipfs/go-ipfs/cmd/ipfs
gomobile: go build -pkgdir=/Users/wehriam/go/pkg/gomobile/pkg_darwin_arm -tags ios -o=/var/folders/2s/cx9fndsd5md4yxcrx6z50rch0000gn/T/gomobile-work-919090730/arm github.com/ipfs/go-ipfs/cmd/ipfs failed: exit status 2
# gx/ipfs/QmXtSA4dxoDKMzhHkwqeoBoBYASov1ZWnLQo38juKNbe3z/badger/y
../../go/src/gx/ipfs/QmXtSA4dxoDKMzhHkwqeoBoBYASov1ZWnLQo38juKNbe3z/badger/y/file_dsync.go:24:21: undefined: syscall.O_DSYNC
```

```
saucer:ipfs-ios wehriam$ go version
go version go1.9.2 darwin/amd64
```

```
saucer:ipfs-ios wehriam$ gomobile version
gomobile version +50b7067 Sun Dec 17 15:46:28 2017 +0000 (android,ios); androidSDK=/Users/wehriam/Library/Android/sdk/platforms/android-26
```

```
saucer:ipfs-ios wehriam$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wehriam/go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2s/cx9fndsd5md4yxcrx6z50rch0000gn/T/go-build097124384=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

```
saucer:ipfs-ios wehriam$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.1 (17B1003)
      Kernel Version: Darwin 17.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: saucer
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 6 days 23:51
```

#### Thanks:

Huge thanks to the contributors and maintainers of the go-ipfs project and IPFS community at large. You do great work with huge impact.

**Comment by wehriam** [comment]
See also:

- issue building ipfs for ios - https://github.com/ipfs/go-ipfs/issues/4210
- cmd/link: use libsystem_kernel.dylib or libSystem.dylib for syscalls on macOS -
 https://github.com/golang/go/issues/17490
- Integrate ipfs to ios, the app crashed after enter background exceed 7 minutes https://github.com/ipfs/go-ipfs/issues/2994
- gomobile building for Android https://github.com/ipfs/go-ipfs/issues/2816

**Comment by Stebalien** [comment]
There was an issue in badger and has been recently fixed. Unfortunately, the recent fix wasn't quite correct. The new fix is at https://github.com/dgraph-io/badger/pull/378. Once that gets merged, we'll bubble it up to here.

* #4210 has been fixed (forgot to close it).
* We have no information on that crashing issue so we can't really debug it. It may have already been fixed, for all we know (it has been a year).
* With regards to the android issue, I believe the reporter was trying to use go-ipfs as a library.

**Comment by wehriam** [comment]
Thanks @Stebalien - just mentioned those others for your reference in case they were helpful in resolving this one.

**Comment by Stebalien** [comment]
@magik6k this has now been fixed in badger. Mind updating `go-ds-badger`?

**Comment by magik6k** [comment]
So you can now close issues cross-repo, fun.. Keeping this open until it's in merged to master.

@Stebalien mind including this in https://github.com/ipfs/go-ipfs/pull/4610?

**Comment by Stebalien** [comment]
@magik6k done.
