### ISSUE TITLE
ipfs add got stuck (general no-progress oddities)

### ISSUE THREAD

**Issue by jcaesar** [ipfs/go-ipfs#4556]
#### Version information:
go-ipfs version: 0.4.13-3b16b74
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2

#### Description:

I did an `ipfs add -r --pin=false /somedir`, which finished quite quickly, since I'd run the command before. Then I did a `ipfs add -r /somedir`, which printed the hash of `/somedir`, but did not terminate for about half a day. After some discussion with @lgierth, I tried restarting the docker container with the node, and tried `ipfs pin add --progress /ipfs/QmSomedir`, which didn't show any progress. The folder is 2GB, 20k files, and the root dir contains about 9.5k files.

I collected [information](https://ipfs.io/ipfs/QmZ7KWNrtbzs6Jg7zqjwF9wYrWbegzDH2PeRLeEjDX63ry) as per https://github.com/ipfs/go-ipfs/blob/master/docs/debug-guide.md#beginning
At the time of the collection, I had exactly one unrelated add command running (was unfortunately started automatically), all other cmds should have been stopped.

Weirdly, restarting the node/ipts docker container did not resolve the issue. Restarting the underlying VM did.

(If in doubt, I'd close this bug report without thinking about it too much. I have weird problems on a daily basis, and it's gone.)

**Comment by Stebalien** [comment]
Thanks for reporting this. Do you have GC enabled?

**Comment by Stebalien** [comment]
This could be https://github.com/ipfs/go-ipfs/issues/4561 (maybe). That's why I asked about GC.

**Comment by jcaesar** [comment]
I do not think I do. [$ ipfs config show](https://ipfs.io/ipfs/QmVwqSTRN4x27cNVmdFyaJ8ZiCiAiBRMEk1CswMZPtyZpM).

**Comment by Stebalien** [comment]
Nevermind. I found a deadlock in that trace.

**Comment by Stebalien** [comment]
Wait, no. That's just really high lock contention.

How do you start your daemon? Also, it may just be swapping... (we fixed a bug when adding lots of small files recently). How did memory usage look (if you recall)? That would also explain the insane lock contention.

**Comment by jcaesar** [comment]
The daemon was running in the docker container by jbenet, invoked as `ipfs daemon --migrate=true`. I gave it a memory limit of 2GB, and I recall that docker said it's using more than 90% of it. I don't have swap on that machine because it makes more trouble than it fixes, imho.

**Comment by Stebalien** [comment]
Hm. The memory limit may have been the issue then. We should have a new release very soon and I think it'll likely fix this issue.

**Comment by jcaesar** [comment]
(I haven't see this again with the newer versions, so I suppose this could be closed.)

**Comment by Stebalien** [comment]
Good to hear.
