### ISSUE TITLE
ipfs add's maybePauseForGC assumes that locks are fair

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4560]
They aren't guaranteed to be. We should consider, e.g., sleeping if pausing for GC.

**Comment by schomatis** [comment]
@Stebalien Would you mind elaborating a bit more on this issue? (to see if I could work on it.)

**Comment by Kubuxu** [comment]
@Stebalien given improvements to locks fairness in Go 1.9 (IIRC), I am not sure if it a problem. See https://github.com/golang/go/issues/13086

**Comment by Stebalien** [comment]
Actually... It looks like this isn't an issue for rwlocks as locking for *writing* prevents any new read-locks from being acquired.

@schomatis my worry was that we unlock/relock in quick succession and might not give something else waiting on the lock to actually acquire it. However, that's not an issue as writers on rwlocks prevent any new read locks from being taken when blocked on acquiring the write lock.
