### ISSUE TITLE
The add command's addAllAndPin function doesn't hold the pin lock

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4561]
While the file adder *does* hold the pin lock while adding a single file, the outer `addAllAndPin` function doesn't. This means that we can GC between adding and pinning.

**Comment by schomatis** [comment]
@Stebalien Is someone working on this? I'm interested to learn more about the locking system while adding/pinning, as it's something I stumbled upon while working on #4650.

**Comment by Stebalien** [comment]
Nope. All yours!

**Comment by schomatis** [comment]
@Stebalien The exported [`AddFile`][ADDFILE_EXPORTED] function is just a wrapper for the internal `addFile` function while also holding the pin lock, and it's only used by [`addAllAndPin`][ADDALLANDPIN] (in the `ipfs add` command). I think the logic of `addAllAndPin` should belong to the `Adder` and not to the `ipfs add` command (as the latter it's taking more responsability than it should about the add/pin logic). In this way `addAllAndPin` could directly use the `addFile` internal function while holding the pin lock all the way (including the call to `PinRoot`).

So the proposal would be:

1. Move `addAllAndPin` inside the `Adder` (in `coreunix`), replacing the call to `AddFile` with `addFile`.

2. Copy the pin lock logic from `AddFile` to `addAllAndPin` covering the calls to `addFile` and `PinRoot`.

3. (optional) Eliminate `AddFile` which doesn't seem to be used anywhere outside `addAllAndPin` (and some tests).


[ADDFILE_EXPORTED]: https://github.com/ipfs/go-ipfs/blob/de92ff69614d1d2d0ba0e640e0784a98eae435d1/core/coreunix/add.go#L428

[ADDALLANDPIN]: https://github.com/ipfs/go-ipfs/blob/de92ff69614d1d2d0ba0e640e0784a98eae435d1/core/commands/add.go#L295

As side note, I'm having trouble understanding the purpose of [`PinLock`][PINLOCK]. Its name and comment seem to imply that someone who grabs that lock will use it to pin content, but the lock (that seems more related to the GC than the pin/add functionality) is commonly used just for add operations (that don't pin while holding this lock), e.g., `AddFile`, [`AddR`][ADDR] and [`AddWrapped`][ADDWRAPPED]. 

[PINLOCK]: https://github.com/ipfs/go-ipfs-blockstore/blob/b0f4743fbd48e24e3e208ee99730d07b42fa8181/blockstore.go#L68-L72
[ADDR]: https://github.com/ipfs/go-ipfs/blob/de92ff69614d1d2d0ba0e640e0784a98eae435d1/core/coreunix/add.go#L331

[ADDWRAPPED]: https://github.com/ipfs/go-ipfs/blob/de92ff69614d1d2d0ba0e640e0784a98eae435d1/core/coreunix/add.go#L367

**Comment by Stebalien** [comment]
> Its name and comment seem to imply that someone who grabs that lock will use it to pin content, but the lock (that seems more related to the GC than the pin/add functionality)

You're right, it's a "don't GC" lock.

---

So, being able to add individual files is nice. We'll want to discuss this a bit before we get rid of that ability.

Ideally, anything added with the adder should be temporarily pinned until we call `Finalize`. At *that* point, we should remove the temporary pin add a *real* pin if `adder.Pin` was set. Unfortunately, we don't have a temporary pin system at the moment (although we desperately need one and it would allow us to get rid of the pin lock entirely).

@lgierth any opinions on this API?

**Comment by kjzz** [comment]
hey @schomatis , are you still doing for this?if you do not finish, maybe i can help.because i am learn more about the add/pin.So i think maybe i can have  a try.

**Comment by schomatis** [comment]
Great! But we should first check with @Stebalien the status of this issue

**Comment by kjzz** [comment]
Thx a lot @schomatis. If this issue is still pending,please ping me @Stebalien .

**Comment by kjzz** [comment]
Hey @schomatis @Stebalien , i have create a pr #5506  about this issue . Could you help me review it?

**Comment by kjzz** [comment]
Hey @schomatis  @Stebalien  , i have create a pr #5506 about this issue . Could you help me review it?
