### ISSUE TITLE
High lock contention on the bitswap engine lock.

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4565]
This is a really critical shared lock. We should probably use a rwlock.

**Comment by Stebalien** [comment]
This is going to be fun...

**Comment by Stebalien** [comment]
We should also avoid iterating over every peer whenever we add a block. That should help a lot.

**Comment by whyrusleeping** [comment]
We can probably do a few simple things in the short term to buy ourselves some slack. Like not using defer.

> We should also avoid iterating over every peer whenever we add a block. That should help a lot.

Yeah, that one looks particularly painful.

**Comment by Stebalien** [comment]
I'm not sure if defer is really much of an issue here. I think the problem here is not taking the lock too often, it's holding it too long (long critical section).

**Comment by Stebalien** [comment]
Final profiles: [ipfs-profile-preload-packet-sjc-001-2020-04-23T18_02_35+0000.tar.gz](https://github.com/ipfs/go-ipfs/files/4524405/ipfs-profile-preload-packet-sjc-001-2020-04-23T18_02_35%2B0000.tar.gz)
