### ISSUE TITLE
Feature: multiaddr option for p2p stream dial

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-ipfs#4571]
#### Description: Add an option for ipfs p2p stream dial to take a multiaddr rather than an id. 

This would mean the caller can directly connect to a multiaddr. The motivation for this is from Peergos where we want to connect to an onion address, behind which another ipfs instance is, but we don't want to expose to the world that we are connecting to that onion address (which would leak the social graph in our case). This means we can't call in the usual way by the id of the ipfs node, because this would announce our intention to the dht. 

Other usages of this api would be to allow easier integration of ipfs based apps with existing server based apps and APIs. 

After some discussion with @whyrusleeping we concluded that this would be a good addition to the api.

**Comment by whyrusleeping** [comment]
The deeper issue here is that we need ways of controlling when we do 'findpeer' operations. Towards this, `ipfs swarm connect` needs to be able to *only* use the address you give it, and not try to search the DHT.

**Comment by Stebalien** [comment]
You can now do this with `ipfs p2p forward /x/my/protocol /ip4/127.0.0.1/tcp/1234 /remote/multiaddr`.

**Comment by Stebalien** [comment]
If this doesn't work for some reason (it should, but just in case), please leave a comment and we can reopen.
