### ISSUE TITLE
'config show' help message is incorrect

### ISSUE THREAD

**Issue by djdv** [ipfs/go-ipfs#4572]
`ipfs config show --help` says
>WARNING: Your private key is stored in the config file, and it will be included in the output of this command.

the former is true but the latter is not, private keys are not being output anymore (not sure when this happened).
I'm unsure if this is a bug or just an outdated warning, it's likely the latter.

In either case it makes me wonder if `show` should have a flag for displaying hidden/sensitive fields or if the warning should be changed to something like
>WARNING: Sensitive data like your private key will not be included in the output of this command.
For the flag maybe something like `--full` and place the warning there, or have `--hidesensative` defaulting to true that has to be explicitly made false.

If someone were to try and clone the config of a running instance with `ipfs config show > current.conf.bak` they'll actually be left with an incomplete config file which may not be expected given the current warning.

**Comment by Stebalien** [comment]
We intentionally don't expose the private key over *any* API interface. Losing one's private key is generally an unrecoverable compromise. It appears that the error message is out of date, thanks for noticing.
