### ISSUE TITLE
Warn when no peers and no boostrap peers configured

### ISSUE THREAD

**Issue by dongtianyi** [ipfs/go-ipfs#4576]
#### Version information:
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/darwin
Golang version: go1.9.2

#### Type: 
Bug

#### Description:
1 I use "ipfs bootstrap rm ..." to delete all the node"
2 run "ipfd daemon"
3 my ipfs node can not connect to network.

Yes, I know that I must use "ipfs bootstrap add [<peer>]" to add myself bootstrap peer. 
Actually, when I remove all the bootstrap nodes, I forget to set myself bootstrap peers.

It should give a warning when running "ipfs daemon".

**Comment by Stebalien** [comment]
There *are* perfectly valid reasons to remove all bootstrap peers. For example, you want to remotely tell IPFS which peers to connect to or you want to add the bootstrap peers later.

Now, we could try to add something that detects this situation when you do something that requires peers. That is, when a command fails, run a simple function to try to diagnose what might have gone wrong and add that additional information to the error sent back to the user. However, we have to be careful here. Eventually, we'd like to expose parts of the API to semi-trusted applications (e.g., webapps) and we'd like to avoid exposing anything potentially sensitive).

> Yes, I know that I must use "ipfs bootstrap add []" to add myself bootstrap peer.

You should never be adding yourself to the bootstrap peer list.

**Comment by lgierth** [comment]
> It should give a warning when running "ipfs daemon".

I think that's a reasonable thing to add

**Comment by kjzz** [comment]
Hey @Stebalien @lgierth , I am interested in this , can i help you do this?

**Comment by dtkav** [comment]
I'm browsing through the `help wanted` tag and there are a lot of issues like this one that seem to be resolved.

Can this issue be closed?

**Comment by Stebalien** [comment]
Yes. And please continue to point them out, thanks!
