### ISSUE TITLE
How visit private network of ipfs resource??

### ISSUE THREAD

**Issue by shishi614** [ipfs/go-ipfs#4581]
for example:public network of ipfs  via http://ipfs.io/ipfs/QmZhNfGkkqgzmCbW4gZe5JUA4mRWzWGQPmejcBeiCcG6i2 can visit my resource by ipfs add command .
how can i visit private network of ipfs resource via web way??

Private Networks the way of create as follow :

Private Networks
Allows ipfs to only connect to other peers who have a shared secret key.

State
Experimental

In Version
master, 0.4.7

How to enable
Generate a pre-shared-key using ipfs-swarm-key-gen):

**Comment by jessepeterson** [comment]
I'm confused about what you're asking. You're saying you have a resource in a private swarm that is accessible from the public IPFS network? Or are you saying you want to setup/maintain an "ipfs.io"-like gateway for your private swarm? The former should not be possible. The latter is probably possible.

**Comment by Stebalien** [comment]
`ipfs.io` is what we call a "gateway". If you're running an IPFS node on your local machine, you'll actually have your own gateway at `http://localhost:8080`. So, to access your private content, go to, e.g., `http://localhost:8080/ipfs/QmZhNfGkkqgzmCbW4gZe5JUA4mRWzWGQPmejcBeiCcG6i2`.

You will not be able to access it through the public gateway (unless someone else has added the content to the ipfs network) as the gateway won't be able to connect to your private network to access it (as that would defeat the purpose of private networks).

FYI, in the future, we generally prefer that support questions be asked on https://discuss.ipfs.io (and your questions will likely be answered faster there anyways).
