### ISSUE TITLE
HTTP API requests are FORBIDDEN from Adobe Flash and AIR apps

### ISSUE THREAD

**Issue by gdeverlant** [ipfs/go-ipfs#4585]
*Edit: Go to https://github.com/ipfs/go-ipfs/issues/4585#issuecomment-361317000 for the resolution.*

#### Version information:
```
go-ipfs version: 0.4.14-dev-429ab6369
Repo version: 6
System version: amd64/windows
Golang version: go1.9.2
```

#### Description:

I come up with another error with my tests on Windows 7. When I check the HTTP API via Chrome the requests are returning results.

When I try via my video editor to access the HTTP API via the URLLoader class the IPFS node returns 403 - Forbidden error.

![image](https://user-images.githubusercontent.com/26530975/34258813-f989cdf2-e65f-11e7-981d-2c71acc442a5.png)

**Comment by gdeverlant** [comment]
Tried with the HTTPService API

![image](https://user-images.githubusercontent.com/26530975/34260754-2d01ec76-e667-11e7-9ca2-a7d4d3c8d893.png)

**Comment by gdeverlant** [comment]
Accessing the API is working via Socket TCP Programming only...

![image](https://user-images.githubusercontent.com/26530975/34269103-6e4f2948-e683-11e7-9336-b3f5610c2b4a.png)

**Comment by gdeverlant** [comment]
Google Chrome receives a normal JSON result. Is there some **HEADERS** which are mandatory so that I can receive a normal result like with Chrome?

![image](https://user-images.githubusercontent.com/26530975/34972588-cf78b9d8-fa82-11e7-8b26-02aa2dcd3f5a.png)

**Comment by gdeverlant** [comment]
I have found on this repo : https://github.com/ipfs-shipyard/ipfs-webui

```
> ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["http://localhost:3000"]'
> ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
> ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials '["true"]'
```

I tried it by only changing the port 3000 to 5001 ending up ewith this config file :

```
{
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Credentials": [
        "true"
      ],
      "Access-Control-Allow-Methods": [
        "PUT",
        "GET",
        "POST"
      ],
      "Access-Control-Allow-Origin": [
        "http://localhost:5001"
      ]
    }
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Announce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ]
  },
....
....
....
```

And it still doesn't work!

**Comment by kevina** [comment]
@gdeverlant There is likely something odd about your setup.  The API works fine for me using `curl`.  If you have curl installed try using it from the command line and see if you still get access denied.

```
$ curl -v  http://127.0.0.1:5001/api/v0/version
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 5001 (#0)
> GET /api/v0/version HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 127.0.0.1:5001
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
< Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
< Content-Type: application/json
* Server go-ipfs/0.4.14-dev is not blacklisted
< Server: go-ipfs/0.4.14-dev
< Trailer: X-Stream-Error
< Vary: Origin
< Date: Tue, 16 Jan 2018 05:50:07 GMT
< Transfer-Encoding: chunked
< 
{"Version":"0.4.14-dev","Commit":"c1a488f","Repo":"6","System":"amd64/linux","Golang":"go1.9.2"}
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by gdeverlant** [comment]
I works now but I had to change the config for :

```
> ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin **'["*"]'**
> ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
> ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials '["true"]'
```

Is this normal ?

**Comment by kevina** [comment]
@gdeverlant I don't think so.  The default setup does not define any access control.  This is what that part of the config file looks like for me:
```
  "API": {
    "HTTPHeaders": null
  },
```

**Comment by gdeverlant** [comment]
This is my default config file with **ipfs daemon --init**

```
"Gateway": {
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "RootRedirect": "",
    "Writable": false,
    "PathPrefixes": []
  },
  "API": {
    "HTTPHeaders": null
  }
```

**Comment by gdeverlant** [comment]
With this config set :
```
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials '["true"]'
```

My App goes through:
```
initializing IPFS node at C:\Users\ergu\.ipfs

===============================================================================================================================================================
===============================================================================================================================================================
generating 2048-bit RSA keypair...
===============================================================================================================================================================
===============================================================================================================================================================
done
peer identity: QmYXJwhMDUPCHVdBX6DHRwiSrBPo6fLxSLReEpRZUkC2Fg

===============================================================================================================================================================
===============================================================================================================================================================
to get started, enter:

	ipfs cat /ipfs/QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv/readme


===============================================================================================================================================================
===============================================================================================================================================================
Process exited with  0
Process exited with  0
Process exited with  0
Process exited with  0
Initializing daemon...

===============================================================================================================================================================
===============================================================================================================================================================
Swarm listening on /ip4/10.0.2.15/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit/ipfs/QmYXJwhMDUPCHVdBX6DHRwiSrBPo6fLxSLReEpRZUkC2Fg

===============================================================================================================================================================
===============================================================================================================================================================
Swarm announcing /ip4/10.0.2.15/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip6/::1/tcp/4001

===============================================================================================================================================================
===============================================================================================================================================================
API server listening on /ip4/127.0.0.1/tcp/5001

===============================================================================================================================================================
===============================================================================================================================================================
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

===============================================================================================================================================================
===============================================================================================================================================================
openHandler: [Event type="open" bubbles=false cancelable=false eventPhase=2]
progressHandler loaded:101 total: 0
httpStatusHandler: [HTTPStatusEvent type="httpStatus" bubbles=false cancelable=false eventPhase=2 status=200 responseURL=null]
completeHandler: {"Version":"0.4.14-dev","Commit":"429ab6369","Repo":"6","System":"amd64/windows","Golang":"go1.9.2"}
```

**Comment by kevina** [comment]
If you then try
```
ipfs config --json API.HTTPHeaders null
```
does it fail again?

**Comment by gdeverlant** [comment]
With your suggestion my config file: 
```
"API": {
    "HTTPHeaders": null
  }
```

**Comment by kevina** [comment]
I don't know why the default setup differs for you.  The only think I can think of is that you are not accessing the gateway via localhost/127.0.0.1 and but that should get a connection confuses not forbidden.

@lgierth (or anyone else familiar with the gateway code), any ideas?

**Comment by gdeverlant** [comment]
I set my HTTP Headers like this :

```
	requestHeaders.push( new URLRequestHeader('Host', "127.0.0.1:5001"));
			requestHeaders.push( new URLRequestHeader('Origin', "http://127.0.0.1"));
			requestHeaders.push( new URLRequestHeader('Upgrade-Insecure-Requests', "1"));
			requestHeaders.push( new URLRequestHeader('Accept', "*/*"));
```

**Comment by kevina** [comment]
@gdeverlant again I am not sure what is going on, the only thing I can think of is to try not setting any additional headers in your request because they should not be needed and could be part of the problem.

**Comment by gdeverlant** [comment]
Even if I don't send any headers it doesn't work!

**Comment by gdeverlant** [comment]
So as a conclusion IPFS is the cause because setting this config option:

```
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
```

Allows me to use the normal URLRequest+URLLoader

**Comment by Stebalien** [comment]
Could you post the actual headers your program is sending/receiving? You can use something like wireshark to sniff the connection itself. It sounds like your program may be sending an `Origin` header or a weird `Referer` header.

**Comment by gdeverlant** [comment]
The problem is not my program... I'm able to use the same kind of request with Perkeep an its HTTP api which is also written in  Go and it has no problem!

**Comment by gdeverlant** [comment]
As I said the request are working once ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'.

**Comment by gdeverlant** [comment]
Here is the traffic with wireshark : 

[traffic.zip](https://github.com/ipfs/go-ipfs/files/1671618/traffic.zip)

**Comment by Stebalien** [comment]
> The problem is not my program... I'm able to use the same kind of request with Perkeep an its HTTP api which is also written in Go and it has no problem!

We check some headers on *our* side for security reasons. However, this should only certain requests made by browsers (e.g., those made with javascript), random HTTP clients usually don't set these headers.

> Here is the traffic with wireshark

Unfortunately, that packet dump doesn't include the actual API request (no HTTP traffic).

> As I said the request are working once `ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'.`

That's probably because your program is, internally, specifying some `Referer` or `Origin` header. That command will allow *all* origins. I'd like to see the headers that your program is sending so I can tell you which specific ones you need to send.

**Comment by gdeverlant** [comment]
Let's then make a live session because I don't know what you want to do and I'm no pro of wireshark

**Comment by Stebalien** [comment]
I just wanted to see the headers and wireshark is the only language/ide-independent cross-platform hammer I know :).

**Comment by gdeverlant** [comment]
I'm on the irc channel waiting for you to answer so that we can look into it :D

**Comment by gdeverlant** [comment]
We found the solution for this problem and it was the referrer Header from my app which was sending something like "app://Nameoftheapp.swf".

Requests coming from Flash or Adobe AIR the solution is to inject the Referrer on the HTTPRequest object header like the following:

```Actionscript
var request:URLRequest = new URLRequest("http://localhost:5001/api/v0/version");
request.requestHeaders.push( new URLRequestHeader('Referer', "http://localhost:5001"));
```

**Comment by Stebalien** [comment]
@gdeverlant thanks! I've updated the title and added a link to your comment so people will find this when searching.
