### ISSUE TITLE
About data recovery

### ISSUE THREAD

**Issue by shishi614** [ipfs/go-ipfs#4598]
version 0.4.13

i create a private work with three nodes ,A,B,C.
i put file with ipfs add at A node . other node get data with ipfs get. i see data storage at blocks.

i enter foler blocks\ZZ,
vi IQGECJOYVVE7YVF5UKOWP6PS5XOKMHPCQEHIQLAIRZ3HL4GSB5EZZQ.data and add some content in the first.
then i download file with ipfs get ,arrise valid merkledag node,but recover that file wit delete my added content ,ipfs get 
arrise same errror.

i modify file content in node A. i can,t get file at A node, even if i recover the content of modify.

192:Downloads iinda$ ipfs get QmabAfNFj32UYZnVY9iwg7hvHR2TSteEXvDUz4tzCC4hyH
Saving file(s) to QmabAfNFj32UYZnVY9iwg7hvHR2TSteEXvDUz4tzCC4hyH
1.13 GB / 1.13 GB [===============================================] 100.00% 42s
Error: The block referred to by 'QmUwLnVUoNyU5qxA6UUWVJfS3RGJ2d7TEc2cJosT3GEpMB' was not a valid merkledag node

leerspace1d
Once you corrupt a datastore I don't know if there are tools available to recover the datastore. I know you can identify corrupt blocks on a node using ipfs verify, but I'm not sure what options are next besides starting over.

This is what I mean by replication helping protect against intentional corruption on one node.

on IPFS node A
ipfs add your content and take note of the resulting hash (Qmhash)
on IPFS node B
ipfs pin or ipfs get your hash (Qmhash)
on IPFS node A
corrupt your IPFS datastore
then delete it and reinitialize your node with ipfs init
then ipfs pin or ipfs get your hash (Qmhash)
Node A should now be able to retrieve the hash without error assuming that Node B and Node A can communicate with each other.

how can i do ? a little modify cause data damage, How is data security guaranteed?
how can i find the special file of hash and delete the file of damaged,
All delete because of a little damage, a lot of data in node must ipfs get hash one by one is very difficult.
I don't think the plan is very reliable.

I asked the question in the community, leerspace1d answered, and the others didn't answer, anyone  have other good methods here to recover the corrupted data.
thanks!!

**Comment by Stebalien** [comment]
Sorry for the delay, support questions on this issue tracker tend to get lost in the noise. The forums really are the better place to ask questions like this. I've responded to your question there: https://discuss.ipfs.io/t/about-data-recovery-how-can-i-do/1864/9.
