### ISSUE TITLE
MDNS query

### ISSUE THREAD

**Issue by richardschneider** [ipfs/go-ipfs#4600]
#### Version information:
```
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/windows
Golang version: go1.9.2
```

#### Description:

Trying to do a mdns (Multicast DNS)  query to go-ipfs with no luck.  `go-ipfs` and the query app are running on the same host.  I get no response to the query.

What is the service name? I've tried `_ipfs-discovery._udp.local.` and `_ipfs-discovery._upd.`

If I run `js-ipfs`, it will respond to `_ipfs-discovery._udp`.

**Comment by richardschneider** [comment]
Used wireshark to log MDNS packets.  It appears the go-ipfs is doing a MDNS query for `_ipfs-discovery._upd.local`.  I believe that `.local` should be removed.

**Comment by Stebalien** [comment]
It should be `_ipfs-discovery._udp`. Just to make sure, `ipfs config 'Discovery.MDNS.Enabled'` returns true?

**Comment by richardschneider** [comment]
- I'm on AMD, so 0.4.13 works.  It's only win32 (x86) that it fails on
- Yes, it enabled

**Comment by richardschneider** [comment]
So it looks like it is broken.  See also https://github.com/libp2p/js-libp2p-mdns/issues/67

**Comment by richardschneider** [comment]
If any one is still interested, the issue is that go is sending a [legacy unicast query](https://tools.ietf.org/html/rfc6762#section-6.7).  Which means that it is not sending the query to  port 5353.

I changed my [code](https://github.com/richardschneider/net-mdns/issues/61) to send the DNS answer to the specific port of the query and go-ipfs was happy.  It connected to my node!

**Comment by Stebalien** [comment]
Wow. Something else to add to https://github.com/libp2p/go-libp2p/issues/623.
