### ISSUE TITLE
Swarm address filters

### ISSUE THREAD

**Issue by richardschneider** [ipfs/go-ipfs#4605]
#### Version information:
```
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/windows
Golang version: go1.9.2
```

#### Description:

Using the commands `ipfs swarm filters add/rm` changes the `.ipfs/config` with the supplied value.  I like this behaviour.  However, the [docs](https://ipfs.io/docs/commands/#ipfs-swarm-filters-add) state

> 'ipfs swarm filters add' will add an address filter to the daemons swarm.
  Filters applied this way will not persist daemon reboots, to achieve that,
  add your filters to the ipfs config file.

Let's change the documentation.

**Comment by Stebalien** [comment]
Actually, I believe we just need to rebuild the docs. I believe those are generated from the help text. @lgierth do you have any idea how to do that?
