### ISSUE TITLE
Remove DHT signatures

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4613]
Instead, records should (and do) provide their own signatures. We should simply validate them from the DHT record validator function.

Supersedes #4597.

**Comment by dirkmc** [comment]
@Stebalien you want me to take a stab at implementing this?

**Comment by dirkmc** [comment]
I guess if the DHT record validator checks the signature then the resolver doesn't need to fetch the public key at all when calling `GetValue` right?

Currently the DHT
- [Goes online if necessary](https://github.com/libp2p/go-libp2p-kad-dht/blob/3fc048d420079423db2551b21827112a66679372/dht.go#L175) to get the public key on GET
- [Does not go online](https://github.com/libp2p/go-libp2p-kad-dht/blob/d2378be37a962f21ed871df2806bd984f850d511/handlers.go#L186) to get the public key on PUT (it just fails validation if the key is not in the peerstore)

Should the DHT pass a hint to the validator to indicate whether or not it should go online to get the public key?

**Comment by Stebalien** [comment]
> I guess if the DHT record validator checks the signature then the resolver doesn't need to fetch the public key at all when calling GetValue right?

The opposite. We *don't* want the validator fetching anything. The resolver needs to first fetch the key, put it in the peerstore, and then resolve the IPNS record. The validator can use the peerstore which won't go to the network to fetch it.

On Put, we'd have the same behavior as we currently have (as the resolver won't go online).

---

Eventually, we could add some form of offline/online hint (#4009) but we can cross that bridge later.

**Comment by dirkmc** [comment]
Ah I see what you're saying, ok makes sense

**Comment by dirkmc** [comment]
@Stebalien here's a first pass at the go-ipfs part:
https://github.com/ipfs/go-ipfs/pull/4628
@vyzo @whyrusleeping you might want to check this out also

**Comment by dirkmc** [comment]
@Stebalien PR to remove Author and Signature from go-libp2p-record: https://github.com/libp2p/go-libp2p-record/pull/15
Is this what you had in mind?

**Comment by vyzo** [comment]
Is there anything else that relies in DHT record signatures?

**Comment by Stebalien** [comment]
@vyzo not that I know of.

We should have @diasdavid chime in here, however, I'm pretty sure JS doesn't actually require this field either. @diasdavid, is JS like go in this? Will it only check this signature if present (so if we remove it, we won't have any issues)? My cursory look through the JS DHT code indicated that this was the case.

**Comment by dirkmc** [comment]
Here's the go-libp2p-kad-dht PR: https://github.com/libp2p/go-libp2p-kad-dht/pull/114
