### ISSUE TITLE
"ipfs files" commands are escaping windows path slashes

### ISSUE THREAD

**Issue by Xendipity** [ipfs/go-ipfs#4615]
#### Version information:
```
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/windows
Golang version: go1.9.2
```

#### Description:

While using the go-ipfs cli on a windows git-bash terminal, I'm running into an issue where the `ipfs files` commands are escaping forward slashes: `/`: 

Fails:
```
$ ipfs files mkdir /breakfast
Error: Paths must start with a leading slash.
```

Works:
```
$ ipfs files mkdir //breakfast
```

I have this general problem with all `ipfs files` commands. Looked around through some issues and this one could be related to another recent issue https://github.com/ipfs/go-ipfs/issues/4602 but you guys would know more.

**Comment by Stebalien** [comment]
This is actually an issue with git-bash and I'm not sure there's much we can do about it. Unfortunately, git-bash recognizes that `ipfs` is a *windows* command, sees that `/breakfast` is a path, and then rewrites it as a windows path (probably as something like `C:\path\to\git\bash\root\breakfast`).

[Apparently](https://stackoverflow.com/questions/7250130/how-to-stop-mingw-and-msys-from-mangling-path-names-given-at-the-command-line#34386471), setting `MSYS_NO_PATHCONV=1` may fix this (git bash uses msys). Alternatively, passing a double leading slash will tell git bash to not rewrite the path.
