### ISSUE TITLE
After installing, I can't untar the tar file

### ISSUE THREAD

**Issue by elaineyumusic** [ipfs/go-ipfs#4619]
#### Description: I installed the pre-built package for Mac OS X at: https://ipfs.io/docs/install/  When I go to Terminal and I go to the Downloads folder (cd Downloads). I try to untar gx but it doesn't work. This is what I typed: cd Downloads
tar xvfz go-ipfs.tar.gz

This is what pops up.
tar: Error opening archive: Failed to open 'go-ipfs.tar.gz'

I checked the downloads folder and the gx folder is there and so is the tar file.

<img width="416" alt="screenshot 2018-01-29 17 37 03" src="https://user-images.githubusercontent.com/35931062/35524702-420c9f0e-051a-11e8-979b-71fa68050efd.png">

**Comment by kevina** [comment]
The instruction are misleading a bit the file is named `go-ipfs_v0.4.13_darwin-amd64.tar.gz` assuming you are using the 64 bit version of OS X.

**Comment by elaineyumusic** [comment]
Thanks! What do I do next?

Downloads elaineyu$ tar go-ipfs_v0.4.13_darwin-amid64.tar.gz
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help

I'm not a computer programmer so I'm not sure.

**Comment by kevina** [comment]
```
tar xfvz go-ipfs_v0.4.13_darwin-amid64.tar.gz
```
This is not really the place to get support, https://discuss.ipfs.io would be better.

**Comment by Stebalien** [comment]
I believe osx can also extract it for you if you use finder.
