### ISSUE TITLE
`ipfs stats bw` contains extra row with unused headers

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/go-ipfs#4620]
#### Version information:

```
go-ipfs version: 0.4.14-dev-cfdcd98
Repo version: 6
System version: amd64/linux
Golang version: go1.9.1
```

#### Type:

Bug

#### Severity:

Low

#### Description:

When running `ipfs stats bw`, the first row contains some type of headers who I guess I meant is to show some values as well, but no values are to be seen.

This is the output:

```
Total Up    Total Down  Rate Up     Rate Down
Bandwidth
TotalIn: 3.7 MB
TotalOut: 1.3 MB
RateIn: 1.1 kB/s
RateOut: 425 B/s
```

First, the labels are not consistent with the labels below, and they also don't show any information.

**Comment by kevina** [comment]
I think #3856 was the culprit.  The header line is meant for the `--poll` output which also seams to be broken.  Still looking into this.

**Comment by kevina** [comment]
P.R. #3856 is the culprit.  The header line is meant for the `--poll` option, which before that commit was only outputted when that option was used.  More to the point, this is the normal output:
```
Bandwidth
TotalIn: 11 MB
TotalOut: 5.6 MB
RateIn: 17 kB/s
RateOut: 11 kB/s
```
and this is the output with `--poll`:
```
Total Up    Total Down  Rate Up     Rate Down
   16 kB       18 kB        13 B/s      14 B/s
```
Note that the commit also changed the behavior of `--poll` a bit.  Before the stats line was updated in place, now interval creates a new line.  I am not sure if this is a good or bad thing.

CC: @keks

**Comment by kevina** [comment]
Okay, this should be an easy fix.  I will try to have a p.r. in in the next day or so.
