### ISSUE TITLE
Consider ignoring errors from the exchange in the blockservice

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4623]
Currently, the blockservice can succeed in adding a block and then fail because it fails somewhere when telling the exchange we have the block.

We should probably just log and ignore (and, maybe, change the `HasBlock` signature on the exchange to not return an error).

**Comment by cannium** [comment]
I happen to encounter the comments when reading related code. Some thoughts:
- `exchange.HasBlock` return error only if the write to datastore fails. If it fails, would peers know the new blocks?(haven't read about bitswap...) If not, then we should not simply ignore the error, at least make it optional for users to choose.
- Would some kind of batch processing be useful here, like `exchange.HasBlocks` ?
