### ISSUE TITLE
Integers in DAGs are serialized as doubles (in CLI)

### ISSUE THREAD

**Issue by lbelyaev** [ipfs/go-ipfs#4635]
#### Version information:
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2

#### Type:
Bug?

#### Severity:
Medium
#### Description:
Hi,
Looks like ipfs CLI (ipfs dag put <object>) serializes integers in DAGs as double-precision floats, is this a bug or intentional decision?

example:
`echo '{"var":1}' | ipfs dag put`
`zdpuAxQm7QaVc9ufEyKcqNX35WLw7LwdtYkhD4ksvuvaeeaBW`

test:
`ipfs block get zdpuAxQm7QaVc9ufEyKcqNX35WLw7LwdtYkhD4ksvuvaeeaBW | xxd`
`00000000: a163 7661 72fb 3ff0 0000 0000 0000       .cvar.?.......`

Thanks
Leo

**Comment by Stebalien** [comment]
See: https://github.com/ipld/interface-ipld-format/issues/9. There are a lot of decisions we need to make concerning primitive types in IPLD.

**Comment by lbelyaev** [comment]
@Stebalien thanks for the reference, I probably missed the earlier thread. Looking at https://github.com/ipld/interface-ipld-format/issues/9 , i tend to agree with @kevina 's proposal, but I might not be aware of all the moving parts
