### ISSUE TITLE
Please don't run os builds as a part of the test_go_short

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#4642]
Commit f3ad2c95bdcac987bfe2485fde72d63a2f0f4104 as part of pr #4464 now builds for all platforms as part of `test_go_short`.  This takes a fair amount of time.  The idea of `test_go_short` was to be quick.  I use it as a quick sanity check before I push a commit.  I let the build severs do the more expensive tests.

**Comment by kevina** [comment]
More to the point I use it to make sure the tests compile after doing any sort of refactoring as "go build" does not compile the tests.  If there was a way to just compile all the tests I would be happy with that but I am not sure how to do that.

**Comment by Stebalien** [comment]
That's because, apparently, `test_go_short` works by running `test_go_expensive` with `-test.short`.
