### ISSUE TITLE
Better document targets in make output

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#4647]
From my comments on https://github.com/ipfs/go-ipfs/pull/4645:

> You might want to add test_go_test under TESTING TARGETS (when you type just make) and explain what test_go_expensive does.

Just a suggestion, only creating this issue to make sure my comment was not lost in the noise as that p.r was merged without my comment being acknowledged.

**Comment by Stebalien** [comment]
> You might want to add test_go_test under TESTING TARGETS

`test_go_test` is an internal target and probably shouldn't be called directly. However, yes, these targets should all be documented.

**Comment by kevina** [comment]
> `test_go_test` is an internal target and probably shouldn't be called directly.

It would be nice to have a documented target that runs all the go tests without anything else just to keep things uniform.

**Comment by Stebalien** [comment]
@kevina fair enough. Done.
