### ISSUE TITLE
allow blockservice to lazily create sessions

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4660]
If we have all the data for a given request locally, and we use a command that uses a bitswap session, we will create the whole session (caches, buffers, goroutines and all) for nothing. We should make the blockservice session code only spin up the bitswap session when a disk get fails (and we would fall back to the session).

**Comment by hannahhoward** [comment]
given that even regular Bitswap GetBlocks creates sessions these days, seems like this isn't relevant

**Comment by hannahhoward** [comment]
sorry rewind, i see we're talking about a situation where no calls to bitswap are made
