### ISSUE TITLE
ipfs init does not respect IPFS_PATH

### ISSUE THREAD

**Issue by identicalsnowflake** [ipfs/go-ipfs#4671]
On Linux, `ipfs init` always initializes ipfs in the home directory, rather than in the `IPFS_PATH` directory. I'm sure the `IPFS_PATH` variable is set because subsequently running `ipfs daemon` correctly says there is no initialized repository at the IPFS_PATH.

Manually copying `.ipfs` from my home directory and into the folder given in `IPFS_PATH` allows the daemon to run normally.

**Comment by VictorBjelkholm** [comment]
Seems to be working fine for here:

```
➜  ~ ipfs version --all
go-ipfs version: 0.4.14-dev-d58da7474
Repo version: 6
System version: amd64/linux
Golang version: go1.9.3
➜  ~ IPFS_PATH=$(mktemp -d) ipfs init
initializing IPFS node at /tmp/tmp.h06H1yGgdE
generating 2048-bit RSA keypair...done
peer identity: QmcAHUXhq3CpCEHe57Pe3FqMYVxMhpdgKgrFY2fsoSDF8r
to get started, enter:

        ipfs cat /ipfs/QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv/readme
```

Can you share with us exactly what version of go-ipfs you are using and also how you set the environment variable?

**Comment by identicalsnowflake** [comment]
I tried both `IPFS_PATH=/var/ipfs sudo ipfs init` and just using `export IPFS_PATH=/var/ipfs` and neither worked for me. I don't think it's a problem with the variable being set, since subsequently running `sudo ipfs daemon` does correctly look in this directory (and works after I manually copy/paste).

I'm not at my computer now, so I'll confirm the exact version for you later, but I'm pretty sure I just installed it with the update utility, so whatever that chose should be it (I was hoping for a build from my distro so I wouldn't have to worry about updates, but I couldn't find one, so I just setup the updater to run on startup).

**Comment by VictorBjelkholm** [comment]
The problem seems related to your use of `sudo`. Check out the difference in these two commands (one is using `sudo`, the other one doesn't)

```
➜  ~ IPFS_PATH=$(mktemp -d) sudo ipfs init
[sudo] password for user:
initializing IPFS node at /root/.ipfs
generating 2048-bit RSA keypair...done
peer identity: QmUTDLyaqeC9bHWjKFMWBEKkRnhFGbZN9o2ms27QVNEQdt
to get started, enter:

        ipfs cat /ipfs/QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv/readme

➜  ~ IPFS_PATH=$(mktemp -d) ipfs init
initializing IPFS node at /tmp/tmp.X781FuJLEi
generating 2048-bit RSA keypair...done
peer identity: QmczyeJiW8pm2DTBTGC8jPgzWAy9RYR6A7RNz1KpAXFyGs
to get started, enter:

        ipfs cat /ipfs/QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv/readme

```

When using `sudo`, the environment variables does not pass on to the next command. You can pass `-E` to preserve the environment variables, but better is to not run ipfs as root. It's simply not needed and if you need some special permissions, you can create a new `ipfs` user and give the priviligies to that user.

**Comment by identicalsnowflake** [comment]
Ah, TIL. Well that makes sense then.

Sorry for bothering you!
