### ISSUE TITLE
Extracting importers requires extracting many things, let me know if I can go ahead

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipfs#4679]
If I got it right, extracting the `importer` module for re-use in ipfs-cluster to use it is going to require to additionally extract (because of intermodule deps):

* blocks
* blockservice
* exchange
* pin
* unixfs
* routing
* merkledag

This is a bit of work and I want to make sure we you are OK with it? Or would you rather do things (or have me do things) differently?

@whyrusleeping @Stebalien

**Comment by whyrusleeping** [comment]
@hsanjuan All of this sounds good except pin. I don't think that one is necessary quite yet, is it?

In any case, i'm 👍 for having these extracted.

**Comment by whyrusleeping** [comment]
how about: start working on this, do exchange+bitswap last. We're working on a fix to bitswap that will hopefully be the last piece before the 0.4.14 release. Once that release is in, we can merge all these extractions.

**Comment by hsanjuan** [comment]
There is a dep from blocks/blockstore to pin (removing a block needs a pinner to unpin, if I remember well).

I can't do exchange last because it's not the top dependency, but I can wait and do others in the meantime.

**Comment by magik6k** [comment]
Extracting exchange+bitswap now will make https://github.com/ipfs/go-ipfs/pull/4333 a bit annoying to fix (not that it doesn't have enough conflicts now), AFAIK we wanted to merge 4333 after 0.4.14 is released. so that shouldn't block this for long

**Comment by hsanjuan** [comment]
@magik6k ack. not touching exchange for the moment.

**Comment by kevina** [comment]
I am also have outstanding fixed to few of those packages so I would appreciate it I'd we hold off a bit.

On February 15, 2018 4:22:38 AM EST, Hector Sanjuan <notifications@github.com> wrote:
>@magik6k ack. not touching exchange for the moment.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ipfs/go-ipfs/issues/4679#issuecomment-365868998

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kevina** [comment]
Also what the motivation for separating these out?

**Comment by ZenGround0** [comment]
@kevina https://github.com/ipfs/notes/issues/278

**Comment by magik6k** [comment]
This has happened (the package lives in https://github.com/ipfs/go-unixfs)
