### ISSUE TITLE
Ignore keys with invalid names in keystore

### ISSUE THREAD

**Issue by matrushka** [ipfs/go-ipfs#4681]
#### Version information:
go-ipfs version: 0.4.13-cc01b7f
Repo version: 6
System version: amd64/darwin
Golang version: go1.9.2

#### Type:
Enhancement

#### Description:
Right now dotfiles under the keystore directory causes an error while running `ipfs key list`. Although having a dotfile (or any file with an invalid name) shouldn't cause the whole thing to fail. It should print out a warning about the problem. When it comes to why I need this feature is:

##### Motivations:
* I want to deploy an IPFS node with a specific key inside it by using Kubernetes
* I want to use secret feature of Kubernetes to deploy the key to nodes I want to spin up (http://kubernetes.io/docs/concepts/configuration/secret/)
* I can deploy the key succesfully but kubernetes uses some dotfiles to deploy secret files which breaks all the key related functions.
* So this issue can be solved via either patching Kubernetes or go-ipfs but I thought the go-ipfs behaviour should be more forgiving and informative, since it's preventing access to valid keys and not informing the user about exactly why.

##### How the feature should work:
* While renaming or generating a key the proper error message is displayed so it's all good ✅
* If you have a key with an invalid name inside the keystore directory and `list` is being called it should return all the valid keys and log or display warnings about the invalid ones.

**Comment by Stebalien** [comment]
Ignoring hidden files sounds reasonable.

Want to take a crack at this? It should be fairly straight forward. You'll have to edit `keystore/keystore.go` and make two changes:

1. `Has` should call the `validateName` function before checking if we have the file (so `Has(".specialFile")` doesn't indicate that we have a key named `.specialFile`.
2. `List` should filter the returned list of file names by `validateName` (and log bad files).

**Comment by matrushka** [comment]
@Stebalien sure I'll try to have a look.
