### ISSUE TITLE
type mismatch panic on ipfs add

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4683]
**Verision**
./ipfs version --all
go-ipfs version: 0.4.14-dev-eca0486e1
Repo version: 6
System version: amd64/linux
Golang version: go1.9.4

**Output**
```
IPFS_PATH="/data/ipfsrepo"  IPFS_FD_MAX="4096" ./ipfs add --progress --local --nocopy --fscache --quieter --recursive mirror/
 
 849.23 GB / 849.35 GB [==========================================================================================================================================]  99.99% 0s
panic: interface conversion: interface {} is cmdkit.Error, not *coreunix.AddedObject

goroutine 70 [running]:
github.com/ipfs/go-ipfs/core/commands.glob..func7.2(0xc42001a3c0)
        /home/alvaro/gocode/src/github.com/ipfs/go-ipfs/core/commands/add.go:405 +0xa60
created by github.com/ipfs/go-ipfs/core/commands.glob..func7.3
        /home/alvaro/gocode/src/github.com/ipfs/go-ipfs/core/commands/add.go:467 +0xc7
```

**Comment by whyrusleeping** [comment]
reported in #3885

**Comment by Stebalien** [comment]
Effectively, https://github.com/ipfs/go-ipfs-cmds/issues/62. We shouldn't be using the same logic for errors and values.

**Comment by rngkll** [comment]
Let us know if you need help reproducing the issue, are running the command daily.

We will like to help on fixing this.

**Comment by whyrusleeping** [comment]
@rngkll I've got a patch that fixes the issue (linked above your comment on github). We're working on determining if its the 'right' fix, or just a hack that works for now that we may regret later. Its an issue in our newly refactored command RPC library.
