### ISSUE TITLE
Don't depend on golang.org for building

### ISSUE THREAD

**Issue by Sak94664** [ipfs/go-ipfs#4684]
#### Type:
Enhancement

#### Description:
(Build From Source Code)
When it was trying to connect 'golang.org' ,it reported 'timeout'.And I looked up on the Internet.It said that 'golang.org' is blocked in China.And I also knew that there is a mirror on github.com
Would anyone like to change Download address from 'golang.org' to 'github.com'?
Thanks in advance 
:)

**Comment by magik6k** [comment]
I blocked golang.org locally and tried this in temporary gopath.

The problem appears to be that `make install_unsupported` fails to fetch gx/gx-go, which both depend on some things from golang.org, not much though:

```
golang.org/x/crypto/blake2s
golang.org/x/crypto/sha3
golang.org/x/net/context
```

There was some issue about changing the `gx/Qmpkg` paths to `ipfs.io/ipfs/Qmpkg`, can't locate it now, though if that got implemented it would be possible to gx-ify gx to avoid this problem.

`make build` worked fine for me.

@Sak94664 for now you can get the binary build of go-ipfs (or gx + gx-go to build go-ipfs manually) from https://dist.ipfs.io/#go-ipfs

**Comment by Sak94664** [comment]
@magik6k Thanks a lot :)
But 'go get' doesn't work for me,what can I do?
used gx get in 'source_code_root/cmd/ipfs' and the problem happened.(the same as 'go get')
It said 'import path does not begin with hostname.'
Saw issue 2401 ,but neither make install nor make install_unsupported don't work for me.
Now I can only use the pre-compiled binaries.(works fine)
Hope the bug can be solved :)

**Comment by magik6k** [comment]
This should work:
```
[install binary gx, gx-go]
$ go get github.com/ipfs/go-ipfs
go-ipfs$ gx install
go-ipfs$ go install -ldflags="-X github.com/ipfs/go-ipfs/repo/config.CurrentCommit=$(git rev-parse --short HEAD)"  ./cmd/ipfs
```

**Comment by Sak94664** [comment]
`[76 / 286] 480sERROR: from shell.Get(): net/http: request canceled (Client.Timeout exceeded while reading body)
retrying fetch Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ after a second...`
it reports this.
@magik6k 
Strange.Is it still fetch from golang.org?

(Behind NAT)

**Comment by Kubuxu** [comment]
We are using go modules now (https://github.com/ipfs/go-ipfs/pull/6038)
