### ISSUE TITLE
Keep on getting bitswap: couldnt open sender again after SendMsg

### ISSUE THREAD

**Issue by JuliaCao** [ipfs/go-ipfs#4690]
#### Version information:
I have

go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/darwin
Golang version: go1.9.2

#### Description:

I tried to download using ipfs get multiple times, it always proceeds without bug until 89%, where I keep on getting these errors (i/o timeouts and dial attempt failed):

01:04:59.232 ERROR    bitswap: couldnt open sender again after SendMsg(<peer.ID PfiTMf>) failed: dial attempt failed: <peer.ID Rz5GnE> --> <peer.ID PfiTMf> dial attempt failed: i/o timeout wantmanager.go:237
01:05:23.287 ERROR    bitswap: couldnt open sender again after SendMsg(<peer.ID V7nVwS>) failed: dial attempt failed: context deadline exceeded wantmanager.go:237

I also tried to connect to the server before doing get, but that did not help either.

Any idea why this might happen or how to solve it?

**Comment by Stebalien** [comment]
Are you trying to download from one of your servers? Does its peer ID start with `QmPfiTMf` or `QmV7nVwS`? If not, those error messages are likely unrelated (see https://github.com/ipfs/go-ipfs/issues/4128). If so, this is very interesting and would explain a lot.

The more likely explanation is that the server you're trying to fetch the file from doesn't have the rest of the file.

Of course, it could be a totally unrelated bug... we have many of those.

**Comment by mitar** [comment]
(That's being downloaded from my server.)

How can I verify on the server if it has everything?

**Comment by mitar** [comment]
@JuliaCao: Is it possible that you downloaded first 89% on a different connection than you are trying the rest? So when you run `ipfs get` it caches all the data, so when you retry running `ipfs get` it might be that it first restored 89% of content from cache and when it then tries to get the rest, if fails.

**Comment by Stebalien** [comment]
@mitar download the latest master and run `ipfs files stat --with-local /ipfs/QmIdOfTheFileInQuestion` (but I don't know which file this is).

**Comment by mitar** [comment]
Agh. I am running things from Docker image on the server. Let's wait for this to get released. ;-) I will in meantime try to get all data again myself to another server, to see if it works.

**Comment by Stebalien** [comment]
@mitar you can also probably just use `ipfs refs QmId...` and see if it returns immediately.

**Comment by mitar** [comment]
There are 431604 refs when doing `ipfs refs -r ...`. It takes time to even just print them out. So I am not sure how to determine "immediately". But it looks like it finishes and to my knowledge this is the only server seeding it, so I think the server has all the data.

**Comment by Stebalien** [comment]
@mitar yeah, that means it has all the data. What's the server's peer ID?

**Comment by mitar** [comment]
`/ip4/169.229.219.152/tcp/4001/ipfs/QmSUMYKijNo1UBEJseWhE2JivoRRzJT69AT5Nd5M2dByVQ`

An interesting thing is that if I currently run `ipfs id` on the server, its public IP is not among its addresses. (It is running inside Docker container, so its public port is mapped using Docker.)

**Comment by mitar** [comment]
So it seems this is not really a problem. The issue is that at 89% there are just many (few 100k) small files to retrieve. This is why it visually looks like it is stuck, but in fact it is working. There are some warnings output by daemon by they are not blocking.

I do have some additional warnings by daemon though. Like:

```
20:38:22.489 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:180
20:38:22.489 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:180
20:38:22.565 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:180
20:38:22.578 ERROR     flatfs: too many open files, retrying in 600ms flatfs.go:180
20:38:22.590 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:180
20:38:33.623 ERROR    bitswap: couldnt open sender again after SendMsg(<peer.ID Q85u4d>) failed: dial attempt failed: <peer.ID c5z81N> --> <peer.ID Q85u4d> dial attempt failed: connection refused wantmanager.go:237
20:39:36.671 ERROR    bitswap: couldnt open sender again after SendMsg(<peer.ID XkksFy>) failed: dial attempt failed: context deadline exceeded wantmanager.go:237
20:39:55.421 ERROR    bitswap: couldnt open sender again after SendMsg(<peer.ID T6E8Hv>) failed: dial attempt failed: context deadline exceeded wantmanager.go:237
20:40:15.791 ERROR    bitswap: couldnt open sender again after SendMsg(<peer.ID NiNd8u>) failed: connection write timeout wantmanager.go:237
20:40:54.473 ERROR    bitswap: couldnt open sender again after SendMsg(<peer.ID S4iGrz>) failed: session shutdown wantmanager.go:237
20:48:14.622 ERROR    bitswap: couldnt open sender again after SendMsg(<peer.ID NiNd8u>) failed: connection write timeout wantmanager.go:237
```

**Comment by mitar** [comment]
I opened #4706.

**Comment by Stebalien** [comment]
Damn. Those flatfs files are definitely relevant. Possibly forcing us to re-download the small blocks. You could try switching to the badger datastore but we still don't consider it stable yet.

**Comment by hannahhoward** [comment]
I honestly can't tell if this is still considered an issue -- it seems like it was traced to FlatFS? If there is not actionable work here, I'd be inclined to close pending work on datastore. @magik6k -- leave final close decision to you?

**Comment by Stebalien** [comment]
This is really just yet another too many open files issue so keeping it open probably doesn't help. Also, your resend wantlist patch probably fixes this issue.
