### ISSUE TITLE
Error: multihash too short. must be > 3 bytes

### ISSUE THREAD

**Issue by ivan386** [ipfs/go-ipfs#4694]
#### Version information:
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/windows
Golang version: go1.9.2

#### Description:
```
>ipfs block get z2yYDV
Error: multihash too short. must be > 3 bytes
```

z2yYDV -> (01 55 00 00) is valid zero length "identity" hash of zero length raw block.

**Comment by kevina** [comment]
This should likely be reported to https://github.com/multiformats/go-multihash.

**Comment by ivan386** [comment]
@kevina 
Ok. https://github.com/multiformats/go-multihash/issues/69
