### ISSUE TITLE
Sharness randomly fails on jenkins

### ISSUE THREAD

**Issue by magik6k** [ipfs/go-ipfs#4698]
Sharness sometimes fails on Jenkins for what seems to be no apparent reason. I've got this a few times

Occurred in https://github.com/ipfs/go-ipfs/pull/4682 / https://ci.ipfs.team/blue/organizations/jenkins/go-ipfs/detail/PR-4682/4/pipeline

Full log: https://ncry.pt/p/rENn#72Z7nYJ7izEKFU1_trTKQ8cYyNe1jk8ZwRnhwNgaoEc

**Comment by hsanjuan** [comment]
Yeah I see this a lot

**Comment by magik6k** [comment]
We don't run Jenkins anymore and this doesn't seem to happen on circle
