### ISSUE TITLE
go get breaks with "is not using a known version control system" 

### ISSUE THREAD

**Issue by preetsinojiya** [ipfs/go-ipfs#4716]
Version information:
Go version: go1.9.2 darwin/amd64
OS: macOS high sierra 

Type: Bug

Description:
Running: go get -u -d github.com/ipfs/go-ipfs

Actual behavior:
package github.com/ipfs/go-ipfs: directory "/Users/path/Projects/go/src/github.com/ipfs/go-ipfs" is not using a known version control system

Expected behavior:
Should create $GOPATH/src/github.com/ipfs/go-ipfs directory

**Comment by preetsinojiya** [comment]
Previously, I tried deleting ipfs/ directory from src/ folder. But did not work.

Now, I deleted everything from src/ folder and reinstalled everything and it seems to be working. Still not clear what could be the cause, but it's working now.

**Comment by leerspace** [comment]
I'm pretty sure this is an issue with go rather than IPFS. There seem to be other go users encountering this issue outside of trying to `go get` go-ipfs.

**Comment by CyberoxiDevops** [comment]
I created a go mod file with the command "go mod init" and afterwards "go mod tidy". when I ran the command "go get -u %packageName" it worked.

**Comment by m0sh1x2** [comment]
> I created a go mod file with the command "go mod init" and afterwards "go mod tidy". when I ran the command "go get -u %packageName" it worked.

Yes this is the solution `go mod init REPO && go mod tidy`, I even wrote an article as this solution is very hard to find and doesn't get indexed well for some reason - https://m0sh1x2.com/posts/fixing-error-obtaining-vcs-status-directory-is-not-using-a-known-version-control-system/
