### ISSUE TITLE
ipfs get drops containing directory structure in output when <ipfs_path> contains trailing slash ('/')

### ISSUE THREAD

**Issue by yuri-sevatz** [ipfs/go-ipfs#4720]
#### Version information:
ipfs version 0.4.13

#### Type:
Bug

#### Description:
```
ipfs init
ipfs daemon &
mkdir -p ~/test/test2/hello/
echo "Aperture Science" >> ~/test/test2/hello/world.txt
ipfs add -r -w ~/test
ipfs get -o ~/Downloads/test /ipfs/`ipfs id -f='<id>'`/test/
ls -R ~/Downloads/test
```

Results in:

> /home/ninja/Downloads/test:
> hello
> 
> /home/ninja/Downloads/test/hello:
> world.txt

Yet leaving out the trailing slash after the path portion at the end of the get command:

```
mkdir -p ~/test/test2/hello/
echo "Aperture Science" >> ~/test/test2/hello/world.txt
ipfs add -r -w ~/test
ipfs get -o ~/Downloads/test /ipfs/`ipfs id -f='<id>'`/test
ls -R ~/Downloads/test
```

Results in:

> /home/ninja/Downloads/test:
> test2
> 
> /home/ninja/Downloads/test/test2:
> hello
> 
> /home/ninja/Downloads/test/test2/hello:
> world.txt

It seems leaving out the trailing slash **after the path** in the `ipfs get` command allows the folder structure to download correctly, but adding one in causes `ipfs get` to squash subfolders of the parent folder together right in your output path.

This is probably quite dangerous and counter-intuitive.

**Comment by schomatis** [comment]
I can reproduce this. The function [`DagArchive`](https://github.com/ipfs/go-ipfs/blob/199a52d777e2b292fe430e8470d88037c43ed7ca/unixfs/archive/archive.go#L36) that prepares the output does not clean the path as the resolver does in [`Segments`](https://github.com/ipfs/go-ipfs/blob/199a52d777e2b292fe430e8470d88037c43ed7ca/path/path.go#L46).

**Comment by schomatis** [comment]
@yuri-sevatz Could you try that again with #4743?
