### ISSUE TITLE
dag/put HTTP API enhancement

### ISSUE THREAD

**Issue by vmx** [ipfs/go-ipfs#4722]
#### Version information:
go-ipfs version: 0.4.14-dev-25eeb1e25
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2

#### Description:

In the HTTP API currently a `dag/put` returns the CID (as link). Similar endpoints return other things:

 -  `block/put`: `Key` (which is the CID) and `Size`
 - `add`: `Name`, `Hash` (which is the CID), `Bytes`, `Size`

Should `dag/put` also return the size and return the CID not as link, but just the hash?

**Comment by Kubuxu** [comment]
I think it was done on purpose, we want to have links instead of CIDs but we can't change old APIs.

**Comment by magik6k** [comment]
Ideally all endpoints would embed CIDs as IPLD links to make things more consistent, but that reqiires http-api v2 or something like that

Closing as there isn't much we can do about this

**Comment by vmx** [comment]
Just a note (for people stumbling over this issue). IPLD links are not a thing anymore, the IPLD implementations now use the program language specific representation of CIDs. I'd called it "JSON representation of Links".
