### ISSUE TITLE
AddNodeLink and AddNodeLinkClean seem to have the same functionality

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#4729]
While reviewing code for issue #4052 I came across the functions [`AddNodeLink`](https://github.com/ipfs/go-ipfs/blob/master/merkledag/node.go#L92) and [`AddNodeLinkClean`](https://github.com/ipfs/go-ipfs/blob/master/merkledag/node.go#L109) that would seem to have the same code except for an extra line in `AddNodeLink` where [the name is set to the link that will be added](https://github.com/ipfs/go-ipfs/blob/master/merkledag/node.go#L100), but the link name is not used in the [`AddRawLink`](https://github.com/ipfs/go-ipfs/blob/master/merkledag/node.go#L121) function that receives the link (as the name is specified as a separate argument), and the link itself seems to be discarded after the call (its members `Size` and `Cid` are copied but not the link structure).

Both functions are equally used in the code base but I'm failing (from reading the code and the comments) to see their difference, am I missing something?

**Comment by Stebalien** [comment]
No, that looks like duplicate code. It looks like we *used* to cache children nodes inside link objects but don't do that anymore. Feel free to deduplicate.

(also, if I don't get back to you in a reasonable amount of time (e.g., 2 days) on a question, please hunt me down on IRC and yell at me)
