### ISSUE TITLE
Gcc error when trying to build the latest go-ipfs from master branch

### ISSUE THREAD

**Issue by alvin-reyes** [ipfs/go-ipfs#4739]
#### Version information:
0.4.13

#### Type:
Bug

#### Description:
I'm getting an error when trying to build a fresh copy off of master branch of go-ipfs.

```
go install -ldflags="-X "github.com/ipfs/go-ipfs/repo/config".CurrentCommit=199a52d"  ./cmd/ipfs
# github.com/ipfs/go-ipfs/cmd/ipfs
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exec: "gcc": executable file not found in $PATH

cmd/ipfs/Rules.mk:37: recipe for target 'cmd/ipfs-install' failed
make: *** [cmd/ipfs-install] Error 2
root@IPFS-BUILD:/usr/local/src/github.com/ipfs/go-ipfs# apt install gcc
When requesting a feature, please be sure to include:
```

* Your motivation. Why do you need the feature? - I'm trying to build a fresh go-ipfs for some future extensions.
* How the feature should work. - I'm assuming that the initial build will at least succeed .

**Comment by Kubuxu** [comment]
Try running `CGO_ENABLED=0 make build` but I've never seen this problem before.

**Comment by alvin-reyes** [comment]
Apparently my new DO droplet didn't have gcc installed at all. I installed gcc and everything worked fine.

https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91

I'll close this one now. Thank you.

**Comment by GUOxirong** [comment]
c
