### ISSUE TITLE
Openbsd 6.2

### ISSUE THREAD

**Issue by jhautefeuille** [ipfs/go-ipfs#4748]
gmake install_unsupported

>> gmake: *** [Rules.mk:109: install_unsupported] Error 1

**Comment by vext01** [comment]
I'd close this, since 6.2 is quite an old release now.

**Comment by djdv** [comment]
Our build system and Go itself have changed a bit.
I was able to successfully build and run the latest master on this machine
```
puff$ go version
go version go1.12.1 openbsd/amd64
puff$ uname -prs
OpenBSD 6.5 amd64
```
by using `GOTAGS=nofuse gmake install`.

The next iteration of the mount command will use a library that is OpenBSD compatible and tested (https://github.com/billziss-gh/cgofuse)
https://github.com/ipfs/go-ipfs/issues/5003
![obsd-ipfs](https://user-images.githubusercontent.com/13862850/57799683-9d666080-771d-11e9-8e2b-11f48a68d6f7.png)
