### ISSUE TITLE
ipfs get never returns

### ISSUE THREAD

**Issue by kiahmed** [ipfs/go-ipfs#4762]
#### Version information:

Output From `ipfs version --all`
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/windows
Golang version: go1.9.2

#### Description:
when try to get a an object with its hash that I know already exists , it won't ever return. Now, my ipfs node is new deployed yesterday and repo size is only 180 mb, is it becase of that? How long it takes fo sync , does it downloads the entire file system locally ? It only gets whats available locally in my repo, not from the other nodes. for example this command wont get anything , also can't find other peers

ipfs get zb2rhn5vsovF4m8LRPKX7Hpj6mT8TZbRtuT4YmgcMWtynw6D7

**Comment by kiahmed** [comment]
also getting this error on screen:
[0;37m16:48:04.092 [31mERROR [0;34m       dht: [0mloggableKey could not cast key: 2f69706e732f12204dd24a1498d24850beabf7b0573dbba861c47a7079db660250cdf6e635ff0a4e invalid cid version number: 47 [0;37mlookup.go:35[0m

**Comment by Stebalien** [comment]
> also can't find other peers

This looks like: https://github.com/ipfs/go-ipfs/issues/4512

I'd try building master from source. FYI, there should be a release with this fix in it pretty soon. We have an RC1 out.
