### ISSUE TITLE
ipfs object diff: check object contents

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#4775]
As explained by @magik6k in a [comment](https://github.com/ipfs/go-ipfs/pull/4767#issuecomment-370466270), the command `ipfs object diff` doesn't specifically check the data of the objects, just the hash (CID) of its links. My question, in order to work on a solution, is what is an *object*? (in the context at least of the `ipfs object` command).

The command [`ipfs object put`](https://github.com/ipfs/go-ipfs/blob/c00482ab1931c582388022540b38d27b12f20ea0/core/commands/object/object.go#L572) handles the [`ProtoNode`](https://github.com/ipfs/go-ipfs/blob/c00482ab1931c582388022540b38d27b12f20ea0/merkledag/node.go#L21) structure while the command [`ipfs object diff`](https://github.com/ipfs/go-ipfs/blob/c00482ab1931c582388022540b38d27b12f20ea0/merkledag/utils/diff.go#L97) handles the IPLD [`Node`](https://github.com/ipfs/go-ipld-format/blob/master/format.go#L26) interface, which is implemented by `ProtoNode`, but I don't see that `Node` gives access to the `data` of the `ProtoNode`, just `RawData` (through the `Block` interface), but that also includes the bytes from the serialized links (besides `data`).

Should the `Diff` function check the underlying type of the interface to specifically look at `data` (and if so, it should have to look for all the particularities of each type that implements the interface to perform a correct comparison)? Is there an `Equals`/`Compare` function that already abstracts these details? I would really appreciate if someone could point me to more documentation (PR/issue/spec) of how the different data types of IPFS are stacked and interact (e.g., the blocks are one layer below, unixfs is above, etc.)

**Comment by magik6k** [comment]
But the `merkledag.utils.Diff` (which is used by `ipfs object diff`) does expect the nodes to be Protobuf nodes:

https://github.com/ipfs/go-ipfs/blob/c00482ab1931c582388022540b38d27b12f20ea0/merkledag/utils/diff.go#L109-L110

What I meant in the comment was to use the `cleanA/B` nodes to get the data to compare.

**Comment by schomatis** [comment]
@magik6k Thanks again for the clarification. I see now that the check of the links works as a filter of [`RawNode`](https://github.com/ipfs/go-ipfs/blob/c00482ab1931c582388022540b38d27b12f20ea0/merkledag/utils/diff.go#L97-L106) and similar types before the cast, I'll prepare the PR then and let you know.

https://github.com/ipfs/go-ipfs/blob/c00482ab1931c582388022540b38d27b12f20ea0/merkledag/utils/diff.go#L97-L110

**Comment by schomatis** [comment]
Also, care should also be taken in the checks to ensure that `RawNode` nodes don't pass to the conversion stage.

```
mkdir dir
touch dir/file
ipfs add dir -r --cid-version 1
# added zb2rhk8YBkoAB3KCZScAnrZbSfReGyRtBwqLsDtHb6V8JKVDP dir/file
# added zdj7Wd7esoDPpKVgEU1AP928fAp8Rjzm6DFme1ptKA8q79CBT dir

ipfs object diff zdj7Wd7esoDPpKVgEU1AP928fAp8Rjzm6DFme1ptKA8q79CBT zb2rhk8YBkoAB3KCZScAnrZbSfReGyRtBwqLsDtHb6V8JKVDP
Error: interface conversion: format.Node is *merkledag.RawNode, not *merkledag.ProtoNode
```

I'll add this case to the tests.

**Comment by schomatis** [comment]
@whyrusleeping Could you confirm that `Diff` is assuming `ProtoNode` nodes as input? In that case is it ok to error out when receiving `RawNode`? If not, how the different cases should be handled?

**Comment by Stebalien** [comment]
So, `object diff` was designed to work over `ProtoNode`. However, IMO, it *would* make sense to treat `RawNode`s as protonodes with no links (within the `object` commands).

FYI, IIRC, the plan is to deprecate these commands anyways. We really should have an `ipfs dag diff`.

**Comment by schomatis** [comment]
@Stebalien Thanks for the heads up, in your opinion is it worth working on this? The main problem with this command is already address with #4767, this issue was about some more specific corner cases.

**Comment by Stebalien** [comment]
Meh. I'm not that interested in putting *too* much work into the `ipfs object` commands in general (would rather focus on `ipfs dag diff`).

**Comment by schomatis** [comment]
Ok, closing this then.
