### ISSUE TITLE
`ipfs get` doesn't work for small files

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4781]
```sh
> ipfs get -o myfile "$(echo "foo" | ipfs add -q)" && cat myfile
```

:scream:

**Comment by Stebalien** [comment]
So, apparently this only happens with go-ipfs 1.10. Possibly related to the http library? Maybe we need to flush something?

**Comment by patmaddox** [comment]
I have two machines running OS X 10.12.6 that both work with homebrew ipfs. One reports go1.9.2 and the other reports go1.10. Both show that ipfs was "poured from bottle."

The machine that's broken is a 10.10.5 machine and homebrew says it was built from source.

I'll experiment with a different go version, but maybe the above info helps somewhat...

**Comment by schomatis** [comment]
@Stebalien The new [`regFileReader.Read()`](https://github.com/golang/go/commit/3bece2fa0e10c2dec37b3f57925def40c8191e37#diff-6ce8fb1d02e21c5b3b730dd7876959e9R635) in `go1.10` now returns in a successful read that reaches the end of the file both the number of bytes read and the `io.EOF` error (I'm not sure the intention behind this change in the API, there's no comment in the `switch` nor an explanation in the commit message besides saying that *regFileReader and sparseFileReader were completely rewritten*, so it may be an unintended modification).

When the tar extractor [detects the `EOF` error](https://github.com/ipfs/go-ipfs/blob/b002acc6896a40a915f10ff1d79ce3130e34f6a6/thirdparty/tar/extractor.go#L116-L119) it assumes nothing has been read (the end of the file has been reached) so it doesn't copy anything to the output and returns no error.

**Comment by Kubuxu** [comment]
That is our mistake as EOF always could be returned with some data.

**Comment by schomatis** [comment]
You're right, as the [`Reader`](https://golang.org/pkg/io/#Reader) interface specifies:

> Callers should always process the n > 0 bytes returned before considering the error err. Doing so correctly handles I/O errors that happen after reading some bytes and also both of the allowed EOF behaviors.
