### ISSUE TITLE
Error: Import cycle not allowed

### ISSUE THREAD

**Issue by alvin-reyes** [ipfs/go-ipfs#4786]
#### Version information:
0.4.13 using go 1.10

#### Type:
Bug

#### Description:
Import cycle error when trying to build a fresh IPFS source

```
import cycle not allowed
package github.com/ipfs/go-ipfs/cmd/ipfs
        imports expvar
        imports net/http
        imports crypto/tls
        imports crypto/x509
        imports net
        imports runtime/cgo
        imports runtime/cgo
cmd/ipfs/Rules.mk:37: recipe for target 'cmd/ipfs-install' failed
make: *** [cmd/ipfs-install] Error 1

```

**Comment by Stebalien** [comment]
That's... very odd. It looks like an import cycle *in* `runtime/cgo`. We've had other issues with go 1.10 so I'd try compiling it with go 1.9.3 to see if that problem goes away.

**Comment by alvin-reyes** [comment]
I manage to resolved this by removing (unsetting) the ```
GOROOT. I am now encountering a different error.

warning: GOPATH set to GOROOT (/usr/local/go) has no effect
lbin/check_go_version 1.9
bin/check_go_path /usr/local/go/src/github.com/ipfs/go-ipfs /usr/local/go/src/github.com/ipfs/go-ipfs
gx install --global
ERROR: Error: strconv.Atoi: parsing "t": invalid syntax
ERROR: req-check hook failed: exit status 1
mk/gx.mk:4: recipe for target 'gx-deps' failed
make: *** [gx-deps] Error 1

```

**Comment by Stebalien** [comment]
Are you trying to build go-ipfs as root? I strongly recommend against this. I'd set your GOPATH to be something like `~/go` and build go-ipfs there.

**Comment by OlegKorchagin** [comment]
> ```
> import cycle not allowed
>         [...]
>         imports runtime/cgo
>         imports runtime/cgo
> ```

I apologize if I get into a serious conversation with children's opinion, but  its easy to get the same error in the same **native golang code**,  if mixed up GOLANG and GOPATH

right:
```
export GOROOT=/opt/go
export PATH=$GOROOT/bin:$PATH
export GOPATH=$HOME/work
```

fail:
```
export GOPATH=/opt/go
export PATH=$GOPATH/bin:$PATH
export GOROOT=$HOME/work
go build
[...]
import cycle not allowed
        [...]
        imports runtime/cgo
        imports runtime/cgo
```

**Comment by Kubuxu** [comment]
@OlegKorchagin thanks, I think this resolves the issue.
