### ISSUE TITLE
`ipfs get directory_hash` only gets empty files

### ISSUE THREAD

**Issue by patmaddox** [ipfs/go-ipfs#4787]
#### Version information:

go-ipfs version: 0.4.13-cc01b7f
Repo version: 6
System version: amd64/darwin
Golang version: go1.10
OS X 10.10.5

#### Type:

Bug

#### Description:

`ipfs get` with a directory hash appears to work, but only gets empty files

If I do `ipfs get QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv` (the help directory) I see:

```
Saving file(s) to QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv
 6.39 KB / 6.39 KB [================================================] 100.00% 0s
```

but the files are all empty:

```
$ ls -l QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv
total 0
-rw-r--r--  1 padillac  staff  0 Mar  6 22:08 about
-rw-r--r--  1 padillac  staff  0 Mar  6 22:08 contact
-rw-r--r--  1 padillac  staff  0 Mar  6 22:08 help
-rw-r--r--  1 padillac  staff  0 Mar  6 22:08 ping
-rw-r--r--  1 padillac  staff  0 Mar  6 22:08 quick-start
-rw-r--r--  1 padillac  staff  0 Mar  6 22:08 readme
-rw-r--r--  1 padillac  staff  0 Mar  6 22:08 security-notes
```

I just installed IPFS on this machine tonight using homebrew, I don't know if `ipfs get` ever worked. After installing IPFS I installed `osxfuse` also using homebrew, and accessed the files through the mounted `/ipfs`. I thought perhaps FUSE might be messing something up, so I uninstalled it but `ipfs get` still only gets empty files.

I can view the content directly with `ipfs cat QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv/about`

`ipfs repo verify` reports `verify complete, all blocks validated.`

**It is particularly concerning to me that `ipfs-go` does not seem to verify the results of `ipfs get` and report an error when they don't match.** After all, the whole point is that it can hash the contents and I can be confident that I'm getting the same content that was added.

**Comment by Stebalien** [comment]
Dup of #4781. Try building with go 1.9.3.
