### ISSUE TITLE
Audit bad uses of Read

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4793]
Read can:

1. Fail to fully fill the target buffer even if there's more data to be read.
2. Read data *and* return an EOF at the same time.

We haven't been handling these cases well leading to #4781. We need to audit all uses of Read.

Progress:

* [ ] ipfs org
    * [x] go-ipfs:  #4790, #4792 
    * [x] go-ipfs-cmds: none
    * [x] go-ipfs-cmdkit: none
    * [ ] fs-repo-migrations
* [x] multiformats org: https://github.com/multiformats/go-multihash/pull/72, https://github.com/multiformats/go-multistream/pull/24
* [x] libp2p org
  * [x] go-libp2p-pnet: https://github.com/libp2p/go-libp2p-pnet/pull/18
* [ ] whyrusleeping

(I'm ignoring test cases for now)

**Comment by kevina** [comment]
Not very common but, read can also:

3. Read nothing, even when not at EOF, that is both data and err will be nil.

**Comment by kevina** [comment]
> Yes, but that case is also seriously discouraged. We should handle it but handling it may often involve returning a io.ErrNoProgress error (looping would likely be a bad idea in many cases).

Maybe, it is rare enough that it unlikely we need to write special code for it.  This may mean looping until we get an EOF.   The worst thing this will do is waste CPU time unless the Reader is broken in which case the function may never return.  For example the fix #4710 (as of the time I wrote this comment) will simply loop until it gets an EOF.

Returning `io.ErrNoProgress` might be better, but it will also mean more code to handle a rare edge case.

The only thing we should not do is break out of a loop and _not_ return any indication of an error when no data is read.

**Comment by Stebalien** [comment]
> The only thing we should not do is break out of a loop and not return any indication of an error when no data is read.

Yes. Absolutely.
