### ISSUE TITLE
IPFS add hangs after some time

### ISSUE THREAD

**Issue by S3bb1** [ipfs/go-ipfs#4794]
#### Version information:
go-ipfs version: 0.4.13-cc01b7f
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2

#### Type:
Bug

#### Description:

i refer to this topic:

https://discuss.ipfs.io/t/ipfs-daemon-doesnt-add-file-after-a-while/1836/8

we're currently adding smaller files (max. 256kb) to ipfs ... and sometimes the add will stop suddenly ... no error logs ... the debug logs saying nothing relevant about any issue

i can reproduce the bug, because it appears suddenly and not on a specific file.

i can post a debug log in the timeframe when the issue occurs, but there are only debug and infos and no error

The strange thing is:
When the server don't respond anymore and i try to add a file via IPFS add and the console says "[===============================>100%]file.txt"
and dont responds ... when i cancel the request and send it again, it says me the hash of the file and no more progress indicator but without responding

**Comment by S3bb1** [comment]
we have now updated to 0.4.14-rc to see if the issue occurs twice

**Comment by Stebalien** [comment]
That may have been fixed by the RC but most of the issues fixed in the RC exhibited high memory and CPU usage (often crashing the daemon).

If you could provide a goroutine dump and, if possible, a CPU profile, that would be really helpful. See:
https://github.com/ipfs/go-ipfs/blob/master/docs/debug-guide.md

**Comment by S3bb1** [comment]
Thx for the answer! I will create a dump when the problem occurs. Server is stable since Yesterday.

**Comment by S3bb1** [comment]
Seems that 0.4.14 fixed the Problem ... no errrors since 12 days. I will close the issue and reopen it when it occurs, thanks for your help
