### ISSUE TITLE
Unable to setup private IPFS

### ISSUE THREAD

**Issue by gouravrattihalli** [ipfs/go-ipfs#4814]
#### Version information:
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2

#### Description:

Hi, 

I'm trying to setup private IPFS. I have performed the following steps:

1.  ipfs init
2.  ipfs bootstrap rm --all
3.  ipfs bootstrap add /ip4/ip addr/tcp/4001/peer ID(got from ipfs id)
4.  generated swarm.key using the key generator
5.  ipfs daemon 

I get the output as "Daemon is ready", but I'm never able to access the webui. Also when I try to access the webui, the daemon prints out 

 ERROR core/serve: ipfs resolve -r /ipfs/some ID/: Failed to get block for some ID: context canceled gateway_handler.go:621

Can someone tell me where I'm going wrong?

Thanks

**Comment by Kubuxu** [comment]
WebUI is downloaded from global network, start up daemon normally once (without private network) access WebUI and then enable private network. You need to do it just once in private network. It would be good idea to also pin it.

**Comment by gouravrattihalli** [comment]
How would I enable private network?, I tried to remove all nodes from bootstrap, and then add swarm.key, but the webui still shows up a lot of connections.

**Comment by Kubuxu** [comment]
You can set `LIBP2P_FORCE_PNET=1` to stop launch without PNET. Did you restart the daemon?

**Comment by gouravrattihalli** [comment]
Awesome, the webui is working and shows 0 nodes connected. Now to add more nodes to my IPFS I have to add the nodes in the bootstrap (this is done on both the nodes, initial and the new node to be added?)

**Comment by Kubuxu** [comment]
You have to do it on at least one node, possibly the one that will will go down more frequently or both.

For further support questions please use https://discuss.ipfs.io

**Comment by gouravrattihalli** [comment]
Awesome, thanks for the support, my nodes are now connected.
