### ISSUE TITLE
Question：Why the hash values of go-ipfs is different from the hash values of go-cid?

### ISSUE THREAD

**Issue by HanawaBanana** [ipfs/go-ipfs#4821]
I found the Cid of go-ipfs return is different from go-cid, I doubt it maybe do other things for data source. 
There are my code and result.
```go
import (
"fmt"
"github.com/ipfs/go-cid"
mh "github.com/multiformats/go-multihash"
)

func main() {
 // Create a cid manually by specifying the 'prefix' parameters
 pref := cid.Prefix{
   Version: 0,
   Codec: cid.DagProtobuf,
   MhType: mh.SHA2_256,
   MhLength: -1, // default length
 }

 // And then feed it some data
 c, err := pref.Sum([]byte("Hello World!"))
 if err != nil {
  fmt.Println("Created CID error : ", err)
 }

 fmt.Println("Created CID: ", c)
}
root@debug010000002015:~/go# go run main.go 
Created CID:  QmWvQxTqbG2Z9HPJgG57jjwR154cKhbtJenbyYTWkjgF3e



root@iZbp14ymw7axoy46k0srmrZ:~/opt/gxb4# echo -n "Hello World!" | ipfs add
added Qmf1rtki74jvYmGeqaaV51hzeiaa6DyWc98fzDiuPatzyy Qmf1rtki74jvYmGeqaaV51hzeiaa6DyWc98fzDiuPatzyy
```

If anyone give advices, thanks a lot!

**Comment by Kubuxu** [comment]
go-ipfs adds some wrapping and additional data to the file. A the `Codec` name suggests it is Protobuf based.

In case of small files (less than 256KB) you can use `Codec: cid.Raw`, `Version: 1`and `--raw-leaves` option in command line to get the same hash.

In future for questions not directly related to bugs, features or problems with go-ipfs itself please use https://discuss.ipfs.io

**Comment by HanawaBanana** [comment]
where are the specifics of how the current default behavior of ipfs add -n is implemented ?

**Comment by ZenGround0** [comment]
As far as I know there is some useful information under `ipfs add --help`.  Apart from that I'm afraid the best place I've found for the specifics is the code itself.
