### ISSUE TITLE
--help is broken for commands that require an argument that can be read from stdin 

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4837]
Unfortunately, we try to read the argument from stdin *before* parsing the help flag. To reproduce, run `ipfs dht provide --help`.

**Comment by whyrusleeping** [comment]
:(

**Comment by djdv** [comment]
Would it be crazy to have some type of alias like `ipfs help dht provide`?
I'm not proposing that as a solution, but in addition to --help, like `git` has.
