### ISSUE TITLE
question: Why is single file transfer so slow

### ISSUE THREAD

**Issue by kvm2116** [ipfs/go-ipfs#4838]
#### Version information:

go-ipfs version: 0.4.14-rc2-4bdbe1a
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2

#### Description:

I have setup a private network of 2 nodes (following the steps mentioned here: https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks).
I am sending a directory from one node to the other node.
I measured time to transfer the directory using rsync and using ipfs.

rsync takes 7 seconds, while ipfs takes 17 seconds.
Question: Why is ipfs so slow? Can it be made faster? I was expecting ipfs to take about the same time as rsync.

RSYNC:
sent 1.72K bytes  received 42.10M bytes  4.95M bytes/sec
total size is 226.37M  speedup is 5.38

real	0m7.332s
user	0m2.368s
sys	0m0.480s

IPFS:
time ipfs get QmTAFJvt6Pk9nR1grQwu7f4vQh3BbhpLhXRebBpdqu1WwV
Saving file(s) to QmTAFJvt6Pk9nR1grQwu7f4vQh3BbhpLhXRebBpdqu1WwV
 215.94 MB / 215.94 MB [===========================================] 100.00% 16s

real	0m16.806s
user	0m0.268s
sys	0m0.840s

**Comment by eingenito** [comment]
There's been some recent improvements in bitswap, including this one: ipfs/go-bitswap/pull/5 that should improve this situation. There's still plenty to do but most of the discussion and progress is going on in other issues/prs/repos. I'm going to close this issue, but of course you should feel free to reopen - or comment on the ongoing work. If you want to re benchmark with the latest changes that would be great too. Thanks.
