### ISSUE TITLE
Context Canceled Error on large directory

### ISSUE THREAD

**Issue by Cole128** [ipfs/go-ipfs#4839]
#### Version information:
Version 0.4.13

#### Type:
Bug

#### Description:
I am uploading a very large directory to ipfs, around 69 gb, and encountered an error when uploading it. My ipfs repo is set to 100 gb of space, and although I am pinning other content, I definitely have enough space on the disk and in the repo. When uploading this directory, it uploaded for a little bit, then I got this error:

```
Error: context canceled
14:52:37.072 ERROR commands/h: net/http: request canceled client.go:24
```

What does this mean, context canceled? Does it mean my machine stopped the process? Please help.

EDIT: After some testing, I am guessing my Debian GNU/Linux server cancelled the process on it's own for some reason. I tried adding a file and Ctrl-C-ing it myself, and got the same error: Context canceled. Does anyone have any idea why this would happen? This is a low level machine, and so this would be demanding for the CPU, but why would it shut down the process.

EDIT 2: Some searching shows that the kernel might be shutting down the process for taking up too much resources, I will try disabling OOM killer for that process.

**Comment by Stebalien** [comment]
We'll hopefully be releasing 0.4.14 in a few days and that may fix your oom-kill bug.

**Comment by Cole128** [comment]
@Stebalien Isn't 0.4.14 already released? Or does release candidate mean you're just testing it out. Either way it's good to know you guys know about the issue. Stopping OOM killer for that process wasn't such a big deal, but it's harsh for noobs, and was a little bit worrying, as the kernel was stopping it for a reason. Glad to hear it will be/is fixed!

**Comment by Stebalien** [comment]
> Or does release candidate mean you're just testing it out.

We're working through some last minute regressions. I can't guarantee your issue will have been fixed, but we fixed a bunch of (temporary) memory leaks around adding large directories so I'm guessing it will be.

**Comment by Kubuxu** [comment]
@Cole128 please try out the RC, you can download it from here: https://dist.ipfs.io/go-ipfs/v0.4.14-rc2

**Comment by Cole128** [comment]
Thanks. This my server though, I don't want to break anything. The rc should be stable enough though right?

Cole Anthony Capilongo
colecmac@protonmail.com

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Kubuxu** [comment]
@Cole128 yes, we are running it already. Most bugs in recent RCs were due to API compatibility, currently we are fixing: https://github.com/ipfs/go-ipfs/issues/4837. We didn't find anything that could be really problematic.

**Comment by Cole128** [comment]
Ok, thanks.

Cole Anthony Capilongo
colecmac@protonmail.com

Sent from ProtonMail mobile

-------- Original Message --------
