### ISSUE TITLE
Invalid JSON response

### ISSUE THREAD

**Issue by richardschneider** [ipfs/go-ipfs#4852]
#### Version information:
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/windows
Golang version: go1.9.2
#### Description:
The JSON response from `POST http://localhost:5001/api/v0/add?wrap-with-directory=true` is invalid JSON.  It should be an array **NOT** two JSON objects.

*Actual response*
```json
{"Name":"Qmf412jQZiuVUtdgnB36FXFX7xg5V6KEbSJ4dpQuhkLyfD","Hash":"Qmf412jQZiuVUtdgnB36FXFX7xg5V6KEbSJ4dpQuhkLyfD","Size":"19"}
{"Name":"","Hash":"QmXXrjdh9bdM6UrYoecSW6xDztjY9gWRHKc7AkMGspopFA","Size":"111"}
```

*Expected response*
```json
[
{"Name":"Qmf412jQZiuVUtdgnB36FXFX7xg5V6KEbSJ4dpQuhkLyfD","Hash":"Qmf412jQZiuVUtdgnB36FXFX7xg5V6KEbSJ4dpQuhkLyfD","Size":"19"}
{"Name":"","Hash":"QmXXrjdh9bdM6UrYoecSW6xDztjY9gWRHKc7AkMGspopFA","Size":"111"}
]
```

**Comment by Stebalien** [comment]
That's actually expected. The result is sent as a [JSON stream](https://en.wikipedia.org/wiki/JSON_streaming). Otherwise, we'd have to send the result back all at once which would be problematic for, e.g., monitoring progress.

**Comment by richardschneider** [comment]
There are four types of JSON streams.  Which one is GO IPFS using?

**Comment by richardschneider** [comment]
Perhaps some documentation would help implementators.  What other APIs use JSON stream?

**Comment by richardschneider** [comment]
Also note that `--progress` was not set, so a caller would only expect one response that contains the "wrapped directory" information not a list/stream of nodes.

@Stebalien I think this should be re-opened.

**Comment by Kubuxu** [comment]
@richardschneider as far as I know we use NDJSON. In case of add command all filtering is done on the side of the client.

**Comment by Stebalien** [comment]
> Perhaps some documentation would help implementators. What other APIs use JSON stream?

Basically, anything that takes a variable number of inputs and performs a variable number of operations. I don't know the exhaustive list but it would include:

* add
* pin ls/add/verify
* refs (local)

> Perhaps some documentation would help implementators.

Definitely. Could you open an issue here: https://github.com/ipfs/http-api-docs/issues?
