### ISSUE TITLE
Cannot access localhost pages including WebUI

### ISSUE THREAD

**Issue by zoeleesss** [ipfs/go-ipfs#4853]
#### Version information:
go-ipfs version: 0.4.13-cc01b7f
Repo version: 6
System version: amd64/darwin
Golang version: go1.9.2
OS: MacOS 10.12.6

#### Type:
Cannot access localhost:5001 and localhost:8080 via browser. 
I tried in Chrome. Didn't work.

#### Description:
e.g. 
http://localhost:5001/api/v0/version , http://127.0.0.1:8080/ipfs/QmU4wiEy1rEJtQFAEfmH5amxN8fMubhzs76xaPVUj78e3z ,
http://localhost:5001/webui/    

![screen shot 2018-03-21 at 5 04 01 pm](https://user-images.githubusercontent.com/31149915/37701622-9bbaf70c-2d2a-11e8-94f2-872d5d73e0b4.png)

The Chrome browser says `ERR_EMPTY_RESPONSE`

However, i can have access to these sites via terminal:

![screen shot 2018-03-21 at 5 08 22 pm](https://user-images.githubusercontent.com/31149915/37701649-b41f3042-2d2a-11e8-8e5c-1b2c2a159d6f.png)

![screen shot 2018-03-21 at 5 01 53 pm](https://user-images.githubusercontent.com/31149915/37701364-a5274b98-2d29-11e8-977c-8c1a5dac3836.png)

And, I can have access to this site:  
(same hash as above.)
https://gateway.ipfs.io/ipfs/QmcJBQ3ZaKgR2u2SngGiuaS9icBfX2TvxHAMxQnHReQV3X/

Does it have any thing to with my installing ?
I installed go and ipfs with homebrew:
`brew install go`
`brew install ipfs`
Then I followed the demo video. But didn't work.

At last, weirdly enough, I cannot ping ipfs.io via terminal. But can have access via browser.

![screen shot 2018-03-21 at 5 13 58 pm](https://user-images.githubusercontent.com/31149915/37701781-4615e2ca-2d2b-11e8-9b5e-0fa34b24c443.png)

Please give me some insights.
Thx!!!

**Comment by Stebalien** [comment]
May be an ipv6 v ipv4 issue? Try `http://localhost:5001` instead of `http://127.0.0.1:5001`.

**Comment by Stebalien** [comment]
Also, try upgrading to the latest git. There were a few nasty issues in the version of go-ipfs that you're using.
