### ISSUE TITLE
IPFS fails to publish name in online mode but works in  offline mode- v0.4.13 

### ISSUE THREAD

**Issue by DeepakkumarArumugam** [ipfs/go-ipfs#4858]
#### Version information: 
IPFS - 0.4.13
fs-Repo - 6
go - go version go1.10 darwin/amd64
Os - mac sierra v10.12.6

#### Description:
 @whyrusleeping  - IPFS fails to publish name in online mode with no connected peers but publishes in offline mode.

**Comment by hsanjuan** [comment]
Closing as outdated.
