### ISSUE TITLE
Linux: ERROR    bitswap: Error writing block to datastore: open /.ipfs/blocks/MX/put-253548744: permission denied bitswap.go:317

### ISSUE THREAD

**Issue by avatar-lavventura** [ipfs/go-ipfs#4860]
**Version information:**

go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2

The way I run IPFS: `ipfs daemon &`

Error I am having, when try to read a IPFS file (ex:` ipfs cat QmNmpu64oYaoKFoEtN8ZoYzRspDAyvhGgTRFm3h8dSevFe`):

```
07:27:47.687 ERROR    bitswap: Error writing block to datastore: open /home/ubuntu/.ipfs/blocks/MX/put-035762932: permission denied bitswap.go:317
07:27:47.810 ERROR    bitswap: Error writing block to datastore: open /home/ubuntu/.ipfs/blocks/MX/put-104604099: permission denied bitswap.go:317
07:27:57.754 ERROR    bitswap: couldnt open sender again after SendMsg(<peer.ID bU9jYr>) failed: dial attempt failed: <peer.ID TDHH9n> --> <peer.ID bU9jYr> dial attempt failed: dial tcp4 :5812: i/o timeout wantmanager.go:237

```

Please note that I have face similar issue that occur on Windows(https://github.com/ipfs/go-ipfs/issues/3971) on linux side as well.

**Comment by Kubuxu** [comment]
What are the permissions on those files/directories. Which file system are you using? Can you create files in this directory?

**Comment by avatar-lavventura** [comment]
My user have a root access so there should be no problem on permission.  And this works for other `ipfsHashes` for that specific `ipfsHash` it does not work.

**Comment by Kubuxu** [comment]
Can you try resolving it by running `chown -R "$USER:$USER" ~/.ipfs/`.

**Comment by avatar-lavventura** [comment]
`chown -R "$USER:$USER" ~/.ipfs/` solved the problem, thank you. What might be the reason only one ipfs-block is defined under `root` permission and others as `user`.

**Comment by Kubuxu** [comment]
You might have run `ipfs init` as a root or something like that, or run `ipfs daemon` as a root for a while.
