### ISSUE TITLE
[coreapi] [feature] Pass `Adder` options as arguments to `UnixfsAPI.Add`

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#4868]
To allow options like `--pin`, `--nocopy`, `--hash`, etc. in the [Core API](https://github.com/ipfs/go-ipfs/blob/v0.4.14/core/coreapi/unixfs.go#L19), in a similar way to [`ipfs add`](https://github.com/ipfs/go-ipfs/blob/v0.4.14/core/commands/add.go#L272) (and maybe then some of [`addAllAndPin`](https://github.com/ipfs/go-ipfs/blob/v0.4.14/core/commands/add.go#L307) could be absorbed by the Core API centralizing the add functionality).

**Comment by magik6k** [comment]
`ipfs add` is now built on top of CoreAPI now, and supports most(all?) adder functions.
