### ISSUE TITLE
ipfs get doesn't work with sharded directories

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4871]
It serializes files with the tar writer which doesn't currently support sharded directories.

https://github.com/ipfs/go-ipfs/blob/3cbf97bea12c5a1f6c007b094ca4df51b1747831/unixfs/archive/tar/writer.go#L83-L96

**Comment by diasdavid** [comment]
@VictorBjelkholm this was the problem we were seeing this morning.
