### ISSUE TITLE
Getting -unexpected end of data while extracting .tbz file in ec2 instance 

### ISSUE THREAD

**Issue by deba46** [ipfs/go-ipfs#4878]
Here is my code -  It is printing first tarinfo file and then throwing error .Looks like not able to read second file from tar file. Input file i have opened is .tbz format

```py
try:
    with tarfile.open(temp_path) as tar:
        for tarinfo in tar:
            if tarinfo.isreg():
                print("a regular file") .
                print(tarinfo.name)
except Exception as e:
        logger.error('Failure during extract:-' + str(e))
```

**Comment by Stebalien** [comment]
@deba46 I believe you've found the wrong issue tracker :laughing:. This is the issue tracker for go-ips, the Go implementation of Interplanetary Filesystem.

If not, feel free to reopen this issue. If you do, please add some additional information:

* IPFS version
* What you were doing at the time.
* How this issue relates to go-ipfs.
