### ISSUE TITLE
Api Docs

### ISSUE THREAD

**Issue by nothingismagick** [ipfs/go-ipfs#4879]
## api docs

The current release of go-ipfs is v0.4.14, but https://ipfs.io/docs/api/ shows that the docs were 

> Generated on 2017-08-23, from go-ipfs v0.4.11-dev

Seeing as there have been over 700 commits to master since this release, are these api docs accurate - or more to the point, where are the api-docs for v0.4.14?

**Comment by Mr0grog** [comment]
This might be better covered over at https://github.com/ipfs/http-api-docs/issues/3#issuecomment-375174441 . It was actually hand-edited *after* that generation date (although I’m still not sure it’s actually up-to-date).
