### ISSUE TITLE
Improve docs around ipfs update

### ISSUE THREAD

**Issue by nothingismagick** [ipfs/go-ipfs#4880]
## SOLUTION (Worked for me this time)

``` bash 
$ go get -u github.com/ipfs/ipfs-update
$ ipfs update versions
$ ipfs update install v0.4.14
# or
$ go get -u github.com/ipfs/ipfs-update
$ ipfs update install latest
```

### Caveat: 
I know that this is really an issue for ipfs-update (will post there too)

### Background:
I want to update go-ipfs from `ipfs version 0.4.14-rc3` to `ipfs version 0.4.14` (but actually I don't care just want latest) and there is a command listed under ipfs --help that says:

```
ipfs update --help

ipfs-update is an 'external' command.
It does not currently appear to be installed.
Please refer to the ipfs documentation for instructions.
```

Which [ipfs documentation](https://docs.google.com/spreadsheets/d/1IDVAGfniyHCJLIxLc3y7K7YTOFGCtgwTVCZEojtNLlw/edit#gid=0)? The fastest way was to duckduckgo search for ipfs update, choose the github repo, parse the README, copy, paste, execute go get, run `ipfs update`, it shows me its internal version (1.5.3 but really I don't care), no - I have to run it twice more, `ipfs update versions`, read the list for the latest one, now `ipfs update install v0.4.14`.  

The relevant question here is:  Why is it an external command (and a non-installed one at that) if it is listed as a tool in the CLI `ipfs --help`?

**Comment by nothingismagick** [comment]
@VictorBjelkholm  [wrote](https://github.com/ipfs/ipfs-update/issues/83#issuecomment-376578238): 

> A possible flow would be to run `ipfs update` without any additional flags/arguments would check for a new version but not install it. Running `ipfs upgrade` would upgrade to the latest version found.

My current workaround for this command (for embedding in shell scripts etc.) is:

```
$ ipfs update install $(ipfs update versions | sed '$!d')
```

**Comment by Kubuxu** [comment]
Could you rename the issue to: "Improve docs around `ipfs update`".

**Comment by nothingismagick** [comment]
@Kubuxu - I changed it, but it is also an issue about expected behaviour within the CLI. Adding a new command to the cli (ipfs upgrade) is more than a mere documentation issue.

**Comment by Kubuxu** [comment]
I think it might be good for `ipfs update` to install the newest version after user confirmation.

**Comment by djdv** [comment]
Something like
>v0.0.1 is installed, v0.0.2 is available. Upgrade? [y/N]

or if already up to date
>v0.0.2 already up to date

**Comment by aschmahmann** [comment]
Downloading ipfs-update is now documented if you type `ipfs update` or `ipfs update --help`
