### ISSUE TITLE
what's the ipnsps used for?

### ISSUE THREAD

**Issue by llgoer** [ipfs/go-ipfs#4901]
I find ipnsps in /core/commands/ipnsps.go,but i use `ipfs daemon --enable-namesys-pubsub`to start ,then the IPNS also too slow.

**Comment by Stebalien** [comment]
It's IPNS over pubsub. If you have the namesys-pubsub experiment enabled, every time you resolve a new IPNS address IPFS will subscribe to updates to that IPNS record using pubsub. That way, when you resolve that address in the future, you should already know the result (received over pubsub) and won't have to go to the DHT to find it.

That is, of course, the theory. In practice, it's a highly experimental feature that may cause all manner of trouble. Be warned.

I've opened a new issue for documenting this feature: https://github.com/ipfs/go-ipfs/issues/4902

If you have any more questions about IPNS over pubsub, please continue the discussion on: https://discuss.ipfs.io/
