### ISSUE TITLE
Build error due to Window newline symbol

### ISSUE THREAD

**Issue by maybeuright** [ipfs/go-ipfs#4905]
I build the code on win64 PC with cygwin.
I found all the files contained window newline '\r' and golang compiler cannot recognize it.
The solution is as below:

cd src
find . -type f -exec dos2unix.exe {} \;

**Comment by maybeuright** [comment]
Don't think it's a bug.
But it's not convenient.

**Comment by Kubuxu** [comment]
I think it is your Git settings. Here all files have LF line ends.
```
commands/command.go: ASCII text
```
if it was CRLF it would be:
```
commands/command.go: ASCII text, with CRLF line terminators
```

**Comment by maybeuright** [comment]
Yes, this is the root cause. Thanks!

**Comment by maybeuright** [comment]
The root cause is 
1) GO compiler cannot compile files including CRLF.
2) My config item "core.autocrlf" is true, which means git replaced LF with CRLF when download.
3) Suggest using "git config --global core.safecrlf true"
