### ISSUE TITLE
Add a config profile ls command

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4913]
Currently, figuring out which profiles exist is a bit of a pain. It would be nice to have a `config profile ls` command that lists all the existing profiles.

Ideally, this would work by introspecting the list of profiles in `repo/config/profile.go`. However, to make that work, the `Transformer` functions there will need to be replaced with `Profile` structs:

```go
type Profile struct {
	Description	string
	Transformer	func(c *Config) error
}
```

**Comment by preetsinojiya** [comment]
Will work on this!

**Comment by magik6k** [comment]
https://github.com/ipfs/go-ipfs/pull/4846/files sort of solves it already
