### ISSUE TITLE
Add a --dry-run flag to config profile apply

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4914]
This would print a diff between the current config and the config that *would* be generated. Possibly using, e.g., https://github.com/elgris/jsondiff

**Comment by preetsinojiya** [comment]
Seems like no one is working on this one now. So will work on this one and update the progress.

**Comment by preetsinojiya** [comment]
Any suggestion for the change that aligns with the ipfs preferred code design will be appreciated.
