### ISSUE TITLE
Windows Ctrl-C and daemon

### ISSUE THREAD

**Issue by richardschneider** [ipfs/go-ipfs#4922]
#### Version information:
go-ipfs version: 0.4.14-
Repo version: 6
System version: amd64/windows
Golang version: go1.10

#### Description:
Run the daemon in a Windows command prompt and the press `CTRL-C`.  The daemon stops  However, if I run the daemon again I get the following error

```
Initializing daemon...
Error: cannot acquire lock: file "C:\\Users\\Owner\\.ipfs\\repo.lock" already locked
Received interrupt signal, shutting down...
```

**Comment by Kubuxu** [comment]
You can recover it with `ipfs repo fsck` and it should be fixed in next version.

Resolved by https://github.com/ipfs/go-ipfs/pull/4855
