### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by mym-xjl** [ipfs/go-ipfs#4925]
D:\go_workspace\src\github.com\ipfs\go-ipfs>go get -u github.com/whyrusleeping/gx
package golang.org/x/sys/windows: unrecognized import path "golang.org/x/sys/windows" (https fetch: Get https://golang.org/x/sys/windows?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

**Comment by llgoer** [comment]
use proxy to get it

**Comment by djdv** [comment]
Users located in China should look at these:
https://github.com/ipfs/go-ipfs/issues/4851
https://github.com/ipfs/go-ipfs/issues/4684

golang.org and ipfs.io may be blocked by GFW :^(

**Comment by djdv** [comment]
Soon, we'll be distributing tar archives which contain everything you need to build offline, this should help users who have specific network restrictions.

**Comment by Kubuxu** [comment]
We both provide tarballs (https://github.com/ipfs/go-ipfs/pull/4920) and support go modules (https://github.com/ipfs/go-ipfs/pull/6038) now so I call it resolved.
