### ISSUE TITLE
docker image for ARM

### ISSUE THREAD

**Issue by yrzr** [ipfs/go-ipfs#4931]
Since we do have ARM build, why not an ARM docker image?

The official images [arm32v7/golang](https://hub.docker.com/r/arm32v7/golang/) and [arm32v7/busybox](https://hub.docker.com/r/arm32v7/busybox/) can be used as the base image.

Moreover, `COPY --from=0 /lib/x86_64-linux-gnu/libdl-2.24.so /lib/libdl.so.2` should be changed to `COPY --from=0 /lib/arm-linux-gnueabihf/libdl-2.24.so /lib/libdl.so.2` and `  && wget -q -O tini https://github.com/krallin/tini/releases/download/$TINI_VERSION/tini \` should be changed to `  && wget -q -O tini https://github.com/krallin/tini/releases/download/$TINI_VERSION/tini-armhf \`

I've successfully built images [here](https://hub.docker.com/r/yrzr/go-ipfs-arm64v8).

@lgierth

**Comment by johnelliott** [comment]
I just ran the @yrzr image successfully. 👍

**Comment by johnelliott** [comment]
@yrzr I see you've made some CI code to maintain that image, but it looks like it's based of modifying the dockerfile here with the changes you outlined above. Are these changes something we could commit to this repository?

**Comment by yrzr** [comment]
@johnelliott Thank you for your reply. It seems that writing a dedicated `Dockerfile.arm` file, build and push corresponding images to docker hub is a common solution.

**Comment by yrzr** [comment]
@johnelliott My modifications are meant to be built on ARM. If one wants to build ARM images on x86, here is a [solution](https://github.com/multiarch/crossbuild).

**Comment by johnelliott** [comment]
Yes, I did not yet try to build the same image  with your changes on the hypriot-pi machine but I have no doubt it will work similarly.

If the convention exists to have an additional Dr. file in this repo then I support that idea. It seems more difficult to maintain that in a separate repository

**Comment by johnelliott** [comment]
I successfully built and ran a node with @yrzr's proposed changes based on https://github.com/yrzr/go-ipfs-armhf/blob/master/.gitlab-ci.yml. If it was this simple I think others would benefit.

@Stebalien If I fork/commit/pr, what other things should I know about in order to contribute?

**Comment by roderik** [comment]
since the amd64 image was crashing on quemu on a M1 mac, i quickly built 0.8.0 on github for arm as well using github actions. No changes needed, just the GHA actions.

https://github.com/settlemint/go-ipfs/blob/feat/arm-build/.github/workflows/docker.yml

Image is available here: https://hub.docker.com/repository/docker/settlemint/go-ipfs

**Comment by odanado** [comment]
I've created various versions of go-ipfs Docker Images.

Docker Hub: https://hub.docker.com/r/odanado/go-ipfs/tags
GitHub: https://github.com/odanado/go-ipfs-docker
