### ISSUE TITLE
Data in Merkle DAG service

### ISSUE THREAD

**Issue by OhJerry** [ipfs/go-ipfs#4935]
I am trying to figure out how file is "added" into ipfs. 
I noticed that the data inside DAG nodes are not just plaintext, but texts with special characters:
![image](https://user-images.githubusercontent.com/19763683/38637323-d5bceb6c-3d98-11e8-8c7a-62f54414bd3c.png)
I am now focusing on merkledag\coding.go, and this screenshot shows different n.data with different inputs. Notice that each string with different length has different prefix and postfix.

Those special characters seems having some relationship with **marshal** functions, that helps to encrypt the message(?). When I delete them, some error would occur, like this one:
Error: proto: bad wiretype for field unixfs_pb.Data.Fanout: got wiretype 7, want 0

So which function produces those special characters, and why do we need them?

**Comment by ivan386** [comment]
https://ipfs.io/docs/commands/#ipfs-add
### ipfs add <path>
By default ipfs wrap file data by dag node. Dag node contain 2 protobuffers.
1. https://github.com/ipfs/go-ipfs/blob/0cb22ccf359e05fb5b55a9bf2f9c515bf7d4dba7/merkledag/pb/merkledag.proto#L31-L39
2. https://github.com/ipfs/go-ipfs/blob/0cb22ccf359e05fb5b55a9bf2f9c515bf7d4dba7/unixfs/pb/unixfs.proto#L3-L20

merkledag PBNode.Data contains unixfs message Data
unixfs Data.Data contans file data

### ipfs add --raw-leaves <path>
If you use flag --raw-leaves on add then it will be raw file data for files less than 256kb.

If you add big file than it will be splitted on 256kb parts and build merkledag tree.
