### ISSUE TITLE
Multiple connections to same node?

### ISSUE THREAD

**Issue by sci4me** [ipfs/go-ipfs#4938]
I just started running the IPFS node on my machine and, in the webui, I noticed that there appear to be more than one connections to the same node. Not sure if this is intentional but seems like a bug.

**Comment by Stebalien** [comment]
That can happen if both sides try to connect at the same time. I'm currently working on a large refactor of go-libp2p that'll make this slightly better but we need connection migration to completely fix this (a non-trivial problem).

Just to make sure, *how* many of these duplicate connections are you seeing and what do they look like?

**Comment by sci4me** [comment]
I was only seeing one or two, but right now I see none. What do you mean by what do they look like?

**Comment by Stebalien** [comment]
> I was only seeing one or two, but right now I see none.

Yeah, that sounds like simultaneous connects (can happen when there's a disconnect and then both sides reconnect at the same time).

> What do you mean by what do they look like?

A screenshot but that shouldn't be necessary now.

---

Closing in favor of #4644.
