### ISSUE TITLE
Config is not thread-safe

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4942]
While we try to make it thread-safe by copying the config on read (see `Repo.Config()`) this doesn't really fix the problem because we have, e.g., maps inside of it. Furthermore, while not safety issue, the profile apply commands don't compose atomically.

Instead of exposing `Config()`, `SetConfig()`, `BackupConfig()`, etc., we should probably provide the following two methods:

```go
ReadConfig(read func (cfg *Config) error) error

// Not sure about the signature but I'd *like* backups to be atomic.
UpdateConfig(update func (cfg *Config) error, backup bool) (backup string, err error)
```

**Comment by chenminjian** [comment]
I am very interested in this. Can I help with this?

**Comment by Stebalien** [comment]
I'd like to get someone (@magik6k? @schomatis?) to comment on the design first.

**Comment by magik6k** [comment]
Looks good to me

**Comment by Stebalien** [comment]
@chenminjian then go ahead.

**Comment by chenminjian** [comment]
OK.

**Comment by schomatis** [comment]
SGTM

**Comment by kevina** [comment]
This SGTM but I would need to see how the implementation works out.

**Comment by schomatis** [comment]
@Stebalien Is this blocked by https://github.com/ipfs/go-ipfs/pull/5634 or can @chenminjian still attempt a fix here?

**Comment by Stebalien** [comment]
Not really. That fixes the thread-safety issue but still doesn't allow for atomic config updates. For that, we need this change (so we can apply transformations while holding a lock on the entire config.

**Comment by Stebalien** [comment]
Really, I'm not sure if there *is* a thread-safety issue anymore (if ever?). However, having a way to clone the config is still useful.

**Comment by schomatis** [comment]
> However, having a way to clone the config is still useful.

Ok, pinging @chenminjian then, as he seemed really interested in this and has already landed some pretty useful patches regarding the `go-ipfs` config system.

**Comment by chenminjian** [comment]
❤️ Thanks for pinging me. I watched go-ipfs, so I didn't notice this email immediately.

**Comment by chenminjian** [comment]
> However, having a way to clone the config is still useful.
This has been implemented in the latest `go-ipfs-config`.
