### ISSUE TITLE
Infinite loop in refs command client

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#4945]
#### Description:

I did `ipfs refs -r z8mWaFiA3ZiXGAPg8vKUJpnsGMErzLyN5` to fetch the Git repository mentioned in [git-remote-ipld](https://github.com/magik6k/git-remote-ipld). After a minute or so of printing CIDs, it seems to get into an infinite loop printing ever more CIDs, and eventually runs out of memory (> 30 GB). Note that this is the client, not the daemon. The daemon is fine.

I can pin the thing just fine.

**Comment by Kubuxu** [comment]
@magik6k dedup it with #4944
