### ISSUE TITLE
gx install hangs fetching random dependancies 

### ISSUE THREAD

**Issue by mrosset** [ipfs/go-ipfs#4947]
#### Type:

Bug
#### Description:
I'm updating a power8 install, because power8 doe not have gx or ipfs binaries. I just bootstrap by hand.
However gx install will hang randomly installing dependacies. I thought it might be network related so I attempted to use  gx install on another network and on a x86_64 arch. And It I still get network hangs on muliple machines. it's not one particular package, if I stop the install and start again, it will randomly hang on something else.

**Comment by lgierth** [comment]
We're having issues on the ipfs.io gateway in the past hour which should be a bit better now. Retry.

**Comment by mrosset** [comment]
I just noticed it seems to be resovled now, thanks for the quick reply. 

The reason made this issue is this is not an isolated case. I really like ipfs, but  I can't help but wonder if something needs to be done to have either gx time out with a error message. Or use a dedicated gateway for gx packages. I'm also not gx fan, though I understand the use case here. I really am fond of go get :)
