### ISSUE TITLE
Error when renaming keys

### ISSUE THREAD

**Issue by martin-looklet** [ipfs/go-ipfs#4953]
#### Version information:

go-ipfs version: 0.4.14-
Repo version: 6
System version: amd64/darwin
Golang version: go1.10

#### Type:

Bug

#### Description:

If I create a key with `ipfs key gen` and try to rename it, I get an error, but the key is renamed:
```
> ipfs key gen --type=rsa --size=2048 key1
> ipfs key rename key1 key2 
Error: expected a KeyRenameOutput as command result
> ipfs key list
self
key2
```

**Comment by grokcoder** [comment]
This issue should be closed

**Comment by Kubuxu** [comment]
@grokcoder thanks for fixing it.
