### ISSUE TITLE
`ipfs pin add` concurrency problem on low-end systems

### ISSUE THREAD

**Issue by elitak** [ipfs/go-ipfs#4963]
#### Version information:
go-ipfs version: 0.4.11-
Repo version: 6
System version: arm64/linux
Golang version: go1.8.5

#### Description:
I'm running the daemon on an ARM machine where resources are tight. It has 1GB of RAM and a large volume over USB2.0. The following is a problem I run into very reliably.

I have a directory full of symlinks to /ipfs/<SomeMultiHash>. If I want to mass-pin them I have 2 ways of doing this:
 - `find -type l -print0 | xargs -0 readlink -m | xargs -l ipfs pin add` ~~(This works fine, pinning each one-by-one)~~ _edit: It turns out this fails in the same way eventually, too._
 - `find -type l -print0 | xargs -0 readlink -m | ipfs pin add` (feeds tho whole list via stdin)

The latter, when run across only a few hundred links, results in errors like:

```
Error: pin: The block referred to by '<<redacted multihash>> was not a valid merkledag node``
and subsequently,

Error: pin: Failed to get block for <<redacted multihash>>: open /mnt/storage/blocks/<<redacted block path>>
<<redacted block id>>.data: structure needs cleaning
```

I have to remount the FS at this point. I get the "structure needs cleaning" message on both EXT4 and XFS.

Why does the stdin mode of `ipfs pin add` thrash the disk so badly that it faults? Shouldn't the daemon process the hashes in smaller chunks? Maybe at least add a commandline option for `ipfs pin add` that causes it to process lines serially, one at a time.

**Comment by Stebalien** [comment]
Triaging old issues...

Unfortunately, this looks like a hardware issue.
