### ISSUE TITLE
Ipfs swarm connect with empty timeout parameter doesn't print error message

### ISSUE THREAD

**Issue by PlayerWithoutName** [ipfs/go-ipfs#4964]
#### Version information:
ipfs version --all                                                                                                                                
go-ipfs version: 0.4.14-rc3-3ae409019
Repo version: 6
System version: amd64/linux
Golang version: go1.9.3

#### Type:
Bug

#### Description:
When `ipfs swarm connect` is used with timeout, and the timeout is reached, it prints that the context deadline was exceeded. However, when the flag is present, but has no value, command exits with code 1 and doesn't print anything.

#### Steps to reproduce:

`ipfs swarm connect /any_peer_address --timeout=`

**Comment by overbool** [comment]
Hey @Stebalien, Could you help me review my pr in https://github.com/ipfs/go-ipfs-cmds/pull/118

**Comment by Stebalien** [comment]
Done! The fix will be included in the next update of go-ipfs-cmds. Thanks @overbool!

**Comment by Stebalien** [comment]
Merged.
