### ISSUE TITLE
ipfs daemon -- Error: EOF

### ISSUE THREAD

**Issue by vasa-develop** [ipfs/go-ipfs#4969]
#### Version information:
go-ipfs version: 0.4.14-
Repo version: 6
System version: amd64/linux
Golang version: go1.10

#### Type:
Bug

#### Description:
Fresh installation of ipfs was done.
```ipfs daemon``` was not working.
Logs for ```IPFS_LOGGING=debug ipfs daemon ```

```
16:44:57.855 DEBUG   cmd/ipfs: config path is /home/vasa/.ipfs run.go:107
Initializing daemon...
Successfully raised file descriptor limit to 2048.
16:44:57.859 DEBUG       core: core is shutting down... builder.go:142
16:44:57.859 ERROR   cmd/ipfs: error from node construction: EOF executor.go:108
Error: EOF
Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)
```
Note:  the daemon was working with ```ipfs daemon --offline```

**Comment by magik6k** [comment]
Might be related: https://github.com/ipfs/go-ipfs/pull/4952. If you weren't setting up private network then it's a different issue.

Would it be a problem for you to share the ipfs repo (`~/.ipfs`)? Note that sharing it will expose some keys, so you'll have to remove and re-init it.

**Comment by vasa-develop** [comment]
Nope, I wasn't trying the private net.
[Here](https://github.com/vasa-develop/ipfs_repo) is the link to my repo.

**Comment by magik6k** [comment]
You have empty `swarm.key` in your repo, which is for private net setup. Removing this file should fix the issue. #4952 will provide a better error message. Do you have any idea for how the file might have gotten there?
