### ISSUE TITLE
Leveldb corruption

### ISSUE THREAD

**Issue by Magalame** [ipfs/go-ipfs#4981]
#### Version information:
go-ipfs version: 0.4.12-rc1-8ec1ce9e
Repo version: 6
System version: arm/linux
Golang version: go1.9

#### Type:
Bug

#### Description:

* What you were doing when you experienced the bug.

I played around a bit with launching/killing ipfs, because it was using a lot of ressources, and it kept rebooting.

* Any error messages you saw, *where* you saw them, and what you believe may have caused them (if you have any ideas).

The actual bug is that when I want to actiate it now, with `ipfs deamon` I obtain the following:

Initializing daemon...
Adjusting current ulimit to 2048...
Successfully raised file descriptor limit to 2048.
Error: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000224]

From what I know there is an [easy](https://ceph.com/planet/how-to-repair-a-leveldb-database/) way to fix this, however I do not know the location of the said database.

Thanks for your help!

**Comment by Stebalien** [comment]
> Please always try to shutdown IPFS gracefully to prevent corruption.

Note: IPFS *should* recover from a crash. This is a bug.

**Comment by Magalame** [comment]
Just in case it helps, the repair from python worked perfectly well!

**Comment by domainvip** [comment]
how to recover the file?

**Comment by Magalame** [comment]
```
$ python
…
>>> import leveldb
>>> leveldb.RepairDB("~/.ipfs/datastore")
```

**Comment by domainvip** [comment]
leveldb.RepairDB("~/.ipfs/datastore")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
leveldb.LevelDBError: IO error: ~/.ipfs/datastore: No such file or directory

**Comment by Magalame** [comment]
Try that:
```
$cd ~/.ipfs/datastore
$ python
…
>>> import leveldb
>>> leveldb.RepairDB("./")
```

**Comment by domainvip** [comment]
it works!thank you very mush!

**Comment by Magalame** [comment]
Welcome!
