### ISSUE TITLE
PubSub Example

### ISSUE THREAD

**Issue by agahEbrahimi** [ipfs/go-ipfs#4987]
Hello,

I have been trying to make the Getting started example [here](https://ipfs.io/blog/25-pubsub/) work, but all it does is give 
`20:16:49.493 ERROR   floodsub: error reading rpc from <peer.ID (a peer ID)>: connection reset comm.go:36`
this error consecutively in the daemon. 
I've also been trying to find a working example of writing pubsub into the code and using it, but all I found was the Godoc for pubsub in the go-ipfs-api. 

Thank you in advance,
Note: I have seen the JS examples of pubsub and I'm asking about Go and not JS.

**Comment by travisperson** [comment]
Related to #4604 

Looks like there was a fix that went into `go-floodsub` (appears the error isn't really an error).

**Comment by Stebalien** [comment]
Yes, that error is just noise. As it is, there isn't really anything we can do here so I'm going to close this issue for now.
