### ISSUE TITLE
Calling `/shutdown` on API usually closes connection without sending reply

### ISSUE THREAD

**Issue by alexander255** [ipfs/go-ipfs#4994]
#### Version information:

go-ipfs version: 0.4.14-
Repo version: 6
System version: amd64/linux
Golang version: go1.10

#### Type:

Bug

#### Description:

Usually invoking the `/shutdown` API call over the HTTP API will disconnect before sending a reply, causing spurious errors in clients invoking this call. This was not the case in previous versions.

**Comment by Stebalien** [comment]
Duplicate: https://github.com/ipfs/go-ipfs/issues/4055
