### ISSUE TITLE
ipfs files cp command help text inaccurate

### ISSUE THREAD

**Issue by achingbrain** [ipfs/go-ipfs#4996]
The CLI help says that `ipfs files cp` can be used to copy files into mfs:

```sh
$ ipfs files cp --help
USAGE
  ipfs files cp <source> <dest> - Copy files into mfs.
```

It doesn't seem to work like that though:

```sh
$ ipfs files cp ./my-file.txt /my-file.txt
Error: paths must start with a leading slash
```

**Comment by Mr0grog** [comment]
I *think* what this is meant to mean (at least what I have found) is that it only copies *from* IPFS-at-large, not from disk:

```sh
$ ipfs files cp /ipfs/QmV5QdWAVbYCpcEspWu4tiCtVfdL9SESidLmnXLEJ82gdL /research-stuff
```

So if you want to copy from disk:

```sh
$ ipfs add ./my-file.txt
$ ipfs files cp /ipfs/<hash from previous command> /my-file.txt
```

The help text could still be clearer on that, though. I definitely tried to do what you’re describing the first time :P

**Comment by achingbrain** [comment]
Ok, so the source can be IPFS-at-large or the existing mfs, but IPFS-at-large seems to win in the case where there's a matching path in your mfs:

```sh
$ echo 'alive' | ipfs files write --create /dog.txt
$ ipfs files cp /dog.txt /cat.txt
$ ipfs files read /cat.txt
alive
$ ipfs files stat --hash /cat.txt
QmcDam5WmvRs3ExhQrUSYdT43iERyDdVVPkmtW5L2y64h9
$ ipfs files mkdir /ipfs
$ echo 'dead' | ipfs files write --create /ipfs/QmcDam5WmvRs3ExhQrUSYdT43iERyDdVVPkmtW5L2y64h9
$ ipfs files cp /ipfs/QmcDam5WmvRs3ExhQrUSYdT43iERyDdVVPkmtW5L2y64h9 /shroedinger.txt
$ ipfs files read /shroedinger.txt
```

...drumroll

```sh
alive
```

**Comment by Mr0grog** [comment]
Yeah, I *believe* that’s a known issue based on comments like this: https://github.com/ipfs/go-ipfs/issues/4602#issuecomment-360927582

**Comment by nickdex** [comment]
I had to find this issue after searching quite a lot (maybe I was just unlucky) learn how to use files api :sweat_smile:

**Comment by hsanjuan** [comment]
@nickdex, @achingbrain  can you review: https://github.com/ipfs/go-ipfs/pull/7069 ?

**Comment by nickdex** [comment]
@hsanjaun looks much better now, thank you.
