### ISSUE TITLE
IPNS resolution doesn't always honor timeout

### ISSUE THREAD

**Issue by karalabe** [ipfs/go-ipfs#4997]
#### Version information:
Build from source, latest master

#### Type:
Bug

#### Description:
I was benchmarking IPNS publishing and resolution performance. See https://github.com/ipfs/go-ipfs/issues/3860#issuecomment-386103425 for a preliminary report.

One anomaly my benchmark surfaces was that IPNS resolution sometimes doesn't honor the configured timeout. If you look at my benchmark report chart, the blue triangles represent the time a `Namesys.Resolve` method call took. They are almost always at 9 seconds (my configured timeout), however every now and again, they bump up to 15-20 seconds, occasionally 1+ minute. This seems to indicate that IPNS resolution gets blocked on a mutex, preventing it from timing out. This is a significant issue, since code relying on it cannot have QoS guarantees and/or properly act on failures.

![ipns](https://i.imgur.com/S7WMjAf.png)

The code snippet I used to do the IPNS resolutions is:

```go
// Start a new IPFS node to consume IPNS entries from
node, err := core.NewNode(context.TODO(), &core.BuildCfg{Online: true})
if err != nil {
	log.Crit("Failed to start consumer node", "err", err)
}
defer node.Close()

[...]

for i := 0; ; i++ {
	// Start a new name system for each resolution to prevent cache hits
	node.Namesys = namesys.NewNameSystem(node.Routing, node.Repo.Datastore(), 1024)

	// Resolve IPNS ad ifinitum
	log.Info("Resolving IPNS entry", "peers", len(node.Peerstore.Peers()))
	start := time.Now()

	res, err := node.Namesys.Resolve(context.TODO(), "/ipns/"+addr.B58String(), func(opt *nsopts.ResolveOpts) { opt.DhtRecordCount = 3; opt.DhtTimeout = 9 * time.Second })
	if err != nil {
		log.Error("Failed to resolve IPNS entry", "peers", len(node.Peerstore.Peers()), "elapsed", time.Since(start), "err", err)
	} else {
		log.Info("Resolved IPNS entry", "value", res.Segments()[1], "peers", len(node.Peerstore.Peers()), "elapsed", time.Since(start))
	}
	// Don't spin like crazy
	time.Sleep(3 * time.Second)
}
```

**Comment by vyzo** [comment]
It might be the big sender lock rearing its ugly head.

Related work:
- https://github.com/libp2p/go-libp2p-kad-dht/issues/88
- https://github.com/libp2p/go-libp2p-kad-dht/pull/92

**Comment by Stebalien** [comment]
We have now fixed this. The primary issue was that we waited on a per-peer lock. We now use a custom "context obeying" lock here.
