### ISSUE TITLE
My server ip:8080:ipfs/Qmco94dYP733XwrUqFUhDtDG8RsqmGQ6UDPvnmH4Pvy2rv

### ISSUE THREAD

**Issue by blockChainB** [ipfs/go-ipfs#5015]
My server is on the public net, after IPFs daemon

My server ip:8080:ipfs/Qmco94dYP733XwrUqFUhDtDG8RsqmGQ6UDPvnmH4Pvy2rv

Do not work, why? thanks you

**Comment by overbool** [comment]
Change `"Gateway": "/ip4/127.0.0.1/tcp/8080"` to `"Gateway": "/ip4/0.0.0.0/tcp/8080"`  in `~/.ipfs/config`

**Comment by Stebalien** [comment]
@blockChainB in the future, please try to ask support questions on https://discuss.ipfs.io/.
