### ISSUE TITLE
Identity hash length check

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#5019]
The length of the identity hash is not checked, why is that?

https://github.com/ipfs/go-ipfs/blob/578cb240d4c8e294282400848966ae0d374c6b94/thirdparty/verifcid/validate.go#L57-L59

The identity hash should always have a digest length equal to the size of its data (`minimumHashLength` wouldn't apply here), otherwise a collision attack would be trivial. The identity hash is the only function where the confusion property is zero, each output byte has a one-to-one mapping with its input, trimming the output effectively leaves blind spots at the input.

**Comment by kevina** [comment]
@schomatis the idea of the Identity hash is that the data is in the hash itself, if the hash is trimmed then the data the hash represents will be different so I am not sure how this can lead to a collision attack.

Having the reported length be different from the actual length should still be an error though as it is meaningless, but it doesn't create a security problem as far as I can tell.

**Comment by schomatis** [comment]
If it is part of the spec, I would prefer to rely on the meaning of a negative `MhLength`, which is interpreted as the default hash length, and for the identity hash that is `-1` which the sum interprets as "do not trim". If that is valid I would just modify `ValidateCid` to enforce a negative `MhLength` in the case of the identity hash.

@Kubuxu WDYT?

**Comment by vyzo** [comment]
> The length of the identity hash is not checked, why is that?

bug or feature?

**Comment by Kubuxu** [comment]
In the cid security, it is not checked because it can be shorter.

> If that is valid I would just modify ValidateCid to enforce a negative MhLength in the case of the identity hash.

I don't fully understand, cid security deals only with encoded multihashes and it is not possible to encode negative number as for multihash spec.

**Comment by schomatis** [comment]
> In the cid security, it is not checked because it can be shorter.

@Kubuxu Yes, I understand, but it shouldn't (IMO) because of the security concern described above.

> it is not possible to encode negative length as for multihash spec.

The Multihash implementation heavily relies on negative values to signal an undefined/default length, that's why I was asking. But if that is not part of the specification maybe we should go with @kevina's solution. I wasn't particularly thrilled with it because I'm not sure if the `Sum` functionality should be concerned with this type of check (which will effectively divide the length check between `Sum` and `ValidateCid`).

**Comment by schomatis** [comment]
@kevina Could you take a look at https://github.com/multiformats/go-multihash/pull/74 please, WDYT?

**Comment by schomatis** [comment]
So, picking up from the discussion in the https://github.com/multiformats/go-multihash/pull/74, I'll then add a patch here to enforce a `MhLength` equal to `-1`, that means, to never truncate an identity hash. Note that a `MhLength` with a positive value equal to the length of the data currently associated with the prefix is not valid, as the `Cid` object has no knowledge of such data so it can't rely on that, it should always stay as a generic "do not truncate".

**Comment by Stebalien** [comment]
Sounds reasonable. However, I'd also add back the patch to go multihash that checks if mhlen == len(data) or mhlen < 0 (as a "prefix" identity hash is useless and dangerous in general).

**Comment by kevina** [comment]
> I'll then add a patch here to enforce a MhLength equal to -1, that means, to never truncate an identity hash.

I don't think that is correct.  A cid prefix can have a length of -1 but a full CID should not have a length of -1.  I will not support that idea without a lot of very careful review.  It is likely to break things.  I don't the Cid once converted to its binary representation should ever have a -1 length otherwise there will be two ways to represent the same multihash.  If I am missing something obvious I apologize.

**Comment by schomatis** [comment]
> I don't think the Cid once converted to its binary representation should ever have a -1 length otherwise there will be two ways to represent the same multihash.

I'm not sure I see the problem here, the hash will be the same. But I agree that representations should be normalized as much as possible (that's why I wanted to always have a `-1` instead of the data length).

Anyway, all these are design considerations that are secondary to the main issue, which is including a check for the identity hash length, that's my main priority here, @kevina I've implemented your [proposed solution](https://github.com/multiformats/go-multihash/pull/77), let me know what you think please.

**Comment by Kubuxu** [comment]
@schomatis it is not possible to express `-1` in CID, the numbers inside CID's and multihashes are unsigned varints.

**Comment by schomatis** [comment]
@Kubuxu I see. `MhLength` is defined as a signed integer but it is encoded as an unsigned one. Why is that? (I'm just asking out of curiosity, to better understand the Multihash spec and implementation, not to modify the solution proposed here.)

**Comment by Kubuxu** [comment]
Because `-1` is used to signify default length. If you are asking: why the `MhLength` is signed.

If you are asking why the multihash encoded value is unsigned: apart from truncation, the length field can be used to skip hash with unknown code in an undelimited buffer. If it could be signed, it could not be used for this purpose.

**Comment by schomatis** [comment]
Fixed by https://github.com/multiformats/go-multihash/pull/74.
