### ISSUE TITLE
Can't compile for other Arch, such as mips

### ISSUE THREAD

**Issue by haoglehaogle** [ipfs/go-ipfs#5023]
Hello, 

~/go# go version
go version go1.10.2 linux/amd64

I try to compile this source code for mips, get the following errors information:

/go/src/github.com/ipfs/go-ipfs# make install
bin/check_go_version 1.9
bin/check_go_path /root/go/src/github.com/ipfs/go-ipfs /root/go/src/github.com/ipfs/go-ipfs
go install -ldflags="-X "github.com/ipfs/go-ipfs/repo/config".CurrentCommit=b3faaad13" ./cmd/ipfs
# gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/ipv4
../../../gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/ipv4/icmp.go:34:2: undefined: sysICMPFilter
# gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/ipv6
../../../gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/ipv6/icmp.go:34:2: undefined: sysICMPv6Filter
cmd/ipfs/Rules.mk:37: recipe for target 'cmd/ipfs-install' failed

**Comment by Stebalien** [comment]
It looks like our version of golang.org/x/net doesn't support MIPs. I'm not sure if the current version does either but we can look into that.

**Comment by haoglehaogle** [comment]
hello,
I found new version x/net support mips,  I can replace these source file with new files? or are there any better way to do that? thanks!

**Comment by Kubuxu** [comment]
We are using go modules now. If it still exists on master please reopen or open a new issue.
