### ISSUE TITLE
/api/v0/key/gen does not work

### ISSUE THREAD

**Issue by fcbrandon** [ipfs/go-ipfs#5027]
#### Version information:
```
go-ipfs version: 0.4.15-
Repo version: 6
System version: amd64/windows
Golang version: go1.10.2
```

#### Type:
Bug

#### Description:
I'm attempting to create a key via the HTTP API, but get the following output:
`curl http://localhost:5001/api/v0/key/gen?arg=mykeyname&type=rsa&size=2048
{"Message":"please specify a key type with --type","Code":0,"Type":"error"}`

The command line works just fine. Looks like the API may not be handling the query string options correctly? I tried with only the _arg_ option, but failed with the exact same version.

Repros in v0.4.14 as well.

**Comment by Mr0grog** [comment]
Is it possible you’re having shell escaping issues? e.g. this wouldn’t work in bash:

```sh
$ curl http://localhost:5001/api/v0/key/gen?arg=mykeyname&type=rsa&size=2048
```

…but this would (note the quotes):

```sh
$ curl 'http://localhost:5001/api/v0/key/gen?arg=mykeyname&type=rsa&size=2048'
```

**Comment by fcbrandon** [comment]
Ah, that did indeed fix the problem I was seeing in the shell. Thanks @Mr0grog.

Though I was only trying our curl to troubleshoot a problem using the API from JavaScript, which now appears to be a CORS issue (that is yet unresolved :/ ).

**Comment by Mr0grog** [comment]
@fcbrandon if you’re having CORS issues in the browser, have you checked this note on the js-ipfs-api README? https://github.com/ipfs/js-ipfs-api#cors

For more support-type issues like CORS (“I can’t get this to work” rather than “this seems broken”), we’re trying to handle them over on discuss.ipfs.io

**Comment by fcbrandon** [comment]
👍 Thanks @Mr0grog - That linked did help me get through the CORS problems. And I'll check out the _discuss_ link in the future :)
