### ISSUE TITLE
Node behind NAT unable to pin content from the internet when using `--enable-pubsub-experiment` and badgerds

### ISSUE THREAD

**Issue by postables** [ipfs/go-ipfs#5028]
Can't quite figure out why, but my IPFS node behind my firewall is completely unable to pin any content from the internet, not clear what is causing the problem.

For example, here is my IPFS node at home pinning a small file, taking almost no time to complete (5-10 seconds):
```
solidity@darkmatter:~$ ipfs pin add QmWx6TjMkRVodw3vibMDjYmKzzNtfK6Nu7uTSDezWdtvUg
pinned QmWx6TjMkRVodw3vibMDjYmKzzNtfK6Nu7uTSDezWdtvUg recursively
```

Now, here is my production IPFS node at my datacenter, approximately 2 minutes after running the command:
```
root@nexus:~# ipfs pin add QmWx6TjMkRVodw3vibMDjYmKzzNtfK6Nu7uTSDezWdtvUg


```

As you can see, no updates. Now, I'm not quite sure WHAT is causing the problem, I think it may be due to me being behind a firewall? However I have made sure to forward ports 4001 to my node. Any suggestions on how I can figure out what exactly is causing the issue? I have access to prometheus metrics so let me know if there's anything you want to see.

I have left some files pinning overnight as well, which also haven't worked.

I'm using IPFS Version 0.4.15 with BadgerDS is being used, along with `--enable-pubsub-experiment`

https://i.imgur.com/ts5OJ8v.png

**Comment by postables** [comment]
UPDATE!!!!!!!!!!!!!!!!!!!!!

I have tried disabling `--enable-pubsub-experiment` which has solved the issue!!!!! Any idea how I can go about fixing this pubsub issue? I'm building out a portion of my aplication using pubsub.

**Comment by postables** [comment]
No idea,  but re-enabling pubsub is working. Not sure what the issue was closing as it is no longer of relevance

**Comment by postables** [comment]
Issue is still present :/

**Comment by Stebalien** [comment]
How this relates to pubsub is a bit mystifying. My only guess is that your node is triggering some suspicious activity scan. Try running `ipfs config profile apply server` and then leaving go-ipfs off for ~30m.

**Comment by postables** [comment]
I forgot to close this, but it has since been "resolved". I'm not sure what the issue was, however I think it might've been due to the distro (OpenMediaVault) I was using and some special configuration it had with regards to the software it comes with. I tried spinning up an Ubuntu 16.04.4LTS server on the same lan as the OMV box, and that node had no troubles at all.

**Comment by Stebalien** [comment]
Ah. Got it.

You did close it, I just saw a lot of open/close events and no solution so I figured it might still be an issue. Glad you figured it out!
