### ISSUE TITLE
ERROR ipns-repub:

### ISSUE THREAD

**Issue by sravanthbaratam** [ipfs/go-ipfs#5029]
#### Version information:
Output From `ipfs version --all`
go-ipfs version: 0.4.14-
Repo version: 6
System version: amd64/darwin
Golang version: go1.10

#### Type:
bug

#### Description:
 ipfs daemon
Initializing daemon...
Successfully raised file descriptor limit to 2048.
Swarm listening on /ip4/10.2.129.14/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit/ipfs/QmdVfXinCsJdSvTVLJo1QkvzfJQT5XCnG4GmnN4AG5Ljkf
Swarm announcing /ip4/10.2.129.14/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
11:31:31.136 ERROR ipns-repub: Republisher failed to republish: failed to find any peer in table core.go:518
11:36:31.133 ERROR ipns-repub: Republisher failed to republish: failed to find any peer in table core.go:518
11:41:31.136 ERROR ipns-repub: Republisher failed to republish: failed to find any peer in table core.go:518

**Comment by Stebalien** [comment]
We should reduce the verbosity of that message. That just means that you aren't connected to anyone at the moment (so you obviously can't republish your IPNS records).
