### ISSUE TITLE
Questions about maintaining IPFS datastore persistence throughout hardware failure.

### ISSUE THREAD

**Issue by bonedaddy** [ipfs/go-ipfs#5030]
With content available throughout IPFS, one node suffering hardware failure isn't so much of an issue. The issue I see is when there is one node whose pinning a file. If the hard disks the datastore my IPFS node uses reside on suffer failures, then there exists the potential for that content to be gone forever. This leads to having to resort to typical data availability mechanisms such as backups, RAID, etc...

Currently I'm preparing to setup a RAID5 array for my IPFS datastore, however I have some questions and concerns that I'm not quite sure how to get around. Note that IPFS is a requirement, as I'm attempting to learn what I can and can't do with IPFS, "stress test" if you will. I would love some feedback, tips, etc.. to try things I may have missed out on, or be able to make use of the large amount of storage, and server resources I have at hand.

I am using IPFS Cluster to replicate the data between different peers, however hardware failure is still a concern.

Node configurations:
10K RPM SAS drives
BadgerDS
Server profile
12CPU cores
16GB RAM

1) RAID Arrays

Currently I'm targetting RAID5 arrays. However the main concern with RAID5 is that usable space is reduced down to 3/5 of your raw storage capacity. Now under normal situations this is manageable, however ipfs in the current state (without the experimental **nocopy**  option) duplicates data on disk, another main concern is the actual performance of the IPFS datastore existing on RAID5 arrays, I'm not sure of the implications to this, perhaps someone else has some insight? I imagine there will be a significant performance hit

Another concern is the actual raw storage capacity that will be needed to account for RAID5 storage space consumption, as well as because of IPFS duplication on disk. Since I'm using RAID5, would it be safe to disable the nocopy option?

If RAID5 would prove to be unsuitable, my next choice would be RAID10 to maintain some data availability, while also getting some performance gains over RAID1

2) Data Backups

The piece of the puzzle are databackups, of which there are many ways to accomplish this. My initial idea is to do daily incremental backups of the datastore directory, followed by a weekly full backup. The backup would be to a non IPFS node, and the content would reside as is. Would this be enough to simply, "rsync" that data back to the the IPFS datastore directory when restoring a failed node?

3) Underlying filesystem of the datastore

The disk drives for which the datastore is stored on also needs to be taken into consideration. My initial choice is either BTRFS, or XFS. XFS is desirable as it can be extended on the file. LVM would be used to make management of increasing drive size easier.

4) Any other things?

**Comment by hsanjuan** [comment]
Hi @bonedaddy , I am sorry no one got back on this one. I believe you made a lot of progress on this front so I will close this for now. If you have any follow ups, please post to Discuss and we'll try to help there..
