### ISSUE TITLE
go-net/trace module is gx-vendored, conflicts with golang stdlib

### ISSUE THREAD

**Issue by j0sh** [ipfs/go-ipfs#5034]
#### Version information:

0.4.15-dev from package.json (embedding go-ipfs in an application)

#### Type:

Bug

#### Description:

Currently, gRPC cannot be used with go-ipfs embedded in a golang application. This stems from IPFS vendoring the go-net/trace module, which is used by the badger data store.

The trace module defines a few HTTP routes  within `http.DefaultServeMux` , however this panics if another module tries to handle the same routes with the same mux. IPFS vendors its own copy of the trace module (using stdlib HTTP), which conflicts with the standard trace module used by gRPC.

It would be really good not to vendor the trace module and just use `golang.org/x/net/trace`, although I understand the awkwardness with trace being distributed out-of-tree.

Alternatively (maybe there is already an API for this and I haven't found yet), don't eagerly load the badger datastore if it's not being used. As far as I can tell, it's not used by default, but is still loaded somehow.

As a short-term fix, I solved this by nuking badger-related code from `repo/fsrepo/datastores.go` , but I'd really rather not maintain an out-of-tree patch for this. Converting gRPC to use gx and maintaining that is not really desirable, either.

Example of a panic:
```
vagrant@livepeer-ubuntu1604:~/go/src/github.com/livepeer/go-livepeer/server$ time go test -run RPCTranscoderReq
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x1cbe4a0, 0x112cff9, 0xf, 0x1bd1340, 0x12b3dd8)
        /usr/local/go/src/net/http/server.go:2270 +0x627
net/http.(*ServeMux).HandleFunc(0x1cbe4a0, 0x112cff9, 0xf, 0x12b3dd8)
        /usr/local/go/src/net/http/server.go:2302 +0x55
net/http.HandleFunc(0x112cff9, 0xf, 0x12b3dd8)
        /usr/local/go/src/net/http/server.go:2314 +0x4b
github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/trace.init.0()
        /home/vagrant/go/src/github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/trace/trace.go:110 +0x42
github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net/trace.init()
        <autogenerated>:1 +0x549
github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmdKhi5wUQyV9i3GcTyfUmpfTntWjXu8DcyT9HyNbznYrn/badger.init()
        <autogenerated>:1 +0x78
github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmPAiAmc3qhTFwzWnKpxr6WCXGZ5mqpaQ2YEwSTnwyduHo/go-ds-badger.init()
        <autogenerated>:1 +0x55
github.com/livepeer/go-livepeer/vendor/github.com/ipfs/go-ipfs/repo/fsrepo.init()
        <autogenerated>:1 +0x6e
github.com/livepeer/go-livepeer/ipfs.init()
        <autogenerated>:1 +0x89
github.com/livepeer/go-livepeer/eth.init()
        <autogenerated>:1 +0xaa
github.com/livepeer/go-livepeer/core.init()
        <autogenerated>:1 +0x8c
github.com/livepeer/go-livepeer/server.init()
        <autogenerated>:1 +0x96
main.init()
        <autogenerated>:1 +0x53
exit status 2
FAIL    github.com/livepeer/go-livepeer/server  0.114s
```

**Comment by whyrusleeping** [comment]
Hrm... thats rather annoying. @schomatis could you investigate?

**Comment by schomatis** [comment]
@j0sh Could you provide me more information about your build environment? I'm having trouble building `livepeer` for an Ubuntu 16.04.

**Comment by j0sh** [comment]
@schomatis Ubuntu 16.04 is what we use for our Vagrant dev environment https://github.com/livepeer/devenv

What errors do you see with building https://github.com/livepeer/go-livepeer?

For what it's worth, here is the branch I'm working off of https://github.com/livepeer/go-livepeer/tree/ja/rpc . To demonstrate the issue, run `go test` from the `server` dir. Might have to `go get google.golang.org/grpc` if you don't have it already.

**Comment by schomatis** [comment]
@j0sh I was having problems building `ffmpeg` (related to https://github.com/lutris/ffmpeg-nvenc/issues/18 I think) so I modified the `install_ffmpeg.sh` script to checkout the master branch instead of [`n4.0`](https://github.com/livepeer/go-livepeer/blob/master/install_ffmpeg.sh#L27) which seemed to fix the issue. After that I'm failing to see the `RPCTranscoderReq` test.

```
~/go/src/github.com/livepeer/go-livepeer$ PKG_CONFIG_PATH=~/compiled/lib/pkgconfig go build ./cmd/livepeer/livepeer.go
~/go/src/github.com/livepeer/go-livepeer$ cd server/
~/go/src/github.com/livepeer/go-livepeer/server$ go test -run RPCTranscoderReq
testing: warning: no tests to run
PASS
ok  	github.com/livepeer/go-livepeer/server	0.085s
~/go/src/github.com/livepeer/go-livepeer/server$ go test -v
=== RUN   TestGotRTMPStreamHandler
--- PASS: TestGotRTMPStreamHandler (0.37s)
=== RUN   TestGetHLSMasterPlaylistHandler
--- PASS: TestGetHLSMasterPlaylistHandler (0.00s)
=== RUN   TestParseSegname
--- PASS: TestParseSegname (0.00s)
PASS
ok  	github.com/livepeer/go-livepeer/server	0.465s
```

**Comment by schomatis** [comment]
Oh, I see from your previous comment that you we're not on the master branch. I can now reproduce this. I'll take a look at the Badger code.

**Comment by schomatis** [comment]
Searching for the `panic: http: multiple registrations for /debug/requests` error, this seems to be a common problem when vendored packages (that have a different import path)  import the `golang.org/x/net/trace` package (such as Badger), its `init()` function registers `/debug/requests` without noticing that it has been already registered before (see https://github.com/GoogleCloudPlatform/google-cloud-go/issues/663). I'm not sure how this can be fixed.

Also, a related [comment](https://github.com/golang/go/issues/20478#issuecomment-309087389) caught my attention,

> are you vendoring in libraries? Unfortunately, libraries vendoring their dependencies is not a properly supported feature, we suggest only the main packages should vendor dependencies.

I wouldn't say `gx` does this, but I think that mixing `gx` vendoring with standard vendoring might cause trouble (I'm not sure), I would think that either we vendor everything through `gx` or nothing. Right now there seems to be 3 different version of the `net` package:

```
./vendor/golang.org/x/net
./vendor/github.com/ethereum/go-ethereum/vendor/golang.org/x/net
./vendor/gx/ipfs/QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC/go-net
```

@whyrusleeping WDYT?

**Comment by whyrusleeping** [comment]
Thats... unpleasant. You could hack around this by doing a `gx-go rw --undo go-net` in each package that uses it (this is annoying too). It would be great to have a bit more intelligence here from the go handler registration code...

One thing that would probably work (and is blah because i don't like forcing people to use gx when they have their own vendoring) would be for you to import the trace package youre wanting to use via the gx path.

**Comment by schomatis** [comment]
@j0sh were you able to work around this problem? Is there something that can be done from the go-ipfs side?

**Comment by j0sh** [comment]
We worked around the issue by removing the badger data store from `repo/fsrepo/datastores.go` and vendoring our own copy of go-ipfs : see https://github.com/livepeer/go-ipfs/commit/e6c0cc00e717221f95fb616913ea00e4c4a5b860

I can't say what would be the best way for go-ipfs to work around this particular issue, but ideally it doesn't involve downstream users such as us maintaining their own modifications to the code.

**Comment by schomatis** [comment]
> I can't say what would be the best way for go-ipfs to work around this particular issue, but ideally it doesn't involve downstream users such as us maintaining their own modifications to the code.

Agreed, thanks for the feedback.

**Comment by Kubuxu** [comment]
We are using go modules now.
