### ISSUE TITLE
Can't build Dockerfile - " /bin/sh: 1: gx: Exec Format Error"

### ISSUE THREAD

**Issue by NickJLange** [ipfs/go-ipfs#5038]
#### Description:

docker build .
/bin/sh: 1: gx: Exec format error
make: *** [gx-deps] Error 2

I have been trying to figure out what is triggering this in gx.mk to no avail - the files pulled down in bin/gx run from the CLI (they also do not appear to be a shell file).

I'm open to ideas...

# Go Environment
Nicks-MacBook-Pro:go-ipfs njl$ go version
go version go1.10.2 darwin/amd64

#Envirionment Docker
:go-ipfs njl$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

**Comment by whyrusleeping** [comment]
very strange. @Kubuxu @lgierth any ideas?

**Comment by NickJLange** [comment]
Could it be the go-compiled objects are for linux running on osx ?

**Comment by NickJLange** [comment]
Root Cause: This was because OSX Docker needs gx and gx-go to be a linux binary. 

I ended up building both / copying them in place to get past this issue.

Leaving me with the next set of errors...
`o build -i -ldflags="-X "github.com/ipfs/go-ipfs/repo/config".CurrentCommit=2ba7179" -o "cmd/ipfs/ipfs" "github.com/ipfs/go-ipfs/cmd/ipfs"
Putting child 0x5643dc850f00 (cmd/ipfs/ipfs) PID 1034 on the chain.
Live child 0x5643dc850f00 (cmd/ipfs/ipfs) PID 1034 
fuse/mount/fuse.go:12:2: cannot find package "bazil.org/fuse" in any of:
	/go/src/github.com/ipfs/go-ipfs/vendor/bazil.org/fuse (vendor tree)
	/usr/local/go/src/bazil.org/fuse (from $GOROOT)
	/go/src/bazil.org/fuse (from $GOPATH)
fuse/mount/fuse.go:13:2: cannot find package "bazil.org/fuse/fs" in any of:
	/go/src/github.com/ipfs/go-ipfs/vendor/bazil.org/fuse/fs (vendor tree)
	/usr/local/go/src/bazil.org/fuse/fs (from $GOROOT)
	/go/src/bazil.org/fuse/fs (from $GOPATH)
cmd/ipfs/main.go:28:2: cannot find package "github.com/Kubuxu/go-os-helper" in any of:
	/go/src/github.com/ipfs/go-ipfs/vendor/github.com/Kubuxu/go-os-helper (vendor tree)
	/usr/local/go/src/github.com/Kubuxu/go-os-helper (from $GOROOT)
	/go/src/github.com/Kubuxu/go-os-helper (from $GOPATH)
unixfs/hamt/hamt.go:32:2: cannot find package "github.com/Stebalien/go-bitfield" in any of:
	/go/src/github.com/ipfs/go-ipfs/vendor/github.com/Stebalien/go-bitfield (vendor tree)
	/usr/local/go/src/github.com/Stebalien/go-bitfield (from $GOROOT)
	/go/src/github.com/Stebalien/go-bitfield (from $GOPATH)
namesys/proquint.go:8:2: cannot find package "github.com/bren2010/proquint" in any of:
	/go/src/github.com/ipfs/go-ipfs/vendor/github.com/bren2010/proquint (vendor tree)
	/usr/local/go/src/github.com/bren2010/proquint (from $GOROOT)
	/go/src/github.com/bren2010/proquint (from $GOPATH)
exchange/reprovide/reprovide.go:10:2: cannot find package "github.com/cenkalti/backoff" in any of:
	/go/src/github.com/ipfs/go-ipfs/vendor/github.com/cenkalti/backoff (vendor tree)
	/usr/local/go/src/github.com/cenkalti/backoff (from $GOROOT)
	/go/src/github.com/cenkalti/backoff (from $GOPATH)
`

**Comment by whyrusleeping** [comment]
@NickJLange thats really strange. Does `go env GOOS` on a docker image on osx return `darwin` or `linux` ?

**Comment by lanzafame** [comment]
So I had been getting the following error attempting to build the ipfs-cluster container on macOS:
```
deptools/gx_v0.13.0 install --global
deptools/gx_v0.13.0: 1: deptools/gx_v0.13.0: ����: not found
deptools/gx_v0.13.0: 2: deptools/gx_v0.13.0: Syntax error: word unexpected (expecting ")")
Makefile:63: recipe for target 'deps' failed
make: *** [deps] Error 2
```
And going off what you said @NickJLange, I replaced the macOS gx/gx-go binaries and the build is now working 👍

**Comment by NickJLange** [comment]
Regarding the missing dependencies - I've pulled in the latest repo, still failing to build in docker. Where does gx install get it's file list from ? (sadly osx strace / dtruss is nerfed - I can't see the opening stat to figure).

@lanzafame  - Did you have to do any manual dependency management to get docker to build the container?

**Comment by lanzafame** [comment]
@NickJLange nope, I just changed the Makefile to download the linux gx binaries. In saying this, I haven't had any issues building the ipfs container, only the ipfs-cluster container.

**Comment by lgierth** [comment]
I wonder where our build system gets the idea that it's `darwin` while in the VM-backed container?

**Comment by rob-deutsch** [comment]
Hey - I just had the same problem - and I realised what was happening.

The problem is that your local (MacOS) copy of the go-ipfs source code has some cached MacOS binaries in the bin directory. These binaries didn't come with the source code, as can be seen in `go-ipfs/.gitignore`:

````
bin/gx
bin/gx*
bin/tmp
````

The problem is that Docker is uploading these binaries to your Linux server, and then your Linux server can't actually run them.

If you delete all the binaries in the bin/ folder and try docker again it will work just fine.

Unfortunately I don't know the best way to fix this problem. I suspect that adding these files to .dockerignore too would stop the error from occurring, but I don't know if this will impact performance.
