### ISSUE TITLE
Add README for the `docs` folder.

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#5049]
And maybe also include the table of contents in the repo README to make them more visible and accessible to the user.

**Comment by whyrusleeping** [comment]
Sounds good to me!

**Comment by Mr0grog** [comment]
I tried to effectively do this in ipfs/docs#68 here: https://ipfs.io/ipfs/QmVUdHfpo9hyC8wXmgd2frRrsp83iRvuL8HWyp1LPzjsPq/reference/go/overview/

It doesn’t cover a few files (like `AUTHORS` and `generate-authors.sh`) that didn’t seem to fit in the docs site. I’m struggling a little with thinking of a good way to have a README here while also exposing a useful list of docs in the docs site and not making extra work for people (the [examples directory in js-ipfs](https://github.com/ipfs/js-ipfs/tree/master/examples) poses a similar issue).

**Comment by Mr0grog** [comment]
OK, the more I think about this, the more I feel like we should just put a copy of that page as the README in the docs folder.

- Linking from here to the docs site and then back to the `docs` folder seems like some unnecessary jumping around.

- We’ll probably move some docs move from here to the docs site, at which point what’s relevant for pages in the docs site to cover and what’s relevant for a README here to cover will diverge.

- I think I’m more worried than is really reasonable about the duplication :)

I’ll go ahead and make a PR for this now.
