### ISSUE TITLE
Add a context to cmds.Request 

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#505]
Currently (unless I'm missing something) we have no way of allowing the user to cancel a command. If we add in a context to the request handler it will allow us to have a mechanism to cancel commands with.

**Comment by jbenet** [comment]
@whyrusleeping yep, the context should be cancelled if/when the request's connection terminates.

**Comment by jbenet** [comment]
it's gonna get confusing cause the request already has a context (it's something else atm).

**Comment by jbenet** [comment]
related: #242

**Comment by jbenet** [comment]
this is done. just needs to be wired to more commands (`ipfs refs` does it, albeit in avery ugly way (see that writer trick)

**Comment by rht** [comment]
> (ipfs refs does it, albeit in avery ugly way (see that writer trick)

Does this refer to https://github.com/ipfs/go-ipfs/blob/master/core/commands/refs.go#L105?
Which commands don't have request context?

**Comment by jbenet** [comment]
@rht not sure, we should go through all of them and make sure all the ctx related thing derive from `req.Context()`

**Comment by whyrusleeping** [comment]
yeah, i recently refactored and made the `req.Context()` more reliable, and also made it respect the global timeout flag. We should go through and make sure that it is used correctly all over the codebase.
