### ISSUE TITLE
the issue IPFs gateway compatibility on phone

### ISSUE THREAD

**Issue by lemonwin798** [ipfs/go-ipfs#5078]
#### Version information:
0.4.15

#### Type:
Bug

#### Description:
I compiled a IPFs version of the phone, and Gateway has been established in the localhost.
 
Then using httpclient loop to get file data
 
It is often the case that the connection is broken.,
 
After checking, it was found that the binary stream from gateway_handler was http.ServeContent, causing the upper client link to break.
 
I saw it in fs.io

> 

               ctype = mime.TypeByExtension(filepath.Ext(name))
		if ctype == "" {
			// read a chunk to decide between utf-8 text and binary
			var buf [sniffLen]byte
			n, _ := io.ReadFull(content, buf[:])
			ctype = DetectContentType(buf[:n])
			_, err := content.Seek(0, io.SeekStart) // rewind to output whole file
			if err != nil {
				Error(w, "seeker can't seek", StatusInternalServerError)
				return
			}
		}
           

Because no found mimetype, so it needs to be DetectcontentType(), This approach will lead to httpclient break.
But it didn't appear on PC， It's only occasional on the phone
So I want to ask: Is this the problem of golang or is the interface of IPFS call incorrect?

**Comment by Stebalien** [comment]
Are you seeing any error messages? What made you believe this was related to to the call to DetectContentType?

**Comment by Stebalien** [comment]
I'm really skeptical this is an issue with go-ipfs and I'm having trouble understanding exactly *what* behavior you're seeing.

If you can give us a way to reproduce this, we can re-open the bug and try to fix this. As-is, there's not much we can do about this (I'm not even sure what's going wrong).
