### ISSUE TITLE
sharness tests: `ipfs object`

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#508]
```
    ipfs object - Interact with ipfs objects

    ipfs object get <key>             - Get the DAG node named by <key>
    ipfs object put <data> <encoding> - Stores input, outputs its key
    ipfs object data <key>            - Outputs raw bytes in an object
    ipfs object links <key>           - Outputs links pointed to by object
    ipfs object stat <key>            - Outputs statistics of object
```

**Comment by cryptix** [comment]
[t0051-object.sh](https://github.com/jbenet/go-ipfs/blob/master/test/sharness/t0051-object.sh) has most of these. Maybe I missed a corner case with the encodings.

- [x] `object get`
- [x] `object stat`
- [x] `object put` (protobuf and json)
- [ ] `object data`
- [ ] `object links`

**Comment by jbenet** [comment]
we need to also check that we test the flags + arguments. maybe we should add that to the list

**Comment by whyrusleeping** [comment]
we test these and stuff and things
