### ISSUE TITLE
`dht: Error correcting DHT entry: EOF asm_amd64.s:2361`

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#5099]
While working on an UnixFS PR (https://github.com/ipfs/go-ipfs/pull/5098) I stumbled upon some (what I'm assuming are) unrelated DHT spurious errors on the Travis job:

```
15:54:17.294 ERROR        dht: Error correcting DHT entry: EOF asm_amd64.s:2361
15:54:17.295 ERROR        dht: Error correcting DHT entry: EOF asm_amd64.s:2361
15:54:17.295 ERROR        dht: Error correcting DHT entry: EOF asm_amd64.s:2361
15:54:17.295 ERROR        dht: Error correcting DHT entry: EOF asm_amd64.s:2361
15:54:17.295 ERROR        dht: Error correcting DHT entry: EOF asm_amd64.s:2361
15:54:17.295 ERROR        dht: Error correcting DHT entry: EOF asm_amd64.s:2361
15:54:17.295 ERROR        dht: Error correcting DHT entry: EOF asm_amd64.s:2361
15:54:17.295 ERROR        dht: Error correcting DHT entry: EOF asm_amd64.s:2361
15:54:17.317 ERROR        dht: Error correcting DHT entry: EOF asm_amd64.s:2361
--- FAIL: TestRepublish (2.63s)
	repub_test.go:69: could not resolve name
```

https://travis-ci.org/ipfs/go-ipfs/jobs/389786949#L824
(Line 824, the anchor might not be working.)

**Comment by Stebalien** [comment]
So, the errors and the failure are independent.

The error is just a noisy log line. Fix: https://github.com/libp2p/go-libp2p-kad-dht/pull/166/files#diff-01edc34c001f7e76bbe6d5023612f005L179

The test failure looks like a timing issue. Given that the test fails after 2 seconds and the record expires after 1 second, I'm guessing the record has simply expired.
