### ISSUE TITLE
jenkins config from repo?

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#510]
I think we should be able to configure jenkins from the repo (like travis). it's painful to have to go to a web service when something changes in the repo. Particularly problematic as things are in PR, as it will necessarily break. 

cc @briantigerchow

**Comment by briantigerchow** [comment]
You're completely right about this. I initially leaned toward on-Jenkins configuration to iterate more quickly and get it going. 

Ideally, we'd want all tests to be executed using `make` tasks, yeah? If so, want 'em in the top-level Makefile (cautious of co-opting/polluting it).


For full transparency...
Alternatively, there's https://github.com/groupon/DotCi. That plugin/suite makes Jenkins work a lot like Travis (declarative yaml). Dotci is opinionated such that we'd have to perform some non-trivial infrastructure reconfiguration. It is also incompatible with Slave swarms, so slave authentication would need to be handled differently. When I evaluated these trade-offs a few months ago, I the sheer number of concessions sufficiently unattractive. Just want to make all parties are aware the option exists.

**Comment by jbenet** [comment]
https://github.com/groupon/DotCi seems like the right _idea_ -- a lot of the features they boast sound good -- but sounds like it's not going to work for us. Your call -- I don't have good knowledge on all the tradeoffs involved at all.

**Comment by whyrusleeping** [comment]
we use circleCI and travis and appeyor now, which are all configurable through config files in this repo
