### ISSUE TITLE
recursive boolean on API doesn't get true

### ISSUE THREAD

**Issue by FraYoshi** [ipfs/go-ipfs#5101]
#### Version information:
go-ipfs version: 0.4.15-
Repo version: 6
System version: amd64/linux
Golang version: go1.10.2

curl 7.60.0 (x86_64-pc-linux-gnu) libcurl/7.60.0 OpenSSL/1.1.0h zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) nghttp2/1.31.1
Release-Date: 2018-05-16

#### Type:
Bug

#### Description:
Trying to recursively add a folder but the `recursive=true` command doesn't actually recurse...

#### My command:
`curl -F file=@folder-with-files "127.0.0.1:5001/api/v0/add?recursive=true"`

**Comment by whyrusleeping** [comment]
I'm not actually sure how to add a folder of items via curl... cc @Kubuxu @magik6k or @kevina maybe?

**Comment by Stebalien** [comment]
Recursive won't work here, you have to specify each and every file on the command line along with a `filename=` header. That is:

```
> curl -F 'file=@$filename; filename=$filename' ...
```

Repeating that `-F` flag for each file in the directory.
