### ISSUE TITLE
ipfs swarm connect /ipfs/QmId fails

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#5102]
When we don't already know a peer's address, `ipfs swarm connect /ipfs/QmId` always fails. This is because we:

1. Record "" as the peer's address (https://github.com/ipfs/go-ipfs-addr/issues/4)
2. Never search for addresses if we *think* we know a peer's address https://github.com/libp2p/go-libp2p/issues/351.

**Comment by whyrusleeping** [comment]
good catch
