### ISSUE TITLE
virustotal

### ISSUE THREAD

**Issue by KonoromiHimaries** [ipfs/go-ipfs#5103]
https://www.virustotal.com/#/url/2817c788b4337c4cc8107639189f4f7313fb168ef3efae6deebf0333a0cff617/detection

**Comment by Stebalien** [comment]
We run a public IPFS gateway on `https://ipfs.io` so this isn't unexpected.

Basically, it means that someone, somewhere added some program that some antivirus *thinks* is a virus to IPFS and then posted a link to `https://ipfs.io/ipfs/HASH_OF_PROGRAM` somewhere on the web. When we discover such links, we block them at our gateway (we can't remove these files from IPFS, but we can stop serving them). However, we can't catch everything.
