### ISSUE TITLE
Filestore possiblly not hooked up right

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#5121]
When the filestore is used the `CachedBlockstore` is not according to this code (in [builder.go](https://github.com/ipfs/go-ipfs/blob/d643c045d22e15ae2735fc70fd69c80d48f70d93/core/builder.go)):

```go
	bs := bstore.NewBlockstore(rds)
	...

	cbs, err := bstore.CachedBlockstore(ctx, bs, opts)
	...

	n.BaseBlocks = cbs
	n.GCLocker = bstore.NewGCLocker()
	n.Blockstore = bstore.NewGCBlockstore(cbs, n.GCLocker)

	if conf.Experimental.FilestoreEnabled {
		...
		n.Filestore = filestore.NewFilestore(bs, n.Repo.FileManager())
		n.Blockstore = bstore.NewGCBlockstore(n.Filestore, n.GCLocker)
		...
	}
```
It looks like it was always this way based on 2884c8434350538339bef4e9e2e4da8657548e3e

@whyrusleeping Was this intentional or an oversight.

**Comment by whyrusleeping** [comment]
Oh, that looks like an oversight on my part.

**Comment by kevina** [comment]
So is the fix to change
```
n.Filestore = filestore.NewFilestore(bs, n.Repo.FileManager())
```
to
```
n.Filestore = filestore.NewFilestore(cbs, n.Repo.FileManager())
```
that is `s/bs/cbs/`?

If so I think I will just fix it in https://github.com/ipfs/go-ipfs/pull/5117.  I actually noticed this bug as enabling the filestore broke id-hashes.

**Comment by kevina** [comment]
@whyrusleeping see #5122.
