### ISSUE TITLE
`ipfs add -r directory` doesn't upload files and directories with dot prefix

### ISSUE THREAD

**Issue by eykrehbein** [ipfs/go-ipfs#5126]
When I try to upload a directory including a `.config` file and a `.git` directory, IPFS uploads everything but those files and folders which are prefixed by a dot. I cannot imagine that this is a wanted feature, so I decided to open this issue.

**Comment by Stebalien** [comment]
You can pass `-H` to include hidden files. I also can't imagine why we exclude hidden files by default.

**Comment by Stebalien** [comment]
Unfortunately, fixing this would break too much. We'll have to reconsider in the next iteration of the API.

**Comment by Stebalien** [comment]
(closing as we can't fix this right now)

**Comment by iuriguilherme** [comment]
I vote against adding `.hidden` files by default as it is historical behavior, I rely on this behavior on automatic scripts which publish sites to IPNS. They shall not make it available via IPFS gateways stuff like **.htaccess** (bad) or **.env** (VERY bad).

I would happily change all my scripts but if such a change happen, there **SHOULD** be warnings everywhere so users don't make it "forever" available unwanted files.
