### ISSUE TITLE
ipfs adds windows hidden files when daemon is running.

### ISSUE THREAD

**Issue by ivan386** [ipfs/go-ipfs#5127]
#### Version information:
>ipfs version --all
go-ipfs version: 0.4.15-
Repo version: 6
System version: amd64/windows
Golang version: go1.10.2

#### Description:
ipfs adds windows hidden files(set attribute hidden) when daemon is running. 

>ipfs add -r folder
 0 B / ? [-----------------------------------------------------------------------------------
added QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH folder/hidden file.txt
added QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn folder/hidden folder
added QmSV8Kkch6P8yoZVkFCd3zutRNoRmSvkt2EPF4hvqBvvY4 folder

**Comment by hsanjuan** [comment]
Changes are this does not happen anymore, since I think the ability to add hidden files was removed altogether or refactored.. and we released a few versions.

Please re-check and re-open if still happens.

**Comment by Stebalien** [comment]
I can confirm that this has been fixed.
