### ISSUE TITLE
docs/config.md: Routing option within discovery

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#5128]
`Routing` config option appears listed under `Discovery` in `docs/config.md`. this is a bug. `Routing` should be its own heading, with `Type` = `dhtclient`, etc. 

(eg https://github.com/ipfs/go-ipfs/blob/0cb22ccf359e05fb5b55a9bf2f9c515bf7d4dba7/repo/config/profile.go#L153 )

**Comment by magik6k** [comment]
Fixed in https://github.com/ipfs/go-ipfs/pull/6309
