### ISSUE TITLE
I seem to keep getting this issue,

### ISSUE THREAD

**Issue by LWFlouisa** [ipfs/go-ipfs#5132]
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use

Is there any way to fix this problem?

As an aside, IPFS doesn't seem to be working on other sites either, like DTube.  can't even use the gateway.

**Comment by Stebalien** [comment]
You have something else listening on that port. Are you running two IPFS daemons?

**Comment by LWFlouisa** [comment]
I might, I can check. I know how I had the plugin on firefox as well. Would that conflict?

**Comment by Stebalien** [comment]
> I might, I can check. I know how I had the plugin on firefox as well. Would that conflict?

Not unless it starts an IPFS node (it shouldn't).
