### ISSUE TITLE
use local .go-ipfs?

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#515]
not sure this is a good idea:

if there is a `.go-ipfs` directory in the current dir (or ancestors in the tree, like for git), should `ipfs` use that dir instead of defaulting to `~/.go-ipfs`? 

RFC

**Comment by diasdavid** [comment]
I like this idea, but it should be `.ipfs` to keep it consistent with the default repo value

**Comment by whyrusleeping** [comment]
needs more discussion before we think about implementing it
