### ISSUE TITLE
make install failed

### ISSUE THREAD

**Issue by W-B-S** [ipfs/go-ipfs#5152]
plugin/loader/preload.sh > plugin/loader/preload.go     QmRAPFFaF7nrezCZQaLihyp2qbAXqSJU5WpvSpwroMv1Xt 5ms[1B
-u系统找不到指定的文件。
go fmt plugin/loader/preload.go >/dev/null
plugin\loader\preload.go:13:16: expected operand, found ']'
plugin\loader\preload.go:15:3: expected ']', found 'EOF'
exit status 2
make: *** [plugin/loader/Rules.mk:6: plugin/loader/preload.go] Error 1

**Comment by magik6k** [comment]
Can you send the contents of `plugin/loader/preload.go` and `go env`?

**Comment by W-B-S** [comment]
I have reload the source code from github and rebuild ,It's ok now ,thanks
