### ISSUE TITLE
Ipfs private network, file access issues

### ISSUE THREAD

**Issue by zhjgit** [ipfs/go-ipfs#5154]
In ipfs private network, if an ipfs node uploads a file and the node disconnects, how does the other node connected to it access the file he uploaded previously?

**Comment by leerspace** [comment]
If there weren't any nodes that accessed the file from the source node while it was up, then other nodes won't be able to access the file after it's down. You'd need to use something like ipfs-cluster if you wanted your nodes to automatically replicate content across them.

**Comment by zhjgit** [comment]
Thank you. I have solved this problem with ipfs-cluster.
