### ISSUE TITLE
IPFS API not responsive if the repository size has a lot of objects

### ISSUE THREAD

**Issue by koalalorenzo** [ipfs/go-ipfs#5163]
#### Version information:
Siderus Orion `0.6.1`
go-ipfs `0.4.15`

#### Type:
Bug

#### Description:
Original thread: https://github.com/Siderus/Orion/issues/124

In the original 3d the issue is happening when we add a new file or when we simply open a new window. These two windows are using:

- PIN list
- Add a file

As we am using `js-ipfs-api`, we have noticed that the issue is caused by `go-ipfs`.
Probably this is a duplicate but I was not able to find a clone of this.

**Comment by postables** [comment]
have you tried using badgerds for your data store?

**Comment by koalalorenzo** [comment]
That could be a solution for new repositories that we set up in the client.
In the original issue the owner of the repo decided to not use Siderus Orion repository but to use its own (which is its own `go-ipfs` instance running in background). We can suggest that to @NatoBoram

**Comment by lgierth** [comment]
Migrating to badger datastore is great but not what this issue is about. Could you tell us more about the repo? OS, size, nature of the content (i.e. tons of small objects, or large objects), how exactly is the API not responsive, is all of it unresponsive?

**Comment by NatoBoram** [comment]
@lgierth The first piece of information I can give you is the issue https://github.com/Siderus/Orion/issues/124, which contains a few screenshots of the API in action.

Then, eh... I added *multiple* [UIbuntu 18.04 ISO](https://www.reddit.com/r/Ubuntu/comments/8f8v1n/download_ubuntu_1804_lts_via_ipfs/)s flavours, and *all* Android P Developer Preview ZIPs, and I generally use IPFS whenever I have to share something. So... "there's stuff in there". I also use IPFS when I want to share images on Internet and I host them on my private node and sometimes mirror them on my [public node](http://natoboram.mynetgear.com:8080/ipfs/).

I'm using Windows 10 with Go-IPFS running in a scheduled task on login.

With that, I think you might have a good idea of the nature of the node's content.

**Comment by Stebalien** [comment]
This is https://github.com/ipfs/go-ipfs/issues/5221. Closing as a duplicate.
