### ISSUE TITLE
MFS root shouldn't need to put the node in the DAG.

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#5171]
If you look at the `closeChild` implementation in the mfs Root, you'll see that it adds the root object's node to the DAG:

https://github.com/ipfs/go-ipfs/blob/336520d4ef0d06ac28b6e6c189c3d4c099b1ba38/mfs/system.go#L162-L172

However, the child *should already have done this*.

**Comment by schomatis** [comment]
Closing in favor of https://github.com/ipfs/go-mfs/issues/34.
