### ISSUE TITLE
ipfs How to view the contents of document files such as Word, Excel, etc.

### ISSUE THREAD

**Issue by zhjgit** [ipfs/go-ipfs#5174]
I know to view plain text ，ipfs cat QmZcJpv8KUxiE2FVLH0Dn7LHh2MCNQexJD2SJTppBxZXmh,
but , ipfs How to view the contents of document files such as Word, Excel, etc.

**Comment by Stebalien** [comment]
In an attempt to keep this issue tracker manageable, we've moved questions and discussions to https://discuss.ipfs.io.

(yes, we sometimes answer questions here but we try to avoid that)
