### ISSUE TITLE
ipfs How to know the type and name of the file by hash code

### ISSUE THREAD

**Issue by zhjgit** [ipfs/go-ipfs#5175]
ipfs How to know the type and name of the file by hash code?

When I upload a picture or an excel document, I return a hash. How do other ipfs nodes know the type of the uploaded file, and then download and view it?

**Comment by Stebalien** [comment]
In an attempt to keep this issue tracker manageable, we've moved questions and discussions to https://discuss.ipfs.io.

(yes, we sometimes answer questions here but we try to avoid that)
