### ISSUE TITLE
use a random port for swarm when ipfs init

### ISSUE THREAD

**Issue by thomas92911** [ipfs/go-ipfs#5176]
#### Version information:
0.4.15

#### Type:
Feature

#### Description:
When Ipfs init, please use a random port number for swarm, do not use 4001 in a fixed way, 
in China this will cause the government to Ban off this port.

thomas92911
from China.

**Comment by Stebalien** [comment]
So, really, the main problem here is mostly documentation. We'd have to tell users which ports to open in their firewall. However, we *should* have a config profile at least.

**Comment by whyrusleeping** [comment]
Yeah, I think having an option to do `ipfs init --profile=randomports` might be good.

**Comment by thomas92911** [comment]
If everyone else uses 4001, the network service provider can still control the network link, 
so it is better to use the random port by default, 

use  `ipfs init --swarmport=4001`  to specify

**Comment by whyrusleeping** [comment]
> If everyone else uses 4001, the network service provider can still control the network link,
so it is better to use the random port by default,

Ah, right. the MITM can see both ends... I do like the random ports idea too. Aside from the documentation and firewall problems @Stebalien mentioned, there is also the problem of actually selecting a port. Some people get offended if you use a port that they are using for something else (even if that something else isnt using it all the time), so we should avoid using common ports, and also any port in use at the time.

To make firewall port opening stuff a bit easier, we could have a command that walks the user through how to set things up, and also give it the ability to verify connectivity.

**Comment by Stebalien** [comment]
> Ah, right. the MITM can see both ends...

You don't even have to MITM. You can just crawl the DHT, probe any nodes you find, and then shut them down. IIRC, this kind of technique is already in-use by some countries (mostly to combat things like TOR and I2P).

**Comment by tarekbadrshalaan** [comment]
Hi @Stebalien , @whyrusleeping 

as you said @Stebalien 
> Also note: As it stands, it's pretty easy to identify and enumerate all IPFS nodes. This means that hostile networks can repeatedly list all nodes in the network, find the port IPFS is running on, and block it (or block the entire computer).

Is this issue still we need to work on ??

if yes, what's the command you like to use: 
`ipfs init --profile=randomports` or `ipfs init --swarmport=4001`

**Comment by Stebalien** [comment]
Probably the former. As we add more transports, we'll need to listen on *multiple* ports so the second option won't work so well.

**Comment by tarekbadrshalaan** [comment]
Hi @Stebalien Thanks for your reply.
I will start work on `ipfs init --profile=randomports` and back to you.

**Comment by Stebalien** [comment]
This has now been merged but needs a test.

**Comment by Stebalien** [comment]
(merged in go-ipfs-config, still needs to be bubbled)

**Comment by tarekbadrshalaan** [comment]
Thanks @Stebalien for your response , I will create the tests ASAP.

**Comment by tarekbadrshalaan** [comment]
Thanks @Stebalien for your response , I will create the tests ASAP.

**Comment by thomas92911** [comment]
`ipfs swarm peers` still has this problem

**Comment by magik6k** [comment]
The `randomports` profile is now in go-ipfs master.
