### ISSUE TITLE
Running "ipfs repo gc" crashes the daemon.

### ISSUE THREAD

**Issue by Kycklingar** [ipfs/go-ipfs#5177]
#### Version information:
go-ipfs version: 0.4.15-
Repo version: 6
System version: amd64/windows
Golang version: go1.10.2

#### Type:
Bug

#### Description:
Running "ipfs repo gc" crashes the daemon.
I'm using badgerds and have the filestore enabled.

Repo stats:
```
NumObjects: 10162874
RepoSize:   469320810480
StorageMax: 10000000000
RepoPath:   G:\badger
Version:    fs-repo@6
```

Output from the gc terminal:
```
...
removed QmSuRe1...
removed QmSuReT...
removed QmSuRed...
Error: read tcp 127.0.0.1:51235->127.0.0.1:5001: wsarecv: An existing connection was forcibly closed by the remote host.
```

Output from the daemon terminal:
https://ipfs.io/ipfs/zb2rhWkXJndDWB1gW3K8MC8zrVcGFt4kaWcRkQGNiyykZyruX

**Comment by schomatis** [comment]
Hey @Kycklingar, thank you for reporting this! At first sight it seems like an out of memory error, the `VirtualAlloc` reports an [`ERROR_COMMITMENT_LIMIT`](https://msdn.microsoft.com/en-us/library/cc231199.aspx) (I'm cc'ing @djdv just in case there's more to that error that what the MSDN reports). What it's noticeable is that it is happening during a GC operation, which in Badger entails writing to disk and performing several operations to check if a key has been marked as deleted, so it's not impossible, but I would think it's unlikely. Let me dig deeper and see if there's anything more.

Could you provide more information about you're working environment?

**Comment by Kycklingar** [comment]
@schomatis  I have 24 GB of memory installed and the ipfs daemon uses 8 GB on idle and usually jumps to around 16GB when adding/pinning.

**Comment by schomatis** [comment]
So, looking closer at the stack trace I don't see anything suspicious that would make me think this is anything other than a OOM error, maybe @magik6k could provide some more insight here, he has more experience with this part of the code than me, it does catch my attention that the memory doubles while adding, but that may be normal.

**Comment by magik6k** [comment]
Would be great if you could provide a few heap trace dumps while the GC is running,  you can do this with

```
curl localhost:5001/debug/pprof/heap > ipfs.heap
```

**Comment by Kycklingar** [comment]
@magik6k Here you go: https://ipfs.io/ipfs/zdj7WcbaM64YJXFRnDwAxsiP2xnvGk3z3PN9GokAA5AGDaJBC
I ran the GC for about 2 hours before I cancelled it because the computer became unresponsive.

**Comment by Stebalien** [comment]
Yep. Looks like badger eating ram like nothing else:

```
Showing nodes accounting for 7.12GB, 98.70% of 7.21GB total
Dropped 199 nodes (cum <= 0.04GB)
Showing top 10 nodes out of 46
      flat  flat%   sum%        cum   cum%
    5.67GB 78.66% 78.66%     5.67GB 78.66%  gx/ipfs/QmdKhi5wUQyV9i3GcTyfUmpfTntWjXu8DcyT9HyNbznYrn/badger/table.(*Table).Lock
    0.87GB 12.00% 90.66%     0.87GB 12.00%  gx/ipfs/QmcZfnkapfECQGcLZaf9B79NRg7cRa9EnZh4LSbkCzwNvY/go-cid.init
    0.24GB  3.38% 94.04%     0.24GB  3.38%  gx/ipfs/QmdKhi5wUQyV9i3GcTyfUmpfTntWjXu8DcyT9HyNbznYrn/badger/skl.(*Skiplist).Put
    0.16GB  2.22% 96.25%     0.16GB  2.22%  gx/ipfs/QmdKhi5wUQyV9i3GcTyfUmpfTntWjXu8DcyT9HyNbznYrn/badger.(*Txn).SetWithTTL
    0.12GB  1.62% 97.88%     0.12GB  1.62%  gx/ipfs/QmXqKGu7QzfRzFC4yd5aL9sThYx22vY163VGwmxfp5qGHk/bbloom.(*Bloom).AddIfNotHasTS
    0.06GB  0.82% 98.70%     0.06GB  0.82%  gx/ipfs/QmdKhi5wUQyV9i3GcTyfUmpfTntWjXu8DcyT9HyNbznYrn/badger/skl.(*Arena).putVal
         0     0% 98.70%     0.11GB  1.47%  github.com/ipfs/go-ipfs/core.setupNode
         0     0% 98.70%     0.16GB  2.22%  github.com/ipfs/go-ipfs/filestore.(*FileManager).readDataObj
         0     0% 98.70%     0.16GB  2.17%  github.com/ipfs/go-ipfs/filestore.(*Filestore).HashOnRead
         0     0% 98.70%     0.73GB 10.10%  github.com/ipfs/go-ipfs/merkledag.EnumerateChildrenAsync
```

```
ROUTINE ======================== gx/ipfs/QmdKhi5wUQyV9i3GcTyfUmpfTntWjXu8DcyT9HyNbznYrn/badger/table.(*Table).readIndex in /home/steb/projects/go/src/gx/ipfs/QmdKhi5wUQyV9i3GcTyfUmpfTntWjXu8DcyT9HyNbznYrn/badger/table/table.go
         0     5.82GB (flat, cum) 80.64% of Total
         .          .    191:	res, err := t.read(off, sz)
         .          .    192:	y.Check(err)
         .          .    193:	return res
         .          .    194:}
         .          .    195:
         .   146.38MB    196:func (t *Table) readIndex() error {
         .          .    197:	readPos := t.tableSize
         .          .    198:
         .          .    199:	// Read bloom filter.
         .          .    200:	readPos -= 4
         .          .    201:	buf := t.readNoFail(readPos, 4)
         .          .    202:	bloomLen := int(binary.BigEndian.Uint32(buf))
         .          .    203:	readPos -= bloomLen
         .          .    204:	data := t.readNoFail(readPos, bloomLen)
         .          .    205:	t.bf = *bbloom.JSONUnmarshal(data)
         .          .    206:
         .          .    207:	readPos -= 4
         .          .    208:	buf = t.readNoFail(readPos, 4)
         .          .    209:	restartsLen := int(binary.BigEndian.Uint32(buf))
         .          .    210:
         .          .    211:	readPos -= 4 * restartsLen
         .          .    212:	buf = t.readNoFail(readPos, 4*restartsLen)
         .          .    213:
         .          .    214:	offsets := make([]int, restartsLen)
         .          .    215:	for i := 0; i < restartsLen; i++ {
         .          .    216:		offsets[i] = int(binary.BigEndian.Uint32(buf[:4]))
         .     5.67GB    217:		buf = buf[4:]
         .          .    218:	}
         .          .    219:
         .          .    220:	// The last offset stores the end of the last block.
         .          .    221:	for i := 0; i < len(offsets); i++ {
         .          .    222:		var o int
```

**Comment by schomatis** [comment]
@Stebalien Help me understand the memory profile (I'm only familiar with the cumulative CPU one), how is the memory consumption grouped? By file, structure, function call? The `readIndex` function seems to be taking 146 MB but the internal (local) `buf` variable can take more than that (5 GB in this case)?

For context, `readIndex()` reads the index of an SST table block that holds a set of 100 (`restartsLen`) keys that are grouped with a common prefix. The mentioned `buf` is retrieving the offsets of the keys to fraction them in `offsets`.

**Comment by schomatis** [comment]
> I wonder if the mmap is messing with the heap profiler (as buf isn't really on the heap).

Yes, although the SSTable by default is loaded into RAM, `mmap` is used only for the log file and the `logFile` structure isn't even on the top ten list. The `buf` variable with the slice header should be on the stack, but the buffer itself should be on the heap, still I see no reason in `readIndex()` why it shouldn't be GC'ed, so I'm a bit lost here.

Anyway, I'll research this a bit more then to see what I can find out, otherwise I'll raise the issue at Badger.

**Comment by schomatis** [comment]
Hey @Kycklingar, sorry for the delay, I'll make a priority of this issue in the upcoming days.

**Comment by schomatis** [comment]
@manishrjain From a Badger DB perspective, does this memory usage seems normal to you? (especially on the `Table` object which I would have expected to be much less than the `logFile` one)

**Comment by manishrjain** [comment]
This does look weird, I'd expect line 201 to take up RAM, not line 217. Just to understand this better, can you provide the output of `badger info`. And also, the options used to bring up the Badger instance.

**Comment by schomatis** [comment]
@Kycklingar Do you still have access to the DB to run that command and post the output here? (And also the `.ipfs/config` to check if some of the default options were changed, such as `syncWrite`.)

**Comment by Kycklingar** [comment]
@schomatis Yes I do but I would rather not do that as it would leave the machine unresponsive for somewhere between 1 and 24 hours.
Anyway here is the config file: https://ipfs.io/ipfs/zb2rhmfQX5qtQH4npp5DnmCajiBiJ8uVPcGyqnb29NmZnVkYk

**Comment by schomatis** [comment]
@Kycklingar The `badger info` command is independent of the IPFS stack and it shouldn't affect the consumed RAM so much as it opens the DB in read-only mode, if you could try it that would be very helpful, if you can't that's understandable also and we'll have to triage this with the available information.

**Comment by schomatis** [comment]
@manishrjain From the config file it would seems that `syncWrites` is set and the rest are the default Badger options.

**Comment by Kycklingar** [comment]
@schomatis Oh sorry I thought you meant running the gc again. Here's the output from badger info: https://ipfs.io/ipfs/zb2rhfrsAvUmdSGASSZYdr7Y1uZ8tGrhNdEifK9pUhMpBuwdt

**Comment by schomatis** [comment]
Thanks! So @manishrjain I think you now have the requested information, ping me if you need anything else.

**Comment by schomatis** [comment]
@manishrjain If still relevant to the current Badger release, could you take a look at the provided information please? (If it's too outdated I'll go ahead and close this one.)

**Comment by manishrjain** [comment]
Just looking at the available information:

- We have ~5GB of LSM tree, which is being stored in RAM by default.
- The heap profile shows Badger using 5.6GB, which seems close enough to be accountable by the LSM tree being stored in RAM.

You could try to set the `ipfs repo gc` to load LSM tree as mmap so the OS can swap out the pages, instead of trying to load everythin in RAM. I don't see any indication that the memory usage was higher than 8GB (Showing nodes accounting for 7.12GB, 98.70% of 7.21GB total), that somehow seems like a harder limit than the indicated 24GB available RAM (in the comments).

Note that the `repo gc` command and other commands can have their own settings for where to load the LSM and value log (ram, mmap, disk, etc.) -- these can be independent, based on performance needs.

**Comment by schomatis** [comment]
@manishrjain Thanks for the fast response.

As mentioned in the previous comments this seems like an OOM error, I'll be closing this issue but @Kycklingar please feel free to reopen if this is still a problem or you have any other evidence that would contradict @manishrjain analysis (I would recommend trying the suggested `mmap` setting to see if that controls the RAM usage).
