### ISSUE TITLE
something about node data sync

### ISSUE THREAD

**Issue by luzhongqiu** [ipfs/go-ipfs#5180]
I have three node called A,B,C
when I upload a file from A, It can been seen at B. But when I shutdown A, B can not see it again. so I want to know why it is not sync between these node.

**Comment by leerspace** [comment]
What do you mean "it can be seen at B"? How are you accessing the content on node B while node A is up?

**Comment by Stebalien** [comment]
We've moved discussions and questions to https://discuss.ipfs.io as this issue tracker is getting a bit overloaded.
