### ISSUE TITLE
MFS directory listings with `l: true` changes the file list order

### ISSUE THREAD

**Issue by achingbrain** [ipfs/go-ipfs#5181]
It seems that the order of directory contents returned from `ipfs.files.ls` api invocations changes if you pass `l: true` or `l: false`.

Compare (these tests have not previously only run against go-ipfs as there's been no mfs implementation in js-ipfs):

https://github.com/ipfs/interface-ipfs-core/blob/master/js/src/files/ls.js#L54-L61

vs

https://github.com/ipfs/interface-ipfs-core/blob/master/js/src/files/ls.js#L74-L92

Is this desired behaviour?  Only we'll have to implement it in js-land as well if so.

**Comment by schomatis** [comment]
> Is this desired behaviour?

It wouldn't seem so, a `sort()` was added to the function that list names (https://github.com/ipfs/go-ipfs/commit/b4a47e35db6c2908588eb80a465d84716cef61de) when `-l: false`, 

https://github.com/ipfs/go-ipfs/blob/7e8f6c96047e1a94c1c892aa50e1c75e01b7fda2/mfs/dir.go#L235-L251

the function that lists entries (`-l: true`) with all of the information (including the name) doesn't sort its output,


https://github.com/ipfs/go-ipfs/blob/7e8f6c96047e1a94c1c892aa50e1c75e01b7fda2/mfs/dir.go#L253-L260

**Comment by Stebalien** [comment]
Yeah, that sort should probably be removed and turned into an option (applied at a higher layer).

**Comment by schomatis** [comment]
So, while working on #5219 I remembered that the entries are already sorted at the DAG link level,

https://github.com/ipfs/go-ipfs/blob/a9efa7e201707bd1a0d48fe1146a76ec0097db92/merkledag/node.go#L79-L84

I actually couldn't get an output from `ipfs files ls` that wasn't sorted (with or without `-l`),

> It seems that the order of directory contents returned from ipfs.files.ls api invocations changes if you pass l: true or l: false.

@achingbrain Could you provide me an example of that?

**Comment by achingbrain** [comment]
@schomatis sure, I came across this in the interface tests:

https://github.com/ipfs/interface-ipfs-core/blob/master/js/src/files/ls.js#L57-L58

vs

https://github.com/ipfs/interface-ipfs-core/blob/master/js/src/files/ls.js#L77-L88

**Comment by schomatis** [comment]
Oh, yes, you posted that when you submitted the issue, sorry, I'm not
familiar with that repo, I meant if you have a `go-ipfs` command example,
e.g.,

```
ipfs add
ipfs files cp /ipfs/<hash> /b
ipfs files cp /ipfs/<hash> /a
ipfs files ls /
# They appear in order
ipfs files ls / -l
# And now they don't
```

**Comment by schomatis** [comment]
I'm suspecting that I'm confusing the JS `ipfs.files.ls` call with the actual `ipfs files ls` (`go-ipfs`) command.

**Comment by schomatis** [comment]
```
ipfs config --json Experimental.ShardingEnabled true
HASH=$(echo "" | ipfs add -Q)
ipfs files cp /ipfs/$HASH /b
ipfs files cp /ipfs/$HASH /a
ipfs files ls /
# a
# b
ipfs files ls / -l
# b	Qmc5m94Gu7z62RC8waSKkZUrCCBJPyHbkpmGzEePxy2oXJ	1
# a	Qmc5m94Gu7z62RC8waSKkZUrCCBJPyHbkpmGzEePxy2oXJ	1
```
