### ISSUE TITLE
Performance with 1GB+ files

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#519]
Currently, ipfs doesn't deal well with 1GB+ files. dht + bitswap go berserk (pegs cpu) and i've yet to see one terminate (before i give up not being able to write test because of cpu pegging).

Would be great to 
1. Rate limit ipfs completely: be able to set cpu/bw caps. (harder)
2. Rate limit bitswap and dht asyncness*. i'm reluctant to mess with it atm though.  
3. Get a progress indicator #501 

[*] I wrote a simple module to do this nicely, see it in blockservice: https://github.com/jbenet/go-ipfs/blob/master/blockservice/blockservice.go#L71-L81

**Comment by whyrusleeping** [comment]
checking this out.

**Comment by briantigerchow** [comment]
to take precise measurements, see the benchmark at https://github.com/jbenet/go-ipfs/blob/master/test/bench/bench_cli_ipfs_add/main.go.

**Comment by whyrusleeping** [comment]
Im going to close this one, Ive been able work with two or three gig files pretty readily.

**Comment by whyrusleeping** [comment]
Gonna keep this open until we address the issues with leveldb compaction, I want to move to storing blocks on disk similar to how git does it.

**Comment by travisperson** [comment]
Ping! With the latest repo merge can this one be closed?

/cc @whyrusleeping

**Comment by whyrusleeping** [comment]
yeah, adding files is blazing fast now. closing
