### ISSUE TITLE
Local Service Discovery

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#520]
Would be nice if `ipfs daemon` looked for peers through Local Service Discovery (and all those protocols). This would be pretty sweet.

**Comment by zignig** [comment]
A multicast beacon would work too , many of the Service discovery protocols are pretty heavy.

**Comment by whyrusleeping** [comment]
yeah, a UDP broadcast of 'hey im ipfs! heres some info!' every so often would suffice for our uses. but we need to focus on being more lightweight...

**Comment by whyrusleeping** [comment]
we do this now, yay mdns!
