### ISSUE TITLE
Adding files hangs when --routing=none

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#5201]
When the daemon is started with `ipfs daemon --routing=none`, adding files with or without `--local` simply hangs. This does not appear to be a recent regression (present in 0.4.14 and probably before).

**Comment by madper** [comment]
Hi @Stebalien ,
I failed to reproduce the issue with the latest master. 
Please could you kindly correct my steps?
![screenshot from 2018-07-17 22-43-48](https://user-images.githubusercontent.com/451815/42824792-24a73f22-8a13-11e8-94f3-a9b3418a803a.png)

BR

**Comment by Stebalien** [comment]
I can't either... I'll reopen if I can figure out how I did this in the first place.
