### ISSUE TITLE
Windows 10 building issue

### ISSUE THREAD

**Issue by spartucus** [ipfs/go-ipfs#5203]
#### Description:

I'm following [MSYS2](https://github.com/ipfs/go-ipfs/blob/master/docs/windows.md#msys2) way to install ipfs on windows, when running `make install` error ocurs: 
```
error: couldn't download with ftp (2)
Unable to download https://ipfs.io/ipfs/QmYpvspyyUWQTE226NFWteXYJF3x3br25xmB6XzEoqfzyv/gx/v0.13.0/gx_v0.13.0_windows-amd64.zip. exiting.
make: *** [bin/Rules.mk:23: bin/gx-v0.13.0] Error 1
```
It seems like connection issue, so i paste "https://ipfs.io/ipfs/QmYpvspyyUWQTE226NFWteXYJF3x3br25xmB6XzEoqfzyv/gx/v0.13.0/gx_v0.13.0_windows-amd64.zip" into Chrome and zip file downloaded successfully. 

So i also tried `curl https://ipfs.io/ipfs/QmYpvspyyUWQTE226NFWteXYJF3x3br25xmB6XzEoqfzyv/gx/v0.13.0/gx_v0.13.0_windows-amd64.zip` in command line, it says:
```
C:\Users\THINK>curl https://ipfs.io/ipfs/QmYpvspyyUWQTE226NFWteXYJF3x3br25xmB6XzEoqfzyv/gx/v0.13.0/gx_v0.13.0_windows-amd64.zip
curl: (7) Failed to connect to ipfs.io port 443: Timed out
```

EDIT:
I download `gx_v0.13.0_windows-amd64.zip` and move it t bin/tmp, and rename it to gx.zip. And also comment the download part of `dist_get` like;
```
#download "$url" "$tmpfi"
#if [ $? -ne 0 ]; then
#	die "failed to download $url to $tmpfi"
#fi
```
And when i `make install` again, this time it comes with a different error message:
```
C:\Users\THINK\go\src\github.com\ipfs\go-ipfs>make install
bin/check_go_version 1.10
bin/check_go_path /c/Users/THINK/go/src/github.com/ipfs/go-ipfs /c/Users/THINK/go/src/github.com/ipfs/go-ipfs
rm -f bin/gx-go.exe
cp bin/gx-go-v1.7.0.exe  bin/gx-go.exe
gx install --global
ERROR: req-check hook failed: fork/exec C:\Users\THINK\go\src\github.com\ipfs\go-ipfs\bin\gx-go.exe: %1 is not a valid Win32 application.
make: *** [mk/gx.mk:4: gx-deps] Error 1
```

**Comment by Stebalien** [comment]
Do you use a proxy?

**Comment by Stebalien** [comment]
You'll need to set the proxy environment variables. See:

* https://stackoverflow.com/questions/9445489/performing-http-requests-with-curl-using-proxy
* https://wiki.archlinux.org/index.php/Proxy_settings#Environment_variables

**Comment by Stebalien** [comment]
Closing as this isn't a bug. Feel free to ask for clarification.
