### ISSUE TITLE
webui not work

### ISSUE THREAD

**Issue by uppercaveman** [ipfs/go-ipfs#5210]
Version information:
ipfs version 0.4.15

change ports :

ipfs config Addresses.API "/ip4/127.0.0.1/tcp/10501"
ipfs config Addresses.Gateway "/ip4/127.0.0.1/tcp/10580"

go to _http://localhost:10501/webui_ not work.

**Comment by Stebalien** [comment]
Did you restart your node?
What does `ipfs --api /ip4/127.0.0.1/tcp/10501 config API` show?

**Comment by uppercaveman** [comment]
I changed it first and then started it.

ipfs --api /ip4/127.0.0.1/tcp/10501 config API  : 
![1531227921521](https://user-images.githubusercontent.com/4667056/42511763-5a7225f6-8485-11e8-9496-26821046c289.jpg)

ipfs daemon : 
![image](https://user-images.githubusercontent.com/4667056/42511871-a3b574f2-8485-11e8-9606-90929cb75175.png)

**Comment by uppercaveman** [comment]
supplement : 

http://localhost:10501/webui not work : 

![image](https://user-images.githubusercontent.com/4667056/42512102-4affaf7a-8486-11e8-87a8-ee689cf2c49f.png)

But API is ok : 
![image](https://user-images.githubusercontent.com/4667056/42512156-765f13ae-8486-11e8-81d7-e97ac0873ec0.png)

**Comment by Stebalien** [comment]
Ah. So, you're using a private network. See: https://github.com/ipfs/go-ipfs/issues/4174

**Comment by uppercaveman** [comment]
Thanks @Stebalien
