### ISSUE TITLE
Avoid use of `pb.Data`

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#5217]
Avoid direct manipulation of the UnixFS format (`pb.Data`) and use the `FSNode` abstraction instead.

Replacing all `FromBytes()` calls (and removing the function itself),

https://github.com/ipfs/go-ipfs/blob/a9efa7e201707bd1a0d48fe1146a76ec0097db92/unixfs/unixfs.go#L32-L40

with `FSNodeFromBytes()` should be a good first step,

https://github.com/ipfs/go-ipfs/blob/a9efa7e201707bd1a0d48fe1146a76ec0097db92/unixfs/unixfs.go#L153-L162

**Comment by overbool** [comment]
@schomatis can i help you do for it?

**Comment by schomatis** [comment]
Yes, go ahead!

**Comment by kevina** [comment]
Offhand this sounds like a good idea. But I would need to see the P.R. before I am able to give any opinion.  Refactors like this are hard for me to visualize without just doing it.  Also a p.r. makes sure we don't miss any corner cases.
