### ISSUE TITLE
How are entries removed from the DHT?

### ISSUE THREAD

**Issue by ambertch** [ipfs/go-ipfs#5220]
Say I have a piece of content pinned on two servers, and issue an `ipfs dht findprovs` from a third, the peer IDs of the two servers are listed.

When I remove the pin from one of them, findprovs still lists the node. This is expected if the content hasn't been GC'd, although even when I delete .ipfs and reinitialize, the node is still listed as having the content.

When is the DHT updated when content is removed from one of the nodes where a copy lives? 

Thanks!

**Comment by Stebalien** [comment]
The provider records expire after a period of time and are repeatedly republished.

Note: We're trying to move all discussions and questions to https://discuss.ipfs.io.

(Yes I occasionally answer questions here when they are borderline bugs/feature requests but it's best to just ask questions on the discuss.ipfs.io forum).
