### ISSUE TITLE
[jenkins] CI build should fetch gx from dists, not go get

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#5222]
We currently use go get to fetch and install gx. We should just be using the scripts we have in the repo for installing gx binaries.

**Comment by whyrusleeping** [comment]
cc @VictorBjelkholm @magik6k

**Comment by magik6k** [comment]
That happens for windows only, right?

**Comment by Kubuxu** [comment]
We are using go modules now.
