### ISSUE TITLE
Tool for converting hashes

### ISSUE THREAD

**Issue by kyledrake** [ipfs/go-ipfs#5229]
Create a tool / subcommand within go-ipfs for converting between cidv0 and cidv1, and different bases (base58, base32, etc).

https://github.com/ipfs/ipfs/issues/337

@kevina

**Comment by Stebalien** [comment]
Take a look at the `cid-fmt` command in the `go-cid` package. The command you're looking for is `cid-fmt -b b -v 1 '%s'`. It could definitely be better documented and more user friendly...

**Comment by kevina** [comment]
I am thinking this should be a sub-command of `go-ipfs`.  See #5357.

**Comment by alanshaw** [comment]
JS CID tool coming together here: https://github.com/ipfs-shipyard/cid-tool - it can and will be integrated with ipfs as `ipfs cid` but can also be used as a standalone CLI tool.
