### ISSUE TITLE
Refactor blockstore to work with bare multihashes instead of CIDs

### ISSUE THREAD

**Issue by kyledrake** [ipfs/go-ipfs#5231]
This is needed to prevent issues with blockstore data duplication when different CIDs are provided for the same multihash.

The "quick fix" version is to check for both, but a proper conversion and migration would be better for preventing dupes.

https://github.com/ipfs/ipfs/issues/337

@kevina

**Comment by kevina** [comment]
See https://github.com/ipfs/go-ipfs/pull/5285 for the "quick fix".

**Comment by kevina** [comment]
See https://github.com/ipfs/go-ipfs-blockstore/issues/8 for a discussion on what the new interface should be.

**Comment by lidel** [comment]
Continued in https://github.com/ipfs/go-ipfs/issues/6815
