### ISSUE TITLE
Create ipfs.add flag for specifying base of produced CID

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#5233]
This is a small, but important piece on the road to CIDv1 in Base32: https://github.com/ipfs/ipfs/issues/337
IMO it should happen before anything else:

> To make migration easier, it should be possible for user to opt-in for different base when adding files:
> 
> `ipfs add --cid-base=base32`  (use of `--cid-base` should imply `--cid-version 1`)

**Note**: it is a separate thing from "specifying full default cidv1 parameters", which is tracked in   https://github.com/ipfs/go-ipfs/issues/5230

cc @kevina  @kyledrake @alanshaw (for parity with js-ipfs – https://github.com/ipfs/js-ipfs/issues/1440)

**Comment by kevina** [comment]
Actually what I plan to implement is a little different.  It is a global `mbase` option.  We output CIDs in nearly every command so a global option makes more sense.  This option does not imply that newly added files are CIDv1 it simply changes the output (when fully implemented) of all `go-ipfs` commands to output CIDv1 in the given base.

**Comment by kevina** [comment]
Note that it doesn't imply CIDv1 because it makes sense to decouple the base CIDv1 are displayed and the CID version of newly added files.

**Comment by lidel** [comment]
@kevina Global flag for default base of outputted CIDs across entire app is a good idea, as it would solve issue raised in https://github.com/ipfs/go-ipfs/issues/5234 :+1: 

But it does not remove the need for opt-in `--cid-base=` parameter in `ipfs add`, it is a complementary UX feature.

Users should have an option to change the default base via ad-hoc command to enable batch scripting that outputs different base depending on added content. I see some scenarios where hashes for some files need to be as short as possible, while others need to conform to some standard or limitation, eg. be URL and Origin-safe. Having `--cid-base=` parameter will  make it easy to handle it programmatically without need for conversion step in userland.

**Comment by kevina** [comment]
> Users should have an option to change the default base via ad-hoc command to enable batch scripting that outputs different base depending on added content.

By a global flag I mean a command line flags that can be used with all `ipfs` command, not just `ipfs add`.  This is separate from a config option.  `ipfs add`.  `ipfs add --mbase=base32 --cid-version=1` will be identical to `ipfs add --cid-base=base32`.

**Comment by lidel** [comment]
Ack, finally got it, if it is a global commandline param, it brings much more value.
It solves UX around base encoding across all APIs and makes all sorts of scripting easier, 
eg `ipfs files ls -l --mbase=base32`
:+1:  from me, as long we implement the same in js-ipfs (cc @alanshaw)

**Comment by hsanjuan** [comment]
(subscribing)
