### ISSUE TITLE
ipfs resolve should respect CID base

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#5234]
#### Description:

Actual:
```
# ipfs resolve /ipfs/bafkreickb4yq3sr3q2xqn3z3wzimilsa4wkbx25azqbvcnihq65moyjcvi
/ipfs/zb2rhbdNoGAYtRfZgcobnk5bJWTrqZY18zZ2o3dmp4QD12mxV
```

Expected:
```
# ipfs resolve /ipfs/bafkreickb4yq3sr3q2xqn3z3wzimilsa4wkbx25azqbvcnihq65moyjcvi
/ipfs/bafkreickb4yq3sr3q2xqn3z3wzimilsa4wkbx25azqbvcnihq65moyjcvi
```

It forgets the base32 encoding and applies base58btc instead.

Part of ipfs/ipfs#337 (cc @kyledrake)

**Comment by Stebalien** [comment]
This is going to be *so* painful...

**Comment by kevina** [comment]
This ended up being fairly easy to do #5289 now respects the CID in `ipfs resolve`.

**Comment by kevina** [comment]
However, other similar cases such of `ipfs pin` are not so easy.  As a solution to that I present https://github.com/ipfs/go-cid/pull/64.
