### ISSUE TITLE
Failing Docker Hub build

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/go-ipfs#5238]
Just got an email that the build is failing. It failed at this step: `Build failed: The command '/bin/sh -c cd $SRC_DIR && mkdir .git/objects && ([ -z "$GX_IPFS" ] || echo $GX_IPFS > /root/.ipfs/api) && make build' returned a non-zero code: 2`

Trying to get some better logs out of Docker Hub but I'm not having any success with that. Locally everything works fine.

**Comment by schomatis** [comment]
Most probably fixed by #5239.

**Comment by VictorBjelkholm** [comment]
Yup, seems to work fine again. Thanks @schomatis!
