### ISSUE TITLE
Failing building from source

### ISSUE THREAD

**Issue by kvm2116** [ipfs/go-ipfs#5240]
#### Type:

Bug

#### Description:

I am trying to build IPFS from source on Linux 16.04 according to the directions given [here](https://github.com/ipfs/go-ipfs#build-from-source). The build fails giving the following error:

go install -ldflags="-X "github.com/ipfs/go-ipfs/repo/config".CurrentCommit=419bfdc" ./cmd/ipfs
# github.com/ipfs/go-ipfs/unixfs/io
unixfs/io/directory.go:110:15: fsNode.GetType undefined (type *unixfs.FSNode has no field or method GetType)
cmd/ipfs/Rules.mk:37: recipe for target 'cmd/ipfs-install' failed
make: *** [cmd/ipfs-install] Error 2

**Comment by Stebalien** [comment]
Fixed by https://github.com/ipfs/go-ipfs/pull/5239.
