### ISSUE TITLE
DHT Records: signatures

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#525]
Currently, DHT provider records are not signed, meaning anyone can sign someone else up for providing an object. That shouldn't happen: dht provide records must be signed, and only used if sig verify succeeds.

The `{Get/Put}Value` records we use (IPNS) already have their own notion of validity.

**Comment by whyrusleeping** [comment]
I dont know how i feel about this. I agree its needed for the security aspect, but signing every single provider would get *really* expensive. And we are already worried about CPU consumption. Id say leave this issue open, but not worry about it for a little while.

**Comment by briantigerchow** [comment]
I was curious about the cost of Sign/Verify. If I made a mistake with the calculation, let me know.

```
BenchmarkSign1B             1000           2406924 ns/op
BenchmarkSign10B            1000           2360527 ns/op
BenchmarkSign100B           1000           2354136 ns/op
BenchmarkSign1000B           500           2361775 ns/op
BenchmarkSign10000B          500           2415993 ns/op
BenchmarkSign100000B         500           2718051 ns/op
BenchmarkVerify1B          30000             52117 ns/op
BenchmarkVerify10B         30000             50968 ns/op
BenchmarkVerify100B        30000             51037 ns/op
BenchmarkVerify1000B       30000             56768 ns/op
BenchmarkVerify10000B      10000            105744 ns/op
BenchmarkVerify100000B      2000            628530 ns/op
```

see #528

**Comment by whyrusleeping** [comment]
hrm... i wonder how 2.4 ms will impact the time it takes to add a larger file

**Comment by briantigerchow** [comment]
> hrm... i wonder how 2.4 ms will impact the time it takes to add a larger file

At steady state, with an average block size of 256KB, the 2.4ms operation caps sustained throughput at 102 MB/s. (Burst rate not affected)

**Comment by whyrusleeping** [comment]
okay, 102MB/s isnt terrible for now. We will have to look for different solutions in the future (should be fairly easy to parallelize)

**Comment by diasdavid** [comment]
This is now included on the Record Spec https://github.com/ipfs/specs/tree/master/records

**Comment by Kubuxu** [comment]
I don't think it should be closed as it concerns whole DHT not only IPNS/RS.
See https://github.com/ipfs/specs/issues/73

**Comment by Winterhuman** [comment]
@whyrusleeping @daviddias This issue is closed, but, are peer records and provider records now signed? (Also, do you have the link for what https://github.com/ipfs/specs/tree/master/records later became? It leads nowhere)

**Comment by Winterhuman** [comment]
Nevermind, https://github.com/ipfs/specs/issues/73 and https://github.com/ipfs/specs/issues/160 are still open, should this issue be reopened or has this been superseded by another issue?

**Comment by Winterhuman** [comment]
@Kubuxu Could this issue be reopened?

**Comment by Jorropo** [comment]
@Winterhuman we have other issues describing the problem, they are linked to this one. It doesn't need to be reoppened
