### ISSUE TITLE
how can i read pubsub api's data

### ISSUE THREAD

**Issue by tyhtao1990** [ipfs/go-ipfs#5252]
i am test pubsub function in my machine.
1. i used commands in two temminals -> one input command:  ipfs pubsub sub c1, another input command: ipfs pubsub pub c1 1.the sub terminal output "1" inresult
2.i used pubsub api in two temminals the same way:
1.one temminal: curl "http://localhost:5001/api/v0/pubsub/pub?arg=a&arg=1"
2.another temminal: curl "http://localhost:5001/api/v0/pubsub/sub?arg=a"
result:{"from":"EiDBT+y085JoaLu/Mg2H0OW9Rg0e77PxQo14CJdwzf47jA==","data":"MQ==","seqno":"FUJ09LcKz8Q=","topicIDs":["a"]}

my question is the data in api is encrypt. how can i decrpt it?

i found the answer in issues, one told to use the keypairs that show up in command "ipfs key list", but how can i use the key to decrypt？
another told to use "ipfs crypt" , but i found this command have not been exised.

how can i decrpt the data in pubsub api?

**Comment by tyhtao1990** [comment]
i found the reason, the data need to use base64 to decrpt
but i can't decrpt the "from" param

**Comment by Stebalien** [comment]
Please ask support questions on https://discuss.ipfs.io.
