### ISSUE TITLE
DAG reader: seeking to the end of the file leaves the offset at zero

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#5255]
Seeking to an offset equal to the size of the file (or a bigger)  leaves the `linkPosition` (unmodified) at the start of the file (where subsequent read operations will pick up from).

https://github.com/ipfs/go-ipfs/blob/9bad5fe6fef11fc5d923e7ebecbe6f53deb044fe/unixfs/io/pbdagreader.go#L275-L286

I'm working on some modifications to the DAG reader and I'm not sure if this is a bug or it is an intended behavior (I don't know what happens in the Unix API when doing something like this) as some of the current tests (like [`TestLargeWriteChunks`](https://github.com/ipfs/go-ipfs/blob/9bad5fe6fef11fc5d923e7ebecbe6f53deb044fe/unixfs/mod/dagmodifier_test.go#L292)) depend on it.

**Comment by Stebalien** [comment]
This should follow POSIX and seek past the end of the file. Reading should return zero bytes and an EOF.

**Comment by schomatis** [comment]
Ok, this is a bug then, thanks.

**Comment by schomatis** [comment]
Fixed in https://github.com/ipfs/go-unixfs/pull/60.
