### ISSUE TITLE
make: check_go_path args with whitespace

### ISSUE THREAD

**Issue by djdv** [ipfs/go-ipfs#5260]
#### Version information:
N/A

#### Type:

Bug

#### Description:
I'm trying to build from "/c/Users/Dominic Della Valle/Projects/Go/src/github.com/ipfs/go-ipfs"
with `make build`. The fact that my username has a space in it, is causing issues
```
>make build
bin/check_go_version 1.10
bin/check_go_path
must pass in your current working directory
make: *** [mk/golang.mk:69: check_go_path] Error 1
```
For whatever reason `make`'s `realpath` is returning an empty string and passing that to `check_go_path`
https://github.com/ipfs/go-ipfs/blob/6f140d2579f3f404c862ac4eccc495a20b426264/mk/golang.mk#L69

Wrapping the `pwd` return in quotes like `$(realpath "$(shell pwd)")` doesn't have any effect either.

**Comment by djdv** [comment]
ping @magik6k

**Comment by Stebalien** [comment]
I pushed the logic into `check_go_path` as doing this in make turned into a nightmare. Fixed in https://github.com/ipfs/go-ipfs/pull/5261.
