### ISSUE TITLE
`Sync()`/`modifyDag()`: correctly handle offsets bigger than file size

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#5263]
See https://github.com/ipfs/go-ipfs/pull/5262#issuecomment-406457401.

`Sync()` doesn't detect it (to maybe call `expandSparse()`) and `modifyDag()` isn't prepared for this scenario, it iterates to the end of the DAG and does nothing,

https://github.com/ipfs/go-ipfs/blob/1dede1b1d7046b4a2246b7ec29820655548ad324/unixfs/mod/dagmodifier.go#L310-L341

and after that when the write buffer hasn't been drained (written to the DAG) it incorrectly interprets it as a need to append,

https://github.com/ipfs/go-ipfs/blob/1dede1b1d7046b4a2246b7ec29820655548ad324/unixfs/mod/dagmodifier.go#L215-L217

**Comment by kjzz** [comment]
hey @schomatis , i am interested in this.Can i help u do for this?

**Comment by schomatis** [comment]
Sure! This code has now been moved to https://github.com/ipfs/go-unixfs.

**Comment by kjzz** [comment]
Thanks.If i have any problem,i will ping you.

**Comment by schomatis** [comment]
Fixed in https://github.com/ipfs/go-unixfs/pull/33.
