### ISSUE TITLE
Resolving links in sharded directories does not seem to work

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/go-ipfs#5270]
#### Version information:

Gateways running commit 1dede1b1d7046b4a2246b7ec29820655548ad324

#### Type:

Bug
#### Description:

I've tried three projects that are using sharded directories and one without. The one without resolves links correctly but none of the projects using sharded directories works for resolving links. However, it does work when using 0.4.15

- https://localhost:7002/ipns/arch.victor.earth/community works correctly (using version 0.4.15)
- https://ipfs.io/ipns/arch.victor.earth/community gets error message `ipfs resolve -r /ipns/arch.victor.earth/community: no link by that name`

**Comment by magik6k** [comment]
Likely introduced in https://github.com/ipfs/go-ipfs/pull/4672 which switched from using `path.pesolver.ResolvePath` to `path.pesolver.ResolveToLastNode` which doesn't appear to respect `Resolver.ResolveOnce`. As the gateway uses coreapi it got affected by this

**Comment by VictorBjelkholm** [comment]
@magik6k something is still weird here...

https://ipfs.io/ipfs/QmXeh5S5Dk528ueFX3iFRB5TuKUNrWM9dEiLfC4crVwuHD is a sharded directory.

https://ipfs.io/ipfs/QmXeh5S5Dk528ueFX3iFRB5TuKUNrWM9dEiLfC4crVwuHD/PAL_Express.html gives me `no link by that name`

If I look on the IPLD explorer and take that path: https://explore.ipld.io/#/explore/QmXeh5S5Dk528ueFX3iFRB5TuKUNrWM9dEiLfC4crVwuHD it would be `27PAL_Express.html`

https://ipfs.io/ipfs/QmXeh5S5Dk528ueFX3iFRB5TuKUNrWM9dEiLfC4crVwuHD/27PAL_Express.html gives me `inconsistent ResolveOnce / nd.Resolve`

**Comment by VictorBjelkholm** [comment]
Also:

```
$ ipfs resolve /ipfs/QmXeh5S5Dk528ueFX3iFRB5TuKUNrWM9dEiLfC4crVwuHD/PAL_Express.html
Error: no link named "PAL_Express.html" under QmXeh5S5Dk528ueFX3iFRB5TuKUNrWM9dEiLfC4crVwuHD
```

**Comment by magik6k** [comment]
Looking at it

**Comment by magik6k** [comment]
So that's probably a separate issue as the right resolver is used, and on the right nodes. The error seems to come from https://github.com/ipfs/go-unixfs/blob/master/hamt/hamt.go#L388. Digging deeper

**Comment by whyrusleeping** [comment]
It would be interesting to figure out what exactly is malformed here, and how @VictorBjelkholm managed to get an incorrectly formed sharded directory.

Also better error messages would be 🔥

**Comment by VictorBjelkholm** [comment]
I'm not sure where those hashes come from, don't remember. But here is another example from Cloudflares Stack Exchange archive:

https://ipfs.io/ipfs/QmVsEiBRsdiHMvmDVJTNtrXNqSKYdtoepcoZxUrQ8rU7qR/ham/A/index.html

There is supposed to be a directory called `/ham` under `QmVsEiBRsdiHMvmDVJTNtrXNqSKYdtoepcoZxUrQ8rU7qR` but the following happens instead:

```console
$ ipfs resolve /ipfs/QmVsEiBRsdiHMvmDVJTNtrXNqSKYdtoepcoZxUrQ8rU7qR/ham
Error: no link named "ham" under QmVsEiBRsdiHMvmDVJTNtrXNqSKYdtoepcoZxUrQ8rU7qR

```

**Comment by magik6k** [comment]
I'll look into this later today

**Comment by VictorBjelkholm** [comment]
Thanks @magik6k 

IPLD explorer to the rescue! Loaded it up (https://explore.ipld.io/#/explore/QmVsEiBRsdiHMvmDVJTNtrXNqSKYdtoepcoZxUrQ8rU7qR) and found the "true" directory name `05ham` which actually resolves this time:

```console
$ ipfs resolve /ipfs/QmVsEiBRsdiHMvmDVJTNtrXNqSKYdtoepcoZxUrQ8rU7qR/05ham
/ipfs/zdj7WZpLoZYr4AoDUdpCNBVHLi1S8y6muFoCgwUa9kmxUpYCr
```

So it's not fully "not-working" :)

**Comment by VictorBjelkholm** [comment]
Thanks @Stebalien and @magik6k, I can confirm that the `resolve` now works for sharded directories!
