### ISSUE TITLE
Multiple gateway requests handled in a queue, not in parallel

### ISSUE THREAD

**Issue by negamaxi** [ipfs/go-ipfs#5273]
Hi. I have a web application that simultaneously renders multiple images like that:
```html
<img src="http://127.0.0.1:8080/ipfs/Qm..." />
```
Most of this images are NOT CACHED locally and therefore remain in a pending state in a chrome devtools. At the same time I have an audio tag that also refers to an audio file that CACHED in a local IPFS repo:
```html
<audio src="http://127.0.0.1:8080/ipfs/Qm..." />
```
But it will never play until all previous image requests will be canceled or resolved. To make this work in parallel I have to move all image requests to HTTP API and leave gateway for audio only.

Is it expected behavior for IPFS gateway? Is there any way to make it handle multiple requests in parallel, not in a queue? Thanks.

IPFS: 0.4.16
Browser: Chromium 61
OS: Linux

**Comment by Stebalien** [comment]
No, this is not expected behavior. Are you sure this is an API versus gateway issue (and that caching isn't affecting that)? Chrome itself will limit the number of concurrent HTTP requests.

**Comment by VictorBjelkholm** [comment]
@negamaxi you could have a http2 gateway via nginx or similar in between for browsers to load from, which would proxy requests to the http gateway from go-ipfs, avoiding the limiter in the browsers (Chrome at least)

Another idea is to use js-ipfs in the browser, connect it to your go-ipfs node explicitly (with a `ipfs.swarm.connect` call on startup) and load the images via js-ipfs.

**Comment by negamaxi** [comment]
@VictorBjelkholm Ok, I've got the idea. Thanks.

**Comment by Stebalien** [comment]
Ideally, IPFS would be smarter about prefetching. However, for now, you can use the read-only API exposed over the gateway.
