### ISSUE TITLE
Provide a way to truncate a corrupted Badger DB

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#5275]
Badger needs explicit consent from the user to truncate a corrupted DB when starting: passing a `--truncate` flag. That flag is not being provided as an option right now and the user gets errors like:

```
# IPFS_PATH=/ipfs/ipfs_master/repo ./ipfs daemon
Initializing daemon...
Error: Unable to replay value log: "/ipfs/ipfs_master/repo/badgerds/000017.vlog": Data corruption detected. Value log truncate required to run DB. This would result in data loss.
Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)
```

(and https://github.com/ipfs/go-ipfs/issues/5213#issuecomment-406890792), which are not really useful.

Documentation should also be added as it's a normal scenario to have a (relatively small) portion of the DB corrupted after a crash.

**Comment by Stebalien** [comment]
Will this small amount include "synced" data? If so, and if there's no way for us to actually sync the data, we should move to a different datastore. If not, we should just truncate by default.

Explicitly, I'd expect the following semantics:

1. If `Datastore.Put` has returned, the data must be persisted. Passing the truncate option shouldn't remove this data.
2. If `Datastore.Put` has not returned, we don't care. Passing the truncate option may remove this data.

**Comment by schomatis** [comment]
> Will this small amount include "synced" data?

It shouldn't if `syncWrites` is set (which by default it is), as everything will be directly persisted to the value log on disk, and from that point it can be recovered after a crash. However, if that is a deal breaker, let me double check that and get back to you.

**Comment by Stebalien** [comment]
We need *some* commit point. Some point where we can know that the data has been persisted.

**Comment by manishrjain** [comment]
Yes, that understanding is correct. If it was applied successfully to the value log, it would be replayed back after crash.

**Comment by Stebalien** [comment]
So, it looks like, given the semantics we expect, we should always enable truncation if SyncWrites is enabled.

PR: https://github.com/ipfs/go-ds-badger/pull/30

**Comment by Stebalien** [comment]
@schomatis do you have time to fix this as we discussed? That is:

1. Add a `truncate` config option.
2. Turn it *on* by default.

**Comment by schomatis** [comment]
Yes, I'll try to get to it next week.

> Turn it on by default.

Could you point me to the part of the code that generates the `config` file please?

**Comment by Stebalien** [comment]
You'll need to add something to the profile here: https://github.com/ipfs/go-ipfs-config/blob/235aea7b2426fa745412285d1d2a4a129ed564a5/profile.go#L123

Document it in: https://github.com/ipfs/go-ipfs/blob/master/docs/datastores.md#badgerds

And handle the configuration here: https://github.com/ipfs/go-ipfs/blob/4fb2666a2463bf0f17e21d3e02f176a5eb917745/repo/fsrepo/datastores.go#L341-L412

**Comment by Stebalien** [comment]
@djdv or @schomatis can we try to move forward on this?

**Comment by schomatis** [comment]
Yes, sorry, totally forgot about this one.
