### ISSUE TITLE
Update CircleCI config to 2.0

### ISSUE THREAD

**Issue by eefahy** [ipfs/go-ipfs#5279]
CircleCI 1.0 [is going away](https://circleci.com/blog/sunsetting-1-0/) Aug 31, 2018. Upgrading to 2.0 likely means using their `docker` job executor as the `machine` executor is a paid feature in 2.0.

**Comment by magik6k** [comment]
We'll probably just switch to using Jenkins exclusively. The only significant thing that needs to be adapted from Circle is gathering coverage

**Comment by kevina** [comment]
Closes #5284.
