### ISSUE TITLE
Corrupted badger database - Assert failed

### ISSUE THREAD

**Issue by leerspace** [ipfs/go-ipfs#5280]
#### Version information:

go-ipfs version: 0.4.16-
Repo version: 7

If it matters, this is a Windows 10 machine and the repo is symbolically linked from the default `.ipfs` location in my user folder to an NTFS-formatted HDD.

#### Type:

Bug

#### Description:

I'm creating this as a separate issue at requested in a response to [this issue comment](https://github.com/ipfs/go-ipfs/issues/4363#issuecomment-407143736).

At some point something happened such that I received this error when trying to start the daemon: `Error: Unable to replay value log: "C:\\Users\\user\\.ipfs\\badgerds\\000088.vlog": Data corruption detected. Value log truncate required to run DB. This would result in data loss`. It's possible I may have killed a hung command or killed the daemon or something similar; but I'm not sure what I did leading up to this.

I then ran `badger --vlog-dir badgerds/ --dir badgerds/ backup -t` as described in #5213 and it completed, but now the error output below is what I get when attempting to start the daemon with this repo.

```
>ipfs daemon
Initializing daemon...
2018/07/23 12:36:25 Assert failed
gx/ipfs/QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L/badger/y.AssertTrue
        /build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L/badger/y/error.go:55
gx/ipfs/QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L/badger.replayFunction.func2
        /build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L/badger/db.go:149
gx/ipfs/QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L/badger.(*valueLog).iterate
        /build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L/badger/value.go:305
gx/ipfs/QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L/badger.(*valueLog).Replay
        /build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L/badger/value.go:690
gx/ipfs/QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L/badger.Open
        /build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L/badger/db.go:300
gx/ipfs/QmaovxzXCm7NMURpC9U5M6QCyHcumPDYAFSq5Rkr8M8CW1/go-ds-badger.NewDatastore
        /build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmaovxzXCm7NMURpC9U5M6QCyHcumPDYAFSq5Rkr8M8CW1/go-ds-badger/datastore.go:51
github.com/ipfs/go-ipfs/repo/fsrepo.(*badgerdsDatastoreConfig).Create
        /build/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/repo/fsrepo/datastores.go:411
github.com/ipfs/go-ipfs/repo/fsrepo.measureDatastoreConfig.Create
        /build/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/repo/fsrepo/datastores.go:334
github.com/ipfs/go-ipfs/repo/fsrepo.(*measureDatastoreConfig).Create
        <autogenerated>:1
github.com/ipfs/go-ipfs/repo/fsrepo.(*FSRepo).openDatastore
        /build/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/repo/fsrepo/fsrepo.go:422
github.com/ipfs/go-ipfs/repo/fsrepo.open
        /build/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/repo/fsrepo/fsrepo.go:170
github.com/ipfs/go-ipfs/repo/fsrepo.Open.func1
        /build/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/repo/fsrepo/fsrepo.go:114
github.com/ipfs/go-ipfs/repo.(*OnlyOne).Open
        /build/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/repo/onlyone.go:35
github.com/ipfs/go-ipfs/repo/fsrepo.Open
        /build/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/repo/fsrepo/fsrepo.go:116
main.daemonFunc
        github.com/ipfs/go-ipfs/cmd/ipfs/daemon.go:238
gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds.(*executor).Execute
        /build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds/executor.go:108
gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds/cli.Run.func4
        /build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds/cli/run.go:146
runtime.goexit
        /home/why/go/src/runtime/asm_amd64.s:2361
```

**Comment by Stebalien** [comment]
Line: https://github.com/dgraph-io/badger/blob/be3a85f6a32751997ddee1b298c2113aa7bec157/db.go#L152

Thoghts @manishrjain?

**Comment by manishrjain** [comment]
What version of Badger are you on? Can you please upgrade to the latest?

**Comment by manishrjain** [comment]
Possible to switch to v1.5.3? Contains more bug fixes.

Meanwhile, if you can somehow give me access to the data set, I can try and understand why that check is failing.

**Comment by leerspace** [comment]
I can't update to v1.5.3, but I can try it again if it's added to a released version of go-ipfs.

Here's the affected badger directory: https://ipfs.io/ipfs/QmQhLSu7EZa9mYvQf8xG2x3gR5CJnSHEdJWjukjBSVGyaH

**Comment by manishrjain** [comment]
Thanks for sharing the directory. I'm currently traveling and with a slow net connection, so won't be able to download the dir. Will look into it once back. If you can keep the directory around for a few weeks, that'd be great. In any case, do mention here before you remove the directory contents.

**Comment by Stebalien** [comment]
I'll try to keep it pinned.

**Comment by leerspace** [comment]
I'll also try to keep it pinned on an always-on node for at least the next month.

**Comment by manishrjain** [comment]
Please do feel free to ping me on 7th Aug and onwards, in case I forget. Ideally, if you can create an issue in Badger, and link to this, I'd be able to stay on top of it easily.

**Comment by manishrjain** [comment]
I installed ipfs but not sure how do I download the whole directory? Any advice?

**Comment by manishrjain** [comment]
Hey guys, just an update. Trying to download the directory, it's taking long (ETA: >1d) to download the files.

**Comment by Stebalien** [comment]
Yeah, bitswap is slow and it's a large directory.

**Comment by manishrjain** [comment]
Had a look today, and found inconsistencies in the state of data, and logic allowed by Badger. It looks to me like the directory or Badger code might have been externally modified.

https://github.com/dgraph-io/badger/issues/541#issuecomment-412717790

**Comment by leerspace** [comment]
Outside of attempting to recover the repo with `badger backup`, I haven't made any changes to the repo. I'll have to defer to someone else on whether go-ipfs is doing anything non-standard with badger.

If it defies explanation and this is the only instance, maybe this is due to an obscure Windows, NTFS, unreported hardware error, or maybe even user error somehow.

**Comment by schomatis** [comment]
That would correspond this Badger [commit](https://github.com/gxed/badger/commit/deb140b6378159c58f803c01430a1b6ba3af248e).

**Comment by manishrjain** [comment]
The version in that directory matches with v1.4.0, but the version of Badger in gxed/badger is a closely matched fork and is in between v1.5.1 and v1.5.2. So, there might be inconsistencies there.

Not sure how the directory reached where it reached -- I doubt it would be easy to replicate this behavior. If you need to recover this data, I could write a tool which iterates over value log and creates a new Badger directory -- that could be useful to other people as well.

**Comment by Stebalien** [comment]
The version in that directory is [deb140b6378159c58f803c01430a1b6ba3af248e](https://github.com/dgraph-io/badger/commit/deb140b6378159c58f803c01430a1b6ba3af248e). In gxed/badger, the commit is [bf67ffc788f43d12a4677432ad102967a1067339](https://github.com/gxed/badger/commit/bf67ffc788f43d12a4677432ad102967a1067339).

The diff is:

```diff
diff --git a/.gx/lastpubver b/.gx/lastpubver
new file mode 100644
index 0000000..453e79e
--- /dev/null
+++ b/.gx/lastpubver
@@ -0,0 +1 @@
+2.6.1: QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L
diff --git a/package.json b/package.json
new file mode 100644
index 0000000..975eb32
--- /dev/null
+++ b/package.json
@@ -0,0 +1,60 @@
+{
+  "author": "dgraph-io",
+  "bugs": {
+    "url": "https://github.com/dgraph-io/badger"
+  },
+  "gx": {
+    "dvcsimport": "github.com/dgraph-io/badger"
+  },
+  "gxDependencies": [
+    {
+      "author": "whyrusleeping",
+      "hash": "QmVmDhyTTUcQXFD1rRQ64fGLMSAoaQvNH3hwuaCFAPq2hy",
+      "name": "errors",
+      "version": "0.0.1"
+    },
+    {
+      "author": "magik6k",
+      "hash": "Qmbvv2urkn5Wtwws4yzjE85qRjB293EodchZofJsrTRuvN",
+      "name": "go-lz4",
+      "version": "1.0.0"
+    },
+    {
+      "author": "kubuxu",
+      "hash": "QmXqKGu7QzfRzFC4yd5aL9sThYx22vY163VGwmxfp5qGHk",
+      "name": "bbloom",
+      "version": "0.1.1"
+    },
+    {
+      "author": "kubuxu",
+      "hash": "QmVGjyM9i2msKvLXwh9VosCTgP4mL91kC7hDmqnwTTx6Hu",
+      "name": "sys",
+      "version": "0.2.0"
+    },
+    {
+      "author": "whyrusleeping",
+      "hash": "QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC",
+      "name": "go-net",
+      "version": "0.0.0"
+    },
+    {
+      "author": "why",
+      "hash": "QmXSs8cccbT4zDR95c1iRpYKDqVMzqeF1J6iZcavgE6eNw",
+      "name": "protobuf",
+      "version": "0.0.0"
+    },
+    {
+      "author": "magik6k",
+      "hash": "QmRFFHk2jw9tgjxv12bCuuTnSbVXxEvYQkuNCLMEv9eUwP",
+      "name": "go-farm",
+      "version": "1.0.0"
+    }
+  ],
+  "gxVersion": "0.10.0",
+  "language": "go",
+  "license": "Apache 2.0",
+  "name": "badger",
+  "releaseCmd": "git commit -a -m \"gx publish $VERSION\"",
+  "version": "2.6.1"
+}
+
diff --git a/protos/backup.pb.go b/protos/backup.pb.go
index 13a9f61..9b805ee 100644
--- a/protos/backup.pb.go
+++ b/protos/backup.pb.go
@@ -15,7 +15,7 @@
 */
 package protos
 
-import proto "github.com/golang/protobuf/proto"
+import proto "github.com/gxed/protobuf/proto"
 import fmt "fmt"
 import math "math"
 
diff --git a/protos/manifest.pb.go b/protos/manifest.pb.go
index d8db55f..7473f78 100644
--- a/protos/manifest.pb.go
+++ b/protos/manifest.pb.go
@@ -3,7 +3,7 @@
 
 package protos
 
-import proto "github.com/golang/protobuf/proto"
+import proto "github.com/gxed/protobuf/proto"
 import fmt "fmt"
 import math "math"
 
diff --git a/table/builder.go b/table/builder.go
index 43e6562..c93bf88 100644
--- a/table/builder.go
+++ b/table/builder.go
@@ -22,8 +22,8 @@ import (
 	"io"
 	"math"
 
-	"github.com/AndreasBriese/bbloom"
 	"github.com/dgraph-io/badger/y"
+	"github.com/gxed/bbloom"
 )
 
 var (
@@ -201,7 +201,7 @@ func (b *Builder) blockIndex() []byte {
 
 // Finish finishes the table by appending the index.
 func (b *Builder) Finish() []byte {
-	bf := bbloom.New(float64(b.keyCount), 0.01)
+	bf, _ := bbloom.New(float64(b.keyCount), 0.01)
 	var klen [2]byte
 	key := make([]byte, 1024)
 	for {
@@ -224,7 +224,7 @@ func (b *Builder) Finish() []byte {
 	b.buf.Write(index)
 
 	// Write bloom filter.
-	bdata := bf.JSONMarshal()
+	bdata, _ := bf.JSONMarshal()
 	n, err := b.buf.Write(bdata)
 	y.Check(err)
 	var buf [4]byte
diff --git a/table/table.go b/table/table.go
index 9804fa1..5f9dde1 100644
--- a/table/table.go
+++ b/table/table.go
@@ -27,9 +27,9 @@ import (
 	"sync"
 	"sync/atomic"
 
-	"github.com/AndreasBriese/bbloom"
 	"github.com/dgraph-io/badger/options"
 	"github.com/dgraph-io/badger/y"
+	"github.com/gxed/bbloom"
 	"github.com/pkg/errors"
 )
 
@@ -202,7 +202,7 @@ func (t *Table) readIndex() error {
 	bloomLen := int(binary.BigEndian.Uint32(buf))
 	readPos -= bloomLen
 	data := t.readNoFail(readPos, bloomLen)
-	t.bf = bbloom.JSONUnmarshal(data)
+	t.bf = *bbloom.JSONUnmarshal(data)
 
 	readPos -= 4
 	buf = t.readNoFail(readPos, 4)
```

Basically, it switches to a forked bloom filter implementation and a vendored protobuf.

**Comment by leerspace** [comment]
> I doubt it would be easy to replicate this behavior. If you need to recover this data, I could write a tool which iterates over value log and creates a new Badger directory -- that could be useful to other people as well.

@manishrjain Thanks, but I don't think there's anything in this directory that is irreplaceable and that I don't have stored somewhere else. I'd try it out if a tool like this is created, though.

**Comment by manishrjain** [comment]
So, this commit: https://github.com/dgraph-io/badger/commit/deb140b6378159c58f803c01430a1b6ba3af248e is pre v1.4.0 release. I'll create an issue to build a tool like that but, if you don't need it, then I won't work on it immediately.

**Comment by magik6k** [comment]
IIRC this issue was fixed in Badger, if that's not the case please reopen.
