### ISSUE TITLE
`ipfs add -r /[path]` does not see seem to upload complete data

### ISSUE THREAD

**Issue by Miraj98** [ipfs/go-ipfs#5288]
Whenever I run the command `ipfs add -r /[path]` the respective files seem to have been added but I also get a progress bar after adding all the files. The progress bar is never 100%. I just wanted to know if `ipfs add` command is working as intended.
```
Apples-MacBook-Pro:Desktop miraj$ ipfs add -r ./test/
added QmccaabqsYh2BpHSDo4ETbUVL9qXmbwyMb3PG84ghj3KGJ test/app.js
added Qmd5Pf3a6TwXcGRcRKELUAMHJdxj7wPNQQj93saJZQ9jhR test/index.html
added QmX5RYMxZQMoDFv6KyqUYfxkRaTbS4pvntSGEs7BUsnXCu test
 740 B / 868 B [==============================================>--------]  85.25%
```

**Comment by Stebalien** [comment]
I've noticed a bug in how the commands library calculates file sizes that may be causing this. Once we merge https://github.com/ipfs/go-ipfs-cmdkit/issues/24, I'll give you a branch you can try to see if it fixes this bug.

**Comment by Stebalien** [comment]
Basically, we're telling the progress bar that there should be more data than there is. If that *is* the bug, then this is a harmless display bug.
