### ISSUE TITLE
Why not distribute prebuilt files on Github's releases page?

### ISSUE THREAD

**Issue by 1354092549** [ipfs/go-ipfs#5299]
In some cases, `ipfs.io` is blocked by some firewall, but GitHub not.

**Comment by Stebalien** [comment]
We actually distribute go-ipfs over IPFS. If you download from dist.ipfs.io, you're actually just going through our IPFS gateway. The current IPFS path is /ipfs/QmNuyz8s1MZHPBp3nu4hnAXJyXbyZXdVkJfKu38JiSv7KC (you can find go-ipfs in /ipfs/QmNuyz8s1MZHPBp3nu4hnAXJyXbyZXdVkJfKu38JiSv7KC/go-ipfs/v0.4.17/). You should be able to fetch that through any IPFS node/gateway.

We don't distribute through GitHub as multiple distribution channels are a pain to maintain. We may revisit this in the future but, for now, we have pretty limited bandwidth.

---

Closing for tracking this is non-actionable for now. Feel free to ask further questions in this thread.

**Comment by NiKiZe** [comment]
How does one find a alternative ipfs gateways?
The main issue for the users in question is that internet is censored.
So finding alternatives might be hard.

But now I'm curious, does adding binaries to Github releases take bandwidth?
https://help.github.com/articles/creating-releases/
It might be helpful to just make every other release available on github, that way it can be used to bootstrap into the latest version.

**Comment by Stebalien** [comment]
Fine... Saturdays just make me lazy. I've added the latest release to GitHub and am updating the release process documentation.
