### ISSUE TITLE
armv7h / badgerds: Unable to mmap RDWR log file: invalid argument

### ISSUE THREAD

**Issue by jcaesar** [ipfs/go-ipfs#5305]
#### Version information:
```
go-ipfs version: 0.4.17-
Repo version: 7
System version: arm/linux
Golang version: go1.10.3
```

#### Description:
When trying to use the badgerds profile on an odroid xu4 with a btrfs home dir, I get the following output:
```
initializing IPFS node at /ipfs/debugbadgerds
generating 2048-bit RSA keypair...done
peer identity: QmbuM7F8j8rVrQtFVgTqQEmp1nHzYqXpj1kngY8CaLY672
Error: Unable to mmap RDWR log file: invalid argument
```
Hopefully relevant strace is attached.

**Comment by whyrusleeping** [comment]
cc @schomatis and maybe @djdv (platforms!)

**Comment by schomatis** [comment]
Hey @jcaesar, Badger tries to `mmap` twice the (default) value of the log file, i.e., 2GB,

**Comment by Mr0grog** [comment]
> (Is this information available in any document?)

It *should* be here, but is not: https://github.com/ipfs/go-ipfs/blob/master/docs/datastores.md#badgerds

**Comment by jcaesar** [comment]
@schomatis Reducing the `vlogFileSize` indeed does get rid of the problem. The limit seems to be `1073M`. 

I'm wondering why this problem doesn't occur on some of my x86_64 VPSs with less RAM…

**Comment by schomatis** [comment]
> I'm wondering why this problem doesn't occur on some of my x86_64 VPSs with less RAM…

I really have no idea, but I'm suspecting the 32-bit nature of the Cortex processors might be a problem, 2GB is just over the top of the maximum positive signed integer (which would explain the `EINVAL` being returned instead of `ENOMEM`).

**Comment by schomatis** [comment]
There seems to be an issue in Badger about it: https://github.com/dgraph-io/badger/issues/514.
