### ISSUE TITLE
`ipfs dht findprovs` can't handle `/ipfs/$hash` 

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/go-ipfs#5311]
#### Version information:
```
go-ipfs version: 0.4.15-
Repo version: 6
System version: amd64/linux
Golang version: go1.10.2
```

#### Type:
Bug

#### Description:

Trying to find out how many providers there are for a hash and it's link, so wanted to run things via `ipfs resolve` that returns in the format of `/ipfs/$hash`. However, `ipfs dht findprovs` only seems to accept the hashes without the `/ipfs` prefix. When trying with `/ipfs/$hash`, the error message is `Error: selected encoding not supported`

```
$ ARXIV_HASH=QmfXH9XtP7xmoTH8WAp4HNSduqWMwLTH8B8TvbTkdgzNAa && ipfs resolve "/ipfs/$ARXIV_HASH"
/ipfs/QmfXH9XtP7xmoTH8WAp4HNSduqWMwLTH8B8TvbTkdgzNAa

$ ARXIV_HASH=QmfXH9XtP7xmoTH8WAp4HNSduqWMwLTH8B8TvbTkdgzNAa && ipfs dht findprovs $(ipfs resolve "/ipfs/$ARXIV_HASH")
Error: selected encoding not supported

$ ipfs dht findprovs /ipfs/QmfXH9XtP7xmoTH8WAp4HNSduqWMwLTH8B8TvbTkdgzNAa
Error: selected encoding not supported

$ ipfs dht findprovs QmfXH9XtP7xmoTH8WAp4HNSduqWMwLTH8B8TvbTkdgzNAa
QmTiCerJDqrC6vLDgcNzu8qNK4e9rTx6bJLtSgQHpkUUfk
QmViCToRk7k8asw6B7XNiC8bjomGG26XqXPWWb4WB5HKPL
QmcQzakZ46etK56gWJWqT3GqZRMCw6ovPUWEUBeCf5pUpK
^C
Error: context canceled
```

**Comment by whyrusleeping** [comment]
need to do a path resolution before passing it to the dht, I think we're currently just calling cid.Parse

**Comment by grokcoder** [comment]
the source code just decode input argument using cid.Decode 

```
c, err := cid.Decode(req.Arguments()[0])
if err != nil {
    res.SetError(err, cmdkit.ErrNormal)
    return
}
```
so what is the legal input for `findprovs`, cid or
 all of 
/ipfs/Qmcqtw8FfrVSBaRmbWwHxt3AuySBhJLcvmFYi3Lbc4xnwj
/ipns/QmatmE9msSfkKxoffpHwNLNKgwZG8eT9Bud6YoPab52vpy

are OK? any other format? @whyrusleeping

**Comment by VictorBjelkholm** [comment]
@grokcoder changing `cid.Decode` to `cid.Parse` seems to fix the problem with `/ipfs/$hash`. Just need to add some additional tests to `dht findprovs` with the different formats that we pass around as `/ipfs/$hash` is not tested as a input right now.

**Comment by grokcoder** [comment]
got it, thx @VictorBjelkholm

**Comment by Stebalien** [comment]
@meteorplus please keep discussions on-topic.

**Comment by meteorplus** [comment]
okay sorry

**Comment by Stebalien** [comment]
Fixed.
