### ISSUE TITLE
`foofoo.block` has more links than UnixFS `Blocksizes`

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#5312]
I'm refactoring the DAG reader (https://github.com/ipfs/go-ipfs/pull/5257) and I'm having an [error](https://github.com/ipfs/go-ipfs/pull/5257/files#diff-0046ca7d126fec814fde6c7ffc49ab0dR277) in the test file [`t0110-gateway.sh`](https://github.com/ipfs/go-ipfs/blob/e71dce5dfba3616e5ade4abf0844925389497a56/test/sharness/t0110-gateway.sh#L164) where the [`foofoo.block`](https://github.com/ipfs/go-ipfs/blob/e71dce5dfba3616e5ade4abf0844925389497a56/test/sharness/t0110-gateway.sh#L160) file, which is saved as a block and retrieved as a file DAG through the gateway, would appear to have an inconsistency between its number of DAG links and its number of UnixFS `Blocksizes`, is this expected in the test? If not, how could I regenerate that file with the UnixFS format fixed?

/cc @magik6k

**Comment by kevina** [comment]
This is not broken.

Please see https://github.com/ipfs/go-ipfs/pull/4680#discussion_r171793589 and https://github.com/ipfs/go-ipfs/issues/4286#issuecomment-336163070.

**Comment by schomatis** [comment]
Thanks for the references @kevina, I'll take a closer look at them. From a first read I'm understanding that UnixFS `Blocksizes` might be optional, I guess my question then is, to make the DAG reader comply with the standard expected behavior, if there is indeed a mismatch between those two indicators, what should be the correct response when seeking? I'll keep reading to see if I can find the answer there.

**Comment by kevina** [comment]
@schomatis yes please see #4680 as is is closely related.

**Comment by schomatis** [comment]
So, reading the PR that added this test, #4320, I understand that this is testing how to handle a UnixFS file that has no `Blocksizes`, and the answer seems to be rely on the UnixFS `Filesize`, @magik6k, is this correct? I can rely on the UnixFS `Filesize` and I should not trust `Blocksizes` (using instead the DAG links)?

**Comment by schomatis** [comment]
Fixed with https://github.com/ipfs/go-ipfs/pull/5257/commits/a7772902a8f0f583ab0fc757bd812ce0d57a5b69.

**Comment by magik6k** [comment]
AFAIK We want to relay on Blocksizes if they are present and defer to Filesize only if we really need to. See https://github.com/ipfs/go-ipfs/pull/4680#issuecomment-399294210 for better explanation/interpretation.

**Comment by schomatis** [comment]
Yes, my question was mostly oriented to how should the reader behave with the gateway to pass this particular test (the other seems to be a discussion for a long term solution), I understand now that `-1, nil` should be returned without moving the offset when there are no `Blocksizes`.
