### ISSUE TITLE
Can't install ipfs server 

### ISSUE THREAD

**Issue by ambrusha** [ipfs/go-ipfs#5314]
After I do `make install`

[go install -ldflags="-X "github.com/ipfs/go-ipfs/repo/config".CurrentCommit=255e158" ./cmd/ipfs
go install: no install location for /home/andrii/ipfsWork/src/src/github.com/ipfs/go-ipfs/cmd/ipfs: hidden by /usr/local/go/src/github.com/ipfs/go-ipfs/cmd/ipfs
cmd/ipfs/Rules.mk:37: recipe for target 'cmd/ipfs-install' failed
make: *** [cmd/ipfs-install] Error 1](url)

**Comment by Stebalien** [comment]
Please don't tombstone issues like this, it's really confusing. If you figure it out, just close the issue and leave a comment.

**Comment by ambrusha** [comment]
I’m really sorry ((
I thought that it will be not useful, but don’t find how to delete it...

З повагою,
Андрій Косніцький
096 111 92 70

30 лип. 2018 р. о 19:37 Steven Allen <notifications@github.com> пише:

**Comment by Stebalien** [comment]
No problem and there's no need to feel sorry. In retrospect, my comment was a bit curt (sorry about that).

And yeah, there's no way to delete issues, unfortunately.
