### ISSUE TITLE
Gateway not loading at all

### ISSUE THREAD

**Issue by skddc** [ipfs/go-ipfs#5324]
#### Version information:
```
go-ipfs version: 0.4.16-
Repo version: 7
System version: amd64/linux
Golang version: go1.10.3
```

#### Type:
Bug

#### Description:
I'm starting the daemon as usual with `ipfs daemon`. No gateway is loaded, just the API:

```
~ $ ipfs daemon
Initializing daemon...
Successfully raised file descriptor limit to 2048.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.179.209/tcp/4001
Swarm listening on /ip4/192.168.43.36/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit/ipfs/QmSRUnjuCxYiN9JfFtJ983vPnf5Rdu786eEPPHBUvxy6Sj
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/178.162.193.97/tcp/4001
Swarm announcing /ip4/192.168.179.209/tcp/4001
Swarm announcing /ip4/192.168.43.36/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Daemon is ready
```

The gateway part of my config looks like this:

```json
  "Gateway": {
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "PathPrefixes": [],
    "RootRedirect": "",
    "Writable": false
  }
```

**Comment by magik6k** [comment]
Can you try starting the daemon with `--debug --offline` and posting the log here? (`--offline` to reduce log spam)

Also:
* Make sure that `Addresses.Gateway` in config is set to a valid address like `/ip4/127.0.0.1/tcp/8080`
* Make sure that the port is not bound to anything else (check `netstat -tupln | grep 8080`)
* This is very unlikely to help, try after everything else fails - run the daemon with `IPFS_REUSEPORT=false ipfs daemon`

**Comment by skddc** [comment]
Thanks! Turns out my config was missing the `Addresses.Gateway` entry. Not sure why or how it got lost, but adding one immediately made it work again.
