### ISSUE TITLE
CoreAPI: UnixFS, discerning directories from non-directories.

### ISSUE THREAD

**Issue by djdv** [ipfs/go-ipfs#5326]
At the moment, I am relying on an error returned from [Cat()](https://github.com/ipfs/go-ipfs/blob/4bca53e0c9b52b1e2a066aa21d1e05d44bffd1ac/core/coreapi/interface/unixfs.go#L11) to determine the type of object I'm dealing with.
([reference](https://github.com/djdv/go-ipfs/commit/6db3ef41149ecfb4680651f9edcad042fc057e81#diff-864dd5908401b70ccd37dcd44f2de8e1R80))
 I think something like `.IsDir()` on the UnixFS interface, or something more generic, like `.Type` on the ObjectStat, containing some value like: Unknown, UnixFsDir, RawData, etc., would be a better alternative than relying on Cat()'s error, if you're trying to use the CoreAPI alone (without dropping into relevant pkg for each node format you wish to handle).

Relevant:
https://github.com/ipfs/go-unixfs/issues/3
https://github.com/ipfs/go-ipfs/issues/3430

Ping @schomatis, @magik6k

**Comment by magik6k** [comment]
Unixfs coreapi will get a major refactor, I'll take that into account
