### ISSUE TITLE
OpenBSD build error due to Fuse

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#5334]
```
# gx/ipfs/QmSJBsmLP1XMjv8hxYg2rUMdPDB7YUpyBo9idjrJ6Cmq6F/fuse
../../../gx/ipfs/QmSJBsmLP1XMjv8hxYg2rUMdPDB7YUpyBo9idjrJ6Cmq6F/fuse/error_std.go:27:20: undefined: errNoXattr
../../../gx/ipfs/QmSJBsmLP1XMjv8hxYg2rUMdPDB7YUpyBo9idjrJ6Cmq6F/fuse/fuse.go:1346:26: undefined: attr
../../../gx/ipfs/QmSJBsmLP1XMjv8hxYg2rUMdPDB7YUpyBo9idjrJ6Cmq6F/fuse/fuse_kernel.go:404:17: undefined: attr
```

**Comment by djdv** [comment]
Just as an aside, I'm currently reimplementing `mount` with the intention of supporting Windows [go-ipfs/win-mount](https://github.com/djdv/go-ipfs/tree/feat/win-mount), this uses a different fuse library ([cgofuse](https://github.com/billziss-gh/cgofuse)).
When this is closer to completion, I'd like to do experiments with the existing implementation on various platforms vs the new one. This should likely work on OpenBSD without change, but is untested at the moment.

**Comment by Stebalien** [comment]
The tricky part there will be cross compiling. We currently avoid cgo entirely for this reason.

**Comment by vext01** [comment]
Hi,

go-ipfs OpenBSD packager here.

I've hit this same issue. I'm not sure if this is related, but our fuse implementation isn't complete.

**Comment by magik6k** [comment]
You should be able to build with `-tags=nofuse` go bulid flag

**Comment by vext01** [comment]
According to the docs, this flag should be appended by the build system automatically:
https://github.com/ipfs/go-ipfs/blob/master/docs/openbsd.md

[note also use of deprecated target `install_unsupported`]
