### ISSUE TITLE
How do I change the ipfs/$hash path to something/$hash ?

### ISSUE THREAD

**Issue by meteorplus** [ipfs/go-ipfs#5342]
Hello guys

How the heck do I change the ipfs/$hash path to something/$hash ?

I found some info but its is very long and confusing!
https://github.com/ipfs/specs/pull/152

isn4t there a config I can change for my gateway?

Maybe in the ipfs config or my nginx config?

Thank you

**Comment by Stebalien** [comment]
Please ask support questions on discuss.ipfs.io.

**Comment by meteorplus** [comment]
thanks but I tried to post there and this happened

https://discuss.ipfs.io/t/account-temporarily-on-hold/3554

**Comment by Stebalien** [comment]
Sorry about that, discuss that for fresh accounts sometimes. Give it a few days and one of us will usually stop by to clear the block and answer the question.

**Comment by meteorplus** [comment]
no worries thanks for the response :)
