### ISSUE TITLE
experimental QUIC support

### ISSUE THREAD

**Issue by marten-seemann** [ipfs/go-ipfs#5343]
There are multiple ways we can enable experimental QUIC support:

1. We always use QUIC, as long as a QUIC address is configured.
2. We add a config option in the `Experimental` section, and then use QUIC if a QUIC address if it is configured.

1. just requires a single step to enable QUIC, but doesn't really make it clear that QUIC support is still experimental. 2. is clear about that, but it requires two steps to enable QUIC.

@Stebalien, @whyrusleeping what do you think?

**Comment by whyrusleeping** [comment]
@magik6k I think the relay option is more of an extra feature we are enabling or disabling, where QUIC is just another transport. I wouldnt want to have similar flags for tcp, websockets, etc.

@marten-seemann I think your option 2 sounds like a good way to move forward for now. The main reason being that I would still like to be able to dial to a QUIC peer if I don't have a QUIC listen address. and without the config option, its not possible to say "don't use QUIC at all for anything"
