### ISSUE TITLE
migration 6 to 7 broke config/identity and daemon cannot start

### ISSUE THREAD

**Issue by victorb** [ipfs/go-ipfs#5351]
#### Version information:

```
go-ipfs version: 0.4.17-
Repo version: 7
System version: amd64/linux
Golang version: go1.10.3
```

#### Type:

Bug

#### Description:

I've updated go-ipfs to 0.4.17 and next time I start the daemon, it asks me to run migrations. Since I want to run the daemon, I select yet. It continues to migrate my IPNS record keys, and seems to finish all the way until it's trying to start the daemon, then it fails with `private key in config does not match id: <peer.ID ViCToR> != <peer.ID 12D3Ko> daemon.go:332`.

This issue is possibly related to the fact that I first generate my keypair on another machine, then imported it to the one I'm running the daemon on, by simply replacing the values in the `$IPFS_PATH/config` file. Might not have been the right way, but has been running without issues until this migration.

```
$ ipfs daemon
Initializing daemon...
Successfully raised file descriptor limit to 2048.
Found outdated fs-repo, migrations need to be run.
Run migrations now? [y/N] y
  => Looking for suitable fs-repo-migrations binary.
  => None found, downloading.
  => Running: /tmp/go-ipfs-migrate945733802/fs-repo-migrations -to 7 -y
Found fs-repo version 6 at /home/user/.ipfs
===> Running migration 6 to 7...
applying 6-to-7 repo migration
migrating IPNS record for key: self
migrating IPNS record for key: archive-ietf-rfcs
no IPNS record for key found
migrating IPNS record for key: test
no IPNS record for key found
migrating IPNS record for key: archive-openaddresses
no IPNS record for key found
updated version file
===> Migration 6 to 7 succeeded!
  => Success: fs-repo has been migrated to version 7.
Calculating datastore size. This might take 5m0s at most and will happen only once
19:14:43.487 ERROR   cmd/ipfs: error from node construction: private key in config does not match id: <peer.ID ViCToR> != <peer.ID 12D3Ko> daemon.go:332
Error: private key in config does not match id: <peer.ID ViCToR> != <peer.ID 12D3Ko>
Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)
```

Trying to start the daemon after this issue gives the same error.

```
$ ipfs daemon
Initializing daemon...
Successfully raised file descriptor limit to 2048.
19:14:55.670 ERROR   cmd/ipfs: error from node construction: private key in config does not match id: <peer.ID ViCToR> != <peer.ID 12D3Ko> daemon.go:332
Error: private key in config does not match id: <peer.ID ViCToR> != <peer.ID 12D3Ko>
Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)
```

**Comment by Stebalien** [comment]
Are you using ed25519 keys? We recently made a breaking change to embed the public key directly in the peer ID by default (which changes the peer ID). We didn't bother with a migration because, unless I'm mistaken, there's no way to initialize a node with ed25519 keys anyways.

**Comment by Stebalien** [comment]
However, we might want to run a migration anyways?

**Comment by VictorBjelkholm** [comment]
Yeah, keys were generated with custom software (https://github.com/victorbjelkholm/ipfs-keygen) so I might be kind of alone in having this setup.

I'll just change to generate RSA keys for the time being instead, until ed25519 is officially supported. Just wanted to raise the issue in case something else was going on.
