### ISSUE TITLE
Merge Process Changes

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#5353]
Historically, Merging PRs in go-ipfs has been gated by me. As a long time contributor and maintainer of this project, I have a huge amount of context on how different changes affect the codebase, and ensuring that I review every PR means that I keep that mental state up to date, and can generally give fully informed feedback on changes that come in.

However, i've recently been pulled in a thousand different directions, this project is getting huge, and all the related bits that my attention is needed on continually eat my attention. So, to make sure that we're not blocked here, i'm going to augment the merge process a bit. @Stebalien has been helping maintain the project for over a year now, and has done an incredible job pushing things forward. Starting now, he will be able to merge PRs that have his signoff plus the signoff of another contributor who is familiar with that part of the codebase (and also who is not the author of the PR). 

We're also going to be making some other changes soon, involving giving contributors more ownership over different parts of the system. More information on that is still to come, but I wanted to seed the idea so people could start thinking about it.

I'm excited to enable the team to move forward faster, and look forward to seeing how this changes things :)

**Comment by whyrusleeping** [comment]
cc @Stebalien @magik6k @kevina @schomatis @lgierth @keks @hsanjuan @marten-seemann

**Comment by lgierth** [comment]
I approve this very much, thank you :100:

**Comment by Stebalien** [comment]
So, the "who is not also an author of the PR" bit is a bit tricky. Most PRs tend to be authored by the authority on the code in question. This means that I'll review it but, other than @whyrusleeping, nobody else can do the second review (as someone familiar with the code).
