### ISSUE TITLE
build request: Linux on ARMv8 / arm64 / aarch64

### ISSUE THREAD

**Issue by tidux** [ipfs/go-ipfs#5362]
I've tested this with `make install_unsupported` and it works.  

```
$ uname -a
Linux HOSTNAMEGOESHERE 4.9.0-6-arm64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) aarch64 GNU/Linux
$ ipfs version
ipfs version 0.4.18-dev
$ ipfs swarm peers | wc -l
691
$
```

**Comment by Stebalien** [comment]
Does `make install` not work on those platforms? Or are you requesting pre-built binaries?

**Comment by Stebalien** [comment]
FYI, there's a patch for distributing arm64 builds here: https://github.com/ipfs/distributions/pull/182. However, it needs some review.

**Comment by tidux** [comment]
`make install` fetches arch specific files so no.  I had to do `make install_unsupported` to get it to build.  Prebuilt binaries would be useful but not super necessary.

On August 9, 2018 1:10:11 PM PDT, Steven Allen <notifications@github.com> wrote:
>Does `make install` not work on those platforms? Or are you requesting
>pre-built binaries?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ipfs/go-ipfs/issues/5362#issuecomment-411881477

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Stebalien** [comment]
Ah. I see. Yeah, we'll need to distribute builds of, gx and gx-go for that to work.

**Comment by Kubuxu** [comment]
We now don't need to distributed gx (https://github.com/ipfs/go-ipfs/pull/6038) and we also tests builds on arm and arm64. We also have arm and arm64 release on dist.
