### ISSUE TITLE
Badger on 32-bit architectures

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#5367]
I understand that IPFS can run on 32-bit architectures, but as of now Badger doesn't seem capable of that, see https://github.com/dgraph-io/badger/issues/514 and  #5305.

**Comment by Stebalien** [comment]
We should be able to operate in normal "io" mode on 32bit platforms.

**Comment by manishrjain** [comment]
Submitted https://github.com/dgraph-io/badger/commit/341a135a4ab7d861599a45ca4ce00412c690bf66.

**Comment by VictorBjelkholm** [comment]
Seems this has been merged (https://github.com/dgraph-io/badger/commits/master) but maybe the dep hasn't been updated yet?

**Comment by Stebalien** [comment]
Badger has now been updated.

**Comment by Stebalien** [comment]
New fixed: Badger was doing some atomic operations on some misaligned atomic variables. This has since been fixed but we still need to update badger.

**Comment by Stebalien** [comment]
Badger has since been updated.
