### ISSUE TITLE
Clarification needed for name.publish --resolve flag

### ISSUE THREAD

**Issue by alanshaw** [ipfs/go-ipfs#5368]
#### Version information:
go-ipfs version: 0.4.17-dfd19c4
Repo version: 7
System version: amd64/darwin
Golang version: go1.10.3

#### Type:
Bug

#### Description:
`--resolve` doesn't seem to be working...

```sh
$ ipfs resolve /ipns/ipfs.io
/ipfs/QmYNQJoKGNHTpPxCBPh9KkDpaExgd2duMa3aF6ytMpHdao
$ ipfs name publish --resolve=true /ipns/ipfs.io
Published to QmahispzgXbQ5ewaxSjdrst8KNLzREhVHdhxZwAUHQWqLb: /ipns/ipfs.io
$ ipfs name resolve
Error: could not resolve name (recursion limit exceeded)
```

I was expecting:

```sh
ipfs name publish --resolve=true /ipns/ipfs.io
Published to QmahispzgXbQ5ewaxSjdrst8KNLzREhVHdhxZwAUHQWqLb: /ipfs/QmYNQJoKGNHTpPxCBPh9KkDpaExgd2duMa3aF6ytMpHdao
```

FYI, this works...:

```
$ ipfs name resolve --recursive=true
/ipfs/QmYNQJoKGNHTpPxCBPh9KkDpaExgd2duMa3aF6ytMpHdao
```

**Comment by Stebalien** [comment]
I see. So, I believe that flag was added to allow publishing *without* fetching/resolving the target. Really, it should have been called `check-resolves` or something like that but, at this point, we should just clarify the documentation.

IMO, If you want to resolve before publishing, I'd just use `ipfs name publish $(ipfs resolve -r ...)`.

**Comment by alanshaw** [comment]
> IMO, If you want to resolve before publishing, I'd just use `ipfs name publish $(ipfs resolve -r ...)`.

Yep, agree, that's easy enough - just some clarification on the docs then so others don't have the same issue :D
