### ISSUE TITLE
Can go-ipfs be programmed or am I stuck with the CLI? 

### ISSUE THREAD

**Issue by sorleone** [ipfs/go-ipfs#5377]
Can I build something with go-ipfs or can I just use it with the CLI? Js-ipfs is very well documented and very easy to get started, however as long as it keeps crashing every 15 minutes is useless. So I was wondering if I can go back and start from scratch again my project with go-ipfs. However the only things I can find are CLI commands and something about the http api, which I don't like since I don't have the full control I have with js-ipfs and that I hope to have with go-ipfs. There aren't many people able to use the terminal so why all this emphasis on that, instead of making it easy for people to build something with go-ipfs? Since few people even know about this language, there should be a very good guide that helps starting from scratch...

The error I get with js-ipfs has been around for quite long if you search for it:

https://github.com/libp2p/js-libp2p-switch/issues/235

I get it with version 0.31.4, 0.31.3, and 0.30.0, but I think every version has it. This is what I get:

```
js-ipfs/node_modules/pull-pair/index.js:11
      throw new Error('already piped')
```

I get this problem with the main example of the ipfs-pubsub-room repository:

https://github.com/ipfs-shipyard/ipfs-pubsub-room

**Comment by Stebalien** [comment]
Latest iteration of that bug: https://github.com/ipfs/js-ipfs/issues/1446

The HTTP API allows you to write programs that use the go-ipfs daemon externally, can do this from the browser using [js-ipfs-api](https://github.com/ipfs/js-ipfs-api) or from a go application using [go-ipfs-api](https://github.com/ipfs/go-ipfs-api).

You can also use go-ipfs as a library but this isn't currently well supported. We're working on improving this situation by implementing something we call the CoreAPI (the current interfaces live in core/coreapi/interfaces) but that hasn't been completed. Once that has been completed, we'll write some examples.

> There aren't many people able to use the terminal so why all this emphasis on that, instead of making it easy for people to build something with go-ipfs?

Take a look at:

* [ipfs-desktop](https://github.com/ipfs-shipyard/ipfs-desktop)
* [ipfs-companion](https://github.com/ipfs/ipfs-companion)

IPFS itself is a building block. It's designed in the client-server model where a single user will have a single IPFS daemon running in the background with multiple applications acting as clients. The CLI interface is currently just a convenient client that's relatively easy to write and maintain.

---

Closing for tracking purposes as this issue isn't directly actionable, feel free to ask follow up questions.

Note: In the future, you should probably ask questions at https://discuss.ipfs.io (our discussion forum). I've answered this one here as it's almost a feature request but the discussion forum is better suited to questions like this.

**Comment by sorleone** [comment]
@Stebalien thank you very much, now it's clearer. What I'd love to have from the js-ipfs-api is:

1. Direct encrypted messages between peers (like sendTo of ipfs-pubsub-room), how can I do that? libp2p dial?
2. An on ready event like the js-ipfs implementation has, how can I have something similar?
3. Discover the location of a node, even just at country level of precision. I know this can be done because the WebUI has a globe with positions of the nodes on it.
4. Are pubsub messages encrypted? Can I add a password to join a channel?

Bonus questions: 

1. Why does the js-ipfs node always have much less connections with swarm peers, compared with the go-ipfs node?
2. When will IPFS be production ready and pubsub stopping being just "experimental"?

**Comment by Stebalien** [comment]
> do you also have a chat or Slack

You can find us on the #ipfs channel on Freenode (IRC).

> ...

Let's move this to the forums or IRC. This looks like it's going to be a long discussion.

**Comment by sorleone** [comment]
@Stebalien Done, https://discuss.ipfs.io/t/how-can-i-send-and-receive-private-messages-with-js-ipfs-api/3637
