### ISSUE TITLE
Allow "Addresses.Gateway" / "Addresses.API" to be array (Allow gateway/api to listen on multiple addresses)

### ISSUE THREAD

**Issue by mkg20001** [ipfs/go-ipfs#5401]
#### Version information:

```
go-ipfs version: 0.4.17-
Repo version: 7
System version: amd64/linux
Golang version: go1.10.3
```

#### Description: Allow "Addresses.Gateway" / "Addresses.API" properties to be arrays (Allow gateway/api to listen on multiple addresses)

Currently it's only possible to make the gateway/API listen on one address only.

Instead both of these parameters should accept arrays to make it possible to for ex listen on `/ip6/::1/tcp/8080` as well.

**Comment by kjzz** [comment]
hey @Stebalien,if anyone work for this issue?if not,can i do for this?

**Comment by overbool** [comment]
@kjzz sorry, I'm fixing it.

**Comment by overbool** [comment]
@Stebalien this feature refers to go-ipfs-config, should modify it first?

**Comment by lgierth** [comment]
> this feature refers to go-ipfs-config, should modify it first?

Yes, and there's an fs-repo migration required, to do the string-to-array conversion in existing config files: https://github.com/ipfs/fs-repo-migrations -- best to coordinate with @kevina here

**Comment by lgierth** [comment]
Taken care of in #5532 and #5553
