### ISSUE TITLE
Error: leveldb/storage: corrupted or incomplete meta file

### ISSUE THREAD

**Issue by douglasmsi** [ipfs/go-ipfs#5402]
# version

**go-ipfs version: 0.4.17**

**repo version: 7**

**System version: 386/windows**

**Golang version: go1. 10.3**

## Description

After two weeks, my ipfs is present this error when I try started.

Error: leveldb/storage: corrupted or incomplete meta file. 

How can I fixed? 

Tks

**Comment by magik6k** [comment]
I haven't done that on windows, but can you try something like this (after installing python/pip):
```
> pip install leveldb
(cd into the .ipfs directory in your home dir)
> python
>>> import leveldb
>>> leveldb.RepairDB('./datastore')
>>> exit()
```

**Comment by Stebalien** [comment]
Alternatively, try building/installing the latest master. We now automatically recover corrupted leveldb databases.

**Comment by Stebalien** [comment]
Duplicate of: #4981

**Comment by douglasmsi** [comment]
Are there a solution for Windows? Just try building/installing from master?

Tks

**Comment by magik6k** [comment]
You can get binaries from ci - https://ci.ipfs.team/job/IPFS/job/go-ipfs/job/master/ (for windows you'll need to rename ipfs to ipfs.exe)

**Comment by douglasmsi** [comment]
I deleted the files and just started again the daemon. It's work.
