### ISSUE TITLE
Could We Enable Some Sort of Notificatoin On Jenkins Build Failures?  Please

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#5405]
Since it seams like CircleCI is going away would it be possible to enable some sort of notification on Jenkins build failures.

I realize email notifications are annoying not some but they are also extremely helpful, at least to me.  Otherwise I have to keep checking back on the status when a build fails and I often miss it.

Would it be acceptable to send email to just the `Committer` (not the `Author`) of any pushes as they are the one most responsible.  The way TravisCI handles notifications is annoying (email almost everyone responsible) but I like how CircleCI does it.

**Comment by magik6k** [comment]
cc @VictorBjelkholm

**Comment by VictorBjelkholm** [comment]
Opened this issue for it: https://github.com/ipfs/testing/issues/133
