### ISSUE TITLE
Bad headers from ipfs.io gateway

### ISSUE THREAD

**Issue by mitra42** [ipfs/go-ipfs#5407]
The https://ipfs.io gateway seems to have a new problem, I'm not sure if this is the correct place for it (since I believe its running go-ipfs). 

The headers from https://ipfs.io are breaking calls from the browser (current Chrome  68.0.3440.106). Specifically its doubling up some headers. Here is an example . ...
```
mitraglass:~ mitra$ curl -I https://ipfs.io/ipfs/zdj7WXBxVbxKozyeyTXSW6xujY5i78DMSrsq6GQZsZw4dQeTw
HTTP/2 200 
date: Wed, 29 Aug 2018 04:08:16 GMT
content-type: text/plain; charset=utf-8
content-length: 87
accept-ranges: bytes
access-control-allow-methods: GET
access-control-allow-origin: *
cache-control: public, max-age=29030400, immutable
etag: "zdj7WXBxVbxKozyeyTXSW6xujY5i78DMSrsq6GQZsZw4dQeTw"
last-modified: Thu, 01 Jan 1970 00:00:01 GMT
suborigin: ipfs000bafybeia2eunjb4kujnicecuwfq7bdug6kyso4jaha55rgcuux5mra4guqy
x-ipfs-path: /ipfs/zdj7WXBxVbxKozyeyTXSW6xujY5i78DMSrsq6GQZsZw4dQeTw
strict-transport-security: max-age=31536000; includeSubDomains; preload
access-control-allow-origin: *
access-control-allow-methods: GET, POST, OPTIONS
access-control-allow-headers: X-Requested-With, Range, Content-Range, X-Chunked-Output, X-Stream-Output
access-control-expose-headers: Content-Range, X-Chunked-Output, X-Stream-Output
x-cache: MISS
x-ipfs-pop: lb1.sjc

```
Specifically the double `access-control-allow-origin: *` is causing a Chrome error message
```
Failed to load https://ipfs.io/ipfs/zdj7WXBxVbxKozyeyTXSW6xujY5i78DMSrsq6GQZsZw4dQeTw: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'null' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by Stebalien** [comment]
Also cc @kyledrake.

This looks like a bug in the gateway config, not IPFS. Is that correct? Go deduplicates headers.

**Comment by parkan** [comment]
what is the `x-ipfs-pop` header? I can't find any reference to it

my guess would be that this is nginx sending extra headers

**Comment by parkan** [comment]
what is the `x-ipfs-pop` header? I can't find any reference to it

my guess would be that this is nginx sending extra headers, though it's also possible that this is behavior related to failing to deduplicate headers in mixed case

**Comment by lgierth** [comment]
Sorry about that, the Access-Control-* thing should be fixed since last night.

> what is the x-ipfs-pop header? I can't find any reference to it

This one is set in nginx and tells us which datacenter the request was handled by (PoP = Point of Presence). There's currently:

- fra / Frankfurt
- sjc / Silicon Valley
- nyc / New York Metro Area

**Comment by Stebalien** [comment]
Yep. Looks fixed to me.

**Comment by lgierth** [comment]
> tells us which datacenter the request was handled by

The other way to check this is a traceroute (or better: `mtr`)
