### ISSUE TITLE
Add file takes long time and concurrency in ipfs

### ISSUE THREAD

**Issue by beyonderyue** [ipfs/go-ipfs#5408]
#### Version information:

go-ipfs version: 0.4.15-
Repo version: 6
System version: amd64/linux
Golang version: go1.10.2
#### Type:

Enhancement
#### Description:

blocks: 15GB
datastore: 860KB
When I add a small file using ipfs add or java-ipfs-api, it will take over 20 seconds.
Why it take so long time?

And does ipfs support add files simutanneously? 
When I open 100 threads to add different files to ipfs, it will take long time.
 Can you give me some advice when using ipfs in concurrency situation?

**Comment by Stebalien** [comment]
This looks like https://github.com/ipfs/go-ipfs/issues/5221.
