### ISSUE TITLE
Ecosystem: please add and use consistently tagged releases

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/go-ipfs#5410]
Currently many modules have some (gx-)releases git tagged, and some don't. Often it is the case that newer ones are not tagged, with older ones being tagged. 

With the introduction of go modules in go 1.11 (also known as vgo) this becomes a real issue. As far as I can tell, the go module resolver uses git tags, if present and formatted accordingly, to determine the available versions. This creates an issue when trying to install some of the packages in the libp2p/ipfs ecosystem, as "latest" now means "last tagged release", which is not equal to actual "latest release". This is fixable by hand most of the time, fetching specific commits, but it would be much nicer to just make it work out of the box. 

From my understanding there are two things to do to resolve this

1. Manually/using a script, tag all releases in the various repos
2. Add auto tagging for gx releases, so this is consistent in the future: https://github.com/whyrusleeping/gx/issues/157

**Comment by Kubuxu** [comment]
As we introduced go modules https://github.com/ipfs/go-ipfs/pull/6038 we will tag consistently.
