### ISSUE TITLE
gateway overrides /version with information about IPFS

### ISSUE THREAD

**Issue by swedneck** [ipfs/go-ipfs#5422]
#### Version information:
0.4.17

#### Type:
Bug (probably)

#### Description:

When using a domain with a dnslink, any request to example.com/version will return information about the IPFS node running on the gateway, instead of potential information about the webapp's version.
Examples: https://riot.swedneck.xyz/version, https://https://docs.ipfs.io/version, http://explore.ipld.io/version

This breaks the version checking function of the Riot matrix client, which otherwise works perfectly via IPFS.

**Comment by lidel** [comment]
Thank you for reporting this @swedneck!

It sure looks like a bug: makes it impossible to expose asset named  `/version` when dnslink is used.
I suspect it is a legacy thing: these days version can be read via `/api/v0/version` call

Anyone familiar whats the story behind `/version`? Would it be ok to PR a fix removing it (at least when dnslink is in use)?

**Comment by Stebalien** [comment]
Yes, this does look like a bug. *Having* the version endpoint on the gateway isn't but it shouldn't be available when we pivot to a dnslink-based website.

**Comment by lgierth** [comment]
> but it shouldn't be available when we pivot to a dnslink-based website.

:+1: 

It's probably easy to fix by simply reordering the http handlers in https://github.com/ipfs/go-ipfs/blob/78a32f2e48db69a1d517da29121ef5a51b2a8015/cmd/ipfs/daemon.go#L543-L549 by moving `VersionOption` after `GatewayOption`.

**Comment by swedneck** [comment]
@lgierth I just tried compiling it with that change and it works!
