### ISSUE TITLE
Update IPFS Snap

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/go-ipfs#5423]
#### Version information:

```
go-ipfs version: 0.4.15-rc1-
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2
```

#### Type:

Update Request

#### Description:

Currently, the snap looks like this : 

```
channels:                           
  stable:    v0.4.14     (589) 11MB -
  candidate: v0.4.14     (589) 11MB -
  beta:      v0.4.14     (589) 11MB -
  edge:      v0.4.15-rc1 (696) 11MB -
```

However, the latest version is `0.4.17`. Snaps are damn convenient because they auto-update themselves, they're isolated from the system, and they fit *most* distros at once. It's easier to install, it allows for auto-completion, and has different release channels.

I'd suggest to anyone new to IPFS to install it using a package manager such as Snap Store instead of the barbarous ways of having random files lay around in the filesystem that's to be added to `$PATH` and doesn't allow for auto-completion nor auto-updates.

**Comment by Stebalien** [comment]
@lgierth any idea who maintains the snap?

**Comment by magik6k** [comment]
IIRC it's built from the release branch, so just pushing the release commit to it should do the trick (It seems to be as outdated as the snap - https://github.com/ipfs/go-ipfs/tree/release)

**Comment by Stebalien** [comment]
I tried that but I'm still not seeing a release.

**Comment by magik6k** [comment]
Oh, it's apparently packaged in https://github.com/elopio/ipfs-snap by @elopio

**Comment by elopio** [comment]
oh, sorry, the Travis builds died some time ago. I've just fixed it, basically updating to go1.11 and refreshing the apt repos. Now v0.4.17 is in the candidate channel.

I would apapreciate your help giving it a try. Maybe we can release to stable on Friday.

**Comment by Stebalien** [comment]
@ipfs/go-team anyone use Ubuntu?

**Comment by elopio** [comment]
Should work in other stuff too: https://docs.snapcraft.io/core/install

**Comment by elopio** [comment]
btw, you might find this interesting. It's the number of active devices with the snap installed.
![ekrankopio de 2018-09-13 11-11-30](https://user-images.githubusercontent.com/617831/45506206-ce843080-b74b-11e8-8640-ee07b7c24f81.png)

**Comment by Stebalien** [comment]
That explains the number of 0.4.15 users...

**Comment by elopio** [comment]
Not really. Travis broke before the final release of 0.4.15, so I never moved it to stable.
![screenshot from 2018-09-13 15-09-28](https://user-images.githubusercontent.com/617831/45516063-38f69a00-b767-11e8-94bb-abda704aa684.png)

**Comment by Stebalien** [comment]
Interesting...

**Comment by keks** [comment]
FWIW, snap still is at 0.4.14. @Stebalien did you try pushing another release after the snap was fixed?

**Comment by elopio** [comment]
@keks, are you on the candidate channel? I don't want to push it to stable and trigger updates for everybody before a little more testing.

**Comment by cimm** [comment]
A bit off topic but couldn't we add @elopio's IPFS snap to the main `go-ipfs` repository?

I was looking for the IPFS snap and there is nothing indicating this isn't an "official" snap. All links point to the main IPFS website, the snap name isn't prefixed with the maintainer's name, only the publisher name "elopio" looked off. It's not that I don't trust Leo, his name always shows up when looking for snap packages and I think he is deeply involved with the project but it would be cleaner if the snap was published by IPFS itself, wouldn't it?

Maybe the snap is not stable enough yet, fair enough, but we do have snap release channels for that. We don't need a separate repository, do we?

Don't take this the wrong way @elopio, my tinfoil hat always itches when I see a snap that's not maintained by the main project. You never know if it's still maintained and the upstream project might forget it even exists (the official IPFS documentation does not mention it for example).

**Comment by Stebalien** [comment]
This is both the official and *only* snap that I know of. If @elopio wants, I'd be happy to move it to the `ipfs` org but I'd like to keep it as a separate repo so @elopio can keep maintaining it. Note: @elopio's a member of the @snapcore organization.

Alternatively, maybe a note in the README would suffice?

**Comment by elopio** [comment]
@cimm I think everybody should know more their maintainers, what you are doing is very good.

I'm happy to transfer it to the official ipfs name if the team agrees this is a good idea. Or make it clearer that's a package maintained by the community, which is not a bad thing either. Just let me know what should I do.

For the record, I no longer work on snapcraft. Earlier this year I started working on a company that builds on Ethereum called @zeppelinsolutions, so I continued maintaining a few decentralization snaps that I like a lot, and I'm still a contributor to ubuntu.

And if you are curious about how the ipfs snap is built, take a look at https://github.com/elopio/ipfs-snap
Everything is automatically done by Travis. The only thing I do manually is to move it from candidate to stable after a week or so of testing.

pura vida.

**Comment by NatoBoram** [comment]
I'd just change `contact` from `https://github.com/ipfs/ipfs` to `https://github.com/elopio/ipfs-snap`, that ought to be enough :)

**Comment by elopio** [comment]
Done.

**Comment by Stebalien** [comment]
Let's leave it where it is for now. And thanks @elopio for maintaining it!

(closing because the actual issue has since been fixed)
