### ISSUE TITLE
error: rabin chunker parameter [min]

### ISSUE THREAD

**Issue by diwufeiwen** [ipfs/go-ipfs#5425]
Version information:

0.4.17

Type:

Bug (probably)

Description:
// QmZooytqEoUwQjv7KzH4d3xyJnyvD3AWJaCDMYt5pbCtua\chunker\chunker.go
func (c *Chunker) reset() {
	...
	c.pre = c.MinSize - windowSize
}
windowSize = 16,c.pre data type is uint64,when first enters,c.MinSize=[min],if [min]<16, --->c.pre<0,cause the file will not be  blocked.

Suggest:check the command line arguments:rabin-[min]-[avg]-[max], if min<16, return an error.

**Comment by Stebalien** [comment]
Correct, this is a bug.

**Comment by kjzz** [comment]
hey @schomatis @Stebalien , i want to fix this,because i want to know more about chuncker.WDYT?

**Comment by Stebalien** [comment]
Go ahead. It should be a relatively straight-forward fix.

**Comment by schomatis** [comment]
Thanks @kjzz! Let me know if you need any help.

**Comment by Stebalien** [comment]
Merged. We can keep this open till we update the dep here.

**Comment by kjzz** [comment]
@Stebalien Thx a lot,maybe i can add some test after go-ipfs-chunker publish new version.

**Comment by Stebalien** [comment]
The dep has been updated. @kjzz has submitted tests in #5449; we can close this once that gets merged.

**Comment by Stebalien** [comment]
Thanks @kjzz!
