### ISSUE TITLE
Include ability to download any content type via gateway port.

### ISSUE THREAD

**Issue by andrewheadricke** [ipfs/go-ipfs#5436]
Enhancement request:

There are lots of public IPFS gateways for read-only access to content uploaded in `file` format.. But it is not possible to access any other content like DAGs, custom objects, blocks etc from public gateways.

This means there is an incentive NOT to adopt any other formats apart from standard the standard file object, as its the only data accessible from public gateways.

If I could fetch DAGs, objects, blocks etc from public gateways, still read-only, then I would be inclined to use the newer DAG formats etc.

**Comment by Stebalien** [comment]
The gateway does, in fact, expose a read-only API (a subset of the normal API). I've just added some (very basic) documentation in #5437.
