### ISSUE TITLE
Key renaming to same name causes key to be deleted

### ISSUE THREAD

**Issue by rob-deutsch** [ipfs/go-ipfs#5450]
### Version information:
```
go-ipfs version: 0.4.17-dfd19c470
Repo version: 7
System version: amd64/darwin
Golang version: go1.10.3
```

### Type:
Bug

### Description:
Renaming a key to the same name causes an error and the key is deleted.

### Reproduction steps:
If you create a key called 'foo', and rename this key to 'foo', there is an error and it disappears:
```
$ ipfs key list
self
$ ipfs key gen foo --type=rsa --size=2048
QmcaW6t1MpTBh46GvkaTUA57kr9WcyFk8Fe6nkxQpWzGm5
$ ipfs key list
self
foo
$ ipfs key rename --force foo foo
Key QmcaW6t1MpTBh46GvkaTUA57kr9WcyFk8Fe6nkxQpWzGm5 renamed to foo with overwriting
$ ipfs key list
self
$
```

^--- My 'foo' key has disappeared :( :(

### Suggested fix:
This is slightly more involved because I think that fixing this issue should also involve changing some existing existing behaviour.

go-ipfs currently responds in the following two ways when a key is renamed to the same name:
```
$ ipfs key rename foo foo
Error: key by that name already exists, refusing to overwrite
$ ipfs key rename --force foo foo
Key QmcaW6t1MpTBh46GvkaTUA57kr9WcyFk8Fe6nkxQpWzGm5 renamed to foo with overwriting
!!!HORRIBLE ERROR!!!!
$ 
```

I would suggest that the behaviour of a same-rename without --force should be changed, and that the bug be fixed, so that the following happens:
```
$ ipfs key rename foo foo
Key QmcaW6t1MpTBh46GvkaTUA57kr9WcyFk8Fe6nkxQpWzGm5 renamed to foo
$ ipfs key rename --force foo foo
Key QmcaW6t1MpTBh46GvkaTUA57kr9WcyFk8Fe6nkxQpWzGm5 renamed to foo
$ 
```

The reason that I think the non-force behaviour should be changed is because nothing is actually being overridden when a key is renamed to the same name.

### Fixing:
Once you agree on a solution, If its okay with you I would like to fix this myself and submit a PR. I have identified the function question at [core/coreapi/key.go#L134](https://github.com/ipfs/go-ipfs/blob/master/core/coreapi/key.go#L134) and begun to implement a fix.

**Comment by Stebalien** [comment]
Both of those suggestions sound reasonable, go for it.

I'm less sure about allowing this command to succeed *without* force but that's probably fine. Looking at prior art, the posix `rename` syscall *always* succeeds if two files are the same while the `mv` command (on linux) always fails.
