### ISSUE TITLE
Object links command is broken on master branch

### ISSUE THREAD

**Issue by rob-deutsch** [ipfs/go-ipfs#5458]
### Version information:
````
go-ipfs version: 0.4.18-dev-
Repo version: 7
System version: amd64/darwin
Golang version: go1.10.3
````

### Type:
Bug

### Description:
My apologies, I don't know if I should be reporting bugs on the master branch, but I noticed that `ipfs object links` isn't working. See reproduction steps:

````
$ ipfs object get QmYhHUDK28dU5QJnMnPwGU8gCUxegdcA5LkHjNU1ikbwWY
{"Links":[{"Name":"bigfile","Hash":"QmSkLz9P64rK8gwPw9JWN8FDBkJEP2x5W48DFJ4JjVB2nr","Size":102424431},{"Name":"smallfile","Hash":"QmNnfArfVAabiCgQKeE2cNi7CfYScX5BgHyvNRdJUSWehB","Size":61}],"Data":"\u0008\u0001"}
$ ipfs object links QmYhHUDK28dU5QJnMnPwGU8gCUxegdcA5LkHjNU1ikbwWY
01:19:33.729 ERROR   cmds/lgc: expected type *objectcmd.Object, got objectcmd.Object command.go:41
$
````

**Comment by overbool** [comment]
@rob-deutsch I can't reproduce your bug, did you do anything else

**Comment by rob-deutsch** [comment]
Weird! I can't replicate it either now!

Closing for now on the assumption that I did something silly without realising.

**Comment by Stebalien** [comment]
No, this is a bug that only happens when the daemon is in offline mode.

**Comment by rob-deutsch** [comment]
Thanks @Stebalien!
