### ISSUE TITLE
a question about data transmittion

### ISSUE THREAD

**Issue by qipx0033** [ipfs/go-ipfs#5463]
Hi experts, I wonder that how could I get content in the node behind a Symmetric NAT. I get two ipfs nodes. One node A has public IP while the other node B is behind a symmetirc NAT. After I put a file in B, I could get the file from B. How it works? Thank you.

**Comment by Stebalien** [comment]
Please ask questions like this on https://discuss.ipfs.io/ (helps us keep the issue tracker tidy).
