### ISSUE TITLE
Handle `ipfs object diff` error

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#5468]
https://github.com/ipfs/go-ipfs/blob/e4e35047bd338029fd2c4ff25c71bc6cccc35bf3/core/commands/object/diff.go#L76-L95

The error generated by the `Diff()` function is being ignored and we're silently failing here, e.g.,

```
IPFS=$(echo "IPFS" | ipfs add --raw-leaves --chunker size-1 -Q)
IPFA=$(echo "IPFA" | ipfs add --raw-leaves --chunker size-1 -Q)
ipfs object diff $IPFS $IPFA
# It prints nothing, giving the impression the objects are the same (which they are not).
# It should print "ERROR: expected protobuf dag node".
```

**Comment by schomatis** [comment]
@overbool Wanna take this one?

**Comment by schomatis** [comment]
BTW, one thing I'm not understanding about Go: it doesn't complain about the unused `err` variable even though it is being redefined, so it is in fact (from my understanding) a new variable. If I rename it to `newErr` it *does* complain, but redefining a new variable with an already used name (`err`) seems fine even if it's not used. @Stebalien What am I missing?

**Comment by overbool** [comment]
@schomatis, Yeah, i will try my best to finish this task, Thx.

**Comment by overbool** [comment]
@schomatis I am willing to do it, thx.
