### ISSUE TITLE
Add support for raw leaves in `ipfs object diff`

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#5470]
See https://github.com/ipfs/go-ipfs/issues/4687#issuecomment-417511872.

**Comment by overbool** [comment]
@schomatis I am fixing this issue

**Comment by overbool** [comment]
@schomatis could you help me review my pr in https://github.com/ipfs/go-ipfs/pull/5472?

**Comment by schomatis** [comment]
On it.

**Comment by overbool** [comment]
@schomatis The `ipfs object` is not very uniform currently, because `ipfs object diff` support the `RawNode` but `ipfs object get` doesn't.

Is there any planning on refactoring these commands?

**Comment by schomatis** [comment]
> Is there any planning on refactoring these commands?

Not really, they are going to be replaced by the `ipfs dag` commands, you could raise another issue to discuss adding support for raw nodes for the entire `ipfs object` command set, but I'm sure we could use your help with a lot of other more relevant issues. That being said, if you're interested in doing it as a way to learn more about how `go-ipfs` works under the hood go for it, just know that we don't plan on supporting these commands much longer (although time is largely a relative concept here :)
