### ISSUE TITLE
TestExternalUnmount fails unmounting ipns

### ISSUE THREAD

**Issue by rob-deutsch** [ipfs/go-ipfs#5475]
### Version information:
go-ipfs version: 0.4.18-dev-
Repo version: 7
System version: amd64/darwin
Golang version: go1.10.3

### Type:
Bug

### Description:
Reproduction steps:

````
~/go/src/github.com/ipfs/go-ipfs#  cd fuse/node/
~/go/src/github.com/ipfs/go-ipfs/fuse/node# go test
--- FAIL: TestExternalUnmount (0.09s)
	mount_test.go:83: exit status 1
FAIL
exit status 1
FAIL	github.com/ipfs/go-ipfs/fuse/node	0.150s
~/go/src/github.com/ipfs/go-ipfs/fuse/node# 
````

The reason it fails is the following process:
1. [mount_test.go#L45](https://github.com/ipfs/go-ipfs/blob/master/fuse/node/mount_test.go#L45) creates an offline node: `node, err := core.NewNode(context.Background(), nil)`
2. [mount_unix.go#L78](https://github.com/ipfs/go-ipfs/blob/master/fuse/node/mount_unix.go#L78) will only create the ipns node if its an online node: `if node.OnlineMode() {`
3. [mount_test.go#L90](https://github.com/ipfs/go-ipfs/blob/master/fuse/node/mount_test.go#L90) tries to unmount ipns: `err = node.Mounts.Ipns.Unmount()`
4. Of course, this attempt fails

Also, this test is written for Linux only, it won't work on macOS.

I'm working on a fix now

**Comment by keks** [comment]
> I'm working on a fix now

Thanks :) Feel free to ping me if you need help or guidance.

**Comment by rob-deutsch** [comment]
PR #5476 submitted :)
