### ISSUE TITLE
'ipfs pin rm', 'ipfs block rm', 'ipfs repo gc' is not responding

### ISSUE THREAD

**Issue by zyhiang** [ipfs/go-ipfs#5489]
#### Version information:

go-ipfs version: 0.4.14
Repo version: 6
System version: amd64/debian
Golang version: go1.11

#### Type:

bug or intended?

#### Description:

My ./ipfs/block folder has a size of 1T and does not respond after executing the title command. The maximum time is twelve hours.

**Comment by magik6k** [comment]
Did you try restarting the daemon (to make sore that nothing is holding the GC lock)?

**Comment by c3rv3au** [comment]
Yes I did.

**Comment by c3rv3au** [comment]
Problem persist on 2 of my nodes.

**Comment by ninkisa** [comment]
Hello c3rv3au,

have you found a solution?
I'm facing the same issue. ipfs is up but all comands are hanging

ipfs version 0.4.21
ipfs repo verify is passing

I'm attaching the pprof profile

[ipfs_pprof.zip](https://github.com/ipfs/go-ipfs/files/3481517/ipfs_pprof.zip)

**Comment by Stebalien** [comment]
I've filed a new issue that precisely describes the problem: https://github.com/ipfs/go-ipfs/issues/6562
