### ISSUE TITLE
IPFS does not work after upgrade

### ISSUE THREAD

**Issue by timthelion** [ipfs/go-ipfs#5499]
#### Version information:
```
> ipfs version --all
go-ipfs version: 0.4.17-
Repo version: 7
System version: amd64/linux
Golang version: go1.10.3
```
#### Description:
After upgrading to the latest version of IPFS, it does not work. If I go to any ifps or ipns link in the browser I see: `Cannot GET /ipns/Qme48wyZ7LaF9gC5693DZyJBtehgaFhaKycESroemD5fNX/post/putting_this_blog_on_ipfs/`.

Note: the hash changes based on the content ;)

Note 2: I did not test immediately before the upgrade. I test IPFS every now and then to see if it has gotten fast enough to be usable and I upgrade immediately every time I try it out again. This time there was some kind of repo migration done.

**Comment by rob-deutsch** [comment]
Hey, could you jump over to the command line and try:

`ipfs get /ipns/Qme48wyZ7LaF9gC5693DZyJBtehgaFhaKycESroemD5fNX/post/putting_this_blog_on_ipfs/`

This ought to give more information about what's gone wrong.

**Comment by timthelion** [comment]
That works, which lead me to realize what the problem is, and it's not a bug in ipfs-go at all, but rather ipfs-companion in chromium. The companion is redirecting me to the port 8080 (where node.js runs), when my ipfs gateway is on port 9001.
