### ISSUE TITLE
Using ipfs dht to store key and value pair

### ISSUE THREAD

**Issue by nadendlaprasad** [ipfs/go-ipfs#5519]
I would like to use **ipfs dht** to store {key,value pair}.  
for example:   ipfs dht put "key1" "hello"
  Here **key1** is the key which stores the value **hello**                                             
But, As per my understanding, to store {key,value} pair using **ipfs dht put**  key must have the valid key type. I see the only available keystype as **ipns** . Is it possible to create custom key type ? If yes could you please share the documentation link.

i also tried to store {key,value} pair using ipns keytype and I am facing an issue while executing the following command 

```
>ipfs dht put -v /ipns/k1 hello
record could not be unmarshalled
```

Is the above error message makes sense? If yes could you please let me know what's wrong

**Comment by nadendlaprasad** [comment]
@overbool  Thanks for your reply. Is there anyway to create a custom keytype ? Like for example i want to create a keytype called **hello**

**Comment by overbool** [comment]
As far as i know, `ipfs dht put` only supports `/ipns` key type currently.

**Comment by nadendlaprasad** [comment]
can we expect this feature in the coming versions? 

I mean allowing the users to create a keytype of their own and using the DHT functionality to persist {key,value} pair across the nodes

**Comment by Stebalien** [comment]
Rather late but...

The issue here is security. The DHT is basically a world-writable key-value store so we need some way to _validate_ values in the DHT.

We are (slowly) working towards a more pluggable DHT where you'll be able to create sub-dhts for new key types but it's going to be a while before that lands.

(closing as that work is currently being discussed here: https://github.com/ipfs/notes/issues/291#issuecomment-414495124, https://github.com/libp2p/research-dht/pull/8)

**Comment by susarlanikhilesh** [comment]
How to create a key with ipns type? so that I can use dht put command. I looked for examples but couldn't find. 
Any help is appreciated. 

Thank you

**Comment by aschmahmann** [comment]
@susarlanikhilesh questions about how to use IPFS (as opposed to bug reports or feature requests) are best asked on discuss.ipfs.io as it makes the information more visible then posting on closed GitHub issues.

You can use libraries like go-ipns (https://github.com/ipfs/go-ipns) to create IPNS records. However, you're likely better off just doing `ipfs name publish --key=mykey /ipfs/Qmxyz`. Again if you have more questions about this ask on discuss and feel free to tag me.
