### ISSUE TITLE
Switch to the new iptb

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#5521]
We have a new iptb version with a changed API. Somebody needs to go through and update all invocations of `iptb` in our test cases to use this new API.

**Comment by Stebalien** [comment]
@ipfs/go-team who wants this? It's not exactly a glorious task but we need to get it done.

**Comment by bigs** [comment]
commenting to follow this issue, as i'll be doing similar stuff for libp2p

**Comment by Stebalien** [comment]
@travisperson I know you're busy, but could you make this happen? We have to cut an off-master point release of iptb every time we release because we're stuck on 1.0.

**Comment by travisperson** [comment]
@Stebalien Ya I can update this. I have a branch that has most of the sharness tests updated already from a while back. Let me rebase it, update anything new and I'll open a PR.

**Comment by Stebalien** [comment]
Awesome! Doesn't that depend on https://github.com/ipfs/iptb/pull/91?

**Comment by travisperson** [comment]
Yes. Down the road I want to move the plugins out of the main iptb project. At the moment thought that is a bit difficult due to packages conflicting due to gx. That should be fixed this quarter though so for now they will stay there.

**Comment by travisperson** [comment]
Fixed in https://github.com/ipfs/go-ipfs/pull/5636
