### ISSUE TITLE
Better support for /dnsaddr/ (i.e. in swarm connect)

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipfs#5522]
#### Version information: 

master

#### Type:

Enhancement

#### Description:

It should be possible to do `ipfs swarm connect /dnsaddr/something`. Right now it doesn't attempt to resolve and throws `Error: invalid peer address: invalid IPFS address`

**Comment by overbool** [comment]
It seems the same problem like https://github.com/ipfs/go-ipfs/issues/5249.

Maybe we should resolve the dns address before `swarm connect`.

**Comment by overbool** [comment]
@hsanjuan `Error: invalid peer address: invalid IPFS address` implies that the `addr` is invalid ipfs address, because it misses `tcp` and `ipfs` protocol. I try `ipfs swarm connect /dnsaddr/xxx/tcp/4001/ipfs/Qmxxx` in my bash, it print `connect Qmxxx success`.

**Comment by hsanjuan** [comment]
@overbool you are confusing `/dns4` or `/dns6` with `/dnsaddr` (common mistake), but they are different. `/dns4` resolves domain to `/ip4/<ip>`. `/dnsaddr` resolves multiaddress from `_dnsaddr` TXT field associated to the domain.

**Comment by overbool** [comment]
@hsanjuan You are right. I've confused `/dns4` with `/dnsaddr`.

**Comment by overbool** [comment]
It seems the same issue https://github.com/ipfs/go-ipfs/issues/5249. 
Maybe we should resolve `addr` before connecting.

**Comment by Stebalien** [comment]
@overbool that one is for the `--api` flag (that's how we tell the IPFS client which daemon it should connect to).

@hsanjuan we'll have to think about a better way to do https://github.com/multiformats/go-multiaddr-dns/blob/78f39e8892d4f8c5c9f18679cc06d0b40ecab8cf/resolve.go#L167

Basically, when we resolve a dnsaddr, we match the *final* component to try to pull out the right ones. In theory, this allows us to have *multiple* distinct peers with the same hostname. In practice, this is kind of arbitrary. Any solution that tries to solve this issue will also have to solve that.

Note: there are also security concerns but I'm not *that* concerned. If the user doesn't specify a peer ID, they have no reason to believe we'll end up connecting to the right peer (they haven't told us which one to use).

**Comment by hsanjuan** [comment]
Ok, two problems here.

The first is the one triggering the issue. `connect` commands parses with https://github.com/ipfs/go-ipfs-addr/blob/master/ipfsaddr.go#L72 and this errors when the given address does not have an `/ipfs/` part, before resolving it.

The second is related domain resolution as mentioned. Thing works with empty trailers (no `/ipfs/peer` part in the original multiaddress, my usecase), or otherwise it seems the trailer needs to match the one defined in the dnslink.

That makes some current bootstrap peers (https://github.com/ipfs/go-ipfs-config/blob/master/bootstrap_peers.go#L20), problematic. Since the `_dnsklink` for bootstrap.libp2p.io contains `/ipfs/Qm...` parts, the bootstrap peer `/dnsaddr/bootstrap.libp2p.io/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN` doesn't resolve at all because the peer ids don't match (empty).

But the second problem should not affect me if I just want to run `ipfs swarm connect /dnsaddr/cluster.ipfs.io` because this domain provides the full address, peer included (just like bootstrap.ipfs.io).

**Comment by overbool** [comment]
@Stebalien Did you mean that we should append an addr with new pid(`ipfs/Qmnewpeerid`) when the trailer doesn't match the resolved dnsaddr?

https://github.com/multiformats/go-multiaddr-dns/blob/78f39e8892d4f8c5c9f18679cc06d0b40ecab8cf/resolve.go#L167

**Comment by overbool** [comment]
@Stebalien If we only solve this issue without considering `resolveDnsaddr`  improvement currently, I had made a pr https://github.com/ipfs/go-ipfs/pull/5535. Could u help me review it?
