### ISSUE TITLE
ipfs p2p listen and foward should show actual port when listening on 0

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipfs#5523]
#### Version information:

 master
#### Type:

Enhancement

#### Description:

`ipfs p2p forward` and `ipfs p2p listen` commands take a listen-address or a target address. It works with `/ip4/127.0.0.1/tcp/0` but `ipfs p2p ls` does still show 0 instead of the actual port it bound to (which should be a random available one). This can only be discovered with `lsof` or similar (I think).

Ideally, `p2p ls` should list the bind-address with the actual port.

**Comment by Stebalien** [comment]
We could also just set `laddr` to that address (and/or not even store it?). However, we need to make sure we can tell which forwarders were created with dynamic ports and which weren't (see: https://github.com/ipfs/go-ipfs/issues/5460#issuecomment-424817513).

**Comment by overbool** [comment]
@Stebalien Should ` target address` in `ipfs p2p listen` accept `0` port?  I don't think it makes sense here.

**Comment by hsanjuan** [comment]
Ah yes, for `p2p listen`  it doesn't make sense. Only for `listener` local addresses.

**Comment by hsanjuan** [comment]
Also, launching two `forward` with a `/tcp/0` shows `listener already registered`.
