### ISSUE TITLE
`ipfs p2p forward` should accept full multiaddresses as target (not only /ipfs/<peerID>)

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipfs#5524]
#### Version information: 

master

#### Type:

Feature

#### Description:

`ipfs p2p forward` takes an `*/ipfs/<peerID>` multi-address as target. ~~This assumes the given peer is routable.~~

However, sometimes it would be useful to do `ipfs p2p forward <proto> /dnsaddr/mypeer`  ~~or `ipfs p2p forward <proto> /ip4/1.2.4.5/tcp/23131/ipfs/<peerID>`~~. In these case, the command should ~~automatically add the peer addresses to the peerstore so that they can be connected (right now, a manual `swarm connect` is required in advance).~~ resolve the addresses.

~~This simplifies connecting to libp2p peers which are not part of the ipfs network or, particularly, the ipfs dht.~~

**Comment by magik6k** [comment]
If no one grabs this soon, I'll do that in a spare moment

**Comment by kjzz** [comment]
Hey @magik6k ,  can i help you do for this?i am interested in this.

**Comment by kjzz** [comment]
Hey @magik6k @Stebalien ,  can i help you do for this?I am interested in this issue.

> sometimes it would be useful to do ipfs p2p forward <proto> /dnsaddr/mypeer or ipfs p2p forward 
   \<proto> /ip4/1.2.4.5/tcp/23131/ipfs/\<peerID>

Can you explain it for me?

And as i known, we can use command `ipfs p2p forward /x/_testing /ip4/127.0.0.1/tcp/4567 /ip4/127.0.0.1/tcp/23131/ipfs/<peer id>` and `ipfs p2p forward /x/_testing /ip4/127.0.0.1/tcp/4567 /dnsaddr/bootstrap.libp2p.io/ipfs/<peer id>` to connect right now.

**Comment by hsanjuan** [comment]
@kjzz you're right, it already takes a full multiaddress and adds it to the peerstore before forwarding so that should work. What doesn't work is resolving `/dns*/` first. Sorry for the confusion here.

**Comment by kjzz** [comment]
Thx for replying @hsanjuan , so you mean that we should support command such as `ipfs p2p forward /x/_testing /ip4/127.0.0.1/tcp/4567 /dnsaddr/bootstrap.libp2p.io`? 
And before forwarding , we should use resolve all multiaddrs?Then add it to peer store?

**Comment by hsanjuan** [comment]
@kjzz yes, in principle, but we have some discussion about how painful it is to manually resolve in several places etc. https://github.com/ipfs/go-ipfs/pull/5535#issuecomment-425597268 maybe hold off a bit, as ideally this should be taken care of directly at libp2p-level.
