### ISSUE TITLE
Improve performance on low bandwith / Reduce extra bandwidth usage

### ISSUE THREAD

**Issue by mkg20001** [ipfs/go-ipfs#5534]
#### Version information:

```
go-ipfs version: 0.4.17-
Repo version: 7
System version: amd64/linux
Golang version: go1.10.3
```

#### Description:

Currently I'm using IPFS on a connection that has about 400 kBit/s down and 100 kBit/s max, though values are usually much lower because it's a shared one.
Downloading files on IPFS is next to impossible, even after setting ConnMngr.HighWater/LowWater to 20/10 and adding the source node as bootstrap peer.
Would it be possible to somehow minimize the amount of "extra" bytes that need to be transferred (e.g. SECIO Handshake, DHT, etc) to a minimum?
Is there a config that would achive this? Would this require some code changes?

**Comment by eingenito** [comment]
It's actually one of our most critical areas of active development. The prominent related issues are probably https://github.com/ipfs/go-ipfs/issues/3786, https://github.com/ipfs/go-ipfs/issues/5037, https://github.com/ipfs/go-ipfs/issues/4396 etc..

One thing you can try (if you're connected directly to the providing peer) is mentioned here: https://github.com/ipfs/go-ipfs/issues/5037#issuecomment-393478197.

There are other important DHT chattiness improvements under discussion: https://github.com/libp2p/go-libp2p/issues/436

Running with the server profile as described here: https://github.com/ipfs/go-ipfs/issues/5013#issuecomment-389910309 may also help cut down on chattiness; I'm unsure about that.

**Comment by eingenito** [comment]
Hey @mkg20001 - I'm going to close this issue, not because it's solved or anything but just because it's covered in a lot of other roll-up issues. It's also referenced from all the issues above now. Feel free to reopen if you have additional questions or information. Thanks.
