### ISSUE TITLE
IPNS Publishing: crypto/rsa: message too long for RSA public key size

### ISSUE THREAD

**Issue by postables** [ipfs/go-ipfs#5536]
#### Version information:
ipfs version 0.4.17

#### Type:
Bug

#### Description:
Attempting to publish IPNS Records with RSA Keys fails due to the following error:
```
Error: crypto/rsa: message too long for RSA public key size
```
This is not effecting any of my ED25519 keys, as can be seen by the succesful publishing of a record signed by an [ed key](https://cloudflare-ipfs.com/ipns/12D3KooWSev8mmycrPbCMs4Awe4AFGkUQKPh7CTuifh51U8iFEr8). 

Initially I thought this bug was strictly related to my project as can be seen by the bug report I opened up (https://github.com/RTradeLtd/Temporal/issues/204). This caused me to attempt to reproduce the issue via the command line. I was able to replicate the issue across my two IPFS nodes:

```
Primary Node

rtrade@ipfs-node-1:/var/log/temporal$ ipfs name publish --key=postables-4096 /ipfs/QmYA2fn8cMbVWo4v95RwcwJVyQsNtnEwHerfWR8UNtEwoE
Error: crypto/rsa: message too long for RSA public key size

Secondary Node:

rtrade@ipfs-node-2:~$ ipfs name publish --key=postables-4096 /ipfs/QmYA2fn8cMbVWo4v95RwcwJVyQsNtnEwHerfWR8UNtEwoE
Error: crypto/rsa: message too long for RSA public key size
```

**Comment by Stebalien** [comment]
That's not the issue. IPNS doesn't use the `Encrypt` method (really, it should be removed).

@postables Are you *sure* you're not using a really tiny key? This happens to me when I use a 64bit key.

**Comment by postables** [comment]
@Stebalien that's a very good question! the keys *should have* been generated with a bitsize between 2048-4096.

I'll double check and make sure I'm not accidentally generating keys that are too small

**Comment by postables** [comment]
@Stebalien You were correct! I tried with a fresh key:
```
rtrade@ipfs-node-1:/ipfs/keystore$ ipfs key gen -t rsa -s 4096 rsatest
...
rtrade@ipfs-node-1:/ipfs/keystore$ ipfs name publish --key=rsatest /ipfs/QmYA2fn8cMbVWo4v95RwcwJVyQsNtnEwHerfWR8UNtEwoE
Published to QmdL4nwg3cLdXjveTMPRy2uDxAwmvHGyAZDfKQpZvzGgMQ: /ipfs/QmYA2fn8cMbVWo4v95RwcwJVyQsNtnEwHerfWR8UNtEwoE
```

And it worked, looks like the issue is with my key generation. Thank you.
