### ISSUE TITLE
Hangs while fetching an non existing hash

### ISSUE THREAD

**Issue by rohitkhatri** [ipfs/go-ipfs#5537]
When I try to fetch any non existing hash with `ipfs get` command like the below:

```
ipfs get QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa
```
It just hangs.

I'm using private network using own swarm key.

Here's how I have setup my network:

```
ipfs init
ipfs bootstrap rm --all
ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8091
ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
ipfs-swarm-key-gen > ~/.ipfs/swarm.key
export BOOTSTRAP_PEER_ID=$(ipfs id -f="<id>")
ipfs bootstrap add /ip4/127.0.0.1/tcp/4001/ipfs/${BOOTSTRAP_PEER_ID}
export LIBP2P_FORCE_PNET=1 && ipfs daemon
```

**Comment by magik6k** [comment]
It's not really possible to know that a chunk of data doesn't exist on the network, so ipfs just keeps looking for it indefinitely.

For a workaround, there is a `--timeout` flag on all commands, so you can specify that for example `get` should fail after some amount of time:
```
ipfs get QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa --timeout=60s
```

**Comment by rohitkhatri** [comment]
@magik6k Thanks for replying, and what If the file is longer and takes time to download, will that work without timeout option?

**Comment by magik6k** [comment]
No, timeout applies since command start. I don't think there is any built-in way to do that, but you can try creating a utility which tracks `get` output and aborts it if it takes too long to process some item.

This could be implemented as `--read-timeout` flag on `ipfs get` command quite easily

**Comment by eingenito** [comment]
There is another command you can run to look up content in the DHT (as a distinct step from fetching the content) and that would be `ipfs dht findprovs hash --timeout=60s`. 

If that command fails to return any hashes of peer records (which are subsequently used to lookup qne actually connect to providing peers), you've failed to find any mention of the content in the DHT. If it does successfully return hashes of providers then you know that at some point some peers advertised themselves as providing the content. And that your `get` is failing further along the process.

**Comment by Stebalien** [comment]
@magik6k can you file that suggestion as a new issue (trying to see if we can replace "I have a problem" issues with "Implement feature X" issues to make the issue tracker easier to track).

**Comment by Stebalien** [comment]
Closing for tracking in favor of #5541. @rohitkhatri feel free to ask followups (or ask for this to be reopened).
