### ISSUE TITLE
MFS: unable to remove malformed nodes

### ISSUE THREAD

**Issue by djdv** [ipfs/go-ipfs#5538]
I managed to add an invalid node to MFS and was unable to remove it.
I added it via something similar to this
```go
mfs.PutNode(APINode.FilesRoot, "/bad-node", new(dag.ProtoNode))
```
trying to remove it via `ipfs files rm /bad-node` results in
>Error: proto: required field "Type" not set

and the file remains in the MFS listing.

I'm not sure if `PutNode` should check validity before put-ing, or if `rm` should account for these kinds of things.

**Comment by schomatis** [comment]
> I'm not sure if `PutNode` should check validity before put-ing,

It should.



> if `rm` should account for these kinds of things.

I'm not sure why this corrupted node would cause the error during the remove operation (it might be related to the MFS directory caching mechanism), I would expect that the modification (unlink) happened only at the (valid) parent directory without caring for the integrity of the child. Could you post a simple example to reproduce the error please?

Also, stop corrupting MFS @djdv!! :rofl:

**Comment by djdv** [comment]
>Could you post a simple example to reproduce the error please?

This should be all that's needed. If I start with a fresh repo `ipfs init`, and make that API call on an instance of it, then try to `rm` that path, it fails with that error.

Something like this should work (with proper imports and adding to commands root).
But I don't want to test it right now 👀 

```go
var CorruptCmd= &cmds.Command{
	Helptext: cmdkit.HelpText{
		Tagline:          "Corrupts MFS, for when you need to",
	},
	Run: func(req *cmds.Request, res cmds.ResponseEmitter, env cmds.Environment) error {
		node, _ := cmdenv.GetNode(env)
		mfs.PutNode(node.FilesRoot, "/bad-node", new(dag.ProtoNode))
		return errors.New("MFS corrupted")
	}

}
```


>Also, stop corrupting MFS @djdv!!


Y̨o̱ű h̡aͦv́e̽ m᷀ŷ͓ ẉo̝r̮d̈́ t͊h̩e̡r͉e̛ w̯i̗l̅l͡ b̢eͤ n͝o̮ m͜o͕rͯe͊ cͅo̅r͍ȑu͒p̮t͓i̕oͪnͪ

**Comment by schomatis** [comment]
@overbool Do you want to take a look here? We need to find the source of the error and understand which check is failing during the addition.

**Comment by overbool** [comment]
@schomatis ok, I'm interested at it.

**Comment by overbool** [comment]
> mfs.PutNode(APINode.FilesRoot, "/bad-node", new(dag.ProtoNode))

`proto.Unmarshal` causes the error `Error: proto: required field "Type" not set`, because the node is a empty `ProtoNode` that doesn't contain `data`. https://github.com/ipfs/go-mfs/blob/master/dir.go#L154.

I think we should check validity before `PutNode`, WDYT? @schomatis

**Comment by schomatis** [comment]
So, it turns out there's a not-very-well-documented `-r` flag that works more like a `--force` flag,

https://github.com/ipfs/go-ipfs/blob/e93aa25e9746894700886ce4213d5ac423f85758/core/commands/files.go#L1053-L1055

removing the link without checking the integrity of the node it points to. It makes sense (following the Unix API) that the `rm` command needs to know *what* it is removing (thus the node needs to be valid) to avoid removing an entire directory (without the `-r` specified). Then, a couple of things:

1. Yes, let's add a check before inserting *any* node in MFS, @overbool could you submit a PR in MFS to that end?

2. We need to improve the documentation of this `-r` flag, and maybe even evaluating changing its behavior: even if removing recursively don't allow removing invalid nodes (unless a new flag, `--force`, is specified), let me sit on that a bit and open a new issue.

3. In the meanwhile, @djdv (thanks for reporting this by the way) could you check if the `-r` flag solves your particular corruption scenario?

**Comment by overbool** [comment]
@schomatis You are right, `-r` can solve this issue.

**Comment by djdv** [comment]
>even if removing recursively don't allow removing invalid nodes (unless a new flag, --force, is specified)

Agreed.

>In the meanwhile, @djdv (thanks for reporting this by the way) could you check if the -r flag solves your particular corruption scenario?

It appears so.
I thought I had tried this, but I guess not. Since the target was a "file", I must not have considered recursive removal. Or assumed it would also error out.
Strange behaviour imo. Would much rather see an explicit `force`-like flag here.

**Comment by overbool** [comment]
According to your discussion, i have summarized the following four modifications:

1. add the `force` flag to remove anything else (including file, directory, corrupted node, etc).
2. add a check before inserting any node in MFS
3. `-r` flag doesn't allow removing invalid nodes(maybe we should add a check before removing recursively).
4. update our document about `-r` flag.

WDYT? @schomatis @djdv 

If you are agreeing with me, I will finish https://github.com/ipfs/go-ipfs/pull/5555 and fix https://github.com/ipfs/go-mfs/issues/15

**Comment by schomatis** [comment]
Agreed!

> 3. (maybe we should add a check before removing recursively).

The check is done implicitly (and should be documented better) when the child is requested to check if it's a file or a directory,

https://github.com/ipfs/go-ipfs/blob/master/core/commands/files.go#L1069

because MFS will decode the node to classify it and add it to the cache.

**Comment by djdv** [comment]
Agreed.
Just to be clear
>including file, directory

Are we saying that `force` should remove directories even when `-r` is not provided?
I'm fine with either, just want to make sure.

**Comment by schomatis** [comment]
> Are we saying that `force` should remove directories even when `-r` is not provided?

Yes, I mean, it's kind of implied in the logic. Using `--force` would mean "I'm just removing the link, I'm not checking anything, I don't even care what it points to: file, directory, corrupted node, nothing". That should be clearly documented.

**Comment by djdv** [comment]
Closed by: https://github.com/ipfs/go-ipfs/pull/5555
