### ISSUE TITLE
Forbid RSA keys smaller than 2048

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#5543]
We should forbid generating RSA keys smaller than 2048. We can just generate ed25519 keys when testing.

@alanshaw: How will this affect the interoperability tests? Do we need to add a `--i-understand-i-am-generating-an-insecure-key=true` escape hatch?

See #5536.

**Comment by kjzz** [comment]
Hey @Stebalien , i have a question about this.If someone generate a rsa key offline(i mean that they use other tools to generate rsa key) by themselves and add this in `.ipfs/config`,how can we forbid this situation?

**Comment by Stebalien** [comment]
In general, users are free to do what they want. The only limit I'd like to impose here is a UX limit: prevent users from *accidentally* generating insecure keys.

**Comment by kjzz** [comment]
Do you mean that we should add some flag when we use `ipfs key gen` such as `--i-understand-i-am-generating-an-insecure-key=true`(maybe another name will be better)?

**Comment by Kubuxu** [comment]
I've run a quick benchmark and `ipfs init` with 1024 and 2048. In an average of 100 runs, 1024 is 3.9 times faster than 2014 (0.0869 vs 0.335 seconds).

This might be useful in case of tests (where we are currently using it).

**Comment by Stebalien** [comment]
@kjzz yes. Although I intentionally picked `--i-understand-i-am-generating-an-insecure-key=true` I want it to be unreasonably long.

@Kubuxu, reminds me that we *also* need to apply this to `ipfs init`.

---

Let's hold off on implementing this for now. I'd like to get feedback from JS land and I'm not sure I want that flag to actually show up in the help.

**Comment by bertrandfalguiere** [comment]
related: #6751

**Comment by alanshaw** [comment]
> @alanshaw: How will this affect the interoperability tests? Do we need to add a --i-understand-i-am-generating-an-insecure-key=true escape hatch?

js-ipfs can generate 2048 keys. Tests will take slightly longer. Tests where we're explicitly generating 1024 bit keys will fail, and we can fix that when it happens.

I'm happy to just forbid RSA keys smaller than 2048. If users make a lot of noise or if it effects the tests in a _really_ adverse way _then_ I'd consider adding an escape hatch.
