### ISSUE TITLE
Running a command locally (not on daemon)

### ISSUE THREAD

**Issue by rob-deutsch** [ipfs/go-ipfs#5547]
I'm experimenting with go-ipfs, and I want to add a command just for my experiments.

The thing is, that I want this command to run only on the client (NOT on the daemon, even if there is a daemon). A bit like how `ipfs version` operates.

How do I do this with the new `go-ipfs-cmds.Command` structure?

**Comment by eingenito** [comment]
@rob-deutsch - there may well be a better way, but one trivial way of launching code exclusively on the client is to put your logic in the `PreRun` function (which executes in the command line process) rather than the `Run` function which executes (via http API) on the daemon. You can see the details here: https://github.com/ipfs/go-ipfs-cmds/blob/master/http/client.go#L93

**Comment by rob-deutsch** [comment]
Thanks for the response @eingenito, but it doesn't look like `PreRun` allows for any output to be sent to the console?

Should I just `fmt.Print` from within PreRun?

**Comment by eingenito** [comment]
Yep, I think so. I've never written a command, but I think that's what the existing commands do. They basically marshall the data coming back from the http API request and then output the formatted results to stdout. No different from what you're proposing.

**Comment by kevina** [comment]
@rob-deutsch there are better ways than just using PreRun. All it takes is an entry in the `cmdDetailsMap` in `cmd/ipfs/ipfs.go`, this will work for any command.  Or am I missing something?

**Comment by eingenito** [comment]
Oh neat - that is way better @rob-deutsch. Please ignore my answer; as @kevina points out there's already a facility for marking a command as needing to run on the client. And it does some important setup work beforehand. You can see an example here: https://github.com/ipfs/go-ipfs/blob/78b8e6e0a402c560f1cf7c2246a24de0e2f86e98/cmd/ipfs/ipfs.go#L93. 

Thanks @kevina.

**Comment by eingenito** [comment]
Yep - thanks for commenting @kevina.
