### ISSUE TITLE
Add a `--force` flag for `ipfs files rm`

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#5554]
At the moment the `-r` is acting also as `--force`: in the case the file (node) we're trying to remove is corrupt it will just unlink without caring what it is unlinking (file, directory, corrupted node, etc); see https://github.com/ipfs/go-ipfs/issues/5538#issuecomment-426312110. The `-r` should only allow to remove valid directories and the new `--force` flag should allow to remove anything else.

This would imply changing the API, some users might already rely on this side effect of `-r` but seems subtle enough to modify it without breaking much. @magik6k WDYT?

**Comment by overbool** [comment]
@schomatis OK
