### ISSUE TITLE
How does pubsub discover other subscribers?

### ISSUE THREAD

**Issue by klueq** [ipfs/go-ipfs#5569]
go-ipfs uses DHT to do that. But how exactly does it do that? And what's the most efficient way to make a well-connected sub-network (aka overlay network) where all the nodes hold the same unique 256 bit value. Would it be the pubsub mechanism?

**Comment by vyzo** [comment]
It puts a block, which causes a call to `Provide`; the CID is the synthetic (`floodsub:+topic`).

In general, if you want to use the DHT for rendezvous, just make up a key from the topic name, hash it to get a CID and call `Provide` on the DHT.
To discover other peers, use the same synthetic key with `FindProviders`, at which point you can connect to some of them.

Note that we are working on a new mechanism for discovery using rendezvous; see https://github.com/libp2p/specs/pull/56

**Comment by klueq** [comment]
Is the DHT API in go-ipfs available for getting/setting arbitrary key/values? I remember notes about that it's restricted to only IPNS-related stuff.

Do I get it right that the peer discovery process consists of the two steps:

- The 1-st node uses `dht.set(topic)` and the `topic` key ends up physically stored on a few nodes chosen by the Kademlia algorithm.
- The 2-nd node uses `dht.get(topic)` to discover the nodes who store this key and then somehow finds out the id of the 1-st node, who stored the `topic` hey.

Is it possible that in the 2-nd step `dht.get(topic)` discovers a few nodes, but none of them store the value given by the 1-st node, so the two nodes don't discover each other? This would explain why I'm not seeing anything published to the `chat` topic.

**Comment by klueq** [comment]
Are those connectivity issues debuggable? Logs, etc.

**Comment by vyzo** [comment]
Sure, you can use the dht api (`ipfs dht ...`) to find providers and you an try connecting with `ipfs swarm connect`.
The only difficulty is that you'll have to compute the cid by hand (but you can write some code to do that).

**Comment by klueq** [comment]
IIRC, `ipfs dht` doesn't allow arbitrary keys: only the `ipns` ones.

**Comment by vyzo** [comment]
`ipfs dht findprovs` takes a cid, not a key.

**Comment by klueq** [comment]
I think I now get the idea: those who want to form an overlay network with id `foobar123`, compute the cid of the file with this content (this is the output of `echo "foobar123" > temp.txt && ipfs add temp.txt`) and ask the ipfs network to find peers who have this file (this is same as trying to download it with `ipfs get`). That's very smart.
