### ISSUE TITLE
[Docker] Dockerfile says switch to a non-privileged user but actually dont.

### ISSUE THREAD

**Issue by nicolashomble** [ipfs/go-ipfs#5572]
#### Description:

Hi,

In Dockerfile you say "# Create the fs-repo directory and switch to a non-privileged user." but actually, you dont switch to user ipfs(1000). Default user after starting the container stay root. Don't you miss a "USER ipfs" instructions after 

ENV IPFS_PATH /data/ipfs
RUN mkdir -p $IPFS_PATH \
  && adduser -D -h $IPFS_PATH -u 1000 -G users ipfs \
  && chown ipfs:users $IPFS_PAT

 ?

I'm new to docker, perhaps i'm worng but i don't see any switch between root and a non-privileged user.

Anyway, thank you for this image ;)

Regards,
Nicoals

**Comment by rob-deutsch** [comment]
Hi Nicolas, I think that ipfs _is_ run as a non-privileged user. This is handled by the [`container_demon`](https://github.com/ipfs/go-ipfs/blob/c96373e80e10442bc4aa444181330223398edcc4/bin/container_daemon) script which is [renamed to `start_ipfs`](https://github.com/ipfs/go-ipfs/blob/c96373e80e10442bc4aa444181330223398edcc4/Dockerfile#L46) in the Docker container.

You can confirm this as follows:

````
$ ps aux | grep ipfs
root     21370  0.0  0.0   4188   192 ?        Ss   Oct08   0:01 /sbin/tini -- /usr/local/bin/start_ipfs daemon --migrate=true
1000     21527  2.8  7.1 389032 287344 ?       Sl   Oct08  33:16 ipfs daemon --migrate=true
$ 
````

**Comment by nicolashomble** [comment]
Hi Rob,
You are right, like i said, i'm new to docker and i didn't see the difference between daemon started as ipfs inside the container and the default user when i run a docker exec -it [container] /bin/sh command.

It's crystal clear now ;)

Thank you
