### ISSUE TITLE
Concern Regarding Code Quality of Badger

### ISSUE THREAD

**Issue by david1371** [ipfs/go-ipfs#5578]
My Posts will be deleted on badger repository. So posting it here, since you guys use badger.

Badger team did changes on May 9th to introduce move keys.
https://github.com/dgraph-io/badger/commit/7af00762e98cf59c2ca6a774b49487b8903257c6

There were many bugs, issues related to same thing which were fixed over months. The last fix was done a week back. The issues ranged from badger being stuck in recursive loop during get to badger not returning data which was inserted.

https://github.com/dgraph-io/badger/commit/d1185f0eb43dffb2fab28767ed0e184e5ce4d284
https://github.com/dgraph-io/badger/commit/af99e5f9ec18aca5d8ff40d2cfd909f7d21f392d
https://github.com/dgraph-io/badger/commit/d055ef4c2a32cc8197a0ca7513b24b59326921b5
https://github.com/dgraph-io/badger/commit/3340933a01945fb517775a0e0f079a701d04f094
https://github.com/dgraph-io/badger/commit/2e3a32f0ccac3066fb4206b28deb39c210c5266f

@manishrjain How do you plan to address the code quality of badger.

**Comment by schomatis** [comment]
Based on our [code of conduct](https://github.com/ipfs/community/blob/master/code-of-conduct.md) I'm closing this issue.

This is the same user that has been aggressively submitting issues on the Badger camp. Although some of the technical points raised may be valid this is certainly not the way to discuss them. Any integrity related problems found in the Badger code should be reported in a responsible way respecting the point of view of its core developers. From my personal experience interacting with the Badger folks, and @manishrjain in particular, any problems we had found while using the database have been promptly acknowledged and, if necessary, fixed.
