### ISSUE TITLE
private network: how to revoke/refuse an unauthorized node?

### ISSUE THREAD

**Issue by bo-liu** [ipfs/go-ipfs#5579]
The requirement is use IPFS setup a private network,  with a central authority center control which nodes can join or should quit after a period of time.

Current private work have the limitation:
1) Anyone can join the private network from a node(by copy the swarm.key) instead of a central authority center?
2) How to force some nodes quit the private network?

**Comment by Stebalien** [comment]
> Anyone can join the private network from a node(by copy the swarm.key) instead of a central authority center?

Yes.

> How to force some nodes quit the private network?

You'd have to:

1. Create a new swarm key.
2. Distribute it to the nodes you want to *keep* in the private network.

---

Basically, the current private network architecture is designed for centrally controlled private clusters and has very limited scope and functionality.

**Comment by bo-liu** [comment]
Got it, thank you!
