### ISSUE TITLE
Swarm Connect failure when trying to connect two nodes I control

### ISSUE THREAD

**Issue by obo20** [ipfs/go-ipfs#5588]
#### Version information:
go-ipfs version: 0.4.17-
Repo version: 7
System version: amd64/darwin
Golang version: go1.10.3

#### Type:
Bug

#### Description:
I'm trying to manually connect two ipfs nodes together via IPFS swarm.

On the first node, I get:
Error: connect (my node ID) failure: dial attempt failed: <peer.ID XXXXXX> --> <peer.ID YYYYYY> dial attempt failed: context deadline exceeded

On the second node, I get:
Error: connect (my second node ID) failure: dial attempt failed: failed to dial <peer.ID XXXXXX> (default failure)

This is happening 100% of the time without fail, and is turning into a pretty big issue for me, as attempting to pin via "ipfs pin (hash) -r" when I'm not directly connected between the two nodes seems to be bugged as well.

**Comment by leerspace** [comment]
For anyone else who comes across this, I think this is the same issue as what's being discussed in [this discourse thread](https://discuss.ipfs.io/t/ipfs-dht-cant-seem-to-find-anything-correctly/4037).

**Comment by vyzo** [comment]
Are your peers in different networks and behind NAT/firewalls?

**Comment by obo20** [comment]
@vyzo the peers are both on digital ocean, and they're behind no NAT.

They are behind firewalls, but these two peers have all TCP ports open right now for testing purposes.

**Comment by Stebalien** [comment]
If you run `ipfs dht findpeer YYYYYY` on peer XXXXXX, what do you get?

**Comment by obo20** [comment]
It turns out while there was no firewall issues on Digital Ocean's networking side, there was an unintentional firewall that was set up on ubuntu. By running "sudo ufw allow 4001" on each of the nodes, the issue was fixed.
