### ISSUE TITLE
Multibase PeerIDs

### ISSUE THREAD

**Issue by magik6k** [ipfs/go-ipfs#5589]
Currently we can't encode ipns names with Base32, we should try finding a way to do that.

**Comment by kevina** [comment]
I think this is outside of the scope of the case32cid1 work.  Is there a pressing need for this outside of familiarity?

**Comment by magik6k** [comment]
Yep, it's outside the cid-b32 work, just wanted to start the discussion

**Comment by Zolmeister** [comment]
duplicate: https://github.com/ipfs/go-ipfs/issues/5287
