### ISSUE TITLE
Cost of updating many small keys in Badgedb?

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#5593]
One of the arguments against storing pinning information as part of an inode () is the cost of largescale updates.

This issue is to get a handle on the cost.  If nothing us to document it.

@eingenito  idea of not having to update every block when a pin is updated may help make this less important,

**Comment by Stebalien** [comment]
@magik6k is this a known issue with badger?

**Comment by magik6k** [comment]
Cost of updating keys should be roughly the same as just writing new ones, so that's not really an issue. The issue is GCing old versions (afaik updates to keys just leave old versions behind to be GCed).

**Comment by Stebalien** [comment]
Got it. That should be fine given that https://github.com/ipfs/go-ds-badger/issues/54 has been fixed.

**Comment by Stebalien** [comment]
Got it. That should be fine given that https://github.com/ipfs/go-ds-badger/issues/54 has been fixed.
