### ISSUE TITLE
catch ctx.Errs and prettify for users

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#560]
```
> ipfs cat <hash>
context deadline exceeded
```

is not user friendly. worse when it happens on the web:

![](http://ipfs.benet.ai:8080/ipfs/QmUpRpppQ1YcLuVxnWNKE4wtps5UvcvCgwcSEc1NTdwu4G/ctx.png)  

btw, o/  that is AFAIK, the first ipfs-hosted image embedded in github

**Comment by whyrusleeping** [comment]
image link is broken, so much for the permanent web ;)

this would be really nice to have though, its an ugly error

**Comment by eingenito** [comment]
Closing - I think this behavior has changed since.
