### ISSUE TITLE
Add slash for dir in `ipfs files ls`

### ISSUE THREAD

**Issue by overbool** [ipfs/go-ipfs#5601]
We can get the follow result using `ipfs files ls`:

```
dir-a
dir-b
a
b
c
```

Is this a good advice that add the slash for directory to distinguish directory from file?

just like the follow:
```
dir-a/
dir-b/
a
b
c
```

**Comment by Stebalien** [comment]
We can but, unfortunately, this will force us to fetch the first block of every file to resolve the type. However, I don't think this'll be that much of an issue in practice, especially for MFS. This is *also* what `ipfs ls` does so we should probably just mirror that.

Thoughts @schomatis?

**Comment by schomatis** [comment]
We could add the slash when using the `-l` flag which already fetches that information,

https://github.com/ipfs/go-ipfs/blob/9bf4e4145ea897ced2f9aa2087296b3beda6e941/core/commands/files.go#L456-L460
