### ISSUE TITLE
Add templating to `ipfs config show`

### ISSUE THREAD

**Issue by abitrolly** [ipfs/go-ipfs#5603]
#### Version information:
Output From `ipfs version --all`:
```
$ ipfs version --all
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
go-ipfs version: 0.4.18-dev-9bf4e41
Repo version: 7
System version: amd64/linux
Golang version: go1.11
```
#### Description:

I'd like to get value of `Datastore.Path` from `ipfs config show` with a single command.  The best way would be using [JMESPath](http://jmespath.org/tutorial.html) for that:
```
ipfs config show --query Datastore.Path
```
Took it from here:
https://flyingzumwalt.gitbooks.io/decentralized-web-primer/install-ipfs/lessons/initialize-repository.html

**Comment by Stebalien** [comment]
Going through old issues...

We do support paths (`ipfs config Datastore.Path`). Unfortunately, `Datastore.Path` no longer exists as we've replaced it with a more comprehensive datastore config system (where one can compose multiple datastores).

**Comment by abitrolly** [comment]
@Stebalien so how can I find where IPFS stores content? My disk space is limited and I don't want to end up with locked system, because system disk is run out of space,

**Comment by Stebalien** [comment]
By default, it stores it in `~/.ipfs`. If the `$IPFS_PATH` variable is set, it stores it there.
