### ISSUE TITLE
Fixing leading k in variable names (via golint)

### ISSUE THREAD

**Issue by jurraca** [ipfs/go-ipfs#5608]
#### Version information:
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2

#### Type:
Enhancement

#### Description:
I've run `gometalinter` on the repo, and started fixing some linter errors such as having a leading k in variable names, for example https://github.com/ipfs/go-ipfs/blob/9bf4e4145ea897ced2f9aa2087296b3beda6e941/core/core.go#L334
 
Anyone oppose these variable names being fixed across the repo? Is there a philosophical objection to this naming in general? Happy to get cracking on the rest of the linter errors as well if that's helpful. Thanks.

**Comment by Stebalien** [comment]
Well, in this case, the leading `k` should be `key`. I'm guessing the lint was meant to catch something else. Unless they're glaring issues (missing documentation, bad code, etc.) I'd prefer *not* to make a ton of small changes all over the code as patches like that tend to introduce a bunch of merge conflicts.

However, feel free to *make* the PRs anyways, if they're not much work. We'll probably need to consider this on a case-by-case basis.
