### ISSUE TITLE
test more network topologies

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#561]
currently we have `3nodetest`, which has saved our butts many, many times.

@briantigerchow and I were discussing ratcheting up now, and trying a few others. Here's some ideas we were discussing. No need to do them all now (and we probably wont succeed yet), but can try a few.
- `cup`: 4 nodes, 2 bootstrap, 2 clients of different bootstrap nodes. add+cat from the clients.
- `star`: N (6?) nodes connected to a central bootstrapper. one peer adds a file, 2 others cat. take that one down, the rest cat. should all work just fine.
- `line` N (6?) nodes bootstrapped sequentially: `o->o->o->o->o` -- add + cat from first to last. should find each other with our bootstrapping logic.
- `semi-disjoint` N nodes, N/2 in two different clusters, with their own bootstrap.  `ipfs connect` a single node from one machine to the other. should all find each other "over time" (hard to know atm)
- `semi-disjoint-cat` same as above, but add some files to each cluster before connecting. then cat after connecting.
- `lifecycles` connect N (15?) nodes in a randomized topology (using 2-3 different bootstrap nodes). cycle some nodes in and out, all the while adding + cating files from different places.

**Comment by whyrusleeping** [comment]
might be good to have a test that simulates the current NAT issues we run into, i.e. have some nodes that cant be dialed to, but can dial out.

**Comment by whyrusleeping** [comment]
This is still relevant.

I made some helpful repos to aid in some of these things: https://github.com/whyrusleeping/testnet-utils

https://github.com/whyrusleeping/ipfs-network-tests

https://github.com/whyrusleeping/go-ctrlnet

**Comment by whyrusleeping** [comment]
closing, continuation of this work may be tracked in the ipfs/test-lab repo
