### ISSUE TITLE
Overlay Networks: DHT vs PubSub

### ISSUE THREAD

**Issue by klueq** [ipfs/go-ipfs#5619]
What's the best way to build overlay networks?

For example, 1% of the nodes want to join a sub-network and have its network id (a GUID). How can a new node discover a few other nodes with the same network id the most efficient way?

**Comment by Stebalien** [comment]
Unfortunately, the only way to do this right  *now* is to use `ipfs dht provide` and `ipfs dht findproviers`. Basically, you find nodes providing the "special" block. Eventually, we'd like to finish a "discovery" system (see https://github.com/libp2p/go-libp2p-discovery) for arbitrary rendezvous.

(closing as *technically* questions like this should be asked on discuss.ipfs.io; however, I'm answering it here as it's weird enough that you might not get a decent answer there)
