### ISSUE TITLE
Packaging go-ipfs for Guix

### ISSUE THREAD

**Issue by Ambrevar** [ipfs/go-ipfs#5621]
I'm trying to package IPFS for [Guix](https://guix.info).  It is similar to Nix in many aspects except that there is no network access at build time, so all dependencies must be fetched beforehand.
With other Go packages, it's perfectly fine because each "github.com/<user>/<package>" can be trivially packaged separately.  In the case of "gx"-paths however, it's not so trivial.

What would you people suggest?

My first clue would be to package "gx" and then package all "gx"-dependencies.
Something along those lines:
```sh
$ gx init
$ gx import --local Qm...
```
and then package the resulting `gx/ipfs/Qm` path.

Any better idea?

**Comment by lanzafame** [comment]
@warpfork thoughts?

**Comment by magik6k** [comment]
There is a make target to generate source tarball:
```
make go-ipfs-source.tar.gz
```

Does that work for you?

**Comment by Ambrevar** [comment]
It works from my user session but not for a Guix package declaration since there is no network access, unless all dependencies (the "gx/ipfs/Qm...") are already packaged in which case `go build` won't need network.

**Comment by Stebalien** [comment]
Sorry for the delay, going through old notifications.

We actually publish source packages at `https://dist.ipfs.io/go-ipfs/v$VERSION/go-ipfs-source.tar.gz`. These *should* be entirely self contained so a guix package should be able to just fetch that as the input and build it.

**Comment by Ambrevar** [comment]
It worked beautifully, thanks for the tip!

**Comment by Stebalien** [comment]
What's the package name?

**Comment by Ambrevar** [comment]
go-ipfs! :)
