### ISSUE TITLE
Building with gx on different machines leads to different dependencies

### ISSUE THREAD

**Issue by postables** [ipfs/go-ipfs#5623]
#### Version information:
```
solidity@dark:~$ ipfs version --all
go-ipfs version: 0.4.17-
Repo version: 7
System version: amd64/linux
Golang version: go1.10.3
```

#### Type:
Bug

#### Description:
Building `go-ipfs` with `gx install --local --nofancy` for go-ipfs 0.4.17 on different machines is pulling in different dependencies.

Attempting to vendor my project https://github.com/RTradeLtd/Temporal on my machine via `make vendor` will result in incorrect dependencies being pulled in. Attempting to run `go vet` after will result in [these](https://gist.github.com/postables/ff76f52c59bf2b0487076bb253bcb73f) errors being displayed. The interesting thing to note is that my `git diff` will show a *ton* of changes, several thousand of them.

On the contrary, one of my contributors is able to build the project with `make vendor`, and their `git diff` won't show *any difference*.

I've tried off every branch in my project, including freshly downloading the entire repo. Anytime I try to re-vendor my project, go-ipfs doesn't get built properly by gx, and there are always missing dependencies that I can't seem to fix. 

This issue is quite new, and I don't recall having ran into this issue when I last ran `make vendor` earlier in the week.

**Comment by lanzafame** [comment]
I have experienced a similar phenomenon when attempting to gx a new third-party package, it ended up being an issue with how I had gxed some of it's dependencies, but I haven't experienced this ever with `go-ipfs`.

**Comment by hsanjuan** [comment]
@postables maybe it's github being broken since a few hours ago and returning different results when gx checks `lastpubver` ?

**Comment by lanzafame** [comment]
I think I had ended up with two versions of a transitive dependency. And
there was a bit of coin flip as to which gx choose the first time round and
then the second time it would be different/the one I wanted. Yeah I'm not
sure how having dep and gx vendoring of the same pkg but diff versions
would go...

**Comment by hsanjuan** [comment]
`gx deps dupes` should be empty. Otherwise that might happen.

**Comment by hsanjuan** [comment]
you need to install gx packages first (`gx install --global`)

**Comment by postables** [comment]
After running my makefile which i modified to use `gx install --global` I then went into `vendor/github.com/ipfs/go-ipfs` and ran `gx deps dupes`

```
solidity@dark:~/go/src/github.com/RTradeLtd/Temporal/vendor/github.com/ipfs/go-ipfs$ gx deps dupes
ERROR: package go-log (QmcVVHfdyv15GVPk7NrxdWjh2hLVccXnoD8j2tyQShiXJb) not found
```

**Comment by hsanjuan** [comment]
did you run `gx install --global` in the vendor ? go-ipfs is complaining it cannot find it's own dependencies (which are already re-written).

**Comment by postables** [comment]
Yup :confused:

**Comment by postables** [comment]
I tried this again with the `0.4.18` release and still ran into the same issue. I'm going to poke around a bit and try to resolve this.

**Comment by postables** [comment]
@hsanjuan It seems that [this](https://github.com/RTradeLtd/Temporal/blob/V2/utils/multihash.go) set of code is what's causing the issues. I removed it, and was able to vendor properly.

**Comment by hsanjuan** [comment]
@postables why do you have some deps rewritten and some deps not rewritten?

**Comment by postables** [comment]
@hsanjuan It's been awhile since I wrote that util, so my memory may be a little hazy however I believed it was because the dependencies that I was using through IPFS either didn't have the required functionality, or there were some conflicting package versions.

Do you think the issue is because I didn't rewrite the deps?

**Comment by hsanjuan** [comment]
> Do you think the issue is because I didn't rewrite the deps?

Probably? Those deps are part of the gx dep tree as well so I'm not sure what can happen when you have the same lib imported from two different places.

**Comment by postables** [comment]
Hmm okay, I'll poke around a bit, however I'll close this issue as it's resolved. Thanks :D
