### ISSUE TITLE
Swarm connect 2 nodes failed, but dht findpeer could find each other

### ISSUE THREAD

**Issue by larryatdatahearts** [ipfs/go-ipfs#5633]
Version information:
localhost:go-ipfs Larry$ ./ipfs version --all
go-ipfs version: 0.4.17-
Repo version: 7
System version: amd64/darwin
Golang version: go1.10.3

Type:
Bug

Description:
I'm trying to manually connect two ipfs nodes together via IPFS swarm. Those 2 nodes are behind NAT in 2 different home network.

On the first node, I get:
Error: connect (my node ID) failure: dial attempt failed: <peer.ID XXXXXX> --> <peer.ID YYYYYY> dial attempt failed: context deadline exceeded

On the second node, I get:
Error: connect (my second node ID) failure: dial attempt failed: failed to dial <peer.ID XXXXXX> (default failure)

I used dht findpeer and was able to find each other.

I did some research that NAT is supported. I am wondering how I could make the 2 nodes connected.

Thanks

Larry

**Comment by Stebalien** [comment]
At the moment, make sure you're nodes aren't firewalled (either locally or at the NATs). We *do* try to ask your router to forward a port for IPFS but it doesn't always work. You can also *explicitly* use a relay (https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#circuit-relay) but that's obviously not a great solution.

If you *can* configure your NATs, you could try manually forwarding ports.

We're working on an an auto-relay system to automatically enable relaying in situations like this but it's still a work in progress.

---

Closing as this issue isn't directly actionable. Feel free to ask followup questions.

**Comment by larryatdatahearts** [comment]
Thanks. 

Is there an instruction how to config the firewall? Which ports should be forwarded?

Larry

**Comment by Stebalien** [comment]
Assuming you're listening on the default port, you'll need to forward port 4001 (TCP). The actual process of forwarding your ports depends on your router.
