### ISSUE TITLE
Resolution commands rework

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#5635]
1. `ipfs name resolve` and `ipfs dns` should be recursive by default, the current behavior is a surprising foot-gun. We should consider just changing this as I'm sure it'll fix *significantly* more bugs than it causes.
2. `ipfs dns` should resolve up to the first non-dnslink path by default. It shouldn't return an *error* when it hits a non-dnslink path, it should just *return* that path.

I'd also like to return a partial result when we hit the recursion limit (along with the error) but that's less pressing.

---

Can anyone think of anything this would break?

@alanshaw, how will this affect JS? Is this doable?

@whyrusleeping any idea why we aren't recursive by default?

**Comment by lidel** [comment]
> Can anyone think of anything this would break?

:+1:  for recursive by default, but given the fact we expose both commands on our public gateways, we should also implement recursion limit, otherwise people can easily DOS us by requesting lookup for circular IPNS links.

cc https://github.com/ipfs/go-ipfs/issues/4293 and https://github.com/ipfs/go-ipfs/issues/4181 where Lars suggested limit:
> Agreed -- probably with a sensible recursion limit (10 or so), similar to what curl/wget would do for redirects. 

FYI wget follows up to 20 redirects by default:

> `--max-redirect=number` Specifies the maximum number of redirections to follow for a resource. The default is 20, which is usually far more than necessary. However, on those occasions where you want to allow more (or fewer), this is the option to use. 
> – https://www.gnu.org/software/wget/manual/html_node/HTTP-Options.html

**Comment by alanshaw** [comment]
Same for `ipfs.resolve`?

**Comment by alanshaw** [comment]
I've opened an issue on the interface repo so we can track this: https://github.com/ipfs/interface-ipfs-core/issues/377

**Comment by Stebalien** [comment]
I agree, a recursion limit is a must. @whyrusleeping didn't object and can't remember why we didn't make this recursive by default either.

Note: Users can *still* recursively resolve using `ipfs cat`, etc. so this shouldn't change much from a security standpoint.
