### ISSUE TITLE
Are Bitswap Sessions actually being used?

### ISSUE THREAD

**Issue by hannahhoward** [ipfs/go-ipfs#5640]
Possible Bug

It is not clear to me that in the current go-ipfs/master along with go-bitswap/master that any code in https://github.com/ipfs/go-bitswap/blob/master/session.go#L54 is being run.

Testing with the `cat` command, the call stack is as follows:
-- [api.Unixfs().Get()](https://github.com/ipfs/go-ipfs/blob/master/core/coreapi/unixfs.go#L136)
-- [api.core().getSession()](https://github.com/ipfs/go-ipfs/blob/master/core/coreapi/coreapi.go#L91)
-- [dag.NewSession()](https://github.com/ipfs/go-merkledag/blob/master/session.go#L16)
-- [dagService.Session()](https://github.com/ipfs/go-merkledag/blob/master/merkledag.go#L155)
-- [blockService.NewSession()](https://github.com/ipfs/go-blockservice/blob/master/blockservice.go#L115)

However, here's the issue -- to call bitswap sessions you would need to satisfy the branching condition on [line 117](https://github.com/ipfs/go-blockservice/blob/master/blockservice.go#L117)-- but you don't and instead it just returns the value at [line 125](https://github.com/ipfs/go-blockservice/blob/master/blockservice.go#L125)

@schomatis identified this issue in discussions of https://github.com/ipfs/go-bitswap/pull/8 in relation to that feature branch of `go-bitswap` but it appears to affect master as well. (and can't be fixed through updating go-ipfs-exhange-interface to 0.1.1 since `NewSession` in master in BitSwap just returns a Session struct)

Am I missing something? Or are we not getting the benefit of sessions we intend to get.

**Comment by whyrusleeping** [comment]
@hannahhoward I remember noticing this while we were meeting in LA, some interface changes seem to have snuck in there and broken things. This is fixed in https://github.com/ipfs/go-bitswap/pull/8/files (and a type assertion was added to ensure we don't break this in the future).

We should probably apply that fix independently.

**Comment by schomatis** [comment]
> This is fixed in https://github.com/ipfs/go-bitswap/pull/8/files

@whyrusleeping Where? (I mean, which line?)

**Comment by whyrusleeping** [comment]
@schomatis here: https://github.com/ipfs/go-bitswap/pull/8/files#diff-f2fccfb96064097b73fbe8eeae3703eeR70

And this assertion to ensure that it works: https://github.com/ipfs/go-bitswap/pull/8/files#diff-0e99f1e85b5e90e54545f9cf6d323debR33

**Comment by schomatis** [comment]
Oh, I understand, thanks. My original problem that @hannahhoward is citing was actually related to a version mismatch, not the interface change.

**Comment by hannahhoward** [comment]
@whyrusleeping + @Stebalien I am going to work on extracting the parts of that PR (tests + that fix) that we know we want into a seperate PR we can merge right away.

**Comment by Stebalien** [comment]
:heart:

**Comment by whyrusleeping** [comment]
@hannahhoward the way i put the commits together should make it pretty easy. I separated the 'adding tests' and the 'changing sessions' into separate commits.

**Comment by hannahhoward** [comment]
Will do. I'm in TN for a conference till tomorrow but will work on this Monday.
