### ISSUE TITLE
IPNS config parse error when only set RecordLifetime

### ISSUE THREAD

**Issue by S3bb1** [ipfs/go-ipfs#5641]
#### Version information:
go-ipfs version: 0.4.17-dfd19c4
Repo version: 7
System version: amd64/linux
Golang version: go1.10.3

#### Type:
Bug

#### Description:
When setting only the config "Ipns.RecordLifetime" and let the config "ipns.RepublishPeriod" empty (equals "") there is a parsing error ... in the code it seems that their is a wrong parsing of the values 

https://github.com/ipfs/go-ipfs/blob/7de79280bbd709e74604d5fc624ff98a7e4c5a89/core/core.go#L598

should this code equal d, err := time.ParseDuration(cfg.Ipns.RecordLifetime) ?

**Comment by Stebalien** [comment]
Yes. Thanks for catching this, this is a truly ancient bug.
