### ISSUE TITLE
Option to configure IPFS gateway to only serve files on disk

### ISSUE THREAD

**Issue by edsilv** [ipfs/go-ipfs#5644]
Could an option be added to limit the gateway to only serve files that are on disk? This is useful when you want an internal pinning and sharing service but don't want to act as a "full" gateway.

(I spoke to @jbenet about this at the recent London meetup and was advised to create an issue).

**Comment by Stebalien** [comment]
https://github.com/ipfs/go-ipfs/pull/4150 has been kicking around for a while and has recently seen some activity. We'll see if we can get it off the ground.

**Comment by BenLubar** [comment]
This is fixed by #5649
