### ISSUE TITLE
dht.SendMessage

### ISSUE THREAD

**Issue by lele012** [ipfs/go-ipfs#5652]
if the remote peer really don't response, dht.SendMessage wait too long. Sometimes , peer send message , it doesn't want wait the response , how to do  ?

**Comment by Stebalien** [comment]
That's a bug in [go-libp2p-kad-dht[(https://github.com/libp2p/go-libp2p-kad-dht), we should be obeying the context (although that's moderately difficult to do correctly). Please report a bug there.
