### ISSUE TITLE
Extensive use of PubSub may cause "out of memory" error

### ISSUE THREAD

**Issue by romikser** [ipfs/go-ipfs#5657]
#### Version information:
I am using go-ipfs as library for my project. Commit I'm using is b5bba2ce80f8f6cd7b268ade72ad670e1102ab54.

#### Type:
Bug

#### Description:
Our application extensively uses pubsub. Recently we've updated IPFS because of gossipsub and started using gossipsub in our project. After some time we've noticed that application crashes with goroutines count ~800000 and "out of memory" error. 

The crash happened when node tried to resolve IPNS during heavy pubsub messages exchange. We've noticed it and disabled ipnsps, which did help.

After that I started investigating the problem. For test purposes I've set up 3 nodes. Two were listening two different pubsub topics, and the third one extensively published to one of topics (every 10 milliseconds I picked topic randomly). After 10 seconds from node publishing to topics I tried to subscribe to another topic and crashed after some time. Judging by logs, the problem is announceRetry method getting called infinite number of times.

I didn't manage to reproduce this bug using floodsub, so maybe the problem is with gossipsub only. Also I didn't manage to crash when I published to one topic instead of two.

P.S. In logs "WE SHOULD CRASH" message is where I started subscribing to topic on sending node.

[Log.log](https://github.com/ipfs/go-ipfs/files/2519611/Log.log)

**Comment by vyzo** [comment]
Uh oh, do you mind opening an issue in https://github.com/libp2p/go-libp2p-pubsub?

**Comment by Stebalien** [comment]
Can you post the output of `curl 'http://localhost:5001/debug/pprof/goroutine?debug=2'` after memory starts building up (you shouldn't have to wait that long).

**Comment by vyzo** [comment]
Are you using validators by any chance? It's the one thing that spawns goroutines in the pubsub implementation.

**Comment by romikser** [comment]
> Uh oh, do you mind opening an issue in https://github.com/libp2p/go-libp2p-pubsub?

I am using in as part of IPFS. I though it would be to start discussion here, because it may be a problem of pubsub configuration used in IPFS.



> I don't think announce retry is the culprit; this creates a short-lived goroutine, which reschedules a new instance of itself if it fails. So there should be only one goroutine active retrying to announce at any given time.
> The basic issue is that you are sending too fast and overflowing the send buffers; perhaps we should make these buffers configurable.

I'm not sure about the exact reason of bug. But in my logs I can see like a 100000 of routines calling announceRetry. And, as I understand, it's announce called by announceRetry start all of these routines.



> Can you post the output of `curl 'http://localhost:5001/debug/pprof/goroutine?debug=2'` after memory starts building up (you shouldn't have to wait that long).

Yeah, I need a bit of time. But I think I can do it today.



> Are you using validators by any chance? It's the one thing that spawns goroutines in the pubsub implementation.

I'm using gossipsub configuration provided by IPFS, I don't add any custom validators. I see that IPFS uses some record validator, maybe it is the problem

**Comment by vyzo** [comment]
> I am using it as part of IPFS. I though it would be better to start discussion here, because it may be a problem of pubsub configuration used in IPFS.

Sure, let's find out what is causing it first -- and if it is indeed a pubsub bug.

> But in my logs I can see like a 100000 of routines calling announceRetry after 30 seconds of running. And, as I understand, it's announce method called by announceRetry starts all of these routines.

This certainly is a bug if it is happening.

**Comment by vyzo** [comment]
So looking at the announce retry code, it is buggy as it starts a goroutine to retry if any of the peers fail (instead of having a peer-specific retry).
Still, not sure it justifies 100k goroutines.

**Comment by romikser** [comment]
Added log produced by debug/pprof/goroutine?debug=2. Here I got 96000+ routines calling announceRetry. It's after ~30 seconds of running. If I hadn't stopped the process, the number of routines would have continued to grow.

[log.txt.zip](https://github.com/ipfs/go-ipfs/files/2524493/log.txt.zip)

**Comment by vyzo** [comment]
I am working on a fix, I think the footgun is the loop retrying to send announces to all peers instead of just the peer that failed.

**Comment by romikser** [comment]
@vyzo sounds great! Let me know, it you need any help.

**Comment by vyzo** [comment]
we'll need some help testing it, this should be fast to merge and bubble up.

**Comment by romikser** [comment]
Works much better now. The number of routines grows, but it stops at ~5000-6000 and even decreases after some time. Tested it with heavier loads, works great too.

**Comment by vyzo** [comment]
Excellent, thank you for spotting this!

**Comment by vyzo** [comment]
The fix is bubbling up in #5688.

**Comment by Stebalien** [comment]
(fixed)
