### ISSUE TITLE
ipfs repo verify is single threaded

### ISSUE THREAD

**Issue by baryluk** [ipfs/go-ipfs#5696]
```
go-ipfs version: 0.4.18-rc1-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1
```

`ipfs repo verify` takes ages (hours) on big repos, and it only is using single core/thread on my machine.

**Comment by Stebalien** [comment]
Fixed by @chenminjian. @baryluk, can you try out the latest master?
