### ISSUE TITLE
Unexpected X-Chunked-Output in /api/v0/version response

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#5711]
#### Version information: 
0.4.18-rc1-f0bf99361

#### Type: 
Bug

#### Description:

**TL;DR** response headers for `/api/v0/version`  include _unexpected_ `X-Chunked-Output: 1` which breaks response parser in js-ipfs-api. 

It is very  likely caused by the same codepaths as https://github.com/ipfs/go-ipfs/issues/4721

> ## :anger:  go-ipfs v0.4.18-rc1 + js-ipfs-api v26.1.0 
> 
> Due to bogus header in go-ipfs response js-ipfs-api thinks the payload is a stream, so it creates a stream object from it internally which has no attributes of expected names, producing `undefined` values for end user:
> ![2018-10-31--22-55-36](https://user-images.githubusercontent.com/157609/47821364-bc446d00-dd60-11e8-8bd5-7453cc54dcf1.png)
> 
> Response headers include unexpected `X-Chunked-Output: 1`:
> ```
> HTTP/1.1 200 OK
> Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
> Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
> Content-Type: application/json
> Server: go-ipfs/0.4.18-rc1
> Trailer: X-Stream-Error
> Vary: Origin
> X-Chunked-Output: 1
> Date: Wed, 31 Oct 2018 21:47:29 GMT
> Transfer-Encoding: chunked
> ```

Example of correct  response (previous  version):

> ## :ok:  go-ipfs v0.4.17 + js-ipfs-api v26.1.0 
> 
> ![go-ipfs-version-ok-2018-10-31--21-47-31](https://user-images.githubusercontent.com/157609/47819232-2ad1fc80-dd5a-11e8-89dd-d185ce721b92.png)
>
> Response headers:
> ```
> HTTP/1.1 200 OK
> Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
> Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
> Content-Type: application/json
> Server: go-ipfs/0.4.17
> Trailer: X-Stream-Error
> Vary: Origin
> Date: Wed, 31 Oct 2018 21:47:14 GMT
> Transfer-Encoding: chunked
> ```
> 

Just for the record, js-ipfs (also ok):

> ## :ok: js-ipfs v0.32.3 + js-ipfs-api v26.1.0 
> 
> ![js-ipfs-version-ok-2018-10-31--21-47-31](https://user-images.githubusercontent.com/157609/47819012-864fba80-dd59-11e8-876c-7be6aabb855d.png)
> 
> Response headers:
> ```
> HTTP/1.1 200 OK
> access-control-allow-headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
> access-control-expose-headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
> vary: origin,accept-encoding
> content-type: application/json; charset=utf-8
> cache-control: no-cache
> content-encoding: gzip
> Date: Wed, 31 Oct 2018 21:52:50 GMT
> Connection: keep-alive
> Transfer-Encoding: chunked
> ```
>

**Comment by magik6k** [comment]
Already fixed in https://github.com/ipfs/go-ipfs/pull/5697
