### ISSUE TITLE
refused connection when use ipfs p2p

### ISSUE THREAD

**Issue by katmai1** [ipfs/go-ipfs#5720]
I trying create a tunnel ipfs between 2 remote nodes but always refused connection

NODE A
ipfs config --json Experimental.Libp2pStreamMounting true
ipfs p2p listener open p2p-test /ip4/127.0.0.1/tcp/9999

NODE B
ipfs config --json Experimental.Libp2pStreamMounting true
ipfs p2p stream dial PEER_ID_NODE_A  p2p-test /ip4/127.0.0.1/tcp/9999

The last command always return a connection refused

**Comment by Stebalien** [comment]
The latest release (0.4.18) should be available on https://dist.ipfs.io/#go-ipfs. You shouldn't need to compile from source.

**Comment by katmai1** [comment]
works with 0.4.18, but I need connect peers manually with command 'ipfs swarm connect /p2p-circuit/ipfs/SERVER_PEER_ID'
