### ISSUE TITLE
Remove MessageTextMarshaler once its no longer needed

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#5722]
To avoid dead code.

Its in `core/commands/root.go.`

**Comment by overbool** [comment]
@kevina This might have to wait https://github.com/ipfs/go-ipfs/pull/5659 is merged

**Comment by kevina** [comment]
@overbool correct, i posted this si we would not forget about it.  If one of your p.r. removes the last usage of the function fell free to remove it, otherwise we can do it in a separate p.r.
