### ISSUE TITLE
go-ipfs should have a link to the web UI on "ipfs daemon" cmd output

### ISSUE THREAD

**Issue by momack2** [ipfs/go-ipfs#5727]
The web UI is awesome! We should link people to it in the output text when they start up a daemon via the "ipfs daemon" command. Concretely, let's add a link to http://127.0.0.1:5001/ipfs/QmSDgpiHco5yXdyVTfhKxr3aiJ82ynz8V14QcGKicM3rVh/#/ to easily see their peers and node status in the web UI.

**Comment by dtkav** [comment]
I'm brand new to go, and excited about ipfs so I took a crack at this one. Hope that's alright!

**Comment by momack2** [comment]
Thanks Daniel! No prob. =]
