### ISSUE TITLE
0.4.18 webui resources

### ISSUE THREAD

**Issue by andrewheadricke** [ipfs/go-ipfs#5732]
I just installed the latest IPFS 0.4.18 and noticed something odd.  When loading the new webui in the browser, CPU usage jumps to 75%-100%, and network traffic also jumps massively from like less than 100KiB per second to like 1.5MiB sec, both incoming and outgoing go up.

When I close the webui, the CPU usage and network consumption both fall back to normal levels.

Any reason why it would behave in such a way?

**Comment by magik6k** [comment]
This is most likely the geoip database, which queries the network for each peer, conecting to more peers in the process. I'm not sure if there is much we can do here other than generally optumizing go-ipfs. I'd recommend openning an issue in https://github.com/ipfs-shipyard/ipfs-webui
