### ISSUE TITLE
Link struct is not good

### ISSUE THREAD

**Issue by thomas92911** [ipfs/go-ipfs#5742]
Type: Etc

1. Link struct is fixed,  name, size, cid,  Unable to expand
2. The basic file system cannot be expanded
3. Each ipld project is not compatible, because data read/writer

Suggest:
Link struct change to Link Interface, like Node Interface,  all from rawdata decode.
Increase scalability，reduce the difference in implementation of ipld

**Comment by kevina** [comment]
We are redoing the unixfs to address this issue and more.  See https://github.com/ipfs/unixfs-v2
