### ISSUE TITLE
filestore documentation should mention the daemon needs to be restarted

### ISSUE THREAD

**Issue by BenLubar** [ipfs/go-ipfs#5746]
#### Version information:
```
go-ipfs version: 0.4.18-6f19dd5
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1

(using the Docker Hub image from ipfs/go-ipfs)

docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

Docker version 18.06.1-ce, build e68fc7a
```

#### Type:
Task

#### Description:
Running this command:
```
ipfs config --json Experimental.FilestoreEnabled true
```
is not enough; the error message will still be shown when running `ipfs filestore` commands and `--nocopy` will be silently ignored on the `ipfs add` command until the daemon is restarted.

This should be mentioned in the documentation.

**Comment by joshuahannan** [comment]
Can this issue be closed since it looks like it was addressed in #5927 ?
