### ISSUE TITLE
Block downloads don't actually happen

### ISSUE THREAD

**Issue by fiatjaf** [ipfs/go-ipfs#5748]
#### Version information:

go-ipfs version: 0.4.17-
Repo version: 7
System version: 386/linux
Golang version: go1.10.3

#### Type:
Bug

#### Description:
I've called `ipfs pin add QmbEVFkLyNjvYRSYsPeDjBaR6c4pPyUAWACzupf857Fkjy` from the HTTP API, sat and waited. This is a collection of files that are available from at least one other node I control.

I call `watch -n 1 'ipfs bitswap wantlist'` and watched the wantlist move. Apparently each second the list moved 5 positions on average. Does that mean 5 blocks are being downloaded every second?

I don't know how to know how much bandwidth is being used or anything like that, but apparently there's at least some amount of download happening, however `du -sh .ipfs/datastore/` showed 2.7MB 12 hours ago, now it shows 4.5MB. If I watch the evolution of `du -s .ipfs` I see nothing. It stays still for dozens of minutes, even though the wantlist is moving.

**Comment by Stebalien** [comment]
Is the wantlist actually changing or just resorting?

**Comment by fiatjaf** [comment]
Just resorting.

**Comment by fiatjaf** [comment]
But hey, why? The blocks should be available. And the node which has the blocks is listed in the `Bootstrap` section.

**Comment by Stebalien** [comment]
Are you connected to it? Check `ipfs swarm peers`, it may be unreachable. Also try `ipfs findprovs HashOfData`. That'll tell you if your node has announced those blocks.

**Comment by fiatjaf** [comment]
I wasn't connected, but I should have automatically connected with them, right? They're in my Bootstrap list, and they have announced the blocks (at least the root block). I would expect IPFS to find the nodes which have the wanted blocks and connect directly to them, otherwise how is it going to fetch the data?

In this case, nodes A and B have the data, node C wants it. A and B are connected and available, why can't C connect to them and fetch the data even after 12 hours?

I've manually issued `ipfs swarm connect` commands and successfully connected from C to A and B, then the wantlist started moving at a pace of 1 block per second (this time I got it right)... for 30 seconds, then A and B stopped showing on `ipfs swarm peers` and the wantlist stopped moving again.

Some seconds later, C got connected to A again and the wantlist began slowly moving again, stopping for many seconds, then moving again and so on. At some point the connection to A disappeared and a connection to B appeared.

I don't understand why it is this so slow. Both A and B have good overall upload bandwidth and a `scp` would copy these files from B to C or A to C without a problems. Is this how it should be?

**Comment by Stebalien** [comment]
So, I assumed there was a NAT somewhere in between. Node C should connect to them and find the data.

It might be the case that the provider record sent to the DHT was lost or is outdated, that's why I suggested running `ipfs findprovs HashOfData` to see if A or B show up.

The disconnect may be the connection manager on A/B killing the connection (it shouldn't, that's something we're working on).

**Comment by fiatjaf** [comment]
Right, thank you for working on that and letting me know.

Actually, things got a lot better after the time I wrote my previous rant. I don't know if it was because I updated the node C to 0.4.18 or some of my meddling with the configurations or maybe improved connectivity.

**Comment by Stebalien** [comment]
Turns out there was a pretty nasty issue here: https://github.com/ipfs/go-bitswap/issues/53.
