### ISSUE TITLE
File IsDirectory check maybe not right

### ISSUE THREAD

**Issue by songjiayang** [ipfs/go-ipfs#5757]
#### Version information:
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/darwin
Golang version: go1.11.1

#### Type:
Bug

#### Description:

When I add a file not directory to IPFS, I find the `file.IsDirectory()` always be true, It's confused to me.

Let's to see the code https://github.com/ipfs/go-ipfs/blob/master/core/coreunix/add.go#L414

```golang
switch {
case file.IsDirectory():
    // Iterate over each top-level file and add individually. Otherwise the
    // single files.File f is treated as a directory, affecting hidden file
    // semantics.
    for {
        f, err := file.NextFile()
        if err == io.EOF {
            // Finished the list of files.
            break
        } else if err != nil {
            return nil, err
        }
        if err := adder.addFile(f); err != nil {
            return nil, err
        }
    }
    break
default:
    if err := adder.addFile(file); err != nil {
        return nil, err
    }
    break
}
```

It means never run default case.

**Comment by kevina** [comment]
We should be changing the file interface soon see https://github.com/ipfs/go-ipfs-files/pull/2

**Comment by songjiayang** [comment]
thanks for your reply @kevina

**Comment by magik6k** [comment]
If you are adding via the `add` command this is correct as we wrap files into a directory implicitly to make it possible to add multiple files is a single call to the command, the files refactor won't change that.

That said `coreunix` package is on my list of things to refactor as about half of it's code is redundant with coreapi now, so I'll take this into account

**Comment by songjiayang** [comment]
got it.
