### ISSUE TITLE
dlv debug ipfs prompts could not launch process: could not get .debug_frame section: could not find .debug_frame section

### ISSUE THREAD

**Issue by xiedeacc** [ipfs/go-ipfs#5764]
#### Version information:
ipfs version --all
go-ipfs version: 0.4.19-dev-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1

go env
GOARCH="amd64"
GOBIN="/root/src/go/bin"
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/src/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build990065578=/tmp/go-build -gno-record-gcc-switches"

dlv version      
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $

gdb -v
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".

ubuntu 18.04
system has two gcc compiler
gcc 4.8.5
gcc 7.3

#### Description:
use dlv debug ipfs prompts
could not launch process: could not get .debug_frame section: could not find .debug_frame section
use gdb debug ipfs prompts
1 cgoexport.c: No such file or directory

**Comment by magik6k** [comment]
This is because a bug in how go inserts debug info when the program uses `plugin` package.

Just build ipfs with `-tags=noplugin`
