### ISSUE TITLE
curl local ipfs server and return 500

### ISSUE THREAD

**Issue by chenminjian** [ipfs/go-ipfs#5772]
#### Version information:
go-ipfs version: 0.4.19-dev-
Repo version: 7
System version: amd64/darwin
Golang version: go1.11.1

#### Type:
Bug

#### Description:

![wx20181113-111255](https://user-images.githubusercontent.com/13758621/48393613-40c4c180-e74b-11e8-8646-8d8128872bbc.png)

When the mfs file does not exist, I send `files stat` request to ipfs server and return 500.
Even if the file does not exist, we should return 200. Does that make sense?

**Comment by eingenito** [comment]
Makes sense to me.

**Comment by Stebalien** [comment]
(moving from https://github.com/ipfs/go-ipfs/pull/5775#issuecomment-439507822)

I don't think this is the right solution:

* `Type` is the *file type*.
* This is an RPC API, not a normal HTTP endpoint. For us: 200 means "it worked", 404 means "that API endpoint doesn't exist", 400 means "you passed a bad option", *500* means "some error occurred when processing a well-formed request".

Note: I'm not *happy* with how we're using HTTP status codes, that's just how the API currently works. IMO, we should only be using HTTP errors for *transport* errors (missing endpoint, malformed request, command *paniced*, etc) and should have *status* information encoded in the response. However, that ship has kind of sailed.

**Comment by chenminjian** [comment]
Yes, this is not just a problem with `files stat`. We should have status information encoded in the response.

**Comment by Stebalien** [comment]
Unfortunately, it's too late for that. We use the status code to say whether or not the result is an error (any error) and then put the value in the result.

Basically, forget that we're using HTTP here. We *happen* to be using HTTP as the transport but we've chosen our own semantics. They suck but the only real solution is to create an entirely new HTTP API protocol (which is on our TODO list, just not at the top yet).

I'm going to close this as "can't fix" for now as there's really not much we can do without breaking the API.

**Comment by Stebalien** [comment]
(closing for tracking, we can continue discussing this)
