### ISSUE TITLE
coreunix Adder methods are now unexported, any chance they can be exported?

### ISSUE THREAD

**Issue by b5** [ipfs/go-ipfs#5779]
#### Version information:
go-ipfs v0.4.18

#### Type:
Feature Request

#### Description:
Apologies, I haven't found the PR that made this change, but we rely on core/coreunix Adder pretty heavily, and in the latest release they're now unexported, so we can't make use of them. I'm sure there's a good reason for this, so my question is: 

Is there any way to get access to hashes of files as they're being added to a DAG under the new coreunix API?

Thanks! yay 0.4.18!

**Comment by b5** [comment]
Ah nevermind. I think we're better off shimming the bits we need to stay exported & start migrating toward just using `coreapi` methods. Making more stuff public just makes for more things that can break.

By-the-by @magik6k super solid work on `coreapi`. If you ever need to chat to someone who's _using_ that package, I'd love to give feedback if you think it would help.

**Comment by Stebalien** [comment]
Feedback and input on the coreapi would be awesome. And yeah, I that's the new "official" way to do things. We still have quite a bit of code duplication but we can hopefully, eventually, refactor this stuff into some nice, clean APIs.
