### ISSUE TITLE
circuit relay transmission rate is too slow

### ISSUE THREAD

**Issue by wyblyf** [ipfs/go-ipfs#5788]
#### Version information:

go-ipfs version: 0.4.18-dev-1e0d53f
Repo version: 7
System version: amd64/linux
Golang version: go1.11

#### Type:

Enhancement
#### Description:

There are two computer peers in NAT, A & B, A send files to B through RELAY（It has been confirmed that the p2p connection between the two nodes cannot communicate）. Both peer and RELAY peers have a network speed of 10MB/s. No other processes occupy bandwidth, and the transmission is to slow:

![h_h ob z4v4 tw ow77q0v](https://user-images.githubusercontent.com/6084318/48889019-76665a80-ee6f-11e8-8ada-69654c877dca.png)

the relay swarm record:
reach@reach-virtual-machine:~/go/src/github.com/ipfs/go-ipfs$ ipfs swarm peers|grep EbeuTR
/ipfs/QmPiHzwdbJ9uaZD3ntG8uiqRnuFHaW2qXYgTTA6syvWYzm/p2p-circuit/ipfs/QmTbdUZWWKzRDXijkRy3oArg6KnJsHPuJb3UYi4yEbeuTR

**Comment by magik6k** [comment]
This is more likely a bitswap perf issue.
* Do you know what prevents nodes from connecting directly?
* If you manage to connect the nodes directly, what bandwidth are you getting? 
* If you can't connect directly, can you try setting up p2p tunnel - https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#ipfs-p2p - and measuring bandwidth through it?
* What are latencies between peers (`ipfs ping Qm.. `)?

**Comment by wyblyf** [comment]
Connecting directly bandwidth and ping：
![1542959129 1](https://user-images.githubusercontent.com/6084318/48932429-d542d700-ef36-11e8-9da5-9aab3b005888.jpg)

Relay bandwidth（Get file waiting for 20 minutes and not starting） and ping:
![1542960421 1](https://user-images.githubusercontent.com/6084318/48933074-d7f2fb80-ef39-11e8-8da9-aa91e087591d.jpg)
And the relay ping seems to be stable:
![1542962052 1](https://user-images.githubusercontent.com/6084318/48934087-a54b0200-ef3d-11e8-995f-4122c116953b.jpg)

**Comment by magik6k** [comment]
So if I'm reading this correctly there still may be a problem on our side - do you see the slow bandwidth to/from the relay node only when using ipfs? (can you confirm that the connection from A<->Relay and B<->Relay is as fast as it should be (preferably using a tool like `iperf3` to diagnose))?

Can you try running:
* `iperf3 -s -p [someport]` on Relay
* `iperf3 -c [relayIP] -p [someport]` on A and B
* `iperf3 -R -c [relayIP] -p [someport]` on A and B
