### ISSUE TITLE
`/api/v0/resolve?cid-base=base32` not encoding CID in path with base32

### ISSUE THREAD

**Issue by alanshaw** [ipfs/go-ipfs#5790]
#### Version information:
0.4.18

#### Type:
Bug

#### Description:

Raising this issue in response to https://github.com/ipfs/go-ipfs/pull/5464#issuecomment-440920464

```sh
$ curl "https://ipfs.io/api/v0/resolve?cid-base=base32&arg=/ipfs/QmTVyRqL8rdJzpCjZSjjw9bJ1M3ioWuyJhCLpYfgRMmzD4"
{"Path":"/ipfs/QmTVyRqL8rdJzpCjZSjjw9bJ1M3ioWuyJhCLpYfgRMmzD4"}
```

**Comment by kevina** [comment]
Sorry.  You misunderstood.  It is suppose to but only after support for `--cid-base` lands.
