### ISSUE TITLE
Configuring ipfs init for Dockerfile

### ISSUE THREAD

**Issue by leonprou** [ipfs/go-ipfs#5796]
#### Version information:
0.4.18

#### Type:
Enhancement

#### Description:
Please add an ability to configure `ipfs init` command in the Dockerfile. I need to configure the IPFS container to init the ipfs with `---profile=server` config. Currently we're running the IPFS node container  of your official image, it works great but it would be even cooler if I had an option to configure its parameters.

**Comment by Stebalien** [comment]
Fixed by https://github.com/ipfs/go-ipfs/pull/5473.

**Comment by leonprou** [comment]
Thanks!

It's not available at the official image yet, yeah?

**Comment by Stebalien** [comment]
Not until we cut a new release.
