### ISSUE TITLE
pubsub: already have connection to peer

### ISSUE THREAD

**Issue by katmai1** [ipfs/go-ipfs#5817]
Hi,
 I trying use IPFS in my project, and pubsub for the broadcast messages and works fine but on ipfs daemon console appears this message every few minutes.
"16:58:25.275 ERROR     pubsub: already have connection to peer:  <peer.ID Qm*BewHac> pubsub.go:268"
Why appears this message? I'm not be trying connect because the connection between peers is established from first boot.
I think that's is a bug (or i'm not using pubsub correctly)
any idea?

**Comment by Stebalien** [comment]
It's a known bug: https://github.com/libp2p/go-libp2p-pubsub/issues/117

(closing this to avoid duplicating the discussion).
