### ISSUE TITLE
WebUI unable to browse file contents of remote IPFS node

### ISSUE THREAD

**Issue by MidnightLightning** [ipfs/go-ipfs#5821]
#### Version information:
v0.4.18

#### Type:
Bug

#### Description:
When connecting to the WebUI of an IPFS node that's not running on localhost, when connecting you can set up the path to the IPFS node from your workstation with a configuration string like `/ip4/192.168.0.101/tcp/5001`. That allows the WebUI to show the "Files" directory listings appropriately, but if you navigate to a particular file and then click to view it, it does not work.

It seems the WebUI, after connecting to the "API" port (5001 typically) of the node, it looks up the node's own config file to find the configured "Gateway" port (8080 typically) of the node. However, when viewing a remote node, that doesn't work. The remote IPFS node may have something like `/ip4/0.0.0.0/tcp/8080` (bind to all IPs it has, on port 8080), which then causes the WebUI to try and connect to `http://0.0.0.0:8080/..`, which is not the proper URL (should be `http://192.168.0.101:8080`, combining the IP address from the "API" configuration, and the port from the "Gateway").

**Comment by Stebalien** [comment]
This looks like: https://github.com/ipfs-shipyard/ipfs-webui/issues/836. Closing as this is a bug in the webui.
