### ISSUE TITLE
How should I combine hyperledger composer with IPFS?

### ISSUE THREAD

**Issue by zcyzhu** [ipfs/go-ipfs#5846]
How should I combine hyperledger composer with IPFS?I wrote the application with hyperledger composer, but I don't know how to combine IPFS with hyperledger composer.I want to store images, files and other content on composer how to combine hyperledger composer and IPFS?

**Comment by Stebalien** [comment]
Please post questions on https://discuss.ipfs.io. FYI, someone has already asked [this question](https://discuss.ipfs.io/t/combining-ipfs-and-hyperledger-composer/2193) so you might try joining in on that thread.
