### ISSUE TITLE
go-ipfs build on amd64/darwin faild

### ISSUE THREAD

**Issue by jujuandsn** [ipfs/go-ipfs#5847]
#### Version information:
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/darwin
Golang version: go1.11.1
#### Type:
build faild,when i input "make install",it responsed me the following error

#### Description:
bin/check_go_version 1.11
GOPATH="/Users/juju/go" bin/check_go_path github.com/ipfs/go-ipfs
installing gx v0.14.0
bin/dist_get "/ipfs/QmPrXH9jRVwvd7r5MC5e6nV4uauQGzLk1i2647Ye9Vbbwe" gx bin/gx-v0.14.0 v0.14.0
==> Using curl to download "https://ipfs.io/ipfs/QmPrXH9jRVwvd7r5MC5e6nV4uauQGzLk1i2647Ye9Vbbwe/gx/v0.14.0/gx_v0.14.0_darwin-amd64.tar.gz" to "bin/tmp/gx.tar.gz"
error: couldn't download with curl (7)
Unable to download https://ipfs.io/ipfs/QmPrXH9jRVwvd7r5MC5e6nV4uauQGzLk1i2647Ye9Vbbwe/gx/v0.14.0/gx_v0.14.0_darwin-amd64.tar.gz. exiting.
make: *** [bin/gx-v0.14.0] Error 1

**Comment by postables** [comment]
can you try downloading with `curl -L` because you e downloading through an IPFS gateway I believe you're hitting a redirect which curl needs the `-L` flag to handle

**Comment by magik6k** [comment]
The gateway at https://ipfs.io/ipfs might have been down for a moment or there may be some firewall in your network preventing you from connecting to it.

Are you able to download https://ipfs.io/ipfs/QmPrXH9jRVwvd7r5MC5e6nV4uauQGzLk1i2647Ye9Vbbwe/gx/v0.14.0/gx_v0.14.0_darwin-amd64.tar.gz manually?

**Comment by Stebalien** [comment]
Are you in China? Unfortunately, ipfs.io is blocked. That's why this is failing.

If you *just* want to build from source, we publish a pre-build source bundle on GitHub: https://github.com/ipfs/go-ipfs/releases/download/v0.4.18/go-ipfs-source.tar.gz

**Comment by Stebalien** [comment]
(closing for tracking purposes, please ask follow up questions in this thread)
