### ISSUE TITLE
Question: atomic write algorithm

### ISSUE THREAD

**Issue by mcollina** [ipfs/go-ipfs#5863]
As part of https://github.com/ipfs/js-ipfs/issues/1785, I'm investigating what is the algorithm being used by the Go IPFS implementation to write chunks to disk. Can you point me to some code, or flesh it out in pseudocode?

**Comment by magik6k** [comment]
Assuming this is related to flatfs, the code lives in https://github.com/ipfs/go-ds-flatfs/blob/master/flatfs.go#L361

**Comment by Stebalien** [comment]
TL;DR:

1. Create a temporary file. (open)
2. Write to the temporary file. (write)
3. Close the temporary file. (close)
4. Atomically `rename`. (rename)
5. Sync the file. (sync)
6. Sync the directory. (sync)

The difference between go and js is that we *don't* use `realpath` (we don't really care about the real path).

**Comment by mcollina** [comment]
What go/fs/unix operation does sync file and sync directory operate?

**Comment by Stebalien** [comment]
"syncfs".

**Comment by mcollina** [comment]
Thanks!
