### ISSUE TITLE
0.4.19 release

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#5867]
I'd like to ship 0.4.19 before the new year, or at least immediately after. Any PRs/changes to take into account?

PRs that look like they're pretty much ready:

* Bitswap Performance (:yum:): https://github.com/ipfs/go-bitswap/pull/27
* Resolve change that didn't make it into the last release: https://github.com/ipfs/go-ipfs/pull/5704
* CID base: https://github.com/ipfs/go-ipfs/pull/5789, depends on https://github.com/ipfs/go-ipfs/pull/5854

I'd also like to fix: https://github.com/libp2p/go-libp2p/issues/510 first, if possible.

Major user-facing changes as I see them:

* Experimental NAT detection and autorelay.
* Bug fixes.

**Comment by hannahhoward** [comment]
What's the plan on this one? Just curious. I'd love to ship the BS improvements :)

**Comment by hannahhoward** [comment]
> BS improvements :)

I mean Bitswap... but might be an apt description.

**Comment by Stebalien** [comment]
We just ran into an issue with Textile around https://github.com/libp2p/team-mgmt/issues/15#issue-380927291. I'm planning on talking with them today.

Unfortunately, my week has been captured by the libp2p team week.

**Comment by ianopolous** [comment]
Thanks for the heads up @Stebalien

**Comment by Stebalien** [comment]
Status:

* Release notes in #6001.
* Blocked on https://github.com/ipfs/go-bitswap/issues/73.

**Comment by Stebalien** [comment]
Blocked by https://github.com/ipfs/go-ipfs/issues/6007.

**Comment by parkan** [comment]
are we still blocked by something here? the dependency issues mentioned itt look to be all closed

**Comment by Kubuxu** [comment]
@parkan we have released first release candidate and we will wait a few days to collect feedback.

**Comment by Stebalien** [comment]
Release pending in https://github.com/ipfs/go-ipfs/pull/6026.

**Comment by Stebalien** [comment]
Ok, so, a few more blockers:

* https://github.com/libp2p/go-libp2p-kad-dht/issues/276
* https://github.com/ipfs/go-bitswap/pull/87

**Comment by Stebalien** [comment]
And another! https://github.com/ipfs/go-ipfs/issues/6028

**Comment by Stebalien** [comment]
I'd like to merge https://github.com/ipfs/go-ds-flatfs/pull/52 (old bug, just showing up now) and then immediately cut a release (tomorrow). Speak now or wait till 0.4.20.

**Comment by Luflosi** [comment]
Should this issue be closed since 0.4.19 has been released?

**Comment by Stebalien** [comment]
Yes. Thanks!
