### ISSUE TITLE
The MFS root state isn't saved if the daemon is stopped with `Ctrl+C`

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#5868]
Following a series of (maybe not bugs but at least) some unusual behaviors I've found that `Ctrl+C`ing the daemon causes the MFS root's `Close` method (in `teardown`) to *silently* fail and thus causing any un-flushed files to be lost. Since the `ipfs files` command has the `--flush` option set by default this may not have had serious repercussions.

The `Close` error was ([silently](https://github.com/ipfs/go-ipfs/issues/5866)) failing because, when flushing, the `DAG.Add` operation was failing with `blockservice is closed` that was actually a [hard-coded error](https://github.com/ipfs/go-blockservice/blob/8819f05e9f18ea89cf7f125edac566529d76f703/blockservice.go#L154) (which threw me off *substantially*) shadowing any general `HasBlock` errors  in the exchange service, i.e., Bitswap.

The real error was `bitswap is closed` generated in `receiveBlockFrom` that detected that the `process` was on its way to shutting down. This `process` was [tied](https://github.com/ipfs/go-bitswap/blob/e1a25234046f371f5cf3161cc1a410adfd581e28/bitswap.go#L145) to the context that created the Bitswap interface, which actually seems to be derived from the original context that started the daemon that is closed when signaling the interrupt generated by `Ctrl+C`,

https://github.com/ipfs/go-ipfs/blob/c17aaa6e26512b6bbd0f60c0c39c82daacfba9e1/cmd/ipfs/main.go#L396-L409

This doesn't seem to happen with the `ipfs shutdown` command which more gracefully issues a `Process().Close()` without canceling the root context.

**Comment by Stebalien** [comment]
Hello: https://github.com/ipfs/go-ipfs/issues/4623

Would ignoring this error be enough?

**Comment by schomatis** [comment]
> Would ignoring this error be enough?

I guess so (I'll test it a bit) but the bigger issue I think is that we're not honoring the `teardown` order

https://github.com/ipfs/go-ipfs/blob/c17aaa6e26512b6bbd0f60c0c39c82daacfba9e1/core/core.go#L668-L676

so any other service inter-dependency we rely on in the future will be subjected to a similar problem.

**Comment by Stebalien** [comment]
I see. Yeah, we really need a proper service management system (#5810). Regardless, we shouldn't be using context for closing processes.
