### ISSUE TITLE
how to add file (like img) to ipfs by curl?

### ISSUE THREAD

**Issue by waliguder** [ipfs/go-ipfs#5869]
```
#use postman to post url
#first run ipfs daemon
#url
http://localhost:5001/api/v0/add
#data
arg='file path'
```

![1545360469 1](https://user-images.githubusercontent.com/27879437/50321913-06023600-050e-11e9-8bb2-3d4cd9ce11fd.jpg)

but only upload file path instead of img file
![image](https://user-images.githubusercontent.com/27879437/50322014-5e393800-050e-11e9-9790-5c426262eea9.png)

How to properly upload a photo file or other using post request？

**Comment by chenminjian** [comment]
curl -F file=@/Users/chenminjian/info.log "http://localhost:7878/v1/files/add"
