### ISSUE TITLE
networked IPNS tests

### ISSUE THREAD

**Issue by briantigerchow** [ipfs/go-ipfs#587]
Let's add a few networked tests (can be after alpha) for IPNS. These tests can instantiate core IPFSNodes with

- [ ] if a record is expired and the node is offline, it is discarded (not used)
- [ ] if a record is expired and the node is connected, node fetches new record
- [ ] if record is valid and node is connected, use existing record but async'ly fetch new record

@whyrusleeping are these test cases already covered?

**Comment by whyrusleeping** [comment]
I dont beleive we actually do any sort of networked ipns tests. I really want to have them, ipns is really important and everyone i talk to about this project wants it (so it should get dev-love too!)

**Comment by whyrusleeping** [comment]
we have some networked ipns tests in sharness, more would be good, but i'm closing this for now
