### ISSUE TITLE
How to get the list of hashes uploaded on my computer

### ISSUE THREAD

**Issue by waliguder** [ipfs/go-ipfs#5875]
`Ipfs files ls `
can get a list of the files I uploaded, 
but they don't return their corresponding hash values.

**Comment by schomatis** [comment]
Hey @waliguder, the command you're looking for is `ipfs refs local`:

* https://discuss.ipfs.io/t/how-can-i-get-hash-if-i-forget/2016
* https://discuss.ipfs.io/t/list-all-items-stored-on-ipfs-and-corresponding-hash-value/427/4

For future questions about usage please use our community forum in https://discuss.ipfs.io/.

**Comment by waliguder** [comment]
Thanks.
Ok.
I will be there
