### ISSUE TITLE
Better support for folder sharing

### ISSUE THREAD

**Issue by birbird** [ipfs/go-ipfs#5879]
Hi 
I am new to IPFS, apologize in advance if I am wrong.

I am building a file sharing app. I think IPFS focus on file, can not handle folder well.

I want to build something like this:
On peer A, ipfs add [folder path], then get a [hashOfFolderA]
On peer B, ipfs ls [hashOfFolderA], then get all the children of folder A
If something changed in folder A, B can get those changes in next ls with on effect.

My problem is, I cannot **really** add a folder, I need to ipfs add <folder path> -r, which actually add all files under the folder traverse.
And if something changed, I need to run ipfs add again. Most important, the hashOfFolderA will change after its content changed. Then A have to tell B the new hash to let B get the latest conetent of folderA.

Maybe IPFS is not designed for this scenario, if any existing API can achieve something similar, I am happy to try.

Any help will be highly appreciated.

**Comment by magik6k** [comment]
You should be able to use `ipfs files` (or `ipfs object patch` if you want to operate on a lower level) to update parts of directory tree. (for a file sharing app, `ipfs files` should be good fit)

The main issue here is that once files are added to ipfs, they are chunked into blocks and copied into the datastore (there is `--nocopy`, but that's another thing), and there is really no way to trace back those blocks back to files in the filesystem. We also don't store file attributes such as modification time, so it's not easy to tell what changed even when given previous directory hash (this will change with unixfsv2 - https://github.com/ipfs/unixfs-v2)

**Comment by birbird** [comment]
@magik6k Thanks a lot
