### ISSUE TITLE
coredag package

### ISSUE THREAD

**Issue by briantigerchow** [ipfs/go-ipfs#589]
The coreunix package provides basic functions for unix-y file/reader handling. To complement coreunix, provide a `coredag` package for raw DAG manipulation.

**Comment by whyrusleeping** [comment]
im unsure how this will pan out, If im dealing with just DAG's and i try to 'add' some data that is larger than the blocksize, what happens?

**Comment by whyrusleeping** [comment]
we kindof have this now in the form of merkledag/utils, in any case, this issue is too old. closing
