### ISSUE TITLE
Slow Speed Issue 

### ISSUE THREAD

**Issue by ArmaghanRaza** [ipfs/go-ipfs#5897]
#### Version information:
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1

#### Type:

bug

#### Description:
When I publish some content to a specific hash and try to load the hash in my browser it takes a long time to load the stuff. I have tried direct access to localhost using the same hash ( considering ports obviously) but still speed is very slow. I understand my content is hosted by only myself atm but its very slow in the case of direct access also. I think Its related to IPNS because otherwise its just alright.

**Comment by magik6k** [comment]
If you are using `/ipns/Qm` then it's most likely https://github.com/ipfs/go-ipfs/issues/3860

**Comment by Stebalien** [comment]
This may also be related to some recent public gateway slowdowns we've been noticing.

**Comment by Kubuxu** [comment]
Closing due to lack or response.
