### ISSUE TITLE
Switch to go-dnslink

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#5902]
That is, https://github.com/ipfs/go-dnslink. Before we do that, we need to port all existing functionality from go-ipfs to go-dnslink (e.g., `_dnslink.domain` support).

**Comment by anacrolix** [comment]
I take it this functionality isn't part of libp2p. In that case, consider leaving it where it is. The IPFS repos are already too fragmented. An separate repository for dnslink really isn't that useful to anyone else, and maintaining it separately is extra overhead.

**Comment by Stebalien** [comment]
libp2p has dnsaddr. You're probably right about fragmentation. DNSLink is really only useful along with an IPNS/IPFS resolver anyways.

We can consider moving all of namesys later.
