### ISSUE TITLE
Add support for .local domains within the boostrap list

### ISSUE THREAD

**Issue by ghost** [ipfs/go-ipfs#5911]
I'm adding this as a distinct item. Maybe not too hard to do, and would enable IPFS to be used in local networks or mesh networks in which IP addresses are dynamic and avahi (or similar) is used.

**Comment by Stebalien** [comment]
We now have support for `/dnsaddr`, `/dns4`, and `/dns6`. We're already using `/dnsaddr` for bootstrap nodes so this should "just work" (assuming your local DNS resolver supports dnssd).
