### ISSUE TITLE
Counting peers that have a specific block

### ISSUE THREAD

**Issue by Ape** [ipfs/go-ipfs#5912]
I'd like to count how many peers have a specified block available. I can query a block and see if anybody sends it to me, but is it possible to count how many peers would be willing to send it?

**Comment by Stebalien** [comment]
A lot has changed since this issue was filed and `ipfs dht findprovs` seems to work pretty well. However, regardless, it won't give a complete view of how many peers have a file but that would likely require crawling the entire network (which isn't a feature we're likely going to add to go-ipfs).
