### ISSUE TITLE
IPFS crashes cjdns; can I tell it not to use my cjdns IP?

### ISSUE THREAD

**Issue by adamnovak** [ipfs/go-ipfs#5915]
Right now if I run IPFS and cjdns at the same time, my cjdns will crash and knock me offline. I don't know if it's caused by misbehaving other nodes on the network DDOSing me or what.

The real issue is on cjdns's end, but I think that it would be good if I could tell IPFS not to listen/connect on that interface. Is that possible? Or do I have to do something fancy with Linux control groups to hide the interface from IPFS at the kernel level?

**Comment by Stebalien** [comment]
Addressed by @lgierth.
