### ISSUE TITLE
quic close all connect

### ISSUE THREAD

**Issue by s1377427321** [ipfs/go-ipfs#5921]
I use quic transmission，but sometimes quic will close all network connections.

source code：
     ts, err := c.conn.AcceptStream()
i detecte error 
    InternalError: read udp4 0.0.0.0:55289: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress

**Comment by Stebalien** [comment]
Closing in favor of https://github.com/libp2p/go-libp2p/issues/519.
