### ISSUE TITLE
Logging needs to be unified

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#593]
We have a few different libraries we are using for logging (go-logging, prefixlog, and eventlog), with roughly the same interface. Would be best to consolidate to just use one.

**Comment by rht** [comment]
Putting https://github.com/ipfs/go-ipfs/issues/592, https://github.com/ipfs/go-ipfs/issues/1224, https://github.com/ipfs/go-ipfs/issues/1217 here to collect all logging cleanup related issues in one place.

**Comment by lgierth** [comment]
And #1375

**Comment by whyrusleeping** [comment]
did this
