### ISSUE TITLE
Failed to Initialize repo on fsrepo.Open(configPath), 

### ISSUE THREAD

**Issue by moon004** [ipfs/go-ipfs#5930]
**Version information:** 

> **ipfs version --all**
go-ipfs version: 0.4.19-dev-c17aaa6e2
Repo version: 7
System version: amd64/windows
Golang version: go1.11`

> **ipfs config --json Datastore.Spec**`
```{
  "mounts": [
    {
      "child": {
        "path": "blocks",
        "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
        "sync": true,
        "type": "flatfs"
      },
      "mountpoint": "/blocks",
      "prefix": "flatfs.datastore",
      "type": "measure"
    },
    {
      "child": {
        "compression": "none",
        "path": "datastore",
        "type": "levelds"
      },
      "mountpoint": "/",
      "prefix": "leveldb.datastore",
      "type": "measure"
    }
  ],
  "type": "mount"
}
```
**Type:**
Bug?

**Description:**
I get the error of **unknown datastore type: flatfs** when i try to init my repo via fsrepo.Open(myConfigPath). My main purpose is to start a NewNode so that i'm able to use the ipfs API. i debugged it and found out that the code [https://github.com/ipfs/go-ipfs/blob/de0bbb00e224b2a597eeccdc72b8cd49dc2ca10f/repo/fsrepo/datastores.go#L59-L62](url) does not have type of "flatfs" nor "levelds", and it is called from https://github.com/ipfs/go-ipfs/blob/de0bbb00e224b2a597eeccdc72b8cd49dc2ca10f/repo/fsrepo/datastores.go#L83.

Or am i doing something wrong here? I really appreciate your help.

**Comment by moon004** [comment]
I built the binary from source, and since im on windows i built it from this guide (msys2), [here](https://github.com/ipfs/go-ipfs/blob/master/docs/windows.md). Does it work with that build?

Quick question, I wanted to build a CLI on top of ipfs using Go, the compiled go code doesn't depend on the built go-ipfs binary right?

By the way, i followed the guide [here](https://ipfs.io/ipfs/QmQwAP9vFjbCtKvD8RkJdCvPHqLQjZfW7Mqbbqx18zd8j7/api/readme.md)

Is there any work around? thank you in advance for your time :relaxed::grin:

**Comment by magik6k** [comment]
That guide is a bit outdated, and node constructor is going to be refactored soon (if things go well, this quarter), so it might be a good idea to use http api, at lest for now.

If you really need/want to use the node directly, you need to somehow invoke plugin loader - see [here](https://github.com/ipfs/go-ipfs/blob/master/cmd/ipfs/main.go#L63-L75) - and make sure that plugins exist in the provided path, or are on the [preload list](https://github.com/ipfs/go-ipfs/blob/master/plugin/loader/preload_list) and that [preload.go](https://github.com/ipfs/go-ipfs/blob/master/plugin/loader/preload.go) is matching preload_list (You can re-generate it with `make plugin/leader/preload.go`)

I'd recommend using https://github.com/ipfs/go-ipfs-api for now (or, if you don't mind using things which will likely receive a few breaking changes in near future, https://github.com/ipfs/go-ipfs-http-client/pull/1, which implements the [CoreAPI](https://github.com/ipfs/go-ipfs/tree/master/core/coreapi/interface) interface over http api)

**Comment by moon004** [comment]
Thank you for the fast response. I'll try it out. I'll close the issue for now, and open again if theres any problem.

Thanks @magik6k , i really appreciate it. 😄
