### ISSUE TITLE
commit aefb37254 has build error with cid

### ISSUE THREAD

**Issue by godcong** [ipfs/go-ipfs#5941]
#### Type:
 newest master commit aefb37254 build error

#### Description:
go build -i -ldflags="-X "github.com/ipfs/go-ipfs".CurrentCommit=aefb37254" -o "cmd/ipfs/ipfs" "github.com/ipfs/go-ipfs/cmd/ipfs"
# github.com/ipfs/go-ipfs/core/coreapi/interface/options
core/coreapi/interface/options/unixfs.go:122:2: cannot use prefix (type "gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Prefix) as type "github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Prefix in return argument
# github.com/ipfs/go-ipfs/filestore
filestore/filestore.go:199:2: impossible type switch case: b (type "github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmWoXtvgC8inqFkAATB7cp2Dax7XBi9VDvSg9RCCZufmRk/go-block-format".Block) cannot have dynamic type *posinfo.FilestoreNode (wrong type for Cid method)
        have Cid() "gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Cid
        want Cid() "github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Cid
filestore/filestore.go:223:3: impossible type switch case: b (type "github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmWoXtvgC8inqFkAATB7cp2Dax7XBi9VDvSg9RCCZufmRk/go-block-format".Block) cannot have dynamic type *posinfo.FilestoreNode (wrong type for Cid method)
        have Cid() "gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Cid
        want Cid() "github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Cid
filestore/fsrefstore.go:303:39: cannot use b.Node.Cid() (type "gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Cid) as type "github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Cid in argument to dshelp.CidToDsKey
# github.com/ipfs/go-ipfs/p2p
p2p/local.go:58:49: cannot use l.proto (type "github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmZNkThpqfVXs9GNbexPrfBbXSLNYeKrE7jwFM2oqHbyqN/go-libp2p-protocol".ID) as type "gx/ipfs/QmZNkThpqfVXs9GNbexPrfBbXSLNYeKrE7jwFM2oqHbyqN/go-libp2p-protocol".ID in argument to l.p2p.peerHost.NewStream
# github.com/ipfs/go-ipfs/core/coredag
core/coredag/dagpb.go:28:28: cannot use cidPrefix(mhType, mhLen) (type *"github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Prefix) as type "gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Builder in argument to nd.SetCidBuilder:
        *"github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Prefix does not implement "gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Builder (wrong type for Sum method)
                have Sum([]byte) ("github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Cid, error)
                want Sum([]byte) ("gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Cid, error)
core/coredag/dagpb.go:44:28: cannot use cidPrefix(mhType, mhLen) (type *"github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Prefix) as type "gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Builder in argument to nd.SetCidBuilder:
        *"github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Prefix does not implement "gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Builder (wrong type for Sum method)
                have Sum([]byte) ("github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Cid, error)
                want Sum([]byte) ("gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Cid, error)
core/coredag/raw.go:35:27: cannot use blk (type *"github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmWoXtvgC8inqFkAATB7cp2Dax7XBi9VDvSg9RCCZufmRk/go-block-format".BasicBlock) as type "gx/ipfs/QmWoXtvgC8inqFkAATB7cp2Dax7XBi9VDvSg9RCCZufmRk/go-block-format".Block in field value:
        *"github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmWoXtvgC8inqFkAATB7cp2Dax7XBi9VDvSg9RCCZufmRk/go-block-format".BasicBlock does not implement "gx/ipfs/QmWoXtvgC8inqFkAATB7cp2Dax7XBi9VDvSg9RCCZufmRk/go-block-format".Block (wrong type for Cid method)
                have Cid() "github.com/ipfs/go-ipfs/vendor/gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Cid
                want Cid() "gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid".Cid
cmd/ipfs/Rules.mk:22: recipe for target 'cmd/ipfs/ipfs' failed
make: *** [cmd/ipfs/ipfs] Error 2

**Comment by magik6k** [comment]
I can't reproduce. Did you do anything gx-related? Did you use `gx-go link`? Does `gx deps dupes` show anything?

Things to try:
* `gx-go rw --fix && gx-go rw` in go-ipfs repo
* Removing `$GOPATH/src/gx/ipfs` and running `git reset --hard origin/master` in go-ipfs repo

**Comment by godcong** [comment]
sorry, i copied `gx` into the vendor.
when used the master, the `gx` packages is not newest
