### ISSUE TITLE
Disable DNSResolver option

### ISSUE THREAD

**Issue by cpacia** [ipfs/go-ipfs#5945]
Not sure what the best way to handle this is, but the issue is if a user is using Tor, say, the DNSResolver in the name system may leak their IP. As far as I can tell it looks like the resolver does an `IsDomain` check and exits if it's not a domain name without actually doing the DNS query. 

So if they don't try to resolve a domain name it shouldn't leak but if they do then it would leak their IP. 

I'm currently gating the `Resolve` function in my own code with a `IsDomain` check to make sure it's not allowing domains to be passed in but it might be nice to be more explicit about this as a consumer may inadvertently pass in a domain name while trying to remain private.

Possibly a resolve option to skip the dnsrolver. 

I can submit a PR if you guys think that's the way to go.

**Comment by magik6k** [comment]
Other nice way would be to disable dns resolver when namesystem is constructed - e.g. by setting
https://github.com/ipfs/go-ipfs/blob/ca77ecc766cd79f6f57490e0fa10d6a12c1be9ae/namesys/namesys.go#L45
to a dummy resolver which returns a closed channel from `resolveOnceAsync`

**Comment by lidel** [comment]
I think we should default to DNS over TLS or HTTPS and make it possible for user to set custom DNS server. That way Tor users could make go-ipfs use DNS over Tor ([`DNSPort 9053`](https://web.archive.org/web/20190610011256/http://tuxdiary.com/2015/11/16/resolve-dns-tor/) to `/etc/tor/torrc`).

See https://github.com/ipfs/go-ipfs/issues/6532
