### ISSUE TITLE
No relay with in aws and EnableAutoRelay.

### ISSUE THREAD

**Issue by gaillard** [ipfs/go-ipfs#5946]
#### Version information:
Latest master build

#### Description:
I was trying to test relay and was running the node in ec2 with just port 80 and no other ports open in the security group. Using default config (so port 4001) plus EnableAutoRelay=true. After 20 minutes or so still no circuit address from ipfs id cmd.

Note when running on my home system behind a NAT with no upnp, I get a relay address, however it comes and goes.

Should I be doing anything else?

Is the expectation that relays come and go depending on what blocks are trying to be fetched?

**Comment by vyzo** [comment]
Our infrastructure deployment is currently incomplete I think.

**Comment by vyzo** [comment]
The reason it comes and goes is that we currently only have relays in the bootstrappers, which may easily close the connections.
This should go away as we deploy relay capacity outside the bootstrappers, with high connection quota.
Not sure why it doesn't work on ec2 though.

**Comment by gaillard** [comment]
@vyzo I have a little private network (swarm key, all go-ipfs) now to test this on 3 boxes. Box (A) that is double nat, then two in aws, Relay with a port open and B with nothing open. A and B have Relay as the only bootstrap address like:
```
"Bootstrap": [
    "/ip4/THE IP/tcp/8443/ipfs/PeerID_Relay"
  ],
```
they both (A and B) have `"EnableAutoRelay": true,` otherwise default config.

Relay config beyond default looks like:
```
"Bootstrap": null,
"Addresses": {
   ...
  "Announce": [
      "/ip4/THE IP/tcp/8443"
  ],
  Swarm": [
      "/ip4/0.0.0.0/tcp/8443"
  ]
}
...
"Swarm": {
    "EnableRelayHop": true,
    "EnableAutoRelay": true,
    "EnableAutoNATService": true
    ...
}
``` 

When all three daemons are running I see both A and B have Relay as a peer, however I don't see any relay connection in `ipfs swarm peer -v` or `ipfs id`. 

I'm running master.

Anything I can check or certain logs to enable etc?

**Comment by gaillard** [comment]
@vyzo also I should note that if lets say a file is on A with hash HashA.
Then from B this fails `ipfs cat HashA`, but it works if I connect the circuit manually via discovery such as
```
ipfs dht findprovs HashA
  > PeerA
ipfs swarm connect '/p2p-circuit/ipfs/PeerA'
  > connect PeerA success
ipfs cat HashA
```

Is that circuit connection being made on demand depending on what is trying to be `cat`'d supposed to work just from `ipfs cat blah`?

**Comment by vyzo** [comment]
Hrm, Is the DHT enabled? and even functional with just 3 nodes in the private network? 
You need the DHT for autorelay to work.

**Comment by gaillard** [comment]
@vyzo I switched the Relay to be on a box outside aws with an open port and moved B into aws, then if I wait a bit I see a relay address `ipfs id` for B, and all seems to work normally.

So it seems something about having the relay within ec2 is causing an issue.

(side note, also trying to get js-ipfs to be able to see and use these boxes, to no avail https://github.com/ipfs/js-ipfs/issues/1857)

**Comment by Stebalien** [comment]
We've changed how relays and autonat work significantly since this issue was filed so I'm going to close this for now. If it becomes a problem in the future, please open a new issue.
