### ISSUE TITLE
"Generic" Plugin type(feature)?

### ISSUE THREAD

**Issue by eyedeekay** [ipfs/go-ipfs#5954]
#### Version information:

go-ipfs version: 0.4.18-aefc746
Repo version: 7
System version: amd64/linux
Golang version: go1.11

#### Type:

Feature Request

#### Description:

I would like to be able to create a type of plugin which extends IPFS's functionality by connecting it to the API's of other applications automatically, in particular my use case is making the gateway available via tunnels and hidden services. The current plugin system requires that plugins implement one of the existing plugin interfaces, and implementing the hidden service listeners on top of the existing plugin interfaces is a pretty messy process. In our branch at https://github.com/rtradeltd/go-ipfs I have created a prototype of a "Generic" plugin interface which only requires implementing "plugin.Plugin" with an Exists() function that is intended to the return nil if the plugin was initialized correctly, and an error if something went wrong. If this is acceptable I'd like to submit it.

**Comment by Stebalien** [comment]
How about something like: #5955? That way you don't even need to use the HTTP API?

**Comment by eyedeekay** [comment]
> How about something like: #5955? That way you don't even need to use the HTTP API?

Oh I hadn't seen that yet. To all appearances it fulfills what I need and much of what I will eventually need. If it doesn't I'll reopen. Thanks for your help :)
