### ISSUE TITLE
JSON from /dht/findprovs is in wrong format

### ISSUE THREAD

**Issue by useaquestion** [ipfs/go-ipfs#5959]
#### Version information:
go-ipfs version: 0.4.17-
Repo version: 7
System version: amd64/windows
Golang version: go1.10.3

#### Type:
bug

#### Description:
http://localhost:5001/api/v0/dht/findprovs?arg=QmbKU5Ht3toTdyTJGuqUwxvekWsvo394z1hS2SVLcLpVHw&num-providers=2

Provides the below response:

`
{"Extra":"","ID":"QmWbeKBWuQTBsr8y2FuEa9wX2WUPXr98kB9fir9G71HXcq","Responses":null,"Type":6} {"Extra":"","ID":"QmatonFXvhot53W2Ey9ZuCYrkjkLHivnkYAsFqNGqitSj1","Responses":null,"Type":6} {"Extra":"","ID":"QmdinCWcGHuVXQUAukqfsV4qX78j1k5St9jMrqHkhZHNiw","Responses":null,"Type":6} {"Extra":"","ID":"QmWbeKBWuQTBsr8y2FuEa9wX2WUPXr98kB9fir9G71HXcq","Responses":null,"Type":0} {"Extra":"","ID":"QmdinCWcGHuVXQUAukqfsV4qX78j1k5St9jMrqHkhZHNiw","Responses":null,"Type":0} {"Extra":"","ID":"QmatonFXvhot53W2Ey9ZuCYrkjkLHivnkYAsFqNGqitSj1","Responses":null,"Type":0} {"Extra":"","ID":"","Responses":[{"Addrs":null,"ID":"QmPgEufTcDYbdnCmuuPwqPzivEdmB3iRabeBdMb8DXsGRG"}],"Type":4} {"Extra":"","ID":"","Responses":[{"Addrs":["/ip4/171.4.251.189/tcp/4001","/ip4/127.0.0.1/tcp/4001","/ip4/192.168.1.8/tcp/4001","/ip6/::1/tcp/4001"],"ID":"QmdeMvS5W9MDQRSNF1KamKUaAWMhamR3zWC1dqpgdKi9Fb"}],"Type":4}
`

However, this is not valid JSON output:

> SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 2 column 1 of the JSON data

**Comment by magik6k** [comment]
The output is [ndjson](http://ndjson.org/), which is just json strings separated by new lines. The reason we do this is to allow streaming results as they get discovered.

(assuming you use JS, you might also want to look into using https://github.com/ipfs/js-ipfs-http-client)
