### ISSUE TITLE
files mv cmd has wrong dst filename

### ISSUE THREAD

**Issue by chenminjian** [ipfs/go-ipfs#5963]
#### Version information:
go-ipfs version: 0.4.19-dev-
Repo version: 7
System version: amd64/darwin
Golang version: go1.11.1

#### Type:
bug

#### Description:
```
$ ipfs files cp /ipfs/QmbAq3aBS8SKPWqiDPcXBSLpxEhp8h4SfiUjtvdjiP6Q5f /a

$ ipfs files mkdir /dir66

$ ipfs files mv /a /dir66

$ ipfs files ls /dir66
dir66
```

`a` is the correct answer instead of `dir66 `.

**Comment by Stebalien** [comment]
(fixed)
