### ISSUE TITLE
There is no option to disable IPv4 peer connections

### ISSUE THREAD

**Issue by Mikaela** [ipfs/go-ipfs#5980]
#### Version information:

```
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1
```

#### Type:

bug/feature

#### Description:

On IPv4 I am behind Carrier Grade NAT in addition to my own NAT. I think IPFS makes my router more overwhelmed by opening needless IPv4 connections well above HighWater (109/20) possibly leading to https://github.com/ipfs/go-ipfs/issues/3320 and requiring me to reboot my router more often than when IPFS is not running.

I have removed IPv4 addresses from swarm and bootstrap peers where I also removed /dnsaddrs.

**Comment by Stebalien** [comment]
You can configure IPFS to not _listen_ on IPv4 but it'll still dial IPv4 addresses. If it didn't, most of the network would be undialable (without a relay, at least). If you _really_ want to prevent IPFS from dialing IPv4 addresses, you can set up a filter: `ipfs swarm filters add /ip4/0.0.0.0/ipcidr/0`.

Closing for tracking but feel free to ask followup questions. We can reopen if it turns there's a bug I'm missing here.

**Comment by Mikaela** [comment]
Thank you, `ipfs swarm filters add /ip4/0.0.0.0/ipcidr/0` seems to do this and with quick testing my performance isn't suffering. No one at IRC knew that command at the time I asked so I opened an issue.

**Comment by Stebalien** [comment]
Yeah, this isn't a common ask so that's not surprising. I'm glad it worked!
