### ISSUE TITLE
[bug/doc] Files added by WebUI does not show up as "pinned" using the CLI.

### ISSUE THREAD

**Issue by EliasGabrielsson** [ipfs/go-ipfs#5981]
### Symptom:

Files added using the `webui` does not show up while issuing command: `ipfs pin ls`. The files show up in the web ui.

### Expected outcome:
According to the documentation for the IPFS HTTP CLIENT - API an added file by the webui shall be pinned by default https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/FILES.md#add. I therefore expect that issuing command `ipfs pin ls` will show up files added by webgui which is not happening.

#### Version information:
```
go-ipfs version: 0.4.19-dev-6a5a26851
Repo version: 7
System version: amd64/freebsd
Golang version: go1.11.4
```

**Comment by Stebalien** [comment]
Yeah, this needs to be documented but I'm not sure where. Files added through the webui get added to something called "MFS". You can view these files by running `ipfs files ls ...`. The difference is:

1. Files pinned with `ipfs pin` are fetched up-front and are guaranteed to fully exist on the local machine.
2. Files added through `ipfs files` don't _necessarily_ need to exist locally. However, files in `ipfs files` that _do_ exist locally won't be garbage collected. This means you can run `ipfs files cp /ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco /wikipedia-snapshot` and IPFS will only fetch the pieces of wikipedia it needs on demand.

Mind filing a bug with the WebUI (https://github.com/ipfs-shipyard/ipfs-webui)? I believe this is something that'll need to be documented on their end (although I'm not sure how).

**Comment by olizilla** [comment]
For posterity: The current MFS root is recursively pinned. Files that you add via the webui are pinned, transitively. You'll only find the CID for `/` of your MFS in the pins list.

**Comment by Stebalien** [comment]
> For posterity: The current MFS root is recursively pinned. Files that you add via the webui are pinned, transitively. You'll only find the CID for 

In js-ipfs, maybe. In go-ipfs, kind of but not really. `ipfs files` uses a _special_ pin type we call "best effort" and this doesn't show up in `ipfs pin ls`. Unfortunately, it's its own special thing.
