### ISSUE TITLE
ipfs 0.4.18 reproducebly crashes

### ISSUE THREAD

**Issue by skliarie** [ipfs/go-ipfs#5989]
type: bug
ipfs 0.4.18 reproducebly crashes, when I do ipfs add this IPNS: /ipns/QmdwSsWWao7qK1ceVxgis6z8U7TsPsUUk3HxRPVKr3DvSh 

ipfs@backup4:~$ ipfs version --all
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1

Find attached crashdump
[ipfs_0.4.18_crashdump.txt.gz](https://github.com/ipfs/go-ipfs/files/2855043/ipfs_0.4.18_crashdump.txt.gz)

**Comment by Kubuxu** [comment]
Looks like we are hit thread limit. What is interesting there 450 threads Closing a file descriptor.

```
goroutine 20301898 [syscall]:
syscall.Syscall(0x3, 0xc6b, 0x0, 0x0, 0xc005fb6a60, 0xa6a76d, 0x7f0b5b417210)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(0xc6b, 0xc005fb6ac0, 0x9ccfa1)
	/usr/lib/go/src/syscall/zsyscall_linux_amd64.go:310 +0x40
internal/poll.(*FD).destroy(0xc021fd6c00, 0x1924601, 0xc005fb6a01)
	/usr/lib/go/src/internal/poll/fd_unix.go:78 +0x4e
internal/poll.(*FD).readUnlock(0xc021fd6c00)
	/usr/lib/go/src/internal/poll/fd_mutex.go:232 +0x54
internal/poll.(*FD).Read(0xc021fd6c00, 0xc030855498, 0x4, 0x4, 0x0, 0x19246e0, 0xc0000ac130)
	/usr/lib/go/src/internal/poll/fd_unix.go:181 +0x1ab
net.(*netFD).Read(0xc021fd6c00, 0xc030855498, 0x4, 0x4, 0xc00499f300, 0xc, 0x40)
	/usr/lib/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000efc0, 0xc030855498, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:177 +0x68
io.ReadAtLeast(0x7f0bb046c0b0, 0xc00ba99ad0, 0xc030855498, 0x4, 0x4, 0x4, 0xc0001a1590, 0xc02eb15280, 0xa0792b)
	/usr/lib/go/src/io/io.go:310 +0x88
io.ReadFull(0x7f0bb046c0b0, 0xc00ba99ad0, 0xc030855498, 0x4, 0x4, 0xc033f7a380, 0xe846ba, 0xc0001a1590)
	/usr/lib/go/src/io/io.go:329 +0x58
gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio.ReadLen(0x7f0bb046c0b0, 0xc00ba99ad0, 0xc030855498, 0x4, 0x4, 0xc033f7a380, 0x9ccfa1, 0xc005fb6d48)
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio/num.go:27 +0x74
gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio.(*reader).nextMsgLen(0xc01c662f00, 0x192b6c0, 0xc0308554d0, 0xc005fb6d78)
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio/msgio.go:159 +0x78
gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio.(*reader).NextMsgLen(0xc01c662f00, 0x0, 0x0, 0x0)
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio/msgio.go:154 +0x84
gx/ipfs/QmXVoVfwEXZdG9zNNHE9in55SepeSJM5GSETEyWNSNMygc/go-libp2p-secio.(*etmReader).Read(0xc03422e3c0, 0xc0254014b4, 0xc, 0xc, 0x0, 0x0, 0x0)
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmXVoVfwEXZdG9zNNHE9in55SepeSJM5GSETEyWNSNMygc/go-libp2p-secio/rw.go:163 +0xcf
io.ReadAtLeast(0x7f0bb70af2e8, 0xc03c0ae6c0, 0xc0254014b4, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:310 +0x88
io.ReadFull(0x7f0bb70af2e8, 0xc03c0ae6c0, 0xc0254014b4, 0xc, 0xc, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:329 +0x58
gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux.(*Session).recvLoop(0xc024e82b40, 0x0, 0x0)
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux/session.go:535 +0xec
gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux.(*Session).recv(0xc024e82b40)
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux/session.go:514 +0x2b
created by gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux.newSession
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux/session.go:128 +0x387
```

**Comment by skliarie** [comment]
How can I change the limit to be unlimited? I run ipfs using nice anyway.

**Comment by Kubuxu** [comment]
Please check and share here: `cat /proc/sys/kernel/threads-max` and `ulimit -a`.

**Comment by skliarie** [comment]
ipfs@backup4:~$ cat /proc/sys/kernel/threads-max
192588
ipfs@backup4:~$ ulimit -a 
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 96294
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 16383
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 16383
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

BTW, backup4 is LXC-based vserver, but is not limited in any way.

**Comment by magik6k** [comment]
This might also be a systemd limit - check `TasksMax` (Here is a good article explaining the issue: https://www.elastic.co/blog/we-are-out-of-memory-systemd-process-limits)

**Comment by Kubuxu** [comment]
This would seem to be consistent with a number of threads locked in `Close`. I don't know why they are locked there but, 450 there + some will reach 512 which might be a limit systemd sets.

**Comment by skliarie** [comment]
Yes, it was it. I raised /sys/fs/cgroup/pids/system.slice/ssh.service/pids.max (I start ipfs daemon over ssh) to 4096 and the problem went away. Time to start ipfs using systemd with explicit TasksMax arg..
It seems the more popular content is, the more threads are spawned to receive the blocks.
Thank you for prompt answers!

**Comment by Kubuxu** [comment]
Aah, I think I know what is it. It is connecting manager sweeping old connections.
