### ISSUE TITLE
block putting with cached byte array for file read 

### ISSUE THREAD

**Issue by songjiayang** [ipfs/go-ipfs#5991]
#### Description:

Currently, in the block put api, we use `ioutil.ReadAll` to get the contents of the entire block. Usually the contents of the block is 256KB, so using the `ioutil.ReadAll` method will cause frequent memory allocation problems.  Can we use a cached byte array to avoid memory allocation,  for example:

```golang
var (
	blockBufChan = make(chan []byte, 40)
)

func init() {
	for i:=0; i < 40 ; i++ {
		blockBufChan <- make([]byte, 262158)
	}
}

func (api *BlockAPI) Put(ctx context.Context, src io.Reader, opts ...caopts.BlockPutOption) (coreiface.BlockStat, error) {
	settings, pref, err := caopts.BlockPutOptions(opts...)
	if err != nil {
		return nil, err
	}

	data := <- blockBufChan
	defer func() {
		blockBufChan <- data
	}()

	var size = 0
	for {
		n, err := src.Read(data[size:])
		if err != nil && err != io.EOF  {
			return nil, err
		}
		size += n
		if err == io.EOF {
			break
		}
	}

	bcid, err := pref.Sum(data[0:size])
	if err != nil {
		return nil, err
	}

	b, err := blocks.NewBlockWithCid(data[0:size], bcid)
	if err != nil {
		return nil, err
	}

	if settings.Pin {
		defer api.blockstore.PinLock().Unlock()
	}

	err = api.blocks.AddBlock(b)
	if err != nil {
		return nil, err
	}

	if settings.Pin {
		api.pinning.PinWithMode(b.Cid(), pin.Recursive)
	}

	return &BlockStat{path: coreiface.IpldPath(b.Cid()), size: size}, nil
}
```

of course,  the length of  blockBufChan and every byte array in it can be configurable.

**Comment by Stebalien** [comment]
So, the issue is that the blockstore (and, well, literally every other component in the system) reserves the right to hang onto the block for as long as it wants (e.g., it might cache it). We _do_ want to do something like this eventually but that will likely require a large refactor of the interfaces (e.g., reference counted blocks, lifetimes, ownership, etc.).

**Comment by songjiayang** [comment]
> So, the issue is that the blockstore (and, well, literally every other component in the system) reserves the right to hang onto the block for as long as it wants (e.g., it might cache it). We _do_ want to do something like this eventually but that will likely require a large refactor of the interfaces (e.g., reference counted blocks, lifetimes, ownership, etc.).

right
