### ISSUE TITLE
why DNSlink bind failed? Is it design to be?

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#5992]
DNS bind ipns failure !!!!
I think this failure is related the issue in above post. Please advise.

working sample:

local gateway
http://127.0.0.1:8080/ipfs/QmcXbRoSrnmqwVFms3t9iX6DZMtKfUB9PJj6j8HQp59Ubj
http://127.0.0.1:8080/ipns/QmbX1mn42J9Fh7ascyaX2txtqRxRNFg3NWMXFr8k6HqKBj

publick gateway
https://ipfs.io/ipfs/QmcXbRoSrnmqwVFms3t9iX6DZMtKfUB9PJj6j8HQp59Ubj
https://ipfs.io/ipns/QmbX1mn42J9Fh7ascyaX2txtqRxRNFg3NWMXFr8k6HqKBj

Now I bind domain 'pdfbay.org' DNS txt record

@ means current domain pdfbay.org
TXT: type
1m: 1 second

@ | TXT | 1m | "dnslink=/ipns/QmbX1mn42J9Fh7ascyaX2txtqRxRNFg3NWMXFr8k6HqKBj"

Now the failure happened: (nothing shows)
http://localhost:8080/ipns/pdfbay.org
https://ipfs.io/ipns/pdfbay.org

**Comment by Stebalien** [comment]
It's working for me. It may have been an issue with DNS propagation time.

**Comment by Kubuxu** [comment]
The IPNS doesn't seem to be able to resolve (`/ipns/QmbX1mn42J9Fh7ascyaX2txtqRxRNFg3NWMXFr8k6HqKBj`) if you switch dnslink to `/ipfs/` it should work.

**Comment by Stebalien** [comment]
(it worked for me once...)

**Comment by Kubuxu** [comment]
On the other hand on my local machine I was able to resolve it:
```
ipfs name resolve -r /ipns/pdfbay.org                        
/ipfs/QmcXbRoSrnmqwVFms3t9iX6DZMtKfUB9PJj6j8HQp59Ubj
```

**Comment by Kubuxu** [comment]
I was also able to resolve it on gateway (after some time).

**Comment by Kubuxu** [comment]
I would say it was IPNS being IPNS and deciding to be slow. We are working on it.

**Comment by hoogw** [comment]
Yes, it works for me after 1 hour.  try and fail.

Let me summarize the working sample.
DNS bind ipns failure !!!!
I think this failure is related the issue in above post. Please advise.

working sample:


local gateway 
http://127.0.0.1:8080/ipfs/QmcXbRoSrnmqwVFms3t9iX6DZMtKfUB9PJj6j8HQp59Ubj
http://127.0.0.1:8080/ipns/QmbX1mn42J9Fh7ascyaX2txtqRxRNFg3NWMXFr8k6HqKBj

publick gateway
https://ipfs.io/ipfs/QmcXbRoSrnmqwVFms3t9iX6DZMtKfUB9PJj6j8HQp59Ubj
https://ipfs.io/ipns/QmbX1mn42J9Fh7ascyaX2txtqRxRNFg3NWMXFr8k6HqKBj


Now I bind domain 'pdfbay.org' DNS txt record 

@ means current domain pdfbay.org
TXT: type
1m:  1 second

@ | TXT | 1m | "dnslink=/ipns/QmbX1mn42J9Fh7ascyaX2txtqRxRNFg3NWMXFr8k6HqKBj"

Now the failure happened: (nothing shows)
http://localhost:8080/ipns/pdfbay.org
https://ipfs.io/ipns/pdfbay.org


 By the way,  on terminal, I try ipfs name resolve, it works fine:
https://ipfs.io/ipns/pdfbay.org

D:\>ipfs name resolve -r pdfbay.org
/ipfs/QmcXbRoSrnmqwVFms3t9iX6DZMtKfUB9PJj6j8HQp59Ubj

Never Mind, after a few hours try again, delete DNS, try again, 
It finally works. 

The working DNSlink bind to domain pdfbay.org as 

Note, Even you config correctly ,it need some time, may be up to 1 hours to have ipfs bind works, 


http://localhost:8080/ipns/pdfbay.org
https://ipfs.io/ipns/pdfbay.org
