### ISSUE TITLE
BUG: the length of the identity hash must be equal to the length of the data

### ISSUE THREAD

**Issue by ivan386** [ipfs/go-ipfs#6007]
#### Version information:
Version | "0.4.19-dev"
-- | --
Commit | "ef94a43e8"
Repo | "7"
System | "amd64/linux"
Golang | "go1.11.4"

#### Description:
I try to open this [link]( 
https://ipfs.io/ipfs/uAXAASxJFCjoBcAA2EjAKIhIg-BnibCPDDbicOSNiGB_lIYDbHBAGRwaLnjjbSOE-1ssSCjIwMTkuMDIuMjAKAggBEgdpcGZzLmlvCgIIAQ/):
```
https://ipfs.io/ipfs/uAXAASxJFCjoBcAA2EjAKIhIg-BnibCPDDbicOSNiGB_lIYDbHBAGRwaLnjjbSOE-1ssSCjIwMTkuMDIuMjAKAggBEgdpcGZzLmlvCgIIAQ/
```
And get this error:
```
ipfs cat /ipfs/uAXAASxJFCjoBcAA2EjAKIhIg-BnibCPDDbicOSNiGB_lIYDbHBAGRwaLnjjbSOE-1ssSCjIwMTkuMDIuMjAKAggBEgdpcGZzLmlvCgIIAQ/: the length of the identity hash (75) must be equal to the length of the data (77)
```
On other gateway [it works](https://cloudflare-ipfs.com/ipfs/uAXAASxJFCjoBcAA2EjAKIhIg-BnibCPDDbicOSNiGB_lIYDbHBAGRwaLnjjbSOE-1ssSCjIwMTkuMDIuMjAKAggBEgdpcGZzLmlvCgIIAQ/)

**Comment by Stebalien** [comment]
Fix part one: https://github.com/ipfs/go-cid/pull/84. However, I believe the problem is deeper. Do you remember how you ended up creating that object?

**Comment by Stebalien** [comment]
Ah, nevermind. I thought the data had gotten corrupted. It turns out we're just trying to recompute the CID somewhere and failing.

**Comment by ivan386** [comment]
> Do you remember how you ended up creating that object?

I use [js-ipfs-wrap-with-directory](https://github.com/ivan386/js-ipfs-wrap-with-directory) script to generate ID hash from file structure.

```
wrap_files_with_directory({
    "ipfs.io":{
        "2019.02.20" : "Qmf38iBq7nsjP3tBhppnpx61FMSPG5pbcbW6MTnYfnApcA"
    },
})
```
result
```
/ipfs/uAXAASxJFCjoBcAA2EjAKIhIg-BnibCPDDbicOSNiGB_lIYDbHBAGRwaLnjjbSOE-1ssSCjIwMTkuMDIuMjAKAggBEgdpcGZzLmlvCgIIAQ/
```

**Comment by Stebalien** [comment]
Got it. I just wanted to make sure go-ipfs wasn't generating really long inlined objects unless requested by the user.
