### ISSUE TITLE
IPLD requirements for go-ipfs

### ISSUE THREAD

**Issue by mikeal** [ipfs/go-ipfs#6014]
The IPLD team is trying to get a handle on our roadmap and plan for the next few quarters. go-ipfs is the primary consumer of Go IPLD interfaces and we’d like to get a good list of things go-ipfs needs over the next year or so.

**Comment by Stebalien** [comment]
* A nice format-agnostic (mostly) DAG mutation tool. Ideally, one that can queue up a bunch of changes while lazily computing hashes.
* A way to decode _arbitrary_ formats into a struct, possibly following links as necessary.
* Generics. Oh, wait, these were requests from IPLD, not go.
