### ISSUE TITLE
Boostrap nodes are blocked by GFW. How can I find a usable peer conveniently

### ISSUE THREAD

**Issue by blurHY** [ipfs/go-ipfs#6016]
Without manually adding a peer, IPFS will not work in China.
Finding a peer by oneself isn't convenient

**Comment by blurHY** [comment]
How can I set a proxy for the bootstrap nodes

**Comment by Stebalien** [comment]
Please don't open duplicate issues. Let's continue this discussion on https://github.com/ipfs/go-ipfs/issues/5993.
