### ISSUE TITLE
inappropriate ioctl for device

### ISSUE THREAD

**Issue by thomas92911** [ipfs/go-ipfs#6028]
Version: 0.4.19-rc1
Type: meta
OS: MacOS Mojave 10.14.3
Go Version: 1.12 darwin/amd64

Some commands such as `ipfs id` display an error at the end.

```
Error: sync /dev/stderr: inappropriate ioctl for device
```

**Comment by Stebalien** [comment]
Thanks for the report, we should have a fix in https://github.com/ipfs/go-ipfs-cmds/pull/147.

**Comment by thomas92911** [comment]
`ipfs swarm peers|grep *`  still has this problem.

**Comment by Stebalien** [comment]
1. Does that happen without the pipe?
2. Does that happen when piping to `cat`?

**Comment by michaelavila** [comment]
@Stebalien @thomas92911 I'm testing this with `0.4.19-rc2`, but see the same error for the same command:

```shell
$ ipfs swarm peers | grep "*"
Error: sync /dev/stdout: bad file descriptor
```

- I do not see the error when not piping to anything.
- I do not see the error when piping to cat.
- I do not see the error when using a different grep expression, e.g. `ipfs swarm peers | grep "/"`.

**Comment by michaelavila** [comment]
I actually see this behavior with any grep that does not produce a result, e.g.:

```shell
$ ipfs swarm peers | grep "blarg"
Error: sync /dev/stdout: bad file descriptor
```
