### ISSUE TITLE
https://ipfs.io/ipfs/Qm.....   Why Failed All Time?

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#6033]
Try this link

[https://transparentgov.net/json2tree/ipfsList.html](https://transparentgov.net/json2tree/ipfsList.html)

I list 4 gateway by their logo-icon, click any ipfs-icon, 
ipfs.io often failed, however, infura.io is fastest load file. 

Cloud-flare.com is second fast, but often get 505- time out error when load PDF.
All 4 gateway pull files from the same resource, same computer, same ipfs daemon. 
There is only 1 computer hosting all above files. 

why ipfs.io often failed? why the gateway speed difference of 4 gateway?

**Comment by hoogw** [comment]
also, if you have a ipfs daemon instance running? 
could it speed up the loading in browser?

Without ipfs daemon running, only click above test link, it will be slow, correct?

If you have a ipfs daemon, running, when you click above link, 
in your browser, all public gateway will automatically change to https://127.0.0.0:8080/ipfs.......

Why this happen? how it works?

**Comment by LetItGlow** [comment]
I can browse just fine, the URL doesn't get replaced with the local gateway.
Do you use a browser addon like "IPFS Companion"?

**Comment by hoogw** [comment]
Yes, Chrome add a IPFS-extension add-on. It will auto use local gateway. 
FIrefox also have a add-on.

**Comment by Stebalien** [comment]
So, gateways _cache_ content. In this case, it looks like CloudFlair had already cached the content but ipfs.io hadn't.

I'm not sure if there's anyone on the network providing that content (or at least a significant portion of it). I'm having trouble finding online providers even on my local machine using a local IPFS node.

**Comment by Stebalien** [comment]
Closing as I'm pretty sure this is just an issue of the content not being available. Feel free to continue discussing.
