### ISSUE TITLE
IPNS resolve fails using ECC key

### ISSUE THREAD

**Issue by reardenlife** [ipfs/go-ipfs#6043]
ipfs v.0.4.19-dev

I installed ipfs on server #1, generated ECC key and published some content on IPNS using that key.  Content resolves OK, although with a huge lag:

```sh
[root@v48807 dompoc]# ipfs key list -l
QmQBojsRJJrwvqDdbmWbmbZ7GCTnhHmzri5DhEqLP2zVXq self
QmafEdQrhntRYzKu3V2Mn4Rd21Px9Hpfgbw6YBvCNJyDJH addr1
QmVHUFuEj1v8YvWKS3p5NHNdZy66Ds4bLevt8KrbPPgWHh addr2
QmafEdQrhntRYzKu3V2Mn4Rd21Px9Hpfgbw6YBvCNJyDJH mykey
[root@v48807 dompoc]# date && ipfs name resolve /ipns/QmafEdQrhntRYzKu3V2Mn4Rd21Px9Hpfgbw6YBvCNJyDJH && date
Sun Mar  3 22:21:26 MSK 2019
/ipfs/QmaKVGFUQtGFfschpohWmWicmZwUPeTHLu74kymn3vupBj
Sun Mar  3 22:22:26 MSK 2019
```

Then I installed ipfs on a different server and tried to resolve that IPNS path and failed.  Although the node itself (see above, the <b>self</b> key) is available:

```bash
[root@329020 ipfs]# date && ipfs name resolve /ipns/QmafEdQrhntRYzKu3V2Mn4Rd21Px9Hpfgbw6YBvCNJyDJH || date
Sun Mar  3 19:31:46 UTC 2019
Error: could not resolve name
Sun Mar  3 19:32:47 UTC 2019
[root@329020 ipfs]# ipfs ping QmQBojsRJJrwvqDdbmWbmbZ7GCTnhHmzri5DhEqLP2zVXq
PING QmQBojsRJJrwvqDdbmWbmbZ7GCTnhHmzri5DhEqLP2zVXq.
Pong received: time=166.36 ms
Pong received: time=125.47 ms
Pong received: time=32.16 ms
Pong received: time=79.04 ms
Pong received: time=160.03 ms
Pong received: time=85.26 ms
Pong received: time=189.14 ms
Pong received: time=134.40 ms
Pong received: time=81.88 ms
Pong received: time=1.53 ms
Average latency: 105.53ms
```

Interestingly, the resolution of an address generated by using the <b>self</b> key (RSA) works fine:

```bash
[root@329020 ipfs]# date && ipfs name resolve  /ipns/QmQBojsRJJrwvqDdbmWbmbZ7GCTnhHmzri5DhEqLP2zVXq && date
Sun Mar  3 19:41:26 UTC 2019
/ipfs/QmaKVGFUQtGFfschpohWmWicmZwUPeTHLu74kymn3vupBj
Sun Mar  3 19:41:36 UTC 2019
```

I am not sure what to do at this point and how to debug it.  Any help will be appreciated.

**Comment by reardenlife** [comment]
The whole thing is quite funny, because a while ago it was working: https://github.com/libp2p/libp2p/issues/62#issuecomment-449876488

The only difference now is that I didn't build ipfs from scratch, but copied the compiled binary from the source server.  And the second server geographically situated farther right now.  So it should not matter.

The main question is how to debug it.

I looked into the config and realized that the "self" key is situated there.  I am not sure if I can just put my ECC key there.  Let me try.

**Comment by reardenlife** [comment]
It appears to me that there might be a problem related to the availability of public keys: https://github.com/libp2p/go-libp2p-kad-dht/issues/139#issuecomment-394335969
But in my case, since the version of ipfs is 0.4.19 and it calculates peerid differently than the latest stable one (namely, it does NOT embed the short public keys), it seems that the majority of nodes spit out my ipns record as invalid one.

How I can make sure that this is the case?

**Comment by reardenlife** [comment]
Hm...

###--enable-namesys-pubsub

Got it working with above option enabled.

**Comment by lordcirth** [comment]
IPNS records have the `--lifetime` option, after which they are invalid.

**Comment by reardenlife** [comment]
@lordcirth 

Good.
So you are proposing to use short lifetimes?
If so, in this case the node should be constantly online to re-publish something on IPNS. So once it goes offline, the other nodes are unable to retrieve the content from node's IPNS path?..

**Comment by lordcirth** [comment]
The settings you want depend on whether it's better to resolve an old value or fail. A long lifetime but short ttl will mean that resolves will frequently take the full 60 seconds, but will fall back to an old value if that's all that's available.

**Comment by lidel** [comment]
Closing (ed25519 been the default for a while, no issues)
