### ISSUE TITLE
large 277GB, with sub-folder very likely failed, time out, very slow, why?

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#6048]
Try my sample:
[https://transparentgov.net/json2tree/ipfsList.html](https://transparentgov.net/json2tree/ipfsList.html)

For large  277GB, ( click 'Los Angeles County Land Records' ), it extremely slow, specially more level of sub-folder, you are more likely to get 505 time out error, 524 time-out, fail. 

277GB - (  'Los Angeles County Land Records' ), very likely failed, time out, very slow.

33GB- ( Los Angeles City Engineering Land Records), possible fail.

For only 0-1 level sub-folder , it is fast, and not likely fail. (all Others than Los Angeles)

**Comment by Stebalien** [comment]
Already answered in https://github.com/ipfs/go-ipfs/issues/6033.
