### ISSUE TITLE
How to set  node<peer ID> with higher priority for specific <hash-key>?

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#6053]
My workplace node (upload 800Mbps),  my home(upload 10Mbps) node.
Both host the same content. 
[https://transparentgov.net/json2tree/ipfsList.html](https://transparentgov.net/json2tree/ipfsList.html)

slow node always been used, even the fast node available. 
I want to use fast node first.
Can I specify the fast(high bandwidth) node have higher priority? 

I try:    ipfs dht provide hash-key...

But it does not work. 

What this command really does?
Does it inform IPFS that, my node peer-ID provide this hash-key...?

How to set  node peer-ID with higher priority for specific hash-key...?

**Comment by Stebalien** [comment]
Please stop filing duplicate issues.
