### ISSUE TITLE
Can't retrieve raw nodes using the dag cli/http api

### ISSUE THREAD

**Issue by achingbrain** [ipfs/go-ipfs#6076]
I can add and fetch a CBOR node via the CLI:

```console
$ echo -e "\xa1\x63\x66\x6f\x6f\x63\x62\x61\x72" | ipfs block put --format=cbor
zdpuAspUFE9aaNm5FQB5T3jXig5xDuzRPYGqswYPrZbJHbCqz
$ ipfs dag get zdpuAspUFE9aaNm5FQB5T3jXig5xDuzRPYGqswYPrZbJHbCqz
{"foo":"bar"}
```

But if I add the same data as a raw node I can't get the data back:

```console
$ echo -e "\xa1\x63\x66\x6f\x6f\x63\x62\x61\x72" | ipfs block put --format=raw
zb2rhe3JxU16E17kG3GSnUW5paVwzNrnpFwLCiQPRbeediA8t
$ ipfs dag get zb2rhe3JxU16E17kG3GSnUW5paVwzNrnpFwLCiQPRbeediA8t
{"Block":{}}
```

Since it's a raw node I would have expected to to just blurt out the raw data and (potentially) make my console go all weird in the same way as the block api:

```console
$ ipfs block get zb2rhe3JxU16E17kG3GSnUW5paVwzNrnpFwLCiQPRbeediA8t
?cfoocbar
```

Is this intentional?

#### Version information:

```console
$ ipfs version --all
go-ipfs version: 0.4.19-dev-481136b
Repo version: 7
System version: amd64/darwin
Golang version: go1.11.2
```

**Comment by Stebalien** [comment]
No, this is because our current IPLD implementation doesn't currently have a nice way to translate between node types. Quick fix: https://github.com/ipfs/go-ipfs/issues/6076. Longer term fix requires https://github.com/ipld/go-ipld-prime.
