### ISSUE TITLE
ipfs dns throws Error: could not resolve name (recursion limit exceeded)

### ISSUE THREAD

**Issue by niinpatel** [ipfs/go-ipfs#6086]
#### Version information:
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/windows
Golang version: go1.11.1

#### Description:

run `ipfs dns ipfs.io` on the terminal 

OR go to: https://ipfs.io/api/v0/dns?arg=ipfs.io

Both are showing the exact same error so I assume they're coming from the same place. 

Expected behavior is that it should give an ipns path something like `/ipns/website.ipfs.io`

**Comment by zicmama** [comment]
"ipfs name resolve" run into the same error
Error: could not resolve name (recursion limit exceeded)

The Site_ID is containing 1446 directories and 39254 sub CID in total...
Where is the limit? 

It opens in web browser (DNSLink procedure) but every directory is 404.

**Comment by Stebalien** [comment]
@zicmama please file a new issue (and include additional information like your IPFS version).
