### ISSUE TITLE
Unpinning unixfs files will unpin shared blocks

### ISSUE THREAD

**Issue by hinshun** [ipfs/go-ipfs#6124]
#### Type:
- "feature": If you'd like to suggest a feature.
- "enhancement ": If you'd like to suggest an improvement on to existing feature.

#### Description:
Suppose I have files `foo` and `bar` over 4MB each added to IPFS as unixfs nodes with some block deduplication. I can choose to recursively pin the root ipld node and its children.

When I want to unpin `foo` and allow the chunked blocks to be GC'ed, I will also unpin shared blocks with `bar`. Is there a way to only unpin the root and allow GC to figure out what is still referenced?

**Comment by Kubuxu** [comment]
@hinshun if `foo` and `bar` are pinned recursively (ipfs pin add default behaviour) removing pin of one will not un-pin shared blocks.
