### ISSUE TITLE
webui dont show any files

### ISSUE THREAD

**Issue by icf20** [ipfs/go-ipfs#6131]
go-ipfs version: 0.4.19-83d3f7672

![image](https://user-images.githubusercontent.com/17784575/55030646-1d6d2580-500d-11e9-9eb0-d7da2b547d85.png)

![image](https://user-images.githubusercontent.com/17784575/55030691-2cec6e80-500d-11e9-9996-1d1606346056.png)

so where are those 11 mb in files?

**Comment by icf20** [comment]
i pinned the image above and still i get no files in the webui

**Comment by magik6k** [comment]
This UI only shows files under `ipfs files`, which is a set of commands which expose unix-like mutable file system (MFS).

You should be able get things to show up there by doing `ipfs files cp /ipfs/QmThing /SomeFileName`

Perhaps there should be a note saying that it works this way, cc @olizilla

**Comment by Mikaela** [comment]
I had often been wondering about this too. Will other files be shown there in the future?

**Comment by Mikaela** [comment]
I think my question is https://github.com/ipfs/go-ipfs/issues/4763, https://github.com/ipfs/ipfs-gui/issues/10#issuecomment-373928862 & https://github.com/ipfs/go-ipfs/issues/4586
