### ISSUE TITLE
ipfs add --nocopy <url> fails with "Error: urlstore not enabled" for big files

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipfs#6139]
#### Version information: master
go-ipfs version: 0.4.20-dev-1682880df
Repo version: 7
System version: amd64/linux
Golang version: go1.11.4
#### Description:

I understand that `urlstore` does not need to be enabled for `add --nocopy <url>`, and it seems so for small files, but I get this more or less consistently:

```
ipfs add --nocopy https://dist.ipfs.io/ipfs-cluster-service/v0.10.0-rc1/ipfs-cluster-service_v0.10.0-rc1_linux-amd64.tar.gz
 8.50 MiB / 14.46 MiB [==========================================>------------------------------]  58.80% 00m15sError: urlstore is not enabled
Error: urlstore is not enabled
```

When I reproduce it, it happens at 8.50MB consistently.

**Comment by jmank88** [comment]
Do you have `filestore` enabled?
Perhaps some checks are too strict, and only need to check for `filestore`?

**Comment by hsanjuan** [comment]
filestore is enabled, urlstore not.

**Comment by jmank88** [comment]
I was just able to add that same file to nodes with filestore (and without urlstore), via both a direct `ipfs add --nocopy` and via my branches `ipfs-cluster-ctl add --nocopy`. :confused:

**Comment by jmank88** [comment]
But the code suggests that the only way to `AllowURLs` is with `urlstore`:
https://github.com/ipfs/go-ipfs/blob/master/repo/fsrepo/fsrepo.go#L181

**Comment by Stebalien** [comment]
> I understand that urlstore does not need to be enabled for add --nocopy <url>, and it seems so for small files, but I get this more or less consistently:

The urlstore _does_ need to be enabled for that to work. I believe you're _not_ seeing this error for small files because there's a bug: https://github.com/ipfs/go-ipfs/issues/6139#issue-425982186 (we're not handling block put errors).

`ipfs add` actually has two checks:

1. When processing the flags, we check if the filestore is enabled if the user passes the no-copy flag.
2. When adding chunks to the filestore, we check if the filestore/urlstore (AllowUrls/AllowFiles) is enabled.

Really, I think the only sane solution is to remove the up-front filestore check. We can't actually know if we're going to be handling URLs or local files until we actually start processing the files to be added.

**Comment by jmank88** [comment]
> Really, I think the only sane solution is to remove the up-front filestore check. We can't actually know if we're going to be handling URLs or local files until we actually start processing the files to be added.

I'm testing this, and it appears the the `--nocopy` flag is silently ignored when this check is removed and neither `filestore` or `urlstore` is enabled.

What about something like:
```diff
-if settings.NoCopy && !cfg.Experimental.FilestoreEnabled {
+if settings.NoCopy && !cfg.Experimental.FilestoreEnabled && !cfg.Experimental.UrlstoreEnabled {
-	return nil, filestore.ErrFilestoreNotEnabled
+	return nil, filestore.ErrNoCopyNotEnabled
}
...
+var ErrNoCopyNotEnabled = errors.New("nocopy requires urlstore or filestore")
```

**Comment by Stebalien** [comment]
You _sure_ that's not https://github.com/ipfs/go-ipfs/issues/6139#issue-425982186?

**Comment by hsanjuan** [comment]
> You _sure_ that's not [#6139 (comment)](https://github.com/ipfs/go-ipfs/issues/6139#issue-425982186)?

wrong link @Stebalien (links to this issue)?

**Comment by jmank88** [comment]
I think https://github.com/ipfs/go-ipfs/pull/6140#discussion_r269610708 needs some more work, but even an modified version doesn't error out. The `--nocopy` flag isn't completely ignored though. `DagBuilderHelper.fullpath` is still set, which should trigger creation of a `FilestoreNode`, but apparently that isn't a problem?

**Comment by Stebalien** [comment]
Yeah, I meant https://github.com/ipfs/go-ipfs/pull/6140#discussion_r269610708. And yes, @jmank88 is correct.
