### ISSUE TITLE
ERROR  basichost: DiscoverNAT error: no NAT found natmgr.go:96

### ISSUE THREAD

**Issue by Mikaela** [ipfs/go-ipfs#6142]
#### Version information:

go-ipfs version: 0.4.20-dev 1682880df
Repo version: 7
System version: amd64/linux
Golang version: go1.11.5

#### Description:

When I start ipfs via systemd, I see `Mar 27 18:00:30 sedric ipfs[638]: 18:00:30.087 ERROR  basichost: DiscoverNAT error: no NAT found natmgr.go:96` in `journalctl -u ipfs`. I thought that I would report it just in case, even if it doesn't seem to affect IPFS functioning any way.

I don't understand the error and I am definitely behind Carrier Grade NAT. I think this error didn't happen on [0.4.19](https://github.com/ipfs/go-ipfs/releases/tag/v0.4.19) where I upgraded from due to #6070.

**Comment by Kubuxu** [comment]
It shouldn't be on the error level.

**Comment by Stebalien** [comment]
Yeah, this should definitely be at the info level.

**Comment by Stebalien** [comment]
(note: this _actually_ means we didn't find a NAT we could portmap with...)

**Comment by Stebalien** [comment]
https://github.com/libp2p/go-libp2p/pull/568

**Comment by tangray** [comment]
i want to  know how to solve this problem ,can you give me a solution?

**Comment by Stebalien** [comment]
This was a noisy error that has been fixed in v0.4.20. Please upgrade.
