### ISSUE TITLE
OOM with 7G MemoryMax

### ISSUE THREAD

**Issue by mcamou** [ipfs/go-ipfs#6143]
#### Version information:
go-ipfs version: 0.4.19-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.5

#### Type:
bug

#### Description:
We are using IPFS in production with badgerds (private swarm). We have noticed very high memory usage. In the systemd unit file we set MemoryMax to 7G. ipfs keeps getting killed due to OOM. On one of our servers it gets killed at least once a day, on another one it's every 2 minutes (the API doesn't even have a chance to come up).

We started fresh on the one that was crashing every 2 minutes, replacing badgerds with the file-based store (all objects were already elsewhere in the swarm) and the memory usage is a LOT lower.

Here are the repo stats from the one that crashes at least once a day:

```
$ ipfs repo stat --human
NumObjects: 132289
RepoSize (MiB): 12410
StorageMax (MiB): 976562
RepoPath: /data/ipfs/repo
Version: fs-repo@7
```

I was also able to get the files from the [debug guide](https://github.com/ipfs/go-ipfs/blob/master/docs/debug-guide.md), once this morning and once 7 hours later. I am attaching them in case they are useful for debugging this. At the moment the `ipfs` process is eating up 4443M RES, 18.2 VIRT, 154M SHR.

[ipfs_stats.zip](https://github.com/ipfs/go-ipfs/files/3014743/ipfs_stats.zip)

**Comment by Stebalien** [comment]
Unfortunately, badger is known to eat memory like nothing else. It's one of the key reasons we haven't made it the default.

**Comment by Stebalien** [comment]
@mcamou the latest release includes some badger improvements that significantly reduce memory usage. Could you try again?

**Comment by Stebalien** [comment]
(closing due to age, please comment if this is still an issue with 0.4.21)
