### ISSUE TITLE
"ipfs add"  and "ipfs files write" the difference between the two

### ISSUE THREAD

**Issue by VKingi** [ipfs/go-ipfs#6159]
1. When I use commands:
~~~sh
 ipfs add test.mp4
~~~
hash value: QmS2sz7WNaVMDbbuBdzLVNVXwtWsNyNs3S4KjFaYY87aAV 

2. When I use commands:
~~~sh
cat test.mp4 | ipfs files write --create /test/test.mp4
~~~
hash value: QmazXU4S74VbLjqLouNMuJhKnWp5XKnyp7qqLnRmD3WLgu

> Obviously the two hash values are different,But when I used "ipfs get $hashValue" to download the files, I found they were identical

My question:
1. Why are they different?
2. Why are there two ways to add files, and the difference between them?

All these problems have been bothering me, but I still haven't found the result. Please help me, thanks.

**Comment by Stebalien** [comment]
I'd be happy to answer your question on [discuss.ipfs.io](https://discuss.ipfs.io) or on the #ipfs freenode IRC channel (you can flag me down by mentioning "@stebalien").

**Comment by VKingi** [comment]
Is it because I'm not good at English that you don't understand me?

**Comment by Stebalien** [comment]
It's just our policy to keep the noise down on this issue tracker.

> 🔥❓If you have a *QUESTION* about IPFS, please ask on our forum at https://discuss.ipfs.io 🔥❓
