### ISSUE TITLE
Symbolic Links

### ISSUE THREAD

**Issue by mildred** [ipfs/go-ipfs#616]
Symbolic links are not implemented. `ipfs add -r` on a directory containing a symlink to a directory will fail.

You can reproduce it using:

    mkdir -p a/b
    ln -s b a/c
    touch a/b/c
    ipfs add -r a

You get:

    Error: Post http://127.0.0.1:5001/api/v0/add?encoding=json&r=true&stream-channels=true: read a/c: is a directory

I think I also got `ipfs add -r` to stop in the middle of adding because of that. At some point, it would just stop and not continue. Running stat, I found that it thought that the symlink to a directory was a file, and tried to read it:

    open("root/ckeditor/plugins/openlink", O_RDONLY|O_CLOEXEC) = 5
    read(5, 0xc208130000, 32768)            = -1 EISDIR (Is a directory)
    epoll_wait(4, {}, 128, 0)               = 0
    futex(0xf2e878, FUTEX_WAIT, 0, NULL)    = 0
    futex(0xf2da30, FUTEX_WAKE, 1)          = 1
    ...

The normal sequence for a directory would be:

    open("root/ckeditor/plugins/newpage/lang", O_RDONLY|O_CLOEXEC) = 5
    getdents64(5, /* 68 entries */, 4096)   = 2160
    getdents64(5, /* 0 entries */, 4096)    = 0
    lstat("root/ckeditor/plugins/newpage/lang/fa.js", {st_mode=S_IFREG|0644, st_size=235, ...}) = 0
    ...

We should implement symbolic links in the unixfs protocol buffer object.

**Comment by mildred** [comment]
As far as ipfs add is concerned, we could do two things:

- follow symlinks as if they were the target file (this is what we do currently apart from the bug above)
- insert symlinks as such in the unixfs DAG

In any case, I think this should be configurable by a command line switch. Just like we have `cp --no-dereference` and `cp --dereference`

**Comment by jbenet** [comment]
> ```
Error: Post http://127.0.0.1:5001/api/v0/add?encoding=json&r=true&stream-channels=true: read a/c: is a directory
```
@mappum we shouldn't show that url in the error o/


Agreed with your analysis @mildred, as discussed in #620 let's:

- Default to inserting symlinks into `unixfs` (like git does)
- Option to follow symlinks. whatever is most common in other unix utils.

**Comment by diasdavid** [comment]
@whyrusleeping Can we make getting symlinks working a priority?

**Comment by whyrusleeping** [comment]
@diasdavid sure thing.

**Comment by whyrusleeping** [comment]
Kachow!

**Comment by diasdavid** [comment]
:boom: :D
