### ISSUE TITLE
lost packages go-mfs and go-unixfs in master

### ISSUE THREAD

**Issue by ivan386** [ipfs/go-ipfs#6170]
#### Description:
gx cant download packages:
QmNQtvcJon7xo5V8DMn6MEKMFMCeXnKUNdtGC2NwGYkqk1 go-mfs
QmVmueix5wxmr8UWpfpcKw6F1xT7T8AS7CXQRM37BE29eX go-unixfs

**Comment by Stebalien** [comment]
I've re-pinned these on cluster.

Note: We no longer support building go-ipfs with `gx`. We now use go modules.
