### ISSUE TITLE
Allow /wss/ addresses to be announced.

### ISSUE THREAD

**Issue by BenLubar** [ipfs/go-ipfs#6173]
#### Version information:
```
go-ipfs version: 0.4.20-dev-81b1cfead
Repo version: 7
System version: amd64/linux
Golang version: go1.12.1
```

#### Type:
enhancement

#### Description:
I'm running a websocket node on `/dns4/ipfs.local.lubar.me/tcp/443/wss/ipfs/QmRWvGqZPFzWMQWpkdRXXRtwMx56oKoizen2PaSLeZDgLH`, but there is no way to announce this as go-ipfs doesn't support TLS on websockets.

It would be nice to add `wss` as a dummy protocol just so the node could announce itself.

**Comment by Stebalien** [comment]
See: https://github.com/multiformats/go-multiaddr/issues/64

**Comment by Stebalien** [comment]
It is now possible to announce these addresses (although go-ipfs won't actually listen on them so you'll need to stick a reverse proxy out in front.
