### ISSUE TITLE
ipfs add -r .... error......

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#6202]
v0.4.16

mac error:  
........
added QmR4MQdiLL99HuALaH5u9aPWFbkVWv6kjb7DswV44K2nnm Los_Angeles_County_Land_Records/landrecords/Sewer_Plans/PC/PC09000/PC09419.PDF
 127.15 GiB / 277.90 GiB [================>-------------------]  45.76% 3h33m07sError: open /Volumes/d/ipfs_repo/blocks/BJ/put-052381753: too many open files
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x171ded8]

goroutine 24 [running]:
os.(*File).Name(...)
	/home/why/go/src/os/file.go:49
gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs.(*Datastore).writeDiskUsageFile.func1(0xc420382e0f, 0x0)
	/build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs/flatfs.go:875 +0x38
gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs.(*Datastore).writeDiskUsageFile(0xc42013b0a0, 0x1fc595f777, 0x1)
	/build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs/flatfs.go:880 +0x152
gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs.(*Datastore).checkpointLoop(0xc42013b0a0)
	/build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs/flatfs.go:837 +0x217
created by gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs.Open
	/build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs/flatfs.go:261 +0x245
phoenixs-imac:~ phoenix$

**Comment by Stebalien** [comment]
0.4.16 is quite out of date. Please update to 0.4.19.
