### ISSUE TITLE
internalWebError: operation not supported

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/go-ipfs#6203]
#### Version information:

```yaml
go-ipfs version: 0.4.20-rc1-4fd81e373-dirty
Repo version: 7
System version: amd64/linux
Golang version: go1.12.2
```

#### Description:

When I try to access [this hash](http://127.0.0.1:8080/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD) specifically, I get `internalWebError: operation not supported`. It also happens with plenty other public nodes.

The hash was found here : https://github.com/ipfs/package-managers/issues/18#issuecomment-475227762

#### Affected

* https://gateway.ipfs.io/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD
* https://gateway.pinata.cloud/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD
* https://gateway.serph.network/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD
* https://ipfs.eternum.io/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD
* https://ipfs.greyh.at/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD
* https://ipfs.infura.io/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD
* https://ipfs.io/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD
* https://ipfs.sloppyta.co/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD
* https://ipfs.wa.hle.rs/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD

#### Ok

* https://cloudflare-ipfs.com/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD
* https://ipfs.deo.moe/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD
* https://ipfs.jes.xxx/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD

**Comment by Stebalien** [comment]
Is that hash a symlink?

**Comment by magik6k** [comment]
It's a HAMT sharded directory. Try running `ipfs config --json Experimental.ShardingEnabled true` and restarting the daemon.

**Comment by Stebalien** [comment]
@magik6k doesn't _reading_ a sharded directory work without enabling the sharding experiment? If not, we should probably make it work.

**Comment by NatoBoram** [comment]
Here's parts of my settings.

```json
	"Experimental": {
		"FilestoreEnabled": true,
		"Libp2pStreamMounting": true,
		"P2pHttpProxy": true,
		"QUIC": true,
		"ShardingEnabled": true,
		"UrlstoreEnabled": true
	}
```

```json
		"DisableBandwidthMetrics": false,
		"DisableNatPortMap": false,
		"DisableRelay": false,
		"EnableAutoNATService": true,
		"EnableAutoRelay": true,
		"EnableRelayHop": true
```

Pretty much everything else was left as default + badgerds.

**Comment by Stebalien** [comment]
Is there a peer providing this file that I could connect to?

**Comment by senden9** [comment]
Hi!
I think I have the same issue. What I try to do is to implement some kind of mirror of the archlinux package archive.
To do this I created a local mirror of the archlinux archive. This gives me some directories full of symlinks. See `/core/cos/x86_64` for example:
```
$ exa -lha /srv/pacman-mirror/repo/core/os/x86_64 | head
Permissions Size User    Date Modified Name
lrwxrwxrwx    53 stefano 21 Jun  2018  acl-2.2.53-1-x86_64.pkg.tar.xz -> ../../../pool/packages/acl-2.2.53-1-x86_64.pkg.tar.xz
lrwxrwxrwx    57 stefano 21 Jun  2018  acl-2.2.53-1-x86_64.pkg.tar.xz.sig -> ../../../pool/packages/acl-2.2.53-1-x86_64.pkg.tar.xz.sig
lrwxrwxrwx    66 stefano 17 Aug 14:35  amd-ucode-20190815.07b925b-1-any.pkg.tar.xz -> ../../../pool/packages/amd-ucode-20190815.07b925b-1-any.pkg.tar.xz
lrwxrwxrwx    70 stefano 17 Aug 14:35  amd-ucode-20190815.07b925b-1-any.pkg.tar.xz.sig -> ../../../pool/packages/amd-ucode-20190815.07b925b-1-any.pkg.tar.xz.sig
lrwxrwxrwx    66 stefano 29 Aug 20:49  archlinux-keyring-20190827-1-any.pkg.tar.xz -> ../../../pool/packages/archlinux-keyring-20190827-1-any.pkg.tar.xz
lrwxrwxrwx    70 stefano 29 Aug 20:49  archlinux-keyring-20190827-1-any.pkg.tar.xz.sig -> ../../../pool/packages/archlinux-keyring-20190827-1-any.pkg.tar.xz.sig
lrwxrwxrwx    58 stefano  4 Jul 17:11  argon2-20190702-1-x86_64.pkg.tar.xz -> ../../../pool/packages/argon2-20190702-1-x86_64.pkg.tar.xz
lrwxrwxrwx    62 stefano  4 Jul 17:11  argon2-20190702-1-x86_64.pkg.tar.xz.sig -> ../../../pool/packages/argon2-20190702-1-x86_64.pkg.tar.xz.sig
lrwxrwxrwx    54 stefano 21 Jun  2018  attr-2.4.48-1-x86_64.pkg.tar.xz -> ../../../pool/packages/attr-2.4.48-1-x86_64.pkg.tar.xz
```

I can access this path via the ipfs-webui and see all files listed that are also on my local drive.
![image](https://user-images.githubusercontent.com/905857/65317828-cfd90c00-db9c-11e9-9129-92d0ee2dbe58.png)

But I can not look at this folder with one of the following link:

* http://127.0.0.1:8080/ipfs/QmZa8Vn963WnVwFKSmZ2Rx9GqHHs4jQpyh1UdAP6W64Us3/repo/core/os/x86_64
* https://ipfs.io/ipfs/QmZa8Vn963WnVwFKSmZ2Rx9GqHHs4jQpyh1UdAP6W64Us3/repo/core/os/x86_64
* https://cloudflare-ipfs.com/ipfs/QmZa8Vn963WnVwFKSmZ2Rx9GqHHs4jQpyh1UdAP6W64Us3/repo/core/os/x86_64

Here I get `internalWebError: operation not supported` for each of the three requests.

But I can list that files via the cli tool:
```
ipfs ls -v /ipfs/QmZa8Vn963WnVwFKSmZ2Rx9GqHHs4jQpyh1UdAP6W64Us3/repo/core/os/x86_64 | head
Hash                                           Size   Name
QmZ5EpzSj4fngmcnR5DSWkr72AfwSAGKy3ee4MAMxshpoP 0      acl-2.2.53-1-x86_64.pkg.tar.xz
QmVDYD4pcEsbnAhBebC8pCVz5LbAUbKUMgqi9r5pUDcfUF 0      acl-2.2.53-1-x86_64.pkg.tar.xz.sig
QmQNBknk2PeABfHgizJjYwsctcoJPuWAuy3WiJUDEagm56 0      amd-ucode-20190815.07b925b-1-any.pkg.tar.xz
QmfNNUW7WKbqDkA54B3xZv1KW9E4rcqiuvSiChW6HfKjdd 0      amd-ucode-20190815.07b925b-1-any.pkg.tar.xz.sig
QmbexeDpPzCudv26TWCbpjwe6heiCbzcuhtHgULAKp3BQm 0      archlinux-keyring-20190827-1-any.pkg.tar.xz
QmamUDcybMFd6BTRFGmdGvykwNrHoj2cS6mLnduZT4jc7K 0      archlinux-keyring-20190827-1-any.pkg.tar.xz.sig
QmZ7DpDXSXbbfarcJtVuiTS6eff8abjn65JaLdmfZb3yA1 0      argon2-20190702-1-x86_64.pkg.tar.xz
QmeHkEG7dTmN3tLCxD5PbN2swdi2FQo9sHKaH1qoRH9Rm1 0      argon2-20190702-1-x86_64.pkg.tar.xz.sig
QmVmWy7uDf4tSB8rrMiUhGn4SMUC3KJPx8hNRyotpyqeNf 0      attr-2.4.48-1-x86_64.pkg.tar.xz
```

But I can not look into any of that files. 
```
ipfs cat /ipfs/QmZa8Vn963WnVwFKSmZ2Rx9GqHHs4jQpyh1UdAP6W64Us3/repo/core/os/x86_64/acl-2.2.53-1-x86_64.pkg.tar.xz.sig   
Error: operation not supported
```
I can look at the direct location where the symlink is pointing to.
```
ipfs cat /ipfs/QmZa8Vn963WnVwFKSmZ2Rx9GqHHs4jQpyh1UdAP6W64Us3/repo/pool/packages/acl-2.2.53-1-x86_64.pkg.tar.xz.sig                                                             :(
(Some binary garbage)
```

If you want to try a reproduction of that bug(?) feel free to connect to my node via `ipfs swarm connect /dns6/stefano-probst.com/tcp/4001/ipfs/QmbNqjDtCbSWgzGzKVDpuj5JaFGSQCRQHQvG5FjweatdoQ` :)

**Comment by Stebalien** [comment]
Ah. So, the issue is that:

1. That directory contains a bunch of symlinks.
2. Those symlinks don't have sizes.
3. We error out because a file doesn't have a size.
