### ISSUE TITLE
ipfs add -r .... error again....

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#6205]
I have tried v0.4.16 error out. 

Now update to v0.4.19 get same error, 

I heard v20 have fixed some bugs. 
When v0.4.20 release?

ERROR:

added QmR4MQdiLL99HuALaH5u9aPWFbkVWv6kjb7DswV44K2nnm Los_Angeles_County_Land_Records/landrecords/Sewer_Plans/PC/PC09000/PC09419.PDF
127.15 GiB / 277.90 GiB [================>-------------------] 45.76% 3h33m07sError: open /Volumes/d/ipfs_repo/blocks/BJ/put-052381753: too many open files
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x171ded8]

goroutine 24 [running]:
os.(*File).Name(...)
/home/why/go/src/os/file.go:49
gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs.(*Datastore).writeDiskUsageFile.func1(0xc420382e0f, 0x0)
/build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs/flatfs.go:875 +0x38
gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs.(*Datastore).writeDiskUsageFile(0xc42013b0a0, 0x1fc595f777, 0x1)
/build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs/flatfs.go:880 +0x152
gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs.(*Datastore).checkpointLoop(0xc42013b0a0)
/build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs/flatfs.go:837 +0x217
created by gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs.Open
/build/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs/flatfs.go:261 +0x245

phoenixs-imac:~ phoenix$

**Comment by Kubuxu** [comment]
Can you post the output of `ulimit -a`?

**Comment by Stebalien** [comment]
@hoogw 

1. What go version.
2. Could I get a stack trace from 0.4.19, that's still the one from 0.4.16.

The out of file descriptors errors is one thing but this _really_ shouldn't be panicing.

**Comment by hoogw** [comment]
mac-mini:~ sirius$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 64000
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1064
virtual memory          (kbytes, -v) unlimited
mac-mini:~ sirius$ ulimit -n
64000
mac-mini:~ sirius$ 


-----------------------------------
those error are from Mac, 
now I try to run same again on a windows 10 pc.
It tooks 5 hours to add 120GB, to get ERROR. 
 

@Stebalien

1.What go version.
        I do not install any go, but I still can run ipfs add -r, ipfs daemon, ipfs desktop
        Do you know why?

2. Could I get a stack trace from 0.4.19, that's still the one from 0.4.16.
           It is running now, after 5 hours, if I get error on windows PC too, will post error here.

**Comment by hoogw** [comment]
mac, or PC, no one install any go, 
but I still can run ipfs without any problem. 

0.4.19 on mac error, I closed terminal without copy down. 
But I am getting 0.4.19 on PC error, if any after 5 hours.

Do I really need install go? to run ipfs? I never install any go, ipfs just works.

**Comment by Stebalien** [comment]
> I do not install any go

Nevermind. I thought you had built go-ipfs yourself.

---

Wait, so _have_ you seen this error in 0.4.19?

**Comment by hoogw** [comment]
To add  277GB los angeles county land record, pdf, 

I have try 0.4.19 on 2 mac, both error as too many files open......

I do this:
                        sudo nano .bash_profile

export IPFS_PATH=/Volumes/ipfs1/ipfs_repo
sudo launchctl limit maxfiles 65536 200000
        

same error, 


Then I downgrade to 0.4.16, because I success add 277GB before as 4.16.

Now, even 4.16 failed. 

last chance is I use windows 10 PC with 0.4.19, add 277GB again,

**Comment by hoogw** [comment]
stay tuned, I should get either error or success tonight on window 10 pc to add 277GB pdf.
I will post here either way.

**Comment by hoogw** [comment]
4 hours only add 34GB 12%, total need 1 day,  
ipfs_repo was put on an external HDD, via usb 2.0, 
maybe this is why it slow. 

I also shut down ipfs daemon, ipfs desktop, only let "ipfs add" run.......
But still slow,
Maybe CPU 1.6Hz and 8GB Ram DDR3 make it slow,   
I am not sure.  Hopefully tomorrow morning, I should have result.

**Comment by hoogw** [comment]
1 day  add 124GB, 44%, ..... so far no error

**Comment by Stebalien** [comment]
External hard drive over USB will definitely make things slower and so will the 1.6GHz CPU.

Just to confirm, you _haven't_ seen the _panic_ on go-ipfs 0.4.19. You've only seen the "too many open files" error. Correct?

**Comment by hoogw** [comment]
2 day add 244GB, 85%  no error, 
looks like windows 10 pc no problem.

I am going to re-try on mac after window PC finished.
mac previously error out, looks like I need to adjust config Mac to avoid error

**Comment by hoogw** [comment]
I really did see the panic on go-ipfs 0.4.19 ( on Mac ) many times, 
panic error is exactly the error that accidently shut down my ipfs-daemon process (Mac).

Because of this shut down of ipfs-daemon process (Mac) event,
this event trigger shut down another on going ipfs-add process.

So I decide to NOT run ipfs-daemon, only run 1 process ipfs-add.

when I run only 1 process ipfs-add

both 2 time error, see too many files....
but only 1 time error, see panic ..........

=======================

I am going to re-create the error on Mac again in the next week, to copy and past the error message here.

So far ipfs-add on window 10 pc, without any problem, after it finish, 
I will try again on mac. 

here is result page:  los angeles county land record is (277GB), is the one error out.
[https://transparentgov.net/json2tree/ipfsList.html](https://transparentgov.net/json2tree/ipfsList.html)

 ipfs.io link never worked.
cloudflare.com works , some time timeout
infura.io works,  some time timeout

Be aware, all the content now currently host on my home computer. 
I have 2 mac, 1 pc, host the same content on my home LAN.

My question here is, 

   If 2 mac offline, only 1 pc online. Would ipfs smart enough to find this 1 PC?

   or If only 1 mac online, the other mac and pc both offline, would ipfs smart enough to find that 1 mac?

   My home LAN have only 1 public ISP provided IP,  97.xxx.xxx.xx

   2 mac, 1 pc have there own LAN ip, 192.168.86.YY

-----------------

recent 2 days, my home internet is so slow, only 16Mbps down, some time even interrupt, I think it is ISP charter's problem.   

I am calling charter's custom service, to see if they can fix the internet problem next week.

**Comment by Stebalien** [comment]
> I really did see the panic on go-ipfs 0.4.19 ( on Mac ) many times,
panic error is exactly the error that accidently shut down my ipfs-daemon process (Mac).

I'm really looking for the _exact_ panic stacktrace because we've changed flatfs since 0.4.16.

---

If your machines are reachable on the public interface, the ipfs network should be able to find content on them.

**Comment by hoogw** [comment]
Got it, no problem. I should be able to re-generate many panic error on Mac next week. 
I have see many time panic error last week, have no idea what it is means......

I have 2 NAS, synology DS1090+(8GB DDR3, intel 2.3Hz) and qnap TS451+(8GB DDR3, intel 2.0Hz) ,
 those are reachable on public internet.

this link reach synology machine.
[http://pdfbay.org/](http://pdfbay.org/)

Because I have only 1 public IP,  (ISP charter spectrum)
so I config router, DHCP , let port 80 re-direct to  synology, port 10 re-direct to qnap. 


ipfs now only running on 2 mac and 1 pc in the same LAN, does not have public interface,
I can not reach them from internet. but I can reach those 2 NAS machine, by http://97.xx.xx.xx:80 and http://97....:10  

What is the best way to run ipfs, can output best performance? and fail proof?
Right now ipfs only run on 2 mac and 1 pc, 
if run on NAS, could I get any better performance result?

fail proof, if one machine offline, the other machine automatically pickup in the same LAN.(only 1 public IP)

**Comment by hoogw** [comment]
mac 0.4.19 error
ipfs add -r xxxx
.......
ords/landrecords/Sewer_Plans/PC/PC00001/PC00237.PDF
added QmXwCrDgHDQSqdbZQUnXqmwpV1iH2e348RpPxWG4iSXFqL Los_Angeles_County_Land_Records/landrecords/Sewer_Plans/PC/PC00001/PC00240.PDF
added Qmc6v8vF7LCy3ECmj3AoHsgXWQPyd5879FVaSwPevW6bUH Los_Angeles_County_Land_Records/landrecords/Sewer_Plans/PC/PC00001/PC00242.PDF
 54.49 GiB / 277.62 GiB [=======>-----------------------------]  19.63% 6h27m19sError: stat /Volumes/d/ipfs_repo/blocks/R2/CIQMHK3GJOK5Q7XZM6X5AOEFWR2Z4K3OYHGO7ZAPPGHSJYH6OICOR2Q.data: input/output error

**Comment by hoogw** [comment]
2nd mac 0.4.19 error
ipfs add -r xxxx


added QmZSEEr7Cr1LzWZNBPXH4cyHAxPZTwRaNr7LLP4CFJnyd1 Los_Angeles_County_Land_Records/landrecords/tract/MB0779/TR0779-076.pdf
added QmQiEjQ4EWdh8WKHSzwomxsQFcXabwb5z4BgU6SKEDe6sK Los_Angeles_County_Land_Records/landrecords/tract/MB0779/TR0779-078.pdf
added QmTtwAVF7tdKnkrcnxMxZsHBUgq9nU9c6oRijdPMasr5Fz Los_Angeles_County_Land_Records/landrecords/tract/MB0779/TR0779-080.pdf
added QmZfZVJVCXzbeQzfeCYMDLtgG1PyQMU8uw8rMEm6QGTA9E Los_Angeles_County_Land_Records/landrecords/tract/MB0779/TR0779-082.pdf
 261.14 GiB / 277.62 GiB [=================================>--]  94.06% 1h00m45sError: rename /Volumes/d/ipfs_repo/blocks/RN/put-996653373 /Volumes/d/ipfs_repo/blocks/RN/CIQDG6OY7T2P4JN27WJPWYIKJXNEQNUOU46IJYQR4R3E6TQ4A3DWRNI.data: input/output error
siriuss-mini:~ sirius$ 

--------------------------------------------
No panic error found on mac, or pc.

**Comment by hoogw** [comment]
I think the problem is Mac, it need to configure somehow. 
ipfs iteself is fine, no panic error in the last 2 run. 
so ticket can close.
