### ISSUE TITLE
why request timeout? only half of request success? performance very unstable

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#6206]
[https://transparentgov.net/json2tree/ipfsList.html](https://transparentgov.net/json2tree/ipfsList.html)

all those content are currently host on my home computer, (ISP speed:  upload 10Mbps download 60Mbps)

Except( Los_Angeles_County_Land_Records 277GB) get error when add,
all others should working.
But only maybe half of request, success open file, the other half I get timeout error. 
The performance is big issue. 

Why some pdf file success, some pdf file timeout????
ipfs.io always failed.
cloudflare are some times failed.

Why the performace is so unstable, you don't know your next request will be success or timeout.
 
[https://transparentgov.net/json2tree/ipfsList.html](https://transparentgov.net/json2tree/ipfsList.html)

**Comment by Stebalien** [comment]
Let's try to keep this to one issue (#6054).
