### ISSUE TITLE
unconnectable in China?

### ISSUE THREAD

**Issue by mnuestc** [ipfs/go-ipfs#6219]
I tried to run two nodes for sharing files, one running natively and the other in a virtual machine,the two nodes both don't have external ip. I have tried all the methods described by "Transferring a file with ipfs"——[https://github.com/ipfs/go-ipfs/blob/master/docs/file-transfer.md], 
but it still doesn't work. can not NAT traversal? 
peer one -upload file
![微信图片_20190415203553](https://user-images.githubusercontent.com/36103788/56133493-1d829480-5fbf-11e9-80da-680bd9819380.png)

peer two -cat file
![p2](https://user-images.githubusercontent.com/36103788/56133494-1e1b2b00-5fbf-11e9-9726-792dc6de1930.png)
![p22](https://user-images.githubusercontent.com/36103788/56133495-1e1b2b00-5fbf-11e9-8c2a-915101873acc.png)

**Comment by Stebalien** [comment]
`ipfs swarm connect /ip4/10.0.2.15/...` definitely won't work as `10.0.2.15` is a private address. IPFS will try to configure your NATs to forward the appropriate ports but that doesn't always work.

For the moment, try enabling AutoRelay on both nodes with `ipfs config --json Swarm.EnableAutoRelay true` (remember to restart your node). It may take a few minutes for this feature to kick in but, once it does, both of your nodes should start advertising _relayed_ addresses.

**Comment by Stebalien** [comment]
(closing for tracking)
