### ISSUE TITLE
Switch CIDv1 from Base58 to Base32 (go-ipfs)

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#6220]
> **This not about making CIDv1 the default**, but a small UX tweak to remove confusion for users who **opt-in to CIDv1 and expect Base32** (think IPFS Camp).
>
> Actual move to CIDv1 as the new default is tracked in:
> - Migration to CIDv1 (default base32)  https://github.com/ipfs/ipfs/issues/337
>   - Make base32 CIDv1 the default for go-ipfs: https://github.com/ipfs/go-ipfs/issues/4143 https://github.com/ipfs/go-ipfs/issues/5358
> - js-ipfs counterpart: https://github.com/ipfs/js-ipfs/issues/1995

## Problem 

Right now if someone wants to use CIDv1 they can opt-in via `--cid-version 1`, but by default they get CIDv1 in **Base58**:

```console
$ ipfs add --cid-version 1 guardian.jpg
added zb2rhk6GMPQF3hfzwXTaNYFLKomMeC6UXdUt6jZKPpeVirLtV guardian.jpg                                                                                                                                                                  
```

To get the representation [we aim for](https://github.com/ipfs/ipfs/issues/337), they need to convert **Base58** CIDv1 to **Base32** in additional step:

```console
$ ipfs cid base32 zb2rhk6GMPQF3hfzwXTaNYFLKomMeC6UXdUt6jZKPpeVirLtV
bafkreigh2akiscaildcqabsyg3dfr6chu3fgpregiymsck7e7aqa4s52zy
```

The need for the conversion step is not only unnecessary, but harmful to our migration efforts.  Users report confusion why CIDv1 produced by go-ipfs can't be used in `<cid>.ipfs.dweb.link` and [why Web UI swaps out the CID](https://user-images.githubusercontent.com/665810/55393420-1d9d8180-5535-11e9-98a4-05055a64721d.png). 

It is _really_ embarrassing when we need to ask people to use `ipfs cid base32` during demos and workshops (_"why do i need to convert? isn't base32 the future default for CIDv1?"_)

## Solution

We should **switch default representation of CIDv1 from Base58 to Base32** (without making CIDv1 the default itself).

This will ensure that:
- one can just `ipfs add --cid-version 1` and use the output immediately 
  (small change, huge UX improvement)
- UX win: CIDv1 look the same everywhere
- our CIDv1 tests can be written against `bafy..` CIDs

### References

- Migration to CIDv1 (default base32)  https://github.com/ipfs/ipfs/issues/337
- js-ipfs version of this issue https://github.com/ipfs/js-ipfs/issues/1995
- existing issues in the wild
  - "broken CIDv1 in subdomain" https://zb2rhk6GMPQF3hfzwXTaNYFLKomMeC6UXdUt6jZKPpeVirLtV.ipfs.dweb.link
  - "explore a `bafy` CID but in the breadcrumb & the CID info it's displayed as `zdj` CID"  https://github.com/ipfs-shipyard/ipfs-webui/issues/999
  - IPFS Camp (we need to address this before the camp)

**Comment by Stebalien** [comment]
You can currently pass the `--cid-base` flag to specify the default CID base. You can also pass `--upgrade-cidv0-in-output` flag to auto-upgrade cidv0 to cidv1.

**Comment by lidel** [comment]
The change suggested here is that user should not need to pass anything to get Base32 if they already opted-in to CIDv1 via `--cid-version 1`
