### ISSUE TITLE
Creating a new MFS directory

### ISSUE THREAD

**Issue by gasparyanyur** [ipfs/go-ipfs#6224]
#### Version information:

```
go-ipfs version: 0.4.20-rc1-4fd81e373-dirty
Repo version: 7
System version: amd64/linux
Golang version: go1.12.3

```

#### Description:

Hi all. In my app I have a private repository where users can add and validate files to get high raiting. So there are risks that users can change file content and other users needs to 
catch that. So  I want to create files via `MFS` and then check if the conent wasn't changed by another user using the hash of fail.  I am using `g-ipfs` to have `ipfs` private network . But I can not find the way to create directory for my files where I will be share my files. 

Please help me to solve this problem!

I apologize if the question is not reasonable, I'm just a beginner

**Comment by magik6k** [comment]
`ipfs files mkdir /someDirectory` should work. 

Also note that when you refer to files with `/ipfs/...` paths, the content can't be modified without changing the path as ipfs checks hashes when fetching from the network.

**Comment by gasparyanyur** [comment]
@magik6k  thanks foy reply. Let me know please, is there a way to check if file modified. Logically , I need to check if file has been changed that tag it as invalid

**Comment by magik6k** [comment]
I'm not sure where your users have the ability to modify the data.

In MFS you can check hash of the file with `ipfs files stat /path/to/file`. If it differs between checks, the file has been modified.

(btw. https://discuss.ipfs.io/ is the place for questions like those)

**Comment by gasparyanyur** [comment]
I have created 2 different directories 
`ipfs files mkdir /dir1`
`ipfs files mkdir /dir2`

And when run 
`ipfs files stat /dir1`
`ipfs files stat /dir2`
I am getting the same result. Why ?))

**Comment by magik6k** [comment]
The hashes are the same because both directories are empty (and are serialized in the same way - file names are held in parent directories)

You may want to follow https://proto.school/#/data-structures/ (especially 'Merkle trees and Directed Acyclic Graphs (DAG)') as it should help explain some of the concepts

**Comment by Stebalien** [comment]
(closing for tracking as this isn't a bug)
