### ISSUE TITLE
Human output for "CumulativeSize" in "ipfs object stat"

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipfs#6226]
#### Version information:

master

#### Type:

enhancement

#### Description:

`ipfs object stat` returns the `CumulativeSize` of a UnixFS dag. It would be nice to have this humanized (with an optional flag), so that it shows `1.3GB` or `234MB` etc.

**Comment by hsanjuan** [comment]
Similar to https://github.com/ipfs/go-ipfs/issues/6103

**Comment by vikramsk** [comment]
Hello! 
I'm new to this project and this seems to be a good first issue. I would like to take this up.

**Comment by hsanjuan** [comment]
@vikramsk thank you very much!
