### ISSUE TITLE
remote ip address of peer

### ISSUE THREAD

**Issue by lele012** [ipfs/go-ipfs#6227]
I have customized a bootstrap node named A . When a peer (name B) connected to the bootstrap (the peer and the bootstrap in internal network) , i run "ipfs swarm peers" in the bootstrap site,  the address of B is the ip address of LAN  , how can i do to get the external ip address of  B ?

**Comment by Stebalien** [comment]
I'd really love to answer your question but this is clearly a question and not a bug. Could you re-ask on https://discuss.ipfs.io and flag me down (@stebalien)?

**Comment by lele012** [comment]
Thank you ，  i know how to get the remote ip

**Comment by spaceh3ad** [comment]
Awesome @lele012 could you share...?
