### ISSUE TITLE
404 error on Gateway page for a /ipns/ request

### ISSUE THREAD

**Issue by zicmama** [ipfs/go-ipfs#6233]
#### Version information:
go-ipfs version: 0.4.19-
Repo version: 7
System version: arm/linux
Golang version: go1.11.5

#### Type:
bug

https://localhost:8080/ipfs/QmezEsw3kWYyyBaxPp9ayLUBke63NKzF95Y4mGJPjrykUF is OK
but https://localhost:8080/ipns/ipfs.copylaradio.com result in a 404 page
> 404 Error!
> It's all gone horribly wrong
> The document "/ipns/ipfs.copylaradio.com" doesn't exist. Are you sure you know what you're doing?
(404 page having error loading /ipns/newimages/favicon-196.png)

CLI and mount are OK

```
ipfs dns ipfs.copylaradio.com
/ipfs/QmezEsw3kWYyyBaxPp9ayLUBke63NKzF95Y4mGJPjrykUF

ls -al /ipns/ipfs.copylaradio.com
lr-xr-xr-x 1 root root 0 Apr 17 21:48 /ipns/ipfs.copylaradio.com -> /ipfs/QmezEsw3kWYyyBaxPp9ayLUBke63NKzF95Y4mGJPjrykUF
```

It seems

**Comment by Stebalien** [comment]
Are you sure the _content_ is available? Does `ipfs cat /ipfs/QmezEsw3kWYyyBaxPp9ayLUBke63NKzF95Y4mGJPjrykUF` work?

**Comment by zicmama** [comment]
Yes the file is available
ipfs cat /ipfs/QmezEsw3kWYyyBaxPp9ayLUBke63NKzF95Y4mGJPjrykUF > img.jpg
fetch the file.

Problem seems related to ipns subdirectory resolution from gateway, filesystem (fuse mount) works.

**Comment by zicmama** [comment]
Could it be related to DNS TXT RECORD "dnslink=/ipfs/QmezEsw3kWYyyBaxPp9ayLUBke63NKzF95Y4mGJPjrykUF" 

If it pointing to a file or a directory, does it need final '/'

**Comment by Stebalien** [comment]
Wait, are you seeing that _exact_ 404 page?

> 404 Error!
It's all gone horribly wrong
The document "/ipns/ipfs.copylaradio.com" doesn't exist. Are you sure you know what you're doing?

That's not a go-ipfs error page. Are you running something else on port 8080? https://github.com/fatg3erman/RompR?

**Comment by zicmama** [comment]
Maybe I am misunderstanding something.

In one case, I have added ipfs access as /ipfs on the webite you mention (but error is not related to it).

nginx config
```
# IPFS GATEWAY PROXY
  location /ipfs {
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host            $host;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
```

```
ipfs name publish --key=zicmama /ipfs/Qmam8wSeLVqGAjpKfVrRtrhHMjbBrd3jDCPRkJjfrq7iwf
Published to QmWHJ5HYf6xqbaAdg8wQygLGjUSQPH5r4xq4NhHUpTAxyU: /ipfs/Qmam8wSeLVqGAjpKfVrRtrhHMjbBrd3jDCPRkJjfrq7iwf
```

```
http://copylaradio.local/ipfs/Qmam8wSeLVqGAjpKfVrRtrhHMjbBrd3jDCPRkJjfrq7iwf/113/Les%20Princes%20de%20la%20ville
```
**OK**

```
http://copylaradio.local/ipns/QmWHJ5HYf6xqbaAdg8wQygLGjUSQPH5r4xq4NhHUpTAxyU
```
**404**


404 problem happens also on another node, where gateway gives access to the same ipfs object but through DNSLink TXT method.

**Comment by Stebalien** [comment]
My point is that the 404 error message you posted is _not_ an error message returned by go-ipfs.

---

WRT https://github.com/ipfs/go-ipfs/issues/6233#issuecomment-484484765, is this a different issue?

> http://copylaradio.local/ipns/QmWHJ5HYf6xqbaAdg8wQygLGjUSQPH5r4xq4NhHUpTAxyU

Your nginx config doesn't appear to be passing `/ipns`, just `/ipfs`.

**Comment by zicmama** [comment]
Thank you. You are right!!!

What that lot of config and parameters I had to get used to, I forgot a bad line in nginx
 "try_files $uri $uri/ =404;"

Sorry for disturb, and great thanks for helping me.
Now I have a full understanding of ipfs base!
