### ISSUE TITLE
IPNS publish very slow

### ISSUE THREAD

**Issue by kubatial** [ipfs/go-ipfs#6236]
#### Version information:

go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1

#### Type:

-"bug", "feature"

#### Description:

I am running an IPFS node on a standard Ubuntu machine in AWS as part of an app I am developing. As part of the app I also have to regularly generate keys for my node and then do an ipfs name publish. The problem is that whenever I try publishing, it generally takes a long time (2-3min on average, occasionally 5min or longer). Anything above 1 min would basically make my app unusable. I have tried running the daemon with --enable-namesys-pubsub, but without any noticeable improvements. I was wondering if there is some easy way I might have missed which would get the publishing time down to under 1min. Maybe a setting which might make the publishing faster locally at first and propagate it through the network later?

Thanks in advance

**Comment by Stebalien** [comment]
Unfortunately, no. At the moment, IPNS publishing is just really slow due to some issues with our DHT and scaling.

Dup of https://github.com/ipfs/go-ipfs/issues/3860.

**Comment by ec1oud** [comment]
It's still too slow.  For the ipfs client it should be instantaneous, because it's up to the daemon to do the actual work, and there's nothing for the client to wait for.
