### ISSUE TITLE
IPFS daemon use over 100% CPU after resume from hibernate

### ISSUE THREAD

**Issue by beenotung** [ipfs/go-ipfs#6243]
#### Version information:
go-ipfs version: 0.4.19-83d3f7672
Repo version: 7
System version: amd64/linux
Golang version: go1.12.1

#### Type:
bug

#### Description:

When I resume from hibernate (systemctl hibernate) on archlinux, I notice from htop there are two ipfs daemon process using ~104% CPU on my 4-core (2 thread per core) system.
The system was moving ~1.6GB of memory from swap into RAM at that time.

**Comment by Stebalien** [comment]
Could you follow https://github.com/ipfs/go-ipfs/blob/master/docs/debug-guide.md#beginning and post the results?

**Comment by beenotung** [comment]
this bug doesn't come often, I'll do that next time if ever

**Comment by Stebalien** [comment]
Thanks!
