### ISSUE TITLE
make intall fails due to linker memory usage

### ISSUE THREAD

**Issue by kaysond** [ipfs/go-ipfs#6249]
Just cloned the repo onto my 1GB RAM vps and I get...

```
root@ubuntu-s-1vcpu-1gb-sfo2-01:/usr/src/go-ipfs# make install
go version go1.12.4 linux/amd64
bin/check_go_version 1.12
go install -ldflags="-X "github.com/ipfs/go-ipfs".CurrentCommit=c1bc202f4" ./cmd/ipfs
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
make: *** [cmd/ipfs/Rules.mk:37: cmd/ipfs-install] Error 1
```

The process is getting killed due to OOM. Funnily enough, I'm trying to build the latest to debug a memory leak. Is there an easy way to reduce the memory footprint of the linker?

**Comment by magik6k** [comment]
I don't think there is much we can do here. You can try (cross-)compiling on a larger machine (we don't use cgo, so is should be really simple).

You may also try appending `-tags="nofuse purego"` to the build command, but it may not help at all.

**Comment by Stebalien** [comment]
(closing for tracking as there's nothing we can really do about this)

**Comment by Stebalien** [comment]
Specifically, you can cross compile with:

```
GOOS=linux GOARCH=amd64 go build ./cmd/ipfs
```

**Comment by kaysond** [comment]
Thanks!
