### ISSUE TITLE
http api Identify with HEAD request

### ISSUE THREAD

**Issue by travisperson** [ipfs/go-ipfs#625]
I wasn't able to find a really easy way to determine if the service running on port 5001 was the ipfs daemon. It might be beneficial to have the API respond to a request to `HEAD` requests with something to identify itself.

```
curl -I http://127.0.0.1:5001/ipfs/
HTTP/1.1 400 Bad Request
Date: Fri, 23 Jan 2015 06:06:42 GMT
Content-Length: 38
Content-Type: text/plain; charset=utf-8
Server: Ipfs-Daemon/0.1.7
```

**Comment by jbenet** [comment]
:+1: on the `Server` header! We should use the same `ipfs-agent` string: `go-ipfs/<version>`

**Comment by jbenet** [comment]
Would be good to still:
- [ ] include the server header (should be the go-ipfs agent)

The identification can now happen by going to `/version`. example: http://localhost:5001/version

**Comment by whyrusleeping** [comment]
HEAD requests work now, we can close this after @Kubuxu's PR merges

**Comment by diasdavid** [comment]
Security wise, it is a bad practice to announce the running service (and version) on HTTP headers or any kind of banners
