### ISSUE TITLE
ipfs add with two files only adds one of them in 0.4.20

### ISSUE THREAD

**Issue by olizilla** [ipfs/go-ipfs#6254]
#### Version information:
```console
$ ipfs version --all
go-ipfs version: 0.4.20-
Repo version: 7
System version: amd64/darwin
Golang version: go1.12.4
```
#### Description:

Adding 2 files via the CLI  returns the cid for only 1 of the files:

```console
$ iim use go 0.4.20
$ ipfs version
ipfs version 0.4.20
$ echo "A" > a.txt
$ echo "B" > b.txt
$ ipfs add a.txt b.txt
added QmNRpQVA5n7osjtyjYaWEQpwYnbV1QoVkrSe7oyccMJh1m a.txt
 2 B / 4 B [================================>--------------------------------]  50.00%
```
For comparison, on 0.4.19

```console
$ iim use go 0.4.19
$ ipfs version
ipfs version 0.4.19
$ ipfs add a.txt b.txt
added QmNRpQVA5n7osjtyjYaWEQpwYnbV1QoVkrSe7oyccMJh1m a.txt
added QmbN4uJU4zirdG1g9qcYYAAHNCU6MRHZBSwTx61WGVKich b.txt
 4 B / 4 B [=================================================================] 100.00%
```

Same issue occurs via the http api, found will debugging a build failure on js-ipfs-http-client after updating to 0.4.20, see: https://github.com/ipfs/js-ipfs-http-client/pull/973

**Comment by olizilla** [comment]
on the cli, it doesn't seem to be the argument order that determines which file will be added, but the first on when alphabetically ordered. If you add a.txt and b.txt it doesn't matter which order you pass them in, it's always the CID for a.txt that gets reported

```console
$ ipfs add b.txt a.txt
added QmNRpQVA5n7osjtyjYaWEQpwYnbV1QoVkrSe7oyccMJh1m a.txt
 2 B / 4 B [================================>--------------------------------]  50.00%

$ ipfs add a.txt b.txt
added QmNRpQVA5n7osjtyjYaWEQpwYnbV1QoVkrSe7oyccMJh1m a.txt
 2 B / 4 B [================================>--------------------------------]  50.00%
```

**Comment by alanshaw** [comment]
> only returns the cid

It's a little worse than that - it actually only adds one file:

```console
⨎ ipfs add --only-hash extreme-closeup.jpg 
added QmdpvgAXfyhyk4Erwge93CkiWt7TpndYm4SW3mZndRBpsc extreme-closeup.jpg
 70.99 KiB / 70.99 KiB [=============================================================================================================================] 100.00%

⨎ ipfs add alan-cat.jpg extreme-closeup.jpg 
added QmXmYiRaRg4YRVdtPRv3CgH1sje7xzjNPv9yCyUcSe8SAC alan-cat.jpg
 100.83 KiB / 171.81 KiB [========================================================================>--------------------------------------------------]  58.68%

⨎ ipfs ls QmdpvgAXfyhyk4Erwge93CkiWt7TpndYm4SW3mZndRBpsc
Error: merkledag: not found
```

**Comment by magik6k** [comment]
This is probably a regression from https://github.com/ipfs/go-ipfs/pull/6019. Should be easy to fix

**Comment by magik6k** [comment]
Pushed a fix: https://github.com/ipfs/go-ipfs/pull/6255

**Comment by Stebalien** [comment]
Does this relate to #3300?

**Comment by Stebalien** [comment]
Answer: no. That's an issue in go-ipfs-cmds (we put all arguments into a single directory)

**Comment by olizilla** [comment]
Could you share a rough ETA for when this fix will land in a release so we can schedule an ipfs-desktop release. Folks are going to start asking us for a relase with 0.4.20 in, but this is a blocker for that.
