### ISSUE TITLE
Lean on datastore queries in provider queue

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6260]
At the moment, we read in the head/tail of the provider queue on start. However, it's probably easier to just repeatedly query the datastore.

That is,

1. Store provider queue entries as `/provider/queue/$nanosecond-timestamp/$cid` -> (or even just `/provider/queue/$start-timestamp.$counter`).
2. Each time we're signaled (size-one channel?) that something was enqueued, query `Query{Prefix: "/provider/queue/", Order: [OrderByKey]}`.

Motivation: track less state. This is really low-priority, it just may simplify this queue a bit and remove room for bugs.

**Comment by michaelavila** [comment]
Noted :+1:. I'll look into this as I'm working on the remainder of the provider PRs. Thanks for bringing it up.

**Comment by michaelavila** [comment]
Closing as this has been implemented. Thanks for the suggestion!
