### ISSUE TITLE
server profile should not include non-global IPv6 ranges

### ISSUE THREAD

**Issue by teran-mckinney** [ipfs/go-ipfs#6284]
#### Version information:

```
$ ipfs version --all
go-ipfs version: 0.4.20-dev-221d1b13a
Repo version: 7
System version: amd64/linux
Golang version: go1.12
```

#### Description:

If you have a private IPv6 address, say such as fec0::, ipfs will announce this. If you do `ipfs init --profile server`, there's a very hefty list of IPv4s to avoid, but not the same for IPv6.

https://en.wikipedia.org/wiki/Reserved_IP_addresses#IPv6

This seems like a pretty easy patch to write up. If you can confirm this is not intended behavior, I can open a PR.

(I also see swarm announcements for 127.0.0.1, I'm not sure if that's a bad thing or not.)

**Comment by Stebalien** [comment]
> (I also see swarm announcements for 127.0.0.1, I'm not sure if that's a bad thing or not.)

Long discussion here: https://github.com/libp2p/go-libp2p/issues/436

---

But yes, the server profile should block all non-routable addresses. Patches most welcome! (https://github.com/ipfs/go-ipfs-config/blob/master/profile.go)

**Comment by teran-mckinney** [comment]
Thank you! I went ahead and opened a pull request.

https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml

I had pretty mixed feelings on what to add. We could have Teredo, 6to4, etc. But I think that could break desired connectivity in some cases. I hope this is at least a start.

I can see the swarm announcements being a potential privacy issue as well. Especially if say you're a client on a laptop and you really just want outbound connections. If you have IPv6 privacy mode enabled, you hand out every last one of your globally routable addresses. Of cousre this PR doesn't impact that, but I think it may be something to think about more.

**Comment by Stebalien** [comment]
That's a good enough start for now. We can always adjust this later.

> I can see the swarm announcements being a potential privacy issue as well. Especially if say you're a client on a laptop and you really just want outbound connections. If you have IPv6 privacy mode enabled, you hand out every last one of your globally routable addresses. Of cousre this PR doesn't impact that, but I think it may be something to think about more.

I agree. That's a large part of that libp2p issue I listed.

**Comment by teran-mckinney** [comment]
Gotcha. Thank you for merging!
