### ISSUE TITLE
Connection counts climbing far past HighWater setting

### ISSUE THREAD

**Issue by leerspace** [ipfs/go-ipfs#6286]
#### Version information:

```
$ ipfs version --all
go-ipfs version: 0.4.20-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.4
```

#### Type:
bug

#### Description:

While using my node, the connection counts started climbing rapidly past the `HighWater` connection setting and seemed to be stuck in a climb -- reaching 2000+ connections before I shutdown the daemon (see `ipfs.peers` file in link below). At the time of the connection count climb I think I was pinning a few hashes and publishing an IPNS entry.

It looks like there are a couple of old issues that sound similar (_e.g._, #4718, #5248) but they are closed. I wonder if this could be related to #3532, but it's not clear to me if connections are building rapidly in that issue.

My node's `LowWater` and `HighWater` connection counts are set to the defaults (see `ipfs.config` for full output from `ipfs config show`). `QUIC` and `EnableAutoRelay` are both enabled, but `EnableRelayHop` is not.

Debug data using [these instructions](https://github.com/ipfs/go-ipfs/blob/master/docs/debug-guide.md#beginning) and `ipfs swarm peers` and `ipfs config show` output from after the issue started and before the daemon were killed are available here:

https://ipfs.io/ipfs/QmZqhucUHSoW3WzXsu7gepmQX9NqQzkjcsQAN1r4kjQYBH

**Comment by vyzo** [comment]
Have you recently advertised as a relay _hop_ with autorelay?
The provider record stays for 24hrs, and that would certainly inundate you with new connections.

**Comment by leerspace** [comment]
@vyzo Assuming I would do that using the `EnableRelayHop`, I have not done that on this node as far as I can remember (I'd say 99% sure).

**Comment by Stebalien** [comment]
@leerspace could you post the output of `ipfs swarm peers -v`?

**Comment by leerspace** [comment]
I didn't think to get verbose output from `swarm peers` before; but once I notice it happening again I'll grab it and add it to this issue.

**Comment by leerspace** [comment]
I got this to happen again to some extent (2000+ peers), but I think this is probably just a duplicate of #6283.

Here's the `ipfs swarm peers -v` output in case I'm wrong (see 1556850569 for example, file names are unix timestamps from `date +%s`): https://ipfs.io/ipfs/QmSzBfiMwU5ChkMtZpFbUtWWXQPQBhbPSg6kh5GZQxBx6x

I should probably be using `ipfs daemon --routing=dhtclient` on this node as suggested in another issue since the `*Water` connection thresholds don't seem to keep connections under control with default routing.

**Comment by Stebalien** [comment]
Unfortunately, we don't (yet) have anything to simply _stop_ new connections. Libp2p needs to feed the connection manager down through to the transports themselves.

But still, that's a _lot_ of inbound connections.

**Comment by swedneck** [comment]
i seem to still be running into this with v0.4.21, my node consistently has around 8000 peers even though my highwater is set to 900.

**Comment by dokterbob** [comment]
Some problem with 0.4.22. With the following settings:

```
    "ConnMgr": {
      "GracePeriod": "30s",
      "HighWater": 15000,
      "LowWater": 10000,
      "Type": "basic"
    },
```

I'm consistently seeing 35-50k connections, which is essentially bringing our server to it's knees.

**Comment by dokterbob** [comment]
Additional note: this seems to have started right after I enabled RelayHop and AutoRelay (second vertical white line), which I then quickly disabled (third vertical line) - the first line is the 0.4.22 upgrade. Could the removal thereof not have been propagated well throughout the DHT?

![2019-08-25 13 56 24](https://user-images.githubusercontent.com/22742/63650227-50dce900-c740-11e9-8a2d-917e2365336b.png)

**Comment by dokterbob** [comment]
Sadly, this problem persists. I think it's time to reopen this issue.
![ssp_temp_capture](https://user-images.githubusercontent.com/22742/63677047-19c01380-c7e4-11e9-8dcf-62529ecb7606.png)

On an 8-core CPU it soaks up a good 700% of load (purple here is IPFS).
![ssp_temp_capture](https://user-images.githubusercontent.com/22742/63677117-3fe5b380-c7e4-11e9-8ce1-0f2d1a957b0b.png)

**Comment by dokterbob** [comment]
@aschmahmann Great, thanks for the quick feedback!

Note that the [config doc] specifically state:
> EnableAutoRelay Enables automatic relay for this node. If the node is a HOP relay (EnableRelayHop is true) then it will advertise itself as a relay through the DHT.

**Comment by dokterbob** [comment]
The latter.

**Comment by dokterbob** [comment]
Thanks!
