### ISSUE TITLE
Occasional Invalid JSON Response From Logging API

### ISSUE THREAD

**Issue by postables** [ipfs/go-ipfs#6294]
#### Version information:
go-ipfs version: 0.4.20-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.4

#### Description:

Occasionally when pulling logs from the API call `log/tail` responses given will be invalid json or will not unmarshal properly.

Some of the responses will look like this when unmarshaled into a `map[string]interface{}` type.
```
map[event:dhtReceivedMessage message:map[key: type:FIND_NODE] peerID:....c system:dht time:2019-05-01T04:00:38.478822015Z]
```

However during testing usually every 5-7 logs that are returned from `log/tail` will cause an error when attempting to unmarshal into a `map[string]interface{}` type. Printing the log that cause this failure will usually return a single character like `0` or `:`

To reproduce see this [gist](https://gist.github.com/postables/a4cc856bcc4f43b06de18367231302fe)

Here's an example error
```
2019/05/02 23:26:05 invalid character 'D' looking for beginning of value
exit status 1
```

**Comment by Stebalien** [comment]
This looks like https://github.com/ipfs/go-ipfs-api/pull/180. `json.Decoder` buffers internally so it's probably throwing away part of the next line.

**Comment by postables** [comment]
ah I see, let me try implementing the pubsub style decoder for the logger in [ipfs/go-ipfs-api#179](https://github.com/ipfs/go-ipfs-api/pull/179). If that works then this is definitely due to a bug in the code I'm writing, and I will close this issue.

**Comment by postables** [comment]
Update: it definitely was due to the way I was decoding the log streams. After making the fix I am no longer receive this error.
