### ISSUE TITLE
Too many CLOSE_WAIT after access via http api

### ISSUE THREAD

**Issue by suutaku** [ipfs/go-ipfs#6295]
#### Version information:
`JohnSuus-MacBook-Pro-4:build john$ ipfs version --all
go-ipfs version: 0.4.21-dev-7e9eb72bf
Repo version: 7
System version: amd64/darwin
Golang version: go1.12.4`

#### Description:

Running ipfs daemon on Mac OS X 10.13.6. 
Access` 127.0.0.1:5001/api/v0/xxxxxx` once per second. after about 10 minute, running 
`sudo losf -nP -iTCP:5001`
I got 300+ TCP `CLOSE_WAIT` status.
It's some kind of FD leaks?

I had follow @Stebalien 's suggestion to modify code 
`go-ipfs/core/corehttp/corehttp.go`

by added 
`server.SetKeepAlivesEnabled(false)`
after 
```
server := &http.Server{ 
 	Handler: handler, 
 } 
```

but it finally invalid.

and I also set a nginx reverse proxy out in front, the number of `CLOSE_WAIT` was keep increasing.

can you take a look agin? 
now my server is down due this issue....

**Comment by suutaku** [comment]
### update
I found CLOSE_WAIT only happens on invalid access. for example, client side reach the timeout, terminate the connection and have not receive  response  from daemon.
I tested  command of IPFS HTTP API.
by add `progress=true` flag to `/pin/add` command, no `TIME_WAIT` happen even the hash is invalid.
but commands like `pin/rm` have no flag like `progress` , so it still `TIME_WAIT` when client reach the timeout.

**Comment by Stebalien** [comment]
Wait, are you seeing `TIME_WAIT` or `CLOSE_WAIT`?

**Comment by suutaku** [comment]
> Wait, are you seeing `TIME_WAIT` or `CLOSE_WAIT`?

I'm sorry!  typing miss. It's `CLOSE_WAIT` !!!!!!!

**Comment by suutaku** [comment]
@Stebalien 
after check the source code. if client reach the timeout,  IPFS hang on `serverHandler{c.server}.ServeHTTP(w, w.req)` at ` net/http/server.go:1884`.
I think is IPFS handleFunc's bug?

**Comment by Stebalien** [comment]
Could you run `curl http://127.0.0.1:5001/debug/pprof/goroutine?debug=2 > goroutines' and upload the result? That'll tell me where it's getting stuck.

**Comment by suutaku** [comment]
[http://www.cotnetwork.com/goroutines](url)
ipfs version 0.4.21-dev

**Comment by Stebalien** [comment]
Were you reproducing the issue when you ran `curl http://127.0.0.1:5001/debug/pprof/goroutine?debug=2 > goroutines`? I'm not seeing anything stuck in `ServeHTTP`.

**Comment by suutaku** [comment]
client (curl) was quit. but ServeHTTP for client request still running (for a long time). At this time, TCP was CLOSE_WAIT on server side.

**Comment by Stebalien** [comment]
I see. So the bug is specifically with `ipfs pin add` and `ipfs pin rm`. It looks like we aren't feeding the context all the way through so we're not completely canceling the operation.

**Comment by suutaku** [comment]
thank you. I'm going to test it.

**Comment by suutaku** [comment]
problem solved. 
thank you agin!
