### ISSUE TITLE
Output Issue in "ipfs ping"

### ISSUE THREAD

**Issue by remmerw** [ipfs/go-ipfs#6298]
#### Type: Release 0.4.20
 
- "bug": Using `ipfs ping --enc=json --count=1 QmRZq4kheCH3R4NHjeJpd5b17JkRdDSBTYMLtuYtjjfxxx`

(changed PID)

#### Description:
Testing the output and function of ipfs ping
Example:
`ipfs ping --enc=json --count=1 QmRZq4kheCH3R4NHjeJpd5b17JkRdDSBTYMLtuYtjjfxxx`

Ping Scenario: (2 Nodes)
One Node pings the second node (QmRZq4kheCH3R4NHjeJpd5b17JkRdDSBTYMLtuYtjjfxxx) within the same network:

(Both nodes are "online")
`ipfs ping --enc=json --count=1 QmRZq4kheCH3R4NHjeJpd5b17JkRdDSBTYMLtuYtjjfxxx`

Output:

```
{"Success":true,"Time":0,"Text":"PING QmRZq4kheCH3R4NHjeJpd5b17JkRdDSBTYMLtuYtjjfxxx."}
{"Success":true,"Time":144643541,"Text":""}
{"Success":true,"Time":0,"Text":"Average latency: 144.64ms"}
-> ok
```

Now switch off the second node from network: (wait 2-3 sec)
`ipfs ping --enc=json --count=1 QmRZq4kheCH3R4NHjeJpd5b17JkRdDSBTYMLtuYtjjfxxx`

Output:

```
{"Success":true,"Time":0,"Text":"PING QmRZq4kheCH3R4NHjeJpd5b17JkRdDSBTYMLtuYtjjfxxx."}
{"Success":true,"Time":0,"Text":"Average latency: 0.00ms"}
-> Issue is here, reported as success (maybe only an issue of evaluating the result)
```

Some seconds later: (node 2 still not connected)

```
ipfs ping --enc=json --count=1 QmRZq4kheCH3R4NHjeJpd5b17JkRdDSBTYMLtuYtjjfxxx
{"Success":true,"Time":0,"Text":"PING QmRZq4kheCH3R4NHjeJpd5b17JkRdDSBTYMLtuYtjjfxxx."}
{"Success":false,"Time":0,"Text":"Ping error: context deadline exceeded"}
-> all fine
```

**Comment by magik6k** [comment]
Relevant code if anyone wants to dig into this - https://github.com/ipfs/go-ipfs/blob/master/core/commands/ping.go#L142

**Comment by Stebalien** [comment]
We should be returning errors from ping. PR: https://github.com/libp2p/go-libp2p/pull/626
