### ISSUE TITLE
Slow at swarm connect on mobile device

### ISSUE THREAD

**Issue by rafaelekol** [ipfs/go-ipfs#6303]
IPFS version: 0.4.20
Type: Bug
Description: 
I am trying using IPFS in Android app. I managed to start Daemon and fetch json files via IPNS.
My actions are like this: First I start Daemon, then I do swarm connect to our Peer. Then I try to fetch json file via IPNS like this
`http://127.0.0.1:5001/api/v0/cat?arg=/ipns/peer_hash/rates/latest/USD/index.json` 
These actions can take about 3 minutes. The longest time takes `swarm connect`. Can I speedup this connection process?

**Comment by Stebalien** [comment]
If you _know_ the IP/port of the peer, you can specify it on connect `ipfs swarm connect /ip4/.../tcp/.../ipfs/Qm...`. It's probably taking a while to find them.

**Comment by rafaelekol** [comment]
We need it to be in decentralized way(via PeerId). Thus connecting directly by IP not suiting us.

**Comment by Stebalien** [comment]
Got it. Unfortunately, the issue here is simply that the DHT (the system we use to discover peers) is really slow at the moment. This is probably made worse by the fact that you're running on a mobile device.
