### ISSUE TITLE
pin ls should stream the result

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/go-ipfs#6304]
#### Version information:
go-ipfs version: 0.4.20-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.4

#### Description:

`pin ls` build the full result before starting to send the result. With a big repository (~1TB, millions of recursive pins), this means that the command start to output something after one hour.

It should be entirely possible to stream that result:

- output all the direct pins while adding them to the set
- output all the recursive pins while adding them to the set, ignore those already in the set
- walk the content graph from the recursive pins to get the indirect pins, ignore those already in the set

**Comment by magik6k** [comment]
I picked this up at one point - https://github.com/ipfs/go-ipfs/pull/5005, but it's so outdated that it's probably easier to redo this from scratch

**Comment by MichaelMure** [comment]
Updated PR: https://github.com/ipfs/go-ipfs/pull/6493

**Comment by Stebalien** [comment]
Thanks! Closing.

**Comment by Stebalien** [comment]
Sorry, closing the outdated PR (#5005).

**Comment by MichaelMure** [comment]
#6493 has been merged.
