### ISSUE TITLE
Release v0.4.21

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#6305]
Even though the last release was 21 days ago, a large number of important fixes prompt release of 0.4.21. 

Key Features:
  -  raise default fd limit to 8192 ([ipfs/go-ipfs#6261](https://github.com/ipfs/go-ipfs/pull/6261))
 

Key Fixes:
-  add: Fix adding multiple files ([ipfs/go-ipfs#6255](https://github.com/ipfs/go-ipfs/pull/6255)
)

TODOs:
...

**Comment by magik6k** [comment]
I'd vote for including https://github.com/ipfs/go-ipfs/pull/6300 (base32 for cidv1) in this release

**Comment by Stebalien** [comment]
> I'd vote for including #6300 (base32 for cidv1) in this release

Works for me but we'll need to wait for js-ipfs.

**Comment by obo20** [comment]
I'd like to see https://github.com/ipfs/go-ipfs/pull/6266 included in this if possible.

**Comment by obo20** [comment]
Also, I'm not sure if there's a fix for https://github.com/ipfs/go-ipfs/issues/6271 yet, but having this functionality working is one of the most important features Pinata needs right now.

**Comment by olizilla** [comment]
@Kubuxu please can we get some bullet points on what is already in this release and what's left to do?

**Comment by Stebalien** [comment]
New blocker: https://github.com/libp2p/go-libp2p/issues/644. Yay!

**Comment by davidalbela** [comment]
Hi,

Have you planned to upload the official docker image with the tag name of this release `v0.4.21` to Dockerhub? Thanks.

**Comment by olizilla** [comment]
Dockerhub has failed to trgger the build for the v0.4.21 tag. We're looking into it. In the mean time the `release` tag can be used.

https://github.com/ipfs/go-ipfs/issues/3999
