### ISSUE TITLE
Config: use YAML or TOML instead of JSON

### ISSUE THREAD

**Issue by hazae41** [ipfs/go-ipfs#6306]
#### Description:
Let's make a comparison of the IPFS config in JSON and in YAML

YAML

	API:
	  HTTPHeaders:
		Access-Control-Allow-Methods:
		- PUT
		- POST
		- GET
		Access-Control-Allow-Origin:
		- "*"
	Addresses:
	  API: "/ip4/127.0.0.1/tcp/5001"
	  Announce: []
	  Gateway: "/ip4/127.0.0.1/tcp/8080"
	  NoAnnounce: []
	  Swarm:
	  - "/ip4/0.0.0.0/tcp/4001"
	  - "/ip6/::/tcp/4001"
	Bootstrap:
	- "/dnsaddr/bootstrap.libp2p.io/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN"
	- "/dnsaddr/bootstrap.libp2p.io/ipfs/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa"
	- "/dnsaddr/bootstrap.libp2p.io/ipfs/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
	- "/dnsaddr/bootstrap.libp2p.io/ipfs/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"
	- "/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"
	- "/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM"
	- "/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu"
	- "/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64"
	- "/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd"
	- "/ip6/2604:a880:1:20::203:d001/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM"
	- "/ip6/2400:6180:0:d0::151:6001/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu"
	- "/ip6/2604:a880:800:10::4a:5001/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64"
	- "/ip6/2a03:b0c0:0:1010::23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd"
	Datastore:
	  BloomFilterSize: 0
	  GCPeriod: 1h
	  HashOnRead: false
	  Spec:
		mounts:
		- child:
			path: blocks
			shardFunc: "/repo/flatfs/shard/v1/next-to-last/2"
			sync: true
			type: flatfs
		  mountpoint: "/blocks"
		  prefix: flatfs.datastore
		  type: measure
		- child:
			compression: none
			path: datastore
			type: levelds
		  mountpoint: "/"
		  prefix: leveldb.datastore
		  type: measure
		type: mount
	  StorageGCWatermark: 90
	  StorageMax: 10GB
	Discovery:
	  MDNS:
		Enabled: true
		Interval: 10
		enabled: true
	Experimental:
	  FilestoreEnabled: false
	  Libp2pStreamMounting: false
	  P2pHttpProxy: false
	  QUIC: false
	  ShardingEnabled: false
	  UrlstoreEnabled: false
	Gateway:
	  APICommands: []
	  HTTPHeaders:
		Access-Control-Allow-Headers:
		- X-Requested-With
		- Range
		- User-Agent
		Access-Control-Allow-Methods:
		- GET
		Access-Control-Allow-Origin:
		- "*"
	  NoFetch: false
	  PathPrefixes: []
	  RootRedirect: ''
	  Writable: false
	Identity:
	  PeerID: QmUuAD3WionaEQ6VX1ZubJg9R5sjmJiYr2MCTEeuWdRYXF
	Ipns:
	  RecordLifetime: ''
	  RepublishPeriod: ''
	  ResolveCacheSize: 128
	Mounts:
	  FuseAllowOther: false
	  IPFS: "/ipfs"
	  IPNS: "/ipns"
	Pubsub:
	  DisableSigning: false
	  Router: ''
	  StrictSignatureVerification: false
	Reprovider:
	  Interval: 12h
	  Strategy: all
	Routing:
	  Type: dht
	Swarm:
	  AddrFilters: 
	  ConnMgr:
		GracePeriod: 300s
		HighWater: 300
		LowWater: 50
		Type: basic
	  DisableBandwidthMetrics: false
	  DisableNatPortMap: false
	  DisableRelay: false
	  EnableAutoNATService: false
	  EnableAutoRelay: false
	  EnableRelayHop: false

JSON

	{
		"API": {
			"HTTPHeaders": {
				"Access-Control-Allow-Methods": [
					"PUT",
					"POST",
					"GET"
				],
				"Access-Control-Allow-Origin": [
					"*"
				]
			}
		},
		"Addresses": {
			"API": "/ip4/127.0.0.1/tcp/5001",
			"Announce": [],
			"Gateway": "/ip4/127.0.0.1/tcp/8080",
			"NoAnnounce": [],
			"Swarm": [
				"/ip4/0.0.0.0/tcp/4001",
				"/ip6/::/tcp/4001"
			]
		},
		"Bootstrap": [
			"/dnsaddr/bootstrap.libp2p.io/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
			"/dnsaddr/bootstrap.libp2p.io/ipfs/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
			"/dnsaddr/bootstrap.libp2p.io/ipfs/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
			"/dnsaddr/bootstrap.libp2p.io/ipfs/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
			"/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
			"/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
			"/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
			"/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
			"/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
			"/ip6/2604:a880:1:20::203:d001/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
			"/ip6/2400:6180:0:d0::151:6001/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
			"/ip6/2604:a880:800:10::4a:5001/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
			"/ip6/2a03:b0c0:0:1010::23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd"
		],
		"Datastore": {
			"BloomFilterSize": 0,
			"GCPeriod": "1h",
			"HashOnRead": false,
			"Spec": {
				"mounts": [
					{
						"child": {
							"path": "blocks",
							"shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
							"sync": true,
							"type": "flatfs"
						},
						"mountpoint": "/blocks",
						"prefix": "flatfs.datastore",
						"type": "measure"
					},
					{
						"child": {
							"compression": "none",
							"path": "datastore",
							"type": "levelds"
						},
						"mountpoint": "/",
						"prefix": "leveldb.datastore",
						"type": "measure"
					}
				],
				"type": "mount"
			},
			"StorageGCWatermark": 90,
			"StorageMax": "10GB"
		},
		"Discovery": {
			"MDNS": {
				"Enabled": true,
				"Interval": 10,
				"enabled": true
			}
		},
		"Experimental": {
			"FilestoreEnabled": false,
			"Libp2pStreamMounting": false,
			"P2pHttpProxy": false,
			"QUIC": false,
			"ShardingEnabled": false,
			"UrlstoreEnabled": false
		},
		"Gateway": {
			"APICommands": [],
			"HTTPHeaders": {
				"Access-Control-Allow-Headers": [
					"X-Requested-With",
					"Range",
					"User-Agent"
				],
				"Access-Control-Allow-Methods": [
					"GET"
				],
				"Access-Control-Allow-Origin": [
					"*"
				]
			},
			"NoFetch": false,
			"PathPrefixes": [],
			"RootRedirect": "",
			"Writable": false
		},
		"Identity": {
			"PeerID": "QmUuAD3WionaEQ6VX1ZubJg9R5sjmJiYr2MCTEeuWdRYXF"
		},
		"Ipns": {
			"RecordLifetime": "",
			"RepublishPeriod": "",
			"ResolveCacheSize": 128
		},
		"Mounts": {
			"FuseAllowOther": false,
			"IPFS": "/ipfs",
			"IPNS": "/ipns"
		},
		"Pubsub": {
			"DisableSigning": false,
			"Router": "",
			"StrictSignatureVerification": false
		},
		"Reprovider": {
			"Interval": "12h",
			"Strategy": "all"
		},
		"Routing": {
			"Type": "dht"
		},
		"Swarm": {
			"AddrFilters": null,
			"ConnMgr": {
				"GracePeriod": "300s",
				"HighWater": 300,
				"LowWater": 50,
				"Type": "basic"
			},
			"DisableBandwidthMetrics": false,
			"DisableNatPortMap": false,
			"DisableRelay": false,
			"EnableAutoNATService": false,
			"EnableAutoRelay": false,
			"EnableRelayHop": false
		}
	}

YAML is a lot more human-readable than JSON especially for complex and error-prone configurations such as IPFS

More: https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/

**Comment by hazae41** [comment]
TOML can be a good replacement as well 

	Bootstrap = [
	  "/dnsaddr/bootstrap.libp2p.io/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
	  "/dnsaddr/bootstrap.libp2p.io/ipfs/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
	  "/dnsaddr/bootstrap.libp2p.io/ipfs/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
	  "/dnsaddr/bootstrap.libp2p.io/ipfs/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
	  "/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
	  "/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
	  "/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
	  "/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
	  "/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
	  "/ip6/2604:a880:1:20::203:d001/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
	  "/ip6/2400:6180:0:d0::151:6001/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
	  "/ip6/2604:a880:800:10::4a:5001/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
	  "/ip6/2a03:b0c0:0:1010::23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd"
	]

	[API]

	  [API.HTTPHeaders]
	  Access-Control-Allow-Methods = [
		"PUT",
		"POST",
		"GET"
	  ]
	  Access-Control-Allow-Origin = [
		"*"
	  ]

	[Addresses]
	API = "/ip4/127.0.0.1/tcp/5001"
	Announce = []
	Gateway = "/ip4/127.0.0.1/tcp/8080"
	NoAnnounce = []
	Swarm = [
	  "/ip4/0.0.0.0/tcp/4001",
	  "/ip6/::/tcp/4001"
	]

	[Datastore]
	BloomFilterSize = 0.0
	GCPeriod = "1h"
	HashOnRead = false
	StorageGCWatermark = 90.0
	StorageMax = "10GB"

	  [Datastore.Spec]
	  type = "mount"

		[[Datastore.Spec.mounts]]
		mountpoint = "/blocks"
		prefix = "flatfs.datastore"
		type = "measure"

		  [Datastore.Spec.mounts.child]
		  path = "blocks"
		  shardFunc = "/repo/flatfs/shard/v1/next-to-last/2"
		  sync = true
		  type = "flatfs"

		[[Datastore.Spec.mounts]]
		mountpoint = "/"
		prefix = "leveldb.datastore"
		type = "measure"

		  [Datastore.Spec.mounts.child]
		  compression = "none"
		  path = "datastore"
		  type = "levelds"

	[Discovery]

	  [Discovery.MDNS]
	  Enabled = true
	  Interval = 10.0
	  enabled = true

	[Experimental]
	FilestoreEnabled = false
	Libp2pStreamMounting = false
	P2pHttpProxy = false
	QUIC = false
	ShardingEnabled = false
	UrlstoreEnabled = false

	[Gateway]
	APICommands = []
	NoFetch = false
	PathPrefixes = []
	RootRedirect = ""
	Writable = false

	  [Gateway.HTTPHeaders]
	  Access-Control-Allow-Headers = [
		"X-Requested-With",
		"Range",
		"User-Agent"
	  ]
	  Access-Control-Allow-Methods = [
		"GET"
	  ]
	  Access-Control-Allow-Origin = [
		"*"
	  ]

	[Identity]
	PeerID = "QmUuAD3WionaEQ6VX1ZubJg9R5sjmJiYr2MCTEeuWdRYXF"

	[Ipns]
	RecordLifetime = ""
	RepublishPeriod = ""
	ResolveCacheSize = 128.0

	[Mounts]
	FuseAllowOther = false
	IPFS = "/ipfs"
	IPNS = "/ipns"

	[Pubsub]
	DisableSigning = false
	Router = ""
	StrictSignatureVerification = false

	[Reprovider]
	Interval = "12h"
	Strategy = "all"

	[Routing]
	Type = "dht"

	[Swarm]
	DisableBandwidthMetrics = false
	DisableNatPortMap = false
	DisableRelay = false
	EnableAutoNATService = false
	EnableAutoRelay = false
	EnableRelayHop = false

	  [Swarm.ConnMgr]
	  GracePeriod = "300s"
	  HighWater = 300.0
	  LowWater = 50.0
	  Type = "basic"

**Comment by hazae41** [comment]
YAML for Go https://github.com/go-yaml/yaml

YAML for JavaScript https://github.com/nodeca/js-yaml

**Comment by bertrandfalguiere** [comment]
I guess it should be possible to convert a YAML or TOML file into a JSON on-the-fly so that the user can use either format.

**Comment by DonaldTsang** [comment]
Sounds like a good format, are there any other alternatives?

**Comment by hazae41** [comment]
I think a lot of developers knows YAML. For others, there is a lot of documentation available for YAML and this would not be painful to learn as it is human-readable.

**Comment by DonaldTsang** [comment]
@hazae41 might want to read this article https://github.com/crystal-lang/shards/issues/25

**Comment by hazae41** [comment]
HOCON is very good compared to YAML or TOML as it is interoperable with JSON and there is a powerful "include" notation https://github.com/lightbend/config/blob/master/HOCON.md#includes
