### ISSUE TITLE
Use 0.0.0.0 instead of 127.0.0.1 for API and Gateway

### ISSUE THREAD

**Issue by hazae41** [ipfs/go-ipfs#6314]
#### Description: 
When the daemon is running in a container with a custom hostname, API and Gateway are unavailable until we set 0.0.0.0 instead of 127.0.0.1 in the config

**Comment by Stebalien** [comment]
The docker image (see the `Dockerfile` and `bin/container_daemon` files) automatically sets the gateway/API addresses to 0.0.0.0.

**Comment by hazae41** [comment]
This should be available for all containers, not just Docker

**Comment by Stebalien** [comment]
You can configure your container image to launch ipfs with the `container_daemon` script or you can manually configure go-ipfs. There isn't really anything go-ipfs itself can do here and changing the defaults for everyone would be a massive security issue.
