### ISSUE TITLE
Multipart `Block-put` for multiple block injection

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipfs#6315]
#### Description:

I would like to have a "streaming" block-put where I can send many blocks on a single request to the `block/put` http endpoint. I don't think this works right now (correct me if I missed it).

Ideally the happy path is to translate this into a nicely buffered and optimized `PutMany()` so that, when ingesting many blocks via the API, there is a significant performance gain vs injecting one by one.

**Comment by Stebalien** [comment]
I agree. We'll have to make sure to use `EmitOnce` when only putting one block for compatibility with js-ipfs but that's not that bad.

The only interesting thing here is that the current block API in the core API doesn't support batch put. See: https://github.com/ipfs/interface-go-ipfs-core/issues/31.

**Comment by magik6k** [comment]
https://github.com/ipfs/go-ipfs/pull/6331
