### ISSUE TITLE
CI isn't failing for go tests that don't compile

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6320]
See: https://github.com/ipfs/go-ipfs/pull/6319

Any ideas?

**Comment by cbuesser** [comment]
I think this is happening because your 

```bash
$ make -j 1 test/unit/gotest.junit.xml \
$ && [[ ! $(jq -s -c 'map(select(.Action == "fail")) | .[] test/unit/gotest.json) ]] 
```
is returning a 0 when it fails to parse a:
```json
FAIL github.com/ipfs/go-ipfs/cmd/ipfs/util [build failed]
```
line in the test/unit/gotest.json

**Comment by magik6k** [comment]
That looks like a `go test` bug

**Comment by magik6k** [comment]
https://github.com/golang/go/issues/23037, we can implement a work around
