### ISSUE TITLE
Please include a systemd script

### ISSUE THREAD

**Issue by cbluth** [ipfs/go-ipfs#6323]
#### Type:

- "doc": If it's related to missing/incorrect documentation.

#### Description:
 
Hello,

I am looking for a systemd script to run this as a service for multiple users.

**Comment by magik6k** [comment]
There were a few systemd related PRs in the past: https://github.com/ipfs/go-ipfs/pull/5583 https://github.com/ipfs/go-ipfs/pull/1864

**Comment by NatoBoram** [comment]
There's an example here : https://github.com/ipfs/website/tree/master/static/docs/examples/init#systemd

**Comment by koalalorenzo** [comment]
Some points that are related to this
`go-ipfs` looks like it is not really built as a service for all the users. Once you run ipfs as a systemd service all the users that wants to use IPFS are forced to:

1. Use the API: this should be the default behaviour but requires `IPFS_PATH` to be set anyway or `--api`
2. Set up `IPFS_PATH` and have the permissions to run commands

Systemd does support user services, but that doesn't help much if it is a multi user system where all the users wants IPFS running even if they are not logged in (please correct me if I am wrong!). 

I hope to see ipfs growing into a more stable daemon that can be run on systemd!

**Comment by Stebalien** [comment]
You can actually configure the ipfs client to use a remote server by running:

```bash
> mkdir -p ~/.ipfs
> echo '/dns4/localhost/tcp/5001' > ~/.ipfs/api
```

We should _probably_ have a nice command for this.

**Comment by koalalorenzo** [comment]
> You can actually configure the ipfs client to use a remote server by running:
> 
> ```shell
> > mkdir -p ~/.ipfs
> > echo '/dns4/localhost/tcp/5001' > ~/.ipfs/api
> ```
> 
> We should _probably_ have a nice command for this.

My point is that it should not be required to do that if it was a service. Hashicorp's products are a good example.

**Comment by Stebalien** [comment]
Ah, yeah, I agree (but we need multitenent support for that to really happen).

**Comment by cbluth** [comment]
finally, some info on how to run ipfs for multiple users!

**Comment by koalalorenzo** [comment]
We are maintaining also a apt repository with deb packages (works both for ubuntu and deb) that includes the service for multiple user: 
https://blog.siderus.io/how-to-get-ipfs-on-ubuntu-debian-linux-d7920c1a42b7

The builds are automated and we are using it on most of the gateways. `ipfs-gateway` is the name of the package for the global service but it requires are repo in `/var/ipfs`

**Comment by Stebalien** [comment]
Done. See misc/systemd.
