### ISSUE TITLE
Bug Party

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6324]
🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛

**What**

Squash all the bugs (or at least triage them).

**When**

May 14-16

**Where**

Right here and on [#ipfs-dev:matrix.org](https://matrix.to/#/!yUPGdymyMBYidlxQfd:matrix.org?via=matrix.org&via=t2bot.io) (or #ipfs-dev on Freenode).

**Why**

We have _way_ too many bugs.

🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

---

Tracking spreadsheet: https://docs.google.com/spreadsheets/d/1hFloma49nf62WbN0fU1wqt0vxyrY3v9L3K7hOJOpIjs/edit?usp=sharing

Instructions:

1. Pick an unassigned issue from that spreadsheet.
2. Write your github handle in the "Assignee" field.
3. Investigate the issue.
4. Fill out the resolution.
5. Repeat.

**Comment by djdv** [comment]
Cool!
![more like bug bash](https://user-images.githubusercontent.com/13862850/57964185-ff31f080-78fe-11e9-86e5-24ebc6e4917c.png)

**Comment by Stebalien** [comment]
Final stats: Starting with a total of 953 issues/PRs, we triaged 238 (25%) of these issues. Out of these, we validated 125 (~53%), iceboxed 3, and closed 110 (~46%).

We haven't finished by a long shot but, if we keep this up, we can make a pretty big dent.
