### ISSUE TITLE
Add a flag to optionally output hash in MFS while adding/creating Directory/Files

### ISSUE THREAD

**Issue by vasa-develop** [ipfs/go-ipfs#6326]
This is a feature request originated from **[this](https://discuss.ipfs.io/t/can-we-add-a-flag-to-optionally-output-hash-in-mfs-while-adding-creating-directory-files/5403)** thread on IPFS discussion Forum.

This feature request involves the introduction of a new flag for MFS, to optionally get the directory/file hashes when using `mkdir` OR `write` commands.

**Comment by djdv** [comment]
Associating these 2 issues: https://github.com/ipfs/go-ipfs/issues/2610

**Comment by aschmahmann** [comment]
closing this for further discussion of API overhaul on #7493
