### ISSUE TITLE
ipfs add with wild card only add the first file.

### ISSUE THREAD

**Issue by ylussaud** [ipfs/go-ipfs#6328]
#### Version information:

go-ipfs version: 0.4.20-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.4

#### Type:

bug

#### Description:

Using wild card when adding files to ipfs  doesn't work any more. Only the first file is added even if the total size seems to be properly computed:

ipfs add Z*
added Qm.... Za....
 362.07 MiB / 14.78 GiB [>--------------------------------------]   2.39% 01m32s

Adding recursively a folder work as expected.

As a work around I moved back to 0.4.19.

**Comment by magik6k** [comment]
This is https://github.com/ipfs/go-ipfs/issues/6254, and was fixed in https://github.com/ipfs/go-ipfs/pull/6255
