### ISSUE TITLE
Usage + APIs

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#633]
- [ ] provide CLI overview
- [ ] provide Golang API overview btc
- [ ] provide JSON API overview
- [ ] mention node-ipfs JS bindings

**Comment by jbenet** [comment]
I'd like to command and API docs. We have `ipfs commands` which outputs the list. we can probably also trivially generate one page with _all_ the help texts (i've done this before) separated by markdown headers, with a markdown TOC at the head. The API is a bit trickier, as it involves translating our commands lib into nice, standard API text. Definitely doable. 

Here are some nice api docs to emulate:
- https://stripe.com/docs/api#transfers
- https://developer.github.com/v3/
- https://coreos.com/docs/
- http://backbonejs.org/docs/backbone.html

Maybe we can generate much of the markdown needed for slate: https://github.com/tripit/slate -- though we'd still need lots of examples.

cc @mappum

**Comment by diasdavid** [comment]
API's are now all being documented at https://github.com/ipfs/api  🎉🎉🎉

**Comment by diasdavid** [comment]
Update: 

- https://github.com/ipfs/api
- https://github.com/ipfs/api/pull/17
- https://github.com/ipfs/specs/pull/65
