### ISSUE TITLE
clone IPFS

### ISSUE THREAD

**Issue by hnamzian** [ipfs/go-ipfs#6334]
How is it possible to clone IPFS and create a private IPFS network?

**Comment by suutaku** [comment]
all data and peers ? why you need clone ipfs?

**Comment by hnamzian** [comment]
I want to clone IPFS to use as in a private project. In fact I want to run IPFS on my own peers.

**Comment by suutaku** [comment]
you just build a private network by using a swam.key.
Im using private network now. 
try to google `ipfs private network` you will find how to do.

**Comment by hnamzian** [comment]
Thank you

**Comment by Stebalien** [comment]
In the future, let's try to keep questions on https://discuss.ipfs.io and the #ipfs IRC channel.
