### ISSUE TITLE
Performace, or How IPFS will be better than BitTorrent

### ISSUE THREAD

**Issue by DonaldTsang** [ipfs/go-ipfs#6342]
Here are a list of issues that is plaguing IPFS: Performace. It has to beat existing system to gain a wider adoption. One factor is "the default should be semi-optimal", where once installed, without much parameter tweaking, it will perform better than BitTorrent.
- https://github.com/ipfs/go-ipfs/issues/2111 (transfer speed)
- https://github.com/ipfs/go-ipfs/issues/2828 (DHT management) 
- https://github.com/ipfs/go-ipfs/issues/2917 (network traffic usage)
- https://github.com/ipfs/go-ipfs/issues/3429 (another bandwidth usage)
- https://github.com/ipfs/go-ipfs/issues/3545 (file adding)
- https://github.com/ipfs/go-ipfs/issues/3638 (import issue)
- https://github.com/ipfs/go-ipfs/issues/3885 (hanging system)
- https://github.com/ipfs/go-ipfs/issues/5221 (slow pinning)
- https://github.com/ipfs/go-ipfs/issues/5438 (another)
- https://github.com/ipfs/go-ipfs/issues/5723 (Bitswap)

Here are some tests
- https://github.com/ipfs/go-ipfs/issues/3131 (speed testing)
- https://github.com/ipfs/go-ipfs/issues/3316 (adding files)
- https://github.com/ipfs/go-ipfs/issues/3317 (high-speed ethernet)
- https://github.com/ipfs/go-ipfs/issues/3860 (IPNS)
- https://github.com/ipfs/go-ipfs/issues/5037 (another speed test)
- https://github.com/ipfs/go-ipfs/issues/5226 (newer test)
- https://github.com/ipfs/go-ipfs/issues/5420 (further analysis)

**Comment by Stebalien** [comment]
Yes we have performance issues and we're working on them. But this issue doesn't really add anything to the discussion.

**Comment by DonaldTsang** [comment]
@Stebalien I was expecting this to be a meta-issue on performance

**Comment by Stebalien** [comment]
Ah, got it. My concern with this issue is that it's kind of a grab bag of different unrelated performance issues and we already have a `perf` label.

There appear to be four categories:

* IPNS is slow: https://github.com/ipfs/go-ipfs/issues/3860
* Adding files to go-ipfs is slow. Could probably use a good meta issue, want to make one?
* Bitswap transfer speed is slow: https://github.com/ipfs/go-ipfs/issues/5723
* IPFS uses a lot of background bandwidth: https://github.com/ipfs/go-ipfs/issues/3429 (may need a better meta issue?).

**Comment by DonaldTsang** [comment]
@Stebalien In that case making a meta-issue for all four topics would be better, it would make reading easier.

**Comment by jasonzhouu** [comment]
suggest a new item:
- https://github.com/ipfs/go-ipfs/issues/6382 (latency of DHT resolving)

**Comment by DonaldTsang** [comment]
@jasonzhouu are you suggesting to combine those two issues?

**Comment by jasonzhouu** [comment]
@DonaldTsang 
I'm suggesting add the first one
And change the description of the second one, which already exist in your list.

**Comment by Stebalien** [comment]
I've created a meta issue for resolution delay #6383.

**Comment by jasonzhouu** [comment]
> I've created a meta issue for resolution delay #6383.

Awesome!
