### ISSUE TITLE
How to create permanent connection (keep alive) with "IPFS swarm connect"

### ISSUE THREAD

**Issue by nk-the-crazy** [ipfs/go-ipfs#6347]
IPFS version: 0.4.20
-----
To speedup content discovery, creating connection to source peer
( via  "ipfs swarm connect /PEER_MULTI_ADDRESS". ).
Connection is succeeded but why it is disconnecting unexpectedly (connection is alive for max 10 - 40 secs). I assume,  this issue was solved in 0.4.20 (by marking it as "important"). 
Or Am I missing something ?

**Comment by obo20** [comment]
The fix you're referring to unfortunately doesn't work. See: https://github.com/ipfs/go-ipfs/issues/6271
