### ISSUE TITLE
circuit relay not connect peers automatically 

### ISSUE THREAD

**Issue by suutaku** [ipfs/go-ipfs#6351]
go version: go1.12.5 darwin/amd64
OS:  Mac OS X 10.14
ipfs version: 0.4.21-dev

peer1: behind NAT 1
peer2: with public IP
peer3: behind NAT 2

`ipfs swarm peers`

peer1  ---> peer2 [OK]
peer3 ---> peer2 [OK]
peer1  ---> peer3 [NOT OK]

if ruing ipfs swarm connect by hand

At peer3
```
ipfs swarm connect /ipfs/peer2/p2p-circuit/ipfs/peer1 [OK]
```
At peer1
```
ipfs swarm connect /ipfs/peer2/p2p-circuit/ipfs/peer3 [OK]
```

problem is peer1 and peer3 can connect each other via p2p circuit but not going connect automatically. it is I missed some thing?

**Comment by Stebalien** [comment]
Peer 1 doesn't know that peer 3 is behind peer 2. If you enable the autorelay service (https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#autorelay) on peer3, it will:

1. Automatically search for relays.
2. Advertise them.

However, you may need to enable AutoRelay on peer2 as well for peer3 to decide to use it. Unfortunately, if you enable both `AutoRelay` and `Relay.Hop` on peer2, that peer will start acting as a relay for the rest of the network.

@vyzo is this correct?

**Comment by vyzo** [comment]
yes, it is correct.

**Comment by suutaku** [comment]
Thanks. So what should I do is enable AutoRelay both 3 peers and also enable RelayHop on peers2?
> Unfortunately, if you enable both AutoRelay and Relay.Hop on peer2, that peer will start acting as a relay for the rest of the network.

As a really for the rest of the network is not a good thing for peer2?

**Comment by Stebalien** [comment]
> As a really for the rest of the network is not a good thing for peer2?

Well, there are a _lot_ of nodes on the network. You'll get a _lot_ of connections and it will use a lot of bandwidth. My point is that there's no built-in support for _private_ relays at the moment.

**Comment by Stebalien** [comment]
(closing for tracking as this is a question)
