### ISSUE TITLE
Rename "ipfs" command to "goipfs"

### ISSUE THREAD

**Issue by hazae41** [ipfs/go-ipfs#6371]
This would be useful for differentiate it from js-ipfs

**Comment by Stebalien** [comment]
Unfortunately, that would also break everything that depends on the ipfs command and assumes that it's called ipfs. Installing go-ipfs should continue to "just work" by default and the fallout here just isn't worth it.

However, package maintainers and users are free to call the binary whatever they want. For example, Debian could use it's [Alternatives System](https://wiki.debian.org/DebianAlternatives) to provide an `ipfs` command that's actually just a symlink to either js-ipfs or go-ipfs.

If/when the ipfs-update command supports js-ipfs, we can consider doing something similar (install go-ipfs as go-ipfs, js-ipfs as js-ipfs, and symlink `ipfs` to the user's preferred implementation).

---

Also note: 99.9% of users on a desktop are going to want to install go-ipfs for performance reasons. While js-ipfs can run in node, it was really built for the browser (you'll notice that the npm package is just called 'ipfs', not 'js-ipfs').
