### ISSUE TITLE
ipfs not installing

### ISSUE THREAD

**Issue by rathanu** [ipfs/go-ipfs#6377]
everytime i try to install "go-ipfs"
this happens
i dont understand 
pls help

kabuli@Kabulis-MacBook-Pro:~/go-ipfs$ make install
dyld: Symbol not found: _unlinkat
  Referenced from: /usr/local/go/bin/go
  Expected in: flat namespace

dyld: Symbol not found: _unlinkat
  Referenced from: /usr/local/go/bin/go
  Expected in: flat namespace

dyld: Symbol not found: _unlinkat
  Referenced from: /usr/local/go/bin/go
  Expected in: flat namespace

make: *** [check_go_version] Trace/BPT trap: 5

pls help me

**Comment by Stebalien** [comment]
This is the best answer I could find: https://trac.macports.org/ticket/58138. Unfortunately, this isn't an issue with go-ipfs so there isn't much we can do to help.

I recommend installing go from https://golang.org/dl/.

**Comment by rathanu** [comment]
I did install GoLang. .but i dunno. I might have deleted some files in
/usr/local/go/bin .. And everytime that message is showing up

**Comment by Stebalien** [comment]
Yes but _where_ did you install it from? It looks looks like you installed some stuff from macports (or elsewhere?) and go isn't happy about it.

**Comment by rathanu** [comment]
😂😂 maybe. I'll send u as to where I downloaded it from..

**Comment by rathanu** [comment]
heyy man ..can u help me out.. im running Flask for the first time.. and i
dont understand as to whats happening. whats goin on here and why is it not
working.. pls help me.. my Blockchain app is not working

.. [image: Screen Shot 2019-06-04 at 9.00.08 pm.png]

**Comment by Stebalien** [comment]
I can't see that screenshot but there's likely nothing I can do to help.

**Comment by younasm** [comment]
Hi,

I just install ipfs using the ipfs CLI code on ipfs.io website.

after installation when I enter `ipfs --version` in terminal it gives me the following error.

```
dyld[48654]: symbol not found in flat namespace ''
zsh: abort      ipfs
```

I am using Macbook m1 pro chip
