### ISSUE TITLE
Run js interop tests in Circle

### ISSUE THREAD

**Issue by magik6k** [ipfs/go-ipfs#6393]
To keep things like https://github.com/ipfs/go-ipfs/issues/6389 from happening

**Comment by Stebalien** [comment]
@magik6k how do we make this happen without blocking PRs. IIRC, interop tests can take >20 minutes. Is it possible to schedule nightly tests runs in Circle?

**Comment by magik6k** [comment]
Afaik Yes.

Also, wouldn't just marking the check as optional be enough?

**Comment by Stebalien** [comment]
> Also, wouldn't just marking the check as optional be enough?

Yeah, actually, it should. Especially if we get emails on failure.

**Comment by Stebalien** [comment]
Tracking broken tests:

*  [ci failure](https://circleci.com/gh/ipfs/go-ipfs/16697?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
  * [ ] IPNS pubsub issue: https://github.com/ipfs/interop/issues/71
  * [ ] Files issue: https://github.com/ipfs/interop/issues/75
