### ISSUE TITLE
ipfs get over one hop not working

### ISSUE THREAD

**Issue by ligi** [ipfs/go-ipfs#6407]
to reproduce this I need 3 machines - all run go-ipfs 0.4.21:

machine 1 (lets call 'server' here) has a public IP
machine 2 (lets call 'client' here) is behind a NAT

now I can connect from machine 2 to machine 1 via `ipfs swarm connect` and get content that is pinned on machine 1

now introducing machine 3 which is in the same network as machine 1 and connect them via `ipfs swarm connect` in both ways (I think there should be a way to do it one way only - see this coment: https://github.com/ipfs/go-ipfs/issues/6271#issuecomment-498843986) so I can get content pinned on machine 1 by machine 3 and the other way around
But now when I try to get content pinned on 3 with machine 2 it is not working. It is directly downloading when I `ipfs get` the content on machine 1

**Comment by Stebalien** [comment]
If I'm understanding this correctly, the issue is that machine 1 will not fetch content from machine 3 on behalf of machine 2. This was a planned feature in the original IPFS whitepaper but has a bunch of legal implications that need to be thought through before it's practical.

At the moment, machine 1 can make itself a public relay but then it'll relay traffic for _any_ peer on the network.

**Comment by ligi** [comment]
Can't machine 1 not just establish a encrypted communication between node 2 and 3 so it does not know the content it is transporting? Was already puzzled that I manually have to connect nodes to get content from A to B - if what you say is true that makes IPFS unusable for me.

**Comment by deviousasti** [comment]
I'm assuming there's peer exchange happening on all nodes.
But will the public peer be able to assist in traversing NAT?

```

             +-------------------+ Public Server  +---------------+
             |                                                    |
             |                                                    |
             |                                                    |
             |                                                    |
             +                                                    |
+----------CGNAT+-------+                            +---------Single NAT---+
|            +          |                            |            |         |
|            +          |                            |            +         |
|        Machine 2      |                            |      Machine 1       |
|                       |                            |                      |
|                       |                            |                      |
+-----------------------+                            +----------------------+

```

> At the moment, machine 1 can make itself a public relay but then it'll relay traffic for _any_ peer on the network.

Is circuit relay operational at the moment?

**Comment by Stebalien** [comment]
> Can't machine 1 not just establish a encrypted communication between node 2 and 3 so it does not know the content it is transporting? 

It can using the p2p-circuit ("relay") transport. However:

@ligi

Nodes won't relay traffic by default as this can easily run up a large bandwidth bill. However, you can _enable_ this on node 1 by setting `Swarm.EnableRelayHop` to true.

There's no way for node 2 to _know_ that node 3 is connected to node 1 as well unless node 1 says so by announcing a special relay address. You can do this manually by adding a p2p-circuit address to `Addresses.Announce` ("/p2p/QmNode1/p2p-circuit").

You can also _automatically_ use a public relay by enabling `Swarm.EnableAutoRelay`. If you do that, your node will (a) find a public relay and (b) advertise a relay address using that relay. However, node 1 won't automatically be a public relay.

You can _make_ it a public relay by additionally setting `Swarm.EnableRelayHop`. However, doing so will make your node _very_ popular and may cost quite a bit in terms of bandwidth.

**Comment by Stebalien** [comment]
@deviousasti 

> Is circuit relay operational at the moment?

Yes (ish). Nodes will connect to other nodes _through_ relays by default if those nodes advertise a relay. However:

1. Nodes won't _act_ as relays by default unless configured to do so (`Swarm.EnableRelayHop`).
2. Nodes won't announce relays by default unless configured to do so (`Swarm.EnableAutoRelay`).

**Comment by godcong** [comment]
> I'm assuming there's peer exchange happening on all nodes.
> But will the public peer be able to assist in traversing NAT?
> 
> I can't get 1 to talk to 2. They can both talk to the public peer though.
> 
> ```
> 
>              +-------------------+ Public Server  +---------------+
>              |                                                    |
>              |                                                    |
>              |                                                    |
>              |                                                    |
>              +                                                    |
> +----------CGNAT+-------+                            +---------Single NAT---+
> |            +          |                            |            |         |
> |            +          |                            |            +         |
> |        Machine 2      |                            |      Machine 1       |
> |                       |                            |                      |
> |                       |                            |                      |
> +-----------------------+                            +----------------------+
> ```
> 
> > At the moment, machine 1 can make itself a public relay but then it'll relay traffic for _any_ peer on the network.
> 
> Is circuit relay operational at the moment?
i used `frp` to link machine 2 with a public IP Machine
