### ISSUE TITLE
Error: unknown datastore type: flatfs

### ISSUE THREAD

**Issue by Joe0826** [ipfs/go-ipfs#6416]
My computer is Windows 10 64bit, I have been rebuild a new IPFS.exe fellow the stop of https://github.com/ipfs/go-ipfs/blob/master/docs/windows.md#minimal. There are no problem during the process  and result can see:
![image](https://user-images.githubusercontent.com/32236734/58945029-9dee9600-87b5-11e9-8476-d9265fce3a2b.png)
But when I want run the .\ipfs.exe  in cmd, it show like this:
![image](https://user-images.githubusercontent.com/32236734/58945012-93340100-87b5-11e9-8a67-fbfc10d6a6a7.png)
I don't know the reason for this Error and what does it mean
I need you help,please tell me what's wrong with this.
Thank you very much

**Comment by Stebalien** [comment]
What's the output of `git status`? It looks like you may have modified one of the the plugin/loader/preload.go source file.
