### ISSUE TITLE
Extract the `provider` module

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipfs#6417]
I would like to use `provider` (in its current encarnation and in the future ones) separately from go-ipfs (just like I use everything else like bitswap or merkledag).

Therefore I would like to request permission to extract this submodule into its own repository.

**Comment by Stebalien** [comment]
Michael is currently working on the provider subsystem so he has volunteered to extract it.

**Comment by michaelavila** [comment]
@hsanjuan sounds good. I'll take care of this right away.

**Comment by michaelavila** [comment]
@hsanjuan a few notes:

* I moved the `provider` module out to https://github.com/ipfs/go-ipfs-provider. 
* I'm waiting to get https://github.com/ipfs/go-ipfs/pull/6421 reviewed and merged.
* I am starting work now on the README, ci, etc, for `go-ipfs-provider`, but you should be good to test integrating it with `ipfs-lite`.
* As part of getting https://github.com/ipfs/go-ipfs/pull/6421 merged I am going to tag an official version of `go-ipfs-provider`, but until then can you just reference a commit?
