### ISSUE TITLE
I can not access my file through a public gateway or different node, only locally

### ISSUE THREAD

**Issue by anarkrypto** [ipfs/go-ipfs#6425]
**$ hash=`echo "I <3 IPFS -$(whoami)" | ipfs add -**

**$ curl "http://127.0.0.1:8080/ipfs/$hash"**
_I <3 IPFS -anarkrypto_
### 
**$ curl "https://ipfs.io/ipfs/$hash"**
...Loading Forever... 

Ports 4001, 4002 and 5001 are already open.
The config seems okay.
No error log with ipfs daemon so far

ipfs version 0.4.21
Ubuntu 18.04

I opened a discussion in the community. But no one answered yet.
https://discuss.ipfs.io/t/i-can-not-access-my-file-through-a-gateway-or-another-node/5598/3

**Comment by anarkrypto** [comment]
If I try connect to my vps from my pc
**$ ipfs swarm connect "/ip4/104.211.48.196/tcp/4001/ipfs/Qmbv3mQrWzYXmqM3LdrUMnCysP9UAqSXnfn3yXoQdjrZFV"**
_Error: connect Qmbv3mQrWzYXmqM3LdrUMnCysP9UAqSXnfn3yXoQdjrZFV failure: failed to dial : all dials failed
  * [/ip4/104.211.48.196/tcp/4001] dial tcp4 0.0.0.0:4001->104.211.48.196:4001: i/o timeout_

**nc 104.211.48.196 4001**
Returns no response.

**sudo ufw status**
_Status: active

To                         Action      From
--                         ------      ----
Apache Full                ALLOW       Anywhere                  
22/tcp                     ALLOW       Anywhere                  
443/tcp                    ALLOW       Anywhere                  
4001/tcp                   ALLOW       Anywhere                  
5001/tcp                   ALLOW       Anywhere                  
4002/udp                   ALLOW       Anywhere                  
Apache Full (v6)           ALLOW       Anywhere (v6)             
22/tcp (v6)                ALLOW       Anywhere (v6)             
443/tcp (v6)               ALLOW       Anywhere (v6)             
4001/tcp (v6)              ALLOW       Anywhere (v6)             
5001/tcp (v6)              ALLOW       Anywhere (v6)             
4002/udp (v6)              ALLOW       Anywhere (v6)_

**Comment by Stebalien** [comment]
> nc 104.211.48.196 4001

Your peer is firewalled _somewhere_. Unfortunately, this isn't really something we can help debug. Your VPS probably has some external firewall configurable through some web console (it might even let through 80, 443, and 22 by default).

**Comment by rusfearuth** [comment]
Okay, but how to use ipfs in this case? Does not it have some tools for fixing this problem?

I'm asking because it looks strange. Interplanetary fs in this case only interometry fs or flattenary.

**Comment by Stebalien** [comment]
You can enable the experimental AutoRelay service to allow inbound connections through a relay: `ipfs config --json Swarm.EnableAutoRelay true`

**Comment by specious** [comment]
The option is now `ipfs config --json Swarm.AutoRelay.Enabled true`.

**Comment by wasimsohail** [comment]
I had the same problem and it's solved by allowing port 4001 on the VPS control panel of my VPS provider.
