### ISSUE TITLE
Improve error when invoking IPFS concurrently

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6434]
Currently, we return "resource temporarily unavailable" which is the _underlying_ error returned when we fail to lock the repo. However, that doesn't tell the _user_ what's going on.

We should replace that error with "IPFS currently running", or something like that.

**Comment by utkarsh5k** [comment]
Looking to get involved with this project. I can pick this up.

**Comment by Stebalien** [comment]
Awesome! I believe the correct way to fix this is to modify the `Lock` function in github.com/ipfs/go-fs-lock to inspect the error. Really, this should probably move some of the error handling code from the `Locked` function into the `Lock` function.

**Comment by mahekchheda** [comment]
Is this still up for grabs? I would like to start contributing to this project from this.

**Comment by Stebalien** [comment]
@mahekchheda yes! The code you're looking for is here: https://github.com/ipfs/go-fs-lock/blob/5ab4a142bd9022c9ee4130c9c83fdca06f9acf9c/fslock.go#L23-L71

**Comment by leiter-jakab** [comment]
Hi, I created a pull request for this issue https://github.com/ipfs/go-fs-lock/pull/9. I would be glad to hear your feedback. Unfortunately I didn't manage to link up the commits with this issue, because it's in a different repository.

**Comment by leiter-jakab** [comment]
@Stebalien I think this issue has been solved with https://github.com/ipfs/go-fs-lock/pull/9.
