### ISSUE TITLE
Make ipfs repo fsck a no-op.

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6435]
Both the repo and the leveldb datastore use proper file locking on all platforms users should never need to call `ipfs repo fsck`. Unfortunately, this command can be rather dangerous (https://github.com/ipfs/go-ipfs/issues/6363).

The only semi-useful thing it does is remove the API file. Any objections to at least _gimping_ this command so it only does that? @magik6k?

**Comment by djdv** [comment]
Chiming in to say that removing lock files isn't the first thing I think of when I think of `repo fsck` anyway. Typically I assume this to mean some kind of integrity check, and be (more or less) idempotent by default. (At worst setting some kind of "we know it's corrupt"-like flag.)

If the current default behavior deletes without prompt, and can be labeled "dangerous", that seems like it should change.

**Comment by Stebalien** [comment]
So, I'm actually just going to try to go ahead and fix #5784 so we can completely deprecate this command.
