### ISSUE TITLE
localhost:5001/webui not responding

### ISSUE THREAD

**Issue by oceanzhang01** [ipfs/go-ipfs#6436]
ipfs daemon
Initializing daemon...
go-ipfs version: 0.4.21-
Repo version: 7
System version: amd64/darwin
Golang version: go1.12.5
11:22:59.100 ERROR p2pnode: mdns error: could not determine host IP addresses for DWDdeMacBook-Pro.local. discovery.go:46
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.97.79/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.97.79/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

localhost:5001/webui not responding
![image](https://user-images.githubusercontent.com/17286950/59170997-8deb0380-8b73-11e9-9313-98c477962114.png)
what wrong with it ?

**Comment by eingenito** [comment]
Hey @oceanzhang01 - when you view the webui for the first time IPFS needs to go and fetch the webui application from the IPFS network (all the images/javascript/html etc.) and depending on a lot of factors this can take a little while (it's ~20MB of content). If you wait a bit you should complete the fetch of the webui and subsequently be able to load it quickly as it will be in your local IPFS repository.

**Comment by werty1st** [comment]
I try to setup a private network (https://medium.com/@s_van_laar/deploy-a-private-ipfs-network-on-ubuntu-in-5-steps-5aad95f7261b) and encouter the same problems.
so far I have no solution.
