### ISSUE TITLE
Slow transfer on localhost

### ISSUE THREAD

**Issue by lucasmaheo** [ipfs/go-ipfs#6442]
# go-ipfs version
ipfs version 0.4.21

I have deployed a small private swarm of IPFS nodes in Kubernetes on a local network (also tried local host with minikube), and ```ipfs get``` is really slow. My CPU should be able to handle this small load, and transfer using scp between "nodes" is lightning fast.

# Transfer results
- 162MB file: 46s (average of multiple tries)
- 325MB file: 2m41s (also averaged)

- Initial ```ipfs add``` results in 3~4s of hashing.
- ```ipfs get```-ing on the node that added the file results in 1s "download"

# Troubleshooting and ideas
I have tried using ```--routing=none``` and ```--routing=dhtclient``` to no avail.

The gap in transfer time between the two file sizes may indicate it comes from hashing I suppose (the merkle tree must be deeper), but the CPU is not at full capacity.

Any idea what may cause this?

**Comment by Stebalien** [comment]
This looks like a regression in bitswap. @magik6k has bisected this to 6225024751a80d45b1b0c4a0b8d166bfafcf22a4.

**Comment by lucasmaheo** [comment]
Went back to v0.4.20 for now. This seems to fix the issue, but something may arise on other functionalities I guess.

**Comment by magik6k** [comment]
A likely fix: https://github.com/ipfs/go-peertaskqueue/pull/5

**Comment by Kubuxu** [comment]
Fix in https://github.com/ipfs/go-peertaskqueue/pull/7

**Comment by hinshun** [comment]
Thank you! I was on `v0.4.21` with some disappointing speeds which have now improved by ~5x.
