### ISSUE TITLE
Deploy new versions to npm

### ISSUE THREAD

**Issue by 0x6431346e** [ipfs/go-ipfs#6451]
#### Description:

Hello!

We have several packages that depend on `go-ipfs` and recently people started running into timeouts here:

```
Downloading https://dist.ipfs.io/go-ipfs/v0.4.18/go-ipfs_v0.4.18_linux-amd64.tar.gz
```

1. It is reliable to depend on this download source, or is the plan that you only host the latest versions? Does it make sense to host these ourselves?

2. Could someone please deploy the new versions to npm? The [latest one is `0.4.18`](https://www.npmjs.com/package/go-ipfs) published 7 months ago.

Thanks!

**Comment by Stebalien** [comment]
> It is reliable to depend on this download source, or is the plan that you only host the latest versions? 

We keep all versions (except RCs).

> Could someone please deploy the new versions to npm? The latest one is 0.4.18 published 7 months ago.

Working on it. Thanks for the reminder.

**Comment by Stebalien** [comment]
Status: waiting to get permissions (cc @daviddias).

**Comment by daviddias** [comment]
_go-ipfs has been updated on npm_

Super sorry for this hiccup. We were so happy with the auto publish on https://github.com/ipfs/npm-go-ipfs-dep that it seems we skipped to check https://github.com/ipfs/npm-go-ipfs. 

I've opened an issue to track adding auto publish to it https://github.com/ipfs/npm-go-ipfs/issues/21.
