### ISSUE TITLE
IPFS fails to build

### ISSUE THREAD

**Issue by AdwaitB** [ipfs/go-ipfs#6460]
#### Description:
`make install` fails for both release and master branches.
Running `go version go1.12.6 darwin/amd64` on MacOS Mojave 10.14.5.

`github.com/dgraph-io/badger@v2.0.0-rc.2+incompatible: unknown revision v2.0.0-rc.2` seems to be causing the issue.

[ipfs-release-build-error.txt](https://github.com/ipfs/go-ipfs/files/3314515/ipfs-release-build-error.txt)

**Comment by Kubuxu** [comment]
Fixed by: https://github.com/ipfs/go-ipfs/pull/6461

**Comment by MichaelMure** [comment]
This would fix master, but v0.4.21 would still be broken.

**Comment by Kubuxu** [comment]
Solution for v0.4.21 build:
```bash
GOPROXY='https://proxy.golang.org' make build
```

@MichaelMure can you test it out?

**Comment by MichaelMure** [comment]
@Kubuxu it does work! :tada:
