### ISSUE TITLE
Any documentation for testing local changes (on OSX)?

### ISSUE THREAD

**Issue by utkarsh5k** [ipfs/go-ipfs#6471]
I am a newbie to IPFS and Go, and right now I am just setting up my dev box. After building from source, its not quite clear to me how I can run the locally built version, so that I can make changes in the code base and see how it works. Is there a documentation for the same?

**Comment by Stebalien** [comment]
The "build from source" section of the README _should_ get you started. Have you setup your PATH correctly?

**Comment by utkarsh5k** [comment]
I followed the build from source section. Then I went to the commands folder and tried to run [install.sh](https://github.com/ipfs/go-ipfs/blob/master/cmd/ipfs/dist/install.sh), but the code 

```
INSTALL_DIR=$(dirname $0)
```
resolves to '.', and therefore the script fails because it cannot find a folder ```./ipfs```. 

Am I doing the right thing by running install.sh, or do I have to set paths manually?

**Comment by Stebalien** [comment]
Sorry for the delay, this fell to the bottom of my inbox.

The `install.sh` script is meant to be shipped with pre-compiled IPFS bundles, not used to install IPFS from source. You should install `cmd/ipfs/ipfs` manually _or_ run `make install` in the project root.
