### ISSUE TITLE
how to customize file name by /api/v0/get

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#6477]
/api/v0/get

I try to get downloaded file as xxx.zip,

add &output=xxx.zip does not work. the file name is always "get"
http://localhost:5001/api/v0/get?arg=QmVjMzmryeWLfmxHo3GEY8iiCK6A69ertoiSZShoTqqTCF&output=xxx.zip&archive=false

also those does not work.
&compress=false
&archive=false

how to download a file as " .zip" ?
how to download a file not zipped?

**Comment by Stebalien** [comment]
We'd be happy to answer on the discussion forums, https://discuss.ipfs.io.
