### ISSUE TITLE
Mars bootstrap server doesn't begin with "QmSoLMa"

### ISSUE THREAD

**Issue by lgarron** [ipfs/go-ipfs#649]
It's cute that the other 8 servers match planet initials, but it would be *really* cool if all of them matched this before it's too late.

**Comment by whyrusleeping** [comment]
Yeah, mars was the first so we figured 'Qma' was cool enough. But if @briantigerchow wants to generate a key for me, ill set that up

**Comment by diasdavid** [comment]
We've been deploying new bootstrap servers and although that would be definitely really cool, it would require to wire everything up and deploy a new config bootstrap list. Closing this for now, cc'ing @lgierth for his consideration when spawning a new node :)

**Comment by lgierth** [comment]
Imho this is a wontfix -- QmSoL peerids were mined to make runtime inspection easier. Given that mining time is in the order of days, this is not a practical way for the future. We should rather build `/dns` support into multiaddr, and improve inspection tooling.
