### ISSUE TITLE
Subdomain Gateway

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#6498]
> This is a prerequisite for https://github.com/ipfs/go-ipfs/issues/5982,
> but also a very needed standalone feature.

## Context

[Base32-encoded CIDv1](https://github.com/ipfs/ipfs/issues/337) can be used in DNS as a  subdomain label:

```
https://<cidv1b32>.ipfs.example.com
https://<cidv1b32>.ipns.example.com
```

It provides unique Origin per CID and enables websites to get a valid origin-based security perimeter for free. 

Examples of "Subdomain Gateways" in production:
  - https://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq.ipfs.dweb.link/wiki/
  - https://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq.ipfs.cf-ipfs.com/wiki/ (Cloudflare)

## How it works today? What is missing?

Right now HTTP Gateway exposed by go-ipfs does not support HTTP requests for hostnames that match `<cidv1b32>.ipfs.*` – all existing subdomain gateways implement CID conversion and path redirect in Nginx ([config example](https://github.com/ipfs/infra/issues/81#issuecomment-461045160)) or other reverse proxy running in front of go-ipfs.

## Support requests with `Host: <cidv1b32>.ipfs.*`

go-ipfs already supports [DNSLink](http://dnslink.dev/). We need it to also support HTTP requests for hostnames that match `<cidv1b32>.ipfs.*`. It would enable people to run subdomain gateways without the need for running reverse proxy.

Assuming go-ipfs is running a gateway on `localhost:8080`, below should work:

```
$ curl -v 'http://bafkreigh2akiscaildcqabsyg3dfr6chu3fgpregiymsck7e7aqa4s52zy.ipfs.localhost:8080/wiki/'
> GET /wiki/ HTTP/1.1
> Host: bafkreigh2akiscaildcqabsyg3dfr6chu3fgpregiymsck7e7aqa4s52zy.ipfs.localhost:8080
```

## Related
- Migration to CIDv1 (default base32): https://github.com/ipfs/ipfs/issues/337
- CID as a Subdomain: https://github.com/ipfs/in-web-browsers/issues/89
- HTTP PROXY for `http://<cidv1b32>.ipfs.localhost`: https://github.com/ipfs/go-ipfs/issues/5982
- Gateway index pages link to wrong places when using CID-as-subdomain: https://github.com/ipfs/go-ipfs/issues/5309
- Setup hash subdomain proxying: https://github.com/ipfs/infra/issues/81
- Hostname for localhost gateway: https://github.com/ipfs/in-web-browsers/issues/109

**Comment by lidel** [comment]
(dumping notes from 1:1 with @Stebalien, will reformat later)

    - we dont want both subdomain and path gw on the same hostname
        - it breaks Origin isolation introduced by custom hostname
    - how to handle it?
        - separate port?
            - creates separate Origins, but  
        - redirect?
            - what about localhost? 
              perhaps we should redirect `localhost` with paths to `127.0.0.1` and call it a day? (that will put path-based gateway on different Origin)

**Comment by Stebalien** [comment]
First step: https://github.com/libp2p/go-libp2p-core/pull/41
