### ISSUE TITLE
Memory leak over time 0.4.21

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#6508]
After 1 week runing ipfs with desktop 

Ram is very high 

Cause Mouse move slow, mouse click freeze, screen freezing 

Kill ipfs, then mouse click back normal.

**Comment by hoogw** [comment]
Ipfs also cause lock of hard drive.
Writing to drive speed low as 0.5mb/sec

Kill ipfs,

Writing to drive speed back to 60mb/sec

**Comment by Stebalien** [comment]
What's the output of `ipfs version --all`?

**Comment by Jorropo** [comment]
My node runned without a stop for a bit more than 7 days normaly (I rebooted it to change repo size) on 0.4.21.

**Comment by Stebalien** [comment]
@Jorropo are you confirming the bug?

**Comment by Jorropo** [comment]
@Stebalien no, I have some problem about some cpu consumption spike each second (that start to appear after 2 days) but ram doesn't change significantly (it randomly change around 10% up and down depending of bitswap, gateway, peer count).
```
go-ipfs version: 0.4.21-8ca278f45-dirty
Repo version: 7
System version: amd64/linux
Golang version: go1.12.5
```

**Comment by Stebalien** [comment]
Got it, thanks! We have some datastructures that never forget peers but there really isn't enough here to determine the extent of the issue.

@hoogw could you post some more details? How much memory, what os, etc. Note: Running out of memory will cause a system to freeze so that's not surprising (assuming that's the issue).

**Comment by christroutner** [comment]
Sorry for lack of specifics, but I'm seeing the same memory leak. I've got long-running nodes on a Digital Ocean droplet and I'm seeing a very clear pattern of memory increase with time.

**Comment by Stebalien** [comment]
@christroutner could you run the [collect-profiles.sh](https://github.com/ipfs/go-ipfs/blob/master/bin/collect-profiles.sh) script and post the results?

**Comment by christroutner** [comment]
@Stebalien, sure! How should I run this? Is it a one-time execution? Should I run it with `nohup` as a background process that collects data over time?

**Comment by Stebalien** [comment]
One time thing. Wait for memory to build up and then run it and post the resulting zip. While you do so, please _also_ report the memory usage as reported by our OS (go and the os often disagree).

**Comment by bclermont** [comment]
I confirm this problem

I deploy IPFS servers using this [this helm chart from official helm/charts repo](https://github.com/helm/charts/tree/master/stable/ipfs) and memory usage increase until k8s restart the pod and it can reach  up to 2 Gb RSS.

CPU usage is a bit low

I just upgraded 0.4.22 to see how it goes

**Comment by Stebalien** [comment]
You're unlikely to see a reduction in memory usage in 0.4.22. If you can reproduce this issue, please open a new issue with the archive produced by https://github.com/ipfs/go-ipfs/blob/master/bin/collect-profiles.sh. That'll give us a more accurate picture of what's actually taking memory.
