### ISSUE TITLE
Pin ls stops traversing recursive pins after hitting a direct pin

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6527]
We should avoid re-emitting these directly pinned blocks but we still need to continue traversing the tree. This needs a _test_ to be considered fixed.

Regression from #6493.

**Comment by lanzafame** [comment]
@Stebalien Does this also mean that this case isn't covered by the current test set? I am guessing this was caught via manual testing as the tests passed in #6493.

**Comment by Stebalien** [comment]
It is not covered by the current test set. I haven't actually reproduced this issue, I just happened to re-read the code...

**Comment by lanzafame** [comment]
Can we add to this issue that the fix includes a test to cover this case?

**Comment by lanzafame** [comment]
Just in case someone else picks up the fix.
