### ISSUE TITLE
Configurable DNS Servers

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#6532]
## Context

Right now go-ipfs uses DNS provided by the operating system.

It brings serious downsides:
- DNS-based surveillance and censorship at ISP level ([context](https://www.zdnet.com/article/mozilla-no-plans-to-enable-dns-over-https-by-default-in-the-uk/))
- Browsing DNSLink websites in coffee shops is risky: We are unable to tell if the DNS query was resolved over unencrypted connection. Most of the DNS servers provided by public WiFis are plaintext. This means someone could do MITM on and inject malicious response, changing DNSLink etc. (#6530)
- Leaking plaintext queries in privacy-sensitive contexts (https://github.com/ipfs/go-ipfs/issues/5945, https://github.com/ipfs-shipyard/ipfs-companion/issues/900)

## Hardening DNS in go-ipfs

There are multiple steps to improve the situation, the basic ones would be:

- Stop using DNS provided by OS. We are unable to guarantee it uses TLS, it should never be used by go-ipfs.
- Pick a safe DNS over TLS (or HTTPS) provider and make it implicit default.
  (see https://wiki.mozilla.org/Trusted_Recursive_Resolver for prior art)
- Make it possible for users to override default DNS resolver via `DNS.*` config
  - Ideally, we should support plaintext DNS (only on localhost), DNS over TLS and DNS over HTTPS.
     - If we want to minimize the scope: focus on DNS over HTTPS (DoH). It works in browser, and we want to use it in js-ipfs  (https://github.com/ipfs/js-ipfs/issues/2212) as replacement for calling `https://ipfs.io/api/v0/dns` all the time. 
     - There should be a way to configure custom resolver per TLD or domain

## Ongoing work

- [x] https://github.com/protocol/web3-dev-team/pull/42: Proposal: configurable DNS resolvers for human-readable names
  - :point_right: **this document is an updated problem statement and definition of the end user UX we aim for** 
- [ ] go-ipfs https://github.com/ipfs/go-ipfs/pull/8068: support custom DoH resolvers, depends on:
  - [x] https://github.com/multiformats/go-multiaddr-dns/pull/26: refactor: Resolver to support custom per-TLD resolvers
  - [x] https://github.com/libp2p/go-doh-resolver/pull/1/: create DoH resolver
  - [x] https://github.com/ipfs/go-namesys/pull/10: make DNS resolver pluggable, use new madns.BasicResolver interface 
  - [x] https://github.com/libp2p/go-libp2p/pull/1073:  option for custom dns resolver 
  - [x] <del>https://github.com/ipfs/interface-go-ipfs-core/pull/69</del>
  - [x] https://github.com/ipfs/go-ipfs-config/pull/126: add custom DNS Resolver configuration
  - [ ] https://github.com/libp2p/go-libp2p/issues/1079: go-libp2p release

**Comment by Snawoot** [comment]
I guess IPFS Companion _really_ needs it due to ipfs-shipyard/ipfs-companion#900
