### ISSUE TITLE
`ipfs daemon` says "could not determine host IP address"

### ISSUE THREAD

**Issue by souvikhaldar** [ipfs/go-ipfs#6540]
#### Version information:
 `ipfs version --all`

go-ipfs version: 0.4.21-
Repo version: 7
System version: amd64/darwin
Golang version: go1.12.5

#### Description:

  * What you were doing when you experienced the bug.
I ran `ipfs daemon` then it gave the following error:  
![image](https://user-images.githubusercontent.com/20991754/61961050-5f6e9e00-afe4-11e9-9c38-5d8d7807edfa.png)

  * Any error messages you saw, *where* you saw them, and what you believe may have caused them (if you have any ideas).
  * When possible, steps to reliably produce the bug.  
 run ` ipfs daemon` on mac.
I used this link to download then executed `install.sh` --> https://dist.ipfs.io/#go-ipfs

**Comment by Stebalien** [comment]
Thanks for the report! This is a known issue in 0.4.21 that affects MDNS (local peer discovery). It has been fixed in 0.4.22-rc1. You can follow the release process here #6506.
