### ISSUE TITLE
Write access using fuse or docker-volume-ipfs

### ISSUE THREAD

**Issue by SweeXordious** [ipfs/go-ipfs#6542]
Hello,

I started experimenting with IPFS and i was wondering if there is a way to add content to it without having to go by `ipfs add` and `ipfs name publish`?
I used `--mount` with fuse but i cant seem to be able to write directly into `/ipfs` or `/ipns`.
I also tried [docker-ipfs-volume](https://github.com/vdemeester/docker-volume-ipfs)  but i also cant seem to write on the directories of IPFS.

Is it that iam missing something or its not possible yet to interact with directories `mkdir /ipfs/folder` and have IPFS do the work on the background?

**Comment by Stebalien** [comment]
> This bug tracker is only for actionable bug reports and feature requests. Please direct any questions to https://discuss.ipfs.io or to our Matrix (#ipfs:matrix.org) or IRC (#ipfs on freenode) channels.

> If you don't get an immediate response, please keep trying.

**Comment by pirate** [comment]
What's wrong with this issue? This seems like a perfectly reasonable/actionable feature request @Stebalien.

**Comment by Stebalien** [comment]
This is a question/help request as labeled by the submitter.
