### ISSUE TITLE
pin slowly between two servers

### ISSUE THREAD

**Issue by godcong** [ipfs/go-ipfs#6546]
`ServerA` and `ServerB` and `ServerC` is two computer names.

(1).  pin speed slowly in local network:
a `data` file only added from `ServerA`
when i used `ipfs pin add [data_hash]` from `ServerA` to `ServerB` , `ipfs swarm connect [ServerA_id]` to connect `ServerA` at `ServerB`.
the local network can transfer a file at speed 100M/s.
but the ipfs pin speed is only `RateIn: 1 M/s`, i used `ipfs stats bw` to see it.

(2). ipfs drop data server on pinning:
`ServerC` and `ServerA` are in the different countries.
when i used `ipfs pin add [data_hash]` from `ServerA` to `ServerC` , `ipfs swarm connect [ServerA_id]` to connect `ServerA` at `ServerC`.
`ServerC` alway droped `ServerA` before it pinned.
so it alway run at speed `RateIn: 0 B/s`,
because no one has the `data` file.

when a server is pinning a file.
it need to save a `list`,who has the file.
1),when a server can't find the file from any one. 
it neet to get the file from `list`.
2),when a server can fild the file from other server.
it neet to add the server info into `list` for get.

I don't know, what is it doing this now.
so it's only my idea for pin.

ps: I added 300G+ data in every server.

**Comment by obo20** [comment]
Upgrading to the new 0.4.22-rc1 branch might help with this. There was a nasty bitswap bug that was fixed in 0.4.22 that hampered speeds in the exact manner you're describing.

**Comment by godcong** [comment]
> Upgrading to the new 0.4.22-rc1 branch might help with this. There was a nasty bitswap bug that was fixed in 0.4.22 that hampered speeds in the exact manner you're describing.

yeah, thanks.
i will test in this new version

**Comment by Stebalien** [comment]
> 100M/s

Note: A 100 megabit link is 12.5 megabytes per second.

But yeah, as @obo20 says, this will be _really_ slow on 0.4.21.

**Comment by godcong** [comment]
i updated to 0.4.22.
the `pin` speed looks fine know.
