### ISSUE TITLE
dht & bitswap error

### ISSUE THREAD

**Issue by aeharvlee** [ipfs/go-ipfs#6547]
#### Description:
Whenever I run ipfs daemon as HTTP gateway in the Linode cloud service(let me call this machine as "linode-ipfs"), and visit "linode-ipfs" from other computer using Chrome browser,
error occurs.
`06:38:12.375 ERROR    bitswap: couldnt open sender again after SendMsg(<peer.ID Y5fmmP>) failed: dial attempt failed: <peer.ID P9XXLf> --> <peer.ID Y5fmmP> dial attempt failed: dial tcp4 222.88.238.138:1024: getsockopt: connection refused wantmanager.go:233`

`06:39:49.212 ERROR        dht: checking dht client type: dial attempt failed: failed to dial 
<peer.ID PadbDi> (default failure) notif.go:43`

`06:41:51.643 ERROR        dht: checking dht client type: write tcp 172.104.127.99:4001->83.23.250.112:21805: write: connection reset by peer notif.go:43`

Just 3 messages I worte above appears repeatedly until I stopped connecting from Chrome Browser. 
If I stop visiting, then new meesages appear.
`06:49:54.245 ERROR core/serve: ipfs resolve -r /ipfs/QmP9XXLfEpwK2dhoCnTSmKPrKJibjq3WCyejbA4NSPHZ6Y: Failed to get block for QmP9XXLfEpwK2dhoCnTSmKPrKJibjq3WCyejbA4NSPHZ6Y: context canceled gateway_handler.go:548`

Here's my ipfs conf file and nginx conf file contents.
1. cat ~/.ipfs/config
{
  "Identity": {
    "PeerID": "QmP9XXLfEpwK2dhoCnTSmKPrKJibjq3WCyejbA4NSPHZ6Y",
    "PrivKey": "CAASpwkwggSjAgEAAoIBAQCcpEgUPKdkrA/Pr6HUmlVslqv0N7QFGBYnOm0p+ptEODXVsK5v+907m7QLoMsHHcgBbxRn4bj/SDy7Kuxc3O1/fvRjMYDuz+JllMwKcseN8GSGBnrw0I8Slj/HR0abYUqymuFVx8rycvaPXUObjAvYRxZTJcqtq7ALvmYlZFeOhCU6rvrQIeihyViLSCTo92Mxkj4IO8G9VgLxN8aKoUJbjV6YSEYOeV36f0Iar0fU8rGFzW+3+zPwOhRJZEGB9RgFKg05XQTN30GPi23h/u6Npgz5UVERTnIUb1NnmX0LMZkJn/Qt5CrV2Fq7rDOidwEEGJuXy1TWGGse3uSP5MIBAgMBAAECggEANWU6vMtANG0CpsUz4QkK/Y0O6JzkXKgtRQoBlEG9E7AlicZEcB/m9h7JbP1OuApK11JKHm8vZLX3HcYv9CfLPZ7FJ9sEHGP4xK/ILfeaVqQPYDBtUBGH88oLy55cTzMHB4MMNPV6FNNjgNNF7Iv8rajtz0IeqLzRse8hWrWtswKILdmPaNa4qDXFchthd5LjATkWk0H4fZQCkcCWjohKipk/2MlGl7ilvqT9THEyfsf5GzTz4ionQQTblbKcZymPglJuQPvf4GmWxXGORqf1hYkqALRewDKhE7So/SQAOwMd9ARmPpK2A5+DX7XTC29u3Bnx/TYjgkCj2BQjJAVmEQKBgQDNNolLFcSUukmD73KMT7hISkP97+Z+Qs0ovUhS/u0GnGESLRt3VQ2XDpCNk92m9aP5S+RXr3wJC38uoouHRkcVYiIrNG0AqRNJYc3tpqtYp7skr7soVrQ3G55dPYqR9ZdsH7fVY0poRp4R/KjWkqWU++2MsPdPJDLMFylFy7MpNwKBgQDDaHbw7TgjAiYQA9RFjch+vEN7IRTpRsdfVt9zX1jSbQkRT7Ss+g9aS78UxJ/cjWoKMTlF+NfM2GYLtoslp6Y7tJBsxlh4D/hNoUquqYn9+hnZjWXx2v5S6v/YTcEGgZoSnPcVROIJzzLeu+HqrxLOIOk2VMo0cbkuWrh4lREqhwKBgQCFVcgDB1PBJwEZPn14+VtNbSOcXUGwDAttSv8xHf4362eO/cv4z0STP51gwBCmqLgwBMWKy7SV0+iBDpAGBv2swSReWiPw5+pmJaw9m6t9YQ5RmfTLEvrpS4KsJo5go+gNEtbJSUhRVIDkQvwY3xPDJ6WDYoBt5aEzxmDEvsPcJQKBgF1NN915puAwWnQzH9vGAwFgaugTt6Rawz9mf3LbB9IRdc7qO96L12DJ4gbMi3gHnaYYMrySQJfyi2b0ViQ4lErVwE/vtLY/CdQnOz2Cffziug0CUrbUVbLJujdRiOTOZP6WK/Pf2/3LDQMEuq4Pwe7iD/h9K782vbDAaGxK4NNpAoGARpWu/tKi79PC86TgaEsNMT+e3vDEifz/ZFwHifuMlKWn7tyfOWZSc0loBgD/pAc//iTHEd6CZH35v3HEpw+2gubzErKarZ24Q4FyqKAwZUpDxjUGbobFnRoLP0Rta4JjPZOGPmOhdAaF90Xc3VgJf44cJgWEalgoVd5vMkB2HfA="
  },
  "Datastore": {
    "Type": "leveldb",
    "Path": "/root/.ipfs/datastore",
    "StorageMax": "10GB",
    "StorageGCWatermark": 90,
    "GCPeriod": "1h",
    "Params": null,
    "NoSync": false,
    "HashOnRead": false,
    "BloomFilterSize": 0
  },
  "Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ],
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Gateway": "/ip4/0.0.0.0/tcp/8080"
  },
  "Mounts": {
    "IPFS": "/ipfs",
    "IPNS": "/ipns",
    "FuseAllowOther": false
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Ipns": {
    "RepublishPeriod": "",
    "RecordLifetime": "",
    "ResolveCacheSize": 128
  },
  "Bootstrap": [
    "/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z",
    "/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
    "/ip4/162.243.248.213/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm",
    "/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
    "/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
    "/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
    "/ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3",
    "/ip4/104.236.151.122/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx",
    "/ip6/2604:a880:1:20::1f9:9001/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z",
    "/ip6/2604:a880:1:20::203:d001/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
    "/ip6/2604:a880:0:1010::23:d001/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm",
    "/ip6/2400:6180:0:d0::151:6001/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
    "/ip6/2604:a880:800:10::4a:5001/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
    "/ip6/2a03:b0c0:0:1010::23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
    "/ip6/2a03:b0c0:1:d0::e7:1/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3",
    "/ip6/2604:a880:1:20::1d9:6001/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx"
  ],
  "Tour": {
    "Last": ""
  },
  "Gateway": {
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
				"Access-Control-Expose-Headers",
				"Range"
      ],
			"Access-Control-Expose-Headers": [
				"Location",
				"Ipfs-Hash"
			],
      "Access-Control-Allow-Methods": [
				"POST",
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ],
			"X-Special-Header": [
				"Access-Control-Expose-Headers: Ipfs-Hash"
			]
    },
    "RootRedirect": "",
    "Writable": true,
    "PathPrefixes": []
  },
  "SupernodeRouting": {
    "Servers": null
  },
  "API": {
    "HTTPHeaders": null
  },
  "Swarm": {
    "AddrFilters": null,
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false
  },
  "Reprovider": {
    "Interval": "12h"
  },
  "Experimental": {
    "FilestoreEnabled": false,
    "ShardingEnabled": false
  }
}

2. cat /etc/nginx/conf.d/default.conf
server {
	listen 80;
	listen [::]:80;

	server_name <ip address of linode-ipfs>;

	# IPFS proxypass
	location /ipfs {
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Server $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_pass http://127.0.0.1:8080$uri;
	}
}

3. I tried this in Google Chrome
`<ip address of linode-ipfs>:8080/ipfs/<CID of something stored in linode-ipfs>`

Can i get any help please? Thanks.

**Comment by Stebalien** [comment]
1. Please update to the latest go-ipfs, 0.4.21. 0.4.9 is _terribly_ out of date.
2. Please re-generate your peer's ID. You posted your private key in the issue description.

If you continue to experience this issue on 0.4.21, please file a new issue.
