### ISSUE TITLE
Cannot connect to any node

### ISSUE THREAD

**Issue by ridenaio** [ipfs/go-ipfs#6548]
#### Version information:

go-ipfs version: 0.4.21
Repo version: 7
System version: amd64/windows
Golang version: go1.12.5

#### Description:

We use go-ipfs as a library (0.4.22-rc1) and faced with connectivity problem. We found out, that on **some machines** ipfs permanently cannot connect to any node. This issue can be solved in two ways:

1) Change ipfs port to some high number (e.g. 54321), instead of 4001. (if you change to 4002, it does not help)
2) With VPN it always works (even on 4001 port)

Moreover, we found out, that this issue can be reproduced on public ipfs network, with distributive, downloaded from github (0.4.21 release)

We checked this problem on amd64/windows, amd64/linux (centos 7), mac (Sierra 10.12.6)

```
13:41:43.789 DEBUG  bootstrap: failed to bootstrap with QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: failed to dial QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: no good addresses bootstrap.go:182

13:41:43.892 DEBUG reuseport-: failed to reuse port, dialing with a random port: dial tcp6 [::]:4001->[2400:6180:0:d0::151:6001]:4001: connectex: A socket operation was attempted to an unreachable network. reuseport.go:60

13:41:48.955 DEBUG  bootstrap: failed to bootstrap with QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu: failed to dial : all dials failed

13:42:29.294 DEBUG reprovider: Failed to provide key: failed to find any peer in table reprovide.go:105
```

Full ipfs daemon log [ipfs-log.txt](https://github.com/ipfs/go-ipfs/files/3445963/ipfs-log.txt)

**Comment by Stebalien** [comment]
> 13:41:43.892 DEBUG reuseport-: failed to reuse port, dialing with a random port: dial tcp6 [::]:4001->[2400:6180:0:d0::151:6001]:4001: connectex: A socket operation was attempted to an unreachable network. reuseport.go:60

_This_ looks like an IPv6 issue.

---

Otherwise, this sounds like it may be some kind of network/firewall/ISP issue given that a VPN suddenly fixes the issue. I'm also seeing:

```
[/ip4/104.236.179.241/tcp/4001] dial tcp4 0.0.0.0:4001->104.236.179.241:4001: i/o timeout bootstrap.go:94
```

Meaning that you've exceeded the 10s timeout for the connection. Your ISP may be blocking or rate-limiting connections from low-numbered ports.

Try setting the `LIBP2P_TCP_REUSEPORT` environment variable to `false`. That will cause IPFS to dial from a high-numbered random port.
