### ISSUE TITLE
corehttp.CommandsOption should be be niladic

### ISSUE THREAD

**Issue by briantigerchow** [ipfs/go-ipfs#656]
Right now, this `ServeOption` requires a `commands.Context`. This context is passed to the command framework's HTTP handler.

**now** :hankey:

```Go
corehttp.ListenAndServe(node, "/ip4/0.0.0.0/tcp/4001", corehttp.CommandsOption(req.Context()))
```

This context only exists when the core is created using `ipfs daemon`. Customers creating their own IPFS programs may want to use this ServeOption. Right now it's necessary for them to create a commands context. This is cumbersome and unnecessary.

**goal** :smile: 

```Go
corehttp.ListenAndServe(node, "/ip4/0.0.0.0/tcp/4001", corehttp.CommandsOption)
```

**problem**: many API commands assume that the running daemon is using an FSRepo. For instance, the following commands assume the `Config` file exists on disk:

```
cmd/ipfs/tour.go:               path := req.Context().ConfigRoot
cmd/ipfs/tour.go:               path := req.Context().ConfigRoot
core/commands/bootstrap.go:             r := fsrepo.At(req.Context().ConfigRoot)
core/commands/bootstrap.go:             r := fsrepo.At(req.Context().ConfigRoot)
core/commands/config.go:                r := fsrepo.At(req.Context().ConfigRoot)
core/commands/config.go:                filename, err := config.Filename(req.Context().ConfigRoot)
core/commands/config.go:                filename, err := config.Filename(req.Context().ConfigRoot)
core/commands/config.go:                r := fsrepo.At(req.Context().ConfigRoot)
core/commands/log.go:           path := fmt.Sprintf("%s/logs/events.log", req.Context().ConfigRoot)
```

**objective**: remove the assumption that the daemon is backed by an `FSRepo`.

**solutions**

a) :black_joker: :bomb: nuke theses commands and go home comedy option :bomb: :black_joker:

* Not a serious proposal, but a good queen's duck.

b) :rainbow: Change `commands.Context.GetConfig` to `GetRepo` and remove `ConfigRoot`. :rainbow: 

* This way, whether or not the daemon is running, items in `core/commands` never make the assumption `ConfigRoot` is where the config should be found.

* Remove the `commands/log` command because it reaches into the FSRepo. If users want to tail the events.log file, they can do so using standard unix tools.

**Comment by jbenet** [comment]
Reninder: the webui also tails logs. This uses the `commands/log`. Though the user can do it, we should discourage the user from poking into the managed FSRepo directory.


Maybe a `corelog`


—
