### ISSUE TITLE
MDNS not working in private network

### ISSUE THREAD

**Issue by kpp** [ipfs/go-ipfs#6571]
On default configs MDNS not working in private network.
However if I set `Swarm.EnableAutoNATService = true` on bootstrap nodes and `Swarm.EnableAutoRelay = true` on clients they can find each other (ipfs swarm peers shows mutable connections on 192.168.1.X). Without an access to bootstrap nodes local peers still cannot find each other through MDNS.

Is it a bug or a feature?

**Comment by Stebalien** [comment]
> This bug tracker is only for actionable bug reports and feature requests. Please direct any questions to https://discuss.ipfs.io or to our Matrix (#ipfs:matrix.org) or IRC (#ipfs on freenode) channels.

If you think this might be a bug, please file one and include the relevant information (e.g., IPFS version).

**Comment by kpp** [comment]
> If you think this might be a bug

I do

> include the relevant information (e.g., IPFS version).

ipfs version 0.4.21
