### ISSUE TITLE
IPFS's publickey and IPFS's privatekey

### ISSUE THREAD

**Issue by froud** [ipfs/go-ipfs#6578]
what should i do if i want to user the ipfs's publickey to encryption the file and decrypt the file by  ipfs's  privatekey?  The most important question is that I can't convert the ipfs's  privatekey that starts with CAA to RSAPrivatekey object.

**Comment by froud** [comment]
> What is IPFS's privatekey format? it starts with CAA(), unlike most keyPair that start with MII
> forexample:
> ![image](https://user-images.githubusercontent.com/23519709/63152960-b1cd3880-c03f-11e9-9972-aa669c3ed869.png)
> ![image](https://user-images.githubusercontent.com/23519709/63152980-bc87cd80-c03f-11e9-82fc-c54cbeadf2f6.png)

**Comment by ivan386** [comment]
@froud Key inside protocol buffer. Decode it from base64. Delete first 5 bytes. Encode in base64.

**Comment by Stebalien** [comment]
@froud please direct questions to the discussion forums at [discuss.ipfs.io](https://discuss.ipfs.io).
