### ISSUE TITLE
Potential patent problem with golang-lru.ARCCache

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/go-ipfs#6590]
#### Version information:

go-ipfs v0.4.22

#### Description:

I'm obviously not a lawyer and not even really versed in those kind of things, but golang-lru state that:

> ARC has been patented by IBM, so do not use it if that is problematic for your program.

https://github.com/hashicorp/golang-lru/blob/master/doc.go#L16-L17

go-ipfs does use ARC, specifically through `go-ipfs-blockstore`. Would that be a problem?

**Comment by Stebalien** [comment]
Simple fix: https://github.com/ipfs/go-ipfs-blockstore/pull/20

**Comment by parkan** [comment]
good find @Stebalien, I was wondering whether this patent was in the OSS pool... 2Q looks nearly indistinguishable in general case performance from ARC based on the [paper](https://dbs.uni-leipzig.de/file/ARC.pdf) so this fix seems reasonable
