### ISSUE TITLE
Issue while addding files in IPFS server having cloudflare enabled

### ISSUE THREAD

**Issue by danishshaikh42** [ipfs/go-ipfs#6591]
HI,

I have a ubuntu server on which i have installed ipfs-api, I am using Nginx for reverse proxy.
my etc/nginx/sites-available/default file looks like this:

```nginx
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  listen [::]:2053 ssl ipv6only=on; # managed by Certbot
  listen 2053 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/my.websit/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/my.websit/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
  server_name cryptoblox.co;
  location / {
    proxy_pass http://localhost:2096;
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}
```

I am using 2096 port in my ipfs config for API.

In my Node js code i am using it like this:

```js
const ipfs = ipfsAPI('my.website', '2096', { protocol: 'https' })
```

To add the file I am using:

```js
ipfs.files.add(testBuffer, function (err, file) {
  if (err) {
      console.log(err);
      res.send(responseGenerator.getResponse(500, "Failed to process your request!!!", []));
  }
  console.log(file)
```

I am getting the below error whuile adding the file:

> Unexpected token < in JSON at position 0 

Please help me solve this issue, i have been trying since many days.

**Comment by Stebalien** [comment]
Nginx is returning an HTML page (`<` comes from trying to parse HTML as JSON). You may be using the wrong port in `ipfsAPI`. Looking at the NGINX config, it looks like you're running IPFS on port 2096 _locally_ but NGINX is exposing it on port 80.

If you need more help solving this, please ask on the forums (https://discuss.ipfs.io).
