### ISSUE TITLE
ipfs slow file transfer

### ISSUE THREAD

**Issue by kpp** [ipfs/go-ipfs#6594]
#### Version information:

go-ipfs version: 0.4.22-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.7

#### ipfs daemon --debug

[ipfslogs.txt](https://github.com/ipfs/go-ipfs/files/3525413/ipfslogs.txt)

#### collect-profiles.sh

[ipfs-profile-customer-2019-08-21T14:51:52+02:00.tar.gz](https://github.com/ipfs/go-ipfs/files/3525416/ipfs-profile-customer-2019-08-21T14.51.52%2B02.00.tar.gz)

#### Description:

I got a private network of two nodes.

case 1:
server->server
ipfs get: 1minute
scp: 40s.

case 2:
server->client
ipfs get: 6m32.138s
scp: 2m32.684s

In both cases there are only **two** peers in the network.

Why so slow?

**Comment by Stebalien** [comment]
We are aware that transfering files directly between two peers on a fast network is slower than directly copying the files and we're working on fixing the underlying components responsible.

I've written up a meta-issue to explain what's going on and track progress on fixes: https://github.com/ipfs/go-ipfs/issues/6599
