### ISSUE TITLE
ipfs refs doesn't work with sharded directories

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#6596]
#### Version information:

0.4.22

#### Description:

`ipfs refs` does not work with HAMT-sharded unixfs directories:

```console
$ ipfs refs -r /ipfs/QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX/wiki/Mars.html
Error: no link named "wiki" under QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX
```

Note: the same path works fine with `ipfs resolve`:

```console
$ ipfs resolve -r /ipfs/QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX/wiki/
/ipfs/QmRNXpMRzsTHdRrKvwmWisgaojGKLPqHxzQfrXdfNkettC

$ ipfs resolve -r /ipfs/QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX/wiki/Mars.html
/ipfs/bafkreig6ltd5dojmrhlsweuiaxt3ag2p5644wwcyjmqt6gajmbrbylke4m
```

**Comment by DaniellMesquita** [comment]
Hasn't been fixed, apparently (at least on ipfs.io gateway).

@Stebalien

> git clone https://ipfs.io/ipfs/QmYrS7cNYXGGh4n38w5vcgBrinF7X3Yii24PCa2FEWVXuZ/
> Cloning into 'QmYrS7cNYXGGh4n38w5vcgBrinF7X3Yii24PCa2FEWVXuZ'...
> remote: ipfs resolve -r /ipfs/QmYrS7cNYXGGh4n38w5vcgBrinF7X3Yii24PCa2FEWVXuZ/info/refs: no link named "refs" under QmbJsMQ5qNb4zwDEQUTFtCp7S1MyZFnrkMMmW6kyg8en62
> fatal: repository 'https://ipfs.io/ipfs/QmYrS7cNYXGGh4n38w5vcgBrinF7X3Yii24PCa2FEWVXuZ/' not found

![Screenshot from 2021-05-03 13-01-33](https://user-images.githubusercontent.com/6765277/116901009-cc7a8300-ac0f-11eb-9f41-987d61e09ab4.png)
![Screenshot from 2021-05-03 13-01-42](https://user-images.githubusercontent.com/6765277/116901026-d1d7cd80-ac0f-11eb-999f-de09f1ffd10c.png)

**Comment by Stebalien** [comment]
This issue is about the `ipfs refs` command. Your issue is due to the fact that there is no "refs" folder inside of the "info" folder. The "refs" folder you're seeing there is in the root directory, the "info" directory only contains an "exclude" file.

**Comment by DaniellMesquita** [comment]
@Stebalien

> Your issue is due to the fact that there is no "refs" folder inside of the "info" folder. 

Then, why it worked locally?

**Comment by woss** [comment]
@DaniellMesquita your issue is that you didn't run the [`git update-server-info`](https://git-scm.com/docs/git-update-server-info) inside the bare repo. Do that and then add the repo to the ipfs. you will be able to clone it now.
