### ISSUE TITLE
Docker built go-ipfs fails to report its commit version

### ISSUE THREAD

**Issue by olizilla** [ipfs/go-ipfs#6622]
Versions of go-ipfs built via our Dockerfile are unable to report their commit version, as initially reported by @gmasgras

To see this in action you can try out the go-ipfs:latest image and ask it for `ipfs version --commit`

```console
$ docker run -d --name ipfs_host -v $ipfs_staging:/export -v $ipfs_data:/data/ipfs -p 4001:4001 -p 127.0.0.1:8080:8080 -p 127.0.0.1:5001:5001 ipfs/go-ipfs:latest

$ docker exec ipfs_host ipfs version --commit
ipfs version 0.4.22-
```

The output of the ipfs verison command should be the same when docker is used to build it. 

We use docker built go-ipfs versions on the gateway and not being able to ask them for their commit will make reporting issues harder.

**Comment by olizilla** [comment]
Some old prior art on this issue https://github.com/ipfs/go-ipfs/pull/2734

**Comment by olizilla** [comment]
Looks like CI tests for this got disabled some time ago in this commit https://github.com/ipfs/go-ipfs/pull/2256/commits/c103efc1a9d3420b1f014a92a4ea7862ac13c57b as part of the move to gx https://github.com/ipfs/go-ipfs/pull/2256

**Comment by gmasgras** [comment]
more context from https://github.com/protocol/bifrost-infra/issues/170#issuecomment-525930434

This is likely because we don't copy .git/objects) in the Docker build context.
see:
https://github.com/ipfs/go-ipfs/blob/master/cmd/ipfs/Rules.mk#L16
https://github.com/ipfs/go-ipfs/blob/master/mk/git.mk#L1
https://github.com/ipfs/go-ipfs/blob/master/.dockerignore#L3)

**Comment by Stebalien** [comment]
Ah. This was broken in c8c0c48e2db2bf5ca683f1305c0d2c69c858d1ea.

**Comment by Stebalien** [comment]
Should be fixed in https://github.com/ipfs/go-ipfs/pull/6626.

**Comment by Stebalien** [comment]
Hm. Apparently, "append" is completely ignored when overridden in the command. I'm switching it to GOTAGS.
