### ISSUE TITLE
Doesn't seem to work on windows

### ISSUE THREAD

**Issue by Ilias48rus** [ipfs/go-ipfs#6623]
The last release Prebuild behaves same as ipfs-update -- https://github.com/ipfs/ipfs-update/issues/63#issuecomment-527970102, on win10_1903 .

**Comment by Stebalien** [comment]
By default, the ipfs command will just print the help text. To run the ipfs daemon, you need to run `ipfs daemon` from a terminal window.

If you want to use ipfs from windows, I recommend installing https://github.com/ipfs-shipyard/ipfs-desktop.
