### ISSUE TITLE
Unusual bug -- can get stuck pegging CPU, freezes os

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#6644]
#### Version information:

```
> ipfs version --all
go-ipfs version: 0.4.22-rc1-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.6
```

I've updated to 0.4.22, will post here again someday if it happens again.

#### Description:

Sometimes, long running ipfs daemons may get stuck pegging CPU. This particular node (this is a stress test node on purpose) is running on a DigitalOcean droplet, 4GB mem, 60 GB disk (90% full). It usually grows connections steadily up to 20K+ peers (i have a high conn mgr count), OOMs (killed by os), then service reboots .

When this problem occurs, the node is stuck pegging the CPU, and the entire os becomes unresponsive (impressively, ssh and mosh both fail to connect, and even accessing web console gets stuck)

This run got stuck for many days:

![image](https://user-images.githubusercontent.com/138401/64915709-3e901280-d722-11e9-8c28-aae7394702bb.png)

I've seen this before in other nodes. Much more often in the past (probably 4.12.x and earlier). Would be great to create a test case that can repro this.

**Comment by Stebalien** [comment]
When this happens, could you take a CPU dump? Or just run this script: https://github.com/ipfs/go-ipfs/blob/master/bin/collect-profiles.sh

@mburns, have you seen something similar (recently) on the gateways/bootstrapper?

---

@jbenet to double check, this is IPFS that's pegging the CPU, not something else on the machine? OOM conditions tend to cause some applications to spin trying to repeatedly allocate (even the kernel does this).

**Comment by benjamin-actyx** [comment]
I’ve encountered similar behaviour, so I’m just gonna add some profiling data here.
In my case, the node should actually not be serving anything – it’s on a swarm with occasionally active pubsub traffic, but no locally available data should really be queried by other nodes, at least not very often.
The CPU usage normally sits at "unnoticable" – under 3%. After leaving the node running overnight, which I don’t normally do, I encountered it taking like 80% today. That’s just 80% of one core, not the whole system, of course, but still way more than it should take.

I’m attaching info collected via https://github.com/ipfs/go-ipfs/blob/master/bin/collect-profiles.sh, as well as 2 stack dumps taken via method from https://poormansprofiler.org/
One of the 2 dumps is especially noteworthy, as it somehow includes a thread with a 133k elements long stack, most of it the same repeating entry:
`0x0000000000b0a47c in context.(*valueCtx).Done (~r0=<optimized out>) at <autogenerated>:1`

[profile.zip](https://github.com/ipfs/go-ipfs/files/4163926/profile.zip)
[stackdumps.zip](https://github.com/ipfs/go-ipfs/files/4163931/stackdumps.zip)

**Comment by Stebalien** [comment]
@dirkmc if you have some downtime between bitswap stuff, could you take a look at this?

**Comment by Stebalien** [comment]
Revisiting

@benjamin-actyx

In your case, you appear to have many incoming calls to the DHT's "add provider". We had several performance issues there and that code has been rewritten to address them.

@jbenet

Additionally, go-ipfs 0.5 and subsequent releases included some major refactors to bitswap, some of which likely could have caused this issue. In particular, we optimized quite a bit of our wantlist handling to improve performance on the preload nodes.

I'm going to close this as there's not enough information to investigate further (and lots of code has changed). We can start a new issue if we see a similar issue in the future.
