### ISSUE TITLE
Ipfs node in mainland China, node connection has a big problem

### ISSUE THREAD

**Issue by IPSE-TEAM** [ipfs/go-ipfs#6649]
We are the IPSE project party. In the past, our ipfs client dumped more than 1000 ipfs nodes distributed in mainland China to bootstrap, which can connect to most nodes, but recently, in this way, the basic connection is not To these seed nodes, the number of nodes connected to them has dropped significantly. Previously, they were able to connect to more than 1,000, and now they are at most 600, and most of them are distributed in North America and Europe. I suspect that after the ipfs node update version, the ability to NAT has dropped, and I hope to optimize this function.

**Comment by hsanjuan** [comment]
Consolidated on https://github.com/ipfs/go-ipfs/issues/6660
