### ISSUE TITLE
`ipfs ping` yourself.

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#665]

**Comment by whyrusleeping** [comment]
do you still want this? if so, what is the reason? We don't allow connections to ourselves because reasons and things (it generally only occurs in a buggy situation).

**Comment by jbenet** [comment]
I wanted to mirror how ping works in oses-- to exercise the network. Ok if
it does not.

**Comment by whyrusleeping** [comment]
okay,  this would be very weird to rig up through the network layer to allow connections to yourself. I'm gonna close this
