### ISSUE TITLE
Error while starting daemon to create a private IPFS network

### ISSUE THREAD

**Issue by danishshaikh42** [ipfs/go-ipfs#6650]
Hi,

While starting the daemon while implementing the private IPFS network, I am getting the below error : 

Initializing daemon...
go-ipfs version: 0.4.22-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.7
07:17:53.948 ERROR   cmd/ipfs: error from node construction:  could not build arguments for function "github.com/ipfs/go-ipfs/core/node".IpnsRepublisher.func1 (pkg/mod/github.com/ipfs/go-ipfs@v0.4.22/core/node/ipns.go:38): failed to build namesys.NameSystem: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Namesys.func1 (pkg/mod/github.com/ipfs/go-ipfs@v0.4.22/core/node/ipns.go:31): failed to build routing.IpfsRouting: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Routing (pkg/mod/github.com/ipfs/go-ipfs@v0.4.22/core/node/libp2p/routing.go:60): could not build value group libp2p.Router[group="routers"]: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".BaseRouting (pkg/mod/github.com/ipfs/go-ipfs@v0.4.22/core/node/libp2p/routing.go:34): failed to build libp2p.BaseIpfsRouting: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (pkg/mod/github.com/ipfs/go-ipfs@v0.4.22/core/node/libp2p/host.go:39): could not build value group []config.Option[group="libp2p"]: function "github.com/ipfs/go-ipfs/core/node/libp2p".PNet (pkg/mod/github.com/ipfs/go-ipfs@v0.4.22/core/node/libp2p/pnet.go:19) returned a non-nil error: failed to configure private network: malformed private network key: encoding/hex: invalid byte: U+0020 ' ' daemon.go:337

Error: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".IpnsRepublisher.func1 (pkg/mod/github.com/ipfs/go-ipfs@v0.4.22/core/node/ipns.go:38): failed to build namesys.NameSystem: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Namesys.func1 (pkg/mod/github.com/ipfs/go-ipfs@v0.4.22/core/node/ipns.go:31): failed to build routing.IpfsRouting: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Routing (pkg/mod/github.com/ipfs/go-ipfs@v0.4.22/core/node/libp2p/routing.go:60): could not build value group libp2p.Router[group="routers"]: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".BaseRouting (pkg/mod/github.com/ipfs/go-ipfs@v0.4.22/core/node/libp2p/routing.go:34): failed to build libp2p.BaseIpfsRouting: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (pkg/mod/github.com/ipfs/go-ipfs@v0.4.22/core/node/libp2p/host.go:39): could not build value group []config.Option[group="libp2p"]: function "github.com/ipfs/go-ipfs/core/node/libp2p".PNet (pkg/mod/github.com/ipfs/go-ipfs@v0.4.22/core/node/libp2p/pnet.go:19) returned a non-nil error: failed to configure private network: malformed private network key: encoding/hex: invalid byte: U+0020 ' '

Kindly help,
Danish

**Comment by Stebalien** [comment]
Wow, that error is downright terrible (https://github.com/ipfs/go-ipfs/issues/6651).

The issue is that you have a space (" ") _somewhere_ in and/or after your private key and IPFS is failing to decode it.

**Comment by danishshaikh42** [comment]
I do not have space in my "PrivKey" object in config file.

**Comment by Stebalien** [comment]
Sorry, I meant in your _swarm_ key (the shared secret for the private network). It could be (probably is) at the end.

**Comment by danishshaikh42** [comment]
my swarm file looks like this

/key/swarm/psk/1.0.0/
/base16/
f“c0dre4559€e€“âd9eaabcc9cde€9ffeeâaââcâdbfbba9c“cd9âe€€a9“câd€0d

Changed some values for secutity purpose, But I don't see any spaces, Kindly help

**Comment by danishshaikh42** [comment]
What should be the correct format for the swarm.key file

**Comment by Stebalien** [comment]
So:
1. You need to drop the space.
2. The medium post is breaking the hyphen. a-f0–9 should be a-f0-9

The correct command would be:

```
> echo -e "/key/swarm/psk/1.0.0/\n/base16/\n$(tr -dc 'a-f0-9' < /dev/urandom | head -c64)"
```

**Comment by danishshaikh42** [comment]
Thanks @Stebalien, It worked. Thanks, just one more thing wanna ask that we are using the below configuration for the private network

  "API": "/ip4/0.0.0.0/tcp/2087",
    "Announce": [],
    "Gateway": "/ip4/0.0.0.0/tcp/2096",

Is defining port for the gateway really required in private environment?

**Comment by Stebalien** [comment]
You can _disable_ the gateway by setting it to the empty string. However, I'm not sure how the gateway relates to using a private network.

**Comment by mmalviya** [comment]
it di not help me , i am still getting the same error.

ERROR   cmd/ipfs: error from node construction:  could not build arguments for function "github.com/ipfs/go-ipfs/core/node".IpnsRepublisher.func1 (pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/core/node/ipns.go:38): failed to build namesys.NameSystem: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Namesys.func1 (pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/core/node/ipns.go:31): failed to build routing.IpfsRouting: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Routing (pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/core/node/libp2p/routing.go:60): could not build value group libp2p.Router[group="routers"]: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".BaseRouting (pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/core/node/libp2p/routing.go:34): failed to build libp2p.BaseIpfsRouting: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/core/node/libp2p/host.go:39): could not build value group []config.Option[group="libp2p"]: function "github.com/ipfs/go-ipfs/core/node/libp2p".PNet (pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/core/node/libp2p/pnet.go:19) returned a non-nil error: failed to configure private network: malformed private network key: psk header error: multicodec did not match daemon.go:337

Error: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".IpnsRepublisher.func1 (pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/core/node/ipns.go:38): failed to build namesys.NameSystem: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Namesys.func1 (pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/core/node/ipns.go:31): failed to build routing.IpfsRouting: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Routing (pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/core/node/libp2p/routing.go:60): could not build value group libp2p.Router[group="routers"]: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".BaseRouting (pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/core/node/libp2p/routing.go:34): failed to build libp2p.BaseIpfsRouting: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/core/node/libp2p/host.go:39): could not build value group []config.Option[group="libp2p"]: function "github.com/ipfs/go-ipfs/core/node/libp2p".PNet (pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/core/node/libp2p/pnet.go:19) returned a non-nil error: failed to configure private network: malformed private network key: psk header error: multicodec did not match

**Comment by Stebalien** [comment]
@mmalviya that's a different error. Please file a new issue with the exact commands you ran.

**Comment by gianfeliceM** [comment]
Hi i have the same problem as danishshaikh42 but on windows. Can you help me?

**Comment by Stebalien** [comment]
The solution is here: https://github.com/ipfs/go-ipfs/issues/6650#issuecomment-533756709. If you're still having trouble, please reach out on the forums (https://discuss.ipfs.io)

**Comment by SCUT-FMS** [comment]
我也有同样的问题，构建私有网络时失败，能否帮我解决一下。
Initializing daemon...
go-ipfs version: 0.7.0-ea77213e3
Repo version: 10
System version: amd64/linux
Golang version: go1.14.9
2020-10-21T09:36:22.634+0800	ERROR	cmd/ipfs	error from node construction: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".PeerWith.func1 (/build/ipfs/parts/ipfs/build/core/node/peering.go:29): failed to build *peering.PeeringService: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Peering (/build/ipfs/parts/ipfs/build/core/node/peering.go:14): failed to build host.Host: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (/build/ipfs/parts/ipfs/build/core/node/libp2p/host.go:40): could not build value group []config.Option[group="libp2p"]: received non-nil error from function "github.com/ipfs/go-ipfs/core/node/libp2p".PNet (/build/ipfs/parts/ipfs/build/core/node/libp2p/pnet.go:21): failed to configure private network: expected file header /key/swarm/psk/1.0.0/, got: key/swarm/psk/1.0.0/

Error: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".PeerWith.func1 (/build/ipfs/parts/ipfs/build/core/node/peering.go:29): failed to build *peering.PeeringService: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Peering (/build/ipfs/parts/ipfs/build/core/node/peering.go:14): failed to build host.Host: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (/build/ipfs/parts/ipfs/build/core/node/libp2p/host.go:40): could not build value group []config.Option[group="libp2p"]: received non-nil error from function "github.com/ipfs/go-ipfs/core/node/libp2p".PNet (/build/ipfs/parts/ipfs/build/core/node/libp2p/pnet.go:21): failed to configure private network: expected file header /key/swarm/psk/1.0.0/, got: key/swarm/psk/1.0.0/

**Comment by Stebalien** [comment]
This issue is closed. Please ask on discuss.ipfs.io.
