### ISSUE TITLE
Connectivity issues in China

### ISSUE THREAD

**Issue by IPSE-TEAM** [ipfs/go-ipfs#6660]
The ip in China is not enough. The ip of our ipfs node is changing, but we update the changed peerid to bootstrap, but it is not good to find the peers I need to connect through the nodes in bootstrap. The main reason may be that the intranet penetrates NAT.

**Comment by hsanjuan** [comment]
Seems related to your other #6649 issue so I'm going to consolidate here.

There are major improvements coming to DHT (ability to find other dialable nodes) and using TLS instead of secio might improve connectivity. Stay tuned for v0.5.0 in the next few weeks.

**Comment by hsanjuan** [comment]
From the other issue:

```
We are the IPSE project party. In the past, our ipfs client dumped more than 1000 ipfs nodes distributed in mainland China to bootstrap, which can connect to most nodes, but recently, in this way, the basic connection is not To these seed nodes, the number of nodes connected to them has dropped significantly. Previously, they were able to connect to more than 1,000, and now they are at most 600, and most of them are distributed in North America and Europe. I suspect that after the ipfs node update version, the ability to NAT has dropped, and I hope to optimize this function.
```

**Comment by hsanjuan** [comment]
Actually, let's consolidate this on https://github.com/ipfs/go-ipfs/issues/5993 which talks about the same. Other than that and waiting for v0.5.0 there are no actionables for this issue.

Thanks!
