### ISSUE TITLE
Offline ipns records are not shared between local nodes

### ISSUE THREAD

**Issue by kpp** [ipfs/go-ipfs#6662]
#### Version information:

```
go-ipfs version: 0.4.22-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.7
```

#### Description:

Run 2 nodes in local private (with swarm.key) network. Both of them find each other and present in `ipfs swarm peers` as `192.168.x.x`. Call `ipfs cat /ipns/hash/path` on node №1 to resolve & cache the content, turn off the internet connection. Trying cat or resolve `/ipns/hash/path` on node №2 with the same hash/path will result in an error (**routing: not found**) even before [1m](https://github.com/ipfs/go-ipfs/issues/6656) is exceeded.
However if I resolve `ipfs resolve /ipns/` and cat an `/ipns/` name on node №1, save this resolved /ipfs hash, turn off the internet connection, calling `ipfs cat /ipfs/resolved_hash` on node №2 will succeed even on a clean repo. This means that blocks are transferred in the local network however there are several issues with ipns name resolving. Right?

**Comment by sintanial** [comment]
Same problem, any news ?

**Comment by Stebalien** [comment]
@sintanial this issue was filed 10 hours before you commented. Please be patient.

---

@kpp the IPNS record is cached in-memory on node 1. This cache is not made available to the DHT.

However, it probably should be: https://github.com/libp2p/notes/issues/16. Unfortunately, fixing this issue is non-trivial.

**Comment by Stebalien** [comment]
Closing in favor of https://github.com/ipfs/notes/issues/391. This is going to take some design and cross-implementation protocol work.
