### ISSUE TITLE
`~/.go-ipfs` has wrong permissions

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#667]
its 755, should be 644

**Comment by whyrusleeping** [comment]
This might actually be leveldb... https://github.com/syndtr/goleveldb/blob/master/leveldb/storage/file_storage.go#L64

**Comment by travisperson** [comment]
My config is actually set to 0775. Curious if you mean that or is your 755? Might be another issue in here as well.
https://github.com/jbenet/go-ipfs/blob/master/repo/fsrepo/serialize/serialize.go#L32

**Comment by dylanPowers** [comment]
I'd argue that for others it should be set to 0. Especially the config file

**Comment by whyrusleeping** [comment]
@dylanPowers were actually going to move the private key out of the config rather soon. But I do agree that the key should have 600 perms

**Comment by mb0** [comment]
the .go-ipfs folder needs executable bit set so the owner can list the directory contents.
not setting the executable bit for directories does make other permissions not that useful.

right now the config file is set to 0660. so it makes sense to set the directory to either 0775 as it already is (or to 0770 if the logs or the datastore directories should in fact not be readable).

**Comment by jbenet** [comment]
@mb0 thoughts on `0660` vs `0600` for config?

fwiw, i observe this for `.gitconfig`

```
linux> ls -l ~/.gitconfig
-rw-rw-r-- 1 jbenet jbenet 1660 Nov  6 12:10 /home/jbenet/.gitconfig

darwin> ls -l ~/.gitconfig
-rw-r--r-- 1 jbenet staff 1976 Dec 14 21:07 /Users/jbenet/.gitconfig
```
but that may be my doing.

**Comment by whyrusleeping** [comment]
`0755` is just fine.
