### ISSUE TITLE
Ipfs get hanging

### ISSUE THREAD

**Issue by gasparyanyur** [ipfs/go-ipfs#6679]
Hi all. I have a problem with getting a new published files using `ipns`
When I run the following command

`ipfs get --output /home/abc/data /ipns/QmHASH`

I do not receive any files, errors or information. The `ipfs get` hanging.
Also there is no problem with `NAT` because I have tested with some ways with disabling nodes by rotation.

Can anybody help to solve this problem ?

**Comment by naman1303** [comment]
Hope you are using \<peerID\> (or the hash which comes as a result of publish) and not the hash of file itself in the below command. 

> ipfs get --output /home/abc/data /ipns/**_QmHASH_**

Please refer to this [link](https://medium.com/coinmonks/how-to-add-site-to-ipfs-and-ipns-f121b4cfc8ee). It explains and executes the steps in a simple and easy manner.
