### ISSUE TITLE
Getting 404 page not found error while accessing the data

### ISSUE THREAD

**Issue by danishshaikh42** [ipfs/go-ipfs#6682]
Hello,

I have ipfs installed on my machine, here is how my config file looks like:

 "Addresses": {
    "API": "/ip4/0.0.0.0/tcp/2087",
    "Announce": [],
    "Gateway": "/ip4/0.0.0.0/tcp/2083",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ]
  }

I am able to upload the file on the IPFS and able to see the hash generated on my server using ipfs pin ls command, However, while accessing the data using the same hash from my server, I am getting the below error

404 page not found

Earlier it was working fine, Kindly help me with the issue.

Thanks,
Danish

**Comment by hsanjuan** [comment]
How are you accessing the data from your server? 404 indicates you are calling an nonexistent endpoint...

**Comment by danishshaikh42** [comment]
I am accessing it using mydomain.com/ipfs/hash. The endpoint exists, because while running the daemon using node js code with the same configuration, I am able to access the files.

The problem occurs while running the daemon using ipfs daemon command, The hash is seen with the ipfs pin ls command but unable to access in the browser.

**Comment by godcong** [comment]
do you open the used port from iptables on you server.

**Comment by danishshaikh42** [comment]
Yes the ports are open, I think it is looking for the file where it is not present. i am accessing it at : mydomain/ipfs/hashOfTheFile

**Comment by godcong** [comment]
i think you need check 2 ways.
1. Confirm that the address you are visiting is the gateway address:
"Gateway": "/ip4/0.0.0.0/tcp/2083"
2. Confirm the Gateway settings `Access-Control-Allow-Methods` is allow visiting
 "Gateway": {
    "HTTPHeaders": {
      "Access-Control-Allow-Methods": [
        "GET","POST","*"
      ],
    },

If it is still not correct,...

**Comment by agowa338** [comment]
I also run into this issue and it looks like a regression.
I've
```
    "API": "/ip6/::1/tcp/5001",
    "Gateway": "/ip6/::1/tcp/8080"
```
in my configuration file and that results in the same error.

But if I change the API to the default of `/ip4/127.0.0.1/tcp/5001` it starts working again.
Using developer tools in the browser reveals what is going wrong in the first case:
![image](https://user-images.githubusercontent.com/2544867/71648704-f6642280-2d07-11ea-88aa-497cc18b7ada.png)

This can also be reproduced by using anything except the default like `/ip4/127.174.134.32/tcp/5001`.

**Comment by Stebalien** [comment]
@agowa338 can you open a new bug? The original issue is an issue with the Gateway. Your issue looks like a bug in the webui.
