### ISSUE TITLE
Unable to add a file using the http api

### ISSUE THREAD

**Issue by xwvvvvwx** [ipfs/go-ipfs#6698]
#### Version information:

go-ipfs version: 0.4.21-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.6

#### Description:

I have an IPFS node running on a remote server (at `10.10.0.1`), but I am unable to add a file using the http api:

- If I run `curl -F "file=@<FILE>" 10.10.0.1:5001/api/v0/add` it hangs forever.
- If I run `curl 10.10.0.1:5001/api/v0/swarm/peers`, I get a json list with all my peers back, so I think my connection to the remote server is OK.
- If I ssh onto the server and run `ipfs add <FILE>` directly everything works, so I think my node is well connected.
- If I run `ipfs log level cmds/http debug && ipfs log tail | grep cmds/http` on the server, I do not see any output in the log when making any request to the http api.

I don't know how to debug this further, am I doing something wrong?

#### Additional Information

output from `curl -v -F "file=@<FILE>" 10.10.0.1:5001/api/v0/add`:

```
*   Trying 10.10.0.1:5001...
* TCP_NODELAY set
* Connected to 10.10.0.1 10.10.0.1 port 5001 (#0)
> POST /api/v0/add HTTP/1.1
> Host: 10.10.0.1:5001
> User-Agent: curl/7.65.3
> Accept: */*
> Content-Length: 4510
> Content-Type: multipart/form-data; boundary=------------------------9bb213b4bebbd3a1
> Expect: 100-continue
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
```

output from `curl --version`:

```
curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1c zlib/1.2.11 libssh2/1.9.0 nghttp2/1.39.2
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

**Comment by Stebalien** [comment]
I can't reproduce. Do you have any kind of proxy server sitting between you and the daemon? While running curl, could you also run `ipfs diag cmds`? That should tell you all "active" commands (and all recently run commands).

**Comment by godcong** [comment]
Look at your config `api`
 "API": "/ip4/127.0.0.1/tcp/5001"
is this?
 "API": "/ip4/0.0.0.0/tcp/5001"
change to this and reset ipfs，then retry `curl xxx`

**Comment by xwvvvvwx** [comment]
> Do you have any kind of proxy server sitting between you and the daemon?

I am connected to the sever over a wirguard tunnel. Reducing the `mtu` on the wireguard interface from 1420 to 1400 fixed this issue for me (`sudo ip link set mtu 1400 dev wg0`).
