### ISSUE TITLE
Out of Memory Crash After ~24 Hours

### ISSUE THREAD

**Issue by peat** [ipfs/go-ipfs#6702]
#### Version information:

go-ipfs version: 0.4.22-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.7

#### Description:

I'm running a small IPFS node, using the out-of-the-box configuration on Ubuntu 19.04. I used the `go get ...` method for installing `ipfs-update` and ran `ipfs-update install latest`

The VM it's running on has 2GB of RAM. It starts fine, and the only thing I use it for is pinning a few small sites I'm hacking on while learning about IPFS (`/ipns/ipfs.golf` if you're curious).

Over time, without any activity on my part (not hitting any of the services, `ipfs get ...`, or anything else), the memory consumption swells and `ipfs daemon` eventually crashes.

Here's what I currently see from various commands:

```
$ ps -p 12805 -o etime
    ELAPSED
   23:16:38
$ sudo pmap 12805 | tail -n 1
 total          1423432K
$ ifps swarm peers | wc -l
860
$ ipfs stats bw
Bandwidth
TotalIn: 922 MB
TotalOut: 1.8 GB
RateIn: 5.4 kB/s
RateOut: 16 kB/s
```

Let me know how I can help; happy to pair with someone or provide shell on the VM for someone to poke at it directly. Thanks!

**Comment by Stebalien** [comment]
First off, could you run the bin/collect-profiles.sh script in this repo and post the results (after IPFS has been running for a while)? That'll help us figure out what's taking all that memory.

After doing that, try running `ipfs config Routing.Type dhtclient` and restarting your daemon. That'll configure your node to be a light client in the DHT and should reduce the amount of peerings/inbound traffic.

**Comment by peat** [comment]
Thanks! Some of the commands in the `bin/collect-profiles.sh` script would crash on OOM errors, but I was able to manually run some of the commands in the `debug-guide.md` to produce these files (heap, sysinfo, cpuprof, stacks, and vars):

[ipfs-profile.zip](https://github.com/ipfs/go-ipfs/files/3703320/ipfs-profile.zip)

I've restarted and set the `Routing.Type` ... I'll keep an eye on it and report back tomorrow.

**Comment by Stebalien** [comment]
Yeah, you have a _lot_ of inbound connections. To double check, are have you enabled `Swarm.EnableRelayHop`? If you have, please turn it off.

Other than that, you can save >50MiB by turning off metrics (`ipfs config --json Swarm.DisableBandwidthMetrics true`). The rest looks like https://github.com/libp2p/go-libp2p-peerstore/issues/93.

**Comment by Stebalien** [comment]
Not really. The real issue is that you shouldn't be receiving that many inbound connections. I assume you're seeing a ton of CPU utilization as well.

**Comment by peat** [comment]
CPU is between 3-6% on a single core ... not bad! My laptop hovers around 25% with ~900 peers.

With the `RoutingType` set to `dhtclient` it's much less memory hungry. It's still leaking somewhere (probably the libp2p issue?), growing from about 25% of the available memory to about 50% over the last 24 hours. It has around 600 - 900 peers at any given time.

**Comment by Stebalien** [comment]
We've optimized DHT requests to not kill the network since this issue was reported. Closing as there's likely no other actionable info here.
