### ISSUE TITLE
Broken Installer 

### ISSUE THREAD

**Issue by NickTheLim** [ipfs/go-ipfs#6704]
go install  "-asmflags=all='-trimpath=/home/user/go'" "-gcflags=all='-trimpath=/home/user/go'" -ldflags="-X "github.com/ipfs/go-ipfs".CurrentCommit=f97ed7da4" ./cmd/ipfs
# runtime/cgo
_cgo_export.c:3:20: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
                    ^
compilation terminated.
cmd/ipfs/Rules.mk:37: recipe for target 'cmd/ipfs-install' failed
make: *** [cmd/ipfs-install] Error 2

**Comment by Stebalien** [comment]
Try building with `make install CGO_ENABLED=0`.

**Comment by NickTheLim** [comment]
Can someone add a list of dependencies to the install page?

Says it only needs go, but it really needs make, cmake, gcc, git, a ton of other stuff....

Supper annoying and restrictive for IPFS adoption.

**Comment by NickTheLim** [comment]
"Try building with make install CGO_ENABLED=0."

Doesn't show an error, but doesn't show anything. Additionally doesn't work.

ipfs
-bash: ipfs: command not found

**Comment by Stebalien** [comment]
> Doesn't show an error, but doesn't show anything. Additionally doesn't work.

As the name implies, `make build` builds, it does not install. You'll have to use `make install` to actually install (or you'll have to manually copy over the binary).

---

In general, end users are expected to install from a pre-built binary. Advanced users who'd like to build from source generally already have make, gcc, git, etc. (a standard compiler toolchain).

However, I've improved the README a bit (https://github.com/ipfs/go-ipfs/pull/6706) to hopefully reduce confusion in the future.
