### ISSUE TITLE
The number of connected peers keeps below 50 

### ISSUE THREAD

**Issue by daviddias** [ipfs/go-ipfs#6710]
#### Version information:

go-ipfs version: 0.4.22-
Repo version: 7
System version: amd64/darwin
Golang version: go1.12.7

#### Description:

With go-ipfs 0.4.22, the number of nodes I connect to is always below 50

@aschmahmann is experiencing the same using this version.

Then I went and tried with 0.4.20, installed with ipfs-update

#### Version information:

go-ipfs version: 0.4.20-
Repo version: 7
System version: amd64/darwin
Golang version: go1.12.4

#### Description:

With go-ipfs 0.4.20, the number of nodes I connect to is always 0

When tried to connect to Bootstrap nodes, I get:

```
» ipfs swarm connect /ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
Error: connect QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ failure: dial attempt failed: 1 error occurred:
        * <peer.ID Qm*xZDh5L> --> <peer.ID Qm*QLuvuJ> (/ip4/104.131.131.82/tcp/4001) dial attempt failed: dial tcp4 0.0.0.0:4010->104.131.131.82:4001: i/o timeout
```

```
» ipfs swarm connect /ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd
Error: connect QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd failure: dial attempt failed: 2 errors occurred:
        * <peer.ID Qm*xZDh5L> --> <peer.ID Qm*VQKNAd> (/ip6/2a03:b0c0:0:1010::23:1001/tcp/4001) dial attempt failed: dial tcp6 [2a03:b0c0:0:1010::23:1001]:4001: connect: no route to host
        * <peer.ID Qm*xZDh5L> --> <peer.ID Qm*VQKNAd> (/ip4/178.62.158.247/tcp/4001) dial attempt failed: dial tcp4 0.0.0.0:4010->178.62.158.247:4001: i/o timeout
```

I can ping both

```
» ping 104.131.131.82
PING 104.131.131.82 (104.131.131.82): 56 data bytes
64 bytes from 104.131.131.82: icmp_seq=0 ttl=51 time=287.927 ms
64 bytes from 104.131.131.82: icmp_seq=1 ttl=51 time=298.889 ms
```

```
» ping 178.62.158.247
PING 178.62.158.247 (178.62.158.247): 56 data bytes
64 bytes from 178.62.158.247: icmp_seq=0 ttl=52 time=36.246 ms
64 bytes from 178.62.158.247: icmp_seq=1 ttl=52 time=37.349 ms
```

I did manage to connect to another node on the network that are not the bootstrappers

```
» ipfs swarm connect /ip4/147.75.195.153/tcp/4001/ipfs/QmW9m57aiBDHAkKj9nmFSEn7ZqrcF1fZS4bipsTCHburei
connect QmW9m57aiBDHAkKj9nmFSEn7ZqrcF1fZS4bipsTCHburei success
```

For both tests, I'm using a reliable Internet connection from a home router that I've used multiple times.

**Comment by olizilla** [comment]
The bootstrappers are not as reliable as I'd like right now. It's on the list of "things I'd like to improve very soon".

50 is surprising. I am running a pretty stock ipfs-desktop provided ipfs node and am connected to about ~1000 peers currently.

**Comment by aschmahmann** [comment]
Brief update. After some messing around on my network I'm able to (pretty slowly and after manually running a number of DHT queries) get a healthy (over my high water limit) number of connections.

The main change I made to my network was turning off some random DoS protection feature on my router that was preventing port forwarding from working (although UPnP was still working).

**Comment by thienpow** [comment]
my connected peers is always around 6-7K !!!

**Comment by jacobheun** [comment]
I think we can close this. With 0.5 dht improvements and table refreshing low connection count shouldn't be an issue.

**Comment by thienpow** [comment]
i am using go-ipfs 0.6.0 , peers always reach 6-7k is it normal?

**Comment by jacobheun** [comment]
What does your swarm config look like? `ipfs config Swarm`

**Comment by thienpow** [comment]
```
thienpow@Thiens-MacBook-Pro ~ % ipfs config Swarm
{
  "AddrFilters": null,
  "ConnMgr": {
    "GracePeriod": "20s",
    "HighWater": 900,
    "LowWater": 600,
    "Type": "basic"
  },
  "DisableBandwidthMetrics": false,
  "DisableNatPortMap": false,
  "EnableAutoRelay": false,
  "EnableRelayHop": false,
  "Transports": {
    "Multiplexers": {},
    "Network": {},
    "Security": {}
  }
}
```

**Comment by thienpow** [comment]
if i am using IPFS Desktop, then peers is slow to grow and always around 200...
i think the different is IPFS Desktop start the daemon with --enable-gc --routing dhtclient
while if i start the daemon with "ipfs daemon" only... it shoot to 6-7k peers and 2700 threads in the ipfs process.

**Comment by jacobheun** [comment]
It's possible you are close to some popular content, which would make sense that running in dhtclient mode is lowering your connections. That sounds like you're getting a lot of inbound dht queries. If you're just running this on your home computer you may want to run in dht client mode.
