### ISSUE TITLE
Can't connect to any peer

### ISSUE THREAD

**Issue by lhadoux** [ipfs/go-ipfs#6721]
#### Version information:
v0.4.22

#### Description:
IPFS was working correctly  until yesterda but now, ipfs can't connect to any peers ( "ipfs swarm peers" prompt no result )

I tried to observe the logs while sending a new document and here is the result :

{"event":"swarmDialBackoff","peerID":"QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM","system":"swarm2","time":"2019-10-22T12:15:28.7480621Z"}
{"TraceID":2967012782558879382,"SpanID":6378776141593416157,"ParentSpanID":0,"Operation":"swarmDialAttemptSync","Start":"2019-10-22T14:15:28.7480621+02:00","Duration":0,"Tags":{"system":"swarm2"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":[{"Key
":"peerID","Value":"QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM"}]}]}
{"event":"bootstrapDialFailed","peerID":"QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM","system":"bootstrap","time":"2019-10-22T12:15:28.7485622Z"}
{"TraceID":5513320901784437587,"SpanID":3263299279084138467,"ParentSpanID":0,"Operation":"bootstrapDial","Start":"2019-10-22T14:15:28.7480621+02:00","Duration":500000,"Tags":{"system":"bootstrap"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":[{"Ke
y":"peerID","Value":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3"}]},{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":[{"Key":"peerID","Value":"QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM"}]}]}
{"addresses":["/p2p-circuit","/ip4/192.168.109.107/tcp/4001","/ip4/192.168.56.1/tcp/4001","/ip4/192.168.99.1/tcp/4001","/ip4/172.30.1.1/tcp/4001","/ip4/127.0.0.1/tcp/4001","/ip6/::1/tcp/4001"],"event":"interfaceListenAddresses","system":"addrutil","time":"2019-10-22T1
2:15:28.7505626Z"}
{"addresses":["/p2p-circuit","/ip4/192.168.109.107/tcp/4001","/ip4/192.168.56.1/tcp/4001","/ip4/192.168.99.1/tcp/4001","/ip4/172.30.1.1/tcp/4001","/ip4/127.0.0.1/tcp/4001","/ip6/::1/tcp/4001"],"event":"interfaceListenAddresses","system":"addrutil","time":"2019-10-22T1
2:15:28.7860697Z"}
{"addresses":["/p2p-circuit","/ip4/192.168.109.107/tcp/4001","/ip4/192.168.56.1/tcp/4001","/ip4/192.168.99.1/tcp/4001","/ip4/172.30.1.1/tcp/4001","/ip4/127.0.0.1/tcp/4001","/ip6/::1/tcp/4001"],"event":"interfaceListenAddresses","system":"addrutil","time":"2019-10-22T1
2:15:28.7860697Z"}
{"TraceID":6645274790161126449,"SpanID":3185543642992326824,"ParentSpanID":0,"Operation":"swarmDialDo","Start":"2019-10-22T14:15:28.7480621+02:00","Duration":5003135300,"Tags":{"system":"swarm2"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":[{"Key
":"localPeer","Value":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3"}]},{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":[{"Key":"remotePeer","Value":"QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd"}]},{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Field
s":[{"Key":"subsystem","Value":"swarm"}]}]}
{"event":"swarmDialBackoffAdd","localPeer":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3","remotePeer":"QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd","subsystem":"swarm","system":"swarm2","time":"2019-10-22T12:15:33.7515626Z"}
{"TraceID":7890212039028885394,"SpanID":5631808866020731620,"ParentSpanID":0,"Operation":"swarmDialAttemptStart","Start":"2019-10-22T14:15:28.7480621+02:00","Duration":5003635300,"Tags":{"system":"swarm2"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fiel
ds":[{"Key":"subsystem","Value":"swarm"}]},{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":[{"Key":"localPeer","Value":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3"}]},{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":[{"Key":"remotePeer","Value":
"QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd"}]}]}
{"TraceID":5155692032737472884,"SpanID":5126804528880294226,"ParentSpanID":0,"Operation":"swarmDialAttemptSync","Start":"2019-10-22T14:15:28.7480621+02:00","Duration":5003635300,"Tags":{"system":"swarm2"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Field
s":[{"Key":"peerID","Value":"QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd"}]}]}
{"event":"bootstrapDialFailed","peerID":"QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd","system":"bootstrap","time":"2019-10-22T12:15:33.7520627Z"}
{"TraceID":6986367473221341783,"SpanID":5145114247548433529,"ParentSpanID":0,"Operation":"bootstrapDial","Start":"2019-10-22T14:15:28.7480621+02:00","Duration":5003635300,"Tags":{"system":"bootstrap"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":[
{"Key":"peerID","Value":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3"}]},{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":[{"Key":"peerID","Value":"QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd"}]}]}
{"TraceID":1335270666629521185,"SpanID":8288258547924569493,"ParentSpanID":0,"Operation":"swarmDialDo","Start":"2019-10-22T14:15:28.7835692+02:00","Duration":5002635200,"Tags":{"system":"swarm2"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7835692+02:00","Fields":[{"Key
":"remotePeer","Value":"QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN"}]},{"Timestamp":"2019-10-22T14:15:28.7835692+02:00","Fields":[{"Key":"subsystem","Value":"swarm"}]},{"Timestamp":"2019-10-22T14:15:28.7835692+02:00","Fields":[{"Key":"localPeer","Value":"QmWwkGgHj
N1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3"}]}]}
{"event":"swarmDialBackoffAdd","localPeer":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3","remotePeer":"QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN","subsystem":"swarm","system":"swarm2","time":"2019-10-22T12:15:33.7865696Z"}
{"TraceID":1098624368586899102,"SpanID":6586516150749552674,"ParentSpanID":0,"Operation":"swarmDialAttemptStart","Start":"2019-10-22T14:15:28.7835692+02:00","Duration":5002635200,"Tags":{"system":"swarm2"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7835692+02:00","Fiel
ds":[{"Key":"subsystem","Value":"swarm"}]},{"Timestamp":"2019-10-22T14:15:28.7835692+02:00","Fields":[{"Key":"localPeer","Value":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3"}]},{"Timestamp":"2019-10-22T14:15:28.7835692+02:00","Fields":[{"Key":"remotePeer","Value":
"QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN"}]}]}
{"TraceID":4805966960403987913,"SpanID":7745483561237455608,"ParentSpanID":0,"Operation":"swarmDialAttemptSync","Start":"2019-10-22T14:15:28.7835692+02:00","Duration":5002635200,"Tags":{"system":"swarm2"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7835692+02:00","Field
s":[{"Key":"peerID","Value":"QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN"}]}]}
{"event":"bootstrapDialFailed","peerID":"QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN","system":"bootstrap","time":"2019-10-22T12:15:33.7865696Z"}
{"TraceID":5786152407204404889,"SpanID":3625921263613239251,"ParentSpanID":0,"Operation":"bootstrapDial","Start":"2019-10-22T14:15:28.7480621+02:00","Duration":5038139700,"Tags":{"system":"bootstrap"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":[
{"Key":"peerID","Value":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3"}]},{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":[{"Key":"peerID","Value":"QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN"}]}]}
{"TraceID":2394181469523588534,"SpanID":2764601410947005342,"ParentSpanID":0,"Operation":"swarmDialDo","Start":"2019-10-22T14:15:28.7835692+02:00","Duration":5003135300,"Tags":{"system":"swarm2"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7835692+02:00","Fields":[{"Key
":"subsystem","Value":"swarm"}]},{"Timestamp":"2019-10-22T14:15:28.7835692+02:00","Fields":[{"Key":"localPeer","Value":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3"}]},{"Timestamp":"2019-10-22T14:15:28.7835692+02:00","Fields":[{"Key":"remotePeer","Value":"QmcZf59bW
wK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"}]}]}
{"event":"swarmDialBackoffAdd","localPeer":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3","remotePeer":"QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt","subsystem":"swarm","system":"swarm2","time":"2019-10-22T12:15:33.7870697Z"}
{"TraceID":878006195427263024,"SpanID":8411560229034802597,"ParentSpanID":0,"Operation":"swarmDialAttemptStart","Start":"2019-10-22T14:15:28.7835692+02:00","Duration":5003135300,"Tags":{"system":"swarm2"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7835692+02:00","Field
s":[{"Key":"localPeer","Value":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3"}]},{"Timestamp":"2019-10-22T14:15:28.7835692+02:00","Fields":[{"Key":"remotePeer","Value":"QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"}]},{"Timestamp":"2019-10-22T14:15:28.7835692+02:0
0","Fields":[{"Key":"subsystem","Value":"swarm"}]}]}
{"TraceID":5913865731083990503,"SpanID":4730344302051576373,"ParentSpanID":0,"Operation":"swarmDialAttemptSync","Start":"2019-10-22T14:15:28.7835692+02:00","Duration":5003135300,"Tags":{"system":"swarm2"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7835692+02:00","Field
s":[{"Key":"peerID","Value":"QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"}]}]}
{"event":"bootstrapDialFailed","peerID":"QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt","system":"bootstrap","time":"2019-10-22T12:15:33.7870697Z"}
{"TraceID":8369893859576941559,"SpanID":668466851824001947,"ParentSpanID":0,"Operation":"bootstrapDial","Start":"2019-10-22T14:15:28.7480621+02:00","Duration":5038639800,"Tags":{"system":"bootstrap"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":[{
"Key":"peerID","Value":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3"}]},{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":[{"Key":"peerID","Value":"QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"}]}]}
{"TraceID":8775018476357313461,"SpanID":5891401212842833899,"ParentSpanID":0,"Operation":"bootstrapStart","Start":"2019-10-22T14:15:28.7480621+02:00","Duration":5038639800,"Tags":{"system":"bootstrap"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Fields":
[{"Key":"peerID","Value":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3"}]}]}
{"error":"failed to bootstrap. failed to dial : all dials failed\n  * [/ip4/139.178.88.21/tcp/4001] dial tcp4 0.0.0.0:4001->139.178.88.21:4001: i/o timeout","event":"bootstrapError","peerID":"QmWwkGgHjN1obBWkS4aAdJe46fwK6JJryUS8B5mDNucuj3","system":"bootstrap","time":
"2019-10-22T12:15:33.7870697Z"}
{"TraceID":8263591921871347376,"SpanID":3185968610038181506,"ParentSpanID":0,"Operation":"periodicBootstrap","Start":"2019-10-22T14:15:28.7480621+02:00","Duration":5038639800,"Tags":{"system":"bootstrap"},"Logs":[{"Timestamp":"2019-10-22T14:15:28.7480621+02:00","Field
s":[{"Key":"peerID","

I thenk tried to use ipfs desktop and had the same problem.

**Comment by lordcirth** [comment]
@lhadoux Can you still not connect to any peer? Do you have the standard bootstrap list? What OS are you on? Did anything change around when it stopped working? Thanks.
