### ISSUE TITLE
Flaky go-ipfs test

### ISSUE THREAD

**Issue by momack2** [ipfs/go-ipfs#6728]
CI: https://circleci.com/gh/ipfs/go-ipfs/21847?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

![Screen Shot 2019-10-25 at 1 52 38 AM](https://user-images.githubusercontent.com/618519/67557624-469c8400-f6ca-11e9-92a5-c51d956c9ea8.png)

Added a PR to the readme and got some CI failures. Shouldn't have, so filing a bug as requested by @Stebalien

**Comment by Stebalien** [comment]
Turns out this is not a go-ipfs issue. The `_dnsaddr.bootstrap.libp2p.io` TXT records are too large to fit into a single packet. This has been reported to infra.

**Comment by Stebalien** [comment]
(and fixed)
