### ISSUE TITLE
large repo + diskUsage calc timesout systemd unit

### ISSUE THREAD

**Issue by elitak** [ipfs/go-ipfs#6741]
#### Version information:
go-ipfs version: 0.4.22-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.9
Please check dist.ipfs.io for a newer version of go-ipfs and update if necessary. Report back if the problem persists.

#### Description:
I have a very large repo (10TB+ on XFS). Sometimes (I don't know the interval), ipfs-daemon decides it needs to refresh the blocks/diskUsage.cache file *on startup*, and takes so long computing the new usage, that systemd thinks the service has failed to start and kills the process. How can I disable the recalculation or make it run only after the daemon has started up, in a background thread?

**Comment by Stebalien** [comment]
At the moment, the only way to do this is to use badger (not flatfs). This can happen when we fail to persist the disk usage file on close (e.g., we crash).

Note: we currently abort trying to calculate the size after 5 minutes. You might want to consider increasing your systemd service start timeout.

Alternatively, if you have some time, I'd love a patch that calculates the disk usage in the background. IIRC, we don't do this as it's difficult to impossible to get a consistent snapshot of the datastore size while it's open for writing.

**Comment by elitak** [comment]
Where in the code is the check and the 5m timeout? I'd rather just patch that for now.

**Comment by Stebalien** [comment]
The `DiskUsageCalcTimeout` defined in github.com/ipfs/go-ds-flatfs (flatfs.go). You should be able to set this from an `init() {}` from within go-ipfs itself (or a plugin) to avoid having to patch the dep.
