### ISSUE TITLE
ipfs add with onlyhash, memery high usage

### ISSUE THREAD

**Issue by hcg1314** [ipfs/go-ipfs#6744]
#### Version information:
go-ipfs version: 0.4.22-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.7

#### Description:
The VM has 8GB of RAM.
My application will generate a lots of calls `ipfs add -n` with a speed 40 per seonds.
Firstly, the ipfs daemon just cost little memery. however, one hours later, out of memery.
If stop my application, the ipfs will return to normal after a few hours.

i want to know, is there a way to reduce recovery time? thanks!

[here is the data collected by bin/collect-profiles.sh](https://github.com/ipfs/go-ipfs/files/3802961/ipfs-profile-xzj-tmp-per03-2019-11-04T115439%2B0800.tar.gz)

**Comment by hcg1314** [comment]
when i add `defer nilnode.Peerstore.Close()` in core/coreapi/unixfs.go，the MEM% grow up slower

**Comment by Stebalien** [comment]
@hcg1314 what if you add `defer nilnode.Close()`?

**Comment by hcg1314** [comment]
> @hcg1314 what if you add `defer nilnode.Close()`? #6744

If add `defer nilnode.Close()`, seems like can not release Peerstore. 
I have tested it.

**Comment by Stebalien** [comment]
What if you add both? I'm trying to figure out "the MEM% grow up slower".

There's a bug in go-ipfs 0.4.22 where we don't close the peerstore when the node is closed. This has been fixed in master.

**Comment by hcg1314** [comment]
'master' branch has fix this issue
