### ISSUE TITLE
What is the impact of raising the minimum RSA key length to 2048 bits

### ISSUE THREAD

**Issue by olizilla** [ipfs/go-ipfs#6751]
[libp2p 0.3 was released](https://github.com/libp2p/go-libp2p/releases/tag/v0.3.0) with the change

> The minimum allowed strength of RSA keys is now 2048 bits

The default key size for `ipfs init` was [originally 4096](https://github.com/ipfs/go-ipfs/blame/fb12530822708ccb4c4d4bc4426ddb0b8baf2bcb/cmd/ipfs2/init.go#L105-L111) in 2014, and was [lowered to 2048](https://github.com/ipfs/go-ipfs/commit/16f56e1c9b62e91f0c009eb03749a0276e45c9d4) in 2015 ([v0.3.1](https://github.com/ipfs/go-ipfs/commit/b1adeef85ce0558ca51754a01d6ebaac2ebeeccd)), so there has never been a time when 1024 keys were generated for users without them explicitly opting in.

However, users have been able to `ipfs init -b 1024` since 2014 and the current release 0.4.22 still allows the user to `ipfs init -b 1024` without a warning.

If a user has an existing repo that was deliberatly set up with a rsa key less than 2048 bits what will be their experience? Do we have any numbers on how many nodes are out there using short rsa keys? It is notable that the old solarnet boostrap nodes all have 1024 bit keys, which would acount for ~5 unique peer ids that would no longer be dialable.

**Comment by Stebalien** [comment]
> If a user has an existing repo that was deliberatly set up with a rsa key less than 2048 bits what will be their experience?

1. IPFS will refuse to start.
2. Even if they downgrade, nobody will talk with them.

> Do we have any numbers on how many nodes are out there using short rsa keys? 

No, but my guess is 5. We could figure this out by adding some logging to the bootstrappers to record every public key smaller than 2048 bits. Alternatively, we could augment the current DHT crawlers to record this (but I don't even know where they live).

We can trivially revert this change in go-ipfs itself and add a deprecation period. However,

**Comment by Stebalien** [comment]
New information: apparently, libp2p doesn't _recursively_ resolve dnsaddr addresses.

**Comment by Stebalien** [comment]
https://github.com/libp2p/go-libp2p/issues/744

**Comment by Stebalien** [comment]
Resolved.
