### ISSUE TITLE
why go-ipfs can't run in alphine linux？

### ISSUE THREAD

**Issue by happyqq** [ipfs/go-ipfs#6752]
when I download https://github.com/ipfs/go-ipfs/releases/download/v0.4.22/go-ipfs_v0.4.22_linux-amd64.tar.gz
I unzip this file.
but I can't run go-ipfs run in alphine linux 3.10
who can help me to resolve this problem?

**Comment by Stebalien** [comment]
Please ask support questions on https://discuss.ipfs.io. When you do, please include the _exact_ error you saw.
