### ISSUE TITLE
Support for golang 1.11 required for debian package

### ISSUE THREAD

**Issue by emelleme** [ipfs/go-ipfs#6757]
#### Version information:
go-ipfs version: 0.4.22-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.6

#### Description:

While creating a package of go-ipfs, we were unable to build the package. go-ipfs requires golang version 1.12+, but debian latest versions are at golang 1.11. 

Please update go-ipfs to support golang versions 1.11 to enable packaging of go-ipfs for proper debian package distribution.

Thank you.

**Comment by dpocock** [comment]
This page shows the available versions of Go in Debian and Ubuntu:

https://packages.qa.debian.org/g/golang-defaults.html

As Debian 10 (buster) has just been released with Go 1.11 and there is typically a delay of 2 years between Debian releases, Debian users will be on Go 1.11 until mid-2021.

For IPFS to be successful, it needs as many people as possible to be part of it.  That means it is probably a good idea not to use the latest features of Go and only depend on features available in the stable releases of the major distributions.

Somebody may put a newer version of Go in the Debian backports repository but that may break things for other applications that only work with 1.11.  As there are an increasing number of Go applications in Debian, some users may not be able to install a backport if they don't want to take that risk.

**Comment by dpocock** [comment]
Fedora's Go packages are covered here:

https://bodhi.fedoraproject.org/updates/?packages=golang

Summarising: Debian has 1.11, Ubuntu has 1.12 and Fedora has 1.13.  This is not unusual as each distribution takes a different approach to updating their packages during the lifecycle of a stable release.

**Comment by Stebalien** [comment]
Unfortunately, we need the latest features and bugfixes. We're going to be switching to go 1.13 soon for ed25519 support in TLS.

Regardless, you probably shouldn't ship go-ipfs in a stable debian repo anyways as the network protocols are constantly evolving and we don't backport patches. End-users should generally install https://github.com/ipfs-shipyard/ipfs-desktop or https://github.com/ipfs/ipfs-update (which needs a bit of work...).
