### ISSUE TITLE
IPFS Add With OnlyHash, High CPU Usage

### ISSUE THREAD

**Issue by hcg1314** [ipfs/go-ipfs#6760]
#### Version information:
go-ipfs version: 0.5.0-dev-ec748a7
Repo version: 7
System version: amd64/linux
Golang version: go1.12.7

I clone the newest 'master' branch, and compile the ipfs myself.

#### Description:
The VM has 8G RAM and 4 CPUs.
When i execute `ipfs add -n xxx` with a speed 40 per second, ipfs daemon %CPU is 389，almost all my cpu resources.
From the cpu.svg, we know `crypto/rsa.GenerateKey` has cost so much cpu resources. My question is whether it is necessary to create a different identity for each fake repo? Is it possible to use a same identity?

```
func defaultRepo(dstore repo.Datastore) (repo.Repo, error) {
	c := cfg.Config{}
        // distinguish the fake repo by `NilRepo` tag, and use a same identity
	priv, pub, err := ci.GenerateKeyPairWithReader(ci.RSA, 2048, rand.Reader)
	if err != nil {
		return nil, err
	}

	pid, err := peer.IDFromPublicKey(pub)
	if err != nil {
		return nil, err
	}

	privkeyb, err := priv.Bytes()
	if err != nil {
		return nil, err
	}

	c.Bootstrap = cfg.DefaultBootstrapAddresses
	c.Addresses.Swarm = []string{"/ip4/0.0.0.0/tcp/4001"}
	c.Identity.PeerID = pid.Pretty()
	c.Identity.PrivKey = base64.StdEncoding.EncodeToString(privkeyb)

	return &repo.Mock{
		D: dstore,
		C: c,
	}, nil
}
```

[here is the data collected by bin/collect-profiles.sh](https://github.com/ipfs/go-ipfs/files/3834875/profile.tar.gz)

**Comment by hcg1314** [comment]
here is the `time ipfs add -n xxx` result:
![1](https://user-images.githubusercontent.com/41573766/68655204-91dbe100-056a-11ea-98c9-5e8412ae0230.png)

**Comment by Stebalien** [comment]
We should just stop creating ephemeral nodes in this case.

**Comment by hcg1314** [comment]
> We should just stop creating ephemeral nodes in this case.

You mean we can create a permanent node for `ipfs add -n xxx`?  This is better. Don't create and release object frequently.

**Comment by Stebalien** [comment]
Sorry, too many types of "nodes". I meant we shouldn't instantiate a new instance of the "IPFS node" (the application) each time we do this. We're literally creating a new instance of IPFS with a "nil" datastore.

**Comment by hcg1314** [comment]
func (api *UnixfsAPI) Add(ctx context.Context, files files.Node, opts ...options.UnixfsAddOption) (path.Resolved, error) {}
```
if settings.OnlyHash {
        // i mean that can`core.NewNode` be done only once for all adding with hash-only?
	nilnode, err := core.NewNode(ctx, &core.BuildCfg{
		//TODO: need this to be true or all files
		// hashed will be stored in memory!
		NilRepo: true,
	})
	if err != nil {
		return nil, err
	}
	defer nilnode.Close()
	addblockstore = nilnode.Blockstore
	exch = nilnode.Exchange
	pinning = nilnode.Pinning
}
```

**Comment by Stebalien** [comment]
?

**Comment by hcg1314** [comment]
i mean reuse the object  created by `core.NewNode`

**Comment by Stebalien** [comment]
Hm. Probably?

**Comment by Stebalien** [comment]
@hcg1314 thanks for fixing this!
