### ISSUE TITLE
private network was not configured but is enforced by the environment

### ISSUE THREAD

**Issue by GiovanniCapizzi** [ipfs/go-ipfs#6763]
I'm trying to setup a private ipfs network. I'm using the current docker hub image and I did small changes to the start_ipfs file:

```#!/bin/sh
set -e
user=ipfs
repo="$IPFS_PATH"

if [ `id -u` -eq 0 ]; then
  echo "Changing user to $user"
  # ensure folder is writable
  su-exec "$user" test -w "$repo" || chown -R -- "$user" "$repo"
  # restart script with new privileges
  exec su-exec "$user" "$0" "$@"
fi

# 2nd invocation with regular user
ipfs version

if [ -e "$repo/config" ]; then
  echo "Found IPFS fs-repo at $repo"
else
  case "$IPFS_PROFILE" in
    "") INIT_ARGS="" ;;
    *) INIT_ARGS="--profile=$IPFS_PROFILE" ;;
  esac
  ipfs init $INIT_ARGS
  ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
  ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080

  # edits ...
  
  ipfs bootstrap rm --all
  ipfs bootstrap add /ip4/$(hostname -i)/tcp/4001/ipfs/$(ipfs config show | grep "PeerID" |  sed 's/^.*: "\(.*\)"$/\1/')

  # ----------------------------------------

  # Set up the swarm key, if provided

  SWARM_KEY_FILE="$repo/swarm.key"
  SWARM_KEY_PERM=0400

  # Create a swarm key from a given environment variable
  if [ ! -z "$IPFS_SWARM_KEY" ] ; then
    echo "Copying swarm key from variable..."
    echo -e "$IPFS_SWARM_KEY" >"$SWARM_KEY_FILE" || exit 1
    chmod $SWARM_KEY_PERM "$SWARM_KEY_FILE"
  fi

  # Unset the swarm key variable
  unset IPFS_SWARM_KEY

  # Check during initialization if a swarm key was provided and
  # copy it to the ipfs directory with the right permissions
  # WARNING: This will replace the swarm key if it exists
  if [ ! -z "$IPFS_SWARM_KEY_FILE" ] ; then
    echo "Copying swarm key from file..."
    install -m $SWARM_KEY_PERM "$IPFS_SWARM_KEY_FILE" "$SWARM_KEY_FILE" || exit 1
  fi

  # Unset the swarm key file variable
  unset IPFS_SWARM_KEY_FILE

fi

# edits ...
export LIBP2P_FORCE_PNET=1 
exec ipfs "$@"


```
Then I start the node with:
```docker run -d --name ipfs_bootstrap -e IPFS_PROFILE=server -e SWARM_KEY=./bootstrap/key/swarm.key -v $ipfs_staging:/export -v $ipfs_data:/data/ipfs -v $ipfs_start/start_ipfs.sh:/usr/local/bin/start_ipfs -p 4001:4001 -p 127.0.0.1:8080:8080 -p 127.0.0.1:5001:5001 ipfs/go-ipfs:latest ```

But it gives this error. I am able to setup a working network manually with these steps but I cannot reproduce with that image. Any idea? 
```15:27:04.294 ERROR p2p-config: tried to create a libp2p node with no Private Network Protector but usage of Private Networks is forced by the enviroment config.go:79
15:27:04.294 ERROR   cmd/ipfs: error from node construction:  could not build arguments for function "github.com/ipfs/go-ipfs/core/node".IpnsRepublisher.func1 (/go-ipfs/core/node/ipns.go:38): failed to build namesys.NameSystem: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Namesys.func1 (/go-ipfs/core/node/ipns.go:31): failed to build routing.IpfsRouting: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Routing (/go-ipfs/core/node/libp2p/routing.go:60): could not build value group libp2p.Router[group="routers"]: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".BaseRouting (/go-ipfs/core/node/libp2p/routing.go:34): failed to build libp2p.BaseIpfsRouting: function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (/go-ipfs/core/node/libp2p/host.go:39) returned a non-nil error: privnet: private network was not configured but is enforced by the environment daemon.go:337

Error: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".IpnsRepublisher.func1 (/go-ipfs/core/node/ipns.go:38): failed to build namesys.NameSystem: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Namesys.func1 (/go-ipfs/core/node/ipns.go:31): failed to build routing.IpfsRouting: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Routing (/go-ipfs/core/node/libp2p/routing.go:60): could not build value group libp2p.Router[group="routers"]: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".BaseRouting (/go-ipfs/core/node/libp2p/routing.go:34): failed to build libp2p.BaseIpfsRouting: function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (/go-ipfs/core/node/libp2p/host.go:39) returned a non-nil error: privnet: private network was not configured but is enforced by the environment```

**Comment by Stebalien** [comment]
1. SWARM_KEY should be IPFS_SWARM_KEY
2. It needs to be a literal string containing the _contents_ of your swarm key file, not the path of the file.

**Comment by GiovanniCapizzi** [comment]
Dear lord... One full day making containers and docker files and I didn't see that error.. It was completely blind to me, so sorry!

**Comment by GiovanniCapizzi** [comment]
> * SWARM_KEY should be IPFS_SWARM_KEY
> * It needs to be a literal string containing the _contents_ of your swarm key file, not the path of the file.

Sorry for the mistake, it didn't work either:
```Changing user to ipfs
ipfs version 0.4.22
Found IPFS fs-repo at /data/ipfs
Initializing daemon...
go-ipfs version: 0.4.22-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.7
23:00:11.954 ERROR p2p-config: tried to create a libp2p node with no Private Network Protector but usage of Private Networks is forced by the enviroment config.go:79
23:00:11.955 ERROR   cmd/ipfs: error from node construction:  could not build arguments for function "github.com/ipfs/go-ipfs/core/node".IpnsRepublisher.func1 (/go-ipfs/core/node/ipns.go:38): failed to build namesys.NameSystem: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Namesys.func1 (/go-ipfs/core/node/ipns.go:31): failed to build routing.IpfsRouting: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Routing (/go-ipfs/core/node/libp2p/routing.go:60): could not build value group libp2p.Router[group="routers"]: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".BaseRouting (/go-ipfs/core/node/libp2p/routing.go:34): failed to build libp2p.BaseIpfsRouting: function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (/go-ipfs/core/node/libp2p/host.go:39) returned a non-nil error: privnet: private network was not configured but is enforced by the environment daemon.go:337

Error: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".IpnsRepublisher.func1 (/go-ipfs/core/node/ipns.go:38): failed to build namesys.NameSystem: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Namesys.func1 (/go-ipfs/core/node/ipns.go:31): failed to build routing.IpfsRouting: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Routing (/go-ipfs/core/node/libp2p/routing.go:60): could not build value group libp2p.Router[group="routers"]: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".BaseRouting (/go-ipfs/core/node/libp2p/routing.go:34): failed to build libp2p.BaseIpfsRouting: function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (/go-ipfs/core/node/libp2p/host.go:39) returned a non-nil error: privnet: private network was not configured but is enforced by the environment```

Cannot do right now other tests, it's too late now, I will try again tomorrow

**Comment by Stebalien** [comment]
> Found IPFS fs-repo at /data/ipfs

It's using your already initialized repo rather than copying in the key.

**Comment by GiovanniCapizzi** [comment]
Finally solved thanks!

**Comment by mrodriguez3313** [comment]
> Finally solved thanks!

How did you solve the problem? @GiovanniCapizzi

**Comment by GiovanniCapizzi** [comment]
> > Finally solved thanks!
> 
> How did you solve the problem? @GiovanniCapizzi

Hey, I just did the same thing as in the first post, but i corrected "SWARM_KEY" to "IPFS_SWARM_KEY"  and I didn't set it to a path but to the swarm key string.

Just read the key in this way:

`IPFS_SWARM_KEY=$(sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g' ./ipfs/swarm.key)`

Hope you will solve, let me know

**Comment by mrodriguez3313** [comment]
Thank you for the response! It seems that wasn't my problem, even though I had that exact same output error, but I was able to fix it another way. It must've been my set up that went wrong? For my set up I didn't make a custom dockerfile and just ran it like below; I bootstrapped my local machine and added myself; I generated a swarm file and had it in ~/.ipfs. What I did was (just to mention in case someone else can benefit from it) is I manually added the LIBP2P_FORCE_PNET=1 env variable manually:
I ran my docker container like this:

`> docker run -d --name ipfs_node -e IPFS_SWARM_KEY=<swarm-key-string-without-quotation-marks> -v $ipfs_staging:/export -v $ipfs_data:/data/ipfs ipfs/go-ipfs:latest `

Then after it started the daemon, I added the swarm file into the directory where the config file is for ipfs in docker. For me it was /data/ipfs/:
`sudo docker cp swarm.key ipfsnode:/data/ipfs`
(I did this just for safe measure)

Then stopped the container and had to find the environment variables for docker which for me was at /var/lib/docker/volumes/<container-id>/config.v2.json: 
To edit it I did:

`sudo vim  /var/lib/docker/<docker-id>/config.v2.json`

And I manually put in the variable LIBP2P_FORCE_PNET=1 in there and when I went to restart the container I had no problems and when I go to check the swarm peers and swarm addrs on both my local machine and my container, I can only see my local machine and the container. When I add a file from one I can do ifps cat <file-hash> and see the contents of the file from either machine. Hope this helps anyone else!

**Comment by D3vl0per** [comment]
> > > Finally solved thanks!
> > 
> > 
> > How did you solve the problem? @GiovanniCapizzi
> 
> Hey, I just did the same thing as in the first post, but i corrected "SWARM_KEY" to "IPFS_SWARM_KEY" and I didn't set it to a path but to the swarm key string.
> 
> Just read the key in this way:
> 
> `IPFS_SWARM_KEY=$(sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g' ./ipfs/swarm.key)`
> 
> Hope you will solve, let me know

Thank you so much!
