### ISSUE TITLE
Make license file format compatible with pkg.go.dev

### ISSUE THREAD

**Issue by jimpick** [ipfs/go-ipfs#6772]
https://pkg.go.dev/ is a new service from Google that is an improved godoc.org - most useful is that it can display documentation from multiple versions.

It won't display some information about ipfs/go-ipfs "due to license restrictions"...

https://pkg.go.dev/github.com/ipfs/go-ipfs?tab=licenses

https://pkg.go.dev/license-policy says:

> If we are not able to detect a suitable license, only limited package and module information will be made available. If you are a package author seeking to make your content available on the Go website, please be aware that our detection algorithms can be affected by any modifications of the license text, or by the use of an uncommon license file name. We currently check for licenses only in files with the following names: COPYING, COPYING.md, COPYING.txt, LICENCE, LICENCE.md, LICENCE.txt, LICENSE, LICENSE.md, LICENSE.txt.

**Comment by Mr0grog** [comment]
Looks like this was fixed in #6873 and #6874 — pkg.go.dev is showing the right licensing info now.

**Comment by Stebalien** [comment]
Yep!
