### ISSUE TITLE
If there are too many IPFs pin operations, it will be stuck when add uploads the file

### ISSUE THREAD

**Issue by xjxqsl** [ipfs/go-ipfs#6777]
#### Version information:
go-ipfs version: 0.4.18-aefc746
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1

If there are too many IPFs pin operations, it will be stuck when add uploads the file

**Comment by Stebalien** [comment]
Please try again with the latest version of go-ipfs (0.4.22). 0.4.18 was released over a year ago.
