### ISSUE TITLE
find peer early exit

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#678]
FindPeer may fail to find all addresses associated with a peer, if the first respondee to the query does not have all addresses. 

Example:
```
A FindPeer(X) -> {B, C}

B replies: {X : [127.0.0.1:4001]}
A ends find peer
C replies {X : [76.45.35.75:4001]} and is ignored since A ended the query
```

I will address this soon, just wanted to file a bug so i remember.

**Comment by jbenet** [comment]
yeah :/

**Comment by whyrusleeping** [comment]
I'll verify.

**Comment by whyrusleeping** [comment]
not yet fixed AFAICT, i have a changeset im working on that fixes a similar issue with "Get" so i may just apply the same fix to findPeer

**Comment by whyrusleeping** [comment]
solved
