### ISSUE TITLE
Too many open files on Unixfs().Add()

### ISSUE THREAD

**Issue by hacdias** [ipfs/go-ipfs#6780]
#### Version information:

Latest via https://github.com/ipfs/interface-go-ipfs-core

#### Description:

While using `Unixfs().Add()` to add a file with over 1 GB, it fails on my computer with `too many open files` and the error is caused while trying to open a file on the block storage.

Related to https://github.com/ipfs/testground/pull/58

**Comment by Stebalien** [comment]
How many concurrent adds are you performing? I assume you're using the local runner and running multiple IPFS nodes at once.

For now, let's switch that test case to badger. Unfortunately, flatfs doesn't currently limit the number of open files so, if you have a low limit and many concurrent adds, you'll run out of file descriptors.

**Comment by hacdias** [comment]
Fixed this by changing the `ulimit`!
