### ISSUE TITLE
Ipfs gc problem

### ISSUE THREAD

**Issue by xjxqsl** [ipfs/go-ipfs#6783]
Two ipfs nodes: when one ipfs node uploads the file, the other one downloads the file. When the node of the upload node is gc, the node file of the download end cannot be downloaded. Can you perform gc according to the time cycle of the data，Delete garbage files based on time

**Comment by dirkmc** [comment]
To run garbage collection manually:
`ipfs repo gc`
This will garbage collect any unpinned files.

To pin a file run `ipfs pin add <hash>`

**Comment by Stebalien** [comment]
Ah, I think you're asking for garbage collection of infrequently used/old data?

This is a long-time wish-list item: https://github.com/ipfs/go-ipfs/issues/5515. For now, most users just disable GC and keep everything.

(closing as a duplicate).
