### ISSUE TITLE
v0.4.22 constantly error, have to manually restart ipfs, why?

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#6806]
I have latest ipfs runing, v0.4.22 with ipfs desktop 
but every a few days, the status is error.

I have to restart ipfs, use ipfs-desktop (mac)

What cause the ipfs error?
NO more than 7 days, I will experience a ipfs error. 

If error can not be fixed, then
Is there way ipfs-desktop can automatically restart ipfs when error or failure?

**Comment by Stebalien** [comment]
Could you post the logs? See https://github.com/ipfs-shipyard/ipfs-desktop#where-is-the-configuration-and-logs.

**Comment by hoogw** [comment]
this is commend tool:

`The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
siriuss-mini:~ sirius$ ipfs daemon
Initializing daemon...
go-ipfs version: 0.4.22-
Repo version: 7
System version: amd64/darwin
Golang version: go1.12.7
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.86.207/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.86.207/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
panic: concurrent write to websocket connection

goroutine 17657899 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc001b66150, 0x5d4b701, 0x0, 0x0, 0x0, 0x10173af, 0x6779ff8)
	pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:591 +0x77a
github.com/gorilla/websocket.(*messageWriter).Close(0xc001b66150, 0x0, 0x889605d4b700)
	pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:709 +0x56
github.com/gorilla/websocket.(*Conn).prepWrite(0xc002853b80, 0x2, 0x203002, 0x6779ff8)
	pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:459 +0x20d
github.com/gorilla/websocket.(*Conn).NextWriter(0xc002853b80, 0x2, 0x100bbd9, 0xc00758fd80, 0x10, 0xc0075f1501)
	pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:494 +0x39
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc002853b80, 0x2, 0xc00a29b000, 0x23, 0x1000, 0x10, 0xc000387800)
	pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:755 +0x73
github.com/libp2p/go-ws-transport.(*Conn).Write(0xc006f6a120, 0xc00a29b000, 0x23, 0x1000, 0xc00ab25cc0, 0x100c468, 0x1)
	pkg/mod/github.com/libp2p/go-ws-transport@v0.0.4/conn.go:74 +0x59
bufio.(*Writer).Flush(0xc0096979c0, 0xc0096979c0, 0xc00a6659b0)
	/usr/lib/go/src/bufio/bufio.go:590 +0x7b
github.com/multiformats/go-multistream.delimWriteBuffered(0x5b79250, 0xc006f6b800, 0xc00a6659b0, 0x21, 0x21, 0x0, 0x0)
	pkg/mod/github.com/multiformats/go-multistream@v0.0.4/multistream.go:72 +0xdd
github.com/multiformats/go-multistream.ReadNextTokenBytes(0x5d4b770, 0xc006f6b800, 0xc009b69620, 0x103689f, 0xc009b695f0, 0xc009b69620, 0x1009c35)
	pkg/mod/github.com/multiformats/go-multistream@v0.0.4/multistream.go:393 +0x17f
github.com/multiformats/go-multistream.ReadNextToken(...)
	pkg/mod/github.com/multiformats/go-multistream@v0.0.4/multistream.go:377
github.com/multiformats/go-multistream.readMultistreamHeader(0x5d4b770, 0xc006f6b800, 0xc006f6b800, 0x5d4b770)
	pkg/mod/github.com/multiformats/go-multistream@v0.0.4/client.go:90 +0x3a
github.com/multiformats/go-multistream.SelectProtoOrFail(0x1e28f36, 0xc, 0x5d4b740, 0xc006f6b800, 0x5d4b740, 0x0)
	pkg/mod/github.com/multiformats/go-multistream@v0.0.4/client.go:31 +0xd7
github.com/multiformats/go-multistream.SelectOneOf(0xc00038aa00, 0x2, 0x2, 0x5d4b740, 0xc006f6b800, 0x2000200, 0x2000000, 0x0, 0x0)
	pkg/mod/github.com/multiformats/go-multistream@v0.0.4/client.go:57 +0x6c
github.com/libp2p/go-conn-security-multistream.(*SSMuxer).selectProto.func1(0xc003c7cf60, 0x0, 0xc000140af0, 0x5d4b6e8, 0xc006f6b800, 0xc00b435030, 0xc00b435110)
	pkg/mod/github.com/libp2p/go-conn-security-multistream@v0.0.2/ssms.go:68 +0x192
created by github.com/libp2p/go-conn-security-multistream.(*SSMuxer).selectProto
	pkg/mod/github.com/libp2p/go-conn-security-multistream@v0.0.2/ssms.go:63 +0xe5
siriuss-mini:~ sirius$

**Comment by hoogw** [comment]
last a few days log:
    `2019-12-28T07:29:50.658Z info: [web ui] navigate to /
2019-12-28T07:30:06.655Z info: [web ui] window hidden
2019-12-28T07:32:29.330Z info: [web ui] navigate to /
2019-12-29T16:54:18.528Z info: [web ui] navigate to /
2019-12-29T17:51:57.466Z info: [ipfsd] stop daemon STARTED
2019-12-29T17:53:49.087Z info: [web ui] navigate to /
2019-12-29T18:00:08.945Z info: [ipfsd] stop daemon STARTED
2019-12-29T18:00:08.948Z info: [ipfsd] stop daemon FINISHED 0.002263143002986908s
2019-12-29T18:00:57.020Z info: [meta] logs can be found on /Users/sirius/Library/Application Support/IPFS Desktop
2019-12-29T18:01:01.391Z info: [web ui] window ready
2019-12-29T18:01:01.391Z info: [tray] starting
2019-12-29T18:01:01.446Z info: [tray] started
2019-12-29T18:01:01.447Z info: [ipfsd] start daemon STARTED
2019-12-29T18:01:01.869Z error: [ipfsd] start daemon Error: Error: mkdir /Volumes/d/ipfs_repo: no such file or directory
2019-12-29T18:01:01.899Z info: [npm on ipfs] no action taken
2019-12-29T18:01:01.900Z info: [ipfs on path] no action taken
2019-12-29T18:01:03.323Z error: [launch on startup] old mechanism disabled
2019-12-29T18:01:03.353Z info: [launch on startup] enabled
2019-12-29T18:01:12.807Z info: [web ui] navigate to /
2019-12-31T06:16:46.123Z info: [web ui] navigate to /
2020-01-01T17:53:37.354Z info: [web ui] navigate to /

**Comment by hoogw** [comment]
`2019-12-26T06:25:22.777Z error: [launch on startup] old mechanism disabled
2019-12-26T08:43:40.118Z error: [launch on startup] old mechanism disabled
2019-12-26T09:03:51.208Z error: [ipfsd] start daemon Error: Error: mkdir /Volumes/d/ipfs_repo: permission denied
2019-12-26T09:03:52.841Z error: [launch on startup] old mechanism disabled
2019-12-29T18:01:01.869Z error: [ipfsd] start daemon Error: Error: mkdir /Volumes/d/ipfs_repo: no such file or directory
2019-12-29T18:01:03.323Z error: [launch on startup] old mechanism disabled

**Comment by hoogw** [comment]
Is it possible my hard drive HDD, physical failure?

If the hard drive physical failure, what error message would be?

Last year, I have experience that when ipfs add folder for 300GB, always failure at 275 GB, found out it is hard drive physical failure, unstable, error,... I changed the hard drive to a new one, it succeeded. 

Now in order to prevent that, I use 2 hard drive setup raid 1, duplicate each other, even one failed, the other still working.  I checked the raid 1 status, both hard drive is online, no issue, when error happened.

**Comment by Mithgol** [comment]
That's likely #6197.

**Comment by Stebalien** [comment]
@Mithgol is right. Could you try building the latest master?

**Comment by hoogw** [comment]
I don't know how to build the latest master.  I will wait next release v0.4.23 then use update tool to update it like I update from 4.19 to 4.22

**Comment by Stebalien** [comment]
Released.
