### ISSUE TITLE
build error (linux Ubuntu 16.04)

### ISSUE THREAD

**Issue by mud0107** [ipfs/go-ipfs#6810]
error description

parallels@ubuntu:~/go/src/github.com/ipfs/go-ipfs$ make install
go version go1.13.5 linux/amd64
bin/check_go_version 1.13
go install  "-asmflags=all='-trimpath=/home/parallels/go'" "-gcflags=all='-trimpath=/home/parallels/go'" -ldflags="-X "github.com/ipfs/go-ipfs".CurrentCommit=73419b9" ./cmd/ipfs
# runtime
/usr/local/go/src/runtime/stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at /usr/local/go/src/runtime/stubs_amd64x.go:10:6
/usr/local/go/src/runtime/unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at /usr/local/go/src/runtime/alg.go:321:40
/usr/local/go/src/runtime/unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at /usr/local/go/src/runtime/alg.go:329:40
cmd/ipfs/Rules.mk:37: recipe for target 'cmd/ipfs-install' failed
make: *** [cmd/ipfs-install] Error 2

soultion??

**Comment by godcong** [comment]
it looks your go source problems
some value was defined in two files,and build import these two.
