### ISSUE TITLE
Unable to connect ipfs webui

### ISSUE THREAD

**Issue by SirBlues** [ipfs/go-ipfs#6824]
三台主机，添加，config内容
{
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Methods": [
        "PUT",
        "GET",
        "POST"
      ],
      "Access-Control-Allow-Origin": [
        "http://192.168.159.128:5001",
        "http://127.0.0.1:5001",
        "https://webui.ipfs.io"
      ]
    }
  },
  "Addresses": {
    "API": "/ip4/0.0.0.0/tcp/5001",
    "Announce": [],
    "Gateway": "/ip4/0.0.0.0/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ]
  },
  "Bootstrap": null,
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Experimental": {
    "FilestoreEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "PreferTLS": false,
    "QUIC": false,
    "ShardingEnabled": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET",
        "POST",
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoFetch": false,
    "PathPrefixes": [],
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "QmYWgc14JTEZhxhrd8XmMAzueLJT8EqnwZ7J9m52wkt6DN",
    "PrivKey": "CAASqAkwggSkAgEAAoIBAQDdyZ0+/S/eSSMkjcEj9clqw/bv+sZPgmvObr5jzNr2giElWeaOMnHyW2NoQpVj1sgnLqWHXGZYueK+5KaxMuFS2LjcqhUz8q1iAokal1GhOcxbkZ4nme4q6He4rxOCyCg3o6EAiy4TV/u9oL09ICb++A+5iO9XgZoomSP3q0N2ECo9c12B2N9zZk+S/CRGVDLu+EsBt9KMMd/FPgMVDO+cTaHlK1vC0MzPenzt117jmGRPNstwC5cYMdN7+HseOJXBoquc+945tXDkPT93M3dTONq+Dxk54EGNUF+W3SZYPhX9sRe2YFgS7T2JRMGx1/vs6KsQpxxnrIc71S4mLg81AgMBAAECggEAfl8IiAF/quqFaaiTqke78meiZm6/XEJ15vPW68qn4NmYxU2KPu+jWXKVG60ErhSNizXa/1u4vUl9V0O1bzYMiUYPXzxSRH08KaJEOLCLxI/IT0yTjwD4Yd5/iO3I8jXWJI3JiSPEpyT0vcG+0ftl/NWfMBpENdoU2pkXk2E0WSohI7pLTuxbgfCopAKHQt9wU+9pvCDLdMaMekE5+hFpgfym+fcmE9stfvJGPuNwKLBDGOXHUemWJ3WnMfCxfPsat+1JHcehml1f7tJpdxXCETVhRU3URh3nAg01iKOZ0/ebNnlKrYq5d788awIoAWi4d7F6uP2u/otq0QyoqShyQQKBgQD0wF+iKRLK9P0PUA5cqg7UK8GuGt//LLjEIgbfScTptdIWjJfLkgQOp0jEW2t/kn9ylTpZtSRt5IblnrMT4NFq6V5V/cqdSB8xX+BAXL41/z+d4P1CQK4WktNn8fFuvGtF4eHUpf+7qw9AmPJODcUoWODiGLff6RtXlYoKoakYqQKBgQDn+w7+kF/jZG1tzh2td6vWtimB4VrhFkT7xHeDCUX/KJiwAVh0UqFS/XxXo+Q4oUpxWu9LN7yBV+TMmp9IkgKZNkwyjiT1hNnlix7Xk+ONmKR/9gQvtkjaH9lzm3rRGcAIyi8YPQ1grUubb/typJpxn4/S4N6h2+jU9g35ujtdrQKBgQDjnv3R/E0EADBRy2xv9aBw5njsCQaFdPwpPFQT2bGOgZBvdDXAF346eo2MQFGLhZ2N3Qc1YugMY9qpNpzpQc7BlWQsqSmEeQy5iKcwdJBZ+5cYp6Qht7GwQMDoDPUyvX0ustKqR++8g2xd8WB4Awp3aaFL5R0s2siY/fQxywNOcQKBgF5zFoDI0XGowvERGX42Gi26Tx4FXdYFFiMXs70TOn+PzNLkSVpbBjne4RBhtxrjeIa8im8qi0JyQcKYNb/7SrmMpOt0elHIPFs8EFufZ+ePvXIn/T5bzj+Y9hUeuZuHC2vIvfH1cYvqIr1vk4XyxLr8RzeJvLtT6PFEGR6TF3alAoGBAN8BP0QY8hI/F9rf2JotzKzxz4evFLR/K41kaMvMf/NjB9c0W4Pbi74zNyQ6ewB4+eK3HUaU4XEF3PE9IzXYXEmPO+n6Ch7JFuB6gb5WQVvYCyuiyntuzV2lvcAVHjX9OPBdx0xNDEhCNKHAacueI5PSqlEoJwbhgrBUn0f82ho2"
  },
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": "",
    "StrictSignatureVerification": false
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Type": "dht"
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 900,
      "LowWater": 600,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "DisableRelay": false,
    "EnableAutoNATService": false,
    "EnableAutoRelay": false,
    "EnableRelayHop": false
  }

--------------------------------------------------------------
ipfs daemon &    
[1] 11871
[root@master ~]# Initializing daemon...
go-ipfs version: 0.4.22-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.7
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.159.128/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.159.128/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/0.0.0.0/tcp/5001
WebUI: http://0.0.0.0:5001/webui
Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
Daemon is ready

-------------------------------------
ipfs swarm peers
/ip4/192.168.159.129/tcp/4001/ipfs/QmSch2HCAu8JrSsVY43YGryFsAKJCDEQ5AwzNqtTSUrmBT
/ip4/192.168.159.130/tcp/4001/ipfs/QmasZHPr94VdDa4EmtZ9kM6ewsdaTxa6fAj1AqQHp32CLt

http://192.168.159.128:5001/webui
to
http://192.168.159.128:5001/ipfs/QmfQkD8pBSBCBxWEwFSu4XaDVSWK6bjnNuaWZjMyQbyDub/
连接失败

Firefox 无法建立到 192.168.159.128:5001 服务器的连接。

    此站点暂时无法使用或者太过忙碌。请过几分钟后再试。
    如果您无法载入任何网页，请检查您计算机的网络连接状态。
    如果您的计算机或网络受到防火墙或者代理服务器的保护，请确认 Firefox 已被授权访问网络。

Unable to connect http://ip:5001/webui
my firewall is stop，selinux is disable

**Comment by SirBlues** [comment]
wget http://192.168.159.128:5001/webui
--2020-01-14 11:12:23--  http://192.168.159.128:5001/webui
Connecting to 192.168.159.128:5001... failed: Connection refused.

**Comment by SirBlues** [comment]
wget http://192.168.159.128:5001/ipfs/QmfQkD8pBSBCBxWEwFSu4XaDVSWK6bjnNuaWZjMyQbyDub/
--2020-01-14 11:33:11--  http://192.168.159.128:5001/ipfs/QmfQkD8pBSBCBxWEwFSu4XaDVSWK6bjnNuaWZjMyQbyDub/
Connecting to 192.168.159.128:5001... connected.
HTTP request sent, awaiting response...

**Comment by seveirbian** [comment]
Have you resolve this? I have the same problem.

**Comment by seveirbian** [comment]
May be it is because this peer has no bootstrap peers, so it can not download the webui file.

**Comment by Stebalien** [comment]
Please ask support questions on [discuss.ipfs.io](https://discuss.ipfs.io).
