### ISSUE TITLE
Connection/event plugin type

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6827]
We need a plugin type that can respond to (libp2p) events (disconnect, connect, etc.).

**Comment by Stebalien** [comment]
We can use this to create a plugin that collects network stats.

**Comment by Stebalien** [comment]
Good point.

* The plugin types are defined in `plugin/`.
* Existing plugins can be found in `plugin/plugins/`.
* The plugin loader lives in `plugin/loader/loader.go`. You'll probably need to modify the `Start` function to hook into the appropriate libp2p events. For now, that'll just be the connect/disconnect events.

Technically, we don't even need a new plugin type: we can just use the internal plugin type. However, a new event plugin type would still be a nice addition.

The plugin itself will likely implement two interfaces:

1. A new "EventPlugin" interface for accepting events. There are several possible designs here ranging from the "notifiee" design originally used by libp2p to the more recently introduced event bus design. Anyone implementing this feature should familiarize themselves with both designs.
2. The standard `Plugin` interface. The plugin will be passed an environment on "Init" containing a `Config`. This config is loaded from "Plugins.Plugins.plugin-name in the ipfs config and can be used to, e.g., configure where the events are written (e.g., to a socket, http endpoint, etc.).

**Comment by dokterbob** [comment]
This would be of great help for us at ipfs-search.com - we'd love to be able to index IPNS - but it seems there is currently no infrastructure to get that data out. Hence, it would be great if that (perhaps) could be included as events.

**Comment by Stebalien** [comment]
@dokterbob there's now an "internal" plugin (disabled by default) in master that logs peer IDs using zap. You can build with it enabled by running `make build IPFS_PLUGINS=peerlog`.

Once we completely switch over to zap, it _should_ be possible to turn on specific logging sub-systems and, e.g., log dht queries (which should get you content & ipns requests).
