### ISSUE TITLE
cannot use the api via a unix domain socket

### ISSUE THREAD

**Issue by jmgurney** [ipfs/go-ipfs#6853]
#### Version information:
```
$ipfs-go version --all
go-ipfs version: 0.4.21-
Repo version: 7
System version: amd64/freebsd
Golang version: go1.13.5
```

#### Description:

When trying to access the daemon over a unix domain socket, the client fails badly:
```
$echo a random string | ipfs-go --api=/unix/var/db/ipfs-go/socket/api.sock add -
Error: Post http:///var/db/ipfs-go/socket/api.sock/api/v0/add?chunker=size-262144&encoding=json&hash=sha2-256&inline-limit=32&pin=true&progress=true&stream-channels=true: http: no Host in request URL
```

The socket does exist and is accessible:
```
$ls -l /var/db/ipfs-go/socket/api.sock
srwxrwxrwx  1 883  883  0 Jan 30 00:53 /var/db/ipfs-go/socket/api.sock=
```

And the daemon is running and properly configured w/ the following lines (rest of config is standard server config):
```
    "API": [ "/ip4/127.0.0.1/tcp/5001", "/unix/var/db/ipfs-go/socket/api.sock" ],
```
I'd expect that the above command to work properly and w/o issue.

**Comment by hsanjuan** [comment]
Without checking anything else, your ipfs version is `0.4.21` and we just released `0.4.23`. I am not sure when API-unix-socket support was added, but I would say it was after 0.4.21 (https://github.com/ipfs/go-ipfs/commit/460c2119e4ccbe0d08e64a04be4445c78a72c851). It may be that this is only available on master. Mind testing with master and 0.4.23 and reporting back?

**Comment by Stebalien** [comment]
It's only available in the latest master.

**Comment by jmgurney** [comment]
Confirmed that it works on 0.5.0-dev.
