### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference handler.go:93

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#6860]
#### Version information:
go-ipfs version: 0.4.23-6ce9a355f
Repo version: 7
System version: amd64/linux
Golang version: go1.13.7

running cluster 0.12.1
#### Description:

Launching ipfs after update to 0.4.23, I get this panic basically every few seconds while running all kinds of cluster/ipfs commands. It stopped after a while.

The integrity of the files should be good, had no crashes or reboots since I've installed ipfs (originally 0.4.22) and the files are stored on a ZFS filesystem which shows no consistency errors.

While I cannot reproduce it yet, I'll let you know when I can.

[ipfs.log](https://github.com/ipfs/go-ipfs/files/4141396/ipfs.log)

Might be tied to this output on the console, or completely independent:

https://github.com/ipfs/go-ipfs/issues/6859

**Comment by Stebalien** [comment]
Fix in https://github.com/ipfs/go-unixfs/pull/81.

**Comment by RubenKelevra** [comment]
Wow, that was fast! Thanks for the work! :)

**Comment by Stebalien** [comment]
I'll let dependabot bubble it.
