### ISSUE TITLE
Deadlock in GC

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-ipfs#6885]
#### Version information:
go-ipfs version: 0.4.23-
Repo version: 7
System version: amd64/linux
Golang version: go1.13.7

#### Description:
This is a bug that has been showing up for a while (at least since 0.4.22 maybe longer) in Peergos but I haven't been able to track it down until now. I seem to have a situation where a call to repo.gc and a concurrent call to pin.update both over the http api cause the ipfs instance to hang. I don't have a reliable repro, this is based on a thread dump from peergos when we hit it. I've managed to get a goroutine dump of ipfs hitting this which is here: [ipfs goroutine dump](https://alpha.peergos.net/#%7B%22secretLink%22:true%2c%22link%22:%22#6MDZhRRPT4ugkJuUfceM6bPnpQKEj5dB2NqLxD1RxFn3oA3CusXayN8RReauEh/6MDZhRRPT4ugkJuUfcRzRbPpFimcBNJx2N9TJDnL4W3ETYhwdsWdvgCkXkwipF/FXzuyr6hqrL4mYt3Afp8vKaG8uSRNRQDp6P8Doz7fV8N/5Pf7SvG7hkFZnqRgp89HefFbFpRim2Sj4iMA9tinrPwGcrwEDcF%22%7D)

I might be wrong, but I think there is a deadlock involving the pin update handler and the gc handler. 

> goroutine 18167701 [semacquire, 2586 minutes]:
> sync.runtime_SemacquireMutex(0xc00033a188, 0x97e100, 0x0)
> 	/usr/lib/go/src/runtime/sema.go:71 +0x47
>  sync.(*RWMutex).Lock(0xc00033a180)
>  	/usr/lib/go/src/sync/rwmutex.go:103 +0x88
>  github.com/ipfs/go-ipfs-blockstore.(*gclocker).GCLock(0xc00033a180, 0xc004059e80, 0xc004059e80)
> 	pkg/mod/github.com/ipfs/go-ipfs-blockstore@v0.0.1/blockstore.go:272 +0x39

and 

> goroutine 20678918 [semacquire, 2546 minutes]:
>  sync.runtime_SemacquireMutex(0xc00033a18c, 0xc01702fa00, 0x0)
>  	/usr/lib/go/src/runtime/sema.go:71 +0x47
>  sync.(*RWMutex).RLock(...)
>  	/usr/lib/go/src/sync/rwmutex.go:50
>  github.com/ipfs/go-ipfs-blockstore.(*gclocker).PinLock(0xc00033a180, 0x0, 0xc01702faca)
>  	pkg/mod/github.com/ipfs/go-ipfs-blockstore@v0.0.1/blockstore.go:278 +0xe6

**Comment by ianopolous** [comment]
Having read some of the go code and docs on go locks I believe the problem is taking both a Rlock and lock on the same thing here:
https://github.com/ipfs/go-ipfs-blockstore/blob/master/blockstore.go#L267
and
https://github.com/ipfs/go-ipfs-blockstore/blob/master/blockstore.go#L273

**Comment by ianopolous** [comment]
Actually, using locks on our side to exclude concurrent gc and pinupdate calls I've managed to reproduce the hang with just a pin.update call. So it's probably just that the gc lock is waiting for the pin update to return, and the pin update has hung in both cases.

**Comment by ianopolous** [comment]
With more investigation I think it might be as simple as a pin update where the new hash is not present (it's just been GC'd). What is the behaviour in that case? Ideally the pin update would error immediately if the new hash (or any merkle descendent isn't in the blockstore).

**Comment by Stebalien** [comment]
So, we _will_ block the GC while the pin is in progress. However, we shouldn't block everything else while the pin update is in progress. It turns out we were holding the _pin_, not just the gc, lock.

Could you test https://github.com/ipfs/go-ipfs-pinner/pull/2? If you're using go-ipfs 0.4.23 and can't test with master, you'll have to make that change to `Update` in `pin/pin.go`.

**Comment by ianopolous** [comment]
I think we were calling GC (after a timeout) before the pin update call and thus the new pin target is deleted before the pin update call, which then I think hangs forever holding the lock because the target is gone. So this change would mean that other valid pin updates and GC could progress, but the original one with the missing target will still hang, just not holding any locks?

**Comment by ianopolous** [comment]
The real solution to stopping us needing to coordinate calls to gc with pin.update is https://github.com/ipfs/notes/issues/106

**Comment by ianopolous** [comment]
I've made that change locally to v0.4.23 and verified it removes our global hang. We can add a timeout on our side in the meantime to fix the caller hanging. Thanks @Stebalien !
