### ISSUE TITLE
IPFS private network setup not works

### ISSUE THREAD

**Issue by khanhphungntu** [ipfs/go-ipfs#6890]
I am trying to create a private network of IPFS with two nodes. Each node is an EC2 instance running on AWS. I generated swarm key and configure my node as follow:

"API": "/ip4/0.0.0.0/tcp/5001",
"Announce": [],
"Gateway": "/ip4/0.0.0.0/tcp/8080",
"NoAnnounce": [],
"Swarm": [
  "/ip4/0.0.0.0/tcp/4001",
  "/ip6/::/tcp/4001"
]
"Bootstrap": [ "/ip4/172.31.25.195/tcp/4001/ipfs/QmaRpyg48RqdUwXVD84RSAd8hFvA2MNPvu3Z7yTxRFJKub" ]

Then I run "ipfs daemon" to start all nodes and "ipfs swarm peers" to list all connected peers. However, "ipfs swarm peers" doest list anything and I dont know what is the problem?

**Comment by Stebalien** [comment]
Hm. This sounds like a misconfiguration or a firewall issue. Please ask on discuss.ipfs.io. We can re-open this issue if it turns out to be a bug.
