### ISSUE TITLE
Disabling HAMT sharing for directories leads to nil pointer dereference

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#6894]
#### Version information:
go-ipfs version: 0.4.23-6ce9a355f
Repo version: 7
System version: amd64/linux
Golang version: go1.13.7

#### Description:
I've disabled HAMT sharding for directories on a node that had it previously activated. This results in trouble reading the repo.

***Expected behavior***

Detect that there's HAMT data and read them anyway, but do not create new HAMT sharded directories

***Log***

[crash_hamt.log](https://github.com/ipfs/go-ipfs/files/4191212/crash_hamt.log)

**Comment by Stebalien** [comment]
Those crashes are actually from trying to _write_ to a HAMT directory. When sharding is disabled, we won't create new sharded directories but we'll still modify existing ones when requested through MFS.

This is #6860.
