### ISSUE TITLE
Version management (SemVer or similar)

### ISSUE THREAD

**Issue by travisperson** [ipfs/go-ipfs#691]
I didn't see an issue files for this, but also saw a lot of discussion recently. I just had a few comments I wanted to put down in an easier to find location than irc logs.

The idea of having the git short hash as part of the version came up but I also think that each pull request should always update the version information, in which ever regard is required (major, minor, patch).

**Comment by jbenet** [comment]
> each pull request should always update the version information

editing the same place in code would create a ton of merge conflict friction. :-1: Maybe we can write a go-semver thing that does: https://github.com/jbenet/random-ideas/issues/22

**Comment by travisperson** [comment]
The author of the pull request doesn't do the versioning. When it's merged you update the version.

**Comment by jbenet** [comment]
then we either cant merge PRs from github-- or have to step into the codebase to change it between every PR, adding a commit. either case, every commit won't carry a version change (multi commit PRs). it's also a manual step likely to be cumbersome and missed by maintainers. I think in general the version number should be automated, or driven by an explicit publish/release step -- git tags, or package managers?

**Comment by dylanPowers** [comment]
I'd also like to add that having release notes would be nice to have with each version release. It could be something as simple as listing the issues that were closed

**Comment by whyrusleeping** [comment]
Agreed. I'll start doing release notes when we bump versions

**Comment by whyrusleeping** [comment]
this is a thing. we do version releases and changelogs
