### ISSUE TITLE
Received interrupt signal, shutting down...

### ISSUE THREAD

**Issue by dominic-healid** [ipfs/go-ipfs#6911]
The daemon just stops after a few hours inactivity, it doesn't give any error message just the `Received interrupt signal, shutting down...`

Is there someone that can point me to a possible cause of this issue?

Thanks

**Comment by Stebalien** [comment]
@peterQiu this sounds like a support question. Please ask on discuss.ipfs.io.

you should also upgrade to the latest version, 0.4.23. Quite a few bugs have been fixed since 0.4.19.

**Comment by callname001** [comment]
I have also encountered the same problem.
Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)

**Comment by Stebalien** [comment]
Something is telling the IPFS daemon to shut down. If you'd like more help on this issue, I suggest asking on https://discuss.ipfs.io.
