### ISSUE TITLE
Responsible Disclosure - Expired PGP Key - Please provide a new one!

### ISSUE THREAD

**Issue by amarsalekIAIK** [ipfs/go-ipfs#6924]
Your published PGP key [1] is expired, meaning it is not easily possible to report security issues privately. Please publish a new key! 

[1] https://github.com/ipfs/go-ipfs/blob/master/README.md#security-issues

**Comment by willscott** [comment]
There are very few security issues which reach a level where a direct email to the `security@ipfs.io` point of contact will be insufficient. If you believe this applies in this situation, email the security point of contact to request a private channel to disclose over.

**Comment by Stebalien** [comment]
Duplicate of https://github.com/ipfs/go-ipfs/issues/6897#issuecomment-585295843.

(but yeah, we need to fix this)

**Comment by JesusMcCloud** [comment]
> There are very few security issues which reach a level where a direct email to the `security@ipfs.io` point of contact will be insufficient. If you believe this applies in this situation, email the security point of contact to request a private channel to disclose over.

We have done that and we have yet to receive a response.
