### ISSUE TITLE
adding swarm filters to default profile

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#6925]
Currently, the server profile got a swarm filter for private subnetworks (IPv4/6).

A not so strict swarm filter should be part of the standard profile as well, allowing for connections based on mDNS-discoveries.

Usual home users just use mDNS, so connecting to announced private IPs doesn't make much sense for them and just waste CPU time/system resources and maybe even conntracking space in the home-router.

**Comment by Stebalien** [comment]
Duplicate?

**Comment by RubenKelevra** [comment]
> Duplicate?

Nope, https://github.com/ipfs/go-ipfs/issues/6926 was about what it's going to be announced to the network.

This one is about what a default client is going to connect to.

I think we should just add all the swarm filters which are already part of the server profile.

Just make sure that nodes detected via mDNS are still allowed to be connected.

---

If someone is currently announcing like 10.10.2.2 my client would try to connect to this IP address which has no usecase.

If someone really wants to connect clients in different private IP ranges he/she would probably use the bootstrap function and don't rely on announces to thru the internet.

**Comment by RubenKelevra** [comment]
@Stebalien please reopen :)

**Comment by Stebalien** [comment]
Got it. This is part of https://github.com/libp2p/go-libp2p/issues/436 as well.
