### ISSUE TITLE
Don't hang on start when we can't find the MFS root

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6935]
#### Version information:

v0.4.23

#### Description:

Currently, if we can't find the MFS root block, we hang on start trying to find it (possibly before the network is ready?).

1. We shouldn't block startup on this.
2. We should set a short timeout and log _loudly_.

**Comment by aschmahmann** [comment]
More info in https://github.com/ipfs/go-ipfs/issues/7183

**Comment by schomatis** [comment]
Closing in favor of the linked issue (adding the OP info there).
