### ISSUE TITLE
Ignore `--raw-leaves` when data fits in one block

### ISSUE THREAD

**Issue by achingbrain** [ipfs/go-ipfs#6940]
Following on from https://github.com/ipfs/js-ipfs-unixfs-importer/issues/44#issuecomment-573745942

If we are importing a file, the returned CID should resolve to a DAG that represents a UnixFS entry.  That entry should allow for metadata such as modes, mtimes, etc.

If the `--raw-leaves` flag has been set, and the data fits in one block, the `--raw-leaves` flag should be ignored and the data inlined* into the root `dag-pb` node.

Current behaviour is to return a CID that resolves to a raw node, eg a buffer - this cannot have metadata set on it.

js-IPFS has implemented the change to [only output UnixFS things](https://github.com/ipfs/js-ipfs-unixfs-importer/pull/49) from an import, this issue is to track the go-IPFS version.

cc: @Stebalien @hsanjuan 

----

\* = js-ipfs-unixfs-importer has a `reduceSingleLeafToSelf` option which allows the user to control whether or not to inline the file data into the root `dag-pb` node, it's not currently exposed by the `ipfs.add` command though doing that might be something to entertain.  Maybe with a shorter name..

**Comment by Stebalien** [comment]
This change was never agreed on. Raw leaves are still _valid_ files, they just can't carry metadata. If there's no metadata, there's no reason not to save some space and use a raw leaf.

**Comment by achingbrain** [comment]
Ah, I think I misread your comment then.

> For now, I'd ignore raw leaves when we have metadata and everything fits into a single file.

I guess the distinction is to only do this when we have metadata, not all the time.

**Comment by Stebalien** [comment]
Yeah, I know it's _just_ a few bytes, but I'd like to be as efficient as possible.

(and, as usual, I'd like to avoid changing hashes unless we have a pressing reason to do so)

**Comment by achingbrain** [comment]
Ok, this can probably be closed then as the work will be done as part of https://github.com/ipfs/go-ipfs/issues/6920 which will need to pass the interface and interop tests to be considered done, which include tests for this case so it won't be missed.
