### ISSUE TITLE
URLstore detection isn't reliably used when using "--chunker" option

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#6945]
#### Version information:
go-ipfs version: 0.4.23-6ce9a355f
Repo version: 7
System version: amd64/linux
Golang version: go1.13.7

#### Description:
URLstore is not always correctly used when using different options:

```
$  ipfs add --nocopy --raw-leaves --chunker=size-1048576 -t https://mirrors.edge.kernel.org/archlinux/iso/2020.03.01/archlinux-2020.03.01-x86_64.iso.sig
 310 B / 310 B [==========================================================================================================================================================] 100.00%
Error: urlstore is not enabled
$  ipfs add --nocopy --raw-leaves --chunker=size-1048576 -t https://archive.archlinux.org/repos/2020/02/04/core/os/x86_64/archlinux-keyring-20200108-1-any.pkg.tar.zst
added QmagMqLXXzYeozK4eskF5vpoDK6HCRCCbNPHiVkpthiWZ9 archlinux-keyring-20200108-1-any.pkg.tar.zst
 868.27 KiB / 868.27 KiB [================================================================================================================================================] 100.00%
$ ipfs add --nocopy --chunker=size-1048576 -t https://archive.archlinux.org/repos/2020/02/04/core/os/x86_64/archlinux-keyring-20200108-1-any.pkg.tar.zst
added QmagMqLXXzYeozK4eskF5vpoDK6HCRCCbNPHiVkpthiWZ9 archlinux-keyring-20200108-1-any.pkg.tar.zst
 868.27 KiB / 868.27 KiB [================================================================================================================================================] 100.00%
$ ipfs add --nocopy --chunker=size-1048576 https://archive.archlinux.org/repos/2020/02/04/core/os/x86_64/archlinux-keyring-20200108-1-any.pkg.tar.zst
added bafkreiascrsj7t3ostado3juq4cnk56epjrsrejpdyrxk3ornpd7pu4spa archlinux-keyring-20200108-1-any.pkg.tar.zst
 868.27 KiB / 868.27 KiB [================================================================================================================================================] 100.00%
$ ipfs add --nocopy https://archive.archlinux.org/repos/2020/02/04/core/os/x86_64/archlinux-keyring-20200108-1-any.pkg.tar.zst
 868.27 KiB / 868.27 KiB [================================================================================================================================================] 100.00%
Error: urlstore is not enabled
```

I guess the file is stored locally when it fits in the first chunk, maybe a off-by-one error?

**Comment by alanshaw** [comment]
Notes from my testing:

* Verified in go-ipfs 0.4.23, running as a daemon or not
* The inconsistency does not seem related to options passed to add, it only happens for me with URLs I've _previously added successfully with `Experimental.UrlstoreEnabled` set to `true`_
    * So to replicate, enable urlstore, add a few URLs, then disable urlstore and try to add those same URLs - on some of them you'll get the "Error: urlstore is not enabled" but others you will not.
    * The reason I say it doesn't seem related to the options passed to add is because my error message appearing/not appearing is inconsistent with the output above

**Comment by RubenKelevra** [comment]
> * So to replicate, enable urlstore, add a few URLs, then disable urlstore and try to add those same URLs - on some of them you'll get the "Error: urlstore is not enabled" but others you will not.

On my node URL-store wasn't enabled in the past and I just tested around with adding some URLs. First I thought URL-store was enabled, since there was no error message, then I tried adding a different larger file and then the error message appeared.

Not sure what's going on.

**Comment by hsanjuan** [comment]
This must be related to blocks which were already available.

When you are adding, if the file was added before, the blockstore wrapper skips writing blocks since they are already there available locally, therefore the operations seem to succeed when using a URL but the url store is not getting hit at all and therefore does not fail even when disabled.

While weird, I think things are probably working as expected, particularly for experimental features.

**Comment by RubenKelevra** [comment]
Alright :)
