### ISSUE TITLE
DNSLink Chaining

### ISSUE THREAD

**Issue by nick** [ipfs/go-ipfs#6959]
The DNSLink [documentation](https://dnslink.io/#dnslink-chaining) states the following:

> Tools should support DNSLink chaining and detect loops as errors.
> 
>     > dig +short TXT _dnslink.test3.dnslink.dev
>     dnslink=/dnslink/test4.dnslink.dev
> 
> Should go on to resolve
> 
>     > dig +short TXT _dnslink.test4.dnslink.dev
>     dnslink=/ipfs/Qmc2o4ZNtbinEmRF9UGouBYTuiHbtCSShMFRbBY5ZiZDmU

However, it seems this functionality is unsupported in go-ipfs?

**Comment by hsanjuan** [comment]
hey @nick, can you specify where the problem is and how to reproduce it?

I see https://github.com/ipfs/go-ipfs/pull/6087/files so recursive resolving should be supported with `ipfs resolve -r`.

**Comment by Stebalien** [comment]
Note: IPFS currently uses `/ipns/...` for DNSLink, not `/dnslink` (for historical reasons). Is that the issue?

**Comment by nick** [comment]
Aha! Using `/ipns` instead of `/dnslink` did the trick. Thanks!
