### ISSUE TITLE
Enable the Noise security transport by default

### ISSUE THREAD

**Issue by jacobheun** [ipfs/go-ipfs#6991]
Once the [go-libp2p-noise](https://github.com/libp2p/go-libp2p-noise) security transport is finished we should add and enable it.

## Rollout Strategy
The current plan for rollout, in conjunction with the other security transports is as follows:

**In go-ipfs 0.5.0:**
TLS > SECIO _(TLS with fallback support to SECIO)_

**In go-ipfs 0.6.0:**
TLS > Noise > SECIO _(TLS with fallback support to Noise and then SECIO)_

**In go-ipfs 0.7.0:**
TLS > Noise _(depending on performance of TLS/Noise, these may be swapped)_

## Success Criteria
- IPFS nodes can encrypt traffic over the Noise security transport
- Fallback support is enabled for the SECIO security transport to support backwards compatibility and interop with other implementations (js-ipfs)

**Comment by bonedaddy** [comment]
Why is fallback SECIO and not TLS? Seems like a poor choice of fallback protocols given that SECIO falls under the "dont roll your own crypto"

**Comment by Stebalien** [comment]
In go-ipfs 0.5.0:

* TLS > SECIO

In go-ipfs 0.6.0:

* TLS > Noise > SECIO

In go-ipfs 0.7.0:

* TLS > Noise (depending on performance of TLS/Noise, these may be swapped).

Or, at least, that's the current plan.
