### ISSUE TITLE
Arch Linux User Package

### ISSUE THREAD

**Issue by ianonavy** [ipfs/go-ipfs#7]
Hi,

I've created a package for the Arch User Repository. If you'd like, I can fork and write some instructions on the README. It is available here: https://aur.archlinux.org/packages/go-ipfs-git/

The package `git clone`s from this exact repo and `go get`s the dependencies as per the README file. I hope this helps users try out IPFS more easily.

    wget https://aur.archlinux.org/packages/go/go-ipfs-git/go-ipfs-git.tar.gz
    tar -xvf go-ipfs-git.tar.gz
    cd go-ipfs-git
    makepkg -i

**Comment by edrex** [comment]
The package should probably include an `ipfs.service` file. It might also make sense to create a dedicated `ipfs` system user to run the service as (that's how I have it setup). It seems like there's no benefit to running per-user ipfs nodes, if you have root access, but if that was wanted a secondary `ipfs@.service` could be included. Also an `ipfs.socket` could be included, to support socket activation.

**Comment by jbenet** [comment]
@ianonavy  ipfs is useful now!

**Comment by ianonavy** [comment]
@jbenet It appears I orphaned the AUR package and [Freso](https://aur.archlinux.org/account/Freso) has picked it up. Glad to hear this project is still going strong. :)

**Comment by jbenet** [comment]
@ianonavy thanks :) -- do you know Freso's account on github?

**Comment by ianonavy** [comment]
https://github.com/freso

**Comment by anatol** [comment]
FYI: `go-ipfs` package has been promoted to the official Arch repository. It will make ipfs usage at Linux Arch even more easier and pleasant.

I have the same question as @edrex. ipfs should be really a system service with blocks stored under `/var/`. But it looks like `ipfs` client expects to see config files under ~/.ipfs/. Is there a way to tell  client the new location for configs/block/logs files?

**Comment by lgierth** [comment]
> Is there a way to tell client the new location for configs/block/logs files?

Yes: #1872

**Comment by edrex** [comment]
This can be closed. btw, the official package includes a Systemd user unit, which can be set to start when the user logs in.

**Comment by Freso** [comment]
Yeah, there's an official package in Arch Linux's community repository: https://www.archlinux.org/packages/community/x86_64/go-ipfs/ - and I will still be maintaining the -git package at https://aur.archlinux.org/packages/go-ipfs-git as well. (And yes, I'm @Freso here on GitHub. ;))

**Comment by jbenet** [comment]
@Freso @ianonavy @anatol @edrex this is all great to hear!! Thanks very much for shipping this.

**Comment by diasdavid** [comment]
Sweet! Thank you for making it! Let's make sure to add a reference to this package on the [distributions page](https://github.com/ipfs/distributions) //cc @Dignifiedquire . 

Closing this issue :)
