### ISSUE TITLE
Update go-ds-s3 plugin for 0.5 release

### ISSUE THREAD

**Issue by momack2** [ipfs/go-ipfs#7001]
Update go-ds-s3 plugin to work with go-ipfs 0.5 RC: https://github.com/ipfs/go-ipfs/issues/6776

(A lot of ecosystem collabs use the S3 plugin and will need it to be updated for testing and validating the 0.5 RC!)

**Comment by MichaelMure** [comment]
This is done for the -rc1.

**Comment by georgyo** [comment]
This ticket should be closed.
