### ISSUE TITLE
The pinning subsystem accepts and processes identity CIDs

### ISSUE THREAD

**Issue by ribasushi** [ipfs/go-ipfs#7034]
#### Version information:
`ipfs version 0.5.0-dev`
Local build of https://github.com/ipfs/go-ipfs/commit/39b9c3a32b9bcc682

As per subject:

```
admin:~/devel/go-ipfs$ echo -n | cmd/ipfs/ipfs add --cid-version=1 --inline -q 
bafkqaaa
```
```
admin:~/devel/go-ipfs$ cmd/ipfs/ipfs pin add bafkqaaa
pinned bafkqaaa recursively
```
```
admin:~/devel/go-ipfs$ cmd/ipfs/ipfs pin ls
bafkqaaa recursive
```

Is this intentional or something that needs fixing? @Stebalien @hsanjuan

**Comment by Stebalien** [comment]
I think this is the least bad thing to do.

1. We don't want to randomly fail to pin some CIDs.
2. An identity CID could link to other content. We definitely want that to work.

**Comment by ribasushi** [comment]
Of course... I overfocused on the case of leaf inlined CIDs, but of course an inliner may very well be a dag-cbor or something that holds links, which would recurse and would make sense to pin.

We could argue that raw-encoding ( `\x55` ) is guaranteed to be a leaf, and should silently noop on pinning, but that's a bit of broken symmetry for no gain.

I will close the issue tomorrow as "works as intended" unless more thoughts crop up.
