### ISSUE TITLE
IPFS hungs up in a busy loop (no announce filter all IPs)

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7049]
#### Version information:
0.5.0-dev-84724a360

I got a client which only have private IPs (not worth announcing), so I filter them out (with no announce).

I noticed that IPFS also announces `::1` and `127.0.0.1`. When those are also added to the NoAnnounce filter, IPFS ends up with no IPs left to announce on startup.

While this should normally not impact network operations to find a proper relay (because of NAT), IPFS ends up in a busy loop complaining about the missing IP addresses.

**Comment by Stebalien** [comment]
Exact log messages?

**Comment by Stebalien** [comment]
Note: If you're not planning on accepting inbound connections, set the listen addresses to an empty list instead of setting `NoAnnounce`. However, I can't reproduce this either way.

**Comment by Stebalien** [comment]
I am seeing https://github.com/libp2p/go-libp2p-swarm/pull/185, but that shouldn't create a busy loop.

**Comment by RubenKelevra** [comment]
It's quite racy, but when you give it enough time, the daemon ends up in a busy loop with these messages last in log:

```
Mär 30 18:38:23 i3 ipfs[936487]: 2020-03-30T18:38:23.093+0200        WARN        pubsub        go-log@v1.0.3/log.go:180        bootstrap: error providing rendezvous for /record/L2lwbnMvEiCZqCEy82lEXS2773MpDH7LzEoW5P7Dm5YfEdLQapqKpQ: no known addresses for self. cannot put provider.
Mär 30 18:38:23 i3 ipfs[936487]: 2020-03-30T18:38:23.093+0200        DEBUG        dht        go-libp2p-kad-dht@v0.5.2/lookup.go:114        closestPeers query run error: context canceled
Mär 30 18:38:23 i3 ipfs[936487]: 2020-03-30T18:38:23.093+0200        WARN        pubsub        go-log@v1.0.3/log.go:180        bootstrap: error providing rendezvous for /record/L2lwbnMvEiCZqCEy82lEXS2773MpDH7LzEoW5P7Dm5YfEdLQapqKpQ: no known addresses for self. cannot put provider.
Mär 30 18:38:23 i3 ipfs[936487]: 2020-03-30T18:38:23.093+0200        DEBUG        dht        go-libp2p-kad-dht@v0.5.2/lookup.go:114        closestPeers query run error: context canceled
Mär 30 18:38:23 i3 ipfs[936487]: 2020-03-30T18:38:23.093+0200        WARN        pubsub        go-log@v1.0.3/log.go:180        bootstrap: error providing rendezvous for /record/L2lwbnMvEiCZqCEy82lEXS2773MpDH7LzEoW5P7Dm5YfEdLQapqKpQ: no known addresses for self. cannot put provider.
Mär 30 18:38:23 i3 ipfs[936487]: 2020-03-30T18:38:23.093+0200        DEBUG        dht        go-libp2p-kad-dht@v0.5.2/lookup.go:114        closestPeers query run error: context canceled
Mär 30 18:38:23 i3 ipfs[936487]: 2020-03-30T18:38:23.093+0200        WARN        pubsub        go-log@v1.0.3/log.go:180        bootstrap: error providing rendezvous for /record/L2lwbnMvEiCZqCEy82lEXS2773MpDH7LzEoW5P7Dm5YfEdLQapqKpQ: no known addresses for self. cannot put provider.
Mär 30 18:38:23 i3 ipfs[936487]: 2020-03-30T18:38:23.093+0200        DEBUG        dht        go-libp2p-kad-dht@v0.5.2/lookup.go:114        closestPeers query run error: context canceled
Mär 30 18:38:23 i3 ipfs[936487]: 2020-03-30T18:38:23.093+0200        WARN        pubsub        go-log@v1.0.3/log.go:180        bootstrap: error providing rendezvous for /record/L2lwbnMvEiCZqCEy82lEXS2773MpDH7LzEoW5P7Dm5YfEdLQapqKpQ: no known addresses for self. cannot put provider.
```

[ipfs_log_2020-03-30-#7049.txt.gz](https://github.com/ipfs/go-ipfs/files/4404604/ipfs_log_2020-03-30-.7049.txt.gz)

**Comment by RubenKelevra** [comment]
I'm now running 

```
go-ipfs version: 0.5.0-dev-bf8db8708
Repo version: 9
System version: amd64/linux
Golang version: go1.14.1
```

It's more stable, but I had one hung up at the same time when my wifi got disconnected - might be the trigger or just coincidence.

[ipfs_log_2020-04-02-#7049.txt](https://github.com/ipfs/go-ipfs/files/4418627/ipfs_log_2020-04-02-.7049.txt)

**Comment by RubenKelevra** [comment]
I'm now running 

```
go-ipfs version: 0.5.0-dev-bf8db8708
Repo version: 9
System version: amd64/linux
Golang version: go1.14.1
```

It's more stable, but I had one hung up at the same time when my wifi got disconnected - might be the trigger or just coincidence.

[ipfs_log_2020-04-02-#7049.txt](https://github.com/ipfs/go-ipfs/files/4418627/ipfs_log_2020-04-02-.7049.txt)

**Comment by Stebalien** [comment]
Ah... I see the problem. https://github.com/libp2p/go-libp2p-pubsub/pull/278
