### ISSUE TITLE
It is very inefficient for IPFs to find content through broadcasting, when there are massive content and massive nodes in the network. Addressing will take a long time.

### ISSUE THREAD

**Issue by zoujunrong** [ipfs/go-ipfs#7060]
DO NOT ASK QUESTIONS HERE

This bug tracker is only for actionable bug reports and feature requests. Please direct any questions to https://discuss.ipfs.io or to our Matrix (#ipfs:matrix.org) or IRC (#ipfs on freenode) channels.

If you don't get an immediate response, please keep trying.

**Comment by RubenKelevra** [comment]
I think @zoujunrong answered this ticket for himself. :)
