### ISSUE TITLE
Panic in go-cid after repo migration from 7 to 9

### ISSUE THREAD

**Issue by ridenaio** [ipfs/go-ipfs#7078]
#### Version information:
`github.com/ipfs/go-ipfs v0.4.22-0.20200331193918-bf8db8708551`

#### Description:
After upgrading go-ipfs to the latest commit, we faced with repo migration problem. We've used code from [fs-repo-migrations](https://github.com/ipfs/fs-repo-migrations) repo. Our previous repo version was 7. So we've used 7-8 migration and 8-9 migration, one by one. All migrations have been done without error. 

The problem appears after several minutes from the application start. We suddenly receive panic from `go-cid` package.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa84c51]

goroutine 630 [running]:
github.com/ipfs/go-cid.Cid.Prefix(0xc002b48210, 0x26, 0xc0009f3d80, 0x406e3b, 0xc003edd8c0, 0xc0009f3e48)
	D:/projects/go/pkg/mod/github.com/ipfs/go-cid@v0.0.5/cid.go:492 +0xa1
github.com/ipfs/go-verifcid.ValidateCid(0xc002b48210, 0x26, 0xc0041e0101, 0x0)
	D:/projects/go/pkg/mod/github.com/ipfs/go-verifcid@v0.0.1/validate.go:52 +0x40
github.com/ipfs/go-ipfs-provider/simple.(*Reprovider).Reprovide(0xc000e0b340, 0xc003b0e830, 0x3)
	D:/projects/go/pkg/mod/github.com/ipfs/go-ipfs-provider@v0.4.1/simple/reprovide.go:101 +0xf3
github.com/ipfs/go-ipfs-provider/simple.(*Reprovider).Run(0xc000e0b340)
	D:/projects/go/pkg/mod/github.com/ipfs/go-ipfs-provider@v0.4.1/simple/reprovide.go:78 +0x1d5
created by github.com/ipfs/go-ipfs-provider.(*system).Run
	D:/projects/go/pkg/mod/github.com/ipfs/go-ipfs-provider@v0.4.1/system.go:30 +0x75

Process finished with exit code 2

```

We use Cidv1 in our project. We logged cids, which caused this panic, they look strange, too long. Examples:

`bafkqc4asecpw4j474a3yl5ldusu355w2xegxoxir6jhi3jdksnxfprcplvnns`
`bafkqcviseap2qwlmb6mtgwxs73tcvodoj7k5ea7ke6gql4x4tbsikddusnnnk`

go-multihash `Decode` function returns error `length greater than remaining number of bytes in buffer`

Our usual cids are 3 characters shorter:
`bafkreie52glc3ufyffszcckk4nzd2vlmnwwkak3ynx7wxebudrmworslki`

**Comment by ribasushi** [comment]
These are both legit CIDs. Are you sure they are the ones causing a panic?

https://gchq.github.io/CyberChef/#recipe=From_Base32('a-z2-7%3D',true)To_Hex('Space',0)&input=YWZrcWM0YXNlY3B3NGo0NzRhM3lsNWxkdXN1MzU1dzJ4ZWd4b3hpcjZqaGkzamRrc254ZnByY3Bsdm5ucw

https://gchq.github.io/CyberChef/#recipe=From_Base32('a-z2-7%3D',true)To_Hex('Space',0)&input=YWZrcWN2aXNlYXAycXdsbWI2bXRnd3hzNzN0Y3ZvZG9qN2s1ZWE3a2U2Z3FsNHg0dGJzaWtkZHVzbm5uawo

**Comment by ridenaio** [comment]
Yes, I added in the initial issue text: go-multihash `Decode `function returns error `length greater than remaining number of bytes in buffer`

**Comment by ribasushi** [comment]
@ridenaio reproduced locally, looking more...

**Comment by ribasushi** [comment]
I misread the cyberchef output: the "longer" CIDs have a malformed prefix: `01 55 01 55` twice

@hsanjuan does this ring a bell by chance while I dig?

**Comment by ribasushi** [comment]
@ridenaio are you able to induce the same panic if you `ipfs pin ls` ? If not - do you happen to grep the CIDs in question in the output?

**Comment by hsanjuan** [comment]
The migrations did not touch anything that could cause this (they did not touch the blockstore).

@ridenaio are you running custom builds of go-ipfs (with dependencies on custom versions)?

**Comment by ridenaio** [comment]
@ribasushi I've run 
```
	api, _ := coreapi.NewCoreAPI(node)
	data, _ := api.Pin().Ls(ctx)
```
and everything works fine. These long CIDs from question I've logged as written [here](https://github.com/ipfs/go-ipfs/issues/7078#issuecomment-607859803)


@hsanjuan we use the latest commit from the master. All out packages you can find [here](https://gist.github.com/ridenaio/fdf4ad6477c12e62dcfc4d80df487856)


We found out that for some reason we had these packages as indirect dependencies in our `go.mod` file (and versions were different from go-ipfs `go.mod` file)
```
	github.com/ipfs/go-ds-badger v0.2.3 // indirect
	github.com/ipfs/go-ds-flatfs v0.4.1 // indirect
	github.com/ipfs/go-filestore v1.0.0 // indirect
```
Probably, they were updated to the latest versions after `go get -u` command. 

After removing these dependencies from `go.mod` everything works fine.

**Comment by hsanjuan** [comment]
Filestore was the problem (https://github.com/ipfs/go-filestore/releases click to expand 1.0.0 description).

Please remember to follow steps here: https://github.com/golang/go/wiki/Modules#how-to-upgrade-and-downgrade-dependencies (first `go get` without `-u`). The bare `-u` flag can be very problematic as it will indiscriminately upgrade things.

Whenever I use it, I manually remove `// indirect` dependencies that it adds, but these days we handle most of the dependency maintenance through dependabot.

I'm very glad we found the issue though!
