### ISSUE TITLE
plugin/loader: preloads dgraph-io/badger (v1), which is incompatible with its v2

### ISSUE THREAD

**Issue by mvdan** [ipfs/go-ipfs#7122]
https://github.com/ipfs/go-ipfs/blob/23af25f1767bb38a05cff7a736c339fec00bcf7f/plugin/loader/preload.go#L4 means that go-ipfs forces importing the badger DB module v1, which is unfortunately incompatible at init time with its v2 - it will panic. See https://github.com/dgraph-io/badger/issues/1208.

While I think this is a bug on their part, I also think it's strange that go-ipfs forcibly pulls in v1 of badger. At least it seems to me like it should be configurable. Ideally, it should be pulling in v2 instead, which was first released about six months ago.

Happy to help or bounce ideas if needed. I've also pinged upstream on the issue above, but I think there's something to be done here as well.

**Comment by mvdan** [comment]
I realise there's https://github.com/ipfs/go-ipfs/issues/6818, but that seems like an enhancement, whereas I'd call this more of a bug :)

**Comment by Stebalien** [comment]
Go-ipfs uses badger 1 because we haven't tested badger 2 which we consider to be a _different_ datastore due to the format incompatibilities. We plan on introducing a plugin for badger 2, but haven't yet merged the appropriate patches.

**Comment by mvdan** [comment]
Fair enough, thank you for your time.
