### ISSUE TITLE
Strage sharness failure in CAR tests

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#7123]
> Error: Unknown command `""$("`

https://app.circleci.com/pipelines/github/ipfs/go-ipfs/2385/workflows/312a4b14-636d-4e3a-a327-4cf9ba8db077/jobs/29097

**Comment by ribasushi** [comment]
Spent 2h chasing the wrong problem, the error you see is an incorrect argument pass 🤦 

The timeout however is indicative of another problem, I only managed to get it once locally in a slightly different config. Will finish figuring it out + PR tomorrow

**Comment by Stebalien** [comment]
Another case: https://app.circleci.com/pipelines/github/ipfs/go-ipfs/2441/workflows/4c474b78-9880-48d4-9f2d-cc50329a419b/jobs/29650/artifacts

This is after disabling the GC logic. I'm pretty sure it's the FIFO import.
