### ISSUE TITLE
Config to hide IP

### ISSUE THREAD

**Issue by danrobi11** [ipfs/go-ipfs#7124]
Hello. 
Im a regular non-technical user, so im not too sure how to setup IPFS.
Which config setup should I run in order to not have my IP showing anywhere?
Im reading here under 'Routing.Type' But nothing about IP: https://github.com/ipfs/go-ipfs/blob/master/docs/config.md
Can you plz add under 'Routing.Type' a setup guide in order to not have our IP showing anywhere.
Thx!

**Comment by hsanjuan** [comment]
Hello, I don't mean to be harsh, but this is clearly a (you must have seen this when clicking to open a new issue):

```
Question/Support
DO NOT SELECT THIS OPTION: Ask questions on discuss.ipfs.io, IRC (#ipfs on freenode), or Matrix (#ipfs:matrix.org)
```

So I am closing.

There is no available way to fully hide your IP. If you want to track the effort, subscribe to https://github.com/ipfs/go-ipfs/issues/6430.
