### ISSUE TITLE
ipfs repo gc --quiet  is  not quiet

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#7129]
#### Version information:

0.5.0-rc1 with badgerds and enabled sharding

#### Description:

Calling `ipfs repo gc --quiet` does not seem to do anything, 
`--quiet` still prints every (removed?) CID. 

My expectation would  be to supress all output, or only print summary at the end.

**Comment by Stebalien** [comment]
Yeah, this is very confusing `--quiet` just means "don't print 'removed CID'", just print "CID". Instead of removing this, I'd add a "silent" flag to match `ipfs add`.

**Comment by gargdeepak** [comment]
@Stebalien can I please pick this up if no one else is working on it ?

**Comment by hsanjuan** [comment]
> @Stebalien can I please pick this up if no one else is working on it ?

Go ahead (adding the --silent flag).

**Comment by hsanjuan** [comment]
Ah sorry @gargdeepak , there is a PR already for this (#7147).
