### ISSUE TITLE
How to mount IPFS "file system" on OS X "Catalina" ?

### ISSUE THREAD

**Issue by babonet13** [ipfs/go-ipfs#7144]
Trying to follow these instructions : https://github.com/ipfs/go-ipfs/blob/master/docs/fuse.md
But impossible to create a /ipfs directory on OS X "Catalina"
> Coz root direcory is "Read Only" : https://support.apple.com/en-us/HT210650

So, what is the instruction to mount it in another location than the default "/ipfs" directory ?

**Comment by willscott** [comment]
`-f` and `-n` can be passed to the `ipfs daemon --mount` command to specify alternative directories for `/ipfs` and /ipns` respectively. (the long form of these options are `--ipfs-path` and `--ipns-path`.

try:
```
ipfs daemon --mount --ipfs-path=~/Desktop/ipfs --ipns-path=~/Desktop/ipns
```

**Comment by babonet13** [comment]
Thanks so much Will for your quick and precise answer …

**Comment by babonet13** [comment]
Seems it is now "--mount-ipfs" instead of "--ipfs-path" ...

Trying to mount a sub-directory "ifs" in my User home
ipfs daemon --mount --mount-ipfs=/Users/hubject/ipfs

I got this error 
2020/04/11 23:13:23 mount helper error: mount_osxfuse: /ipns: Read-only file system
23:13:23.592 ERROR       node:  error mounting: mount_osxfusefs: exit status 64 mount_unix.go:95
Error: mount_osxfusefs: exit status 64

What should I check ?

**Comment by willscott** [comment]
you have not specified where to mount ipns, and in this mode ipfs will attempt to mount two different paths. try also specifying `--mount-ipns=/Users/hubject/ipns`

**Comment by babonet13** [comment]
Yep. It works better. Thanks
I can see this is the same Peer ID
![Capture d’écran 2020-04-11 à 23 30 31](https://user-images.githubusercontent.com/20139338/79055352-a2dd6b00-7c4c-11ea-888d-3bd3c653e474.png)


But I do NOT retrieve the files and folders I have in the Desktop App (or in the Firefox Companion Extension) 

![Capture d’écran 2020-04-11 à 23 30 48](https://user-images.githubusercontent.com/20139338/79055365-c6a0b100-7c4c-11ea-9401-91d6dfed4c51.png)

**Comment by willscott** [comment]
that's probably a different issue.
https://discuss.ipfs.io/ is probably the right place to get help 😃  if you comment in this closed issue, very few others will notice to chime in to answer.

**Comment by babonet13** [comment]
OK, I will do that.
Have a nice day !
