### ISSUE TITLE
IPFS returning: "Error: not a valid proquint string" when doing "ipfs name resolve /ipfs/hash"

### ISSUE THREAD

**Issue by obo20** [ipfs/go-ipfs#7149]
Throwing this bug report up at request of @Stebalien.

The error message here is a bug and should be fixed.

**Comment by Stebalien** [comment]
I assumed you tried to visit `ipns://something`? You'll get that error if `something` doesn't parse as a domain with a known TLD, nor valid IPNS key. If you don't mind saying, what URL did you visit?

Also note:

1. Proquint support will be gone from go-ipfs 0.9.0 so this issue (the bad error message) will effectively be fixed.
2. We're loosening the restrictions on what counts as a valid domain (no longer checking a TLD list) (again, in the next release).

Release tracking issue: https://github.com/ipfs/go-ipfs/issues/8058

**Comment by ThomasFreedman** [comment]
I ran into this error on one of my servers. I published a website on another IPFS node and when I tried to pin it on another got this error. Both servers involved are running the same 0.8.0-rc2 version. I will be updating them this weekend.

I've always been puzzled by the CIDs returned on one of my nodes, it doesn't conform to the Qm... 42 character CID format I see everywhere else. The ipns "published to" keys from that node start with k and are very long, and the peerID starts with 12. I'm getting the error on the node with the typical Qm CID structure, but the key it's trying to resolve that produces the error is: /ipns/k51qzi5uqu5dmdr312hi2slkfhc2e4dxbm55inrhdqkr0z8ly51evcyrj8tr1k

**Comment by Winterhuman** [comment]
Checking with https://cid.ipfs.io/#k51qzi5uqu5dmdr312hi2slkfhc2e4dxbm55inrhdqkr0z8ly51evcyrj8tr1k shows that it is a valid IPNS address. Also, it's completely normal that IPNS keys start `k51...` and PeerIDs `12D3KooW...`, this was changed from the version you're currently running.

**Comment by aschmahmann** [comment]
As @Winterhuman correctly mentioned Proquint support has been removed for a while and your error is likely due to you entering an invalid key (e.g. commonly something like a copy-paste error).

Closing this issue since "Error: not a valid proquint string" is no longer in the codebase 😄.
