### ISSUE TITLE
Allow to download blocks of other types as raw block.

### ISSUE THREAD

**Issue by ivan386** [ipfs/go-ipfs#7158]
This allow to download file from gateways by blocks and check it hashes by simple fetch.

Example:
1. Original CID: 
[Qmd3Gk5XmBrywwV5sdg8K24FqwQj6qmUMrin9tTvfaJdEc](https://gateway.ipfs.io/ipfs/Qmd3Gk5XmBrywwV5sdg8K24FqwQj6qmUMrin9tTvfaJdEc) - return file
2. Change to CID Base16 and Version 1: 
[f01 _70_ 1220da6b97d622ca3a8eca04f50438984eaad72c1d3f39a7a4678d8249ba038a68dd](https://gateway.ipfs.io/ipfs/f01701220da6b97d622ca3a8eca04f50438984eaad72c1d3f39a7a4678d8249ba038a68dd) - return file
3. Change Type from ```MerkleDAG protobuf```(0x70) to ```raw binary```(0x55):
[f01 _55_ 1220da6b97d622ca3a8eca04f50438984eaad72c1d3f39a7a4678d8249ba038a68dd](https://gateway.ipfs.io/ipfs/f01551220da6b97d622ca3a8eca04f50438984eaad72c1d3f39a7a4678d8249ba038a68dd) - must return block with that hash

Gateway have block with that hash* but return "504 Gateway Time-out"

*sha2-256-da6b97d622ca3a8eca04f50438984eaad72c1d3f39a7a4678d8249ba038a68dd

**Comment by Stebalien** [comment]
Use the block API on the read-only gateway: `GATEWAY/api/v0/block/get/Qm...`.

**Comment by ivan386** [comment]
@Stebalien api not available on most public gateways. Only ipfs.io and gateway.ipfs.io give access to api. Others return 403, 404, 502 errors.

**Comment by Stebalien** [comment]
We're not going to add a feature specifically to allow abusing the gateway's _file_ endpoint to download raw blocks. If the user has blocked the read-only API and only allows the /ipfs endpoint, that's there decision.

Anyways, this hack will likely "just work" once we address https://github.com/ipfs/specs/issues/242. However, I don't consider this to be a desired _feature_ of the ipfs gateway.
