### ISSUE TITLE
Subdomain redirect doesn't apply to directory listings

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#7164]
#### Version information:

> v0.5.0-rc2

#### Description:

When listing a _directory_ with no index file, the subdomain gateway redirect isn't applied.

> http://localhost:8080/ipns/dist.ipfs.io/go-ipfs

**Comment by lidel** [comment]
Thanks for bringing this to my attention. Will look into this. 
(Good news is that directory listing is generated by go-ipfs, so there is no security concerns, mostly cosmetic one)
