### ISSUE TITLE
A 'Publish Website' option in the control panel

### ISSUE THREAD

**Issue by danrobi11** [ipfs/go-ipfs#7175]
Hello
Im suggesting same sort of 'Publish Website' feature like OnionShare.
In the GO-IPFS control panel drag/drop/add dir/file in the 'Publish Website' section. That creates automatically a persistent address. Done.
Note: enable/disable DHT option would be useful as well
Thanks!

**Comment by hsanjuan** [comment]
Hi, is this supposed to be a webui feature or IPFS Desktop?

**Comment by danrobi11** [comment]
Im running GO-IPFS desktop v0.4.23 when I click on status/file/settings that open a control panel page, thats what im talking about. Sort of the same control panel as the browser extension.

**Comment by hsanjuan** [comment]
Ok, I am trasferring this to IPFS WebUI as probably that's the thing.

**Comment by hsanjuan** [comment]
Hmm, I can't transfer accross organizations... can you post this in https://github.com/ipfs-shipyard/ipfs-webui ?
