### ISSUE TITLE
Can't duplicate dev environment in prod

### ISSUE THREAD

**Issue by LiskLabs** [ipfs/go-ipfs#7184]
#### Version information:

> WIN SRV 2012 R2

ipfs version --all
go-ipfs version: 0.5.0-rc2
Repo version: 9
System version: amd64/windows
Golang `version:` go1.13.8
PowerShell Version  : 5.1.14409.1005

> WIN 10

ipfs version --all
go-ipfs version: 0.5.0-rc2
Repo version: 9
System version: amd64/windows
Golang version: go1.13.8
PowerShell Version  : 5.1.18362.752

```
// command is IPFS cat or add
PowerShell.Create().AddScript(command).Invoke()[0].ToString();
```

On the DEV environment works perfect and returns. On SRV 2012 I get an empty string.

**Comment by hsanjuan** [comment]
Hello,

any information from the logs? what are you trying to `cat` or `add`? This seems like an issue with your platform that we can do little about. Otherwise please provide more information on how go-ipfs is malfunctioning because it is impossible to guess from this...

**Comment by LiskLabs** [comment]
Hei

When I type in console works good, I  have a problem getting IPFS output programmaticly.

I tried 3 scenarios and still get empty string back :
1. SSH stream on localhost
2. Redirect output to file and read from file
3. Run node script on hdd

I am trying to cat a small size file that I previously added. Works good on dev environment.
Something is different when IPFS outputs because I cant't get it in any way on the server.

**Comment by LiskLabs** [comment]
This bit of code runs ipfs throw powershell succesfully on DEV machine : 

```
public static string RunScript(string scriptText)
        {
            var runspace = RunspaceFactory.CreateRunspace();
            runspace.Open();

            var pipeline = runspace.CreatePipeline();
            pipeline.Commands.AddScript(scriptText);

            var results = pipeline.Invoke();
            runspace.Close();

            var stringBuilder = new StringBuilder();
            foreach (var obj in results)
            {
                stringBuilder.AppendLine(obj.ToString());
            }
            return stringBuilder.ToString();
        }
```

**Comment by hsanjuan** [comment]
Sorry but there is nothing that we can do here. I suggest you ask in https://discuss.ipfs.io as this is a support question for a language we don't work with. I think you should debug your code to see what is getting called at what point, and look at the go-ipfs log for clues about what happens differently between the two environments, but this is very likely not a go-ipfs issue.
