### ISSUE TITLE
My IPFS blocks directory has more files in it than the NSA

### ISSUE THREAD

**Issue by doomicle** [ipfs/go-ipfs#7185]
My drive was filling up, and I decided I'd like to move my IPFS directory to a drive with more space...
Right click, properties, lets see how much space it's using... 2 days later... Nope, that's not going to happen.

Then I think to myself, how am I even going to delete this directory from my drive when it contains so many files that the file system is going to choke while trying to delete it, and the only way to get rid of the directory would be to reformat the drive in order to get rid of it? Shall I just move the rest of my data off of the drive and reformat it? Is that really a design feature we want for IPFS? What about warning the user before install? Shall we put a notice in the installer that says "your drive is going to need a reformat in order to remove the IPFS directory after your done with it"... 
Doesn't seem like a selling point to me.

This would normally be avoided by chunking the files into larger files, and using code to mark the segments in the files as needed. So why not do that?

**Comment by Stebalien** [comment]
What filesystem are you using? I've never had a problem _deleting_ an IPFS repo.

We actually chunk files into _smaller_ pieces to deduplicate small chunks across multiple files. However, as you've pointed out, storing these as separate files can cause problems on many filesystems.

We're working on switching to a new datastore, #4279. We're finally wrapping everything up and should be able to switch the default in 0.6.0 (the next release after this one).
