### ISSUE TITLE
Use libsodium as encryption library

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7188]
Currently, there's been the options explored to switch from the internal go libraries to an external optimized encryption library, namely OpenSSL (#7150).

While OpenSSL offers all needed functionality, it also offers a lot more than necessary. Due to its age it has quite some old code for compatibility reasons for its interface, which might or might not be well maintained.

This is one of the reasons why Google, for example, started a fork [BoringSSL](https://boringssl.googlesource.com/boringssl/) and remove old unneeded code - while not being backward compatible anymore.

**Libsodium** is a better choice for a new integration of an external library - it is well maintained, actively developed by cryptographers, is portable but also highly optimized and is one order of magnitude smaller than OpenSSL.

It's also the reference implementation of **Curve25519** and **ChaCha**(/Salsa20) - which we both probably end up using anyway.

It also offers Salsa2012+umac as an extremely lightweight encryption/authentification mode, which allows getting decent decryption rates on IoT/embedded devices:

A 74K MIPS32 with ~540 MHz does around 22 MBit/s with salsa2012 and umac - while aes128 with gcm does 4 MBit/s. [Source](https://github.com/NeoRaider/fastd/wiki/Benchmarks)

**Comment by Stebalien** [comment]
Want to take this? You'd need to patch https://github.com/libp2p/go-libp2p-core/tree/master/crypto with RSA/ed25519 support for libsodium (behind a `libsodium` build flag).

**Comment by RubenKelevra** [comment]
I'm not sure if I'm already qualified to do cryptographic work ... tbh.

But if the timeline is open, yeah sure.

**Comment by RubenKelevra** [comment]
The implementation and default use of Noise instead of TLS fixes this issue for me.

I think that's an even better option, thanks for the implementation, guys! 😙🎶
