### ISSUE TITLE
ipfs daemon panic

### ISSUE THREAD

**Issue by CsterKuroi** [ipfs/go-ipfs#7194]
#### Version information:
>ipfs version --all
go-ipfs version: 0.4.23-
Repo version: 7
System version: amd64/windows
Golang version: go1.13.7

#### Description:
>ipfs daemon
Initializing daemon...
go-ipfs version: 0.4.23-
Repo version: 7
System version: amd64/windows
Golang version: go1.13.7
Swarm is limited to private network of peers with the swarm key
Swarm key fingerprint: b63c0a21bfedfaff35be7bf3adc36cb6
Swarm listening on /ip4/10.0.130.239/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/169.254.148.101/tcp/4001
Swarm listening on /ip4/169.254.253.152/tcp/4001
Swarm listening on /ip4/192.168.96.161/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/10.0.130.239/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/169.254.148.101/tcp/4001
Swarm announcing /ip4/169.254.253.152/tcp/4001
Swarm announcing /ip4/192.168.96.161/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
panic: runtime error: slice bounds out of range [974875304:78837476]
goroutine 450 [running]:
github.com/dgraph-io/badger.(*valueLog).Read(0xc000436188, 0x1b600000000, 0xb675, 0xc006a2c6c0, 0x0, 0xc006a2e253, 0xc, 0xd, 0x24, 0x0)
        pkg/mod/github.com/dgraph-io/badger@v1.6.0-rc1/value.go:1095 +0x2c3
github.com/dgraph-io/badger.(*Item).yieldItemValue(0xc006363340, 0x0, 0x0, 0x45, 0x42, 0x0, 0xc006a2e253)
        pkg/mod/github.com/dgraph-io/badger@v1.6.0-rc1/iterator.go:168 +0x123
github.com/dgraph-io/badger.(*Item).ValueCopy(0xc006363340, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        pkg/mod/github.com/dgraph-io/badger@v1.6.0-rc1/iterator.go:125 +0x180
github.com/ipfs/go-ds-badger.(*txn).get(0xc0064dfb40, 0xc006a88080, 0x3d, 0xc0064dfac8, 0xc00029ea80, 0x1c1400, 0x0, 0xc0064dfb00)
        pkg/mod/github.com/ipfs/go-ds-badger@v0.0.5/datastore.go:381 +0xe8
github.com/ipfs/go-ds-badger.(*Datastore).Get(0xc0002a4640, 0xc006a88080, 0x3d, 0x0, 0x0, 0x0, 0x0, 0x0)
        pkg/mod/github.com/ipfs/go-ds-badger@v0.0.5/datastore.go:193 +0x16a
github.com/ipfs/go-ds-measure.(*measure).Get(0xc0000ba240, 0xc006a88080, 0x3d, 0x0, 0x0, 0x0, 0x0, 0x0)
        pkg/mod/github.com/ipfs/go-ds-measure@v0.0.1/measure.go:149 +0x111
github.com/ipfs/go-ds-measure.(*measure).Get(0xc0000ba480, 0xc006a88080, 0x3d, 0x0, 0x0, 0x0, 0x0, 0x0)
        pkg/mod/github.com/ipfs/go-ds-measure@v0.0.1/measure.go:149 +0x111
github.com/ipfs/go-ipfs/namesys/republisher.(*Republisher).getLastVal(0xc000438dc0, 0xc0068bec60, 0x22, 0xc00637fed0, 0x1, 0x1, 0xc005959d98)
        pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/namesys/republisher/repub.go:144 +0x74
github.com/ipfs/go-ipfs/namesys/republisher.(*Republisher).republishEntry(0xc000438dc0, 0x14ea7e0, 0xc0069b8c00, 0x14f21c0, 0xc00014a720, 0xc0069b8bc0, 0x10000c005787680)
        pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/namesys/republisher/repub.go:129 +0x13d
github.com/ipfs/go-ipfs/namesys/republisher.(*Republisher).republishEntries(0xc000438dc0, 0x14fc5a0, 0xc000104fc0, 0x0, 0x0)
        pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/namesys/republisher/repub.go:94 +0x108
github.com/ipfs/go-ipfs/namesys/republisher.(*Republisher).Run(0xc000438dc0, 0x14fc5a0, 0xc000104fc0)
        pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/namesys/republisher/repub.go:73 +0x19a
github.com/jbenet/goprocess.(*process).Go.func1(0xc000348f40, 0xc000104fc0, 0xc000105020)
        pkg/mod/github.com/jbenet/goprocess@v0.1.3/impl-mutex.go:134 +0x43
created by github.com/jbenet/goprocess.(*process).Go
        pkg/mod/github.com/jbenet/goprocess@v0.1.3/impl-mutex.go:133 +0x1fd

**Comment by Stebalien** [comment]
Can you reproduce this? If so, please:

1. Back up the datastore.
2. Re-try with go-ipfs 0.5.0-rc2.

**Comment by CsterKuroi** [comment]
Panic several times. What's strange is that no IPNS used.
I will `Re-try with go-ipfs 0.5.0-rc2` later.
(Is this an issue related to badger?)

```
ipfs daemon
Initializing daemon...
go-ipfs version: 0.4.23-
Repo version: 7
System version: amd64/windows
Golang version: go1.13.7
Swarm is limited to private network of peers with the swarm key
Swarm key fingerprint: b63c0a21bfedfaff35be7bf3adc36cb6
Swarm listening on /ip4/10.0.130.239/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/169.254.148.101/tcp/4001
Swarm listening on /ip4/169.254.253.152/tcp/4001
Swarm listening on /ip4/192.168.96.161/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/10.0.130.239/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/169.254.148.101/tcp/4001
Swarm announcing /ip4/169.254.253.152/tcp/4001
Swarm announcing /ip4/192.168.96.161/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
panic: runtime error: slice bounds out of range [:4170342822] with capacity 2147436937

goroutine 206 [running]:
github.com/dgraph-io/badger.(*valueLog).Read(0xc00043af88, 0x1b600000000, 0xb675, 0xc0081dc240, 0x0, 0xc0060dca83, 0xc, 0xd, 0x24, 0x0)
        pkg/mod/github.com/dgraph-io/badger@v1.6.0-rc1/value.go:1095 +0x2c8
github.com/dgraph-io/badger.(*Item).yieldItemValue(0xc005dec000, 0x0, 0x0, 0x45, 0x42, 0x0, 0xc0060dca83)
        pkg/mod/github.com/dgraph-io/badger@v1.6.0-rc1/iterator.go:168 +0x123
github.com/dgraph-io/badger.(*Item).ValueCopy(0xc005dec000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        pkg/mod/github.com/dgraph-io/badger@v1.6.0-rc1/iterator.go:125 +0x180
github.com/ipfs/go-ds-badger.(*txn).get(0xc000215b40, 0xc0059f8200, 0x3d, 0xc000215b58, 0xc000060a80, 0x1c0d58, 0x0, 0x2b)
        pkg/mod/github.com/ipfs/go-ds-badger@v0.0.5/datastore.go:381 +0xe8
github.com/ipfs/go-ds-badger.(*Datastore).Get(0xc000334240, 0xc0059f8200, 0x3d, 0x0, 0x0, 0x0, 0x0, 0x0)
        pkg/mod/github.com/ipfs/go-ds-badger@v0.0.5/datastore.go:193 +0x16a
github.com/ipfs/go-ds-measure.(*measure).Get(0xc0000ba240, 0xc0059f8200, 0x3d, 0x0, 0x0, 0x0, 0x0, 0x0)
        pkg/mod/github.com/ipfs/go-ds-measure@v0.0.1/measure.go:149 +0x111
github.com/ipfs/go-ds-measure.(*measure).Get(0xc0000ba480, 0xc0059f8200, 0x3d, 0x0, 0x0, 0x0, 0x0, 0x0)
        pkg/mod/github.com/ipfs/go-ds-measure@v0.0.1/measure.go:149 +0x111
github.com/ipfs/go-ipfs/namesys/republisher.(*Republisher).getLastVal(0xc0003efa90, 0xc005c20ea0, 0x22, 0xc00816ca00, 0x1, 0x1, 0xc00594dd98)
        pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/namesys/republisher/repub.go:144 +0x74
github.com/ipfs/go-ipfs/namesys/republisher.(*Republisher).republishEntry(0xc0003efa90, 0x14ea7e0, 0xc008170780, 0x14f21c0, 0xc0000eb380, 0xc008170740, 0x10000c00591a4e0)
        pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/namesys/republisher/repub.go:129 +0x13d
github.com/ipfs/go-ipfs/namesys/republisher.(*Republisher).republishEntries(0xc0003efa90, 0x14fc5a0, 0xc00584a300, 0x0, 0x0)
        pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/namesys/republisher/repub.go:94 +0x108
github.com/ipfs/go-ipfs/namesys/republisher.(*Republisher).Run(0xc0003efa90, 0x14fc5a0, 0xc00584a300)
        pkg/mod/github.com/ipfs/go-ipfs@v0.4.23/namesys/republisher/repub.go:73 +0x19a
github.com/jbenet/goprocess.(*process).Go.func1(0xc0002b6ed0, 0xc00584a300, 0xc00584a360)
        pkg/mod/github.com/jbenet/goprocess@v0.1.3/impl-mutex.go:134 +0x43
created by github.com/jbenet/goprocess.(*process).Go
        pkg/mod/github.com/jbenet/goprocess@v0.1.3/impl-mutex.go:133 +0x1fd
```

**Comment by Stebalien** [comment]
Yes. But I'm pretty sure it has been fixed in a more recent badger version.

**Comment by CsterKuroi** [comment]
In 0.5.0-rc4, the panic does not occur. I will reopen this issue if it does.

**Comment by woss** [comment]
i'm getting this with `0.20.0-dev`

![image](https://user-images.githubusercontent.com/80440/229344456-a6b1ffc5-640b-4bed-801d-b578aa3c0c17.png)

![image](https://user-images.githubusercontent.com/80440/229344443-87ce2442-6a05-4f99-8910-cd6a835cb479.png)

**Comment by Jorropo** [comment]
@woss this bug have been fixed, there are more than one ways a daemon can panic, you need to compare the stack traces.
