### ISSUE TITLE
ipfs daemon doesn't start fully

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7206]
#### Version information:

```
go-ipfs version: 0.5.0-rc3-e296c61
Repo version: 9
System version: amd64/linux
Golang version: go1.14.2
```

#### Description:

It doesn't happen often, but sometimes the ipfs-daemon doesn't start up right, and this log output is the last thing the daemon prints:

`ipfs[n]: Golang version: go1.14.2`

IPFS won't open any ports, so I cannot provide any debug information. Stacktrace is attached.

The command line is:

```
/usr/bin/ipfs daemon --enable-pubsub-experiment --enable-namesys-pubsub --migrate
```

[stacktrace_ipfs_2020-04-23.txt](https://github.com/ipfs/go-ipfs/files/4522692/stacktrace_ipfs_2020-04-23.txt)

**Comment by RubenKelevra** [comment]
I can confirm this bug for 0.5.0-rc4

**Comment by Stebalien** [comment]
Thank you for finding this and providing stack traces.
