### ISSUE TITLE
DOSsing S3 with HEAD requests when idle

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-ipfs#7210]
I've spent some time trying to debug why we are hitting request rate limits on our S3 bucket with very little user usage. It seems that ipfs is sending many thousands of HEAD requests without any actual usage. Does this make sense? It is stopping us serving actual user requests because we've hit the request limit (currently 750 req/s) Is it possible to rate limit it?

**Comment by ianopolous** [comment]
> {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "accessKey": "...",
            "bucket": "...",
            "path": "blocks",
            "region": "us-east-1",
            "regionEndpoint": "us-east-1.linodeobjects.com",
            "secretKey": "...",
            "type": "s3ds"
          },
          "mountpoint": "/blocks",
          "prefix": "s3.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "1000000GB"
  }

Looking at that, the bloomfilter is what's caching absent blocks right? So maybe setting that non zero would help? What's a good value?

**Comment by Stebalien** [comment]
Yep. The setting depends on how much memory you're willing to spend on this. The gateways use 268435456 (256MiB).

**Comment by ianopolous** [comment]
That seems to have resolved the issue (using 256MiB). Does that imply that some people must be querying the dht for the same blocks over and over at high frequency?

**Comment by Stebalien** [comment]
That traffic was from bitswap requests. A 256MiB bloom filter can hold millions of elements so this makes sense.
