### ISSUE TITLE
IPFS entering a stale state

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7211]
#### Version information:
go-ipfs version: 0.5.0-rc3-b19d57fb6
Repo version: 9
System version: amd64/linux
Golang version: go1.14.2

#### Description:
I've experienced sometimes that IPFS enters a state where it doesn't function correctly, while there are still multiple hundred connections open.

(Happening on a notebook with a constant wifi connection - which might just be interrupted shortly)

This ticket is meant to track down this bug.

My node has trouble to fetch content from the network, while there are around 400 connections open, while two other nodes return the same content within 1 second.

```
[ruben@i3 ~]$ time ipfs resolve /ipns/pkg.pacman.store
/ipfs/bafybeihhsrfmv7eghxx3zya7fvzocebgs5ordmtij4thhkermy3hv6u3xm

real    0m0,097s
user    0m0,017s
sys     0m0,034s
[ruben@i3 ~]$ time ipfs ls /ipfs/bafybeihhsrfmv7eghxx3zya7fvzocebgs5ordmtij4thhkermy3hv6u3xm
bafybeietwnazzive6b7iw24c53u6gvjmwefzxr35nylycjcob6hejzi5ta - arch/

real    0m0,039s
user    0m0,021s
sys     0m0,019s
[ruben@i3 ~]$ time ipfs ls /ipfs/bafybeihhsrfmv7eghxx3zya7fvzocebgs5ordmtij4thhkermy3hv6u3xm/arch
^C
Error: context canceled

real    1m4,579s
user    0m0,014s
sys     0m0,033s
[ruben@i3 ~]$ time ipfs ls /ipfs/bafybeihhsrfmv7eghxx3zya7fvzocebgs5ordmtij4thhkermy3hv6u3xm/arch
^C
Error: context canceled

real    1m15,534s
user    0m0,019s
sys     0m0,032s

```

I've activated the debug log before I requested the content with `ipfs ls` the second time.

After several minutes my node can also fetch this content - the log is covering this point in time as well.

[debug_log_ipfs_2020-04-25.zip](https://github.com/ipfs/go-ipfs/files/4532636/debug_log_ipfs_2020-04-25.zip)

_This ticket was edited to make the issue more clearly._

**Comment by Stebalien** [comment]
"doesn't function correctly" is not helpful. Even if you don't know why this is happening, we still need to know what "doesn't function correctly" means.

Please don't file issues like this.

**Comment by momack2** [comment]
@RubenKelevra can you clarify what exactly the behavior is you’re seeing that you describe as “stale”? Is your node not responding to new commands, not able to make new connections, running out of memory/CPU?

**Comment by RubenKelevra** [comment]
The node isn't returning content via the http gateway.

After a restart (and like 60 seconds to bootstrap) the node can fetch the same content basically instantly.

**Comment by RubenKelevra** [comment]
> "doesn't function correctly" is not helpful. Even if you don't know why this is happening, we still need to know what "doesn't function correctly" means.
> 
> Please don't file issues like this.

I'm sorry, I'll edit the issue to be more clearly :)

**Comment by Stebalien** [comment]
> I'm sorry, I'll edit the issue to be more clearly :)

Thank you! :heart:

I'll dig into this later today.

**Comment by RubenKelevra** [comment]
Okay I can reproduce it.

Cutting the wifi connection for a while, the connections of IPFS will drop - but not to 0 but to something like 4 or 10 connections.

After the wifi reconnect IPFS will reconnect to a lot of nodes - leaving IPFS running for 15 minutes and try something DHT related is still extremely slow, a simple ls of a CID took me over 2 minutes.

On the other hand, if I restart the node when the Wifi connection is reestablished and wait 1 minute for IPFS to bootstrap, a similar request takes less than 1 second.

**Comment by Stebalien** [comment]
Ah. IPFS may have dropped all those peers from your routing table, leaving only a few. It _should_ bootstrap back into the network, but the peers in your routing table may not have been "healthy".

If you can reproduce this, could you _try_ connecting to one of the bootstrap peers? That is, `ipfs swarm connect `/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ`. If that fixes the issue, then we've found the problem.

**Comment by Stebalien** [comment]
Note: I would avoid running with the debug log turned on for _everything_. That will just slow your node to a crawl. Really, the debug logging we have is mostly useful for debugging specific subsystems.

**Comment by RubenKelevra** [comment]
> Really, the debug logging we have is mostly useful for debugging specific subsystems.

Yeah, it was more of last resort since I wasn't sure what's going on and which part of IPFS might have run into trouble.

I thought it's more helpful than nothing :)

> Ah. IPFS may have dropped all those peers from your routing table, leaving only a few. It _should_ bootstrap back into the network, but the peers in your routing table may not have been "healthy".
> 
> If you can reproduce this, could you _try_ connecting to one of the bootstrap peers? That is, `ipfs swarm connect /ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ`. If that fixes the issue, then we've found the problem.

Okay:

```
#################################
broken automatic reconnect
#################################
restart ipfs
bootstrap for 15 minutes...
ipfs swarm peers: 735
disable wifi
stay offline for 200 seconds...
ipfs diag sys:
################################
{"diskinfo":{"free_space":33478672384,"fstype":"2435016766","total_space":24704565248},"environment":{"GOPATH":"","IPFS_PATH":""},"ipfs_commit":"","ipfs_version":"0.6.0-dev","memory":{"swap":104000,"virt":1564928000},"net":{"interface_addresses":["/ip4/127.0.0.1","/ip6/::1"],"online":true},"runtime":{"arch":"amd64","compiler":"gc","gomaxprocs":4,"numcpu":4,"numgoroutines":287,"os":"linux","version":"go1.14.2"}}
################################
ipfs swarm peers: 9
running ipfs gc
try to fetch unpinned file... error

real    0m0,007s
user    0m0,003s
sys     0m0,001s
enable wifi
wait 2 minutes, to let ipfs reconnect
ipfs swarm peers: 29
try to fetch unpinned file... error

real    1m0,037s
user    0m0,004s
sys     0m0,003s

#################################
working reconnect with restart of daemon
#################################
disable wifi
stay offline for 200 seconds...
running ipfs gc
enable wifi
wait 2 seconds to get the network ready
restart ipfs
wait 2 minutes, to let ipfs reconnect
ipfs swarm peers: 54
try to fetch unpinned file... successful

real    0m3,737s
user    0m0,003s
sys     0m0,002s

#################################
running disconnect with manual swarm connect...
#################################
restart ipfs
bootstrap for 15 minutes...
ipfs swarm peers: 232
disable wifi
stay offline for 200 seconds...
ipfs diag sys:
################################
{"diskinfo":{"free_space":33231499264,"fstype":"2435016766","total_space":24467353600},"environment":{"GOPATH":"","IPFS_PATH":""},"ipfs_commit":"","ipfs_version":"0.6.0-dev","memory":{"swap":4000,"virt":1559676000},"net":{"interface_addresses":["/ip4/127.0.0.1","/ip6/::1"],"online":true},"runtime":{"arch":"amd64","compiler":"gc","gomaxprocs":4,"numcpu":4,"numgoroutines":284,"os":"linux","version":"go1.14.2"}}
################################
ipfs swarm peers: 8
running ipfs gc
try to fetch unpinned file... error

real    0m0,007s
user    0m0,003s
sys     0m0,003s
enable wifi
wait 2 seconds to get the network ready
manually connect to bootstrap node...
connect QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ success
wait 2 minutes, to let ipfs reconnect
ipfs swarm peers: 17
try to fetch unpinned file... error

real    0m0,034s
user    0m0,004s
sys     0m0,001s
```

So it gets weirder:

* If I let the service run and disconnect for 200 seconds and give it 2 minutes to reconnect, the request times out.
* If I restart the daemon it gets in 2 minutes ready to fetch a file (fetch takes like 2-5 seconds).
* If I do the same thing as in the first case, but manually connect to the host you provided, the same request returns an error immediately.

The HTTP error returned is always 404.

The test is not 100% reproducible, I ran it twice:
* The first time it had trouble to fetch case 1, the second time it had no trouble.
* In both cases it fetched in case 2 the file properly.
* The last case resulted in the same behavior both times.



[ipfs_stale_state_test.sh.txt](https://github.com/ipfs/go-ipfs/files/4571358/ipfs_stale_state_test.sh.txt)

**Comment by Stebalien** [comment]
@dirkmc could you look at this when you get a chance?

**Comment by RubenKelevra** [comment]
Just some thought:

Maybe we want to watch out for the event, that many connections stop receiving data at the same time, without having to wait for a timeout for each one.

Like having a flag if there was no data received on the connection for 10 seconds or so.

If we have, say 50 connections in total (minimum) and there's a large percentage of connections in this state, there's been an issue, as a routing failure, the internet connection has failed, a network outage somewhere, a router reboot, a switch to a different Wifi etc.

To recover from we could randomly drop connections from the "flagged" list, and redial those peers, maybe with a bias towards nodes that we consider most valuable in the routing table.

If our detection is correct, there are two ways this situation can recover:

* The stale connections start receiving data again
* Our redials are successful

If the stale connections start receiving again, great - we cancel this by redialing a last time all dropped connections and stop.

If the radials are successful, great, we slowly redial all flagged connections after dropping.

If the redials are not successful we need to keep the list of died connections for a while, say 10 minutes or so, and as soon as the new redials are working (say 10% has been successful), we try to redial the list again - if it's not working we drop the peer.

In any case, such a situation should not change the routing table in a way that we consider the peer as "bad", but just add a "temporary outage" flag to them, so if we try to look up content, we skip those peers for the time of the recovery operation.

**Comment by RubenKelevra** [comment]
I thoroughly tested this, the bug is gone. After 2 minutes IPFS will be able to fetch the file in like 5 seconds, compared to after 15 minutes with more connections it will take like 2-3 seconds.
