### ISSUE TITLE
QUIC isn't working

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7212]
#### Version information:
go-ipfs version: 0.5.0-rc3-b19d57fb6
Repo version: 9
System version: amd64/linux
Golang version: go1.14.2

#### Description:

There are no UDP ports announced by my node:

```
$ ipfs id | grep -vE "127.0.0.1/tcp|::1/tcp|p2p-circuit" | grep "/udp/"

```

While QUIC is on:
```
$ cat .ipfs/config | grep -i quic
    "QUIC": true,
```

**Comment by Stebalien** [comment]
You still need to configure your node to _listen_ on a QUIC address. That config option only allows _dialing_ QUIC peers. Take a look at the documentation in docs/experimental-features.md.

**Comment by RubenKelevra** [comment]
> You still need to configure your node to _listen_ on a QUIC address. That config option only allows _dialing_ QUIC peers. Take a look at the documentation in docs/experimental-features.md.

Oh wow, I found the issue: my udp port definitions was just missing a `/quic` at the end. Thanks for the heads up!
