### ISSUE TITLE
GC does not release disk space

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7223]
#### Version information:
go-ipfs version: 0.5.0-rc4
Repo version: 9
System version: amd64/linux
Golang version: go1.14.2

I'm running revision https://github.com/ipfs/go-ipfs/commit/5fff291bf7b79ae51dac8697e96a5259958c3dfb

#### Description:
I converted my repo with applying the `badgerds` profile and using ds-convert to convert the flatfs to the database format.

My repo is around 6 GB before starting the GC:
```
[ruben@i3 ~]$ ipfs repo stat
NumObjects: 13000
RepoSize:   5965932321
StorageMax: 10000000000
RepoPath:   /home/ruben/.ipfs
Version:    fs-repo@9
```

There are no files or pins left (I've deleted many):

```
[ruben@i3 ~]$ ipfs files ls
[ruben@i3 ~]$ ipfs pin ls
[ruben@i3 ~]$ 
```

GC run:
```
[ruben@i3 ~]$ ipfs repo gc
removed bafk[...]
[...]
```

After the GC has completed, my repo is at the same size:

```
[ruben@i3 ~]$ ipfs repo stat
NumObjects: 4
RepoSize:   5969617821
StorageMax: 10000000000
RepoPath:   /home/ruben/.ipfs
Version:    fs-repo@9
```

A restart of the daemon actually increased the storage consumption:

```
[ruben@i3 ~]$ sudo systemctl restart ipfs@ruben
[ruben@i3 ~]$ sleep 10; ipfs repo gc; ipfs repo stat
NumObjects: 4
RepoSize:   5972373166
StorageMax: 10000000000
RepoPath:   /home/ruben/.ipfs
Version:    fs-repo@9
```

I also checked if the storage consumption is real:

```
[ruben@i3 ~]$ du -hc /home/ruben/.ipfs/badgerds/ | tail -n1
5,6G    total
```

* Is this a known limitation of the badgerds profile or is this a bug?
* If so, how do I compact the storage with a badgerds database?

**Comment by RubenKelevra** [comment]
Ah, sorry, found this bug on the datastore repo:

https://github.com/ipfs/go-ds-badger/issues/54#issuecomment-581476607

**Comment by CsterKuroi** [comment]
The same thing happened to me.

**Comment by RubenKelevra** [comment]
@CsterKuroi thanks for your confirmation. It's a known issue and there's currently work beeing done to fix it.
