### ISSUE TITLE
Rework relay options

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#7228]
The current relay options are confusing and dangerous. Setting `EnableAutoRelay` _and_ `EnableRelayHop` will cause nodes to advertise themselves as relays to the rest of the network.

At a minimum, we should make `EnableAutoRelay` do what it _looks_ like it should do: automatically use public relays. Then, we can:

1. Remove `EnableRelayHop`. I'm concerned users have enabled this without having any idea what it does.
2. Add a `PublicRelayMode` option with three variants: "disabled", "enabled", "i am an isp" (what EnableRelayHop + PublicRelayMode currently do).

**Comment by hsanjuan** [comment]
Priority, status, plus potential assignment to milestone please?

**Comment by RubenKelevra** [comment]
How about using default Linux terminology here?

- "TrafficForwarding": (Enable/Disable)
- - Enabled or disabled that this node will forward any traffic
- "AdvertiseTrafficForwarding: (Enable/Disable) 
- - Enables or disables that this node will advertise itself as traffic forwarder (relay hop) to the network
- "UseTrafficForwarding": (On/Auto/Off)
- - Enables or disables that this node will search and use traffic forwarder (relay hops). Auto will decide this based on the autonat status

**Comment by Stebalien** [comment]
Calling it "relay" in some places and "traffic forwarding" in others is going to be _really_ confusing.

**Comment by eminence** [comment]
Are there any options to control how a node advertises itself as providing relay services?  For example, can I configure node A on my network to provide relay services *only* to other nodes on my LAN (and also configure the other nodes on my LAN to use node A as a relay)?

**Comment by Stebalien** [comment]
Please ask questions on discuss.ipfs.io

**Comment by Winterhuman** [comment]
@Stebalien Should this be closed now that `EnableRelayHop` is no longer an option (along with the other CircuitV1 options)?

**Comment by Stebalien** [comment]
Yep!
