### ISSUE TITLE
Implement GitFlow

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#7245]
We're switching to a fixed release model where we'll have to branch off a new release every 6 weeks, releasing three weeks after branching. That means:

* Each release has 6 weeks of features, 3 weeks of baking.
* This means that every release will get:
  * 3 weeks of "shared" time with the previous release.
  * 3 weeks of focus time.

Given that we can't afford to lose that shared time, we need to find a way to keep merging when the next release is baking. Git-flow was designed for exactly this kind of scheduled release cycle.

First of all, any objections from the team? Specifically, the model I'm talking about is https://nvie.com/posts/a-successful-git-branching-model/.

Second, we have two options:

* A: True git-flow. That is, the model described in the link above.
* B: Use "master" as gitflow's develop (as we do now) and a "release" branch as gitflow's master (which is almost what we do now).

That is:

* A: patches go to develop, "master" is the stable release branch.
* B: patches go to master, "release" is the stable release branch.

I'm leaning towards B given that:

1. For 99% of users, this work flow will look like the standard GitHub PR model.
2. We're already half-way there (we already have a release branch).

The main thing we need to implement full git-flow is to start doing the back merges (e.g., https://github.com/ipfs/go-ipfs/pull/7243), so we can easily deploy hot patches at any time.

Thoughts?

_Originally posted by @Stebalien in https://github.com/ipfs/go-ipfs/issues/2753#issuecomment-620866691_

Note: B was proposed in https://github.com/ipfs/go-ipfs/issues/2753 but I'm forking this into a new issue because that issue doesn't _quite_ describe git-flow and I don't wan to introduce too much confusion.

**Comment by RichardLitt** [comment]
I think you lay out the options well, and I would probably go with B, because it makes slightly more sense for an edge project. The most important thing is sign-posting this well for devs.

**Comment by ribasushi** [comment]
👍 from me, though I'd strongly recommend `variant A`. With a shortened release cycle* having the "main github branch" reflect "latest stable release" will present the best platform for casual contributors. That is a contributoe would not need to remain in the PL loop to submit and test a patch, while the PL dev team will have all the relevant context to "forward-port" the submitted work to the net release branch. With that said: I won't object if `variant B` is chosen going forward.

*This comment should not be considered an endorsement of time-boxed releases...

**Comment by hsanjuan** [comment]
> +1 from me, though I'd strongly recommend `variant A`. With a shortened release cycle* having the "main github branch" reflect "latest stable release" will present the best platform for casual contributors. That is a contributoe would not need to remain in the PL loop to submit and test a patch, while the PL dev team will have all the relevant context to "forward-port" the submitted work to the net release branch. With that said: I won't object if `variant B` is chosen going forward.

I really hope contributors send patches to latest "develop" (or master in variant B). The amount of "sorry, this was fixed already in `develop` but forgot this issue was similar to this other that we closed", plus the work to forward-porting will be non trivial.

Variant B seems the most natural for how we work (note that we have a few dozens repositories where we work on master and afaik we are not changing the workflow everywhere either), so while I could work on variant A just fine, a new comer might get confused.

**Comment by jacobheun** [comment]
I'd recommend B. Option A creates more overhead for little gain in my experience, especially with the current workflow. It's almost the same as B except it has an extra branch, master, which always points to the latest release.

Additionally, if we ever get to the point where we can be confident in a CD pipeline for master, you can drop the release branch and not need to change anything else.

**Comment by willscott** [comment]
I'd prefer Option B as well

**Comment by Stebalien** [comment]
Ok, we're implementing option B.

I've:

* Protected all release-* branches. We'll use these to prepare new releases.
* Merged release back into master.

I've also created a release-0.5.1 branch and created a PR against it.

**Comment by Stebalien** [comment]
This PR has raised a question: there are two ways to make "hotfixes".

1. Branch from release-VER, merge to release-VER, eventually merge release-VER into master.
2. Branch from master, merge to master, cherry-pick to release-VER.

The first option is nice because it's easy. However, it means we need to decide to make the change ahead-of-time.

The second option is nice because all PRs go to master and we can decide what needs to get backported _later_. Lots of projects (e.g., go) use the second option.

My only concern with the second option is merge conflicts because we _do_ want to merge release back into master at the end of the day.

**Comment by Stebalien** [comment]
If we go with option 2, I'd like to consider merging to release-* without merge commits and _only_ cherry-picking/fast-forwarding. That way, the release-log is at least somewhat clean.

**Comment by hsanjuan** [comment]
I like option two, but sounds like go.mod/sum conflicts on cherry pick are going to happen pretty often. Many fixes are just bubbling a dependency... might have to adopt both ways depending on the fix?

**Comment by RubenKelevra** [comment]
How about having a development cycle like Linux?

So all pull requests will be on hold until the next merge window, in this time the master will be tested and bugfixes will be made, if the release is out, the release will be branched off and fixes will be cherry-picked/rebased from the master to the release branches - when necessary.

In the merge window, everyone can focus on merging the different changes together and do preliminary testing for the compatibility, while new features will be developed in feature branches (like today).

**Comment by Stebalien** [comment]
We're intentionally _not_ doing that so we can have a fast release cycle without pausing the world every time there's a release. Linux has that release cycle because most work is done in separate feature branches by completely independent groups. Merging doesn't really stop, it just happens elsewhere.

**Comment by RubenKelevra** [comment]
> We're intentionally _not_ doing that so we can have a fast release cycle without pausing the world every time there's a release. Linux has that release cycle because most work is done in separate feature branches by completely independent groups. Merging doesn't really stop, it just happens elsewhere.

Okay in this case it would make sense to have a development branch which takes all PRs and a master branch which gets the rebase/merge from the development branch on each feature freeze.

Patches/fixes get pulled to the development branch as well and then backported with rebase/cherry-pick to the master and release branches if necessary.

I guess that's option A? 🤔

**Comment by Stebalien** [comment]
We've gone with option B so the standard release flow of PRing to master still works.

**Comment by RubenKelevra** [comment]
> We've gone with option B so the standard release flow of PRing to master still works.

Ah! your last comments sounded like there's still an open discussion :)

**Comment by hsanjuan** [comment]
Closing as it would seem decision was taken.
