### ISSUE TITLE
bad links via IPNS mountpoint

### ISSUE THREAD

**Issue by neededanametoreportbug** [ipfs/go-ipfs#7246]
ipfs version --all
go-ipfs version: 0.5.0
Repo version: 9
System version: amd64/linux
Golang version: go1.13.10

Trying to access content via the IPNS filesystem mount point results in broken links to the IPFS filesystem mount point, except for the local peer.

eg:
ipfs mount
>IPFS mounted at: /ipfs
>IPNS mounted at: /ipns

ipfs name resolve ipfs.io
>/ipfs/bafybeih2idmvr2uum3k7btt6mjxfzeb7ank5g6zkmrfbxkvu6ownzbrtky

cd /ipns/ipfs.io
>bash: cd: /ipns/ipfs.io: No such file or directory

ls /ipns/ipfs.io
>lr-xr-xr-x. 1 root root 0 Apr 29 19:26 /ipfs.io -> /ipfs//ipfs/

Looks like the link has an unnecessary "/ipfs/" added to the destination

However local peer is visible via the ipns mount point though, eg :/ipns/local and /ipns/[peer id]

**Comment by hsanjuan** [comment]
I can reproduce this and it's a regression from v0.4.23. However I am not sure when it happened.
