### ISSUE TITLE
enable gateway by default

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#725]
- [x] enable gateway by default (at `/ip4/127.0.0.1/tcp/8080`)
- [x] whitelist only the webui on the private route
- [ ] tell user how to change the ports
- [x] check referrer on API webui

**Comment by mappum** [comment]
> tell user how to change the ports

@jbenet Where are you thinking we should do this?

**Comment by jbenet** [comment]
@mappum could be in a reference doc, or in the quick start?

**Comment by briantigerchow** [comment]
@mappum is there a PR?

**Comment by travisperson** [comment]
I think this is a pretty easily tackled issue and can be closed quickly once a good location is picked for the information.

**Comment by whyrusleeping** [comment]
this makes me realize we dont have a good place for general documentation...

**Comment by diasdavid** [comment]
`ipfs daemon --help` 🚀
