### ISSUE TITLE
Use go-multiaddr-dns DefaultResolver instead of std lib Resolver

### ISSUE THREAD

**Issue by cpacia** [ipfs/go-ipfs#7260]
Would be nice to swap out the `net.LookupTXT` in the dns resolver for the `madns.DefaultResolver.LookupTXT` function.

This would allow one to just override the `madns.DefaultResolver` and it would work for both libp2p and IPFS. As it stands now there is no way to configure this resolver. 

https://github.com/ipfs/go-ipfs/blob/f006fc164771d6ab2e2b2608992bc6e5d1f17a8f/namesys/dns.go#L28

**Comment by matyapiro31** [comment]
Ref: #6915

**Comment by hsanjuan** [comment]
@Stebalien this looks like an ok proposal unless I'm missing something.

**Comment by Stebalien** [comment]
`madns.DefaultResolver` isn't quite right as madns and dnslink are two separate specs. Ideally we'd construct resolvers with the right dns resolver, but threading that through is difficult. We might need a global `go-dns` package.

**Comment by lidel** [comment]
We are tracking configurable DNS servers (for all record types) in https://github.com/ipfs/go-ipfs/issues/6532
