### ISSUE TITLE
unexpected high cpu load and memory consumption

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7263]
#### Version information:
I was running 0.5.0-rc4 from commit https://github.com/ipfs/go-ipfs/commit/116999a194f75e70cd13e378c50f96065f650845 

```
Repo version: 9
System version: amd64/linux
Golang version: go1.14.2
```

#### Description:
While there was just single digit MBit/s traffic on the server, the CPU was under substantial load by IPFS and it used nearly half of the RAM.

```
ipfs       13567  6.1  6.2 4970396 1017004 ?     Ssl  Apr21 884:15 /usr/local/bin/ipfs-cluster-service daemon
ipfs     2403637  223 43.9 16769580 7202860 ?    Ssl  Apr26 16229:31 /usr/bin/ipfs daemon --enable-pubsub-experiment --enable-namesys-pubsub
```

The VM has 16 G memory and 4 cores of an Intel Xeon Gold 6140 CPU @ 2.30GHz.

The debug-files are attached.
[ipfs_debug.tar.gz](https://github.com/ipfs/go-ipfs/files/4563675/ipfs_debug.tar.gz)

**Comment by Stebalien** [comment]
It looks like you have ~243 QUIC connections. Is that correct? (`ipfs swarm peers | grep -c quic`).

cc @marten-seemann I'm seeing a lot of timers firing and a lot of timers being held by QUIC connections.

**Comment by marten-seemann** [comment]
@Stebalien Looking at `ipfs.heap`, it looks like the QUIC sessions are holding 41 MB of timers in total. That doesn't seem right for just 243 connections.

It seems like the session doesn't reset or stop the timer when it is closed (I just created https://github.com/lucas-clemente/quic-go/issues/2515), so maybe we're leaking timers there? Although the timer is set to a maximum of 30s (the idle timeout), so leaked timers should be garbage collected after that time frame.

**Comment by Stebalien** [comment]
The timer is getting created with a timeout of "max int".

**Comment by marten-seemann** [comment]
I'm not sure if that's the problem, since the timer would get reset as soon as the first packet is either sent or received. In any case, stopping the timer when the QUIC connection is closed seems like the right thing do.

**Comment by RubenKelevra** [comment]
> It looks like you have ~243 QUIC connections. Is that correct? (`ipfs swarm peers | grep -c quic`).

This could be right, the server has enough power to handle a lot of connections, so the limiter is basically "open", to avoid that my server is cutting connections, but leave the other side handle the disconnects (if this makes any sense).

**Comment by Stebalien** [comment]
This has since been fixed.
