### ISSUE TITLE
quick start fixes

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#727]
- [ ] mount
- [ ] rename `object -> dag` once #634 merges
- [ ] `ipfs webui` opens webui in your browser
- [ ] change directory example (fruits/corps with apple)

**Comment by whyrusleeping** [comment]
update here? this should be checked.

**Comment by RichardLitt** [comment]
@whyrusleeping This doesn't look like it has actually be closed. #2144 doesn't follow the steps outlined by @jbenet... Reopen?
