### ISSUE TITLE
Get Directory Hash from File Hash

### ISSUE THREAD

**Issue by devanshusehgal** [ipfs/go-ipfs#7279]
It'd be really useful to be able to get the Directory Hash from the File Hash.
If we could get the directory hash we can get file name and metadata.
Is there a way to currently get the hash of the directory?

![Screenshot from 2020-05-06 16-35-42](https://user-images.githubusercontent.com/38864946/81170104-b49a0000-8fb7-11ea-9da3-6f403115b9f2.png)

**Comment by Stebalien** [comment]
I'm not sure what you're asking. `QmNWV...MrTUNn` is the directory hash.

**Comment by devanshusehgal** [comment]
Is there a way to get to this directory hash

> Qm...TuNn

when someone only knows the file hash

> Qm...KiZY

**Comment by Stebalien** [comment]
Ah, no. Unfortunately, that's impossible as it would require a cycle. The file would need to contain the hash of the directory and the directory would need to contain the hash of the file.

If you want someone to have a directory containing the filename, you need to give them the directory.
