### ISSUE TITLE
My broadband bandwidth is only 10MiB, but I can reach 40MiB with ipfs

### ISSUE THREAD

**Issue by sun-wenming** [ipfs/go-ipfs#7303]
0.6.0 version

Why use ipfs to download so fast.My broadband bandwidth is only 10MiB, but I can reach 40MiB with ipfs, far exceeding my actual bandwidth.That's cool.But I want to know why.I can't find the answer from google.Can anyone tell me why.Thanks.

![image](https://user-images.githubusercontent.com/22268505/81543668-f86e7a00-93a8-11ea-8830-367fd54905b4.png)

**Comment by mohe2015** [comment]
@sun-wenming You probably already downloaded some part of the data so ipfs can provide you the file locally. It doesn't actually download it from the internet (at least not all parts of the file)

**Comment by sun-wenming** [comment]
em. maybe not. But, ipfs is so quick.  I am now focusing on mobile applications.

**Comment by bertrandfalguiere** [comment]
Maybe it's a difference between MiB and MB, or maybe there is another node with some files on your local network?
