### ISSUE TITLE
Gateway should generate an index for directories containing CBOR-DAGs

### ISSUE THREAD

**Issue by dysbulic** [ipfs/go-ipfs#7304]
I am working on a [git remote](//github.com/dhappy/git-remote-igis/tree/rev/javascript) which, when a repo is pushed to IPFS, produces [a UnixFS filesystem of the pushed branch with a `.git` CBOR-DAG object added](//explore.ipld.io/#/explore/QmRSQhu5ps8tjwRx43rbbeABza5FY7Z5wWxpRzVW137UMT).

When viewing [the produced filesystem through the gateway](http://gateway.temporal.cloud/ipfs/QmRSQhu5ps8tjwRx43rbbeABza5FY7Z5wWxpRzVW137UMT), if it needs to generate an index, it fails with the error: `internalWebError: unknown node type`. If an `index.html` is present, that is served.

**Comment by lidel** [comment]
Continued in https://github.com/ipfs/go-ipfs/issues/8223 (closing this one, as that one has more generic unixfs example)
