### ISSUE TITLE
Config nodes to listen on QUIC by default

### ISSUE THREAD

**Issue by momack2** [ipfs/go-ipfs#7343]
- [x] change the default config to listen on quic by default https://github.com/ipfs/go-ipfs/pull/7349
- [ ] upgrade bootstrappers to listen on quic https://github.com/protocol/bifrost-infra/issues/778
- [ ] add a migration to https://github.com/ipfs/fs-repo-migrations/pull/102
  - listen on quic on existing TCP listen addresses
  - add quic addresses for the bootstrappers

**Comment by RubenKelevra** [comment]
QUIC is still experimental, I feel like this should be done when QUIC is considered stable. :)

**Comment by aschmahmann** [comment]
@RubenKelevra the plan is to make QUIC non-experimental and supported by default. In order to do that this issue needs to be tackled.

**Comment by RubenKelevra** [comment]
> @RubenKelevra the plan is to make QUIC non-experimental and supported by default. In order to do that this issue needs to be tackled.

Yeah. I've just tested it. The daemon will start happily with the definition but quic disabled.

So there's no blocker for this, regardless if QUIC is stable or not.


Currently I'm experiencing memory leaks with QUIC on, while not all fixes for this (as far as I understand) are in the master.

See https://github.com/ipfs/go-ipfs/issues/7263

**Comment by dirkmc** [comment]
Should the reverse migration always set `Experimental.QUIC` to `false`?
This could be surprising to someone who
  - has `Experimental.QUIC` set to `true`
  - migrates forwards
  - migrates backwards
  - `Experimental.QUIC` is now `false`

**Comment by RubenKelevra** [comment]
> Should the reverse migration always set `Experimental.QUIC` to `false`?
> This could be surprising to someone who
> 
> * has `Experimental.QUIC` set to `true`
> * migrates forwards
> * migrates backwards
> * `Experimental.QUIC` is now `false`

I don't think we should enable experimental options on the migration.

As far as I understand the idea is to enable the listening entries for quic on the migration and add the quic addresses for the bootstrappers. When QUIC is stable, the experimental option will be removed and it will be on by default.

**Comment by dirkmc** [comment]
Right, of course, that makes sense :)

**Comment by Stebalien** [comment]
@dirkmc 

The idea is to:

1. _Drop_ the experimental feature flag and enable it by default. The migration doesn't have to handle that.
2. Have a migration that adds the listen address. The reverse migration shouldn't do anything.

So yeah, the reverse migration may be a bit surprising, but it won't be the end of the world. At worst, we'll end up disabling the QUIC transport.

**Comment by Stebalien** [comment]
Complete feature description:

1. No reverse migration.
2. On the forward migration:
    1. Add a QUIC bootstrap address for mars.
    2. For every `/tcp/PORT` swarm listen address, add a `/udp/PORT/quic` listen address.
    3. For every `/tcp/PORT` address in Announce/NoAnnounce, add a `/udp/PORT/quic` address.
