### ISSUE TITLE
Add other subdomain option for ipfs daemon.

### ISSUE THREAD

**Issue by matyapiro31** [ipfs/go-ipfs#7345]
I'm testing OpenNIC domain registration, I cannot use `_dnslink` for subdomain in be.libre(opennic domain registration service).
How about adding an option to change it?

**Comment by RubenKelevra** [comment]
`_dnslink` isn't supposed to be a subdomain, but you're supposed to add a TXT-record to your (sub)domain which starts with `_dnslink`.

I'm sure be.libre supports TXT-records.

Additionally an option to change the setting on your client, doesn't help anyone else who wants to access your page.

**Comment by Stebalien** [comment]
I think he means he can't add a TXT record to a _dnslink subdomain.  Unfortunately, that's something that needs to be solved upstream.

**Comment by RubenKelevra** [comment]
@matyapiro31 not affiliated in any way, but OVH has a very good dns service, offering DNS-Sec on nearly all TLDs and can process every DNS records you like. :)
