### ISSUE TITLE
progressbar on `ipfs add` and `ipfs get`

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#736]
Get doesnt seem to have a progress bar, it should have one (we know the total size)

And maybe so should recursive refs.

**Comment by MichaelMure** [comment]
related: https://github.com/jbenet/go-ipfs/issues/930

**Comment by cryptix** [comment]
We have a working progressbar for [`ipfs add`](https://github.com/jbenet/go-ipfs/blob/master/core/commands/add.go#L136) and it is in [`ipfs get`](https://github.com/jbenet/go-ipfs/blob/master/core/commands/get.go#L125) as well but it looks like it needs some love.

**Comment by whyrusleeping** [comment]
get has a progressbar now, but as @cryptix said, it might need some love. It looks like we're not setting the 'max size' properly

**Comment by jbenet** [comment]
We need to do a cleanup of all progressbar stuff-- looks like there's
several issues

**Comment by whyrusleeping** [comment]
'get' has a progress bar, 'add' does as well. There is another issue open to add one to refs
