### ISSUE TITLE
Config: Silently ignore tailing JSON commas

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7383]
The current config parser seems to be very strict when parsing arrays, many parsers just ignore trailing commas in them.

I had several times going back and remove a comma because I copied a line to a different place and forgot to remove the comma.

It would be nice if the JSON parser could parse the config file a bit more loosely, to tailing commas.

**Comment by Stebalien** [comment]
How about https://github.com/ipfs/go-ipfs/issues/6306? JSON is JSON and should be left as JSON.

**Comment by RubenKelevra** [comment]
Javascript allows tailing commas in arrays and ECMAScript 5 allows them for objects as well.

So we're technically too strict in the parsing.

Well, actually a JSON document is already a valid YAML document, since JSON is a subset of YAML. So we could just switch to a YAML parser and have both: What people understand as JSON and YAML parsed.

**Comment by Stebalien** [comment]
No, we're doing the right thing. We're using the default JSON decoder for go that follows the spec. JSON is a subset of JavaScript objects.
