### ISSUE TITLE
Document that the ipfs object command only works with DagPB nodes

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#7396]
#### Version information:

> v0.6.0-rc1

#### Description:

The `ipfs object` command only works with DagPB nodes. Specifically, it won't work with other IPLD formats like DagCBOR, raw nodes (and raw leaves), etc.

**Comment by Stebalien** [comment]
@RubenKelevra, are you interested in picking this up?

**Comment by RubenKelevra** [comment]
Yes

**Comment by RubenKelevra** [comment]
Damn, I had a hard time finding this again, can you assign me, please @Stebalien?

**Comment by lidel** [comment]
@RubenKelevra @Stebalien I kinda did this as part of https://github.com/ipfs/go-ipfs/pull/8010 – mind reviewing that one?
