### ISSUE TITLE
Vulnerability: any application have access to change IPFS settings

### ISSUE THREAD

**Issue by ZhoraBartolomey** [ipfs/go-ipfs#7406]
#### Version information:
go-ipfs v0.5.1

#### Description:
I found serious vulnerability: any application and any user have access to **change IPFS settings**  through the API. 

Hope you fix it.

**Comment by rpodgorny** [comment]
(i'm not the original poster)

i think this needs to be (partially) redesigned in general. most modern operating systems are multi-user and while sharing block data may not be a security/privacy issue, sharing the mfs state certainly is.

**Comment by Stebalien** [comment]
Yeah, this definitely needs to be redesigned. Long discussion here: https://github.com/ipfs/go-ipfs/issues/1014. Also, https://github.com/ipfs/go-ipfs/issues/1532.

The short-term version is to have per-user daemons on separate ports with separate tokens.

**Comment by RubenKelevra** [comment]
Well, as a workaround you can just unix sockets to restrict the API access to certain users on a machine. :)

**Comment by polymorphm** [comment]
actually it's not closed.
