### ISSUE TITLE
`ipfs get` is unsuitable to output to stdout

### ISSUE THREAD

**Issue by l29ah** [ipfs/go-ipfs#7417]
If you want to pipe the result through your shell pipe conveyor, even if you specify `-o /dev/stdout`, the output will be messed up by `Saving file(s) to /proc/self/fd/1` and maybe other output that belongs in stderr.

**Comment by ribasushi** [comment]
@l29ah `ipfs get` is designed for writing out recursive directory trees to a filesystem location. For pipe operation over a stream you want `ipfs cat`

I'll keep the ticket open in case I misunderstood your question/constraints. Please close it if your question has been answered.

Cheers!
