### ISSUE TITLE
A small tip to reduce the final binary size

### ISSUE THREAD

**Issue by yu-chenxi** [ipfs/go-ipfs#7425]
*According to this post [shrink your Go binaries with this one weird trick](https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/), I think just modify the build config file [Rules.mk](https://github.com/ipfs/go-ipfs/blob/master/cmd/ipfs/Rules.mk) a little bit and the go-ipfs size will reduce a lot as well as its docker image.*

* the modification
![diff](https://user-images.githubusercontent.com/29013148/83882708-18f5de00-a775-11ea-8d0a-a69ef1b3f948.PNG)

* the size before and after
![compare](https://user-images.githubusercontent.com/29013148/83883382-fa441700-a775-11ea-8ed7-c6d1113a0466.PNG)

**Comment by ribasushi** [comment]
@yu-chenxi once you apply this type of stripping stacktraces/stackdumps/profiles become unusable, so I would strongly recommend not going down this road.

If the size of the final binary is problematic we could look into applying https://upx.github.io/ to the final result. Could you tun some tests with `upx --brute` see if the size reduction is satisfactory?

**Comment by yu-chenxi** [comment]
Of cource, the **size of final binary** is not problem. My issue is just a tip.
You say the runtime **stacktraces** will be missing after stripping the debug info, Really?
but the follow well-known open-source project release binaries are all stripped the debug info:
* [hugo](https://github.com/gohugoio/hugo/releases)
* [caddy](https://github.com/caddyserver/caddy/releases)

**Comment by ribasushi** [comment]
@yu-chenxi I didn't say they will be missing, I said they will become not-usable ;)

go-ipfs is still a rapidly evolving project with a lot of nits to be taken care of, especially in the network interoperability department. Being able to get a reliable stack dump of a running process is something we badly need for the time being.

Nevertheless it would be very interesting to see if UPX-packing helps here: I agree with you that the current size of the daemons is rather obnoxious :(

**Comment by yu-chenxi** [comment]
I know now the go-ipfs is immature.
Thanks for **IPFS developers' day and night efforts**.

**Comment by yu-chenxi** [comment]
@ribasushi  I know now the go-ipfs is immature.
And thanks for the **IPFS developers' day and night efforts**.
