### ISSUE TITLE
/api/v0/dns/pkg.pacman.store false-negative?

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#7439]
> This was originally found in https://github.com/ipfs-shipyard/ipfs-companion/issues/877 – cc @RubenKelevra 

#### Version information:

`go-ipfs/0.6.0-rc1/aa16952`

#### Valid DNSLink

`pkg.pacman.store` has a valid DNSLink set up on `_dnslink`:

```console
$ dig +short TXT _dnslink.pkg.pacman.store
dnslink=/ipns/QmfYwNBmDaGXP8cxTRxoSmGkYQFRFT4HjeeFjMvc9Y4KHq
```

Unsure if it is relevant, but the main hostname has TXT record which si not related to DNSLink:

```
$ dig +short TXT pkg.pacman.store
"1|https://ipfs.io/ipns/pkg.pacman.store/"
```

#### Resolv works

Recursive resolution works fine via `resolve` command:

```console
$ ipfs resolve -r /ipns/pkg.pacman.store
/ipfs/bafybeif7tmfpjaaospz2ephgmzifw66jm2foqaxcokf2zehufbvegu566y
```

and via `Host` HTTP header on public gateways:

```console
curl -Is -H 'Host: pkg.pacman.store' http://gateway.ipfs.io | grep X-Ipfs-Path
X-Ipfs-Path: /ipns/pkg.pacman.store/
```

#### /api/v0/dns/ check fails

DNSLink check itself returns false-negative for some reason (both on CLI and HTTP API) :upside_down_face: 

```console
$ ipfs dns pkg.pacman.store
Error: not a valid domain name
```

**Comment by RubenKelevra** [comment]
Do we have any outdated ACL for domains which might not include `store` as tld?

Also: I had the DNS-Link entry directly on the subdomain `pkg.`.

Which leads to the same result.

**Comment by AluisioASG** [comment]
So I built v0.6.0-rc7 with a patch to show the domain name with the error:

```diff
diff --git i/namesys/dns.go w/namesys/dns.go
index 984a27a..738612f 100644
--- i/namesys/dns.go
+++ w/namesys/dns.go
@@ -3,6 +3,7 @@ package namesys
 import (
 	"context"
 	"errors"
+	"fmt"
 	"net"
 	"strings"
 
@@ -53,7 +54,7 @@ func (r *DNSResolver) resolveOnceAsync(ctx context.Context, name string, options
 	domain := segments[0]
 
 	if !isd.IsDomain(domain) {
-		out <- onceResult{err: errors.New("not a valid domain name")}
+		out <- onceResult{err: fmt.Errorf("not a valid domain name: %s", domain)}
 		close(out)
 		return out
 	}
```

which shows that `ipfs dns` does not recurse:

```
$ ipfs dns pkg.pacman.store
Error: not a valid domain name: QmfYwNBmDaGXP8cxTRxoSmGkYQFRFT4HjeeFjMvc9Y4KHq
```

which [is documented](https://docs.ipfs.io/reference/cli/#ipfs-dns):

>   Note: This command can only recursively resolve DNS links, it will fail to recursively resolve through IPNS keys etc. For general-purpose recursive resolution, use `ipfs name resolve -r`.

and also makes this https://github.com/ipfs-shipyard/ipfs-companion/issues/288.

**Comment by gileri** [comment]
Looks like the same issue as described in #6454

**Comment by RubenKelevra** [comment]
> Looks like the same issue described in #6454

You're right. This one is a duplicate.

@lidel can you close one of the two tickets?

Additionally, I've changed the subdomain layout a bit, the same service is now available under:

`x86-64.archlinux.pkg.pacman.store`

**Comment by RubenKelevra** [comment]
@AluisioASG wrote:
> Because I'm having the same problem with my domain (aasg.name), I built v0.6.0-rc7 with a patch to show the domain name with the error

Sounds like an improvement, mind doing a PR?

**Comment by lidel** [comment]
@AluisioASG please open a PR with your change, it will be useful

I'm closing this one, let's continue in https://github.com/ipfs/go-ipfs/issues/6454#issuecomment-739055758
FYSA this issue no longer impacts IPFS Companion, we switched to `name resolve`: https://github.com/ipfs-shipyard/ipfs-companion/pull/959
