### ISSUE TITLE
remove identity from config file. place private, public keys in id, id.pub files

### ISSUE THREAD

**Issue by briantigerchow** [ipfs/go-ipfs#744]
connected to #783

WIP: https://github.com/jbenet/go-ipfs/tree/feat/identity

- [x] create FSRepo.Identity component
- [x] write files to `id`, `id.pub` files
- [x] read identity into memory (*Config)

**Comment by briantigerchow** [comment]
@jbenet @whyrusleeping @cryptix 

**code**

On branch https://github.com/jbenet/go-ipfs/tree/feat/identity, ipfs learns to read and write the `Identity` from `id` and `id.pub` files in the IPFS_PATH.

**compatibility**

Presently, It is not backwards compatible with old configs/repos.

Old configs must be updated:

1. read Identity from `config`
2. write Identity to `id`, `id.pub`
3. finally, overwrite `config` file with Identity erased

From here forward, this is referred to as the _update procedure_.

**proposal**

I see a couple ways to provide backward compatibility.

a) Provide a command/script/tool allowing user to manually perform the update procedure.

pros: puts user in control
cons: inconvenient. commands will fail

b) During normal operation, if old config is detected, let ipfs silently perform update procedure.

pros: least painful for the user
cons: complexity is shifted to code; users might find this behavior surprising

Thoughts?

**Comment by jbenet** [comment]
I like the ssh keys approach. But we need to have sets of keys, not just one. AFAIK only one key per file in ssh, so we'd need a way to account for them.

Then again,  the widest system in use is pgp/gpg keyrings (`.pubring.gpg` and `.secring.gpg`) which many people in infrastructure world use for deployments / signing + validating binaries, etc:
- https://www.gnupg.org/gph/en/manual.html
- http://irtfweb.ifa.hawaii.edu/~lockhart/gpg/gpg-cs.html
- https://github.com/xordataexchange/crypt by kelseyhightower (now at coreos)
- https://www.youtube.com/watch?v=zYpqqfuGwW8

--- 

On making backwards incompatible changes to repos, please see:
- https://github.com/jbenet/go-ipfs/issues/537
- https://github.com/jbenet/random-ideas/issues/33

We write the upgrade/downgrade tool, and run it automatically as part of the upgrade procedure (which can be run at the beginning when launching new versions for the first time), but user can step in manually and run the tools to fix things if needed.

**Comment by whyrusleeping** [comment]
keys will soon be stored in the blockstore, once it can be 'private'
