### ISSUE TITLE
Migration from v9 to v10 ends up with duplicate swarm-listening definitions

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7444]
I tried to use the v9 to v10 migration on two nodes, in both cases there was already a QUIC listening definition in the swarm-listening array.

The migration added an identical secondary listening entry for QUIC (twice, one for IPv4 one for IPv6).

On the first node, this ended up with just a weird config, since the port is random:

```
    "Swarm": [
      "/ip4/0.0.0.0/tcp/0",
      "/ip6/::/tcp/0",
      "/ip4/0.0.0.0/udp/0/quic",
      "/ip6/::/udp/0/quic",
      "/ip4/0.0.0.0/udp/0/quic",
      "/ip6/::/udp/0/quic"
    ]
```

On the secondary node this is ending up with this duplicate entries:

```
    "Swarm": [
      "/ip4/0.0.0.0/tcp/443",
      "/ip6/::/tcp/443",
      "/ip4/0.0.0.0/udp/443/quic",
      "/ip6/::/udp/443/quic",
      "/ip4/0.0.0.0/udp/443/quic",
      "/ip6/::/udp/443/quic"
    ]
```

## Proposed solution

If there's any quic definition in the listing ports, just skip this migration step.

**Comment by Stebalien** [comment]
Hm. That's what _should_ have happened. Thanks for catching this!

**Comment by Stebalien** [comment]
Ah, I see. The check was buggy.

**Comment by Stebalien** [comment]
Very buggy.
