### ISSUE TITLE
Huge badger data store

### ISSUE THREAD

**Issue by sidenaio** [ipfs/go-ipfs#7454]
#### Version information:
ipfs-go v0.5.2-0.20200520231924-554a21b64784

#### Description: 
After badgerDS was introduced as stable in 0.5.0,  we started to use badgerDs as a default datastore. It gives us better synchronization speed, but the size of that datastore grows unexpectedly. 
For the last two weeks, we have ~500mb of live data. But on one node the datastore contains 18GB. 
The node that worked with badger ~ 1 month has 120GB datastore. 

Looks like badger creates a lof of vlog files. 

![image](https://user-images.githubusercontent.com/50700001/84261699-aa7a9c80-ab35-11ea-9941-36517973ef90.png)

![image](https://user-images.githubusercontent.com/50700001/84261749-be260300-ab35-11ea-9b16-c035cdb29b36.png)

Maybe this problem caused by [our way](https://github.com/idena-network/idena-go/blob/master/ipfs/ipfs.go#L179)  to call corerepo.ConditionalGC.  We invoke corerepo.ConditionalGC every 15 seconds. To prevent big delay in read\write operations we cancel GC invocation if any read\write operation appears.

**Comment by ridenaio** [comment]
So, they will release both v1 and v2 versions? This [bugfix upstream](https://github.com/dgraph-io/badger/commit/fd8989493b52f39957e89ff3a7679bc45ea92674) was merged only into v2.

**Comment by ridenaio** [comment]
We've forked badger repo, [added](https://github.com/sidenaio/badger/commit/92fce499d15c34ab0c3065b799a0d1890f8df2eb) this fix and [replaced package](https://github.com/idena-network/idena-go/commit/880cf2498dd9ab1a49408bb9eda2a19fd34140ed). 

We ran the app, and made a screen on start
![photo_2020-06-11_17-15-49](https://user-images.githubusercontent.com/50695987/84384388-54762980-ac07-11ea-8d5e-c522bd7c4d0c.jpg)


it worked for several minutes and we saw this:

![photo_2020-06-11_17-18-35](https://user-images.githubusercontent.com/50695987/84384614-aa4ad180-ac07-11ea-8ae8-6fd42252c6f7.jpg)

In less than 2 minutes `000018.vlog` file size was increased by more than **1gb**. Other `vlog` files remained the same.

After 3 hours, nothing changed. All `vlog` files are still in place.

**Comment by RubenKelevra** [comment]
Hey @ridenaio,

There's a ticket tracking the progress of the fix for badger v1:

https://github.com/dgraph-io/badger/issues/1362

I'm sorry, but I'm afraid that this is the wrong place to ask for support for badger.

As far as I know:

New writes are are expected to be written to value logs, which are by default up to 1 GB. the garbage collector will clean them up if they reach a certain threshold of not containing useful data anymore.

Maybe add a support ticket on the badger repo or wait for the release which is expected shortly and will be included in ipfs :)

**Comment by aschmahmann** [comment]
Any idea if this can be closed given that we're now using go-ds-badger v0.2.5 which uses badger v.1.6.2?

**Comment by sidenaio** [comment]
Yes, we've tried 1.6.2 and it shows better GC.
