### ISSUE TITLE
TCP/IPv6 reset issues

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7455]
## Version

master @ 970a0b414

## Description

I run an external monitoring service on one of my IPFS nodes.

The service tries to ping IPv4/6 and a TCP connect on the IPv4/6 port of the IPFS daemon.

While IPv4 TCP connect, and the pinging works with no outages, the IPv6 TCP connect have regular outages of some minutes.

The outage has to be confirmed by 10 servers (of this provider) to be triggered. So ipfs or the server fails to answer 10 times in a row.

So something isn't working right for IPv6.

How the history looks like for this:

![Screenshot_20200610-153054__01](https://user-images.githubusercontent.com/614929/84280669-e6aefc80-ab37-11ea-8708-7cc3160a49d0.jpg)

**Comment by RubenKelevra** [comment]
> * What's the output of `ipfs id`?

```
{
        "ID": "QmWsTDap1zmaVLRaUFKBmo25ST6MGtjZQBAT2u72wz4Qma",
        "PublicKey": "CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCsT0oWp56ss9emH6vFpV2LfbWuZ+aqNfcY+/8vzyTbeoy1cCeTd5KpvRm7AipRHYu2oJHmgFFYPR3xzKGGltjklinfn7tOp3EPUxQwQ/Be4QEjNJ0w4OTH0uRP4Drz9rpjo+nE38UpaJWUbANJl7E90hIM1tJC+4ZMC77zxQeMaZx/pCXdxakWaVxfVPIZ89/LXInAXNjLs0kHslV5DgYM/ncP23Cf14jRebidE56H8yQ0TibNe7SyHwuh4+4r5LvQ7wMq0A0lNj7T63A0dmwvGzxSyxBjMhJDatKBMEGpPrRAwrPboaA+HuCqkEdkkKKg/Zs/7FKa+CjHK5jdNgBAgMBAAE=",
        "Addresses": [
                "/ip4/127.0.0.1/tcp/443/p2p/QmWsTDap1zmaVLRaUFKBmo25ST6MGtjZQBAT2u72wz4Qma",
                "/ip4/194.59.205.143/tcp/443/p2p/QmWsTDap1zmaVLRaUFKBmo25ST6MGtjZQBAT2u72wz4Qma",
                "/ip6/::1/tcp/443/p2p/QmWsTDap1zmaVLRaUFKBmo25ST6MGtjZQBAT2u72wz4Qma",
                "/ip6/2a03:4000:34:5c2::f3/tcp/443/p2p/QmWsTDap1zmaVLRaUFKBmo25ST6MGtjZQBAT2u72wz4Qma",
                "/ip4/127.0.0.1/udp/443/quic/p2p/QmWsTDap1zmaVLRaUFKBmo25ST6MGtjZQBAT2u72wz4Qma",
                "/ip4/194.59.205.143/udp/443/quic/p2p/QmWsTDap1zmaVLRaUFKBmo25ST6MGtjZQBAT2u72wz4Qma",
                "/ip6/::1/udp/443/quic/p2p/QmWsTDap1zmaVLRaUFKBmo25ST6MGtjZQBAT2u72wz4Qma",
                "/ip6/2a03:4000:34:5c2::f3/udp/443/quic/p2p/QmWsTDap1zmaVLRaUFKBmo25ST6MGtjZQBAT2u72wz4Qma"
        ],
        "AgentVersion": "go-ipfs/0.6.0-dev/",
        "ProtocolVersion": "ipfs/0.1.0"
}
```

> * What's the output of `ip addr`?

```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 8a:06:86:e5:f7:4b brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3
    inet 194.59.205.143/22 brd 194.59.207.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2a03:4000:34:5c2::f3/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::8806:86ff:fee5:f74b/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by Stebalien** [comment]
Ok, I was concerned we might be filtering out your address and advertising the wrong ones. That's not the case.

This looks like an issue with your network, not go-ipfs. What happens if you just open a TCP connection using IPv6 and leave it there?

**Comment by RubenKelevra** [comment]
> This looks like an issue with your network, not go-ipfs. What happens if you just open a TCP connection using IPv6 and leave it there?

Well I've run a IPv6 ping to this machine the other day: Lithuania <-> this server

Packet loss was 0.04 % over 24h.

I'll try some more diagnostics tomorrow and report back.

**Comment by Stebalien** [comment]
Packet loss isn't going to cause TCP resets.

**Comment by RubenKelevra** [comment]
Well, yeah. I expected that maybe there are routing errors which end up with icmps destination unreachable.

This could cause those resets from an L4 router in the path. (I hate this blackboxes) 🙄

I'll investigate in the next days to pinpoint it down, so far I couldn't find a cause.

**Comment by Stebalien** [comment]
Ah, yes, black boxes....

**Comment by RubenKelevra** [comment]
Okay, there's some non-persistant weird issue on the network side. But I can confirm that this isn't a go-ipfs issue. :)
