### ISSUE TITLE
Socket activation via Unix Domain Sockets 

### ISSUE THREAD

**Issue by Ericson2314** [ipfs/go-ipfs#7463]
It looks like:
 1. #6675 adds support for socket activation via tcp
 2. #6678 adds support unix domain sockets

But there is no support for socket activation via unix domain sockets. I would like this. Is this something people would be interested in adding?

**Comment by Stebalien** [comment]
This already works. Just add `ListenStream=/path/to/my.socket` to your systemd socket unit.

**Comment by Ericson2314** [comment]
@Stebalien awesome! Do I need to specify the path anywhere else e.g. `ipfs config`, is the new line in `socket unit` sufficient?

**Comment by Stebalien** [comment]
You don't need to specify anything in your config unless you want to. If you _do_ specify the socket in your config, go-ipfs will listen on that socket even when the systemd socket unit is disabled but that's not necessary.

**Comment by Ericson2314** [comment]
Alright, thanks so much!!
