### ISSUE TITLE
ipfs migration without starting the daemon

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7471]
Currently, it seems to be impossible to do a migration (if necessary) without starting the daemon. 

I'm a package maintainer and like script the migration after installation of the new package instead of running the migration on the first run of the daemon, which - as discussed earlier in a PR - might hit the timeout of systemd for starting a service.

I like to have an `ipfs migrate --assume-yes` or something like this for unattended migration while updating a package with a package manager.

It should return 0 if everything is fine, regardless if a migration was necessary or not.

**Comment by RubenKelevra** [comment]
This would solve https://github.com/ipfs/go-ipfs/issues/7269

**Comment by Stebalien** [comment]
You can run the migration tool: https://dist.ipfs.io/#fs-repo-migrations.
Or you can use `ipfs update` to update, which will apply the migration when it installs the new version.

**Comment by RubenKelevra** [comment]
> You can run the migration tool: https://dist.ipfs.io/#fs-repo-migrations.

This requires quite some boiler plating, which is already integrated into the ipfs-binary, to be used by `ipfs daemon --migrate`.

> Or you can use `ipfs update` to update, which will apply the migration when it installs the new version.

This doesn't work, I build the binary from git. So it makes no sense for me to fetch an older version.

**Comment by Stebalien** [comment]
Fair enough. I agree we should add an `ipfs migrate` command (probably `ipfs repo migrate`).

**Comment by Stebalien** [comment]
Command:

```
USAGE
  ipfs repo migrate - Apply any outstanding migrations to the repo.

SYNOPSIS
  ipfs repo migrate [--allow-downgrade]

OPTIONS
  --allow-downgrade bool - Allow downgrading to a lower repo version
```

This command should:

1. Refuse to run when the daemon is online. Add a line to the `cmdDetailsMap` in `cmd/ipfs/ipfs.go` specifying `cannotRunOnDaemon: true`.
2. Opens the repo (see how `fsrepo.Open` is used in `cmd/ipfs/daemon.go`).
3. Checks to see if there's a "needs migration" error (again, look at `cmd/ipfs/daemon.go`).
4. If so, runs `migrate.RunMigration` (see `cmd/ipfs/daemon.go` again).

**Comment by aschmahmann** [comment]
Note: state of this issue is that this is blocked pending a refactor of fs-repo-migrations (i.e. https://github.com/ipfs/fs-repo-migrations/issues/98) such that we're using many binaries instead of one. This will mean that calling `ipfs repo migrate` will get and run each of the migration binaries required and become the primary way to do manual migrations.
