### ISSUE TITLE
Config inconsistent at runtime

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#7481]
#### Version information:

> v0.5.1

#### Description:

The config attached to the command context is _not_ the same config returned by `repo.Config()`. The commands context should just ask the repo for the config.

**Comment by schomatis** [comment]
@Stebalien Could you provide a code example, please?

**Comment by BigLep** [comment]
@Stebalien : do you have more input here so this can be actioned?

**Comment by BigLep** [comment]
2022-03-11 conversation: end goal is to make it crystal clear for users on whether they need to reboot or not when making config changes.

For priority determination, it would useful to know how many users are snagged by this issue.
