### ISSUE TITLE
File/folder versioning

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7486]
There's been a long ongoing discussion to add versioning to IPFS, this is the feature request keep track of the progress to add file/folder versioning.

As mentioned on the [notes ticket](https://github.com/ipfs/notes/issues/23) we could add optional binary patches with zstd, which would enable us save just the backward facing diffs and the newest version of a file.

Folders could be diffed as well, which obviously makes sense on very large folders, but not sure how this would conflict with sharding.

**Comment by Stebalien** [comment]
The go-ipfs issue tracker tracks issues/features of the go implementation, not protocol changes. This feature will need a concrete proposal and consensus to proceed.

Honestly, it's probably blocked on better [IPLD tooling](https://github.com/ipld/go-ipld-prime) (in go-ipfs, at least) and finally landing UnixFSv2.

**Comment by RubenKelevra** [comment]
Okay :)
