### ISSUE TITLE
"max_size" for add operations that fetch from an external source

### ISSUE THREAD

**Issue by obo20** [ipfs/go-ipfs#7489]
When adding content to an IPFS node from an external source such as in the following situations:
* adding content via a url via `ipfs add {url}`
* adding a pin by its CID via `ipfs pin add {cid}`

It would be super helpful to have a "max_size" option that you can pass in to limit the size of any potential files being added, specifically when utilizing the pin by url functionality of `ipfs add` (since you can't get object state before downloading like you can with a CID).

**Comment by Stebalien** [comment]
For `ipfs add URL`, `curl URL | dd bs=1MiB count=N | ipfs add` is probably simpler unless you're using the URLStore.

However, for `ipfs pin add`, I can see this being very useful. Personally, I'd have this count the space used by all blocks referenced by the root, after deduplication. SGTY?

**Comment by aschmahmann** [comment]
@obo20 does the above suggestion work for you (i.e. CLI manipulation for add and go-ipfs based solution for pin add)?

**Comment by BigLep** [comment]
Closing since haven't heard back.
