### ISSUE TITLE
`ipfs cat` should allow ipns paths.

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#750]
We need to go through the entire cli and make sure everything (or almost everything) that should take a path should work with `/ipfs/...` and `/ipns/...`.

`ipfs cat` doesnt:
```
ipfs cat /ipns/QmNaFWP1vMk57i62PugNTPY3RBDYP66B6Ek3xnHCQYD8ui
```

gateway works though! :) http://gateway.ipfs.io/ipns/QmNaFWP1vMk57i62PugNTPY3RBDYP66B6Ek3xnHCQYD8ui

**Comment by whyrusleeping** [comment]
this works
