### ISSUE TITLE
Please, support dynamic webapps, such as PHP, Python, Ruby, Golang, etc.

### ISSUE THREAD

**Issue by heroku-miraheze** [ipfs/go-ipfs#7500]
Please, support dynamic webapps, such as PHP, Python, Ruby, Golang, etc.
IPFS does not support actually dynamic webapps, but we need to support it to host PHP, Python, Ruby, Golang, etc.
Thank you.

**Comment by Stebalien** [comment]
Traditional web backends require traditional centralized servers and can't run on IPFS. Web3/dapps need to be re-written to work without these centralized servers (or you'll need to host these centralized services on a standard webserver).
