### ISSUE TITLE
something depends on hsanjuan/go-libp2p-http in 0.5.1

### ISSUE THREAD

**Issue by ec1oud** [ipfs/go-ipfs#7513]
I'm trying to build ipfs on a GnuBee running OpenWrt; the golang package is 1.13 so that limits me to something older than the latest ipfs, so I checked out the v0.5.1 git tag.

```
$ make nofuse
go: github.com/ipfs/go-ipfs/cmd/ipfs imports
	github.com/ipfs/go-ipfs/core/corehttp imports
	github.com/hsanjuan/go-libp2p-http: github.com/hsanjuan/go-libp2p-http@v0.1.5: parsing go.mod:
	module declares its path as: github.com/libp2p/go-libp2p-http
	        but was required as: github.com/hsanjuan/go-libp2p-http
go version go1.13.12 linux/mipsle
bin/check_go_version 1.13.8
plugin/loader/preload.sh > plugin/loader/preload.go
go fmt plugin/loader/preload.go >/dev/null
go: github.com/ipfs/go-ipfs/cmd/ipfs imports
	github.com/ipfs/go-ipfs/core/corehttp imports
	github.com/hsanjuan/go-libp2p-http: github.com/hsanjuan/go-libp2p-http@v0.1.5: parsing go.mod:
	module declares its path as: github.com/libp2p/go-libp2p-http
	        but was required as: github.com/hsanjuan/go-libp2p-http
go build  "-asmflags=all='-trimpath=/home/rutledge/src/go'" "-gcflags=all='-trimpath=/home/rutledge/src/go'" -ldflags="-X "github.com/ipfs/go-ipfs".CurrentCommit=8431e2e87" -tags="nofuse" -o "cmd/ipfs/" ""
go build: no main packages to build
make: *** [cmd/ipfs/Rules.mk:22: cmd/ipfs/] Error 1
```

But github is redirecting https://github.com/hsanjuan/go-libp2p-http to https://github.com/libp2p/go-libp2p-http now, so I guess that's why this started happening.

**Comment by hsanjuan** [comment]
In v0.5.1 that library is correctly imported as libp2p/go-libp2p-http: https://github.com/ipfs/go-ipfs/blob/v0.5.1/core/corehttp/p2p_proxy.go#L14

Double-check your setup, as this should not be happening.

**Comment by ec1oud** [comment]
I only saw this problem with 0.5.1, but not with 0.5.0.

Compiling and linking on the device turned out to be hopeless with only 512MB anyway: even after adding 2GB of swap, it would run out of memory and reboot every time, with or without using cgo.  Cross-compiling at first did not result in a runnable executable, which is why I was trying to compile on there... but that was because I didn't know about the softfloat option.  `GOARCH=mipsle GOOS=linux GOMIPS=softfloat make nofuse` works, so now I have 0.6.0 running on the GnuBee, and only taking about 50MB memory at startup.

**Comment by hsanjuan** [comment]
Nice to hear, still unsure what caused the problem in the first place.
