### ISSUE TITLE
The object put endpoint returns a status code 500 when additional fields are present in the payload

### ISSUE THREAD

**Issue by odisseus** [ipfs/go-ipfs#7520]
#### Version information:
go-ipfs version: 0.6.0-d6e036a88
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4

#### Description:
This request works correctly:
```
$ curl -X POST -i  -F data=@in1.json "http://127.0.0.1:5001/api/v0/object/put"
HTTP/1.1 200 OK
Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
Content-Type: application/json
Server: go-ipfs/0.6.0
Trailer: X-Stream-Error
Vary: Origin
Date: Fri, 03 Jul 2020 01:03:30 GMT
Transfer-Encoding: chunked

{"Hash":"QmRrqNYPLSvM4AiodsQAtT3EKyVSMhdBHdzhsaMeJ1BBa6"}
```

```
$ cat in1.json 
{
    "Data": "Hello DAG!",
    "Links": []
}

```

Adding an additional field to the payload results in an error 500:
```
$ curl -X POST -i  -F data=@in2.json "http://127.0.0.1:5001/api/v0/object/put"
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
Content-Type: application/json
Server: go-ipfs/0.6.0
Trailer: X-Stream-Error
Vary: Origin
Date: Fri, 03 Jul 2020 01:04:06 GMT
Transfer-Encoding: chunked

{"Message":"json: unknown field \"foo\"","Code":0,"Type":"error"}
```

```
$ cat in2.json 
{
    "Data": "Hello DAG!",
    "Links": [],
    "foo": "bar"
}
```

To my understanding, in the latter case the server should either return a normal response (ignoring the additional field) or return an error 400 (because the cause of the problem is a bad request).

**Comment by Stebalien** [comment]
The HTTP API is an RPC API and doesn't follow REST semantics. It returns HTTP status codes to indicate RPC transport level errors:

* 200 - Success (may be followed by a trailing header indicating a late error later).
* 404 - RPC endpoint doesn't exist.
* 400 - argument invalid (bad flag).
* 500 - Application level error.

At the RPC transport level, the request was a valid and expected byte stream.

**Comment by odisseus** [comment]
I still don't understand why an adding one more field in the payload turns a "success" into an "application level error". Shouldn't the additional field be just ignored?

**Comment by Stebalien** [comment]
The object is invalid. Ignoring the extra field would mean silently throwing away data. If the user passed `{"dataa": ...}`, we wouldn't want to throw away data and store an empty object just because a key is misspelled.

**Comment by odisseus** [comment]
Does this apply to all endpoints? Do I understand correctly that every endpoint which accepts JSON objects will reject objects that have additional fields?

**Comment by Stebalien** [comment]
It depends on the endpoint. Most endpoints don't accept JSON input at all (normal arguments are passed in the query string).

The other case I know of is `ipfs dag put`. If you try to call `ipfs dag put` with a field not allowed by the specified format, it'll reject the request.

**Comment by odisseus** [comment]
Speaking of the allowed fields: is there a formal specification (e. g. something like Swagger) of the entire HTTP interface of the daemon?

**Comment by Stebalien** [comment]
There are the auto-generated API docs (https://docs.ipfs.io/reference/http/api/) and (https://github.com/ipfs/go-ipfs/blob/master/docs/implement-api-bindings.md).
