### ISSUE TITLE
IPNS republisher ignores existing EOLs

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/go-ipfs#7537]
It looks like the IPNS republisher ignores the EOL set in the original record.

Say Alice creates an IPNS record with and EOL of 10 years from now, but has a republisher rate of 4 hours. Alice will end up republishing a record with the same sequence number, path, TTL, etc. but with a shorter EOL (i.e. the `Ipns.RecordLifetime` set in the config file, which defaults to 24 hours).

This might just be as simple a fix as correcting these few lines, but we should check it out to be sure.

https://github.com/ipfs/go-ipfs/blob/231fab811d83322e61fe8d9c65d7bcd9fd6d243c/namesys/republisher/repub.go#L137-L139

@Stebalien thoughts?

**Comment by Stebalien** [comment]
Yeah, this just looks like a big.
