### ISSUE TITLE
Improve publishing of observable addresses

### ISSUE THREAD

**Issue by rklaehn** [ipfs/go-ipfs#7538]
We have a problem where a go-ipfs node that runs from inside a container does not properly publish its own observed address. This is in a relatively small private swarm.

It seems like the current heuristics is 3 dials within 10 minutes:

@hsanjuan said on slack:
> there is a threshold of having like 3 successful connections withing a 10 minute time frame for an external IP to show up there (when not discovered by autonat etc).

The heuristics for when to publish externally observed addresses could be improved for this case.

@Stebalien suggested on slack:
> It needs confirmations from multiple observers before it starts reporting them. But we should probably change that when we have few observations. For example, if we have fewer than 8 observations for any given address, we could continue to advertise all observed addresses. Once we get 8+ distinct observations for a given address, we'd stop. Could you file an issue in go-libp2p?

**Comment by aschmahmann** [comment]
Moved this issue to go-libp2p.

Also, for such a small network would you be able to use manually configured addresses  https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#addressesannounce?
