### ISSUE TITLE
Subdomain gateway redirect ipns key to libp2p-key base32 instead of libp2p-key base36

### ISSUE THREAD

**Issue by xmaysonnave** [ipfs/go-ipfs#7544]
#### Version information:
go-ipfs version: 0.6.0
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4

1 - Initial key gen cidv0 ed25519 
[cidv0 ed25519](https://cid.ipfs.io/#12D3KooWQmkZNHTPWio9bRF2VjHq7WvBnKtbTocpNPddqqiFYM4w)
Converted in libp2p-key cidv1 base32
[libp2p-key cidv1 base32](https://cid.ipfs.io/#bafzaajaiaejcbxrt4db3xaqro23sjw4v2imrj2gvu47udglwbrovzave4orrkaam)
Converted in libp2p-key cidv1 base 36
[libp2p-key cidv1 base 36](https://cid.ipfs.io/#k51qzi5uqu5dlpyo95fcwr39ox3gauhvduks5o726m9t9r7cszpowe1x6lj5l8)

2 - First test with a public gateway who do not support yet subdomains
The three urls are resolved. Each page is loaded and displayed
[cidv0 ed25519](https://gateway.ipfs.io/ipns/12D3KooWQmkZNHTPWio9bRF2VjHq7WvBnKtbTocpNPddqqiFYM4w)
[libp2p-key cidv1 base32](https://gateway.ipfs.io/ipns/bafzaajaiaejcbxrt4db3xaqro23sjw4v2imrj2gvu47udglwbrovzave4orrkaam)
[libp2p-key cidv1 base 36](https://gateway.ipfs.io/ipns/k51qzi5uqu5dlpyo95fcwr39ox3gauhvduks5o726m9t9r7cszpowe1x6lj5l8)

3 - Second test with a public gateway who support subdomains

[cidv0 ed25519](https://dweb.link/ipns/12D3KooWQmkZNHTPWio9bRF2VjHq7WvBnKtbTocpNPddqqiFYM4w)
redirects to 
https://bafzaajaiaejcbxrt4db3xaqro23sjw4v2imrj2gvu47udglwbrovzave4orrkaam.ipns.dweb.link/
The page is not loaded

[libp2p-key cidv1 base32](https://dweb.link/ipns/bafzaajaiaejcbxrt4db3xaqro23sjw4v2imrj2gvu47udglwbrovzave4orrkaam)
redirects to
https://bafzaajaiaejcbxrt4db3xaqro23sjw4v2imrj2gvu47udglwbrovzave4orrkaam.ipns.dweb.link/
The page is not loaded

[libp2p-key cidv1 base 36](https://dweb.link/ipns/k51qzi5uqu5dlpyo95fcwr39ox3gauhvduks5o726m9t9r7cszpowe1x6lj5l8)
redirects to
https://bafzaajaiaejcbxrt4db3xaqro23sjw4v2imrj2gvu47udglwbrovzave4orrkaam.ipns.dweb.link/
The page is not loaded

4 - Third test
[libp2p-key cidv1 base 36](https://k51qzi5uqu5dlpyo95fcwr39ox3gauhvduks5o726m9t9r7cszpowe1x6lj5l8.ipns.dweb.link)
The page is loaded as expected.

Thanks

**Comment by xmaysonnave** [comment]
As a final test. on my local ipfs server the tests are consistent.
- localhost:8080 redirects an ipns key to its libp2p-key base32 representation and fails to load
- 127.0.0.:80801 loads the three cid representations
Thanks

**Comment by aschmahmann** [comment]
This should be resolved by https://github.com/ipfs/go-ipfs/pull/7441
