### ISSUE TITLE
Chunk size >1M hides add progress bar

### ISSUE THREAD

**Issue by Artoria2e5** [ipfs/go-ipfs#7555]
#### Version information:
```
go-ipfs version: 0.6.0
Repo version: 10
System version: amd64/darwin
Golang version: go1.14.4
```

#### Description:
I am trying to add a large file on my slow computer, so it is quite important to be able to see a progress bar. However, it seems that a chunk size larger than 1M makes the progress bar never show up:
```
# shows progress bar
ipfs add -p --chunker=size-1048576 wikipedia_zh_all_maxi_2020-07.zim 
# no progress bar
ipfs add -p --chunker=size-1048577 wikipedia_zh_all_maxi_2020-07.zim
```

Something similar happens with the content-based hashes, but they are a bit harder to stably trigger. The buzhash thing seems to almost always trigger though.

**Comment by Artoria2e5** [comment]
Okay, the comment about buzhash seems to be a case of the error message not showing up instead. Who know running the daemon creates this sort of trouble...

**Comment by aschmahmann** [comment]
@Artoria2e5 are you not seeing an error? When I run the your command I get this:

```
ipfs add -p --chunker=size-1048577 .\file

Error: chunker parameters may not exceed the maximum chunk size of 1048576
```

**Comment by Artoria2e5** [comment]
Oh, that makes sense given my comment about buzhash. Apparently on my build, the errors never show up if the daemon is running; `htop` would only show some very busy `ipfs` processes. I guess that's a bug in itself.

**Comment by aschmahmann** [comment]
Interesting. If you're able to give more information onto your setup and what's going on (what types of errors you can see and not) feel free to open a new issue on error logging. I'm going to close this issue though since it's not a problem.
