### ISSUE TITLE
High CPU/RAM and spamming DHT errors: "ignoring incoming dht message while not in server mode"

### ISSUE THREAD

**Issue by hazae41** [ipfs/go-ipfs#7573]
#### Version information:

go-ipfs version: 0.6.0
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4

#### Description:
Today, I noticed a high CPU/RAM usage on my server.
I watched the daemon logs and saw nothing but the following error.
It was spammed yesterday (with a few seconds interval) until 07:24:37, I can't go up to see when it started.

> 2020-08-02T07:24:37.300Z
ERROR
dhtgo-libp2p-kad-dht@v0.8.2/dht_net.go:87
ignoring incoming dht message while not in server mode

**Comment by aschmahmann** [comment]
@hazae41there's not really enough information here to determine why you have high CPU/RAM usage. Could you give more background as to your setup? What does your config look like `ipfs config show`, what addresses do you see with `ipfs id`, are you behind a NAT, on a cloud setup, etc.?

The error "ignoring incoming dht message while not in server mode" occurs when your DHT is in client mode and yet other people on the network think you should be in server mode. This switching between client and server can occur if you manually restart your node as a DHT client (e.g. you were running a publicly accessible default node and then restarted it and ran it with `--routing=dhtclient` which is the default for IPFS Desktop. Additionally, it can occur automatically if your network connectivity is interrupted (e.g. router/ISP issues) that causes your node to switch into client mode since it no longer thinks it's accessible by the rest of the network.

@willscott @Stebalien any ideas here?

**Comment by hazae41** [comment]
@aschmahmann I don't think the problem comes from my config since I left it untouched.

The daemon is running on a cheap hosted VPS with the 4001 port opened on TCP and UDP on both IPv4 and IPv6.


This is the output of "ipfs id"

```
{
        "ID": "QmNUDMycSZLUdbKcZTN5ynX8LYrwL32ZkU5cKN7JDC4459",
        "PublicKey": "CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQClYGZ8zD6Arb1nF4CsY3RTSnlNYGIPxxRkx8EIciXilLffo0+JEyO9Ayk99nbbQTKt7sRylQ5rqnxRFiB+VaWIE1RhH4uBQltXhRxAaZBYNaVz1mGmVgzj0xbPMjd1zB+bK/E9T6SJSjZasGhkalpmT3s5XA1F3mPwBmguQq1vgwnxdHxy3NQ3dvLQ9tTuuuLvstzMmP7RFnbjI5hCC5h0KkMzFlW/u8cLp1FRr75Y/PtKJdpZjY6hW6jtBA/PEurEe8nPoFV9A0dNYpYMjrxc+hSW9f2+ExrIE9MTBm65V8z6fYLZIV0i/kEHUIVLjk4+5j6WIwNLtzNlNPSiFX4HAgMBAAE=",
        "Addresses": [
                "/ip4/127.0.0.1/tcp/4001/p2p/QmNUDMycSZLUdbKcZTN5ynX8LYrwL32ZkU5cKN7JDC4459",
                "/ip4/217.160.255.130/tcp/4001/p2p/QmNUDMycSZLUdbKcZTN5ynX8LYrwL32ZkU5cKN7JDC4459",
                "/ip6/::1/tcp/4001/p2p/QmNUDMycSZLUdbKcZTN5ynX8LYrwL32ZkU5cKN7JDC4459",
                "/ip6/2001:8d8:1800:837f::1/tcp/4001/p2p/QmNUDMycSZLUdbKcZTN5ynX8LYrwL32ZkU5cKN7JDC4459",
                "/ip4/127.0.0.1/udp/4001/quic/p2p/QmNUDMycSZLUdbKcZTN5ynX8LYrwL32ZkU5cKN7JDC4459",
                "/ip4/217.160.255.130/udp/4001/quic/p2p/QmNUDMycSZLUdbKcZTN5ynX8LYrwL32ZkU5cKN7JDC4459",
                "/ip6/::1/udp/4001/quic/p2p/QmNUDMycSZLUdbKcZTN5ynX8LYrwL32ZkU5cKN7JDC4459",
                "/ip6/2001:8d8:1800:837f::1/udp/4001/quic/p2p/QmNUDMycSZLUdbKcZTN5ynX8LYrwL32ZkU5cKN7JDC4459"
        ],
        "AgentVersion": "go-ipfs/0.6.0/",
        "ProtocolVersion": "ipfs/0.1.0"
}
```

**Comment by aschmahmann** [comment]
Your node seems to currently be acting as a DHT server. Are you still getting those error messages?

**Comment by hazae41** [comment]
@aschmahmann No, it just happened one time

**Comment by hazae41** [comment]
Still happening

![image](https://user-images.githubusercontent.com/4405263/89730341-0a11fd00-da3e-11ea-9b1d-b6f1c97a3b6d.png)

**Comment by jacobheun** [comment]
@hazae41 can you dump your config `ipfs config show`, along with a pprof dump? While the dht error logs are a problem, they may be a red herring for the cpu issue.

**Comment by hazae41** [comment]
`{
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Methods": [
        "PUT",
        "POST"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    }
  },
  "Addresses": {
    "API": "/ip6/::/tcp/5001",
    "Announce": [],
    "Gateway": [
      "/ip4/0.0.0.0/tcp/8080",
      "/ip6/::/tcp/8080"
    ],
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip6/::/udp/4001/quic"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"
  ],
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Experimental": {
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "ShardingEnabled": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "QmNUDMycSZLUdbKcZTN5ynX8LYrwL32ZkU5cKN7JDC4459"
  },
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Type": "dht"
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 900,
      "LowWater": 600,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "EnableAutoRelay": false,
    "EnableRelayHop": false,
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}`

How do I make a pprof dump?

**Comment by jacobheun** [comment]
> How do I make a pprof dump?

Take a look at the debug guide https://github.com/ipfs/go-ipfs/blob/master/docs/debug-guide.md#general-performance-debugging-guidelines

**Comment by kuzdogan** [comment]
How were you able to resolve this @hazae41 This is causing massive resource consumption on our side and couldn't find a solution to this. Tried switching the server profile on `ipfs init --profile server` but no help

**Comment by hazae41** [comment]
> How were you able to resolve this @hazae41 This is causing massive resource consumption on our side and couldn't find a solution to this. Tried switching the server profile on `ipfs init --profile server` but no help
> 
> 
> 
> Our config: https://gist.github.com/kuzdogan/c1d69dabafc8286f31afc8bb988099b8

No, sorry 😞

**Comment by Man-Jain** [comment]
https://discuss.ipfs.tech/t/spamming-dht-errors-ignoring-incoming-dht-message-while-not-in-server-mode/17254

Been getting the same error for my IPNS node which handles around 1000 IPNS records. Here's the pprof dump - https://bafybeicw4kza5a4vmgmdovp5i5nc6jv7wpsok7v33diiog372zf4trmeaa.ipfs.sphn.link/
