### ISSUE TITLE
How to provide ipfs flags for the docker image?

### ISSUE THREAD

**Issue by markg85** [ipfs/go-ipfs#7595]
Hi,

It's surprisingly difficult to find the flags that IPFS supports to enable.
When you finally do find it ([here](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md)) then you're probably still wondering how to fully enable a feature.

Take for instance IPFS pubsub.
There are apparently flags that can influence it's behavior.
And there is the command line argument: --enable-pubsub-experiment to enable it.

That is vague. At best.
I'd suggest to use the config file for "all" flags.

An example of how this could work is having a "features" json object within the config like so:
```
{
  ...
  "features" : {
    "pubsub": true,
    "something...": false
    ...
  }
}
```

And if `--enable-pubsub-experiment` is applied as command line argument then it implicitly means the feature is enabled in the json config.

I found this when trying to enable pubsub with ipns in a docker container.
In that case i know i need to pass `--enable-pubsub-experiment --enable-namesys-pubsub` but i **still** don't know how to pass them to the IPFS container.

I hope someone knows how to pass these flags in a docker container **without** making a custom container.

Cheers,
Mark

**Comment by aschmahmann** [comment]
@markg85 it looks like you've solved this so I'll close it for now.

**Comment by miguelmota** [comment]
I was able to pass flags like this:
 
```
docker run -p 5001:5001 ipfs/go-ipfs daemon --enable-pubsub-experiment
```
