### ISSUE TITLE
IPFS Files Shows /404

### ISSUE THREAD

**Issue by yvain99** [ipfs/go-ipfs#7604]
Hello, at first my ipfs can import, but after some uploads it turns to /404 and no import button anymore, anyone experiencing the problem?

![ScreenShot_20200818210837](https://user-images.githubusercontent.com/19401967/90523414-0ba69800-e197-11ea-8669-b3df5a052165.png)

**Comment by Jorropo** [comment]
It's probably an [ipfs-webui](https://github.com/ipfs-shipyard/ipfs-webui) issue, go-ipfs is the repo for the go node.

**Comment by lidel** [comment]
This is webui/desktop problem.
Let's continue in https://github.com/ipfs-shipyard/ipfs-webui/issues/1422
