### ISSUE TITLE
How to export (and import) an ipfs key?

### ISSUE THREAD

**Issue by markg85** [ipfs/go-ipfs#7618]
Hi,

It looks like we're going to get a ipfs key import and export mechanism in 0.7.0: https://github.com/ipfs/go-ipfs/pull/7546
That's super! Thank you for that :)

But i really wonder how importing and exporting is supposed to be done now?
As  there are some totorials that tell you to, quite simply, copy the generated key in your keystore folder to you destination.
But there's a little issue in that. There doesn't seem to be a separate key file (anymore?).
The file in `.ipfs/keystore` is a binary single file containing all the keys.

I couldn't find any (command line) tool to interact with it and grab a key from it...
There do seem to be go libraries for that.

Just curious how this is supposed to work.

Cheers,
Mark

**Comment by jacobheun** [comment]
Importing and exporting will be done via a local file, so you won't need to mess with the repo at all directly. This will enable you to export/import based on key names `ipfs key list`.

```
ipfs key export -o ./mykey.key mykey
ipfs key import anotherkey ./mykey.key
```

**Comment by markg85** [comment]
> Importing and exporting will be done via a local file, so you won't need to mess with the repo at all directly. This will enable you to export/import based on key names `ipfs key list`.
> 
> ```
> ipfs key export -o ./mykey.key mykey
> ipfs key import anotherkey ./mykey.key
> ```

Hi @jacobheun 
Thank you for explaining that! :)

However... I think you misunderstood me. What you described is what will be possible in IPFS versioin 0.7.0!
I'm asking how it's supposed to be done in **today'** IPFS (0.6.x).

**Comment by jacobheun** [comment]
Each time you create a key a new binary file is added to the keystore. So you should be able to just move it out of / into the keystore folder for "importing". Something like:

```bash
$ ipfs key gen a-test-key
$ ipfs key gen another-test-key
$ ipfs key list
self
a-test-key
another-test-key
$ ls ~/.ipfs/keystore/
key_x key_y
$ mv ~/.ipfs/keystore/key_x ./key_x.bak
$ ipfs key list
self
another-test-key
```

**Comment by markg85** [comment]
That's not what i get.
In ~/.ipfs/keystore i only have 1 file (and 2 keys in IPFS):
```
❯ ls -la
total 12
drwx------ 2 mark users 4096 Aug 23 18:37 .
drwxr-xr-x 5 mark users 4096 Aug 24 11:26 ..
-r-------- 1 mark users 1196 Aug 23 18:37 key_onugc4tfmqwwwzlz
```

Which leads me to think that all keys are stored in one binary file?

**Comment by jacobheun** [comment]
Two keys other than `self`? `self` is not added to the keystore

**Comment by markg85** [comment]
:O i get it now!
I have "shared-key" and "shared-key-2". But the filenames apparently don't look like that. As now i have:
```
❯ ls -l
total 8
-r-------- 1 mark users 1196 Aug 23 18:37 key_onugc4tfmqwwwzlz
-r-------- 1 mark users 1196 Aug 24 15:57 key_onugc4tfmqwwwzlzfuza
```

I see now. That's weird but sure, i can work with that :)

**Comment by aschmahmann** [comment]
@markg85 in case you're wondering those key names are base32 encoded https://github.com/ipfs/go-ipfs/blob/92fbcc3d1c0186e0773584900b2af4f075e67520/keystore/keystore.go#L164 (e.g. Base32Decode(onugc4tfmqwwwzlz) = shared-key).

It looks like this issue is closed, but feel free to reopen if I'm mistaken.

**Comment by markg85** [comment]
> @markg85 in case you're wondering those key names are base32 encoded
> 
> https://github.com/ipfs/go-ipfs/blob/92fbcc3d1c0186e0773584900b2af4f075e67520/keystore/keystore.go#L164
> 
> (e.g. Base32Decode(onugc4tfmqwwwzlz) = shared-key).
> It looks like this issue is closed, but feel free to reopen if I'm mistaken.

Super :)
Yup, solved. Thanks guys!
