### ISSUE TITLE
bind wrong port makes reverse connection failed

### ISSUE THREAD

**Issue by godcong** [ipfs/go-ipfs#7636]
#### Version information:
Until the latest version

#### Description:
When ipfs connects to other ipfs nodes,
It will bind port `4001` to the local address,
This is usually no problem.

But when your ipfs node is hidden behind the router.
On the router the port `4001` is not open, the open port is a random port of `upnp`.
This causes the router to forward the correct data to your node.

The only thing that can be done now is that the router opens a `port forwarding` request that uses the same port as IPFS.
So the question now is whether ipfs tends to use `upnp` or manually open ports on the router.

**Comment by aschmahmann** [comment]
This seems to be a general question about how things work as opposed to a bug report or feature request. Questions like these are best asked on discuss.ipfs.io as they make it easier for other users to find the information in the future (closed GitHub issues aren't very searchable).

I'm going to close this issue for now, but feel free to reopen if there's an actual bug you are reporting. Feel free to repost on discuss.ipfs.io and tag me if you'd like me to respond there.

--------

The above being said go-ipfs can automatically use NAT port mapping (i.e. UPnP). It is enabled by default and configured by the this config field https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#swarmdisablenatportmap.

If you don't have port mapping enabled (either in go-ipfs or on your router itself) then you're stuck with the more tricky NAT/stateful firewall traversal techniques that exist. As these techniques (e.g. UDP hole punching) are not currently built in primitives in go-libp2p performing them can be quite difficult to do by simply orchestrating a go-ipfs binary and likely would require some more invasive work to be done.
