### ISSUE TITLE
apt-get does not work in Dockerfile

### ISSUE THREAD

**Issue by anthonybudd** [ipfs/go-ipfs#7655]
#### Version information:
go-ipfs version: 0.7.0-rc1-901c58b
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4

#### Description:
apt-get does not work in my Dockerfile despite the fact it is used in the [FROM Dockerfile](https://github.com/ipfs/go-ipfs/blob/master/Dockerfile)

**My DockerFile**
FROM ipfs/go-ipfs
RUN apt-get update

**Output from $> docker build**
Building ipfs
Step 1/4 : FROM ipfs/go-ipfs
 ---> 438b797aff64
Step 2/4 : RUN apt-get update
 ---> Running in 95d998f8cfe3
/bin/sh: apt-get: not found
ERROR: Service 'ipfs' failed to build: The command '/bin/sh -c apt-get update' returned a non-zero code: 127

**Comment by olizilla** [comment]
The Dockerfile in the go-ipfs repo use a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/). The first half of the file is the defines the builder image with all the tools needed to build go-ipfs, while the second half defines a much smaller image with only what is needed to run go-ipfs. 

The binaries are copied over to a busybox image (no apt), and that is the image that is published to the docker hub. Busybox images are intended to be extremely minimal, so there is no need to update anything in it.

- https://github.com/ipfs/go-ipfs/blob/2ae5c52f4f0f074864ea252e90e72e8d5999caba/Dockerfile#L49-L60
- https://docs.docker.com/develop/develop-images/multistage-build/

As this the lack of apt is expected, I'm going to close this issue out, but feel free to open an new one if you hit other problems.

**Comment by bronger** [comment]
IPFS itself is so big that the smallness of Busybox is thwarted. Instead, the lack of tools in the container makes hunting of problems more difficult. Is it worth it opening an issue requesting to switch to an apt-based image?
