### ISSUE TITLE
proposal: Adding `ipfs swarm stat`

### ISSUE THREAD

**Issue by Jorropo** [ipfs/go-ipfs#7656]
The goal is to have something similar to `ipfs repo stat` but for swarm.
I've first submitted a PR (#7647) but as correctly pointed by @aschmahmann this should be discussed in an issue first.
#### Goal
So the goal to replace syntax heavy wording to get swarm related info (proposed output of `ipfs swarm stat`):
```
ListenAddr: 10
ConnectedPeers: 15
KnownPeers: 136
```
#### Proposal VS Now
Proposed Field : Bash equivalent with current CLI :
- `ListenAddr` : ```echo $((`ipfs id | jq ".Addresses" | wc -l` - 2))```
- `ConnectedPeers` : `ipfs swarm peers | wc -l`
- `KnownPeers` : `ipfs swarm addrs | grep "\(([0-9])\)$" | wc -l`

As you can see nothing proposed here is currently impossible but it's way easier done using `ipfs swarm stat`.

**Comment by Jorropo** [comment]
I was also thinking of including bandwith metrics but it's not as easy :
- Bandwith metrics may not be present if disabled (they take CPU time and memory), how to communicate that ? (there is 2 main option, null them or not print them at all, the first one is ugly and the second one is not script friendly).
- What value they represent ? For all current value it's easy (peers, kpeers and laddrs), it's just a snapshot of the time of the command, but bandwith is a flux, so is this the average over the last second ? This need to be asked.

**Comment by aschmahmann** [comment]
@Jorropo go-ipfs generating concise reports of already available data seems like it could be an unending process. Given that this data is already available it doesn't seem like there's a big rush on getting this data output.

What would be nice to have here is integration with libp2p introspection once that's landed https://github.com/libp2p/go-libp2p/issues/947 so we can output all the raw data you might need from libp2p.

**Comment by BigLep** [comment]
Reassigned to @Stebalien.  He will take a quick look at the PR this week.

**Comment by Stebalien** [comment]
After thinking about this for a bit, I'm convinced this command doesn't really pull its weight:

* KnownPeers can get _really_ slow over time so we wouldn't want to include it in a quick stat command (at least not enabled by default). I'm also not sure when this information would actually be useful.
* ListenAddr just doesn't seem all that useful.
* ConnectedPeers _is_ useful, but I think we'll usually want more information (how many UDP connections versus TCP? how many inbound versus outbound? are we connected to the IPFS DHT?).

**Comment by Stebalien** [comment]
Note: with respect to ipfs-companion, it's unclear if "len(peers) > 0" is even the right metric.
