### ISSUE TITLE
Adding a `--follow-symlinks` to `ipfs add`

### ISSUE THREAD

**Issue by Jorropo** [ipfs/go-ipfs#7657]
Nothing else to say, it would follow symlinks (recurse them as if they were directory).
I'm willing to do it if you are ok with that :)

**Comment by aschmahmann** [comment]
@Jorropo does `--dereference-args` not do what you want?

**Comment by Jorropo** [comment]
> @Jorropo does `--dereference-args` not do what you want?

It does mb, I've should have red more carefully the help.
