### ISSUE TITLE
Background downloads with API

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/go-ipfs#7672]
Sometimes, I want to download very large files, something like 10 GB. I don't necessarily want to leave a terminal hanging there be responsible for my download. I think the download feature can be improved quite a lot by using background downloads.

1. All downloads should happen via the running daemon regardless of if called via terminal or API. If there's none, then the initiator should start a daemon in another process, use it, then kill it when it's over.
2. Downloads should have progress reporting available via API.
3. The terminal initiating the download should send an API command to the deamon to initiate the download then report progress via the API
4. The daemon should be able to pause and resume downloads

This would make the daemon responsible for all downloads and have better integration with supporting tools such as IPFS Desktop.

Related : https://github.com/ipfs-shipyard/ipfs-desktop/issues/1499

**Comment by lidel** [comment]
>  I don't necessarily want to leave a terminal hanging there be responsible for my download.

To be fair, if you want background download in terminal, you can `ipfs refs -r <cid> & disown` or run `ipfs refs -r` inside of `tmux` or `screen`. No need for anything new.

>  1. All downloads should happen via the running daemon regardless of if called via terminal or API. If there's none, then the initiator should start a daemon in another process, use it, then kill it when it's over.

Check [ipfs-or-gateway](https://www.npmjs.com/package/ipfs-or-gateway) and [ipget](https://github.com/ipfs/ipget/) – those CLI tools may do 80% of what you want. 

> 2. Downloads should have progress reporting available via API.
> 3. [progress reporting]

Fair request. Already tracked in https://github.com/ipfs/go-ipfs/issues/4028, so I'm closing this as a duplicate.

> 4. The daemon should be able to pause and resume downloads

Technically you can do this already by interrupting `ipfs get` `cat` or `refs`. 
Blocks that were downloaded up to that point are in local repo, and won't be downloaded again if you make the call again.
