### ISSUE TITLE
ipfs can't open local media file with media player tools

### ISSUE THREAD

**Issue by godcong** [ipfs/go-ipfs#7697]
#### Version information:

i get the last commit(c4071893b1a881f7396e8401ce7a5264816ac809) and build it:
local:
go-ipfs version: 0.8.0-dev
Repo version: 10
System version: amd64/windows
Golang version: go1.15
remote:
go-ipfs version: 0.8.0-dev
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4

#### Description:

I have a media file(`file.mp4`) added into ipfs with a directory.
Then visit the site by web browsers with an address like:
`http://$my_local_ip:8080/ipfs/bafybeichvy2ycggddvsmqz3o5tonfnzejk23m5v46a52p77qmrear5jsle/file.mp4`
This case was ok.

But if i open this with a player tool(PotPlayer ,VlcPlayer)
This site is not open.
**This case was failed.**  
Now,I can't open media file with player

I openned the hash with remote address and a player tool.
`http://$my_remote_ip:8080/ipfs/bafybeichvy2ycggddvsmqz3o5tonfnzejk23m5v46a52p77qmrear5jsle/file.mp4`
This case was ok,too.

**Comment by godcong** [comment]
This seems to be a problem caused by the subdomain cannot be resolved.
If I turn off the following flag, everything is normal.
https://github.com/ipfs/go-ipfs/blob/a6c15986122a09e545c04da013a5fca2833bf541/core/corehttp/hostname.go#L91
=>
```
if gw.UseSubdomains && false{
```

**Comment by lidel** [comment]
Subdomain gateways return HTTP 301 redirect to CID-based Origin at subdomain hostname.
Perhaps your player does not support HTTP redirects antr trips when one is returned by `http://localhost:8080`?

To work around player issue, you may want to use IP-based URLs `http://127.0.0.1:8080`, which is path-based and does not redirect to subdomains.

----

I'm closing this as it does not sound like a problem with gateway, but third party player you are using.
The player should be smart enough to follow HTTP redirects, so you may fill an issue against its repo.

**Comment by godcong** [comment]
> When a path is requested, subdomain gateways return HTTP 301 redirect to CID-based Origin at subdomain hostname.
> Perhaps your player does not support HTTP redirects antr trips when one is returned by `http://localhost:8080`?
> 
> To work around player issue, you may want to use IP-based URLs `http://127.0.0.1:8080`, which is path-based and does not redirect to subdomains.
> 
> I'm closing this as it does not sound like a problem with gateway, but third party player you are using.
> The player should be smart enough to follow HTTP redirects, so you may fill an issue against its repo.
en,
`http://127.0.0.1:8080` was ok.
`http://localhost:8080` was failed.
