### ISSUE TITLE
Release v0.8.0

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/go-ipfs#7707]
> Release Issue Template

# go-ipfs 0.8.0 Release

We're happy to announce go-ipfs 0.8.0. This is planned to be a fairly small release focused on integrating in the new pinning service/remote pinning [API](https://github.com/ipfs/pinning-services-api-spec) that makes the experience of managing pins across pinning services easier and more uniform.

## 🗺 What's left for release

- Remote Pinning
   - [x] go-IPFS integration: #7559, #7661, etc.
      - [x] Modify config to store pinning service information
      - [x] Add commands for manually working with the pinning service API
      - [x] Add basic policy support (e.g. automatically pin/unpin MFS root)
   - [x] HTTP API integration (js: https://github.com/ipfs/js-ipfs/pull/3293)
   - [ ] ~WebUI integration: https://github.com/ipfs-shipyard/ipfs-webui/pull/1615~ Dropped from v0.8.0, although the latest deployed WebUI is always available at https://webui.ipfs.io/#/
- QUIC
   - [x] update quic-go to support QUIC draft-32

# 🚢 Estimated shipping date

TBD

### 🧷 Remote pinning services

There is now support for asking remote services to pin data for you. This means anyone can implement the [spec](https://ipfs.github.io/pinning-services-api-spec/) (developed in this [repo](https://github.com/ipfs/pinning-services-api-spec)) and allow for pin management.

All of the CLI (and corresponding HTTP API) commands are available under `ipfs pin remote`.

This remote pinning service comes with a redesign of how we're thinking about pinning and includes some commonly requested features such as:
- Pins can have names (and coming soon metadata)
- The same content can be pinned multiple times, but of course stored only once
  - This allows applications using the same pinning service to manage their own pins without worrying about removing content important to another application
- Data can be pinned in either the foreground or background

Examples include:
```
ipfs pin remote service add myservice https://myservice.tld:1234/api/path myaccess key

ipfs pin remote add /ipfs/bafymydata --service=myservice --name=myfile 
ipfs pin remote ls --service=myservice --name=myfile
ipfs pin remote ls --service=myservice --cid=bafymydata
ipfs pin remote rm --serivce=myservice --name=myfile
```
A few notes:

Remote pinning services work with recursive pins. This means commands like `ipfs pin remote ls` will not list indirectly pinned CIDs.

While pinning service data is stored in the configuration file it cannot be edited directly via the `ipfs config` commands due to the sensitive nature of pinning service API keys. The `ipfs pin remote service` commands can be used for interacting with remote service settings.

### 📌 Faster local pinning and unpinning

The pinning subsystem has been redesigned to be much faster and more flexible in how it tracks pins. For users who are working with many pins this will lead to a big speed increase in listing and modifying the set of pinned items as well as decreased memory usage.

Part of the redesign was setup to account for being able to interact with local pins the same way we can now interact with remote pins (e.g. names, being allowed to pin the same CID multiple times, etc.). Keep posted for more improvements to pinning.

#### QUIC update

QUIC support has received a number of upgrades, including the ability to take advantage of larger UDP receive buffers for increased performance.

Linux users may notice a logged error on daemon startup if your system needs extra configuration to allow IPFS increase the buffer size. A helpful link for resolving this is in the log message as well as [here](https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size).

#### :wave: No more Darwin 386 builds

Go 1.15 (the latest version of Go) [no longer supports](https://github.com/golang/go/issues/34749) Darwin 386 and so we are dropping support as well.

## Changelog

< changelog generated by bin/mkreleaselog >

## ✅ Release Checklist

For each RC published in each stage:

- version string in `version.go` has been updated (in the `release-vX.Y.Z` branch).
- tag commit with `vX.Y.Z-rcN`
- upload to dist.ipfs.io
  1. Build: https://github.com/ipfs/distributions#usage.
  2. Pin the resulting release.
  3. Make a PR against ipfs/distributions with the updated versions, including the new hash in the PR comment.
  4. Ask the infra team to update the DNSLink record for dist.ipfs.io to point to the new distribution.
- cut a pre-release on [github](https://github.com/ipfs/go-ipfs/releases) and upload the result of the ipfs/distributions build in the previous step.
- Announce the RC:
  - [x] On IRC/Matrix (both #ipfs and #ipfs-dev)
  - [x] To the _early testers_ listed in [docs/EARLY_TESTERS.md](https://github.com/ipfs/go-ipfs/tree/master/docs/EARLY_TESTERS.md).

Checklist:

- [ ] **Stage 0 - Automated Testing**
  - [x] Fork a new branch (`release-vX.Y.Z`) from `master` and make any further release related changes to this branch. If any "non-trivial" changes (see the footnotes of [docs/releases.md](https://github.com/ipfs/go-ipfs/tree/master/docs/releases.md) for a definition) get added to the release, uncheck all the checkboxes and return to this stage.
    - [x] Follow the RC release process to cut the first RC.
    - [x] Bump the version in `version.go` in the `master` branch to `vX.(Y+1).0-dev`.
  - [x] Automated Testing (already tested in CI) - Ensure that all tests are passing, this includes:
    - [x] unit, sharness, cross-build, etc (`make test`)
    - [x] lint (`make test_go_lint`)
    - [x] [interop](https://github.com/ipfs/interop#test-with-a-non-yet-released-version-of-go-ipfs)
    - [x] [go-ipfs-api](https://github.com/ipfs/go-ipfs-api)
    - [x] [go-ipfs-http-client](https://github.com/ipfs/go-ipfs-http-client)
    - [x] [WebUI](https://github.com/ipfs-shipyard/ipfs-webui)
- [ ] **Stage 1 - Internal Testing**
  - [ ] CHANGELOG.md has been updated
    - use [`./bin/mkreleaselog`](https://github.com/ipfs/go-ipfs/tree/master/bin/mkreleaselog) to generate a nice starter list
  - [ ] Network Testing:
    - [ ] test lab things - TBD
  - [x] Infrastructure Testing:
    - [x] Deploy new version to a subset of Bootstrappers
    - [x] Deploy new version to a subset of Gateways
    - [x] Deploy new version to a subset of Preload nodes
    - [ ] Collect metrics every day. Work with the Infrastructure team to learn of any hiccup
  - [ ] IPFS Application Testing -  Run the tests of the following applications:
    - [x] [IPFS Desktop](https://github.com/ipfs-shipyard/ipfs-desktop) - @hacdias
    - [x] [IPFS Companion](https://github.com/ipfs-shipyard/ipfs-companion) - @lidel
    - [ ] [NPM on IPFS](https://github.com/ipfs-shipyard/npm-on-ipfs) - @achingbrain
- [x] **Stage 2 - Community Dev Testing**
  - [x] Reach out to the IPFS _early testers_ listed in [docs/EARLY_TESTERS.md](https://github.com/ipfs/go-ipfs/tree/master/docs/EARLY_TESTERS.md) for testing this release (check when no more problems have been reported). If you'd like to be added to this list, please file a PR.
  - [x] Reach out to on IRC for beta testers.
  - [x] Run tests available in the following repos with the latest beta (check when all tests pass):
    - [ ] [orbit-db](https://github.com/orbitdb/orbit-db)
- [x] **Stage 3 - Community Prod Testing**
  - [x] Documentation
    - [x] Ensure that [CHANGELOG.md](https://github.com/ipfs/go-ipfs/tree/master/CHANGELOG.md) is up to date
    - [x] Ensure that [README.md](https://github.com/ipfs/go-ipfs/tree/master/README.md)  is up to date
    - [ ] Ensure that all the examples we have produced for go-ipfs run without problems
    - [ ] Update HTTP-API Documentation on the Website using https://github.com/ipfs/http-api-docs
  - [x] Invite the IPFS [_early testers_](https://github.com/ipfs/go-ipfs/tree/master/docs/EARLY_TESTERS.md) to deploy the release to part of their production infrastructure.
  - [x] Invite the wider community through (link to the release issue):
    - [x] [discuss.ipfs.io](https://discuss.ipfs.io/c/announcements)
    - [ ] Twitter
    - [x] IRC
- [x] **Stage 4 - Release**
  - [x] Final preparation
    - [x] Verify that version string in [`version.go`](https://github.com/ipfs/go-ipfs/tree/master/version.go) has been updated.
    - [x] Merge `release-vX.Y.Z` into the `release` branch.
    - [x] Tag this merge commit (on the `release` branch) with `vX.Y.Z`.
    - [x] Release published
      - [x] to [dist.ipfs.io](https://dist.ipfs.io)
      - [x] to [npm-go-ipfs](https://github.com/ipfs/npm-go-ipfs)
      - [x] to [chocolatey](https://chocolatey.org/packages/ipfs)
      - [x] to [snap](https://snapcraft.io/ipfs)
      - [x] to [github](https://github.com/ipfs/go-ipfs/releases)
      - [x] to [arch](https://www.archlinux.org/packages/community/x86_64/go-ipfs/) (flag it out of date)
    - [x] Cut a new ipfs-desktop release
  - [x] Publish a Release Blog post (at minimum, a c&p of this release issue with all the highlights, API changes, link to changelog and thank yous)
  - [x] Broadcasting (link to blog post)
    - [ ] Twitter
    - [ ] IRC
    - [ ] [Reddit](https://reddit.com/r/ipfs)
    - [ ] [discuss.ipfs.io](https://discuss.ipfs.io/c/announcements)
    - [ ] Announce it on the [IPFS Users Mailing List](https://groups.google.com/forum/#!forum/ipfs-users)
- [ ] **Post-Release**
  - [ ] Merge the `release` branch back into `master`, ignoring the changes to `version.go` (keep the `-dev` version from master).
  - [ ] Create an issue using this release issue template for the _next_ release.
  - [ ] Make sure any last-minute changelog updates from the blog post make it back into the CHANGELOG.

## ❤️ Contributors

< list generated by bin/mkreleaselog >

Would you like to contribute to the IPFS project and don't know how? Well, there are a few places you can get started:

- Check the issues with the `help wanted` label in the [go-ipfs repo](https://github.com/ipfs/go-ipfs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)
- Join an IPFS All Hands, introduce yourself and let us know where you would like to contribute - https://github.com/ipfs/team-mgmt/#weekly-ipfs-all-hands
- Hack with IPFS and show us what you made! The All Hands call is also the perfect venue for demos, join in and show us what you built
- Join the discussion at [discuss.ipfs.io](https://discuss.ipfs.io/) and help users finding their answers.
- Join the [🚀 IPFS Core Implementations Weekly Sync 🛰](https://github.com/ipfs/team-mgmt/issues/992) and be part of the action!

## ⁉️ Do you have questions?

The best place to ask your questions about IPFS, how it works and what you can do with it is at [discuss.ipfs.io](http://discuss.ipfs.io). We are also available at the `#ipfs` channel on Freenode, which is also [accessible through our Matrix bridge](https://riot.im/app/#/room/#freenode_#ipfs:matrix.org).

**Comment by MichaelMure** [comment]
I suppose this will be covered by "update quic-go to support QUIC draft-32", but please make sure this new release include https://github.com/lucas-clemente/quic-go/pull/2827

**Comment by marten-seemann** [comment]
@MichaelMure Yes, that PR is part of #7769.

**Comment by aschmahmann** [comment]
go-ipfs v0.8.0-rc1 is out, give it a spin and let us know how it goes :smile: 

CC Early Testers:
- pacman.store (@RubenKelevra)
- Infura (@MichaelMure)
- Textile (@sanderpick)
- Pinata (@obo20)
- RTrade (@postables)
- QRI (@b5)
- Siderus (@koalalorenzo)
- Charity Engine (@rytiss, @tristanolive)
- Fission (@bmann)

**Comment by lidel** [comment]
Quick prompt for folks interested in remote pinning commands:
- `ipfs pin remote service --help`
- `ipfs pin remote --help`

**Comment by RubenKelevra** [comment]
> go-ipfs v0.8.0-rc1 is out, give it a spin and let us know how it goes 
> 
> CC Early Testers:
> 
> * pacman.store (@RubenKelevra)

I've updated from 0.6 to 0.8 master on my 3 servers and saw some issues with fetching of data, while the connection was fine (mtr was running to the fasted of them with low ping and no outages) while this happened.

Looks to me (without further investigation) that the connection drops out.

Speed is as usual for IPFS, but still below the bandwidth available (which would be 1200 KiB/s) - the high speed of the first file was just because this one was already in the cache.

![Screenshot_20201223_233758](https://user-images.githubusercontent.com/614929/103042029-7702db00-4578-11eb-8c4d-152dcfc04516.png)

**Comment by RubenKelevra** [comment]
Never seen this issue again, looks like this might just have been a temporary connection issue dropping a lot of UDP traffic, while ICMP has worked fine. Dunno.

I'll create a ticket if this ever occurs again and will investigate further in this case. :)

**Comment by aschmahmann** [comment]
v0.8.0-rc2 is out with a number of bug fixes:
- fixed the `ipfs config show` bug related to the pinning services config https://github.com/ipfs/go-ipfs/issues/7818
- fs-repo-migrations is now faster for this migration and has a locking issue fixed
- added a policy for remote pinning services to automatically pin your MFS root to the remote service
- support inlined DNSLink names with TLS
- a libp2p update that included some QUIC fixes

One breaking change from RC1 is that instead of having pinning service APIs defined as `Pinning.RemoteServices.{yourServiceName}.Api` it is now `Pinning.RemoteServices.{yourServiceName}.API` to be more consistent with our other config options, sorry for any inconvenience here. I'm a bit out of :battery: for today, but hope to have a script to make this quick to fix for folks (although if someone else wanted to write it I wouldn't complain :smile:).

More docs around how to configure the MFS policy coming soon as well as any other info on the RC I may have forgotten tonight.

Give it a spin and let us know how it goes :pray:.

**Comment by lidel** [comment]
Good news regarding config `API` key rename:  there is no breaking change, preexisting `Api` will work just fine because if exact match is not found, `encoding/json` will do case-insensitive match as a fallback:

https://golang.org/pkg/encoding/json/#Unmarshal
> To unmarshal JSON into a struct, Unmarshal matches incoming object keys to the keys used by Marshal (either the struct field name or its tag), preferring an exact match but **also accepting a case-insensitive match.**

**Comment by aschmahmann** [comment]
reopening while some of the post-release process is still ongoing (e.g. package managers, blog posts, etc.)

**Comment by fiott248** [comment]
where is the version of python library to match with this agent "0.8.0" i can only install up to 0.7.0.
