### ISSUE TITLE
Suddenly every python IPFS api doesn't work. 

### ISSUE THREAD

**Issue by fregataa** [ipfs/go-ipfs#7765]
**Version information:**
> github.com/ipfs/go-ipfs v0.6.0

**Description:**
I have used **ipfshttpclient** from [https://pypi.org/project/ipfshttpclient/](url) and **ipfsApi** from [https://pypi.org/project/ipfs-api/](url).
they worked without any malfunction 6 hours ago but suddenly those 2 python modules have stopped working since 4 hours ago. 
my code with **ipfshttpclient** module results this error below
`ipfshttpclient.exceptions.StatusError: HTTPError: 405 Client Error: Method Not Allowed for url: http://localhost:5001/api/v0/version?stream-channels=true`

and the code with **ipfsApi** module results this error
`urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f596da55470>: Failed to establish a new connection: [Errno 111] Connection refused`

but IPFS CLI commands and JS-IPFS API such as ipfs-http-client still work very well. 
is there any change with python api?? 

I have just checked http requests made by the modules and I found that the method of the requests are not POST.

**Comment by fregataa** [comment]
nah, my mistake. ipfsApi has no problem now. and I have not used ipfshttpclient.
but still, ipfshttpclient is malfunctioning and I cannot find the official homepage of it. 
where should I report this issue?? 
it just send requests with a wrong method!

**Comment by jacobheun** [comment]
The repo for the python client is at https://github.com/ipfs-shipyard/py-ipfs-http-client. Closing this here as it's not an issue in go-ipfs.
