### ISSUE TITLE
My IPFS webui suddenly 404 in "FILES" section

### ISSUE THREAD

**Issue by yvain99** [ipfs/go-ipfs#7768]
Hello,

I am using ipfs and upload file via localhost:5001/webui.. It was going fine but suddenly after refreshing the page I got 404 in files section and I cannot upload any file.. can you guys help me for this issue?

Thanks

**Comment by jacobheun** [comment]
Can you create an issue in https://github.com/ipfs-shipyard/ipfs-webui, this is likely an issue with the webui? Also, it would be helpful when you do so to include a screenshot of the browser console and browser so there is more data to help us debug. If you can reliably reproduce this, steps to do so, or a gif of the issue would also be really helpful.
