### ISSUE TITLE
Append Announces

### ISSUE THREAD

**Issue by Jorropo** [ipfs/go-ipfs#7791]
Hi, I would like to add announces on top of the listen addrs but,
currently if `len(announces) > 0` the regular addrs are replaced by the announces :
https://github.com/ipfs/go-ipfs/blob/1bf8a723f95f8ca9bd5f520b0896b7afc9658a53/core/node/libp2p/addrs.go#L55-L59

I would like to create a way for announces to be added to listen addresses, not replace them.
Wich option would be fine to add ?
- Add an `.Addresses.AppendAnnounce bool` key, if true `addrs = append(allAddrs,annAddrs...)` else the current logic.
- Add an `.Addresses.ExtraAnnounce []ma.Multiaddr` wich is always appended after the current logic.
- Replace the current logic by `addrs = append(allAddrs,annAddrs...)` (breaking change ?).

**Comment by aschmahmann** [comment]
@Jorropo implementing one of these proposals seems reasonable. It would be helpful to know a little more context around the use case you're working on.

**Comment by Jorropo** [comment]
> @Jorropo implementing one of these proposals seems reasonable. It would be helpful to know a little more context around the use case you're working on.

Really there is none in this case, could be someone running behind a nat without nat traversal and wanting to announce his port forward while still announcing his local addrs.

**Comment by TheDiscordian** [comment]
> @Jorropo It would be helpful to know a little more context around the use case you're working on.

I've run into a need for this when enabling WSS. My current solution is to grab everywhere I'm announcing to, make a big list, then append my 2 new announcements to that list. It'd be a lot more intuitive to be able to just append to the usual generated list (especially with dynamic IPs...).

Explicitly, currently I'm doing this:

```
"Announce": ["/ip4/127.0.0.1/tcp/4001","/ip4/127.0.0.1/tcp/4011/ws","/ip4/127.0.0.1/udp/4001/quic","/ip4/172.105.103.78/tcp/4001","/ip4/172.105.103.78/tcp/4011/ws","/ip4/172.105.103.78/udp/4001/quic","/ip6/2600:3c04::f03c:92ff:fecf:988b/tcp/4001","/ip6/2600:3c04::f03c:92ff:fecf:988b/tcp/4011/ws","/ip6/2600:3c04::f03c:92ff:fecf:988b/udp/4001/quic","/ip6/::1/tcp/4001","/ip6/::1/tcp/4011/ws","/ip6/::1/udp/4001/quic","/dns4/ipfs.thedisco.zone/tcp/4430/wss","/dns6/ipfs.thedisco.zone/tcp/4430/wss"]
```

When I think this would make more sense:

```
"Announce": [],
"ExtraAnnounce": ["/dns4/ipfs.thedisco.zone/tcp/4430/wss","/dns6/ipfs.thedisco.zone/tcp/4430/wss"]
```

**Comment by lidel** [comment]
@TheDiscordian see proposed config in https://github.com/ipfs/go-ipfs/pull/8177  – would appreciate feedback if it is intuitive enough.

**Comment by BigLep** [comment]
2021-11-12 discussion: we believe this is just waiting until @lidel frees up to get this reviewed/merged.
