### ISSUE TITLE
Improve error when broken CIDv0 is used

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#7792]
If you make a `{cidv0}.ipfs.dweb.link` subdomain URL with a v0 CID, you get: 

```invalid ipfs path: invalid path "/ipfs/{cidv0}/": invalid CID: selected encoding not supported```

Browsers force-lowercase authority part of every URI which breaks CIDv0. 
That is why advise use of `dweb.link/ipfs/{cidv0}` as canonical link (it coverts and redirects, working around browser limitations).

Perhaps we could special-case this natively in go-ipfs, and detect that error was caused by "broken cidv0" starting with `qm..` ?
That is what we already do in ipfs-companion in Firefox: https://github.com/ipfs-shipyard/ipfs-companion/pull/911:

![](https://user-images.githubusercontent.com/157609/96525661-dc3a0780-127b-11eb-8d79-5560e0177f33.png)

At very minimum we could make text error more useful by detecting `qm..` and providing more useful error suggesting to "covert CIDv0 to CIDv1 in base32 and try again"?

cc @gozala @autonome @andrew @jessicaschilling

**Comment by lidel** [comment]
Idea: perhaps the error could mention `ipfs cid base32 <cidv0>` as a quick fix?

**Comment by autonome** [comment]
+1 and error could also mention CID.asV1() for webdevs - which was the
context where I saw this confusion in the wild.

**Comment by jessicaschilling** [comment]
Without context for the phrase logic of the original error message (i.e. not sure if we can bypass the original message's repetition of `invalid ipfs path: invalid path`), would suggest something like:

`invalid ipfs path "/ipfs/{cidv0}/": This looks like a CIDv0 that has been lowercased. Convert the CIDv0 to CIDv1 in base32 using "ipfs cid base32 <cidv0>" and try again.`

@autonome suggestion for how we could work in language about `CID.asV1()`?

**Comment by autonome** [comment]
I'll defer to @achingbrain's thoughts on that.

**Comment by lidel** [comment]
I believe the message should be implementation-agnostic, so mentioning `ipfs cid base32 <cidv0>` is enough.
JS devs will know to either use `ipfs.cid.base32()` or `CID.asV1()`
