### ISSUE TITLE
Repo GC doesn't works with badger.

### ISSUE THREAD

**Issue by Jorropo** [ipfs/go-ipfs#7793]
#### Version information:

```console
$ ipfs version --all
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4
```

#### Description:
First create badger ds ipfs node.
Then add some file to the store (don't pin them or unpin them before continuation).
Run :
```
ipfs repo gc
```
Nothing happends (or sometime very few blocks actualy gets deleted (<0.01%)).

Might be a duplicate of #4300 but #4300 says that this should be fixed.
PS: I'm not talking about reclaiming disk space, I really just want to remove all blocks that are not pinned (someone downloaded some copyrighted contents with my node and I want to get it out without having to rm the store).

**Comment by aschmahmann** [comment]
This may be related to https://github.com/ipfs/go-ds-badger/issues/54 which should be fixed in master (and in the upcoming release).

@Stebalien any thoughts on if these two issues are the same or if it's something else?

**Comment by Stebalien** [comment]
I believe this is "poor command docs". `ipfs get` and the gateway don't pin files by default but `ipfs add` does unless you pass `--pin=false`.

If someone downloaded material through your gateway or the `ipfs get` command, the `ipfs repo gc` command should delete them.

**Comment by Jorropo** [comment]
> This may be related to [ipfs/go-ds-badger#54](https://github.com/ipfs/go-ds-badger/issues/54) which should be fixed in master (and in the upcoming release).

I'm gonna try with latest master and let you know, if it works I'll close :eyes:

> I believe this is "poor command docs". `ipfs get` and the gateway don't pin files by default but `ipfs add` does unless you pass `--pin=false`.

I know thx :), it's not that bad.
 
> If someone downloaded material through your gateway or the `ipfs get` command, the `ipfs repo gc` command should delete them.

My content was downloaded using the http gateway and `ipfs get`, I can confirm that with `v0.7.0` that doesn't works.

**Comment by Stebalien** [comment]
>> If someone downloaded material through your gateway or the `ipfs get` command, the `ipfs repo gc` command should delete them.
>
> My content was downloaded using the http gateway and `ipfs get`, I can confirm that with `v0.7.0` that doesn't works.

Are you sure the contents weren't pinned somehow and how did you determine that the blocks weren't deleted?

**Comment by Jorropo** [comment]
> Are you sure the contents weren't pinned somehow and how did you determine that the blocks weren't deleted?

They are not pinned, 100%.
In fact checking again I don't see any non pinned files anymore.
I was thinking that because I havn't see any message about deleted block, so it seems to be a bug about logging not gc.
Space is not reclaimed BTW (even if they are 15Gb of space to reclaim), but that might be expected.
