### ISSUE TITLE
Custom IPLD codecs

### ISSUE THREAD

**Issue by sanderpick** [ipfs/go-ipfs#7810]
[go-ipld-prime](https://github.com/ipld/go-ipld-prime) provides a framework for writing custom IPLD codecs. I'd love to have the ability to register different codecs with `go-ipfs` via the config file or some other mechanism.

We have an encryption scheme that currently works on UnixFS, but since the whole network doesn't know how to walk those nodes, they can't be easily replicated. A good start would be to allow IPFS node owners to "opt-in" to different codecs. 

Given the complexity around defining a comprehensive security model for IPFS, I think allowing users to try out different approaches will enable a more iterative + community driven approach to a solution.

**Comment by aschmahmann** [comment]
> I'd love to have the ability to register different codecs with go-ipfs via the config file or some other mechanism.

This is already available via plugins https://github.com/ipfs/go-ipfs/blob/master/docs/plugins.md.

Note: These use the older IPLD interfaces. While updating from go-ipld-format to go-ipld-prime is on the roadmap this will likely cause you problems in the near term.

cc @jacobheun

**Comment by sanderpick** [comment]
Oh, I should have known :) Still worth playing around with. Thanks @aschmahmann 🙏
