### ISSUE TITLE
Confusing error message from "ipfs key export"

### ISSUE THREAD

**Issue by teknomunk** [ipfs/go-ipfs#7814]
#### Version information:
go-ipfs version: 0.8.0-dev-42d3f541d
Repo version: 11
System version: amd64/linux
Golang version: go1.15.6

Installed from a package I built today from https://aur.archlinux.org/packages/go-ipfs-git/

#### Description:
I reproduced the issue reported on the forums at [ERROR with ipfs key export](https://discuss.ipfs.io/t/error-with-ipfs-key-export/9580) on my local machine.

When you run the command "ipfs key export $KEY_NAME" (where $KEY_NAME is not "self") while the ipfs daemon is running, it responds with the message:

Error: lock /home/teknomunk/.ipfs/repo.lock: someone else has the lock

When you stop the ipfs daemon, the command completes without issue.

If the requirement for key export to be an offline command cannot be removed, I think the error message should let the operator know that the command can only be run while the daemon is not.

**Comment by gammazero** [comment]
@teknomunk Thank you for bringing this to our attention.  It probably makes sense to provide the same error that is given when trying to run `ipfs key rotate`:
```
Error: ipfs daemon is running. please stop it to run this command
```
