### ISSUE TITLE
rename `url` in pin remote to endpoint

### ISSUE THREAD

**Issue by Gozala** [ipfs/go-ipfs#7825]
Per @lidel we use `endpoint` option everywhere in ipfs-client, but then e.g. if user omits endpoint option go-ipfs will produce error with message "argument "url" is required", which can be very confusing for the user.

We should either change naming in go-ipfs as well from url to endpoint everywhere, or change it back to `url` in js-ipfs.

**Comment by lidel** [comment]
I believe this will be addressed by #7823
