### ISSUE TITLE
ipfs.pin.remote.ls with multiple status values returns empty set

### ISSUE THREAD

**Issue by Gozala** [ipfs/go-ipfs#7827]
Reading the `ipfs pin remote ls --help` states following about `--status` option:

```
Return only pin objects with the specified
                      statuses (queued,pinning,pinned,failed). Default:
                      [pinned].
```

Which lead me to believe that specifying multiple statuses would result in list containing pins matching both, but instead it returns empty list. Here is the illustration:

```
ipfs pin remote ls --service=mock --status=pinned
QmR7HHZXd1tVuL1aroK8GGhcAxF6x5ho8Y7YZfuLBtQDqb  pinned  pinned-peerdium
Qmdi3ZutGjD7d25MppgUjdjYCsdyrE31NMPS18PsFAEnsM  pinned  pinned-foo
ipfs pin remote ls --service=mock --status=queued
QmTgk4CwNa3HYVfFjeqAcGfeGwYq1jXjrK43pvdY7EAqBn  queued  lunetarium
ipfs pin remote ls --service=mock --status=queued,pinned
```

Behavior is the same with HTTP API.

**Comment by Gozala** [comment]
Turns out the problem was caused by the fact that on the endpoint request hits:
`/pins?limit=10&status=queued%2Cpinned`

Which then schema generated server parses into `status: [ 'queued,pinned' ]` instead of `['queued', 'pinned']`. While I can fix that on the server side I do thing that request should arrive at:

`/pins?limit=10&status=queued&status=pinned`

**Comment by aschmahmann** [comment]
@Gozala this is a request for a change to the pinning service API spec as it is what is dictating the way the HTTP requests are emitted. https://ipfs.github.io/pinning-services-api-spec/#tag/pins/paths/~1pins/get

Additionally, AFAIK having repeated query params be treated as an array is not actually supported by any spec, despite it being implemented in some places and seeming like a good idea (e.g. the IPFS API does this for Strings arguments).

The discussion on whether to make this change in the pinning service API spec is https://github.com/ipfs/pinning-services-api-spec/pull/69.

As a result closing this issue (unless/until the spec is changed)
