### ISSUE TITLE
Ipfs executes pin=true slowly

### ISSUE THREAD

**Issue by xjxloveqsl** [ipfs/go-ipfs#7842]
Version 0.6.0
The PIN gets slower and slower as there are many IPFS Pin Add files

**Comment by aschmahmann** [comment]
This is a duplicate of #5221 and #7674. This is also resolved in master via #7750 and will be in the 0.8.0 release (#7707 ).

**Comment by xjxloveqsl** [comment]
Thank you. The problem we encountered is that when the number of pins increases, the interface will gradually encode. I don't know if it has something to do with the number of small files with pins

**Comment by xjxloveqsl** [comment]
Do I need to update to 0.8.0 to solve this problem，Thank you

**Comment by gammazero** [comment]
@xjxloveqsl Yes, update to 0.8.0 should resolve this issue.
