### ISSUE TITLE
lock /Users/yenan/.ipfs/repo.lock: someone else has the loc

### ISSUE THREAD

**Issue by xjxloveqsl** [ipfs/go-ipfs#7843]
version 0.6.0 
Docker restart report the following error
Error: lock /Users/yenan/.ipfs/repo.lock: someone else has the lock

Thank You

**Comment by VandeurenGlenn** [comment]
@xjxloveqsl How long did you wait before restarting?
Ipfs needs time to close connections and the repo before you can restart again.

**Comment by Stebalien** [comment]
Alternatively, do you have anything else running IPFS commands? If so,
that might be opening the repo (conflicting with the daemon you're
trying to start).

**Comment by aschmahmann** [comment]
This hasn't had any input in a while, if the issue continues to occur feel free to reopen.
