### ISSUE TITLE
[ipfs urlstore] ipfs get very slow

### ISSUE THREAD

**Issue by chaos369** [ipfs/go-ipfs#7846]
#### Version information:
root@mac:~/packages/go-ipfs# ipfs version --all
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4

#### Description:

Hi,
I added one file by urlstore, then get the file. It took very long time to get the file.

  1 ipfs add --nocopy  --pin=false http://192.168.1.12:8082/file   (or  ipfs urlstore add  --nocopy  --pin=false http://192.168.1.12:8082/file)

 2  ipfs get QmYdGH8CEK97eLBGdiRCqa2MCaZXUrUQTQBSQFrjBVKEbv

root@Jms:~/tmp# ipfs get QmYdGH8CEK97eLBGdiRCqa2MCaZXUrUQTQBSQFrjBVKEbv
Saving file(s) to QmYdGH8CEK97eLBGdiRCqa2MCaZXUrUQTQBSQFrjBVKEbv
72.09 MiB / 72.09 MiB [===========================================================================================] 100.00% **4m28s**

**Comment by Stebalien** [comment]
Does your HTTP server support HTTP range requests? Also, what's the latency to the server. IPFS makes one request per block (although it tries to do a bit of prefetching), so range request support and low latency requests are a must.

**Comment by chaos369** [comment]
Yes, It supports range requests. But It's gone when I test again after 3 days.  I'll keep watching.
