### ISSUE TITLE
Should use base32 as default in the "ipfs add -q --only-hash" command

### ISSUE THREAD

**Issue by DaniellMesquita** [ipfs/go-ipfs#7852]
Instead, its outdated and still using CIDv0.

**Comment by DaniellMesquita** [comment]
@Stebalien

**Comment by aschmahmann** [comment]
This isn't a bug and is covered in the issue for the migration from CIDv0 to (b32) CIDv1 https://github.com/ipfs/go-ipfs/issues/5358.

**Comment by DaniellMesquita** [comment]
@aschmahmann what is the workaround to get the base32 hash of an file?

**Comment by DaniellMesquita** [comment]
Conclusion:
> Ok, the pipelines command to get the CIDv1 of an file is: `ipfs add -q --only-hash <file.extension> | ipfs cid base32`
via: https://github.com/ipfs/go-ipfs/issues/5358#issuecomment-758413740

**Comment by DaniellMesquita** [comment]
@aschmahmann when this workaround will be implemented in the `ipfs add -q --only-hash ` command?

As newer applications should support CIDv1, some commands should be updated to default into it.

**Comment by DaniellMesquita** [comment]
@lidel, will this command be updated to use CIDv1 by default?

**Comment by lidel** [comment]
@DaniellMesquita you can opt-in to using CIDv1 by passing: `ipfs add --cid-version 1`

Note that defaulting to CIDv1 via `--cid-version 1` implies `--raw-leaves=true`, which will produce different DAG than `--raw-leaves=true`, which is the default for CIDv0. We are still trying to find good time to make the switch, ideally will group all changes of the defaults like this into a single release. For now, just pass `--cid-version 1`.

**Comment by DaniellMesquita** [comment]
@lidel, So, its `ipfs add -q --cid-version 1 --only-hash`?

Is it bad to produce an different merkletree/DAG? Then, how to keep compatibility?
