### ISSUE TITLE
Gateway needs to log all the requests for better logging

### ISSUE THREAD

**Issue by dmellos** [ipfs/go-ipfs#7873]
https://discuss.ipfs.io/t/ipfs-logging-configuration/9771/8

I am trying to download the content from the gateway. I do not see any logs for my requests in the ipfs logs.
What if the hash I am using is incorrect?
What if one ipfs node (not having the content on its ow repo) is waiting for an another node to get the data?

I need to see these details in the logs, but there are no logs for gateway requests.

**Comment by lidel** [comment]
Re-posting comment from the forums:
 
> I had a quick look, and it may be that the gateway handlers are not logging much at all. I see no calls to around here `log.Info/Debug(...)`
> 
>  https://github.com/ipfs/go-ipfs/blob/2ed9254426e900cf00a9b35304dc5b5de8173208/core/corehttp/gateway_handler.go#L154
> 
> **I recommend opening a feature request in go-ipfs about better logging of gateway requests [..]
> 
> Your best-shot workaround, however, is to put the IPFS gateway behind an nginx reverse proxy, which will log everything you want and let you control other stuff that IPFS does not allow to customize (max request body size, timeouts etc).

So the action here would be to add some additional Debug lines so one can enable useful gateway logs via `ipfs log level` command.
That is a sensible request in my opinion.

Bare minimum would be to log for each request, a pair:

```
{incoming HTTP request URL} → {actual content path}
```

@dmellos would the above  be enough, or would you be interested in any additional info?

**Comment by dmellos** [comment]
@lidel , I think lets include HTTP response status and request type (GET/POST) along with request URL and the content path, and that should be enough.

**Comment by sujanasowrirajan** [comment]
Hello! I can pick this up if no one is working on it.

Would this log line work?
`{request type} {incoming HTTP request URL} → {actual content path}`

And adding a debug log for all errors in webErrorWithCode to see the reason for failure:
https://github.com/ipfs/go-ipfs/blob/2ed9254426e900cf00a9b35304dc5b5de8173208/core/corehttp/gateway_handler.go#L701

**Comment by manute** [comment]
Hey 👋 ,

I've created this https://github.com/ipfs/go-ipfs/pull/8518 for addressing this issue. 

Thanks!

**Comment by shohamc1** [comment]
This should be closed.
