### ISSUE TITLE
Enable configurable DSCP tagging on outbound traffic to enable traffic prioritization

### ISSUE THREAD

**Issue by dlakelan** [ipfs/go-ipfs#7877]
Realistically I'm willing to share my internet connection to make IPFS a reality. And I'm savvy enough to be able to tag packets with DSCP and drop their priority. But the average person isn't. A configurable DSCP tag on outbound traffic would easily combine with something like OpenWrt's SQM on typical routers to enable people to provide IPFS at low priority so as not to interfere with more important traffic like VOIP or games or even web browsing. In the desktop app, this should be implemented with a pull-down menu with various common tags by NAME such as CS1 and CS2 and AF41 and etc, which would set the settings in the IPFS config file.

Prioritization is the solution for "not clogging the pipes" whereas bandwidth limits artificially lower the performance below what it should otherwise be, prioritization just makes the IPFS daemon's packets queue up if someone else needs to use the network.

**Comment by RubenKelevra** [comment]
Well, the priority that a user expects IPFS traffic gets depends on what he/she is using it for. If you're web browser with IPFS there would be no reason to drop the priority below regular web browsing.

I don't think there's a need to prioritize anything except real-time traffic if you do fair queuing. I'm using sch_cake on my OpenWRT router and never had any issue with running multiple IPFS nodes in the same network.

**Comment by Stebalien** [comment]
Unfortunately, tagging packets is way too low level for go-ipfs to handle and would likely require running as root.

Most users would be better served by setting QoS rules per port. go-ipfs uses the same source/dest port for all connections, so this should be pretty easy to setup.
