### ISSUE TITLE
`config show` expects "Pinning" 

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7878]
#### Version information:
go-ipfs version: 0.9.0-dev-7588a6a52
Repo version: 11
System version: amd64/linux
Golang version: go1.15.6

#### Description:
I just tried to run `ipfs config show` on my node but it just shows an error message. Not sure why...

```
$ ipfs config show 
Error: case mismatch in config, expected "Pinning" but got ""
```

**Comment by gammazero** [comment]
This is a duplicate of #7818
