### ISSUE TITLE
[Question] How to filter the "ipfs pin ls" command to display exact like in IPFS UI?

### ISSUE THREAD

**Issue by DaniellMesquita** [ipfs/go-ipfs#7892]

**Comment by aschmahmann** [comment]
Questions should be asked on discuss.ipfs.io for more community visibility.

**Comment by godcong** [comment]
Is ask accessible?
I never opened it.
No matter whether I use proxy or not, I can't access it.

**Comment by aschmahmann** [comment]
@godcong are you saying you cannot access https://discuss.ipfs.io/ (e.g. it's blocked by your ISP)?
