### ISSUE TITLE
Using IPFS to release IPFS

### ISSUE THREAD

**Issue by FledgeXu** [ipfs/go-ipfs#7893]
For now IPFS bases on GitHub to release its binary files. However, IPFS also can use IPFS itself to release and it is a good way to prove IPFS capability. So could you add a IPFS way to download IPFS binary files?

**Comment by aschmahmann** [comment]
@FledgeXu there is already a way to do this 😄. The releases are available at dist.ipfs.io which is available over IPFS. For example the go-ipfs v0.7.0 linux amd64 binaries are available at `/ipns/dist.ipfs.io/go-ipfs/v0.7.0/go-ipfs_v0.7.0_linux-amd64.tar.gz`. You can also use https://github.com/ipfs/ipfs-update which will pull the data by default from IPFS. 

This is documented at https://docs.ipfs.io/recent-releases/go-ipfs-0-7/install/ and the update page, but if you've got any suggestions you can make an issue/PR against the [docs repo](https://github.com/ipfs/ipfs-docs)).
