### ISSUE TITLE
Optional ipfs daemon --agent-version-suffix=

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#7898]
I propose we add support for running `ipfs daemon` with optional `--agent-version-suffix=` parameter.

This would enable vendors that bundle go-ipfs binary to customize `AgentVersion` (listed in `ipfs id` and announced to other peers) without the need for creating a fake libp2p protocol just to tell one cohort of `go-ipfs` nodes  from another.

The first users of this would be Brave browser and IPFS Desktop:
- `--agent-version-suffix=brave/1.19.85`  →  `go-ipfs/0.9.0/brave/1.19.85`
- `--agent-version-suffix=desktop/0.14.0`  →   `go-ipfs/0.9.0/desktop/0.14.0`

## Rationale

This would be opt-in, so does not introduce any new tracking vector, it simply aims to make things easier for vendors and to introduce common convention that preserves version number of go-ipfs.

In the current situation, where vendor can rebuild go-ipfs binary and change agentVersion, but then we lose information about % of different go-ipfs nodes on the DHT.  By making it a suffix, and making it work without rebuild, we will decrease the number of opaque AgentVersions, making it easier for us to track upgrade dynamics etc. 

### CLI param, ENV or Config?

No preference  atm – all will work for Brave.

- Config option would work fine
- Env variable `IPFS_AGENT_VERSION_SUFFIX`  (similar to `IPFS_PATH`) is good enough too
- Explicit  flag for `ipfs daemon` would be preferred, because it has added value if user  has multiple go-ipfs nodes running on same localhost (eg. ipfs-desktop and brave). It enables things like  `ps aux | grep brave` to quickly identify specific daemon instance.

cc @andrew @bbondy

**Comment by lidel** [comment]
Added to maintenance board, we want to land this by EOY so vendors like IPFS Cluster, Brave or Berty could add their own version suffix for improved metrics.

**Comment by schomatis** [comment]
@lidel Going with the preferred CLI param option as suggested. Let me know if you'd like something different.

**Comment by schomatis** [comment]
@lidel The agent version comes from the user agent in

https://github.com/ipfs/go-ipfs/blob/65d570c6cbe24f313fc6f02c3dc16aabc53306d1/version.go#L14

Do we care to _also_ modify this as well with the new option or just the agent version propagated over the wire? I'm going with the second option leaving user agent as is but let me know otherwise.

**Comment by schomatis** [comment]
I'm now realizing that `UserAgent` linked above is also used by libp2p to the point of being almost exactly a synonim with the agent version so I'll modify the original `UserAgent` as well unless noted otherwise.

**Comment by lidel** [comment]
Follow-up PRs:
- https://github.com/ipfs/go-ipfs/pull/8482
- https://github.com/brave/brave-browser/issues/18505
- https://github.com/ipfs/ipfs-desktop/pull/1914
