### ISSUE TITLE
ipfs version 0.8.0-rc1 spins up too many processes & ram crashes pi 3b+ and kills pihole

### ISSUE THREAD

**Issue by sabotagebeats** [ipfs/go-ipfs#7907]
Version information:

ipfs version --all
go-ipfs version: 0.8.0-rc1
Repo version: 11
System version: arm/linux
Golang version: go1.15.6

What you were doing when you experienced the bug.: using pi to run ipfs headless with pihole on pi3b+ with raspberry pi os lite
Any error messages you saw: no error messages, but top shows all ram used and hogged by many ipfs procs
steps to reliably produce the bug.: let ipfs run you will see lots of procs that suck memory

To mitigate so far I have tried to add the following to my config and have changed nice for current active ipfs procs to 19

    `"ConnMgr": {
      "Type": "basic",
      "LowWater": 25,
      "HighWater": 50,
      "GracePeriod": "10s"
    }`

**Comment by aschmahmann** [comment]
@sabotagebeats is this a new problem, or have you noticed this with previous versions of go-ipfs as well? Has the mitigation worked, or have you tried using the `lowpower` config?

**Comment by sabotagebeats** [comment]
> @sabotagebeats is this a new problem, or have you noticed this with previous versions of go-ipfs as well? 
this is the only version of ipfs i've used
> Has the mitigation worked, or have you tried using the `lowpower` config?
so far the mitigation has worked, although it ran fine for a week or so before having a problem
I have not tried the lowpower config. 

right now I am still showing 13 PID as `/usr/local/bin/ipfs daemon --migrate` but they are using less than 1/3 of the ram they were using before.

**Comment by sabotagebeats** [comment]
I have not had this problem again and suspect it may be from an interaction with another application. Feel free to close issue, and I will reopen if I notice the issue again.
