### ISSUE TITLE
Migrate to go-ipld-prime

### ISSUE THREAD

**Issue by oed** [ipfs/go-ipfs#7909]
I noticed that there was not issue explicitly tracking support for **go-ipld-prime**, so I created this issue. Looks like https://github.com/ipfs/go-ipfs/issues/6208 mentions it but not as a primary focus.

Would like to understand what the timeline for this looks like. I'm currently blocked from using go-ipfs because my project requires the [dag-jose](https://github.com/ipld/specs/blob/master/block-layer/codecs/dag-jose.md) ipld codec, which is implemented for go-ipld-prime.

**Comment by Stebalien** [comment]
There are a few teams looking into this, but yeah, we should have a tracking issue.

**Comment by willscott** [comment]
@oed  - do you have specific interfaces to the go-ipfs library / cli that you hope to use but can't because they're currently not ipld-prime aware?

I'm starting to try to scope scope getting the interfaces ipld-prime aware so that `ipld.Node`'s can be passed in and out, and it would be good to make sure that what happens in that scoping unblocks you

**Comment by oed** [comment]
@willscott We have an implementation of go-dag-jose here: https://github.com/alexjg/go-dag-jose
If your work makes it possible to use this codec, which is made for ipld-prime, in the current ipfs implementation that would be perfect!

**Comment by willscott** [comment]
@hannahhoward, @gammazero, @acruikshank, and @mvdan and I are starting to dig into what needs to happen here.

We've put together [an initial inventory](https://hackmd.io/KnC0cZGPRvSQG0g8Z9OMXw) of the packages with ipld-format dependencies. The first milestone we're breaking off is becoming opinionated with what interface we want to replace the current `DagService` with.

**Comment by oed** [comment]
I guess this can be closed now, or when 0.10 is released 🎉

**Comment by willscott** [comment]
Would be great to hear your experience of dag-jose codec working in the current master. Are you able to get it integrated as a plugin?

You're right though that this issue can be closed :)
