### ISSUE TITLE
pin remote add: improve Peer hints in Pin.origins

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#7915]
go-ipfs 0.8.0-rc2 adds `pin remote` commands (details in  #7559). 

When a new remote pin is added via `pin remote add` `Pin.origins` array is populated with all  multiaddrs of the local node.

## Problem

This is a bit naive, because:
- local node may not have the data
- most of multiaddrs are LAN ones and not diallable from the outside (and if service is in LAN, then it does not need them, mdns/land DHT will do just fine)

## Proposed improvements

1.  Check if pinned root CID  is in local blockstore. If it is not, then send empty `Pin.origins = []` 
    (local node is not origin, we are pinning some external CID, eg. when DAG is too big to fit on local laptop)
    CLI prior art:
    ````console
    $ ipfs block stat --offline $cid
    Error: blockservice: key not found
    ````
2. Filter out IP  multiaddrs  from  loopback addres (https://golang.org/pkg/net/#IP.IsLoopback) and maybe networks designated as local/LAN/private: https://en.wikipedia.org/wiki/Private_network

**Comment by bisakhmondal** [comment]
Hey @lidel, I want to give it a try, can I?
I suppose from a top-level look,
https://github.com/ipfs/go-ipfs/blob/cd72589cfd41a5397bb8fc9765392bca904b596a/core/commands/pin/remotepin.go#L176-L179
this need to be updated.
Thanks :)

**Comment by lidel** [comment]
@bisakhmondal yes, sounds about right. 

I believe we should:
-  filter out loopback addres via [IP.IsLoopback](https://golang.org/pkg/net/#IP.IsLoopback)
- filter out addrs that match denylist defined in config under [`NoAnnounce`](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#addressesnoannounce) 


This way people who want to use private networks, still can.
