### ISSUE TITLE
IPFS Client OOMKill

### ISSUE THREAD

**Issue by grostirolla1** [ipfs/go-ipfs#7954]
#### Version information:
go-ipfs version: 0.7.0-ea77213
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4

#### Description:
When trying to add multiple files in parallel (or even adding lots of single files in sequence for a long period of time) the IPFS clients is being oomkilled. The memory keeps growing until it reaches the limit (in my case 5GiB), and the client is killed. 
I've tried a couple of suggestions from this issue https://github.com/ipfs/go-ipfs/issues/3532 without much luck.
 - `ipfs config --bool Swarm.DisableBandwidthMetrics true`
 - `--enable-gc`
 - `--routing=dhtclient`

#### How to Reproduce:
Generate files
 - `for i in {1..100}; do dd if=/dev/random of=file_$i count=1 bs=102400000; done`
Add files through API
 - `for i in {1..100}; do curl -XPOST -F file=@file_$i "http://localhost:5001/api/v0/add"& done`
Or directly on the CLI (faster)
- `for i in {1..100}; do ipfs add file_$i & done`

Depending on your machine configurations (disk, memory etc) the oomkill might happen even when sending 100 x 10MB files.
This seems like a problem on how the memory is managed by IPFS.

**Comment by BigLep** [comment]
2021-05-24 next step: see is can reproduce this locally.

**Comment by tsoeiroecore** [comment]
Hey guys, any updates on this? I'm facing similar issues in a highly concurrent environment.

**Comment by BigLep** [comment]
@tsoeiroecore : are you able to provide a reproducible case?

**Comment by BigLep** [comment]
Closing due to no response with a reproducible case.
