### ISSUE TITLE
HTTP API /api/v0/add doesn't handle symlink

### ISSUE THREAD

**Issue by wanderer** [ipfs/go-ipfs#7974]
#### Version information:
go-ipfs version: 0.8.0
Repo version: 11
System version: amd64/linux
Golang version: go1.14.10

#### Description:
There doesn't seem to be a way to add a symlink with `/api/v0/add` to ipfs.

**Comment by Stebalien** [comment]
This is supported. You can create a symlink file with https://pkg.go.dev/github.com/ipfs/go-ipfs-files?utm_source=godoc#NewLinkFile. You can then add the file with https://pkg.go.dev/github.com/ipfs/go-ipfs-http-client#UnixfsAPI.Add.

In terms of the HTTP Protocol, you need to send a multipart file with:

1. The multipart content-type set to `application/symlink`.
2. The body set to the body of the symlink.
