### ISSUE TITLE
"pin verify" HTTP post returns success code (200) but no data in the response

### ISSUE THREAD

**Issue by Clay-Ferguson** [ipfs/go-ipfs#7981]
#### Version information:
Docker 'image': ipfs/go-ipfs:v0.7.0

#### Description:
I'm using the HTTP API and this post returns HTTP Success code 200 as expected but no data, in the response. There should always be a JSON response.

```sh
curl -X POST "http://127.0.0.1:5001/api/v0/pin/verify
```

Docs:
https://docs.ipfs.io/reference/http/api/#api-v0-pin-verify

**Comment by Stebalien** [comment]
By default, this command only returns invalid pins and nothing on success. If you want to return all pins, pass `verbose=true` but even that will return nothing if you have nothing pinned.

You'd see the same thing if you were to return an empty stream from, e.g., gRPC.

**Comment by Clay-Ferguson** [comment]
Thanks. So I guess this is a documentation problem only then. Docs clearly state it should always return JSON.

**Comment by Stebalien** [comment]
Hm. Good point.

Those docs are auto-generated so we'll need a way to distinguish between "returns a stream" and "returns a single item". Unfortunately, this _isn't_ encoded in the actual types (all commands can theoretically return zero or more results) so it'll probably take some manual work.

https://github.com/ipfs/go-ipfs/issues/8042

**Comment by Clay-Ferguson** [comment]
I guess you're saying the "auto-generated" stuff isn't the "main" documentation right? ....or not the comprehensive docs? Where are the real docs? The complete ones. Surely you guys aren't expecting to just have a single sentence of docs on most of these API calls right?

**Comment by Stebalien** [comment]
No, those are the main docs and PRs to improve them are most welcome.

**Comment by Clay-Ferguson** [comment]
I guess in an open-source FOSS kind of world, we're all getting what we paid for. I mean if IPFS was charging people to use the API no manager in his right mind would say, "Yeah let's just make it hard for our customers to use our product, and claim we just don't have time to document a PUBLIC API". (emphasis on the word "public" there right?).

On a team where everyone is a developer, no one will want to take an entire day just to write English sentences. It needs to be elevated in priority by someone resembling a manager. Someone who recognizes this as the massive friction point it is for all IPFS adopters. This kind of management has been lacking in IPFS for at least 4 years, because you've been adding tons of new features while your documentation problem sits neglected, and excuses are made about why.

**Comment by Stebalien** [comment]
I completely agree that we need better documentation and it's something
we've worked on extensively with dedicated projects and teams. It's not
great, but it's vastly improved and is continuing to improve.

However, we do have limited people and time. At this point, bringing the
go-ipfs API documentation up from "ok" to "great" across the board isn't
the highest priority. Instead, we're focusing on specific use-case
verticals and building documentation/examples/fixes for them.

You can track progress in:
- https://github.com/ipfs/ipfs-docs/pulse/monthly
- https://github.com/ipfs/ipfs-docs/projects
