### ISSUE TITLE
Prometheus `ipfs_http_request` metrics are not exposed

### ISSUE THREAD

**Issue by thibmeu** [ipfs/go-ipfs#7983]
#### Version information:
Custom implementation not using the cli
go-ipfs version: v0.8.0 tag 
System version: amd64/linux
Golang version: 1.15.8

#### Description:
Starting v0.8.0, prometheus metrics exposed by [`MetricsCollectionOption`](pkg/go-ipfs/core/corehttp/metrics.go) are not exposed to prometheus DefaultRegisterer.
When OpenCensus Metrics [were added](https://github.com/ipfs/go-ipfs/pull/7593), all `prometheus.Register` of `MetricsCollectionOption` were changed to register on a new custom registry. There are no comment on this change in the PR or in the changelog for v0.8.0.
```go
// file core/corehttp/metrics.go
promRegistry := prometheus.NewRegistry()
//...

if err := promRegistry.Register(reqCnt); err != nil {
  // note: this is always false, as the registry is new.
  if are, ok := err.(prometheus.AlreadyRegisteredError); ok {
//...
```

This registry is not returned and does not include any collector. So while metrics are still registered, I cannot find how to expose them.

A possible fix is to remove the addition of this new registry for this metric. An other option is to expose this new registry as a global variable which can then be collected.

**Comment by Lekensteyn** [comment]
CC @lanzafame @aschmahmann, a potential regression from #7593

**Comment by aschmahmann** [comment]
cc @marten-seemann if you have time to take a look

**Comment by lanzafame** [comment]
Sorry, this one is on me. #7986 contains the fix. 
CC @aschmahmann

**Comment by thibmeu** [comment]
The fix looks good to me. That's the exact same one I have on my configuration.
