### ISSUE TITLE
Illegal RFC1918 traffic

### ISSUE THREAD

**Issue by rlucassen2** [ipfs/go-ipfs#7985]
$ ipfs version --all
go-ipfs version: 0.8.0
Repo version: 11
System version: amd64/linux
Golang version: go1.15.8

I'm new to ipfs and today I built a Debian Bullseye IPFS server using the 0.8.0 tarball. IPFS works well! The host is in a DMZ (DeMilitarized Zone) and has ip 10.239.22.32, the ports 4001/udp and 4001/tcp of the external ip are NAT-ed to 10.239.22.32 (although udp is not mentioned in the docs)

But there is one thing that should not occur, and which, IMHO as a IPFS noob, is a bug. This is the situation which is a normal NAT configuration:

`internet <-1-> external ip <-2-> NAT firewall <-3-> IPFS in DMZ`

As the traffic comes from the internet, I should definitely NOT see any RFC1918 reply traffic at point 3 as these addresses are not routable over the internet. As I explicitely reject outgoing RFC1918 traffic to the internet, the firewall logs from time to time fill up with RFC1918 rejects. Apparently the ipfs daemon tries to reply to the original source-address-before-NAT of the other nodes. I just c/p some firewall log entries:

`timestamp       source add      sport   dest add        dport   proto`
`20:58:20        10.239.22.32    4001    172.17.0.1      4001    TCP`
`20:58:21        10.239.22.32    4001    172.17.0.1      4001    TCP`
`20:58:21        10.239.22.32    58054   172.31.13.74    20030   TCP`
`20:58:21        10.239.22.32    4001    10.244.8.113    31026   TCP`
`20:58:21        10.239.22.32    4001    172.17.0.10     4001    UDP`
`20:58:21        10.239.22.32    4001    172.17.0.10     4001    TCP`
`20:58:22        10.239.22.32    4001    172.21.0.2      4001    TCP`
`20:58:22        10.239.22.32    55744   172.21.0.2      4001    TCP`
`20:58:22        10.239.22.32    4001    10.0.0.100      36442   TCP`
`20:58:23        10.239.22.32    44722   172.17.0.1      4001    TCP`
`20:58:23        10.239.22.32    4001    10.244.8.113    31026   UDP`
`20:58:24        10.239.22.32    45650   10.0.2.15       42788   TCP`
`20:58:24        10.239.22.32    4001    10.10.10.100    4001    TCP`
`20:58:24        10.239.22.32    4001    192.168.0.191   4001    TCP`

You can clearly see in this dump that ipfs is trying to setup a connection to 172.19.0.3 on tcp port 4001 (which is rejected by the
firewall):

`21:05:19.911924 IP 10.239.22.32.4001 > 172.19.0.3.4001: Flags [S], seq 1050858194, win 64240, options [mss 1460,sackOK,TS val 2184226457 ecr 0,nop,wscale 7], length 0`

I'm sure the issue described here above should not occur. IPFS is replying to the peer's original internal source address instead of the peer's NAT-ed one.

R.

**Comment by willscott** [comment]
This traffic is likely IPFS attempting to discover if other IPFS nodes in the p2p network are on it's same local network. This is used to prioritize content lookup and retrieval within the local network, since that will be faster than going out to the internet.

IPFS will ask for the routing table from the OS, and should only make these requests if those local addresses are routable. (e.g. it's only worth trying to open a connection to a peer with a 172.16.x.x address if our local machine also knows how to send packets to a 172.16.x.x address.)

**Comment by rlucassen2** [comment]
> PFS will ask for the routing table from the OS, and should only make these requests if those local addresses are routable. (e.g. it's only worth trying to open a connection to a peer with a 172.16.x.x address if our local machine also knows how to send packets to a 172.16.x.x address.)

But that sounds to me like a design glitch. As _**all**_ networks have a default gateway, _**all**_ addresses will be routable. Even if they do not exist. A peer cannot simply be aware of the networks that are _behind_ a gateway, which is always part of the local layer2 network.

If you're on a 10.0.0.0/24 network and your gateway is 10.0.0.1, there is no way for the ipfs instance to know if there is another RFC1918 network behind the 10.0.0.1. You will explicitely have to tell the peer that such a network exists. That said, and IMHO of course, ipfs should _never_ connect to other RFC1918 networks, except when it has explicitely been told to do so.

R.

**Comment by RubenKelevra** [comment]
@rlucassen2 Hey, this is a duplicate, see https://github.com/ipfs/go-ipfs/issues/6932 and https://github.com/libp2p/go-libp2p/issues/436

**Comment by RubenKelevra** [comment]
To avoid this from happening, you can add a swarm filter, which will forbid IPFS to access those IPs. This will also forbid any connection within your private networks, so just be aware of this. 

```
  "Swarm": {
    "AddrFilters": [
      "/ip4/10.0.0.0/ipcidr/8",
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.0.0/ipcidr/29",
      "/ip4/192.0.0.8/ipcidr/32",
      "/ip4/192.0.0.170/ipcidr/32",
      "/ip4/192.0.0.171/ipcidr/32",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/192.168.6.0/ipcidr/24",
      "/ip4/192.168.34.0/ipcidr/24",
      "/ip4/192.168.34.0/ipcidr/24",
      "/ip4/192.168.34.0/ipcidr/24",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
```

If you want to filter the announced IPs to the DHT as well, you can add an announce filter under `NoAnnounce` too. :)

**Comment by Stebalien** [comment]
Thanks @RubenKelevra!

**Comment by rlucassen2** [comment]
> "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.0.0/ipcidr/29",
      "/ip4/192.0.0.8/ipcidr/32",
      "/ip4/192.0.0.170/ipcidr/32",
      "/ip4/192.0.0.171/ipcidr/32",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/192.168.6.0/ipcidr/24",
      "/ip4/192.168.34.0/ipcidr/24",
      "/ip4/192.168.34.0/ipcidr/24",
      "/ip4/192.168.34.0/ipcidr/24",

`"/ip4/192.0.0.0/ipcidr/24",`
covers:
`"/ip4/192.0.0.0/ipcidr/29",`
`"/ip4/192.0.0.8/ipcidr/32",`
`"/ip4/192.0.0.170/ipcidr/32",`
`"/ip4/192.0.0.171/ipcidr/32",`

and:

`"/ip4/192.168.0.0/ipcidr/16",`

covers:

`"/ip4/192.168.6.0/ipcidr/24",`
`"/ip4/192.168.34.0/ipcidr/24",`
`"/ip4/192.168.34.0/ipcidr/24",`
`"/ip4/192.168.34.0/ipcidr/24",`

So:

` "Swarm": {`
`    "AddrFilters": [`
`      "/ip4/10.0.0.0/ipcidr/8",`
`      "/ip4/100.64.0.0/ipcidr/10",`
`      "/ip4/169.254.0.0/ipcidr/16",`
`      "/ip4/172.16.0.0/ipcidr/12",`
`      "/ip4/192.0.0.0/ipcidr/24",`
`      "/ip4/192.0.2.0/ipcidr/24",`
`      "/ip4/192.168.0.0/ipcidr/16",`
`      "/ip4/198.18.0.0/ipcidr/15",`
`      "/ip4/198.51.100.0/ipcidr/24",`
`      "/ip4/203.0.113.0/ipcidr/24",`
`      "/ip4/240.0.0.0/ipcidr/4",`
`      "/ip6/100::/ipcidr/64",`
`      "/ip6/2001:2::/ipcidr/48",`
`      "/ip6/2001:db8::/ipcidr/32",`
`      "/ip6/fc00::/ipcidr/7",`
`      "/ip6/fe80::/ipcidr/10"`
`    ],`

Will do the same job. Thanks!

Richard

**Comment by RubenKelevra** [comment]
Yeah, this has more historic reasons :)

**Comment by jcomeauictx** [comment]
isn't that what `ipfs init --profile=server` is for?
