### ISSUE TITLE
CID with unexpected EOF can't  be removed from MFS

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#7999]
#### Version information:

```
go-ipfs version: 0.8.0
Repo version: 11
System version: amd64/linux
Golang version: go1.15.8
```

#### Description:

Given `QmYw8okuEpxCPhfX3CKbF8mtpmyHPHP9VC3VNhUepytcSh` which is producing EOF error:

```console
$ ipfs files stat /ipfs/QmYw8okuEpxCPhfX3CKbF8mtpmyHPHP9VC3VNhUepytcS
Error: unexpected EOF
```

..one can import it to MFS, but then removal is not possible:

```
$ ipfs files cp /ipfs/QmYw8okuEpxCPhfX3CKbF8mtpmyHPHP9VC3VNhUepytcSh /foo
Error: cp: cannot flush the created file /foo: unexpected EOF

$ ipfs files ls /
foo

$ ipfs files rm /foo
Error: unexpected EOF
```

### :see_no_evil: 

I imagine we should 
- guard `files cp` against EOF somehow, so getting into this mess is not possible
- (and/or) make it possible to `files rm` even when a file causes unexpected error

**Comment by aschmahmann** [comment]
> guard files cp against EOF somehow, so getting into this mess is not possible

We can do some amount of guarding but unless we want `ipfs files cp` to become an expensive verification operation or add some potentially complicated indices and data labels around verification this is an inevitability. In particular, if the user imports a huge DAG using `ipfs files cp /ipfs/{rootCID} /mydag` then either we have to know that `rootCID` represents a valid UnixFS DAG or for the sake of performance/simplicity put this responsibility on the user.

 > (and/or) make it possible to files rm even when a file causes unexpected error

We do `ipfs files rm /mydag --force` will do the job

---

Seems like this is closeable, but if I've missed something feel free to reopen.
