### ISSUE TITLE
Improve DNSLink error

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#8000]
In 0.8.0, when DNSLink fails to resolve, a non-actionable error is displayed:

![2021-03-22--17-42-45](https://user-images.githubusercontent.com/157609/112026120-2c243f80-8b36-11eb-8076-90839959fb4d.png)

It is so vague that one may assume its IPFS fault :see_no_evil: 

@whyrusleeping suggested we should probably print an error that firmly places the blame on specific website  instead of  "ipfs failing to resolve". I agree, and think we could make it both actionable and educational, encouraging self-service. 

Some ideas for replacing `could not resolve name` :

1.  `DNS TXT record was not found at _dnslink.some.example.com`
2. `some.example.com is missing a DNSLink record (https://docs.ipfs.io/concepts/dnslink/)`
3. ?? (suggestions welcome)

cc @jessicaschilling @autonome

**Comment by gammazero** [comment]
This has been fixed by https://github.com/ipfs/go-namesys/pull/9
and by PR #8057

**Comment by hydrogenbond007** [comment]
I am still getting the error.

**Comment by hydrogenbond007** [comment]
@lidel Was trying to open nimi.eth.limo and snapshot but was unable to. Uniswap is working fine

**Comment by lidel** [comment]
You get error because there is no [DNSLink](https://docs.ipfs.io/concepts/dnslink/) TXT record on `_dnslink.nimi.eth.limo`.

You use a centralized HTTP server, and you get error because it is missing DNSLink.

:point_right:  Please report issue to the owner of `eth.limo`

Below are technical details you can relay to them:


----

No TXT record on `_dnslink.nimi.eth.limo`:


```console
$ dig +noall +answer TXT _dnslink.nimi.eth.limo
```

It should return something like:

```console
$ dig +noall +answer TXT _dnslink.nimi.eth.limo
_dnslink.nimi.eth.limo. 3600	IN TXT	"dnslink=/ipfs/bafybeigknsqcydpmamnjjlnhinq5clw6mlwgm76vxzrcjwmnfyygfhbyym"
```

This should be easy to fix, given they probably use https://github.com/wealdtech/coredns-ens behind the scenes anyway.

For reference, `_dnslink.nimi.eth` (without `.limo` suffix) has a valid DNSLink when resolved using DNS over HTTPS gateway provided by Cloudflare:

```console
$ curl -s -H 'accept: application/dns-json' 'https://resolver.cloudflare-eth.com/dns-query?type=TXT&name=_dnslink.nimi.eth' | jq .Answer
[
  {
    "name": "_dnslink.nimi.eth",
    "type": 16,
    "TTL": 3600,
    "data": "\"dnslink=/ipfs/bafybeigknsqcydpmamnjjlnhinq5clw6mlwgm76vxzrcjwmnfyygfhbyym\""
  }
...
```


`.limo` mirror should return the same records

**Comment by hydrogenbond007** [comment]
Big thanks @lidel ! Will try it out
