### ISSUE TITLE
more code comment 

### ISSUE THREAD

**Issue by ItsFunny** [ipfs/go-ipfs#8003]
I am a newbee to ipfs ,and I cant analyze theses code below 
```
stream.go#startStreaming
	go func() {
		_, err := io.Copy(s.Local, s.Remote)
		if err != nil {
			s.reset()
		} else {
			s.close()
		}
	}()

	go func() {
		_, err := io.Copy(s.Remote, s.Local)
		if err != nil {
			s.reset()
		} else {
			s.close()
		}
	}()
```
- whats theses for ? 
- where handle the logics 

Best Wishes

**Comment by Stebalien** [comment]
We could definitely use a lot better code documentation, but I'm going to close this issue as it's not directly actionable.

But thanks for the reminder, we'll keep this in mind.
