### ISSUE TITLE
README in github dark mode

### ISSUE THREAD

**Issue by ligi** [ipfs/go-ipfs#8024]
no biggie - just noticed it - since github has a dark mode now the contrast here can be a problem:

![Selection_075](https://user-images.githubusercontent.com/111600/112453776-50f7fd00-8d58-11eb-8072-9b90b79a38ff.png)

a simple color change can fix this

**Comment by RubenKelevra** [comment]
@ligi thanks for bringing this up. Can you give #8027 a review?

**Comment by ligi** [comment]
done

**Comment by RubenKelevra** [comment]
I pushed a third version to the PR:

![Screenshot_20210328_235303](https://user-images.githubusercontent.com/614929/112769368-ecbb8e80-9020-11eb-8abf-a7393f39d284.png)

**Comment by ligi** [comment]
even nicer!
