### ISSUE TITLE
go-ipfs\ipfs.exe : Win64/Trojan.Generic.HgEASREA 

### ISSUE THREAD

**Issue by doobo** [ipfs/go-ipfs#8032]
类型:包含木马的压缩包文件
描述:包含至少 1 个木马程序
go-ipfs\ipfs.exe : Win64/Trojan.Generic.HgEASREA

扫描引擎:云安全引擎
位置:F:\下载\go-ipfs_v0.8.0_windows-amd64.zip
处理建议:隔离文件
![image](https://user-images.githubusercontent.com/18480897/112740170-4c785200-8fad-11eb-9f91-f55875ee4ed6.png)

**Comment by RubenKelevra** [comment]
Hey @doobo,

where did you download this archive?

Can you provide a checksum of the archive?

I've uploaded the official windows 64 build of 0.8 to virustotal and it seems to be clean (as expected):

https://www.virustotal.com/gui/file/1de3dc6958db5490481d976f7837595f486ec0910cf70909c070ed8a2931b606/detection

**Comment by doobo** [comment]
> Hey @RubenKelevra
,
download: https://github.com/ipfs/go-ipfs/releases/download/v0.8.0/go-ipfs_v0.8.0_windows-amd64.zip

soft: https://api.5fu8.com/template/link/go/aaARrq

cid: QmQM691VRsCKRc3MioYC2KERVUVSHcxE24VmuSiNDthbDR

md5 : | 861277e621db4aecad796e479b87110a

sha256 : | f29802dfb4573cac91afdca95b0604d115523a1fd4018452ff2e36faa08191f0

**Comment by RubenKelevra** [comment]
> Hey @RubenKelevra
> download: https://github.com/ipfs/go-ipfs/releases/download/v0.8.0/go-ipfs_v0.8.0_windows-amd64.zip
> sha256 : | f29802dfb4573cac91afdca95b0604d115523a1fd4018452ff2e36faa08191f0

This is the file I've checked. There's no reason to believe it has been tempered with ATM. 

So it's likely just a false alarm by your antivirus tool. Contact the support team of the antivirus tool and let them know, so they can fix it :)

**Comment by Stebalien** [comment]
Unfortunately, anti-viruses are notorious for flagging p2p software as "malware", usually because p2p software makes and receives connections to random other peers on the internet (which can look suspicious).

Please report this as a false-positive to your AV provider (and tell us which AV provider this is so we can followup and make sure this doesn't happen again).

**Comment by doobo** [comment]
> Unfortunately, 
Security software：https://api.5fu8.com/template/link/go/aaARrq
Software name：360 Total Security
Software website： https://www.360totalsecurity.com

**Comment by doobo** [comment]
![image](https://user-images.githubusercontent.com/18480897/112960512-138bd900-9177-11eb-9def-402dbe6a796f.png)

**Comment by doobo** [comment]
![image](https://user-images.githubusercontent.com/18480897/112979847-b3ebf880-918b-11eb-99fc-333274f3f9de.png)

**Comment by Stebalien** [comment]
Thank you!
