### ISSUE TITLE
Questions about TPS testing bug

### ISSUE THREAD

**Issue by EdgarLQS** [ipfs/go-ipfs#8036]
version:v0.8.0
I used binary file to test the TPS was about 500, but I used Docker to test the TPS was about 160, why is this?
Thank you for your answer

**Comment by Stebalien** [comment]
IPFS doesn't have transactions.

**Comment by Stebalien** [comment]
Note:

- If you have a question about IPFS, please ask on discuss.ipfs.io.
- If you'd like to report a bug, please go into more detail about the issue you encountered.
