### ISSUE TITLE
Reprovider "roots" crash

### ISSUE THREAD

**Issue by hsn10** [ipfs/go-ipfs#8041]
go-ipfs version: 0.8.0
Golang version: go1.15.8

panic: close of closed channel

goroutine 760 [running]:
github.com/ipfs/go-ipfs-provider/simple.(*Reprovider).Run(0xc001f7b400)
        github.com/ipfs/go-ipfs-provider@v0.4.3/simple/reprovide.go:115 +0x285
created by github.com/ipfs/go-ipfs-provider.(*system).Run
        github.com/ipfs/go-ipfs-provider@v0.4.3/system.go:30 +0x75

reprovider is in roots mode

**Comment by aschmahmann** [comment]
@hsn10 can you give any context on when this happened? Was it during normal operation, while the node was shutting down, etc?

**Comment by hsn10** [comment]
During normal operation but there are frequent about 5 min long internet outages
