### ISSUE TITLE
ipfs panic at the time of pin many files

### ISSUE THREAD

**Issue by godcong** [ipfs/go-ipfs#8091]
#### Version information:

Ipfs version: 0.8.0
Repo version: 11
System version: arm64/android
Golang version: go1.16

#### Description:

before panic i was running `pin` many files.
but i never used `remote pin`.
i was running on the release version of ipfs 0.8.0 
```
2021-04-25T12:25:58.175Z        ERROR   remotepinning/mfs       pinning reading config (open /config.502382534: no such file or directory)
2021-04-25T12:26:47.781Z        ERROR   badger  writeRequests: Create value log file. Path=/badgerds/000603.vlog. Error=open /badgerds/000603.vlog: no such file or directory
2021-04-25T12:26:47.782Z        ERROR   badger  WatchBatch.Cancel error while finishing: Create value log file. Path=/badgerds/000603.vlog. Error=open /badgerds/000603.vlog: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x586ba9c1ec]

goroutine 8105555 [running]:
github.com/dgraph-io/badger.(*valueLog).write(0x4000d31d70, 0x400a42c460, 0xe, 0x14, 0x0, 0x0)
        /project/pkg/mod/github.com/dgraph-io/badger@v1.6.2/value.go:1166 +0x20c
github.com/dgraph-io/badger.(*DB).writeRequests(0x4000d31c00, 0x400a42c460, 0xe, 0x14, 0x586c5026f0, 0x0)
        /project/pkg/mod/github.com/dgraph-io/badger@v1.6.2/db.go:635 +0xa0
github.com/dgraph-io/badger.(*DB).doWrites.func1(0x400a42c460, 0xe, 0x14)
        /project/pkg/mod/github.com/dgraph-io/badger@v1.6.2/db.go:709 +0x44
created by github.com/dgraph-io/badger.(*DB).doWrites
        /project/pkg/mod/github.com/dgraph-io/badger@v1.6.2/db.go:762 +0x358
```

**Comment by godcong** [comment]
I tried to annotate the operation of the remote pin.
It still panic after a certain period of time.

**Comment by h1z1** [comment]
Curious was this in online or offline mode ( the daemon running)? 

I've run into similar things when pinning but in offline mode.    It's like the database doesn't completely "shutdown" though ipfs returns.

**Comment by godcong** [comment]
Yes, I running under daemon.
I am using a usb external ssd hard drive.
Before panic occurred, the reading of config also failed.
Will this be related to the performance of the hard disk or machine, or hard disk IO?

MyCPU is RK3399，4G memory，1T KIOXIA SSD under USB MODE

**Comment by godcong** [comment]
```
2021-04-25T14:51:21.284Z        ERROR   remotepinning/mfs       pinning reading config (open /config.275923813: no such file or directory)
2021-04-25T14:57:16.657Z        ERROR   badger  Failure while flushing memtable to disk: : open /badgerds/005138.sst: no such file or directory. Retrying...
```

I changed to pin a batch of files every 30 seconds 
Then appeared `Failure while flushing memtable to disk`.
You can see this error tries to run per seconds
But it was successfully written the second time
Is it possible that there is too much concurrency and there is not enough `io` on the disk to handle this.

**Comment by h1z1** [comment]
Sounds a bit different from what I have.  Shouldn't matter unless there are IO errors though which may be your case.   Anything in syslog about the device disappearing?  Given it's a usb drive.

**Comment by godcong** [comment]
@h1z1 what’s your system os and disk format?
i used ntfs in android.
Then, it is now changed to the default format of Android. It seems that this phenomenon doesn't happen anymore.
I found that there is a `ntfs-3g` process, which takes up a lot of memory space when using `ntfs`.
It may be that the processing performance of this process cannot meet the io of `ipfs` and causes the crash.

**Comment by h1z1** [comment]
@godcong - ext4 and zfs

**Comment by godcong** [comment]
This seems to be caused by ntfs-3g not having time to forward read and write requests, i changed to ext4
