### ISSUE TITLE
Improve pinning progress reporting

### ISSUE THREAD

**Issue by kallisti5** [ipfs/go-ipfs#8101]
Pinning ~20GiB on my node, and this is the progress I get:

```
$ ipfs pin add --progress /ipns/hpkg.haiku-os.org
Fetched/Processed 8353 nodes
Fetched/Processed 8540 nodes
.
.
Fetched/Processed 95036 nodes
etc.
```

It would be nice to have a little more information. Even some cleanup of the language would be helpful to be consistent. (is this node like a peer? Is it node like a chunk of a CID?)

Examples:

```
* Discovering Chunks: 8353 nodes (rolling update)

Then...

* Discovered Chunks across 9000 nodes
* Doing other stuff... (rolling update)
```

It may seem small, but after using IPFS for a few months off and on, I still don't know what it's talking about :laughing:

**Comment by kallisti5** [comment]
Someone just keyed me in onto ```ipfs bitswap stat```

This produces a wantlist:
```
        wantlist [1 keys]
                Qme5ubrNa932DxVxMtTkkjpiaKMLhVPfoFszyGfhS5BctD
```

Displaying the total wantlist count, or the CID's it wants on ```pin --progress``` might give users some idea on what's going on.

**Comment by godcong** [comment]
Can we get the total number of nodes？
This progress cannot clearly show the overall progress

**Comment by kallisti5** [comment]
I just realized I opened two enhancements for this one.
https://github.com/ipfs/go-ipfs/issues/8112 has a better example of what could be done... closing this one as a duplicate.
