### ISSUE TITLE
changed Mounts in config but still failed

### ISSUE THREAD

**Issue by bussiere** [ipfs/go-ipfs#813]
I changed the Mounts value 

  "Mounts": {
    "IPFS": "/media/bussiere/TOSHIBA EXT/ipfs",
    "IPNS": "/media/bussiere/TOSHIBA EXT/ipns"
  },

but i have this error message  

Error:  failed to open /etc/fuse.conf: Permission denied\nfusermount: failed to access mountpoint /ipfs: Permission denied

**Comment by jbenet** [comment]
thanks @bussiere, looks like a bug on our mount code.

**Comment by bussiere** [comment]
it's an external disk on NTFS but it should work i think

regards and thanks

**Comment by whyrusleeping** [comment]
@bussiere were you able to mount it there with the command line flags? `ipfs mount -f /x/y/z -n /a/b/c`

**Comment by lidel** [comment]
Seems that adding user to the 'fuse' group solved the same error for `givello` at IRC:
https://botbot.me/freenode/ipfs/2015-04-04/?msg=35837331&page=2

Just make sure your current user and/or fuse group have required permissions to `/media/bussiere/TOSHIBA EXT/`

**Comment by jbenet** [comment]
@lidel would you mind checking if thats in the ipfs fuse doc, and if not
adding it? thx

**Comment by diasdavid** [comment]
Seems this was done in https://github.com/ipfs/go-ipfs/issues/1026 :)
