### ISSUE TITLE
Cannot verify ipfs on Mac when downloading binary file

### ISSUE THREAD

**Issue by adam-worth** [ipfs/go-ipfs#8132]
#### Description:

While trying to install go-ipfs I've encountered the same error found in [issue-6756](https://github.com/ipfs/go-ipfs/issues/6756) where MacOS is unable to verify ipfs.

System:
- macOS Catalina 10.15.7

**Steps taken:**
Attempt 1:
- Downloaded [macOS binary](https://dist.ipfs.io/#go-ipfs)
- Followed steps taken in [issue-6756](https://github.com/ipfs/go-ipfs/issues/6756) when opening the binary
- Executed shell script within go-ipfs directory, `sh install.sh` (this succeeded and I was able to locate ipfs within my bin, which I then tried to then execute `ipfs version` to ensure it was installed correctly and ran into the same issue as in the aforementioned ticket)

Attempt 2:
- Followed [the command-line instructions](https://docs.ipfs.io/install/command-line/#official-distributions) which then suceeded

**Comment by lidel** [comment]
This was fixed in https://github.com/ipfs/distributions/pull/367 – please upgrade to go-ipfs 0.12.2 or later.
