### ISSUE TITLE
Remove part of path

### ISSUE THREAD

**Issue by nickreserved** [ipfs/go-ipfs#8137]
Hector suggests me here https://discuss.ipfs.io/t/weird-ipfs-add-error/11273/2 to report a bug.

I reach to this error with that sequence:
ipfs files rm -r /ΕΜΠ
ipfs add --nocopy -r /root/.ipfs/nas/Μηχανικός/ΕΜΠ
Second command failed because of file GaussPoints.m
Then I run the following command and it seems that ipfs try to add the file from a different path (where of course does not exist).
The screenshot is here: https://ibb.co/sJTLKkC

**Comment by Stebalien** [comment]
See https://discuss.ipfs.io/t/weird-ipfs-add-error/11273/4.
