### ISSUE TITLE
0.9.0-rc1 crashes with "panic: send on closed channel"

### ISSUE THREAD

**Issue by Luflosi** [ipfs/go-ipfs#8146]
#### Version information:
go-ipfs version: 0.9.0-rc1
Repo version: 11
System version: amd64/linux
Golang version: go1.15.10

#### Description:
After updating IPFS from version 0.8.0 to version 0.9.0-rc1, the daemon crashed after a little more than a day of running. It printed the following and exited with exit code 2/INVALIDARGUMENT:
```
panic: send on closed channel
goroutine 1720527432 [running]:
github.com/libp2p/go-libp2p-kad-dht/fullrt.(*FullRT).findProvidersAsyncRoutine.func1(0x23a9060, 0xc2315a15c0, 0xc01e55faa0, 0x22, 0xc2315a15c0, 0xc1e4fa17b0)
        /build/ipfs-src/vendor/github.com/libp2p/go-libp2p-kad-dht/fullrt/dht.go:1107 +0x649
github.com/libp2p/go-libp2p-kad-dht/fullrt.(*FullRT).execOnMany.func1(0x23a8fe0, 0xc35dfe2280, 0xc0003a0580, 0xc25ca568c0, 0xc0602e9da0, 0xc0602e9c80, 0xc01e55faa0, 0x22)
        /build/ipfs-src/vendor/github.com/libp2p/go-libp2p-kad-dht/fullrt/dht.go:844 +0xae
created by github.com/libp2p/go-libp2p-kad-dht/fullrt.(*FullRT).execOnMany
        /build/ipfs-src/vendor/github.com/libp2p/go-libp2p-kad-dht/fullrt/dht.go:841 +0x1c5
```
Before starting the daemon, I executed `ipfs config --json Experimental.AcceleratedDHTClient true` if that's relevant.
I don't know how to reproduce the error.
I'm happy to provide any additional information (command line arguments, config, etc....) that may be useful.

**Comment by aschmahmann** [comment]
Thanks @Luflosi for the report this seems to be related to a race condition in the experimental DHT client. It should get fixed up before the next RC.
