### ISSUE TITLE
failed to sync btt-tx

### ISSUE THREAD

**Issue by basunjoy3849** [ipfs/go-ipfs#8152]
![Screenshot 2021-05-22 121003](https://user-images.githubusercontent.com/83465336/119217300-edd7dc00-baf6-11eb-8b0e-6225aaddb4c4.png)

Can anybody help me with this, getting this repeatedly.

**Comment by aschmahmann** [comment]
This does not appear to be related to go-ipfs in any way. You should open an issue with the application that gave you the error you posted.

In the future if filing bugs on go-ipfs it will make it easier for you to get assistance if you could follow the report guidelines in the issue template (go-ipfs version, OS, what you were doing, etc.)
