### ISSUE TITLE
[OT] add configuration entries for timeout in BS monitoring tool

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#8157]
Formatting as independent issue to flag as potential tribute.

See https://github.com/ipfs/go-ipfs/pull/8082#issuecomment-847092561.

**Comment by coryschwartz** [comment]
I'm really not sure the best way to go about this.

As it is written in https://github.com/ipfs/go-ipfs/pull/8082, the configuration is driven by environment variables, so you could do this I think two ways.

1. Set the environment variables (i.e. with os.Setenv) and provide some reasonable commandline for doing that. 
    * this would be confusing, since some things that are driven by envirnment variables are not  read each time they are accessed
2. Provide runtime configuration and provide some reasonable commandline for doing that.
    * Plumbing through go-ipfs-config, 

Maybe it's sufficient just to look at the existing bitswap, although I admit I don't have full context so this might be wrong. I started an alternative implementation in https://github.com/ipfs/go-ipfs/pull/8356 that just looks at the bitswap  in the CLI -- this way the daemon can continue running and you don't need to make changes to variables.

**Comment by schomatis** [comment]
@coryschwartz 

I think your point number 2 above is exactly the plan in https://github.com/ipfs/go-ipfs/pull/8082#issuecomment-847092561 linked in the OP. Is there some confusion about the plan itself (adding to the standard `ipfs config` option), or how to execute that plan? I'm a bit confused on why you felt the need to propose an alternative (point 1): was there an issue with the original plan?

This effort is totally independent from the BitSwap issue the tool was trying to solve. It can just be thought of 'I need these two configuration variables to be _dynamically_ configurable so I don't need to restart the node on each change'.

**Comment by BigLep** [comment]
@schomatis : where did this land?  Is this worth picking up?

**Comment by schomatis** [comment]
I think not, closing.
