### ISSUE TITLE
`0.9.0-rc2` has the `-rc1` version

### ISSUE THREAD

**Issue by Jorropo** [ipfs/go-ipfs#8161]
![Capture d’écran du 2021-05-28 16-48-48](https://user-images.githubusercontent.com/24391983/120020358-e1b5b800-bfe9-11eb-8dc8-1556562b6a32.png)

I don't know if the build actually have all `-rc2` features but is named `-rc1` or if it's actually `-rc1`.

/cc @aschmahmann

**Comment by aschmahmann** [comment]
Oops, thanks I clicked the wrong folder for GitHub upload, the correct data is there now.

As an aside/heads up the data was correct on dist.ipfs.io which we currently have more tooling around publishing and is available over IPFS and via tools like https://github.com/ipfs/ipfs-update
