### ISSUE TITLE
[0.9.0-RC2] daemon no longer shutsdown cleanly

### ISSUE THREAD

**Issue by eminence** [ipfs/go-ipfs#8164]
#### Version information:
go-ipfs version: 0.9.0-rc2-4d31ec1b8
Repo version: 11
System version: amd64/linux
Golang version: go1.15.2

#### Description:
After running the daemon, and then pressing <kbd>ctrl+c</kbd>, I see these messages:

    Received interrupt signal, shutting down...
    (Hit ctrl-c again to force-shutdown the daemon.)

But after several minutes, the daemon remains running.  In my experience, shutting down the daemon in this way will actually shutdown the daemon within 2 or 3 seconds.  Pressing <kbd>ctrl+c</kbd> a second time will correctly terminate the daemonl

Please note that I'm running RC2 with the following experimental settings:

```json
 "Experimental": {
    "AcceleratedDHTClient": true,
    "FilestoreEnabled": true,
  },
```

**Comment by aschmahmann** [comment]
@eminence thanks for the report. I've seen this happen mostly if you're in the middle of doing a reprovide of a lot of data while using the accelerated dht client. It's still worth fixing, but if so it's a little less critical given that this occurs by default once every 12 hours.

If you dump the output from running `ctrl + \` (i.e. killing the daemon and dumping the stack) when this behavior occurs it'll be easier to diagnose. Note that you will likely need to pipe the logging the output to a file or your terminal may overload with too much data from the dump.

**Comment by eminence** [comment]
I confirm that this is actually not that common.  Happens maybe.... 5% or 10% of the time?  (That's a very unscientific guess).
But it can happen when trying to kill the daemon seconds after starting it.

I was able to capture the full dumps twice.  They are indeed very long, so I'm uploading them (instead of including them inline)


[ipfs-daemon.log](https://github.com/ipfs/go-ipfs/files/6585528/ipfs-daemon.log)
[ipfs-daemon2.log](https://github.com/ipfs/go-ipfs/files/6585529/ipfs-daemon2.log)

**Comment by RubenKelevra** [comment]
This might be related?

https://github.com/ipfs/go-ipfs/issues/8195

**Comment by lidel** [comment]
@eminence mind checkign if this is still the case with 0.12.2 or later?

**Comment by eminence** [comment]
I won't be able to do any additional testing on this for a little bit, so let's go ahead and close this issue under the assumption that it's been fixed.  If I see this again, I'll let you know!
