### ISSUE TITLE
Increase maxium chunk size to 4mb

### ISSUE THREAD

**Issue by lizelive** [ipfs/go-ipfs#8179]
Setting the chunk size to 1mb doubles the performance over a chunk size of 256kb.
Increasing it further will allow for efficient usage of cloud storage back-ends where the request as well a improving local performance esp with HDD and write amplification.
This also increases the size of files that can be handled efficiently without removing the ability to deal with smaller files.

**Comment by jesuscoins776** [comment]
How can I perform this action?

**Comment by aschmahmann** [comment]
Increasing the maximum chunk size also increases the amount of data that a malicious peer can send over Bitswap before you realize it's the wrong data (i.e. it wastes your bandwidth). Until that's resolved (e.g. some proposal like https://github.com/protocol/beyond-bitswap/pull/29) then increasing this limit seems unlikely.

Similarly, if you actually want to be able to retrieve the data from a go-ipfs node then this requires a spec change to Bitswap across all implementations to be able to support it.

Overall, this doesn't seem likely to change in the near future as it has security tradeoffs as well as requires spec changes. If/when go-ipfs starts being able to send arbitrarily sized blocks without adding much attack surface this could be revisited.

I'm going to close this issue for triage purposes, but if you'd like to discuss this more on discuss.ipfs.io (or here) feel free. I'd recommend the forums as closed GitHub issues have low discoverability.
