### ISSUE TITLE
How do I manually push files to the entire IPFS network

### ISSUE THREAD

**Issue by herexu** [ipfs/go-ipfs#8184]
Help
How do I manually push files to the entire IPFS network?
I tested the Add file to the local IPFS node file and it will not sync to other nodes right away.
enven after three hours

**Comment by unbeatable-101** [comment]
> Help
> How do I manually push files to the entire IPFS network?
> I tested the Add file to the local IPFS node file and it will not sync to other nodes right away.
> enven after three hours

Try sharing your peer id `ipfs id` and asking them to manually connect to it

Also you should have probably asked this on https://discuss.ipfs.io/

**Comment by bertrandfalguiere** [comment]
No other node will ever download your content unless they ask for it. Otherwise, any node could flood the network and your own node with their content. The "add" command just advertize to the network that you have this piece of data and that you are ready to send it if it is requested. You can ask pinning service to host your stuff if needed.

**Comment by herexu** [comment]
> Try sharing your peer id `ipfs id` and asking them to manually connect to it
> 
> Also you should have probably asked this on https://discuss.ipfs.io/

how to share my peer id `ipfsid `?
i am not find the fouction on the doc.ipfs.io.
the doc of office <https://docs.ipfs.io/how-to/address-ipfs-on-web/> doesn't have the solution.
or is there something wrong withe my thinking

**Comment by unbeatable-101** [comment]
> how to share my peer id ipfsid ?

Type `ipfs id` into the commandline and copy one of the addresses (e.g. `/ip6/::1/udp/4001/quic/p2p/12D3KooWRwY7U7mNmtB8naEJFu87kvnUMMeb7bsJfPJ1xiN9V4C6`, make sure it doesn't have `192.168.0.#` or `127.0.0.1` in it)

Then type `ipfs swarm connect <address>` on the machine you are trying to connect with and it should resolve the CID

**Comment by herexu** [comment]
> You can ask pinning service to host your stuff if needed.

how to ask pinning ipfs.io? 
it there describe in the office doc?

> > 如何共享我的对等 ID ipfsid？
> 
> 键入`ipfs id`到命令行并复制地址之一（例如`/ip6/::1/udp/4001/quic/p2p/12D3KooWRwY7U7mNmtB8naEJFu87kvnUMMeb7bsJfPJ1xiN9V4C6`，确保它不具有`192.168.0.#`或`127.0.0.1`它）
> 
> 然后`ipfs swarm connect <address>`在您尝试连接的机器上键入，它应该解析 CID

**Comment by unbeatable-101** [comment]
> how to ask pinning ipfs.io?

http://docs.ipfs.io/how-to/work-with-pinning-services/#use-an-existing-pinning-service

**Comment by herexu** [comment]
> > 如何询问固定ipfs.io？
> 
> http://docs.ipfs.io/how-to/work-with-pinning-services/#use-an-existing-pinning-service

$ ipfs pin remote service add nickname https://my-pin-service.example.com/api-endpoint myAccessToken

myAccessToken is the unique secret token provided to you by the pinning service. 

how can i fetch the myAccessToken

**Comment by unbeatable-101** [comment]
You get one from the pinning service's website

**Comment by herexu** [comment]
> You get one from the pinning service's website

from the https://ipfs.io/?
I am not found the entrance in https://ipfs.io/

**Comment by unbeatable-101** [comment]
That is a gateway, not a pinning service.

Check out pinata.cloud

**Comment by herexu** [comment]
> That is a gateway, not a pinning service.
> 
> Check out https://pinata.cloud

i can't open https://pinata.cloud in browser, but i can ping pinata.cloud

**Comment by herexu** [comment]
> https://pinata.cloud
https://pinata.cloud is the office service?
if the https://pinata.cloud  is stop the service , isn't my node out of the network ?
and if my node is pin to the https://pinata.cloud ,my file can query on ipfs.io?

**Comment by herexu** [comment]
> That is a gateway, not a pinning service.
> 
> Check out https://pinata.cloud

if i don't use the pinning service of choice supports then  how to use the commands to push the file to network.
now the situation is i use hte ipfs servie, and ipfs add <myfile>,but <myfile> can push to the web,I can't query from the https://ipfs.io/ipfs/xxxxxxx

**Comment by RubenKelevra** [comment]
Hey @herexu,

as explained before adding a file to your local ipfs node, with `ipfs add` will advertise this file to the network.

If someone else wants to access the file, he/she will download the file from your node and store it temporarily in his/her node.

When you access a CID via http, like `https://ipfs.io/ipfs/$CID` the http gateway will request the file from your local node and deliver it back to you via http.

This obviously means the file is (for a short while) stored on the HTTP gateway server, serving the file to your browser. But there's no guarantee how long the file is being stored there.

If you want to have persistency of your file on the network, you either need to run a server that serves the file to the network, or you need to create an account on a pinning service, where you can enter the CID to be stored (pinned) there.

As an easy starting point to get a server which can hold some gigabytes of data for you, have a look at oracle - they offer a free tier for a small server:

https://www.oracle.com/cloud/free/

(not affiliated in any way with IPFS or me) :)

**Comment by Stebalien** [comment]
Please move this discussion to https://discuss.ipfs.io.
