### ISSUE TITLE
"ipfs dns" fails on subdomains containing underscores

### ISSUE THREAD

**Issue by jsmaniac** [ipfs/go-ipfs#8186]
#### Version information:

```
go-ipfs version: 0.8.0
Repo version: 11
System version: amd64/linux
Golang version: go1.16.4
```

#### Description:

`ipfs dns` fails on subdomains containing underscores, but the dnslink entry is present and can be fetched using `dig`:

```
$ ipfs dns computer_programmer.neocities.org
Error: not a valid domain name: computer_programmer.neocities.org

$ dig +short TXT computer_programmer.neocities.org
"dnslink=/ipfs/QmPfFntYpZcyom5XnQN1st2YvCANykPWYrTrUzTkqpgJFT"
```

**Comment by BigLep** [comment]
In 0.9 we made significant changes to our DNS handling and we're no longer coupled to the ICANN list.  Please reopen if this manifests on 0.9.  Thanks!
