### ISSUE TITLE
ipfs key export name-of-key shouldn't require stopping the daemon

### ISSUE THREAD

**Issue by jsmaniac** [ipfs/go-ipfs#8187]
When I run `ipfs key export name-of-key` I get the following error:

```
Error: ipfs daemon is running. please stop it to run this command
Use 'ipfs key export --help' for information about this command
```

Since this operation is pretty much just copying the key out of `~/.ipfs/keystore` as follows, there's not much reason to require any lock at all, assuming that the keys are added to the keystore using an atomic `mv`. If the keys are not added to the keystore atomically it is a concern (if the computer is stopped abruptly halfway through writing a key, it would cause some problems), but would still not warrant stopping the entire daemon just to access one small file.

```
ipfs_key_export() {
  cp ~/.ipfs/keystore/key_$(printf %s "$1" | base32 | tr '[:upper:]' '[:lower:]') "$1"
}
```

**Comment by aschmahmann** [comment]
Done in #8113, will be in the v0.9.0
