### ISSUE TITLE
`ipfs add --nocopy` is not properly handeling symlinks

### ISSUE THREAD

**Issue by ljmf00** [ipfs/go-ipfs#8188]
#### Version information:
```
go-ipfs version: 0.8.0-ce693d7e8
Repo version: 11
System version: amd64/linux
Golang version: go1.16.2
```

#### Description:

I'm creating an IPFS mirror for Arch Linux package repository to have my hands dirty. After syncing with `rsync` and adding the repo with `ipfs add -r --raw-leaves --nocopy --fscache /mnt/ArchlinuxMirror` discovered that symlinks are not properly handled. See this example:

The HTTP version of the mirror is: https://mirror.f4st.host/archlinux/

In the IPFS version, `ipns://k51qzi5uqu5dmhjdoh63s0ec29xgn895ripzszbudvzzitgarxmhcm8ym4fh6h/community/os/x86_64/community.db` this is a symlink to `community.db.tar.gz` but instead, it's outputting the string path of the symlink.

This can possibly have security issues as it may disclose internal paths to the files. I didn't test it tho.

**Comment by BigLep** [comment]
IPFS is adding as a symlink.  This is what IPFS does.  Currently you'll need to resolve symlinks outside of IPFS before doing ``ipfs add``.

**Comment by ljmf00** [comment]
> IPFS is adding as a symlink. This is what IPFS does. Currently you'll need to resolve symlinks outside of IPFS before doing `ipfs add`.

A flag to resolve symlinks is desired, symlinks out of the given context folder should warn the user,  and possibly halt the execution, and a custom context could be passed to avoid warnings of that type.

Including symbolic links out of the context folder could lead to scary things at the end-user part if they follow symbolic links by default.
