### ISSUE TITLE
go-ipfs isn't updated in brave

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#8199]
The built-in version of go-ipfs in the brave browser is still at version 0.7 which is quite old.

Why is that? Is there a compatibility issue with 0.8?

Here's the ticket in the brave bugtracker:

https://github.com/brave/brave-browser/issues/16171

**Comment by aschmahmann** [comment]
As alluded to in the v0.9.0 release issue https://github.com/ipfs/go-ipfs/issues/8058 Brave was having difficulty running repo migrations (such as the v0.7.0 to v0.8.0 one) when users were in restrictive environments. That should be helped with the updating migrations over IPFS work.
