### ISSUE TITLE
Storing Bytes kind through DAG-JSON via `ipfs dag put` fails.

### ISSUE THREAD

**Issue by d70-t** [ipfs/go-ipfs#8216]
#### Version information:
```
$ ipfs version --all
go-ipfs version: 0.9.0
Repo version: 11
System version: amd64/darwin
Golang version: go1.16.5
```

#### Description:
According to the [DAG-JSON spec](https://ipld.io/specs/codecs/dag-json/spec/#bytes-kind), it should be possible to express data as a Bytes kind using e.g. `{"/": {"bytes": "maGVsbG8"}}`. In this case `maGVsbG8` is multibase base64 encoding of some bytes, in this case, the ASCII-String `hello`.

Trying to add such an object to IPFS using:
```bash
echo '{"test": {"/": {"bytes": "maGVsbG8"}}}' | ipfs dag put --input-enc=json
```
results in the following error:
```
Error: link should have been a string
```

My suspection is that that go-ipfs tries to read this accidentally as a [Link kind](https://ipld.io/specs/codecs/dag-json/spec/#link-kind), which is not correct.

My expectation would be, that this object would be added just fine.

**Comment by lidel** [comment]
This should be fixed in 0.10.0-rc1 – give it a try!
