### ISSUE TITLE
cant build IPFS from source: Interrupt/Exception caught (code = 0xc0000005, addr = 0x73776f64)

### ISSUE THREAD

**Issue by shaheerbakali** [ipfs/go-ipfs#8226]
I want to build IPFS from source.
I have been following the steps that are given here: https://github.com/ipfs/go-ipfs/blob/master/docs/windows.md

When I execute this command in my cmd: make install
I get the following error: 
C:\Users\Lenovo\go\src\github.com\ipfs\go-ipfs>make install
go version go1.16.5 windows/amd64
bin/check_go_version 1.15.2
plugin/loader/preload.sh > plugin/loader/preload.go
make: *** [plugin/loader/Rules.mk:8: plugin/loader/preload.go] Error 1

Please can someone help me out here, thanks alot.

**Comment by Stebalien** [comment]
https://superuser.com/questions/375029/make-interrupt-exception-caught? Alternatively, try running `go build -o ipfs.exe ./cmd/ipfs` directly.

If that doesn't work, please ask on the forums (https://discuss.ipfs.io).
