### ISSUE TITLE
error building IPFS from source!

### ISSUE THREAD

**Issue by shaheerbakali** [ipfs/go-ipfs#8228]
I am trying to build IPFS from source following steps from: https://github.com/ipfs/go-ipfs/blob/master/docs/windows.md
and after this command in cmd: `make install`
I get the following error: 
```
go version go1.16.5 windows/amd64
bin/check_go_version 1.15.2
plugin/loader/preload.sh > plugin/loader/preload.go
/bin/sh: line 1: plugin/loader/preload.go: Permission denied
make: *** [plugin/loader/Rules.mk:8: plugin/loader/preload.go] Error 1
```

Please please can someone help me out on this.
Thanks alot!

**Comment by Jorropo** [comment]
@shaheerbakali you need to run in a bash compatible shell.

cmd isn't.

Install cgywin (built in with the git installation) and use this shell, or use WSL.

**Comment by Stebalien** [comment]
Please ask on the forums (https://discuss.ipfs.io).
