### ISSUE TITLE
CID bafkqaaa causes error: cannot detect content-type: EOF

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#8230]
> Originally reported by Brave: https://github.com/brave/brave-browser/issues/16671

go-ipfs 0.9.0 updated  mimetype dep https://github.com/gabriel-vasile/mimetype and that introduced regression on gateway when an empty byte array payload is returned to the user.

Unfortunately, that edge case changes HTTP response for CID `bafkqaaa` which we use in various places.
- In v0.8.0 it was empty body with HTTP 200 (ok) status code
- In v0.9.0 it returns `cannot detect content-type: EOF` with HTTP 500 error

## TODO

- [x] Switch back to 1.1.2 (safe choice for patch release) – done: https://github.com/ipfs/go-ipfs/pull/8229
     > We were at 1.1.2 in v0.8.0 the latest is v1.3.0 which seems ok, and v1.2.0 is what we have and has the behavior change
- [x] Add sharness tests – done: https://github.com/ipfs/go-ipfs/pull/8232

**Comment by aschmahmann** [comment]
Switching back to 1.1.2 #8229

**Comment by lidel** [comment]
Sharness test https://github.com/ipfs/go-ipfs/pull/8232

**Comment by gabriel-vasile** [comment]
Hi,
> We were at 1.1.2 in v0.8.0 the latest is v1.3.0 which seems ok, and v1.2.0 is what we have and has the behavior change

I'm pretty sure v1.3.0 is not ok. The offending change is https://github.com/gabriel-vasile/mimetype/commit/b1ae8bfa0b92cc1d99213c1b8ea8cac8614dcd18#diff-cf06cf150d88adb18fa7da76b698e820f978ae9b6c547b3530305051e6687459L44
I'll add the missing `err != io.EOF` and release it as v.1.3.1.
