### ISSUE TITLE
IPFS and Solidity contract

### ISSUE THREAD

**Issue by alysak6075** [ipfs/go-ipfs#8235]
Hello,

I am trying to retrieve the IPFS hash/file that is at the bottom of the Contract tab

https://etherscan.io/address/0xbbd3c0c794f40c4f993b03f65343acc6fcfcb2e2#code

This is the link:
ipfs://62c1e84b5f1f3effe1c0e4adbbd785ad950c738ea87a7aaef091add4452a9cbd

from my understanding and from the solidity docs this is the IPFS hash of the file but IPFS responds with:
Error: invalid path "/ipfs/62c1e84b5f1f3effe1c0e4adbbd785ad950c738ea87a7aaef091add4452a9cbd": invalid CID: selected encoding not supported

it looks like i need to base58 encode this:
122062c1e84b5f1f3effe1c0e4adbbd785ad950c738ea87a7aaef091add4452a9cbd

which gives me this:
QmUzAA35NGHkSs5nMDXh9HgvbNWwmiQ24xQTx3Ppedfeip

which LOOKS like a valid hash for ipfs.
but it hangs and never receives anything.
if someone could point me in the right direction?

Please help?

**Comment by aschmahmann** [comment]
As mentioned by the bot above please go to https://discuss.ipfs.io for general support questions.
