### ISSUE TITLE
ipfs pin add --progress stuck at "Fetched/Processed 0 nodes" for hours

### ISSUE THREAD

**Issue by ligi** [ipfs/go-ipfs#8242]
I added some content - a directory via `ipfs add -r <path>` and it worked:

```
...
added Qmcwa4FAW74p3M5AsRLC41ifo5ytEouam7EL1Ad3MasNog output
 8.26 MiB / 8.26 MiB [==============================================================================================================================] 100.00%
```
and took about 30min

then I tried to pin it on my dappnode (added it on my laptop which is not 100% online) and it was just hanging:

![image](https://user-images.githubusercontent.com/111600/124442648-3d0f5e80-dd7d-11eb-9d91-addc653c070c.png)

And as I do not get any progress there I tried:

`ipfs pin add QmZvCJBNKdKMohHE5u18vNgK6pA3RS5CkWu82M7HWZ84pA --progress`

even on the same machine where I did the successful `ipfs add` to eliminate connection problems.
And it is stuck on `Fetched/Processed 0 nodes` for hours.
The problem is that one subdirectory contains a lot of (small) files (272745)
Is there anything I can do or is it just not possible with IPFS?

if you want to reproduce it - I was trying to pin the directory `output` that is created in the build-step of https://github.com/ethereum-lists/website
But guess a simpler repo might be to just use https://github.com/ethereum-lists/4bytes directly as I am pretty sure this is the culprit (cannot test now as I am now on 3g and limited data)

**Comment by aschmahmann** [comment]
@ligi there's not a ton of information in here to go on and for general support questions like these it's best to go to discuss.ipfs.io. This helps us keep our issue tracker more focused on bugs and features while also making it easier for the community to discover solutions to existing questions (nobody can really find anything on closed GitHub issues). Feel free to tag me in your post there and we can continue.

**Comment by ligi** [comment]
I opened a post here: https://discuss.ipfs.io/t/adding-a-directory-with-a-lot-of-files/11730
that said I really think it is a bug - it is stuck at 'Fetched/Processed 0 nodes' for days now - and I think it is a bug triggered by too many files (maybe some overflow)
