### ISSUE TITLE
How to edit IPFS source code?

### ISSUE THREAD

**Issue by shaheerbakali** [ipfs/go-ipfs#8246]
Hello,

I have built IPFS from source on my laptop.

Now I want to edit the source code for my own project.

To start off, I am trying to edit the code such as when I run the command `ipfs swarm peers` I want the code to run and print whatever message I would like.

Please can someone help me in doing this.
Thanks alot!

**Comment by RubenKelevra** [comment]
Source code is usually edited with a text editor. If you're not familiar which tools are recommended, have a look at [How to Write Go Code](https://golang.org/doc/code).

Please refrain from opening further tickets here, if they are not directly related to bugs or features in the project's source code.

If you like to chat casually with the community, the [forum](https://discuss.ipfs.io/) is the right place.

**Comment by aschmahmann** [comment]
As mentioned above for general support ask on discuss.ipfs.io
