### ISSUE TITLE
[Request] Configuration option for max number of peers from one address.

### ISSUE THREAD

**Issue by obo20** [ipfs/go-ipfs#8259]
From looking through many of our IPFS peers, we're starting to see an uptick in cases where many peers are coming from one IP address or one IP address block. These IP addresses are constantly changing and are coming from all over the world.

I can't think of a legitimate reason for this type of behavior. @aschmahmann can you think of any?

It would be nice to cut down on spammy addresses by having a config setting that prevents IPFS from connecting to a peer if it shares the same IP address as another peer. (Or possibly you could provide a max number of peers per IP address as the config option).

To take it one step further if you could do this with IP blocks that would be even better. I'm seeing many cases that look like this:
AA.BBB.CC.224/.......
AA.BBB.CC.224/.......
AA.BBB.CC.224/.......
AA.BBB.CC.224/.......
AA.BBB.CC.224/.......
AA.BBB.CC.224/.......
AA.BBB.CC.225/.......
AA.BBB.CC.225/.......
AA.BBB.CC.225/.......
AA.BBB.CC.225/.......
AA.BBB.CC.225/.......
AA.BBB.CC.225/.......
AA.BBB.CC.225/.......
AA.BBB.CC.226/.......
AA.BBB.CC.226/.......
AA.BBB.CC.226/.......
AA.BBB.CC.226/.......
etc...

So if there's something that could prevent this as well that would also be awesome, but I would be happy even for a singular IP level config option.

**Comment by Stebalien** [comment]
> I can't think of a legitimate reason for this type of behavior. @aschmahmann can you think of any?

Yes. ISP level NATs and running out of IPv4 addresses.

It's perfectly reasonable to put restrictions in-place if:

1. You know what you're doing and you're aware that you might potentially cause problems for legitimate users.
2. You are _not_ running as a DHT server. If you're running as a DHT server, refusing some requests but not others can degrade the network.

Given this, I'd be hesitant to put this _directly_ into go-ipfs (users will just "turn it on" without understanding it, we've seen that happen in the past). Have you considered firewall rules? E.g. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-using_nftables_to_limit_the_amount_of_connections

**Comment by obo20** [comment]
@Stebalien that's a good point. I'll consider this issue resolved since it seems there are indeed legitimate use cases for this.

**Comment by thattommyhall** [comment]
multiple ports on the same IP is how the hydra-boosters work too, you'd not want to exclude them
