### ISSUE TITLE
Low power mode / traffic reduction 

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#8285]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Not a protocol enhancement 

I don't think this feature requires any change to the bitswap protocol, as we are just change our answer to the requests for certain blocks for a short period of time. 

### Description

Currently we have a low power profile which reduces the amount of open connections and switch the dht from server to client.

I like to propose an addition which would would reduce the amount of traffic further to enhance battery life and on slow uplink connections to allow a node to focus on "useful" transfers.

The functionality might sound similar to so called superseeding in some BitTorrent clients - but is much simpler and without additional queries to other nodes. 

The idea is keep a list of the last transferred blocks in memory as a list, with a lifetime of say 15 minutes and a list length of 10'000 elements.

If the 15 minutes elapsed for an element or the 10'000 elements are overflowing, the entry(s) would be deleted.

If a transfer is requested and the block is on the list, the node would temporarily respond with "I don't have this block".

This way a node isn't sending the same blocks to multiple nodes, while they could request the blocks from each other and keep the upstream free to send new blocks to the network.

After 15 minutes we basically assume that the node which received the block in the past is now offline and can't provide it.

#### Implementation idea

To simplify the complexity of dropping from the end of the queue and dropping old items, we could hold a hash table for each minute and count the global amount of items in a counter.

If a minute elapsed, we just drop the whole hash table and create a new one for the new minute. 

If we reach 10'000 elements in the global counter, we just drop elements (randomly) from the oldest hash table with elements in it.

**Comment by Stebalien** [comment]
Problem: limited upload bandwidth.
Solution: limit upload bandwidth.

Anyways, bitswap prefers faster (low latency) peers when downloading, so most peers will swarm around those faster peers. We could take advantage of this by delaying outbound responses.

Responding with "I don't have" for 15 minutes is _very_ likely to break things in strange, hard to debug ways (leading to strange, hard to debug bug reports that I'll have to deal with). We can't actually _know_ if there's some "super seeder" available.

Also note: a _lot_ of bitswap bandwidth isn't responding to blocks, it's receiving random requests from random peers looking for content they can't find on the DHT. The best way to save power is to run in DHT "client" mode and set very low connection manager limits to receive fewer of these opportunistic requests.

If you'd like to play around with different bitswap strategies, I highly suggest you try out testground and https://github.com/ipfs/test-plans/tree/master/bitswap-tuning.

---

And again I'd like to ask you to focus on one problem, research it till you know it backwards and forwards, then try to solve it. I appreciate your enthusiasm, but having to explain to you why your latest under-researched idea won't work takes a tremendous amount of my time.

**Comment by RubenKelevra** [comment]
> And again I'd like to ask you to focus on one problem, research it till you know it backwards and forwards, then try to solve it. I appreciate your enthusiasm, but having to explain to you why your latest under-researched idea won't work takes a tremendous amount of my time.

Okay

**Comment by Stebalien** [comment]
To expand on this slightly, discuss.ipfs.io is a great place to post random ideas as food for thought. It's just that every issue and PR in this repo gets triaged by, and demands time from, the core team.
