### ISSUE TITLE
Installing node onto user-specified hard drive

### ISSUE THREAD

**Issue by michK** [ipfs/go-ipfs#8300]
### Checklist

- [X] I am reporting a documentation issue in this repo, not https://docs.ipfs.io.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Location

https://docs.ipfs.io/how-to/configure-node/#datastore

### Description

I want to specify a node to use a specific hard drive, which is not the MFS drive.

I have tried installing go-ipfs onto the drive I want to house the node, but when I `init` the node, it seems to
automatically place the node in the home directory of the MFS. Moving the created `.ipfs/` directory to
the other drive seems to mess up the configuration since running `ipfs` now tells me I need to re-`init`,
so it is not seeing the moved node directory.

I believe some documentation on how to specify a custom storage location will be useful.

**Comment by michK** [comment]
I have just stumbled onto the following when running `ipfs` without argument:

```
ipfs uses a repository in the local file system. By default, the repo is
  located at ~/.ipfs. To change the repo location, set the $IPFS_PATH
  environment variable:
  
      export IPFS_PATH=/path/to/ipfsrepo
```

Using this I can create the node on the disk I want to use, which partially solves my problem, but I would still be curious whether the node can be installed on my MFS while specifying a different disk for storing the data.

**Comment by Stebalien** [comment]
This is documented in `ipfs init --help`.

> Using this I can create the node on the disk I want to use, which partially solves my problem, but I would still be curious whether the node can be installed on my MFS while specifying a different disk for storing the data.

I assume MFS -> NFS?

I assume you're trying to put your repo (config, private keys, etc.) in one place and the data in another? The only way to do this is with symlinks.

If you have any more questions on this, please ask on the forums. Splitting out parts of the repo isn't something common enough to be documented.

**Comment by michK** [comment]
Thank you very much.

With MFS I meant main file system, which I assume is same as NFS (native file system?).

I don't mind so much where the repo etc is, as long as the node is on the other drive, which I was able to figure out with the `IPFS_PATH=/path/to/ipfsrepo` environmental var.

Thanks again.

**Comment by Stebalien** [comment]
> With MFS I meant main file system, which I assume is same as NFS (native file system?).

[NFS](https://en.wikipedia.org/wiki/Network_File_System)

> I don't mind so much where the repo etc is, as long as the node is on the other drive, which I was able to figure out with the IPFS_PATH=/path/to/ipfsrepo environmental var.

Please try to be a bit more specific. "node" could mean anything here.

**Comment by michK** [comment]
With node I meant the disk location where the data is stored.

I have a 2TB drive that I would like to host various IPFS projects data, so I do not mind where specific applications are stored, as long as the data is stored on the 2TB drive.

**Comment by Stebalien** [comment]
Ah, got it. Yes. Setting IPFS_PATH is the way to go.
