### ISSUE TITLE
IPLD Prime leftover bugs

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/go-ipfs#8373]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

built from source

### Description

- [ ] #8377
- [ ] #8378
- [ ] #8376

https://github.com/ipfs/go-ipfs/pull/7976#issuecomment-900421769

**Comment by warpfork** [comment]
I'm breaking all three of these out into their own issues.  They are all sizable, and none of them has anything to do with each other, and they are not likely to be equal importance nor urgency either.
