### ISSUE TITLE
IPFS http servers do not respond meaningfully to HEAD requests

### ISSUE THREAD

**Issue by BrendanBenshoof** [ipfs/go-ipfs#840]
node:5001/ipfs/hash returns code 400 Bad Request for all HEAD requests

node:8080/ipfs/hash returns 405 (arguably correct) for all HEAD requests
node:8080/ipns/hash returns 405 (arguably correct) for all HEAD requests

node:5001/ returns code 404 (correct!)
node:5001/webui returns 302 on my machine
node:5001/webui returns 301 on the travis CI machine
node:5001/webui/ returns 404 (ideally fixed soon in pull #823 )

Ideal behavior is HEAD requests returning corresponding errors as if they were a GET request.

**Comment by jbenet** [comment]
Agreed! Thanks for reporting

**Comment by Kubuxu** [comment]
This was resolved:
```
$ curl -I localhost:8080/ipns/bin.kubuxu.ovh/
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output
Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output
Content-Length: 1986
Content-Type: text/html; charset=utf-8
Last-Modified: Tue, 02 Feb 2016 21:18:55 GMT
Suborigin: bin.kubuxu.ovh
X-Ipfs-Path: /ipns/bin.kubuxu.ovh/
Date: Tue, 02 Feb 2016 21:18:55 GMT

$ curl -I localhost:8080/ipns/nonexisting.kubuxu.ovh/
HTTP/1.1 400 Bad Request
Date: Tue, 02 Feb 2016 21:19:03 GMT
Content-Length: 43
Content-Type: text/plain; charset=utf-8
```
