### ISSUE TITLE
`ipfs files ls` not working for symlink files

### ISSUE THREAD

**Issue by LynHyper** [ipfs/go-ipfs#8400]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

third-party binary

### Version

```Text
go-ipfs version: 0.9.1-dc2715af6
Repo version: 11
System version: amd64/linux
Golang version: go1.16.6
```

### Config

```json
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Announce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip6/::/udp/4001/quic"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa"
  ],
  "DNS": {
    "Resolvers": null
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Experimental": {
    "AcceleratedDHTClient": false,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "ShardingEnabled": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "12D3KooWRrHcQmuvWwq4Fa9UN7EnVgWgvFcm57oPF6BmfmegxocN"
  },
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": null,
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Type": "dht"
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 900,
      "LowWater": 600,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "EnableAutoRelay": false,
    "EnableRelayHop": false,
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

### Description

Apologise in advance if this is a duplicate, I've checked a number of the existing issues and as far as I could find there are no issues describing this problem, however, I might of missed it since there are quite a few.

**How to replicate:**

1. Create a dir called `test`
2. Create a file outside of `test` called `testfile`
3. Create a symlink from `testfile` to `test/symtestfile`
4. Do `ipfs add -r test/` or `ipfs add test/symtestfile`
5. `test` and `symtestfile` will fail to be added, but, no error messages are created. Strangely though, `ipfs pin ls` still returns values despite the fact that `ipfs files ls` does not. `testfile` can be added completely fine.
6. Using the IPFS node's webui with the "Import" button works completely fine and the folder and file are added correctly with the correct content.

With CLI:
```
ipfs add -r test/
added QmY5DTqJZTVFrv7Su37ycNRZkZqAr66awtYqiDTGuuXtaJ test/testfile
added QmXJ9LSyT4b2Vez1g9YLDdVYzEJyVb4GEyy8k5LFY4XjPs test
 0 B / ? [----------------------------------------------------------------------------------------------------------------------------------------=]

ipfs pin ls
QmY5DTqJZTVFrv7Su37ycNRZkZqAr66awtYqiDTGuuXtaJ indirect
QmXJ9LSyT4b2Vez1g9YLDdVYzEJyVb4GEyy8k5LFY4XjPs recursive

ipfs files ls
"No output"
```

With WebUI:
```
Import > Add "test" dir > "test" and "symtestfile" added correctly

ipfs files ls
"test"

ipfs files ls /test
"symtestfile"
```

Additionally, a user named **Fayne Aldan** in the Matrix room experienced this same issue in a Windows machine, but, the "Import" button didn't work for them at all even with presumably correct symlinks. This means it isn't isolated to Linux symlinks, but, Linux and Windows symlinks create different results.

**Comment by LynHyper** [comment]
I found out the symlinks I was creating were being reported as "Kind: broken links", I'm currently attempting to contact someone in the Matrix room running Linux to find someone to help reproduce the issue; I can't figure out why my symlinks are failing, for now the issue has still been created on Fayne's Windows machine so I'll leave it open for now.

**Comment by Stebalien** [comment]
go-ipfs adds symlinks as _symlinks_, it doesn't follow them (same as the `tar` and `cp` commands).

Currently, you can follow symlinks appearing on the commandline (e.g., files you're directly adding) with the `--dereference-args` flag. However, there's no way to say "follow all symlinks".

**Comment by LynHyper** [comment]
I'm not sure what you mean by "following" symlinks, could you explain in more detail? Also, does this mean the "Import" button calls `--dereference-args` hence why it works when `ipfs add` doesn't by default?

**Comment by Stebalien** [comment]
> Does this mean the "Import" button calls

The "import" button likely uses some electron feature to upload the entire directory, following symlinks. It doesn't use the same directory traversal logic that `ipfs add` does.

> I still believe the above issue needs to be addressed since ipfs add should report an error like "/test/symtestfile is a symlink and could not be added." (Or even just an error in general in case that can't be detected)

This is a tricky case of defaults. But requiring some form of "allow dangling symlinks" option sounds reasonable.

**Comment by LynHyper** [comment]
An "allow dangling symlinks" option seems like a good call, however, I still think `ipfs add -r /test`'s output needs an error message; currently it doesn't show any sign that the symlink file is causing problems which is confusing when the file and dir don't show up in the webui or in `ipfs files ls`.

**Comment by Stebalien** [comment]
The first command is working correctly, I think. There's likely a bug in `ipfs files ls`.

If you run `ipfs get` on the resulting CID, you should get a symlink back.

**Comment by LynHyper** [comment]
Just tested it, `ipfs get CID-of-symtestfile` gave me a file that was symlinked to `testfile` so it does appear to be working, both `ipfs files ls` and the webui show no files. `ipfs pin ls` lists the CIDs as expected still.

**Comment by LynHyper** [comment]
Actually, if this isn't working for the webui either doesn't this mean this isn't a problem with `ipfs files ls` but perhaps something lower?

**Comment by LynHyper** [comment]
Just realised it wasn't showing up in the MFS because `ipfs add` doesn't add to the MFS, welp. Closing this issue.
