### ISSUE TITLE
be friendly to HDD/SSD setup

### ISSUE THREAD

**Issue by skliarie** [ipfs/go-ipfs#8408]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

I have a machine with bunch of HDD and couple of SSD drives.
The IPFS storage is on HDD, and the performance is expectedly poor. I would like to use SSD to speed things up.

I noticed that during pinning, most used directory is  storage/blocks/.temp. It seems the directory is used as intermediate storage for blocks-in-transit, before final copy into storage/blocks directory.

I tried to make that directory symlink to SSD-hosted location or even bind mount, but in both cases IPFS daemon stopped accepting new blocks. I guess there is some move operation that is not working on cross-filesystem boundary.

Can you add option of specifying location of that temp directory? And allow it to be on a separate filesystem than the primary storage?
Expect that some brave souls might decide to put it on /dev/shm RAM disk..

**Comment by Stebalien** [comment]
Unfortunately, putting ".temp" on an SSD won't help as, as you noted, blocks aren't copied, they're moved. Putting it on an SSD would require _copying_ the block's data from the SSD to the HDD, while the current "move" operation just update's the file's metadata.

I suggest you consider using a journaling/log filesystem, storing the journal/log on the SSD. I believe both XFS and EXT4 support this, but you'll want to do your own research as I've never done anything like this.

**Comment by skliarie** [comment]
For some reason (and that might be bug by itself), files/blocks in .temp directory have in-proportionally high write IO (relative to incoming data rate). As if for every incoming tcp/ip packet, whole file in .temp is read into RAM, updated and then written back (just guessing).
In my case, increase of total storage area by 200-300 KBytes/sec is accompanied by about 11MBytes/sec of writes.
Final cross-device copy would cause minuscule amount of IO in comparison.

**Comment by Stebalien** [comment]
> For some reason (and that might be bug by itself), files/blocks in .temp directory have in-proportionally high write IO (relative to incoming data rate). 

Well, that's where we _write_ new blocks, so I'd expect it to have all the write IO. We then move them into one of the shards under the "blocks" directory.

The code is in https://github.com/ipfs/go-ds-flatfs/blob/c6e8c322e1c850e57aacd79fc68caa7b534e26e5/flatfs.go#L524.

>  In my case, increase of total storage area by 200-300 KBytes/sec is accompanied by about 11MBytes/sec of writes.

Ah... you may be receiving multiple copies of the same block at the same time. We _do_ check to see if we already have the block, but that check races with put. It sounds like you could benefit from a write-coalescing blockstore.

**Comment by skliarie** [comment]
Ok, will convert to badger, closing
