### ISSUE TITLE
Warn users when pinned dataset is larger than local GCThreshold

### ISSUE THREAD

**Issue by kallisti5** [ipfs/go-ipfs#8413]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

In #8103 we saw users attempting to pin "large" data sets (in this case, 90GiB) reach a hangup during the pinning process. 

If the size of the dataset you're attempting to pin is larger then GCThreshold, the chunks will be *immediately* garbage collected when ctl+c'ing or terminating the pin. This defeats the purpose of IPFS as users should be able to "resume" downloading chunks from where they left off if pinning is interrupted.

Instead of letting users pin potentially massive amounts of data which will unknowingly be destroyed, maybe a warning when this condition exists in ```ipfs pin``` would be beneficial?

```
ipfs pin /ipns/blah
warning: pinned dataset is larger than your GCThreshold, data will need to be re-downloaded if interrupted!
```

It would be better to guide users to increase their GCThreshold instead of silently letting them believe  that IPFS can't resume pinning.

#8412 is another alternative strategy to fix this (Chunk garbage collection minimum time)
#3121 seems to be another alternative strategy for this (best effort pins)

**Comment by lidel** [comment]
I don't believe this is feasible:  it is not possible to tell the size of non-UnixFS DAGs without fetching  them. This warning would only work for UnixFS data, and the behavior of  `ipfs pin` should be codec-agnostic as much as possible.

iiuc there is a way of doing best-effort pins with MFS – see https://github.com/ipfs/go-ipfs/issues/3121#issuecomment-985785917
Closing this and suggest continuing in  https://github.com/ipfs/go-ipfs/issues/3121 where we discuss approach that is codec-agnostic.
