### ISSUE TITLE
Warn user when 'pin remote add' while offline

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#8418]
## UX problem

> if someone pins something via `pin remote add` but their node is in offline mode, it just hangs forever and fails to pin the thing in a very opaque way

## Potential fix

When in offline mode, we could check if CID is present in local datastore, and if so, show a warning that node is offline and pinning may fail if there is no other provider. 

The check for presence in local datastore is necessary, because we don't want to warn users when they pin CIDs that are not in the local node.

**Comment by Zanda256** [comment]
Can I work on this @lidel ?

**Comment by lidel** [comment]
@Zanda256 sure, give it a try!

**Comment by Zanda256** [comment]
Hey @lidel ,  I am having some ambiguities,  can you spare a little time to discuss?

**Comment by BigLep** [comment]
@Zanda256 : ipfs maintainers have a lot on their plate currently.  Do you want to post what your questions are?

**Comment by Zanda256** [comment]
In core/commands/pin/remotepin.go

I check if the node is offline using the line,  `offline, _ := req.Options["offline"].(bool)`  and `node.IsOnline`(I test both these conditions) , is this redundant or it's okay?
Also , I use this line to get all keys in the local blockstore `allKeys, err := node.Blockstore.AllKeysChan(ctx)`,  then compare the provided cid and if it matches ,I print the warning. Just not sure if `isInBlockstore, err := node.Blockstore.Has(rp.Cid())` only checks the local blockstore. I request some clarification.

Also, how to print the warning to the UX or cli, the `RemotePinOutPut` struct doesn't cater for a warning message, was thinking appending it to the status string, and pass that into `res.Emit(createdStruct)`. 
I need some guidance please. Any comments are appreciated. Thank you.

**Comment by schomatis** [comment]
Leaving feedback on PR.

**Comment by schomatis** [comment]
@lidel Just to make sure _I_ am understanding the issue correctly (but this might be obvious to the rest here):

* The pinning client is independent of the online/offline option of our own daemon. We can be offline but still connect to a remote service and request to pin a CID.
* The likeliest case assumed here is that I have a CID and I want to pin it on another machine, so I connect to it through this independent pin client and ask it to store my CID and also tell it that _I_ have this CID and it should fetch it from me.
* There is _no_ timeout on this operation (which, independent of this issue, seems it should be) so if I'm offline and I'm the only one that have this CID (case assumed here) the remote machine can't fetch it and hence can't pin it so the pin operation never completes (not even with a `StatusFailed` so I'm assuming the remote service also has no timeout).

The fix then is:
* Check if we have the CID which would imply we're in this likeliest case of being the only ones that have it (e.g., I just created that content).
* If offline warn the user that the remote service won't be able to fetch it from us and if this is the only available copy of this CID this will hang (which again on itself sounds like weird UX).

The proposed PR is indeed aligned with this.

**Comment by lidel** [comment]
Correct, that is the idea. 
We want to give folks an early warning that they forgot to start daemon, so they don't waste time while waiting for a pin that most likely will never succeed.
