### ISSUE TITLE
ipfs fuse stress fail on osx

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#842]
in fuse/readonly:

```
> go test -v
=== RUN TestIpfsBasicRead
--- PASS: TestIpfsBasicRead (0.12s)
=== RUN TestIpfsStressRead
--- FAIL: TestIpfsStressRead (3.66s)
	ipfs_test.go:178: Incorrect Read! [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [24 94 56 145 176 71 157 62 73 225 128 254 8 221 197 7 231 43 195 34]
	ipfs_test.go:178: Incorrect Read! [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [24 94 56 145 176 71 157 62 73 225 128 254 8 221 197 7 231 43 195 34]
	ipfs_test.go:178: Incorrect Read! [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [24 94 56 145 176 71 157 62 73 225 128 254 8 221 197 7 231 43 195 34]
	ipfs_test.go:178: Incorrect Read! [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [24 94 56 145 176 71 157 62 73 225 128 254 8 221 197 7 231 43 195 34]
=== RUN TestIpfsBasicDirRead
--- PASS: TestIpfsBasicDirRead (0.13s)
=== RUN TestFileSizeReporting
--- PASS: TestFileSizeReporting (0.12s)
FAIL
exit status 1
FAIL	github.com/jbenet/go-ipfs/fuse/readonly	4.185s
```

I modified `ipfs_test.go` to show the output:

```diff
diff --git a/fuse/readonly/ipfs_test.go b/fuse/readonly/ipfs_test.go
index ebdfac5..55155c9 100644
--- a/fuse/readonly/ipfs_test.go
+++ b/fuse/readonly/ipfs_test.go
@@ -175,7 +175,7 @@ func TestIpfsStressRead(t *testing.T) {
 				}
 
 				if !bytes.Equal(rbuf, data) {
-					t.Fatal("Incorrect Read!")
+					t.Fatal("Incorrect Read!", rbuf, data)
 				}
 			}
 		}()
```

---

anyway this failure is persistent. happens always on osx. and it likley has been failing since 0fe7706 -- (i checked 2a9cc10 at it failes then at least)

**Comment by jbenet** [comment]
cc @whyrusleeping @cryptix

**Comment by jbenet** [comment]
@cryptix has a related problem where -- if he runs with `-race` -- the process may zombify and the mount point may become entirely unusable. (may be related or its own issue)

**Comment by whyrusleeping** [comment]
@jbenet are you able to run with `-race`?

**Comment by whyrusleeping** [comment]
also, we should make the distinction, is this fuse, or osxfuse? (is @cryptix on OSX?)

**Comment by cryptix** [comment]
@whyrusleeping the zombies (happen)d on my linux box.

**Comment by whyrusleeping** [comment]
@tv42 any idea if running the race detector with fuse will cause issues?

**Comment by tv42** [comment]
@whyrusleeping Race detector just slows things down, as long as you're not hitting an osxfuse timeout it shouldn't change behavior.. Though the slowdown by itself may change what races are likely.

**Comment by tv42** [comment]
I can't explain the exact thing you're seeing with it without more information, and I'm not following the code very well right now, but I think the tests might be hurting you by having a mount active while mutating data underneath (not through the fs). Basically, if you let the kernel access the data once, and you don't carefully forbid caching, it "knows" what's there.

And most of the time, you really want to let the kernel cache, that's what gives you speed.

What my tests do is setup data directly first, then mount, then observe/mutate things through the fs, unmount, and finally optionally verify mutation directly.

**Comment by jbenet** [comment]
data in this mount is immutable, so caching shouldn't be a problem
