### ISSUE TITLE
Provide a way to destroy pinset

### ISSUE THREAD

**Issue by gammazero** [ipfs/go-ipfs#8421]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

Sometimes it is necessary to remove the entire pin set:
- If there is ever a need to rebuild the node's pin set.
- When inconvenient to remove many individual pins.  It may be much easier to remove all pins and re-pin specific objects.

To support this, the local pinning API should expose a `RemoveAll` method.  There should be an `ipfs pin removeall` command that deletes all pins.

**Comment by BigLep** [comment]
Per 2021-11-12 conversation, we're not planning to tackle this until there is more of an impetus for this, especially since someone can modify the datastore directly.
