### ISSUE TITLE
Partial pinning progress is not preserved well.

### ISSUE THREAD

**Issue by skliarie** [ipfs/go-ipfs#8426]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

third-party binary

### Version

```Text
/ # ipfs version --all
go-ipfs version: 0.9.1-dc2715a
Repo version: 11
System version: amd64/linux
Golang version: go1.15.2

As shipped by docker ipfs/go-ipfs:v0.9.1
```

### Config

```json
not relevant
```

### Description

I am trying to pin a huge (108GB) pinset /ipfs/bafybeieto6mcuvqlechv4iadoqvnffondeiwxc2bcfcewhvpsd2odvbmvm, with over a million nodes. It is progressing slowly.

If I kill "ipfs pin add --progress" for any reason, subsequent "ipfs pin add" quickly progresses to about half of the node the previous run got to. I am using flatfs if that helps.

I would expect previous progress to be kept around..

**Comment by skliarie** [comment]
Not sure if it is related, but will mention anyway:
If I run same pin in a different window, it is progressing differently than in the first window. For example, after many hours,  in first window I see this:
Fetched/Processed 545645 nodes
And in the second:
Fetched/Processed 537759 nodes

As if the two pinning processes operate on independent storage engines...

**Comment by Stebalien** [comment]
The two pin operations take different paths through the graph. For performance, we don't bother making it deterministic.

**Comment by skliarie** [comment]
Does it mean that I can speed up download by pinning same hash in parallel?

**Comment by Stebalien** [comment]
That will likely just waste more bandwidth.

**Comment by aschmahmann** [comment]
Seems like this is resolved/explained. Feel free to reopen if I'm mistaken
