### ISSUE TITLE
merkledag.GetNodes has no way of failing

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#843]
Other than a context cancel, `dagserv.GetNodes` has no way of failing due to blocks not being found. This needs to be thought about, should be discussed along with #830 as we need to decide when it is acceptable to say that a given block is 'not found' and we also need a way of returning that error case back up through the NodePromise stuff

**Comment by jbenet** [comment]
We should have a set of errors that can be returned-- these are the equivalent of ICMP, or socket, or HTTP error codes for ipfs. Perhaps we can use interfaces (like the `net` package, with http://golang.org/pkg/net/#Error so users can cast and get some meaningful information) or codes like `http`.

**Comment by whyrusleeping** [comment]
the nodePromise `Get` can fail now
