### ISSUE TITLE
Multipart reader regression in go 1.17

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#8445]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

built from source

### Description

See the test failure in https://github.com/ipfs/go-ipfs-files/pull/40:

```
--- FAIL: TestMultipartFiles (0.00s)
    helpers_test.go:122: [2] found end of directory, expected files.Event{kind:0, name:"nested", value:"some content"}
FAIL
FAIL	github.com/ipfs/go-ipfs-files	0.007s
FAIL
```

This isn't a flake so _something_ is going wrong. I'm not sure if this affects production, but we should figure it out before releasing.

**Comment by BigLep** [comment]
Next step:
1. Confirm this only manifests with go 1.17 and if so release with 1.16.

**Comment by Stebalien** [comment]
>    Confirm this only manifests with go 1.17 and if so release with 1.16.

The CI passes with 1.17 but not with 1.16, so I believe we can consider this confirmed. But yeah, we can just not use 1.17 when we release.

**Comment by marten-seemann** [comment]
> The CI passes with 1.17 but not with 1.16

I believe this should be the other way around: The CI passes with 1.16 but not with 1.17.

Is this a bug in the standard library?

**Comment by Stebalien** [comment]
Uh, yes, you're right. And it might be a bug, or they might be getting more strict.

**Comment by marten-seemann** [comment]
This is probably due to https://github.com/golang/go/commit/784ef4c5313.

**Comment by marten-seemann** [comment]
Now the question is, have we been using the multipart reader in an incorrect way, potentially creating a security issue as described in the Go issue, or is this something we should work around by reimplementing the Go 1.16 behavior? @Stebalien?

**Comment by Stebalien** [comment]
We've been using it exactly as we intended.

**Comment by Stebalien** [comment]
Fix in https://github.com/ipfs/go-ipfs-files/pull/42

**Comment by lidel** [comment]
Remaining work: tag a new release of https://github.com/ipfs/go-ipfs-files and switch go-ipfs to it.
