### ISSUE TITLE
[Proposal] Generate swagger format api.

### ISSUE THREAD

**Issue by manonthegithub** [ipfs/go-ipfs#8453]
Not sure if you already considered that or not, but would be nice to have the api described in a universal format from which one can automatically generate client stubs for any (almost any) language. [Swagger](https://swagger.io/tools/swagger-codegen/) may be an example of such a format.

**Comment by lidel** [comment]
I am afraid swagger won't be compatible with RPC-style API at `/api/v0` – see https://github.com/ipfs/http-api-docs/issues/3#issuecomment-596434150.
We can revisit this in the future, when we introduce `v1`
