### ISSUE TITLE
Way to disable progress bars for 'cat' and 'get'

### ISSUE THREAD

**Issue by andrewchambers** [ipfs/go-ipfs#8470]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

In some scripting contexts it is not acceptable to display a progress bar, but there is no way to disable the progress bars without also hiding error messages (by redirecting stderr).

Ideally there would be a -q option or --no-progress such for such situations.

**Comment by schomatis** [comment]
This seems like a fair request: we should have the same behavior of silencing the progress bar (or any other output) like `ipfs add` does. Assigning myself with no commitment on timeline (as there are higher-priority issues in the queue), but feel free to ping in a couple of weeks if this hasn't moved.

**Comment by schomatis** [comment]
Working on this now.

**Comment by schomatis** [comment]
@andrewchambers Could you take a look at https://github.com/ipfs/go-ipfs/pull/8686 to see if this works for you?

**Comment by andrewchambers** [comment]
looks pretty good - i guess as long as its consistent with how other commands disable it, it looks good to me.
