### ISSUE TITLE
IPFS Feedback

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#849]
Hey all, would be great to get some feedback of the things you'd like IPFS to do better _right now_. This includes the go-ipfs repo, the ipfs protocol, the webui, all our codebases, our community channels-- really, anything. There's of course **a lot** well known and planned-- i'm merely prioritizing where we spend our efforts in the coming weeks.

Some questions to get you thinking:
- I'd love it if it were easier to ....
- I wish that ...
- I really hate when ...
- It is very cumbersome to ...
- ... is very annoying
- ... is very broken

Thanks,
Juan

**Comment by whyrusleeping** [comment]
I wish that the protocol didnt appear to have two layers of msgio wrapping.

**Comment by BrendanBenshoof** [comment]
I want to be able to pin files in the webui.
In combination with this, I want to be able to start a download in the background easily.

**Comment by kevinwallace** [comment]
I wish the IPNS<->DNS mapping felt more finalized, so I could start relying on it.

**Comment by whyrusleeping** [comment]
I wish all the log messages didnt say `<autogenerated>`

**Comment by chriscool** [comment]
I wish that there were more tutorials, like step by step way to create a simple js app.

**Comment by whyrusleeping** [comment]
I wish the daemon shut down quickly when i press ctrl + c

**Comment by Luzifer** [comment]
I wish there would be an HTTP-API documentation one can play around with (like on [apiary](http://apiary.io/) or similar)

**Comment by Luzifer** [comment]
I wish there would be a way to see what mime-type the content of a hash has / which name it would be called by before downloading.

**Comment by cryptix** [comment]
> I wish there would be an HTTP-API documentation one can play around with (like on apiary or similar)

:+1:  but I'd like to have a clean cut go client package for interfacing with the JSON API.

I feel like `core/commands` already is that but it is only consumed by the cli tool from which it is hard to grasp how to use the commands on it's own. Maybe pkg `commands` just lacks documentation and usage examples.

**Comment by whyrusleeping** [comment]
I wish ipfs had support for microtransactions.

**Comment by Powersource** [comment]
Pretty old thread heh.

But I wish IPNS was less buggy/faster I guess.

**Comment by daviddias** [comment]
Continues on https://github.com/ipfs/notes/issues/318
