### ISSUE TITLE
Remove ./assets/dir-index-html submodule

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#8532]
I believe we should merge [dir-index-html](https://github.com/ipfs/dir-index-html) back to go-ipfs. 

No reason for it to be outside. It is a key part of gateway functionality, and having a separate repo + git submodule makes it ridiculously hard to contribute changes.

**Comment by longfeiWan9** [comment]
@lidel li maybe I can try to work on this as part of BootCamp?

**Comment by lidel** [comment]
@longfeiWan9 sounds good!

Some pointers:
- would be really nice if we could preserve git history while replacing `./assets/dir-index-html` submodule with a directory, to keep contributor info intact
- (optional) you could see if we still need `bindata` build step: afaik `BindataVersionHash` is used only [here in the `Etag` HTTP header](https://github.com/ipfs/go-ipfs/blob/7c76118b0b7026fba8357807e5a67b59fc2b684b/core/corehttp/gateway_handler.go#L305) to indicate to the browser when HTML with directory listing changed.

ps. i'm around if you want to chat about it (calendly link is in my slack profile)
