### ISSUE TITLE
REQUEST: HTTP Gateway Supports HTTP Range Headers

### ISSUE THREAD

**Issue by netshade** [ipfs/go-ipfs#8540]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

Propose that the IPFS HTTP gateway support [range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#range_requests) to allow requesters to hint to the server that only a subset of a document may be necessary to fulfill the request. Ideally this support would also allow the client to hint to the gateway that only some subset of blocks ( rather than all blocks ) are necessary to be requested from the network in order for the request to be fulfilled.

**Comment by Stebalien** [comment]
Range headers are supported. If something isn't working, please file a new issue with a repro.
