### ISSUE TITLE
ipfs get -o file $address fails (minor argument parse bug)

### ISSUE THREAD

**Issue by joeyh** [ipfs/go-ipfs#856]
ipfs get -o foo Qma8oHaVQtGxsapu1ZCP27CS9A5KhD2C4sqLPSxK7xNLEu

Error: Expected 1 arguments, got 2

It seems that --output=foo works, but no way to use the short option despite it being documented.

**Comment by mappum** [comment]
That is what is currently expected, `-o=foo` is supported but `-o foo` is not. However, if many people expect this argument convention to work then it is a UX bug.

**Comment by joeyh** [comment]
This could be considered a documentation bug; I read the --help and
didn't see that it needed -o=

-- 
see shy jo

**Comment by whyrusleeping** [comment]
@joeyh agreed on it being documentation bug

**Comment by whyrusleeping** [comment]
i think this is fixed now, right @jbenet ?

**Comment by jbenet** [comment]
I believe so, yes. thanks again @AtnNn
