### ISSUE TITLE
ipfs commands want to consume all stdin

### ISSUE THREAD

**Issue by joeyh** [ipfs/go-ipfs#858]
When building a git-annex to ipfs bridge, I noticed that some ipfs commands were blocking, trying to read stdin. In this case, stdin was being used for git-annex IPC. 

Commands observed to read stdin in this way:

ipfs cat $addr > file

ipfs add -q file

In both cases,  I had to use </dev/null to provide ipfs with an empty stdin to avoid it hanging.

**Comment by joeyh** [comment]
Also, with stdin set up this way,

ipfs get --output=$file $addr 

fails with "Error: Expected 1 arguments, got 2"

Amazingly, </dev/null fixed that too. So stdin is somehow influencing argument processing.

**Comment by whyrusleeping** [comment]
@mappum Any ideas on this one?

**Comment by jbenet** [comment]
the problem here is that the cmds lib is to aggressive on parsing args. It treats stdin as an input always. It should not, it should only do so for commands that enable it, and where the other arguments don't obviate stdin.

**Comment by jbenet** [comment]
We should fix this soon-- it's really annoying for users.

**Comment by jbenet** [comment]
ipfs/pm#5

**Comment by chriscool** [comment]
I think this issue is the same as issue #1141 (ipfs cat "multihash too short" error when using stdin) and is fixed by PR #1238 (Improve stdin parsing).

**Comment by chriscool** [comment]
This should be fixed as PR #1238 as been merged.
