### ISSUE TITLE
command option flag inconsistency

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#859]
In our help text for various commands we show both `-longopt` and `--longopt` for various flags, we should pick one of these and stick with it everywhere. (Not necessarily saying we have to drop support for one or the other, just use a single style in our docs and help text)

**Comment by jbenet** [comment]
agreed. I think `-s` and `--long`

**Comment by whyrusleeping** [comment]
I believe we have unified (code enforced) to `--longopt`
