### ISSUE TITLE
Better defaults for ipfs key export (PEM, PKCS, encrypt with passphrase)

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#8594]
## Current implementation

Right now, the `ipfs key export -o foo.key` just spits out the key in proprietary Protobuf, without any protection:

* https://github.com/ipfs/go-ipfs/blob/8cfc88961d4081b2749fba135b63ffcca5a62456/core/commands/keystore.go#L189
* https://github.com/libp2p/go-libp2p-core/blob/1262f601475277211be0af5527932f6e5aa87313/crypto/key.go#L245

This is not only a dangerous default, but makes it difficult to interop with the outside world.
People building on IPFS asked for the ability to generate keys outside go-ipfs and/or export them in a form that is useful out of the box, or a safer way to export a key to move it to a different box.

Ref. https://discuss.ipfs.io/t/importing-pem-encoded-private-key/12770/9

## Proposed fix

We should fix the default behavior and do what js-ipfs does:

> [`ipfs.key.export(name, password, [options])`](https://github.com/ipfs/js-ipfs/blob/c8585080ac795f78bcf9c87608abda234844987d/docs/core-api/KEY.md#ipfskeyexportname-password-options):
> Export a key in a PEM encoded password protected [PKCS 8](https://en.wikipedia.org/wiki/PKCS_8)

Namely:
- never export unencrypted keys by default
- leverage well-established open standards  to maximize interoperability and improve devexp

Some implementation suggestions:
- change the default to produce something like well-established [PEM 8](https://en.wikipedia.org/wiki/PKCS_8) (https://en.wikipedia.org/wiki/PKCS)
- make `--format=pem-pkcs8-encrypted` the implicit default
  - this ensures the default is sane: requires password and produces encrypted key
  - it is ok to allow unencrypted export via explicit opt-in `--format=pem-pkcs8-cleartext`
- handle legacy format: allow users to export to the old format via something like `--format=libp2p-protobuf-cleartext` 
- import should be smart enough to detect the key format based on a few first bytes, but it should also take explicit `--format` and return error if input does not match expected format

-----

Update: turns out js-ipfs uses PEM only for RSA keys, Ed25519 (current default) use custom format encrypted with aes-gcm (details in https://github.com/ipfs/go-ipfs/pull/8616#pullrequestreview-853622126) – I suggested focussing on cleartext (unencrypted) PEM for now, as it the most interoperable with external software.

**Comment by schomatis** [comment]
Makes sense, working on this. Is there a particular use case we should test or just add some sharness with pem files?

**Comment by lidel** [comment]
@schomatis I think sharness tests limited to `ipfs key` commands will be enough:

1. use `key gen` to generate one test key per supported type
2. `key export && key rm` each key (so it only exists in exported form)
3.  `key import && key ls` each to confirm import worked and key is placed in keystore under some petname

**Comment by lidel** [comment]
Turns out js-ipfs uses PEM only for RSA keys, Ed25519 keys (current default) use custom format encrypted with aes-gcm (details in https://github.com/ipfs/go-ipfs/pull/8616#pullrequestreview-853622126)

Due to this, we are focussing on cleartext (unencrypted) PEM for now, as it the most interoperable with external software, and don't be changing any defaults.

Opt-in support for keys in cleartext PEM  files   is being implemented in https://github.com/ipfs/go-ipfs/pull/8616

**Comment by schomatis** [comment]
Done in https://github.com/ipfs/go-ipfs/pull/8616.
