### ISSUE TITLE
docker container only in amd64 architecture

### ISSUE THREAD

**Issue by mabels** [ipfs/go-ipfs#8614]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

I would be nice if you provide in addition to amd64 architecture docker containers. 

- arm64 
- armv7(raspi32) image.

I could provide the build infrastructure (manifest....) but there have to be some workers which run on these architetures, which can only provided from your side. 
As AWS Codebuild is running on arm and amd this might be an cheap and easy solution to it.

**Comment by tylerferrara** [comment]
Let me prefis by saying "I am NOT a maintainer of IPFS"

But getting that out of the way, this should be very easy to do.
[https://docs.docker.com/desktop/multi-arch/](https://docs.docker.com/desktop/multi-arch/)
There's plenty of documentation on converting any `Dockerfile` into a multi-arch image. You could even do this yourself if IPFS is unwilling to host these images.

However, I am also very interested in running **IPFS on arm64** systems aswell and would love to simply pull an official image supported by the project.
