### ISSUE TITLE
make uncompressed .zip files accessible in pieces

### ISSUE THREAD

**Issue by nob404dy** [ipfs/go-ipfs#8618]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

Since i saw that even a **.jpg** (e.g.  Qmc8mmzycvXnzgwBHokZQd97iWAmtdFMqX4FZUAQ5AQdQi) has a ipfs structure as
```
21076541854_939b42d8d8_o.jpg
.
└── Links
      ├── 0
      │    └── Object {type: "file", data: Uint8Array, blockSizes: Array[0]}
      ├── 1
      │    └── Object {type: "file", data: Uint8Array, blockSizes: Array[0]}
      ...
      └── 17
           └── Object {type: "file", data: Uint8Array, blockSizes: Array[0]}
```
I think it would be super awesome to have that for uncompressed **.zip** files
```
uncompressed.zip
.
└── folder
      ├── file.pdf 
      │    └── Object {type: "file", data: Uint8Array, blockSizes: Array[0]}
      ├── file.png
      │    └── Object {type: "file", data: Uint8Array, blockSizes: Array[0]}
      ...
      └── file.avif
           └── Object {type: "file", data: Uint8Array, blockSizes: Array[0]}
```
This would be extremely beneficial for managing archives.
I don't know if something like this is already in development but if not then i would love to implement that. 
I am only a bit concerned that my programming might not be clean enough to properly contribute to this project.

**Comment by Stebalien** [comment]
There was a feature to do _something_ like this for tar files called `ipfs tar`, but the resulting filesystem wasn't actually the same as everything else in IPFS and that command is discouraged now.

But yes, this is a highly desired feature. Basically, we'd:

1. Chunk the file based on the underlying file boundaries.
2. Build _two_ "trees":
    1. A zipfile (or tar) tree that can be read out of go-ipfs as a single zip file.
    2. A _filesystem_ tree that exposes the internal directory structure.

Critically, both of these trees would share the same data blocks and the "zipfile" tree would link to the "filesystem" tree from its metadata.

Unfortunately, this feature has always been blocked on making it easier to add custom metadata to IPFS, which has been blocked on "unixfs-v2". See https://github.com/ipfs/go-unixfs/issues/86 for the current state.

**Comment by Stebalien** [comment]
While this is a really good idea, it's not something someone can take immediate action on without significant design work so I'm going to close it for now. If you want to discuss how this feature could be implemented, please create a thread on https://discuss.ipfs.io.
