### ISSUE TITLE
Provides don't expire on other nodes.

### ISSUE THREAD

**Issue by zignig** [ipfs/go-ipfs#863]
Provides sent to other machines don't expire. 

Per IRC conversation.

15:18 @whyrusleeping oh, provides... yeah.. let me look
15:19 < zignig_> if you have a ttl that decrease as you get further away from the root nodes , it would degrade quite well.
15:19 @whyrusleeping they currently dont expire
15:19 @whyrusleeping it seems
15:19 @whyrusleeping they are supposed to expire after a day though
15:19 < zignig_> your streaming dag layout would make it work well to , the end of the movies starts to drop out first....
15:20 @whyrusleeping and thats configured by the node receiving the provide record
15:20 < zignig_> a ttl hint would be a good idea ( like dns ) 
15:20 @whyrusleeping yeah
15:20 @whyrusleeping can you file an issue for that?
15:21 @whyrusleeping i dont have my laptop out
15:21 < zignig_> how are you ircing ? ( direct mind link )

**Comment by whyrusleeping** [comment]
still an issue i think

**Comment by jbenet** [comment]
Hmm possibly yes. This should go along other dht revamps -- maybe 0.5 or 0.6

**Comment by whyrusleeping** [comment]
Lets verify that this is still an issue

**Comment by whyrusleeping** [comment]
Providers get garbage collected periodically now :)
