### ISSUE TITLE
Zeroconf networking issue (Docker For Mac, M1 Max, 0.11)

### ISSUE THREAD

**Issue by roderik** [ipfs/go-ipfs#8645]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

built from source

### Version

```Text
ipfs/go-ipfs:v0.10.0 & ipfs/go-ipfs:v0.11.0
```

### Config

```json
n/a
```

### Description

I have a very simple docker compose file

```
version: '3'
services:
  ipfs:
    image: 'ipfs/go-ipfs:v0.11.0'
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      - 5001:5001
      - 8080:8080
      - 8081:8081
```

That dies on startup with 'no supported interface'

```
graph-ipfs-1        | ipfs version 0.11.0
graph-ipfs-1        | Found IPFS fs-repo at /data/ipfs
graph-ipfs-1        | Initializing daemon...
graph-ipfs-1        | go-ipfs version: 0.11.0-67220ed
graph-ipfs-1        | Repo version: 11
graph-ipfs-1        | System version: amd64/linux
graph-ipfs-1        | Golang version: go1.16.7
graph-ipfs-1        | 2022/01/06 16:48:13 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
graph-ipfs-1        | 2022/01/06 16:48:13 [zeroconf] no suitable IPv4 interface: udp4: failed to join any of these interfaces: [{12 1500 eth0 02:42:ac:13:00:03 up|broadcast|multicast}]
graph-ipfs-1        | 2022/01/06 16:48:13 [zeroconf] no suitable IPv6 interface: udp6: failed to join any of these interfaces: [{12 1500 eth0 02:42:ac:13:00:03 up|broadcast|multicast}]
graph-ipfs-1        | 2022-01-06T16:48:13.408Z	ERROR	cmd/ipfs	ipfs/daemon.go:430	error from node construction: no supported interface
graph-ipfs-1        | 
graph-ipfs-1        | Error: no supported interface
```

If I modify it to use v0.10 it works and starts.

```
version: '3'
services:
  ipfs:
    image: 'ipfs/go-ipfs:v0.10.0'
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      - 5001:5001
      - 8080:8080
      - 8081:8081
```

```
graph-ipfs-1        | Changing user to ipfs
graph-ipfs-1        | ipfs version 0.10.0
graph-ipfs-1        | Found IPFS fs-repo at /data/ipfs
graph-ipfs-1        | Initializing daemon...
graph-ipfs-1        | go-ipfs version: 0.10.0-64b532f
graph-ipfs-1        | Repo version: 11
graph-ipfs-1        | System version: amd64/linux
graph-ipfs-1        | Golang version: go1.16.7
graph-ipfs-1        | 2022/01/06 17:09:24 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
graph-ipfs-1        | 2022/01/06 17:09:24 [zeroconf] no suitable IPv4 interface: udp4: failed to join any of these interfaces: [{18 1500 eth0 02:42:ac:13:00:03 up|broadcast|multicast}]
graph-ipfs-1        | 2022/01/06 17:09:24 [zeroconf] no suitable IPv6 interface: udp6: failed to join any of these interfaces: [{18 1500 eth0 02:42:ac:13:00:03 up|broadcast|multicast}]
graph-ipfs-1        | Swarm listening on /ip4/127.0.0.1/tcp/4001
graph-ipfs-1        | Swarm listening on /ip4/127.0.0.1/udp/4001/quic
graph-ipfs-1        | Swarm listening on /ip4/172.19.0.3/tcp/4001
graph-ipfs-1        | Swarm listening on /ip4/172.19.0.3/udp/4001/quic
graph-ipfs-1        | Swarm listening on /p2p-circuit
graph-ipfs-1        | Swarm announcing /ip4/127.0.0.1/tcp/4001
graph-ipfs-1        | Swarm announcing /ip4/127.0.0.1/udp/4001/quic
graph-ipfs-1        | Swarm announcing /ip4/172.19.0.3/tcp/4001
graph-ipfs-1        | Swarm announcing /ip4/172.19.0.3/udp/4001/quic
graph-ipfs-1        | Swarm announcing /ip4/81.245.59.99/udp/62096/quic
graph-ipfs-1        | API server listening on /ip4/0.0.0.0/tcp/5001
graph-ipfs-1        | WebUI: http://0.0.0.0:5001/webui
graph-ipfs-1        | Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
graph-ipfs-1        | Daemon is ready
```

The compose file is the same as the one introduced in this repo

**Comment by roderik** [comment]
ps. did not built from source, but dockerhub is not an option in the dropdown

**Comment by LeslieOA** [comment]
@roderik 
I've experienced the exact same mileage with:

* M1 MacBook (12.0.1)
* Docker Desktop 4.3.2 (72729)
* `ipfs/go-ipfs:latest` (`0.11.0`)

No issues on my Intel Core i5 though which I've switched to for the interim. 
Had any luck since? Thanks.

**Comment by carlosdp** [comment]
Running into the same issue here, M1 Mac

**Comment by LeslieOA** [comment]
> Running into the same issue here, M1 Mac

@carlosdp As @roderik mentions, `go-ipfs:v0.10.0` works, so you can use this [docker-compose.yml](https://gist.github.com/LeslieOA/81b001e42f0bd249c1ce14e75b375b1d) for the meantime.
Hope this helps.

**Comment by marten-seemann** [comment]
For context, this is where the error originates: https://github.com/libp2p/zeroconf/blob/92498dabf5ddc3bb3568c9e6b61aa550ec81294d/connection.go#L84-L94.

**Comment by godcong** [comment]
I had the same problem when running in windows wsl mode.
ipfs version: 0.11.0
> libp2p/zeroconf/v2/server.go:Line168

```
	ipv4conn, err4 := joinUdp4Multicast(ifaces)
	if err4 != nil {
		log.Printf("[zeroconf] no suitable IPv4 interface: %s", err4.Error())
	}
	ipv6conn, err6 := joinUdp6Multicast(ifaces)
	if err6 != nil {
		log.Printf("[zeroconf] no suitable IPv6 interface: %s", err6.Error())
	}
	if err4 != nil && err6 != nil {
		// No supported interface left.
		return nil, fmt.Errorf("no supported interface")
	}
```

**Comment by rjmalagon** [comment]
A workaround is disabling MDNS in the config file.
```  "Discovery": {
    "MDNS": {
      "Enabled": false,
      "Interval": 10
    } ```

**Comment by islami00** [comment]
Strangely enough, I had a similar problem on gitpod. 
After trying to change the docker settings it just started working (Still shows udp buffer limit error though). I should've documented what I did because now the problem is back with a different workspace.

**Comment by godcong** [comment]
> @marten-seemann any ideas why disabling MDNS would resolve this? Any chance it's related to any of the other MDNS issues filed in go-libp2p (e.g. [libp2p/go-libp2p#1333](https://github.com/libp2p/go-libp2p/issues/1333))?
failed on this step `service.Start()` .
Failure to start returns an error, causing the entire ipfs to fail to start.

**Comment by marten-seemann** [comment]
> @marten-seemann any ideas why disabling MDNS would resolve this? 

@aschmahmann I don't think so. I think this would be solved by https://github.com/ipfs/go-ipfs/pull/8704. Any change we can merge that PR?

**Comment by dedshit** [comment]
> A workaround is disabling MDNS in the config file.
> ```  "Discovery": {
>     "MDNS": {
>       "Enabled": false,
>       "Interval": 10
>     } ```

thanks it worked👍

**Comment by ohmpatel1997** [comment]
I am still facing this issue. I am on docker M1. I am trying to setup IPFS cluster and peers are not being discovered by each other. 

@LeslieOA your docker compose file is not working for me either. would you please me out?
