### ISSUE TITLE
Missing recommendation on deployment an IPFS w/CORS settings for js-ipfs `ipfs-http-client` via Docker

### ISSUE THREAD

**Issue by jjperezaguinaga** [ipfs/go-ipfs#8646]
### Checklist

- [X] I am reporting a documentation issue in this repo, not https://docs.ipfs.io.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Location

https://github.com/ipfs/go-ipfs/blob/master/README.md

### Description

# Introduction
As IPFS gains mass adoption and becomes mainstream for many developers learning about decentralized technologies, there will further need to provide documentation on how to deploy IPFS nodes in VPS or other environments. As one of the main goals of decentralization is to diminish the dependency on centralized providers that provide public IPFS gateways (e.g. Infura, Cloudflare), it will be of further importance to avoid everyone having to use a third-party provider and have more instructions on how to DIY.

# Current behavior
The [README](https://github.com/ipfs/go-ipfs/blob/master/README.md) has very close to zero information about deploying IPFS nodes from locally to any external VPS provider. One low-hanging fruit is using Docker, which is already supported by major IaaS providers (e.g. GCP, AWS, DO) via a one-click install. Information relevant to deploying `go-ipfs` via Docker, thus, could exist, but is yet missing.

# Expected behavior
A `deployment` section in the README.md should provide a few paragraphs on how to deploy an IPFS node in some major providers via Docker by simply passing the Docker image and some environment variables. Some expected configurations, to just mention some, should include:

- [ ] Provide required configuration for CORS usage (this is particularly relevant for web developers that want to use [js-ipfs](https://github.com/ipfs/js-ipfs) via the `ipfs-http-client`).
- [ ] Provide suggested ports for exposing both the API, webui and public gateway.
- [ ] Recommended settings for mapping volume for data retention and read-write permissions in volumes
- [ ] Recommended docker image distribution to avoid using the `latest` tag
- [ ] Add instructions on `pinning` via the node itself or external providers like [IPFS Pinata](https://www.pinata.cloud/) (no affiliation).

# Suggestions of completeness
- [ ] README.md includes a sample `docker-compose.yaml` file which has single-line instructions for CORS support
- [ ] README.md includes at least one major VPS provider instructions w/enough instructions for allowing anyone to quickly deploy and maintain an IPFS node.

**Comment by jjperezaguinaga** [comment]
For further context, for a simple web app that uses IPFS and needs to be tested [locally](https://github.com/onPoster/app/issues/60), we had to [add](https://github.com/onPoster/subgraph/pull/11) an additional shell script that sent the CORS instructions upon start (inspired in [this](https://github.com/shinedme/shinedme-workspace/blob/74615acdfb7ddd3a75e41d268c72a5d6aac81b60/docker-compose-prod.yml) setup). It was not immediately clear that this was needed and further research had to be done.

**Comment by aschmahmann** [comment]
@jjperezaguinaga there are some docs and examples on docs.ipfs.io and all of the default go-ipfs config options and what they do are described in https://github.com/ipfs/go-ipfs/blob/master/docs/config.md. Disabling CORS for all requests (what you did in the linked setup) is generally not a good idea.

@TheDiscordian do you know of good resources to point them at?
