### ISSUE TITLE
Malwarebytes

### ISSUE THREAD

**Issue by shanej1595** [ipfs/go-ipfs#8682]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

ipfs-desktop

### Version

```Text
version is 0.11.0 I can't get any other info right now as I'm not currently on that system
```

### Config

```json
can't get that info at the moment I'm not connected to that system, but I don't think that would be relevant in this case.
```

### Description

Just downloaded Malwarebytes and it keeps blocking inbound and outbound traffic saying that it's a trojan, and malware. The reason I wrote malware after trojan even though a trojan is a form of malware, is that it's blocking the same program twice, once stating trojan, the other stating malware, and actually there's a third category that just popped up that says compromised.

**Comment by aschmahmann** [comment]
https://github.com/ipfs/go-ipfs/issues/8032#issuecomment-809901644

If you could report the false positive to Malwarebytes that would be great, you can post the link to your post here and we can follow up or reach out if they have any questions or issues https://forums.malwarebytes.com/forum/42-file-detections.

btw which OS and version of ipfs-desktop do you have and where did you install them from?

**Comment by lidel** [comment]
I got my hands on (clean) Windows laptop and was able to reproduce:
-  install free trial from https://www.malwarebytes.com/ 
- install latest ipfs-desktop and start it 
- go to Peers page, wait for few hundreds peers, and a few minutes 


Malwarebytes should get triggered by some peers,  over time, for multiple reasons:
> <img width="442" alt="ipfs-exe-peers-triggering RTP detection" src="https://user-images.githubusercontent.com/157609/151637915-6e39eeba-a209-4276-8e60-017efecf1059.png">

Messages are the usual antivirus boilerplate which makes little sense here: 
there is no "website" to block, those are outbound connections to libp2p peers made by `ipfs.exe`

While possible that those remote peers are infected or their IP was compromised recently, it is more likely those are false-positives.

Filled https://forums.malwarebytes.com/topic/283250-ipfsexe-libp2p-connections-trigger-false-positive-rtp-events/  asking Malwarebytes to investigate and safelist ipfs.exe, if possible.

**Comment by shanej1595** [comment]
> I got my hands on a (clean) Windows laptop, and was able to reproduce:
> 
> * install free trial from https://www.malwarebytes.com/
> * install latest ipfs-desktop and start it  (I used ipfs-desktop v0.18.1, which bundles go-ipfs v0.11.0)
> * go to Peers page, wait for few hundreds peers, and a few minutes
> 
> Malwarebytes should get triggered by some peers, over time, for multiple reasons:
> 
> > <img alt="ipfs-exe-peers-triggering RTP detection" width="442" src="https://user-images.githubusercontent.com/157609/151637915-6e39eeba-a209-4276-8e60-017efecf1059.png">
> 
> Messages are the usual antivirus boilerplate which makes little sense here: there is no "website" to block, those are outbound connections to libp2p peers made by `ipfs.exe` over TCP or QUIC
> 
> While possible that those remote peers are infected or their IP was compromised recently, it is more likely those are false-positives.
> 
> Filled https://forums.malwarebytes.com/topic/283250-ipfsexe-libp2p-connections-trigger-false-positive-rtp-events/ asking Malwarebytes to investigate and safelist ipfs.exe, if possible.

They probably won't get back to you with a legitimate answer. IPFS takes money out of GH's affiliates pockets (and a lot of pockets [ie people who invested and put money into AV programs]) My take on it is that it will always be a false positive. 
They'll probably tell you they found some bullshit lines of obfuscated code or some crap like that.
