### ISSUE TITLE
Add ipfs-companion chrome extension id to accepted origins for future manifest v3 version

### ISSUE THREAD

**Issue by meandavejustice** [ipfs/go-ipfs#8689]
[Manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/) removes support for the blocking webRequest api. We are currently using this api to intercept requests and modify the Origin URL to that of the ipfs-webui. With support for this feature gone we need another way for companion to make api requests to ipfs.

I'm proposing that we add the chrome-extension-id (which is generated once on upload to the chrome web store) to the [default allowed origins](https://github.com/ipfs/go-ipfs/blob/ef866a1400b3b2861e5e8b6cc9edc8633b890a0a/core/corehttp/commands.go#L40). This way companion can still be useful for users when manifest v2 is deprecated, and they will not have to manually update their configurations.

I have discussed this a bit with @lidel on slack, but wanted to get the ball rolling here so that we can have the ability to get ipfs-companion manifest v3 into the chrome store (if only as a beta channel for power users) by the end of Q1.

For further context: https://github.com/ipfs/ipfs-companion/issues/666 (mv3 tracking issues)

**Comment by lidel** [comment]
- SGTM, this should work for Chromium-based browsers (Google Chrome, Brave, Opera, Edge)
 - Caveats (all fixable, i think)
   - There may be a regression if user has a custom list of allowed origins (making [this check fail](https://github.com/ipfs/go-ipfs/blob/ef866a1400b3b2861e5e8b6cc9edc8633b890a0a/core/corehttp/commands.go#L88)). This means Companion not working for those folks
     - TBD: I think we may adjust the behavior to always append `defaultSafelistedOrigins` and skip it only when set to `null`, but we will decide this detail when a PR is open and we can see behavior in real world (I have no trust in browser specs around CORS and localhost, seen many bugs over the years)
    -  Need to figure out something else for Firefox (which anonymizes extension ids per user)
       - We've discussed this and if  Firefox will allow blocking `webRequest` APIs in Manifest V3, then we could keep the Origin fixup we use right now in V2 
  
Extension IDs from Chrome Web Store:
  - Official Stable: https://chrome.google.com/webstore/detail/ipfs-companion/nibjojkomfdiaoajekhjakgkdhaomnch (>60k users)
  - Beta (Unlisted): https://chrome.google.com/webstore/detail/ipfs-companion-beta/hjoieblefckbooibpepigmacodalfndh (~100 users)
  
@meandavejustice feel free to open a PR that adds their Origin URLs to `defaultLocalhostOrigins`, we will iterate on details there :)
