### ISSUE TITLE
why isn't there an ipfs rm command?

### ISSUE THREAD

**Issue by anarcat** [ipfs/go-ipfs#869]
i just ran `ipfs add <tons of files>`. tons of stuff ended up in my local data store. i want to remove it. like now. where's the `ipfs rm <tons of files>`?

assuming that's the only thing i did, can i `rm -rf $IPFS_DIR/datastore`? (seems that no: #245).

i know about the `pin` command set, but the semantics are confusing to me (and others, #590).

thanks

**Comment by insanity54** [comment]
First time user here. I'm also confused on this. There is a way to add, but where is the remove? Is unpinning what I want? From the [pin example](http://gateway.ipfs.io/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/example#/ipfs/Qma4WJEfopqa2ToR9qV9iCsFAWMfuR4hsjBr2zZkMkF6Cx/readme.md) I see `add` automatically creates a recursive pin. It must do something else besides pinning. I thought I'd figure it out from the code but [it's greek to me](https://github.com/ipfs/go-ipfs/blob/master/core/commands/add.go), what a strange language, looks fun, maybe I'll learn.

**Comment by whyrusleeping** [comment]
We need more documentation around this operation, but the current method of removing content from your local datastore is to unpin it, then run an `ipfs repo gc`

**Comment by whyrusleeping** [comment]
`ipfs rm` would be a somewhat misleading command, you could do `ipfs add <file that already exists elsewhere on the network>`, `ipfs rm <that>` and then still `ipfs cat <that>` and it would reappear. What really needs to be done here is not `ipfs rm` but better pinning semantics (maybe get rid of pinning (see the end of #257 and also in #590)
