### ISSUE TITLE
Better handling of fallbacks for migration downloads

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/go-ipfs#8714]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.io

### Version

```Text
go-ipfs v0.12.0-rc1
```

### Config

```json
Default config for a fresh node
```

### Description

Currently when go-ipfs tries to fetch migrations when running the daemon and realizing that the repo version needs to be upgraded it can fetch the migrations over an HTTP gateway or over IPFS.

Unfortunately the way in which fallbacks are used (e.g. try a gateway then IPFS, or vice versa) 
uses the `MultiFetcher` https://github.com/ipfs/go-ipfs/blob/cde79df1408c3bd518fec1622d97bf4a251af81e/repo/fsrepo/migrations/fetcher.go#L42

The `MultiFetcher` returns when the first fetch of an `io.ReadCloser` succeeds https://github.com/ipfs/go-ipfs/blob/cde79df1408c3bd518fec1622d97bf4a251af81e/repo/fsrepo/migrations/fetcher.go#L54-L58 

Unfortunately, this means that if the download terminates in the middle no fallback occurs.

----

There are a number of ways to fix this

 One relatively simple one would be modifying the `Fetcher` interface's `Fetch` function to take a writer so it can output to a file and therefore the `Fetch` function will only return when it's done fetching everything. Existing implementations could be made compliant by taking the `io.ReadCloser` they were previously returning and doing an `io.Copy` into the new writer before returning.

This makes the simple `MultiFetcher` logic work at the cost of not saving some bytes and being smarter about download resumption.

**Comment by BigLep** [comment]
2022-02-10 discussion: 
Implement interface change in go-ipfs so only return when have all the data.  (don't return "done" until actually "done").
By doing this, we'll actually get ipfs fallback if HTTP fails.

**Comment by lidel** [comment]
Additional ideas:
- Confirm we got all data expected (number of bytes in [content-length](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length) header should match bytes in response body)
  - IMO we should do this as a failsafe in case anything weird happens
- (optional) If HTTP download is interrupted mid-flight we could leverage smart retry via [range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) from the last byte received
- (optional) we could default to IPFS, and use `ipfs.io/api/v0/dag/export` for now and run `dag import` in parallel to regular IPFS fetch
