### ISSUE TITLE
ipfs swarm connect is undocumented

### ISSUE THREAD

**Issue by anarcat** [ipfs/go-ipfs#873]
i was told on irc to run `ipfs swarm connect`, but i don't understand why and `ipfs swarm connect --help` doesn't explain what the command actually does at all.

**Comment by timgws** [comment]
Should this issue still be closed?

`./ipfs swarm connect --help`

      ipfs swarm connect <address>... - Open connection to a given address

    ARGUMENTS:
  
      <address>... - address of peer to connect to

    DESCRIPTION:

      'ipfs swarm connect' opens a connection to a peer address. [...]

**Comment by jbenet** [comment]
I think that existed at the time. Would making it 
```
`ipfs swarm connect` opens a new direct connection a peer address.
```
be clearer?

**Comment by anarcat** [comment]
i guess we can followup in #1229...
