### ISSUE TITLE
Testground CI timeouts after 6 hours

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#8731]
## Problem

Testground CI runs for 6h and then timeouts:

> ![2022-02-10_22-32](https://user-images.githubusercontent.com/157609/153509037-61612c3b-bc2e-4fc4-aead-0efd12bf3159.png)
>
> > ![2022-02-10_22-35](https://user-images.githubusercontent.com/157609/153509080-d6617ce7-c4a4-4ad4-9f2c-a75d10364448.png)

Did something changed 8 days ago? 

> ![2022-02-10_22-33](https://user-images.githubusercontent.com/157609/153509054-6d600b1e-b034-43a8-8365-54afb132ffe3.png)

## Solution

Aside from fixing these tests, cap them?
Seems that when it was working it took ~2minutes, perhaps we should set cap at 15m, 1h,  or something, so these hanging jobs don't  squat workers for 6h each.

**Comment by galargh** [comment]
I manually disabled the tests for now. I'm going to look into it and try to find out what changed.

**Comment by lidel** [comment]
Let's keep this open until @galargh  can switch to upstream action with a fix from https://github.com/coryschwartz/testground-github-action/pull/2:

https://github.com/galargh/go-ipfs/blob/ce25140b69a2d1ae8d3fb6394bf269fd7b274e80/.github/workflows/testground-on-push.yml#L28-L29

**Comment by BigLep** [comment]
@galargh : just checking in to see if we've done the fix so we can resolve this issue.
