### ISSUE TITLE
IPFS_PATH not working with ipfs init on latest from snap

### ISSUE THREAD

**Issue by aronchick** [ipfs/go-ipfs#8752]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

third-party binary

### Version

```Text
0.12
```

### Config

```json
N/a
```

### Description

When I execute the following command, I get a warning saying it’ll overwrite my existing keys. Am I missing something?

‘IPFS_PATH=/tmp/foobaz ipfs init’

I also tried exporting the env variable earlier as well.

**Comment by Jorropo** [comment]
@aronchick snaps run inside isolated dockers and doesn't allows that kind of things to happen (to my knowlege, anyway even if there is an option they are a pain).

If you want to play with ipfs on that kind of level, you should install from:
- [dist.ipfs.io](https://dist.ipfs.io)
- `go install github.com/ipfs/go-ipfs/cmd/ipfs@latest`

**Comment by aronchick** [comment]
Thanks! Will try tomorrow - we should have a detection/warning/remove our (blessed) install from snap

**Comment by aschmahmann** [comment]
https://github.com/ipfs/go-ipfs/issues/8688#issuecomment-1053668859

**Comment by aronchick** [comment]
+1 confirmed. Removing the snap version and installing from dist.ipfs.io solved this. I'll +1 the other bug.

**Comment by guseggert** [comment]
There is also documentation for this in the Snap section of the `go-ipfs` README: https://github.com/ipfs/go-ipfs#snap
