### ISSUE TITLE
Allow / Deny Bitswap replication based on peerID and CID

### ISSUE THREAD

**Issue by laurentsenta** [ipfs/go-ipfs#8763]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Background

Right now, the only way to store personal/private data on the network is to:
- Use a private network (with [swarm keys](https://github.com/Kubuxu/go-ipfs-swarm-key-gen) for example),
- Use semantic security (by encrypting the data).

For some use cases, this is too restrictive:
"I wouldn't store my passwords or my medical records on the IPFS network, even encrypted."

For these use cases, decentralization might still be necessary, but they would require a permissioned approach:
ideally, we'd let a user define who can replicate their data / what can be replicated from their node.

There are a lot of discussions around the question of authorizations (see below), @kylehuntsman and I have been working on the smallest step forward we could find: let a node accept/reject a bitswap request based on peerID and CID.

(one might find a certain resemblance with libp2p's [ConnectionGater](https://pkg.go.dev/github.com/libp2p/go-libp2p-core/connmgr#ConnectionGater).)

### Stories / Plan

1. [ ] As a developer, I can define a filter predicate (policy). This lets me filter requests based on the requester's ID and the content requested.
   - [ ] Add an optional configuration to go-bitswap that lets a user define this peer-block filter,
   - [ ] Add ipfs-related plumbing to pass this configuration down to the bitswap instance.
2. [ ] As a regular user, I can configure a default policy with a few `allow`, `deny` commands, similar to the [IPFS filter](https://github.com/ipfs/go-ipfs/issues/8492) proposed for gateway operators.
   - [ ] TBD

### Current State

- [Bitswap PR](https://github.com/ipfs/go-bitswap/pull/549)
- [IPFS PR](https://github.com/ipfs/go-ipfs/pull/8772)

### Related Issues and discussions

- https://github.com/ipfs/specs/pull/270
- https://github.com/ipfs/go-ipfs/issues/7871
- https://github.com/ipfs/specs/issues/260
- https://github.com/ipfs/roadmap/issues/75
- https://github.com/ipfs/go-bitswap/issues/532
- https://github.com/ipfs/go-ipfs/issues/6842
- https://github.com/ipfs/go-ipfs/issues/8492
- https://github.com/ipfs/go-ipfs/issues/6097
- https://github.com/ipfs/go-ipfs/issues/6565

**Comment by bertrandfalguiere** [comment]
Sounds like the Block-level acces control by peergos : https://peergos.org/posts/bats

**Comment by kylehuntsman** [comment]
@bertrandfalguiere We actually came across that implementation while researching the idea.

We felt Peergos's implementation was great, but was a bit heavy in terms of spec changes. We ended up taking a more general and lightweight approach that we felt could be immediately useful without the burden of reviewing and merging something like a block spec change to the protocol. Not as robust or as specific of a feature set, but it is harmless and could have some great potential to be built on top of.

**Comment by ianopolous** [comment]
To be clear, the extension we've built is more general than this (it allows arbitrary allow functions as described in https://github.com/ipfs/go-ipfs/issues/7871 and you could do the same thing without any bitswap protocol changes. 

This is the allow signature here, though you would remove the string which is the auth token, and likely could remove the block data as well: https://github.com/Peergos/go-bitswap-auth/blob/master/auth/blockstore.go#L42

**Comment by laurentsenta** [comment]
> To be clear, the extension we've built is more general than this (it allows arbitrary allow functions as described in https://github.com/ipfs/go-ipfs/issues/7871 and you could do the same thing without any bitswap protocol changes.

👍 That's the first task in the description: Arbitrary predicate function, no protocol change.
Here is the [go-bitswap](https://github.com/ipfs/go-bitswap/pull/549) PR as a reference; feel free to review!

If you refer to the second story, the goal is to expose the feature to users who won't compile their node. So it is one default implementation on top of step 1.

Remember this is a special case of the general approach (https://github.com/ipfs/specs/issues/260, https://github.com/ipfs/go-ipfs/issues/7871, https://github.com/ipfs/specs/pull/270) on purpose. We're looking for the smallest contribution we could make to move this forward without making specifications & protocol changes. These require more time and more familiarity with the stack.

**Comment by ianopolous** [comment]
I think we're suggesting the same thing. A configurable allow function. I was mainly disputing the "more general" claim.

**Comment by kylehuntsman** [comment]
> This is the allow signature here, though you would remove the string which is the auth token, and likely could remove the block data as well: https://github.com/Peergos/go-bitswap-auth/blob/master/auth/blockstore.go#L42

Oh nice, thanks for pointing that out. I didn't see that previously. I was referencing the idea of the continuous access-control across nodes when I wrote that.

**Comment by BigLep** [comment]
Closing because this functionality now lives in bitswap: https://github.com/ipfs/go-bitswap/pull/549

We don't expose configuration for this in go-ipfs, but one can make their own ipfs distribution if they want.

If anyone wants this in go-ipfs itself, we should talk about plugin support.  That should be a new issue please.
