### ISSUE TITLE
the repo migration error does not say or link to how to resolve it

### ISSUE THREAD

**Issue by autonome** [ipfs/go-ipfs#8779]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

upgraded recently i guess, b/c tried a cli command and got:

> Error: ipfs repo needs migration

this should tell the user what to do next.

**Comment by 2color** [comment]
@autonome What is the right next step when there's a migration error?

**Comment by 2color** [comment]
@autonome 
Is the correct next step when this error is raised to use the [fs-repo-migrations](https://github.com/ipfs/fs-repo-migrations/blob/master/run.md) tool?

Do we typically add links to repos like the that markdown file in errors?
