### ISSUE TITLE
Could not add migration to IPFS: Cannot get migrations from unknown fetcher type

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#8780]
### Version

```Text
0.12.0
```

### Description

```
Could not add migration to IPFS: Cannot get migrations from unknown fetcher type
```

Above  message was reported by Brave and on https://develop.element.io/#/room/#lobby:ipfs.io:

>  ![2022-03-09_20-59](https://user-images.githubusercontent.com/157609/157524323-d4c931df-25b0-4b40-b80a-6c6e082e3bd7.png)

> ![2022-03-09_20-59_1](https://user-images.githubusercontent.com/157609/157524406-3bb951e3-7150-480f-bfc2-8c60d74c8c1a.png)

It does not impact migration itself, but raises a concern that something went wrong.

In this case, downloaded migration is not added to IPFS, so other machines from LAN can't fetch it locally p2p, but need to fetch from swarm/HTTP. Not a hard error, but something we should fix to improve resilience.

Relevant code: 
- https://github.com/ipfs/go-ipfs/blob/v0.12.0/cmd/ipfs/daemon.go#L489-L493
- https://github.com/ipfs/go-ipfs/blob/v0.12.0/cmd/ipfs/add_migrations.go#L24-L60

**Comment by lidel** [comment]
@gammazero any ideas? is this a bug because we do type assertion over pointer [here](https://github.com/ipfs/go-ipfs/blob/v0.12.0/cmd/ipfs/add_migrations.go#L33-L34)?

**Comment by gammazero** [comment]
@lidel I am guessing this happens because `fetcher` [here](https://github.com/ipfs/go-ipfs/blob/v0.12.0/cmd/ipfs/daemon.go#L491) is `nil`, and that `if` above should check that.
