### ISSUE TITLE
Upgrade quic-go to v0.26.0 to support building with Go 1.18

### ISSUE THREAD

**Issue by makeworld-the-better-one** [ipfs/go-ipfs#8819]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

built from source

### Version

I am using IPFS (v0.12.0) as a library, but the problem remains when building the latest commit or release from source.

### Config

Not relevant to the issue.

### Description

When building go-ipfs, I get this error:

```
# github.com/lucas-clemente/quic-go/internal/qtls
../../../../pkg/mod/github.com/lucas-clemente/quic-go@v0.24.0/internal/qtls/go118.go:6:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration
```

This is because I'm building with Go 1.18, and v0.24.0 of quic-go doesn't support Go 1.18. v0.26.0, [released](https://github.com/lucas-clemente/quic-go/releases) yesterday, now supports Go 1.18. It would be great if go-ipfs could upgrade this dependency to support the latest Go version.

I understand quic-go is not a direct dependency of go-ipfs, so feel free to transfer the issue. I just wanted to file it here since my problem is when trying to build go-ipfs.

**Comment by dvergeylen** [comment]
As a temporary workaround, one may want to upgrade the dependency himself:

```bash
go get github.com/lucas-clemente/quic-go@v0.26.0
```

`make build` them compiles as expected.

**Comment by makeworld-the-better-one** [comment]
Thanks for the tip. I was worried about messing things up by doing that upgrade, since the libraries using quic-go weren't written with this latest version in mind. For now I just switched back to Go 1.17.

**Comment by marten-seemann** [comment]
We'll be releasing go-libp2p v0.19.0 very soon (tracking issue: https://github.com/libp2p/go-libp2p/issues/1298), which will include a newer version of quic-go that builds with Go 1.18.

**Comment by RobotSail** [comment]
@marten-seemann Any ETA on when that'll land? 
We're currently setting up a process to have automated IPFS binary builds for COPR so that RHEL users could access updated builds and this is blocking us as well

**Comment by RubenKelevra** [comment]
> We'll be releasing go-libp2p v0.19.0 very soon (tracking issue: [libp2p/go-libp2p#1298](https://github.com/libp2p/go-libp2p/issues/1298)), which will include a newer version of quic-go that builds with Go 1.18.

Would be nice if this could be split off and just this fix could be added as there seems to be no downside to using the newer QUIC version (as explained in a [previous comment](https://github.com/ipfs/go-ipfs/issues/8819#issuecomment-1077564642) by @dvergeylen), or is there?

**Comment by NatoBoram** [comment]
It should work at the moment

```yaml
go-ipfs version: 0.13.0-dev-63b002566
Repo version: 12
System version: amd64/linux
Golang version: go1.18.1
```

**Comment by lidel** [comment]
This is waiting for go-libp2p 0.19 (to include https://github.com/libp2p/go-libp2p-quic-transport/pull/264#pullrequestreview-933431241)

**Comment by dmgk** [comment]
go-libp2p currently is at v0.19.1, can this move ahead please?

**Comment by aschmahmann** [comment]
The version of quic-go is now at 0.27.0 and CI is building with Go 1.18.1.
