### ISSUE TITLE
undefined: blockstore.ErrNotFound

### ISSUE THREAD

**Issue by Jchicode** [ipfs/go-ipfs#8828]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

ipfs-desktop

### Description

github.com/ipfs/go-ipfs@v0.12.1/blocks/blockstoreutil/remove.go:57:51: undefined: blockstore.ErrNotFound

**Comment by Jchicode** [comment]
Version is v0.12.1

**Comment by Jorropo** [comment]
@Jchicode Can you provide reproduction instructions pls ?
Your description + installation method makes no sense, AFAIK IPFS-Desktop download pre built binaries, and doesn't build anything making the error you see impossible with your current description.

Secondly even if it builds it, v0.12.1 builds perfectly fine on my machine:
```bash
~/k/go-ipfs$ git checkout v0.12.1
~/k/go-ipfs$ go build ./cmd/ipfs
```

The error you see is likely related to #7074, I guess you have custom code or you are importing go-ipfs in your project and you missmatched the versions of different modules (you have updated the `blockstore` module but not the `go-ipfs` one, so you are using two incompatible versions).

**Comment by sudeepdino008** [comment]
I faced the exact same issue, but I was trying to use go-ipfs as a library. Raised the issue here - https://github.com/ipfs/go-ipfs/issues/8881

**Comment by Jorropo** [comment]
@sudeepdino008 it could be that we have mixed deps versions between `go-ipfs as a library` (which I want to replace) and go-ipfs.

Can you give me a simple reproduce-able case ? (do I just git clone https://github.com/covalenthq/ipfs-pinner and `go build ./...` ?)

**Comment by sudeepdino008** [comment]
@Jorropo You are right. It was mixed deps version issue. I've closed - https://github.com/ipfs/go-ipfs/issues/8881
I guess basically the latest go-ipfs doesn't have the ErrNotFound fix and therefore would fail? I'd to update to latest master for it to work,

**Comment by Jorropo** [comment]
> basically the latest go-ipfs doesn't have the ErrNotFound fix and therefore would fail?

Yeah it doesn't we removed it in #7074 and replaced it with `github.com/ipfs/go-ipld-format#ErrNotFound`
However `go-ipfs as a library` has it's own `go.mod` file that doesn't get automatically updated so `go-ipfs as a library` still want the old blockstore version..

**Comment by sudeepdino008** [comment]
@Jorropo Thanks.
can you elaborate a bit on "`go-ipfs as a library` has it's own `go.mod`? It's is the same one as that on go-ipfs repo root, right? Or is there a different `go.mod` as well?

**Comment by Jorropo** [comment]
@sudeepdino008 
- `go-ipfs`'s `go.mod` file [go.mod](https://github.com/ipfs/go-ipfs/blob/master/go.mod)
- `go-ipfs as a library`'s `go.mod` file [docs/examples/go-ipfs-as-a-library/go.mod](https://github.com/ipfs/go-ipfs/blob/cde79df1408c3bd518fec1622d97bf4a251af81e/docs/examples/go-ipfs-as-a-library/go.mod)

**Comment by sudeepdino008** [comment]
I see. I wasn't actually using the go.mod in docs/examples (though I did use the sample code from there). Just `go get` wherever needed.

**Comment by Jorropo** [comment]
@sudeepdino008 make sense.
So FYI I've tried it and *it works*.

I'm pretty certain that you just `go get` the latest version of the blockstore which require `go-ipfs@v0.13.0` (not released yet).
Maybe the example should be more clear about how you are expected to deal with package versions (you must go get versions present in the `github.com/ipfs/go-ipfs` `go.mod` of whatever go-ipfs version you are using).

**Comment by Jchicode** [comment]
> @Jchicode Can you provide reproduction instructions pls ? Your description + installation method makes no sense, AFAIK IPFS-Desktop download pre built binaries, and doesn't build anything making the error you see impossible with your current description.
> 
> Secondly even if it builds it, v0.12.1 builds perfectly fine on my machine:
> 
> ```shell
> ~/k/go-ipfs$ git checkout v0.12.1
> ~/k/go-ipfs$ go build ./cmd/ipfs
> ```
> 
> The error you see is likely related to #7074, I guess you have custom code or you are importing go-ipfs in your project and you missmatched the versions of different modules (you have updated the `blockstore` module but not the `go-ipfs` one, so you are using two incompatible versions).

Sorry, I just saw it.
Yes, I quoted the new version of ```blockstore```, I changed its version to v1.1.2.
