### ISSUE TITLE
Tests sometimes are timing out when testing `go-ipfs-as-a-library`

### ISSUE THREAD

**Issue by ajnavarro** [ipfs/go-ipfs#8956]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

built from source

### Version

```Text
master branch
```

### Description

Tests are timing out because `Republisher` never closes, it is always waiting for the current value to be published on `Republisher.WaitPub`

**Comment by ajnavarro** [comment]
It took me some time to understand all the Makefiles and figure out that FUSE tests are not running on CI. The real problem is a flaky test executing `go-ipfs-as-a-library`, sometimes it just stops writing text to the terminal, and after 10 minutes, CircleCI stops it.

**Comment by lidel** [comment]
More details:
```
cd docs/examples/go-ipfs-as-a-library
go run main.go
```

As discussed during stewards colo, we need to 
- refactor `go-ipfs/docs/examples/go-ipfs-as-a-library/main_test.go` so it does not fetch  data from public swarm
  - need to spawn a local (additional) IPFS node instead,  that provides data.  that wayt test works in 'offline" mode (that way CI won't break the test if they throttle WAN data transfers).
