### ISSUE TITLE
Weird API endpoint design.  All POST vs GET

### ISSUE THREAD

**Issue by kallisti5** [ipfs/go-ipfs#9036]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.io

### Version

```Text
0.13.0, though it started around 0.9.0?
```

### Description

I'm working through fixing 3rd party api libraries, and noticed several odd API design issues.

* /api/v0/version  POST  - No "change", just asking version
* /api/v0/pin/ls POST - No "change", just a query?
* /api/v0/log/tail POST - No "change", just getting logs?
* /api/v0/name/resolve POST - No "change", just a query?
* /api/v0/object/stat POST - No "change", just a query?
* /api/v0/name/pubsub/state POST - No "change", just a query?
* etc.

There are others.. just some weird non-RESTful choices I saw trying to fix 3rd party API libraries.

**Comment by kallisti5** [comment]
This all raises questions on why such a substantial API change didn't spawn a /v1 API endpoint. That's kinda the point of it :-)

**Comment by Jorropo** [comment]
See https://github.com/ipfs/go-ipfs/pull/7097/commits/1b490476e5517931b8d31a6636e7008771db201d
> By limiting the request types we address the possibility that a website
accessed by a browser abuses the IPFS API by issuing GET requests to it which
have no Origin or Referrer set, and are thus bypass CORS and CSRF protections.

---

> This all raises questions on why such a substantial API change didn't spawn a /v1 API endpoint. That's kinda the point of it :-)

There is no (limited) stability promises for `v < 1`.

This change sounds simple trivial fix in your code. Ok it's more work and something that broke at one point, but the costs of having a stable API at that stage sounds not worth it.

I'll raise this at the next maintainer call but I don't think anything special is gonna happen.

/cc @lidel
