### ISSUE TITLE
RestartIPfs

### ISSUE THREAD

**Issue by Mikec90** [ipfs/go-ipfs#9076]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

third-party binary

### Version

```Text
Version v0.13.0 for macOS 64bit
```

### Config
`json
mikec90:patch-1/Closed/
closed repo
Updated version
```


### Description

mikec90:patch-1

**Comment by aschmahmann** [comment]
There is no actionable information in this issue. If something comes up feel free to file another, or of you need general support going to the forums linked above
