### ISSUE TITLE
forcing sort on mdag links affects data chunking

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#915]
forcing sort on mdag links affects data chunking, particularly if names are added to sub-blocks.

**Comment by wking** [comment]
On Tue, Mar 10, 2015 at 03:19:42PM -0700, Juan Batiz-Benet wrote:
> forcing sort on mdag links affects data chunking, particularly if
> names are added to sub-blocks.

This came up on IRC yesterday [1], with @jbenet saying [2]:

> It would be nice to be able to access objects like <path>/2 For the
> third link under <path>, but this conflicts with naming.

I'm not sure how tunable we need the sharding to be, but one approach
would be to use constant-digit-count base-58.  The BTCAlphabet used in
go-base58 [3] will byte-sort in UTF-8 in the same order as the numeric
sort.  With two digits you get 3364 entries, which seems like
reasonable fanout, and you can address your chunks from <path>/11 to
<path>/ZZ and get deeper levels like <path>/11/11, ….  Base-58 isn't
super-intuitive (quick, what's 1234 in Base-58? NH?), but I think
addressing specific chunks by hand is going to be rare enough that
that's not a big deal.  Obviously, individual chunking algorithms can
adjust the number of digits if they feel drawn to deeper or wider
fanout.  With this approach we can byte-sort both numbered links and
UTF-8-named links using the same logic without getting into trouble.

[1]: https://botbot.me/freenode/ipfs/2015-04-29/?msg=37928853&page=10
[2]: https://botbot.me/freenode/ipfs/2015-04-29/?msg=37929383&page=10
[3]: https://github.com/jbenet/go-base58/blob/6237cf65f3a6f7111cd8a42be3590df99a66bc7d/base58.go#L14

**Comment by jbenet** [comment]
it is possible that we could reserve some modifier prefix on the linkname-- e.g. suppose we reserved prefix  `@` (bad example), and could thus do `@link_1` or something. (this is a terrible example, but illustrates the type of thing i mean). 

i suspect both that:
- if we find a good way for this to work, it will be a really powerful notation
- if it is not very cleanly separated, it will clash with some important thing and people will hate it.

**Comment by whyrusleeping** [comment]
This isnt currently an issue, and will be different with ipld, closing.
