### ISSUE TITLE
Things stored in the DHT need to be periodically rebroadcasted

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#919]
Now that we are getting ipns up and more useable, and nodes are starting to be online for longer periods of time, we need to start rebroadcasting values that we store directly in the DHT. Provider entries are already 'reprovided', a similar mechanism is needed for immediate values

**Comment by jbenet** [comment]
:+1:

**Comment by whyrusleeping** [comment]
The only other values stored in the dht are ipns entries and public keys, both are rebroadcast periodically now
