### ISSUE TITLE
tests (all) OOM on mars.

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#928]
I think our tests need to be capable of running on a Raspberry PI. They shouldn't be OOMing on mars.

**Comment by whyrusleeping** [comment]
Well, we have to pick. Do we want our tests to be thorough and catch everything? If so, we need stress tests, stress tests dont really run on low performant machines. Go's own tests dont run well on a pi (they always OOM when im setting Go up).

**Comment by diasdavid** [comment]
Tests are passing locally and on CI machines, @whyrusleeping has extra tests (for really large files) available on his machine
