### ISSUE TITLE
Gateway should allow CORS

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/go-ipfs#934]
Denying cross origin resource sharing (CORS) over IPFS doesn't make much sense. All requests should be allowed. 
Adding "Access-Control-Allow-Origin: *" to the HTTP headers will enable that.  

Use cases:
* I have an app that has a script that wants to access something over IPFS. The script however isn't served over IPFS. 
* I'm using a fancy chrome extension, and my gateway went down in the middle of requests. It fell back to gateway.ipfs.io but the rest of the requests are now failing because of CORS.

**Comment by jbenet** [comment]
Yeah. 

We'll eventually need to use suborigins: www.chromium.org/developers/design-documents/per-page-suborigins

**Comment by whyrusleeping** [comment]
@dylanPowers try out https://github.com/jbenet/go-ipfs/tree/fix/gateway-cors

let me know if that solves the issue for you

**Comment by jbenet** [comment]
mmm not sure what security implications are at play here. 

@mappum your perspective?

**Comment by lidel** [comment]
My 3 cents: HTTP Gateway (8080 by default) is supposed to be read-only, it would not hurt to limit allowed HTTP methods via `Access-Control-Allow-Methods` header:

    Access-Control-Allow-Origin: *
    Access-Control-Allow-Methods: GET, HEAD, OPTIONS

(`OPTIONS` is used in [Preflight request](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing#Preflight_example))

This would enable JavaScript from other domains to access immutable (`/ipfs/`) resources and keep us safe in case at some point  gateway provides mutable ones (`/ipns/` or some control interface) via `PUT`, `POST`, `PATCH` or `DELETE`.  

Good thing is that WebUI runs on a separate port (5001 by default),
so we don't need to worry about it. :+1:

**Comment by whyrusleeping** [comment]
@lidel that makes good sense. 
I think this issue should probably get a slight priority bump.

**Comment by jbenet** [comment]
Agreed. @lidel do you know Go? (Need some help with gateway things)



—

**Comment by lidel** [comment]
Sadly no, I have not touched Go before.  This is a good motivation to learn, but I'd have to do some serious reading before I feel comfortable making any contribution to go-ipfs.

**Comment by jbenet** [comment]
it's a great language! https://tour.golang.org

**Comment by d11e9** [comment]
:+1:

**Comment by jbenet** [comment]
#1529

**Comment by diasdavid** [comment]
We have CORS working now :) Let me us know if you encounter any remaining issues

**Comment by lidel** [comment]
In certain situations browsers execute `OPTIONS` request to read CORS headers 
(Example and more details  in https://github.com/lidel/ipfs-firefox-addon/issues/45#issuecomment-172054478)

HTTP `OPTIONS` method does not seem to be supported even when explicitly enabled:

    ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST", "OPTIONS"]'
    ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
    ipfs config --json Gateway.Writable true

Produces:

    > curl -X OPTIONS http://127.0.0.1:8080/ipfs/QmRqoVq1G9pL7hyLB2EGi5mndRTQv7tKfFXPRUsSbpHqfK
    Method OPTIONS not allowed: bad request for /ipfs/QmRqoVq1G9pL7hyLB2EGi5mndRTQv7tKfFXPRUsSbpHqfK

Am I missing some configuration or do we need to reopen this ticket?

**Comment by Kubuxu** [comment]
More precisely, in certain situation browser __does not__ execute `OPTIONS`. See [simple](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests) vs [preflighted](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests) requests.

**Comment by Kubuxu** [comment]
Also read-only API is missing CORS, it makes impossible to use read only API from browser/XHR.

Is there reason why they are filtered out from __read-only__ API?

https://github.com/ipfs/go-ipfs/blob/5d9ee59908099df3f7e85679f7384c98d4ac8111/commands/http/handler.go#L71-L82

**Comment by jbenet** [comment]
@Kubuxu i do not recall. this may be an error now, as other parts have shifted. what would be nice is a short doc describing _how_ we should handle all the CORS things, and then make sure the implementation does that.

**Comment by jbenet** [comment]
@Kubuxu all this will get smaller once the gateway is split out into its own repo.
