### ISSUE TITLE
release changelogs

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#949]
would be nice to include a changelog

maybe with https://github.com/skywinder/github-changelog-generator

**Comment by diasdavid** [comment]
@whyrusleeping where can I find the release checklist? I want to add an item for myself for:

`- [ ] update the npm-go-ipfs module to install the new go-ipfs release`

**Comment by lgierth** [comment]
Closing this since we've had CHANGELOG.md for a while :)

@diasdavid the release checklist is in docs/releases.md
