### ISSUE TITLE
Some Git like commands

### ISSUE THREAD

**Issue by chriscool** [ipfs/go-ipfs#960]
As discussed with @hosh and @jbenet maybe ipfs could have some Git like commands, like the following:
- `ipfs mv`
  It could do what `mv` does and then `ipfs add -r` on the root directory of the last argument.
  For example `ipfs mv A B/C/D` would do `mv A B/C/D` and then `ipfs add -r B`.
- `ipfs rm`
  It could do what `rm` does and then `ipfs add -r` on the root directory of the last argument.
  For example `ipfs rm B/C/D` would do `rm B/C/D` and then `ipfs add -r B`.

**Comment by jbenet** [comment]
maybe we could specify the command interfaces + semantics like the listings in https://github.com/ipfs/specs/tree/master/keystore

**Comment by hosh** [comment]
`ipfs files mv`
`ipfs files cp`
`ipfs files rm`
`ipfs files ln`

That looks a lot more explicit.

**Comment by chriscool** [comment]
@hosh yeah I agree.

@jbenet ok I will have a look at contributing to https://github.com/ipfs/specs

**Comment by kevina** [comment]
This functionality is now provided via the `ipfs files` API.  Please reopen if I am missing something.
