### ISSUE TITLE
Root has ownership of ipfs mount directories

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/go-ipfs#967]
Run ls on /ipns for instance and you'll find the owner is root. I would expect the owner to match the user of the running ipfs daemon

**Comment by jbenet** [comment]
you should be able to change this. i usually mkdir them myself and chgrp/chown them to the right users.

**Comment by whyrusleeping** [comment]
should be an easy fix, just need to change the Attr function

**Comment by whyrusleeping** [comment]
fixed as of #988
