### ISSUE TITLE
ipfs mount access limited to single user

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/go-ipfs#968]
Situation:
I have my linux service daemon for ipfs (https://github.com/dylanPowers/ipfs-linux-service) that runs under the user 'ipfs-daemon'. I have the ipfs daemon configured to mount at /ipfs and /ipns. Running `ipfs mount` works fine except for the fact that /ipfs and /ipns can only be accessed from the user 'ipfs-daemon'. This is even though I have user_allow_other set in /etc/fuse.conf

For those of us living on the edge with "user_allow_other" enabled, it would be nice if ipfs mount followed suit and passed along the allow_other flag to fuse.

**Comment by jbenet** [comment]
Good find. any thoughts on how this would be achieved?

I _think_ in OSX i get this for free by `chown-ing` /ipfs and /ipns to be readable + executable by everyone, but not sure

**Comment by dylanPowers** [comment]
I think it can be achieved by modifying https://github.com/ipfs/go-ipfs/blob/b6c0ade2769f504e786db65b47135244c0759403/fuse/mount/fuse.go#L27 to be 
```go
conn, err := fuse.Mount(mountpoint, fuse.AllowOther())
```

However I wasn't able to get it to work on Linux in my own testing

**Comment by hosh** [comment]
:+1: Plan with #991 is to also have config options for `allow_other` as well as `allow_root`. 

I don't have much experience with fuse. Why is there an `/etc/fuse.conf` and a separate library api to call FUSE for mounting? Is the user app supposed to look into `/etc/fuse.conf` for instructions on whether `allow_root` or `allow_other` to be enabled?

**Comment by dylanPowers** [comment]
As I understand it, the FUSE library looks at /etc/fuse.conf for globally available configuration options. The user app doesn't need to do anything. Some options like allow_other can create security vulnerabilities so it's disabled in fuse.conf by default for users other than root.

**Comment by dylanPowers** [comment]
Haha, I figured out why I originally couldn't get it to work. I wasn't building correctly/being a golang newb. Now I got it to work.
