### ISSUE TITLE
all commands send a multipart form over, even if no files are specified

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#983]
This comes down to `req.Files()` in `commands/http/client.go:72` never returning `nil`.

**Comment by cryptix** [comment]
Might this be related to the weird ` < /dev/null` and ` | tee` tricks one has to do in scripts?

**Comment by whyrusleeping** [comment]
I honestly am not sure. I just noticed that every single request sends a multipart file regardless of whether or not a file is actually involved.

**Comment by jbenet** [comment]
@mappum is there a reason for this?

**Comment by mappum** [comment]
I just chose to do that for lower code complexity: it was just simpler to send an empty form than to sometimes not send any body.

**Comment by mappum** [comment]
I just chose to do that for lower code complexity: it was just simpler to send an empty form than to sometimes not send any body.

**Comment by whyrusleeping** [comment]
i fixed this, it was actually the source of a bug causing our closeNotify code to not work, took an obnoxiously long time for me to realize what was going on
