### ISSUE TITLE
Reorg jbenet to ipfs

### ISSUE THREAD

**Issue by hosh** [ipfs/go-ipfs#990]
We recently changed from github.com/jbenet/go-ipfs to github.com/ipfs/go-ipfs. This work is intended to change those references to the latter.

**Comment by jbenet** [comment]
yeah! among other things, we need to:

- [ ] change links wherever they appear (docs + code. suggest grepping)
- [ ] re-vendor everything (**sigh** go pkg managament)

**Comment by hosh** [comment]
Yep, I'm changing docks and the deps in the first pass. @jbenet there is also the Travis link. I've changed it, but probably want to create the ipfs account too

**Comment by jbenet** [comment]
- [x] travis should be all set now. https://travis-ci.org/ipfs/go-ipfs (lmk if not)

**Comment by hosh** [comment]
Looks like travis is working
