### ISSUE TITLE
Add mount options allow_root and allow_other

### ISSUE THREAD

**Issue by hosh** [ipfs/go-ipfs#991]

**Comment by hosh** [comment]
<•whyrusleeping> dPow actually has code for it written...
18:31:46 <•whyrusleeping> hosh: the easy way is to look where we call fuse.Mount, and add fuse.AllowRoot() to the function call
18:31:57 <•whyrusleeping> so 'fuse.Mount(ipfsthing, fuse.AllowRoot())'

**Comment by hosh** [comment]
Vague idea in my head: drop those options into the config system. Add those options when actually doing the mount.

**Comment by jbenet** [comment]
+1 for config. once we allow overriding config in commands should work per-command too.

**Comment by dylanPowers** [comment]
Relevant issue on doing the mounting: https://github.com/ipfs/go-ipfs/issues/968
